"""Derive SkyyArmory/build_skyyarmory_0.1.11.py (+ its harness SkyyArmory/test_skyyarmory_0.1.11.py) from the GENERATED 0.1.10
(SkyyArmory/build_skyyarmory_0.1.10.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_10_patch.py; test_skyyarmory_0.1.10.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_11_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.11.py   then
      python SkyyArmory/test_skyyarmory_0.1.11.py --dir tools/dev/scratch/<task>/harness      (never --deploy)

0.1.11 = NO MAGIC SHOT ON THE BO STAFFS (Skyy LOCKED 2026-10-08, playing the Monk: "bow staff shoots magic balls on charge attack" ->
"1, remove the magic shot"; docs/answered/gear.md). All 9 Bo staffs - our 7 Weapon_Bo_<Copper..Onyxium> and the vanilla
Weapon_Staff_Bo_Wood / _Bamboo (the Monk kit) - stop running the vanilla Staff_Primary root (Charging: tap = the Spear swing chain, hold =
Staff_Cast_Summon_Charged = the 50-Mana magic orb). They run ONE new root SkyyArmory_Bo_Primary -> SkyyArmory_Bo_Swings = the vanilla
Staff_Primary key "0" body copied from Assets.zip at build time (Chaining 1.25: Spear_Swing_Left / Spear_Swing_Right, the item vars keep
their damages) with no Charging step: holding the button casts nothing and costs no Mana. The 5 Staff_Cast_Summon_* item vars (the cast and
its Mana cost) leave the 9 items; everything else (swing damages, guard on ours, stats, recipes, looks, animation sets) stays.
POLE-VAULT HOOK: the root is the single place the charged move plugs in later (root -> a Charging step: "0" = SkyyArmory_Bo_Swings, the hold
key = the vault), no item changes needed.
The 2 vanilla Bo items are overrides of the VANILLA ids (copied from Assets.zip at build time, only Interactions + the 5 cast vars changed;
+ the animation set: right click = BLOCK like our 7 (gear.md RIGHT-CLICK BLOCK lock names bo staffs) = GUARD_ROOT + SkyyArmory_Staff, the
staff set with a Guard pose). SkyySkills 0.4.21 ALSO ships both ids (its Mana / 5 spell overrides) and its pack name sorts after
ours ("Skyy:0.4.21 SkyySkills" > "Skyy:0.1.11 SkyyArmory"), so ITS copies win until SkyySkills hands the 2 ids over (like the 8 ladder
staffs in SkyySkills 0.4.15); the build + harness say so (NOTE), they never fail on it.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.10.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.11.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.10.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.11.py")

CR, LF = chr(13), chr(10)
raw = open(SRC, encoding="utf8", newline="").read()
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.10"\nMOD = "SkyyArmory"' in s and "0.1.10 = HOTFIX" in s, "build_skyyarmory_0.1.10.py is not the 0.1.10 pin"


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# ---------------------------------------------------------------------------------------------------------------- header + version
rep('''"""SkyyArmory 0.1.10 - build script (javassist via jpype). GENERATED by tools/armory_0_1_10_patch.py from the GENERATED 0.1.9 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.10.py -> SkyyArmory/SkyyArmory-0.1.10.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.10.py (scratch tools/dev/scratch/armory0110/).''',
    '''"""SkyyArmory 0.1.11 - build script (javassist via jpype). GENERATED by tools/armory_0_1_11_patch.py from the GENERATED 0.1.10 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.11.py -> SkyyArmory/SkyyArmory-0.1.11.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.11.py --dir tools/dev/scratch/<task>/harness.

0.1.11 = NO MAGIC SHOT ON THE BO STAFFS (Skyy LOCKED 2026-10-08 "1, remove the magic shot"): the 7 Weapon_Bo_<metal> and the vanilla
Weapon_Staff_Bo_Wood / _Bamboo run SkyyArmory_Bo_Primary -> SkyyArmory_Bo_Swings (the vanilla Staff_Primary tap chain, copied at build
time; no Charging step) instead of Staff_Primary, and lose the 5 Staff_Cast_Summon_* vars: holding attack casts nothing, costs no Mana.
Swing damages, the guard on ours, stats, recipes, looks unchanged. The 2 vanilla items are overrides of the vanilla ids (Assets.zip copy,
only Interactions + vars changed); SkyySkills 0.4.21 also ships them and loads after us (pack name order), so its copies stay live
until SkyySkills hands the 2 ids over (NOTE, never a failure). Pole-Vault later = the root's charged key; no item change needed.

0.1.10 (the base, everything below is still true):''')
rep('VERSION = "0.1.10"\nMOD = "SkyyArmory"', 'VERSION = "0.1.11"\nMOD = "SkyyArmory"')

# ---------------------------------------------------------------------------------------------------------------- the swing root
rep('''assert az_get("item", "Weapon_Staff_Bo_Bamboo")["Interactions"] == VBO["Interactions"]
''', '''assert az_get("item", "Weapon_Staff_Bo_Bamboo")["Interactions"] == VBO["Interactions"]
# ---- 0.1.11 (Skyy LOCKED 2026-10-08 "1, remove the magic shot"): ONE root for all 9 Bo staffs = the vanilla Staff_Primary tap body (its key
# "0", read above and asserted unchanged) without the Charging step around it: a click swings (Spear_Swing_Left / _Right, the item vars set
# the damages), holding casts nothing. The vanilla root shape (Staff_Primary / Club_Attack: {"Interactions": [id]}). POLE-VAULT HOOK: the
# charged move later turns this root's interaction into a Charging step ("0" = ID_BOSWING, the hold key = the vault) - no item changes.
P_BOINT = "Server/Item/Interactions/Weapons/Bo/SkyyArmory/%s.json"
P_BOROOT = "Server/Item/RootInteractions/Weapons/Bo/SkyyArmory/%s.json"
ID_BOROOT, ID_BOSWING = "SkyyArmory_Bo_Primary", "SkyyArmory_Bo_Swings"
VBO_IDS = ["Weapon_Staff_Bo_Wood", "Weapon_Staff_Bo_Bamboo"]          # the vanilla Bo staffs (the Monk kit gives the Wood one)
BO_CAST_VARS = sorted(k for k in STAFF_VARS if k.startswith("Staff_Cast_Summon_"))
assert BO_CAST_VARS == sorted(["Staff_Cast_Summon_Charged", "Staff_Cast_Summon_Cost", "Staff_Cast_Summon_Launch", "Staff_Cast_Summon_Effect",
                               "Staff_Cast_Summon_Fail"]), BO_CAST_VARS
_bsw = json.loads(json.dumps(VSP["Next"]["0"]))
assert _bsw == {"Type": "Chaining", "ChainingAllowance": 1.25, "Next": ["Spear_Swing_Left", "Spear_Swing_Right"]}, _bsw
assert all(az_has("int", x) or az_has("root", x) for x in _bsw["Next"]), _bsw
add_int(P_BOINT, ID_BOSWING, _bsw)
add_root(P_BOROOT, ID_BOROOT, [ID_BOSWING])
BO_FILES = [P_BOINT % ID_BOSWING, P_BOROOT % ID_BOROOT]
''')

# ---------------------------------------------------------------------------------------------------------------- our 7 Bo items
rep('''    _iv = json.loads(json.dumps(VBO["InteractionVars"]))
''', '''    _iv = json.loads(json.dumps(VBO["InteractionVars"]))
    for _k in BO_CAST_VARS:          # 0.1.11: no cast on a Bo staff - the cast + its Mana cost vars go
        del _iv[_k]
''')
rep('''"Interactions": {"Primary": "Staff_Primary", "Secondary": GUARD_ROOT}''',
    '''"Interactions": {"Primary": ID_BOROOT, "Secondary": GUARD_ROOT}''')
rep('''assert MK_ITEMS == MONK_IDS and len(MK_ITEMS) == 19
''', '''assert MK_ITEMS == MONK_IDS and len(MK_ITEMS) == 19
for _i in BO_IDS:          # 0.1.11: nothing on our Bo staffs casts or spends Mana any more
    _t = json.dumps(ITEMS[_i])
    assert ITEMS[_i]["Interactions"] == {"Primary": ID_BOROOT, "Secondary": GUARD_ROOT} and "Mana" not in _t and "Staff_Cast" not in _t, _i
# ---- 0.1.11: the 2 vanilla Bo staffs = the CURRENT vanilla file (Assets.zip, read at every build, never committed) with only the root, the
# 5 cast vars and the animation set changed. RIGHT CLICK = BLOCK like our 7 (gear.md LOCKED 2026-10-07 RIGHT-CLICK BLOCK: every SkyyArmory
# weapon incl. "bo staffs"; we ship these 2 now): Secondary = GUARD_ROOT and PlayerAnimationsId = SkyyArmory_Staff (the vanilla Staff set +
# Sword's Guard / GuardBash - the set our 7 metal Bo use; the vanilla Staff set has no Guard pose). Same path as vanilla. Not in ITEMS (no
# packCheck line: SkyySkills ships the same 2 ids).
VBO_OVR = {}
for _vid in VBO_IDS:
    _vp = az_path("item", _vid)
    _vd = az_get("item", _vid)
    assert "Parent" not in _vd and _vd["Interactions"] == {"Primary": "Staff_Primary", "Secondary": "Staff_Primary"} \\
        and sorted(_vd["InteractionVars"]) == sorted(STAFF_VARS), "the vanilla %s changed - look before overriding it" % _vid
    _o = json.loads(json.dumps(_vd))
    assert _vd["PlayerAnimationsId"] == "Staff" and "Guard" in ANIMS[ANIM_STAFF]["Animations"] and _vd["Weapon"] == ITEMS[BO_IDS[0]]["Weapon"], _vid
    _o["Interactions"] = {"Primary": ID_BOROOT, "Secondary": GUARD_ROOT}
    _o["PlayerAnimationsId"] = ANIM_STAFF
    for _k in BO_CAST_VARS:
        del _o["InteractionVars"][_k]
    assert sorted(k for k in set(_o) | set(_vd) if _o.get(k) != _vd.get(k)) == ["InteractionVars", "Interactions", "PlayerAnimationsId"], _vid
    assert "Mana" not in json.dumps(_o) and "Staff_Cast" not in json.dumps(_o) and list(_o) == list(_vd), _vid
    assert _vid not in ITEMS and _vp.startswith("Server/Item/Items/"), _vid
    VBO_OVR[_vid] = (_vp, _o)
    put(_vp, _o)
BO_FILES += [VBO_OVR[_i][0] for _i in VBO_IDS]
assert sorted(BO_FILES) == sorted(set(BO_FILES)) and len(BO_FILES) == 4
''')

# ---------------------------------------------------------------------------------------------------------------- texts
rep('''damage each. Hold: the staff cast. Right click: block."''', '''damage each. Right click: block."''')
rep('''- hold = the vanilla staff cast - Lv %d-%d''', '''- no charged attack (0.1.11: the magic shot is gone; Pole-Vault comes later) - Lv %d-%d''')

# ---------------------------------------------------------------------------------------------------------------- clash scan
rep('''OUR_EXCL = OUR_KEYS - STAFF_KEYS
''', '''BOV_KEYS = set(("item", i) for i in VBO_IDS)          # 0.1.11: the 2 vanilla Bo overrides (SkyySkills 0.4.21 ships them too)
OUR_EXCL = OUR_KEYS - STAFF_KEYS - BOV_KEYS
''')
rep('''return sorted(OUR_EXCL & keys), sorted(STAFF_KEYS & keys)''', '''return sorted(OUR_EXCL & keys), sorted(STAFF_KEYS & keys), sorted(BOV_KEYS & keys)''')
rep('''_ex, _st = clash(''', '''_ex, _st, _bv = clash(''', count=2)
rep('''    assert not _st or _mod == "SkyySkills", "%s %s ships the ladder staff items %s - only SkyySkills may (the handover)" % (_mod, _ver, _st)
''', '''    assert not _st or _mod == "SkyySkills", "%s %s ships the ladder staff items %s - only SkyySkills may (the handover)" % (_mod, _ver, _st)
    assert not _bv or _mod == "SkyySkills", "%s %s ships the vanilla Bo staff items %s - only SkyySkills may (until it hands them over)" % (_mod, _ver, _bv)
    if _bv:
        # the engine loads packs without a dependency in text order of "Group:Name" - the LAST one wins a shared id (research/Accessory-Table-Spec 3.1)
        _bvw = max("Skyy:%s SkyyArmory" % VERSION, "Skyy:%s %s" % (_ver, _mod))
        HANDOVER.append("NOTE %s %s also ships the vanilla Bo staffs %s; live copy = %s%s" % (
            _mod, _ver, [k[1] for k in _bv], _bvw, " (its Bo staffs still cast the orb until it hands the 2 ids over to SkyyArmory)"
            if not _bvw.endswith(" SkyyArmory") else " (ours: no magic shot)"))
''')
rep('''assert not _ex and not _st and not _wp''', '''assert not _ex and not _st and not _bv and not _wp''')
rep('''elif _ex or _st or _wp:''', '''elif _ex or _st or _bv or _wp:''')

# ---------------------------------------------------------------------------------------------------------------- jar checks
rep('''"Weapon_Staff_Bo_Wood", "Weapon_Staff_Bo_Bamboo", GUARD_ROOT''', '''GUARD_ROOT''')
rep('''    assert _sitems == sorted(P_SITEM % m for m in METALS), "SkyyArmory must ship all 8 ladder staff files (the handover): %s" % _sitems
''', '''    assert _sitems == sorted([P_SITEM % m for m in METALS] + [VBO_OVR[i][0] for i in VBO_IDS if VBO_OVR[i][0].startswith("Server/Item/Items/Weapon/Staff/")]), \\
        "SkyyArmory must ship all 8 ladder staff files (the handover) + 0.1.11's 2 vanilla Bo overrides: %s" % _sitems
    assert sorted(n for n in _names if n in set(BO_FILES)) == sorted(BO_FILES), "0.1.11: the 4 Bo files"
    assert sorted(n for n in _names if os.path.basename(n)[:-5] in VBO_IDS) == sorted(VBO_OVR[i][0] for i in VBO_IDS), "0.1.11: exactly 2 vanilla Bo files"
    assert not [n for n in _names if n.startswith("Server/") and n.endswith(".json") and "Staff_Primary" in os.path.basename(n)[:-5]
                and "SkyyArmory_Staff_Primary_" not in n], "0.1.11 overrides no Staff_Primary file"
''')
rep('''AZ.close()''', '''print("0.1.11 bo staffs: no magic shot - %d Bo items (%s + the vanilla %s) run %s -> %s (tap chain %s, no Charging); the 5 cast vars "
      "removed; %d files" % (len(BO_IDS) + len(VBO_IDS), ", ".join(m for m in BO_METALS), " / ".join(VBO_IDS), ID_BOROOT, ID_BOSWING,
                             " / ".join(_bsw["Next"]), len(BO_FILES)))
AZ.close()''')

with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(s.replace(LF, NL))
print("wrote %s" % os.path.relpath(DST, ROOT))

# ================================================================================================ harness
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.10 - test harness. GENERATED by tools/armory_0_1_10_patch.py from test_skyyarmory_0.1.9.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.11 - test harness. GENERATED by tools/armory_0_1_11_patch.py from test_skyyarmory_0.1.10.py - edit the patch, never this file.
Run: python SkyyArmory/test_skyyarmory_0.1.11.py --dir tools/dev/scratch/<task>/harness   (--no-set skips the one-JVM SET run, --keep keeps it)
Every 0.1.10 check still runs on the 0.1.10 shape: the 4 new Bo files (the swing root + chain, the 2 vanilla Bo overrides) are popped and
the 7 Weapon_Bo_ items are put back to Staff_Primary + the 5 cast vars for the older checks (P13 / R14 check the real files); R12f / R13f
(0.1.7 / 0.1.8 -> new compares) are history - R14e compares 0.1.10 -> 0.1.11.
NEW P13 (Python) + R14 (JVM, after R13) EXECUTE every 0.1.11 path:
  P13  every Parallel in the WHOLE jar has 2+ entries (the 0.1.10 P0 walked the older set only); the chain = the vanilla Staff_Primary key
       "0" (Assets.zip at test time), the root = the vanilla root shape; the 7 items = their 0.1.10 file with only Primary + the 5 cast vars
       changed; the 2 vanilla overrides = Assets.zip with only Interactions + the 5 cast vars changed, at the vanilla path; a reachability
       walk (item vars applied, our files + Assets.zip) from both buttons of all 9: no Charging, no StatsCondition, no projectile launch, no
       Mana (NEGATIVE CONTROL: the same walk on the 0.1.10 shape finds the Charging + the Mana cast); lang; who wins the 2 vanilla ids.
  R14a THE ENGINE ASSET VALIDATORS on every changed / new asset (decode + the codec's full validate pass + the store's
       logOrThrowValidatorExceptions + the contained assets) - NEGATIVE CONTROL: 0.1.9's one-entry Parallel fails the same function;
  R14b RootInteraction.build() of the new root (Chaining -> the 2 Spear swings, 0 missing, no Charging) + the loaded items name it;
  R14c the pack order: SkyySkills' copies loaded after ours win the 2 vanilla ids (the documented handover), ours back again;
  R14e vs the 0.1.10 jar: the new files = exactly the 4, none gone, the changed non-class files = the 7 Bo items + lang (7 lines).

0.1.10 harness: SkyyArmory 0.1.10 - test harness. GENERATED by tools/armory_0_1_10_patch.py from test_skyyarmory_0.1.9.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.10"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.10 SkyyArmory"',
     'VERSION = "0.1.11"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.11 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory0110", "harness")', 'os.path.join(SCRATCH_ROOT, "armory0111", "harness")')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.10.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.11.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.10"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.11"))')
hrep('"[SkyyArmory] 0.1.10 ready" in m_', '"[SkyyArmory] 0.1.11 ready" in m_')
hrep('"0.1.10 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_', '"0.1.11 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_')
hrep('"0.1.10 crossbow grapple: grapple on" in m_', '"0.1.11 crossbow grapple: grapple on" in m_')
hrep('come from Skyy:0.1.10 SkyyArmory" in str(r[1])', 'come from Skyy:0.1.11 SkyyArmory" in str(r[1])')
# the pack check counts our interactions: + SkyyArmory_Bo_Swings (the root is not in ROOT_CHECK; the vanilla Bo items are not in ITEM_CHECK)
hrep('"51 of 51 items, 340 of 340 interactions, 63 of 63 projectiles, 1 of 1 roots', '"51 of 51 items, 341 of 341 interactions, 63 of 63 projectiles, 1 of 1 roots')

# ---- pop the 0.1.11 files; the older checks see the 0.1.10 shape of the 7 Bo items
hrep('''GUARD17 = "Root_Common_Guard_Entry_StaminaCondition"
''', '''GUARD17 = "Root_Common_Guard_Entry_StaminaCondition"
# 0.1.11: the Bo swing root + chain and the 2 vanilla Bo overrides are checked in P13 / R14; the older checks below see the 0.1.10 set
BO111_ROOT, BO111_SWING = "SkyyArmory_Bo_Primary", "SkyyArmory_Bo_Swings"
VBO111 = ["Weapon_Staff_Bo_Wood", "Weapon_Staff_Bo_Bamboo"]
BO111_CAST = ["Staff_Cast_Summon_Charged", "Staff_Cast_Summon_Cost", "Staff_Cast_Summon_Launch", "Staff_Cast_Summon_Effect", "Staff_Cast_Summon_Fail"]
L111_ITEMS = dict((k_, J_ITEMS.pop(k_)) for k_ in VBO111)
L111_INTS = {BO111_SWING: J_INTS.pop(BO111_SWING)}
L111_ROOTS = {BO111_ROOT: J_ROOTS.pop(BO111_ROOT)}
_l111p = set(list(L111_ITEMS.values()) + list(L111_INTS.values()) + list(L111_ROOTS.values()))
L111_J = dict((p_, J.pop(p_)) for p_ in list(J) if p_ in _l111p)
with zipfile.ZipFile(AZ_PATH) as _az111:
    _vbo111p = [n_ for n_ in _az111.namelist() if n_.startswith("Server/Item/Items/") and n_.endswith("/Weapon_Staff_Bo_Wood.json")]
    _vbo111 = json.loads(_az111.read(_vbo111p[0]).decode("utf-8-sig"))
L111_REAL = {}          # the 7 Weapon_Bo_ items as shipped (P13 / R14); the older checks see Staff_Primary + the vanilla cast vars again
for _k111 in sorted(L17_ITEMS):
    if _k111.startswith("Weapon_Bo_"):
        _d111 = L17_J[L17_ITEMS[_k111]]
        L111_REAL[_k111] = copy.deepcopy(_d111)
        _d111["Interactions"]["Primary"] = "Staff_Primary"
        _iv111 = dict(_d111["InteractionVars"])
        for _c111 in BO111_CAST:
            _iv111[_c111] = copy.deepcopy(_vbo111["InteractionVars"][_c111])
        _d111["InteractionVars"] = dict((k_, _iv111[k_]) for k_ in _vbo111["InteractionVars"])     # the vanilla key order
''')

# ---- P5 clash scan: the 2 vanilla Bo overrides are shared with SkyySkills (its 0.4.15+ spell overrides) until it hands them over
hrep('''OURX = OURK - STAFFK
''', '''BOVK = set(("item", i_) for i_ in VBO111)          # 0.1.11: the 2 vanilla Bo overrides - SkyySkills ships them too (NOTE, P13)
OURX = OURK - STAFFK - BOVK
''')
hrep('''    check(not (OURX & ks) and (not (STAFFK & ks) or mod == "SkyySkills"), "P5 (T10): SET %s %s ships no SkyyArmory asset %s" % (mod, ver, sorted(OURX & ks)[:4]))''',
     '''    check(not (OURX & ks) and (not (STAFFK & ks) or mod == "SkyySkills") and (not (BOVK & ks) or mod == "SkyySkills"),
          "P5 (T10): SET %s %s ships no SkyyArmory asset %s" % (mod, ver, sorted((OURX | BOVK) & ks)[:4]))''')
hrep('''    hit = sorted(n for n in JN if n in p_files or (n.startswith("Server/Item/Items/") and os.path.basename(n)[:-5] in p_items)
                 or (n.startswith("Server/Item/Interactions/") and os.path.basename(n)[:-5] in p_ints))''',
     '''    hit = sorted(n for n in JN if (n in p_files or (n.startswith("Server/Item/Items/") and os.path.basename(n)[:-5] in p_items)
                 or (n.startswith("Server/Item/Interactions/") and os.path.basename(n)[:-5] in p_ints)) and os.path.basename(n)[:-5] not in VBO111)''')

# ---- P13 (Python): every 0.1.11 file, before the JVM part
hrep('''PY_OKS, PY_FAILS = OKS[0], len(FAILS)
''', r'''# ============================================================================================================ P13. 0.1.11 no magic shot on the Bo staffs
# (a) every Parallel in the WHOLE jar (a fresh parse - the 0.1.10 P0 ran on the older set only) has 2+ entries
_p13bad = []


def _p13walk(o_, n_):
    if isinstance(o_, dict):
        if o_.get("Type") == "Parallel" and (not isinstance(o_.get("Interactions"), list) or len(o_["Interactions"]) < 2):
            _p13bad.append(n_)
        for v_ in o_.values():
            _p13walk(v_, n_)
    elif isinstance(o_, list):
        for v_ in o_:
            _p13walk(v_, n_)


_p13n = [n_ for n_ in JN if n_.startswith("Server/") and n_.endswith(".json")]
for n_ in _p13n:
    _p13walk(json.loads(JZ.read(n_).decode("utf-8")), n_)
check(not _p13bad and len(_p13n) > 500, "P13 (0.1.10's P0 on the WHOLE jar): every Parallel in all %d JSON files has at least 2 entries: %s" % (len(_p13n), _p13bad[:4]))
# (b) the chain + the root
_vsp13 = aj("int", "Staff_Primary")
check(L111_J[L111_INTS[BO111_SWING]] == _vsp13["Next"]["0"] and _vsp13["Next"]["0"] == {"Type": "Chaining", "ChainingAllowance": 1.25,
      "Next": ["Spear_Swing_Left", "Spear_Swing_Right"]} and L111_J[L111_ROOTS[BO111_ROOT]] == {"Interactions": [BO111_SWING]}
      and L111_INTS[BO111_SWING] == "Server/Item/Interactions/Weapons/Bo/SkyyArmory/SkyyArmory_Bo_Swings.json"
      and L111_ROOTS[BO111_ROOT] == "Server/Item/RootInteractions/Weapons/Bo/SkyyArmory/SkyyArmory_Bo_Primary.json"
      and not ahas("int", BO111_SWING) and not ahas("root", BO111_ROOT) and not ahas("int", BO111_ROOT),
      "P13: SkyyArmory_Bo_Swings = the vanilla Staff_Primary key \"0\" body (Chaining 1.25: Spear_Swing_Left / _Right, read from Assets.zip now); "
      "the root SkyyArmory_Bo_Primary = {Interactions: [it]} (the vanilla root shape); new ids, our folders")
# (c) the 7 Bo items: their 0.1.10 shape (restored above for the older checks) with only Primary + the 5 cast vars changed
bo13 = []
for i_ in sorted(L111_REAL):
    a_, b_ = L17_J[L17_ITEMS[i_]], L111_REAL[i_]
    ch_ = sorted(k_ for k_ in set(a_) | set(b_) if a_.get(k_) != b_.get(k_))
    ivx_ = sorted(k_ for k_ in set(a_["InteractionVars"]) | set(b_["InteractionVars"]) if a_["InteractionVars"].get(k_) != b_["InteractionVars"].get(k_))
    if ch_ != ["InteractionVars", "Interactions"] or b_["Interactions"] != {"Primary": BO111_ROOT, "Secondary": GUARD17} or ivx_ != sorted(BO111_CAST) \
            or [k_ for k_ in BO111_CAST if k_ in b_["InteractionVars"]] or "Mana" in json.dumps(b_) or "Staff_Cast" in json.dumps(b_):
        bo13.append((i_, ch_, ivx_, b_["Interactions"]))
check(len(L111_REAL) == 7 and not bo13, "P13: the 7 Weapon_Bo_ items = 0.1.10's file with Primary = SkyyArmory_Bo_Primary (right click still the guard) "
      "and the 5 Staff_Cast_Summon_* vars gone (no Mana, no cast); swing damages, stats, recipe, looks untouched: %s" % bo13[:3])
# (d) the 2 vanilla overrides: Assets.zip now, only Interactions + the 5 cast vars changed, at the vanilla path
vb13 = []
for i_ in VBO111:
    vp_ = AIDX["item"][i_]
    v_, o_ = aj("item", i_), L111_J[L111_ITEMS[i_]]
    ch_ = sorted(k_ for k_ in set(v_) | set(o_) if v_.get(k_) != o_.get(k_))
    exp_iv = dict((k_, x_) for k_, x_ in v_["InteractionVars"].items() if k_ not in BO111_CAST)
    if L111_ITEMS[i_] != vp_ or ch_ != ["InteractionVars", "Interactions", "PlayerAnimationsId"] \
            or o_["Interactions"] != {"Primary": BO111_ROOT, "Secondary": GUARD17} or o_["PlayerAnimationsId"] != "SkyyArmory_Staff" \
            or v_["PlayerAnimationsId"] != "Staff" or o_["Weapon"] != L111_REAL["Weapon_Bo_Copper"]["Weapon"] \
            or o_["InteractionVars"] != exp_iv or list(o_) != list(v_) or "Mana" in json.dumps(o_) \
            or v_["Interactions"] != {"Primary": "Staff_Primary", "Secondary": "Staff_Primary"}:
        vb13.append((i_, L111_ITEMS[i_], vp_, ch_))
check(not vb13, "P13: Weapon_Staff_Bo_Wood / _Bamboo = the CURRENT Assets.zip file at its vanilla path with only Interactions (Primary = "
      "SkyyArmory_Bo_Primary, vanilla ran Staff_Primary), the 5 cast vars and the animation set changed: %s" % vb13)
# (d2) FIX 0.1.11 (critic; gear.md RIGHT-CLICK BLOCK lock names bo staffs): the 2 vanilla Bo block on right click exactly like our 7 - the same
# guard root and the same animation set (our SkyyArmory_Staff, which has the Guard / GuardBash poses the vanilla Staff set lacks)
_san13 = json.loads(JZ.read("Server/Item/Animations/SkyyArmory/SkyyArmory_Staff.json").decode("utf-8"))
_cu13 = L111_REAL["Weapon_Bo_Copper"]
gb13 = [(i_, L111_J[L111_ITEMS[i_]]["Interactions"].get("Secondary"), L111_J[L111_ITEMS[i_]]["PlayerAnimationsId"]) for i_ in VBO111]
gb13 = [g_ for g_ in gb13 if g_[1:] != (_cu13["Interactions"]["Secondary"], _cu13["PlayerAnimationsId"])]
check(not gb13 and _cu13["Interactions"]["Secondary"] == GUARD17 and _cu13["PlayerAnimationsId"] == "SkyyArmory_Staff"
      and "Guard" in (_san13.get("Animations") or {}) and "GuardBash" in (_san13.get("Animations") or {})
      and "Guard" not in (aj("anim", "Staff").get("Animations") or {}),
      "P13 (fix): right click on Weapon_Staff_Bo_Wood / _Bamboo = %s (block) with the animation set SkyyArmory_Staff (Guard + GuardBash poses), "
      "the same pair as our 7 metal Bo; NEGATIVE CONTROL: the vanilla Staff set has no Guard pose: %s" % (GUARD17, gb13))


# (e) reachability from both buttons of all 9 (item vars applied, our files + Assets.zip) - and the NEGATIVE CONTROL on the 0.1.10 shape
def _p13res(kind_, id_):
    if kind_ == "int" and id_ == BO111_SWING:
        return L111_J[L111_INTS[id_]]
    if kind_ == "root" and id_ == BO111_ROOT:
        return L111_J[L111_ROOTS[id_]]
    for t_ in (JINT, JROOT) if kind_ == "int" else (JROOT,):
        if id_ in t_:
            return t_[id_]
    if ahas(kind_, id_):
        return aj(kind_, id_)
    return None


def p13_reach(item, buttons=("Primary", "Secondary")):
    """every interaction an item's buttons can reach (item vars applied): references only where the engine reads ids - Next / Failed /
    Interactions / Parent strings, a Charging Next map's values, a Replace's Var when the item sets it"""
    vars_ = item.get("InteractionVars") or {}
    types_, txt_, seen_, todo_ = set(), [], set(), []
    for b_ in buttons:
        r_ = (item.get("Interactions") or {}).get(b_)
        if r_:
            todo_.append(("root", r_))

    def scan(o_, ref_):
        if isinstance(o_, str):
            if ref_:
                todo_.append(("int", o_))
        elif isinstance(o_, list):
            for v_ in o_:
                scan(v_, ref_)
        elif isinstance(o_, dict):
            if "Type" in o_:
                types_.add(o_["Type"])
            nmap_ = ref_ and "Type" not in o_ and o_ and all(re.match(r"^[0-9.]+$", str(k_)) for k_ in o_)
            for k_, v_ in o_.items():
                if k_ == "Var":
                    if isinstance(v_, str) and v_ in vars_:
                        todo_.append(("var", v_))
                    continue
                scan(v_, nmap_ or k_ in ("Next", "Failed", "Interactions", "Parent"))
    while todo_:
        k_, x_ = todo_.pop()
        if (k_, x_) in seen_:
            continue
        seen_.add((k_, x_))
        if x_ in vars_:
            d_ = vars_[x_]
        else:
            d_ = _p13res(k_, x_) if k_ != "var" else None
            if d_ is None and k_ == "int":
                d_ = _p13res("root", x_)
            if d_ is None:
                types_.add("MISSING " + x_)
                continue
        txt_.append(json.dumps(d_))
        scan(d_, isinstance(d_, str))
    return types_, "".join(txt_)


BAD13 = ("Charging", "StatsCondition", "LaunchProjectile", "Projectile")
rb13, rows13 = [], []
for i_ in sorted(L111_REAL) + VBO111:
    it_ = L111_REAL[i_] if i_ in L111_REAL else L111_J[L111_ITEMS[i_]]
    ty_, tx_ = p13_reach(it_, ("Primary",))    # right click = the guard on all 9 (checked in c / d / d2)
    rows13.append((i_, sorted(ty_)))
    if [t_ for t_ in ty_ if t_ in BAD13 or t_.startswith("MISSING")] or '"Mana"' in tx_ or "Staff_Cast" in tx_ or "Chaining" not in ty_:
        rb13.append((i_, sorted(ty_)))
nty_, ntx_ = p13_reach(L17_J[L17_ITEMS["Weapon_Bo_Copper"]], ("Primary",))          # the 0.1.10 shape (restored above) = the magic shot
vty_, vtx_ = p13_reach(aj("item", "Weapon_Staff_Bo_Wood"))             # the vanilla file
check(not rb13 and len(rows13) == 9 and "Charging" in nty_ and '"Mana"' in ntx_ and "Staff_Cast_Summon_Charged" in ntx_
      and "Charging" in vty_ and '"Mana"' in vtx_,
      "P13: from the attack button of all 9 Bo staffs (right click = the guard, P13 c / d2) (item vars applied, our files + Assets.zip) nothing reaches a Charging step, a StatsCondition, "
      "a projectile launch, a Mana cost or a Staff_Cast step - only the Spear swing chain (+ the guard on ours); NEGATIVE CONTROL: the same walk "
      "on the 0.1.10 shape and on the vanilla file finds the Charging step and the Mana cast (SkyyGear's charged-attack walk sees no charged "
      "step on a Bo any more): %s | %s" % (rb13[:2], rows13[:1]))
# (f) lang
lang13 = JZ.read("Server/Languages/en-US/server.lang").decode("utf-8")
lb13 = []
for i_ in sorted(L111_REAL):
    ln_ = [l_ for l_ in lang13.split("\n") if l_.startswith("items.%s.description = " % i_)]
    if len(ln_) != 1 or "Hold" in ln_[0] or "cast" in ln_[0].lower() or not ln_[0].endswith(" damage each. Right click: block.") \
            or not ln_[0].split(" = ", 1)[1].startswith("Tap: staff swings, "):
        lb13.append(ln_)
check(not lb13 and "items.Weapon_Staff_Bo_Wood." not in lang13, "P13: the 7 Bo descriptions say tap = swings + right click = block, no hold / cast "
      "line; no text for the vanilla Bo ids (their vanilla names stay): %s" % lb13[:2])
# (g) who wins the 2 vanilla ids: packs without a dependency load in text order of "Group:Name", the last one wins (research/Accessory-Table-Spec 3.1)
bv13 = []
for mod, ver in PINS:
    jp = os.path.join(ROOT, mod, "%s-%s.jar" % (mod, ver))
    if mod != MOD and os.path.isfile(jp):
        with zipfile.ZipFile(jp) as z_:
            hit_ = sorted(os.path.basename(n_)[:-5] for n_ in z_.namelist() if n_.startswith("Server/Item/Items/") and os.path.basename(n_)[:-5] in VBO111)
        if hit_:
            bv13.append((mod, ver, hit_, max(PACK, "Skyy:%s %s" % (ver, mod))))
check(all(b_[0] == "SkyySkills" for b_ in bv13), "P13: no SET jar but SkyySkills ships the vanilla Bo ids: %s" % bv13)
BO_LIVE13 = [b_ for b_ in bv13 if b_[3] != PACK]
if BO_LIVE13:
    print("P13. NOTE HANDOVER NEEDED: %s %s also ships %s and loads after %s (pack name order) - ITS copies are live, so the vanilla Bo staffs "
          "still cast the orb in game until SkyySkills stops shipping them (our 7 Weapon_Bo_ are fixed either way)" % (
              BO_LIVE13[0][0], BO_LIVE13[0][1], BO_LIVE13[0][2], PACK))
print("P13. 0.1.11: no one-entry Parallel in %d files; 9 Bo staffs reach only %s; 4 new files; vanilla Bo winner %s" % (
    len(_p13n), sorted(set(t_ for r_ in rows13 for t_ in r_[1])), [b_[3] for b_ in bv13] or [PACK]))
PY_OKS, PY_FAILS = OKS[0], len(FAILS)
''')

# ---- R11a: the 0.1.11 root + chain go into the stores first (our 7 Bo items name the root)
hrep('''    for c_, tab_, kind_ in ((INTc, L17_INTS, "interaction"), (ROOTc, L17_ROOTS, "root"), (ITMc, L17_ITEMS, "item")):''',
     '''    for c_, tab_, kind_ in ((INTc, L111_INTS, "interaction"), (ROOTc, L111_ROOTS, "root"),          # 0.1.11: the Bo swing chain + root first
                            (INTc, L17_INTS, "interaction"), (ROOTc, L17_ROOTS, "root"), (ITMc, L17_ITEMS, "item")):''')

# ---- R12f / R13f: history (R14e compares 0.1.10 -> 0.1.11)
hrep('''    OLD17 = os.path.join(HERE, "SkyyArmory-0.1.7.jar")
    if not os.path.isfile(OLD17):
        print("R12f. NOTE no SkyyArmory-0.1.7.jar here - the old-vs-new file compare is skipped")''',
     '''    OLD17 = None          # 0.1.11: the 0.1.7 -> new compare is history - R14e compares 0.1.10 -> 0.1.11
    if OLD17 is None:
        print("R12f. NOTE (0.1.11) the 0.1.7 -> new file compare is history - R14e compares 0.1.10 -> 0.1.11")''')
hrep('''    OLD18 = os.path.join(HERE, "SkyyArmory-0.1.8.jar")
    if not os.path.isfile(OLD18):
        print("R13f. NOTE no SkyyArmory-0.1.8.jar here - the old-vs-new file compare is skipped")''',
     '''    OLD18 = None          # 0.1.11: the 0.1.8 -> new compare is history - R14e compares 0.1.10 -> 0.1.11
    if OLD18 is None:
        print("R13f. NOTE (0.1.11) the 0.1.8 -> new file compare is history - R14e compares 0.1.10 -> 0.1.11")''')

# ---- R14 (JVM): before L2 (L2 changes the store)
hrep('''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''',
     r'''    # ============================================================================ R14. 0.1.11 NO MAGIC SHOT ON THE BO STAFFS - every new path EXECUTED
    # R14a THE ENGINE ASSET VALIDATORS (2026-10-08: a pack that fails validation stops the server): the store's decode, then the codec's FULL
    # validate pass (AssetCodec.validate - what GenerateAssetsEvent.addChildAsset runs on contained assets, where 0.1.9's one-entry Parallel
    # failed), then AssetValidationResults.logOrThrowValidatorExceptions (AssetStore.decodeAsset0 throws there), then the contained assets
    HLOG14 = JClass("com.hypixel.hytale.logger.HytaleLogger").get("SkyyArmoryHarness")
    # the bare JVM holds no qualities / sounds / particles: a validator line that only says such an asset does not exist, for a name that IS in
    # Assets.zip or our jar, is the test bed (kept as a NOTE); every other validator line is a failure
    KNOWN14 = set(k_ for kd_ in AIDX.values() for k_ in kd_) | set(os.path.basename(n_).rsplit(".", 1)[0] for n_ in JN) |         set(n_[len("Common/"):] for n_ in list(JN) + list(AZN) if n_.startswith("Common/"))

    def env14(txt):
        fl_ = re.findall(r"FAIL: ([^\n]*)", txt)
        return bool(fl_) and all(re.search(r"'([^']+)'", f_) and re.search(r"'([^']+)'", f_).group(1) in KNOWN14
                                 and ("doesn't exist" in f_ or "does not exist" in f_) for f_ in fl_)
    ENV14, WARN14 = [], []

    def validate14(c, key, text, depth=0):
        n0_ = len(records())
        o_, w_, ei_ = dec17(c, key, text)
        if o_ is None:
            return None, w_
        prob = [w_] if w_ else []
        msgs = []
        try:
            AR.getAssetStore(c.class_).getCodec().validate(o_, ei_)
        except Exception as e_:
            msgs.append("validate threw %s" % str(e_)[:600])
        vr_ = ei_.getValidationResults()
        try:
            if vr_ is not None:
                vr_.logOrThrowValidatorExceptions(HLOG14)
        except Exception as e_:
            msgs.append("logOrThrowValidatorExceptions: %s" % str(e_))
        try:
            ei_.getData().loadContainedAssets(False)          # the contained (inline) assets go through the store's own decode + validators
        except Exception as e_:
            msgs.append("contained assets: %s" % str(e_)[:600])
        msgs += [m_ for lv_, m_ in records()[n0_:] if "Failed to validate" in m_ or "Array size" in m_ or "FAIL:" in m_]
        for m_ in msgs:
            if "FAIL:" not in m_ and "Array size" not in m_ and "threw" not in m_ and "contained assets:" not in m_:
                WARN14.append("%s: %s" % (key, m_[:200]))          # a WARNING-only result (e.g. the deprecated CancelOnItemChange default)
                continue
            (ENV14 if env14(m_) else prob).append("%s: %s" % (key, m_[:400]))
        # every inline step (a dict with a Type below the top) also through the same decode + full validate on its own - how the store
        # generates a contained asset (GenerateAssetsEvent.addChildAsset: AssetCodec.validate + logOrThrowValidatorExceptions)
        if depth == 0 and c in (INTc, ROOTc):          # items carry no inline Type step (their vars inherit by Parent)
            kids_ = []

            def kids(x_, top_):
                if isinstance(x_, dict):
                    if isinstance(x_.get("Type"), str) and not top_:
                        kids_.append(x_)
                    for v_ in x_.values():
                        kids(v_, False)
                elif isinstance(x_, list):
                    for v_ in x_:
                        kids(v_, False)
            kids(json.loads(text), True)
            for n_, k_ in enumerate(kids_):
                ko_, kw_ = validate14(INTc, "%s_Inline%d" % (key, n_), json.dumps(k_), 1)
                if ko_ is None or kw_:
                    prob.append("inline %d %s: %s" % (n_, k_.get("Type"), kw_))
        return o_, "; ".join(prob)
    # NEGATIVE CONTROL first: 0.1.9's Levitate shape (a Simple whose Next is a ONE-entry Parallel) must fail this very function
    neg14_txt = json.dumps({"Type": "Simple", "RunTime": 0.167, "Next": {"Type": "Parallel", "Interactions": [{"Interactions": [BO111_SWING]}]}})
    neg14_o, neg14_w = validate14(INTc, "SkyyArmoryHarness_OneParallel", neg14_txt)
    pos14_txt = json.dumps({"Type": "Simple", "RunTime": 0.167, "Next": {"Type": "Parallel", "Interactions": [{"Interactions": [BO111_SWING]},
                                                                                                             {"Interactions": [BO111_SWING]}]}})
    pos14_o, pos14_w = validate14(INTc, "SkyyArmoryHarness_TwoParallel", pos14_txt)
    check(neg14_w and "Array size is invalid" in neg14_w and pos14_o is not None and not pos14_w,
          "R14a NEGATIVE CONTROL: the validator function refuses 0.1.9's one-entry Parallel with the engine's own message ('Array size is "
          "invalid') and passes the same step with 2 entries - so it catches what stopped the server: %r | %r" % (neg14_w[:300], pos14_w[:200]))
    val14, objs14 = [], {}
    for c_, tab_, kind_ in ((INTc, L111_INTS, "interaction"), (ROOTc, L111_ROOTS, "root"), (ITMc, dict((i_, L17_ITEMS[i_]) for i_ in L111_REAL), "item"),
                            (ITMc, L111_ITEMS, "item")):
        for k_ in sorted(tab_):
            o_, w_ = validate14(c_, k_, JZ.read(tab_[k_]).decode("utf-8"))
            if o_ is None or w_:
                val14.append("%s %s: %s" % (kind_, k_, w_))
                continue
            objs14.setdefault(kind_, []).append((k_, o_))
    env14n = sorted(set(x_.split(":")[0] for x_ in ENV14))
    check(not val14 and sum(len(v_) for v_ in objs14.values()) == 11,
          "R14a: the ENGINE ASSET VALIDATORS pass on all 11 changed / new assets (the chain, the root, the 7 Weapon_Bo_ items, the 2 vanilla Bo "
          "overrides) and every inline step in them: decode, the codec's full validate pass, logOrThrowValidatorExceptions, contained assets - "
          "no failure, no unknown key: %s" % val14[:4])
    print("R14a. engine validators: 11 assets pass; NOTE %d test-bed lines (an asset that exists in Assets.zip / our jar but is not loaded in the "
          "bare JVM - qualities, models, sounds) on %s; %d WARNING-only results; the negative control said: %s" % (
              len(ENV14), env14n[:12], len(WARN14), re.findall(r"FAIL: [^\n]*", neg14_w)[:2]))
    # R14b: into the real stores from our pack; the vanilla swing closure (best effort, like R12a); RootInteraction.build() of the new root
    for kind_ in ("interaction", "root", "item"):
        load({"interaction": INTc, "root": ROOTc, "item": ITMc}[kind_], [o_ for k_, o_ in objs14.get(kind_, [])], PACK)
    st14 = [k_ for k_ in [BO111_SWING] if str(INTc.getAssetMap().getAssetPack(k_)) != PACK] + \
        [k_ for k_ in [BO111_ROOT] if str(ROOTc.getAssetMap().getAssetPack(k_)) != PACK] + \
        [k_ for k_ in list(L111_REAL) + VBO111 if str(ITMc.getAssetMap().getAssetPack(k_)) != PACK]
    need14 = set()

    def clo14(x):
        if isinstance(x, str):
            if x in INTS_ALL and x not in need14 and INTc.getAssetMap().getAsset(x) is None:
                need14.add(x)
                clo14(INTS_ALL[x])
        elif isinstance(x, list):
            for e_ in x:
                clo14(e_)
        elif isinstance(x, dict):
            for k_, v_ in x.items():
                if k_ not in ("Type", "$Comment"):
                    clo14(v_)
    clo14(L111_J[L111_INTS[BO111_SWING]])
    pend14, got14, vb14 = sorted(need14), {}, []
    for _round in range(12):
        nxt_, now_ = [], []
        for i_ in pend14:
            d_ = INTS_ALL[i_]
            if d_.get("Parent") and d_["Parent"] in need14 and d_["Parent"] not in got14:
                nxt_.append(i_)
                continue
            o_, w_ = decp(INTc, i_, d_)
            if o_ is None:
                vb14.append((i_, w_))
                continue
            got14[i_] = o_
            now_.append(i_)
        load(INTc, [got14[i_] for i_ in now_], "Hytale:Hytale")
        pend14 = nxt_
        if not pend14:
            break
    if vb14:
        print("R14b. NOTE %d vanilla swing leaves did not decode alone in the bare JVM: %s" % (len(vb14), [i_ for i_, w_ in vb14][:6]))
    n_miss14 = len([m_ for lv_, m_ in records() if "Missing interaction" in m_])
    res14 = compile_root(BO111_ROOT)
    cls14 = [(cn_, iid_) for cn_, iid_ in res14["ops"] if iid_ is not None and not iid_.startswith("*")]
    n_miss14b = len([m_ for lv_, m_ in records() if "Missing interaction" in m_])
    cn14 = [cn_ for cn_, iid_ in res14["ops"]]
    van14 = set(i_ for i_, w_ in vb14)          # a vanilla leaf the bare JVM cannot decode compiles as a placeholder - only those may
    bad14 = [x_ for x_ in res14["bad"] if not any(x_.endswith(" " + v_) for v_ in van14)]
    check(not st14 and not bad14 and ("ChainingInteraction", BO111_SWING) in cls14
          and not [c_ for c_ in cn14 if c_ in ("ChargingInteraction", "StatsConditionInteraction", "LaunchProjectileInteraction", "ProjectileInteraction")],
          "R14b: the 11 assets sit in the real stores from %s; RootInteraction.build() of SkyyArmory_Bo_Primary = the Chaining step over the "
          "vanilla Spear swings, no missing interaction, no Charging / StatsCondition / projectile step: %s %s %s" % (PACK, st14[:3], bad14[:2], res14["ops"][:10]))
    it14 = []
    for i_ in list(L111_REAL) + VBO111:
        a_ = ITMc.getAssetMap().getAsset(i_)
        try:
            m_ = a_.getInteractions()
            vals_ = sorted(set(str(v_) for v_ in m_.values()))
            want_ = sorted(set([BO111_ROOT, GUARD17]))          # all 9: the swing root + the guard (fix: the vanilla 2 block too)
            if vals_ != want_:
                it14.append((i_, vals_))
            pa_ = str(a_.getPlayerAnimationsId())
            if pa_ != "SkyyArmory_Staff":
                it14.append((i_, "PlayerAnimationsId %s" % pa_))
        except Exception as e_:
            it14.append((i_, "getInteractions: %s" % str(e_)[:120]))
    check(not it14, "R14b: the 9 loaded Bo items' interaction map names only SkyyArmory_Bo_Primary + the guard root, animation set "
          "SkyyArmory_Staff (the vanilla 2 block like ours): %s" % it14[:3])
    # R14c: the pack order on the shared vanilla ids - SkyySkills' copies loaded AFTER ours (its pack name sorts later) are the live ones
    sk14 = []
    with zipfile.ZipFile(SKILLS_JAR) as z_:
        for n_ in z_.namelist():
            if n_.startswith("Server/Item/Items/") and os.path.basename(n_)[:-5] in VBO111:
                o_, w_ = dec(ITMc, os.path.basename(n_)[:-5], z_.read(n_).decode("utf-8-sig"))
                if o_ is not None:
                    sk14.append((os.path.basename(n_)[:-5], o_))
    if sk14:
        skp14 = "Skyy:%s SkyySkills" % SKILLS_PIN
        order14 = sorted([PACK, skp14])
        load(ITMc, [o_ for k_, o_ in sk14], order14[-1]) if order14[-1] == skp14 else None
        live14 = dict((k_, str(ITMc.getAssetMap().getAssetPack(k_))) for k_, o_ in sk14)
        roots14 = dict((k_, sorted(set(str(v_) for v_ in ITMc.getAssetMap().getAsset(k_).getInteractions().values()))) for k_, o_ in sk14)
        check(order14[-1] == skp14 and all(v_ == skp14 for v_ in live14.values()) and all(v_ == ["Staff_Primary"] for v_ in roots14.values()),
              "R14c (documented, not a defect of this jar): SkyySkills %s ships both vanilla Bo ids and its pack name sorts after ours (%s), so "
              "loaded in engine order ITS copies are live (Staff_Primary = the orb) - the handover to SkyyArmory is needed for the 2 vanilla Bo "
              "staffs: %s %s" % (SKILLS_PIN, order14, live14, roots14))
        load(ITMc, [o_ for k_, o_ in objs14.get("item", []) if k_ in VBO111], PACK)       # ours back for the checks below
        print("R14c. NOTE HANDOVER NEEDED: SkyySkills %s wins %s over %s (pack order) - the vanilla Bo staffs keep the orb until it hands them over" % (
            SKILLS_PIN, sorted(live14), PACK))
    else:
        check(True, "R14c: the pinned SkyySkills ships no vanilla Bo item - ours are live")
        print("R14c. the pinned SkyySkills %s ships no vanilla Bo item - our 2 overrides are live" % SKILLS_PIN)
    # R14e: vs the 0.1.10 jar
    OLD110 = os.path.join(HERE, "SkyyArmory-0.1.10.jar")
    if not os.path.isfile(OLD110):
        print("R14e. NOTE no SkyyArmory-0.1.10.jar here - the old-vs-new file compare is skipped")
    else:
        with zipfile.ZipFile(OLD110) as oz_:
            on_ = oz_.namelist()
            new_ = sorted(set(JN) - set(on_))
            gone_ = sorted(set(on_) - set(JN))
            diff_ = sorted(n_ for n_ in on_ if n_ in JSET and not n_.endswith(".class") and n_ != "manifest.json" and oz_.read(n_) != JZ.read(n_))
            ol_ = oz_.read("Server/Languages/en-US/server.lang").decode("utf-8").split("\n")
            ccl = sorted(n_ for n_ in on_ if n_.endswith(".class") and n_ in JSET and oz_.read(n_) != JZ.read(n_))
            jd_ = []
            for i_ in sorted(L111_REAL):
                a_ = json.loads(oz_.read(L17_ITEMS[i_]).decode("utf-8"))
                if a_ != L17_J[L17_ITEMS[i_]]:          # the restored 0.1.10 shape = the 0.1.10 file exactly
                    jd_.append(i_)
        nl_ = JZ.read("Server/Languages/en-US/server.lang").decode("utf-8").split("\n")
        lchg_ = [k_ for k_ in range(max(len(ol_), len(nl_))) if k_ >= len(ol_) or k_ >= len(nl_) or ol_[k_] != nl_[k_]]
        lang_ok = len(nl_) == len(ol_) and len(lchg_) == 7 and all(
            ol_[k_].startswith("items.Weapon_Bo_") and ol_[k_].replace(" Hold: the staff cast.", "") == nl_[k_] for k_ in lchg_)
        want_diff = sorted([L17_ITEMS[i_] for i_ in L111_REAL] + ["Server/Languages/en-US/server.lang"])
        check(sorted(n_ for n_ in new_ if not n_.endswith(".class")) == sorted(_l111p) and not [n_ for n_ in new_ if n_.endswith(".class")]
              and not gone_ and diff_ == want_diff and lang_ok and not jd_,
              "R14e: vs SkyyArmory-0.1.10.jar - the new files are exactly the 4 Bo files, no class added, none gone, the changed non-class files "
              "are the 7 Weapon_Bo_ items (+ the restored 0.1.10 shape = the old file exactly) + the lang (only the 7 Bo descriptions lose "
              "' Hold: the staff cast.'): new %s gone %s diff %s lang %s jd %s" % (new_[:5], gone_[:3], sorted(set(diff_) ^ set(want_diff))[:4], lchg_[:3], jd_))
        print("R14e. vs 0.1.10: +4 files, 7 Bo items + lang changed, %d classes changed: %s" % (len(ccl), ", ".join(c_.split("/")[-1][:-6] for c_ in ccl)))
    print("R14. 0.1.11 Bo staffs: validators (+ negative control), store, build, pack order, old-jar compare - every path executed")
    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''')

out_t = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(out_t)
print("wrote %s" % os.path.relpath(TDST, ROOT))
