"""Derive SkyyArmory/build_skyyarmory_0.1.18.py (+ its harness SkyyArmory/test_skyyarmory_0.1.18.py) from the GENERATED 0.1.17
(SkyyArmory/build_skyyarmory_0.1.17.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_17_patch.py; test_skyyarmory_0.1.17.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_18_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.18.py   then
      python SkyyArmory/test_skyyarmory_0.1.18.py --dir tools/dev/scratch/<task>/harness      (never --deploy)

0.1.18 = THE WAND LAUNCH (docs/answered/classes.md LOCKED 2026-10-10, Skyy word for word):
  "wand doesnt really launch at all when im in the air now. and it still has a double launch. remove the "slow at the top of the jump." keep
   the delay on the power attack shot so you can aim. but no slow. just the launch."
  WHY (0.1.17 code + Skyy's log: one push, no double-hop guard WARN): after the hop the leap watched for the top of the jump, then HUNG there -
  a Velocity Set EVERY tick for 0.35 s (sideways x 0.2 + 1.5 b/s down) - and let go at the end = the felt second launch. In the air the
  0.1.16 up-cap counted the jump's rise (TravMath.capUp: at a jump's top a 27-degree-down cast got 0 up) and the "top" came at once, so the
  hang cut the backward speed to a fifth after 0.15 s = "doesn't really launch at all".
  1 NO HANG FOR THE WAND. hop.hangSeconds default 0.35 -> 0 (one-time update of an untouched 0.35, PROJECT-RULES 4, migrate018; Skyy's live
    file has no hop.* line = the marker only). With 0 the wand leap never enters the hang: the player gets exactly ONE velocity instruction per
    cast - the launch. (An admin who sets hop.hangSeconds > 0 again gets the old hang; the bow leap keeps its own bow.hangSeconds - untouched.)
  2 THE AIM DELAY STAYS. NEW row hop.aimDelay (0.35 s = the old hang length, 0..1.5): the charged orb is still removed at its spawn and launched
    hop.aimDelay later (LeapState phase 3, Leap.tickPlayer: NO velocity write meanwhile) from where the caster is NOW toward where they look NOW
    (Leap.fire / aim - unchanged). hop.aimDelay 0 + hop.hangSeconds 0 = the 0.1.2 way (orb at the cast, the hop job).
  3 THE FULL LAUNCH IN THE AIR. The wand launch (Leap.launchNow; the 0.1.2 hop job ArmoryTrav.hop the same) = a Set of -look x hop.force with
    the dagger dash config; only the launch's OWN up part is capped at hop.maxUp (TravMath.launchUp) - the player's current vertical speed is
    never counted or subtracted, a jump's rise no longer eats it, and a fall is replaced (Set) - Skyy: full strength in the air. (The old
    "a hop never cancels a damaging fall" rule now applies to the bow leap only.) hop.force 18 unchanged.
  4 THE HEAL AURA AT THE LANDING SPOT stays (0.1.17): with no hang the landing watch starts when the launch is applied (Leap.begin), and the
    orb's fire does not re-arm it (LeapState.armed).
No new item / asset / class / interaction; saved data: config.properties only (migrate018 + 1 new key - a missing key reads its default).
ROLLBACK: 0.1.17 reads hop.hangSeconds 0 as "no hang" (the orb at the top of the jump, no aim delay) and ignores hop.aimDelay (no data loss).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.17.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.18.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.17.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.18.py")

CR, LF = chr(13), chr(10)
raw = open(SRC, encoding="utf8", newline="").read()
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.17"\nMOD = "SkyyArmory"' in s and "0.1.17 = THE WAND ROUND" in s, "build_skyyarmory_0.1.17.py is not the 0.1.17 pin"
assert "migrate018" not in s and "HOP_AIM" not in s and "launchNow" not in s, "0.1.17 already has the 0.1.18 parts"


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# ---------------------------------------------------------------------------------------------------------------- header + version
rep('''"""SkyyArmory 0.1.17 - build script (javassist via jpype). GENERATED by tools/armory_0_1_17_patch.py from the GENERATED 0.1.16 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.17.py -> SkyyArmory/SkyyArmory-0.1.17.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.17.py --dir tools/dev/scratch/<task>/harness.
''', '''"""SkyyArmory 0.1.18 - build script (javassist via jpype). GENERATED by tools/armory_0_1_18_patch.py from the GENERATED 0.1.17 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.18.py -> SkyyArmory/SkyyArmory-0.1.18.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.18.py --dir tools/dev/scratch/<task>/harness.

0.1.18 = THE WAND LAUNCH (Skyy 2026-10-10: "wand doesnt really launch at all when im in the air now. and it still has a double launch. remove
the slow at the top of the jump. keep the delay on the power attack shot so you can aim. but no slow. just the launch."; full notes in
tools/armory_0_1_18_patch.py): hop.hangSeconds default 0.35 -> 0 (one-time update of an untouched line, migrate018) = NO hang: ONE velocity
instruction per cast (the launch), none while the orb waits; NEW row hop.aimDelay (0.35 s): the charged orb still fires that long after the
launch from where you are toward where you look then; the wand launch is a Set whose own up part is capped at hop.maxUp - your current
vertical speed never counts (full strength in the air, a fall replaced); the heal-aura landing watch starts at the launch. Bow leap unchanged.

0.1.17 (the base, everything below is still true unless 0.1.18 above says otherwise):
''')
rep('VERSION = "0.1.17"\nMOD = "SkyyArmory"', 'VERSION = "0.1.18"\nMOD = "SkyyArmory"')

# ---------------------------------------------------------------------------------------------------------------- rows
rep("""    ('hop.hangSeconds', 'Wand hang at the top (s)', 'hop', 'dec', '0.35', '0', '1.5', '', 's', 'live', 'Hop, a slow fall at the top to aim, THEN the orb fires. 0 = the orb at the cast (0.1.2).', 'HOP_HANG', 'double', '0.35', 'Wand hold: the hop, then this many seconds of slow fall at the top (to aim), then the orb fires where you look (0 = the orb at the cast).'),""",
    """    # 0.1.18 (Skyy 2026-10-10: "remove the slow at the top of the jump ... no slow. just the launch"): 0.35 -> 0 (migrate018); the aim delay = hop.aimDelay
    ('hop.hangSeconds', 'Wand slow fall at the top (s)', 'hop', 'dec', '0', '0', '1.5', '', 's', 'live', 'Off (0) = no slow, just the launch (Skyy). Above 0 = the old hang at the top.', 'HOP_HANG', 'double', '0', 'Wand hold: seconds of slow fall at the top of the launch (Skyy 2026-10-10: 0 = no slow, just the launch; the aim pause is hop.aimDelay).'),""")
rep("""    ('hop.maxUp', 'Wand hop max up speed (b/s)', 'hop', 'dec', '15', '0', '50', '', '', 'live', 'Caps the upward push (look down = up). 15 = about 3.5 blocks; a jump never adds. 0 = no cap.', 'HOP_MAXUP', 'double', '15', "Wand hop: the upward part of the push is at most this (blocks per second; 15 = about 3.5 blocks up; in mid-air a jump's rise counts toward it; 0 = no cap, the 0.1.15 way)."),""",
    """    ('hop.maxUp', 'Wand hop max up speed (b/s)', 'hop', 'dec', '15', '0', '50', '', '', 'live', "Caps the launch's own upward part (look down = up). Full in the air too. 0 = no cap.", 'HOP_MAXUP', 'double', '15', "Wand launch: its own upward part is at most this (blocks per second; 15 = about 3.5 blocks up; your current speed never counts - full in the air; 0 = no cap)."),
    # 0.1.18 (Skyy: "keep the delay on the power attack shot so you can aim"): the orb waits this long after the launch - no slow meanwhile
    ('hop.aimDelay', 'Wand aim delay (s)', 'hop', 'dec', '0.35', '0', '1.5', '', 's', 'live', 'The charged orb fires this long after the launch, where you look then. No slow.', 'HOP_AIM', 'double', '0.35', 'Wand hold: after the launch the charged orb waits this many seconds (no slow - you fly on), then fires from where you are toward where you look (0 = with the launch).'),""")

# fixer (critic LOW): hop.hangFall only acts when hop.hangSeconds > 0 (off by default now) - say so on the row, so it does not look live
rep("""    ('hop.hangFall', 'Wand hang drift down (b/s)', 'hop', 'dec', '1.5', '0', '10', '', '', 'live', 'Downward speed while hanging (0 = hold still).', 'HOP_FALL', 'double', '1.5', 'Downward speed (blocks per second) while the wand hop hangs at the top (0 = hold still).'),""",
    """    ('hop.hangFall', 'Wand hang drift down (b/s)', 'hop', 'dec', '1.5', '0', '10', '', '', 'live', 'Only used when the slow fall above is more than 0. Downward speed while hanging.', 'HOP_FALL', 'double', '1.5', 'Only used when hop.hangSeconds is above 0 (off by default since 0.1.18): downward speed (blocks per second) while the wand hop hangs at the top (0 = hold still).'),""")

# ---------------------------------------------------------------------------------------------------------------- markers + the default file
rep("""M17_MARK_ID = 'SkyyArmory 0.1.17 wand hop + heal aura'
""", """M18_MARK_ID = 'SkyyArmory 0.1.18 wand launch'
M18_MARK = '# SkyyArmory 0.1.18 wand launch (Skyy 2026-10-10: "no slow. just the launch"): no slow fall at the top (hop.hangSeconds 0; 0.1.17: 0.35) - the orb still waits hop.aimDelay to aim - a line still on the old 0.35 was updated once'
M17_MARK_ID = 'SkyyArmory 0.1.17 wand hop + heal aura'
""")
rep('''    M16_MARK,
    M17_MARK,
    "hop.force=18",''', '''    M16_MARK,
    M17_MARK,
    M18_MARK,
    "hop.force=18",''')

# ---------------------------------------------------------------------------------------------------------------- loader + texts
rep('''  HOP_HANG = dec(c.getProperty("hop.hangSeconds"), 0.35, 0.0, 1.5);''',
    '''  HOP_HANG = dec(c.getProperty("hop.hangSeconds"), 0.0, 0.0, 1.5);          // 0.1.18: Skyy "no slow. just the launch" 0.35 -> 0''')
rep('''  HOP_MAXUP = dec(c.getProperty("hop.maxUp"), 15.0, 0.0, 50.0);          // 0.1.16: the upward part of the wand hop (0 = no cap)
''', '''  HOP_MAXUP = dec(c.getProperty("hop.maxUp"), 15.0, 0.0, 50.0);          // 0.1.16: the upward part of the wand hop (0 = no cap)
  HOP_AIM = dec(c.getProperty("hop.aimDelay"), 0.35, 0.0, 1.5);          // 0.1.18: the charged orb waits this long after the launch (no slow)
''')
rep('''  return "wand hold: hop " + HOP_FORCE + (HOP_MAXUP > 0.0 ? " (up at most " + HOP_MAXUP + " b/s, a jump never adds)" : " (no up cap)") + ", one hop per cast" + (HOP_HANG > 0.0 ? ", hang " + HOP_HANG + " s (drift " + HOP_FALL + " b/s down), then the orb" : ", the orb at the cast (no hang)")''',
    '''  return "wand hold: launch " + HOP_FORCE + (HOP_MAXUP > 0.0 ? " (its up part at most " + HOP_MAXUP + " b/s, full in the air)" : " (no up cap)") + ", one launch per cast"
    + (HOP_HANG > 0.0 ? ", hang " + HOP_HANG + " s (drift " + HOP_FALL + " b/s down), then the orb" : (HOP_AIM > 0.0 ? ", no slow - the orb " + HOP_AIM + " s later where you look" : ", the orb at the cast (no hang)"))''')

# ---------------------------------------------------------------------------------------------------------------- migrate018 (one key, its own marker)
_a = s.index('for f in ("public static final String M17_KEY1 = \\"hop.force\\";"')
_b = s.index('}""")\n', s.index('public static synchronized String migrate017()')) + len('}""")\n')
_m17 = s[_a:_b]
assert _m17.count("migrate017") == 1 and _m17.count("m17Key") == 3 and _m17.count("public static Object[] m17Update(String text)") == 1, "the migrate017 block moved"
_m18 = (_m17.replace("M17_", "M18_").replace("m17Key", "m18Key").replace("m17Update", "m18Update").replace("m17Log", "m18Log")
        .replace("migrate017", "migrate018"))
_u0 = _m18.index('M(cfg, r"""\npublic static Object[] m18Update(String text) {')
_u1 = _m18.index('}""")\n', _u0) + len('}""")\n')
_m18 = _m18[:_u0] + '''M(cfg, r"""
public static Object[] m18Update(String text) {
  return m18Key(text, M18_KEY1, M18_OLD1, M18_NEW1, true);
}""")
''' + _m18[_u1:]
for _o, _n in (('"public static final String M18_KEY1 = \\"hop.force\\";", "public static final String M18_OLD1 = \\"22\\";",\n'
                '          "public static final String M18_NEW1 = \\"18\\";", "public static final String M18_KEY2 = \\"orb.seconds\\";",\n'
                '          "public static final String M18_OLD2 = \\"3.5\\";", "public static final String M18_NEW2 = \\"5\\";",',
                '"public static final String M18_KEY1 = \\"hop.hangSeconds\\";", "public static final String M18_OLD1 = \\"0.35\\";",\n'
                '          "public static final String M18_NEW1 = \\"0\\";",'),
               ('M18_WHO = \\"SkyyArmory 0.1.17\\"', 'M18_WHO = \\"SkyyArmory 0.1.18\\"'),
               ('" kept (custom) - the 0.1.17 default is "', '" kept (custom) - the 0.1.18 default is "'),
               ('"before the 0.1.17 wand hop + heal aura update"', '"before the 0.1.18 wand launch update"'),
               ('"config.properties NOT updated to the 0.1.17 wand hop + heal aura:', '"config.properties NOT updated to the 0.1.18 wand launch:'),
               ('"config.properties updated to the 0.1.17 wand hop + heal aura: " + chg + " (Skyy 2026-10-10: reduce how far, last a little longer; the old file',
                '"config.properties updated to the 0.1.18 wand launch: " + chg + " (Skyy 2026-10-10: no slow, just the launch; the old file'),
               ('"config.properties: no hop.force / orb.seconds line held the old 22 / 3.5 - nothing changed, the new defaults 18 / 5 apply (0.1.17 marker added)"',
                '"config.properties: no hop.hangSeconds line held the old 0.35 - nothing changed, the new default 0 applies (0.1.18 marker added)"'),
               ('"could not update config.properties to the 0.1.17 wand hop + heal aura (the file is used as it is): "',
                '"could not update config.properties to the 0.1.18 wand launch (the file is used as it is): "')):
    assert _m18.count(_o) == 1, "m18 clone anchor: " + _o
    _m18 = _m18.replace(_o, _n)
assert "0.1.17" not in _m18 and "M17" not in _m18 and "m17" not in _m18 and "KEY2" not in _m18 and "orb.seconds" not in _m18, \
    [l_ for l_ in _m18.split("\n") if "0.1.17" in l_ or "17" in l_ or "KEY2" in l_][:5]
s = s[:_b] + ("# 0.1.18 (Skyy 2026-10-10: \"no slow. just the launch\"): hop.hangSeconds 0.35 -> 0 ONCE - the migrate017 steps (one key, its own marker), "
              "same rules (PROJECT-RULES 4); runs AFTER migrate017\n") + _m18 + s[_b:]
rep('''  String m17 = @PKG@.ArmoryCfg.migrate017();          // 0.1.17: hop.force 22 -> 18 + orb.seconds 3.5 -> 5 ONCE (same rules; after 0.1.16's 30 -> 22)
''', '''  String m17 = @PKG@.ArmoryCfg.migrate017();          // 0.1.17: hop.force 22 -> 18 + orb.seconds 3.5 -> 5 ONCE (same rules; after 0.1.16's 30 -> 22)
  String m18 = @PKG@.ArmoryCfg.migrate018();          // 0.1.18: hop.hangSeconds 0.35 -> 0 ONCE (same rules) - no slow, just the launch
''')
rep('''(m16.length() > 0 ? "; " + m16 : "") + (m17.length() > 0 ? "; " + m17 : ""));''',
    '''(m16.length() > 0 ? "; " + m16 : "") + (m17.length() > 0 ? "; " + m17 : "") + (m18.length() > 0 ? "; " + m18 : ""));''')

# ---------------------------------------------------------------------------------------------------------------- TravMath.launchUp (pure)
rep('''# 0.1.3 THE RHYTHM (pure): the top of a leap''', '''# 0.1.18 THE WAND LAUNCH's up part (Skyy: "wand doesnt really launch at all when im in the air"): only the launch's OWN up part is capped
# at maxUp (0 = no cap); the player's current vertical speed is never counted or subtracted (the launch is a Set - a fall is replaced)
M(tmath, r"""
public static double launchUp(double vy, double maxUp) {
  if (maxUp > 0.0 && vy > maxUp) return maxUp;
  return vy;
}""")
# 0.1.3 THE RHYTHM (pure): the top of a leap''')

# ---------------------------------------------------------------------------------------------------------------- ArmoryTrav.hop (the 0.1.2 hop job)
rep('''  double cvy = Double.NaN;
  try { @VEC@ cv = v.getClientVelocity(); if (cv != null) cvy = cv.y; } catch (Throwable t1) { cvy = Double.NaN; }
  double up = upVy(st, ref, hv[1], @PKG@.ArmoryCfg.HOP_MAXUP, cvy);          // 0.1.16: hop.maxUp, a jump never adds
  double vy = @PKG@.TravMath.hopVy(up, cvy, maxFall(w));         // trav-fix: a hop never cancels a damaging fall (Double-Jump rule 7)
  boolean kept = vy != up;
  v.addInstruction(new @VEC@(hv[0], vy, hv[2]), dash(), @CVT@.Set);''',
    '''  double vy = @PKG@.TravMath.launchUp(hv[1], @PKG@.ArmoryCfg.HOP_MAXUP);          // 0.1.18: the launch's own up part capped - full in the air (Skyy)
  v.addInstruction(new @VEC@(hv[0], vy, hv[2]), dash(), @CVT@.Set);''')
rep('''  LAST_WHY = "hop full" + (kept ? " - fall kept" : "");''', '''  LAST_WHY = "hop full";''')

# ---------------------------------------------------------------------------------------------------------------- the wand leap: ONE launch, the aim delay
rep('''          "public int hangTicks;"):
    F(lstate, f)''', '''          "public int hangTicks;", "public long aimMs;", "public boolean armed;"):          # 0.1.18: the wand's aim delay; the landing watch armed at the launch
    F(lstate, f)''')
rep('''  if (s.kind == 1) @PKG@.ArmoryTrav.landArm(st, s.u, System.currentTimeMillis());          // 0.1.17: the hang is over - watch for the landing''',
    '''  if (s.kind == 1 && !s.armed) @PKG@.ArmoryTrav.landArm(st, s.u, System.currentTimeMillis());          // 0.1.17: the hang is over - watch for the landing (0.1.18: unless armed at the launch)''')
rep('''M(leap, r"""
public static @PKG@.LeapState begin(int kind,''', '''# 0.1.18 THE WAND LAUNCH (Skyy: "no slow. just the launch", full strength in the air): ONE Velocity Set = -look x force with the dagger dash
# config; only its own up part capped at maxUp (TravMath.launchUp); the current vertical speed never counts (a fall is replaced). { x, y, z, 0, 1 }
M(leap, r"""
public static double[] launchNow(@CB@ buf, @REF@ r, double[] dir, double force, double maxUp) {
  if (dir == null || !(force > 0.0)) return null;
  double[] hv = @PKG@.TravMath.hopVector(dir[0], dir[1], dir[2], force, false);          // 0.1.7: never halved over the void (Skyy)
  double vy = @PKG@.TravMath.launchUp(hv[1], maxUp);
  double cvy = clientVy(buf, r);
  if (!vel(buf, r, hv[0], vy, hv[2], true)) return null;
  if (!HOP_LOGGED) {
    HOP_LOGGED = true;
    @PKG@.ArmoryLog.info("first wand launch after start: back " + @PKG@.TravMath.fmt(Math.sqrt(hv[0] * hv[0] + hv[2] * hv[2])) + " b/s, up "
      + @PKG@.TravMath.fmt(vy) + " b/s (look " + @PKG@.TravMath.fmt(hv[1]) + ", hop.force " + @PKG@.TravMath.fmt(force) + ", hop.maxUp "
      + @PKG@.TravMath.fmt(maxUp) + ", your up speed before it " + (Double.isNaN(cvy) ? "?" : @PKG@.TravMath.fmt(cvy)) + " - replaced) - one launch per cast, no slow");
  }
  return new double[] { hv[0], vy, hv[2], 0.0, 1.0 };
}""")
M(leap, r"""
public static @PKG@.LeapState begin(int kind,''')
rep('''  double[] h = hopNow(buf, r, dir, force, kind == 1 ? @PKG@.ArmoryCfg.HOP_MAXUP : 0.0);          // 0.1.16: the cap on the wand only
  if (h != null) { s.hx = h[0]; s.hz = h[2]; s.hopVy = h[1]; s.kept = h[3] > 0.5; }''',
    '''  double[] h = kind == 1 ? launchNow(buf, r, dir, force, @PKG@.ArmoryCfg.HOP_MAXUP) : hopNow(buf, r, dir, force, 0.0);          // 0.1.18: the wand = ONE launch
  if (h != null) { s.hx = h[0]; s.hz = h[2]; s.hopVy = h[1]; s.kept = h[3] > 0.5; }
  if (kind == 1 && s.hangMs <= 0L) {          // 0.1.18 (Skyy: "no slow. just the launch"): no hang - the orb waits hop.aimDelay, NO velocity write meanwhile
    s.phase = 3;
    s.aimMs = Math.round(@PKG@.ArmoryCfg.HOP_AIM * 1000.0);
    if (s.aimMs < 0L) s.aimMs = 0L;
    if (h != null) { @PKG@.ArmoryTrav.landArm(st, u, now); s.armed = true; }          // the heal-aura landing watch starts at the launch
  }''')
rep('''  if (mounted(buf, r)) { fire(s, st, buf, "mounted"); return; }
  s.ticks = s.ticks + 1;''', '''  if (mounted(buf, r)) { fire(s, st, buf, "mounted"); return; }
  s.ticks = s.ticks + 1;
  if (s.phase == 3) {          // 0.1.18: the wand's aim delay - NO velocity write; then the orb from where you are toward where you look NOW
    if (now - s.t0 >= s.aimMs) fire(s, st, buf, "after the aim delay");
    return;
  }''')

# ---------------------------------------------------------------------------------------------------------------- the routing: the aim delay uses the leap path
rep('''    if (!own && @PKG@.ArmoryCfg.PART_TRAV && cu != null && HOP_SERVER && @PKG@.ArmoryCfg.HOP_HANG > 0.0 && @PKG@.ArmoryCfg.HOP_FORCE > 0.0''',
    '''    if (!own && @PKG@.ArmoryCfg.PART_TRAV && cu != null && HOP_SERVER && (@PKG@.ArmoryCfg.HOP_HANG > 0.0 || @PKG@.ArmoryCfg.HOP_AIM > 0.0) && @PKG@.ArmoryCfg.HOP_FORCE > 0.0''')
rep('''  if (@PKG@.ArmoryCfg.HOP_HANG > 0.0 && STATES.get(u) == null && @PKG@.ArmoryTrav.dupHop(u, now)) {''',
    '''  if ((@PKG@.ArmoryCfg.HOP_HANG > 0.0 || @PKG@.ArmoryCfg.HOP_AIM > 0.0) && STATES.get(u) == null && @PKG@.ArmoryTrav.dupHop(u, now)) {''')

# ---------------------------------------------------------------------------------------------------------------- prints
rep('''print("0.1.17 wand round: hop.force default %s''', '''print("0.1.18 wand launch: hop.hangSeconds default %s (one-time update marker %r), hop.aimDelay default %s s, hop.maxUp %s on the launch's own up "
      "part only (full in the air); one velocity instruction per cast" % ([r_[4] for r_ in CFG_LEAP if r_[0] == "hop.hangSeconds"][0], M18_MARK_ID,
                                                                      [r_[4] for r_ in CFG_LEAP if r_[0] == "hop.aimDelay"][0],
                                                                      [r_[4] for r_ in CFG_LEAP if r_[0] == "hop.maxUp"][0]))
print("0.1.17 wand round: hop.force default %s''')

with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(s.replace(LF, NL))
print("wrote %s" % os.path.relpath(DST, ROOT))

if os.environ.get("ARMORY0118_BUILD_ONLY"):
    raise SystemExit(0)
# ================================================================================================================ the harness
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.17 - test harness. GENERATED by tools/armory_0_1_17_patch.py from test_skyyarmory_0.1.16.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.18 - test harness. GENERATED by tools/armory_0_1_18_patch.py from test_skyyarmory_0.1.17.py - edit the patch, never this file.
Run: python SkyyArmory/test_skyyarmory_0.1.18.py --dir tools/dev/scratch/<task>/harness   (--no-set skips the one-JVM SET run, --keep keeps it)
Every 0.1.17 check still runs on the 0.1.17 shape: the jar's files are 0.1.17's (P20 proves it: only the classes + the manifest version differ);
the classes are the real 0.1.18 ones; the old wand checks that need the hang run with hop.hangSeconds 0.35 pinned (an admin value the 0.1.18
code still honours = the exact 0.1.17 rhythm); the default-row checks read the new defaults (hop.hangSeconds 0, hop.aimDelay 0.35); the
launch maths changed on purpose (the launch's own up part capped, the current speed never counted) - the old checks that measured the 0.1.16
mid-air cap / the kept fall on the WAND now expect the 0.1.18 numbers (the bow keeps the old maths); R20g now compares 0.1.16 -> 0.1.17
(history), R21f 0.1.17 -> 0.1.18.
NEW P20 (Python) + R21 (JVM, after R20) EXECUTE every 0.1.18 path:
  P20  vs the 0.1.17 jar: every non-class file byte-identical except the manifest (its version only), the same classes
  R21  a: the rows + defaults (hop.hangSeconds 0, hop.aimDelay 0.35 + clamps), the default file (+ the 0.1.18 marker), armory:leap words,
       TravMath.launchUp (pure); b: ONE VELOCITY WRITE PER CAST through the real chain (ArmoryTrav.added -> Leap.onWandOrb -> begin ->
       launchNow; Leap.tickPlayer every tick) - on the ground, rising after a jump, at the top, falling, falling FAST (replaced): exactly
       one Velocity instruction with the full numbers, NONE during the aim delay, the orb launched after hop.aimDelay from the CURRENT
       position toward the CURRENT look; MUTANT hop.hangSeconds 0.35 = the per-tick hang writes come back; c: the heal-aura landing watch
       armed AT THE LAUNCH, not re-armed by the orb's fire, the aura where the caster landed (a landing during the aim delay kept); d: the
       0.1.2 hop job (hop.aimDelay 0 + hop.hangSeconds 0) with the same launch maths, one write; the bow leap unchanged (hang + kept fall);
       e: THE ONE-TIME UPDATE (hop.hangSeconds 0.35 -> 0: marker, History copy, change-log line, idle second run, a hand-set value kept);
       f: vs the 0.1.17 jar method by method (only the planned methods / fields differ).

0.1.17 harness: SkyyArmory 0.1.17 - test harness. GENERATED by tools/armory_0_1_17_patch.py from test_skyyarmory_0.1.16.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.17"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.17 SkyyArmory"',
     'VERSION = "0.1.18"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.18 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory0117", "harness")', 'os.path.join(SCRATCH_ROOT, "armory0118", "harness")')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.17.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.18.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.17"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.18"))')
for _v in ('"[SkyyArmory] 0.1.17 ready" in m_', '"0.1.17 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_',
           '"0.1.17 crossbow grapple: grapple on" in m_',
           '"0.1.17 monk moves on - Pole-Vault (Bo hold): lunge 3 in 0.2 s, 4.5 up x 7 forward (push x2.1)" in m_',
           '"0.1.17 wand signature on - the signature key when the meter is full (20; quick-shot hit +1, charged hit +2)" in m_',
           'come from Skyy:0.1.17 SkyyArmory" in str(r[1])'):
    hrep(_v, _v.replace("0.1.17", "0.1.18"))
hrep('t_.replace("0.1.17", "V").replace("0.1.16", "V")', 't_.replace("0.1.18", "V").replace("0.1.17", "V").replace("0.1.16", "V")')
hrep("    MN20, MO20 = methods_of(JAR), methods_of(OLD116)",
     "    MN20, MO20 = methods_of(OLD117), methods_of(OLD116)          # 0.1.18: R20g = the 0.1.17 round's compare (history); R21f = 0.1.17 -> 0.1.18")
hrep('''OLD116 = os.path.join(HERE, "SkyyArmory-0.1.16.jar")          # 0.1.17: the base (the SET pin)
''', '''OLD116 = os.path.join(HERE, "SkyyArmory-0.1.16.jar")          # 0.1.17: the base (the SET pin)
OLD117 = os.path.join(HERE, "SkyyArmory-0.1.17.jar")          # 0.1.18: the base (the SET pin)
if not os.path.isfile(OLD117):
    raise SystemExit("the 0.1.18 harness needs SkyyArmory-0.1.17.jar (the base, the SET pin) next to it: %s" % OLD117)
''')
# the setup()-twice check: + the 0.1.18 text step and its marker
hrep('''        r17_ = ACfg.m17Update(t16_)          # 0.1.17: + hop.force 22 -> 18 / orb.seconds 3.5 -> 5
        want_ = (str(r17_[0]) if r17_ is not None else t16_).encode("latin-1")''', '''        r17_ = ACfg.m17Update(t16_)          # 0.1.17: + hop.force 22 -> 18 / orb.seconds 3.5 -> 5
        t17_ = str(r17_[0]) if r17_ is not None else t16_
        r18_ = ACfg.m18Update(t17_)          # 0.1.18: + hop.hangSeconds 0.35 -> 0
        want_ = (str(r18_[0]) if r18_ is not None else t17_).encode("latin-1")''')
hrep('''and str(ACfg.M16_MARK_ID) in txt1_ and str(ACfg.M17_MARK_ID) in txt1_,''',
     '''and str(ACfg.M16_MARK_ID) in txt1_ and str(ACfg.M17_MARK_ID) in txt1_ and str(ACfg.M18_MARK_ID) in txt1_,''')
# ---- the old checks on the 0.1.17 shape: every useDefaults() of the old sections pins hop.hangSeconds 0.35 (the 0.1.17 hang - an admin value
# 0.1.18 still honours); where they asked for the 0.1.2 hop job (hop.hangSeconds 0) the aim delay goes to 0 too (= the 0.1.2 way in 0.1.18)
import re as _re
_nud = ts.count("ACfg.useDefaults()")
assert _nud > 40, _nud
ts = ts.replace("ACfg.useDefaults()", "use_defaults17()")
hrep('''    ACfg, ASp, ADefs = JClass(PKG + "ArmoryCfg"), JClass(PKG + "ArmorySpawn"), JClass(PKG + "ArmoryDefs")
''', '''    ACfg, ASp, ADefs = JClass(PKG + "ArmoryCfg"), JClass(PKG + "ArmorySpawn"), JClass(PKG + "ArmoryDefs")

    def use_defaults17():          # 0.1.18: the old checks = the 0.1.17 shape (hop.hangSeconds 0.35); R21 checks the real 0.1.18 defaults
        ACfg.useDefaults()
        ACfg.HOP_HANG = 0.35
''')
_n0 = len(_re.findall(r"(?m)^( *)ACfg\.HOP_HANG = 0\.0\n", ts))
assert _n0 == 5, _n0
ts = _re.sub(r"(?m)^( *)ACfg\.HOP_HANG = 0\.0\n", lambda m_: m_.group(0) + m_.group(1) + "ACfg.HOP_AIM = 0.0          # 0.1.18: + no aim delay = the 0.1.2 hop job\n", ts)
# N4: the 0.1.2 hop job's launch now REPLACES a fall (Skyy: full strength in the air) - the old "fall kept" numbers become the full launch
hrep('''    check(hf1[0] == (0.0, -30.0, -13.0) and why_f1.endswith("fall kept") and hf2[0] == (0.0, -30.0, 0.0) and hf3[0] == (0.0, 13.0, 0.0)
          and abs(float(AT.maxFall(world)) - 21.0) < 1e-9,
          "N4 (trav-fix, Double-Jump rule 7): falling at 30 b/s the hop keeps the fall (level: (0, -30, -13); look down: (0, -30, 0) - no fall-damage "
          "escape); a 10 b/s fall hops normally (0, 13, 0): %s / %s / %s" % (hf1, hf2, hf3))''',
     '''    check(hf1[0] == (0.0, 0.0, -13.0) and why_f1 == "hop full" and hf2[0] == (0.0, 13.0, 0.0) and hf3[0] == (0.0, 13.0, 0.0)
          and abs(float(AT.maxFall(world)) - 21.0) < 1e-9,
          "N4 (0.1.18, Skyy: the full launch in the air - was Double-Jump rule 7 'fall kept'): falling at 30 b/s the wand hop REPLACES the fall "
          "(level: (0, 0, -13); look down: (0, 13, 0)); a 10 b/s fall the same (0, 13, 0): %s / %s / %s" % (hf1, hf2, hf3))''')
# K: + the new row hop.aimDelay (right after hop.maxUp)
hrep('''    NEW_ROWS += ["hop.hangSeconds", "hop.hangFall", "hop.maxUp", "part.bowtrav",''',
     '''    NEW_ROWS += ["hop.hangSeconds", "hop.hangFall", "hop.maxUp", "hop.aimDelay", "part.bowtrav",''')          # 0.1.18: + hop.aimDelay
# R2: the row defaults (hop.hangSeconds 0, hop.aimDelay 0.35) + the 0.1.18 armory:leap words (the bridge text is the loader's: the real defaults)
hrep('''    want_l = {"hop.force": "18", "hop.maxUp": "15", "hop.hangSeconds": "0.35",''',
     '''    want_l = {"hop.force": "18", "hop.maxUp": "15", "hop.hangSeconds": "0", "hop.aimDelay": "0.35",          # 0.1.18: no hang, the aim delay row''')
hrep('''ltxt.startswith("wand hold: hop 18.0 (up at most 15.0 b/s, a jump never adds), one hop per cast, hang 0.35 s")''',
     '''ltxt.startswith("wand hold: launch 18.0 (its up part at most 15.0 b/s, full in the air), one launch per cast, no slow - the orb 0.35 s later where you look")''')
# R3: a fall is no longer kept on the WAND (Skyy: the full launch in the air): the launch replaces it and the leap runs on (no orb at once)
hrep('''    check(kf == (True, -30.0, True, True, 1, "fired - falling - no hang (fall kept)"),
          "R3 (fall damage rules as the wand hop): falling at 30 b/s the hop keeps the fall (vy -30) and there is no hang - the orb fires at the first tick, "
          "no Set: %s" % (kf,))''', '''    check(kf == (False, 0.0, False, True, 0, "wand leap"),
          "R3 (0.1.18, Skyy: the full launch in the air): falling at 30 b/s the wand launch REPLACES the fall (level look: vy 0, not -30), nothing kept, "
          "the leap runs on (no orb at once, no extra Set on the next tick): %s" % (kf,))
    LP.STATES.clear()          # 0.1.18: that leap still runs (0.1.17: it fired at once) - the checks below start clean''')
# R19d: the real wand leap at a jump's top, straight down: the launch's own up part capped at 15 (0.1.16/17: 9.26 - the jump's rise ate it)
hrep('''    check(up_air == [9.261, 22.0] and up_gnd == 15.0 and up_none == 15.0 and len(hj_) == 1 and abs(hj_[0][0][1] - 9.2612) < 1e-3''',
     '''    check(up_air == [9.261, 22.0] and up_gnd == 15.0 and up_none == 15.0 and len(hj_) == 1 and abs(hj_[0][0][1] - 15.0) < 1e-3          # 0.1.18: 15, the full launch''')
hrep('''"ground / no movement states -> 15; a wand cast looking straight down at a jump's top pushes up 9.26 (one push); the bow leap's hopNow "''',
     '''"ground / no movement states -> 15 (the bow-path helper); a wand cast looking straight down at a jump's top pushes up 15 (0.1.18: the full launch, "
          "its own up part capped - was 9.26; one push); the bow leap's hopNow "''')
hrep('''          and lt19.startswith("wand hold: hop 18.0 (up at most 15.0 b/s, a jump never adds), one hop per cast, hang 0.35 s"),          # 0.1.17: 18''',
     '''          and lt19.startswith("wand hold: launch 18.0 (its up part at most 15.0 b/s, full in the air), one launch per cast, no slow"),          # 0.1.18''')

# ---- P20 (Python): vs the 0.1.17 jar every non-class file is byte-identical, the manifest differs in its version only
P20 = r'''
# ================================================================================================================ P20. 0.1.18: only the classes changed
OZ117 = zipfile.ZipFile(OLD117)
_n20, _o20 = set(JZ15.namelist()), set(OZ117.namelist())
_files20 = sorted(n_ for n_ in _n20 | _o20 if not n_.endswith(".class"))
_diff20 = [n_ for n_ in _files20 if n_ != "manifest.json" and (n_ not in _n20 or n_ not in _o20 or JZ15.read(n_) != OZ117.read(n_))]
_m20n, _m20o = json.loads(JZ15.read("manifest.json").decode("utf-8")), json.loads(OZ117.read("manifest.json").decode("utf-8"))
_m20o2 = dict(_m20o)
_m20o2["Version"] = VERSION
_m20o2["Name"] = str(_m20o.get("Name", "")).replace("0.1.17", VERSION)
check(not _diff20 and _m20n == _m20o2 and _m20o.get("Version") == "0.1.17",
      "P20: vs the 0.1.17 jar every one of the %d non-class files is byte-identical; the manifest differs only in its version (0.1.17 -> %s): %s" % (
          len(_files20), VERSION, _diff20[:5]))
_c20n, _c20o = sorted(n_ for n_ in _n20 if n_.endswith(".class")), sorted(n_ for n_ in _o20 if n_.endswith(".class"))
check(_c20n == _c20o, "P20: the same %d classes (none added / removed): %s" % (len(_c20n), sorted(set(_c20n) ^ set(_c20o))))
print("P20. 0.1.18: %d non-class files identical to 0.1.17, manifest version only, the same %d classes" % (len(_files20), len(_c20n)))
'''
hrep('''print("P19. 0.1.17: %d non-class files identical to 0.1.16, manifest version only, the same %d classes" % (len(_files19), len(_c19n)))
''', '''print("P19. 0.1.17: %d non-class files identical to 0.1.16, manifest version only, the same %d classes" % (len(_files19), len(_c19n)))
''' + P20)

R21 = r'''    # ============================================================================ R21. 0.1.18 THE WAND LAUNCH - every new path EXECUTED
    HM21 = JClass("java.util.HashMap")
    look_keep21 = LP.LOOK

    def setup21(stam=10.0, ground=True, cvy=0.0):          # the REAL 0.1.18 defaults (no pin), the guards + the landing watch on
        fresh19(stam)
        ACfg.useDefaults()
        ACfg.TRAV_FX = False
        AT.LAND_ON = True
        AT.GRID = Grid(world_fn())
        guards19(True, True)
        LP.LOOK = HM21()
        ms_ = MSCc()
        mst_ = MST20()
        mst_.onGround = ground
        ms_.setMovementStates(mst_)
        put(rc, MSCc.getComponentType(), ms_)
        comp(rc, VELc.getComponentType()).setClient(0.0, cvy, 0.0)
        return mst_

    def want21(pitch, force=18.0, maxup=15.0):          # -look x force, only the launch's own up part capped (the look: yaw +x, pitch)
        dx_, dy_ = math.cos(pitch), math.sin(pitch)
        up_ = -dy_ * force
        if maxup > 0 and up_ > maxup:
            up_ = maxup
        return (round(-dx_ * force, 2), round(up_, 2), 0.0)

    def near21(a_, b_):
        return a_ is not None and b_ is not None and all(abs(float(x_) - float(y_)) < 2e-2 for x_, y_ in zip(a_, b_))

    # R21a THE ROWS + DEFAULTS + WORDS + TravMath.launchUp
    setup21()
    Rows21 = JClass(PKG + "CfgRows")
    k21 = [str(k_) for k_ in Rows21.KEYS]
    d21 = dict(zip(k21, [str(d_) for d_ in Rows21.DEFS]))
    h21 = dict(zip(k21, [str(h_) for h_ in Rows21.HELPS]))
    dc21 = str(ACfg.DEF_CFG)
    lt21 = str(br.get("armory:leap"))
    ld21 = (float(ACfg.HOP_HANG), float(ACfg.HOP_AIM), float(ACfg.HOP_MAXUP), float(ACfg.HOP_FORCE))
    pr21 = Props()
    pr21.setProperty("hop.aimDelay", "9")
    ACfg.apply(pr21)
    cl21a = float(ACfg.HOP_AIM)
    pr21.setProperty("hop.aimDelay", "-1")
    ACfg.apply(pr21)
    cl21b = float(ACfg.HOP_AIM)
    ACfg.HOP_AIM = 0.0
    ACfg.HOP_HANG = 0.0
    t21z = str(ACfg.leapText())
    ACfg.HOP_HANG = 0.35
    t21h = str(ACfg.leapText())
    ACfg.useDefaults()
    ACfg.TRAV_FX = False
    lu21 = [round(float(TM.launchUp(a_, b_)), 3) for a_, b_ in ((8.17, 15.0), (22.0, 15.0), (-5.0, 15.0), (30.0, 0.0), (15.0, 15.0), (-18.0, 0.0))]
    check(d21.get("hop.hangSeconds") == "0" and d21.get("hop.aimDelay") == "0.35" and d21.get("hop.maxUp") == "15" and d21.get("hop.force") == "18"
          and k21.index("hop.aimDelay") == k21.index("hop.maxUp") + 1 and max(len(h21["hop.aimDelay"]), len(h21["hop.hangSeconds"]), len(h21["hop.maxUp"]), len(h21["hop.hangFall"])) <= 100
          and h21["hop.hangFall"].startswith("Only used when the slow fall above is more than 0.") and d21.get("hop.hangFall") == "1.5"
          and ld21 == (0.0, 0.35, 15.0, 18.0) and cl21a == 1.5 and cl21b == 0.0
          and "\nhop.hangSeconds=0\n" in dc21 and "\nhop.aimDelay=0.35\n" in dc21 and str(ACfg.M18_MARK) in dc21 and str(ACfg.M17_MARK) in dc21
          and lt21.startswith("wand hold: launch 18.0 (its up part at most 15.0 b/s, full in the air), one launch per cast, no slow - the orb 0.35 s later where you look")
          and "bow full draw: leap 30.0, hang 0.35 s" in lt21 and ", the orb at the cast (no hang)" in t21z and ", hang 0.35 s (drift 1.5 b/s down), then the orb" in t21h
          and lu21 == [8.17, 15.0, -5.0, 30.0, 15.0, -18.0],
          "R21a (Skyy: 'no slow. just the launch'): rows hop.hangSeconds 0 (0.1.17: 0.35), NEW hop.aimDelay 0.35 right after hop.maxUp (helps <= 100), "
          "hop.hangFall says it only acts when the slow fall is above 0 (fixer), "
          "the loader (0 / 0.35 / 15 / 18; aimDelay 9 -> 1.5, -1 -> 0), the default file (+ the 0.1.18 marker), armory:leap words (aim / no-aim / "
          "admin hang), the bow untouched; TravMath.launchUp caps only the launch's own up part: %s | %s | %s" % (ld21, lt21[:150], lu21))

    # R21b ONE VELOCITY WRITE PER CAST through the REAL chain: ArmoryTrav.added (the charged orb's SPAWN) -> Leap.onWandOrb -> begin -> launchNow;
    # Leap.tickPlayer every tick through the aim delay (no write), then the orb from where you are NOW toward where you look NOW
    PITCH21 = -0.4712389          # 27 degrees down (Skyy's log: back 16, up 8.2)
    cases21 = {}
    for name_, ground_, cvy_, pitch_ in (("on the ground", True, 0.0, PITCH21), ("rising after a jump (+8)", False, 8.0, PITCH21),
                                         ("at a jump's top (0)", False, 0.0, PITCH21), ("falling (-10)", False, -10.0, PITCH21),
                                         ("falling fast (-30, would hurt)", False, -30.0, PITCH21), ("straight down at a jump's top", False, 0.0, -1.5707964),
                                         ("level, falling (-12)", False, -12.0, 0.0)):
        mst_ = setup21(ground=ground_, cvy=cvy_)
        TW.ALL.clear()
        o_, p_ = cast19(2300 + len(cases21) * 5, pitch=pitch_)
        ins0_ = instrs19(rc)
        s_ = LP.STATES.get(cu)
        st0_ = None if s_ is None else (int(s_.phase), int(s_.aimMs), bool(s_.armed), int(s_.hangMs))
        tw_ = TW.of(tst)
        armed_ = tw_ is not None and bool(tw_.land.containsKey(cu))
        # the aim delay: 8 ticks (the orb waits, the player flies on - their speed is the client's), no write, no orb
        n_ad = len(list(TBf.ADDED))
        for k_ in range(8):
            LP.tickPlayer(rc, tst, tbuf)
        mid_ = (len(instrs19(rc)), len(list(TBf.ADDED)) - n_ad, LP.STATES.get(cu) is not None)
        # they moved and turned meanwhile: the orb leaves from where they are NOW toward where they look NOW
        at20(rc, -4.5, 66.0, 0.5)
        LP.LOOK.put(cu, JArray(JDouble)([-4.5, 67.6, 0.5, 0.0, 0.0, 1.0]))
        s_.t0 = NOW() - 360
        LP.tickPlayer(rc, tst, tbuf)
        ad_ = list(TBf.ADDED)[n_ad:]
        pc_ = None if not ad_ else ad_[0][0].getComponent(LPCc.getComponentType())
        lv_ = None if pc_ is None else ASp_.launchVelocity(pc_.getSimplePhysicsProvider())
        ts_ = None if not ad_ else TW.of(tst).pend.get(ad_[0][1])
        shot_ = (len(ad_), None if lv_ is None else (round(float(lv_.x()), 3), round(float(lv_.z()), 3) > 1.0),
                 None if ts_ is None else (round(float(ts_.sx), 2), round(float(ts_.sy), 2), round(float(ts_.sz), 2), bool(ts_.land)), str(LP.LAST_WHY))
        for k_ in range(20):
            LP.tickPlayer(rc, tst, tbuf)
        ins_ = instrs19(rc)
        cases21[name_] = {"writes": len(ins_), "launch": ins_[0][0] if ins_ else None, "dash cfg": ins_[0][1] if ins_ else None,
                          "want": want21(pitch_), "state": st0_, "watch armed at the launch": armed_, "aim delay (writes, orbs, waiting)": mid_,
                          "shot": shot_, "after": LP.STATES.get(cu) is None, "stamina": sv(mc, STAM), "first writes": len(ins0_)}
    ok21b = all(v_["writes"] == 1 and v_["first writes"] == 1 and v_["dash cfg"] is True and near21(v_["launch"], v_["want"])
                and v_["state"] == (3, 350, True, 0) and v_["watch armed at the launch"] and v_["aim delay (writes, orbs, waiting)"] == (1, 0, True)
                and v_["shot"][0] == 1 and v_["shot"][1] == (0.0, True) and v_["shot"][2] == (-4.5, 67.6, 1.0, True)
                and v_["shot"][3] == "fired - after the aim delay" and v_["after"] and v_["stamina"] == 5.0 for v_ in cases21.values())
    c21 = cases21
    check(ok21b and near21(c21["on the ground"]["launch"], (-16.04, 8.17, 0.0)) and near21(c21["at a jump's top (0)"]["launch"], (-16.04, 8.17, 0.0))
          and near21(c21["falling fast (-30, would hurt)"]["launch"], (-16.04, 8.17, 0.0)) and near21(c21["straight down at a jump's top"]["launch"], (0.0, 15.0, 0.0))
          and near21(c21["level, falling (-12)"]["launch"], (-18.0, 0.0, 0.0)),
          "R21b (Skyy: 'it still has a double launch' + 'doesnt really launch at all when im in the air'): through the real chain, on the ground / "
          "rising / at a jump's top / falling / falling fast / straight down / level while falling - EXACTLY ONE Velocity instruction per cast (the "
          "launch, dagger dash config) with the FULL numbers (27 degrees down: back 16.04, up 8.17 everywhere - 0.1.17 gave 0 at a jump's top and "
          "kept a -30 fall; straight down: 15 = the cap on its own up part, 0.1.17: 9.26), NONE during 8 aim-delay ticks (the orb waits), then the "
          "orb from where they are NOW (-4.5, 67.6) toward where they look NOW (+z; cast +x), marked for the heal aura; 20 more ticks add nothing; "
          "5 Stamina once: %s" % json.dumps(cases21, default=str))
    # MUTANT hop.hangSeconds 0.35 (the 0.1.17 hang an admin may still set): the per-tick hang writes come back - the check above would see them
    setup21()
    ACfg.HOP_HANG = 0.35
    TW.ALL.clear()
    cast19(2390, pitch=PITCH21)
    sm_ = LP.STATES.get(cu)
    sm_.t0 = NOW() - 1100          # past RISE_MAX (1 s) -> the top -> the hang
    for k_ in range(4):
        LP.tickPlayer(rc, tst, tbuf)
    mut21 = (len(instrs19(rc)), int(sm_.phase), int(sm_.hangTicks))
    LP.STATES.clear()
    ACfg.HOP_HANG = 0.0
    check(mut21[0] == 1 + mut21[2] and mut21[2] >= 3 and mut21[1] == 2,
          "R21b MUTANT hop.hangSeconds 0.35 (= the 0.1.17 hang): 1 launch + %d hang Sets in 4 ticks - the 'double launch' Skyy felt; the default 0 has "
          "none: %s" % (mut21[2], mut21))
    # no look seam (the game path): the orb leaves from the caster's CURRENT feet + 1.6 (TargetUtil.getLook unreadable on the stand-ins)
    setup21()
    LP.LOOK = None
    TW.ALL.clear()
    cast19(2395)
    sn_ = LP.STATES.get(cu)
    at20(rc, 3.5, 70.0, 0.5)
    sn_.t0 = NOW() - 360
    n_ad = len(list(TBf.ADDED))
    LP.tickPlayer(rc, tst, tbuf)
    adn_ = list(TBf.ADDED)[n_ad:]
    tsn_ = None if not adn_ else TW.of(tst).pend.get(adn_[0][1])
    nolook21 = (len(adn_), None if tsn_ is None else (round(float(tsn_.sx), 2), round(float(tsn_.sy), 2), round(float(tsn_.sz), 2)), len(instrs19(rc)))
    check(nolook21[0] == 1 and nolook21[1] is not None and abs(nolook21[1][0] - 3.5) <= 0.51 and abs(nolook21[1][2] - 0.5) <= 0.51
          and 69.4 <= nolook21[1][1] <= 72.2 and nolook21[2] == 1,
          "R21b: without the look seam (the game path TargetUtil.getLook) the orb leaves from where the caster is NOW (moved from 0.5, 64 to 3.5, 70: "
          "within half a block of them, feet to eye), still one write: %s" % (nolook21,))

    # R21c THE HEAL AURA LANDING WATCH from the launch: a landing DURING the aim delay is kept (the orb's fire does not re-arm); the aura there
    NEAR21 = []

    def cast21c(ref_i, keep_armed=True):
        mst_ = setup21(ground=True)
        AT.NEAR = Near20()
        n1_ = npc(ref_i + 1, 12.0, 64.0, 0.5)
        NEARL[:] = [n1_, rc]
        TW.ALL.clear()
        cast19(ref_i, pitch=PITCH21)
        s_ = LP.STATES.get(cu)
        tw_ = TW.of(tst)
        mst_.onGround = False          # in the air
        tw_.run(tst, tbuf, NOW())
        at20(rc, -3.5, 64.0, 0.5)          # ... and down again before the orb fires
        mst_.onGround = True
        tw_.run(tst, tbuf, NOW())
        e_ = tw_.land.get(cu)
        landed_ = None if e_ is None else [round(float(x_), 2) for x_ in list(e_)[3:7]]
        at20(rc, -9.5, 64.0, 0.5)          # walks on; the orb fires now
        if not keep_armed:
            s_.armed = False          # MUTANT: the 0.1.17 fire (re-arms the watch)
        s_.t0 = NOW() - 360
        n_ = len(list(TBf.ADDED))
        LP.tickPlayer(rc, tst, tbuf)
        ad_ = list(TBf.ADDED)[n_:]
        e2_ = tw_.land.get(cu)
        after_ = None if e2_ is None else [round(float(x_), 2) for x_ in list(e2_)[3:7]]
        put(ad_[0][1], LPCc.getComponentType(), ad_[0][0].getComponent(LPCc.getComponentType()))
        put(ad_[0][1], TCc.getComponentType(), TCc(V3(0.5, 66.0, 1.0), R3(0.0, 0.0, 0.0)))
        AT.added(ad_[0][1], ad_[0][0].getComponent(LPCc.getComponentType()), 2002, tst, tbuf)
        reset_buf()
        d_ = DMGc(DPS(rc, ad_[0][1]), DCSc.PROJECTILE, JFloat(88.0))
        d_.putMetaObject(DMGc.HIT_LOCATION, V4(12.0, 65.0, 0.5, 1.0))
        AT.landed(tst, tbuf, d_, ad_[0][1], 2002, n1_)
        aura_ = [(round(float(f_.ax), 2), round(float(f_.ay), 2), round(float(f_.az), 2)) for f_ in heals20(tw_)]
        AT.NEAR = Near()
        return {"landed": landed_, "after the fire": after_, "aura": aura_, "waiting": bool(tw_.landFx.containsKey(cu)), "writes": len(instrs19(rc))}
    lc21 = cast21c(2400)
    lm21 = cast21c(2410, keep_armed=False)
    check(lc21["landed"] == [1.0, -3.5, 64.0, 0.5] and lc21["after the fire"] == [1.0, -3.5, 64.0, 0.5] and lc21["aura"] == [(-3.5, 64.5, 0.5)]
          and not lc21["waiting"] and lc21["writes"] == 1 and lm21["after the fire"] == [0.0, 0.0, 0.0, 0.0] and lm21["aura"] == [] and lm21["waiting"],
          "R21c (0.1.17's heal aura where you land, kept): the watch starts AT THE LAUNCH - up, then down at -3.5 during the aim delay = the landing; "
          "the orb's fire keeps it (LeapState.armed) and the burst puts the aura THERE at once (-3.5, ring 64.5) though they walked on to -9.5; "
          "MUTANT re-arm at the fire (the 0.1.17 order with no hang) = the landing lost, the aura waits for another one: %s | mutant %s" % (lc21, lm21))

    # R21d THE 0.1.2 HOP JOB (hop.aimDelay 0 + hop.hangSeconds 0: the orb at the cast) with the same launch maths, in the air; the BOW unchanged
    hj21 = {}
    for name_, cvy_, ground_ in (("ground", 0.0, True), ("jump top", 0.0, False), ("falling fast (-30)", -30.0, False)):
        setup21(ground=ground_, cvy=cvy_)
        ACfg.HOP_AIM = 0.0
        TW.ALL.clear()
        o_, p_ = cast19(2420 + len(hj21) * 3, pitch=PITCH21)
        orb_kept_ = TW.of(tst).orbs.containsKey(o_) and o_ not in list(TBf.REMOVED) and LP.STATES.get(cu) is None
        for j_ in list(TWd.JOBS):
            j_.run()
        ins_ = instrs19(rc)
        hj21[name_] = (orb_kept_, len(ins_), ins_[0][0] if ins_ else None, str(AT.LAST_WHY), bool(TW.of(tst).land.containsKey(cu)))
    # the bow leap: hopNow keeps a damaging fall (its old rule) and its leap is the 0.1.3 rhythm (phase 1 -> its hang), never the aim phase
    setup21(ground=False, cvy=-30.0)
    bh21 = LP.hopNow(tbuf, rc, JArray(JDouble)([1.0, 0.0, 0.0]), 30.0, 0.0)
    LP.STATES.clear()
    bs21 = LP.begin(2, cu, rc, tst, tbuf, LP.BLAST, int(LP.BLAST_CODE), "Weapon_Shortbow_Crude", 10.0, JArray(JDouble)([1.0, 0.0, 0.0]), 30.0, 0.35, 1.5)
    bs21v = (int(bs21.phase), int(bs21.aimMs), bool(bs21.armed), int(bs21.hangMs), bool(bs21.kept))
    LP.STATES.clear()
    bs21b = LP.begin(2, cu, rc, tst, tbuf, LP.BLAST, int(LP.BLAST_CODE), "Weapon_Shortbow_Crude", 10.0, JArray(JDouble)([1.0, 0.0, 0.0]), 30.0, 0.0, 1.5)
    bs21bv = (int(bs21b.phase), bool(bs21b.armed))
    LP.STATES.clear()
    want_hj = want21(PITCH21)
    check(all(v_[0] and v_[1] == 1 and near21(v_[2], want_hj) and v_[3] == "hop full" and v_[4] for v_ in hj21.values())
          and bh21 is not None and float(bh21[1]) == -30.0 and float(bh21[3]) == 1.0 and bs21v == (1, 0, False, 350, True) and bs21bv == (1, False),
          "R21d: hop.aimDelay 0 + hop.hangSeconds 0 = the 0.1.2 hop job (the orb at the cast) - ONE write with the full launch on the ground, at a "
          "jump's top and in a fast fall (back 16.04, up 8.17), the landing watch armed; the BOW leap unchanged: hopNow keeps a damaging fall (-30), "
          "its leap = the 0.1.3 rhythm (phase 1, its 0.35 s hang; bow.hangSeconds 0 never the wand's aim phase): %s | bow %s %s %s" % (
              json.dumps(hj21), None if bh21 is None else [round(float(x_), 2) for x_ in bh21], bs21v, bs21bv))

    # R21e THE ONE-TIME UPDATE (PROJECT-RULES 4): hop.hangSeconds 0.35 -> 0, its own marker
    MK18 = str(ACfg.M18_MARK)

    def upd18(t_):
        r_ = ACfg.m18Update(t_)
        return None if r_ is None else (str(r_[0]), str(r_[1]), [str(x) for x in r_[2]], [str(x) for x in r_[3]])
    u1 = upd18("a=1\nhop.hangSeconds=0.35\nb=2\n")
    u2 = upd18("a=1\r\nhop.hangSeconds = 0.350\r\n")
    u3 = upd18("hop.hangSeconds=0.5\n")
    u4 = upd18("quick.life=20\n")
    u5 = upd18(u1[0])
    u6 = upd18("hop.hangSeconds=0\n")
    check(u1 == ("a=1\n" + MK18 + "\nhop.hangSeconds=0\nb=2\n", "hop.hangSeconds 0.35 -> 0", [], ["hop.hangSeconds", "0.35", "0"])
          and u2 == ("a=1\r\n" + MK18 + "\r\nhop.hangSeconds = 0\r\n", "hop.hangSeconds 0.350 -> 0", [], ["hop.hangSeconds", "0.350", "0"])
          and u3[0] == MK18 + "\nhop.hangSeconds=0.5\n" and u3[1] == "" and len(u3[2]) == 1 and "kept (custom) - the 0.1.18 default is 0" in u3[2][0]
          and u4 == ("quick.life=20\n" + MK18 + "\n", "", [], []) and u5 is None and u6 == (MK18 + "\nhop.hangSeconds=0\n", "", [], []),
          "R21e (PROJECT-RULES 4): an untouched 0.35 (or 0.350) -> 0 (value text only, CRLF kept, the marker before the line), a hand-set 0.5 KEPT + "
          "noted, no line = the marker only (Skyy's live file: the new default applies), runs once: %s / %s / %s" % (u1, u2, u3))
    mdir18 = os.path.join(SCRATCH, "m18", "mods", "Skyy_SkyyArmory")
    shutil.rmtree(os.path.dirname(os.path.dirname(mdir18)), ignore_errors=True)
    os.makedirs(mdir18)
    mtxt18 = ("# SkyyArmory 0.1.17 test file\r\npart.trav=true\r\n" + str(ACfg.M13_MARK) + "\r\n" + str(ACfg.M14_MARK) + "\r\n" + str(ACfg.M16_MARK) + "\r\n"
              + str(ACfg.M17_MARK) + "\r\nhop.force=18\r\nhop.hangSeconds=0.35\r\nhop.hangFall=1.5\r\nquick.life=20\r\n").encode("latin-1")
    open(os.path.join(mdir18, "config.properties"), "wb").write(mtxt18)
    ACfg.DIR = Paths.get(mdir18)
    ACfg.FILE = ACfg.DIR.resolve("config.properties")
    mr18 = [str(ACfg.migrate013()), str(ACfg.migrate014()), str(ACfg.migrate016()), str(ACfg.migrate017())]          # setup() order (idle here)
    mr18a = str(ACfg.migrate018())
    af18 = open(os.path.join(mdir18, "config.properties"), "rb").read()
    hist18 = os.path.join(mdir18, "config-history")
    baks18 = sorted(f_ for f_ in os.listdir(hist18) if f_.endswith(".bak")) if os.path.isdir(hist18) else []
    bak18 = open(os.path.join(hist18, baks18[-1]), "rb").read() if baks18 else b""
    log18 = open(os.path.join(mdir18, "config-changes.log"), "rb").read().decode("latin-1") if os.path.isfile(os.path.join(mdir18, "config-changes.log")) else ""
    mr18b = str(ACfg.migrate018())
    af18b = open(os.path.join(mdir18, "config.properties"), "rb").read()
    ACfg.load()
    ld18 = (float(ACfg.HOP_HANG), float(ACfg.HOP_AIM))
    chain18 = {}
    for name_, body_ in (("0.1.17 file (0.35)", b"part.trav=true\nhop.force=22\nhop.hangSeconds=0.35\n"), ("hand-set 0.6", b"hop.hangSeconds=0.6\n"),
                         ("no line", b"part.trav=true\n")):
        open(os.path.join(mdir18, "config.properties"), "wb").write(body_)
        ACfg.migrate013()
        ACfg.migrate014()
        ACfg.migrate016()
        ACfg.migrate017()
        ACfg.migrate018()
        t_ = open(os.path.join(mdir18, "config.properties"), "rb").read().decode("latin-1")
        chain18[name_] = sorted(l_ for l_ in t_.split("\n") if l_.startswith(("hop.", "# SkyyArmory 0.1.18")))
    ACfg.DIR = None
    ACfg.FILE = None
    ACfg.useDefaults()
    check(mr18 == ["", "", "", ""] and af18 == upd18(mtxt18.decode("latin-1"))[0].encode("latin-1") and b"hop.hangSeconds=0\r\n" in af18
          and b"hop.hangFall=1.5\r\n" in af18 and baks18 and bak18 == mtxt18
          and "\tSkyyArmory 0.1.18\t-\tupdate\thop.hangSeconds\t0.35\t0\tok" in log18
          and "hop.hangSeconds 0.35 -> 0" in mr18a and mr18b == "" and af18b == af18 and ld18 == (0.0, 0.35)
          and chain18 == {"0.1.17 file (0.35)": [MK18, "hop.force=18", "hop.hangSeconds=0"], "hand-set 0.6": [MK18, "hop.hangSeconds=0.6"], "no line": [MK18]},
          "R21e (the real ArmoryCfg.migrate018 on a scratch file, after migrate013 / 014 / 016 / 017 like setup()): History copy = the old bytes, an "
          "Undo-able change-log line, CRLF kept, the second run idle, the loader reads 0 / 0.35; a 0.1.17 file 22 / 0.35 -> 18 / 0 in one start, a "
          "hand-set 0.6 kept: %s | %s | %s" % (mr18a[:140], log18.strip()[-70:], chain18))

    # R21f vs the 0.1.17 jar METHOD BY METHOD
    MN21, MO21 = methods_of(JAR), methods_of(OLD117)
    cmp21 = {}
    for c_ in sorted(set(MN21) | set(MO21)):
        if c_ not in MN21 or c_ not in MO21:
            cmp21[c_] = "only in " + ("0.1.18" if c_ in MN21 else "0.1.17")
            continue
        ch_ = sorted(k_ for k_ in set(MN21[c_][0]) | set(MO21[c_][0]) if MN21[c_][0].get(k_) != MO21[c_][0].get(k_))
        fd_ = sorted(set(MN21[c_][1]) ^ set(MO21[c_][1]))
        if ch_ or fd_:
            cmp21[c_] = {"methods": [k_.split("(")[0] for k_ in ch_], "fields": [f_.split(":")[0] for f_ in fd_]}
    plan21 = {"ArmoryTrav": ({"hop", "added"}, set()),
              "Leap": ({"launchNow", "begin", "fire", "tickPlayer", "ownShot"}, set()),
              "LeapState": (set(), {"aimMs", "armed"}),
              "TravMath": ({"launchUp"}, set()),
              "ArmoryCfg": ({"m18Key", "m18Update", "m18Log", "migrate018", "load", "apply", "leapText", "useDefaults", "reloadAll"},
                            {"HOP_AIM", "M18_KEY1", "M18_OLD1", "M18_NEW1", "M18_MARK", "M18_MARK_ID", "M18_WHO", "M18_LAST"}),
              "SkyyArmoryPlugin": ({"setup"}, set())}
    bad21 = {}
    for c_, v_ in cmp21.items():
        if c_ in plan21 and isinstance(v_, dict) and set(v_["methods"]) <= plan21[c_][0] and set(v_["fields"]) <= plan21[c_][1]:
            continue
        bad21[c_] = v_
    check(not bad21 and "launchNow" in cmp21.get("Leap", {}).get("methods", []) and "tickPlayer" in cmp21.get("Leap", {}).get("methods", [])
          and "launchUp" in cmp21.get("TravMath", {}).get("methods", []) and "migrate018" in cmp21.get("ArmoryCfg", {}).get("methods", [])
          and "hop" in cmp21.get("ArmoryTrav", {}).get("methods", []),
          "R21f: 0.1.17 -> 0.1.18 METHOD BY METHOD - only the planned methods / fields differ (the launch, the aim phase, the routing, the row + "
          "migrate018, the plugin's setup): %s" % json.dumps(bad21)[:1500])
    print("R21f. vs 0.1.17 method by method: %s" % json.dumps(cmp21)[:1800])
    LP.LOOK = look_keep21
    AT.LAND_ON = True
    ACfg.useDefaults()
    TW.ALL.clear()
    reset_buf()
    LP.STATES.clear()
    put(rc, MSCc.getComponentType(), None)
    at20(rc, 0.5, 64.0, 0.5)
    comp(rc, VELc.getComponentType()).setClient(0.0, 0.0, 0.0)
    print("R21. 0.1.18 wand launch: rows + words + launchUp, ONE write per cast on the ground / rising / top / falling / fast fall / straight down "
          "(none in the aim delay, the orb from the current spot + look), mutant hang, the landing watch from the launch (+ mutant), the 0.1.2 hop "
          "job + the bow unchanged, migrate018, the 0.1.17 compare")
'''
hrep('''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''',
     R21 + '''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''')

out_t = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(out_t)
print("wrote %s" % os.path.relpath(TDST, ROOT))
