"""Derive SkyyArmory/build_skyyarmory_0.1.15.py (+ its harness SkyyArmory/test_skyyarmory_0.1.15.py) from the GENERATED 0.1.14
(SkyyArmory/build_skyyarmory_0.1.14.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_14_patch.py; test_skyyarmory_0.1.14.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_15_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.15.py   then
      python SkyyArmory/test_skyyarmory_0.1.15.py --dir tools/dev/scratch/<task>/harness      (never --deploy)

0.1.15 = THE THREE ARMORY UNTIERED ITEMS (phase G2, research/cloud/UT-First-Batch-Build.md sections 1 + 4; Skyy: "UT weapons and armor are only
mob drops and chest loot (bosses can drop them too.)" + "but you cant craft them." + "they can come from quests, but not shops."). SkyyGear
0.2.16 owns the Untiered table, the orange bags and every number; this jar ships the three items made from its own Iron items and the two
tricks that live in its own code. No saved data, no new setting, no migration.
  ITEMS (built at build time from the jar's own FINAL Iron item files - every Iron behaviour comes along: codes, Mana, blink / hop / burst /
    heal orb, the wand signature, the Bo moves and the guard; Recipe REMOVED - the engine reads Recipe with append, not appendInherited, so
    nothing inherits one; Variant true; own name + description; the Iron texture + icon recoloured ORANGE at build time as a placeholder):
    Weapon_Staff_UT_Loophole (U1, Mage), Weapon_Wand_UT_SecondOpinion (U6, Priest), Weapon_Bo_UT_Turnstile (U7, Monk). They are in the pack
    check (ITEM_CHECK_IDS: 54 items). armory:fn:info answers for them as their Iron base (SkyyGear's shot lines, SkyyClasses' heal caps).
  U1 PIERCE: a staff QUICK shot (code 3000s) fired while the Loophole is in hand pierces like a wand quick shot (the same continuation chain,
    the same pierce.max rule - no cap by default - and the same walls / range); a normal staff quick shot is unchanged.
  U6 HEAL: a wand CHARGED orb fired with the Second Opinion heals from the damage BEFORE the item's own damage cut (SkyyGear's -40 % lands
    first: 1.5 x 0.6 = a weaker heal - the trap the spec found): heal base = landed / (1 + dmg %) x (1 + heal %) = landed x 2.5 by default ->
    exactly 1.5 x an Iron wand's heal at the same level. Both numbers come from SkyyGear (gear:fn:utfx {id, "dmg" / "heal" / "pierce"});
    without SkyyGear 0.2.16 the items are plain Iron copies (pierce 0, heal 0).
  U7 KNOCKBACK x2 is SkyyGear's (its hit system scales the hit's knockback like a speed tier) - nothing here.
ROLLBACK (reported, not edited): below 0.1.15 the three ids are unknown items (treat as lost) - roll SkyyArmory back only together with SkyyGear
0.2.15, after the Untiered rows of these three ids are removed (no new ones made).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.14.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.15.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.14.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.15.py")

CR, LF = chr(13), chr(10)
raw = open(SRC, encoding="utf8", newline="").read()
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.14"\nMOD = "SkyyArmory"' in s and "0.1.14 = THE WAND SIGNATURE" in s, "build_skyyarmory_0.1.14.py is not the 0.1.14 pin"
assert "UT_Loophole" not in s and "utPierce" not in s, "0.1.14 already has the 0.1.15 parts"


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# ---------------------------------------------------------------------------------------------------------------- header + version
rep('''"""SkyyArmory 0.1.14 - build script (javassist via jpype). GENERATED by tools/armory_0_1_14_patch.py from the GENERATED 0.1.13 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.14.py -> SkyyArmory/SkyyArmory-0.1.14.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.14.py --dir tools/dev/scratch/<task>/harness.
''', '''"""SkyyArmory 0.1.15 - build script (javassist via jpype). GENERATED by tools/armory_0_1_15_patch.py from the GENERATED 0.1.14 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.15.py -> SkyyArmory/SkyyArmory-0.1.15.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.15.py --dir tools/dev/scratch/<task>/harness.

0.1.15 = THE THREE ARMORY UNTIERED ITEMS (phase G2; full notes in tools/armory_0_1_15_patch.py): Weapon_Staff_UT_Loophole, Weapon_Wand_UT_
SecondOpinion and Weapon_Bo_UT_Turnstile = copies of the jar's own final Iron staff / wand / Bo (no recipe, hidden from creative, orange
placeholder look) - SkyyGear 0.2.16 makes them Untiered and drops them from orange bags; the Loophole's staff quick shots pierce like wand quick
shots; the Second Opinion's heal orb heals from the damage before its own cut (x (1 + heal %) / (1 + dmg %), SkyyGear's numbers through
gear:fn:utfx); armory:fn:info answers for them as Iron.

0.1.14 (the base, everything below is still true unless 0.1.15 above says otherwise):
''')
rep('VERSION = "0.1.14"\nMOD = "SkyyArmory"', 'VERSION = "0.1.15"\nMOD = "SkyyArmory"')

# ---------------------------------------------------------------------------------------------------------------- the three item copies
rep('''ITEM_CHECK_IDS = sorted(ITEMS)                      # 0.1.3: + the 2 crossbows (ITEMS grew after the closure)''',
    '''# ================================================================= 0.1.15 THE THREE ARMORY UNTIERED ITEMS (tools/armory_0_1_15_patch.py): copies of the jar's own FINAL
# Iron staff / wand / Bo (every later change of those three files is already in ITEMS here: the 0.1.14 signature, the 0.1.11 Bo chain)
UT_ITEMS = [("Weapon_Staff_UT_Loophole", "Weapon_Staff_Iron", P_SITEM % "UT_Loophole", "The Loophole",
             "Untiered staff. Quick shots pierce every enemy in a line. 30% less damage."),
            ("Weapon_Wand_UT_SecondOpinion", "Weapon_Wand_Iron", P_WITEM % "UT_SecondOpinion", "The Second Opinion",
             "Untiered wand. Your heal orb heals 50% more. Wand shots deal 40% less damage."),
            ("Weapon_Bo_UT_Turnstile", "Weapon_Bo_Iron", P_BOITEM % "UT_Turnstile", "The Turnstile",
             "Untiered bo staff. Every hit knocks enemies back twice as far. 25% less damage.")]
UT_RAMP = tuple(tuple(int(h_[k_:k_ + 2], 16) for k_ in (1, 3, 5)) for h_ in ("#7a4300", "#e08a00", "#ffd27a"))     # SkyyGear's orange bag ramp
UT_FILES = []
UT_LANG = []
# the engine's Item codec reads "Recipe" with append (not appendInherited): a copy without a recipe never inherits one (bytecode-checked)
import jpype as _jp
_icls = "com.hypixel.hytale.server.core.asset.type.item.config.Item"
_ib = _jp.JClass("java.io.ByteArrayOutputStream")()
_jp.JClass("javassist.bytecode.InstructionPrinter")(_jp.JClass("java.io.PrintStream")(_ib)).print_(pool.get(_icls).getClassInitializer().toMethod("clinitx", pool.get(_icls)))
_il = str(_ib.toString()).split("\\n")
_ri = [_k for _k, _x in enumerate(_il) if '= "Recipe"' in _x]
assert len(_ri) == 1 and [_x for _x in _il[_ri[0]:_ri[0] + 12] if "AssetBuilderCodec$Builder.append" in _x and "appendInherited" not in _x], \\
    "the Item codec's Recipe is inherited now - a copy without a recipe could inherit its Parent's"
for _uid, _bid, _up, _nm, _ds in UT_ITEMS:
    assert _bid in ITEMS and _uid not in ITEMS and not az_has("item", _uid), (_uid, _bid)
    _it = json.loads(json.dumps(ITEMS[_bid]))
    _it.pop("Recipe", None)
    _it["TranslationProperties"] = {"Name": "server.items.%s.name" % _uid, "Description": "server.items.%s.description" % _uid}
    _it["Variant"] = True
    _tx0, _ic0 = _it.get("Texture"), _it.get("Icon")
    assert _tx0 and _ic0, _bid
    _txb = ASSETS.get("Common/" + _tx0) if ("Common/" + _tx0) in ASSETS else AZ.read("Common/" + _tx0)
    _icb = ASSETS.get("Common/" + _ic0) if ("Common/" + _ic0) in ASSETS else AZ.read("Common/" + _ic0)
    _it["Texture"] = "Items/SkyyArmory/UT/%s.png" % _uid
    _it["Icon"] = "Icons/ItemsGenerated/%s.png" % _uid
    ASSETS["Common/" + _it["Texture"]] = SA.recolor(_txb, UT_RAMP, rank=0.35)
    ASSETS["Common/" + _it["Icon"]] = SA.recolor_icon(_icb, UT_RAMP, rank=0.35)
    UT_FILES += [_up, "Common/" + _it["Texture"], "Common/" + _it["Icon"]]
    assert "Recipe" not in _it
    ITEMS[_uid] = _it
    put(_up, _it)
    UT_LANG += ["items.%s.name = %s" % (_uid, _nm), "items.%s.description = %s" % (_uid, _ds)]
assert all("," not in _x for _x in UT_LANG)
ASSETS[P_LANG] = ASSETS[P_LANG] + "\\n".join(UT_LANG) + "\\n"
print("0.1.15 Untiered items: %s (copies of %s; %d files, orange placeholder art)" % (", ".join(u[0] for u in UT_ITEMS), ", ".join(u[1] for u in UT_ITEMS), len(UT_FILES)))
ITEM_CHECK_IDS = sorted(ITEMS)                      # 0.1.3: + the 2 crossbows (ITEMS grew after the closure); 0.1.15: + the 3 Untiered items''')

# ---------------------------------------------------------------------------------------------------------------- Java: defs, shot fields
rep('''for f in ("public static final String RICO_MARK = %s;" % jstr(RICO_MARK), "public static final int RICO_CODE = %d;" % RICO_CODE,
          "public static final int SIG_MAX = %d;" % SIG_MAX):          # 0.1.14 the wand signature
    F(dfs, f)''', '''for f in ("public static final String RICO_MARK = %s;" % jstr(RICO_MARK), "public static final int RICO_CODE = %d;" % RICO_CODE,
          "public static final int SIG_MAX = %d;" % SIG_MAX):          # 0.1.14 the wand signature
    F(dfs, f)
for f in ("public static final String[] UT_IDS = %s;" % jarr([u[0] for u in UT_ITEMS]),          # 0.1.15 the three Untiered items
          "public static final String[] UT_BASE = %s;" % jarr([u[1] for u in UT_ITEMS])):
    F(dfs, f)
# 0.1.15: an Untiered copy -> its Iron base (armory:fn:info); anything else -> itself
M(dfs, r"""
public static String utBase(String id) {
  if (id == null) return null;
  for (int i = 0; i < UT_IDS.length; i++) if (UT_IDS[i].equals(id)) return UT_BASE[i];
  return id;
}""")''')
rep('''          "public double base;"):          # 0.1.3: the bow's full-draw damage a blast arrow deals (0 = none)
    F(tshot, f)''', '''          "public double base;",          # 0.1.3: the bow's full-draw damage a blast arrow deals (0 = none)
          "public boolean utPierce;",     # 0.1.15: a staff quick shot of the Loophole (pierces like a wand quick shot)
          "public double utHeal;", "public double utDmg;"):          # 0.1.15: the Second Opinion's heal % / damage % (SkyyGear's numbers)
    F(tshot, f)''')
rep('''  @PKG@.TravShot n = new @PKG@.TravShot(this.sx, this.sy, this.sz, this.range, this.code, this.caster, this.pid);
  n.hits = this.hits;
  n.count = this.count;
  return n;''', '''  @PKG@.TravShot n = new @PKG@.TravShot(this.sx, this.sy, this.sz, this.range, this.code, this.caster, this.pid);
  n.hits = this.hits;
  n.count = this.count;
  n.utPierce = this.utPierce;          // 0.1.15
  return n;''')

# ---------------------------------------------------------------------------------------------------------------- Java: the two tricks
rep('''# ---- ArmoryTravSys.onEntityAdded (SPAWN of one of our projectiles): quick orbs -> range / pierce record; wand charged orb -> burst''',
    '''# ---- 0.1.15 the Untiered tricks: SkyyGear's number for an item (gear:fn:utfx {id, word} -> Double; 0 = none / no SkyyGear 0.2.16)
M(trav, r"""
public static double utfx(String id, String word) {
  if (id == null || word == null) return 0.0;
  try {
    Object f = @PKG@.ArmoryTree.bridge().get("gear:fn:utfx");
    if (!(f instanceof java.util.function.Function)) return 0.0;
    Object r = ((java.util.function.Function) f).apply(new Object[] { id, word });
    if (!(r instanceof Number)) return 0.0;
    double v = ((Number) r).doubleValue();
    return Double.isNaN(v) || Double.isInfinite(v) ? 0.0 : v;
  } catch (Throwable t) { return 0.0; }
}""")
# the heal base of an Untiered wand's orb: the landed damage before the item's own cut x (1 + heal %) (pure)
M(trav, r"""
public static double utHealBase(double landed, double dmgPct, double healPct) {
  double f = 1.0 + dmgPct / 100.0;
  if (f < 0.05) f = 0.05;
  double h = 1.0 + healPct / 100.0;
  if (h < 0.0) h = 0.0;
  return landed / f * h;
}""")
# the item in the caster's hand at the spawn (the Leap hand seam in the harness)
M(trav, r"""
public static String casterHand(@CB@ buf, java.util.UUID cu) {
  if (cu == null) return null;
  return @PKG@.Leap.hand(buf, @PKG@.Leap.refOf(buf, cu), cu);
}""")
M(trav, r"""
public static void utMark(@PKG@.TravShot s, @CB@ buf, java.util.UUID cu, int c) {
  if (s == null || cu == null) return;
  String h = casterHand(buf, cu);
  if (h == null) return;
  if (c >= 3000 && c < 4000 && utfx(h, "pierce") > 0.0) s.utPierce = true;
  if (c >= 2000 && c < 3000) {
    double hl = utfx(h, "heal");
    if (hl != 0.0) { s.utHeal = hl; s.utDmg = utfx(h, "dmg"); }
  }
}""")

# ---- ArmoryTravSys.onEntityAdded (SPAWN of one of our projectiles): quick orbs -> range / pierce record; wand charged orb -> burst''')
rep('''    @PKG@.TravShot s = (@PKG@.TravShot) tw.pend.remove(ref);
    if (s == null) {
      if (p == null) return;
      s = new @PKG@.TravShot(p.x, p.y, p.z, (double) (c < 2000 ? @PKG@.ArmoryCfg.RANGE_WAND : @PKG@.ArmoryCfg.RANGE_STAFF), c, cu, pid);
    }
    tw.quick.put(ref, s);
    return;''', '''    @PKG@.TravShot s = (@PKG@.TravShot) tw.pend.remove(ref);
    if (s == null) {
      if (p == null) return;
      s = new @PKG@.TravShot(p.x, p.y, p.z, (double) (c < 2000 ? @PKG@.ArmoryCfg.RANGE_WAND : @PKG@.ArmoryCfg.RANGE_STAFF), c, cu, pid);
      if (c >= 3000) utMark(s, buf, cu, c);          // 0.1.15: a Loophole staff quick shot pierces (a continuation keeps the flag)
    }
    tw.quick.put(ref, s);
    return;''')
rep('''    tw.orbs.put(ref, new @PKG@.TravShot(p == null ? 0.0 : p.x, p == null ? 0.0 : p.y, p == null ? 0.0 : p.z, 0.0, c, cu, pid));
    if (lp != null) return;''', '''    @PKG@.TravShot ws = new @PKG@.TravShot(p == null ? 0.0 : p.x, p == null ? 0.0 : p.y, p == null ? 0.0 : p.z, 0.0, c, cu, pid);
    utMark(ws, buf, cu, c);          // 0.1.15: the Second Opinion's heal numbers
    tw.orbs.put(ref, ws);
    if (lp != null) return;''')
rep('''    double[] h = hitAt(d, buf, tg);
    if (h == null) return;
    burst(st, buf, pj, s, h[0], h[1], h[2], tg, (double) d.getInitialAmount(), (double) d.getAmount());
    return;
  }
  if (c < 1000 || c >= 2000) return;
  @PKG@.TravShot s = (@PKG@.TravShot) tw.quick.get(pj);
  if (s == null || s.caster == null) return;''', '''    double[] h = hitAt(d, buf, tg);
    if (h == null) return;
    double hb = (double) d.getAmount();
    if (s.utHeal != 0.0) hb = utHealBase(hb, s.utDmg, s.utHeal);          // 0.1.15: the Second Opinion heals from the damage before its own cut
    burst(st, buf, pj, s, h[0], h[1], h[2], tg, (double) d.getInitialAmount(), hb);
    return;
  }
  if (!((c >= 1000 && c < 2000) || (c >= 3000 && c < 4000))) return;          // 0.1.15: + staff quick shots (the Loophole only, below)
  @PKG@.TravShot s = (@PKG@.TravShot) tw.quick.get(pj);
  if (s == null || s.caster == null) return;
  if (c >= 3000 && !s.utPierce) return;''')
rep('''    String kind = String.valueOf(a[0]);
    String id = String.valueOf(a[1]);
    if (kind.equals("wand")) {''', '''    String kind = String.valueOf(a[0]);
    String id = @PKG@.ArmoryDefs.utBase(String.valueOf(a[1]));          // 0.1.15: an Untiered copy answers as its Iron base
    if (kind.equals("wand")) {''')

# ---------------------------------------------------------------------------------------------------------------- the SkyySkills Wood wand anchor
# the pinned SkyySkills (0.4.29) now names the 0.1.14 wand signature root as the Wood wands' Ability1 (the "Wood signature goes live" step the
# 0.1.14 notes waited for) - the anchor accepts exactly that one extra key (Primary / Secondary must still be Wand_Primary)
rep('''            assert d["Interactions"] == {"Primary": "Wand_Primary", "Secondary": "Wand_Primary"}, (iid, d["Interactions"])''',
    '''            _wi = dict(d["Interactions"])
            if _wi.get("Ability1") == "SkyyArmory_Wand_Signature":          # 0.1.15: SkyySkills 0.4.29+ gives the Wood wands the signature key
                _wi.pop("Ability1")
            assert _wi == {"Primary": "Wand_Primary", "Secondary": "Wand_Primary"}, (iid, d["Interactions"])''')

# ---------------------------------------------------------------------------------------------------------------- jar checks + prints
rep('''    _sitems = sorted(n for n in _names if n.startswith("Server/Item/Items/Weapon/Staff/"))
    assert _sitems == sorted([P_SITEM % m for m in METALS] + [VBO_OVR[i][0] for i in VBO_IDS if VBO_OVR[i][0].startswith("Server/Item/Items/Weapon/Staff/")]), \\''',
    '''    _sitems = sorted(n for n in _names if n.startswith("Server/Item/Items/Weapon/Staff/") and n != P_SITEM % "UT_Loophole")          # 0.1.15: + the Loophole (checked below)
    assert sorted(n for n in _names if n in set(UT_FILES)) == sorted(UT_FILES) and len(UT_FILES) == 9, "0.1.15: the 3 Untiered items + their 6 art files"
    assert _sitems == sorted([P_SITEM % m for m in METALS] + [VBO_OVR[i][0] for i in VBO_IDS if VBO_OVR[i][0].startswith("Server/Item/Items/Weapon/Staff/")]), \\''')
rep('''print("0.1.14 wand signature: %d rows (Server Setup > Armory > Wand + signature, sig.wand.*) + 1 read-only row; meter %d on %d wands; marker %s "''',
    '''print("0.1.15 Untiered items: %s; Loophole staff quick shots pierce, Second Opinion heals from the pre-cut damage (gear:fn:utfx), "
      "armory:fn:info answers as Iron" % ", ".join(u[0] for u in UT_ITEMS))
print("0.1.14 wand signature: %d rows (Server Setup > Armory > Wand + signature, sig.wand.*) + 1 read-only row; meter %d on %d wands; marker %s "''')

with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(s.replace(LF, NL))
print("wrote %s" % os.path.relpath(DST, ROOT))

# ================================================================================================================ the harness
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.14 - test harness. GENERATED by tools/armory_0_1_14_patch.py from test_skyyarmory_0.1.13.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.15 - test harness. GENERATED by tools/armory_0_1_15_patch.py from test_skyyarmory_0.1.14.py - edit the patch, never this file.
Run: python SkyyArmory/test_skyyarmory_0.1.15.py --dir tools/dev/scratch/<task>/harness   (--no-set skips the one-JVM SET run, --keep keeps it)
Every 0.1.14 check still runs on the 0.1.14 shape: JZ15 = the real 0.1.15 jar; JZ = the jar AS THE 0.1.14 CHECKS KNOW IT - the 3 Untiered items
+ their 6 pictures hidden, the lang read as the 0.1.14 jar's bytes (P17 proves the real files are exactly the planned change); the classes are
the real 0.1.15 ones; R17g now compares 0.1.13 -> 0.1.14 (history), R18g 0.1.14 -> 0.1.15. The pack check counts the 3 items (54).
NEW P17 (Python) + R18 (JVM, after R17) EXECUTE every 0.1.15 path:
  P17  the 3 items = the jar's own final Iron staff / wand / Bo JSON with ONLY the planned keys changed (no Recipe, Variant, own name, the
       orange texture + icon - valid PNGs that shadow nothing); MUTANT: a copy that kept a Recipe fails the same check; the lang = 0.1.14's +
       6 lines; vs the 0.1.14 jar: only these 9 files added, only the lang changed
  R18  a: THE ENGINE ASSET VALIDATORS on the 3 items, in the store from our pack, no recipe to generate (control: the Iron staff has one);
       b: armory:fn:info answers for them exactly as for the Iron base (staff + wand), utBase; c: the heal maths (pre-cut base: Iron 100 =
       60 landed after -40 % -> 150; MUTANT: the landed-damage heal 90 = 0.9 x - the trap); d: gear:fn:utfx read (absent = 0); e: THE PIERCE
       through ArmoryTrav.added -> landed on the stand-ins: a Loophole staff quick shot pierces (continuation, flag kept), an Iron staff quick
       shot / no SkyyGear does not; f: THE HEAL through added -> landed: the Second Opinion's heal orb heals 20 % of 150 = 30 a tick, the
       Iron wand's 20 % of 60 = 12 (1.5 x the Iron wand at its own 100 landed); g: vs the 0.1.14 jar method by method.

0.1.14 harness: SkyyArmory 0.1.14 - test harness. GENERATED by tools/armory_0_1_14_patch.py from test_skyyarmory_0.1.13.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.14"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.14 SkyyArmory"',
     'VERSION = "0.1.15"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.15 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory0114", "harness")', 'os.path.join(SCRATCH_ROOT, "ut02", "harness")')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.14.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.15.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.14"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.15"))')
hrep('"[SkyyArmory] 0.1.14 ready" in m_', '"[SkyyArmory] 0.1.15 ready" in m_')
hrep('"0.1.14 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_', '"0.1.15 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_')
hrep('"0.1.14 crossbow grapple: grapple on" in m_', '"0.1.15 crossbow grapple: grapple on" in m_')
hrep('"0.1.14 monk moves on - Pole-Vault (Bo hold): lunge 3 in 0.2 s, 4.5 up x 7 forward (push x2.1)" in m_',
     '"0.1.15 monk moves on - Pole-Vault (Bo hold): lunge 3 in 0.2 s, 4.5 up x 7 forward (push x2.1)" in m_')
hrep('"0.1.14 wand signature on - the signature key when the meter is full (20; quick-shot hit +1, charged hit +2)" in m_',
     '"0.1.15 wand signature on - the signature key when the meter is full (20; quick-shot hit +1, charged hit +2)" in m_')
hrep('"51 of 51 items, 358 of 358 interactions, 66 of 66 projectiles, 1 of 1 roots (the crossbow right click) come from Skyy:0.1.14 SkyyArmory" in str(r[1])',
     '"54 of 54 items, 358 of 358 interactions, 66 of 66 projectiles, 1 of 1 roots (the crossbow right click) come from Skyy:0.1.15 SkyyArmory" in str(r[1])')
hrep('''t_.replace("0.1.14", "V").replace("0.1.13", "V")''', '''t_.replace("0.1.15", "V").replace("0.1.14", "V").replace("0.1.13", "V")''')
hrep('''    MN17, MO17 = methods_of(JAR), methods_of(OLD113)''', '''    MN17, MO17 = methods_of(OLD114), methods_of(OLD113)          # 0.1.15: R17g = the 0.1.14 round's compare (history); R18g = 0.1.14 -> 0.1.15''')

# ---- the jar as the 0.1.14 checks know it
hrep('''JZ = zipfile.ZipFile(JAR)
# 0.1.14: JZ14 = the real 0.1.14 jar (P16 / R17);''', '''JZ = zipfile.ZipFile(JAR)
# 0.1.15: JZ15 = the real 0.1.15 jar (P17 / R18); from here on JZ is the jar AS THE 0.1.14 CHECKS KNOW IT: the 3 Untiered items + their 6
# pictures hidden, the lang read as the 0.1.14 jar's bytes (P17 proves the real files are exactly the planned change); classes + manifest = real
JZ15 = JZ
OLD114 = os.path.join(HERE, "SkyyArmory-0.1.14.jar")
if not os.path.isfile(OLD114):
    raise SystemExit("the 0.1.15 harness needs SkyyArmory-0.1.14.jar (the base, the SET pin) next to it: %s" % OLD114)
OZ114 = zipfile.ZipFile(OLD114)
UT15_IDS = ["Weapon_Staff_UT_Loophole", "Weapon_Wand_UT_SecondOpinion", "Weapon_Bo_UT_Turnstile"]
UT15_BASE = dict(zip(UT15_IDS, ["Weapon_Staff_Iron", "Weapon_Wand_Iron", "Weapon_Bo_Iron"]))
UT15_ITEMS = dict(zip(UT15_IDS, ["Server/Item/Items/Weapon/Staff/Weapon_Staff_UT_Loophole.json", "Server/Item/Items/Weapon/Wand/Weapon_Wand_UT_SecondOpinion.json",
                                 "Server/Item/Items/Weapon/Bo/Weapon_Bo_UT_Turnstile.json"]))
UT15_ART = sorted(["Common/Items/SkyyArmory/UT/%s.png" % i_ for i_ in UT15_IDS] + ["Common/Icons/ItemsGenerated/%s.png" % i_ for i_ in UT15_IDS])
UT15_NEW = sorted(list(UT15_ITEMS.values()) + UT15_ART)
UT15_LANG = "Server/Languages/en-US/server.lang"


class Z114(object):
    """the 0.1.15 jar as the 0.1.14 checks know it (read only)"""
    def __init__(self, real, old, hide, oldfiles):
        self.real, self.old, self.hide, self.oldfiles = real, old, set(hide), set(oldfiles)

    def namelist(self):
        return [n_ for n_ in self.real.namelist() if n_ not in self.hide]

    def read(self, n_):
        if n_ in self.hide:
            raise KeyError(n_)
        return self.old.read(n_) if n_ in self.oldfiles else self.real.read(n_)

    def close(self):
        self.real.close()
        self.old.close()


JZ = Z114(JZ15, OZ114, UT15_NEW, [UT15_LANG])
# 0.1.14: JZ14 = the real 0.1.14 jar (P16 / R17);''')

# ---- the two P7 anchors on SkyySkills' numbers drifted (the 0.1.14 harness fails them too with today's pin): SkyySkills 0.4.25's class power
# split moved the class bases (Priest 30 -> 42, Mage 30 -> 45; research/Class-Power-Split.md); the per-level rows (Priest 5, Mage 10) and the
# 40 % rule are unchanged - the anchors follow the pinned jar (the 40 % rule per metal is still checked right below them)
hrep('''    check(D15.get("mana.classPerLevel.Priest") == "5" and D15.get("mana.classPerLevel.Mage") == "10" and D15.get("mana.classBase.Priest") == "30"
          and D15.get("mana.classBase.Mage") == "30", "P7 (ST9): %s SkyySkills %s default text: Max Mana per class level Priest 5, Mage 10 (base 30)" % (''',
     '''    _cb7 = ("42", "45") if vtuple(SKILLS_PIN) >= vtuple("0.4.25") else ("30", "30")          # 0.1.15: SkyySkills 0.4.25's class power split
    check(D15.get("mana.classPerLevel.Priest") == "5" and D15.get("mana.classPerLevel.Mage") == "10" and D15.get("mana.classBase.Priest") == _cb7[0]
          and D15.get("mana.classBase.Mage") == _cb7[1], "P7 (ST9): %s SkyySkills %s default text: Max Mana per class level Priest 5, Mage 10 (bases Priest %s / Mage %s)" % (''')
hrep('''              "pinned" if POST_PIN else "partner", SKILLS_PIN if POST_PIN else PARTNER))
    pp, pm = pools(D15, "Priest"), pools(D15, "Mage")''', '''              "pinned" if POST_PIN else "partner", SKILLS_PIN if POST_PIN else PARTNER, _cb7[0], _cb7[1]))
    pp, pm = pools(D15, "Priest"), pools(D15, "Mage")''')
hrep('''check(abs(pp["Mithril"] - 230.8) < 1e-6 and abs(pm["Mithril"] - 430.8) < 1e-6 and abs(W["Mithril"][0] / pp["Mithril"] - 0.3683) < 1e-3
      and abs(S["Mithril"][0] / pm["Mithril"] - 0.3946) < 1e-3, "P7: Mithril pools 230.8 / 430.8 -> 36.8% / 39.5% (spec 15.4)")''',
     '''_mp7 = (230.8, 430.8) if vtuple(SKILLS_PIN) < vtuple("0.4.25") else (230.8 + 12.0, 430.8 + 15.0)          # 0.1.15: + the 0.4.25 base rises (42 - 30, 45 - 30)
check(abs(pp["Mithril"] - _mp7[0]) < 1e-6 and abs(pm["Mithril"] - _mp7[1]) < 1e-6 and W["Mithril"][0] / pp["Mithril"] <= 0.40 and S["Mithril"][0] / pm["Mithril"] <= 0.40,
      "P7: Mithril pools %s / %s -> %.1f%% / %.1f%% (spec 15.4; under 40%%)" % (pp["Mithril"], pm["Mithril"], 100 * W["Mithril"][0] / pp["Mithril"], 100 * S["Mithril"][0] / pm["Mithril"]))''')
# ---- P17 (Python): the files
P17 = r'''# ================================================================================================================ P17. 0.1.15: the 3 Untiered items
def p17_bad(uid, cj, base):
    """the planned change of the Iron base item JSON -> the copy; the keys that differ otherwise (empty = exactly the plan)"""
    want = json.loads(json.dumps(base))
    want.pop("Recipe", None)
    want["TranslationProperties"] = {"Name": "server.items.%s.name" % uid, "Description": "server.items.%s.description" % uid}
    want["Variant"] = True
    want["Texture"] = "Items/SkyyArmory/UT/%s.png" % uid
    want["Icon"] = "Icons/ItemsGenerated/%s.png" % uid
    return sorted(k_ for k_ in set(want) | set(cj) if want.get(k_) != cj.get(k_))


_b17 = {}
_azn17 = set(zipfile.ZipFile(AZ_PATH).namelist())
for _u, _p in UT15_ITEMS.items():
    _cj = json.loads(JZ15.read(_p).decode("utf-8"))
    _bp = [n_ for n_ in JZ15.namelist() if n_.startswith("Server/Item/Items/") and os.path.basename(n_) == UT15_BASE[_u] + ".json"]
    _bj = json.loads(JZ15.read(_bp[0]).decode("utf-8")) if len(_bp) == 1 else {}
    _d = p17_bad(_u, _cj, _bj)
    if _d or "Recipe" in _cj or not _bj:
        _b17[_u] = _d
    for _k in ("Texture", "Icon"):
        _w, _h = SA.png_size(JZ15.read("Common/" + _cj[_k]))
        if not (_w > 0 and _h > 0) or ("Common/" + _cj[_k]) in _azn17 or ("Common/" + _cj[_k]) in OZ114.namelist():
            _b17[_u + " " + _k] = "bad picture"
check(not _b17, "P17: each Untiered item = the jar's own final Iron item with ONLY the planned keys changed (no Recipe, Variant, "
                "own name, the orange texture + icon - valid PNGs that shadow nothing): %s" % _b17)
_m17 = json.loads(JZ15.read(UT15_ITEMS["Weapon_Staff_UT_Loophole"]).decode("utf-8"))
_m17b = json.loads(JZ15.read("Server/Item/Items/Weapon/Staff/Weapon_Staff_Iron.json").decode("utf-8"))
_m17r = dict(_m17, Recipe={"Input": [{"ItemId": "Ingredient_Bar_Iron", "Quantity": 6}], "TimeSeconds": 3})
check(p17_bad("Weapon_Staff_UT_Loophole", _m17r, _m17b) == ["Recipe"], "P17 MUTANT: a copy that kept its Recipe fails the same check")
_lo17 = OZ114.read(UT15_LANG).decode("utf-8")
_ln17 = JZ15.read(UT15_LANG).decode("utf-8")
_lx17 = _ln17[len(_lo17):].strip("\n").split("\n") if _ln17.startswith(_lo17) else None
check(_lx17 is not None and len(_lx17) == 6 and "items.Weapon_Staff_UT_Loophole.name = The Loophole" in _lx17
      and "items.Weapon_Wand_UT_SecondOpinion.description = Untiered wand. Your heal orb heals 50% more. Wand shots deal 40% less damage." in _lx17,
      "P17: the lang = 0.1.14's bytes + 6 lines (3 names + 3 descriptions): %s" % (_lx17[:2] if _lx17 else None))
_n17, _o17 = set(JZ15.namelist()), set(OZ114.namelist())
_d17 = sorted(n_ for n_ in _n17 & _o17 if not n_.endswith(".class") and n_ != "manifest.json" and JZ15.read(n_) != OZ114.read(n_))
_mm17 = json.loads(JZ15.read("manifest.json").decode("utf-8")), json.loads(OZ114.read("manifest.json").decode("utf-8"))
check(sorted(_n17 - _o17) == UT15_NEW and not (_o17 - _n17) and _d17 == [UT15_LANG]
      and dict(_mm17[0], Version=None, Name=None) == dict(_mm17[1], Version=None, Name=None) and _mm17[0]["Version"] == VERSION,
      "P17: vs SkyyArmory-0.1.14.jar - new = the 3 items + 6 pictures, none gone, the only changed non-class file = the lang, the manifest = its version: %s %s" % (
          sorted(_n17 ^ _o17)[:6], _d17[:4]))
print("P17. 0.1.15: 3 Untiered items (Iron copies, no recipe, orange placeholder art), 6 lang lines, nothing else")
PY_OKS, PY_FAILS = OKS[0], len(FAILS)'''
hrep('''PY_OKS, PY_FAILS = OKS[0], len(FAILS)''', P17)

# ---- L: the 3 items into the store before the pack check (54)
hrep('''    check(not bad14l and len(SIG14_NEW) == 4, "L (0.1.14): the 2 signature interactions + the marker decode (no unknown key) and go into the stores: %s" % bad14l[:3])''',
     '''    check(not bad14l and len(SIG14_NEW) == 4, "L (0.1.14): the 2 signature interactions + the marker decode (no unknown key) and go into the stores: %s" % bad14l[:3])
    bad15l, objs15l = [], []          # 0.1.15: the 3 Untiered items (the real files) into the store - the pack check counts them (54)
    for k_ in UT15_IDS:
        o_, w_, ei_ = dec17(ITMc, k_, JZ15.read(UT15_ITEMS[k_]).decode("utf-8"))
        if o_ is None or w_:
            bad15l.append("%s: %s" % (k_, w_))
        else:
            objs15l.append(o_)
    load(ITMc, objs15l, PACK)
    check(not bad15l and len(objs15l) == 3, "L (0.1.15): the 3 Untiered items decode (no unknown key, no failed validation) and go into the store: %s" % bad15l[:3])''')

# ---- R18 (JVM)
R18 = r'''    # ============================================================================ R18. 0.1.15 THE THREE UNTIERED ITEMS - every new path EXECUTED
    # R18a THE ENGINE ASSET VALIDATORS on the 3 real files; in the store from our pack (L); no recipe to generate (control: the Iron staff)
    # the bare JVM registers no common assets: the jar's own Common files (the Iron models, the 6 new pictures - P17 proved they are in the jar)
    # and the vanilla ones count as present, like R17a's vanilla names (env14)
    KNOWN14.update(n_[len("Common/"):] for n_ in JZ15.namelist() if n_.startswith("Common/"))
    KNOWN14.update(n_[len("Common/"):] for n_ in AZN if n_.startswith("Common/"))
    val18 = []
    for k_ in UT15_IDS:
        o_, w_ = validate14(ITMc, k_, JZ15.read(UT15_ITEMS[k_]).decode("utf-8"))
        if o_ is None or w_:
            val18.append("%s: %s" % (k_, w_))
    st18 = [(ITMc.getAssetMap().getAsset(k_) is not None and str(ITMc.getAssetMap().getAssetPack(k_)) == PACK, ITMc.getAssetMap().getAsset(k_) is not None
             and not bool(ITMc.getAssetMap().getAsset(k_).hasRecipesToGenerate()), ITMc.getAssetMap().getAsset(k_) is not None
             and ITMc.getAssetMap().getAsset(k_).getWeapon() is not None) for k_ in UT15_IDS]
    ctl18 = [k_ for k_ in ("Weapon_Wand_Iron", "Weapon_Bo_Iron", "Weapon_Staff_Iron") if ITMc.getAssetMap().getAsset(k_) is not None
             and bool(ITMc.getAssetMap().getAsset(k_).hasRecipesToGenerate())]
    check(not val18 and st18 == [(True, True, True)] * 3 and ctl18,
          "R18a: the ENGINE ASSET VALIDATORS pass on the 3 Untiered items; each sits in the item store from our pack, is a weapon and generates NO "
          "recipe (control: their bases %s do): %s %s" % (ctl18, val18[:2], st18))
    # R18b armory:fn:info answers for them exactly as for the Iron base; utBase
    INF18 = JClass(PKG + "ArmoryInfoFn")()
    ia18 = lambda k_, i_: [str(x_) for x_ in INF18.apply(JArray(JObject)([k_, i_]))]
    check(ia18("staff", "Weapon_Staff_UT_Loophole") == ia18("staff", "Weapon_Staff_Iron") and ia18("wand", "Weapon_Wand_UT_SecondOpinion") == ia18("wand", "Weapon_Wand_Iron")
          and INF18.apply(JArray(JObject)(["wand", "Weapon_Wand_UT_Nope"])) is None and str(ADefs.utBase("Weapon_Bo_UT_Turnstile")) == "Weapon_Bo_Iron"
          and str(ADefs.utBase("Weapon_Staff_Copper")) == "Weapon_Staff_Copper",
          "R18b: armory:fn:info - the Loophole answers as the Iron staff, the Second Opinion as the Iron wand (SkyyGear's shot lines, SkyyClasses' "
          "heal caps); an unknown id null; utBase maps only the 3 copies")
    # R18c the heal maths: Iron lands 100 -> heals from 100; the Second Opinion lands 60 (SkyyGear -40 %) -> heals from 60 / 0.6 x 1.5 = 150
    hb18 = [round(float(AT.utHealBase(60.0, -40.0, 50.0)), 6), round(float(AT.utHealBase(100.0, 0.0, 0.0)), 6), round(float(AT.utHealBase(10.0, -100.0, 50.0)), 6),
            round(float(AT.utHealBase(10.0, 0.0, -150.0)), 6)]
    check(hb18 == [150.0, 100.0, 300.0, 0.0] and round(60.0 * 1.5, 6) == 90.0,
          "R18c: the Second Opinion's heal base = landed / (1 + dmg %%) x (1 + heal %%): 60 at -40 / +50 -> 150 = 1.5 x the Iron wand's 100 (MUTANT: from "
          "the landed damage it would be 60 x 1.5 = 90 = 0.9 x - the trap); the cut clamps at 5 %%, a heal never below 0: %s" % hb18)
    # R18d gear:fn:utfx (SkyyGear 0.2.16's numbers) through the bridge - a stand-in with SkyyGear's default rows; absent = 0
    UTFX18 = {("Weapon_Staff_UT_Loophole", "pierce"): 1.0, ("Weapon_Staff_UT_Loophole", "dmg"): -30.0, ("Weapon_Wand_UT_SecondOpinion", "heal"): 50.0,
              ("Weapon_Wand_UT_SecondOpinion", "dmg"): -40.0}

    @JImplements("java.util.function.Function")
    class UtFx18:
        @JOverride
        def apply(self, a):
            return JDouble(UTFX18.get((str(a[0]), str(a[1])), 0.0))
    br.remove("gear:fn:utfx")
    no18 = [float(AT.utfx("Weapon_Staff_UT_Loophole", "pierce")), float(AT.utfx(None, "pierce"))]
    br.put("gear:fn:utfx", UtFx18())
    yes18 = [float(AT.utfx("Weapon_Staff_UT_Loophole", "pierce")), float(AT.utfx("Weapon_Wand_UT_SecondOpinion", "heal")), float(AT.utfx("Weapon_Staff_Iron", "pierce"))]
    check(no18 == [0.0, 0.0] and yes18 == [1.0, 50.0, 0.0], "R18d: gear:fn:utfx read - without SkyyGear 0.2.16 every number is 0; with it pierce 1 / heal 50: %s %s" % (no18, yes18))
    # R18e THE PIERCE: ArmoryTrav.added (staff quick shot, code 3000s) -> landed on the stand-ins
    hand18 = LP.HAND
    LP.HAND = HashMap()
    reset_buf()
    TW.ALL.clear()
    ACfg.useDefaults()

    def squick18(i_, hand_):
        LP.HAND.put(cu, hand_)
        q_, qp_ = launched(SQORB["Iron"], i_, 0.5, 65.0, 0.5)
        AT.added(q_, qp_, int(ADefs.pidCode(SQORB["Iron"])), tst, tbuf)
        return q_, TW.of(tst).quick.get(q_)
    nA18, nB18 = npc(1840, 5.5, 64.0, 0.5), npc(1841, 9.5, 64.0, 0.5)
    qL, sL = squick18(1850, "Weapon_Staff_UT_Loophole")
    p0_ = int(AT.PIERCES)
    reset_buf()
    dL = DMGc(DPS(rc, qL), DCSc.PROJECTILE, JFloat(35.0))
    dL.putMetaObject(DMGc.HIT_LOCATION, V4(5.5, 65.0, 0.5, 1.0))
    AT.landed(tst, tbuf, dL, qL, int(ADefs.pidCode(SQORB["Iron"])), nA18)
    addL = list(TBf.ADDED)
    nrL = addL[0][1] if addL else None
    contL = None
    if addL:
        pcL = addL[0][0].getComponent(LPCc.getComponentType())
        put(nrL, TCc.getComponentType(), TCc(V3(7.0, 65.0, 0.5), R3(0.0, 0.0, 0.0)))
        AT.added(nrL, pcL, int(ADefs.pidCode(SQORB["Iron"])), tst, tbuf)
        contL = TW.of(tst).quick.get(nrL)
    qI, sI = squick18(1851, "Weapon_Staff_Iron")
    reset_buf()
    dI = DMGc(DPS(rc, qI), DCSc.PROJECTILE, JFloat(35.0))
    dI.putMetaObject(DMGc.HIT_LOCATION, V4(5.5, 65.0, 0.5, 1.0))
    AT.landed(tst, tbuf, dI, qI, int(ADefs.pidCode(SQORB["Iron"])), nA18)
    addI = list(TBf.ADDED)
    br.remove("gear:fn:utfx")
    qN, sN = squick18(1852, "Weapon_Staff_UT_Loophole")
    br.put("gear:fn:utfx", UtFx18())
    check(sL is not None and bool(sL.utPierce) and len(addL) == 1 and str(addL[0][0].getComponent(LPCc.getComponentType()).getProjectileAssetName()) == SQORB["Iron"]
          and int(AT.PIERCES) == p0_ + 1 and contL is not None and bool(contL.utPierce) and contL.hits.contains(nA18)
          and sI is not None and not bool(sI.utPierce) and not addI and sN is not None and not bool(sN.utPierce),
          "R18e THE PIERCE: a staff quick shot fired with the Loophole in hand pierces - a continuation of the same orb past the enemy (the chain's "
          "hit set + the flag kept); with the Iron staff in hand no continuation; without SkyyGear's numbers no pierce: %s / %s" % (len(addL), len(addI)))

    # R18f THE HEAL: a wand charged orb fired with the Second Opinion heals from the pre-cut damage
    def horb18(i_, hand_, landed_):
        LP.HAND.put(cu, hand_)
        o_, op_ = launched(ORB["Iron"], i_, 0.5, 65.5, 0.5)
        AT.added(o_, op_, int(ADefs.pidCode(ORB["Iron"])), tst, tbuf)
        tw_ = TW.of(tst)
        s_ = tw_.orbs.get(o_)
        n0_ = tw_.fx.size()
        reset_buf()
        NEARL[:] = [nB18, rc]
        d_ = DMGc(DPS(rc, o_), DCSc.PROJECTILE, JFloat(88.0))
        d_.setAmount(JFloat(landed_))
        AT.landed(tst, tbuf, d_, o_, int(ADefs.pidCode(ORB["Iron"])), nB18)
        fx_ = [tw_.fx.get(k_) for k_ in range(n0_, tw_.fx.size()) if int(tw_.fx.get(k_).kind) == 2]
        return s_, [round(float(f_.amount), 4) for f_ in fx_]
    sS, hS = horb18(1860, "Weapon_Wand_UT_SecondOpinion", 60.0)
    sW, hW = horb18(1861, "Weapon_Wand_Iron", 60.0)
    sW2, hW2 = horb18(1862, "Weapon_Wand_Iron", 100.0)
    check(sS is not None and float(sS.utHeal) == 50.0 and float(sS.utDmg) == -40.0 and hS == [30.0] and hW == [12.0] and hW2 == [20.0]
          and float(sW.utHeal) == 0.0 and abs(hS[0] / hW2[0] - 1.5) < 1e-9,
          "R18f THE HEAL: the Second Opinion's orb (landed 60 after its -40 %%) heals 20 %% of 150 = 30 a tick = 1.5 x the Iron wand's at its own "
          "landed 100 (20); the Iron wand at 60 heals 12 - nothing changes for it: %s %s %s" % (hS, hW, hW2))
    LP.HAND = hand18
    br.remove("gear:fn:utfx")
    ACfg.useDefaults()
    TW.ALL.clear()
    reset_buf()
    # R18g: vs the 0.1.14 jar METHOD BY METHOD
    MN18, MO18 = methods_of(JAR), methods_of(OLD114)
    cmp18 = {}
    for c_ in sorted(set(MN18) | set(MO18)):
        if c_ not in MN18 or c_ not in MO18:
            cmp18[c_] = "only in " + ("0.1.15" if c_ in MN18 else "0.1.14")
            continue
        ch_ = sorted(k_ for k_ in set(MN18[c_][0]) | set(MO18[c_][0]) if MN18[c_][0].get(k_) != MO18[c_][0].get(k_))
        fd_ = sorted(set(MN18[c_][1]) ^ set(MO18[c_][1]))
        if ch_ or fd_:
            cmp18[c_] = {"methods": [k_.split("(")[0] for k_ in ch_], "fields": [f_.split(":")[0] for f_ in fd_]}
    plan18 = {"ArmoryDefs": ({"utBase"}, {"UT_IDS", "UT_BASE"}), "ArmoryTrav": ({"utfx", "utHealBase", "casterHand", "utMark", "added", "landed"}, set()),
              "TravShot": ({"next"}, {"utPierce", "utHeal", "utDmg"}), "ArmoryInfoFn": ({"apply"}, set())}
    bad18 = {}
    for c_, v_ in cmp18.items():
        if c_ in plan18 and isinstance(v_, dict) and set(v_["methods"]) <= plan18[c_][0] and set(v_["fields"]) <= plan18[c_][1]:
            continue
        bad18[c_] = v_
    check(not bad18 and "added" in cmp18.get("ArmoryTrav", {}).get("methods", []) and "landed" in cmp18.get("ArmoryTrav", {}).get("methods", [])
          and "apply" in cmp18.get("ArmoryInfoFn", {}).get("methods", []),
          "R18g: 0.1.14 -> 0.1.15 METHOD BY METHOD - only the planned methods / fields differ (ArmoryDefs utBase + the 2 tables, ArmoryTrav utfx / "
          "utHealBase / casterHand / utMark / added / landed, TravShot's 3 fields + next, ArmoryInfoFn.apply): %s" % json.dumps(bad18)[:1500])
    print("R18g. vs 0.1.14 method by method: %s" % json.dumps(cmp18)[:1500])
    print("R18. 0.1.15 Untiered items: validators (3), the store + no recipe, armory:fn:info as Iron, the heal maths (+ the trap mutant), gear:fn:utfx, "
          "the Loophole pierce (+ Iron / no SkyyGear controls), the Second Opinion heal = 1.5 x Iron, the 0.1.14 compare - every path executed")
'''
hrep('''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''',
     R18 + '''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''')

out_t = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(out_t)
print("wrote %s" % os.path.relpath(TDST, ROOT))
