"""Derive SkyyArmory/build_skyyarmory_0.1.5.py (+ its harness SkyyArmory/test_skyyarmory_0.1.5.py) from the GENERATED 0.1.4
(SkyyArmory/build_skyyarmory_0.1.4.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_4_patch.py; test_skyyarmory_0.1.4.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_5_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.5.py   then   python SkyyArmory/test_skyyarmory_0.1.5.py
      (never --deploy; SkyyArmory 0.1.5 needs the same deploy partners as 0.1.4 and nothing new)

0.1.5 = THE NEW METAL STAFF LOOKS (art only, no gameplay change; Skyy 2026-10-07, docs/answered/gear.md LOCKED ART answers: "Match the
wands.  New like the concept."; "all of the items look beautiful. are they deployed in game?"):
  the 7 metal staffs Weapon_Staff_Copper / _Iron / _Thorium / _Cobalt / _Adamantite / _Mithril / _Onyxium get their OWN model (wood shaft,
  black leather grip, metal cradle + one big faceted crystal; bands 2 -> 5 per tier, side leaves from Thorium, Cobalt fins, Adamantite
  spikes, a ring on Mithril + Onyxium, gold trim on Mithril), its texture and a 64x64 icon, coloured with the metal-wand recipe.
  The art comes from tools/art/make_staffs.py, CALLED AT BUILD TIME (its functions staff_rig / staff_model / pack / tier_colours /
  paint_texture + SA.render_icon, in the same order as its main()): the vanilla-derived bytes exist only inside the jar, never in a tracked
  file. Shipped exactly like the wand art: Common/Items/Weapons/Staff/SkyyArmory_<Metal>.blockymodel, ..._<Metal>_Texture.png,
  Common/Icons/ItemsGenerated/SkyyArmory_Staff_<Metal>.png. The 7 staff item JSONs (already SkyyArmory's overrides) change Model / Texture /
  Icon ONLY - IconProperties stay the vanilla ones (make_staffs keeps each tier's vanilla rig + length, so the vanilla frame fits),
  interactions / quality / level / recipes / every other key as 0.1.4. Untouched: the Wood staff, every wand, the crossbows, Bo staffs (no
  items yet).
  Build-time checks: the rig nodes (R-Attachment / Origin_Projectile / Origin_Item / Handle position + orientation) = the tier's vanilla
  model, every box has all 6 faces and each face lies inside its texture, textures multiples of 32, icons 64x64, model JSON round-trips;
  when the review copy models-local/art/staffs/ (git-ignored) exists, the jar bytes must equal what Skyy reviewed.
  VERSION 0.1.5; no Java change beyond the version text (no new code path, no setting, no migration).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.4.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.5.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.4.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.5.py")

raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.4"\nMOD = "SkyyArmory"' in s and "0.1.4 = THE STAFF BLINK GOES FURTHER" in s, "build_skyyarmory_0.1.4.py is not the 0.1.4 pin"
SYS0 = s.count("registerSystem(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# ================================================================================================ header + version
rep('''"""SkyyArmory 0.1.4 - build script (javassist via jpype). GENERATED by tools/armory_0_1_4_patch.py from the GENERATED 0.1.3 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.4.py -> SkyyArmory/SkyyArmory-0.1.4.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.4.py (scratch tools/dev/scratch/armory014/).
''', '"""SkyyArmory 0.1.5 - build script (javassist via jpype). GENERATED by tools/armory_0_1_5_patch.py from the GENERATED 0.1.4 - edit the\n'
    'patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.5.py -> SkyyArmory/SkyyArmory-0.1.5.jar (never --deploy). Harness:\n'
    'python SkyyArmory/test_skyyarmory_0.1.5.py (scratch tools/dev/scratch/armory015/).\n\n'
    + open(__file__, encoding="utf8").read().split('"""')[1].split("\n", 3)[3].strip() + "\n\n"
    '0.1.4 (the base, everything below is still true unless 0.1.5 above says otherwise):\n')
rep('VERSION = "0.1.4"\nMOD = "SkyyArmory"', 'VERSION = "0.1.5"\nMOD = "SkyyArmory"')

# ================================================================================================ the staff art paths (the wand convention)
rep('''ICON_WAND = "Icons/ItemsGenerated/SkyyArmory_Wand_%s.png"
''', '''ICON_WAND = "Icons/ItemsGenerated/SkyyArmory_Wand_%s.png"
MODEL_STAFF = "Items/Weapons/Staff/SkyyArmory_%s.blockymodel"        # 0.1.5: the 7 metal staffs' own models (tools/art/make_staffs.py)
TEX_STAFF = "Items/Weapons/Staff/SkyyArmory_%s_Texture.png"
ICON_STAFF = "Icons/ItemsGenerated/SkyyArmory_Staff_%s.png"
''')

# ================================================================================================ the art, generated at build time
STAFF_ART = r'''# ---- 0.1.5: the 7 metal staffs' NEW looks (Skyy 2026-10-07: "Match the wands.  New like the concept."). tools/art/make_staffs.py is run
# HERE (its staff functions, in the order of its main()), so the vanilla-derived model / texture / icon bytes live only in the jar.
sys.path.insert(0, os.path.join(ROOT, "tools", "art"))
import make_staffs as MS
assert tuple(MS.METALS) == tuple(NEW_METALS), (MS.METALS, NEW_METALS)
RIG_NODES = ("R-Attachment", "Origin_Projectile", "Origin_Item", "Handle")
STAFF_FACES = ("front", "back", "left", "right", "top", "bottom")


def staff_art_check(m, model_bytes, tex, icon, vmodel):
    """the 0.1.5 shape rules for one staff: JSON round trip, the vanilla rig kept, 6 faces per box all inside the texture, sizes"""
    md = json.loads(model_bytes.decode("utf-8"))
    assert (json.dumps(md, indent=2) + "\n").encode("utf-8") == model_bytes, m + ": model JSON round trip"
    tw, th = SA.png_size(tex)
    assert tw % 32 == 0 and th % 32 == 0, "%s texture %dx%d is not a multiple of 32" % (m, tw, th)
    assert SA.png_size(icon) == (64, 64), "%s icon %s" % (m, SA.png_size(icon))
    for _rn in RIG_NODES:
        _a, _b = MS.find(md["nodes"], _rn), MS.find(vmodel["nodes"], _rn)
        assert _a is not None and _b is not None and _a.get("position") == _b.get("position") and _a.get("orientation") == _b.get("orientation"), \
            "%s: rig node %s moved off the vanilla staff's" % (m, _rn)
    _boxes = MS.all_boxes(md["nodes"], [])
    _faces = SA.model_faces(md)
    assert len(_boxes) >= 20 and len(_faces) == 6 * len(_boxes), "%s: %d boxes, %d faces" % (m, len(_boxes), len(_faces))
    for _f in _faces:
        _w, _h = _f["wh"]
        _pts = [SA.uv_point(_f["layout"], u, v) for u, v in ((0, 0), (_w, 0), (_w, _h), (0, _h))]
        assert min(p[0] for p in _pts) >= -1e-6 and min(p[1] for p in _pts) >= -1e-6 and max(p[0] for p in _pts) <= tw + 1e-6 \
            and max(p[1] for p in _pts) <= th + 1e-6, "%s: face %s.%s leaves its %dx%d texture: %s" % (m, _f["node"], _f["face"], tw, th, _pts)
    return len(_boxes), (tw, th)


STAFF_ART = {}
STAFF_REVIEW = {}
for _m in NEW_METALS:
    _sd, _svm, _butt, _tip, _hand, _side = MS.staff_rig(AZ, _m)
    assert _sd["IconProperties"] == VSTAFF[_m]["IconProperties"] and _sd["Model"] == VSTAFF[_m]["Model"], _m
    _smodel, _skinds, _sside = MS.staff_model({"model": _svm, "_rig": (_butt, _tip, _hand, _side)}, _m)
    _place, _height = MS.pack(_smodel)
    _stex = MS.paint_texture(_smodel, _place, _height, _skinds, MS.tier_colours(AZ, _m))
    _sicon = SA.render_icon(_smodel, _stex, VSTAFF[_m]["IconProperties"], 64)
    _smj = (json.dumps(_smodel, indent=2) + "\n").encode("utf-8")
    _nb, _tsz = staff_art_check(_m, _smj, _stex, _sicon, _svm)
    STAFF_ART[_m] = (_smj, _stex, _sicon, _nb, _tsz)
    ASSETS["Common/" + MODEL_STAFF % _m] = _smj
    ASSETS["Common/" + TEX_STAFF % _m] = _stex
    ASSETS["Common/" + ICON_STAFF % _m] = _sicon
    # the review copy Skyy looked at (git-ignored models-local/, written by python tools/art/make_staffs.py): when present, it must match
    _rv = os.path.join(ROOT, "models-local", "art", "staffs", "Common")
    _rf = [os.path.join(_rv, "Items", "Weapons", "Staff", "SkyyArmory_Staff_%s.blockymodel" % _m),
           os.path.join(_rv, "Items", "Weapons", "Staff", "SkyyArmory_Staff_%s_Texture.png" % _m),
           os.path.join(_rv, "Icons", "ItemsGenerated", "SkyyArmory_Staff_%s.png" % _m)]
    if all(os.path.isfile(p) for p in _rf):
        _same = [open(p, "rb").read() for p in _rf] == [_smj, _stex, _sicon]
        assert _same, "%s: the built staff art differs from the reviewed copy in models-local/art/staffs (re-run python tools/art/make_staffs.py " \
                      "and let Skyy look again)" % _m
        STAFF_REVIEW[_m] = "= reviewed copy"
    else:
        STAFF_REVIEW[_m] = "no review copy here"
assert len(set(a[1] for a in STAFF_ART.values())) == 7 and len(set(a[2] for a in STAFF_ART.values())) == 7, "every tier has its own texture + icon"

# ---- the 8 staff item overrides (spec 15.2 / 15.3)
STAFF_DIFF = {}
'''
rep('''# ---- the 8 staff item overrides (spec 15.2 / 15.3)
STAFF_DIFF = {}
''', STAFF_ART)
rep('''    if _m == "Onyxium" and ONYX_STAFF_RECIPE:
        _o["Recipe"] = onyx_recipe()
    # everything else equals vanilla (the S14 _spell_diff check)
    _a = dict((k, v) for k, v in _v.items() if k not in ("Interactions", "InteractionVars", "Recipe"))
    _b = dict((k, v) for k, v in _o.items() if k not in ("Interactions", "InteractionVars", "Recipe"))''', '''    if _m == "Onyxium" and ONYX_STAFF_RECIPE:
        _o["Recipe"] = onyx_recipe()
    _look = ()
    if _m in STAFF_ART:          # 0.1.5: the new look - Model / Texture / Icon only (keys keep their vanilla places; IconProperties stay vanilla)
        assert all(k in _o for k in ("Model", "Texture", "Icon", "IconProperties")), _m
        _o["Model"], _o["Texture"], _o["Icon"] = MODEL_STAFF % _m, TEX_STAFF % _m, ICON_STAFF % _m
        _look = ("Model", "Texture", "Icon")
    # everything else equals vanilla (the S14 _spell_diff check)
    _a = dict((k, v) for k, v in _v.items() if k not in ("Interactions", "InteractionVars", "Recipe") + _look)
    _b = dict((k, v) for k, v in _o.items() if k not in ("Interactions", "InteractionVars", "Recipe") + _look)''')

# ================================================================================================ jar check + build line
rep('''    _sitems = sorted(n for n in _names if n.startswith("Server/Item/Items/Weapon/Staff/"))''', '''    _sart = sorted(n for n in _names if n.startswith("Common/") and (n.startswith("Common/Items/Weapons/Staff/") or "/SkyyArmory_Staff_" in n))
    assert _sart == sorted("Common/" + p % m for m in NEW_METALS for p in (MODEL_STAFF, TEX_STAFF, ICON_STAFF)), "0.1.5: 21 staff art files: %s" % _sart
    _sitems = sorted(n for n in _names if n.startswith("Server/Item/Items/Weapon/Staff/"))''')
rep('''print("0.1.4 staff blink: blink.distance default 16 (0.1.3: 10), blink.floorCheck default 0 (0.1.3: 12); one-time update marker %r" % M14_MARK_ID)''',
    '''print("0.1.4 staff blink: blink.distance default 16 (0.1.3: 10), blink.floorCheck default 0 (0.1.3: 12); one-time update marker %r" % M14_MARK_ID)
print("0.1.5 staff looks (tools/art/make_staffs.py at build time): " + "; ".join("%s %d boxes, texture %dx%d, %s" % (
    _m, STAFF_ART[_m][3], STAFF_ART[_m][4][0], STAFF_ART[_m][4][1], STAFF_REVIEW[_m]) for _m in NEW_METALS))''')

assert s.count("registerSystem(") == SYS0, "0.1.5 registers no new system"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))

# ================================================================================================ the harness: 0.1.4's checks + R9
HARNESS_R9 = r'''
# ============================================================================================================ R9. 0.1.5 the new metal staff looks
# (Skyy 2026-10-07: "Match the wands.  New like the concept.") - pure file checks, no JVM: the 7 staffs name files the jar ships, the art =
# tools/art/make_staffs.py run again here, every face inside its texture (own walker, not skyyart's), the vanilla rig kept, the icon = a
# render of the shipped model + texture at the item's own IconProperties, and EVERY other file byte-identical to the 0.1.4 jar.
sys.path.insert(0, os.path.join(ROOT, "tools", "art"))
import make_staffs as MS
STAFF_MODEL = "Items/Weapons/Staff/SkyyArmory_%s.blockymodel"
STAFF_TEX = "Items/Weapons/Staff/SkyyArmory_%s_Texture.png"
STAFF_ICON = "Icons/ItemsGenerated/SkyyArmory_Staff_%s.png"
R9_FACE = {"front": ("x", "y"), "back": ("x", "y"), "left": ("z", "y"), "right": ("z", "y"), "top": ("x", "z"), "bottom": ("x", "z")}


def r9_face_bad(md, tw, th, all6=True):
    """own walker: every box needs the 6 faces (all6; vanilla leaves hidden faces out); each face's texel rectangle (angle 0 / 90 / 180 / 270,
    mirror) inside tw x th"""
    bad_, n_ = [], [0]

    def walk(nodes):
        for n in nodes:
            sh = n.get("shape") or {}
            if sh.get("type") == "box":
                n_[0] += 1
                sz = sh["settings"]["size"]
                lay = sh.get("textureLayout") or {}
                for f, (a, b) in R9_FACE.items():
                    l = lay.get(f)
                    if l is None:
                        if all6:
                            bad_.append("%s.%s no layout" % (n["name"], f))
                        continue
                    w, h = float(sz[a]), float(sz[b])
                    mx, my = (l.get("mirror") or {}).get("x"), (l.get("mirror") or {}).get("y")
                    ang = int(l.get("angle", 0)) % 360
                    xs, ys = [], []
                    for u, v in ((0, 0), (w, 0), (w, h), (0, h)):
                        u, v = (-u if mx else u), (-v if my else v)
                        u, v = {0: (u, v), 90: (-v, u), 180: (-u, -v), 270: (v, -u)}[ang]
                        xs.append(l["offset"]["x"] + u)
                        ys.append(l["offset"]["y"] + v)
                    if min(xs) < -1e-6 or min(ys) < -1e-6 or max(xs) > tw + 1e-6 or max(ys) > th + 1e-6:
                        bad_.append("%s.%s x %.1f..%.1f y %.1f..%.1f" % (n["name"], f, min(xs), max(xs), min(ys), max(ys)))
            walk(n.get("children") or [])
    walk(md["nodes"])
    return n_[0], bad_


def r9_version_only(a, b):
    """the two class files differ ONLY inside "0.1.4" (old) -> "0.1.5" (new) texts at the same offsets (same length, same layout); the fixed
    "SkyyArmory 0.1.4" texts of the 0.1.4 migration stay 0.1.4 in both"""
    if len(a) != len(b):
        return False
    for p in range(len(a)):
        if a[p] != b[p] and not any(a[i:i + 5] == b"0.1.4" and b[i:i + 5] == b"0.1.5" for i in range(max(0, p - 4), p + 1)):
            return False
    return True


def r9_rig(md):
    return [(nm, (MS.find(md["nodes"], nm) or {}).get("position"), (MS.find(md["nodes"], nm) or {}).get("orientation"))
            for nm in ("R-Attachment", "Origin_Projectile", "Origin_Item", "Handle")]


# the old jar: the built 0.1.4 beside the scripts, else the build's fallback = the installed Mods/SkyyArmory.jar when its manifest says 0.1.4
OLD_JAR = os.path.join(HERE, "SkyyArmory-0.1.4.jar")
if not os.path.isfile(OLD_JAR):
    _inst = os.path.join(B.MODS_DIR, "SkyyArmory.jar")
    try:
        with zipfile.ZipFile(_inst) as _iz:
            OLD_JAR = _inst if json.loads(_iz.read("manifest.json").decode("utf-8-sig")).get("Version") == "0.1.4" else None
    except Exception:
        OLD_JAR = None
SA.verify(quiet=True)
z9 = SA.assets()
r9_art = {}
for m in METALS[1:]:
    it = JITEM[SID[m]]
    vi = aj("item", SID[m])
    paths = ("Common/" + STAFF_MODEL % m, "Common/" + STAFF_TEX % m, "Common/" + STAFF_ICON % m)
    check((it["Model"], it["Texture"], it["Icon"]) == (STAFF_MODEL % m, STAFF_TEX % m, STAFF_ICON % m) and all(p in JSET for p in paths)
          and it["IconProperties"] == vi["IconProperties"] and list(it) == [k for k in vi if k != "InteractionVars"] + (["Recipe"] if m == "Onyxium" else []),
          "R9: %s staff names its own model / texture / icon, all three in the jar; IconProperties = vanilla %s; key order kept" % (m, vi["IconProperties"]))
    mb, tb, ib = [JZ.read(p) for p in paths]
    md = json.loads(mb.decode("utf-8"))
    tw, th = SA.png_size(tb)
    nb, fbad = r9_face_bad(md, tw, th)
    vm = json.loads(z9.read("Common/" + vi["Model"]).decode("utf-8-sig"))
    check(tw % 32 == 0 and th % 32 == 0 and SA.png_size(ib) == (64, 64) and nb >= 20 and not fbad and r9_rig(md) == r9_rig(vm),
          "R9: %s - texture %dx%d (multiples of 32), icon 64x64, model JSON valid, %d boxes x 6 faces all inside the texture, rig = the vanilla %s: %s" % (
              m, tw, th, nb, vi["Model"], fbad[:3]))
    # the generator run again here = the jar bytes (the build really called it; deterministic)
    d_, vmodel_, b_, t_, h_, s_ = MS.staff_rig(z9, m)
    gm, gk, _gs = MS.staff_model({"model": vmodel_, "_rig": (b_, t_, h_, s_)}, m)
    gp, gh = MS.pack(gm)
    gt = MS.paint_texture(gm, gp, gh, gk, MS.tier_colours(z9, m))
    gi = SA.render_icon(gm, gt, d_["IconProperties"], 64)
    ri = SA.render_icon(md, tb, it["IconProperties"], 64)
    check(((json.dumps(gm, indent=2) + "\n").encode("utf-8"), gt, gi) == (mb, tb, ib) and ri == ib,
          "R9: %s - tools/art/make_staffs.py run again = the jar's model / texture / icon byte for byte, and rendering the SHIPPED model + texture at "
          "the item's IconProperties gives the shipped icon" % m)
    r9_art[m] = (tb, ib, nb)
# negative controls: the face check catches a face pushed off the texture, a missing face; the rig check catches a moved hand point
md0 = json.loads(JZ.read("Common/" + STAFF_MODEL % "Copper").decode("utf-8"))
tw0, th0 = SA.png_size(JZ.read("Common/" + STAFF_TEX % "Copper"))
mx1 = copy.deepcopy(md0)
MS.find(mx1["nodes"], "Crystal3")["shape"]["textureLayout"]["front"]["offset"]["x"] = tw0 - 2
mx2 = copy.deepcopy(md0)
MS.find(mx2["nodes"], "ButtCap")["shape"]["textureLayout"].pop("top")
mx3 = copy.deepcopy(md0)
MS.find(mx3["nodes"], "R-Attachment")["position"] = {"x": 9, "y": 9, "z": 9}
vm0 = json.loads(z9.read("Common/" + aj("item", SID["Copper"])["Model"]).decode("utf-8-sig"))
vtb0 = z9.read("Common/" + aj("item", SID["Copper"])["Texture"])
check(r9_face_bad(mx1, tw0, th0)[1] and r9_face_bad(mx2, tw0, th0)[1] and r9_rig(mx3) != r9_rig(vm0)
      and not r9_face_bad(vm0, *SA.png_size(vtb0), all6=False)[1],
      "R9 negative controls: a face pushed off the texture and a missing face are caught, a moved rig node is caught (the vanilla Copper staff passes the "
      "same face walker: %s)" % r9_face_bad(vm0, *SA.png_size(vtb0), all6=False)[1][:2])
check(len(set(a[0] for a in r9_art.values())) == 7 and len(set(a[1] for a in r9_art.values())) == 7,
      "R9: 7 different textures + 7 different icons (one look per tier)")
mutant_look = copy.deepcopy(JITEM)
mutant_look["Weapon_Staff_Iron"]["Model"] = "Items/Weapons/Staff/SkyyArmory_Nope.blockymodel"
check(any("SkyyArmory_Nope" in x for x in closure_bad(JINT, JROOT, JPRJ, mutant_look, QM)),
      "R9 negative control: a staff naming a model the jar does not ship is caught by the P1 closure")
# every other file = 0.1.4, byte for byte
if OLD_JAR is None:
    print("R9. NOTE no 0.1.4 jar here (SkyyArmory/SkyyArmory-0.1.4.jar or an installed 0.1.4 Mods/SkyyArmory.jar) - the old-vs-new file compare is skipped")
else:
    with zipfile.ZipFile(OLD_JAR) as oz:
        on = oz.namelist()
        art = set("Common/" + p % m for m in METALS[1:] for p in (STAFF_MODEL, STAFF_TEX, STAFF_ICON))
        look_items = set("Server/Item/Items/Weapon/Staff/Weapon_Staff_%s.json" % m for m in METALS[1:])
        new_only = sorted(set(JN) - set(on))
        gone = sorted(set(on) - set(JN))
        same_bad = [n for n in on if n in JSET and not n.endswith(".class") and n not in look_items and n != "manifest.json" and oz.read(n) != JZ.read(n)]
        look_bad = []
        for n in sorted(look_items):
            a_, b_ = json.loads(oz.read(n).decode("utf-8")), json.loads(JZ.read(n).decode("utf-8"))
            if sorted(k for k in set(a_) | set(b_) if a_.get(k) != b_.get(k)) != ["Icon", "Model", "Texture"] or list(a_) != list(b_):
                look_bad.append(n)
        om, nm9 = json.loads(oz.read("manifest.json").decode("utf-8-sig")), json.loads(JZ.read("manifest.json").decode("utf-8-sig"))
        man_ok = dict(om, Name="", Version="") == dict(nm9, Name="", Version="") and nm9["Version"] == VERSION and nm9["Name"] == VERSION + " " + MOD
        oc = sorted(n for n in on if n.endswith(".class"))
        nc = sorted(n for n in JN if n.endswith(".class"))
        cdiff = [n for n in oc if n in JSET and oz.read(n) != JZ.read(n)]
        cver = [n for n in cdiff if not r9_version_only(oz.read(n), JZ.read(n))]
    check(new_only == sorted(art) and not gone and not same_bad and not look_bad and man_ok and oc == nc and not cver,
          "R9: vs %s - new files = exactly the 21 staff art files, none gone, every other non-class file byte-identical, the 7 staff items differ in "
          "Model / Texture / Icon only (key order kept), manifest = version only, same %d classes and the %d that differ differ only in the version "
          "text: new %s gone %s changed %s %s %s" % (os.path.basename(OLD_JAR), len(nc), len(cdiff), new_only[:3], gone[:3], same_bad[:3], look_bad, cver[:3]))
    print("R9. vs %s: +%d staff art files, %d other files byte-identical, %d classes (%d differ in the version text only)" % (
        OLD_JAR, len(new_only), len([n for n in on if not n.endswith(".class")]) - len(look_items) - 1, len(nc), len(cdiff)))
z9.close()
print("R9. new metal staff looks: 7 staffs -> own model / texture / icon in the jar (" + ", ".join("%s %dx%d %d boxes" % (
    m, SA.png_size(r9_art[m][0])[0], SA.png_size(r9_art[m][0])[1], r9_art[m][2]) for m in METALS[1:]) + "); generator re-run = jar bytes")
'''

traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.4 - test harness. GENERATED by tools/armory_0_1_4_patch.py from test_skyyarmory_0.1.3.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.5 - test harness. GENERATED by tools/armory_0_1_5_patch.py from test_skyyarmory_0.1.4.py - edit the patch, never this file.
Every 0.1.4 check below still runs (P4 patched: the 7 metal staffs = vanilla except the chain AND their new Model / Texture / Icon).
NEW section R9 (after P6, pure file checks): the 7 metal staffs name their own model / texture / icon and the jar ships all 21 files;
textures multiples of 32, icons 64x64, model JSON valid, every box has 6 faces each inside its texture (own walker), the vanilla rig nodes
kept; tools/art/make_staffs.py run again = the jar bytes; the shipped model + texture rendered at the item's IconProperties = the shipped
icon; negative controls (face off the texture, missing face, moved rig node, a staff on a missing model); and vs the 0.1.4 jar (the built
SkyyArmory/SkyyArmory-0.1.4.jar, else the build's fallback = the installed Mods/SkyyArmory.jar when it is 0.1.4, else a NOTE): only the 21
art files are new, every other non-class file byte-identical, the staff items differ in Model / Texture / Icon only, classes differ in the
version text only.

0.1.4 harness: SkyyArmory 0.1.4 - test harness. GENERATED by tools/armory_0_1_4_patch.py from test_skyyarmory_0.1.3.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.4"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.4 SkyyArmory"',
     'VERSION = "0.1.5"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.5 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory014", "harness")', 'os.path.join(SCRATCH_ROOT, "armory015", "harness")')
hrep('''check(len(J_PNG) == 19 and "Server/Languages/en-US/server.lang" in JSET and "manifest.json" in JSET, "P0: 19 PNGs (7 + 2 crossbow textures, 7 + 2 icons, 1 orb texture), lang, manifest")''',
     '''check(len(J_PNG) == 33 and "Server/Languages/en-US/server.lang" in JSET and "manifest.json" in JSET,
      "P0: 33 PNGs (7 + 2 crossbow textures, 7 + 2 icons, 1 orb texture; 0.1.5: + 7 staff textures + 7 staff icons), lang, manifest")''')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.4.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.5.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.4"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.5"))')
hrep('"[SkyyArmory] 0.1.4 ready" in m_', '"[SkyyArmory] 0.1.5 ready" in m_')
hrep('"0.1.4 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_', '"0.1.5 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_')
hrep('"0.1.4 crossbow grapple: grapple on" in m_', '"0.1.5 crossbow grapple: grapple on" in m_')
hrep('come from Skyy:0.1.4 SkyyArmory" in str(r[1])', 'come from Skyy:0.1.5 SkyyArmory" in str(r[1])')
# P4: the 7 metal staffs = vanilla except the chain + the new look
hrep('''    rest_v = dict((k, x) for k, x in v.items() if k not in ("Interactions", "InteractionVars"))
    rest_o = dict((k, x) for k, x in o.items() if k not in ("Interactions", "InteractionVars", "Recipe"))
    check(rest_v == rest_o and o["Interactions"] == {"Primary": "SkyyArmory_Staff_Primary_" + m, "Secondary": "SkyyArmory_Staff_Primary_" + m}''',
     '''    look_ = () if m == "Wood" else ("Model", "Texture", "Icon")          # 0.1.5: the metal staffs' new look (checked in R9)
    rest_v = dict((k, x) for k, x in v.items() if k not in ("Interactions", "InteractionVars") + look_)
    rest_o = dict((k, x) for k, x in o.items() if k not in ("Interactions", "InteractionVars", "Recipe") + look_)
    check(rest_v == rest_o and o["Interactions"] == {"Primary": "SkyyArmory_Staff_Primary_" + m, "Secondary": "SkyyArmory_Staff_Primary_" + m}
          and (m != "Wood" or (o["Model"], o["Texture"], o["Icon"]) == (v["Model"], v["Texture"], v["Icon"]))''')
hrep('''print("P6. art: styles A / B for 7 metals, deterministic, B in the jar, blue orb texture mean %s" % [round(x) for x in mean])
''', '''print("P6. art: styles A / B for 7 metals, deterministic, B in the jar, blue orb texture mean %s" % [round(x) for x in mean])
''' + HARNESS_R9)
tout = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(tout)
print("wrote %s (%d lines)" % (os.path.relpath(TDST, ROOT), tout.count(TNL) + 1))
