"""Derive SkyyArmory/build_skyyarmory_0.1.17.py (+ its harness SkyyArmory/test_skyyarmory_0.1.17.py) from the GENERATED 0.1.16
(SkyyArmory/build_skyyarmory_0.1.16.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_16_patch.py; test_skyyarmory_0.1.16.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_17_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.17.py   then
      python SkyyArmory/test_skyyarmory_0.1.17.py --dir tools/dev/scratch/<task>/harness      (never --deploy)

0.1.17 = THE WAND ROUND (docs/answered/classes.md LOCKED 2026-10-10, Skyy word for word):
  "reduce how far the wand launches you, keep the small pause at the top, with the delay to aim the shot. BUT make the healing aura appear
   where you land, and last a little longer."
  "and double the range of the wands quick shot, but half damage for the second half (the added range does less damage."
  1 SHORTER HOP. hop.force default 22 -> 18 (one-time update of an untouched 22, PROJECT-RULES 4). The hang (hop.hangSeconds 0.35, drift 1.5) and
    the aim delay (the orb fires where you look at the END of the hang) are untouched. hop.maxUp 15 stays (at 18 a 45-degree-down hop pushes
    12.7 up - under the cap; straight down 18 -> capped to 15).
  2 THE HEAL AURA AT THE LANDING SPOT. The charged orb still bursts (damage + the burst particle / sound) where it hits; the HEAL AURA (the
    lingering heal orb: orb.radius / orb.healPercent / orb.tick / party rules unchanged) now appears where the CASTER LANDS: Leap.fire (the end
    of the hang; the 0.1.2 hop job too) arms a landing watch per caster in TravWorld.land; every world tick (TravWorld.run -> ArmoryTrav.landTick)
    the first on-ground tick after the caster was airborne (or 0.4 s after the arm while standing) records the spot; no landing within 3 s =
    the ground right under them (TravMath.groundY, up to 8 blocks down) or, with no ground there, the caster's own position (never projected into
    the void). A burst before the landing waits for it (TravWorld.landFx); a burst after it is placed there at once; the aura lasts orb.seconds
    from the moment it appears. The caster gone / dead before landing = the aura at the burst spot (the 0.1.16 way). Only the wand charged orb
    of a hop (TravShot.land) - a cast refused for Stamina keeps the 0.1.16 spot. orb.seconds default 3.5 -> 5 (one-time update of an untouched
    3.5, the SAME migrate017 pass + marker as the hop force).
  3 QUICK SHOT RANGE x2 WITH FALLOFF. The wand quick shot's range is TravShot.range (TravTick removes the orb past it; the pierce continuation
    starts only inside it) = quick.range.wand (16) - the projectile itself (90 b/s, life quick.life 5 s = 450 blocks, gravity 0) never limits
    it. NEW rows quick.range.wandMult (2.0, 1-4) and quick.farPercent (50, 0-100): a wand quick orb now flies quick.range.wand x the multiplier
    (32); a hit farther than quick.range.wand from the cast point (TravShot sx/sy/sz - kept across pierce continuations) deals quick.farPercent %
    - ArmoryTuneSys (Filter group, before armour; the one place every quick hit is already scaled) multiplies it in ONCE (the tune-off path too).
    The distance = the hit location (Damage HIT_LOCATION), else the NEARER of the orb's position and the target's chest. Staff quick shots unchanged.
No new item / asset / class / interaction; saved data: config.properties only (migrate017 + 2 new keys - a missing key reads its default).
ROLLBACK: 0.1.16 reads hop.force 18 / orb.seconds 5 as custom values and ignores the 2 new keys (no data loss).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.16.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.17.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.16.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.17.py")

CR, LF = chr(13), chr(10)
raw = open(SRC, encoding="utf8", newline="").read()
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.16"\nMOD = "SkyyArmory"' in s and "0.1.16 = THE WAND HOP FIX" in s, "build_skyyarmory_0.1.16.py is not the 0.1.16 pin"
assert "migrate017" not in s and "RANGE_WAND_X" not in s and "landTick" not in s, "0.1.16 already has the 0.1.17 parts"


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# ---------------------------------------------------------------------------------------------------------------- header + version
rep('''"""SkyyArmory 0.1.16 - build script (javassist via jpype). GENERATED by tools/armory_0_1_16_patch.py from the GENERATED 0.1.15 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.16.py -> SkyyArmory/SkyyArmory-0.1.16.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.16.py --dir tools/dev/scratch/<task>/harness.
''', '''"""SkyyArmory 0.1.17 - build script (javassist via jpype). GENERATED by tools/armory_0_1_17_patch.py from the GENERATED 0.1.16 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.17.py -> SkyyArmory/SkyyArmory-0.1.17.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.17.py --dir tools/dev/scratch/<task>/harness.

0.1.17 = THE WAND ROUND (Skyy 2026-10-10: "reduce how far the wand launches you, keep the small pause at the top, with the delay to aim the
shot. BUT make the healing aura appear where you land, and last a little longer." + "and double the range of the wands quick shot, but half
damage for the second half"; full notes in tools/armory_0_1_17_patch.py): hop.force default 22 -> 18 and orb.seconds 3.5 -> 5 (one-time update
of untouched lines, migrate017); the hang + the aim delay unchanged; the charged orb bursts where it hits but its HEAL AURA appears where the
caster lands (first on-ground tick after the hang, at most 3 s - then the ground under them or their position); NEW rows quick.range.wandMult
(2) + quick.farPercent (50): a wand quick shot flies twice quick.range.wand, a hit past quick.range.wand deals 50 % (ArmoryTuneSys, once).

0.1.16 (the base, everything below is still true unless 0.1.17 above says otherwise):
''')
rep('VERSION = "0.1.16"\nMOD = "SkyyArmory"', 'VERSION = "0.1.17"\nMOD = "SkyyArmory"')

# ---------------------------------------------------------------------------------------------------------------- rows
rep(""" ('hop.force',
  'Wand hop force',
  'hop',
  'dec',
  '22',
  '0',
  '50',
  '',
  '',
  'live',
  'Skyy 2026-10-10: 22 ("a little too far"; 0.1.15: 30, 0.1.2: 13). 0 = no hop.',
  'HOP_FORCE',
  'double',
  '22',
  'Wand hop force (Skyy 2026-10-10: 22, "a little too far"; 0.1.15: 30; 13 = the vanilla dagger dash, 0 = no hop).'),""",
    """ ('hop.force',
  'Wand hop force',
  'hop',
  'dec',
  '18',
  '0',
  '50',
  '',
  '',
  'live',
  'Skyy 2026-10-10: 18 ("reduce how far"; 0.1.16: 22, 0.1.15: 30). 0 = no hop.',
  'HOP_FORCE',
  'double',
  '18',
  'Wand hop force (Skyy 2026-10-10: 18, "reduce how far the wand launches you"; 0.1.16: 22; 0.1.15: 30; 0 = no hop).'),""")
rep(""" ('orb.seconds',
  'Heal orb lasts (s)',
  'hop',
  'dec',
  '3.5',
  '0.5',
  '8',
  '',
  's',
  'live',
  'How long the glow stays.',
  'ORB_SECONDS',
  'double',
  '3.5',
  'Heal orb lasts (seconds).'),""", """ ('orb.seconds',
  'Heal orb lasts (s)',
  'hop',
  'dec',
  '5',
  '0.5',
  '8',
  '',
  's',
  'live',
  'How long the heal aura stays where you land (Skyy: a little longer; 0.1.16: 3.5).',
  'ORB_SECONDS',
  'double',
  '5',
  'Heal orb lasts (seconds; it appears where you land - Skyy 2026-10-10: 5, 0.1.16: 3.5).'),""")
rep(""" ('quick.range.wand',
  'Wand quick shot range (blocks)',
  'quick',
  'int',
  '16',
  '4',
  '64',
  '',
  'blocks',
  'live',
  'The quick orb vanishes this far from where it was cast.',
  'RANGE_WAND',
  'int',
  '16',
  'Wand quick shot range (blocks).'),""", """ ('quick.range.wand',
  'Wand quick full-damage range (blocks)',
  'quick',
  'int',
  '16',
  '4',
  '64',
  '',
  'blocks',
  'live',
  'Full damage up to here; the orb flies on to this x the range multiplier.',
  'RANGE_WAND',
  'int',
  '16',
  'Wand quick shot full-damage range (blocks); the orb flies on to this x quick.range.wandMult.'),
 ('quick.range.wandMult',
  'Wand quick range multiplier (x)',
  'quick',
  'dec',
  '2',
  '1',
  '4',
  '',
  'x',
  'live',
  'Skyy 2026-10-10: 2 = twice as far. Hits past the full-damage range deal the far %.',
  'RANGE_WAND_X',
  'double',
  '2',
  'Wand quick shots fly the full-damage range x this (Skyy 2026-10-10: 2 = double; 1 = the 0.1.16 range).'),
 ('quick.farPercent',
  'Wand quick far-hit damage (%)',
  'quick',
  'int',
  '50',
  '0',
  '100',
  'step=5',
  '%',
  'live',
  'Damage of a wand quick hit past the full-damage range (Skyy: half). 100 = no falloff.',
  'FAR_PCT',
  'int',
  '50',
  'A wand quick hit farther than quick.range.wand from the cast deals this % (Skyy 2026-10-10: half; 100 = no falloff).'),""")

# ---------------------------------------------------------------------------------------------------------------- markers + the default file
rep("""M16_MARK_ID = 'SkyyArmory 0.1.16 wand hop force'
""", """M17_MARK_ID = 'SkyyArmory 0.1.17 wand hop + heal aura'
M17_MARK = '# SkyyArmory 0.1.17 wand hop + heal aura (Skyy 2026-10-10: "reduce how far", "last a little longer"): hop 18 (0.1.16: 22), the heal aura lasts 5 s (0.1.16: 3.5) - lines still on the old defaults were updated once'
M16_MARK_ID = 'SkyyArmory 0.1.16 wand hop force'
""")
rep('''    "# Wand hop force (Skyy 2026-10-10: 22, \\"a little too far\\"; 0.1.15: 30; 13 = the vanilla dagger dash, 0 = no hop).",
    M13_MARK,
    M16_MARK,
    "hop.force=22",''', '''    "# Wand hop force (Skyy 2026-10-10: 18, \\"reduce how far the wand launches you\\"; 0.1.16: 22; 0.1.15: 30; 0 = no hop).",
    M13_MARK,
    M16_MARK,
    M17_MARK,
    "hop.force=18",''')
rep('''    "# Heal orb lasts (seconds).",
    "orb.seconds=3.5",''', '''    "# Heal orb lasts (seconds; it appears where you land - Skyy 2026-10-10: 5, 0.1.16: 3.5).",
    "orb.seconds=5",''')
rep('''    "# Wand quick shot range (blocks).",
    "quick.range.wand=16",''', '''    "# Wand quick shot full-damage range (blocks); the orb flies on to this x quick.range.wandMult.",
    "quick.range.wand=16",
    "# Wand quick shots fly the full-damage range x this (Skyy 2026-10-10: 2 = double; 1 = the 0.1.16 range).",
    "quick.range.wandMult=2",
    "# A wand quick hit farther than quick.range.wand from the cast deals this % (Skyy 2026-10-10: half; 100 = no falloff).",
    "quick.farPercent=50",''')

# ---------------------------------------------------------------------------------------------------------------- loader + texts
rep('''  HOP_FORCE = dec(c.getProperty("hop.force"), 22.0, 0.0, 50.0);      // 0.1.16: Skyy "a little too far" 30 -> 22 (0.1.3: "30", max 25 -> 50)''',
    '''  HOP_FORCE = dec(c.getProperty("hop.force"), 18.0, 0.0, 50.0);      // 0.1.17: Skyy "reduce how far" 22 -> 18 (0.1.16: 30 -> 22, 0.1.3: "30")''')
rep('''  ORB_SECONDS = dec(c.getProperty("orb.seconds"), 3.5, 0.5, 8.0);''',
    '''  ORB_SECONDS = dec(c.getProperty("orb.seconds"), 5.0, 0.5, 8.0);          // 0.1.17: Skyy "last a little longer" 3.5 -> 5''')
rep('''  RANGE_WAND = intOf(c.getProperty("quick.range.wand"), 16, 4, 64);
''', '''  RANGE_WAND = intOf(c.getProperty("quick.range.wand"), 16, 4, 64);
  RANGE_WAND_X = dec(c.getProperty("quick.range.wandMult"), 2.0, 1.0, 4.0);          // 0.1.17: Skyy "double the range"
  FAR_PCT = intOf(c.getProperty("quick.farPercent"), 50, 0, 100);          // 0.1.17: "half damage for the second half"
''')
rep('''    + "%/s every " + ORB_TICK + " s (party " + ORB_PARTY_PCT + "%, others " + ORB_OTHERS_PCT + "%) - quick shots: wand " + RANGE_WAND
    + " blocks, pierce "''', '''    + "%/s every " + ORB_TICK + " s at the landing spot (party " + ORB_PARTY_PCT + "%, others " + ORB_OTHERS_PCT + "%) - quick shots: wand " + RANGE_WAND
    + " blocks full damage, flies x" + RANGE_WAND_X + " (" + FAR_PCT + "% past), pierce "''')
# the wand quick orb's whole flight (quick.range.wand x quick.range.wandMult)
rep('''M(cfg, "public static void useDefaults() { apply(props(DEF_CFG)); }")
''', '''M(cfg, "public static void useDefaults() { apply(props(DEF_CFG)); }")
M(cfg, "public static double wandReach() { return (double) RANGE_WAND * (RANGE_WAND_X > 1.0 ? RANGE_WAND_X : 1.0); }")          # 0.1.17
''')

# ---------------------------------------------------------------------------------------------------------------- migrate017 (two keys, one marker)
_a = s.index('for f in ("public static final String M14_KEY1 = \\"blink.distance\\";"')
_b = s.index('}""")\n', s.index('public static synchronized String migrate014()')) + len('}""")\n')
_m14 = s[_a:_b]
assert _m14.count("migrate014") == 1 and _m14.count("m14Key") == 3 and _m14.count('M14_OLD1 = \\"10\\"') == 1, "the migrate014 block moved"
_m17 = (_m14.replace("M14_", "M17_").replace("m14Key", "m17Key").replace("m14Update", "m17Update").replace("m14Log", "m17Log")
        .replace("migrate014", "migrate017"))
for _o, _n in (('M17_KEY1 = \\"blink.distance\\"', 'M17_KEY1 = \\"hop.force\\"'), ('M17_OLD1 = \\"10\\"', 'M17_OLD1 = \\"22\\"'),
               ('M17_NEW1 = \\"16\\"', 'M17_NEW1 = \\"18\\"'), ('M17_KEY2 = \\"blink.floorCheck\\"', 'M17_KEY2 = \\"orb.seconds\\"'),
               ('M17_OLD2 = \\"12\\"', 'M17_OLD2 = \\"3.5\\"'), ('M17_NEW2 = \\"0\\"', 'M17_NEW2 = \\"5\\"'),
               ('M17_WHO = \\"SkyyArmory 0.1.4\\"', 'M17_WHO = \\"SkyyArmory 0.1.17\\"'),
               ('" kept (custom) - the 0.1.4 default is "', '" kept (custom) - the 0.1.17 default is "'),
               ('"before the 0.1.4 staff blink reach update"', '"before the 0.1.17 wand hop + heal aura update"'),
               ('"config.properties NOT updated to the 0.1.4 staff blink reach:', '"config.properties NOT updated to the 0.1.17 wand hop + heal aura:'),
               ('"config.properties updated to the 0.1.4 staff blink reach: " + chg + " (Skyy 2026-10-06; the old file',
                '"config.properties updated to the 0.1.17 wand hop + heal aura: " + chg + " (Skyy 2026-10-10: reduce how far, last a little longer; the old file'),
               ('"config.properties: no blink.distance / blink.floorCheck line held the old 10 / 12 - nothing changed (0.1.4 blink reach marker added)"',
                '"config.properties: no hop.force / orb.seconds line held the old 22 / 3.5 - nothing changed, the new defaults 18 / 5 apply (0.1.17 marker added)"'),
               ('"could not update config.properties to the 0.1.4 staff blink reach (the file is used as it is): "',
                '"could not update config.properties to the 0.1.17 wand hop + heal aura (the file is used as it is): "')):
    assert _m17.count(_o) == 1, "m17 clone anchor: " + _o
    _m17 = _m17.replace(_o, _n)
assert "0.1.4" not in _m17 and "M14" not in _m17 and "m14" not in _m17 and "blink" not in _m17, \
    [l_ for l_ in _m17.split("\n") if "0.1.4" in l_ or "14" in l_ or "blink" in l_][:5]
s = s[:_b] + ("# 0.1.17 (Skyy 2026-10-10: \"reduce how far\", \"last a little longer\"): hop.force 22 -> 18 + orb.seconds 3.5 -> 5 ONCE - the "
              "migrate014 steps (two keys, one marker), same rules (PROJECT-RULES 4); runs AFTER migrate016 (30 -> 22), so 13 -> 30 -> 22 -> 18 chains\n") + _m17 + s[_b:]
rep('''  String m16 = @PKG@.ArmoryCfg.migrate016();          // 0.1.16: a hop.force line still at 30 becomes 22 ONCE (same rules; after 0.1.3's 13 -> 30)
''', '''  String m16 = @PKG@.ArmoryCfg.migrate016();          // 0.1.16: a hop.force line still at 30 becomes 22 ONCE (same rules; after 0.1.3's 13 -> 30)
  String m17 = @PKG@.ArmoryCfg.migrate017();          // 0.1.17: hop.force 22 -> 18 + orb.seconds 3.5 -> 5 ONCE (same rules; after 0.1.16's 30 -> 22)
''')
rep('''(m16.length() > 0 ? "; " + m16 : ""));''', '''(m16.length() > 0 ? "; " + m16 : "") + (m17.length() > 0 ? "; " + m17 : ""));''')
rep('''  @PKG@.ArmoryTrav.LASTHOP.clear();
''', '''  @PKG@.ArmoryTrav.LASTHOP.clear();
  @PKG@.ArmoryTrav.FAR_LOGGED = false;          // 0.1.17
''', count=2)          # setup + shutdown

# ---------------------------------------------------------------------------------------------------------------- TravMath.groundY (pure)
rep('''# 1 = a landing spot (body free + ground below), 0 = body free but no ground (void: the scan goes on, never lands there), -1 = blocked''',
    '''# 0.1.17: the top of the first solid block within depth blocks under the feet column (the heal aura's spot when the caster has not landed
# after 3 s); NaN = none (void / unknown below - the aura then stays at the caster's own position, never projected into the void)
M(tmath, r"""
public static double groundY(@PKG@.TravGrid g, double x, double y, double z, int depth) {
  if (g == null || depth <= 0) return Double.NaN;
  int bx = (int) Math.floor(x);
  int bz = (int) Math.floor(z);
  int by = (int) Math.floor(y + 0.05);
  for (int i = 1; i <= depth; i++) {
    int c = g.at(bx, by - i, bz);
    if (c == 1) return (double) (by - i + 1);
    if (c < 0) return Double.NaN;
  }
  return Double.NaN;
}""")
# 0.1.17: the wand quick words with the far part ("pierces - 32 blocks (50% past 16)"); off / no quick shot = quickWords
M(tmath, r"""
public static String quickWordsW(boolean has, boolean on, int pierceMax, int full, double mult, int farPct) {
  if (!has || !on || !(mult > 1.0)) return quickWords(false, has, on, pierceMax, full);
  String w = quickWords(false, has, on, pierceMax, (int) Math.round((double) full * mult));
  return farPct < 100 ? w + " (" + farPct + "% past " + full + ")" : w;
}""")
# 1 = a landing spot (body free + ground below), 0 = body free but no ground (void: the scan goes on, never lands there), -1 = blocked''')
# quickWords is defined after ground(): quickWordsW must follow it - move the helper below quickWords instead
_qa = s.index('# 0.1.17: the wand quick words with the far part')
_qb = s.index('# 1 = a landing spot (body free + ground below)', _qa)
_qw = s[_qa:_qb]
s = s[:_qa] + s[_qb:]
_qc = s.index('}""")\n', s.index('public static String quickWords(boolean staff')) + len('}""")\n')
s = s[:_qc] + _qw + s[_qc:]
assert s.index("public static String quickWordsW") > s.index("public static String quickWords(boolean staff")
rep('''        @PKG@.TravMath.quickWords(false, @PKG@.ArmoryDefs.W_QORB[i].length() > 0, @PKG@.ArmoryCfg.PART_TRAV, @PKG@.ArmoryCfg.PIERCE_MAX, @PKG@.ArmoryCfg.RANGE_WAND),''',
    '''        @PKG@.TravMath.quickWordsW(@PKG@.ArmoryDefs.W_QORB[i].length() > 0, @PKG@.ArmoryCfg.PART_TRAV, @PKG@.ArmoryCfg.PIERCE_MAX, @PKG@.ArmoryCfg.RANGE_WAND,
          @PKG@.ArmoryCfg.RANGE_WAND_X, @PKG@.ArmoryCfg.FAR_PCT),          // 0.1.17: the doubled range + the far part''')

# ---------------------------------------------------------------------------------------------------------------- TravShot: full range + land
rep('''          "public double utHeal;", "public double utDmg;"):          # 0.1.15: the Second Opinion's heal % / damage % (SkyyGear's numbers)
    F(tshot, f)''', '''          "public double utHeal;", "public double utDmg;",          # 0.1.15: the Second Opinion's heal % / damage % (SkyyGear's numbers)
          "public double full;",          # 0.1.17: a wand quick shot's full-damage range (0 = no falloff); a hit farther from sx/sy/sz = quick.farPercent
          "public boolean land;"):          # 0.1.17: a wand charged orb of a hop - its heal aura appears where the caster lands
    F(tshot, f)''')
rep('''  n.utPierce = this.utPierce;          // 0.1.15
''', '''  n.utPierce = this.utPierce;          // 0.1.15
  n.full = this.full;          // 0.1.17: the continuation keeps the full-damage range (and the first launch's start)
''')

# ---------------------------------------------------------------------------------------------------------------- TravWorld: the landing watches
rep('''F(tworld, "public java.util.ArrayList rico;")          # 0.1.14: the wand signature's ricochet chains (RicoChain, this world's thread only)
''', '''F(tworld, "public java.util.ArrayList rico;")          # 0.1.14: the wand signature's ricochet chains (RicoChain, this world's thread only)
# 0.1.17: caster UUID -> double[8] { armed at, give up at, seen airborne, landed, x, y, z, keep until } and caster -> the heal aura (TravFx)
# waiting for that landing (this world's thread only)
F(tworld, "public java.util.HashMap land;")
F(tworld, "public java.util.HashMap landFx;")
''')
rep('''  this.rico = new java.util.ArrayList();
}""")''', '''  this.rico = new java.util.ArrayList();
  this.land = new java.util.HashMap();
  this.landFx = new java.util.HashMap();
}""")''')
rep('''&& this.books.isEmpty() && this.rico.isEmpty(); }")''', '''&& this.books.isEmpty() && this.rico.isEmpty() && this.land.isEmpty() && this.landFx.isEmpty(); }")''')

# ---------------------------------------------------------------------------------------------------------------- ArmoryTrav: arm (before Leap) ...
rep('''# the player's own jump speed (MovementManager settings - Acrobatics boosts included; the Monk's reader) and ground flag; unreadable = 11.8 / ground''',
    '''# ---- 0.1.17 THE HEAL AURA AT THE LANDING SPOT (Skyy 2026-10-10: "make the healing aura appear where you land"): the hop's caster is watched
# from the end of the hang (Leap.fire; the 0.1.2 hop job: from the hop) until the first on-ground tick (landTick); LAND_ON is also a harness seam
for f in ("public static volatile boolean LAND_ON = true;", "public static final long LAND_WAIT_MS = 3000L;", "public static final long LAND_MIN_MS = 400L;",
          "public static final long LAND_KEEP_MS = 10000L;", "public static final int LAND_DOWN = 8;", "public static final double LAND_UP = 0.5;",
          "public static volatile long LANDINGS = 0L;", "public static volatile long LAND_TIMEOUTS = 0L;", "public static volatile long LAND_AURAS = 0L;",
          "public static volatile long LAND_LOST = 0L;", "public static volatile long FAR_HITS = 0L;", "public static volatile boolean FAR_LOGGED = false;"):
    F(trav, f)
M(trav, r"""
public static void landArm(Object st, java.util.UUID u, long now) {
  if (!LAND_ON || st == null || u == null) return;
  @PKG@.TravWorld tw = @PKG@.TravWorld.get(st);
  if (tw == null) return;
  if (tw.land.size() > 256) tw.land.clear();          // bounded (a watch matters for seconds only)
  tw.land.put(u, new double[] { (double) now, (double) (now + LAND_WAIT_MS), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 });
}""")
# the player's own jump speed (MovementManager settings - Acrobatics boosts included; the Monk's reader) and ground flag; unreadable = 11.8 / ground''')
rep('''  v.addInstruction(new @VEC@(hv[0], vy, hv[2]), dash(), @CVT@.Set);
  markHop(j.u, now);
  HOPS = HOPS + 1L;''', '''  v.addInstruction(new @VEC@(hv[0], vy, hv[2]), dash(), @CVT@.Set);
  markHop(j.u, now);
  landArm(st, j.u, now);          // 0.1.17: the 0.1.2 hop job (no hang) - the heal aura where you land
  HOPS = HOPS + 1L;''')
rep('''  if (s.kind == 1 && s.u != null && s.pid != null) {          // 0.1.16: also known by its caster + id (never a second leap)''',
    '''  ts.land = s.kind == 1;          // 0.1.17: the wand's orb - its heal aura appears where the caster lands
  if (s.kind == 1) @PKG@.ArmoryTrav.landArm(st, s.u, System.currentTimeMillis());          // 0.1.17: the hang is over - watch for the landing
  if (s.kind == 1 && s.u != null && s.pid != null) {          // 0.1.16: also known by its caster + id (never a second leap)''')

# ---------------------------------------------------------------------------------------------------------------- added(): range x2 + land flag
rep('''      s = new @PKG@.TravShot(p.x, p.y, p.z, (double) (c < 2000 ? @PKG@.ArmoryCfg.RANGE_WAND : @PKG@.ArmoryCfg.RANGE_STAFF), c, cu, pid);
''', '''      s = new @PKG@.TravShot(p.x, p.y, p.z, c < 2000 ? @PKG@.ArmoryCfg.wandReach() : (double) @PKG@.ArmoryCfg.RANGE_STAFF, c, cu, pid);
      if (c < 2000 && @PKG@.ArmoryCfg.RANGE_WAND_X > 1.0) s.full = (double) @PKG@.ArmoryCfg.RANGE_WAND;          // 0.1.17: x2, the far part less
''')
rep('''    utMark(ws, buf, cu, c);          // 0.1.15: the Second Opinion's heal numbers
    tw.orbs.put(ref, ws);
    if (own) return;
    if (!@PKG@.ArmoryCfg.PART_TRAV || cu == null || !HOP_SERVER) return;''', '''    utMark(ws, buf, cu, c);          // 0.1.15: the Second Opinion's heal numbers
    ws.land = own && (lp == null || lp.land);          // 0.1.17: the re-launched orb of a hop - its heal aura where the caster lands
    tw.orbs.put(ref, ws);
    if (own) return;
    if (!@PKG@.ArmoryCfg.PART_TRAV || cu == null || !HOP_SERVER) return;
    ws.land = true;          // 0.1.17: the 0.1.2 hop job below (no hang): the aura waits for its landing (a refused hop arms nothing = the burst spot)''')

# ---------------------------------------------------------------------------------------------------------------- burst: the aura waits for the landing
rep('''# the burst (spec 1.2 + 2.4): every OTHER enemy within burst.radius takes burst.percent % of dmgBase; then the heal orb (healBase)''',
    '''# 0.1.17: put a heal aura down at x / y / z NOW (it lasts orb.seconds from now; its ring + pulse are drawn where it is)
M(trav, r"""
public static void landPlace(@PKG@.TravWorld tw, @PKG@.TravFx f, double x, double y, double z, @CB@ buf, long now) {
  if (tw == null || f == null) return;
  f.ax = x;
  f.ay = y;
  f.az = z;
  f.bx = x;
  f.by = y;
  f.bz = z;
  f.until = now + Math.round(@PKG@.ArmoryCfg.ORB_SECONDS * 1000.0);
  f.next = now + f.step;
  f.fxNext = 0L;
  tw.add(f, @PKG@.ArmoryCfg.TRAV_MAXLIVE, now);
  sound(SND_HEAL, x, y, z, buf);
  LAND_AURAS = LAND_AURAS + 1L;
}""")
# 0.1.17: true = the aura of this burst goes where the caster lands (placed now when they already landed, else it waits in tw.landFx);
# false = no watch for this caster (no hop / LAND_ON off) - the 0.1.16 spot
M(trav, r"""
public static boolean landHold(@PKG@.TravWorld tw, @PKG@.TravShot s, @PKG@.TravFx f, @CB@ buf, long now) {
  if (!LAND_ON || tw == null || s == null || !s.land || s.caster == null || f == null) return false;
  Object o = tw.land.get(s.caster);
  if (!(o instanceof double[])) return false;
  double[] e = (double[]) o;
  if (e[3] > 0.5) {
    tw.land.remove(s.caster);
    landPlace(tw, f, e[4], e[5] + LAND_UP, e[6], buf, now);
    return true;
  }
  Object old = tw.landFx.put(s.caster, f);
  if (old instanceof @PKG@.TravFx && old != f) { @PKG@.TravFx of = (@PKG@.TravFx) old; landPlace(tw, of, of.ax, of.ay, of.az, buf, now); }
  return true;
}""")
# 0.1.17: once per world tick (TravWorld.run): each watched caster - landed (on the ground after being airborne, or LAND_MIN_MS after the arm
# while standing) -> the spot; LAND_WAIT_MS without a landing -> the ground under them within LAND_DOWN blocks, else their own position; a
# waiting aura goes there; the caster gone / dead = the aura at its burst spot; a landed watch nobody used is dropped after LAND_KEEP_MS
M(trav, r"""
public static void landTick(@PKG@.TravWorld tw, @ST@ st, @CB@ buf, long now) {
  if (tw == null || (tw.land.isEmpty() && tw.landFx.isEmpty())) return;
  java.util.Iterator it = tw.land.entrySet().iterator();
  while (it.hasNext()) {
    java.util.Map.Entry en = (java.util.Map.Entry) it.next();
    java.util.UUID u = (java.util.UUID) en.getKey();
    double[] e = (double[]) en.getValue();
    @PKG@.TravFx f = (@PKG@.TravFx) tw.landFx.get(u);
    @REF@ r = null;
    try { r = ((@ES@) buf.getExternalData()).getRefFromUUID(u); } catch (Throwable t0) { r = null; }
    boolean gone = false;
    try { gone = r == null || !r.isValid() || dead(buf, r); } catch (Throwable t1) { gone = true; }
    if (gone) {
      it.remove();
      tw.landFx.remove(u);
      LAND_LOST = LAND_LOST + 1L;
      if (f != null) landPlace(tw, f, f.ax, f.ay, f.az, buf, now);
      continue;
    }
    if (e[3] < 0.5) {
      @VEC@ p = posOf(buf, r);
      if (p == null) continue;
      boolean g = grounded(buf, r);
      if (!g) e[2] = 1.0;
      if (g && (e[2] > 0.5 || (double) now - e[0] >= (double) LAND_MIN_MS)) {
        e[3] = 1.0; e[4] = p.x; e[5] = p.y; e[6] = p.z; e[7] = (double) (now + LAND_KEEP_MS);
        LANDINGS = LANDINGS + 1L;
      } else if ((double) now >= e[1]) {
        double gy = Double.NaN;
        try { gy = @PKG@.TravMath.groundY(grid(worldOf(buf)), p.x, p.y, p.z, LAND_DOWN); } catch (Throwable t2) { gy = Double.NaN; }
        e[3] = 1.0; e[4] = p.x; e[5] = Double.isNaN(gy) ? p.y : gy; e[6] = p.z; e[7] = (double) (now + LAND_KEEP_MS);
        LAND_TIMEOUTS = LAND_TIMEOUTS + 1L;
      } else continue;
    }
    if (f != null) {
      it.remove();
      tw.landFx.remove(u);
      landPlace(tw, f, e[4], e[5] + LAND_UP, e[6], buf, now);
    } else if ((double) now >= e[7]) it.remove();
  }
  if (!tw.landFx.isEmpty()) {          // an aura without a watch (its watch was dropped): at its burst spot
    java.util.Iterator io = tw.landFx.entrySet().iterator();
    while (io.hasNext()) {
      java.util.Map.Entry eo = (java.util.Map.Entry) io.next();
      if (tw.land.containsKey(eo.getKey())) continue;
      io.remove();
      @PKG@.TravFx fo = (@PKG@.TravFx) eo.getValue();
      landPlace(tw, fo, fo.ax, fo.ay, fo.az, buf, now);
    }
  }
}""")
# the burst (spec 1.2 + 2.4): every OTHER enemy within burst.radius takes burst.percent % of dmgBase; then the heal orb (healBase)''')
rep('''    tw.add(new @PKG@.TravFx(2, cx, cy, cz, cx, cy, cz, @PKG@.ArmoryCfg.ORB_RADIUS, now + Math.round(@PKG@.ArmoryCfg.ORB_SECONDS * 1000.0), now + step, step,
      per, s.caster, null, s.code), @PKG@.ArmoryCfg.TRAV_MAXLIVE, now);
    sound(SND_HEAL, cx, cy, cz, buf);''', '''    @PKG@.TravFx hf = new @PKG@.TravFx(2, cx, cy, cz, cx, cy, cz, @PKG@.ArmoryCfg.ORB_RADIUS, now + Math.round(@PKG@.ArmoryCfg.ORB_SECONDS * 1000.0), now + step, step,
      per, s.caster, null, s.code);
    if (!landHold(tw, s, hf, buf, now)) {          // 0.1.17: a hop's orb - the aura where the caster lands; else here (0.1.16)
      tw.add(hf, @PKG@.ArmoryCfg.TRAV_MAXLIVE, now);
      sound(SND_HEAL, cx, cy, cz, buf);
    }''')
rep('''public void run(@ST@ st, @CB@ buf, long now) {
  for (int k = this.fx.size() - 1; k >= 0; k--) {''', '''public void run(@ST@ st, @CB@ buf, long now) {
  try { @PKG@.ArmoryTrav.landTick(this, st, buf, now); } catch (Throwable tl) { @PKG@.ArmoryTrav.warn("land", "the heal aura landing watch failed (" + tl + ")"); }          // 0.1.17
  for (int k = this.fx.size() - 1; k >= 0; k--) {''')

# ---------------------------------------------------------------------------------------------------------------- the far-hit factor (ArmoryTuneSys)
rep('''# ArmoryTuneSys (Filter group): true = this pierce chain already hit that enemy (the hit is cancelled - "hitting each" once)''',
    '''# 0.1.17 (Skyy: "double the range ... the added range does less damage"): a WAND quick orb's hit farther than its full-damage range from the
# cast point (TravShot sx/sy/sz, kept by pierce continuations) = x quick.farPercent / 100; else 1 (staff / other shots / no record / x1)
M(trav, r"""
public static float farFactor(@ST@ st, @CB@ buf, @REF@ pj, @REF@ tg, @DMG@ d, String pid) {
  try {
    if (pj == null || pid == null) return 1.0f;
    int c = @PKG@.ArmoryDefs.pidCode(pid);
    if (c < 1000 || c >= 2000) return 1.0f;
    @PKG@.TravWorld tw = @PKG@.TravWorld.of(st);
    if (tw == null) return 1.0f;
    @PKG@.TravShot s = (@PKG@.TravShot) tw.quick.get(pj);
    if (s == null || !(s.full > 0.0) || !(s.range > s.full)) return 1.0f;
    double[] h = null;
    try {
      Object o = d == null ? null : d.getIfPresentMetaObject(@DMG@.HIT_LOCATION);
      if (o instanceof @V4@) { @V4@ v4 = (@V4@) o; h = new double[] { v4.x, v4.y, v4.z }; }
      else if (o instanceof @VEC@) { @VEC@ v3 = (@VEC@) o; h = new double[] { v3.x, v3.y, v3.z }; }
    } catch (Throwable t0) { h = null; }
    double dist = -1.0;
    if (h != null) {
      double dx = h[0] - s.sx;
      double dy = h[1] - s.sy;
      double dz = h[2] - s.sz;
      dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
    } else {
      // no hit location -> the NEARER of the orb's position (it may already be past the target) and the target's chest
      @VEC@ pp = posOf(buf, pj);
      if (pp != null) {
        double ax = pp.x - s.sx;
        double ay = pp.y - s.sy;
        double az = pp.z - s.sz;
        dist = Math.sqrt(ax * ax + ay * ay + az * az);
      }
      if (tg != null) {
        @VEC@ tp = posOf(buf, tg);
        if (tp != null) {
          double bx = tp.x - s.sx;
          double by = tp.y + 0.9 - s.sy;
          double bz = tp.z - s.sz;
          double db = Math.sqrt(bx * bx + by * by + bz * bz);
          if (dist < 0.0 || db < dist) dist = db;
        }
      }
    }
    if (dist < 0.0) return 1.0f;
    if (!(dist > s.full)) return 1.0f;
    FAR_HITS = FAR_HITS + 1L;
    float f = (float) ((double) @PKG@.ArmoryCfg.FAR_PCT / 100.0);
    if (!FAR_LOGGED) {
      FAR_LOGGED = true;
      @PKG@.ArmoryLog.info("first far wand quick hit after start: " + @PKG@.TravMath.fmt(dist) + " blocks from the cast (full damage up to "
        + @PKG@.TravMath.fmt(s.full) + ", the orb flies " + @PKG@.TravMath.fmt(s.range) + ") - damage x" + f + " (quick.farPercent " + @PKG@.ArmoryCfg.FAR_PCT + ")");
    }
    return f;
  } catch (Throwable t) { return 1.0f; }
}""")
# ArmoryTuneSys (Filter group): true = this pierce chain already hit that enemy (the hit is cancelled - "hitting each" once)''')
rep('''      if (chunk != null && !d0.isCancelled() && s0 instanceof @DPRJ@ && @PKG@.ArmoryTrav.repeatHit(st, ((@DPRJ@) s0).getProjectile(), chunk.getReferenceTo(idx), pidOf(buf, ((@DPRJ@) s0).getProjectile()))) d0.setCancelled(true);
      return;''', '''      if (chunk != null && !d0.isCancelled() && s0 instanceof @DPRJ@ && @PKG@.ArmoryTrav.repeatHit(st, ((@DPRJ@) s0).getProjectile(), chunk.getReferenceTo(idx), pidOf(buf, ((@DPRJ@) s0).getProjectile()))) d0.setCancelled(true);
      if (!d0.isCancelled() && s0 instanceof @DPRJ@) {          // 0.1.17: the far part of a wand quick shot, the tune off too
        @REF@ p0 = ((@DPRJ@) s0).getProjectile();
        @REF@ g0 = null;
        if (chunk != null) g0 = chunk.getReferenceTo(idx);
        float ff0 = @PKG@.ArmoryTrav.farFactor(st, buf, p0, g0, d0, pidOf(buf, p0));
        if (ff0 != 1.0f) d0.setAmount(d0.getAmount() * ff0);
      }
      return;''')
rep('''    int bk0 = @PKG@.ArmoryDefs.pidCode(pid);
    if (bk0 >= 7000 && bk0 < 8000) f = (float) (@PKG@.ArmoryCfg.BOOK_K / @PKG@.ArmoryDefs.BOOK_KDEF);          // 0.1.6: every Page Burst hit x book.k / 0.4''',
    '''    int bk0 = @PKG@.ArmoryDefs.pidCode(pid);
    if (bk0 >= 7000 && bk0 < 8000) f = (float) (@PKG@.ArmoryCfg.BOOK_K / @PKG@.ArmoryDefs.BOOK_KDEF);          // 0.1.6: every Page Burst hit x book.k / 0.4
    if (bk0 >= 1000 && bk0 < 2000) {          // 0.1.17: the far part of a wand quick shot, once
      @REF@ g1 = null;
      if (chunk != null) g1 = chunk.getReferenceTo(idx);
      f = f * @PKG@.ArmoryTrav.farFactor(st, buf, ((@DPRJ@) src).getProjectile(), g1, d, pid);
    }''')

# ---------------------------------------------------------------------------------------------------------------- prints
rep('''print("0.1.16 wand hop: one hop per cast''', '''print("0.1.17 wand round: hop.force default %s, orb.seconds default %s (one-time update marker %r); heal aura at the landing spot (wait %d s, "
      "ground look %d blocks); wand quick range x%s (row quick.range.wandMult), far hits %s%% (row quick.farPercent)" % (
          [r_[4] for r_ in CFG_NEW if r_[0] == "hop.force"][0], [r_[4] for r_ in CFG_NEW if r_[0] == "orb.seconds"][0], M17_MARK_ID, 3, 8,
          [r_[4] for r_ in CFG_NEW if r_[0] == "quick.range.wandMult"][0], [r_[4] for r_ in CFG_NEW if r_[0] == "quick.farPercent"][0]))
print("0.1.16 wand hop: one hop per cast''')
rep('''one hop per cast (re-launch known by caster + id within %d ms, same-cast guard %d ms), hop.force default 22 (one-time update "''',
    '''one hop per cast (re-launch known by caster + id within %d ms, same-cast guard %d ms), hop.force 30 -> 22 (one-time update "''')

with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(s.replace(LF, NL))
print("wrote %s" % os.path.relpath(DST, ROOT))

if os.environ.get("ARMORY0117_BUILD_ONLY"):
    raise SystemExit(0)
# ================================================================================================================ the harness
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.16 - test harness. GENERATED by tools/armory_0_1_16_patch.py from test_skyyarmory_0.1.15.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.17 - test harness. GENERATED by tools/armory_0_1_17_patch.py from test_skyyarmory_0.1.16.py - edit the patch, never this file.
Run: python SkyyArmory/test_skyyarmory_0.1.17.py --dir tools/dev/scratch/<task>/harness   (--no-set skips the one-JVM SET run, --keep keeps it)
Every 0.1.16 check still runs on the 0.1.16 shape: the jar's files are 0.1.16's (P19 proves it: only the classes + the manifest version differ);
the classes are the real 0.1.17 ones; the old wand / range / heal-orb checks run with the 0.1.16 numbers pinned where they need them (hop.force
22 in R19, orb.seconds 3.5 + quick.range.wandMult 1 + the landing watch off in N - the exact 0.1.16 behaviour); the default-row checks read the
new defaults (hop.force 18, orb.seconds 5, the doubled quick words); R19g now compares 0.1.15 -> 0.1.16 (history), R20g 0.1.16 -> 0.1.17.
NEW P19 (Python) + R20 (JVM, after R19) EXECUTE every 0.1.17 path:
  P19  vs the 0.1.16 jar: every non-class file byte-identical except the manifest (its version only), the same classes
  R20  a: the rows + defaults (hop.force 18, orb.seconds 5, quick.range.wandMult 2, quick.farPercent 50 + clamps), the default file, armory:trav
       + armory:fn:info words ("pierces - 32 blocks (50% past 16)"), TravMath.quickWordsW / groundY (pure); b: THE RANGE x2 - a wand quick orb's
       record (32, full 16), TravTick keeps it at 20 blocks and removes it past 32 (MUTANT quick.range.wandMult 1 = the 0.1.16 16), the pierce
       continuation at 20 blocks, a staff quick orb unchanged (24, no full); c: THE FAR HALF on REAL Damage objects through
       ArmoryTuneSys.handle (the real dispatch shape): 10 blocks full, 20 blocks x0.5 ONCE, by the hit location / the orb's position, the pierce
       continuation keeps the start + the full range, part.tune off too, farPercent 100 / mult 1 = full, a staff quick orb untouched;
       d: THE HEAL AURA AT THE LANDING SPOT - a full wand cast end to end (hop 18 -> rise -> the hang unchanged -> re-launch -> the burst in
       mid-air): the burst damage at the hit, the aura WAITS, the first on-ground tick puts it where the caster landed (5 s), MUTANT landing
       watch off = the 0.1.16 burst spot; the landing before the burst; standing (0.4 s); no landing in 3 s = the ground under them / their
       position over the void; the caster gone = the burst spot; the 0.1.2 hop job; a hop refused for Stamina = the burst spot; the aura heals
       at the new spot; e: THE ONE-TIME UPDATE (hop.force 22 -> 18 + orb.seconds 3.5 -> 5, one marker; the text step + the real migrate017 on a
       scratch file: History copy, 2 change-log lines, idle second run; 13 / 30 / 22 all end at 18, a hand-set value kept); f: the hop numbers
       at 18 (the hang 0.35 s / 1.5 b/s unchanged); g: vs the 0.1.16 jar method by method (only the planned methods / fields differ).

0.1.16 harness: SkyyArmory 0.1.16 - test harness. GENERATED by tools/armory_0_1_16_patch.py from test_skyyarmory_0.1.15.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.16"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.16 SkyyArmory"',
     'VERSION = "0.1.17"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.17 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory0116", "harness")', 'os.path.join(SCRATCH_ROOT, "armory0117", "harness")')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.16.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.17.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.16"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.17"))')
for _v in ('"[SkyyArmory] 0.1.16 ready" in m_', '"0.1.16 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_',
           '"0.1.16 crossbow grapple: grapple on" in m_',
           '"0.1.16 monk moves on - Pole-Vault (Bo hold): lunge 3 in 0.2 s, 4.5 up x 7 forward (push x2.1)" in m_',
           '"0.1.16 wand signature on - the signature key when the meter is full (20; quick-shot hit +1, charged hit +2)" in m_',
           'come from Skyy:0.1.16 SkyyArmory" in str(r[1])'):
    hrep(_v, _v.replace("0.1.16", "0.1.17"))
hrep('t_.replace("0.1.16", "V").replace("0.1.15", "V")', 't_.replace("0.1.17", "V").replace("0.1.16", "V").replace("0.1.15", "V")')
hrep("    MN19, MO19 = methods_of(JAR), methods_of(OLD115)",
     "    MN19, MO19 = methods_of(OLD116), methods_of(OLD115)          # 0.1.17: R19g = the 0.1.16 round's compare (history); R20g = 0.1.16 -> 0.1.17")
hrep('OLD115 = os.path.join(HERE, "SkyyArmory-0.1.15.jar")          # 0.1.16: the base (the SET pin)\n',
     '''OLD115 = os.path.join(HERE, "SkyyArmory-0.1.15.jar")          # 0.1.16: the base (the SET pin)
OLD116 = os.path.join(HERE, "SkyyArmory-0.1.16.jar")          # 0.1.17: the base (the SET pin)
if not os.path.isfile(OLD116):
    raise SystemExit("the 0.1.17 harness needs SkyyArmory-0.1.16.jar (the base, the SET pin) next to it: %s" % OLD116)
''')
# the setup()-twice check: + the 0.1.17 text step and its marker
hrep('''        r16_ = ACfg.m16Update(t14_)          # 0.1.16: + the hop.force 30 -> 22 step
        want_ = (str(r16_[0]) if r16_ is not None else t14_).encode("latin-1")''', '''        r16_ = ACfg.m16Update(t14_)          # 0.1.16: + the hop.force 30 -> 22 step
        t16_ = str(r16_[0]) if r16_ is not None else t14_
        r17_ = ACfg.m17Update(t16_)          # 0.1.17: + hop.force 22 -> 18 / orb.seconds 3.5 -> 5
        want_ = (str(r17_[0]) if r17_ is not None else t16_).encode("latin-1")''')
hrep('''              and str(ACfg.M14_MARK_ID) in txt1_ and str(ACfg.M16_MARK_ID) in txt1_,''',
     '''              and str(ACfg.M14_MARK_ID) in txt1_ and str(ACfg.M16_MARK_ID) in txt1_ and str(ACfg.M17_MARK_ID) in txt1_,''')
# the old N checks on the 0.1.16 shape
hrep('''    ACfg.HOP_MAXUP = 0.0          # 0.1.16: no up cap (the 0.1.15 maths); the cap is checked in R19
''', '''    ACfg.HOP_MAXUP = 0.0          # 0.1.16: no up cap (the 0.1.15 maths); the cap is checked in R19
    ACfg.ORB_SECONDS = 3.5          # 0.1.17: N keeps the 0.1.16 heal orb (3.5 s) and range (x1); the 0.1.17 defaults are checked in R20
    ACfg.RANGE_WAND_X = 1.0
''')
hrep('''    AT.DUP_MS = 0          # 0.1.16: the older checks run the 0.1.15 hop logic (their casts come in the same ms); R19 switches the guards on
''', '''    AT.DUP_MS = 0          # 0.1.16: the older checks run the 0.1.15 hop logic (their casts come in the same ms); R19 switches the guards on
    AT.LAND_ON = False          # 0.1.17: the older checks keep the heal orb at the burst spot (0.1.16); R20 switches the landing watch on
''')
hrep('''"blink.trailPercent": "30", "blink.tick": "0.5", "blink.cooldown": "0", "hop.force": "22", "burst.radius": "6",          # 0.1.16: 30 -> 22''',
     '''"blink.trailPercent": "30", "blink.tick": "0.5", "blink.cooldown": "0", "hop.force": "18", "burst.radius": "6",          # 0.1.17: 22 -> 18''')
hrep('''"burst.percent": "60", "orb.radius": "9", "orb.seconds": "3.5", "orb.healPercent": "20",''',
     '''"burst.percent": "60", "orb.radius": "9", "orb.seconds": "5", "orb.healPercent": "20",''')
hrep('''"quick.range.staff": "24", "quick.staffBonus": "15", "trav.staminaPercent": "50", "trav.staminaCap": "5"}''',
     '''"quick.range.staff": "24", "quick.staffBonus": "15", "trav.staminaPercent": "50", "trav.staminaCap": "5",
                "quick.range.wandMult": "2", "quick.farPercent": "50"}          # 0.1.17''')
hrep('''and str(a_w[9]) == "pierces - 16 blocks" and float(a_w[10]) == 0.0
          and str(a_0[8]) == "" and str(a_0[9]) == "pierces - 16 blocks"''', '''and str(a_w[9]) == "pierces - 32 blocks (50% past 16)" and float(a_w[10]) == 0.0
          and str(a_0[8]) == "" and str(a_0[9]) == "pierces - 32 blocks (50% past 16)"''')          # 0.1.17: the doubled range + the far part
hrep('''    want_l = {"hop.force": "22", "hop.maxUp": "15", "hop.hangSeconds": "0.35",          # 0.1.16: 30 -> 22 + the cap row''',
     '''    want_l = {"hop.force": "18", "hop.maxUp": "15", "hop.hangSeconds": "0.35",          # 0.1.17: 22 -> 18 (0.1.16: 30 -> 22 + the cap row)''')
hrep('''    check(abs(float(ACfg.HOP_FORCE) - 22.0) < 1e-9 and abs(float(ACfg.HOP_MAXUP) - 15.0) < 1e-9 and abs(float(ACfg.HOP_HANG) - 0.35) < 1e-9''',
     '''    check(abs(float(ACfg.HOP_FORCE) - 18.0) < 1e-9 and abs(float(ACfg.HOP_MAXUP) - 15.0) < 1e-9 and abs(float(ACfg.HOP_HANG) - 0.35) < 1e-9''')
hrep('''ltxt.startswith("wand hold: hop 22.0 (up at most 15.0 b/s, a jump never adds), one hop per cast, hang 0.35 s")''',
     '''ltxt.startswith("wand hold: hop 18.0 (up at most 15.0 b/s, a jump never adds), one hop per cast, hang 0.35 s")''')
hrep('''    check(hv11 is not None and hv11[0] == (0.0, 0.0, -22.0) and why11.startswith("hop full") and hv11b is not None and hv11b[0] == (0.0, 0.0, -22.0)          # 0.1.16: the default 22''',
     '''    check(hv11 is not None and hv11[0] == (0.0, 0.0, -18.0) and why11.startswith("hop full") and hv11b is not None and hv11b[0] == (0.0, 0.0, -18.0)          # 0.1.17: the default 18''')
# R19 on the 0.1.16 shape: hop.force 22 (its numbers), the landing watch off; its default-row checks read 0.1.17's 18
hrep('''        ACfg.useDefaults()
        ACfg.TRAV_FX = False
        AT.GRID = Grid(world_fn())
        AT.NEAR = Near()''', '''        ACfg.useDefaults()
        ACfg.HOP_FORCE = 22.0          # 0.1.17: R19 = the 0.1.16 shape (hop.force 22); R20 checks 18
        AT.LAND_ON = False
        ACfg.TRAV_FX = False
        AT.GRID = Grid(world_fn())
        AT.NEAR = Near()''')
hrep('''    check(d19.get("hop.force") == "22" and d19.get("hop.maxUp") == "15"''', '''    check(d19.get("hop.force") == "18" and d19.get("hop.maxUp") == "15"''')
hrep('''          and c19a == 50.0 and c19b == 0.0 and float(ACfg.HOP_FORCE) == 22.0 and float(ACfg.HOP_MAXUP) == 15.0 and "\\nhop.force=22\\n" in dc19''',
     '''          and c19a == 50.0 and c19b == 0.0 and float(ACfg.HOP_FORCE) == 18.0 and float(ACfg.HOP_MAXUP) == 15.0 and "\\nhop.force=18\\n" in dc19''')
hrep('''          and lt19.startswith("wand hold: hop 22.0 (up at most 15.0 b/s, a jump never adds), one hop per cast, hang 0.35 s"),''',
     '''          and lt19.startswith("wand hold: hop 18.0 (up at most 15.0 b/s, a jump never adds), one hop per cast, hang 0.35 s"),          # 0.1.17: 18''')

hrep('''"orb.tick", "orb.partyPercent", "orb.othersPercent", "pierce.max", "quick.range.wand", "quick.range.staff", "quick.staffBonus"]''',
     '''"orb.tick", "orb.partyPercent", "orb.othersPercent", "pierce.max", "quick.range.wand", "quick.range.wandMult", "quick.farPercent",
                "quick.range.staff", "quick.staffBonus"]          # 0.1.17: + the 2 wand quick rows''')
hrep('''"Quick shot - 3 Mana - %d damage at Lv 15 - pierces - 16 blocks" % fl(18 * mw_)]''',
     '''"Quick shot - 3 Mana - %d damage at Lv 15 - pierces - 32 blocks (50%% past 16)" % fl(18 * mw_)]          # 0.1.17: the doubled range''')

# ---- P19 (Python): vs the 0.1.16 jar every non-class file is byte-identical, the manifest differs in its version only
P19 = r'''
# ================================================================================================================ P19. 0.1.17: only the classes changed
OZ116 = zipfile.ZipFile(OLD116)
_n19, _o19 = set(JZ15.namelist()), set(OZ116.namelist())
_files19 = sorted(n_ for n_ in _n19 | _o19 if not n_.endswith(".class"))
_diff19 = [n_ for n_ in _files19 if n_ != "manifest.json" and (n_ not in _n19 or n_ not in _o19 or JZ15.read(n_) != OZ116.read(n_))]
_m19n, _m19o = json.loads(JZ15.read("manifest.json").decode("utf-8")), json.loads(OZ116.read("manifest.json").decode("utf-8"))
_m19o2 = dict(_m19o)
_m19o2["Version"] = VERSION
_m19o2["Name"] = str(_m19o.get("Name", "")).replace("0.1.16", VERSION)
check(not _diff19 and _m19n == _m19o2 and _m19o.get("Version") == "0.1.16",
      "P19: vs the 0.1.16 jar every one of the %d non-class files is byte-identical; the manifest differs only in its version (0.1.16 -> %s): %s" % (
          len(_files19), VERSION, _diff19[:5]))
_c19n, _c19o = sorted(n_ for n_ in _n19 if n_.endswith(".class")), sorted(n_ for n_ in _o19 if n_.endswith(".class"))
check(_c19n == _c19o, "P19: the same %d classes (none added / removed): %s" % (len(_c19n), sorted(set(_c19n) ^ set(_c19o))))
print("P19. 0.1.17: %d non-class files identical to 0.1.16, manifest version only, the same %d classes" % (len(_files19), len(_c19n)))
'''
hrep('''print("P18. 0.1.16: %d non-class files identical to 0.1.15, manifest version only, the same %d classes" % (len(_files18), len(_c18n)))
''', '''print("P18. 0.1.16: %d non-class files identical to 0.1.15, manifest version only, the same %d classes" % (len(_files18), len(_c18n)))
''' + P19)

# ---- R20 (JVM)
R20 = r'''    # ============================================================================ R20. 0.1.17 THE WAND ROUND - every new path EXECUTED
    TSh20 = JClass(PKG + "TravShot")
    MST20 = JClass("com.hypixel.hytale.protocol.MovementStates")

    def heals20(tw_):
        return [tw_.fx.get(k_) for k_ in range(tw_.fx.size()) if int(tw_.fx.get(k_).kind) == 2]

    def setup20(stam=10.0):          # the 0.1.17 defaults, the guards + the landing watch on, the caster standing (MovementStates onGround)
        fresh19(stam)
        ACfg.useDefaults()
        ACfg.TRAV_FX = False
        AT.LAND_ON = True
        AT.GRID = Grid(world_fn())
        guards19(True, True)
        ms_ = MSCc()
        mst_ = MST20()
        mst_.onGround = True
        ms_.setMovementStates(mst_)
        put(rc, MSCc.getComponentType(), ms_)
        return mst_

    def at20(r_, x, y, z):
        put(r_, TCc.getComponentType(), TCc(V3(x, y, z), R3(0.0, 0.0, 0.0)))

    # R20a THE ROWS + DEFAULTS + WORDS
    setup20()
    Rows20 = JClass(PKG + "CfgRows")
    k20 = [str(k_) for k_ in Rows20.KEYS]
    d20 = dict(zip(k20, [str(d_) for d_ in Rows20.DEFS]))
    h20 = dict(zip(k20, [str(h_) for h_ in Rows20.HELPS]))
    dc20 = str(ACfg.DEF_CFG)
    pr20 = Props()
    pr20.setProperty("quick.range.wandMult", "9")
    pr20.setProperty("quick.farPercent", "150")
    ACfg.apply(pr20)
    cl20a = (float(ACfg.RANGE_WAND_X), int(ACfg.FAR_PCT))
    pr20.setProperty("quick.range.wandMult", "0.5")
    pr20.setProperty("quick.farPercent", "-5")
    ACfg.apply(pr20)
    cl20b = (float(ACfg.RANGE_WAND_X), int(ACfg.FAR_PCT))
    ACfg.useDefaults()
    ACfg.TRAV_FX = False
    tt20 = str(br.get("armory:trav"))
    check(d20.get("hop.force") == "18" and d20.get("orb.seconds") == "5" and d20.get("quick.range.wandMult") == "2" and d20.get("quick.farPercent") == "50"
          and k20.index("quick.range.wandMult") == k20.index("quick.range.wand") + 1 and k20.index("quick.farPercent") == k20.index("quick.range.wand") + 2
          and max(len(h20["quick.range.wandMult"]), len(h20["quick.farPercent"]), len(h20["quick.range.wand"]), len(h20["orb.seconds"]), len(h20["hop.force"])) <= 100
          and float(ACfg.HOP_FORCE) == 18.0 and float(ACfg.ORB_SECONDS) == 5.0 and float(ACfg.RANGE_WAND_X) == 2.0 and int(ACfg.FAR_PCT) == 50
          and float(ACfg.wandReach()) == 32.0 and cl20a == (4.0, 100) and cl20b == (1.0, 0)
          and "\nhop.force=18\n" in dc20 and "\norb.seconds=5\n" in dc20 and "\nquick.range.wandMult=2\n" in dc20 and "\nquick.farPercent=50\n" in dc20
          and str(ACfg.M17_MARK) in dc20 and str(ACfg.M16_MARK) in dc20
          and "quick shots: wand 16 blocks full damage, flies x2.0 (50% past), pierce no cap" in tt20 and "s at the landing spot (party" in tt20,
          "R20a: the rows - hop.force 18, orb.seconds 5, quick.range.wandMult 2 + quick.farPercent 50 right after quick.range.wand (helps <= 100), the loader "
          "(9 -> 4, 150 -> 100, 0.5 -> 1, -5 -> 0), wandReach 32, the default file (+ the 0.1.17 marker: a fresh file is never migrated), armory:trav: %s %s %s" % (
              cl20a, cl20b, tt20[tt20.find("heal orb"):][:200]))
    PL.publish()
    info20 = br.get("armory:fn:info")
    aw20 = [str(x_) for x_ in list(info20.apply(JArray(JObject)(["wand", "Weapon_Wand_Mithril"])))[8:10]]
    as20 = [str(x_) for x_ in list(info20.apply(JArray(JObject)(["staff", "Weapon_Staff_Mithril"])))[8:10]]
    qw20 = [str(TM.quickWordsW(True, True, 0, 16, 2.0, 50)), str(TM.quickWordsW(True, True, 0, 16, 1.0, 50)), str(TM.quickWordsW(True, True, 3, 16, 2.0, 100)),
            str(TM.quickWordsW(False, True, 0, 16, 2.0, 50)), str(TM.quickWordsW(True, False, 0, 16, 2.0, 50)), str(TM.quickWordsW(True, True, 0, 20, 1.5, 40))]
    g20 = Grid(world_fn())
    gv20 = Grid(world_fn(floor_ok=lambda x, z: False))
    gu20 = Grid(world_fn(unknown=lambda x, y, z: y < 66))
    gy20 = [float(TM.groundY(g20, 0.5, 70.0, 0.5, 8)), float(TM.groundY(g20, 0.5, 64.0, 0.5, 8)), float(TM.groundY(g20, 0.5, 71.0, 0.5, 8)), float(TM.groundY(g20, 0.5, 72.0, 0.5, 8)),
            float(TM.groundY(gv20, 0.5, 70.0, 0.5, 8)), float(TM.groundY(gu20, 0.5, 70.0, 0.5, 8)), float(TM.groundY(g20, 0.5, 70.0, 0.5, 0))]
    check(aw20 == ["Hold - hop back + burst 6 blocks + heal orb 9 blocks - 5 Stamina", "pierces - 32 blocks (50% past 16)"] and as20[1] == "24 blocks"
          and qw20 == ["pierces - 32 blocks (50% past 16)", "pierces - 16 blocks", "pierces 3 - 32 blocks", "", "16 blocks", "pierces - 30 blocks (40% past 20)"]
          and gy20[:3] == [64.0, 64.0, 64.0] and all(math.isnan(x_) for x_ in gy20[3:]),          # 72: the ground is 9 below = NaN
          "R20a: armory:fn:info - a wand's quick words %s (the staff's stay %s); TravMath.quickWordsW %s; TravMath.groundY (ground at y 63 -> 64 from 70 / 64 / 71; "
          "72 = 9 blocks up, void, unknown, depth 0 -> NaN): %s" % (aw20, as20, qw20, gy20))

    # R20b THE RANGE x2 (TravShot.range + TravTick's removal + the pierce continuation)
    setup20()
    TW.ALL.clear()
    reset_buf()
    q20, qpc20 = launched(QORB["Iron"], 2051, 0.5, 65.0, 0.5)
    AT.added(q20, qpc20, int(ADefs.pidCode(QORB["Iron"])), tst, tbuf)
    sq20, sqpc20 = launched(SQORB["Iron"], 2052, 0.5, 65.0, 0.5)
    AT.added(sq20, sqpc20, int(ADefs.pidCode(SQORB["Iron"])), tst, tbuf)
    tw20 = TW.of(tst)
    s20, ss20 = tw20.quick.get(q20), tw20.quick.get(sq20)
    rec20 = (float(s20.range), float(s20.full), float(ss20.range), float(ss20.full))
    at20(q20, 20.5, 65.0, 0.5)
    tw20.run(tst, tbuf, NOW())
    kept20 = bool(tw20.quick.containsKey(q20)) and q20 not in list(TBf.REMOVED)
    at20(q20, 32.6, 65.0, 0.5)
    tw20.run(tst, tbuf, NOW())
    gone20 = (not bool(tw20.quick.containsKey(q20))) and q20 in list(TBf.REMOVED)
    ACfg.RANGE_WAND_X = 1.0          # MUTANT: the 0.1.16 range
    reset_buf()
    qm20, qmpc20 = launched(QORB["Iron"], 2053, 0.5, 65.0, 0.5)
    AT.added(qm20, qmpc20, 1002, tst, tbuf)
    recm20 = (float(tw20.quick.get(qm20).range), float(tw20.quick.get(qm20).full))
    at20(qm20, 20.5, 65.0, 0.5)
    tw20.run(tst, tbuf, NOW())
    mgone20 = qm20 in list(TBf.REMOVED)
    # the pierce continuation from a hit at 20 blocks: 0.1.17 spawns one (inside 32), the mutant (16) none
    cont20 = []
    for mult_ in (2.0, 1.0):
        ACfg.RANGE_WAND_X = mult_
        reset_buf()
        qp_, qppc_ = launched(QORB["Iron"], 2054 if mult_ > 1.0 else 2055, 0.5, 65.0, 0.5)
        AT.added(qp_, qppc_, 1002, tst, tbuf)
        tgp_ = npc(2056 if mult_ > 1.0 else 2057, 20.0, 64.0, 0.5)
        dp_ = DMGc(DPS(rc, qp_), DCSc.PROJECTILE, JFloat(18.0))
        dp_.putMetaObject(DMGc.HIT_LOCATION, V4(20.0, 65.0, 0.5, 1.0))
        AT.landed(tst, tbuf, dp_, qp_, 1002, tgp_)
        cont20.append(len(list(TBf.ADDED)))
    ACfg.RANGE_WAND_X = 2.0
    check(rec20 == (32.0, 16.0, 24.0, 0.0) and kept20 and gone20 and recm20 == (16.0, 0.0) and mgone20 and cont20 == [1, 0],
          "R20b (Skyy: 'double the range of the wands quick shot'): a wand quick orb's record flies 32 (full damage 16), a staff quick orb 24 (no falloff); "
          "TravTick keeps it at 20.5 blocks and removes it past 32; MUTANT quick.range.wandMult 1 (= 0.1.16): 16, removed at 20.5; a hit at 20 blocks still "
          "pierces on (0.1.16: none): %s kept %s gone %s mutant %s %s continuations %s" % (rec20, kept20, gone20, recm20, mgone20, cont20))

    # R20c THE FAR HALF through ArmoryTuneSys.handle (Filter group) on REAL Damage objects, the real dispatch shape (chunk -> the target)
    nref20 = [2100]

    def far20(pid, hit_x=None, pos_x=None, tune=True, tgt_x=None):
        nref20[0] += 2
        q_, pc_ = launched(pid, nref20[0], 0.5, 65.0, 0.5)
        AT.added(q_, pc_, int(ADefs.pidCode(pid)), tst, tbuf)
        if pos_x is not None:
            at20(q_, pos_x, 65.0, 0.5)
        TCh.TARGET = npc(nref20[0] + 1, tgt_x if tgt_x is not None else (hit_x if hit_x is not None else (pos_x if pos_x is not None else 5.0)), 64.0, 0.5)
        d_ = DMGc(DPS(rc, q_), DCSc.PROJECTILE, JFloat(18.0))
        if hit_x is not None:
            d_.putMetaObject(DMGc.HIT_LOCATION, V4(hit_x, 65.0, 0.5, 1.0))
        ACfg.PART_TUNE = tune
        tsys.handle(0, chunk, tst, tbuf, d_)
        ACfg.PART_TUNE = True
        return round(float(d_.getAmount()), 4)
    setup20()
    TW.ALL.clear()
    fh0 = int(AT.FAR_HITS)
    AT.FAR_LOGGED = False
    n_log20 = len(records())
    far = {"10 blocks": far20(QORB["Iron"], hit_x=10.0), "20 blocks": far20(QORB["Iron"], hit_x=20.0), "15.9 blocks": far20(QORB["Iron"], hit_x=16.4),
           "16.6 blocks": far20(QORB["Iron"], hit_x=17.1), "by the orb at 20": far20(QORB["Iron"], pos_x=20.0), "by the orb at 9": far20(QORB["Iron"], pos_x=9.0),
           "tune off, 20": far20(QORB["Iron"], hit_x=20.0, tune=False), "tune off, 10": far20(QORB["Iron"], hit_x=10.0, tune=False),
           "staff 10": far20(SQORB["Iron"], hit_x=10.0), "staff 20": far20(SQORB["Iron"], hit_x=20.0), "Wood wand 20": far20(QORB["Wood"], hit_x=20.0)}
    # fix (critic): no hit location -> the NEARER of the orb and the target; an orb already 18 blocks out hitting a mob at 14.5 = FULL
    # (MUTANT = the old orb-first order: 9), the same orb on a mob at 17.5 = 50%
    far["no hit loc, orb 18.5 mob 14.5"] = far20(QORB["Iron"], pos_x=19.0, tgt_x=15.0)
    far["no hit loc, orb 18.5 mob 17.5"] = far20(QORB["Iron"], pos_x=19.0, tgt_x=18.0)
    ACfg.FAR_PCT = 100
    far["farPercent 100, 20"] = far20(QORB["Iron"], hit_x=20.0)
    ACfg.FAR_PCT = 50
    ACfg.RANGE_WAND_X = 1.0
    far["mult 1 (0.1.16), 20"] = far20(QORB["Iron"], hit_x=20.0)
    ACfg.RANGE_WAND_X = 2.0
    far_hits20 = int(AT.FAR_HITS) - fh0
    far_info = [m_ for lv_, m_ in records()[n_log20:] if "first far wand quick hit after start" in m_]
    # the pierce continuation keeps the first launch's start + the full range: a hit at 5 -> the continuation -> its hit at 21 = far
    reset_buf()
    qc_, qcpc_ = launched(QORB["Iron"], 2190, 0.5, 65.0, 0.5)
    AT.added(qc_, qcpc_, 1002, tst, tbuf)
    tgc_ = npc(2191, 5.0, 64.0, 0.5)
    dc_ = DMGc(DPS(rc, qc_), DCSc.PROJECTILE, JFloat(18.0))
    dc_.putMetaObject(DMGc.HIT_LOCATION, V4(5.0, 65.0, 0.5, 1.0))
    AT.landed(tst, tbuf, dc_, qc_, 1002, tgc_)
    ad_ = list(TBf.ADDED)
    cref_, cpc_ = ad_[0][1], ad_[0][0].getComponent(LPCc.getComponentType())
    put(cref_, LPCc.getComponentType(), cpc_)
    at20(cref_, 6.5, 65.0, 0.5)
    AT.added(cref_, cpc_, 1002, tst, tbuf)
    sc20 = TW.of(tst).quick.get(cref_)
    TCh.TARGET = npc(2192, 21.0, 64.0, 0.5)
    dcf_ = DMGc(DPS(rc, cref_), DCSc.PROJECTILE, JFloat(18.0))
    dcf_.putMetaObject(DMGc.HIT_LOCATION, V4(21.0, 65.0, 0.5, 1.0))
    tsys.handle(0, chunk, tst, tbuf, dcf_)
    contfar = (float(sc20.sx), float(sc20.full), float(sc20.range), round(float(dcf_.getAmount()), 4))
    check(far["10 blocks"] == 18.0 and far["20 blocks"] == 9.0 and far["15.9 blocks"] == 18.0 and far["16.6 blocks"] == 9.0 and far["by the orb at 20"] == 9.0
          and far["by the orb at 9"] == 18.0 and far["tune off, 20"] == 9.0 and far["tune off, 10"] == 18.0 and far["staff 10"] == far["staff 20"] and far["staff 10"] > 18.0
          and far["Wood wand 20"] == 9.0 and far["farPercent 100, 20"] == 18.0 and far["mult 1 (0.1.16), 20"] == 18.0 and far_hits20 == 7
          and far["no hit loc, orb 18.5 mob 14.5"] == 18.0 and far["no hit loc, orb 18.5 mob 17.5"] == 9.0
          and contfar == (0.5, 16.0, 32.0, 9.0) and len(far_info) == 1,
          "R20c (Skyy: 'half damage for the second half'): ArmoryTuneSys on real Damage objects - inside 16 blocks of the cast full (18), past it 50%% "
          "(9, applied ONCE: x0.5 not x0.25), by the hit location or else the NEARER of the orb and the mob (orb 18.5 past a mob at 14.5 = full; "
          "MUTANT orb-first = 9), the tune off too, a staff quick orb untouched (x1.15 both), "
          "the Wood wand's tap too, farPercent 100 / mult 1 (0.1.16) = full; the pierce continuation keeps the cast point + the full range (far at 21 = 9); "
          "ONE INFO line: %s | %s | %s" % (json.dumps(far), contfar, far_info[:1]))

    # R20d THE HEAL AURA AT THE LANDING SPOT (Skyy: "make the healing aura appear where you land, and last a little longer")
    NEAR20 = []

    @JImplements("java.util.function.Function")
    class Near20:
        @JOverride
        def apply(self, o):
            NEAR20.append([round(float(x_), 3) for x_ in o])
            l_ = ArrayList()
            for r_ in NEARL:
                l_.add(r_)
            return l_

    def cast20(ref_i, land_on=True, stam=10.0, burst_before_landing=True):
        mst_ = setup20(stam)
        AT.LAND_ON = land_on
        AT.NEAR = Near20()
        n1_, n2_ = npc(ref_i + 1, 12.0, 64.0, 0.5), npc(ref_i + 2, 13.0, 64.0, 0.5)
        NEARL[:] = [n1_, n2_, rc]
        cast19(ref_i)
        hops_ = [x_ for x_ in instrs19(rc) if x_[1]]
        s_ = LP.STATES.get(cu)
        hang_ = None if s_ is None else (int(s_.hangMs), round(float(s_.fall), 3))
        mst_.onGround = False
        tohang19()
        AT.LASTHOP.put(cu, LJ.valueOf(NOW() - 800))
        rf_ = refire19()
        tw_ = TW.of(tst)
        armed_ = bool(tw_.land.containsKey(cu))
        put(rf_[1], LPCc.getComponentType(), rf_[0])
        put(rf_[1], TCc.getComponentType(), TCc(V3(0.5, 66.0, 1.0), R3(0.0, 0.0, 0.0)))
        AT.added(rf_[1], rf_[0], 2002, tst, tbuf)
        flag_ = bool(tw_.orbs.get(rf_[1]).land)
        out_ = {"hop": [round(math.hypot(h_[0][0], h_[0][2]), 3) for h_ in hops_], "hang": hang_, "armed": armed_, "flag": flag_}
        if not burst_before_landing:
            tw_.run(tst, tbuf, NOW())
            at20(rc, -3.5, 64.0, 0.5)
            mst_.onGround = True
            tw_.run(tst, tbuf, NOW())
            e_ = tw_.land.get(cu)
            out_["landed first"] = None if e_ is None else [round(float(x_), 2) for x_ in list(e_)[3:7]]
            at20(rc, -9.5, 64.0, 0.5)          # they walk away before the orb bursts: the aura still goes where they LANDED
        reset_buf()
        d_ = DMGc(DPS(rc, rf_[1]), DCSc.PROJECTILE, JFloat(88.0))
        d_.putMetaObject(DMGc.HIT_LOCATION, V4(12.0, 65.0, 0.5, 1.0))
        AT.landed(tst, tbuf, d_, rf_[1], 2002, n1_)
        out_["burst events"] = events()
        out_["heals at the burst"] = [(round(float(f_.ax), 2), round(float(f_.ay), 2), round(float(f_.az), 2)) for f_ in heals20(tw_)]
        out_["waiting"] = bool(tw_.landFx.containsKey(cu))
        return mst_, tw_, out_

    # 1 the burst in mid-air, the landing after it
    mst20, tw20, o1 = cast20(2200)
    tw20.run(tst, tbuf, NOW())
    o1["after an airborne tick"] = (len(heals20(tw20)), bool(tw20.landFx.containsKey(cu)))
    at20(rc, -4.5, 64.0, 0.5)
    mst20.onGround = True
    l0 = int(AT.LANDINGS)
    t_land = NOW()
    tw20.run(tst, tbuf, t_land)
    hf20 = heals20(tw20)
    o1["aura"] = [(round(float(f_.ax), 2), round(float(f_.ay), 2), round(float(f_.az), 2), round(float(f_.amount), 3), int(f_.until) - t_land) for f_ in hf20]
    o1["after"] = (bool(tw20.land.containsKey(cu)), bool(tw20.landFx.containsKey(cu)), int(AT.LANDINGS) - l0)
    # the aura heals AT ITS NEW SPOT (TravTick -> tickFx: the area query at the landing spot, a heal job for the caster)
    reset_buf()
    del NEAR20[:]
    if hf20:
        hf20[0].next = 0
    tw20.run(tst, tbuf, NOW())
    o1["heal query"] = NEAR20[-1:] if NEAR20 else None
    o1["heal jobs"] = len([j_ for j_ in list(TWd.JOBS) if str(j_.getClass().getSimpleName()) == "TravHeal"])
    check(o1["hop"] == [18.0] and o1["hang"] == (350, 1.5) and o1["armed"] and o1["flag"]
          and [e_[0] for e_ in o1["burst events"]] == [2202] and o1["heals at the burst"] == [] and o1["waiting"]
          and o1["after an airborne tick"] == (0, True) and len(o1["aura"]) == 1 and o1["aura"][0][:4] == (-4.5, 64.5, 0.5, 17.6)
          and 4900 <= o1["aura"][0][4] <= 5100 and o1["after"] == (False, False, 1)
          and o1["heal query"] == [[-4.5, 64.5, 0.5, 9.0]] and o1["heal jobs"] == 1,
          "R20d (1) ONE WAND CAST END TO END at the 0.1.17 defaults: ONE hop of 18 (0.1.16: 22), the hang unchanged (0.35 s, 1.5 b/s drift), the landing "
          "watch armed at the end of the hang, the re-launched orb carries the flag; its burst damages the enemy next to the hit (60%%) AT THE HIT, the "
          "heal aura WAITS (none at the burst, still waiting after an airborne tick); the first on-ground tick puts it WHERE THE CASTER LANDED "
          "(-4.5, 64 -> ring at 64.5), 17.6 a tick (20%% of 88), lasting 5 s from then; it then heals there (the area query at the landing spot, "
          "a heal job): %s" % json.dumps(o1, default=str))
    # 2 MUTANT: the landing watch off = the 0.1.16 burst spot (3.5 s there in 0.1.16; the 0.1.17 5 s)
    mst20, tw20, o2 = cast20(2210, land_on=False)
    check(o2["armed"] is False and o2["heals at the burst"] == [(12.0, 65.0, 0.5)] and not o2["waiting"],
          "R20d (2) MUTANT landing watch off (= 0.1.16): the aura appears AT THE BURST (12, 65), nothing armed / waiting: %s" % json.dumps(o2, default=str))
    # 3 the landing BEFORE the burst (they walk away after landing): the aura appears at once, where they landed
    t3 = NOW()
    mst20, tw20, o3 = cast20(2220, burst_before_landing=False)
    hf3 = heals20(tw20)
    o3["aura"] = [(round(float(f_.ax), 2), round(float(f_.ay), 2), round(float(f_.az), 2)) for f_ in hf3]
    check(o3["landed first"] == [1.0, -3.5, 64.0, 0.5] and o3["aura"] == [(-3.5, 64.5, 0.5)] and not o3["waiting"] and not bool(tw20.land.containsKey(cu)),
          "R20d (3) landed first, then walked to -9.5, THEN the orb bursts: the aura appears at once where they landed (-3.5): %s" % json.dumps(o3, default=str))
    # 4 standing (never airborne - a ceiling): landed only after 0.4 s; 5 no landing in 3 s: the ground under them / over the void their position
    mst20 = setup20()
    TW.ALL.clear()
    tw20 = TW.get(tst)
    AT.landArm(tst, cu, NOW())
    tw20.run(tst, tbuf, NOW())
    e20 = tw20.land.get(cu)
    st0 = float(e20[3])
    e20[0] = float(NOW() - 500)
    tw20.run(tst, tbuf, NOW())
    st1 = [round(float(x_), 2) for x_ in list(tw20.land.get(cu))[3:7]]
    to20 = {}
    for name_, grid_, y_ in (("ground 6 below", Grid(world_fn()), 70.0), ("void below", Grid(world_fn(floor_ok=lambda x, z: False)), 70.0),
                             ("too high (9+)", Grid(world_fn()), 74.0)):
        AT.GRID = grid_
        mst20.onGround = False
        at20(rc, 2.5, y_, 0.5)
        AT.landArm(tst, cu, NOW())
        tw20.run(tst, tbuf, NOW())
        e_ = tw20.land.get(cu)
        before_ = float(e_[3])
        e_[1] = float(NOW() - 1)
        lt0 = int(AT.LAND_TIMEOUTS)
        tw20.run(tst, tbuf, NOW())
        to20[name_] = (before_, [round(float(x_), 2) for x_ in list(tw20.land.get(cu))[3:7]], int(AT.LAND_TIMEOUTS) - lt0)
    AT.GRID = Grid(world_fn())
    check(st0 == 0.0 and st1 == [1.0, 0.5, 64.0, 0.5] and to20["ground 6 below"] == (0.0, [1.0, 2.5, 64.0, 0.5], 1)
          and to20["void below"] == (0.0, [1.0, 2.5, 70.0, 0.5], 1) and to20["too high (9+)"] == (0.0, [1.0, 2.5, 74.0, 0.5], 1),
          "R20d (4) standing all along: not landed at once, landed after 0.4 s at their feet; (5) no landing within 3 s: the ground right under them "
          "(y 64, within 8 blocks), over the void / higher than 8 blocks = their own position (never projected into the void): %s %s" % (st1, to20))
    # 6 the caster gone (left / died) before landing: the waiting aura appears at its burst spot
    setup20()
    TW.ALL.clear()
    tw20 = TW.get(tst)
    AT.landArm(tst, cu, NOW())
    sh20 = TSh20(0.5, 65.0, 0.5, 0.0, 2002, cu, ORB["Iron"])
    sh20.land = True
    AT.burst(tst, tbuf, None, sh20, 12.0, 65.0, 0.5, None, 88.0, 88.0)
    wait6 = (len(heals20(tw20)), bool(tw20.landFx.containsKey(cu)))
    ebu.remove(cu)
    ll0 = int(AT.LAND_LOST)
    tw20.run(tst, tbuf, NOW())
    ebu.put(cu, rc)
    gone6 = ([(round(float(f_.ax), 2), round(float(f_.ay), 2)) for f_ in heals20(tw20)], int(AT.LAND_LOST) - ll0, bool(tw20.land.containsKey(cu)))
    # an aura with no watch for its caster (no hop) = the burst spot at once; a shot without the flag = the burst spot even with a watch
    setup20()
    TW.ALL.clear()
    tw20 = TW.get(tst)
    sh20b = TSh20(0.5, 65.0, 0.5, 0.0, 2002, cu, ORB["Iron"])
    sh20b.land = True
    AT.burst(tst, tbuf, None, sh20b, 11.0, 65.0, 0.5, None, 88.0, 88.0)
    AT.landArm(tst, cu, NOW())
    sh20c = TSh20(0.5, 65.0, 0.5, 0.0, 2002, cu, ORB["Iron"])
    AT.burst(tst, tbuf, None, sh20c, 10.0, 65.0, 0.5, None, 88.0, 88.0)
    nowatch6 = [(round(float(f_.ax), 2), round(float(f_.ay), 2)) for f_ in heals20(tw20)]
    idle6 = bool(tw20.idle())
    check(wait6 == (0, True) and gone6 == ([(12.0, 65.0)], 1, False) and nowatch6 == [(11.0, 65.0), (10.0, 65.0)] and idle6 is False,
          "R20d (6) the caster gone before landing: the waiting aura appears at its burst spot (12, 65), LAND_LOST +1; no watch / no hop flag = the "
          "burst spot at once (11 / 10); a world with a watch is not idle (never dropped): %s %s %s" % (wait6, gone6, nowatch6))
    # 7 the 0.1.2 hop job (hop.hangSeconds 0): armed by the hop; 8 a hop refused for Stamina arms nothing -> the burst spot
    hj20 = {}
    for name_, stam_ in (("hop job", 10.0), ("no Stamina", 0.0)):
        mst_ = setup20(stam_)
        ACfg.HOP_HANG = 0.0
        AT.NEAR = Near20()
        n1_ = npc(2240 if stam_ > 0 else 2245, 12.0, 64.0, 0.5)
        NEARL[:] = [n1_, rc]
        o_, p_ = cast19(2241 if stam_ > 0 else 2246)
        tw_ = TW.of(tst)
        flag_ = bool(tw_.orbs.get(o_).land)
        mst_.onGround = False
        for j_ in list(TWd.JOBS):
            j_.run()
        armed_ = bool(tw_.land.containsKey(cu))
        reset_buf()
        d_ = DMGc(DPS(rc, o_), DCSc.PROJECTILE, JFloat(88.0))
        d_.putMetaObject(DMGc.HIT_LOCATION, V4(12.0, 65.0, 0.5, 1.0))
        AT.landed(tst, tbuf, d_, o_, 2002, n1_)
        at_burst_ = [(round(float(f_.ax), 2), round(float(f_.ay), 2)) for f_ in heals20(tw_)]
        tw_.run(tst, tbuf, NOW())
        at20(rc, 5.5, 64.0, 0.5)
        mst_.onGround = True
        tw_.run(tst, tbuf, NOW())
        hj20[name_] = (flag_, armed_, pushes19(), at_burst_, [(round(float(f_.ax), 2), round(float(f_.ay), 2)) for f_ in heals20(tw_)])
    check(hj20["hop job"] == (True, True, 1, [], [(5.5, 64.5)]) and hj20["no Stamina"] == (True, False, 0, [(12.0, 65.0)], [(12.0, 65.0)]),
          "R20d (7) the 0.1.2 hop job (no hang): the hop arms the watch, the aura waits and appears where they land (5.5); (8) too little Stamina = no "
          "hop, nothing armed, the aura at the burst spot (the 0.1.16 way): %s" % json.dumps(hj20))
    AT.NEAR = Near()

    # R20e THE ONE-TIME UPDATE (PROJECT-RULES 4): hop.force 22 -> 18 + orb.seconds 3.5 -> 5 in ONE pass, one marker
    MK17 = str(ACfg.M17_MARK)

    def upd17(t_):
        r_ = ACfg.m17Update(t_)
        return None if r_ is None else (str(r_[0]), str(r_[1]), [str(x) for x in r_[2]], [str(x) for x in r_[3]])
    v1 = upd17("a=1\nhop.force=22\norb.seconds=3.5\nb=2\n")
    v2 = upd17("a=1\r\nhop.force = 22.0\r\norb.seconds=3.50\r\n")
    v3 = upd17("hop.force=25\norb.seconds=4\n")
    v4 = upd17("quick.life=20\n")
    v5 = upd17(v1[0])
    v6 = upd17("orb.seconds=3.5\n")
    v7 = upd17("hop.force=18\norb.seconds=5\n")
    check(v1 == ("a=1\n" + MK17 + "\nhop.force=18\norb.seconds=5\nb=2\n", "hop.force 22 -> 18, orb.seconds 3.5 -> 5", [], ["hop.force", "22", "18", "orb.seconds", "3.5", "5"])
          and v2 == ("a=1\r\n" + MK17 + "\r\nhop.force = 18\r\norb.seconds=5\r\n", "hop.force 22.0 -> 18, orb.seconds 3.50 -> 5", [], ["hop.force", "22.0", "18", "orb.seconds", "3.50", "5"])
          and v3[0] == MK17 + "\nhop.force=25\norb.seconds=4\n" and v3[1] == "" and len(v3[2]) == 2 and "kept (custom) - the 0.1.17 default is 18" in v3[2][0]
          and "kept (custom) - the 0.1.17 default is 5" in v3[2][1] and v4 == ("quick.life=20\n" + MK17 + "\n", "", [], []) and v5 is None
          and v6 == ("orb.seconds=5\n" + MK17 + "\n", "orb.seconds 3.5 -> 5", [], ["orb.seconds", "3.5", "5"]) and v7 == (MK17 + "\nhop.force=18\norb.seconds=5\n", "", [], []),
          "R20e (PROJECT-RULES 4): untouched 22 / 3.5 (or 22.0 / 3.50) -> 18 / 5 (value text only, CRLF kept, one marker before hop.force), hand-set 25 / 4 "
          "KEPT + noted, no line = marker only (Skyy's live file: the new defaults apply), runs once: %s / %s / %s" % (v1, v2, v3))
    mdir17 = os.path.join(SCRATCH, "m17", "mods", "Skyy_SkyyArmory")
    shutil.rmtree(os.path.dirname(os.path.dirname(mdir17)), ignore_errors=True)
    os.makedirs(mdir17)
    mtxt17 = ("# SkyyArmory 0.1.16 test file\r\npart.trav=true\r\n" + str(ACfg.M13_MARK) + "\r\n" + str(ACfg.M14_MARK) + "\r\n" + str(ACfg.M16_MARK) + "\r\nhop.force=22\r\n"
              "orb.seconds=3.5\r\nquick.life=20\r\n").encode("latin-1")
    open(os.path.join(mdir17, "config.properties"), "wb").write(mtxt17)
    ACfg.DIR = Paths.get(mdir17)
    ACfg.FILE = ACfg.DIR.resolve("config.properties")
    mr17 = [str(ACfg.migrate013()), str(ACfg.migrate014()), str(ACfg.migrate016())]          # setup() order: the older steps first (idle here)
    mr17a = str(ACfg.migrate017())
    af17 = open(os.path.join(mdir17, "config.properties"), "rb").read()
    hist17 = os.path.join(mdir17, "config-history")
    baks17 = sorted(f_ for f_ in os.listdir(hist17) if f_.endswith(".bak")) if os.path.isdir(hist17) else []
    bak17 = open(os.path.join(hist17, baks17[-1]), "rb").read() if baks17 else b""          # read now: the chain below adds + prunes History copies
    log17 = open(os.path.join(mdir17, "config-changes.log"), "rb").read().decode("latin-1") if os.path.isfile(os.path.join(mdir17, "config-changes.log")) else ""
    mr17b = str(ACfg.migrate017())
    af17b = open(os.path.join(mdir17, "config.properties"), "rb").read()
    ACfg.load()
    ld17 = (float(ACfg.HOP_FORCE), float(ACfg.ORB_SECONDS))
    chain17 = {}
    for name_, body_ in (("0.1.2 file (13)", b"part.trav=true\nhop.force=13\norb.seconds=3.5\n"), ("0.1.15 file (30)", b"part.trav=true\nhop.force=30\n"),
                         ("0.1.16 file (22)", b"hop.force=22\n"), ("hand-set 26 / 6", b"hop.force=26\norb.seconds=6\n")):
        open(os.path.join(mdir17, "config.properties"), "wb").write(body_)
        ACfg.migrate013()
        ACfg.migrate014()
        ACfg.migrate016()
        ACfg.migrate017()
        t_ = open(os.path.join(mdir17, "config.properties"), "rb").read().decode("latin-1")
        chain17[name_] = sorted(l_ for l_ in t_.split("\n") if l_.startswith(("hop.force", "orb.seconds")))
    ACfg.DIR = None
    ACfg.FILE = None
    ACfg.useDefaults()
    check(mr17 == ["", "", ""] and af17 == upd17(mtxt17.decode("latin-1"))[0].encode("latin-1") and b"hop.force=18\r\n" in af17 and b"orb.seconds=5\r\n" in af17
          and baks17 and bak17 == mtxt17
          and "\tSkyyArmory 0.1.17\t-\tupdate\thop.force\t22\t18\tok" in log17 and "\tSkyyArmory 0.1.17\t-\tupdate\torb.seconds\t3.5\t5\tok" in log17
          and "hop.force 22 -> 18, orb.seconds 3.5 -> 5" in mr17a and mr17b == "" and af17b == af17 and ld17 == (18.0, 5.0)
          and chain17 == {"0.1.2 file (13)": ["hop.force=18", "orb.seconds=5"], "0.1.15 file (30)": ["hop.force=18"], "0.1.16 file (22)": ["hop.force=18"],
                          "hand-set 26 / 6": ["hop.force=26", "orb.seconds=6"]},
          "R20e (the real ArmoryCfg.migrate017 on a scratch file, after migrate013 / 014 / 016 like setup()): History copy = the old bytes, two Undo-able "
          "change-log lines, CRLF kept, the second run idle, the loader reads 18 / 5; 13 -> 30 -> 22 -> 18 and 30 -> 22 -> 18 in one start, a hand-set "
          "26 / 6 kept: %s | %s | %s" % (mr17a[:140], log17.strip()[-80:], chain17))

    # R20f THE HOP NUMBERS at 18 (g 32 b/s2, jump 11.8; up speed + blocks up above the ground) - the report's table
    tab20 = {}
    for lbl_, pd_, jp_ in (("flat", 0.0, False), ("45 down", 45.0, False), ("straight down", 90.0, False), ("straight down + jump", 90.0, True)):
        tab20[lbl_] = {"0.1.16": hop19(22.0, 15.0, pd_, jp_), "0.1.17": hop19(18.0, 15.0, pd_, jp_)}
    check(tab20["flat"]["0.1.17"][0] == 18.0 and tab20["45 down"]["0.1.17"][1] == 12.73 and tab20["45 down"]["0.1.16"][1] == 15.0
          and tab20["straight down"]["0.1.17"][1] == 15.0 and tab20["45 down"]["0.1.17"][2] < tab20["45 down"]["0.1.16"][2],
          "R20f: hop 18 - flat back 18 (0.1.16: 22), 45 degrees down 12.73 up (under the 15 cap; 0.1.16: capped 15), straight down still capped 15")
    print("R20f. hop numbers (back b/s, up b/s, blocks up above the ground; g 32, jump 11.8): %s" % json.dumps(tab20))

    # R20g vs the 0.1.16 jar METHOD BY METHOD
    MN20, MO20 = methods_of(JAR), methods_of(OLD116)
    cmp20 = {}
    for c_ in sorted(set(MN20) | set(MO20)):
        if c_ not in MN20 or c_ not in MO20:
            cmp20[c_] = "only in " + ("0.1.17" if c_ in MN20 else "0.1.16")
            continue
        ch_ = sorted(k_ for k_ in set(MN20[c_][0]) | set(MO20[c_][0]) if MN20[c_][0].get(k_) != MO20[c_][0].get(k_))
        fd_ = sorted(set(MN20[c_][1]) ^ set(MO20[c_][1]))
        if ch_ or fd_:
            cmp20[c_] = {"methods": [k_.split("(")[0] for k_ in ch_], "fields": [f_.split(":")[0] for f_ in fd_]}
    plan20 = {"ArmoryTrav": ({"landArm", "landPlace", "landHold", "landTick", "farFactor", "hop", "added", "burst"},
                             {"LAND_ON", "LAND_WAIT_MS", "LAND_MIN_MS", "LAND_KEEP_MS", "LAND_DOWN", "LAND_UP", "LANDINGS", "LAND_TIMEOUTS", "LAND_AURAS",
                              "LAND_LOST", "FAR_HITS", "FAR_LOGGED"}),
              "Leap": ({"fire"}, set()),
              "TravMath": ({"groundY", "quickWordsW"}, set()),
              "TravShot": ({"next"}, {"full", "land"}),
              "TravWorld": ({"<init>", "idle", "run"}, {"land", "landFx"}),
              "ArmoryCfg": ({"m17Key", "m17Update", "m17Log", "migrate017", "load", "apply", "travText", "wandReach", "useDefaults", "reloadAll"},
                            {"RANGE_WAND_X", "FAR_PCT", "M17_KEY1", "M17_OLD1", "M17_NEW1", "M17_KEY2", "M17_OLD2", "M17_NEW2", "M17_MARK", "M17_MARK_ID",
                             "M17_WHO", "M17_LAST"}),
              "ArmoryTuneSys": ({"handle"}, set()),
              "ArmoryInfoFn": ({"apply"}, set()),
              "SkyyArmoryPlugin": ({"setup", "shutdown"}, set())}
    bad20 = {}
    for c_, v_ in cmp20.items():
        if c_ in plan20 and isinstance(v_, dict) and set(v_["methods"]) <= plan20[c_][0] and set(v_["fields"]) <= plan20[c_][1]:
            continue
        bad20[c_] = v_
    check(not bad20 and "landTick" in cmp20.get("ArmoryTrav", {}).get("methods", []) and "farFactor" in cmp20.get("ArmoryTrav", {}).get("methods", [])
          and "fire" in cmp20.get("Leap", {}).get("methods", []) and "handle" in cmp20.get("ArmoryTuneSys", {}).get("methods", [])
          and "migrate017" in cmp20.get("ArmoryCfg", {}).get("methods", []),
          "R20g: 0.1.16 -> 0.1.17 METHOD BY METHOD - only the planned methods / fields differ (the landing watch + aura, the far factor, the x2 record, "
          "Leap.fire arms the watch, the rows + migrate017, the info words, the plugin's setup / shutdown): %s" % json.dumps(bad20)[:1500])
    print("R20g. vs 0.1.16 method by method: %s" % json.dumps(cmp20)[:1800])
    AT.LAND_ON = True
    ACfg.useDefaults()
    TW.ALL.clear()
    reset_buf()
    LP.STATES.clear()
    put(rc, MSCc.getComponentType(), None)
    at20(rc, 0.5, 64.0, 0.5)
    print("R20. 0.1.17 wand round: rows + words, the range x2 (TravShot / TravTick / pierce), the far half once through ArmoryTuneSys, the heal aura at the "
          "landing spot (end to end + mutant + every branch), migrate017, hop 18, the 0.1.16 compare")
'''
hrep('''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''',
     R20 + '''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''')

out_t = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(out_t)
print("wrote %s" % os.path.relpath(TDST, ROOT))
