"""Derive SkyyArmory/build_skyyarmory_0.1.13.py (+ its harness SkyyArmory/test_skyyarmory_0.1.13.py) from the GENERATED 0.1.12
(SkyyArmory/build_skyyarmory_0.1.12.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_12_patch.py; test_skyyarmory_0.1.12.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_13_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.13.py   then
      python SkyyArmory/test_skyyarmory_0.1.13.py --dir tools/dev/scratch/<task>/harness      (never --deploy)

0.1.13 = THE LOG FIXES (Skyy 2026-10-08: "the last play has 56+ critical errors dev mode found, so make sure to check the logs to fix things";
docs/log/2026-10.md 2026-10-08 07:12 LOG SCAN). Deploy WITH SkyySkills 0.4.23 (alone it is safe too).
(5) THE DAGGER CHARGE WARNING ('[ChargingInteraction] <player> charge value 0.402 exceeds max allowed 0.400'): the engine's
    ChargingInteraction.validateChargeValue caps the allowed value at the HIGHEST key when AllowIndefiniteHold is false; the client fires the
    last key a frame late, so its reported value overshoots by a few ms -> one WARN per charged dagger attack. Our 0.1.8 override of
    Weapon_Daggers_Primary_Pounce (Shadow Step, keys 0 / 0.4 = vanilla's) now has AllowIndefiniteHold TRUE (the 0.1.12 fist / Bo holds' way):
    the allowed value is the real held time + 0.25 s, so a frame's overshoot never warns, while a client claiming far more than it held still
    does (the engine's anti-cheat stays). Shadow Step fires on RELEASE after a 0.4 s hold (the row text always said "hold the attack + release")
    instead of the moment the hold reaches 0.4 s; a tap / a release before 0.4 s = the vanilla stab chain, unchanged. The 0.200 lines are the
    VANILLA Weapon_Daggers_Primary (keys 0 / 0.2 - SkyyGear's speed copies have the same keys): not ours, and setting it to an indefinite hold
    would break the hand-over into the Pounce charge - left alone (harmless: the engine only logs). 'Missing primary chain for fork' is a
    CLIENT line (the client got a forked chain - a Selector hit, a Parallel - for a chain it no longer has); nothing in our dagger chain forks
    (the Pounce -> one LaunchProjectile): UNVERIFIED which chain - the 17 lines came during dagger taps, where SkyyGear's speed chains run.
(6) THE STAFF HANDOVER CHECK (with SkyySkills 0.4.23 (4)): SkyySkills' overrides of the vanilla Staff_Cast_Summon_Charged / Staff_Cast_Cost
    make the engine re-read this jar's 8 ladder staff + 2 Bo item files under the SkyySkills pack name (AssetStore.reloadChildrenContainerAssets:
    the vanilla staffs' inline vars inherit those two). The FILE is ours - players always got SkyyArmory's staffs. packOf now also reads the
    item's file pack (AssetMap.getPath + AssetModule.findAssetPackForPath): our file under another pack's name counts as ours and is named in
    the INFO line ("re-read under ..."); another pack's FILE still WARNs as before.
NO saved data, no migration, no new row / system / command / class.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.12.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.13.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.12.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.13.py")

CR, LF = chr(13), chr(10)
raw = open(SRC, encoding="utf8", newline="").read()
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.12"\nMOD = "SkyyArmory"' in s and "0.1.12 = THE MONK MOVES built into the real weapons" in s, "build_skyyarmory_0.1.12.py is not the 0.1.12 pin"
assert "REREAD" not in s and "filePack" not in s, "0.1.12 already has the 0.1.13 parts"


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# ---------------------------------------------------------------------------------------------------------------- header + version
rep('''"""SkyyArmory 0.1.12 - build script (javassist via jpype). GENERATED by tools/armory_0_1_12_patch.py from the GENERATED 0.1.11 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.12.py -> SkyyArmory/SkyyArmory-0.1.12.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.12.py --dir tools/dev/scratch/<task>/harness.
''', '''"""SkyyArmory 0.1.13 - build script (javassist via jpype). GENERATED by tools/armory_0_1_13_patch.py from the GENERATED 0.1.12 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.13.py -> SkyyArmory/SkyyArmory-0.1.13.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.13.py --dir tools/dev/scratch/<task>/harness.

0.1.13 = THE LOG FIXES (Skyy 2026-10-08 "check the logs to fix things"; full notes in tools/armory_0_1_13_patch.py): the dagger Pounce override
(Shadow Step) gets AllowIndefiniteHold (fires on release after the 0.4 s hold; no more 'charge value .. exceeds max allowed 0.400' WARN, the
engine's anti-cheat kept); the pack check reads each item's FILE: SkyySkills' Staff_Cast_* overrides make the engine re-read our 10 staff
files under the SkyySkills name - our file = ours (INFO "re-read under ..."), not "ANOTHER PACK WINS". No data / row / class change.

0.1.12 (the base, everything below is still true unless 0.1.13 above says otherwise):
''')
rep('VERSION = "0.1.12"\nMOD = "SkyyArmory"', 'VERSION = "0.1.13"\nMOD = "SkyyArmory"')

# ---------------------------------------------------------------------------------------------------------------- (5) the dagger Pounce
rep('''SS_POUNCE_JSON = json.loads(json.dumps(VPOUNCE))
SS_POUNCE_JSON["Next"]["0.4"] = ID_SS_LAUNCH
''', '''SS_POUNCE_JSON = json.loads(json.dumps(VPOUNCE))
SS_POUNCE_JSON["Next"]["0.4"] = ID_SS_LAUNCH
# 0.1.13 (the 07:12 log scan): AllowIndefiniteHold. With false the engine caps the allowed charge at the highest key (0.4) and the client's
# one-frame overshoot logs 'charge value 0.402 exceeds max allowed 0.400' on every Shadow Step; true = allowed = the held time + 0.25 s
# (ChargingInteraction.validateChargeValue), the step fires on release after 0.4 s (the 0.1.12 fist / Bo holds' way). Keys / pose / particles vanilla.
SS_POUNCE_JSON["AllowIndefiniteHold"] = True
assert dict((k, v) for k, v in SS_POUNCE_JSON.items() if k not in ("Next", "AllowIndefiniteHold")) == dict(
    (k, v) for k, v in VPOUNCE.items() if k not in ("Next", "AllowIndefiniteHold")) and sorted(SS_POUNCE_JSON["Next"]) == ["0", "0.4"]
''')

# ---------------------------------------------------------------------------------------------------------------- (6) the pack check
rep('''M(chk, r"""
public static int packOf(@DAM@ m, String[] ids, java.util.List other, java.util.List miss) {
  int mine = 0;
  for (int i = 0; i < ids.length; i++) {
    String p = null;
    try { p = m.getAssetPack(ids[i]); } catch (Throwable t) { p = null; }
    if (p == null) { miss.add(ids[i]); continue; }
    if (p.equals(@PKG@.ArmoryDefs.PACK)) { mine++; continue; }
    other.add(ids[i] + " (" + p + ")");
  }
  return mine;
}""")''', '''# 0.1.13: the pack an asset's FILE belongs to (AssetMap.getPath + AssetModule.findAssetPackForPath; null = unknown). SkyySkills' overrides of
# the vanilla Staff_Cast_Summon_Charged / Staff_Cast_Cost make the engine re-read our staff files (their vanilla vars inherit those two)
# under the SkyySkills name (AssetStore.reloadChildrenContainerAssets): the label is theirs, the file ours.
F(chk, "public static final java.util.ArrayList REREAD = new java.util.ArrayList();")
M(chk, r"""
public static String filePack(com.hypixel.hytale.assetstore.AssetMap m, String id) {
  try {
    if (m == null || id == null) return null;
    java.nio.file.Path p = m.getPath(id);
    if (p == null) return null;
    com.hypixel.hytale.server.core.asset.AssetModule am = com.hypixel.hytale.server.core.asset.AssetModule.get();
    if (am == null) return null;
    com.hypixel.hytale.assetstore.AssetPack ap = am.findAssetPackForPath(p);
    return ap == null ? null : ap.getName();
  } catch (Throwable t) { return null; }
}""")
M(chk, r"""
public static int packOf(@DAM@ m, String[] ids, java.util.List other, java.util.List miss) {
  int mine = 0;
  for (int i = 0; i < ids.length; i++) {
    String p = null;
    try { p = m.getAssetPack(ids[i]); } catch (Throwable t) { p = null; }
    if (p == null) { miss.add(ids[i]); continue; }
    if (p.equals(@PKG@.ArmoryDefs.PACK)) { mine++; continue; }
    if (@PKG@.ArmoryDefs.PACK.equals(filePack(m, ids[i]))) { mine++; REREAD.add(ids[i] + " (" + p + ")"); continue; }   // 0.1.13: our file, re-read by p
    other.add(ids[i] + " (" + p + ")");
  }
  return mine;
}""")''')
rep('''  java.util.ArrayList other = new java.util.ArrayList();
  java.util.ArrayList miss = new java.util.ArrayList();
  int mi = packOf(im, @PKG@.ArmoryDefs.ITEM_CHECK, other, miss);''', '''  java.util.ArrayList other = new java.util.ArrayList();
  java.util.ArrayList miss = new java.util.ArrayList();
  REREAD.clear();          // 0.1.13: filled by packOf
  int mi = packOf(im, @PKG@.ArmoryDefs.ITEM_CHECK, other, miss);''')
rep('''    + " roots (the crossbow right click) come from " + @PKG@.ArmoryDefs.PACK;
  if (other.isEmpty() && miss.isEmpty() && bad.isEmpty())''', '''    + " roots (the crossbow right click) come from " + @PKG@.ArmoryDefs.PACK;
  if (!REREAD.isEmpty()) pre = pre + " (" + REREAD.size() + " of them our own files re-read under another pack's name - SkyySkills' Staff_Cast_* overrides make the engine re-read the staffs whose vanilla vars inherit them; the file is ours: " + head(REREAD, 4) + ")";   // 0.1.13
  if (other.isEmpty() && miss.isEmpty() && bad.isEmpty())''')
# the probed engine members (the build stops when one changes)
rep('''    (T["PRJ"], "getAssetMap", T["DAM"], []), (T["DAM"], "getAssetPack", S_, [O_]), (T["DAM"], "getAsset", "com.hypixel.hytale.assetstore.JsonAsset", [O_]),''',
    '''    (T["PRJ"], "getAssetMap", T["DAM"], []), (T["DAM"], "getAssetPack", S_, [O_]), (T["DAM"], "getAsset", "com.hypixel.hytale.assetstore.JsonAsset", [O_]),
    # 0.1.13: the item file's pack (packOf)
    ("com.hypixel.hytale.assetstore.AssetMap", "getPath", "java.nio.file.Path", [O_]),
    ("com.hypixel.hytale.server.core.asset.AssetModule", "get", "com.hypixel.hytale.server.core.asset.AssetModule", []),
    ("com.hypixel.hytale.server.core.asset.AssetModule", "findAssetPackForPath", "com.hypixel.hytale.assetstore.AssetPack", ["java.nio.file.Path"]),
    ("com.hypixel.hytale.assetstore.AssetPack", "getName", S_, []),''')

with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(s.replace(LF, NL))
print("wrote %s" % os.path.relpath(DST, ROOT))

# ================================================================================================================ the harness
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.12 - test harness. GENERATED by tools/armory_0_1_12_patch.py from test_skyyarmory_0.1.11.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.13 - test harness. GENERATED by tools/armory_0_1_13_patch.py from test_skyyarmory_0.1.12.py - edit the patch, never this file.
Run: python SkyyArmory/test_skyyarmory_0.1.13.py --dir tools/dev/scratch/<task>/harness   (--no-set skips the one-JVM SET run, --keep keeps it)
Every 0.1.12 check still runs on the 0.1.12 shape: JREAL (the jar the 0.1.12 checks know) = the real 0.1.13 jar with the ONE changed file (the
dagger Pounce override) read as the 0.1.12 jar's bytes (P15 proves the real one is exactly the planned change of those bytes); the classes are
the real 0.1.13 ones (A / X / T / V / every Java path); R15e now compares 0.1.11 -> 0.1.12 (history), R16e 0.1.12 -> 0.1.13.
NEW P15 (Python) + R16 (JVM, after R15) EXECUTE every 0.1.13 path:
  P15  the Pounce = the 0.1.12 file + "AllowIndefiniteHold": true only (keys 0 / 0.4, pose, particles, the launch unchanged); every other
       non-class file byte-identical to 0.1.12 (the manifest = its version only)
  R16  a: the ENGINE ASSET VALIDATORS on the real Pounce; b: the engine's ChargingInteraction.validateChargeValue EXECUTED on the decoded
       0.1.12 and 0.1.13 Pounce (a real InteractionContext / InteractionEntry meta store / TimeResource): Skyy's case (0.402 after 0.399 s)
       WARNs on 0.1.12 and NOT on 0.1.13, a fair hold neither, a client claiming 0.9 after 0.3 s WARNs on both (anti-cheat kept); c: into the
       stores, RootInteraction.build() of the dagger root -> the Pounce -> the launch; d: the staff handover re-read REPRODUCED on the real
       stores (vanilla staff items -> our files -> SkyySkills' Staff_Cast_* overrides) and ArmoryCheck.packOf with AssetModule answering:
       ours (REREAD), without it: another pack (control); e: vs the 0.1.12 jar file by file + method by method.

0.1.12 harness: SkyyArmory 0.1.12 - test harness. GENERATED by tools/armory_0_1_12_patch.py from test_skyyarmory_0.1.11.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.12"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.12 SkyyArmory"',
     'VERSION = "0.1.13"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.13 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory0112", "harness")', 'os.path.join(SCRATCH_ROOT, "armory0113", "harness")')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.12.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.13.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.12"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.13"))')
hrep('"[SkyyArmory] 0.1.12 ready" in m_', '"[SkyyArmory] 0.1.13 ready" in m_')
hrep('"0.1.12 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_', '"0.1.13 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_')
hrep('"0.1.12 crossbow grapple: grapple on" in m_', '"0.1.13 crossbow grapple: grapple on" in m_')
hrep('"0.1.12 monk moves on - Pole-Vault (Bo hold): lunge 3 in 0.2 s, 4.5 up x 7 forward (push x2.1)" in m_',
     '"0.1.13 monk moves on - Pole-Vault (Bo hold): lunge 3 in 0.2 s, 4.5 up x 7 forward (push x2.1)" in m_')
hrep('come from Skyy:0.1.12 SkyyArmory" in str(r[1])', 'come from Skyy:0.1.13 SkyyArmory" in str(r[1])')

# ---- the jar as the 0.1.12 checks know it: the one changed file (the dagger Pounce) read from the 0.1.12 jar
hrep('''JZ = zipfile.ZipFile(JAR)
# 0.1.12: JREAL = the real jar (P14 / R15);''', '''JZ = zipfile.ZipFile(JAR)
# 0.1.13: JZ13 = the real 0.1.13 jar (P15 / R16); from here on JZ is the jar AS THE 0.1.12 CHECKS KNOW IT: the one changed file (the dagger
# Pounce override) read as the 0.1.12 jar's bytes - P15 proves the real one is exactly the planned change of those bytes
JZ13 = JZ
OLD112 = os.path.join(HERE, "SkyyArmory-0.1.12.jar")
if not os.path.isfile(OLD112):
    raise SystemExit("the 0.1.13 harness needs SkyyArmory-0.1.12.jar (the base, the SET pin) next to it: %s" % OLD112)
OZ112 = zipfile.ZipFile(OLD112)
P13_POUNCE = "Server/Item/Interactions/Weapons/Daggers/Primary/Pounce/Weapon_Daggers_Primary_Pounce.json"


class Z112(object):
    """the 0.1.13 jar as the 0.1.12 checks know it (read only)"""
    def __init__(self, real, old, oldfiles):
        self.real, self.old, self.oldfiles = real, old, set(oldfiles)

    def namelist(self):
        return self.real.namelist()

    def read(self, n_):
        return self.old.read(n_) if n_ in self.oldfiles else self.real.read(n_)

    def close(self):
        self.real.close()
        self.old.close()


JZ = Z112(JZ13, OZ112, [P13_POUNCE])
# 0.1.12: JREAL = the real jar (P14 / R15);''')
# ---- R15e is history now: it compares 0.1.11 -> 0.1.12 (the 0.1.12 jar), R16e compares 0.1.12 -> 0.1.13
hrep('''    MN, MO = methods_of(JAR), methods_of(OLD111)''', '''    MN, MO = methods_of(OLD112), methods_of(OLD111)          # 0.1.13: R15e = the 0.1.12 round's compare (history); R16e = 0.1.12 -> 0.1.13''')

# ---- P15 (Python): the 0.1.13 files before the JVM part
P15 = r"""# ============================================================================================================ P15. 0.1.13 the log fixes (pure files)
_p15n, _p15o = json.loads(JZ13.read(P13_POUNCE).decode("utf-8")), json.loads(OZ112.read(P13_POUNCE).decode("utf-8"))
_p15v = aj("int", "Weapon_Daggers_Primary_Pounce")
check(_p15o.get("AllowIndefiniteHold") is False and _p15n.get("AllowIndefiniteHold") is True
      and dict((k_, v_) for k_, v_ in _p15n.items() if k_ != "AllowIndefiniteHold") == dict((k_, v_) for k_, v_ in _p15o.items() if k_ != "AllowIndefiniteHold")
      and _p15n["Next"] == {"0": "Weapon_Daggers_Primary_Chain", "0.4": "SkyyArmory_Shadow_Step_Launch"} and _p15v.get("AllowIndefiniteHold") is False
      and dict((k_, v_) for k_, v_ in _p15n.items() if k_ not in ("Next", "AllowIndefiniteHold")) == dict((k_, v_) for k_, v_ in _p15v.items() if k_ not in ("Next", "AllowIndefiniteHold")),
      "P15: the dagger Pounce = the 0.1.12 file + AllowIndefiniteHold true ONLY (0.1.12 and vanilla: false); keys 0 = the vanilla stab chain, "
      "0.4 = the Shadow Step launch; pose / particles / speed = vanilla: %s" % sorted(set(_p15n) ^ set(_p15o)))
_p15nn, _p15on = set(JZ13.namelist()), set(OZ112.namelist())
_p15d = sorted(n_ for n_ in _p15nn & _p15on if not n_.endswith(".class") and n_ != "manifest.json" and JZ13.read(n_) != OZ112.read(n_))
_p15m = json.loads(JZ13.read("manifest.json").decode("utf-8")), json.loads(OZ112.read("manifest.json").decode("utf-8"))
check(_p15nn == _p15on and _p15d == [P13_POUNCE] and dict(_p15m[0], Version=None, Name=None) == dict(_p15m[1], Version=None, Name=None)
      and _p15m[0]["Version"] == VERSION and _p15m[0]["Name"] == _p15m[1]["Name"].replace("0.1.12", VERSION),
      "P15: vs SkyyArmory-0.1.12.jar - the same file list, the only changed non-class file = the Pounce, the manifest = its version (Version + Name) only: %s %s" % (
          sorted(_p15nn ^ _p15on)[:4], _p15d[:4]))
print("P15. 0.1.13: the Pounce + AllowIndefiniteHold (fires on release, no overshoot WARN), every other file = 0.1.12's")
"""
hrep('''PY_OKS, PY_FAILS = OKS[0], len(FAILS)
''', P15 + '''PY_OKS, PY_FAILS = OKS[0], len(FAILS)
''')

# ---- R16 (JVM): after R15, before L2 (L2 changes the store)
R16 = r'''    # ============================================================================ R16. 0.1.13 THE LOG FIXES - every new path EXECUTED
    # R16a THE ENGINE ASSET VALIDATORS on the real 0.1.13 Pounce (+ its inline steps: none)
    o16n, w16n = validate14(INTc, "Weapon_Daggers_Primary_Pounce", JZ13.read(P13_POUNCE).decode("utf-8"))
    o16o, w16o = validate14(INTc, "Weapon_Daggers_Primary_Pounce", OZ112.read(P13_POUNCE).decode("utf-8"))
    check(o16n is not None and not w16n and o16o is not None and bool(fAIH15.getBoolean(o16n)) and not bool(fAIH15.getBoolean(o16o)),
          "R16a: the ENGINE ASSET VALIDATORS pass on the 0.1.13 Pounce; it decodes with allowIndefiniteHold = true (0.1.12: false): %s" % w16n)
    # R16b the engine's OWN charge check EXECUTED: ChargingInteraction.validateChargeValue(charge, context) on both decoded Pounces with a real
    # InteractionEntry meta store (CHARGE_START_NANOS), a real TimeResource (dilation 1) through a TBuf, a real Ref - the same code that wrote
    # Skyy's '[ChargingInteraction] .. charge value 0.402 exceeds max allowed 0.400 (wall: 0.399 ..)' lines
    TRS16 = JClass("com.hypixel.hytale.server.core.modules.time.TimeResource")
    TM16 = JClass("com.hypixel.hytale.server.core.modules.time.TimeModule")
    EM16 = JClass("com.hypixel.hytale.server.core.modules.entity.EntityModule")
    ICX16 = JClass("com.hypixel.hytale.server.core.entity.InteractionContext")
    IEN16 = JClass("com.hypixel.hytale.server.core.entity.InteractionEntry")
    IMG16 = JClass("com.hypixel.hytale.server.core.entity.InteractionManager")
    REF16 = JClass("com.hypixel.hytale.component.Ref")
    tm_old, em_old = jfield(TM16, "instance").get(None), jfield(EM16, "instance").get(None)
    tm16 = U.allocateInstance(TM16.class_)
    rt16 = U.allocateInstance(jfield(TM16, "timeResourceType").getType())
    setf(tm16, TM16, "timeResourceType", rt16)
    try:
        setf(tm16, TM16, "worldTimeResourceType", rt16)
    except Exception:
        pass
    em16 = U.allocateInstance(EM16.class_)
    setf(em16, EM16, "displayNameComponentType", U.allocateInstance(jfield(EM16, "displayNameComponentType").getType()))
    jfield(TM16, "instance").set(None, tm16)
    jfield(EM16, "instance").set(None, em16)
    TB16 = stub("TBuf16", CP_ + "CommandBuffer", ["public static Object RES = null;"],
                [GETC, "public " + CP_ + "Resource getResource(" + CP_ + "ResourceType t) { return (" + CP_ + "Resource) RES; }"])
    TB16.RES = TRS16()          # the world clock (dilation 1) the charge check reads
    vcv16 = CHI15.class_.getDeclaredMethod("validateChargeValue", JClass("java.lang.Float").TYPE, ICX16.class_)
    vcv16.setAccessible(True)
    csn16 = jfield(CHI15, "CHARGE_START_NANOS").get(None)
    NT16 = JClass("java.lang.System")

    def charge16(obj_, charge_, wall_):
        ent_ = IEN16(0, 0, 0)
        ctx_ = U.allocateInstance(ICX16.class_)
        setf(ctx_, ICX16, "entry", ent_)
        im_ = U.allocateInstance(IMG16.class_)
        setf(im_, IMG16, "commandBuffer", U.allocateInstance(TB16.class_))
        setf(ctx_, ICX16, "interactionManager", im_)
        setf(ctx_, ICX16, "runningForEntity", REF16(None, 16))
        ent_.getMetaStore().putMetaObject(csn16, JClass("java.lang.Long")(int(NT16.nanoTime()) - int(wall_ * 1e9)))
        n0_ = len(records())
        err_ = None
        try:
            vcv16.invoke(obj_, JArray(JClass("java.lang.Object"))([JClass("java.lang.Float")(charge_), ctx_]))
        except Exception as e_:
            c_ = e_
            while c_.getCause() is not None:
                c_ = c_.getCause()
            err_ = str(c_)[:200]
        return [m_ for lv_, m_ in records()[n0_:] if "exceeds max allowed" in m_], err_
    ch16 = {}
    try:
        for tag_, o_ in (("0.1.12", o16o), ("0.1.13", o16n)):
            ch16[tag_] = [charge16(o_, 0.402, 0.399), charge16(o_, 0.38, 0.38), charge16(o_, 0.9, 0.3)]
    finally:
        jfield(TM16, "instance").set(None, tm_old)
        jfield(EM16, "instance").set(None, em_old)
    o12, o13 = ch16.get("0.1.12"), ch16.get("0.1.13")
    check(o12 is not None and o13 is not None and all(e_ is None for row_ in (o12, o13) for w_, e_ in row_)
          and len(o12[0][0]) == 1 and "charge value 0.402 exceeds max allowed 0.400" in o12[0][0][0] and o13[0][0] == []
          and o12[1][0] == [] and o13[1][0] == [] and len(o12[2][0]) == 1 and len(o13[2][0]) == 1 and "max allowed 0.5" in o13[2][0][0],
          "R16b: the engine's validateChargeValue EXECUTED - Skyy's case (0.402 after 0.399 s): 0.1.12 logs the WARN from the log scan, 0.1.13 "
          "does not; a fair hold (0.38 / 0.38) neither; a client claiming 0.9 after 0.3 s still WARNs on 0.1.13 (allowed = held + 0.25 = "
          "0.55: the anti-cheat stays): %s" % json.dumps(ch16)[:700])
    # R16c into the store, then the dagger root compiles: Charging (vanilla 0 / 0.2) -> ... -> our Pounce (Charging) -> the launch, 0 missing
    load(INTc, [o16n], PACK)
    nm16a = len([m_ for lv_, m_ in records() if "Missing interaction" in m_])
    res16 = compile_root("SkyyArmoryTest_ShadowRoot")
    nm16b = len([m_ for lv_, m_ in records() if "Missing interaction" in m_])
    ops16 = [x_ for x_ in res16["ops"] if x_[1] is not None]
    check(not res16["bad"] and nm16b == nm16a and ("ChargingInteraction", "Weapon_Daggers_Primary_Pounce") in ops16
          and ("LaunchProjectileInteraction", "SkyyArmory_Shadow_Step_Launch") in ops16
          and bool(fAIH15.getBoolean(INTc.getAssetMap().getAsset("Weapon_Daggers_Primary_Pounce"))),
          "R16c: the 0.1.13 Pounce in the store; RootInteraction.build() of the Shadow Step root = Charging (our Pounce, indefinite hold) -> the "
          "Shadow Step launch, 0 missing interactions: %s" % (res16["bad"][:2] + ops16[:4]))
    # R16d THE STAFF HANDOVER RE-READ on the real stores, then ArmoryCheck.packOf (the real class) with and without AssetModule answering
    AMc16 = JClass("com.hypixel.hytale.server.core.asset.AssetModule")
    APc16 = JClass("com.hypixel.hytale.assetstore.AssetPack")
    psrc16 = APc16.class_.getDeclaredConstructors()[0].getParameterTypes()[6].getEnumConstants()[2]
    w16 = os.path.join(SCRATCH, "r16")
    SKP16 = "Skyy:%s SkyySkills" % SKILLS_PIN
    src16 = ["Weapon_Staff_%s" % m_ for m_ in METALS] + ["Weapon_Staff_Bo_Wood", "Weapon_Staff_Bo_Bamboo"]
    # test ids (the store's real entries stay as they are for the checks after this one): each item = that staff's vanilla file (its inline
    # vars' Parent renamed to the 2 test parents), then ours; the 2 test parents = the vanilla Staff_Cast_Summon_Charged / Staff_Cast_Cost
    # (Hytale), then SkyySkills' overrides of them (its pack) - the real server's order (Next / Failed left out: only the Parent link counts)
    ids16 = ["SkyyArmoryTest16_" + i_[len("Weapon_Staff_"):] for i_ in src16]
    par16 = {"Staff_Cast_Summon_Charged": "SkyyArmoryTest16_Summon_Charged", "Staff_Cast_Cost": "SkyyArmoryTest16_Cast_Cost"}

    def ren16(x_):
        if isinstance(x_, dict):
            return dict((k_, par16.get(v_, v_) if k_ == "Parent" else ren16(v_)) for k_, v_ in x_.items())
        if isinstance(x_, list):
            return [ren16(v_) for v_ in x_]
        return x_

    def put16(sub_, name_, obj_):
        d_ = os.path.join(w16, sub_)
        os.makedirs(d_, exist_ok=True)
        p_ = os.path.join(d_, name_ + ".json")
        with open(p_, "w", encoding="utf-8") as f_:
            f_.write(json.dumps(obj_, indent=1))
        return Paths.get(p_)

    def loadp16(c_, pack_, paths_):
        l_ = ArrayList()
        for p_ in paths_:
            l_.add(p_)
        return not AR.getAssetStore(c_.class_).loadAssetsFromPaths(pack_, l_).hasFailed()
    vp16, ap16 = [], []
    for i_, s_ in zip(ids16, src16):
        vj_ = aj("item", s_)
        vm_ = dict((k_, v_) for k_, v_ in vj_.items() if k_ in ("TranslationProperties", "Categories", "Tags"))
        vm_["InteractionVars"] = ren16(dict((k_, v_) for k_, v_ in (vj_.get("InteractionVars") or {}).items() if isinstance(v_, dict)))
        vp16.append(put16("H/Server/Item/Items", i_, vm_))
        aj_ = json.loads(JZ13.read([n_ for n_ in JN if n_.startswith("Server/Item/Items/") and n_.endswith("/%s.json" % s_)][0]).decode("utf-8"))
        ap16.append(put16("A/Server/Item/Items", i_, dict((k_, v_) for k_, v_ in aj_.items() if k_ in ("TranslationProperties", "Categories", "Tags"))))
    UNI16 = JClass("com.hypixel.hytale.server.core.universe.Universe")
    pbu16 = jfield(UNI16, "playersByUuid").get(UNI16.get())          # the stand-in players have no packet handler: no broadcast while R16d loads
    keep16 = HashMap(pbu16)
    pbu16.clear()
    vpar16 = []
    for b_, t_ in sorted(par16.items()):
        vpj_ = dict((k_, v_) for k_, v_ in aj("int", b_).items() if k_ not in ("Next", "Failed"))
        vpar16.append(put16("H/Server/Item/Interactions", t_, vpj_))
    ok16 = [loadp16(INTc, "Hytale:Hytale", vpar16)]
    ok16 += [loadp16(ITMc, "Hytale:Hytale", vp16), loadp16(ITMc, PACK, ap16)]
    imap16 = ITMc.getAssetMap()
    mid16 = sorted(set(str(imap16.getAssetPack(i_)) for i_ in ids16))
    sp16 = []
    for b_ in ("Staff_Cast_Cost", "Staff_Cast_Summon_Charged"):
        sj_ = json.loads(SKZ.read([n_ for n_ in SKZ.namelist() if n_.startswith("Server/Item/Interactions/") and n_.endswith("/%s.json" % b_)][0]).decode("utf-8"))
        sp16.append(put16("S/Server/Item/Interactions", par16[b_], dict((k_, v_) for k_, v_ in sj_.items() if k_ not in ("Next", "Failed"))))
    ok16.append(loadp16(INTc, SKP16, sp16))
    after16 = dict((i_, [str(imap16.getAssetPack(i_)), os.path.normcase(str(imap16.getPath(i_))).startswith(os.path.normcase(os.path.join(w16, "A")))]) for i_ in ids16)
    oth0, mis0 = ArrayList(), ArrayList()
    ACk16 = JClass(PKG + "ArmoryCheck")
    mine0 = int(ACk16.packOf(imap16, JArray(JString)(ids16), oth0, mis0))
    rr0 = [str(x_) for x_ in ACk16.REREAD]
    am16 = U.allocateInstance(AMc16.class_)
    pk16 = ArrayList()
    for r_, n_ in ((os.path.join(w16, "H"), "Hytale:Hytale"), (os.path.join(w16, "A"), PACK), (os.path.join(w16, "S"), SKP16)):
        pk16.add(APc16(Paths.get(r_), n_, Paths.get(r_), Paths.get(r_).getFileSystem(), False, None, psrc16))
    setf(am16, AMc16, "assetPacks", pk16)
    am_old16 = jfield(AMc16, "instance").get(None)
    jfield(AMc16, "instance").set(None, am16)
    try:
        ACk16.REREAD.clear()
        oth1, mis1 = ArrayList(), ArrayList()
        mine1 = int(ACk16.packOf(imap16, JArray(JString)(ids16), oth1, mis1))
        rr1 = [str(x_) for x_ in ACk16.REREAD]
        fp16 = [str(ACk16.filePack(imap16, ids16[0])), str(ACk16.filePack(imap16, "No_Such_Item_ZZ")), str(ACk16.filePack(None, ids16[0]))]
    finally:
        jfield(AMc16, "instance").set(None, am_old16)
        ACk16.REREAD.clear()
    check(all(ok16) and mid16 == [PACK] and all(v_ == [SKP16, True] for v_ in after16.values())
          and mine0 == 0 and oth0.size() == 10 and rr0 == []
          and mine1 == 10 and oth1.size() == 0 and len(rr1) == 10 and all(("(%s)" % SKP16) in x_ for x_ in rr1)
          and fp16 == [PACK, "None", "None"],
          "R16d: the re-read REPRODUCED on the real stores (10 test items = the 8 ladder + 2 Bo staffs' vanilla files, then ours) - after our files load (ours), SkyySkills' Staff_Cast_* overrides make the "
          "engine re-read them: label %s, file still ours; packOf without AssetModule = 'another pack' x10 (the 0.1.12 WARN), with "
          "AssetModule.findAssetPackForPath answering = ours x10, listed in REREAD; filePack: ours / unknown id / no map: %s %s %s" % (
              SKP16, json.dumps(after16)[:300], [mine0, oth0.size(), mine1, oth1.size()], fp16))
    pbu16.putAll(keep16)
    # R16e: vs the 0.1.12 jar - file by file (P15) and METHOD BY METHOD
    MN16, MO16 = methods_of(JAR), methods_of(OLD112)
    cmp16 = {}
    for c_ in sorted(set(MN16) | set(MO16)):
        if c_ not in MN16 or c_ not in MO16:
            cmp16[c_] = "only in " + ("0.1.13" if c_ in MN16 else "0.1.12")
            continue
        ch_ = sorted(k_ for k_ in set(MN16[c_][0]) | set(MO16[c_][0]) if MN16[c_][0].get(k_) != MO16[c_][0].get(k_))
        fd_ = sorted(set(MN16[c_][1]) ^ set(MO16[c_][1]))
        if ch_ or fd_:
            cmp16[c_] = {"methods": [k_.split("(")[0] for k_ in ch_], "fields": [f_.split(":")[0] for f_ in fd_]}
    check(cmp16 == {"ArmoryCheck": {"methods": ["filePack", "packCheck", "packOf"], "fields": ["REREAD"]}},
          "R16e: 0.1.12 -> 0.1.13 METHOD BY METHOD - only ArmoryCheck differs (packOf + packCheck changed, filePack + REREAD new; the version "
          "text normalised): %s" % json.dumps(cmp16)[:800])
    print("R16. 0.1.13: Pounce validators + allowIndefiniteHold, the engine's charge check (0.1.12 WARN / 0.1.13 none / cheat WARN), the root "
          "compile, the staff re-read reproduced + packOf with / without AssetModule, the 0.1.12 compare - every path executed")
'''
hrep('''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''',
     R16 + '''    # ---------------- L2. (last: it changes the store) another pack wins one interaction with a wrong number -> ONE WARN naming both''')
# methods_of normalises 0.1.12 / 0.1.11 -> V; 0.1.13 too now
hrep('''                ms_["%s%s" % (m_.getName(), m_.getSignature())] = t_.replace("0.1.12", "V").replace("0.1.11", "V")''',
     '''                ms_["%s%s" % (m_.getName(), m_.getSignature())] = t_.replace("0.1.13", "V").replace("0.1.12", "V").replace("0.1.11", "V")''')

out_t = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(out_t)
print("wrote %s" % os.path.relpath(TDST, ROOT))
