"""Derive SkyyArmory/build_skyyarmory_0.1.10.py (+ its harness SkyyArmory/test_skyyarmory_0.1.10.py) from the GENERATED 0.1.9
(SkyyArmory/build_skyyarmory_0.1.9.py = the tools/deploy_set.py SET pin, made by tools/armory_0_1_9_patch.py; test_skyyarmory_0.1.9.py =
its harness). Every anchor is asserted (rep = exactly one hit). Edit THIS file, never the generated scripts.
Run:  python tools/armory_0_1_10_patch.py   then   python SkyyArmory/build_skyyarmory_0.1.10.py   then   python SkyyArmory/test_skyyarmory_0.1.10.py
      (never --deploy)

0.1.10 = HOTFIX (Skyy 2026-10-08, joining the world: "Asset validation failed: Mod Skyy:0.1.9 SkyyArmory failed to load"): the 7 spellbook
Levitate interactions (SkyyArmory_Spellbook_Lev_<Metal>, since 0.1.6) wrapped their one launch in a Parallel with ONE entry; the engine's
validator wants a Parallel of at least 2 ("Array size is invalid! Was 1, expected between 2 and ...") and refuses the whole pack, so the
server shuts down before you join. Now the Simple's Next names the launch interaction directly (like the vanilla Next strings), nothing else
changes. The harness gains P0: every Parallel in the jar has 2+ entries (the codec decode in L did not run this validator).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.9.py")
DST = os.path.join(ROOT, "SkyyArmory", "build_skyyarmory_0.1.10.py")
TSRC = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.9.py")
TDST = os.path.join(ROOT, "SkyyArmory", "test_skyyarmory_0.1.10.py")

CR, LF = chr(13), chr(10)
raw = open(SRC, encoding="utf8", newline="").read()
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.9"\nMOD = "SkyyArmory"' in s and "0.1.9 = THE CLASS TREE READER" in s, "build_skyyarmory_0.1.9.py is not the 0.1.9 pin"


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


# header + version
rep('''"""SkyyArmory 0.1.9 - build script (javassist via jpype). GENERATED by tools/armory_0_1_9_patch.py from the GENERATED 0.1.8 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.9.py -> SkyyArmory/SkyyArmory-0.1.9.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.9.py (scratch tools/dev/scratch/armory019/).''',
    '''"""SkyyArmory 0.1.10 - build script (javassist via jpype). GENERATED by tools/armory_0_1_10_patch.py from the GENERATED 0.1.9 - edit the
patch, never this file. Run: python SkyyArmory/build_skyyarmory_0.1.10.py -> SkyyArmory/SkyyArmory-0.1.10.jar (never --deploy). Harness:
python SkyyArmory/test_skyyarmory_0.1.10.py (scratch tools/dev/scratch/armory0110/).

0.1.10 = HOTFIX: the 7 spellbook Levitate interactions name their launch directly (a one-entry Parallel failed the engine's asset
validation and the server refused the pack - Skyy could not join, 2026-10-08). Nothing else changed.

0.1.9 (the base, everything below is still true):''')
rep('VERSION = "0.1.9"\nMOD = "SkyyArmory"', 'VERSION = "0.1.10"\nMOD = "SkyyArmory"')
# the fix
rep('''    add_bk(P_BINT, ID_BLEV % _m, {"Type": "Simple", "RunTime": 0.167, "Next": {"Type": "Parallel", "Interactions": [inline_root(ID_BLEVL % _m)]}})''',
    '''    add_bk(P_BINT, ID_BLEV % _m, {"Type": "Simple", "RunTime": 0.167, "Next": ID_BLEVL % _m})          # 0.1.10: no one-entry Parallel (fails validation)''')

with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(s.replace(LF, NL))
print("wrote %s" % os.path.relpath(DST, ROOT))

# ================================================================================================ harness
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('"""SkyyArmory 0.1.9 - test harness. GENERATED by tools/armory_0_1_9_patch.py from test_skyyarmory_0.1.8.py - edit the patch, never this file.',
     '''"""SkyyArmory 0.1.10 - test harness. GENERATED by tools/armory_0_1_10_patch.py from test_skyyarmory_0.1.9.py - edit the patch, never this file.
Every 0.1.9 check still runs; the old-jar compares (R11e, R12f, R13f) allow the 7 changed Levitate interaction files. NEW P0: every Parallel
in the jar has at least 2 entries (the engine validator; a one-entry Parallel refuses the whole pack).

0.1.9 harness: SkyyArmory 0.1.9 - test harness. GENERATED by tools/armory_0_1_9_patch.py from test_skyyarmory_0.1.8.py - edit the patch, never this file.''')
hrep('VERSION = "0.1.9"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.9 SkyyArmory"',
     'VERSION = "0.1.10"\nMOD = "SkyyArmory"\nPKG = "com.skyy.armory."\nPACK = "Skyy:0.1.10 SkyyArmory"')
hrep('os.path.join(SCRATCH_ROOT, "armory019", "harness")', 'os.path.join(SCRATCH_ROOT, "armory0110", "harness")')
hrep('raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.9.py', 'raise SystemExit("build first: python SkyyArmory/build_skyyarmory_0.1.10.py')
hrep('Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.9"))', 'Paths.get(os.path.join(troot, "Skyy_SkyyArmory-0.1.10"))')
hrep('"[SkyyArmory] 0.1.9 ready" in m_', '"[SkyyArmory] 0.1.10 ready" in m_')
hrep('"0.1.9 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_', '"0.1.10 magic traversals: traversals on (Stamina 50% of the Mana, cap " in m_')
hrep('"0.1.9 crossbow grapple: grapple on" in m_', '"0.1.10 crossbow grapple: grapple on" in m_')
hrep('come from Skyy:0.1.9 SkyyArmory" in str(r[1])', 'come from Skyy:0.1.10 SkyyArmory" in str(r[1])')

# the old-jar compares: the 7 Levitate files changed on purpose
LEVF = ('LEV0110 = set("Server/Item/Interactions/Weapons/Spellbook/SkyyArmory/SkyyArmory_Spellbook_Lev_%s.json" % m_ for m_ in '
        '("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium"))   # 0.1.10: changed on purpose\n')
hrep('''            diff_ = [n_ for n_ in on_ if n_ in JSET and not n_.endswith(".class") and n_ not in ("manifest.json", "Server/Languages/en-US/server.lang")
                     and oz_.read(n_) != JZ.read(n_)]
            ddiff = []''',
     '''            diff_ = [n_ for n_ in on_ if n_ in JSET and not n_.endswith(".class") and n_ not in ("manifest.json", "Server/Languages/en-US/server.lang")
                     and n_ not in LEV0110 and oz_.read(n_) != JZ.read(n_)]
            ddiff = []''')
hrep('''            diff_ = [n_ for n_ in on_ if n_ in JSET and not n_.endswith(".class") and n_ != "manifest.json" and oz_.read(n_) != JZ.read(n_)]''',
     '''            diff_ = [n_ for n_ in on_ if n_ in JSET and not n_.endswith(".class") and n_ != "manifest.json" and n_ not in LEV0110 and oz_.read(n_) != JZ.read(n_)]''',
     count=2)

# P0: no Parallel with fewer than 2 entries anywhere in the jar (J = every JSON of the jar, before the older checks reshape it)
hrep('''L17_REAL = {}          # the 22 caster items as shipped''',
     LEVF + '''_p0bad = []


def _p0walk(o_, n_):
    if isinstance(o_, dict):
        if o_.get("Type") == "Parallel" and (not isinstance(o_.get("Interactions"), list) or len(o_["Interactions"]) < 2):
            _p0bad.append(n_)
        for v_ in o_.values():
            _p0walk(v_, n_)
    elif isinstance(o_, list):
        for v_ in o_:
            _p0walk(v_, n_)


for _p0n, _p0d in sorted(J.items()):
    _p0walk(_p0d, _p0n)
check(not _p0bad, "P0 (0.1.10): every Parallel has at least 2 entries (the engine refuses the pack otherwise): %s" % _p0bad[:4])
check(all(J[n_]["Next"] == "SkyyArmory_Spellbook_Lev_Launch_" + n_.split("_Lev_")[1][:-5] for n_ in LEV0110),
      "P0 (0.1.10): the 7 Levitate interactions name their launch directly")
print("P0. 0.1.10: no one-entry Parallel in %d JSON files; the 7 Levitate interactions name their launch" % len(J))
L17_REAL = {}          # the 22 caster items as shipped''')

out_t = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(out_t)
print("wrote %s" % os.path.relpath(TDST, ROOT))
