"""Derive SkyyBank/build_skyybank_0.1.4.py from the LIVE 0.1.3 (build_skyybank_0.1.3.py = the tools/deploy_set.py SET pin).
Run:  python tools/bank_0_1_4_patch.py   then   python SkyyBank/build_skyybank_0.1.4.py   (never --deploy: coordinated deploy)
SkyyBank uses patch scripts from 0.1.4 on (0.1.1 - 0.1.3 were copy + edit): edit THIS file, never the generated build script.

0.1.4 = the vanilla UI pass, PILOT of the shared kit tools/skyyui.py (Skyy 2026-09-28: "the new goal for any and all UI added in the
game is for them to look and feel vanilla"; HANDOFF section 2 rule 0; research/Vanilla-UI-Style-Guide.md section 7 "Restyling an
existing page"; research/Skyy-UI-Inventory.md 5.3). ONLY THE LOOK OF BankPage CHANGES:
  - the generated script imports skyyui as SUI and calls SUI.verify() before anything else (every vanilla value proven against
    Assets.zip at every build), and puts SUI.kit_id() into the ready log line;
  - BankPage.style() (the custom TextButtonStyle triple) is gone; BankPage.colorOf / textOf become the kit's java_status_methods()
    (same names and signatures; "+" / "-" / "=" in the vanilla success / error / SUI.STATUS["="] colours);
  - BankPage.build() keeps 0.1.3's Java prelude and its 7 event bindings VERBATIM (cut out of 0.1.3 by this patch, not retyped) and
    replaces only the markup: a Python function bank_page() in the generated script builds the page from kit calls (page_shell,
    panel "well", label kinds, text_field, button kinds, group, status_line, separator) and emits the Java with the kit's emitters.
Everything else (commands, permissions, BankStore, BankConfig, BankTick, BankJob, texts, amounts, files, bridge keys, jsonStr, typed,
handleDataEvent, openPage) is byte-identical to 0.1.3 - asserted below.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyBank", "build_skyybank_0.1.3.py")
dst = os.path.join(ROOT, "SkyyBank", "build_skyybank_0.1.4.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
assert len(BIND0) == 7, "0.1.3 has 7 event bindings, found %d" % len(BIND0)


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def cut(a, b, new=""):
    """replace everything from anchor a (included) up to anchor b (kept) with new; returns the text that was cut"""
    global s
    assert s.count(a) == 1, "cut start count %d: %s" % (s.count(a), a[:120])
    assert s.count(b) == 1, "cut end count %d: %s" % (s.count(b), b[:120])
    i, j = s.index(a), s.index(b)
    assert i < j, "cut anchors out of order: %s / %s" % (a[:60], b[:60])
    old = s[i:j]
    s = s[:i] + new + s[j:]
    return old


def block(a, b):
    """the text from anchor a (included) to anchor b (excluded) of the CURRENT source (for unchanged-block asserts)"""
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


# blocks that must come out of this patch byte-identical (everything but the BankPage look + header / version / log line)
KEEP = [block("# ================= BankStore =================", "# ================= BankPage (0.1.3; inline"),
        block("# one string value out of the page event JSON", "PM(r\"\"\"\npublic static String colorOf(String res) {"),
        block("# 2475000 ms -> \"41 min 15 s\"; 7500000 -> \"2 h 5 min\"", "PM(r\"\"\"\npublic void build(@REF@ ref"),
        block("# clicks run on the player's world thread (page events)", "# ================= plugin ================="),
        block("for c in (bs, cfg, tick, job, cmd, cmdA, cmdN, adm, admS, admM, page, pl):", "m = B.manifest(")]

# ================================================================================================ docstring
HEAD_OLD = '''"""SkyyBank 0.1.3 - build script (javassist via jpype).
Run:   python build_skyybank_0.1.3.py            -> SkyyBank/SkyyBank-0.1.3.jar
       (no --deploy in this script on purpose: tools/deploy_set.py installs the whole set once Skyy says deploy)
SkyBlock-style bank: /bank (opens the bank page, 0.1.3), /bank balance, /bank status, /bank deposit <n|all|2k|1.5m>,
/bank withdraw <n|all>.

'''
HEAD_NEW = '''"""SkyyBank 0.1.4 - build script (javassist via jpype). GENERATED by tools/bank_0_1_4_patch.py from the LIVE 0.1.3
(build_skyybank_0.1.3.py, the tools/deploy_set.py SET pin) - edit the patch, never this file.
Run:   python build_skyybank_0.1.4.py            -> SkyyBank/SkyyBank-0.1.4.jar
       (no --deploy in this script on purpose: tools/deploy_set.py installs the whole set once Skyy says deploy)
SkyBlock-style bank: /bank (opens the bank page, 0.1.3), /bank balance, /bank status, /bank deposit <n|all|2k|1.5m>,
/bank withdraw <n|all>.

0.1.4 (2026-09-29, the vanilla UI pass - Skyy 2026-09-28: "the new goal for any and all UI added in the game is for them to look and
feel vanilla"; HANDOFF section 2 rule 0; research/Vanilla-UI-Style-Guide.md): the PILOT restyle on the shared kit tools/skyyui.py.
  ONLY THE LOOK OF THE BANK PAGE CHANGED. Commands, permissions, chat texts, amounts, the coins bridge, profiles, interest, files,
  the bridge key bank:<uuid>, every element id of 0.1.3, every b.set target and value, the TextField #SkyyBAmount and its @BAmount
  payload, the 7 event bindings (copied out of 0.1.3 by the patch, not retyped) and the page logic (jsonStr, typed, handleDataEvent:
  Enter never moves coins, keepAmount, rebuilt only after a click, Close = CustomUIPage.close()) are 0.1.3's; the patch asserts it.
  - The build calls SUI.verify() first: every vanilla style value, texture and sound the page uses is proven against Assets.zip
    (read-only) at every build, and a game update that changes one stops the build. KIT_ID (kit version + file hash) is in the ready
    log line.
  - Window: the vanilla decorated container (page_shell: the ContainerHeader title bar with its runes and the two gold ornaments, the
    title BANK in the 15 px Secondary title style, the ContainerPatch body with the container padding 17). The page root is the new
    #SkyyBankF (Anchor Width / Height only, 1100 x 580 - 0.1.3 was 1100 x 680 without a frame; the body is 1066 x 508 inside the
    frame); 0.1.3's root #SkyyBank is now the body, so every appendInline target
    "#SkyyBank" is unchanged. Gone: the dark-blue root panel, the gold accent stripe and the big custom title label (the frame title
    replaces them), and the empty Label spacers (vanilla Anchor margins instead).
  - Purse / Bank (#SkyyBPurseBox / #SkyyBBankBox in #SkyyBBal): two vanilla wells (the translucent black inset of WorldEventPanelPage
    #Summary) side by side, each with a 15 px bold uppercase subtitle (PURSE / BANK), the number (#SkyyBPurse / #SkyyBBalance) in
    the vanilla display style (32 px Secondary font, PortalDeviceSummon) and a grey caption.
  - Interest (#SkyyBInt): one well with the rate line in the vanilla heading style (18 px bold, WorldEventPanelPage #PageTitle), the
    next-payout time in the default label style and the payout line in the vanilla success green (the vanilla error red when the
    account file cannot be read - the only colour that now depends on the state; the texts are 0.1.3's).
  - Controls (#SkyyBCtl, same order): Deposit all | Amount | Deposit | Withdraw | Withdraw all. Deposit all + Deposit = vanilla
    Primary buttons (gold), Withdraw + Withdraw all = vanilla Secondary; every button has the vanilla hover / press / disabled
    textures and the vanilla ButtonsLight sounds. The amount box is the vanilla text field (InputBox.png) around #SkyyBAmount, 16 px
    (the kit look; the text-field look is still Skyy's pick on probe page 2). Captions under the controls in the vanilla caption grey.
  - Result line #SkyyBInfo: the kit status line (16 px bold, centred, wraps to two lines): done = vanilla success green, refused =
    vanilla error red, info (=) = SUI.STATUS["="] (gold for now - Skyy's open pick between gold and the info blue). The chat hint
    line is a vanilla caption.
  - Footer: the vanilla content separator (1 px, 8 px above and below), then Refresh (Secondary) on the left and Close (Secondary with
    the vanilla cancel sound) on the right, like WorldEventPanelPage's footer. Esc still closes the page (CanDismiss).
  - Layout uses only what Skyy pages already proved inline (LayoutMode Top / Left, fixed widths, Anchor margins); the heights are
    budgeted to fill the body exactly (bank_page() asserts fit == 0), so no FlexWeight filler is needed.
  - Kit additions made for this page (skyyui 1.2, tested in tools/skyyui_test.py): group() (a plain layout row / column) and
    status_line(wrap=, max_lines=, anchor=). No UNVERIFIED (trial) kit element is used.
  CHECKED in a bare JVM (2026-09-29, scratch harness under tools/dev/scratch/ui-pilot-bank, deleted afterwards; HytaleServer.jar on the
    classpath, -Xverify:all + init on all 12 classes of 0.1.4 and of 0.1.3): the 10 classes other than BankPage and SkyyBankPlugin
    are byte-identical to 0.1.3; a differential run of 0.1.3 and 0.1.4 side by side (7 states: readable purse + profile, unreadable
    purse, no SkyyCoins, unreadable account file, interest off, bank above the principal cap, no profile + empty bank; 13 clicks in
    three of them: Refresh, Deposit with an empty box, 2k, 1,500, too much, not a number, Enter with and without an amount, Deposit
    all, Withdraw all, withdraw all typed, an unknown action, Close) = 46 page builds with identical b.set texts, identical 7 event
    bindings, identical info / amount box / rebuild / close() calls and identical coins in purse and bank; every appended markup of
    those builds (1564) passed the kit test's own checks (skyyui_test.markup_ok: check_markup, ids + prefix, no document variables,
    verified paths only, kit colours only, SkyyRanks 0.1.1 _check_ui, the java_lit round trip, lint's underscore-id rule;
    check_page on each build) and matched the Python kit markup exactly, with only kit colours at the two runtime colour spots
    (status line by mark; payout line green, red for an unreadable account).
  UNVERIFIED (needs the game): the whole new look - the kit's "base" look has not been seen in game yet (skyyui probe pages 1 and 2:
    frame + ornaments, button textures / inline Sounds / Disabled state / ShrinkTextToFit, the title's LetterSpacing, WrapMaxLines on
    the heading). Open this page only after Skyy has opened probe pages 1 and 2, or together with them on a test server.

'''
rep(HEAD_OLD, HEAD_NEW)

# ================================================================================================ version, kit import, log line
rep('VERSION = "0.1.3"', 'VERSION = "0.1.4"')
rep("import skyybuild as B\n", """import skyybuild as B
import skyyui as SUI       # 0.1.4: the ONE shared vanilla UI kit (research/Vanilla-UI-Style-Guide.md); not "as UI"
SUI.verify()               # proves every vanilla value / texture / sound the page uses against Assets.zip (read-only); stops the build on drift
KIT_ID = SUI.kit_id()      # "skyyui <version> <blob12>" - in the ready log line
""")
rep('log("[SkyyBank] {VERSION} ready - /bank (page), interest "', 'log("[SkyyBank] {VERSION} ready ({KIT_ID}) - /bank (page), interest "')

# ================================================================================================ BankPage: the look only
rep("# ================= BankPage (0.1.3; inline, rebuilt only after a click) =================",
    "# ================= BankPage (0.1.3 logic; 0.1.4 look = the vanilla UI kit tools/skyyui.py; inline, rebuilt only after a click) =================")

# the custom button style helper is replaced by the kit's button styles
cut('PM(r"""\npublic static String style(String bg, String hov, String press, String fg, int fs) {',
    "# one string value out of the page event JSON")

# the result-line colour / text helpers: the kit's (same names, same signatures, vanilla colours)
cut('PM(r"""\npublic static String colorOf(String res) {', '# 2475000 ms -> "41 min 15 s"; 7500000 -> "2 h 5 min"',
    '''# 0.1.4: the result-line helpers are the kit's (same names and signatures as 0.1.3): colorOf picks the vanilla colour by the mark
# ("+" success, "-" error, "=" SUI.STATUS["="]), textOf strips the mark.
for _src in SUI.java_status_methods("colorOf", "textOf"):
    PM(_src)
''')

# build(): keep 0.1.3's prelude and bindings verbatim, replace the markup
OLD_BUILD = cut('PM(r"""\npublic void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {', "# clicks run on the player's world thread (page events)",
                "@@NEWBUILD@@")
_lines = OLD_BUILD.split(LF)
_p0 = [i for i, ln in enumerate(_lines) if ln.startswith("  java.util.UUID u = this.playerRef.getUuid();")]
_p1 = [i for i, ln in enumerate(_lines) if ln.startswith("  long left = @PKG@.BankConfig.LAST")]
assert len(_p0) == 1 and len(_p1) == 1 and _p0[0] < _p1[0], "0.1.3 build prelude not found"
PRELUDE = LF.join(_lines[_p0[0]:_p1[0] + 1])
BINDINGS = LF.join(ln for ln in _lines if "ev.addEventBinding(" in ln)
assert BINDINGS.split(LF) == BIND0
KEEPSET = [ln for ln in _lines if "b.set(\"#SkyyBAmount.Value\"" in ln]
assert KEEPSET == ['  if (this.keepAmount != null && this.keepAmount.length() > 0) b.set("#SkyyBAmount.Value", this.keepAmount);'], KEEPSET
# the 0.1.3 b.set targets and values (Java expressions), to prove 0.1.4 sets the same things
SETS013 = re.findall(r'b\.set\("#(SkyyB[A-Za-z0-9]+)\.Text", (.+?)\);', OLD_BUILD)
assert len(SETS013) == 9, SETS013
IDS013 = sorted(set(re.findall(r"#(SkyyB[A-Za-z0-9]*)", OLD_BUILD)))
assert len(IDS013) == 25, (len(IDS013), IDS013)

NEWBUILD = '''# 0.1.4: the page look from the vanilla UI kit. bank_page() builds the markup with kit calls (every value proven by SUI.verify() above)
# and returns the page shell + the b.set lines; the Java below keeps 0.1.3's prelude and event bindings verbatim.
BANK_W, BANK_H = 1100, 580            # page root (the frame adds 38 px of title bar + 2 x 17 px padding: inner 1066 x 508)
BANK_PREFIX = "SkyyB"                 # every element id starts with it (the 0.1.3 ids already did)
# every element id 0.1.3 had - all kept (the Java binds / sets / reads them); bank_page() asserts each one is still created
BANK_IDS_013 = %(ids)r
# 0.1.3's b.set("#<id>.Text", <Java expression>) lines, unchanged
BANK_SETS_013 = %(sets)r


def bank_page():
    """(shell, sets): BankPage's markup from the kit. Heights and widths are budgeted to fill the body exactly (asserted)."""
    sh = SUI.page_shell("SkyyBankF", BANK_W, BANK_H, "Bank", body_id="SkyyBank")      # decorated window; the 0.1.3 root is the body
    ap, body, W = sh.appends, sh.body, sh.inner_w
    heights = []

    def add(parent, markup, h=0):
        ap.append((parent, markup))
        heights.append(h)

    # profile / hint line (0.1.3 #SkyyBSub; its text is b.set)
    add(body, SUI.label("SkyyBSub", "", "default", h=26, align="Center", anchor={"bottom": 12}), 26 + 12)
    # PURSE and BANK: two wells side by side (WorldEventPanelPage #Summary inset), subtitle / display number / caption
    bal_h, gap = 120, 12
    box_w = (W - gap) // 2
    SUI.fit([box_w, gap, box_w], W, "balance row")
    add(body, SUI.group("SkyyBBal", "Left", h=bal_h, anchor={"bottom": 16}), bal_h + 16)
    inner = [25, 46, 25]
    SUI.fit(inner, bal_h - 2 * 12, "balance well")
    for box, num, head, cap, left in (("SkyyBPurseBox", "SkyyBPurse", "Purse", "coins you carry - lost in part when you die", None),
                                      ("SkyyBBankBox", "SkyyBBalance", "Bank", "coins in the bank - safe when you die", {"left": gap})):
        ap.append(("SkyyBBal", SUI.panel(box, "well", w=box_w, h=bal_h, pad={"horizontal": 8, "vertical": 12}, anchor=left)))
        ap.append((box, SUI.label(None, head, "subtitle", h=inner[0], align="Center")))
        ap.append((box, SUI.label(num, "", "display", h=inner[1], align="Center")))
        ap.append((box, SUI.label(None, cap, "caption", h=inner[2], align="Center")))
    # interest: one well - the rate (vanilla heading), the next payout time, the payout line (success green / error red if unreadable)
    int_h, int_rows = 100, [28, 26, 26]
    SUI.fit(int_rows, int_h - 2 * 10, "interest well")
    add(body, SUI.panel("SkyyBInt", "well", h=int_h, pad={"horizontal": 8, "vertical": 10}, anchor={"bottom": 18}), int_h + 18)
    ap.append(("SkyyBInt", SUI.label("SkyyBRate", "", "heading", h=int_rows[0], align="Center")))
    ap.append(("SkyyBInt", SUI.label("SkyyBNext", "", "default", h=int_rows[1], align="Center")))
    gain_col = SUI.J('readable ? "%%s" : "%%s"' %% (SUI.COLOR["success"], SUI.COLOR["error"]), SUI.COLOR["success"])
    ap.append(("SkyyBInt", SUI.label("SkyyBGain", "", "success", h=int_rows[2], align="Center", col=gain_col)))
    # controls, 0.1.3's order: Deposit all | Amount | Deposit | Withdraw | Withdraw all (green -> Primary, blue -> Secondary)
    ctl_h, far, near, pair = SUI.BTN_H, 30, 12, 6
    all_w, field_w, btn_w = 200, 244, SUI.BTN_MIN_W
    SUI.fit([all_w, far, field_w, near, btn_w, pair, btn_w, far, all_w], W, "controls row")
    assert W - (2 * all_w + 2 * far + field_w + near + 2 * btn_w + pair) == 0, "the controls row must fill the body width exactly"
    add(body, SUI.group("SkyyBCtl", "Left", h=ctl_h), ctl_h)
    ap.append(("SkyyBCtl", SUI.button("SkyyBDepAll", "Deposit all", "primary", w=all_w, anchor={"right": far})))
    ap.append(("SkyyBCtl", SUI.text_field("SkyyBAmtBox", "SkyyBAmount", w=field_w, placeholder="Amount", max_length=16,
                                          anchor={"top": (ctl_h - SUI.FIELD_H) // 2, "right": near})))
    ap.append(("SkyyBCtl", SUI.button("SkyyBDep", "Deposit", "primary", w=btn_w, anchor={"right": pair})))
    ap.append(("SkyyBCtl", SUI.button("SkyyBWd", "Withdraw", "secondary", w=btn_w, anchor={"right": far})))
    ap.append(("SkyyBCtl", SUI.button("SkyyBWdAll", "Withdraw all", "secondary", w=all_w)))
    # captions under the controls (the middle one is b.set: it has commas and dots)
    cap_h, mid_w = 25, field_w + near + btn_w + pair + btn_w
    add(body, SUI.group("SkyyBCap", "Left", h=cap_h, anchor={"top": 4}), cap_h + 4)
    ap.append(("SkyyBCap", SUI.label(None, "your whole purse", "caption", w=all_w, h=cap_h, align="Center", anchor={"right": far})))
    ap.append(("SkyyBCap", SUI.label("SkyyBCapMid", "", "caption", w=mid_w, h=cap_h, align="Center", anchor={"right": far})))
    ap.append(("SkyyBCap", SUI.label(None, "your whole bank", "caption", w=all_w, h=cap_h, align="Center")))
    # the result line (+ / - / = colours from the kit) and the chat hint
    add(body, SUI.status_line("SkyyBInfo", "colorOf(this.info)", h=44, wrap=True, anchor={"top": 13}), 44 + 13)
    add(body, SUI.label("SkyyBChat", "", "caption", h=25, align="Center"), 25)
    # footer: content separator, Refresh left, Close right (WorldEventPanelPage footer; Close = Secondary + the cancel sound)
    add(body, SUI.separator("content", anchor={"top": SUI.SEP_MARGIN, "bottom": SUI.SEP_MARGIN}), 1 + 2 * SUI.SEP_MARGIN)
    add(body, SUI.group("SkyyBBottom", "Left", h=SUI.BTN_H), SUI.BTN_H)
    ap.append(("SkyyBBottom", SUI.button("SkyyBRefresh", "Refresh", "secondary", w=SUI.BTN_MIN_W)))
    ap.append(("SkyyBBottom", SUI.button("SkyyBClose", "Close", "secondary", w=SUI.BTN_MIN_W, sound="cancel",
                                         anchor={"left": W - 2 * SUI.BTN_MIN_W})))
    left = sh.fit(heights, "bank page body")
    assert left == 0, "the bank page body must be filled exactly (no FlexWeight filler): %%d px left" %% left
    ap.check(BANK_PREFIX)                                            # ids, prefix, no duplicates, parents exist, markup rules
    have = set(i for _p, mk in ap for i in re.findall(r"#([A-Za-z0-9]+)\\s*\\{", SUI.render(mk)))
    missing = [i for i in BANK_IDS_013 if i not in have]
    assert not missing, "0.1.4 dropped 0.1.3 element ids: %%s" %% missing
    sets = [(ident, "Text", SUI.J(expr) if not expr.startswith('"') else SUI.java_unlit(expr)) for ident, expr in BANK_SETS_013]
    return sh, sets


BANK_SH, BANK_SET_LINES = bank_page()
BANK_JAVA = "\\n".join("  " + ln for ln in BANK_SH.java("b", sets=BANK_SET_LINES).split("\\n"))
PM(r"""
public void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {
%(prelude)s
""" + BANK_JAVA + r"""
%(keepset)s
%(bindings)s
}""")
''' % {"ids": IDS013, "sets": SETS013, "prelude": PRELUDE, "keepset": KEEPSET[0], "bindings": BINDINGS}
rep("@@NEWBUILD@@", NEWBUILD)

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
for k in KEEP:
    assert k in s, "a block that must stay 0.1.3's changed: %s" % k[:80]
for c in ("#0b1524", "#ffd070", "#ffe08a", "#142236", "#2a2410", "#101c2c", "#1f5a34", "#2c7a48", "#133a22", "#1d3a5f", "#2f5a8f",
          "#0f2038", "#2a3444", "#3a475c", "#1a2230", "#16263a", "#cfe3ff", "#9fb8d0", "#8fa4b8", "#7fe07f", "#ff8080", "#8fc8ff",
          "#e6ffe8", "#e6f2ff", "TextButtonStyle(Default: (Background: #", "public static String style("):
    assert c not in s, "0.1.3 custom look left in 0.1.4: " + c
assert "import skyyui as SUI" in s and s.index("SUI.verify()") < s.index("J = B.start()"), "verify() must run before the build"
for ident in IDS013:
    assert ('"%s"' % ident) in s or ("#" + ident) in s, "id " + ident
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.3 had %d)" % (s.count(LF), OLD.count(LF)))
