"""Derive SkyyClasses/build_skyyclasses_0.1.9.py from the LIVE 0.1.8 (build_skyyclasses_0.1.8.py = the tools/deploy_set.py SET pin).
Run:  python tools/classes_0_1_9_patch.py   then   python SkyyClasses/build_skyyclasses_0.1.9.py   (never --deploy: coordinated deploy)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> classes_0_1_8_patch.py ->
the generated 0.1.8 read here; tools/classes_0_1_6_patch.py is NEVER re-run. Edit THIS file, never the generated build script.

0.1.9 = Classes page polish (Skyy 2026-09-30, seen in game on the deployed 0.1.8):
  - taller cards: on the Archer / Berserker / Priest cards the two-line description ran to the card's bottom edge. The SKYY CARD
    block (the ONE shared card component, identical in SkyyProfiles 0.1.4 - tools/profiles_0_1_4_patch.py; both patches assert the
    same hash, CARD_SHA) now has CARD_H 92 (was 84): the three text lines (24 + 20 + 40) are centred, 4 px free above and below.
  - the vanilla footer Close (Secondary + the vanilla cancel sound, like SkyyBank 0.1.4 / SkyyCollections 0.2.4 / SkyyIslands 0.5.4):
    a new element #SkyyClsClose, a new binding (Activating -> EventData a=clsclose, the LAST binding of every state) and a new branch
    at the TOP of handleDataEvent (before the profile-lock / needs-profile gates, so every player can close): CustomUIPage.close()
    (= PageManager.setPage(None), the SkyyBank 0.1.4 Close; probed in the build).
  - the page keeps its size (1100 x 854): the room comes from the bottom of the page. The sub line is one line (the longest text
    measures 882 of 1066 px with the client's own Nunito Sans advances) and the result line (#SkyyClsInfo) shares ONE footer slot
    with the footer text (#SkyyClsFoot): a row #SkyyClsBottom = [the confirm row | the result line | the footer text] + Close. The
    result line replaces the footer text while it shows (it is empty whenever the confirm row shows: every pick clears it). Budget:
    sub 26 + 8, the card list 8 + 7 x 96 = 680, the footer row 8 + 60 = 782 px = the body.
  Everything else (commands, permissions, config, files, bridge keys, class rules, kits, heals, arrows, the first-join OpenTask gates,
  ClassPage's fields / constructor / safe(), the 0.1.8 build() statements, every other class) is byte-identical to 0.1.8 - asserted
  below (KEEP blocks + the template line multiset). Harness: SkyyClasses/test_skyyclasses_0.1.9.py (part Y: 0.1.8 vs 0.1.9).
Bridge note (SkyyProfiles 0.1.4 reads it for its automatic profile limit): class:list - "Name:Skill,..." of the ENABLED (pickable)
classes, put once in setup() - already exists since 0.1; no new key was needed.
"""
import collections
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.8.py")
dst = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.9.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
# the source must be the generated 0.1.8 of the EDITED lineage
assert 'VERSION = "0.1.8"' in s and "GENERATED by tools/classes_0_1_8_patch.py from the LIVE 0.1.7" in s, \
    "build_skyyclasses_0.1.8.py is not the live 0.1.8"
assert "DEF_HEAL_MSG_MS = 10000   # LOCKED Skyy 2026-09-25" in s, "0.1.8 is not the edited-lineage script"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
assert len(BIND0) == 3, "0.1.8 has 3 event bindings (all in ClassPage), found %d" % len(BIND0)


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def cut(a, b, new=""):
    """replace everything from anchor a (included) up to anchor b (kept) with new; returns the text that was cut"""
    global s
    assert s.count(a) == 1, "cut start count %d: %s" % (s.count(a), a[:120])
    assert s.count(b) == 1, "cut end count %d: %s" % (s.count(b), b[:120])
    i, j = s.index(a), s.index(b)
    assert i < j, "cut anchors out of order: %s / %s" % (a[:60], b[:60])
    old = s[i:j]
    s = s[:i] + new + s[j:]
    return old


def block(a, b):
    """the text from anchor a (included) to anchor b (excluded) of the CURRENT source (for unchanged-block asserts)"""
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


CARD_START = "# =====================================================================================================================\n# SKYY CARD"
CARD_END = "# ======================================================================= (end of the shared SKYY CARD block)"
PAGE_START = "# 0.1.8 (the vanilla UI pass): ClassPage's look = the vanilla UI kit + the shared SKYY CARD above."
# blocks that must come out of this patch byte-identical (everything but the docstring head, the Run line, VERSION, the probe list,
# the SKYY CARD block, ClassPage's look and the top of handleDataEvent)
KEEP = [block("\nHERE = os.path.dirname(os.path.abspath(__file__))", "\nAC = \"com.hypixel.hytale.server.core.command.system.AbstractCommand\""),
        block("# 0.1.6: every new engine call (spec 2.9)", CARD_START),
        block('F(page, "public int pending;")', 'M(page, r"""\npublic void handleDataEvent('),
        block("      rebuild(); return;\n    }\n    if (@PKG@.ClassCfg.needsProfile(u)) {", "if \"--deploy\" in sys.argv:")]

# ================================================================================================ docstring, Run line, version
rep('''"""SkyyClasses 0.1.8 - build script (javassist via jpype). GENERATED by tools/classes_0_1_8_patch.py from the LIVE 0.1.7 (the EDITED
lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7) - edit the patch, not this file; classes_0_1_6_patch.py is never re-run.
Wynncraft-style classes for SkyWynn.
''', '''"""SkyyClasses 0.1.9 - build script (javassist via jpype). GENERATED by tools/classes_0_1_9_patch.py from the LIVE 0.1.8 (the EDITED
lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> classes_0_1_8_patch.py -> 0.1.8) - edit the patch, not this file;
classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
0.1.9 (2026-09-30, Classes page polish - Skyy saw the deployed 0.1.8 in game): ONLY THE /class PAGE CHANGED.
  - Taller cards: the shared SKYY CARD (the same block as SkyyProfiles 0.1.4) is 92 px high (was 84): the three text lines
    (24 + 20 + 40) are centred with 4 px free above and below - the two-line descriptions of Archer / Berserker / Priest ran to the
    card's bottom edge (the lines really take 24.6 + 21.8 + 40.9 = 87.3 px at the client's Nunito Sans line height).
  - The vanilla footer Close: #SkyyClsClose (Secondary + the vanilla cancel sound) at the right end of the footer row; Activating ->
    EventData a=clsclose (the last binding of every state); handleDataEvent checks it FIRST (before the profile-lock / needs-profile
    gates, so every player can close) and calls CustomUIPage.close() (the SkyyBank 0.1.4 Close). Esc still closes too.
  - The window keeps 0.1.8's size, 1100 x 854: the sub line is one line now (the longest measures 882 of 1066 px), and the footer
    row #SkyyClsBottom holds ONE slot left of Close: the in-page confirm row (kit confirm_view compact, the question wraps to two
    lines), else the result line #SkyyClsInfo (vanilla info blue, bold) while there is one, else the footer text #SkyyClsFoot.
    The result line replaces the footer text while it shows (it is always empty while the confirm row shows).
  Commands, permissions, config, files, bridge keys, class rules, kits, heals, arrows and every text are 0.1.8's (the patch asserts
  it). The class list SkyyProfiles 0.1.4 counts for its automatic profile limit is the existing bridge key class:list (ENABLED
  classes, put once in setup()).
''')
rep("Run:   python build_skyyclasses_0.1.8.py            -> SkyyClasses/SkyyClasses-0.1.8.jar",
    "Run:   python build_skyyclasses_0.1.9.py            -> SkyyClasses/SkyyClasses-0.1.9.jar")
rep('VERSION = "0.1.8"', 'VERSION = "0.1.9"')

# ================================================================================================ probe: CustomUIPage.close()
rep('''(T["PLA"], "getPageManager"), (T["PLA"], "getPlayerConnection"), (T["PAGE"], "rebuild"), (T["HSV"], "SCHEDULED_EXECUTOR"),''',
    '''(T["PLA"], "getPageManager"), (T["PLA"], "getPlayerConnection"), (T["PAGE"], "rebuild"), (T["HSV"], "SCHEDULED_EXECUTOR"),
             (T["PAGE"], "close"),     # 0.1.9: the footer Close (CustomUIPage.close() = PageManager.setPage(None), SkyyBank 0.1.4)''')

# ================================================================================================ the shared SKYY CARD block
CARD_SHA_OLD = "85a047857ef2762641fb7045aee6f5ce9acd4e1ded05f55ba4a2a7496445f7d5"      # SkyyClasses 0.1.8 / SkyyProfiles 0.1.3
OLD_CARD = cut(CARD_START, CARD_END, "@@CARD@@")
OLD_CARD += CARD_END
assert s.count("@@CARD@@" + CARD_END) == 1
s = s.replace("@@CARD@@" + CARD_END, "@@CARD@@", 1)
assert hashlib.sha256(OLD_CARD.encode("utf8")).hexdigest() == CARD_SHA_OLD, "the 0.1.8 SKYY CARD block is not the one 0.1.8 shipped"
CARD_BLOCK = r'''# =====================================================================================================================
# SKYY CARD - the ONE shared card component (research/Skyy-UI-Inventory.md 5.5, 5.17 and section 6 "Class cards"): the class
# cards of SkyyClasses' ClassPage and of SkyyProfiles' Create Profile page, SkyyProfiles' profile cards and its empty-slot card.
# Built from kit calls only (tools/skyyui.py). THE SAME BLOCK is in SkyyClasses 0.1.9 and SkyyProfiles 0.1.4: both patches
# (tools/classes_0_1_9_patch.py, tools/profiles_0_1_4_patch.py) insert it and assert its hash - change it in both together
# (0.1.8 / 0.1.3 carried the same block with CARD_H 84).
# A card is one row of a list well (the vanilla #000000(0.15) list inset, padding 4): Group <card> (LayoutMode Left) = a 4 px status
# bar <card>Bar + the card body <card>In (the state background; side by side, so a look without a bar is one plain colour) holding
# the item cells (the vanilla BarterTradeRow slot border with an ItemIcon) | the text column (up to three label lines, their Text
# is b.set) | the action column (a vanilla button or a state word, appended by the page). Only
# properties the deployed pages already use: LayoutMode Left / Top, fixed widths / heights, Anchor margins, Padding, colour
# backgrounds, ItemIcon with an inline ItemId, Wrap (no FlexWeight, no WrapMaxLines, no LayoutMode Center / Full).
# =====================================================================================================================
CARD_H = 92                 # card height: the text lines (name 24 + line two 20 + line three 40 = 84; card_java centres them, so
                            # 4 px stay free above and below) - 0.1.9 / 0.1.4 (Skyy 2026-09-30, seen in game): at 84 the two-line
                            # descriptions (Archer, Berserker, Priest) ran to the card's bottom edge: the three lines really take
                            # 24.6 + 21.8 + 40.9 = 87.3 px at the client's Nunito Sans line height (1.364 em)
CARD_GAP = 4                # space under each card (the OverrideRespawnPointButton option rows: 50 + 4)
CARD_BAR = 4                # status bar at the left edge (WorldEventListRow #StatusBar: 4 px)
CARD_FRAME = 64             # item cell border (BarterTradeRow slot border #1a2530, padding 2) around a 60 px ItemIcon
CARD_CELL = CARD_FRAME + 8  # one icon cell: an 8 px gap + the frame
CARD_ACT_W = 200            # action column: a vanilla normal button (172 = @DefaultButtonMinWidth) centred in it
CARD_BTN_W = SUI.BTN_MIN_W
CARD_PAD_R = 12             # space right of the action column
CARD_LIST_PAD = SUI.WELL_LIST_PAD   # the list well's padding (WorldEventPanelPage #ListContainer: 4)
# card looks: (background, status bar), kit colour names
CARD_LOOKS = {
    "selected": ("rowPressed", "selected"),    # your class / the picked class / the active profile: the WorldEventListRow pressed
                                               # step #182a40(0.9) + its selected blue #4274a5 as the bar (review fix: the active
                                               # tint #7a9cc6(0.25) put the Berserker red at 2.6:1 and the disabled grey at 2.7:1;
                                               # on the pressed step every card text is >= 3.4:1; vanilla's solid #4274a5 row
                                               # would drop the class colours to 1.1-2:1)
    "pending": ("rowHover", "warning"),        # waiting for Confirm: the hovered row #132033(0.8) + the confirm question yellow bar
    "normal": ("row", "row"),                  # the WorldEventListRow panel #101925(0.55); the bar in the card colour = no bar
    "off": ("cardDisabled", "cardDisabled"),   # coming later: BarterTradeRow's disabled card #1a1e24 (+ grey text, covered icons)
    "empty": ("well", "well"),                 # an empty slot: one more step of the list well tone
}


def card_list_h(rows):
    """The height of a list well holding `rows` cards (padding 4 + rows x (card + gap))."""
    return 2 * CARD_LIST_PAD + rows * (CARD_H + CARD_GAP)


def card_list(ident, h, anchor=None):
    """The list well the cards go into (a vanilla panel "well", LayoutMode Top, padding 4)."""
    return SUI.panel(ident, "well", h=h, pad=CARD_LIST_PAD, anchor=anchor)


def card_text_w(w, icon_max):
    """The text column width of a w px card with icon_max item cells."""
    tw = w - CARD_BAR - icon_max * CARD_CELL - CARD_ACT_W - CARD_PAD_R
    SUI.fit([CARD_BAR, icon_max * CARD_CELL, tw, CARD_ACT_W, CARD_PAD_R], w, "card width")
    assert tw >= 240, "card text column too narrow: %d px" % tw
    return tw


def _card_in(outer, *kids):
    """kit markup `outer` with the kit markups `kids` placed inside it (before its closing brace)."""
    assert outer.endswith("}") and kids, outer[:60]
    return outer[:-1] + " ".join(kids) + " }"


def _card_col(col, on):
    """A line colour: a kit colour name or a J(java expr, sample) data colour; with on (a Java boolean expression) the vanilla
    disabled grey when it is false."""
    c = SUI.color(col)
    if on is None:
        return c
    sample = SUI.render(c) if SUI.has_j(c) else c
    return SUI.J("(%s) ? (%s) : %s" % (on, SUI.java_value(c), SUI.java_lit(SUI.COLOR["disabled"])), sample)


def _card_look(look, var):
    """(java declarations, background, bar) for a static look name or [(look, java boolean), ..., last look]."""
    if isinstance(look, str):
        bg, bar = CARD_LOOKS[look]
        return [], SUI.color(bg), SUI.color(bar)
    conds, last = list(look[:-1]), look[-1]
    assert conds and isinstance(last, str), look
    e_bg, e_bar = SUI.java_lit(SUI.color(CARD_LOOKS[last][0])), SUI.java_lit(SUI.color(CARD_LOOKS[last][1]))
    for name, cond in reversed(conds):
        e_bg = "(%s) ? %s : (%s)" % (cond, SUI.java_lit(SUI.color(CARD_LOOKS[name][0])), e_bg)
        e_bar = "(%s) ? %s : (%s)" % (cond, SUI.java_lit(SUI.color(CARD_LOOKS[name][1])), e_bar)
    first = CARD_LOOKS[conds[0][0]]
    decl = ["String %sBg = %s;" % (var, e_bg), "String %sBar = %s;" % (var, e_bar)]
    return decl, SUI.J(var + "Bg", SUI.color(first[0])), SUI.J(var + "Bar", SUI.color(first[1]))


def _card_cell(fid, item, on):
    """One item cell: an 8 px gap + the slot border (padding 2) with the ItemIcon; the coming-later look lays the vanilla
    sold-out cover (BarterTradeRow #0a0e12(0.75)) over it. With on: both looks, picked in the Java (choose)."""
    cell = SUI.group(None, None, w=CARD_CELL, h=CARD_H)
    frame = SUI.item_frame(fid, CARD_FRAME, anchor={"left": CARD_CELL - CARD_FRAME, "top": (CARD_H - CARD_FRAME) // 2})
    icon = SUI.item_icon(None, item, CARD_FRAME - 4, anchor={"left": 0, "top": 0})
    live = _card_in(cell, _card_in(frame, icon))
    if on is None:
        return live
    cover = SUI.group(None, None, anchor={"full": 0}, extra="Background: %s" % SUI.COLOR["cardOverlay"])
    return SUI.choose(SUI.J(on), live, _card_in(cell, _card_in(frame, icon, cover)))


def card_java(ids, w, look, lines, icons=None, icon_item=None, icon_max=1, on=None, var="card", k="k", b="b"):
    """Java statements that append ONE card (they go inside the page's Java loop; ids / texts / colours may be J() values):
      ids       {"list": the list well, "card", "icons" (None = <card>Ics), "text", "act"} - the page's OLD element ids
      w         the card width (the list well's inner width)
      look      a CARD_LOOKS name, or [(look, java boolean), ..., last look name]: the first true condition wins
      lines     [{"id": suffix, "text": java String expression, "kind": label kind, "h": px, "col": kit colour name or
                J(java expr, sample), "wrap": bool, "tag": {"id", "text", "col", "w", "kind"}}] - the label is <card><suffix>; a tag
                is a second, right-aligned label on the same row (<card><tag id>, the row <card><suffix>Row)
      icons     a Java String[] expression (one cell per entry, at most icon_max; icon_item = J(item id of entry k)), or
                icons=None and icon_item = J(one item id): one cell
      on        a Java boolean: false = the coming-later look (grey text, covered icons); None = always on
    The page appends the action column content (card_button / card_state) into ids["act"] afterwards."""
    card, text, act = ids["card"], ids["text"], ids["act"]
    icons_id = ids.get("icons") or card + "Ics"
    tw = card_text_w(w, icon_max)
    decl, bg, bar = _card_look(look, var)
    out = list(decl)
    body = card + "In"
    out.append(SUI.java_append(ids["list"], SUI.group(card, "Left", h=CARD_H, anchor={"bottom": CARD_GAP}), b))
    out.append(SUI.java_append(card, SUI.group(card + "Bar", None, w=CARD_BAR, h=CARD_H, extra="Background: %s" % bar), b))
    out.append(SUI.java_append(card, SUI.group(body, "Left", w=w - CARD_BAR, h=CARD_H, extra="Background: %s" % bg), b))
    out.append(SUI.java_append(body, SUI.group(icons_id, "Left", w=icon_max * CARD_CELL, h=CARD_H), b))
    if icons is None:
        out.append(SUI.java_append(icons_id, _card_cell(card + "F0", icon_item, on), b))
    else:
        out.append("for (int %s = 0; %s < %s.length && %s < %d; %s++) {" % (k, k, icons, k, icon_max, k))
        out.append("  " + SUI.java_append(icons_id, _card_cell(card + "F" + SUI.J(k), icon_item, on), b))
        out.append("}")
    top = SUI.fit([ln["h"] for ln in lines], CARD_H, "card text lines") // 2
    out.append(SUI.java_append(body, SUI.group(text, "Top", w=tw, h=CARD_H, pad={"top": top} if top else None), b))
    sets = []
    for ln in lines:
        lid, col = card + ln["id"], _card_col(ln["col"], on)
        tag = ln.get("tag")
        if tag is None:
            out.append(SUI.java_append(text, SUI.label(lid, "", ln["kind"], h=ln["h"], col=col, wrap=ln.get("wrap", False)), b))
        else:
            row, tid = card + ln["id"] + "Row", card + tag["id"]
            out.append(SUI.java_append(text, SUI.group(row, "Left", h=ln["h"]), b))
            out.append(SUI.java_append(row, SUI.label(lid, "", ln["kind"], w=tw - tag["w"], h=ln["h"], col=col, wrap=False), b))
            out.append(SUI.java_append(row, SUI.label(tid, "", tag.get("kind", "default"), w=tag["w"], h=ln["h"],
                                                      col=_card_col(tag["col"], on), align="End", wrap=False), b))
        sets.append(SUI.java_set(lid, "Text", SUI.J(ln["text"]), b))
        if tag is not None:
            sets.append(SUI.java_set(tid, "Text", SUI.J(tag["text"]), b))
    out.extend(sets)
    out.append(SUI.java_append(body, SUI.group(act, "Top", w=CARD_ACT_W, h=CARD_H, pad={"top": (CARD_H - SUI.BTN_H) // 2,
                                                                                            "left": (CARD_ACT_W - CARD_BTN_W) // 2}), b))
    return "\n".join(out)


def card_button(ident, text, kind="secondary", sound=None):
    """The card's action button: a vanilla normal text button (172 x 44) - append it into the card's action column."""
    return SUI.button(ident, text, kind, w=CARD_BTN_W, sound=sound)


def card_state(text, kind):
    """A state word in the action column instead of a button: Selected / Active = the vanilla success green, Locked / Coming
    soon / Coming later = the vanilla disabled grey (both bold, centred where the button would be)."""
    return SUI.label(None, text, kind, w=CARD_BTN_W, h=SUI.BTN_H, align="Center", bold=True)


def java_block(src, indent):
    """Java statements re-indented by `indent` spaces (for pasting kit output into a method template)."""
    return "\n".join((" " * indent + ln) if ln.strip() else ln for ln in src.split("\n"))


def java_fill(tpl, parts):
    """A Java method template with {{NAME}} placeholders filled with the kit-built Java in parts (each placeholder used at least
    once, none left over)."""
    out = tpl
    for name, java in parts.items():
        tok = "{{" + name + "}}"
        assert tok in out, "unused Java part " + name
        out = out.replace(tok, java)
    left = re.findall(r"\{\{[A-Z0-9]+\}\}", out)
    assert not left, "unfilled Java placeholder: %s" % left
    return out
# ======================================================================= (end of the shared SKYY CARD block)'''
CARD_SHA = "bf659e0208b537a81ac8758d909f81976f03069816ea9dddb300f843a7eaa028"     # the SAME value in tools/profiles_0_1_4_patch.py: the card block is one component in both mods
assert hashlib.sha256(CARD_BLOCK.encode("utf8")).hexdigest() == CARD_SHA, "the SKYY CARD block differs from SkyyProfiles 0.1.4's"
# the only changes against 0.1.8's block: the header naming the two versions, CARD_H 84 -> 92 and its comment
_d = [ln for ln in CARD_BLOCK.split(LF) if ln not in OLD_CARD.split(LF)]
assert len(_d) == 7 and "CARD_H = 92 " in "".join(_d) and len(CARD_BLOCK.split(LF)) == len(OLD_CARD.split(LF)) + 3, _d
rep("@@CARD@@", CARD_BLOCK)

# ================================================================================================ ClassPage: taller cards + footer Close
OLD_PAGE = cut(PAGE_START, 'F(page, "public int pending;")', "@@PAGE@@")
assert "CLS_BUILD = r\"\"\"" in OLD_PAGE and "def class_page_java():" in OLD_PAGE
PAGE_BLOCK = r'''# 0.1.9 (Skyy 2026-09-30, seen in game): ClassPage = 0.1.8's vanilla look with the taller shared SKYY CARD above (CARD_H 92) and
# the vanilla footer Close (Secondary + the cancel sound). The window keeps 0.1.8's size (1100 x 854; the body is 0.1.7's root
# #SkyyCls): the sub line is ONE line now and the footer row #SkyyClsBottom holds one slot left of Close - the in-page confirm row
# (kit confirm_view, compact, the question wraps), else the result line (info, while there is one), else the footer text.
# class_page_java() builds the markup with kit calls at BUILD time and returns build()'s Java: 0.1.8's statements (state, texts, the
# action chain, the 3 event bindings) are kept word for word (the patch asserts it) + the result-line branch and the Close binding.
CLS_W, CLS_H = 1100, 854           # 0.1.8's window, kept (Skyy: "keep the page size")
CLS_PREFIX = "SkyyCls"
CLS_SUB_H, CLS_SUB_GAP = 26, 8     # the sub line: one 16 px line (the longest text measures 882 of 1066 px) + 8 below
CLS_END_TOP, CLS_END_H = 8, SUI.BTN_H + 16      # the footer row: 8 above, 60 high (= the compact confirm row: a 44 px button + 2 x 8)
CLS_CLOSE_GAP = 12                 # between the footer slot and Close
CLS_IDS_018 = ["SkyyCls", "SkyyClsSub", "SkyyClsCard0", "SkyyClsIco0", "SkyyClsTxt0", "SkyyClsAct0", "SkyyClsPick0", "SkyyClsInfo",
               "SkyyClsConfirm", "SkyyClsYes", "SkyyClsNo", "SkyyClsFoot"]      # every element id of the 0.1.8 page (kept)
CLS_IDS_NEW = ["SkyyClsBottom", "SkyyClsClose"]                                   # 0.1.9: the footer row + the Close button
CLS_BUILD = r"""
public void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {
  java.util.UUID u = this.playerRef.getUuid();
  int pi = @PKG@.ClassStore.profileIndex(u);
  boolean lockp = pi >= 0;
  boolean np = !lockp && @PKG@.ClassCfg.needsProfile(u);
  int cur = lockp ? pi : @PKG@.ClassStore.classIndex(u);
{{SHELL}}
  String sub = cur < 0 ? "You have no class yet - your first choice is free. Your class decides your weapons and your combat skill."
    : "You are " + @PKG@.ClassDefs.article(@PKG@.ClassDefs.NAMES[cur]) + " - combat skill " + @PKG@.ClassDefs.SKILLS[cur] + ". Only " + @PKG@.ClassDefs.NAMES[cur] + " weapons deal damage for you.";
  if (lockp) sub = "Your class is locked to this profile - you are " + @PKG@.ClassDefs.article(@PKG@.ClassDefs.NAMES[cur]) + " with combat skill " + @PKG@.ClassDefs.SKILLS[cur] + ". A new class means a new profile.";
  if (lockp && !@PKG@.ClassDefs.ENABLED[cur]) sub = "This profile is locked to " + @PKG@.ClassDefs.NAMES[cur] + " - not playable yet. Its weapons deal no damage until it is released.";
  if (np) sub = "You have no profile yet. Type /profiles to create one - you pick your class there and it is locked to that profile.";
{{SUB}}
{{LIST}}
  for (int i = 0; i < @PKG@.ClassDefs.NAMES.length; i++) {
    boolean on = @PKG@.ClassDefs.ENABLED[i];
    boolean sel = i == cur;
    boolean pend = i == this.pending;
    String[] ic = @PKG@.ClassDefs.ICONS[i].split(",");
    String title = @PKG@.ClassDefs.NAMES[i] + (sel ? " - your class" : (on ? " - " + @PKG@.ClassDefs.ROLES[i] : " - coming soon"));
{{CARD}}
    if (lockp && sel) {
{{SELECTED}}
    } else if (!on) {
{{SOON}}
    } else if (sel) {
{{SELECTED}}
    } else if (lockp || np) {
{{LOCKED}}
    } else {
{{PICK}}
      ev.addEventBinding(@BT@.Activating, "#SkyyClsPick" + i, @EVD@.of("a", "clspick" + i));
    }
  }
{{BOTTOM}}
  boolean said = this.info != null && this.info.length() > 0;
  long cost = @PKG@.ClassCfg.SWITCH_COST;
  if (!lockp && !np && this.pending >= 0 && this.pending < @PKG@.ClassDefs.NAMES.length) {
    String pn = @PKG@.ClassDefs.NAMES[this.pending];
    String q = cur < 0 ? "Become " + @PKG@.ClassDefs.article(pn) + "? Your first choice is free."
      : "Switch to " + pn + " for " + cost + " coins? Your " + @PKG@.ClassDefs.NAMES[cur] + " progress is kept.";
{{CONFIRM}}
    ev.addEventBinding(@BT@.Activating, "#SkyyClsYes", @EVD@.of("a", "clsyes"));
    ev.addEventBinding(@BT@.Activating, "#SkyyClsNo", @EVD@.of("a", "clsno"));
  } else if (said) {
{{INFO}}
  } else if (np) {
    String nf = "Your class comes from your profile - type /profiles to create it. Shields and tools work for every class. Hatchets are tools.";
{{FOOTNF}}
  } else if (lockp) {
    String pt = @PKG@.ClassCfg.profileText(u);
    String lf = "Class locked to " + (pt.length() > 0 ? pt : "this profile") + ". To play another class create a new profile. Shields and tools work for every class. Hatchets are tools.";
{{FOOTLF}}
  } else {
    String foot = "Switching costs " + cost + " coins (first choice free) - cooldown " + @PKG@.ClassCfg.COOLDOWN_MIN + " min"
      + (@PKG@.ClassStore.coinsReady() ? " - purse " + @PKG@.ClassStore.purse(u) + " coins" : "") + ". Shields and tools work for every class. Hatchets are tools.";
{{FOOT}}
  }
{{CLOSE}}
  ev.addEventBinding(@BT@.Activating, "#SkyyClsClose", @EVD@.of("a", "clsclose"));
}"""


def class_page_java():
    """ClassPage.build(): CLS_BUILD with its {{parts}} built from kit calls. 0.1.8's window size; the heights fill the body exactly."""
    heights = [CLS_SUB_H + CLS_SUB_GAP, card_list_h(len(CLASSES)), CLS_END_TOP + CLS_END_H]
    sh = SUI.page_shell("SkyyClsF", CLS_W, CLS_H, "Classes", body_id="SkyyCls")
    assert sh.fit(heights) == 0, "the class page body must be filled exactly: %s in %d px" % (heights, sh.inner_h)
    body, W = sh.body, sh.inner_w
    slot_w = W - CLS_CLOSE_GAP - SUI.BTN_MIN_W                          # the footer slot left of Close
    assert SUI.fit([slot_w, CLS_CLOSE_GAP, SUI.BTN_MIN_W], W, "footer row") == 0
    i = SUI.J("i")
    act = "SkyyClsAct" + i
    ids = {"list": "SkyyClsList", "card": "SkyyClsCard" + i, "icons": "SkyyClsIco" + i, "text": "SkyyClsTxt" + i, "act": act}
    lines = [{"id": "Nm", "text": "safe(title)", "kind": "rowName", "h": 24, "col": SUI.J("@PKG@.ClassDefs.COLORS[i]", CLASSES[0]["color"])},
             {"id": "Sk", "text": 'safe("Combat skill " + @PKG@.ClassDefs.SKILLS[i] + " - " + @PKG@.ClassDefs.WTEXT[i])', "kind": "fieldLabel",
              "h": 20, "col": "value"},
             {"id": "Ds", "text": "safe(@PKG@.ClassDefs.DESCS[i])", "kind": "rowSub", "h": 40, "col": "rowSub", "wrap": True}]
    pick = "SkyyClsPick" + i
    bottom = "SkyyClsBottom"
    info = SUI.label("SkyyClsInfo", "", "info", w=slot_w, h=CLS_END_H, bold=True, wrap=True)
    foot = SUI.label("SkyyClsFoot", "", "caption", w=slot_w, h=CLS_END_H, wrap=True)
    confirm = SUI.confirm_view(bottom, "SkyyClsConfirm", slot_w, question=SUI.J("safe(q)"), compact=True, top=0, wrap=True,
                               ids={"box": "SkyyClsConfirm", "yes": "SkyyClsYes", "no": "SkyyClsNo"})
    assert confirm.h == CLS_END_H, "the compact confirm row must be the footer slot's height (%d / %d)" % (confirm.h, CLS_END_H)
    close = SUI.button("SkyyClsClose", "Close", "secondary", w=SUI.BTN_MIN_W, sound="cancel",
                       anchor={"left": CLS_CLOSE_GAP, "top": (CLS_END_H - SUI.BTN_H) // 2})
    parts = {
        "SHELL": sh.java("b"),
        "SUB": "\n".join([SUI.java_append(body, SUI.label("SkyyClsSub", "", "default", h=CLS_SUB_H, align="Center",
                                                           anchor={"bottom": CLS_SUB_GAP})),
                          SUI.java_set("SkyyClsSub", "Text", SUI.J("safe(sub)"))]),
        "LIST": SUI.java_append(body, card_list("SkyyClsList", card_list_h(len(CLASSES)))),
        "CARD": card_java(ids, W - 2 * CARD_LIST_PAD, [("selected", "sel"), ("pending", "pend"), ("normal", "on"), "off"], lines,
                          icons="ic", icon_item=SUI.J("safe(ic[k])", CLASSES[0]["icons"][0]), icon_max=max(len(c["icons"]) for c in CLASSES),
                          on="on"),
        "SELECTED": SUI.java_append(act, card_state("Selected", "success")),
        "SOON": SUI.java_append(act, card_state("Coming soon", "disabled")),
        "LOCKED": SUI.java_append(act, card_state("Locked", "disabled")),
        "PICK": "if (pend) %s\nelse %s" % (
            SUI.java_append(act, SUI.choose(SUI.J("cur < 0"), card_button(pick, "Choose", "primary"), card_button(pick, "Switch", "primary"))),
            SUI.java_append(act, SUI.choose(SUI.J("cur < 0"), card_button(pick, "Choose"), card_button(pick, "Switch")))),
        "BOTTOM": SUI.java_append(body, SUI.group(bottom, "Left", h=CLS_END_H, anchor={"top": CLS_END_TOP})),
        "CONFIRM": confirm.java("b"),
        "INFO": "\n".join([SUI.java_append(bottom, info), SUI.java_set("SkyyClsInfo", "Text", SUI.J("safe(this.info)"))]),
        "CLOSE": SUI.java_append(bottom, close),
    }
    for tok, var in (("FOOTNF", "nf"), ("FOOTLF", "lf"), ("FOOT", "foot")):
        parts[tok] = "\n".join([SUI.java_append(bottom, foot), SUI.java_set("SkyyClsFoot", "Text", SUI.J("safe(%s)" % var))])
    sh.appends.check(CLS_PREFIX)          # the window frame: ids, prefix, parents, markup rules (every runtime append: java_append)
    indent = {"SHELL": 2, "SUB": 2, "LIST": 2, "CARD": 4, "SELECTED": 6, "SOON": 6, "LOCKED": 6, "PICK": 6, "BOTTOM": 2, "CONFIRM": 4,
              "INFO": 4, "FOOTNF": 4, "FOOTLF": 4, "FOOT": 4, "CLOSE": 2}
    java = java_fill(CLS_BUILD, dict((k, java_block(v, indent[k])) for k, v in parts.items()))
    for ident in CLS_IDS_018 + CLS_IDS_NEW:   # every 0.1.8 element id is still created (runtime ids: "#<id>" + (i)), + the 2 new ones
        assert ("#%s {" % ident) in java or ('#%s" + (i)' % ident[:-1]) in java, "0.1.9 lost the element id #" + ident
    return java, sh


CLS_BUILD_JAVA, CLS_SHELL = class_page_java()
print("class page %dx%d (body %dx%d): %d class cards %d px high, footer Close, kit %s" % (
    CLS_SHELL.w, CLS_SHELL.h, CLS_SHELL.inner_w, CLS_SHELL.inner_h, len(CLASSES), CARD_H, SUI.kit_id()))'''
rep("@@PAGE@@", PAGE_BLOCK + "\n")

# 0.1.8's build() template lines must all be in the 0.1.9 template, word for word (multiset of whole lines), and the 0.1.9 template
# adds only the result-line branch, the footer-row / Close placeholders and the Close binding
_t8 = OLD_PAGE[OLD_PAGE.index('CLS_BUILD = r"""'):OLD_PAGE.index('"""\n\n\ndef class_page_java')].split(LF)
_t9 = PAGE_BLOCK[PAGE_BLOCK.index('CLS_BUILD = r"""'):PAGE_BLOCK.index('"""\n\n\ndef class_page_java')].split(LF)
_missing = collections.Counter(_t8) - collections.Counter(_t9)
assert not _missing, "0.1.8 build() lines missing from the 0.1.9 template: %s" % list(_missing)
_added = collections.Counter(_t9) - collections.Counter(_t8)
assert sorted(_added.elements()) == sorted([
    "{{BOTTOM}}", "  boolean said = this.info != null && this.info.length() > 0;", "  } else if (said) {", "{{CLOSE}}",
    '  ev.addEventBinding(@BT@.Activating, "#SkyyClsClose", @EVD@.of("a", "clsclose"));']), "unexpected template lines: %s" % _added
assert "{{INFO}}" in _t8 and "{{INFO}}" in _t9

# ================================================================================================ handleDataEvent: the Close, first
rep('''public void handleDataEvent(@REF@ ref, @ST@ st, String data) {
  try {
    if (data == null) return;
    java.util.UUID u = this.playerRef.getUuid();
    if (@PKG@.ClassStore.locked(u)) {''', '''public void handleDataEvent(@REF@ ref, @ST@ st, String data) {
  try {
    if (data == null) return;
    if (data.indexOf("clsclose\\"") >= 0) { close(); return; }   // 0.1.9: the footer Close - before the profile gates (everyone may close)
    java.util.UUID u = this.playerRef.getUuid();
    if (@PKG@.ClassStore.locked(u)) {''')

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
_b = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
assert _b == BIND0 + ['  ev.addEventBinding(@BT@.Activating, "#SkyyClsClose", @EVD@.of("a", "clsclose"));'], "event bindings: %s" % _b
for k in KEEP:
    assert k in s, "a block that must stay 0.1.8's changed: %s" % k[:80]
assert s.count("clsclose") == 3 and 'data.indexOf("clsclose\\"")' in s     # the binding, the handler (+ its comment-free payload)
_page = s[s.index("# ================= ClassPage: /class ================="):s.index('M(page, r"""\npublic void handleDataEvent(')]
for c in ("#0b1524", "#d08a4a", "#ffe9c9", "#9fb8cc", "#173524", "#3a2f1a", "#142030", "#0d1219", "#5f6b78", "#9fd8a2", "#c9d6e2",
          "#8fa4b8", "#ffd27a", "#5a4420", "#8a6a30", "#3a2a10", "#2f6a3a", "#3f8a4a", "#1f4a2a", "#e9ffe9", "TextButtonStyle(Default: (Background: #"):
    assert c not in _page, "an old custom look is back in the 0.1.9 page: " + c
assert "import skyyui as SUI" in s and s.index("SUI.verify()") < s.index("J = B.start()"), "verify() must run before the build"
assert s.index("def card_java(") < s.index("CLS_BUILD_JAVA, CLS_SHELL = class_page_java()") < s.index("M(page, CLS_BUILD_JAVA)")
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.8 had %d)" % (s.count(LF), OLD.count(LF)))
