"""Derive SkyyClasses/build_skyyclasses_0.1.12.py from the CURRENT generated 0.1.11 (build_skyyclasses_0.1.11.py).
Run:  python tools/classes_0_1_12_patch.py   then   python SkyyClasses/build_skyyclasses_0.1.12.py   (never --deploy: coordinated deploy)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_11_patch.py
-> the generated 0.1.11 read here; tools/classes_0_1_6_patch.py is NEVER re-run. Edit THIS file, never the generated build script.

0.1.12 = the CLASS SIDE of the magic traversals (research/Magic-Traversal-Spec.md 3.2; section 8 = Skyy's answers 2026-10-05, LOCKED,
docs/answered/classes.md "New answers"). SkyyArmory 0.1.1 (staff blink, wand hop + burst + heal orb) is built in parallel from the same spec
and calls the two new bridge functions; deploy order Classes -> Armory -> Gear (spec 3.4).
  - NEW bridge class:fn:heal -> Function(Object[]{UUID healer, UUID target, Double hp, String why [, String wandItemId]}) -> Double healed.
    The SkyyArmory heal orb calls it once per ally per orb tick ON THE TARGET'S WORLD THREAD (TravTick). Rules, in order:
      refuse (0.0) when priestHeal.enabled is off, the healer is not a Priest (ClassStore.classIndex, offline healers are read from disk
      like class:fn:get), a bad argument, the target is not an online player (a mob / unknown UUID = 0.0), the call is not on the target's
      world thread (World.isInThread - logged, never touches a component), or the target is not ready / dead / in creative;
      SPLIT (spec 8, Skyy: "healing orb heals everyone, but party more"): the healer themself and the healer's party members
      (party:fn:members) get hp; every other player gets hp x priestHeal.othersPercent % (NEW live row, default 50). Without SkyyParty
      everyone except the healer counts as "others". WHO is non-hostile (PvP, trav.players) is SkyyArmory's decision - it only passes
      players it would not hurt;
      CAP: the per-hit cap = the healer's WAND charged cap (0.1.11 capOf: max(maxPerHit, hpPerMana x the wand's charged Mana from
      armory:fn:info)); the wand = the optional 5th element, else the healer's main hand when the healer is in the same world, else none
      (= maxPerHit); then the overheal clamp (room), then HealBudget.take with that cap as the window top (the per-second budget is SHARED
      with the 0.1.11 heal share - spec 1.2 "Classes caps apply"), then EntityStatMap.addStatValue(Health);
      FEEDBACK: the 0.1.6 chat aggregator (HealMsg.given / taken, the priestHeal.feedbackMs throttle, the players' Settings switches);
      XP: skill:fn:healxp exactly like 0.1.7 (others = the 4-element call, self = the 5-element call with Boolean.TRUE), only while the
      healer is online in the target's world, alive and not in creative (spec 1.3: a logged-out / other-world / dead caster's orb still
      heals, without XP).
  - NEW bridge class:fn:ally -> Function(Object[]{UUID a, UUID b}) -> Boolean: TRUE when a == b or b is in a's party (party:fn:members);
    FALSE otherwise, for bad arguments, and without SkyyParty. Spec 8: every traversal lock-on targets party members only; SkyyArmory's
    friendly-fire filter uses it too. Any thread (it only reads the SkyyParty bridge). Guilds can join later.
  - Card texts (spec 3.2.2; UI text rule): Mage "... Hold to blink the way you look and leave a trail of light.", Priest "... Hold to hop
    back and burst - the glow heals your party most." (spec 8: the glow heals everyone non-hostile, the party more).
  - NOT here (spec 3.2 lists none; section 8's Mana : Stamina 2 : 1 traversal cost and "a blink that does not move you costs nothing" are
    SkyyArmory's asset chains + refund - no class-side cost helper exists or is needed).
Everything else (PriestHealSys, the 0.1.11 caps, kits, commands, the /class page code, the SKYY CARD block, arrows, DamageLock,
DeployGuard, migrate0110) is 0.1.11's - asserted below. Harness: SkyyClasses/test_skyyclasses_0.1.12.py.
"""
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.11.py")
dst = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.12.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
# the source must be the generated 0.1.11 of the EDITED lineage
assert 'VERSION = "0.1.11"' in s and "GENERATED by tools/classes_0_1_11_patch.py from the LIVE 0.1.10" in s, \
    "build_skyyclasses_0.1.11.py is not the generated 0.1.11"
assert "DEF_HEAL_MSG_MS = 10000   # LOCKED Skyy 2026-09-25" in s and "DEF_HEAL_SELF_PCT = 100 " in s, "0.1.11 is not the edited-lineage script"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
SYS0 = [ln for ln in s.split(LF) if "registerSystem(" in ln]


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def block(a, b, text=None):
    """the text from anchor a (included) to anchor b (excluded) of `text` (default: the CURRENT source)"""
    t = s if text is None else text
    assert t.count(a) == 1 and t.count(b) == 1, (a[:60], b[:60])
    return t[t.index(a):t.index(b)]


# ================================================================================================ blocks that must stay 0.1.11's
CARD_START = "# =====================================================================================================================\n# SKYY CARD"
CARD_END = "# ======================================================================= (end of the shared SKYY CARD block)"
CARD_SHA = "bf659e0208b537a81ac8758d909f81976f03069816ea9dddb300f843a7eaa028"   # = tools/profiles_0_1_4_patch.py + classes_0_1_9/10/11_patch.py
_card = block(CARD_START, CARD_END) + CARD_END
assert hashlib.sha256(_card.encode("utf8")).hexdigest() == CARD_SHA, "the 0.1.11 SKYY CARD block is not SkyyProfiles 0.1.4's"
KEEP = [
    _card,                                                                                                    # the shared card component
    block("# ================= ClassPage: /class =================", "# ================= OpenTask:"),      # the whole /class page
    block("# ================= ClassRules:", "# ================= bridge functions ================="),     # the weapon lock
    block("# ================= DamageLock:", "# ================= 0.1.7 DeployGuard:"),                   # blocked hits (reads ShotRec)
    block("# ================= 0.1.7 DeployGuard:", "# ================= 0.1.6 HealBudget:"),             # the Priest-only totem
    block("# ================= 0.1.6 HealBudget:", "# ================= 0.1.6 HealMsg:"),                # the 0.1.11 window budget
    block("# ================= 0.1.6 HealMsg:", "# ================= 0.1.6 Kit, part 1:"),                # heal chat lines
    block("# ================= 0.1.6 Kit, part 1:", "# ================= 0.1.6 KitTask:"),                # kits + the off-hand (0.1.10)
    block("# ================= 0.1.6 KitTask:", "# ================= 0.1.6 Kit, part 2:"),                 # KitTask (mode 0/1/2)
    block("# ================= 0.1.7 Arrows:", "# ================= 0.1.6 HealTask:"),                     # daily arrows
    block("# ================= 0.1.6 PriestHealSys:", "# ================= 0.1.6 KitHooks"),             # the 0.1.11 heal share
    block("# ================= 0.1.6 KitHooks", "# ================= 0.1.6 KitMigrate:"),
    block("# ================= 0.1.6 KitMigrate:", "# ================= ClassPage: /class ================="),
    block("# ================= ClassStore:", "# ================= ClassRules:"),
    block("# ================= ShotRec + ShotTrack:", "# ================= DamageLock:"),                  # 0.1.11 launch records
    block("# ================= 0.1.10 ClassCfg.migrate0110:", "# ================= ClassDefs:"),           # the one-time 0.1.10 update
]
# the whole 0.1.11 HealTask (every method stays; 0.1.12 only ADDS methods before run())
HT_RUN = '''M(htask, r"""
public void run() {'''
_ht_before = block("# ================= 0.1.6 HealTask:", HT_RUN)
_ht_run = block(HT_RUN, "# ================= 0.1.6 PriestHealSys:")
KEEP += [_ht_before, _ht_run]

# ================================================================================================ docstring, Run line, version
rep('''"""SkyyClasses 0.1.11 - build script (javassist via jpype). GENERATED by tools/classes_0_1_11_patch.py from the LIVE 0.1.10 (the EDITED
lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_10_patch.py -> 0.1.10) - edit the patch, not this
file; classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
''', '''"""SkyyClasses 0.1.12 - build script (javassist via jpype). GENERATED by tools/classes_0_1_12_patch.py from the generated 0.1.11 (the
EDITED lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_11_patch.py -> 0.1.11) - edit the patch, not
this file; classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
0.1.12 (2026-10-06; research/Magic-Traversal-Spec.md 3.2 + section 8 = Skyy's answers 2026-10-05): the class side of the magic traversals
  (SkyyArmory 0.1.1 = staff blink, wand hop + burst + heal orb; deploy Classes -> Armory -> Gear).
  - class:fn:heal (NEW) -> Function(Object[]{UUID healer, UUID target, Double hp, String why [, String wandItemId]}) -> Double healed,
    called on the target's world thread: refuses (0.0) non-Priests, priestHeal.enabled off, non-players, off-thread calls, targets not
    ready / dead / creative. The healer + party members get hp, every other player hp x priestHeal.othersPercent % (NEW live row,
    default 50 - Skyy: "heals everyone, but party more"). Per-hit cap = the healer's wand charged cap (0.1.11 capOf), overheal clamp,
    the shared per-second budget (HealBudget, window top = that cap), addStatValue, the heal chat lines, Divinity XP (0.1.7 calls) while
    the healer is online in that world, alive and not in creative.
  - class:fn:ally (NEW) -> Function(Object[]{UUID a, UUID b}) -> Boolean: same player or b in a's party (lock-ons = party only).
  - Card texts: Mage "Hold to blink ...", Priest "Hold to hop back and burst ..." (the staff / wand charged traversals).
  The 0.1.11 heal share, caps, kits, arrows, commands, the /class page code and the SKYY CARD block are 0.1.11's.
''')
rep("Run:   python build_skyyclasses_0.1.11.py           -> SkyyClasses/SkyyClasses-0.1.11.jar",
    "Run:   python build_skyyclasses_0.1.12.py           -> SkyyClasses/SkyyClasses-0.1.12.jar")
rep('''    Priest's self-heal HP with a trailing Boolean.TRUE), 0.1.11: armory:fn:info + armory:quick (SkyyArmory - the wand heal caps).''',
    '''    Priest's self-heal HP with a trailing Boolean.TRUE), 0.1.11: armory:fn:info + armory:quick (SkyyArmory - the wand heal caps).
  class:fn:heal (0.1.12) -> Function apply(Object[]{UUID healer, UUID target, Double hp, String why [, String wandItemId]}) -> Double
    healed (0.0 = refused); the target's world thread only. Party + the healer get hp, other players hp x priestHeal.othersPercent %.
  class:fn:ally (0.1.12) -> Function apply(Object[]{UUID a, UUID b}) -> Boolean (same player or same party; SkyyParty missing = FALSE)''')
rep('VERSION = "0.1.11"', 'VERSION = "0.1.12"')

# ================================================================================================ card texts (spec 3.2.2 + section 8)
MAGE_DESC_OLD = "Spellcaster. Staves cast magic at range - hold to charge a bigger blast."
MAGE_DESC_NEW = "Spellcaster. Staves cast magic at range. Hold to blink the way you look and leave a trail of light."
PRIEST_DESC_OLD = "AoE healer and support. Your wand and spellbook hits on monsters heal party members near you. Spells come later."
PRIEST_DESC_NEW = "AoE healer and support. Wand and spellbook hits on monsters heal your party. Hold to hop back and burst - the glow heals your party most."
for _d in (MAGE_DESC_NEW, PRIEST_DESC_NEW):
    assert not set(_d) & set(",:;{}\"'_"), _d
rep('     "desc": "%s",   # 0.1.11 fix round: the staff tap is a quick shot (SkyyArmory)' % MAGE_DESC_OLD,
    '     "desc": "%s",   # 0.1.12: the staff charged traversal (SkyyArmory 0.1.1 blink)' % MAGE_DESC_NEW)
rep('     "desc": "%s",' % PRIEST_DESC_OLD,
    '     "desc": "%s",   # 0.1.12: the wand charged traversal (SkyyArmory 0.1.1 hop + burst + heal orb; spec 8: party most)' % PRIEST_DESC_NEW)

# ================================================================================================ the non-party share constant
rep('''HEAL_QUICK_MAX = 100
''', '''HEAL_QUICK_MAX = 100
# 0.1.12 (research/Magic-Traversal-Spec.md section 8, Skyy 2026-10-05: "healing orb heals everyone, but party more"): class:fn:heal gives the
# healer + party members the full hp, every other (non-hostile) player hp x OTHERS_PCT % - Skyy's example ratio party 100 / others 50
DEF_HEAL_OTHERS_PCT = 50        # priestHeal.othersPercent
HEAL_OTHERS_MAX = 100
CLASS_HEAL_KEY = "class:fn:heal"
CLASS_ALLY_KEY = "class:fn:ally"
''')

# ================================================================================================ engine probes for the new calls
rep('''# 0.1.11: the launched projectile's asset id (ShotTrack -> ShotRec.pid -> the heal cap's quick / charged shot)
B.probe(pool, T["LPC"], "getProjectileAssetName")''', '''# 0.1.11: the launched projectile's asset id (ShotTrack -> ShotRec.pid -> the heal cap's quick / charged shot)
B.probe(pool, T["LPC"], "getProjectileAssetName")
# 0.1.12 (class:fn:heal): the world-thread test (TickingThread.isInThread = Thread.currentThread() == this.thread, read in HytaleServer.jar
# bytecode) and the main hand through a Store (InventoryComponent.getItemInHand(ComponentAccessor, Ref); Store implements ComponentAccessor)
B.probe(pool, T["WLD"], "isInThread")
B.probe(pool, T["ST"], "getExternalData")
assert pool.get(T["ST"]).subtypeOf(pool.get("com.hypixel.hytale.component.ComponentAccessor")), "Store must be a ComponentAccessor"
assert str(pool.get(T["INVC"]).getMethod("getItemInHand", "(Lcom/hypixel/hytale/component/ComponentAccessor;Lcom/hypixel/hytale/component/Ref;)"
                                         "Lcom/hypixel/hytale/server/core/inventory/ItemStack;").getName()) == "getItemInHand"''')

# ================================================================================================ the default file: the rule + the key
rep('''    "priestHeal.maxPerSecond=%s" % dnum(DEF_HEAL_MAX_SEC),
    "# messages = heal chat lines''', '''    "priestHeal.maxPerSecond=%s" % dnum(DEF_HEAL_MAX_SEC),
    "# 0.1.12 (Skyy 2026-10-05): the wand heal orb (SkyyArmory) heals the Priest and party members fully, every other player who is not",
    "# an enemy othersPercent percent of that (0 = party only). Same caps as above (the wand's charged cap per tick, the per-second budget).",
    "priestHeal.othersPercent=%d" % DEF_HEAL_OTHERS_PCT,      # 0.1.12
    "# messages = heal chat lines''')

# ================================================================================================ ClassCfg: field + load()
rep('''F(cfg, "public static volatile long HEAL_QUICK_PCT = %dL;" % DEF_HEAL_QUICK_PCT)          # 0.1.11: priestHeal.quickPercent
''', '''F(cfg, "public static volatile long HEAL_QUICK_PCT = %dL;" % DEF_HEAL_QUICK_PCT)          # 0.1.11: priestHeal.quickPercent
F(cfg, "public static volatile long HEAL_OTHERS_PCT = %dL;" % DEF_HEAL_OTHERS_PCT)        # 0.1.12: priestHeal.othersPercent
''')
rep('''    "__HQP__": "%dL" % DEF_HEAL_QUICK_PCT, "__HQPMAX__": "%dL" % HEAL_QUICK_MAX,
''', '''    "__HQP__": "%dL" % DEF_HEAL_QUICK_PCT, "__HQPMAX__": "%dL" % HEAL_QUICK_MAX,
    # 0.1.12 the heal orb's non-party share
    "__HOP__": "%dL" % DEF_HEAL_OTHERS_PCT, "__HOPMAX__": "%dL" % HEAL_OTHERS_MAX,
''')
rep('''    HEAL_QUICK_PCT = hqp;
    HEAL_MSG = bool(p, "priestHeal.messages", __HM__);''', '''    HEAL_QUICK_PCT = hqp;
    long hop = lng(p, "priestHeal.othersPercent", __HOP__);
    if (hop < 0L) hop = 0L;
    if (hop > __HOPMAX__) hop = __HOPMAX__;
    HEAL_OTHERS_PCT = hop;
    HEAL_MSG = bool(p, "priestHeal.messages", __HM__);''')

# ================================================================================================ the row (kit limits: label 40, help 100)
ROW_OP = ("priestHeal.othersPercent", "Heal orb on non-party players (%)",
          "Wand heal orb on players outside your party as % of what party members get. 0 = party only.")
assert len(ROW_OP[1]) <= 40 and len(ROW_OP[2]) <= 100 and not set('"\\') & set(ROW_OP[1] + ROW_OP[2]), ROW_OP
rep('''     "field:ClassCfg.HEAL_MAX_SEC@config.properties:priestHeal.maxPerSecond"),
    ("priestHeal.messages",''', '''     "field:ClassCfg.HEAL_MAX_SEC@config.properties:priestHeal.maxPerSecond"),
    # 0.1.12 (research/Magic-Traversal-Spec.md section 8, Skyy 2026-10-05: "heals everyone, but party more"): class:fn:heal's non-party share
    ("%s", "%s", "priest", "int", str(DEF_HEAL_OTHERS_PCT), "0", str(HEAL_OTHERS_MAX), "", "%%", "live",
     "%s",
     "field:ClassCfg.HEAL_OTHERS_PCT@config.properties:priestHeal.othersPercent"),
    ("priestHeal.messages",''' % ROW_OP)
rep('''assert len(CFG_ROWS) == 5 + 2 + 1 + 2 * len(CLASSES) + 10 + 4, "row count"   # 0.1.7: + 2 greyed-out switch rows, + 4 arrow rows; 0.1.11: + 2 heal rows''',
    '''assert len(CFG_ROWS) == 5 + 2 + 1 + 2 * len(CLASSES) + 11 + 4, "row count"   # 0.1.7: + 2 greyed-out switch rows, + 4 arrow rows; 0.1.11: + 2 heal rows; 0.1.12: + 1''')
rep('''               "priestHeal.quickPercent", "priestHeal.maxPerHit", "priestHeal.maxPerSecond", "priestHeal.messages", "priestHeal.feedbackMs"], _PR''',
    '''               "priestHeal.quickPercent", "priestHeal.maxPerHit", "priestHeal.maxPerSecond", "priestHeal.othersPercent", "priestHeal.messages",
               "priestHeal.feedbackMs"], _PR''')

# ================================================================================================ the two new bridge classes
rep('''phs   = pool.makeClass(PKG + ".PriestHealSys", pool.get(T["DES"]))
''', '''phs   = pool.makeClass(PKG + ".PriestHealSys", pool.get(T["DES"]))
hfn   = pool.makeClass(PKG + ".HealFn")     # 0.1.12: class:fn:heal (the SkyyArmory heal orb)
alfn  = pool.makeClass(PKG + ".AllyFn")     # 0.1.12: class:fn:ally (traversal lock-ons + friendly fire = party only)
''')

# ================================================================================================ HealTask: the bridge heal (methods before run())
BRIDGE_JAVA = '''# 0.1.12 (research/Magic-Traversal-Spec.md 3.2 + section 8): class:fn:heal / class:fn:ally helpers. A bridge argument as a UUID (a UUID or
# its String form; anything else = null). Pure.
M(htask, r"""
public static java.util.UUID uuidOf(Object o) {
  if (o == null) return null;
  if (o instanceof java.util.UUID) return (java.util.UUID) o;
  if (!(o instanceof String)) return null;
  try { return java.util.UUID.fromString(((String) o).trim()); } catch (Throwable t) { return null; }
}""")
# is b in a's party (party:fn:members of a)? SkyyParty missing / no answer / not in a party = false. Any thread.
M(htask, r"""
public static boolean inParty(java.util.UUID a, java.util.UUID b) {
  if (a == null || b == null) return false;
  String[] ms = members(a);
  if (ms == null) return false;
  String bs = b.toString();
  for (int i = 0; i < ms.length; i++) if (ms[i] != null && ms[i].trim().equalsIgnoreCase(bs)) return true;
  return false;
}""")
# class:fn:ally: the same player, or b in a's party (spec 8: traversal lock-ons target party members only). Later guilds.
M(htask, r"""
public static boolean ally(java.util.UUID a, java.util.UUID b) {
  if (a == null || b == null) return false;
  if (a.equals(b)) return true;
  return inParty(a, b);
}""")
# the heal one target gets (pure, bare-JVM tested): the healer + party members the full hp, every other player hp x othersPct % (0-100)
M(htask, r"""
public static double split(double hp, boolean party, long othersPct) {
  if (!(hp > 0.0) || Double.isInfinite(hp)) return 0.0;
  if (party) return hp;
  long q = othersPct < 0L ? 0L : (othersPct > 100L ? 100L : othersPct);
  return hp * (double) q / 100.0;
}""")
# the healer's wand CHARGED cap with the live config (0.1.11 capOf): max(maxPerHit, hpPerMana x its charged Mana); not a wand SkyyArmory
# knows / no item / no SkyyArmory = maxPerHit. Never throws.
M(htask, r"""
public static double chargedCap(String item) {
  double mana = wandMana(item);
  return capOf(mana, mana > 0.0, false, @PKG@.ClassCfg.HEAL_MAX_HIT, @PKG@.ClassCfg.HEAL_PER_MANA, @PKG@.ClassCfg.HEAL_QUICK_PCT);
}""")
F(htask, "public static volatile boolean OFF_THREAD_ONCE = false;")   # 0.1.12: an off-thread class:fn:heal call is logged once
# class:fn:heal (spec 3.2.1 + section 8): the target's world thread only (SkyyArmory's TravTick). Returns the HP really healed (0 = refused /
# nothing to heal). The order: switch -> arguments -> the healer is a Priest -> the target is an online player -> its world thread -> ready,
# alive, not creative -> split -> the wand's charged cap -> room -> the shared per-second budget -> addStatValue -> chat lines -> XP.
M(htask, r"""
public static double bridgeHeal(java.util.UUID healer, java.util.UUID target, double hp, String why, String wand) {
  if (!@PKG@.ClassCfg.HEAL_ON) return 0.0;
  if (healer == null || target == null || !(hp > 0.0) || Double.isInfinite(hp)) return 0.0;
  int ci = @PKG@.ClassStore.classIndex(healer);
  if (ci != @PKG@.ClassDefs.PRIEST || !@PKG@.ClassDefs.ENABLED[ci]) return 0.0;
  @PR@ tp = @UNI@.get().getPlayer(target);
  if (tp == null || !tp.isValid()) return 0.0;
  @REF@ tr = tp.getReference();
  if (tr == null || !tr.isValid()) return 0.0;
  @ST@ st = tr.getStore();
  if (st == null) return 0.0;
  Object ext = st.getExternalData();
  @WLD@ w = ext instanceof @ES@ ? ((@ES@) ext).getWorld() : null;
  if (w == null) return 0.0;
  if (!w.isInThread()) {
    if (!OFF_THREAD_ONCE) { OFF_THREAD_ONCE = true; @PKG@.ClassCfg.warn("class:fn:heal called off the target's world thread - refused (logged once; why=" + why + ")"); }
    return 0.0;
  }
  @PLA@ pl = (@PLA@) st.getComponent(tr, @PLA@.getComponentType());
  if (pl == null || pl.isWaitingForClientReady() || @PKG@.Kit.creative(pl) || !@PKG@.Kit.alive(st, tr)) return 0.0;
  boolean self = healer.equals(target);
  boolean party = self || inParty(healer, target);
  String item = wand != null && wand.length() > 0 ? wand : null;
  String name = null;
  boolean xpOk = false;
  @PR@ hpr = self ? tp : @UNI@.get().getPlayer(healer);
  if (hpr != null && hpr.isValid()) {
    name = hpr.getUsername();
    @REF@ hr = hpr.getReference();
    if (hr != null && hr.isValid() && hr.getStore() == st) {
      @PLA@ hpl = (@PLA@) st.getComponent(hr, @PLA@.getComponentType());
      xpOk = hpl != null && !@PKG@.Kit.creative(hpl) && @PKG@.Kit.alive(st, hr);
      if (item == null) {
        @IS@ main = @INVC@.getItemInHand(st, hr);
        if (main != null && !main.isEmpty()) item = main.getItemId();
      }
    }
  }
  double cap = chargedCap(item);
  double want = split(hp, party, @PKG@.ClassCfg.HEAL_OTHERS_PCT);
  if (want > cap) want = cap;
  double got = heal(st, tr, target, want, System.currentTimeMillis(), cap);
  if (!(got > 0.0)) return 0.0;
  @PKG@.HealMsg.given(healer, target, got);
  if (!self) @PKG@.HealMsg.taken(target, healer, name, got);
  if (xpOk) {
    if (self) xpSelf(healer, got);
    else xp(healer, got);
  }
  return got;
}""")
'''
rep(HT_RUN, BRIDGE_JAVA + HT_RUN)

FN_JAVA = '''# ================= 0.1.12 HealFn + AllyFn: class:fn:heal / class:fn:ally (research/Magic-Traversal-Spec.md 3.2, section 8) =================
# class:fn:heal apply(Object[]{UUID healer, UUID target, Double hp, String why [, String wandItemId]}) -> Double healed (0.0 = refused);
# UUIDs may also be their String form; the optional 5th element names the wand that cast (else the healer's main hand). Never throws.
hfn.addInterface(pool.get("java.util.function.Function"))
C(hfn, "public HealFn() { }")
M(hfn, r"""
public Object apply(Object o) {
  try {
    if (!(o instanceof Object[])) return Double.valueOf(0.0);
    Object[] a = (Object[]) o;
    if (a.length < 3 || !(a[2] instanceof Number)) return Double.valueOf(0.0);
    java.util.UUID h = @PKG@.HealTask.uuidOf(a[0]);
    java.util.UUID tg = @PKG@.HealTask.uuidOf(a[1]);
    double hp = ((Number) a[2]).doubleValue();
    String why = a.length > 3 && a[3] != null ? String.valueOf(a[3]) : null;
    String wand = a.length > 4 && a[4] instanceof String ? (String) a[4] : null;
    return Double.valueOf(@PKG@.HealTask.bridgeHeal(h, tg, hp, why, wand));
  } catch (Throwable t) { @PKG@.HealTask.failOnce(t); return Double.valueOf(0.0); }
}""")
# class:fn:ally apply(Object[]{UUID a, UUID b}) -> Boolean (same player or same party). Never throws (bad arguments = FALSE).
alfn.addInterface(pool.get("java.util.function.Function"))
C(alfn, "public AllyFn() { }")
M(alfn, r"""
public Object apply(Object o) {
  try {
    if (!(o instanceof Object[])) return Boolean.FALSE;
    Object[] a = (Object[]) o;
    if (a.length < 2) return Boolean.FALSE;
    return Boolean.valueOf(@PKG@.HealTask.ally(@PKG@.HealTask.uuidOf(a[0]), @PKG@.HealTask.uuidOf(a[1])));
  } catch (Throwable t) { return Boolean.FALSE; }
}""")

'''
rep("# ================= 0.1.6 PriestHealSys:", FN_JAVA + "# ================= 0.1.6 PriestHealSys:")

# ================================================================================================ setup: publish the two functions
rep('''  b.put("class:fn:kitnew", new @PKG@.KitNewFn());   // 0.1.6 (SkyyProfiles 0.1.2 Create Profile)
''', '''  b.put("class:fn:kitnew", new @PKG@.KitNewFn());   // 0.1.6 (SkyyProfiles 0.1.2 Create Profile)
  b.put("class:fn:heal", new @PKG@.HealFn());       // 0.1.12: the SkyyArmory heal orb (world thread; party + healer full, others %)
  b.put("class:fn:ally", new @PKG@.AllyFn());       // 0.1.12: traversal lock-ons / friendly fire = party only
''')
rep('''for c in (cfg, kcfg, hooks, defs, st_, rul, afn, gfn, ksoon, knew, srec, strk, lock, dgd, hbud, hmsg, kit_, ktask, arw, htask, phs, khooks,''',
    '''for c in (cfg, kcfg, hooks, defs, st_, rul, afn, gfn, ksoon, knew, srec, strk, lock, dgd, hbud, hmsg, kit_, ktask, arw, htask, hfn, alfn, phs, khooks,''')
rep('''Priests heal their party and own the Healing Totem.''',
    '''Priests heal their party and own the Healing Totem; the wand heal orb and traversal lock-ons go through class:fn:heal / class:fn:ally.''')

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
assert [ln for ln in s.split(LF) if "registerSystem(" in ln] == SYS0, "system registrations changed"
for k in KEEP:
    assert k in s, "a block that must stay 0.1.11's changed: %s" % k[:80]
_card2 = block(CARD_START, CARD_END) + CARD_END
assert _card2 == _card and hashlib.sha256(_card2.encode("utf8")).hexdigest() == CARD_SHA, "the SKYY CARD block must stay SkyyProfiles 0.1.4's"
assert s.count("HealBudget.take(") == 1 and s.count("new @PKG@.HealTask(") == 1 and s.count("new @PKG@.ShotRec(") == 1
assert s.count('b.put("class:fn:heal"') == 1 and s.count('b.put("class:fn:ally"') == 1
# javassist: methods before callers
_ht = block("# ================= 0.1.6 HealTask:", "# ================= 0.1.6 PriestHealSys:")
for _a, _b in (("public static String[] members(", "public static boolean inParty("), ("public static boolean inParty(", "public static boolean ally("),
               ("public static double wandMana(", "public static double chargedCap("), ("public static double capOf(", "public static double chargedCap("),
               ("public static double heal(", "public static double bridgeHeal("), ("public static void xp(", "public static double bridgeHeal("),
               ("public static void xpSelf(", "public static double bridgeHeal("), ("public static boolean inParty(", "public static double bridgeHeal("),
               ("public static double split(", "public static double bridgeHeal("), ("public static double chargedCap(", "public static double bridgeHeal("),
               ("public static java.util.UUID uuidOf(", "public static double bridgeHeal("), ("public static double bridgeHeal(", "public void run()"),
               ("public static void failOnce(", "public static double bridgeHeal(")):
    assert _ht.index(_a) < _ht.index(_b), (_a, _b)
assert s.index("public static double bridgeHeal(") < s.index("@PKG@.HealTask.bridgeHeal(h, tg"), "HealTask.bridgeHeal before HealFn"
assert s.index("public static boolean ally(") < s.index("@PKG@.HealTask.ally("), "HealTask.ally before AllyFn"
assert s.index("public static synchronized void given(") < s.index("public static double bridgeHeal("), "HealMsg before bridgeHeal"
assert s.index("public static boolean alive(") < s.index("public static double bridgeHeal("), "Kit.alive before bridgeHeal"
assert s.index("public Object apply(Object o) {\n  try {\n    if (!(o instanceof Object[])) return Double.valueOf(0.0);") < s.index("public void setup()")
assert 'VERSION = "0.1.12"' in s and "priestHeal.othersPercent" in s and MAGE_DESC_NEW in s and PRIEST_DESC_NEW in s
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.11 had %d)" % (s.count(LF), OLD.count(LF)))
