"""Derive SkyyClasses/build_skyyclasses_0.1.14.py from the CURRENT generated 0.1.13 (build_skyyclasses_0.1.13.py = the tools/deploy_set.py
SET pin) + its harness SkyyClasses/test_skyyclasses_0.1.14.py from test_skyyclasses_0.1.13.py.
Run:  python tools/classes_0_1_14_patch.py   then   python SkyyClasses/build_skyyclasses_0.1.14.py   then
      python SkyyClasses/test_skyyclasses_0.1.14.py      (never --deploy: coordinated deploy with SkyySkills 0.4.21 + SkyyProfiles 0.1.6)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_13_patch.py
-> the generated 0.1.13 read here; tools/classes_0_1_6_patch.py is NEVER re-run. Edit THIS file, never the generated build script.

0.1.14 = ASSASSIN + MONK ARE PLAYABLE (Skyy LOCKED 2026-10-07 "1. make the classes" - docs/answered/classes.md; 2026-10-03 "lets swap
shaman out for a monk, that uses a staff"; 2026-10-04 class weapons: 2 weapon types per class, NO sharing; Monk = Bo staff + fist weapons,
Assassin = daggers + kunai; docs/answered/gear.md 2026-10-06 Monk colour B Saffron #f08a30):
  - ASSASSIN enabled (Assassination; daggers Weapon_Daggers_* + every kunai: the vanilla Weapon_Kunai and SkyyArmory's Weapon_Kunai_<Metal>
    through the old "Weapon_Kunai" rule); role "Priority killer" (research/classes/Assassin.md), its card text.
  - The Shaman slot becomes MONK (same index 6, same place everywhere): name Monk, skill Discipline (research/cloud/Monk-Kit-Spec.md 4
    default - the name is OPEN for Skyy), colour #f08a30, role "Self-speed disruptor" (research/classes/Monk.md), enabled. Weapons: the
    vanilla Bo staffs ("Weapon_Staff_Bo_" - longer than the Mage's "Weapon_Staff_", so only Weapon_Staff_Bo_Bamboo / _Wood move; every
    other vanilla + SkyyArmory staff stays Mage, proven below), SkyyArmory 0.1.7's Bo staffs ("Weapon_Bo_") and fist weapons
    ("Weapon_Fist_": wraps + gauntlets). Kit: Weapon_Staff_Bo_Wood:1 (the vanilla Wood Bo; the cloth wraps start at Lv 10+). Icons: the
    two vanilla Bo staffs (the class cards draw item icons, not emblems - the Monk emblem art stays a picture for later).
    Vanilla Weapon_Claws_Tribal stays unassigned (claws come later - Skyy 2026-10-07 "Wraps + gauntlets only").
  - MIGRATION SAFETY (no file is rewritten): the old name is an ALIAS. ClassDefs.indexOf("Shaman" / "Shamans" / "Shaman skill", any case) =
    the Monk, so a profile:class = Shaman (/profileadmin setclass allowed it), a hand-written class=Shaman file line and /classadmin
    set ... shaman all mean Monk; class:<uuid> then says "Monk" and class:skill:<uuid> "Discipline" (SkyySkills 0.4.21 keeps the saved
    key Combat.Shaman for that slot). Config: the kit row is kit.Monk now. READ-SIDE FALLBACK (fixer 2, critic 1 LOW - an admin could
    have saved a Shaman kit in Server Setup): while the file has NO kit.Monk line, a NON-EMPTY kit.Shaman line is the Monk kit (logged at
    each load; nothing is rewritten); the old default empty "kit.Shaman=" line = the code default; kit.Monk present (even empty) wins.
    The first Monk kit save in Server Setup writes kit.Monk, which then wins for good.
  - Texts: /class description, manifest description. The 'Block weapons no class owns' row is unchanged.
  Nothing else changes: no new class, command, binding or system; no bridge key added or removed.
"""
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.13.py")
dst = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.14.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1.13"' in s and "GENERATED by tools/classes_0_1_13_patch.py from the generated 0.1.12" in s, \
    "build_skyyclasses_0.1.13.py is not the generated 0.1.13"
assert "DEF_HEAL_MSG_MS = 10000   # LOCKED Skyy 2026-09-25" in s and "DEF_HEAL_SELF_PCT = 100 " in s, "0.1.13 is not the edited-lineage script"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
SYS0 = [ln for ln in s.split(LF) if "registerSystem(" in ln]


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def block(a, b, text=None):
    t = s if text is None else text
    assert t.count(a) == 1 and t.count(b) == 1, (a[:60], b[:60])
    return t[t.index(a):t.index(b)]


# ================================================================================================ blocks that must stay 0.1.13's
CARD_START = "# =====================================================================================================================\n# SKYY CARD"
CARD_END = "# ======================================================================= (end of the shared SKYY CARD block)"
CARD_SHA = "bf659e0208b537a81ac8758d909f81976f03069816ea9dddb300f843a7eaa028"   # = tools/profiles_0_1_4_patch.py + classes_0_1_9..13_patch.py
_card = block(CARD_START, CARD_END) + CARD_END
assert hashlib.sha256(_card.encode("utf8")).hexdigest() == CARD_SHA, "the 0.1.13 SKYY CARD block is not SkyyProfiles 0.1.4's"
JAVA_FROM = "# ================= ClassDefs:"
_java_old = s[s.index(JAVA_FROM):]

# ================================================================================================ docstring, Run line, version
rep('''"""SkyyClasses 0.1.13 - build script (javassist via jpype). GENERATED by tools/classes_0_1_13_patch.py from the generated 0.1.12 (the
EDITED lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_12_patch.py -> 0.1.12) - edit the patch, not
this file; classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
''', '''"""SkyyClasses 0.1.14 - build script (javassist via jpype). GENERATED by tools/classes_0_1_14_patch.py from the generated 0.1.13 (the
EDITED lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_13_patch.py -> 0.1.13) - edit the patch, not
this file; classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
0.1.14 (2026-10-07; Skyy LOCKED "1. make the classes", docs/answered/classes.md): ASSASSIN + MONK ARE PLAYABLE. Assassin enabled
  (daggers + kunai). The Shaman slot is the MONK now (skill Discipline, colour #f08a30, role Self-speed disruptor; weapons = the vanilla
  Bo staffs Weapon_Staff_Bo_* - moved from the Mage, no other staff moves - + SkyyArmory's Weapon_Bo_* and Weapon_Fist_* wraps /
  gauntlets; kit Weapon_Staff_Bo_Wood:1). "Shaman" stays an ALIAS of the Monk (ClassDefs.indexOf) for profiles / files / commands that
  still say Shaman - no file is rewritten. Config row kit.Shaman -> kit.Monk. Deploy with SkySkills 0.4.21 + SkyyProfiles 0.1.6
  (full notes in tools/classes_0_1_14_patch.py).
''')
rep("Run:   python build_skyyclasses_0.1.13.py           -> SkyyClasses/SkyyClasses-0.1.13.jar",
    "Run:   python build_skyyclasses_0.1.14.py           -> SkyyClasses/SkyyClasses-0.1.14.jar")
rep('VERSION = "0.1.13"', 'VERSION = "0.1.14"')

# ================================================================================================ the class table
ASSASSIN_DESC_OLD = "Coming later. Fast and deadly with twin daggers and kunai throwing knives."
ASSASSIN_DESC_NEW = "Burst damage on one target. Fast twin daggers up close and kunai thrown from range - strike from behind for more."
# fixer 2 (critic 3, LOW): gauntlets are the HEAVY Monk weapon (classes.md LOCKED 2026-10-07 "gauntlets are kinda a heavy weapon")
MONK_DESC = "Fast melee fighter. A bo staff strikes with reach - quick hand wraps and heavy gauntlets."
SHAMAN_DESC = "Coming later. The fifth Wynncraft class - it gets its own custom weapon."
MONK_ICONS = ["Weapon_Staff_Bo_Wood", "Weapon_Staff_Bo_Bamboo"]
MONK_WTEXT = "Bo Staves / Wraps / Gauntlets"
MONK_KIT = "Weapon_Staff_Bo_Wood:1"
for _d in (ASSASSIN_DESC_NEW, MONK_DESC, MONK_WTEXT, "Priority killer", "Self-speed disruptor", "Discipline"):
    assert not set(_d) & set(",:;{}\"'_\\"), _d
assert len(ASSASSIN_DESC_NEW) <= 130 and len(MONK_DESC) <= 130, "two lines on the card (the SkyyProfiles rule)"
rep('''    {"name": "Assassin", "skill": "Assassination", "color": "#b58cff", "enabled": False, "role": "Fast burst damage",
     "desc": "%s",
     "icons": ["Weapon_Daggers_Iron", "Weapon_Kunai"],''' % ASSASSIN_DESC_OLD,
    '''    # 0.1.14 (Skyy LOCKED 2026-10-07 "make the classes"): playable; role + text from research/classes/Assassin.md
    {"name": "Assassin", "skill": "Assassination", "color": "#b58cff", "enabled": True, "role": "Priority killer",
     "desc": "%s",
     "icons": ["Weapon_Daggers_Iron", "Weapon_Kunai"],''' % ASSASSIN_DESC_NEW)
rep('''    # 0.1.6: Shaman gets a custom weapon later (change note 4); its icon is only a picture (the wand is a Priest weapon now)
    {"name": "Shaman", "skill": "Shaman skill", "color": "#ff7a5c", "enabled": False, "role": "Designed later",
     "desc": "%s",
     "icons": ["Weapon_Deployable_Slowness_Totem"],
     "weapons": [],
     "weapon_text": "Custom weapon later", "kit": ""},''' % SHAMAN_DESC,
    '''    # 0.1.14 (Skyy LOCKED 2026-10-03 "swap shaman out for a monk"; 2026-10-04 Monk = Bo staff + fist weapons; gear.md 2026-10-06 colour
    # B Saffron): the Shaman slot (index 6) is the MONK. "Shaman" stays an alias (ClassDefs.ALIAS_*). Skill name = Monk-Kit-Spec 4 default
    # (OPEN for Skyy). Weapon_Staff_Bo_ is longer than the Mage's Weapon_Staff_ = only the two vanilla Bo staffs move; Weapon_Bo_ +
    # Weapon_Fist_ = SkyyArmory 0.1.7 (no vanilla item has either prefix - asserted below). Claws stay unassigned (later).
    {"name": "Monk", "skill": "Discipline", "color": "#f08a30", "enabled": True, "role": "Self-speed disruptor",
     "desc": "%s",
     "icons": %r,
     "weapons": [("Weapon_Staff_Bo_", "bo staves"), ("Weapon_Bo_", "bo staves"), ("Weapon_Fist_", "fist weapons")],
     "weapon_text": "%s", "kit": "%s"},''' % (MONK_DESC, MONK_ICONS, MONK_WTEXT, MONK_KIT))
rep('''UI_DATA_COLORS = ["#8fd67a", "#e0b060", "#7fb0e0", "#d9443f", "#f2e6a0", "#b58cff", "#ff7a5c"] + ["#8fe39a", "#ffc800", "#ff9d6b"]''',
    '''# 0.1.14: the Monk's saffron #f08a30 replaces the Shaman's #ff7a5c (gear.md LOCKED 2026-10-06)
UI_DATA_COLORS = ["#8fd67a", "#e0b060", "#7fb0e0", "#d9443f", "#f2e6a0", "#b58cff", "#f08a30"] + ["#8fe39a", "#ffc800", "#ff9d6b"]''')
# 0.1.14: the old class name -> the class that replaced it (ClassDefs.ALIAS_FROM / ALIAS_TO; read side only, nothing is rewritten)
rep('''# usable by every class (and by classless players)
FREE_WEAPONS = [("Weapon_Shield_", "shields")]''', '''# 0.1.14: names that once meant a class slot -> that slot's class now (profile:class, class files, commands; any case)
CLASS_ALIASES = [("Shaman", "Monk"), ("Shamans", "Monk"), ("Shaman skill", "Monk")]
# 0.1.14: weapon prefixes only SkyyArmory items carry (no vanilla id - checked against Assets.zip and the SkyyArmory jar below)
ARMORY_PREFIXES = ["Weapon_Bo_", "Weapon_Fist_"]
# usable by every class (and by classless players)
FREE_WEAPONS = [("Weapon_Shield_", "shields")]''')

# ================================================================================================ the Assets.zip prefix check
rep('''for _p, _o, _n in RULES:
    assert any(_i.startswith(_p) for _i in _real), "weapon prefix %s matches no item in Assets.zip" % _p
''', '''for _p, _o, _n in RULES:
    if _p in ARMORY_PREFIXES:   # 0.1.14: SkyyArmory-only prefixes must NOT catch a vanilla item (they would move it)
        assert not any(_i.startswith(_p) for _i in _real), "SkyyArmory prefix %s matches a vanilla item" % _p
        continue
    assert any(_i.startswith(_p) for _i in _real), "weapon prefix %s matches no item in Assets.zip" % _p
''')
rep('''        if _c["weapons"]:  # 0.1.2: a not-yet-designed class (Shaman) has no weapons, its icon is only a picture
''', '''        if _c["weapons"]:  # 0.1.2: a class without weapons would only show a picture (0.1.14: every class has weapons)
''')

# ================================================================================================ build-time proofs (replace 0.1.13's Assassin-disabled line)
rep('''assert all(classify(i)[0] == ASSASSIN_I13 for i in _kunai13) and not CLASSES[ASSASSIN_I13]["enabled"], [(i, classify(i)) for i in _kunai13]
''', '''assert all(classify(i)[0] == ASSASSIN_I13 for i in _kunai13), [(i, classify(i)) for i in _kunai13]   # 0.1.14: the Assassin is playable
''')
rep('''print("0.1.13: %d spellbooks -> Mage (%d vanilla + 7 SkyyArmory), wands + Healing Totem -> Priest, %d kunai ids -> Assassin (disabled)"
      % (len(_books13), len(_books13) - 7, len(_kunai13)))
''', '''print("0.1.13: %d spellbooks -> Mage (%d vanilla + 7 SkyyArmory), wands + Healing Totem -> Priest, %d kunai ids -> Assassin"
      % (len(_books13), len(_books13) - 7, len(_kunai13)))
# 0.1.14: ASSASSIN + MONK playable; every Monk / Assassin weapon proven, no Mage staff affected, no weapon shared
MONK_I14 = [i for i, c in enumerate(CLASSES) if c["name"] == "Monk"][0]
assert MONK_I14 == 6 and ASSASSIN_I13 == 5 and CLASSES[MONK_I14]["enabled"] and CLASSES[ASSASSIN_I13]["enabled"], "Monk = the old Shaman slot"
assert [c["name"] for c in CLASSES] == ["Archer", "Warrior", "Mage", "Berserker", "Priest", "Assassin", "Monk"] and all(c["enabled"] for c in CLASSES)
_vbo14 = [i for i in _real if i.startswith("Weapon_Staff_Bo_")]
_vstaff14 = [i for i in _real if i.startswith("Weapon_Staff_") and not i.startswith("Weapon_Staff_Bo_")]
assert _vbo14 == ["Weapon_Staff_Bo_Bamboo", "Weapon_Staff_Bo_Wood"], _vbo14
assert all(classify(i) == (MONK_I14, "bo staves") for i in _vbo14), [(i, classify(i)) for i in _vbo14]
assert len(_vstaff14) == 22 and all(classify(i) == (MAGE_I13, "staves") for i in _vstaff14), [(i, classify(i)) for i in _vstaff14]
_dag14 = [i for i in _real if i.startswith("Weapon_Daggers_")]
assert len(_dag14) == 16 and all(classify(i) == (ASSASSIN_I13, "daggers") for i in _dag14), [(i, classify(i)) for i in _dag14]
assert classify("Weapon_Claws_Tribal")[0] == UNASSIGNED_OWNER, "claws stay unassigned (Skyy: claws later)"
assert classify("Prototype_Tool_Staff_Mana")[0] == FREE, "a non-Weapon_ staff stays free"
# SkyyArmory 0.1.7 (the SET pin, read only): its Bo / fist ids = Monk, kunai = Assassin, staffs / spellbooks = Mage, wands = Priest
_ARM14 = os.path.join(HERE, "..", "SkyyArmory", "SkyyArmory-0.1.7.jar")
_MONK_ARMORY = ["Weapon_Bo_%s" % m for m in ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")] + \\
               ["Weapon_Fist_Gauntlets_%s" % m for m in ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")] + \\
               ["Weapon_Fist_Wraps_%s" % c for c in ("Linen", "Cotton", "Silk", "Cindercloth", "Shadoweave")]
if os.path.isfile(_ARM14):
    _aids = sorted(os.path.basename(n)[:-5] for n in zipfile.ZipFile(_ARM14).namelist() if n.startswith("Server/Item/Items/") and n.endswith(".json"))
    assert sorted(i for i in _aids if i.startswith(("Weapon_Bo_", "Weapon_Fist_"))) == sorted(_MONK_ARMORY), "SkyyArmory 0.1.7 Monk ids changed"
    _want = {"Weapon_Bo_": MONK_I14, "Weapon_Fist_": MONK_I14, "Weapon_Kunai": ASSASSIN_I13, "Weapon_Staff_": MAGE_I13,
             "Weapon_Spellbook_": MAGE_I13, "Weapon_Wand_": PRIEST_I}
    _bad = [(i, classify(i)[0]) for i in _aids for p, o in _want.items() if o is not None and i.startswith(p) and classify(i)[0] != o]
    assert not _bad, "SkyyArmory ids with the wrong owner: %s" % _bad
    print("0.1.14: SkyyArmory 0.1.7 jar: %d item ids checked (Bo / fists = Monk, kunai = Assassin, staffs / books = Mage, wands = Priest)" % len(_aids))
else:
    print("0.1.14: NOTE - SkyyArmory/SkyyArmory-0.1.7.jar not built here; the Monk ids are checked from the table only")
assert all(classify(i) in ((MONK_I14, "bo staves"), (MONK_I14, "fist weapons")) for i in _MONK_ARMORY)
# no weapon sharing: every prefix has exactly one owner (RULES has no duplicate prefix - asserted above) and no Monk prefix is another
# class's prefix's extension except the Bo-in-staff carve-out (Weapon_Staff_Bo_ under the Mage's Weapon_Staff_)
_own14 = {}
for _p, _o, _n in RULES:
    _own14.setdefault(_o, []).append(_p)
assert sorted(_own14[MONK_I14]) == ["Weapon_Bo_", "Weapon_Fist_", "Weapon_Staff_Bo_"] and sorted(_own14[ASSASSIN_I13]) == ["Weapon_Daggers_", "Weapon_Kunai"]
for _a, _n in CLASS_ALIASES:
    assert _n in [c["name"] for c in CLASSES] and _a.lower() not in [c["name"].lower() for c in CLASSES] + [c["skill"].lower() for c in CLASSES]
print("0.1.14: Assassin playable (%d daggers + kunai); MONK playable: %s + %d SkyyArmory Bo / fist ids; %d other staves stay Mage; aliases %s"
      % (len(_dag14), ", ".join(_vbo14), len(_MONK_ARMORY), len(_vstaff14), ", ".join("%s -> %s" % a for a in CLASS_ALIASES)))
''')

# ================================================================================================ Java: the alias in ClassDefs.indexOf
rep('''F(defs, "public static final String[] R_NOUN = %s;" % jarr([r[2] for r in RULES]))
''', '''F(defs, "public static final String[] R_NOUN = %s;" % jarr([r[2] for r in RULES]))
# 0.1.14: old class names -> today's class index (the Shaman slot is the Monk); read by indexOf only
F(defs, "public static final String[] ALIAS_FROM = %s;" % jarr([a for a, _ in CLASS_ALIASES]))
F(defs, "public static final int[] ALIAS_TO = new int[] { %s };" % ", ".join(str([c["name"] for c in CLASSES].index(n)) for _, n in CLASS_ALIASES))
''')
rep('''    if (NAMES[i].equalsIgnoreCase(s) || SKILLS[i].equalsIgnoreCase(s) || (NAMES[i] + "s").equalsIgnoreCase(s)) return i;
  }
  return -1;
}""")''', '''    if (NAMES[i].equalsIgnoreCase(s) || SKILLS[i].equalsIgnoreCase(s) || (NAMES[i] + "s").equalsIgnoreCase(s)) return i;
  }
  for (int i = 0; i < ALIAS_FROM.length && i < ALIAS_TO.length; i++) {
    if (ALIAS_FROM[i].equalsIgnoreCase(s)) return ALIAS_TO[i];
  }
  return -1;
}""")''')

# ================================================================================================ fixer 2: kit.Shaman read-side fallback
# (second critic 1, LOW) An admin could have saved a NON-EMPTY Shaman kit (kit.Shaman was a visible Server Setup row and /classadmin kit
# took "shaman"). The Monk kit reads it while the file has no kit.Monk line: read side only, nothing rewritten, no field added (one INFO
# line per load). Empty / missing kit.Shaman (every default file) = the code default; a kit.Monk line (even empty) always wins.
rep('''public static String txt(java.util.Properties p, String k, String d) {
  String v = p.getProperty(k);
  return v == null ? d : v.trim();
}""")
''', '''public static String txt(java.util.Properties p, String k, String d) {
  String v = p.getProperty(k);
  return v == null ? d : v.trim();
}""")
# 0.1.14 (fixer 2): the Monk kit = kit.Monk; while that line is missing, a non-empty kit.Shaman (the old slot's row) is read instead
M(cfg, r"""
public static String kitMonk(java.util.Properties p, String d) {
  String v = p.getProperty("kit.Monk");
  if (v != null) return v.trim();
  String o = p.getProperty("kit.Shaman");
  if (o == null || o.trim().length() == 0) return d;
  info("kit.Monk: no kit.Monk line - using the old kit.Shaman line '" + o.trim() + "' as the Monk kit (file not changed; save the Monk kit in Server Setup to write kit.Monk)");
  return o.trim();
}""")
''')
rep('''    "__KITLOAD__": "\\n".join('    @PKG@.KitCfg.K_%s = txt(p, "kit.%s", %s);' % (c["name"].upper(), c["name"], jstr(c["kit"])) for c in CLASSES),''',
    '''    # 0.1.14 (fixer 2): the Monk row reads through kitMonk (the old kit.Shaman line while kit.Monk is missing)
    "__KITLOAD__": "\\n".join(('    @PKG@.KitCfg.K_%s = kitMonk(p, %s);' % (c["name"].upper(), jstr(c["kit"])) if c["name"] == "Monk" else
                              '    @PKG@.KitCfg.K_%s = txt(p, "kit.%s", %s);' % (c["name"].upper(), c["name"], jstr(c["kit"]))) for c in CLASSES),''')
assert s.count("kitMonk(p, ") == 1 and s.count("public static String kitMonk(") == 1

# ================================================================================================ texts
rep('''  super("class", "Open the class page - Archer, Warrior, Mage, Berserker, Priest (Assassin and Shaman later)");''',
    '''  super("class", "Open the class page - Archer, Warrior, Mage, Berserker, Priest, Assassin, Monk");''')
rep('''"SkyWynn classes (Wynncraft style): Archer, Warrior, Mage, Berserker, Priest (Assassin and Shaman later). Your class''',
    '''"SkyWynn classes: Archer, Warrior, Mage, Berserker, Priest, Assassin, Monk. Your class''')
# review fix (critic 3, LOW): the /classadmin kit argument help named Assassin + Shaman "for testing" - both are playable now, Shaman is an alias
rep('''  this.classArg = withRequiredArg("class", "archer | warrior | mage | berserker | priest (assassin, shaman for testing)", @ATY@.STRING);''',
    '''  this.classArg = withRequiredArg("class", "archer | warrior | mage | berserker | priest | assassin | monk", @ATY@.STRING);''')

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
assert [ln for ln in s.split(LF) if "registerSystem(" in ln] == SYS0, "system registrations changed"
_card2 = block(CARD_START, CARD_END) + CARD_END
assert _card2 == _card and hashlib.sha256(_card2.encode("utf8")).hexdigest() == CARD_SHA, "the SKYY CARD block must stay SkyyProfiles 0.1.4's"
# the Java part: only the alias lines, the two texts and the version may differ from 0.1.13
_jn = s[s.index(JAVA_FROM):]
import difflib
_d = [ln for ln in difflib.unified_diff(_java_old.split(LF), _jn.split(LF), lineterm="", n=0) if ln[:1] in "+-" and ln[:3] not in ("+++", "---")]
_ok = ("ALIAS_", "for (int i = 0; i < ALIAS_FROM.length", "if (ALIAS_FROM[i].equalsIgnoreCase(s))", "  }", "Open the class page",
       "SkyWynn classes", "# 0.1.14: old class names", "archer | warrior | mage | berserker | priest")
assert s.count("for testing\", @ATY@.STRING)") == 0 and s.count("priest | assassin | monk\", @ATY@.STRING)") == 1
assert all(any(x in ln for x in _ok) for ln in _d), "unplanned Java lines: %s" % [ln for ln in _d if not any(x in ln for x in _ok)]
assert 'VERSION = "0.1.14"' in s and ASSASSIN_DESC_NEW in s and MONK_DESC in s and ASSASSIN_DESC_OLD not in s and SHAMAN_DESC not in s
assert '"name": "Shaman"' not in s and '"skill": "Shaman skill"' not in s
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.13 had %d)" % (s.count(LF), OLD.count(LF)))

# ================================================================================================================ the harness (0.1.13's + 0.1.14)
TSRC = os.path.join(ROOT, "SkyyClasses", "test_skyyclasses_0.1.13.py")
TDST = os.path.join(ROOT, "SkyyClasses", "test_skyyclasses_0.1.14.py")
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('''"""Bare-JVM check for SkyyClasses 0.1.13 - GENERATED by tools/classes_0_1_13_patch.py from test_skyyclasses_0.1.12.py (edit the patch).''',
     '''"""Bare-JVM check for SkyyClasses 0.1.14 - GENERATED by tools/classes_0_1_14_patch.py from test_skyyclasses_0.1.13.py (edit the patch).
0.1.14 = ASSASSIN + MONK PLAYABLE (Skyy LOCKED 2026-10-07 "1. make the classes"): the Assassin is enabled, the Shaman slot is the Monk
(Discipline, #f08a30, Bo staffs + SkyyArmory Bo / fist weapons; "Shaman" = an alias). Changes to the 0.1.13 checks: B / D / E (the kit rows
kit.Assassin + kit.Monk are normal rows now; kit.Monk = Weapon_Staff_Bo_Wood:1), Q (a wand in the Monk kit asks), T (7 playable classes,
class:list, the Monk + Assassin weapon tables, owners, allowed, block texts, the aliases) and Y (0.1.13 vs 0.1.14: the 0.1.13 jar DRESSED
with the 0.1.14 class tables builds the IDENTICAL page in every state = the page code is unchanged and only the table changed; class bytes:
exactly the planned methods / fields). NEW part MG (migration safety, two starts + the 0.1.13 control on a scratch COPY of the live
players folder + synthetic Shaman cases).
Below: the 0.1.13 text.
Bare-JVM check for SkyyClasses 0.1.13 - GENERATED by tools/classes_0_1_13_patch.py from test_skyyclasses_0.1.12.py (edit the patch).''')
hrep('VERSION = "0.1.13"\nPKG = "com.skyy.classes."', 'VERSION = "0.1.14"\nPKG = "com.skyy.classes."')
hrep('os.path.join(TOOLS, "dev", "scratch", "classes0113", "run")', 'os.path.join(TOOLS, "dev", "scratch", "classes014", "run")')
# ---- B / D / E: the kit rows
hrep('''    ("kit.Assassin", "kits", "items", "Weapon_Daggers_Crude:1", "0", "9", "qty", "", "new,adv"),
    ("kit.Assassin.fromHotbar", "kits", "action", "", "", "", "Use my hotbar", "", "new,danger,adv"),
    ("kit.Shaman", "kits", "items", "", "0", "9", "qty", "", "new,adv"),
    ("kit.Shaman.fromHotbar", "kits", "action", "", "", "", "Use my hotbar", "", "new,danger,adv"),''',
     '''    ("kit.Assassin", "kits", "items", "Weapon_Daggers_Crude:1", "0", "9", "qty", "", "new"),             # 0.1.14: playable
    ("kit.Assassin.fromHotbar", "kits", "action", "", "", "", "Use my hotbar", "", "new,danger"),
    ("kit.Monk", "kits", "items", "Weapon_Staff_Bo_Wood:1", "0", "9", "qty", "", "new"),                  # 0.1.14: the Shaman slot
    ("kit.Monk.fromHotbar", "kits", "action", "", "", "", "Use my hotbar", "", "new,danger"),''')
hrep('''str(KitCfg.K_PRIEST) == "Weapon_Wand_Wood:1" and str(KitCfg.K_SHAMAN) == ""''',
     '''str(KitCfg.K_PRIEST) == "Weapon_Wand_Wood:1" and str(KitCfg.K_MONK) == "Weapon_Staff_Bo_Wood:1"''')
hrep('''    check((get("kits.enabled"), get("kit.Priest"), get("kit.Shaman"), get("priestHeal.sharePercent"), get("priestHeal.radius"),
           get("priestHeal.maxPerHit"), get("priestHeal.feedbackMs"), get("kit.Priest.fromHotbar"))
          == ("true", "Weapon_Wand_Wood:1", "", "25", "16", "10", "10000", ""), "initial gets of the new rows (a 0.1.5 file = defaults)")''',
     '''    check((get("kits.enabled"), get("kit.Priest"), get("kit.Monk"), get("priestHeal.sharePercent"), get("priestHeal.radius"),
           get("priestHeal.maxPerHit"), get("priestHeal.feedbackMs"), get("kit.Priest.fromHotbar"))
          == ("true", "Weapon_Wand_Wood:1", "Weapon_Staff_Bo_Wood:1", "25", "16", "10", "10000", ""), "initial gets of the new rows (a 0.1.5 file = defaults)")
    check(get("kit.Shaman") is None, "0.1.14: kit.Shaman is no row any more (kit.Monk replaced it)")''')
# ---- Q
hrep('''    check("is a Priest weapon - a Shaman" in str(KitHooks.checkKit("kit.Shaman", "Weapon_Wand_Wood:1")), "Shaman kit + wand asks")''',
     '''    check("is a Priest weapon - a Monk" in str(KitHooks.checkKit("kit.Monk", "Weapon_Wand_Wood:1")), "0.1.14: Monk kit + wand asks")
    check(KitHooks.checkKit("kit.Monk", "Weapon_Staff_Bo_Wood:1,Weapon_Fist_Wraps_Linen:1,Weapon_Bo_Iron:1") is None
          and "is a Monk weapon - a Mage" in str(KitHooks.checkKit("kit.Mage", "Weapon_Staff_Bo_Bamboo:1")),
          "0.1.14: the Monk kit takes Bo staffs + fist weapons; a Bo staff in the Mage kit asks: %s" % KitHooks.checkKit("kit.Mage", "Weapon_Staff_Bo_Bamboo:1"))''')
# ---- T: the roster
hrep('''    check(names16 == ["Archer", "Warrior", "Mage", "Berserker", "Priest", "Assassin", "Shaman"], "roster order %s" % names16)
    check([bool(x) for x in Defs.ENABLED] == [True, True, True, True, True, False, False], "playable: the five, Assassin + Shaman later")
    check(str(Defs.listText()) == "Archer:Archery,Warrior:Swordsmanship,Mage:Sorcery,Berserker:Fury,Priest:Divinity", "class:list %s" % Defs.listText())''',
     '''    check(names16 == ["Archer", "Warrior", "Mage", "Berserker", "Priest", "Assassin", "Monk"], "roster order %s (0.1.14: the Shaman slot = Monk)" % names16)
    check([bool(x) for x in Defs.ENABLED] == [True] * 7, "0.1.14: all seven playable")
    check(str(Defs.listText()) == "Archer:Archery,Warrior:Swordsmanship,Mage:Sorcery,Berserker:Fury,Priest:Divinity,Assassin:Assassination,Monk:Discipline",
          "class:list %s" % Defs.listText())
    check(str(Defs.choiceText()) == "Archer, Warrior, Mage, Berserker, Priest, Assassin or Monk" and "(later)" not in str(Defs.allText()),
          "0.1.14: choiceText / allText: %s | %s" % (Defs.choiceText(), Defs.allText()))''')
hrep('''    check(int(Defs.ARCHER) == AR, "ClassDefs.ARCHER")
    print("T. roster done")''', '''    check(int(Defs.ARCHER) == AR, "ClassDefs.ARCHER")
    # ---------------- T14 (0.1.14): Assassin + Monk playable, the weapon tables, the aliases
    AS_, MO_, MA_ = names16.index("Assassin"), names16.index("Monk"), names16.index("Mage")
    check(MO_ == 6 and AS_ == 5 and str(Defs.SKILLS[MO_]) == "Discipline" and str(Defs.COLORS[MO_]) == "#f08a30"
          and str(Defs.ROLES[MO_]) == "Self-speed disruptor" and str(Defs.ROLES[AS_]) == "Priority killer"
          and str(Defs.ICONS[MO_]) == "Weapon_Staff_Bo_Wood,Weapon_Staff_Bo_Bamboo" and str(Defs.WTEXT[MO_]) == "Bo Staves / Wraps / Gauntlets",
          "T14: the Monk row (index 6 = the old Shaman slot): %s %s %s" % (Defs.SKILLS[MO_], Defs.COLORS[MO_], Defs.ICONS[MO_]))
    check(set(str(Defs.prefixesOf(MO_)).split(",")) == {"Weapon_Staff_Bo_", "Weapon_Bo_", "Weapon_Fist_"}
          and set(str(Defs.prefixesOf(AS_)).split(",")) == {"Weapon_Daggers_", "Weapon_Kunai"}
          and set(str(Defs.prefixesOf(MA_)).split(",")) == {"Weapon_Staff_", "Halloween_Broomstick", "Weapon_Spellbook_"},
          "T14: class:weapons:Monk / Assassin / Mage: %s / %s / %s" % (Defs.prefixesOf(MO_), Defs.prefixesOf(AS_), Defs.prefixesOf(MA_)))
    MONK14 = ["Weapon_Staff_Bo_Bamboo", "Weapon_Staff_Bo_Wood"] + ["Weapon_Bo_%s" % m_ for m_ in ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite",
             "Mithril", "Onyxium")] + ["Weapon_Fist_Gauntlets_%s" % m_ for m_ in ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril",
             "Onyxium")] + ["Weapon_Fist_Wraps_%s" % c_ for c_ in ("Linen", "Cotton", "Silk", "Cindercloth", "Shadoweave")]
    STAVES14 = ["Weapon_Staff_%s" % m_ for m_ in ("Adamantite", "Bone", "Bronze", "Cane", "Cobalt", "Copper", "Crystal_Fire_Trork", "Crystal_Flame",
                "Crystal_Ice", "Crystal_Purple", "Crystal_Red", "Doomed", "Frost", "Iron", "Mithril", "Onion", "Onyxium", "Thorium", "Wizard", "Wood",
                "Wood_Kweebec", "Wood_Rotten")]
    DAG14 = ["Weapon_Daggers_%s" % m_ for m_ in ("Adamantite", "Adamantite_Saurian", "Bone", "Bronze", "Bronze_Ancient", "Claw_Bone", "Cobalt",
             "Copper", "Crude", "Doomed", "Fang_Doomed", "Iron", "Mithril", "Onyxium", "Stone_Trork", "Thorium")]
    check(all(int(Defs.ownerOf(i_)) == MO_ for i_ in MONK14) and all(int(Defs.ownerOf(i_)) == MA_ for i_ in STAVES14)
          and all(int(Defs.ownerOf(i_)) == AS_ for i_ in DAG14 + KUNAI13) and int(Defs.ownerOf("Weapon_Claws_Tribal")) == -2,
          "T14: owners - 21 Monk ids, 22 staves stay Mage, 16 daggers + 9 kunai Assassin, claws unassigned: %s" % [
              (i_, int(Defs.ownerOf(i_))) for i_ in MONK14 + STAVES14 + DAG14 if int(Defs.ownerOf(i_)) not in (MO_, MA_, AS_)][:4])
    umo, uas = UUID.fromString("00000000-0000-0000-0000-000000000114"), UUID.fromString("00000000-0000-0000-0000-000000000115")
    Store.setClassKey(str(umo), MO_, True, False)
    Store.setClassKey(str(uas), AS_, True, False)
    check(all(bool(Rules.allowed(umo, i_)) and not bool(Rules.allowed(um13, i_)) and not bool(Rules.allowed(uas, i_)) for i_ in MONK14)
          and all(bool(Rules.allowed(uas, i_)) and not bool(Rules.allowed(umo, i_)) for i_ in DAG14 + KUNAI13)
          and all(bool(Rules.allowed(um13, i_)) and not bool(Rules.allowed(umo, i_)) for i_ in STAVES14)
          and bool(Rules.allowed(umo, "Weapon_Shield_Wood")) and bool(Rules.allowed(uas, "Tool_Hatchet_Iron")),
          "T14: allowed() - a Monk may use every Monk weapon and no Mage staff / dagger / kunai; an Assassin its daggers + kunai only; a Mage "
          "keeps every staff but the Bo staffs; shields + hatchets stay free")
    check(not bool(Rules.allowed(umo, "Weapon_Claws_Tribal")) and not bool(Rules.allowed(uas, "Weapon_Claws_Tribal")),
          "T14: the unowned claws stay blocked for classed players (Block weapons no class owns is unchanged)")
    t1_, t2_, t3_ = (str(Rules.blockText(um13, "Weapon_Staff_Bo_Wood", False)), str(Rules.blockText(um13, "Weapon_Fist_Wraps_Linen", False)),
                     str(Rules.blockText(umo, "Weapon_Daggers_Iron", False)))
    check(t1_ == "Only Monks can use bo staves. You are a Mage - /class shows your weapons."
          and t2_ == "Only Monks can use fist weapons. You are a Mage - /class shows your weapons."
          and t3_ == "Only Assassins can use daggers. You are a Monk - /class shows your weapons.", "T14: block texts: %s | %s | %s" % (t1_, t2_, t3_))
    check(all(int(Defs.indexOf(a_)) == MO_ for a_ in ("Shaman", "shaman", "SHAMANS", "Shaman skill", " shaman ", "Monk", "monks", "Discipline"))
          and int(Defs.indexOf("Assassination")) == AS_ and int(Defs.indexOf("sham")) == -1 and int(Defs.indexOf("Shaman skills")) == -1,
          "T14: indexOf - Shaman / Shamans / Shaman skill (any case) = the Monk; Monk, Monks, Discipline; no prefix guessing")
    check([str(x) for x in Defs.ALIAS_FROM] == ["Shaman", "Shamans", "Shaman skill"] and [int(x) for x in Defs.ALIAS_TO] == [MO_] * 3,
          "T14: the alias table")
    print("T. roster done (0.1.14: 7 playable, Monk + Assassin weapons, aliases)")''')
# ---- Y: the states (the Shaman state is the Monk state now) + the dressed 0.1.13 jar
hrep('''    ("all enabled shaman", "Shaman", "Warrior", "", None, 50, {"Assassin": True, "Shaman": True}),''',
     '''    ("all enabled monk", "Monk", "Warrior", "", None, 50, {"Assassin": True, "Monk": True}),          # 0.1.14: the Shaman slot''')
hrep('''def run_states(jar, out, tag):
    from jpype import JClass, JImplements, JOverride
    _jvm_start([jar])''', '''DRESS = ("NAMES", "SKILLS", "DESCS", "COLORS", "WTEXT", "ROLES", "ICONS", "ENABLED")   # 0.1.14: the ClassDefs class tables


def run_states(jar, out, tag):
    from jpype import JClass, JImplements, JOverride
    _jvm_start([jar])
    dress = arg("--dress")''')
hrep('''    enabled0 = [bool(x) for x in Defs.ENABLED]
    names_ = [str(x) for x in Defs.NAMES]''', '''    # 0.1.14: the new jar records its class tables; the old jar (--dress) is DRESSED with them (same lengths, element by element) before
    # any state is built - an identical page then proves the page code did not change, only the table did
    res["tables"] = dict((k, [bool(x) if k == "ENABLED" else str(x) for x in getattr(Defs, k)]) for k in DRESS)
    if dress:
        dt = json.load(open(dress))["tables"]
        for k in DRESS:
            arr = getattr(Defs, k)
            assert len(arr) == len(dt[k]), (k, len(arr), len(dt[k]))
            for i, v in enumerate(dt[k]):
                arr[i] = v
        res["dressed"] = dict((k, [bool(x) if k == "ENABLED" else str(x) for x in getattr(Defs, k)]) for k in DRESS)
    enabled0 = [bool(x) for x in Defs.ENABLED]
    names_ = [str(x) for x in Defs.NAMES]''')
hrep('''OLD_VERSION = "0.1.12"''', '''OLD_VERSION = "0.1.13"''')
_y_old = ts[ts.index("EXPECTED_DIFF = {"):ts.index("SCRIPT = os.path.join(HERE")]
hrep(_y_old, '''EXPECTED_DIFF = {"com/skyy/classes/ClassDefs.class", "com/skyy/classes/KitCfg.class", "com/skyy/classes/KitHooks.class",
                 "com/skyy/classes/CfgRows.class", "com/skyy/classes/ClassCfg.class", "com/skyy/classes/ClassCmd.class", "manifest.json",
                 "com/skyy/classes/AdminKitClassCmd.class"}     # review fix: the /classadmin kit <class> argument help
VERSION_ONLY = {"com/skyy/classes/SkyyClassesPlugin.class", "com/skyy/classes/CfgFn.class", "com/skyy/classes/KitMigrate.class"}
EXPECTED_DIFF |= VERSION_ONLY
# 0.1.14: the planned method / field changes per class (bytecode child): (changed, new, gone, fields_new, fields_gone)
PLAN14 = {
    "ClassDefs": (["<clinit>()V", "indexOf(Ljava/lang/String;)I"], [], [], ["ALIAS_FROM [Ljava/lang/String;", "ALIAS_TO [I"], []),
    "KitCfg": (["<clinit>()V", "textOf(I)Ljava/lang/String;"], [], [], ["K_MONK Ljava/lang/String;"], ["K_SHAMAN Ljava/lang/String;"]),
    "KitHooks": ([], ["hbMonk(Ljava/util/UUID;Ljava/lang/String;)[Ljava/lang/Object;"], ["hbShaman(Ljava/util/UUID;Ljava/lang/String;)[Ljava/lang/Object;"], [], []),
    "CfgRows": (["<clinit>()V", "header()[Ljava/lang/Object;"], [], [], [], []),     # the rows + the version in the kit header
    "ClassCmd": (["ClassCmd()V"], [], [], [], []),                                    # the /class description
    "AdminKitClassCmd": (["AdminKitClassCmd()V"], [], [], [], []),                    # review fix: the <class> argument help
}
ASSASSIN_DESC_NEW = %r
MONK_DESC = %r
DESCS = []
PAGE_MAP = {}       # 0.1.14: the old jar is dressed with the new tables - nothing to map back


def page_back(text):
    return text


''' % (ASSASSIN_DESC_NEW, MONK_DESC))
hrep('''        p = subprocess.run([sys.executable, me, "--states", j, "--out", outs[tag], "--tag", tag, "--dir", SCRATCH], env=env)''',
     '''        p = subprocess.run([sys.executable, me, "--states", j, "--out", outs[tag], "--tag", tag, "--dir", SCRATCH]
                           + (["--dress", outs["new"]] if tag == "old" else []), env=env)   # 0.1.14: the old jar wears the new tables''')
hrep('''    new, old = json.load(open(outs["new"])), json.load(open(outs["old"]))''',
     '''    new, old = json.load(open(outs["new"])), json.load(open(outs["old"]))
    check(old.get("dressed") == new.get("tables") and new["tables"]["NAMES"][6] == "Monk" and new["tables"]["ENABLED"] == [True] * 7,
          "Y-D: the 0.1.13 jar was dressed with the 0.1.14 class tables (names, skills, texts, colours, weapon texts, roles, icons, playable)")''')
hrep('''              "Y-B %s: the 0.1.13 page = the 0.1.12 page (commands, bindings) but for the Mage + Priest card texts, weapon texts and icons (%d / %d x)"
              % (nm, nj_.count(MAGE_DESC_NEW), nj_.count(PRIEST_DESC_NEW)))
        extra["desc"] += 1 if (nj_.count(MAGE_DESC_NEW) and nj_.count(PRIEST_DESC_NEW)) else 0''',
     '''              "Y-B %s: the 0.1.14 page = the DRESSED 0.1.13 page, command for command and binding for binding (Assassin %d x, Monk %d x)"
              % (nm, nj_.count(ASSASSIN_DESC_NEW), nj_.count(MONK_DESC)))
        extra["desc"] += 1 if (nj_.count(ASSASSIN_DESC_NEW) and nj_.count(MONK_DESC)) else 0''')
hrep('''        got = compare_state(nm, os_, ns_, SUI, counts, data_colors, PAGE_W, PAGE_H, BODY_ID, BODY_INNER_H,
                            {"text_ok": lambda t_: page_back(t_) != t_ or any(v_ in t_ for v_ in PAGE_MAP.values())})''',
     '''        got = compare_state(nm, os_, ns_, SUI, counts, data_colors, PAGE_W, PAGE_H, BODY_ID, BODY_INNER_H)''')
hrep('''    check(extra["desc"] > 0, "Y-B: the new Mage + Priest card texts are on the page (%d states) and fit their cards (the text checks above)" % extra["desc"])
    print("Y-B/G/H. %(identical)d states identical in 0.1.12 and 0.1.13 but for the Mage + Priest card strings (%(desc)d states show it); still: %(cards)d cards "''',
     '''    check(extra["desc"] > 0, "Y-B: the Assassin + Monk card texts are on the page (%d states) and fit their cards (the text / contrast checks above)" % extra["desc"])
    print("Y-B/G/H. %(identical)d states identical in 0.1.14 and the dressed 0.1.13 (%(desc)d states show the Assassin + Monk cards); still: %(cards)d cards "''')
hrep('''"E: classes_0_1_13_patch.py asserts SkyyProfiles 0.1.4's CARD_SHA "''', '''"E: classes_0_1_14_patch.py asserts SkyyProfiles 0.1.4's CARD_SHA "''')
hrep('PATCH_NEW = os.path.join(TOOLS, "classes_0_1_13_patch.py")      # 0.1.13 keeps the block (asserts its CARD_SHA, never redefines it)',
     'PATCH_NEW = os.path.join(TOOLS, "classes_0_1_14_patch.py")      # 0.1.14 keeps the block (asserts its CARD_SHA, never redefines it)')
hrep('''    NEW_ENTRIES = set()          # 0.1.13: no new class
    check(set(zn.namelist()) - set(zo.namelist()) == NEW_ENTRIES and not set(zo.namelist()) - set(zn.namelist()),
          "Y-F: the 0.1.13 jar = the 0.1.12 entries: +%s -%s" % (''', '''    NEW_ENTRIES = set()          # 0.1.14: no new class
    check(set(zn.namelist()) - set(zo.namelist()) == NEW_ENTRIES and not set(zo.namelist()) - set(zn.namelist()),
          "Y-F: the 0.1.14 jar = the 0.1.13 entries: +%s -%s" % (''')
hrep('''        check("com/skyy/classes/%s.class" % _n not in diff, "Y-F: %s.class is byte-identical to 0.1.12's" % _n)''',
     '''        check("com/skyy/classes/%s.class" % _n not in diff, "Y-F: %s.class is byte-identical to 0.1.13's" % _n)''')
_yf_old = ts[ts.index('''    # 0.1.13: every changed class but ClassDefs differs only in the version text'''):ts.index('''    print("Y-F. class bytes: %d entries identical, differ: %s; methods: %s" % (''')]
hrep(_yf_old, '''    # 0.1.14: the version-only classes, then exactly the planned methods / fields (+ ClassCfg: the default file text and the kit load)
    for n_ in sorted(VERSION_ONLY):
        c = cls(n_.split("/")[-1][:-6])
        check(c and not c.get("new") and not c.get("gone") and c.get("fields_same") and c.get("version_only"),
              "Y-F: %s: only the version string differs: %s" % (n_.split("/")[-1], summ(c)))
    for cn_, (ch_, nw_, gn_, fnw_, fgn_) in sorted(PLAN14.items()):
        c = cls(cn_)
        check(c and sorted(c.get("changed", [])) == sorted(ch_) and c.get("new") == nw_ and c.get("gone") == gn_
              and c.get("fields_new") == fnw_ and c.get("fields_gone") == fgn_, "Y-F: %s changes exactly %s: %s" % (cn_, (ch_, nw_, gn_, fnw_, fgn_), summ(c)))
    # review fix (critic 3): AdminKitClassCmd's constructor changed ONLY the <class> argument help string (all seven, monk not shaman)
    _ko, _kn = ldiff("com/skyy/classes/AdminKitClassCmd.class", "AdminKitClassCmd()V") if "AdminKitClassCmd()V" in cls("AdminKitClassCmd").get("changed", []) else ([], [])
    check(_ko == ['ldc "archer | warrior | mage | berserker | priest (assassin, shaman for testing)"']
          and _kn == ['ldc "archer | warrior | mage | berserker | priest | assassin | monk"'],
          "Y-F: AdminKitClassCmd(): only the class argument help changed (no 'for testing', monk not shaman): -%s +%s" % (_ko, _kn))
    cc_ = cls("ClassCfg")
    # fixer 2: + ClassCfg.kitMonk (the kit.Shaman read-side fallback) - one new method, no field
    check(cc_ and cc_.get("new") == ["kitMonk(Ljava/util/Properties;Ljava/lang/String;)Ljava/lang/String;"] and not cc_.get("gone")
          and cc_.get("fields_same") and set(cc_.get("changed", [])) <= {"<clinit>()V", "load()Ljava/lang/String;"},
          "Y-F: ClassCfg: only the default file text + the kit load (kit.Shaman -> kit.Monk via the new kitMonk): %s" % summ(cc_))
    for meth_ in cc_.get("changed", []):
        o_, n_ = ldiff("com/skyy/classes/ClassCfg.class", meth_)
        if meth_ == "load()Ljava/lang/String;":
            # the Shaman row's txt(p, "kit.Shaman", "") became kitMonk(p, "Weapon_Staff_Bo_Wood:1") - nothing else in load() moved
            so_ = [x for x in o_ if not ("Shaman" in x or "SHAMAN" in x or x == 'ldc ""' or "ClassCfg.txt(" in x)]
            sn_ = [x for x in n_ if not ("MONK" in x or "Staff_Bo" in x or "ClassCfg.kitMonk(" in x)]
            check(not so_ and not sn_ and len(o_) == 4 and len(n_) == 3 and any("ClassCfg.kitMonk(" in x for x in n_)
                  and any("ClassCfg.txt(" in x for x in o_),
                  "Y-F: ClassCfg.load(): only the Shaman kit read became the kitMonk read: -%s +%s" % (o_, n_))
            continue
        so_ = [x for x in o_ if "Shaman" not in x and "SHAMAN" not in x and x != 'ldc ""']
        sn_ = [x for x in n_ if "Monk" not in x and "MONK" not in x and "Staff_Bo" not in x]
        check(not so_ and not sn_ and len(o_) == len(n_),
              "Y-F: ClassCfg.%s: only the kit.Shaman strings became kit.Monk strings: -%s +%s" % (meth_, o_[:4], n_[:4]))
    cd_ = cls("ClassDefs")
    if "<clinit>()V" in cd_.get("changed", []):
        o_, n_ = ldiff("com/skyy/classes/ClassDefs.class", "<clinit>()V")
        lo_ = set(x.split(" ", 1)[1] for x in o_ if x.startswith("ldc"))
        ln2 = set(x.split(" ", 1)[1] for x in n_ if x.startswith("ldc"))
        old_ok = set('"%s"' % x for x in ("Shaman", "Shaman skill", "Designed later", "Fast burst damage", "#ff7a5c", "Custom weapon later",
                                          "Weapon_Deployable_Slowness_Totem", "Coming later. Fast and deadly with twin daggers and kunai throwing knives.",
                                          "Coming later. The fifth Wynncraft class - it gets its own custom weapon."))
        check(lo_ - ln2 <= old_ok and '"Monk"' in ln2 and '"Discipline"' in ln2 and '"#f08a30"' in ln2,
              "Y-F: ClassDefs.<clinit>: the strings that left are only the Shaman / old Assassin ones: %s" % sorted(lo_ - ln2 - old_ok))
''')
hrep('''    p15, p16 = props_of(text15), props_of(text16)
''', '''    p15, p16 = props_of(text15), props_of(text16)
    # 0.1.14: the empty Shaman kit line of the edited 0.1.6 file is the Monk kit line now - same place (after kit.Assassin), the Bo staff kit
    _k16_ = list(p16)
    check(p15.get("kit.Shaman") == "" and "kit.Shaman" not in p16 and p16.get("kit.Monk") == "Weapon_Staff_Bo_Wood:1"
          and _k16_[_k16_.index("kit.Monk") - 1] == "kit.Assassin", "0.1.14: kit.Shaman= -> kit.Monk=Weapon_Staff_Bo_Wood:1 in the default file")
    p15 = dict((("kit.Monk", "Weapon_Staff_Bo_Wood:1") if k == "kit.Shaman" else (k, v)) for k, v in p15.items())
''')
hrep('''"Weapon_Battleaxe_Crude:1", "Weapon_Wand_Wood:1", "Weapon_Daggers_Crude:1", ""]''',
     '''"Weapon_Battleaxe_Crude:1", "Weapon_Wand_Wood:1", "Weapon_Daggers_Crude:1", "Weapon_Staff_Bo_Wood:1"]''')
# fixer 2 (second critic 1): the kit.Shaman read-side fallback through the REAL ClassCfg.load(), each file loaded twice, bytes unchanged
hrep('''    Cfg.FILE = Paths.get(fresh)
    Cfg.load()
    check(str(Cfg.summary()) == DEF16, "back to the defaults")''', '''    # 0.1.14 (fixer 2): kit.Shaman -> the Monk kit only while kit.Monk is missing and kit.Shaman is not empty; read side only
    _kc_ = [("kit.Shaman=Weapon_Bo_Iron:1,Weapon_Fist_Wraps_Linen:1\\n", "Weapon_Bo_Iron:1,Weapon_Fist_Wraps_Linen:1", "a saved Shaman kit, no kit.Monk"),
            ("kit.Shaman=\\n", "Weapon_Staff_Bo_Wood:1", "the old default empty kit.Shaman= line"),
            ("kit.Shaman=   \\n", "Weapon_Staff_Bo_Wood:1", "a blank kit.Shaman line"),
            ("kit.Shaman=Weapon_Bo_Iron:1\\nkit.Monk=Weapon_Fist_Wraps_Linen:1\\n", "Weapon_Fist_Wraps_Linen:1", "kit.Monk wins over kit.Shaman"),
            ("kit.Monk=\\nkit.Shaman=Weapon_Bo_Iron:1\\n", "", "an emptied kit.Monk line wins (the admin's empty Monk kit)"),
            ("kit.Monk=  Weapon_Bo_Iron:2  \\n", "Weapon_Bo_Iron:2", "kit.Monk alone, trimmed")]
    for body_, want_, what_ in _kc_:
        open(typed, "w", newline="\\n").write("kit.Assassin=Weapon_Kunai:3\\n" + body_)
        before_ = open(typed, "rb").read()
        Cfg.FILE = Paths.get(typed)
        Cfg.load()
        first_ = str(KitCfg.K_MONK)
        Cfg.load()
        check(first_ == want_ and str(KitCfg.K_MONK) == want_ and open(typed, "rb").read() == before_
              and str(KitCfg.K_ASSASSIN) == "Weapon_Kunai:3" and str(KitCfg.K_PRIEST) == "Weapon_Wand_Wood:1",
              "0.1.14 kit.Shaman fallback: %s -> K_MONK %r twice (want %r), file bytes unchanged, other kits untouched" % (what_, first_, want_))
    Cfg.FILE = Paths.get(fresh)
    Cfg.load()
    check(str(Cfg.summary()) == DEF16, "back to the defaults")''')
# ---- the new part MG (migration safety) - child + parent; main() runs it
MG_PART = r'''# ============================================================================================================== part MG (0.1.14)
# MIGRATION SAFETY: the Shaman -> Monk rename on a scratch COPY of the live players folder + synthetic cases. Each start = its own child JVM
# (-Xverify:all): every live file is read through the real ClassStore.loadKey (class kept, nothing written); a class=Shaman file reads as the
# Monk without being rewritten; a profile whose SkyyProfiles class is still "Shaman" publishes class:<uuid> = Monk / class:skill = Discipline
# and (steady snapshot, the 0.1.3 rule) writes class=Monk into ITS profile file once; the second start writes nothing. The 0.1.13 jar on an
# identical copy is the control (it publishes Shaman / Shaman skill and never writes the disabled class).
MG_SHAMAN_FILE = "00000000-0000-0000-0000-0000000005a1"          # a hand-written class=Shaman file (no SkyyProfiles)
MG_PROFILE_U = "00000000-0000-0000-0000-0000000005a2"            # a profile set to Shaman with /profileadmin setclass
MG_PROFILE_K = MG_PROFILE_U + "-p2"


def run_mg(jar, home, step):
    from jpype import JClass, JImplements, JOverride
    _jvm_start([jar])
    Store, Cfg, Defs = JClass(PKG + "ClassStore"), JClass(PKG + "ClassCfg"), JClass(PKG + "ClassDefs")
    UUID, Paths, Long = JClass("java.util.UUID"), JClass("java.nio.file.Paths"), JClass("java.lang.Long")
    pdir = os.path.join(home, "players")
    Store.DIR = Paths.get(pdir)
    out = {"step": step, "files": {}}
    br = Cfg.bridge()
    for fn in sorted(os.listdir(pdir)):
        if not fn.endswith(".properties"):
            continue
        k = fn[:-len(".properties")]
        Store.loadKey(k)
        out["files"][k] = [None if Store.CLS.get(k) is None else str(Store.CLS.get(k)), int(Store.fileIndex(k))]
        if len(k) == 36:                       # profile 1 / no SkyyProfiles: the tick publishes from the file
            Store.check(UUID.fromString(k))
            out["files"][k].append([None if br.get("class:" + k) is None else str(br.get("class:" + k)),
                                    None if br.get("class:skill:" + k) is None else str(br.get("class:skill:" + k))])

    @JImplements("java.util.function.Function")
    class KeyFn(object):
        @JOverride
        def apply(self, o):
            return MG_PROFILE_K if str(o) == MG_PROFILE_U else str(o)

    u = UUID.fromString(MG_PROFILE_U)
    br.put("profile:fn:key", KeyFn())
    br.put("profile:" + MG_PROFILE_U, "2")
    br.put("profile:key:" + MG_PROFILE_U, MG_PROFILE_K)
    br.put("profile:class:" + MG_PROFILE_U, "Shaman")
    br.put("profile:epoch:" + MG_PROFILE_U, Long(7))
    Store.check(u)
    out["prof_first"] = [str(br.get("class:" + MG_PROFILE_U)), str(br.get("class:skill:" + MG_PROFILE_U)), int(Store.profileIndex(u)),
                         bool(Store.locked(u))]
    time.sleep(1.7)                            # SYNC_STEADY_MS 1500: the same snapshot again -> the steady file sync may run
    Store.check(u)
    out["prof_steady"] = [str(br.get("class:" + MG_PROFILE_U)), str(br.get("class:skill:" + MG_PROFILE_U)), int(Store.fileIndex(MG_PROFILE_K))]
    json.dump(out, open(os.path.join(home, "mg-%s.json" % step), "w"), indent=1)


def part_mg(env):
    me = os.path.abspath(__file__)
    live_players = os.path.join(LIVE, "players")

    def snap(d):
        return dict((f, hashlib.sha256(open(os.path.join(d, f), "rb").read()).hexdigest()) for f in sorted(os.listdir(d)) if f.endswith(".properties"))
    homes = {}
    for tag in ("new", "old"):
        h = os.path.join(SCRATCH, "mg-" + tag)
        shutil.rmtree(h, ignore_errors=True)
        if os.path.isdir(live_players):
            shutil.copytree(live_players, os.path.join(h, "players"))
        else:
            os.makedirs(os.path.join(h, "players"))
        open(os.path.join(h, "players", MG_SHAMAN_FILE + ".properties"), "w").write("class=Shaman\nplayed=Shaman\nprompted=1\n")
        open(os.path.join(h, "players", MG_PROFILE_K + ".properties"), "w").write("prompted=1\n")
        homes[tag] = h
    live_before = snap(live_players) if os.path.isdir(live_players) else {}
    nlive = len(live_before)
    h = homes["new"]
    s0 = snap(os.path.join(h, "players"))
    res = {}
    for step, jar_, hh in (("1", JAR, h), ("2", JAR, h), ("old", OLD_JAR, homes["old"])):
        p = subprocess.run([sys.executable, me, "--mg", jar_, "--home", hh, "--step", step, "--dir", SCRATCH], env=env)
        j = os.path.join(hh, "mg-%s.json" % step)
        check(p.returncode == 0 and os.path.isfile(j), "MG: the %s start's child JVM ran" % step)
        res[step] = json.load(open(j)) if os.path.isfile(j) else {}
        res[step + "_snap"] = snap(os.path.join(hh, "players"))
    if not all(res.get(k) for k in ("1", "2", "old")):
        return
    r1, r2, ro = res["1"], res["2"], res["old"]
    live_keys = [k[:-len(".properties")] for k in live_before]
    changed1 = sorted(f for f in s0 if res["1_snap"].get(f) != s0[f])
    check(changed1 == [MG_PROFILE_K + ".properties"], "MG1: start 1 wrote ONLY the Shaman profile's file (the steady sync): %s" % changed1)
    check(all(r1["files"][k] == ro["files"][k] for k in live_keys)
          and all(r1["files"][k][0] in ("Archer", "Warrior", "Mage", "Berserker", "Priest", None) for k in live_keys),
          "MG1: the %d live player files read the same class in 0.1.14 as in 0.1.13: %s" % (
              nlive, dict((k, (r1["files"][k], ro["files"][k])) for k in live_keys if r1["files"][k] != ro["files"][k])))
    check(r1["files"][MG_SHAMAN_FILE][:2] == ["Monk", 6] and r1["files"][MG_SHAMAN_FILE][2] == ["Monk", "Discipline"]
          and ro["files"][MG_SHAMAN_FILE][:2] == ["Shaman", 6] and ro["files"][MG_SHAMAN_FILE][2] == ["Shaman", "Shaman skill"],
          "MG1: a class=Shaman file = the Monk (class:<uuid> Monk, class:skill Discipline; 0.1.13 said Shaman / Shaman skill) and is NOT rewritten: %s / %s"
          % (r1["files"][MG_SHAMAN_FILE], ro["files"][MG_SHAMAN_FILE]))
    check(r1["prof_first"] == ["Monk", "Discipline", 6, True] and r1["prof_steady"] == ["Monk", "Discipline", 6]
          and ro["prof_first"] == ["Shaman", "Shaman skill", 6, True] and ro["prof_steady"][2] == -1,
          "MG1: profile:class = Shaman -> class:<uuid> Monk / Discipline, locked; after the steady snapshot its profile file says Monk "
          "(0.1.13: Shaman, never written): %s %s | old %s %s" % (r1["prof_first"], r1["prof_steady"], ro["prof_first"], ro["prof_steady"]))
    pf = props_of(open(os.path.join(h, "players", MG_PROFILE_K + ".properties")).read())
    check(pf.get("class") == "Monk" and pf.get("played") == "Monk" and pf.get("prompted") == "1" and "kit" not in pf,
          "MG1: the profile file = class=Monk, played=Monk, the old keys kept, NO kit state (setclass is a fix, not a pick): %s" % pf)
    want2 = dict(r1["files"])
    want2[MG_PROFILE_K] = ["Monk", 6]
    check(res["2_snap"] == res["1_snap"] and r2["files"] == want2 and r2["prof_first"] == r1["prof_first"],
          "MG2: start 2 writes nothing and reads the same (the profile file now carries Monk): %s" % sorted(
              f for f in res["1_snap"] if res["2_snap"].get(f) != res["1_snap"][f]))
    check(sorted(f for f in s0 if res["old_snap"].get(f) != s0[f]) == [], "MG-old: the 0.1.13 jar writes nothing either (control)")
    live_after = snap(live_players) if os.path.isdir(live_players) else {}
    check(live_after == live_before, "MG: the live players folder was only read")
    print("MG. migration safety on a copy of %d live player files + 2 Shaman cases: start 1 = only the Shaman profile's file gets class=Monk "
          "(steady sync), every live class read unchanged, class=Shaman file = Monk unrewritten; start 2 = no write; 0.1.13 control = Shaman, no write"
          % nlive)


'''
hrep('''# ============================================================================================================== child: parts Z + M (0.1.10)''',
     MG_PART + '''# ============================================================================================================== child: parts Z + M (0.1.10)''')
hrep('''    if "--audit" in sys.argv:
        run_audit(arg("--audit"), arg("--out"))
        return''', '''    if "--audit" in sys.argv:
        run_audit(arg("--audit"), arg("--out"))
        return
    if "--mg" in sys.argv:
        run_mg(arg("--mg"), arg("--home"), arg("--step"))
        return''')
hrep('''    part_y(env)
    if not KEEP:''', '''    part_y(env)
    part_mg(env)          # 0.1.14: migration safety (Shaman -> Monk)
    if not KEEP:''')
tout = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(tout)
print("wrote %s (%d lines)" % (os.path.relpath(TDST, ROOT), tout.count(TNL) + 1))
