"""Derive SkyyClasses/build_skyyclasses_0.1.13.py from the CURRENT generated 0.1.12 (build_skyyclasses_0.1.12.py = the tools/deploy_set.py
SET pin) + its harness SkyyClasses/test_skyyclasses_0.1.13.py from test_skyyclasses_0.1.12.py.
Run:  python tools/classes_0_1_13_patch.py   then   python SkyyClasses/build_skyyclasses_0.1.13.py   then
      python SkyyClasses/test_skyyclasses_0.1.13.py      (never --deploy: coordinated deploy with SkyyArmory 0.1.6)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_12_patch.py
-> the generated 0.1.12 read here; tools/classes_0_1_6_patch.py is NEVER re-run. Edit THIS file, never the generated build script.

0.1.13 = SPELLBOOKS ARE MAGE WEAPONS (Skyy LOCKED docs/answered/classes.md 2026-10-04: "mage can have the spell book" -> Mage = staffs +
SPELLBOOKS; Priest = wands + SOUL ORB; docs/answered/gear.md LOCKED 2026-10-07 SPELLBOOKS + KUNAI: research/cloud/Spellbook-Ladder.md
section 7 "books Mage-only, Priest keeps wand + Soul Orb"; SkyyArmory 0.1.6 ships the Copper ... Onyxium spellbooks):
  - The weapon rule ("Weapon_Spellbook_", "spellbooks") moves from the Priest row to the Mage row (the spec's "C:254 Priest prefix"). Every
    user of the rule follows it: ClassRules.allowed / the hit-block popup, PriestHealSys (a spellbook hit never heals - ownerOf != PRIEST),
    kit checks, class:weapons:Mage / class:weapons:Priest on the bridge (SkyySkills' combat XP, SkyyGear's class gate). Priest keeps the
    wands + the Healing Totem (the Soul Orb is a later item).
  - Card texts (UI text rule: no , : ; { } quote underscore): Mage "Spellcaster. Staves and spellbooks cast magic at range. Hold a staff to
    blink - hold a spellbook to levitate."; Priest "AoE healer and support. Wand hits on monsters heal your party. Hold to hop back and
    burst - the glow heals your party most."; weapon texts "Staves / Spellbooks" and "Wands / Healing Totem"; card icons: Mage shows a
    spellbook (Grimoire) in the Crystal staff's place, Priest the Tribal + Rotten wands in the two spellbooks' places (icons must be the
    class's own weapons - asserted by the build).
  - KUNAI (research/cloud/Kunai-Ladder.md section 8: Weapon_Kunai_* = Assassin): ALREADY TRUE - the Assassin row's prefix "Weapon_Kunai"
    catches every Weapon_Kunai_<Metal> (asserted below); Assassin stays 'coming later' (disabled: its weapons follow unassignedBlocked).
  Nothing else changes: no row, no key, no data, no migration, no command / system. Rolling back to 0.1.12 = spellbooks are Priest weapons
  again (a Mage holding one is blocked by the popup; nothing is lost).
"""
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.12.py")
dst = os.path.join(ROOT, "SkyyClasses", "build_skyyclasses_0.1.13.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1.12"' in s and "GENERATED by tools/classes_0_1_12_patch.py from the generated 0.1.11" in s, \
    "build_skyyclasses_0.1.12.py is not the generated 0.1.12"
assert "DEF_HEAL_MSG_MS = 10000   # LOCKED Skyy 2026-09-25" in s and "DEF_HEAL_SELF_PCT = 100 " in s, "0.1.12 is not the edited-lineage script"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
SYS0 = [ln for ln in s.split(LF) if "registerSystem(" in ln]


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def block(a, b, text=None):
    t = s if text is None else text
    assert t.count(a) == 1 and t.count(b) == 1, (a[:60], b[:60])
    return t[t.index(a):t.index(b)]


# ================================================================================================ blocks that must stay 0.1.12's (all Java)
CARD_START = "# =====================================================================================================================\n# SKYY CARD"
CARD_END = "# ======================================================================= (end of the shared SKYY CARD block)"
CARD_SHA = "bf659e0208b537a81ac8758d909f81976f03069816ea9dddb300f843a7eaa028"   # = tools/profiles_0_1_4_patch.py + classes_0_1_9..12_patch.py
_card = block(CARD_START, CARD_END) + CARD_END
assert hashlib.sha256(_card.encode("utf8")).hexdigest() == CARD_SHA, "the 0.1.12 SKYY CARD block is not SkyyProfiles 0.1.4's"
# every Java line of 0.1.12 stays: from the first makeClass to the end of the script, only the version text may differ
JAVA_FROM = "# ================= ClassDefs:"
_java_old = s[s.index(JAVA_FROM):]

# ================================================================================================ docstring, Run line, version
rep('''"""SkyyClasses 0.1.12 - build script (javassist via jpype). GENERATED by tools/classes_0_1_12_patch.py from the generated 0.1.11 (the
EDITED lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_11_patch.py -> 0.1.11) - edit the patch, not
this file; classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
''', '''"""SkyyClasses 0.1.13 - build script (javassist via jpype). GENERATED by tools/classes_0_1_13_patch.py from the generated 0.1.12 (the
EDITED lineage: Skyy's edited 0.1.6 -> classes_0_1_7_patch.py -> 0.1.7 -> ... -> classes_0_1_12_patch.py -> 0.1.12) - edit the patch, not
this file; classes_0_1_6_patch.py is never re-run. Wynncraft-style classes for SkyWynn.
0.1.13 (2026-10-07; Skyy LOCKED 2026-10-04 "mage can have the spell book", research/cloud/Spellbook-Ladder.md section 7): SPELLBOOKS ARE
  MAGE WEAPONS (the Weapon_Spellbook_ rule moves from Priest to Mage; Priest = wands + Healing Totem; a spellbook hit never heals), the Mage /
  Priest card texts, weapon texts and icons. Kunai (Weapon_Kunai_<Metal>, SkyyArmory 0.1.6) are Assassin weapons through the existing
  "Weapon_Kunai" rule. No row, key, data or Java change. Deploy with SkyyArmory 0.1.6 (the spellbooks + kunai items).
''')
rep("Run:   python build_skyyclasses_0.1.12.py           -> SkyyClasses/SkyyClasses-0.1.12.jar",
    "Run:   python build_skyyclasses_0.1.13.py           -> SkyyClasses/SkyyClasses-0.1.13.jar")
rep('VERSION = "0.1.12"', 'VERSION = "0.1.13"')

# ================================================================================================ the class table
MAGE_DESC_OLD = "Spellcaster. Staves cast magic at range. Hold to blink the way you look and leave a trail of light."
MAGE_DESC_NEW = "Spellcaster. Staves and spellbooks cast magic at range. Hold a staff to blink - hold a spellbook to levitate."
PRIEST_DESC_OLD = "AoE healer and support. Wand and spellbook hits on monsters heal your party. Hold to hop back and burst - the glow heals your party most."
PRIEST_DESC_NEW = "AoE healer and support. Wand hits on monsters heal your party. Hold to hop back and burst - the glow heals your party most."
MAGE_ICONS_OLD = ["Weapon_Staff_Iron", "Weapon_Staff_Wizard", "Weapon_Staff_Crystal_Ice"]
MAGE_ICONS_NEW = ["Weapon_Staff_Iron", "Weapon_Staff_Wizard", "Weapon_Spellbook_Grimoire_Brown"]
PRIEST_ICONS_OLD = ["Weapon_Wand_Wood", "Weapon_Spellbook_Grimoire_Brown", "Weapon_Spellbook_Frost", "Weapon_Deployable_Healing_Totem"]
PRIEST_ICONS_NEW = ["Weapon_Wand_Wood", "Weapon_Wand_Tribal", "Weapon_Wand_Wood_Rotten", "Weapon_Deployable_Healing_Totem"]
for _d in (MAGE_DESC_NEW, PRIEST_DESC_NEW, "Staves / Spellbooks", "Wands / Healing Totem"):
    assert not set(_d) & set(",:;{}\"'_"), _d
rep('''     "desc": "%s",   # 0.1.12: the staff charged traversal (SkyyArmory 0.1.1 blink)
     "icons": %s,
     "weapons": [("Weapon_Staff_", "staves"), ("Halloween_Broomstick", "broomsticks")],
     "weapon_text": "Staves", "kit": "Weapon_Staff_Wood:1"},''' % (MAGE_DESC_OLD, '["%s"]' % '", "'.join(MAGE_ICONS_OLD)),
    '''     "desc": "%s",   # 0.1.13: + spellbooks (SkyyArmory 0.1.6 Levitate)
     "icons": %s,   # 0.1.13: a spellbook in the Crystal staff's place
     # 0.1.13 (Skyy LOCKED 2026-10-04 "mage can have the spell book"): spellbooks moved here from the Priest row
     "weapons": [("Weapon_Staff_", "staves"), ("Halloween_Broomstick", "broomsticks"), ("Weapon_Spellbook_", "spellbooks")],
     "weapon_text": "Staves / Spellbooks", "kit": "Weapon_Staff_Wood:1"},''' % (MAGE_DESC_NEW, '["%s"]' % '", "'.join(MAGE_ICONS_NEW)))
rep('''     "desc": "%s",   # 0.1.12: the wand charged traversal (SkyyArmory 0.1.1 hop + burst + heal orb; spec 8: party most)
     "icons": %s,
     # 0.1.7 (LOCKED Skyy 2026-09-25): the vanilla Healing Totem is Priest only (DeployGuard judges the thrown totem when it lands)
     "weapons": [("Weapon_Wand_", "wands"), ("Weapon_Spellbook_", "spellbooks"), ("Weapon_Deployable_Healing_Totem", "healing totems")],
     "weapon_text": "Wands / Spellbooks / Healing Totem", "kit": "Weapon_Wand_Wood:1"},''' % (PRIEST_DESC_OLD, '["%s"]' % '", "'.join(PRIEST_ICONS_OLD)),
    '''     "desc": "%s",   # 0.1.13: spellbooks are Mage weapons now
     "icons": %s,   # 0.1.13: two more wands in the spellbooks' places
     # 0.1.7 (LOCKED Skyy 2026-09-25): the vanilla Healing Totem is Priest only (DeployGuard judges the thrown totem when it lands)
     # 0.1.13: Weapon_Spellbook_ moved to the Mage (Priest = wands + Soul Orb later; research/cloud/Spellbook-Ladder.md section 7)
     "weapons": [("Weapon_Wand_", "wands"), ("Weapon_Deployable_Healing_Totem", "healing totems")],
     "weapon_text": "Wands / Healing Totem", "kit": "Weapon_Wand_Wood:1"},''' % (PRIEST_DESC_NEW, '["%s"]' % '", "'.join(PRIEST_ICONS_NEW)))

# ================================================================================================ build-time proofs of the move
rep('''PRIEST_I = [i for i, c in enumerate(CLASSES) if c["name"] == "Priest"][0]
''', '''PRIEST_I = [i for i, c in enumerate(CLASSES) if c["name"] == "Priest"][0]
# 0.1.13: spellbooks = Mage (every vanilla + SkyyArmory 0.1.6 book), wands = Priest, every SkyyArmory 0.1.6 kunai = Assassin (the old rule)
MAGE_I13 = [i for i, c in enumerate(CLASSES) if c["name"] == "Mage"][0]
ASSASSIN_I13 = [i for i, c in enumerate(CLASSES) if c["name"] == "Assassin"][0]
_books13 = [i for i in _real if i.startswith("Weapon_Spellbook_")] + ["Weapon_Spellbook_%s" % _m for _m in
                                                                     ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")]
_kunai13 = ["Weapon_Kunai"] + ["Weapon_Kunai_%s" % _m for _m in ("Crude", "Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")]
assert len(_books13) == 13 and all(classify(i) == (MAGE_I13, "spellbooks") for i in _books13), [(i, classify(i)) for i in _books13]
assert all(classify(i)[0] == ASSASSIN_I13 for i in _kunai13) and not CLASSES[ASSASSIN_I13]["enabled"], [(i, classify(i)) for i in _kunai13]
assert all(classify(i)[0] == PRIEST_I for i in _real if i.startswith("Weapon_Wand_")) and classify("Weapon_Staff_Iron")[0] == MAGE_I13
print("0.1.13: %d spellbooks -> Mage (%d vanilla + 7 SkyyArmory), wands + Healing Totem -> Priest, %d kunai ids -> Assassin (disabled)"
      % (len(_books13), len(_books13) - 7, len(_kunai13)))
''')

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
assert [ln for ln in s.split(LF) if "registerSystem(" in ln] == SYS0, "system registrations changed"
_card2 = block(CARD_START, CARD_END) + CARD_END
assert _card2 == _card and hashlib.sha256(_card2.encode("utf8")).hexdigest() == CARD_SHA, "the SKYY CARD block must stay SkyyProfiles 0.1.4's"
assert s[s.index(JAVA_FROM):] == _java_old, "0.1.13 changes no Java line (the tables above generate the new ClassDefs constants)"
assert 'VERSION = "0.1.13"' in s and MAGE_DESC_NEW in s and PRIEST_DESC_NEW in s and MAGE_DESC_OLD not in s and PRIEST_DESC_OLD not in s
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.12 had %d)" % (s.count(LF), OLD.count(LF)))

# ================================================================================================================ the harness (0.1.12's + the move)
TSRC = os.path.join(ROOT, "SkyyClasses", "test_skyyclasses_0.1.12.py")
TDST = os.path.join(ROOT, "SkyyClasses", "test_skyyclasses_0.1.13.py")
traw = open(TSRC, encoding="utf8", newline="").read()
TNL = CR + LF if (CR + LF) in traw else LF
ts = traw.replace(CR + LF, LF)


YF_NEW = r'''    bc = json.load(open(bco))

    def ldiff(cls, meth):
        """(lines only in old, lines only in new) of one changed method, the version strings normalised"""
        lo, ln_ = bc[cls]["listings"][meth]
        a_ = lo.split("\n")
        b_ = [x.replace(VERSION, OLD_VERSION) for x in ln_.split("\n")]
        import collections
        return list((collections.Counter(a_) - collections.Counter(b_)).elements()), list((collections.Counter(b_) - collections.Counter(a_)).elements())

    def cls(name):
        return bc.get("com/skyy/classes/%s.class" % name, {})

    def summ(c):
        return dict((x, c.get(x)) for x in ("changed", "new", "gone", "fields_new", "fields_gone", "consts"))

    # 0.1.13: every changed class but ClassDefs differs only in the version text
    for n_ in sorted(VERSION_ONLY):
        c = cls(n_.split("/")[-1][:-6])
        check(c and not c.get("new") and not c.get("gone") and c.get("fields_same") and c.get("version_only"),
              "Y-F: %s: only the version string differs: %s" % (n_.split("/")[-1], summ(c)))
    # ClassDefs: only <clinit> (the tables generated from CLASSES); the strings that left / came = exactly the card strings + the rule move
    cd_ = cls("ClassDefs")
    check(cd_.get("changed") == ["<clinit>()V"] and not cd_.get("new") and not cd_.get("gone") and cd_.get("fields_same"),
          "Y-F: ClassDefs: only <clinit> (the CLASSES tables): %s" % summ(cd_))
    if cd_.get("changed") == ["<clinit>()V"]:
        o_, n_ = ldiff("com/skyy/classes/ClassDefs.class", "<clinit>()V")
        lo_ = sorted(x.split(" ", 1)[1] for x in o_ if x.startswith("ldc"))
        ln2 = sorted(x.split(" ", 1)[1] for x in n_ if x.startswith("ldc"))
        old_ok = set('"%s"' % x for x in (MAGE_DESC_OLD, PRIEST_DESC_OLD, "Staves", "Wands / Spellbooks / Healing Totem",
                                          "Weapon_Staff_Iron,Weapon_Staff_Wizard,Weapon_Staff_Crystal_Ice",
                                          "Weapon_Wand_Wood,Weapon_Spellbook_Grimoire_Brown,Weapon_Spellbook_Frost,Weapon_Deployable_Healing_Totem",
                                          "Weapon_Wand_,Weapon_Spellbook_,Weapon_Deployable_Healing_Totem", "Weapon_Staff_,Halloween_Broomstick"))
        new_ok = set('"%s"' % x for x in (MAGE_DESC_NEW, PRIEST_DESC_NEW, "Staves / Spellbooks", "Wands / Healing Totem",
                                          "Weapon_Staff_Iron,Weapon_Staff_Wizard,Weapon_Spellbook_Grimoire_Brown",
                                          "Weapon_Wand_Wood,Weapon_Wand_Tribal,Weapon_Wand_Wood_Rotten,Weapon_Deployable_Healing_Totem",
                                          "Weapon_Wand_,Weapon_Deployable_Healing_Totem", "Weapon_Staff_,Halloween_Broomstick,Weapon_Spellbook_"))
        # a string that only moved inside the table (same text, other place) shows on both sides - allowed
        moved = set(lo_) & set(ln2)
        check(set(lo_) - moved <= old_ok and set(ln2) - moved <= new_ok and '"%s"' % MAGE_DESC_OLD in lo_ and '"%s"' % PRIEST_DESC_OLD in lo_
              and '"%s"' % MAGE_DESC_NEW in ln2 and '"%s"' % PRIEST_DESC_NEW in ln2,
              "Y-F: ClassDefs.<clinit>: the strings that changed are only the Mage / Priest card strings and the moved rule (-%s +%s); "
              "other instruction lines moved: -%d +%d" % (lo_, ln2, len([x for x in o_ if not x.startswith("ldc")]), len([x for x in n_ if not x.startswith("ldc")])))
    print("Y-F. class bytes: %d entries identical, differ: %s; methods: %s" % (
        same, ", ".join(sorted(n.split("/")[-1] for n in diff)),
        "; ".join("%s %s" % (n.split("/")[-1][:-6], dict((x, bc[n][x]) for x in ("changed", "new", "gone", "consts") if bc[n][x]))
                  for n in sorted(bc) if not n.startswith("_"))))


'''


def hrep(old, new, count=1):
    global ts
    n = ts.count(old)
    assert n == count, "harness anchor count %d (want %d): %s" % (n, count, old[:140])
    ts = ts.replace(old, new)


hrep('''"""Bare-JVM check for SkyyClasses 0.1.12 (kept next to the build so the build report's JVM claim can be re-run). Copied from the 0.1.11
harness.''', '''"""Bare-JVM check for SkyyClasses 0.1.13 - GENERATED by tools/classes_0_1_13_patch.py from test_skyyclasses_0.1.12.py (edit the patch).
0.1.13 = SPELLBOOKS ARE MAGE WEAPONS (Skyy LOCKED 2026-10-04 "mage can have the spell book"; research/cloud/Spellbook-Ladder.md section 7):
the Weapon_Spellbook_ rule moves from the Priest row to the Mage row, the Mage / Priest card texts, weapon texts and icons follow; the
kunai ladder (Weapon_Kunai_<Metal>, SkyyArmory 0.1.6) is Assassin through the old "Weapon_Kunai" rule. Changes to the 0.1.12 checks:
T (prefixes / owners / allowed: spellbooks = Mage, a Priest may not use one, a Mage may; every SkyyArmory book + kunai id), Q (a Priest kit
with a spellbook now asks - another class's weapon), H4 (a Priest's spellbook shot heals NOTHING now - PriestHealSys only heals Priest
weapons), Y (0.1.12 vs 0.1.13: the page identical but for the Mage + Priest card texts, weapon texts and icons; class bytes: ClassDefs
<clinit> = exactly those strings + the moved rule, every other class the version text only, no class added / removed).
Below: the 0.1.12 text.
Bare-JVM check for SkyyClasses 0.1.12 (kept next to the build so the build report's JVM claim can be re-run). Copied from the 0.1.11
harness.''')
hrep('VERSION = "0.1.12"\nPKG = "com.skyy.classes."', 'VERSION = "0.1.13"\nPKG = "com.skyy.classes."')
hrep('os.path.join(TOOLS, "dev", "scratch", "classes0112", "run")', 'os.path.join(TOOLS, "dev", "scratch", "classes0113", "run")')
# ---- Q: a Priest kit with a spellbook = another class's weapon now
hrep('''    check(KitHooks.checkKit("kit.Priest", "Weapon_Wand_Wood:1,Weapon_Spellbook_Frost:1") is None, "Priest kit with Priest weapons: fine")''',
     '''    check(KitHooks.checkKit("kit.Priest", "Weapon_Wand_Wood:1,Weapon_Wand_Root:1") is None, "Priest kit with Priest weapons: fine")
    q13 = KitHooks.checkKit("kit.Priest", "Weapon_Wand_Wood:1,Weapon_Spellbook_Frost:1")
    check(str(q13) == "?Weapon_Spellbook_Frost is a Mage weapon - a Priest cannot fight with it. Save anyway?"
          and KitHooks.checkKit("kit.Mage", "Weapon_Staff_Wood:1,Weapon_Spellbook_Frost:1") is None,
          "0.1.13: a spellbook in the Priest kit asks (a Mage weapon now); the Mage kit takes one: %s" % q13)''')
# ---- T: the roster's weapon rules
hrep('''          and set(str(Defs.prefixesOf(PR_)).split(",")) == {"Weapon_Spellbook_", "Weapon_Wand_", "Weapon_Deployable_Healing_Totem"},
          "class:weapons:Berserker / Priest (+ the Healing Totem): %s" % Defs.prefixesOf(PR_))''',
     '''          and set(str(Defs.prefixesOf(PR_)).split(",")) == {"Weapon_Wand_", "Weapon_Deployable_Healing_Totem"}
          and set(str(Defs.prefixesOf(names16.index("Mage"))).split(",")) == {"Weapon_Staff_", "Halloween_Broomstick", "Weapon_Spellbook_"},
          "class:weapons:Berserker / Priest (wands + the Healing Totem) / Mage (0.1.13: + spellbooks): %s / %s" % (
              Defs.prefixesOf(PR_), Defs.prefixesOf(names16.index("Mage"))))''')
hrep('''           "Weapon_Wand_Root": PR_, "Weapon_Spellbook_Rekindle_Embers": PR_, "Tool_Hatchet_Iron": -1, "Weapon_Shield_Iron": -1,''',
     '''           "Weapon_Wand_Root": PR_, "Weapon_Spellbook_Rekindle_Embers": names16.index("Mage"), "Tool_Hatchet_Iron": -1, "Weapon_Shield_Iron": -1,''')
hrep('''    check(bool(Rules.allowed(ub, "Weapon_Axe_Iron")) and bool(Rules.allowed(up, "Weapon_Wand_Wood")) and bool(Rules.allowed(up, "Weapon_Spellbook_Frost"))''',
     '''    um13 = UUID.fromString("00000000-0000-0000-0000-000000000113")
    Store.setClassKey(str(um13), names16.index("Mage"), True, False)
    BOOKS13 = ["Weapon_Spellbook_%s" % m_ for m_ in ("Frost", "Fire", "Demon", "Grimoire_Brown", "Grimoire_Purple", "Rekindle_Embers", "Copper",
                                                  "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")]
    KUNAI13 = ["Weapon_Kunai"] + ["Weapon_Kunai_%s" % m_ for m_ in ("Crude", "Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")]
    check(all(int(Defs.ownerOf(b_)) == names16.index("Mage") and bool(Rules.allowed(um13, b_)) and not bool(Rules.allowed(up, b_)) for b_ in BOOKS13)
          and all(int(Defs.ownerOf(k_)) == names16.index("Assassin") for k_ in KUNAI13)
          and str(Rules.blockText(up, "Weapon_Spellbook_Copper", False)) == "Only Mages can use spellbooks. You are a Priest - /class shows your weapons.",
          "0.1.13: every spellbook (6 vanilla + the 7 SkyyArmory 0.1.6 metal books) is a Mage weapon - a Mage may, a Priest may not (popup text); "
          "every kunai id (the vanilla Kunai + the 8 SkyyArmory 0.1.6 kunai) is an Assassin weapon: %s" % Rules.blockText(up, "Weapon_Spellbook_Copper", False))
    check(bool(Rules.allowed(ub, "Weapon_Axe_Iron")) and bool(Rules.allowed(up, "Weapon_Wand_Wood")) and not bool(Rules.allowed(up, "Weapon_Spellbook_Frost"))''')
# ---- H4: a Priest's spellbook shot heals nothing now (not a Priest weapon)
hrep('''    for label, item, pid, dmg, want_ in (("spellbook shot", "Weapon_Spellbook_Frost", "Skeleton_Mage_Corruption_Orb", 400, 10.0),
                                         ("an unknown wand", "Weapon_Wand_Root", "SkyyArmory_Orb_Iron", 400, 10.0),
                                         ("a Mithril quick orb from a spellbook", "Weapon_Spellbook_Frost", "SkyyArmory_QuickOrb_Mithril", 400, 10.0)):''',
     '''    for label, item, pid, dmg, want_ in (("spellbook shot (0.1.13: a Mage weapon - no Priest heal at all)", "Weapon_Spellbook_Frost", "Skeleton_Mage_Corruption_Orb", 400, 0.0),
                                         ("an unknown wand", "Weapon_Wand_Root", "SkyyArmory_Orb_Iron", 400, 10.0),
                                         ("a Mithril quick orb from a spellbook (0.1.13: no heal)", "Weapon_Spellbook_Frost", "SkyyArmory_QuickOrb_Mithril", 400, 0.0)):''')
hrep('''        check(deltas()["Tanky"] == want_, "H4 %s: cap = maxPerHit 10: %s" % (label, deltas()))''',
     '''        check(deltas()["Tanky"] == want_, "H4 %s: heal = %s: %s" % (label, want_, deltas()))''')
# ---- Y: 0.1.12 vs 0.1.13
hrep('OLD_VERSION = "0.1.11"', 'OLD_VERSION = "0.1.12"')
_y_old = ts[ts.index("EXPECTED_DIFF = {"):ts.index("SCRIPT = os.path.join(HERE")]
hrep(_y_old, '''EXPECTED_DIFF = {"com/skyy/classes/ClassDefs.class", "manifest.json"}     # 0.1.13: ClassDefs (the tables) + the version-only classes below
VERSION_ONLY = {"com/skyy/classes/SkyyClassesPlugin.class", "com/skyy/classes/CfgFn.class", "com/skyy/classes/CfgRows.class",
                "com/skyy/classes/KitMigrate.class"}
EXPECTED_DIFF |= VERSION_ONLY
# 0.1.13 (Skyy LOCKED 2026-10-04 "mage can have the spell book"): the Mage + Priest card texts, weapon texts and icons
MAGE_DESC_OLD = %r
MAGE_DESC_NEW = %r
PRIEST_DESC_OLD = %r
PRIEST_DESC_NEW = %r
DESCS = [(MAGE_DESC_OLD, MAGE_DESC_NEW), (PRIEST_DESC_OLD, PRIEST_DESC_NEW)]
# every string of the new page mapped back to the old page's (one regex pass, longest first): texts, weapon texts, icon ids
PAGE_MAP = {MAGE_DESC_NEW: MAGE_DESC_OLD, PRIEST_DESC_NEW: PRIEST_DESC_OLD, "Staves / Spellbooks": "Staves",
            "Wands / Healing Totem": "Wands / Spellbooks / Healing Totem", "Weapon_Spellbook_Grimoire_Brown": "Weapon_Staff_Crystal_Ice",
            "Weapon_Wand_Tribal": "Weapon_Spellbook_Grimoire_Brown", "Weapon_Wand_Wood_Rotten": "Weapon_Spellbook_Frost"}
_PAGE_RE = re.compile("|".join(re.escape(k) for k in sorted(PAGE_MAP, key=len, reverse=True)))


def page_back(text):
    return _PAGE_RE.sub(lambda m_: PAGE_MAP[m_.group(0)], text)


''' % (MAGE_DESC_OLD, MAGE_DESC_NEW, PRIEST_DESC_OLD, PRIEST_DESC_NEW))
hrep('PATCH_NEW = os.path.join(TOOLS, "classes_0_1_12_patch.py")      # 0.1.12 keeps the block (asserts its CARD_SHA, never redefines it)',
     'PATCH_NEW = os.path.join(TOOLS, "classes_0_1_13_patch.py")      # 0.1.13 keeps the block (asserts its CARD_SHA, never redefines it)')
hrep('''        mj_ = nj_
        for o__, n__ in DESCS:
            mj_ = mj_.replace(json.dumps(n__)[1:-1], json.dumps(o__)[1:-1])
        mapped_ = json.loads(mj_)''', '''        mapped_ = json.loads(page_back(nj_))          # 0.1.13: the new card strings mapped back to 0.1.12's''')
hrep('''              "Y-B %s: the 0.1.12 page = the 0.1.11 page (commands, bindings) but for the Mage + Priest card texts (%d / %d x)"''',
     '''              "Y-B %s: the 0.1.13 page = the 0.1.12 page (commands, bindings) but for the Mage + Priest card texts, weapon texts and icons (%d / %d x)"''')
hrep('''        got = compare_state(nm, os_, ns_, SUI, counts, data_colors, PAGE_W, PAGE_H, BODY_ID, BODY_INNER_H, {"text_ok": lambda t_: MAGE_DESC_OLD in t_ or PRIEST_DESC_OLD in t_})''',
     '''        got = compare_state(nm, os_, ns_, SUI, counts, data_colors, PAGE_W, PAGE_H, BODY_ID, BODY_INNER_H,
                            {"text_ok": lambda t_: page_back(t_) != t_ or any(v_ in t_ for v_ in PAGE_MAP.values())})''')
hrep('''    print("Y-B/G/H. %(identical)d states identical in 0.1.11 and 0.1.12 but for the Mage + Priest card texts''',
     '''    print("Y-B/G/H. %(identical)d states identical in 0.1.12 and 0.1.13 but for the Mage + Priest card strings''')
hrep('''"E: classes_0_1_12_patch.py asserts SkyyProfiles 0.1.4's CARD_SHA "''', '''"E: classes_0_1_13_patch.py asserts SkyyProfiles 0.1.4's CARD_SHA "''')
hrep('''    NEW_ENTRIES = {"com/skyy/classes/HealFn.class", "com/skyy/classes/AllyFn.class"}   # 0.1.12: class:fn:heal / class:fn:ally
    check(set(zn.namelist()) - set(zo.namelist()) == NEW_ENTRIES and not set(zo.namelist()) - set(zn.namelist()),
          "Y-F: the 0.1.12 jar = the 0.1.11 entries + HealFn + AllyFn: +%s -%s" % (sorted(set(zn.namelist()) - set(zo.namelist())),''',
     '''    NEW_ENTRIES = set()          # 0.1.13: no new class
    check(set(zn.namelist()) - set(zo.namelist()) == NEW_ENTRIES and not set(zo.namelist()) - set(zn.namelist()),
          "Y-F: the 0.1.13 jar = the 0.1.12 entries: +%s -%s" % (sorted(set(zn.namelist()) - set(zo.namelist())),''')
hrep('''    for _n in ("ClassPage", "PriestHealSys", "ShotTrack", "ShotRec", "HealBudget", "HealMsg", "DamageLock", "DeployGuard", "Kit"):
        check("com/skyy/classes/%s.class" % _n not in diff, "Y-F: %s.class is byte-identical to 0.1.11's" % _n)''',
     '''    for _n in ("ClassPage", "PriestHealSys", "ShotTrack", "ShotRec", "HealBudget", "HealMsg", "DamageLock", "DeployGuard", "Kit", "HealTask",
               "HealFn", "AllyFn", "ClassRules", "ClassStore"):
        check("com/skyy/classes/%s.class" % _n not in diff, "Y-F: %s.class is byte-identical to 0.1.12's" % _n)''')
_yf_old = ts[ts.index("    bc = json.load(open(bco))"):ts.index("# ============================================================================================================== child: parts Z + M (0.1.10)")]
hrep(_yf_old, YF_NEW)
tout = ts.replace(LF, TNL)
with open(TDST, "w", encoding="utf8", newline="") as f:
    f.write(tout)
print("wrote %s (%d lines)" % (os.path.relpath(TDST, ROOT), tout.count(TNL) + 1))
