"""Derive SkyyCollections/build_skyycollections_0.2.6.py from the LIVE 0.2.5 (build_skyycollections_0.2.5.py = the tools/deploy_set.py
SET pin; 0.2.5 stays untouched; same style as coll_0_2_5_patch.py: rep() with asserted single anchors, newline-agnostic, the source's
line endings kept). Edit THIS file, never the generated build script (it is overwritten on every run of this patch).
Run:  python tools/coll_0_2_6_patch.py   then   python SkyyCollections/build_skyycollections_0.2.6.py   (never --deploy)
Test: python SkyyCollections/test_skyycollections_0.2.6.py   (bare JVM, -Xverify:all; scratch under tools/dev/scratch/, deleted afterwards)

0.2.6 (lean) = LEADERBOARDS SKIP DELETED AND ARCHIVED PROFILES. SkyyProfiles 0.1.5 added profile delete (6 h undo window) + archive and
publishes profile:fn:state on the skyy.bridge (tools/PROFILES-CONTRACT.md: Function apply(String storage key) -> "active" | "inactive"
| "pending" | "archived" | null; cache hit = no I/O, never throws, never calls out). The contract says mods that scan every profile file
on disk (leaderboards in Skills / Collections) must skip keys whose state is pending or archived.
  - CollTop.all (the /collections top <collection|score> list): after the counts files + the in-memory overlay are merged, every row
    with a value > 0 is checked once per board build (the 30 s board cache = the state cache; there is no batch call in the contract,
    and each call is a SkyyProfiles cache hit) and left out when its key's state is "pending" (deleted, inside the undo window) or
    "archived". A restored profile is "active" / "inactive" again and shows at the next build (at most 30 s later, or at once after
    /collections reload, which clears the cache).
  - new CollTop.stateFn() (the bridge Function or null) and CollTop.gone(fn, key) (true ONLY for exactly "pending" / "archived";
    SkyyProfiles missing, not a Function, null / any other answer, or a throwing call = shown, exactly 0.2.5's list).
  - Nothing saved changes: the counts files, the in-memory data, the bridge publishes, the score and every other path are 0.2.5's
    (the harness compares the class bytes: only CollTop.all differs + the two new CollTop methods, everything else version-only).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyCollections", "build_skyycollections_0.2.5.py")
dst = os.path.join(ROOT, "SkyyCollections", "build_skyycollections_0.2.6.py")
raw = open(src, "rb").read()
NL = "\r\n" if b"\r\n" in raw else "\n"
assert NL == "\n" or raw.count(b"\r\n") == raw.count(b"\n"), "mixed line endings in 0.2.5"
LF = "\n"
s = raw.decode("utf8").replace("\r\n", LF)
OLD = s
assert 'VERSION = "0.2.5"' in s and "GENERATED by tools/coll_0_2_5_patch.py from the LIVE 0.2.4" in s, "not the live generated 0.2.5"
assert 'COLL_PAGE_CHECKED = "be0dca34bcb2"' in s, "build_skyycollections_0.2.5.py is not the checked 0.2.5 page"
assert "profile:fn:state" not in s


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:120])
    s = s.replace(old, new)


# ---------------------------------------------------------------------------------------------------------------- header
rep('''"""SkyyCollections 0.2.5 - build script (javassist via jpype). GENERATED by tools/coll_0_2_5_patch.py from the LIVE 0.2.4
(build_skyycollections_0.2.4.py, the tools/deploy_set.py SET pin) - edit the patch, never this file. 0.2.4 was derived from 0.2.3 by
tools/coll_0_2_4_patch.py;''', '''"""SkyyCollections 0.2.6 - build script (javassist via jpype). GENERATED by tools/coll_0_2_6_patch.py from the LIVE 0.2.5
(build_skyycollections_0.2.5.py, the tools/deploy_set.py SET pin) - edit the patch, never this file. 0.2.5 was derived from 0.2.4 by
tools/coll_0_2_5_patch.py; 0.2.4 from 0.2.3 by tools/coll_0_2_4_patch.py;''')
rep('''0.2.5 (2026-10-02, Skyy's decision''', '''0.2.6 (2026-10-05, lean): LEADERBOARDS SKIP DELETED AND ARCHIVED PROFILES (SkyyProfiles 0.1.5 profile:fn:state, tools/PROFILES-CONTRACT.md).
  /collections top <collection|score> leaves out every profile whose storage key SkyyProfiles answers "pending" (deleted, inside the
  6 h undo window) or "archived"; a restored profile shows again at the next list build (30 s cache; /collections reload clears it).
  One profile:fn:state call per listed key per board build (no batch call exists; a SkyyProfiles cache hit). SkyyProfiles missing,
  any other answer or a throwing call = shown (0.2.5's list). Only the listing filters - no saved data is read differently or changed.
  Full notes: tools/coll_0_2_6_patch.py. CHECKED with SkyyCollections/test_skyycollections_0.2.6.py.
0.2.5 (2026-10-02, Skyy's decision''')
rep("Run:   python build_skyycollections_0.2.5.py          -> SkyyCollections/SkyyCollections-0.2.5.jar",
    "Run:   python build_skyycollections_0.2.6.py          -> SkyyCollections/SkyyCollections-0.2.6.jar")
rep('VERSION = "0.2.5"', 'VERSION = "0.2.6"')
rep('"[SkyyCollections] 0.2.5 ready (', '"[SkyyCollections] 0.2.6 ready (')

# ---------------------------------------------------------------------------------------------------------------- CollTop
rep('''M(top, r"""
public static synchronized java.util.ArrayList all(int board) {''', '''# 0.2.6: SkyyProfiles' profile:fn:state (tools/PROFILES-CONTRACT.md) - the bridge Function, or null when SkyyProfiles is missing
M(top, r"""
public static java.util.function.Function stateFn() {
  try {
    Object f = @PKG@.CollUtil.bridge().get("profile:fn:state");
    if (f instanceof java.util.function.Function) return (java.util.function.Function) f;
  } catch (Throwable t) { }
  return null;
}""")
# 0.2.6: a deleted (pending: inside the undo window) or archived profile is left out of the lists; anything else (no SkyyProfiles,
# active / inactive, null, another answer, a throwing call) is shown - 0.2.5's list
M(top, r"""
public static boolean gone(java.util.function.Function sf, String key) {
  if (sf == null || key == null) return false;
  try {
    Object r = sf.apply(key);
    return "pending".equals(r) || "archived".equals(r);
  } catch (Throwable t) { return false; }
}""")
M(top, r"""
public static synchronized java.util.ArrayList all(int board) {''')
rep('''  java.util.ArrayList rows = new java.util.ArrayList();
  java.util.Iterator vi = m.values().iterator();
  while (vi.hasNext()) { Object[] row = (Object[]) vi.next(); if (((Long) row[1]).longValue() > 0L) rows.add(row); }''',
    '''  java.util.ArrayList rows = new java.util.ArrayList();
  java.util.function.Function sf = stateFn();
  java.util.Iterator vi = m.values().iterator();
  while (vi.hasNext()) { Object[] row = (Object[]) vi.next(); if (((Long) row[1]).longValue() > 0L && !gone(sf, (String) row[2])) rows.add(row); }''')
rep('''  Leaderboards: /collections top <collection|score> - every counts file on disk (one row per profile, "name (profile N)"),
    overlaid with the in-memory counts, cached 30 s.''', '''  Leaderboards: /collections top <collection|score> - every counts file on disk (one row per profile, "name (profile N)"),
    overlaid with the in-memory counts, cached 30 s; 0.2.6: deleted (pending) / archived profiles left out (profile:fn:state).''')

# ---------------------------------------------------------------------------------------------------------------- guards
assert s.count("profile:fn:state") >= 3 and s.count("gone(sf, (String) row[2])") == 1
assert s.index("public static java.util.function.Function stateFn()") < s.index("public static boolean gone(") \
    < s.index("public static synchronized java.util.ArrayList all(int board)")
_gone = sorted(ln for ln in set(OLD.split(LF)) - set(s.split(LF)))
_ALLOWED = {
    '"""SkyyCollections 0.2.5 - build script (javassist via jpype). GENERATED by tools/coll_0_2_5_patch.py from the LIVE 0.2.4',
    "(build_skyycollections_0.2.4.py, the tools/deploy_set.py SET pin) - edit the patch, never this file. 0.2.4 was derived from 0.2.3 by",
    "tools/coll_0_2_4_patch.py; 0.2.3 from 0.2.2 by tools/coll_0_2_3_patch.py; 0.2.2 from 0.2.1 by tools/coll_0_2_2_patch.py; 0.2.1 from 0.2",
    "Run:   python build_skyycollections_0.2.5.py          -> SkyyCollections/SkyyCollections-0.2.5.jar",
    'VERSION = "0.2.5"',
    "    overlaid with the in-memory counts, cached 30 s. _name=<player> is written to each counts file.",
    "  while (vi.hasNext()) { Object[] row = (Object[]) vi.next(); if (((Long) row[1]).longValue() > 0L) rows.add(row); }",
}
_bad = [ln for ln in _gone if ln not in _ALLOWED and "0.2.5 ready (" not in ln]
assert not _bad, "0.2.5 lines lost by accident: %s" % _bad[:5]
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.2.5 had %d)" % (s.count(LF), OLD.count(LF)))
