"""Derive SkyyCooking/build_skyycooking_0.1.5.py from the SET pin build_skyycooking_0.1.4.py (itself generated by tools/cooking_0_1_4_patch.py):
rep(old, new) with asserted anchors, newline-agnostic (the CRLF line endings of 0.1.4 are kept). Edit THIS patch, never the generated build
script. Run: python tools/cooking_0_1_5_patch.py, then python SkyyCooking/build_skyycooking_0.1.5.py.

0.1.5 = COOKING XP BY CRAFT DIFFICULTY (lean round). Skyy 2026-10-04 (docs/answered/skills.md LOCKED): "lower the skewers a bit. the easier to
craft the less xp. the harder to craft the more."
 - The default "XP per craft" table (cooking.properties xp.<output> lines, Server Setup -> Cooking -> Cooking XP -> XP per craft) paid every
   DISH 85% of the raw gathering in its whole ingredient chain x 950 per item (x1.25 with recipe knowledge), so one-step skewers with
   several raw items paid a lot. 0.1.5: a dish pays chain raw x 950 x a DIFFICULTY SHARE:
     share = 20% + 15% per extra crafting step in its chain (distinct crafts: flour, dough, spices, salt, cheese, fish cleaning)
           + 25% when the recipe needs recipe knowledge (pies, Caesar salad)
           + 0% Campfire dish / 5% Cooking Bench "Prepared" / 10% Cooking Bench "Baked" (needs fuel; the Cooking Bench has no tiers)
           + 5% per ingredient tier above 1 (the Bazaar crop ladder, docs/answered/economy.md 2026-10-04: Corn T2, Pumpkin T4; Apple T2
             (fruit tree), Milk T2 (livestock); everything else T1)
   Ingredient crafts (flour, dough, salt, spices, cheese, raw fish) keep 15% of their own inputs (unchanged; they are already the lowest
   share). The weights are build constants here (DIFF_*); the per-dish rows stay the in-game editable surface (no runtime formula).
 - maxXpPerMinute stays 1,500,000 (2x the new bench peak would be 1.4M - pinned so no second setting changes).
 - The meat-pie route still lands in decision 2's 25-30 h window (base XP).
 - ONE-TIME UPDATE (new class CookTblMig, setup() right after CookXpMig.migrate, before CookCfg.load + CfgPub.start): every xp.<dish> line
   whose value is still the 0.1.4 default text - or exactly one of the four 2026-10-04 stopgap values (Food_Kebab_Vegetable / _Fruit 1800,
   _Mushroom 1400, _Meat 2600) - gets the 0.1.5 value; every other value is kept and logged; the three generated help comment lines of the
   xp block (byte-exact 0.1-0.1.4 text) are replaced 1:1 by the new wording; History copy verified first, one Undo-able change-log line
   per changed entry (key xp[<id>] = the kit's table form), run-once marker XP_TBL_MARK above the xp block's help comment, every other
   byte and line ending kept. xpMultiplier is never touched.
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyCooking", "build_skyycooking_0.1.4.py")
dst = os.path.join(ROOT, "SkyyCooking", "build_skyycooking_0.1.5.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


# the 0.1.4 defaults (= the live cooking.properties written by 0.1) and the 0.1.5 table the build must compute (asserted there)
XP_014 = {"Food_Bread": 12900, "Food_Cheese": 430, "Food_Fish_Grilled": 2000, "Food_Fish_Raw": 285, "Food_Kebab_Fruit": 3650,
          "Food_Kebab_Meat": 5250, "Food_Kebab_Mushroom": 2850, "Food_Kebab_Vegetable": 3650, "Food_Pie_Apple": 25250,
          "Food_Pie_Meat": 23900, "Food_Pie_Pumpkin": 23200, "Food_Popcorn": 3000, "Food_Salad_Berry": 4850, "Food_Salad_Caesar": 11800,
          "Food_Salad_Mushroom": 3250, "Food_Vegetable_Cooked": 1200, "Food_Wildmeat_Cooked": 1600, "Ingredient_Dough": 640,
          "Ingredient_Flour": 1425, "Ingredient_Salt": 140, "Ingredient_Spices": 855}
XP_015 = dict(XP_014, Food_Vegetable_Cooked=300, Food_Wildmeat_Cooked=400, Food_Fish_Grilled=850, Food_Kebab_Mushroom=850,
              Food_Salad_Mushroom=950, Food_Kebab_Fruit=1050, Food_Kebab_Vegetable=1050, Food_Salad_Berry=1400, Food_Kebab_Meat=1550,
              Food_Popcorn=1750, Food_Bread=9100, Food_Salad_Caesar=11100, Food_Pie_Apple=24950, Food_Pie_Pumpkin=25150, Food_Pie_Meat=25900)
STOPGAP = {"Food_Kebab_Vegetable": 1800, "Food_Kebab_Fruit": 1800, "Food_Kebab_Mushroom": 1400, "Food_Kebab_Meat": 2600}
ORDER = sorted(XP_015, key=lambda k: (XP_015[k], k))
TABLE = "".join("     %-22s %6s -> %6s%s\n" % (k, "{:,}".format(XP_014[k]), "{:,}".format(XP_015[k]),
                                                   ("   (stopgap 2026-10-04: %s)" % "{:,}".format(STOPGAP[k])) if k in STOPGAP else
                                                   ("" if XP_014[k] != XP_015[k] else "   (ingredient, unchanged)"))
                for k in ORDER)


def spl(xp, mult):
    return " / ".join("%.1f" % (c / (xp * mult)) for c in (5000, 7500, 10000))


# ---------------------------------------------------------------------------------------------------------------- docstring
rep('''"""SkyyCooking 0.1.4 - build script (javassist via jpype). DERIVED from build_skyycooking_0.1.3.py by tools/cooking_0_1_4_patch.py
(0.1.3 / 0.1.2 / 0.1.1 are derived the same way by tools/cooking_0_1_3_patch.py / _0_1_2_patch.py / _0_1_1_patch.py): edit the patch and
re-run it, not this file.
Run:   python build_skyycooking_0.1.4.py            -> SkyyCooking/SkyyCooking-0.1.4.jar
       (never --deploy: tools/deploy_set.py is the only deploy path - HANDOFF section 3)
''', '''"""SkyyCooking 0.1.5 - build script (javassist via jpype). DERIVED from build_skyycooking_0.1.4.py by tools/cooking_0_1_5_patch.py
(0.1.4 / 0.1.3 / 0.1.2 / 0.1.1 are derived the same way by tools/cooking_0_1_4_patch.py / _0_1_3_patch.py / _0_1_2_patch.py /
_0_1_1_patch.py): edit the patch and re-run it, not this file.
Run:   python build_skyycooking_0.1.5.py            -> SkyyCooking/SkyyCooking-0.1.5.jar
       (never --deploy: tools/deploy_set.py is the only deploy path - HANDOFF section 3)

0.1.5 = COOKING XP BY CRAFT DIFFICULTY (Skyy 2026-10-04, docs/answered/skills.md LOCKED: "lower the skewers a bit. the easier to craft the
 less xp. the harder to craft the more.").
 - DEFAULT "XP per craft" TABLE (xp.<output> lines; Server Setup -> Cooking -> Cooking XP -> XP per craft). Until 0.1.4 a dish paid 85% of
   the raw gathering in its whole ingredient chain x 950 per item (x1.25 with recipe knowledge): one-step skewers with 4-5 raw items paid
   3,650-5,250. Now a dish pays chain raw x 950 x a DIFFICULTY SHARE:
     share = 20% + 15% per extra crafting step in the chain (distinct crafts: flour, dough, spices, salt, cheese, fish cleaning)
           + 25% recipe knowledge (pies, Caesar salad) + 0% Campfire dish / 5% Cooking Bench Prepared / 10% Cooking Bench Baked (fuel)
           + 5% per ingredient tier above 1 (Bazaar crop ladder 2026-10-04: Corn T2, Pumpkin T4; Apple T2, Milk T2; the rest T1)
   (the Cooking Bench has no tier levels, so "bench tier" = Campfire < Prepared < Baked). Shares: campfire dishes 20% (grilled fish 35%),
   skewers / berry + mushroom salad 25%, popcorn 50%, bread 60%, Caesar 100%, apple pie 105%, meat + pumpkin pie 115%. Ingredient crafts
   keep 15% of their own inputs (unchanged). Base XP per craft, 0.1.4 -> 0.1.5:
''' + TABLE + '''   Meat-pie route (decision 2, base XP): ~25 focused hours to Cooking 50 (0.1.4: ~27), inside the 25-30 h window. maxXpPerMinute stays
   1,500,000 (pinned: 2x the new bench peak is 1.4M). The weights are the DIFF_* build constants; the in-game editable surface stays the
   per-dish rows (the table is not formula-driven at runtime). xpMultiplier default stays 0.5.
   Skewers per level at Cooking 10 / 11 / 12 (next level costs 5,000 / 7,500 / 10,000; before SkyySkills' own XP multiplier / Wisdom):
     xpMultiplier 0.5 (pack default): Vegetable / Fruit ''' + spl(1050, 0.5) + ''', Mushroom ''' + spl(850, 0.5) + ''', Meat ''' + spl(1550, 0.5) + '''
     xpMultiplier 0.15 (live row 2026-10-04): Vegetable / Fruit ''' + spl(1050, 0.15) + ''', Mushroom ''' + spl(850, 0.15) + ''', Meat ''' + spl(1550, 0.15) + '''
 - ONE-TIME UPDATE of an existing cooking.properties (new class CookTblMig; setup() runs CookMig.migrate -> CookXpMig.migrate ->
   CookTblMig.migrate -> CookCfg.load -> CfgPub.start): for every dish whose default changed, the key's LAST entry (what
   java.util.Properties keeps) decides: a one-line entry holding exactly the 0.1.4 default text (e.g. 3650) - or exactly a 2026-10-04
   stopgap value (Food_Kebab_Vegetable / _Fruit 1800, _Mushroom 1400, _Meat 2600) - moves to the 0.1.5 value (every one-line entry of
   that key holding one of those texts is rewritten, value text only: key, separator and CR stay); anything else (a hand-set value, a
   continued entry) is KEPT and logged ("xp.Food_Pie_Meat=30000 kept (custom) - the 0.1.5 default is 25900"); a missing line stays
   missing (the compiled 0.1.5 value applies). The three generated help comment lines above the xp block (byte-exact 0.1-0.1.4 text) are
   replaced 1:1 by the 0.1.5 wording; any other comment stays. CookMig's reviewed machinery (CookMig.kit / saved / logLine): History copy
   "before the 0.1.5 Cooking XP by difficulty update" verified before the rewrite (else WARN, file untouched, next start tries again);
   CfgRows.atomicWrite; one config-changes.log line PER CHANGED ENTRY in the kit's table form (time, SkyyCooking 0.1.5, -, update,
   xp[Food_Kebab_Vegetable], 3650, 1050, ok) so Server Setup -> Changes undoes each with a tset back; one INFO line (+ one per kept
   value). RUNS ONCE: the marker XP_TBL_MARK goes on its own line above the comment block directly on top of the first xp.* entry (no xp
   entry: above the file's first entry, else on top); a file with XP_TBL_MARK_ID in a comment line is never changed again (an Undo back to
   3650 survives restarts). The 0.1.5 default text carries the marker. xpMultiplier, maxXpPerMinute, xp.default and the ingredient lines
   are never touched.
 Nothing else changed (class compare in the harness): grading, rolls, Grades, effects, tooltips, campfire factors, bridge keys, commands,
 permissions, the other rows. The campfire accessory pays campfire.xpFactor x the NEW xp.<dish> value (Cooked Wildmeat 400 x 0.25 = 100).
 Bare-JVM harness: SkyyCooking/test_skyycooking_0.1.5.py.

0.1.4 (previous version, kept below for the record):
''')
rep('VERSION = "0.1.4"', 'VERSION = "0.1.5"')

# ---------------------------------------------------------------------------------------------------------------- XP table
rep('''XP_DEFAULT = 1000   # any other Cookingbench output (modded content); the server log names it once
''', '''XP_DEFAULT = 1000   # any other Cookingbench output (modded content); the server log names it once
# ---- 0.1.5 (Skyy 2026-10-04): "the easier to craft the less xp. the harder to craft the more." The loop above is the 0.1-0.1.4 table
# (kept as XP_OLD: CookTblMig rewrites only lines still holding these texts). A DISH now pays chain raw x K x a DIFFICULTY SHARE (percent):
#   DIFF_BASE + DIFF_STEP per extra distinct craft in its chain + DIFF_KNOW for recipe knowledge + DIFF_BENCH[class] + DIFF_TIER per
#   ingredient tier above 1. Ingredient crafts keep ING_SHARE of their own inputs. Edit the weights in tools/cooking_0_1_5_patch.py.
XP_OLD = dict(XP)
XP_014 = %r
assert XP_OLD == XP_014, "0.1.5: the 0.1-0.1.4 table changed under the patch (Assets.zip?) - re-check the migration's old texts: %%s" %% XP_OLD
DIFF_BASE, DIFF_STEP, DIFF_KNOW, DIFF_TIER = 20, 15, 25, 5
DIFF_BENCH = {"Campfire": 0, "Prepared": 5, "Baked": 10}   # the Cooking Bench has no tier levels: Campfire dish < Prepared < Baked (fuel)
# ingredient tiers (docs/answered/economy.md 2026-10-04 Bazaar progression: crops T1 Wheat / Carrot / Lettuce / Potato, T2 Corn ..., T4
# Pumpkin; Apple from a T2 fruit tree; Milk needs livestock); everything else (resource groups, eggs, salt rock, flowers, berries) is T1
ING_TIER = {"Plant_Crop_Corn_Item": 2, "Plant_Crop_Pumpkin_Item": 4, "Plant_Fruit_Apple": 2, "Milk_Bucket": 2}
for _i in ING_TIER:
    assert _i in V_ITEMS or _i in V_RTYPES, "0.1.5: ingredient tier id %%s is not in Assets.zip" %% _i
STOPGAP_014 = %r    # Skyy's live rows 2026-10-04 (replaceable defaults for CookTblMig)
def bench_class(out):
    if out in [v[1] for v in VARIANTS]: return "Campfire"
    cats = [c for b in (rd(V_ITEMS[out])["Recipe"].get("BenchRequirement") or []) if b.get("Id") == "Cookingbench" for c in (b.get("Categories") or [])]
    assert len(cats) == 1 and cats[0] in DIFF_BENCH, "0.1.5: %%s has Cooking Bench categories %%s" %% (out, cats)
    return cats[0]
def chain_crafts(out, acc=None):
    acc = set() if acc is None else acc
    acc.add(out)
    for kind, i, n in COOK[out][0]:
        if kind == "I" and i in COOK and i != out: chain_crafts(i, acc)
    return acc
def chain_tier(out):
    t = 1
    for kind, i, n in COOK[out][0]:
        t = max(t, chain_tier(i) if (kind == "I" and i in COOK and i != out) else ING_TIER.get(i, 1))
    return t
def diff_share(out):
    return (DIFF_BASE + DIFF_STEP * (len(chain_crafts(out)) - 1) + (DIFF_KNOW if COOK[out][3] else 0) + DIFF_BENCH[bench_class(out)]
            + DIFF_TIER * (chain_tier(out) - 1))
DIFF = {}
for out in DISHES:
    DIFF[out] = diff_share(out)
    XP[out] = rnd_to(K_XP * DIFF[out] * chain_raw(out) / 100.0, 50)
XP_015 = %r
assert XP == XP_015, "0.1.5: the difficulty table is not the one the patch documents: %%s" %% XP
print("0.1.5 XP per craft by difficulty (share %%, old -> new): " + ", ".join("%%s %%d%%%% %%d -> %%d" %% (d, DIFF[d], XP_OLD[d], XP[d]) for d in sorted(DISHES, key=lambda d: XP[d])))
# Skyy's rule as checks: easy (one craft, no knowledge) < multi-step (3+ crafts); skewers clearly under the 2026-10-04 stopgap rows
_easy = [d for d in DISHES if len(chain_crafts(d)) == 1 and not COOK[d][3]]
_hard = [d for d in DISHES if len(chain_crafts(d)) >= 3]
assert _easy and _hard and max(XP[d] for d in _easy) < min(XP[d] for d in _hard), "0.1.5: an easy dish pays as much as a multi-step one"
assert all(XP[d] <= 0.65 * STOPGAP_014[d] for d in STOPGAP_014), "0.1.5: skewers must pay clearly less than the 2026-10-04 stopgap rows"
assert all(XP[d] < XP_OLD[d] for d in _easy), "0.1.5: every easy dish must pay less than in 0.1.4"
assert all(XP[i] == XP_OLD[i] for i in XP if i not in DISHES), "0.1.5: ingredient crafts keep their 0.1.4 values"
''' % (XP_014, STOPGAP, XP_015))
rep('''MAX_PER_MIN = int(math.ceil(PEAK * 2.0 / 100000.0) * 100000)   # 2x the legit bench peak, rounded up to 100k
''', '''MAX_PER_MIN = int(math.ceil(PEAK * 2.0 / 100000.0) * 100000)   # 2x the legit bench peak, rounded up to 100k
# 0.1.5: the difficulty table lowers the peak (Caesar 11,100 XP per 1 s craft -> 1.4M); the 0.1.4 default 1,500,000 is kept so no second
# setting changes (it still covers 2x the peak)
assert MAX_PER_MIN <= 1500000, "0.1.5: the bench peak grew past the 0.1.4 maxXpPerMinute default - re-think the pin"
MAX_PER_MIN = 1500000
''')

# ---------------------------------------------------------------------------------------------------------------- default text
HELP_OLD = [
    "# Base XP per finished craft at the Cooking Bench, keyed by the craft's primary OUTPUT item id (0 = no XP). Pace (decision 2):",
    "# the meat-pie route reaches Cooking 50 in about 27 focused hours, like Alchemy 50. A dish pays 85% of the raw gathering in its",
    "# whole ingredient chain x 950 per item (x1.25 for pies and Caesar salad, which need recipe knowledge); an ingredient craft pays 15% of its own inputs.",
]
HELP_NEW = [
    "# Base XP per finished craft at the Cooking Bench, keyed by the craft's primary OUTPUT item id (0 = no XP). By difficulty (0.1.5): a dish",
    "# pays the raw gathering in its whole ingredient chain x 950 per item x a share - 20% + 15% per extra crafting step + 25% recipe",
    "# knowledge + 5% Prepared / 10% Baked at the Cooking Bench + 5% per ingredient tier above 1. An ingredient craft pays 15% of its own inputs.",
]
for _l in HELP_OLD + HELP_NEW:
    assert all(32 <= ord(c) < 127 for c in _l), _l     # (the 0.1-0.1.4 first line already holds "(0 = no XP)"; the kit reads it as a comment)
XP_TBL_MARK_ID = "SkyyCooking 0.1.5 Cooking XP by difficulty"
XP_TBL_MARK = ("# %s (Skyy 2026-10-04): easier dishes pay less XP, multi-step dishes more - the xp lines still on the old defaults "
               "were updated once" % XP_TBL_MARK_ID)
assert "=" not in XP_TBL_MARK and all(32 <= ord(c) < 127 for c in XP_TBL_MARK)
rep('''      "# Base XP per finished craft at the Cooking Bench, keyed by the craft's primary OUTPUT item id (0 = no XP). Pace (decision 2):",
      "# the meat-pie route reaches Cooking 50 in about %.0f focused hours, like Alchemy 50. A dish pays %d%% of the raw gathering in its" % (HOURS_50, int(DISH_SHARE * 100)),
      "# whole ingredient chain x %d per item (x%.2f for pies and Caesar salad, which need recipe knowledge); an ingredient craft pays %d%% of its own inputs." % (int(K_XP), KNOW_BONUS, int(ING_SHARE * 100)),
      "xp.default=%d" % XP_DEFAULT]''', '''      XP_TBL_MARK] + XP_HELP_NEW + [
      "xp.default=%d" % XP_DEFAULT]''')
rep('''XP_MARK_ID = "SkyyCooking 0.1.4 Cooking XP"
''', '''XP_MARK_ID = "SkyyCooking 0.1.4 Cooking XP"
# 0.1.5 run-once marker of the XP-per-craft update (CookTblMig) + the xp block's help lines: the byte-exact 0.1-0.1.4 text (CookTblMig
# replaces exactly these, 1:1) and the 0.1.5 wording (the default text and the update write it). Plain ASCII, no '='.
XP_HELP_OLD = %r
XP_HELP_NEW = %r
XP_TBL_MARK_ID = %r
XP_TBL_MARK = %r
assert XP_HELP_OLD[1] == "# the meat-pie route reaches Cooking 50 in about 27 focused hours, like Alchemy 50. A dish pays 85%% of the raw gathering in its"
''' % (HELP_OLD, HELP_NEW, XP_TBL_MARK_ID, XP_TBL_MARK))

# ---------------------------------------------------------------------------------------------------------------- CookTblMig
TBL_MIG = r'''
# ================= CookTblMig (0.1.5): the one-time XP-per-craft update of an existing cooking.properties (see the header) =================
# CookMig's reviewed machinery for the xp.<dish> table lines: the same pure text step on the kit's parser, the same History / atomic write /
# change-log path (CookMig.kit / saved / logLine - same WHO), its own run-once marker XP_TBL_MARK. Compiled after CookXpMig and before the
# plugin: setup() calls it right after CookXpMig.migrate, BEFORE CookCfg.load + CfgPub.start.
_TBL = sorted(d for d in DISHES if XP[d] != XP_OLD[d])
tmig = pool.makeClass(PKG + ".CookTblMig")
F(tmig, "public static final String[] KEYS = %s;" % jstr_arr(["xp." + d for d in _TBL]))
F(tmig, "public static final String[] LOGKEYS = %s;" % jstr_arr(["xp[" + d + "]" for d in _TBL]))
F(tmig, "public static final String[] OLDS = %s;" % jstr_arr([str(XP_OLD[d]) for d in _TBL]))
F(tmig, "public static final String[] STOPS = %s;" % jstr_arr([str(STOPGAP_014.get(d, "")) for d in _TBL]))
F(tmig, "public static final String[] NEWS = %s;" % jstr_arr([str(XP[d]) for d in _TBL]))
F(tmig, "public static final String[] HELP_OLD = %s;" % jstr_arr(XP_HELP_OLD))
F(tmig, "public static final String[] HELP_NEW = %s;" % jstr_arr(XP_HELP_NEW))
F(tmig, "public static final String WHAT = \"before the 0.1.5 Cooking XP by difficulty update\";")
F(tmig, "public static final String MARK = %s;" % json.dumps(XP_TBL_MARK))
F(tmig, "public static final String MARK_ID = %s;" % json.dumps(XP_TBL_MARK_ID))
Mk(tmig, r"""
public static int idx(String key) {
  if (key == null) return -1;
  for (int i = 0; i < KEYS.length; i++) if (KEYS[i].equals(key)) return i;
  return -1;
}""")
Mk(tmig, r"""
public static boolean isOld(int i, String v) {
  if (i < 0 || v == null) return false;
  return v.equals(OLDS[i]) || (STOPS[i].length() > 0 && v.equals(STOPS[i]));
}""")
Mk(tmig, r"""
public static int helpIdx(String s) {
  for (int i = 0; i < HELP_OLD.length; i++) if (HELP_OLD[i].equals(s)) return i;
  return -1;
}""")
# pure text step (ISO-8859-1 chars in and out; lines read with the kit's own parser). null = nothing to do: XP_TBL_MARK_ID is already in a
# comment line. Else Object[]{ new text, "xp.A 3650 -> 1050, ..." or "", kept notes joined by \n or null, String[] { logkey, old, new, ... }
# }. Per key the LAST entry decides (what java.util.Properties keeps): a one-line entry holding exactly OLDS[i] or STOPS[i] -> every one-line
# entry of the key holding one of them gets NEWS[i] (value text only: key, separator and CR stay); anything else is kept (a custom value
# or a continued entry is noted; already NEWS[i] or missing is silent). Comment lines equal to HELP_OLD[j] become HELP_NEW[j] (1:1, CR
# kept). The marker goes above the run of non-blank comment lines directly on top of the FIRST xp.* entry (no run: right above it), else
# the same way above the file's first entry, else on top. Every line is scanned from the start of a logical line, so a comment is never
# the tail of a continued entry and the marker is never swallowed.
Mk(tmig, r"""
public static Object[] update(String text) {
  String[] raw = text.split("\n", -1);
  java.util.ArrayList l = new java.util.ArrayList();
  for (int i = 0; i < raw.length; i++) {
    String s0 = raw[i];
    if (s0.endsWith("\r")) s0 = s0.substring(0, s0.length() - 1);
    l.add(s0);
  }
  int n = KEYS.length;
  String[] eff = new String[n];
  boolean[] multi = new boolean[n];
  int ax = -1;
  int af = -1;
  int com = -1;
  int run = -1;
  int k = 0;
  while (k < l.size()) {
    String s = (String) l.get(k);
    if (@PKG@.CfgFile.isComment(s)) {
      if (s.indexOf(MARK_ID) >= 0) return null;
      if (s.trim().length() > 0) {
        if (com < 0 || com != k - 1) run = k;
        com = k;
      }
      k++;
      continue;
    }
    int e = @PKG@.CfgFile.end(l, k);
    String key = @PKG@.CfgFile.key(s);
    int above = (com >= 0 && com == k - 1) ? run : k;
    if (af < 0) af = above;
    if (ax < 0 && key != null && key.startsWith("xp.")) ax = above;
    int ki = idx(key);
    if (ki >= 0) {
      eff[ki] = @PKG@.CfgFile.value(l, k).trim();
      multi[ki] = e > k;
    }
    k = e + 1;
  }
  int at = 0;
  if (ax >= 0) at = ax;
  else if (af >= 0) at = af;
  boolean[] mig = new boolean[n];
  StringBuilder chg = new StringBuilder();
  StringBuilder kept = new StringBuilder();
  java.util.ArrayList rows = new java.util.ArrayList();
  for (int i = 0; i < n; i++) {
    String v = eff[i];
    if (v == null) continue;
    if (!multi[i] && isOld(i, v)) {
      mig[i] = true;
      if (chg.length() > 0) chg.append(", ");
      chg.append(KEYS[i]).append(" ").append(v).append(" -> ").append(NEWS[i]);
      rows.add(LOGKEYS[i]);
      rows.add(v);
      rows.add(NEWS[i]);
    } else if (multi[i] || !v.equals(NEWS[i])) {
      if (kept.length() > 0) kept.append("\n");
      kept.append(KEYS[i]).append("=").append(@PKG@.CfgRows.oneLine(v)).append(" kept (custom) - the 0.1.5 default is ").append(NEWS[i]);
    }
  }
  java.util.ArrayList out = new java.util.ArrayList();
  k = 0;
  while (k < l.size()) {
    String s2 = (String) l.get(k);
    if (@PKG@.CfgFile.isComment(s2)) {
      int h = helpIdx(s2);
      if (h >= 0) out.add(HELP_NEW[h] + (raw[k].endsWith("\r") ? "\r" : ""));
      else out.add(raw[k]);
      k++;
      continue;
    }
    int e2 = @PKG@.CfgFile.end(l, k);
    int i2 = idx(@PKG@.CfgFile.key(s2));
    if (i2 >= 0 && mig[i2] && e2 == k && isOld(i2, @PKG@.CfgFile.value(l, k).trim())) {
      String cr1 = raw[k].endsWith("\r") ? "\r" : "";
      out.add(s2.substring(0, @PKG@.CfgFile.valStart(s2)) + NEWS[i2] + cr1);
    } else {
      for (int q = k; q <= e2; q++) out.add(raw[q]);
    }
    k = e2 + 1;
  }
  String cr = text.indexOf("\r\n") >= 0 ? "\r" : "";
  String crA = at + 1 < raw.length ? (raw[at].endsWith("\r") ? "\r" : "") : cr;
  out.add(at, MARK + crA);
  StringBuilder sb = new StringBuilder(text.length() + MARK.length() + 16);
  for (int i = 0; i < out.size(); i++) { if (i > 0) sb.append('\n'); sb.append((String) out.get(i)); }
  return new Object[] { sb.toString(), chg.toString(), kept.length() > 0 ? kept.toString() : null, (String[]) rows.toArray(new String[0]) };
}""")
# setup(), right after CookXpMig.migrate and BEFORE CookCfg.load() + CfgPub.start: the file before this update becomes a History version
# (verified by CookMig.saved before the rewrite), the new text is written with the kit's atomicWrite (ISO-8859-1 bytes), one change-log
# line per changed entry, one INFO line (+ one per kept custom value). Returns the INFO line(s) joined by \n ("" = nothing done: no file,
# marker already there, or a failure - WARN, file untouched, the next start tries again)
Mk(tmig, r"""
public static synchronized String migrate() {
  java.nio.file.Path f = @PKG@.CookCfg.FILE;
  if (f == null) return "";
  try {
    if (!java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) return "";
    byte[] old = java.nio.file.Files.readAllBytes(f);
    Object[] r = update(new String(old, "ISO-8859-1"));
    if (r == null) return "";
    byte[] data = ((String) r[0]).getBytes("ISO-8859-1");
    @PKG@.CookMig.kit(f.toAbsolutePath().getParent());
    @PKG@.CfgHist.snapshot(0, old, @PKG@.CfgHist.stamp(), @PKG@.CookMig.WHO, WHAT);
    if (!@PKG@.CookMig.saved(old)) {
      @PKG@.CookCfg.warn("cooking.properties NOT updated to the 0.1.5 Cooking XP by difficulty: the old file could not be kept in " + @PKG@.CfgHist.DIR + " (the file is used as it is; the next start tries again)");
      return "";
    }
    @PKG@.CfgRows.atomicWrite(f, data);
    String[] rows = (String[]) r[3];
    for (int i = 0; i + 2 < rows.length; i += 3) @PKG@.CfgLog.enqueue(@PKG@.CookMig.logLine(rows[i], rows[i + 1], rows[i + 2]));
    if (rows.length > 0) @PKG@.CfgLog.flush();
    String chg = (String) r[1];
    String kept = (String) r[2];
    String msg = null;
    if (chg.length() > 0) msg = "cooking.properties updated to the 0.1.5 Cooking XP by difficulty (" + (rows.length / 3) + " XP per craft line(s) on old defaults): " + chg + " (Skyy 2026-10-04: easier dishes pay less XP, multi-step dishes more; the old file is in config-history; Server Setup -> Changes can undo each line)";
    else if (kept != null) msg = "cooking.properties: the XP per craft lines were changed by hand - kept, nothing changed (0.1.5 Cooking XP by difficulty marker added)";
    else msg = "cooking.properties: no XP per craft line on an old default - nothing changed (0.1.5 Cooking XP by difficulty marker added)";
    @PKG@.CookCfg.info(msg);
    if (kept == null) return msg;
    String[] ks = kept.split("\n");
    for (int i = 0; i < ks.length; i++) @PKG@.CookCfg.info(ks[i]);
    return msg + "\n" + kept;
  } catch (Throwable t) {
    @PKG@.CookCfg.warn("could not update cooking.properties to the 0.1.5 Cooking XP by difficulty (the file is used as it is): " + t);
    return "";
  }
}""")
'''
rep('''# setup(), right after CookMig.migrate and BEFORE CookCfg.load() + CfgPub.start: the file before this update becomes a History version
# (verified by CookMig.saved before the rewrite), the new text is written with the kit's atomicWrite (ISO-8859-1 bytes), one change-log
# line when the value changed, one INFO line (+ one for a kept custom value). Returns the INFO line(s) joined by \\n ("" = nothing done: no
# file, marker already there, or a failure - WARN, file untouched, the next start tries again)
''', '''# (CookXpMig.migrate below; 0.1.5 CookTblMig follows it)
# setup(), right after CookMig.migrate and BEFORE CookCfg.load() + CfgPub.start: the file before this update becomes a History version
# (verified by CookMig.saved before the rewrite), the new text is written with the kit's atomicWrite (ISO-8859-1 bytes), one change-log
# line when the value changed, one INFO line (+ one for a kept custom value). Returns the INFO line(s) joined by \\n ("" = nothing done: no
# file, marker already there, or a failure - WARN, file untouched, the next start tries again)
''')
# insert CookTblMig right after CookXpMig.migrate's source (the end of its Mk block: the unique 0.1.4 WARN text, then the closing)
_anchor = '''    @PKG@.CookCfg.warn("could not update cooking.properties to the 0.1.4 Cooking XP default (the file is used as it is): " + t);
    return "";
  }
}""")
'''
rep(_anchor, _anchor + TBL_MIG)
rep("for c in (cfg, hk, mig, xmig, ck,", "for c in (cfg, hk, mig, xmig, tmig, ck,")
rep('''  @PKG@.CookXpMig.migrate();
  String s = @PKG@.CookCfg.load();''', '''  @PKG@.CookXpMig.migrate();
  @PKG@.CookTblMig.migrate();
  String s = @PKG@.CookCfg.load();''')

# ---------------------------------------------------------------------------------------------------------------- build self-checks
CHECK_015 = r'''
# 0.1.5 self-check: the compiled XP table, the default text (marker + new help above the xp block), and the COMPILED one-time update
# (CookTblMig.update, the pure text step) on the shapes it meets in the field. The harness (SkyyCooking/test_skyycooking_0.1.5.py) runs
# migrate() itself on scratch copies of the live file.
_JTm = jpype.JClass(PKG + ".CookTblMig", loader=_ld)
if dict(zip([str(x) for x in _JCfg.XP_IDS], [int(x) for x in _JCfg.XP_VALS])) != XP:
    raise SystemExit("self-check 0.1.5: compiled CookCfg.XP_IDS / XP_VALS are not the difficulty table")
if [str(x) for x in _JTm.KEYS] != ["xp." + d for d in _TBL] or [str(x) for x in _JTm.NEWS] != [str(XP[d]) for d in _TBL] \
        or [str(x) for x in _JTm.OLDS] != [str(XP_OLD[d]) for d in _TBL] or str(_JTm.MARK) != XP_TBL_MARK or len(_TBL) != len(DISHES):
    raise SystemExit("self-check 0.1.5: compiled CookTblMig tables are not the build's (%d keys)" % len(_TBL))
_blk_new = XP_TBL_MARK + "\n" + "\n".join(XP_HELP_NEW) + "\nxp.default=%d\n" % XP_DEFAULT
if DEFAULTS_TEXT.count(_blk_new) != 1 or any(h in DEFAULTS_TEXT for h in XP_HELP_OLD):
    raise SystemExit("self-check 0.1.5: the default text must carry the marker + the new help lines right above xp.default")
def _tm(t):
    r = _JTm.update(t)
    return None if r is None else (str(r[0]), str(r[1]), None if r[2] is None else str(r[2]), [str(x) for x in r[3]])
def _f014(tab):     # a fresh 0.1.4 file (header line aside) with these dish values
    t = DEFAULTS_TEXT.replace(_blk_new, "\n".join(XP_HELP_OLD) + "\nxp.default=%d\n" % XP_DEFAULT)
    for d in DISHES:
        t = t.replace("\nxp.%s=%d\n" % (d, XP[d]), "\nxp.%s=%d\n" % (d, tab[d]))
    return t
_chg = ", ".join("xp.%s %d -> %d" % (d, XP_OLD[d], XP[d]) for d in _TBL)
_rows = [x for d in _TBL for x in ("xp[%s]" % d, str(XP_OLD[d]), str(XP[d]))]
if _tm(_f014(XP_OLD)) != (DEFAULTS_TEXT, _chg, None, _rows):
    raise SystemExit("self-check 0.1.5: CookTblMig.update of a fresh 0.1.4 file is not exactly the 0.1.5 default text: %r" % (_tm(_f014(XP_OLD)),)[:600])
_sg = dict(XP_OLD, **STOPGAP_014)
_r = _tm(_f014(_sg))
if _r is None or _r[0] != DEFAULTS_TEXT or len(_r[3]) != 3 * len(_TBL) or _r[2] is not None \
        or any("xp[%s]" % d not in _r[3] or str(STOPGAP_014[d]) != _r[3][_r[3].index("xp[%s]" % d) + 1] for d in STOPGAP_014):
    raise SystemExit("self-check 0.1.5: the 2026-10-04 stopgap kebab values must be replaced like old defaults: %r" % (_r,))
_cu = dict(XP_OLD, Food_Pie_Meat=30000, Food_Kebab_Vegetable=1700)
_r = _tm(_f014(_cu))
if _r is None or "\nxp.Food_Pie_Meat=30000\n" not in _r[0] or "\nxp.Food_Kebab_Vegetable=1700\n" not in _r[0] \
        or _r[2] != "xp.Food_Kebab_Vegetable=1700 kept (custom) - the 0.1.5 default is %d\nxp.Food_Pie_Meat=30000 kept (custom) - the 0.1.5 default is %d" % (XP["Food_Kebab_Vegetable"], XP["Food_Pie_Meat"]) \
        or len(_r[3]) != 3 * (len(_TBL) - 2):
    raise SystemExit("self-check 0.1.5: hand-set values must be kept and noted: %r" % (_r,))
if _JTm.update(DEFAULTS_TEXT) is not None:
    raise SystemExit("self-check 0.1.5: CookTblMig.update must leave a marked file alone")
for _nl in ("\n", "\r\n"):
    _h = "# SkyyCooking 0.1 - cooking.properties\nenabled=true\nxpMultiplier=0.5\n" + "\n".join(XP_HELP_OLD) + "\nxp.default=1000\nxp.Food_Bread=12900\nxp.Food_Kebab_Meat=2600\nxp.Ingredient_Flour=1425\n"
    _w = "# SkyyCooking 0.1 - cooking.properties\nenabled=true\nxpMultiplier=0.5\n" + XP_TBL_MARK + "\n" + "\n".join(XP_HELP_NEW) + "\nxp.default=1000\nxp.Food_Bread=%d\nxp.Food_Kebab_Meat=%d\nxp.Ingredient_Flour=1425\n" % (XP["Food_Bread"], XP["Food_Kebab_Meat"])
    if _tm(_h.replace("\n", _nl)) != (_w.replace("\n", _nl), "xp.Food_Bread 12900 -> %d, xp.Food_Kebab_Meat 2600 -> %d" % (XP["Food_Bread"], XP["Food_Kebab_Meat"]), None,
                                      ["xp[Food_Bread]", "12900", str(XP["Food_Bread"]), "xp[Food_Kebab_Meat]", "2600", str(XP["Food_Kebab_Meat"])]):
        raise SystemExit("self-check 0.1.5: CookTblMig.update of the live 0.1 shape (%r) is wrong: %r" % (_nl, _tm(_h.replace("\n", _nl))))
if _tm("enabled=true\nmaxGrade=12\n") != (XP_TBL_MARK + "\nenabled=true\nmaxGrade=12\n", "", None, []) or _tm("") != (XP_TBL_MARK + "\n", "", None, []):
    raise SystemExit("self-check 0.1.5: a file without xp lines must get only the marker (above its first entry / on top)")
print("0.1.5 checks: compiled XP table = the difficulty table (%d dishes changed, ingredients kept); default text marker + help; "
      "CookTblMig.update: fresh 0.1.4 file -> the 0.1.5 default text, the 4 stopgap kebab values replaced, hand-set 30000 / 1700 kept + noted, "
      "the live 0.1 shape (LF + CRLF), marked file untouched, no xp line -> marker only" % len(_TBL))
'''
rep('''
jar = os.path.join(HERE, "SkyyCooking-%s.jar" % VERSION)''', CHECK_015 + '''
jar = os.path.join(HERE, "SkyyCooking-%s.jar" % VERSION)''')

out = s.replace(LF, NL)
open(dst, "w", encoding="utf8", newline="").write(out)
print("wrote %s (%d lines, %s line endings)" % (dst, out.count(LF), "CRLF" if NL == CR + LF else "LF"))
