"""Derive SkyyEssentials/build_skyyessentials_0.1.5.py from the LIVE 0.1.4 (build_skyyessentials_0.1.4.py = the tools/deploy_set.py SET pin).
Run:  python tools/essentials_0_1_5_patch.py   then   python SkyyEssentials/build_skyyessentials_0.1.5.py   (never --deploy: coordinated deploy)
SkyyEssentials uses patch scripts since 0.1.4: edit THIS file, never the generated build script.

0.1.5 = round 8, Skyy's 2026-09-25 answers (OPEN-QUESTIONS "Answer first" 1 + /trade 3 + Server Setup 18; research/Settings-Spec.md 3.11
refusing version; Decisions change notes 2026-09-25 #7a):
 1. PLAYER SWITCHES THAT BLOCK: tpa.requests ("Teleport requests") and msg.private ("Private messages") are registered (general, default ON).
    OFF refuses the sender: /tpa and /tpahere ("[TPA] X is not taking teleport requests." - nothing stored, no cooldown used); /msg, /tell,
    /w, /whisper, /reply and /r <text> ("X has private messages turned off - your message was not sent." - no echo of the text, LAST_PM
    untouched). One gate (EssStore.gate) for both. STAFF BYPASS: holders of skyyessentials.bypass still get through while the new Server
    Setup row privacy.staffBypass is on (default on). ONE staff test, the same as SkyyParty 0.1.5's: PermissionsModule.hasPermission(u,
    "skyyessentials.bypass") alone (ops via hytale:Admin's "*", rank groups via the node, a personal "-skyyessentials.bypass" honoured;
    false on any error); the node is registered in setup() (static registerPermission(String), ungrouped). Notices = SkyyParty's words:
    the sender gets "(sent anyway - staff bypass: <name> has <switch> off)", the target sees the sender as "<name> (staff)".
    A sender whose own msg.private is off gets the spec's "(Your own private messages are off ...)" note after a sent message.
 2. /trade: tradeCancelOnDamage default false (a hit never cancels a trade), but a trader who DIES (health <= 0 or the engine's
    DeathComponent) always ends the open trade (reason "death", the normal cancel path gives everything back). Start-up migration (TCfg.migrateDamage, before the config kit
    starts): ONLY a file whose single tradeCancelOnDamage line is exactly the old default "true" AND that no change log names (config-changes.log
    + its rotations, 0.1.2 "CONFIG tradeCancelOnDamage" lines in trades/trade.log) gets "false" - only that value text changes, verified,
    atomic; logged (server INFO line + one config-changes.log line "SkyyEssentials 0.1.5 update", status ok, so SkyyMenu Changes can Undo it).
 3. The warps page no longer moves the world spawn: the /warpadmin spawn row + its confirm views and the kit action rows spawn.set /
    spawn.reset are gone (SpawnTask, EssWarp.kitSpawn*/spawnSet/instanceErr/failed removed). World spawn = vanilla /spawn set (ops).
 + config kit 1.1 (the rebuild picks it up; asserted) with KEEP=10 old file versions (OPEN-QUESTIONS Server Setup 3, LOCKED: 10).
Everything else (commands, /trade, /r, warps editor, tpa, files, bridge keys, the other rows and pages) stays 0.1.4's.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyEssentials", "build_skyyessentials_0.1.4.py")
dst = os.path.join(ROOT, "SkyyEssentials", "build_skyyessentials_0.1.5.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
REG0 = s.count("registerCommand(")
SYS0 = s.count("registerSystem(")


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def cut(a, b, new=""):
    """replace everything from anchor a (included) up to anchor b (kept) with new"""
    global s
    assert s.count(a) == 1, "cut start count %d: %s" % (s.count(a), a[:120])
    assert s.count(b) == 1, "cut end count %d: %s" % (s.count(b), b[:120])
    i, j = s.index(a), s.index(b)
    assert i < j, "cut anchors out of order: %s / %s" % (a[:60], b[:60])
    s = s[:i] + new + s[j:]


# ================================================================================================ docstring + version + kit version
DOC = '''SkyyEssentials 0.1.5 - build script (javassist via jpype). GENERATED by tools/essentials_0_1_5_patch.py from the LIVE 0.1.4
(build_skyyessentials_0.1.4.py, the tools/deploy_set.py SET pin) - edit the patch, never this file.
Run:   python build_skyyessentials_0.1.5.py            -> SkyyEssentials/SkyyEssentials-0.1.5.jar   (never --deploy: tools/deploy_set.py)

0.1.5 (2026-09-28, round 8 - Skyy's 2026-09-25 answers: OPEN-QUESTIONS "Answer first" 1, /trade 3, Server Setup 18; Decisions change notes
2026-09-25 #7a; research/Settings-Spec.md 3.11, the REFUSING version):
  PLAYER SWITCHES THAT BLOCK THE SENDER (research/Settings-Spec.md 2.2 / 3.11 / section 6 answered "block"):
    tpa.requests ("Teleport requests") and msg.private ("Private messages") are registered in setup() next to tpa.updates (category
    general, default ON, settings:def: + settings:fn:register; no SkyyMenu = always on = 0.1.4 behaviour). One gate, EssStore.gate(target,
    key, sender): 0 = deliver (the target's switch is on), 1 = refuse, 2 = deliver through the staff bypass. The work is gated on purpose
    here (Settings-Spec 1.3 "the one deliberate exception").
    - /tpa and /tpahere (EssStore.request, after the usage / self / online checks, BEFORE tryAdd): OFF -> the sender gets "[TPA] <name> is
      not taking teleport requests." and nothing else happens (no request stored, no cooldown used, the target sees nothing). A request
      that was already pending when the target switched off can still be accepted or denied by the target (their own action).
    - /msg (tell, w, whisper), /reply and /r <text> (all end in EssStore.pm, after the part / empty / online / self checks, BEFORE the two
      say lines): OFF -> "<name> has private messages turned off - your message was not sent." to the sender only; the text is never echoed
      and LAST_PM is not updated (so /r keeps pointing at the previous partner). /r alone and /r <count> still run /redo for builders.
    - A sender whose OWN msg.private is off gets, after a message that was sent: "(Your own private messages are off, so other players
      cannot reply to you - /settings to turn them on.)" (spec 3.11).
    - STAFF BYPASS (Skyy lock; the SAME convention as SkyyParty 0.1.5's party invites): holders of the node skyyessentials.bypass still
      get through while the new Server Setup row privacy.staffBypass is on (default ON; category "Privacy", label "Staff get through
      blocked switches", help naming the node; also on /warpadmin -> Settings). Off = the switches refuse everyone. The ONE staff test
      (EssStore.isStaff) is PermissionsModule.get().hasPermission(sender, "skyyessentials.bypass") alone, inside try (fail closed: false on
      any error): ops pass through hytale:Admin's "*", rank groups through the node, and a personal deny "-skyyessentials.bypass"
      (SkyyRanks offers it) keeps even an op out - HytaleServer.jar PermissionsModule.hasPermission checks the user's own nodes (deny
      first) before any group. It runs only when the target's switch is off. setup() registers the node with the static
      PermissionsModule.registerPermission(String) (EssStore.regPerm; ungrouped, so no group is granted it - refreshVirtualGroups only
      copies registered groups; it shows in /perm list and SkyyRanks' node search; probed at build time).
      Notices (identical words on the three blocked paths - SkyyParty invite, /tpa, /msg): a bypassed request / message is delivered
      normally, the target's line names the sender "<name> (staff)" ("[TPA] <name> (staff) wants to teleport to you ...", "[<name> (staff)
      -> you] ..."), and the staff sender gets one INFO line "(sent anyway - staff bypass: <name> has teleport requests off)" / "... has
      private messages off)". The row is a TCfg loader key too (config.properties privacy.staffBypass=true, appended to older files).
    SkyyMenu 0.3.2 lists unknown keys at the end of the General tab (SetReg.rank 9000), so both rows show there until the next SkyyMenu adds
    them to SET_ORDER (its 0.3.2 build asserts they are NOT in SET_ORDER - that assert must go in SkyyMenu 0.3.3).
  /trade SURVIVES DAMAGE (OPEN-QUESTIONS /trade 3): tradeCancelOnDamage defaults to false (TCfg ROWS, the kit row, DEFAULT_TEXT, the
    field). A trader who DIES still ends the trade, whatever tradeCancelOnDamage says (review 2026-09-28): the 1 s position task on the
    trader's world thread (TStore.posTask) marks TSession.dead[side] when their health is <= 0 or the engine's DeathComponent
    (com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent, present from death until respawn) is on the player; the trade
    thread's tickSession then runs the normal cancelNow(s, "death", ...) path (escrow drained, record written, everything goes back via
    the usual delivery) and both players read "<name> died - trade cancelled. Everything you put in comes back to you."
    TCfg.migrateDamage runs inside TCfg.load at setup, BEFORE the config kit starts (the SkyyGuilds 0.1.3 migrateSkills pattern):
    only when the file has exactly ONE live tradeCancelOnDamage line, its value is exactly the old default "true", and no change log names
    the key (Skyy_SkyyEssentials/config-changes.log + .1-.3, and 0.1.2's "CONFIG tradeCancelOnDamage" lines in trades/trade.log; an
    unreadable log counts as "changed") does that value text become "false": every other byte stays (ISO-8859-1 byte exact, CRLF / LF
    kept), the re-parsed text must equal the old one except that key, written atomically, then the running value follows. Logged: one
    server INFO line and one config-changes.log line in the kit's format ("SkyyEssentials 0.1.5 update", via update, true -> false, ok),
    so SkyyMenu Server Setup -> Changes shows it with an Undo. A value an admin set (a logged change, "on", "yes", two lines, ...) is kept
    with one INFO line per start; "false" and a missing line (appended with the new default) log nothing.
  WARPS PAGE NO LONGER MOVES THE WORLD SPAWN (OPEN-QUESTIONS Server Setup 18): the /warpadmin spawn row (Set the world spawn here / Reset
    to the original), its two confirm views, and the config kit action rows spawn.set / spawn.reset (Server Setup -> Essentials -> Warps)
    are removed, with SpawnTask and EssWarp.kitSpawn / kitSpawnSet / kitSpawnReset / spawnSet / instanceErr / failed. The page is "Warps"
    (880 high); a help line says the world spawn is set with vanilla /spawn set. Vanilla keeps it staff-only: /spawn set is granted to
    hytale:WorldEditor (and ops), /spawn set default to hytale:Admin (HytaleServer.jar constants, 2026-09-28). Old config-changes.log
    lines for spawn.set / spawn.reset stay readable (SkyyMenu shows their key; no Undo on action lines).
  CONFIG KIT 1.1 (tools/skyycfg.py KIT_VERSION, asserted below; CfgRows.KIT): 0.1.4 was built on kit 1.0. The custom row tradeOpenMode's
    file line now runs TCfg.reloadKit after the write (kit 1.1 fix 3; reloadKit re-reads the live keys only, never replyShortcut). KEEP=10
    old versions per file (Skyy LOCKED 2026-09-25, was 20; older copies are pruned at the next write). Schema: 20 rows (21 - spawn.set -
    spawn.reset + privacy.staffBypass), 6 categories (+ privacy).
  Nothing else changes: every command, permission node, /trade, /r, the warps editor, tpa timings, files, bridge keys and the other rows.
  CHECKED in a bare JVM (2026-09-28; SkyyEssentials/test_skyyessentials_0.1.3.py adapted to 0.1.5 in a scratch folder, deleted afterwards;
    277 checks, 0 fails): all 61 classes load under -Xverify:all with HytaleServer.jar (no SpawnTask); defaults = 0.1.2's except
    tradeCancelOnDamage false + privacy.staffBypass true; a 0.1.2 CRLF file keeps every byte except the migrated value and gets the 5
    missing keys appended; one change-log line in the kit's format, listed by the kit's log op; a second start changes nothing; kit
    header 20 rows / 6 categories / KIT 1.1 / KEEP 10, no action rows, spawn.set answers unknown; console sets of privacy.staffBypass
    and tradeCancelOnDamage reach the fields; line-preserving writes, hand edit + reload, export / import preview unchanged; gate: switch
    on 0, off 1, a throwing Settings function 0; with a fake PermissionsModule provider (the engine's own getGroupsForUser / hasPermission
    code): an op and a skyyessentials.bypass holder pass (2), a plain player is refused (1), the bypass row off refuses staff too;
    bytecode: request gates before tryAdd, pm gates before the echo and LAST_PM, setup registers tpa.requests / tpa.updates / msg.private
    before CfgPub.start; hytale:Adventurer gets only the player command nodes; migration cases on a copy of the LIVE world's
    config.properties (migrates; kept when config-changes.log, its .2 rotation or trade.log name the key, when the log is unreadable, for
    "on", for two lines, for a read-only file (no tmp left); false and a 0.1.1 file untouched apart from the appended keys; CRLF + spaces
    byte exact; commented and continuation lines skipped); the warps page (Warps, 1120 x 880, no spawn ids or clicks, help line) and both
    settings pages (the ESS page's 6th row = the staff bypass) render with valid ids / anchors / targets; garbage ops never throw.
    (That run used the earlier group-OR-node staff test; the fix round below replaced it.)
  FIX ROUND (2026-09-28, same version - 0.1.5 never shipped): staff test = hasPermission(node) alone + the node registered in setup();
    row label / help and the bypass notices aligned with SkyyParty 0.1.5; death ends a trade. CHECKED in a bare JVM with the engine's
    real HytalePermissionsProvider (a scratch permissions.json) behind PermissionsModule.get(): an op (/op add = hytale:Admin) passes, a
    skyyessentials.bypass holder passes, a rank group holding the node passes, an op with a personal -skyyessentials.bypass is refused, a
    plain player is refused, no PermissionsModule = refused; regPerm lists the node in getRegisteredPermissions() with no groups.
  UNVERIFIED (needs the game): the refusals / bypass notes with two real accounts, the permission lookups on a real server (op via
    hytale:Admin, a granted skyyessentials.bypass, a SkyyRanks personal deny), the node in /perm list, both new rows on SkyyMenu 0.3.2's
    General tab, the migration line on the live world's first 0.1.5 start (a copy of the live config.properties migrates in the bare-JVM
    check), a trade surviving a hit, a trade ended by a death (and the items back after respawn).

'''
first = s.index('"""') + 3
s = s[:first] + DOC + s[first:]
rep('import skyycfg as CFG\n\nVERSION = "0.1.4"\n',
    'import skyycfg as CFG\n'
    '# 0.1.5: built on config kit 1.1 or newer (tools/CONFIG-CONTRACT.md "Kit versions")\n'
    'assert tuple(int(x) for x in getattr(CFG, "KIT_VERSION", "1.0").split(".")) >= (1, 1), "SkyyEssentials 0.1.5 needs config kit 1.1+"\n'
    '\nVERSION = "0.1.5"\n')

# ================================================================================================ probes (0.1.5 staff check)
rep('''PKG = "com.skyy.essentials"
ES = PKG + ".EssStore"
''', '''# 0.1.5: the staff bypass of the refusing player switches (EssStore.isStaff = hasPermission alone; EssStore.regPerm registers the node)
# and the trade death check (TStore.posTask)
PMODS = "com.hypixel.hytale.server.core.permissions.PermissionsModule"
DEATHC = "com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent"
for c, m in ((PMODS, "get"), (PMODS, "hasPermission"), (PMODS, "registerPermission"), (DEATHC, "getComponentType")):
    B.probe(pool, c, m)
_pmc = pool.get(PMODS)
assert any(str(x.getSignature()) == "(Ljava/lang/String;)V" and J["Modifier"].isStatic(x.getModifiers())
           for x in _pmc.getDeclaredMethods("registerPermission")), "PermissionsModule.registerPermission(String) static void is missing"
assert any(str(x.getSignature()) == "(Ljava/util/UUID;Ljava/lang/String;)Z" and not J["Modifier"].isStatic(x.getModifiers())
           for x in _pmc.getDeclaredMethods("hasPermission")), "PermissionsModule.hasPermission(UUID, String) boolean is missing"
assert any(J["Modifier"].isStatic(x.getModifiers()) and str(x.getSignature()).startswith("()")
           for x in pool.get(DEATHC).getDeclaredMethods("getComponentType")), "DeathComponent.getComponentType() static is missing"

PKG = "com.skyy.essentials"
ES = PKG + ".EssStore"
''')

# ================================================================================================ EssStore: bypass fields + gate
rep('''es.addField(CtField.make("public static volatile boolean PART_MSG = true;", es))
''', '''es.addField(CtField.make("public static volatile boolean PART_MSG = true;", es))
# 0.1.5: Server Setup row privacy.staffBypass (default on): holders of skyyessentials.bypass (ops included, through "*") still reach a
# player whose refusing switch (tpa.requests / msg.private) is off
es.addField(CtField.make("public static volatile boolean STAFF_BYPASS = true;", es))
es.addField(CtField.make('public static final String BYPASS_PERM = "skyyessentials.bypass";', es))
''')
rep('''es.addMethod(CtNewMethod.make("""
public static String key(java.util.UUID a, java.util.UUID b) { return a.toString() + ">" + b.toString(); }""", es))''',
    '''# ---- 0.1.5 the refusing switches (Settings-Spec 3.11, Skyy 2026-09-25: BLOCK the sender) + the staff bypass. isStaff = hasPermission(u,
# skyyessentials.bypass) ALONE (the same test as SkyyParty's skyyparty.bypass): the engine checks the user's own nodes first (a personal
# "-skyyessentials.bypass" denies, even for an op), then each group (hytale:Admin's "*" = every op; a rank group through the node).
# Fail closed: false on any error (a bare JVM has no PermissionsModule).
es.addMethod(CtNewMethod.make(f"""
public static boolean isStaff(java.util.UUID u) {{
  if (u == null) return false;
  try {{
    {PMODS} pm = {PMODS}.get();
    if (pm == null) return false;
    return pm.hasPermission(u, BYPASS_PERM);
  }} catch (Throwable t) {{ return false; }}
}}""", es))
# setup() registers the node: the static registerPermission(String) makes an entry with NO groups, so no group is granted it
# (refreshVirtualGroups only copies registered groups); it then shows in /perm list and SkyyRanks' node search. Never throws.
es.addMethod(CtNewMethod.make(f"""
public static boolean regPerm() {{
  try {{
    {PMODS}.registerPermission(BYPASS_PERM);
    return true;
  }} catch (Throwable t) {{
    warn("could not register the permission node " + BYPASS_PERM + " (the staff bypass still works): " + t);
    return false;
  }}
}}""", es))
# 0 = deliver (the target's switch is on, or no SkyyMenu), 1 = refuse (switched off), 2 = deliver through the staff bypass. The permission
# lookup only runs when the switch is off. Never throws (notifyOn and isStaff catch everything).
es.addMethod(CtNewMethod.make("""
public static int gate(java.util.UUID target, String key, java.util.UUID sender) {
  if (notifyOn(target, key)) return 0;
  if (STAFF_BYPASS && isStaff(sender)) return 2;
  return 1;
}""", es))
es.addMethod(CtNewMethod.make("""
public static String key(java.util.UUID a, java.util.UUID b) { return a.toString() + ">" + b.toString(); }""", es))''')

# /tpa + /tpahere: refused BEFORE tryAdd (nothing stored, no cooldown used); the staff note after the normal lines
rep('''  String them = target.getUsername();
  String err = tryAdd(pr.getUuid(), target.getUuid(), here, me, them);''', '''  String them = target.getUsername();
  // 0.1.5: the target's tpa.requests switch refuses the request (nothing stored, no cooldown used); staff pass while the bypass is on
  int g = gate(target.getUuid(), "tpa.requests", pr.getUuid());
  if (g == 1) {{ say(pr, "[TPA] " + them + " is not taking teleport requests.", ERR); return; }}
  String err = tryAdd(pr.getUuid(), target.getUuid(), here, me, them);''')
# staff bypass notices - the same words as SkyyParty's invite: the target's line names the sender "<name> (staff)" (the /tpaccept and
# /tpdeny hints keep the plain name), the sender gets "(sent anyway - staff bypass: <name> has teleport requests off)"
rep('''  String ex = secs(EXPIRE_MS);
  if (here) {{
    say(pr, "[TPA] Asked " + them + " to teleport to you. They have " + ex + " to accept. /tpacancel to cancel.", INFO);
    say(target, "[TPA] " + me + " wants you to teleport to them. /tpaccept " + me + " to go, /tpdeny " + me + " to refuse (" + ex + ").", INFO);
  }} else {{
    say(pr, "[TPA] Request sent to " + them + ". They have " + ex + " to accept. /tpacancel to cancel.", INFO);
    say(target, "[TPA] " + me + " wants to teleport to you. /tpaccept " + me + " to allow, /tpdeny " + me + " to refuse (" + ex + ").", INFO);
  }}
}}""", es))''', '''  String ex = secs(EXPIRE_MS);
  String who = me + (g == 2 ? " (staff)" : "");
  if (here) {{
    say(pr, "[TPA] Asked " + them + " to teleport to you. They have " + ex + " to accept. /tpacancel to cancel.", INFO);
    say(target, "[TPA] " + who + " wants you to teleport to them. /tpaccept " + me + " to go, /tpdeny " + me + " to refuse (" + ex + ").", INFO);
  }} else {{
    say(pr, "[TPA] Request sent to " + them + ". They have " + ex + " to accept. /tpacancel to cancel.", INFO);
    say(target, "[TPA] " + who + " wants to teleport to you. /tpaccept " + me + " to allow, /tpdeny " + me + " to refuse (" + ex + ").", INFO);
  }}
  if (g == 2) say(pr, "[TPA] (sent anyway - staff bypass: " + them + " has teleport requests off)", INFO);
}}""", es))''')
# /msg, /tell, /w, /whisper, /reply, /r <text> all end here: refused BEFORE the echo (the text is never shown back), LAST_PM untouched
rep('''  if (target.getUuid().equals(pr.getUuid())) {{ say(pr, "You can't message yourself.", ERR); return; }}
  say(pr, "[you -> " + target.getUsername() + "] " + text, PM);
  say(target, "[" + pr.getUsername() + " -> you] " + text, PM);
  LAST_PM.put(pr.getUuid(), target.getUuid());
  LAST_PM.put(target.getUuid(), pr.getUuid());
}}""", es))''', '''  if (target.getUuid().equals(pr.getUuid())) {{ say(pr, "You can't message yourself.", ERR); return; }}
  // 0.1.5: the target's msg.private switch refuses the message (no echo of the text, LAST_PM untouched); staff pass while the bypass is on
  int g = gate(target.getUuid(), "msg.private", pr.getUuid());
  if (g == 1) {{ say(pr, target.getUsername() + " has private messages turned off - your message was not sent.", ERR); return; }}
  say(pr, "[you -> " + target.getUsername() + "] " + text, PM);
  // staff bypass notices - the same words as SkyyParty's invite and /tpa: "<name> (staff)" for the target, "(sent anyway - ...)" for the sender
  say(target, "[" + pr.getUsername() + (g == 2 ? " (staff)" : "") + " -> you] " + text, PM);
  LAST_PM.put(pr.getUuid(), target.getUuid());
  LAST_PM.put(target.getUuid(), pr.getUuid());
  if (g == 2) say(pr, "(sent anyway - staff bypass: " + target.getUsername() + " has private messages off)", INFO);
  if (!notifyOn(pr.getUuid(), "msg.private")) say(pr, "(Your own private messages are off, so other players cannot reply to you - /settings to turn them on.)", INFO);
}}""", es))''')

# ================================================================================================ TCfg loader rows
rep('''    ("tradeCancelOnDamage", "Cancel when a trader is hurt", "bool", "DAMAGE", 0, 1, "true", "",
     "tradeCancelOnDamage: true = a trade is cancelled (everything goes back) when either player loses health."),''',
    '''    ("tradeCancelOnDamage", "Cancel when a trader is hurt", "bool", "DAMAGE", 0, 1, "false", "",
     "tradeCancelOnDamage: false (the default since 0.1.5) = taking damage never cancels a trade. true = a trade is cancelled (everything goes back) when either player loses health. A trader who dies always ends the trade."),''')
rep('''     "tpa.cooldownSeconds: seconds a player waits before sending the next teleport request (0-300)."),
]
IDX = dict((r[0], i) for i, r in enumerate(ROWS))''', '''     "tpa.cooldownSeconds: seconds a player waits before sending the next teleport request (0-300)."),
    # 0.1.5 (field in EssStore)
    ("privacy.staffBypass", "Staff get through blocked switches", "bool", "@ES@.STAFF_BYPASS", 0, 1, "true", "",
     "privacy.staffBypass: true = players with skyyessentials.bypass (ops included) still reach a player who turned Teleport requests or Private messages off in /settings. false = those switches refuse everyone."),
]
IDX = dict((r[0], i) for i, r in enumerate(ROWS))''')
rep('''FILE_ORDER = [REPLY_IDX, IDX["part.tpa"], IDX["part.msg"], IDX["tpa.expireSeconds"], IDX["tpa.cooldownSeconds"]] + list(range(0, 13))
FILE_BLOCKS = {1: "# ---- teleports and private messages (SkyyEssentials 0.1.3) ----", 5: "# ---- /trade (SkyyEssentials 0.1.2) ----"}''',
    '''FILE_ORDER = [REPLY_IDX, IDX["part.tpa"], IDX["part.msg"], IDX["tpa.expireSeconds"], IDX["tpa.cooldownSeconds"],
              IDX["privacy.staffBypass"]] + list(range(0, 13))
FILE_BLOCKS = {1: "# ---- teleports and private messages (SkyyEssentials 0.1.3) ----", 6: "# ---- /trade (SkyyEssentials 0.1.2) ----"}''')
rep('''    + ", " + SLOTS + " slots, countdown " + COUNTDOWN_S + " s, coins " + (COINS ? "allowed" : "off") + ", openMode " + (PAGE_MODE ? "page" : "chest")
    + "; tpa " + (@ES@.PART_TPA ? "on" : "OFF") + " (expire " + (@ES@.EXPIRE_MS / 1000L) + " s, cooldown " + (@ES@.COOLDOWN_MS / 1000L) + " s), msg " + (@ES@.PART_MSG ? "on" : "OFF");''',
    '''    + ", " + SLOTS + " slots, countdown " + COUNTDOWN_S + " s, coins " + (COINS ? "allowed" : "off") + ", openMode " + (PAGE_MODE ? "page" : "chest")
    + ", damage " + (DAMAGE ? "cancels" : "ignored")
    + "; tpa " + (@ES@.PART_TPA ? "on" : "OFF") + " (expire " + (@ES@.EXPIRE_MS / 1000L) + " s, cooldown " + (@ES@.COOLDOWN_MS / 1000L) + " s), msg " + (@ES@.PART_MSG ? "on" : "OFF")
    + ", staff bypass " + (@ES@.STAFF_BYPASS ? "on" : "off");''')

# ================================================================================================ TCfg.migrateDamage (setup only)
MIGRATE = r'''# ---- 0.1.5: the tradeCancelOnDamage migration (setup only, inside load(), BEFORE the config kit starts - the kit owns every write after
# that; the SkyyGuilds 0.1.3 migrateSkills pattern). Only ONE live line holding exactly the old default "true", in a file no change log
# names the key in, becomes "false"; only that value text changes (byte exact otherwise), verified, atomic, logged.
M(tcfg, r"""
public static boolean lineWs(char c) {
  return c == ' ' || c == '\t' || c == 12;
}""")
# where the value of a live <key> line starts (Properties syntax: white space, the key, then white space and / or one = or :); -1 = not a
# line of that key. body = the line without its CR.
M(tcfg, r"""
public static int keyValueAt(String body, String key) {
  int n = body.length();
  int i = 0;
  while (i < n && lineWs(body.charAt(i))) i++;
  if (!body.startsWith(key, i)) return -1;
  i = i + key.length();
  int j = i;
  while (j < n && lineWs(body.charAt(j))) j++;
  if (j < n && (body.charAt(j) == '=' || body.charAt(j) == ':')) {
    j++;
    while (j < n && lineWs(body.charAt(j))) j++;
  } else if (j == i && j < n) return -1;
  return j;
}""")
# a logical line that continues on the next one (an odd number of trailing backslashes)
M(tcfg, r"""
public static boolean lineCont(String body) {
  int k = 0;
  int i = body.length() - 1;
  while (i >= 0 && body.charAt(i) == '\\') { k++; i--; }
  return k % 2 == 1;
}""")
M(tcfg, r"""
public static boolean lineSkip(String body) {
  int n = body.length();
  int i = 0;
  while (i < n && lineWs(body.charAt(i))) i++;
  return i >= n || body.charAt(i) == '#' || body.charAt(i) == '!';
}""")
# does this log file contain the needle? A missing file = no; an unreadable one = YES (never migrate on a guess). Streamed line by line
# (trade.log can be large), ISO-8859-1 so no byte can fail to decode (the needles are ASCII).
M(tcfg, r"""
public static boolean logNames(java.nio.file.Path f, String needle) {
  if (f == null || !java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) return false;
  java.io.BufferedReader r = null;
  try {
    r = new java.io.BufferedReader(new java.io.InputStreamReader(java.nio.file.Files.newInputStream(f, new java.nio.file.OpenOption[0]), "ISO-8859-1"));
    String l = r.readLine();
    while (l != null) {
      if (l.indexOf(needle) >= 0) return true;
      l = r.readLine();
    }
    return false;
  } catch (Throwable t) {
    return true;
  } finally {
    try { if (r != null) r.close(); } catch (Throwable t2) { }
  }
}""")
# was tradeCancelOnDamage ever changed (in game, by command, by import / restore / undo, a hand edit the kit noticed, 0.1.2's /tradeadmin
# config)? config-changes.log + its 3 rotations (key column) and 0.1.2's "CONFIG <key> old -> new" lines in trades/trade.log
M(tcfg, r"""
public static boolean damageTouched() {
  if (DIR == null) return true;
  java.nio.file.Path c = DIR.resolve("config-changes.log");
  if (logNames(c, "\ttradeCancelOnDamage\t")) return true;
  for (int n = 1; n <= 3; n++) if (logNames(c.resolveSibling("config-changes.log." + n), "\ttradeCancelOnDamage\t")) return true;
  return logNames(LOGF, "CONFIG tradeCancelOnDamage ");
}""")
# one line in the kit's change-log format (time, name, uuid, via, key, old, new, status) so SkyyMenu Server Setup -> Changes lists the
# migration (with an Undo: status ok). Written before the kit starts, so nothing else appends to the file at the same time.
M(tcfg, r"""
public static void changeLine(String key, String old, String nw) {
  if (DIR == null) return;
  String t = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss").format(java.time.LocalDateTime.now());
  appendLine(DIR.resolve("config-changes.log"), t + "\tSkyyEssentials @VERSION@ update\t-\tupdate\t" + key + "\t" + old + "\t" + nw + "\tok");
}""")
# the rewritten text must parse to the same keys and values, except tradeCancelOnDamage = false
M(tcfg, r"""
public static boolean sameExceptDamage(java.util.Properties a, java.util.Properties b) {
  if (a.size() != b.size()) return false;
  String bv = b.getProperty("tradeCancelOnDamage");
  if (bv == null || !bv.trim().equals("false")) return false;
  java.util.Iterator it = a.stringPropertyNames().iterator();
  while (it.hasNext()) {
    String k = (String) it.next();
    if (k.equals("tradeCancelOnDamage")) continue;
    String y = b.getProperty(k);
    if (y == null || !y.equals(a.getProperty(k))) return false;
  }
  return true;
}""")
# p = the properties load() parsed. The running value follows the file only after the file says so (a failed rewrite keeps true running,
# so the file, the kit and the game always agree).
M(tcfg, r"""
public static void migrateDamage(java.util.Properties p) {
  String cur = p == null ? null : p.getProperty("tradeCancelOnDamage");
  if (cur == null || !cur.trim().equals("true")) return;
  String keep = " - kept: a trade is still cancelled when a trader takes damage. The new default is off: Server Setup > Essentials > Trade > Cancel when a trader is hurt.";
  if (damageTouched()) { info("config.properties: tradeCancelOnDamage=true was set by an admin (a change log names it)" + keep); return; }
  try {
    byte[] old = java.nio.file.Files.readAllBytes(@ES@.CFG);
    java.util.Properties before = new java.util.Properties();
    before.load(new java.io.ByteArrayInputStream(old));
    String bv = before.getProperty("tradeCancelOnDamage");
    if (bv == null || !bv.trim().equals("true")) { warn("config.properties changed while it was read - tradeCancelOnDamage not updated" + keep); return; }
    String text = new String(old, "ISO-8859-1");
    String[] lines = text.split("\n", -1);
    StringBuilder out = new StringBuilder(text.length() + 8);
    int live = 0;
    int changed = 0;
    boolean cont = false;
    for (int i = 0; i < lines.length; i++) {
      String l = lines[i];
      String body = l.endsWith("\r") ? l.substring(0, l.length() - 1) : l;
      if (cont) cont = lineCont(body);
      else if (!lineSkip(body)) {
        int at = keyValueAt(body, "tradeCancelOnDamage");
        if (at >= 0) {
          live++;
          if (body.startsWith("true", at) && body.substring(at + 4).trim().length() == 0) {
            l = l.substring(0, at) + "false" + l.substring(at + 4);
            changed++;
          }
        }
        cont = lineCont(body);
      }
      if (i > 0) out.append('\n');
      out.append(l);
    }
    if (live != 1 || changed != 1) { info("config.properties: tradeCancelOnDamage is written on " + live + " lines (edited by hand)" + keep); return; }
    byte[] nb = out.toString().getBytes("ISO-8859-1");
    java.util.Properties after = new java.util.Properties();
    after.load(new java.io.ByteArrayInputStream(nb));
    if (!sameExceptDamage(before, after)) { warn("config.properties: rewriting tradeCancelOnDamage would change more than that line - nothing written" + keep); return; }
    atomicWrite(@ES@.CFG, nb);
    DAMAGE = false;
    p.setProperty("tradeCancelOnDamage", "false");
    info("config.properties: tradeCancelOnDamage was still the old default (true) - now false, so taking damage no longer cancels a trade (Skyy 2026-09-25). Only that line changed; a value an admin set is never touched. Undo: Server Setup > Changes.");
    changeLine("tradeCancelOnDamage", "true", "false");
  } catch (Throwable x) {
    warn("could not update tradeCancelOnDamage in " + @ES@.CFG + keep + " (" + x + ")");
    try { java.nio.file.Files.deleteIfExists(@ES@.CFG.resolveSibling(@ES@.CFG.getFileName().toString() + ".tmp")); } catch (Throwable t2) { }
  }
}""")
'''
rep('''# start (setup): missing file -> written with the defaults; unreadable -> BROKEN''',
    MIGRATE + '''# start (setup): missing file -> written with the defaults; unreadable -> BROKEN''')
rep('''    BROKEN = false;
    if (n > 0) {
      String e = appendMissing(miss);
      if (e == null) info("config.properties: added " + n + " missing key(s) at the end with their defaults - every existing line kept");
    }
    return summary0();''', '''    BROKEN = false;
    if (n > 0) {
      String e = appendMissing(miss);
      if (e == null) info("config.properties: added " + n + " missing key(s) at the end with their defaults - every existing line kept");
    }
    migrateDamage(p);
    return summary0();''')

# ================================================================================================ config kit rows
rep('KIT_CATS = [("parts", "Parts"), ("tpa", "Teleports"), ("msg", "Messages"), ("warps", "Warps"), ("trade", "Trade")]',
    'KIT_CATS = [("parts", "Parts"), ("tpa", "Teleports"), ("msg", "Messages"), ("privacy", "Privacy"), ("warps", "Warps"), ("trade", "Trade")]')
rep('''     "field:TCfg.REPLY_FILE" + CF + "replyShortcut"),
    ("warps.editor", "Warps editor", "warps", "link", "", "", "", "warpadmin", "", "",
     "Add, move, rename, remove and visit the /warp warps. It also sets the world spawn.", ""),
    ("spawn.set", "Set the world spawn here", "warps", "action", "", "", "", "Set the world spawn here", "", "danger",
     "Moves the spawn of the world you stand in to your spot. New and respawning players arrive there.",
     "action:EssWarp.kitSpawnSet"),
    ("spawn.reset", "Reset the world spawn to the original", "warps", "action", "", "", "", "Reset the world spawn", "", "danger",
     "The world you stand in goes back to its original spawn point (like /spawn set default).",
     "action:EssWarp.kitSpawnReset"),''', '''     "field:TCfg.REPLY_FILE" + CF + "replyShortcut"),
    # 0.1.5: the staff bypass of the refusing player switches (tpa.requests, msg.private)
    # (same key, category, label and help pattern as SkyyParty 0.1.5's privacy.staffBypass)
    ("privacy.staffBypass", "Staff get through blocked switches", "privacy", "bool", "true", "", "", "", "", "live",
     "Players with skyyessentials.bypass (ops included) reach players who switched /tpa or /msg off.",
     "field:EssStore.STAFF_BYPASS" + CF + "privacy.staffBypass"),
    # 0.1.5: the warps page no longer moves the world spawn (spawn.set / spawn.reset action rows removed, Skyy 2026-09-25)
    ("warps.editor", "Warps editor", "warps", "link", "", "", "", "warpadmin", "", "",
     "Add, move, rename, remove and visit the /warp warps. World spawn: vanilla /spawn set (ops).", ""),''')
rep('''    ("tradeCancelOnDamage", "Cancel when a trader is hurt", "trade", "bool", "true", "", "", "", "", "live",
     "A trade is cancelled (everything goes back) when either player loses health.", "field:TCfg.DAMAGE" + CF + "tradeCancelOnDamage"),''',
    '''    ("tradeCancelOnDamage", "Cancel when a trader is hurt", "trade", "bool", "false", "", "", "", "", "live",
     "Off (default): hits never end a trade, dying always does. On: any lost health ends it (all back).",
     "field:TCfg.DAMAGE" + CF + "tradeCancelOnDamage"),''')
rep('ESS_PAGE_KEYS = ["part.tpa", "part.msg", "tpa.expireSeconds", "tpa.cooldownSeconds", "replyShortcut"]',
    'ESS_PAGE_KEYS = ["part.tpa", "part.msg", "tpa.expireSeconds", "tpa.cooldownSeconds", "replyShortcut", "privacy.staffBypass"]')
rep('''               NOTE="Warps + world spawn: Warps editor (/warpadmin). Trade keys also on /tradeadmin config.",
               RELOAD="TCfg.reloadKit", KEEP=20,''', '''               NOTE="Warps editor: /warpadmin. World spawn: vanilla /spawn set. Trade keys also on /tradeadmin config.",
               RELOAD="TCfg.reloadKit", KEEP=10,''')

# ================================================================================================ warps editor without the world spawn
rep('''# 0.1.3: every engine member the warps editor / world spawn code touches (the vanilla WarpSetCommand / WarpRemoveCommand / WarpCommand.tryGo
# / SpawnSetCommand / SpawnSetDefaultCommand calls, read with tools/dev/bcfull.py this session)''',
    '''# 0.1.3: every engine member the warps editor code touches (the vanilla WarpSetCommand / WarpRemoveCommand / WarpCommand.tryGo calls, read
# with tools/dev/bcfull.py; 0.1.5: the world spawn calls are gone with the spawn buttons)''')
rep('''             (WCF, "setSpawnProvider"), (WCF, "getSpawnProvider"), (WCF, "markChanged"), (WLD, "getName"), (UNI, "getWorld"),''',
    '''             (WLD, "getName"), (UNI, "getWorld"),''')
rep('''# 0.1.3 warps editor + world spawn (research/Server-Setup-Spec.md 5.4). Engine calls copied from vanilla (bytecode, tools/dev/bcfull.py):''',
    '''# 0.1.3 warps editor (research/Server-Setup-Spec.md 5.4). Engine calls copied from vanilla (bytecode, tools/dev/bcfull.py):''')
cut('''#   SpawnSetCommand: WorldConfig.setSpawnProvider(new GlobalSpawnProvider(new Transform(pos, rot))) + markChanged(); SpawnSetDefaultCommand:''',
    '''# =====================================================================================================================================
wpage = pool.makeClass(PKG + ".WarpPage", pool.get(T["PAGE"]))''',
    '''# Warp edits made on the /warpadmin page are written to config-changes.log with the kit's line format, via=command, status "done" (the
# SkyyRanks pattern), so SkyyMenu's Changes view lists them without an Undo it cannot do.
# 0.1.5 (Skyy 2026-09-25, OPEN-QUESTIONS Server Setup 18): the warps page no longer moves the world spawn - the spawn row, its confirm
# views, the kit action rows spawn.set / spawn.reset, SpawnTask and EssWarp.kitSpawn* / spawnSet / instanceErr / failed are removed.
# World spawn = vanilla /spawn set (hytale:WorldEditor + ops) and /spawn set default (hytale:Admin).
''')
rep('''wpage = pool.makeClass(PKG + ".WarpPage", pool.get(T["PAGE"]))
spt = pool.makeClass(PKG + ".SpawnTask")
spt.addInterface(pool.get("java.lang.Runnable"))
''', '''wpage = pool.makeClass(PKG + ".WarpPage", pool.get(T["PAGE"]))
''')
cut('''# the follow-up line for a Server Setup spawn action whose scheduled change did not happen.''',
    '''M(EWARP, r"""
public static @TPP@ tp() {''')
cut('''# ---- world spawn (the world thread of w). Instance worlds (SkyyIslands islands, portal worlds) keep their own spawn: refused.''',
    '''# ---- WarpPage: /warpadmin (and the kit's warps.editor link row).''')
rep('''# ---- WarpPage: /warpadmin (and the kit's warps.editor link row). BIG inline page, 1120 x 930 (28 + 3 + 46 + 28 + 30 + 9 x 50 + 6 + 44 +
# 50 + 50 + 24 + 24 + 32 + 52 = 867 used).''', '''# ---- WarpPage: /warpadmin (and the kit's warps.editor link row). BIG inline page, 1120 x 880 (28 + 3 + 46 + 28 + 30 + 9 x 50 + 6 + 44 +
# 50 + 24 + 24 + 32 + 52 = 817 used; 0.1.5: the 50 px world spawn row is gone).''')
rep('''public String question() {
  String wn = @PKG@.EssWarp.wname(@ES@.worldOf(this.playerRef));
  if ("rm".equals(this.cKind)) return "Remove the warp " + this.cId + "? Nobody can warp there any more (the vanilla /warp list loses it too).";
  if ("spset".equals(this.cKind)) return "Move the spawn of world " + wn + " to where you stand? New and respawning players arrive here.";
  if ("spreset".equals(this.cKind)) return "Put the spawn of world " + wn + " back to its original spawn point?";
  return "";
}''', '''public String question() {
  if ("rm".equals(this.cKind)) return "Remove the warp " + this.cId + "? Nobody can warp there any more (the vanilla /warp list loses it too).";
  return "";
}''')
rep('''  String rs = @PKG@.TradePage.style("#6a2020", "#8f2f2f", "#3a1010", "#ffe6e6", 17);
  String ys = @PKG@.TradePage.style("#6a4a12", "#8a641a", "#3e2a08", "#fff2d6", 17);
  if (!guard()) {''', '''  String rs = @PKG@.TradePage.style("#6a2020", "#8f2f2f", "#3a1010", "#ffe6e6", 17);
  if (!guard()) {''')
rep('''  b.appendInline((String) null, "Group #SkyyWp { Anchor: (Width: 1120, Height: 930); Background: #0b1524(0.97); Padding: (Horizontal: 24, Vertical: 14); LayoutMode: Top; }");
  b.appendInline("#SkyyWp", "Group { Anchor: (Height: 3); Background: #7fb2ff; }");
  b.appendInline("#SkyyWp", "Label { Anchor: (Height: 46); Text: \\"Warps and world spawn\\"; Style:''',
    '''  b.appendInline((String) null, "Group #SkyyWp { Anchor: (Width: 1120, Height: 880); Background: #0b1524(0.97); Padding: (Horizontal: 24, Vertical: 14); LayoutMode: Top; }");
  b.appendInline("#SkyyWp", "Group { Anchor: (Height: 3); Background: #7fb2ff; }");
  b.appendInline("#SkyyWp", "Label { Anchor: (Height: 46); Text: \\"Warps\\"; Style:''')
rep('''  b.appendInline("#SkyyWp", "Group #SkyyWpSpawn { Anchor: (Height: 50); LayoutMode: Left; }");
  b.appendInline("#SkyyWpSpawn", "Label #SkyyWpSpLbl { Anchor: (Width: 330, Height: 44); Text: \\"\\"; Style: (FontSize: 18, RenderBold: true, TextColor: #e6f2ff, VerticalAlignment: Center); }");
  b.set("#SkyyWpSpLbl.Text", "World spawn of " + wn + ":");
  b.appendInline("#SkyyWpSpawn", btn("#SkyyWpSpSet", 320, 42, "Set the world spawn here", ys));
  b.appendInline("#SkyyWpSpawn", gap(12, 42));
  b.appendInline("#SkyyWpSpawn", btn("#SkyyWpSpReset", 300, 42, "Reset to the original", bs));
  ev.addEventBinding(@BT@.Activating, "#SkyyWpSpSet", @EVD@.of("a", "spset"));
  ev.addEventBinding(@BT@.Activating, "#SkyyWpSpReset", @EVD@.of("a", "spreset"));
''', '')
rep('''  b.set("#SkyyWpHelp1.Text", "The world spawn only changes the world you stand in (islands keep their own). Same as vanilla /spawn set.");''',
    '''  b.set("#SkyyWpHelp1.Text", "The world spawn is not changed here: staff set it with the vanilla /spawn set command in that world.");''')
rep('''      if ("rm".equals(k)) this.info = @PKG@.EssWarp.remove(pr, id);
      else if ("spset".equals(k)) this.info = @PKG@.EssWarp.spawnSet(pr, store, ref, @ES@.worldOf(pr), false, "command");
      else if ("spreset".equals(k)) this.info = @PKG@.EssWarp.spawnSet(pr, store, ref, @ES@.worldOf(pr), true, "command");
''', '''      if ("rm".equals(k)) this.info = @PKG@.EssWarp.remove(pr, id);
''')
rep('''    if (a.equals("spset") || a.equals("spreset")) { this.cKind = a; this.cId = null; rebuild(); return; }
''', '')
rep('''  super("warpadmin", "Admin: the warps editor page (add, move, rename, remove and visit warps) and the world spawn");''',
    '''  super("warpadmin", "Admin: the warps editor page (add, move, rename, remove and visit warps)");''')
rep('''MINE = [rq, es, hop, mv, rd, fly, tick] + OLD_CMDS + TRADE_ALL + TCMDS + [eperm, EWARP, wpage, spt, pl]''',
    '''MINE = [rq, es, hop, mv, rd, fly, tick] + OLD_CMDS + TRADE_ALL + TCMDS + [eperm, EWARP, wpage, pl]''')
rep('''admin /fly /tradeadmin /warpadmin (warps editor + world spawn), every setting in game''',
    '''admin /fly /tradeadmin /warpadmin (warps editor), player switches that refuse /tpa and /msg (staff bypass), every setting in game''')

# ================================================================================================ setup(): the two refusing switches
# + the staff bypass node (registered ungrouped: /perm list and SkyyRanks' node search list it, no group is granted it; never throws)
rep('''  @ES@.R_SHORTCUT = @PKG@.TCfg.REPLY_FILE;
''', '''  @ES@.R_SHORTCUT = @PKG@.TCfg.REPLY_FILE;
  // 0.1.5: the staff bypass node of the refusing switches (skyyessentials.bypass), registered ungrouped
  @ES@.regPerm();
''')
rep('''  // 0.1.3 player Settings switch (research/Settings-Spec.md 2.2 / 3.11; tpa.requests and msg.private are NOT built - they wait for Skyy)
  @ES@.regSetting("tpa.updates", "Teleport request updates", "general", true, "Denied, expired and cancelled requests - accepted ones always show");''',
    '''  // player Settings switches (research/Settings-Spec.md 2.2 / 3.11): 0.1.3 tpa.updates; 0.1.5 the REFUSING tpa.requests and msg.private
  // (Skyy 2026-09-25: block the sender; staff bypass = node skyyessentials.bypass while the Server Setup row privacy.staffBypass is on)
  @ES@.regSetting("tpa.requests", "Teleport requests", "general", true, "OFF: nobody can send you /tpa or /tpahere - they are told (staff may still)");
  @ES@.regSetting("tpa.updates", "Teleport request updates", "general", true, "Denied, expired and cancelled requests - accepted ones always show");
  @ES@.regSetting("msg.private", "Private messages", "general", true, "OFF: /msg and /reply to you are refused and the sender is told (staff may still)");''')
rep('''/tpa /tpahere /tpaccept /tpdeny /tpacancel /msg (tell, w, whisper) /reply /fly; " + rNote''',
    '''/tpa /tpahere /tpaccept /tpdeny /tpacancel /msg (tell, w, whisper) /reply /fly; switches tpa.requests msg.private (staff bypass " + (@ES@.STAFF_BYPASS ? "on" : "off") + "); " + rNote''')

# ================================================================================================ /trade: a trader who DIES ends the trade
# (review 2026-09-28: tradeCancelOnDamage now defaults to false, so without this a death - health 0, the death screen, the respawn - left
# the trade open). The 1 s position task on the trader's own world thread marks TSession.dead[side]; the trade thread's tickSession runs
# the normal cancelNow path (escrow drained, record written, items delivered back like every other cancel), whatever DAMAGE says.
rep('''          "public boolean[] hurt;", "public float[] hp;", "public java.util.UUID[] wu;", "public java.util.UUID[] sw;", "public long[] posAt;",''',
    '''          "public boolean[] hurt;", "public boolean[] dead;", "public float[] hp;", "public java.util.UUID[] wu;", "public java.util.UUID[] sw;", "public long[] posAt;",''')
rep('''this.hurt = new boolean[2]; this.hp = new float[2];''', '''this.hurt = new boolean[2]; this.dead = new boolean[2]; this.hp = new float[2];''')
rep('''        if (s.hpSeen[i] && h < s.hp[i] - 0.05f) s.hurt[i] = true;
        s.hp[i] = h;
        s.hpSeen[i] = true;
      }
    }
  } catch (Throwable e) { }
}""")''', '''        if (s.hpSeen[i] && h < s.hp[i] - 0.05f) s.hurt[i] = true;
        // 0.1.5: dead = no health left (a real stat: max above 0)
        if (h <= 0.0f && hv.getMax() > 0.0f) s.dead[i] = true;
        s.hp[i] = h;
        s.hpSeen[i] = true;
      }
    }
  } catch (Throwable e) { }
  // 0.1.5: ... or the engine's DeathComponent is on the player (added at death, removed at respawn)
  try {
    if (st.getComponent(ref, com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent.getComponentType()) != null) s.dead[i] = true;
  } catch (Throwable e) { }
}""")''')
rep('''    if (!@PKG@.TCfg.DAMAGE) s.hurt[i] = false;
    else if (s.hurt[i]) { cancelNow(s, "damage", i, s.name[i]); return; }''', '''    // 0.1.5: a death always ends the trade (before the damage rule, which is off by default)
    if (s.dead[i]) { cancelNow(s, "death", i, s.name[i]); return; }
    if (!@PKG@.TCfg.DAMAGE) s.hurt[i] = false;
    else if (s.hurt[i]) { cancelNow(s, "damage", i, s.name[i]); return; }''')
rep('''  else if (reason.equals("damage")) a = w + " took damage - trade cancelled.";''',
    '''  else if (reason.equals("damage")) a = w + " took damage - trade cancelled.";
  else if (reason.equals("death")) a = w + " died - trade cancelled.";''')
rep('''(T["ESM"], "getComponentType"), (T["ESM"], "get"), (T["ESV"], "get"), (T["DST"], "getHealth"),''',
    '''(T["ESM"], "getComponentType"), (T["ESM"], "get"), (T["ESV"], "get"), (T["ESV"], "getMax"), (T["DST"], "getHealth"),''')

# ================================================================================================ checks on the result
code = s[s.index('\nimport sys, os\n'):]              # everything after the docstring
assert s.count('"0.1.4"') == 0, "a 0.1.4 version string is left"
assert s.count("registerCommand(") == REG0 and s.count("registerSystem(") == SYS0, "no command / system added or removed"
code_nc = "\n".join(l for l in code.split("\n") if not l.lstrip().startswith("#"))     # without the Python comment lines
for gone in ("SpawnTask", "kitSpawn", "spawnSet(", "instanceErr", "EssWarp.failed", "spset", "spreset", "SkyyWpSp", "setSpawnProvider",
             '"spawn.set"', '"spawn.reset"', "spt"):
    assert not re.search((r"\b" if gone[0].isalpha() else "") + re.escape(gone), code_nc), "left in the code: " + gone
assert code.count('"tpa.requests"') == 2 and code.count('"msg.private"') == 3        # gate + regSetting (+ the own-switch note)
assert code.count("int g = gate(target.getUuid(), ") == 2
# the refusal comes before anything is stored / echoed
_rq = code[code.index("public static void request("):]
assert _rq.index('gate(target.getUuid(), "tpa.requests"') < _rq.index("tryAdd(pr.getUuid()") < _rq.index("if (g == 2)")
_pm = code[code.index("public static void pm("):]
assert _pm.index('gate(target.getUuid(), "msg.private"') < _pm.index('say(pr, "[you -> "') < _pm.index("LAST_PM.put(") < _pm.index("if (g == 2)")
# EssStore: warn before isStaff / regPerm before gate before key(); gate before request / pm (javassist: no forward references)
assert code.index("public static void warn(String m) {") < code.index("public static boolean isStaff(") < code.index("public static boolean regPerm(") \
    < code.index("public static int gate(") < code.index("public static String key(") \
    < code.index("public static void request(") < code.index("public static void pm(")
# the ONE staff test: hasPermission(node) alone - no group lookup left; the node registered once, in setup()
_st = code[code.index("public static boolean isStaff("):code.index("public static boolean regPerm(")]
assert "pm.hasPermission(u, BYPASS_PERM)" in _st and "getGroupsForUser" not in code and "ADMIN_GROUP" not in code
assert code.count("registerPermission(BYPASS_PERM)") == 1 and code.count("@ES@.regPerm();") == 1
_su0 = code[code.index("public void setup() {"):]
assert _su0.index("@ES@.regPerm();") < _su0.index("CfgPub.start(")
# identical staff notices on /tpa and /msg (SkyyParty's invite uses the same words)
assert code.count('" (staff)"') == 2 and code.count('(sent anyway - staff bypass: "') == 2
assert 'has teleport requests off)"' in code and 'has private messages off)"' in code and "delivered anyway" not in code
assert code.count('"Staff get through blocked switches"') == 2
# trade death: marked on the world thread, checked before the damage rule, its own cancel line
assert code.count("s.dead[i] = true;") == 2 and code.count('cancelNow(s, "death", i, s.name[i])') == 1
_ts = code[code.index("public static void tickSession("):]
assert _ts.index('cancelNow(s, "death"') < _ts.index("if (!@PKG@.TCfg.DAMAGE) s.hurt[i] = false;")
assert 'reason.equals("death")' in code and "public boolean[] dead;" in code and "this.dead = new boolean[2];" in code
# TCfg: the migration helpers are compiled before load(), which calls migrateDamage once, after the missing-key append
_mg = ["public static boolean lineWs(", "public static int keyValueAt(", "public static boolean lineCont(", "public static boolean lineSkip(",
       "public static boolean logNames(", "public static boolean damageTouched(", "public static void changeLine(",
       "public static boolean sameExceptDamage(", "public static void migrateDamage(", "public static synchronized String load()"]
assert [code.index(x) for x in _mg] == sorted(code.index(x) for x in _mg), "TCfg migration methods out of order"
assert code.index("public static synchronized String appendMissing(") < code.index("public static void migrateDamage(")
assert code.index("public static void info(String m)") < code.index("public static void migrateDamage(")
assert code.index("public static void appendLine(") < code.index("public static void changeLine(")
_ld = code[code.index("public static synchronized String load()"):]
_ld = _ld[:_ld.index('}""")')]
assert _ld.count("migrateDamage(p);") == 1 and _ld.index("appendMissing(miss)") < _ld.index("migrateDamage(p);") < _ld.index("return summary0();")
# setup(): the three switches registered before the kit starts; the kit still starts last
_su = code[code.index("public void setup() {"):]
_su = _su[:_su.index('}""")')]
assert _su.index('"tpa.requests"') < _su.index('"tpa.updates"') < _su.index('"msg.private"') < _su.index("CfgPub.start(")
assert "KEEP=10" in code and 'ESS_PAGE_KEYS = ["part.tpa", "part.msg", "tpa.expireSeconds", "tpa.cooldownSeconds", "replyShortcut", "privacy.staffBypass"]' in code
assert "B.deploy(" not in code and "enable_in_world(" not in code
for ident in re.findall(r"#(Skyy[A-Za-z0-9_]*)", code):
    assert "_" not in ident, "UI id with an underscore: " + ident

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(line endings %s)" % ("CRLF" if NL == CR + LF else "LF"))
