"""Derive SkyyExploration/build_skyyexploration_0.2.5.py from the LIVE 0.2.4 (build_skyyexploration_0.2.4.py = the tools/deploy_set.py SET
pin, GENERATED by tools/exploration_0_2_4_patch.py). Edit THIS patch, never the generated script; every anchor is asserted.
Run:  python tools/exploration_0_2_5_patch.py   then   python SkyyExploration/build_skyyexploration_0.2.5.py   (never --deploy)
      then  python SkyyExploration/test_skyyexploration_0.2.5.py

0.2.5 = UNCLAIMED LUGGAGE: VANISH AT ONCE + A LOOK THAT DOES NOT PROMISE A CHEST WINDOW. Skyy 2026-10-09 after the in-game test: "chess
didnt open to let me see what was in it, and took forever to vanish.   lets make it vanish immediately after being claimed.  BUT if we cant
open it, lets change up the sprite, so players dont expect it to open."
  1. VANISH IMMEDIATELY: luggage.shareSeconds (Server Setup row "Claimed luggage vanishes after", kept) now defaults to 0 = ONE claim per
     luggage: the first player's F gives the loot (as before: coins, mystery bags, the vanilla roll, XP, one chat line) and the block is
     removed in the SAME call on the world thread (the claim line is written first, as in 0.2.4; then state 2 = gone, waiting to come back
     after luggage.respawnSeconds). The vanish shows a small vanilla poof: the Block_Break_Dust particle + the SFX_Cloth_Break sound, 3D at
     the block. Anyone pressing F on it before the block disappears on their screen gets "This luggage was already claimed." A removal that
     fails (never seen; e.g. the chunk unloaded in between) is retried by the once-a-second sweep (share time 0 = due at once). Above 0 the
     0.2.4 behaviour is kept (others nearby claim their own loot for that long, then it vanishes - with the poof now too).
  2. OPEN OR RESPRITE - investigated, RESPRITE chosen (see "WHY NOT A CHEST WINDOW" below). The four blocks keep their ids
     (Skyy_LootChest_T1..T4 - saved chunks and registry lines stay valid) and names, but look like travel sacks, not chests (vanilla models
     BY PATH, nothing copied; every candidate checked against Assets.zip):
       I   the vanilla feed-bag sack (Items/Tools/Feedbag/Feedbag.blockymodel, Feedbag_Texture - plain brown), icon Tool_Feedbag
       II  the same sack, Seedbag_Texture (green), icon Utility_Bag_Seed
       III the bigger Ancient sack (Blocks/Decorative_Sets/Ancient/Sack.blockymodel, Sack.png - tan, a full block), icon Furniture_Ancient_Sack
       IV  the feed-bag sack, Fertilizer_Crystal (purple), icon Tool_Fertilizer_Crystal
     Checked and not used: Furniture_*_Chest_* (chests - the problem), Furniture_*_Crate / *_Barrel (read as containers too),
     Plant_Hay_Bundle (reads as hay), Halloween_Basket_* (seasonal), Deco_Scarak_Eggsacks (a monster nest), Food_Bag / SeedBag /
     Spore_Bag (hand-item models, never used as a placed block by vanilla - unproven size), the backpacks (Items/Back/Backpack*,
     NPC Klops / Goblin backpacks: character attachment models, never placed as a block by vanilla - unproven size / origin).
     Feedbag.blockymodel IS a placed-block model in vanilla (Tool_Feedbag, Tool_Fertilizer*, Ingredient_Flour BlockTypes), so its size and
     hitbox (Plant_Full) are proven. The prompt reads "Press [F] to claim Unclaimed Luggage (I)" (our own hint key
     server.interactionHints.skyyLuggageClaim = "Press [{key}] to claim {name}", in our server.lang next to the names), the item
     description says the loot goes straight into the inventory. Sounds: Cloth (block set), placement / return SFX_Cloth_Land (was the wooden
     chest close). Unchanged: Material Solid, no block entity / container, no recipe, Variant, DropList Empty, unbreakable outside Creative
     (BreakBlockEvent / DamageBlockEvent guards), the orphan rules (no registry line = empty + breakable), the 0.2.4 registry fixes.
  3. ONE-TIME UPDATE of an existing config.properties (new class ExpLgMig, setup() runs it right after ExpCfg.FILE is set and BEFORE
     ExpCfg.load + CfgPub.start; PROJECT-RULES 4, the reviewed SkyyCooking CookMig machinery): a luggage.shareSeconds line still holding
     exactly the old default 20 becomes 0 (key, separator and line ending kept), any other value is kept and logged; the file before the
     update is copied to config-history first and the copy is verified byte for byte (else nothing is written; the next start tries
     again); one Undo-able config-changes.log line; run-once marker LG_MARK right above the line (no line: at the end of the file - so an
     admin who later sets 20 in game keeps it); every other byte and line ending kept. A fresh file has the marker + 0 from the start.
     Skyy's live file has NO luggage line (0.2.4 never writes one into an existing file) -> the default 0 applies, only the marker is added.
  4. Config kit history KEEP 20 -> 10 (Skyy 2026-10-05, AGENT-BRIEF).

WHY NOT A CHEST WINDOW (investigated 2026-10-09, engine bytecode + the live set): the engine can show a virtual chest
(PageManager.setPageWithWindows(ref, store, Page.Bench, true, new ContainerWindow(SimpleItemContainer)) - SkyyVault's proven "open as
chest"), and OpenCustomUIInteraction.firstRun hands our supplier the player + a CommandBuffer. But the rolled loot would live ONLY in that
window's memory while it is open: (a) a server stop / crash with the window open loses every item in it (vanilla chests keep theirs in the
block; ours has none by design); (b) a disconnect / world switch closes it from PlayerSystems$PlayerAddedSystem.onEntityRemove ->
WindowManager.closeAllWindows - whether items put into the inventory THERE are still saved with the player cannot be proven without the
game; (c) opening a page from inside an interaction's tryCreate (the chain still running) and the client's page acknowledgment
(the 2026-10-03 "all pages ignore clicks" bug) are unproven paths; (d) per-player loot in one block needs one window per player and a
leftover rule for every close path. A real container block would be persisted but lets players store their own items in a block that
vanishes, and SkyyGear's chest-loot logic hooks every ContainerBlockWindow. Too risky to verify without the game -> the look changes instead.

ROLLBACK to 0.2.4: no new saved data (the registry lines are unchanged); config.properties keeps luggage.shareSeconds=0 if the update set it
(0.2.4 reads it: one claim, vanishes within a second) - set it back to 20 in Server Setup if wanted. No floor needed.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyExploration", "build_skyyexploration_0.2.4.py")
DST = os.path.join(ROOT, "SkyyExploration", "build_skyyexploration_0.2.5.py")
raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.2.4"' in s and s.startswith('"""SkyyExploration 0.2.4 - build script'), "not the live 0.2.4 script"
SYS0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:200])
    s = s.replace(old, new)


HEAD = open(__file__, encoding="utf8").read().split('"""')[1]
rep('''"""SkyyExploration 0.2.4 - build script (javassist via jpype, tools/skyybuild.py). GENERATED by tools/exploration_0_2_4_patch.py from the
LIVE 0.2.3 - edit the patch, never this file. Run: python SkyyExploration/build_skyyexploration_0.2.4.py -> SkyyExploration-0.2.4.jar
(never --deploy). Test: python SkyyExploration/test_skyyexploration_0.2.4.py
''', '''"""SkyyExploration 0.2.5 - build script (javassist via jpype, tools/skyybuild.py). GENERATED by tools/exploration_0_2_5_patch.py from the
LIVE 0.2.4 - edit the patch, never this file. Run: python SkyyExploration/build_skyyexploration_0.2.5.py -> SkyyExploration-0.2.5.jar
(never --deploy). Test: python SkyyExploration/test_skyyexploration_0.2.5.py

''' + HEAD[HEAD.index("0.2.5 = "):].strip() + '''

0.2.4 (the base, everything below is still true unless 0.2.5 above says otherwise):
''')
rep('VERSION = "0.2.4"', 'VERSION = "0.2.5"')

# ================================================================================================================ tokens + probes
rep('''    "DBE": "com.hypixel.hytale.server.core.event.events.ecs.DamageBlockEvent",
''', '''    "DBE": "com.hypixel.hytale.server.core.event.events.ecs.DamageBlockEvent",
    # 0.2.5 the vanish poof
    "LPTU": "com.hypixel.hytale.server.core.universe.world.ParticleUtil",
''')
LG5_PROBES = '''
# 0.2.5: the vanish poof - ParticleUtil.spawnParticleEffect(String, Vector3dc, ComponentAccessor) (every player within 75 blocks)
B.probe(pool, T["LPTU"], "spawnParticleEffect")
assert "(Ljava/lang/String;Lorg/joml/Vector3dc;Lcom/hypixel/hytale/component/ComponentAccessor;)V" in [str(m_.getSignature()) for m_ in pool.get(T["LPTU"]).getDeclaredMethods() if str(m_.getName()) == "spawnParticleEffect"], "ParticleUtil.spawnParticleEffect(String, Vector3dc, ComponentAccessor) changed"
'''
rep('''LEFT = re.compile(r"@[A-Z][A-Z0-9_]*@")''', LG5_PROBES + '''LEFT = re.compile(r"@[A-Z][A-Z0-9_]*@")''')

# ================================================================================================================ config: shareSeconds 20 -> 0
LG_MARK_ID = "SkyyExploration 0.2.5 luggage vanishes at once"
LG_MARK = ("# %s (Skyy 2026-10-09): a luggage.shareSeconds line still on the old default 20 was set to 0 once - "
           "0 means one claim per luggage and it vanishes the moment it is claimed" % LG_MARK_ID)
assert "=" not in LG_MARK and all(32 <= ord(c) < 127 for c in LG_MARK)
rep('''# Each player claims a luggage once: coins + mystery bags (SkyyGear) + a vanilla loot roll + Exploration XP. After the first claim it stays
# shareSeconds for others nearby, then vanishes; it comes back at the same spot after respawnSeconds. Player chests are never touched.''',
    '''# A claim gives coins + mystery bags (SkyyGear) + a vanilla loot roll + Exploration XP. shareSeconds 0 = one claim per luggage and it
# vanishes at once (above 0: others nearby claim their own loot that long); it comes back at the same spot after respawnSeconds.
# Player chests are never touched.''')
rep('''luggage.ringMax=64
luggage.shareSeconds=20''', '''luggage.ringMax=64
''' + LG_MARK + '''
luggage.shareSeconds=0''')
rep('"long LG_SHARE_S = 20L"', '"long LG_SHARE_S = 0L"')
rep('''  LG_SHARE_S = clampL(lng(p, "luggage.shareSeconds", 20L), 0L, 600L);''', '''  LG_SHARE_S = clampL(lng(p, "luggage.shareSeconds", 0L), 0L, 600L);''')
rep('''    crow("luggage.shareSeconds", "Shared after the first claim", "luggage", "int", "0", "600", "s",
         hlp="Others nearby can still claim their own loot this long, then it vanishes."),''',
    '''    crow("luggage.shareSeconds", "Claimed luggage vanishes after", "luggage", "int", "0", "600", "s",
         hlp="0 = one claim, it vanishes at once. Above 0: others nearby claim their own loot this long."),''')
rep('''RELOAD="ExpCfg.reloadCfg", KEEP=20,''', '''RELOAD="ExpCfg.reloadCfg", KEEP=10,''')

# ================================================================================================================ the Java
# LgApi seam: the poof (the harness records it)
rep('''            "public abstract void sound(@WLD@ w, int x, int y, int z);"):
    lgapi.addMethod(CtNewMethod.make(sub(sig), lgapi))''', '''            "public abstract void sound(@WLD@ w, int x, int y, int z);",
            # 0.2.5: the vanish poof (particle + sound at the block)
            "public abstract void poof(@WLD@ w, int x, int y, int z);"):
    lgapi.addMethod(CtNewMethod.make(sub(sig), lgapi))''')
rep('''LG_SOUND = "SFX_Chest_Wooden_Close"      # review fix (spec 5.2): played 3D when a luggage is placed or comes back
assert LG_SOUND in SOUND_IDS, LG_SOUND''', '''LG_SOUND = "SFX_Cloth_Land"     # 0.2.5: a soft cloth thump (the sacks) when a luggage is placed or comes back (0.2.4: the wooden chest close)
LG_POOF_SND = "SFX_Cloth_Break"     # 0.2.5: the vanish
LG_POOF_FX = "Block_Break_Dust"     # 0.2.5: the vanish particle (a vanilla ParticleSystem id)
assert LG_SOUND in SOUND_IDS and LG_POOF_SND in SOUND_IDS, (LG_SOUND, LG_POOF_SND)
assert any(n_.startswith("Server/Particles/") and n_.endswith("/" + LG_POOF_FX + ".particlesystem") for n_ in NAMES_ALL), LG_POOF_FX''')
# LgEng.poof: the real engine calls (after LgEng.sound)
rep('''  try { @SNU@.playSoundEvent3d(idx, @SCAT@.SFX, (double) x + 0.5, (double) y + 0.5, (double) z + 0.5, w.getEntityStore().getStore()); } catch (Throwable t) { }
}""".replace("@LGSND@", LG_SOUND))''', '''  try { @SNU@.playSoundEvent3d(idx, @SCAT@.SFX, (double) x + 0.5, (double) y + 0.5, (double) z + 0.5, w.getEntityStore().getStore()); } catch (Throwable t) { }
}""".replace("@LGSND@", LG_SOUND))
# 0.2.5 the vanish poof: the vanilla dust puff + the cloth sound, 3D at the block, for everyone near (every failure is swallowed - a poof
# never stops a claim). acc = the caller's accessor (the interaction's CommandBuffer in a claim), null = the world's entity store
F(lgeng, "public static int PSND = Integer.MIN_VALUE + 1;")
M(lgeng, r"""
public static void poof(@WLD@ w, int x, int y, int z, @CAC@ acc) {
  if (API != null) { API.poof(w, x, y, z); return; }
  if (w == null) return;
  @CAC@ a = acc;
  try { if (a == null) a = w.getEntityStore().getStore(); } catch (Throwable t) { return; }
  if (a == null) return;
  try { @LPTU@.spawnParticleEffect("@LGFX@", new org.joml.Vector3d((double) x + 0.5, (double) y + 0.4, (double) z + 0.5), a); } catch (Throwable t) { }
  int idx = PSND;
  if (idx == Integer.MIN_VALUE + 1) {
    try { idx = @SEV@.getAssetMap().getIndex("@LGPSND@"); } catch (Throwable t) { idx = Integer.MIN_VALUE; }
    PSND = idx;
  }
  if (idx == Integer.MIN_VALUE) return;
  try { @SNU@.playSoundEvent3d(idx, @SCAT@.SFX, (double) x + 0.5, (double) y + 0.5, (double) z + 0.5, a); } catch (Throwable t) { }
}""".replace("@LGFX@", LG_POOF_FX).replace("@LGPSND@", LG_POOF_SND))''')
# LgCore.vanish: one place for "the block goes now" (sweep + claim)
rep('''# once a second per world: claimed luggage vanishes after the share time, unvisited luggage goes away, lines whose block is gone are''',
    '''# 0.2.5: a claimed luggage goes NOW (only our block with a line: unplace's rule) -> state 2 (waits to come back; lootedAt kept) + the poof.
# false = it could not be removed yet (an unloaded chunk): the once-a-second sweep tries again. The caller saves the registry.
M(lgcore, r"""
public static boolean vanish(@WLD@ w, @PKG@.LgSite s, @CAC@ acc) {
  if (s == null || s.state != 1) return false;
  String id = @PKG@.LgEng.blockId(w, s.x, s.y, s.z);
  boolean was = ours(id);
  if (!unplace(w, s)) return false;
  s.state = 2;
  count(2, 1L);
  if (was) { try { @PKG@.LgEng.poof(w, s.x, s.y, s.z, acc); } catch (Throwable t) { } }
  return true;
}""")
# once a second per world: claimed luggage vanishes after the share time, unvisited luggage goes away, lines whose block is gone are''')
rep('''    if (s.state == 1 && now - s.lootedAt >= share) {
      if (unplace(w, s)) { s.state = 2; changed++; count(2, 1L); }
      continue;
    }''', '''    if (s.state == 1 && now - s.lootedAt >= share) {
      if (vanish(w, s, null)) changed++;
      continue;
    }''')
# use(): single claim (share 0) -> the block goes in the same call, after the loot + the chat line
rep('''  if (s.state == 1 && now - s.lootedAt >= @PKG@.ExpCfg.LG_SHARE_S * 1000L) { say(pr, "[Exploration] This luggage is already vanishing.", col); return 0; }''',
    '''  if (s.state == 1 && now - s.lootedAt >= @PKG@.ExpCfg.LG_SHARE_S * 1000L) { say(pr, "[Exploration] This luggage was already claimed.", col); return 0; }''')
rep('''  if (sites == null) { say(pr, "[Exploration] This luggage cannot be opened right now - try again later.", col); return 0; }''',
    '''  if (sites == null) { say(pr, "[Exploration] This luggage cannot be claimed right now - try again later.", col); return 0; }''')
rep('''  if (@PKG@.ExpIO.notifyOn(u, "explore.finds")) say(pr, "[Exploration] Unclaimed Luggage (" + TIER[s.tier] + ", Lv " + s.lvl + "): " + (got.length() > 0 ? got : "it was empty"), col);
  return 1;
}""")''', '''  if (@PKG@.ExpIO.notifyOn(u, "explore.finds")) say(pr, "[Exploration] Unclaimed Luggage (" + TIER[s.tier] + ", Lv " + s.lvl + "): " + (got.length() > 0 ? got : "it was empty"), col);
  // 0.2.5 (Skyy 2026-10-09 "vanish immediately after being claimed"): share time 0 = one claim, the block goes now (the claim is saved above)
  if (@PKG@.ExpCfg.LG_SHARE_S <= 0L) {
    try { if (vanish(w, s, acc)) @PKG@.LgReg.save(wn); }
    catch (Throwable t) { @PKG@.ExpCfg.warnEvery("lgvanish", 60000L, "luggage vanish failed (the sweep retries within a second): " + t); }
  }
  return 1;
}""")''')

# ---- ExpLgMig: the one-time luggage.shareSeconds 20 -> 0 update (PROJECT-RULES 4; SkyyCooking CookMig's reviewed machinery)
LG_MIG = ("\nLG_MARK_ID = %r\nLG_MARK = %r\n" % (LG_MARK_ID, LG_MARK)) + r'''
# ================= ExpLgMig (0.2.5): the one-time luggage.shareSeconds update of an existing config.properties (see the header) =========
# SkyyCooking CookMig's reviewed machinery on the kit's own parser (CfgFile) and files (CfgHist / CfgLog / CfgRows.atomicWrite). Runs in
# setup() BEFORE ExpCfg.load + CfgPub.start (the kit has not started; nothing else touches the file then).
lgmig = pool.makeClass(PKG + ".ExpLgMig")
F(lgmig, "public static final String WHO = %s;" % json.dumps("SkyyExploration " + VERSION))
F(lgmig, "public static final String KEY = \"luggage.shareSeconds\";")
F(lgmig, "public static final String OLD = \"20\";")
F(lgmig, "public static final String NEW = \"0\";")
F(lgmig, "public static final String WHAT = \"before the 0.2.5 luggage vanishes at once update\";")
F(lgmig, "public static final String MARK = %s;" % json.dumps(LG_MARK))
F(lgmig, "public static final String MARK_ID = %s;" % json.dumps(LG_MARK_ID))
# pure text step (ISO-8859-1 chars in and out). null = nothing to do (MARK_ID already in a comment line). Else Object[]{ new text,
# "luggage.shareSeconds 20 -> 0" or "", kept note or null, String[] { key, old, new } or {}, the effective value text or null }. The LAST
# entry of the key decides (what java.util.Properties keeps): a one-line entry holding exactly OLD -> every one-line entry of the key
# holding OLD gets NEW (value text only: key, separator and CR stay); anything else is kept (a custom value or a continued entry is
# noted). The marker goes right above the FIRST entry of the key, else at the end of the file (a final line break added first if the
# file has none, in the file's own line ending) - unless the file ENDS inside a continued entry (a dangling backslash: the marker would
# become part of that value), then at the very top. Every line is scanned from the start of a logical line.
M(lgmig, r"""
public static Object[] update(String text) {
  String[] raw = text.split("\n", -1);
  java.util.ArrayList l = new java.util.ArrayList();
  for (int i = 0; i < raw.length; i++) {
    String s0 = raw[i];
    if (s0.endsWith("\r")) s0 = s0.substring(0, s0.length() - 1);
    l.add(s0);
  }
  String eff = null;
  boolean multi = false;
  int ax = -1;
  int le = -1;
  int ls = -1;
  int k = 0;
  while (k < l.size()) {
    String s = (String) l.get(k);
    if (@PKG@.CfgFile.isComment(s)) {
      if (s.indexOf(MARK_ID) >= 0) return null;
      k++;
      continue;
    }
    int e = @PKG@.CfgFile.end(l, k);
    ls = k;
    le = e;
    if (KEY.equals(@PKG@.CfgFile.key(s))) {
      if (ax < 0) ax = k;
      eff = @PKG@.CfgFile.value(l, k).trim();
      multi = e > k;
    }
    k = e + 1;
  }
  boolean mig = eff != null && !multi && eff.equals(OLD);
  String chg = "";
  String kept = null;
  java.util.ArrayList rows = new java.util.ArrayList();
  if (mig) {
    chg = KEY + " " + OLD + " -> " + NEW;
    rows.add(KEY);
    rows.add(OLD);
    rows.add(NEW);
  } else if (eff != null && (multi || !eff.equals(NEW))) {
    kept = KEY + "=" + @PKG@.CfgRows.oneLine(eff) + " kept (custom) - the 0.2.5 default is " + NEW;
  }
  java.util.ArrayList out = new java.util.ArrayList();
  k = 0;
  while (k < l.size()) {
    String s2 = (String) l.get(k);
    if (@PKG@.CfgFile.isComment(s2)) { out.add(raw[k]); k++; continue; }
    int e2 = @PKG@.CfgFile.end(l, k);
    if (mig && e2 == k && KEY.equals(@PKG@.CfgFile.key(s2)) && @PKG@.CfgFile.value(l, k).trim().equals(OLD)) {
      String cr1 = raw[k].endsWith("\r") ? "\r" : "";
      out.add(s2.substring(0, @PKG@.CfgFile.valStart(s2)) + NEW + cr1);
    } else {
      for (int q = k; q <= e2; q++) out.add(raw[q]);
    }
    k = e2 + 1;
  }
  String cr = text.indexOf("\r\n") >= 0 ? "\r" : "";
  if (ax >= 0) {
    String crA = ax + 1 < raw.length ? (raw[ax].endsWith("\r") ? "\r" : "") : cr;
    out.add(ax, MARK + crA);
  } else if (le >= 0 && le == l.size() - 1 && (le > ls || @PKG@.CfgFile.cont((String) l.get(le)))) {
    // fixer 2026-10-09: the file ends inside a continued entry (a dangling backslash) - a marker at the end would become part of that
    // value (java.util.Properties reads the next line as its continuation), so it goes at the very top (line 0 always starts a line)
    out.add(0, MARK + cr);
  } else {
    // the end of the file: text.split keeps a final "" after a closing line break - the marker goes before it
    int last = out.size() - 1;
    if (last >= 0 && ((String) out.get(last)).length() == 0) out.add(last, MARK + cr);
    else if (text.length() == 0) { out.clear(); out.add(MARK + cr); out.add(""); }
    else { out.set(last, (String) out.get(last) + (((String) out.get(last)).endsWith("\r") ? "" : cr)); out.add(MARK + cr); out.add(""); }
  }
  StringBuilder sb = new StringBuilder(text.length() + MARK.length() + 16);
  for (int i = 0; i < out.size(); i++) { if (i > 0) sb.append('\n'); sb.append((String) out.get(i)); }
  return new Object[] { sb.toString(), chg, kept, (String[]) rows.toArray(new String[0]), eff };
}""")
# the config kit's own files for the update, before CfgPub.start (which sets the same values again): history + change log live in the
# folder of config.properties (the kit's HOME, Skyy_SkyyExploration)
M(lgmig, r"""
public static void kit(java.nio.file.Path home) {
  @PKG@.CfgRows.HOME = home;
  if (@PKG@.CfgRows.LOG == null) @PKG@.CfgRows.LOG = @PKG@.ExpCfg.LOG;
  @PKG@.CfgHist.init();
  @PKG@.CfgLog.init();
}""")
# CfgHist.snapshot swallows its own errors: config-history must really hold a copy with exactly these bytes (the copies are checked)
M(lgmig, r"""
public static boolean saved(byte[] old) {
  String[] have = @PKG@.CfgHist.list(0);
  for (int i = have.length - 1; i >= 0; i--) {
    try {
      if (java.util.Arrays.equals(java.nio.file.Files.readAllBytes(@PKG@.CfgHist.bak(0, have[i])), old)) return true;
    } catch (Throwable x) { }
  }
  return false;
}""")
# one config-changes.log line in the kit's scalar-row format (key column = the row key: Server Setup -> Changes undoes it with a plain set)
M(lgmig, r"""
public static String logLine(String k, String o, String n) {
  return @PKG@.CfgLog.now() + "\t" + WHO + "\t-\tupdate\t" + @PKG@.CfgRows.oneLine(k) + "\t" + o + "\t" + n + "\tok";
}""")
# setup(): the file before this update becomes a History version (verified before the rewrite), the new text is written with the kit's
# atomicWrite (ISO-8859-1 bytes), one change-log line when the value changed, one INFO line (+ one for a kept custom value). Returns the
# INFO line(s) ("" = nothing done: no file, the marker already there, or a failure - WARN, file untouched, the next start tries again)
M(lgmig, r"""
public static synchronized String migrate() {
  java.nio.file.Path f = @PKG@.ExpCfg.FILE;
  if (f == null) return "";
  try {
    if (!java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) return "";
    byte[] old = java.nio.file.Files.readAllBytes(f);
    Object[] r = update(new String(old, "ISO-8859-1"));
    if (r == null) return "";
    byte[] data = ((String) r[0]).getBytes("ISO-8859-1");
    kit(f.toAbsolutePath().getParent());
    @PKG@.CfgHist.snapshot(0, old, @PKG@.CfgHist.stamp(), WHO, WHAT);
    if (!saved(old)) {
      @PKG@.ExpCfg.warn("config.properties NOT updated for 0.2.5 (luggage vanishes at once): the old file could not be kept in " + @PKG@.CfgHist.DIR + " (the file is used as it is; the next start tries again)");
      return "";
    }
    @PKG@.CfgRows.atomicWrite(f, data);
    String[] rows = (String[]) r[3];
    for (int i = 0; i + 2 < rows.length; i += 3) @PKG@.CfgLog.enqueue(logLine(rows[i], rows[i + 1], rows[i + 2]));
    if (rows.length > 0) @PKG@.CfgLog.flush();
    String chg = (String) r[1];
    String kept = (String) r[2];
    String msg;
    if (chg.length() > 0) msg = "config.properties updated for 0.2.5: " + chg + " (Skyy 2026-10-09: claimed luggage vanishes at once; the old file is in config-history; Server Setup -> Changes can undo it)";
    else if (kept != null) msg = "config.properties: luggage.shareSeconds was changed by hand - kept, nothing changed (0.2.5 marker added)";
    else msg = "config.properties: no luggage.shareSeconds line on the old default - nothing changed (0.2.5 marker added; the default is 0 = vanishes at once)";
    @PKG@.ExpCfg.info(msg);
    if (kept == null) return msg;
    @PKG@.ExpCfg.info(kept);
    return msg + "\n" + kept;
  } catch (Throwable t) {
    @PKG@.ExpCfg.warn("could not update config.properties for 0.2.5 (luggage vanishes at once; the file is used as it is): " + t);
    return "";
  }
}""")
'''
rep('''LG_CLASSES = [lgapi, lgeng, lgsite, lgreg, lgcore, lguse, lgbrk, lgdmg]
''', '''LG_CLASSES = [lgapi, lgeng, lgsite, lgreg, lgcore, lguse, lgbrk, lgdmg]
''' + LG_MIG + '''LG_CLASSES.append(lgmig)
''')
rep('''  @PKG@.LgReg.DIR = base.resolve("luggage");      // 0.2.4 Unclaimed Luggage registry (per world)
  String sum = @PKG@.ExpCfg.load();''', '''  @PKG@.LgReg.DIR = base.resolve("luggage");      // 0.2.4 Unclaimed Luggage registry (per world)
  @PKG@.ExpLgMig.migrate();                       // 0.2.5 one-time update (luggage.shareSeconds 20 -> 0) BEFORE the config load
  String sum = @PKG@.ExpCfg.load();''')

# ================================================================================================================ assets: the sack looks
rep('''    for _src in ("Furniture_Crude_Chest_Small", "Furniture_Village_Chest_Small", "Furniture_Ancient_Chest_Small", "Furniture_Dungeon_Chest_Epic"):''',
    '''    for _src in ("Tool_Feedbag", "Tool_Fertilizer_Crystal", "Furniture_Ancient_Sack"):''')
rep('''LG_SRC = ["Furniture_Crude_Chest_Small", "Furniture_Village_Chest_Small", "Furniture_Ancient_Chest_Small", "Furniture_Dungeon_Chest_Epic"]''',
    '''# 0.2.5 the sack looks (see the header): (block source for model + hitbox, texture, icon) - all vanilla paths, nothing copied
LG_LOOK = [("Tool_Feedbag", "Items/Tools/Feedbag/Feedbag_Texture.png", "Icons/ItemsGenerated/Tool_Feedbag.png"),
           ("Tool_Feedbag", "Items/Tools/Feedbag/Seedbag_Texture.png", "Icons/ItemsGenerated/Utility_Bag_Seed.png"),
           ("Furniture_Ancient_Sack", "Blocks/Decorative_Sets/Ancient/Sack.png", "Icons/ItemsGenerated/Furniture_Ancient_Sack.png"),
           ("Tool_Feedbag", "Items/Tools/Feedbag/Fertilizer_Crystal.png", "Icons/ItemsGenerated/Tool_Fertilizer_Crystal.png")]
LG_SRC = [_l[0] for _l in LG_LOOK]
LG_HINT = "interactionHints.skyyLuggageClaim"
assert _SRCJ["Tool_Feedbag"]["BlockType"]["CustomModel"] == _SRCJ["Tool_Fertilizer_Crystal"]["BlockType"]["CustomModel"] == "Items/Tools/Feedbag/Feedbag.blockymodel"
assert len(set(_l[1] for _l in LG_LOOK)) == 4 and len(set(_l[2] for _l in LG_LOOK)) == 4, "the four tiers must look different"
for _l in LG_LOOK:
    assert "Chest" not in _l[0] and "Chest" not in _l[1] and "Chest" not in _SRCJ[_l[0]]["BlockType"]["CustomModel"], _l
    assert "BlockEntity" not in _SRCJ[_l[0]]["BlockType"] and "State" not in _SRCJ[_l[0]]["BlockType"], _l     # vanilla deco, no container''')
rep('''for _i, (_bid, _src) in enumerate(zip(LG_IDS, LG_SRC)):
    _v = _SRCJ[_src]
    _vb = _v["BlockType"]
    for _k in ("CustomModel",):
        assert ("Common/" + _vb[_k]) in _NAMES, _vb[_k]
    for _t in _vb["CustomModelTexture"]:
        assert ("Common/" + _t["Texture"]) in _NAMES, _t
    assert ("Common/" + _v["Icon"]) in _NAMES, _v["Icon"]
    _bt = {"Material": "Solid", "DrawType": "Model", "Opacity": "Transparent", "CustomModel": _vb["CustomModel"],
           "CustomModelTexture": [{"Texture": _vb["CustomModelTexture"][0]["Texture"], "Weight": 1}],
           "HitboxType": _vb.get("HitboxType", "Chest_Small"), "VariantRotation": "NESW",
           "Gathering": {"Breaking": {"GatherType": "Woods", "DropList": "Empty"}},
           "BlockParticleSetId": "Wood", "BlockSoundSetId": "Wood", "PhysicalMaterialId": "Wood",
           "Support": {"Down": [{"FaceType": "Full"}]},
           "InteractionHint": "server.interactionHints.open",
           "Interactions": {"Use": {"Interactions": [{"Type": "OpenCustomUI", "Page": {"Id": LG_PAGE}}]}}}
    for _k in ("ParticleColor", "TextureComputedColor"):
        if _k in _vb:
            _bt[_k] = _vb[_k]''', '''for _i, (_bid, _src) in enumerate(zip(LG_IDS, LG_SRC)):
    _v = _SRCJ[_src]
    _vb = _v["BlockType"]
    _tex, _icon = LG_LOOK[_i][1], LG_LOOK[_i][2]
    for _k in ("CustomModel",):
        assert ("Common/" + _vb[_k]) in _NAMES, _vb[_k]
    assert ("Common/" + _tex) in _NAMES, _tex
    assert ("Common/" + _icon) in _NAMES, _icon
    _bt = {"Material": "Solid", "DrawType": "Model", "Opacity": "Transparent", "CustomModel": _vb["CustomModel"],
           "CustomModelTexture": [{"Texture": _tex, "Weight": 1}],
           "HitboxType": _vb.get("HitboxType", "Full"), "VariantRotation": "NESW",
           "Gathering": {"Breaking": {"GatherType": "Woods", "DropList": "Empty"}},
           "BlockParticleSetId": "Dust", "BlockSoundSetId": "Cloth", "PhysicalMaterialId": "Cloth",
           "Support": {"Down": [{"FaceType": "Full"}]},
           "InteractionHint": "server." + LG_HINT,
           "Interactions": {"Use": {"Interactions": [{"Type": "OpenCustomUI", "Page": {"Id": LG_PAGE}}]}}}
    # the sack's own colours for the break / walk particles (the vanilla source block's; the Seedbag look has none -> Feedbag's)
    for _k in ("ParticleColor", "TextureComputedColor"):
        if _k in _vb:
            _bt[_k] = _vb[_k]''')
rep('''        "Variant": True, "MaxStack": 1, "Icon": _v["Icon"], "IconProperties": _v.get("IconProperties", {"Scale": 0.55, "Translation": [0, -15], "Rotation": [22.5, 45, 22.5]}),''',
    '''        "Variant": True, "MaxStack": 1, "Icon": _icon, "IconProperties": _v.get("IconProperties", {"Scale": 0.55, "Translation": [0, -15], "Rotation": [22.5, 45, 22.5]}),''')
rep('''    _lang.append("items.%s.description = Lost luggage of the Department of Arrivals. Press F to claim what is inside - it vanishes soon after." % _bid)''',
    '''    _lang.append("items.%s.description = Lost luggage of the Department of Arrivals. Press F to claim it - the loot goes straight into your inventory and the luggage vanishes." % _bid)
_lang.append(LG_HINT + " = Press [{key}] to claim {name}")      # 0.2.5: the prompt (vanilla's own placeholders, like interactionHints.open)''')
rep('''print("0.2.4 Unclaimed Luggage: %d blocks (%s), page id %s, %d Server Setup rows" % (len(LG_IDS), ", ".join(LG_SRC), LG_PAGE,''',
    '''print("0.2.5 Unclaimed Luggage: %d sack blocks (%s), page id %s, hint %s, %d Server Setup rows" % (len(LG_IDS), ", ".join(_l[1].split("/")[-1] for _l in LG_LOOK), LG_PAGE, LG_HINT,''')
rep('''Unclaimed Luggage: Wynncraft-style loot chests appear on the surface near players (coins, SkyyGear mystery bags, a vanilla roll, XP), each player claims once, then they vanish and come back later; player chests are never touched.''',
    '''Unclaimed Luggage: Wynncraft-style loot sacks appear on the surface near players (coins, SkyyGear mystery bags, a vanilla roll, XP); the first claim empties it and it vanishes at once, coming back later; player chests are never touched.''')

# ================================================================================================================ write
assert "SFX_Chest_Wooden_Close" not in s.split("0.2.4 (the base")[1].split('VERSION = "0.2.5"')[1], "the old chest sound is still used"
assert s.count("registerSystem(") == SYS0 and s.count("registerCommand(") == CMD0, "0.2.5 adds no system and no command"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))
