"""Derive SkyyGear/build_skyygear_0.2.7.py from the LIVE 0.2.6 (build_skyygear_0.2.6.py = the tools/deploy_set.py SET pin, itself GENERATED
by tools/gear_0_2_6_patch.py). Edit THIS file, never the generated script; every anchor is asserted. Run:
    python tools/gear_0_2_7_patch.py      then      python SkyyGear/build_skyygear_0.2.7.py      (never --deploy)
Harness: python SkyyGear/test_skyygear_0.2.7.py (the 0.2.6 harness on the new jar, its Z3 / Z4 / Z5 walk model now also carries our own
crossbows; section AH executes the new trust path, the bands, start twice on a live copy and the class compare 0.2.6 -> 0.2.7).

0.2.7 = THE CHARGED-HIT TRUST LIST FOR OUR OWN CROSSBOWS (Skyy LOCKED docs/answered/gear.md "Copper + Onyxium (Recommended)"; shipped in
SkyyArmory 0.1.3 as Weapon_Crossbow_Copper_Wynn / Weapon_Crossbow_Onyxium_Wynn; deploy log 2026-10-06 20:15 follow-up "SkyyGear trust list
for the new crossbows"). Signal A of Charged Attack Damage (Hytale's own Class Charged on the hit, the crossbow's 3rd bolt in a row) is
trusted only for listed ids (a loose Class tag from another mod never counts). Until now the list was every vanilla weapon id + the pack's
four More Crossbow Tiers crossbows, so the two SkyyArmory crossbows' 3rd-bolt combo never counted and the stat never rolled on them.
  - OWN_TRUST (new, separate from PACK_TRUST - these are our own SkyyArmory items, not a third-party pack mod): Weapon_Crossbow_Copper_Wynn,
    Weapon_Crossbow_Onyxium_Wynn. CHG_TRUST = vanilla + pack + own -> GearChg.TRUST; their charged summary joins GearChg.FALLBACK (the roll
    list used when the runtime walk cannot run). At run time nothing else changes: the engine walk (GearChg.ensure) resolves them through
    the live item map like any item; the Class-tagged combo on them now judges exactly like the vanilla Iron crossbow's
    ("Hytale Charged tag on a hit without a hold (crossbow 3rd bolt in a row)") and the stat may roll on them.
  - THE BUILD-TIME WALK needs their item JSON (the self-check walks every trusted id): read from SkyyArmory's own jar (read only) -
    SkyyArmory/SkyyArmory-0.1.3.jar (the release that shipped them), else the installed Mods/SkyyArmory.jar (manifest Group Skyy, Name
    "<version> SkyyArmory"),
    else REPRODUCED (Parent Template_Weapon_Crossbow + the vanilla Iron crossbow's own InteractionVars - SkyyArmory 0.1.3 builds them exactly
    that way; only the damage numbers differ, which the walk does not read) with one build note. Asserted per item: Parent
    Template_Weapon_Crossbow, no own Interactions (the template's Primary chain = the vanilla combo), every Combo_Projectile_Damage entry
    parents Weapon_Crossbow_Damage_Combo_Projectile. They are walked as overlays (never counted as vanilla: speed tiers, family bases and
    VANILLA_WEAPONS stay exactly 0.2.6's); the crossbow family self-check goes 6 / 6 -> 8 / 8 (gear items / may roll).
  - LEVELS (checked, unchanged): the metal word in the id puts Weapon_Crossbow_Copper_Wynn in the Copper band 10-18 and
    Weapon_Crossbow_Onyxium_Wynn in the Onyxium band 40-49 (GearLevel.band); their family base is the Iron crossbow (GearBase.baseOf, the
    baked FB_FAM / FB_ID "Crossbow" row) like the pack crossbows - no fix needed.
  Nothing else changes: no rows, no data, no migration, no system / command. Rolling back to 0.2.6 is safe (the stat simply stops counting /
  rolling on the two crossbows; items that already rolled it keep the line, like any untrusted weapon).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.6.py")
DST = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.7.py")
raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.2.6"' in s and s.startswith('"""SkyyGear 0.2.6 - build script'), "build_skyygear_0.2.6.py is not the live 0.2.6"
SYS0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:160])
    s = s.replace(old, new)


# ================================================================================================================ header + version
HEAD = open(__file__, encoding="utf8").read().split('"""')[1]
rep('''"""SkyyGear 0.2.6 - build script (javassist via jpype). GENERATED by tools/gear_0_2_6_patch.py from the LIVE 0.2.5 - edit the patch,
never this file. Run: python SkyyGear/build_skyygear_0.2.6.py -> SkyyGear/SkyyGear-0.2.6.jar (never --deploy).

0.2.6 = ''', '''"""SkyyGear 0.2.7 - build script (javassist via jpype). GENERATED by tools/gear_0_2_7_patch.py from the LIVE 0.2.6 - edit the patch,
never this file. Run: python SkyyGear/build_skyygear_0.2.7.py -> SkyyGear/SkyyGear-0.2.7.jar (never --deploy).

''' + HEAD[HEAD.index("0.2.7 = "):].strip() + '''

0.2.6 (the base, everything below is still true unless 0.2.7 above says otherwise):
0.2.6 = ''')
rep('VERSION = "0.2.6"', 'VERSION = "0.2.7"')
rep('''      A = Hytale's own Class Charged on the hit's DamageSequence - trusted ONLY for vanilla weapon ids + the pack's More Crossbow
          Tiers crossbows (verifier: a loose Class tag from another mod never counts)''',
    '''      A = Hytale's own Class Charged on the hit's DamageSequence - trusted ONLY for vanilla weapon ids + the pack's More Crossbow
          Tiers crossbows + (0.2.7) our own SkyyArmory crossbows (verifier: a loose Class tag from another mod never counts)''')

# ================================================================================================================ the own-items trust list
rep('''else:
    print("note: no More_Crossbow_Tiers*.zip (Serj / More Crossbow Tiers) in the Mods folder - the baked pack list (PACK.md, 1.1.0) is used unchecked")
CW = AzWalker(AZ, AZ_NAMES, _MCT)
VANILLA_WEAPONS = sorted(i for i in CW.items if i.startswith("Weapon_") and not str(CW.items[i]).startswith("overlay:"))
CHG_TRUST = sorted(set(VANILLA_WEAPONS) | set(PACK_TRUST))''', '''else:
    print("note: no More_Crossbow_Tiers*.zip (Serj / More Crossbow Tiers) in the Mods folder - the baked pack list (PACK.md, 1.1.0) is used unchecked")
# 0.2.7: OUR OWN items whose Class-tagged steps are trusted like vanilla (NOT a pack mod: SkyyArmory, Skyy's own mod). Skyy LOCKED
# "Copper + Onyxium (Recommended)" (docs/answered/gear.md); SkyyArmory 0.1.3 ships them = the vanilla Iron crossbow (Parent
# Template_Weapon_Crossbow: the same Primary chain, so the 3rd bolt in a row is Hytale's Class Charged combo) with the tier's numbers.
OWN_TRUST = ["Weapon_Crossbow_Copper_Wynn", "Weapon_Crossbow_Onyxium_Wynn"]
OWN_SRC_JAR = "SkyyArmory-0.1.3.jar"
_OWN = {}


def own_items(ids):
    """the own items' JSON for the build-time walk (read only): SkyyArmory's release jar in the project, else the installed SkyyArmory.jar
    (manifest Group Skyy, Name "<version> SkyyArmory"), else None (the caller reproduces them from the vanilla Iron crossbow)"""
    proj = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "SkyyArmory", OWN_SRC_JAR)
    for p_ in (proj, os.path.join(B.MODS_DIR, "SkyyArmory.jar")):
        if not os.path.isfile(p_):
            continue
        try:
            with zipfile.ZipFile(p_) as z_:
                m_ = json.loads(z_.read("manifest.json").decode("utf-8-sig"))
                # skyybuild names the pack "<version> SkyyArmory" (manifest Name "0.1.3 SkyyArmory")
                if m_.get("Group") != "Skyy" or str(m_.get("Name", "")).split(" ")[-1] != "SkyyArmory":
                    continue
                got_ = {}
                for n_ in z_.namelist():
                    b_ = os.path.basename(n_)[:-5]
                    if n_.startswith("Server/Item/Items/") and n_.endswith(".json") and b_ in ids:
                        got_[b_] = json.loads(z_.read(n_).decode("utf-8-sig"))
            if sorted(got_) == sorted(ids):
                return got_, "%s (SkyyArmory %s)" % (os.path.basename(p_), m_.get("Version"))
        except Exception:
            continue
    return None, None


_OWN, OWN_FROM = own_items(OWN_TRUST)
if _OWN is None:
    _vx = json.loads(AZ.read("Server/Item/Items/Weapon/Crossbow/Weapon_Crossbow_Iron.json").decode("utf-8-sig"))
    _OWN = dict((i, {"Parent": _vx["Parent"], "InteractionVars": _vx.get("InteractionVars") or {}}) for i in OWN_TRUST)
    OWN_FROM = "REPRODUCED from the vanilla Iron crossbow (no SkyyArmory jar with them found)"
    print("note: own crossbows " + OWN_FROM)
for _i, _d in _OWN.items():
    assert _d.get("Parent") == "Template_Weapon_Crossbow", "own item %s no longer parents Template_Weapon_Crossbow" % _i
    assert "Interactions" not in _d, "own item %s names its own Interactions now - re-check the trust (0.2.7)" % _i
    _cv = (_d.get("InteractionVars") or {}).get("Combo_Projectile_Damage")
    assert _cv is None or all((isinstance(_x, dict) and _x.get("Parent") == "Weapon_Crossbow_Damage_Combo_Projectile") or
                              _x == "Weapon_Crossbow_Damage_Combo_Projectile" for _x in _cv.get("Interactions", [])), _i
assert not set(OWN_TRUST) & set(PACK_TRUST) and not set(OWN_TRUST) & set(_MCT), "own ids must never collide with the pack's"
_OVL = dict(_MCT)
_OVL.update(_OWN)
CW = AzWalker(AZ, AZ_NAMES, _OVL)
assert not [i for i in OWN_TRUST if i in AZ_NAMES or not str(CW.items.get(i)).startswith("overlay:")], "an own id is a vanilla id now"
VANILLA_WEAPONS = sorted(i for i in CW.items if i.startswith("Weapon_") and not str(CW.items[i]).startswith("overlay:"))
CHG_TRUST = sorted(set(VANILLA_WEAPONS) | set(PACK_TRUST) | set(OWN_TRUST))''')
# the crossbow family: Iron + Ancient (vanilla) + 4 pack + 2 own
rep('''"Weapon_Crossbow_": (6, 6),''', '''"Weapon_Crossbow_": (8, 8),''')
rep('''print("charged attack walk: %d vanilla + %d pack weapons; %d may roll Charged Attack Damage; bow glow = the %.1f s draw (Bow_Charging)"
      % (len(VANILLA_WEAPONS), len(PACK_TRUST), len(CHG_FALLBACK), BOW_GLOW_S))''',
    '''# 0.2.7: both own crossbows walk exactly like the vanilla Iron crossbow: ONE combo step (Class Charged, reached without a hold), no
# partial levels, may roll - the same summary shape as the Iron crossbow
_IXS = CHG_SUM["Weapon_Crossbow_Iron"]
for _i in OWN_TRUST:
    _os = CHG_SUM[_i]
    assert _os["has"] and len(_os["combo"]) == 1 and not _os["partial"] and _i in CHG_FALLBACK and _i in CHG_TRUST, _i
    assert sorted((e[0], e[1]) for e in _os["calcs"].values()) == sorted((e[0], e[1]) for e in _IXS["calcs"].values()), \\
        "own crossbow %s walks differently from the Iron crossbow" % _i
print("charged attack walk: %d vanilla + %d pack + %d own weapons (own from %s); %d may roll Charged Attack Damage; bow glow = the %.1f s "
      "draw (Bow_Charging)" % (len(VANILLA_WEAPONS), len(PACK_TRUST), len(OWN_TRUST), OWN_FROM, len(CHG_FALLBACK), BOW_GLOW_S))''')

# ================================================================================================================ write
assert s.count("registerSystem(") == SYS0 and s.count("registerCommand(") == CMD0, "0.2.7 adds no system / command"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))
