"""Derive SkyyGear/build_skyygear_0.2.8.py from the LIVE 0.2.7 (build_skyygear_0.2.7.py = the tools/deploy_set.py SET pin, itself GENERATED
by tools/gear_0_2_7_patch.py). Edit THIS file, never the generated script; every anchor is asserted. Run:
    python tools/gear_0_2_8_patch.py      then      python SkyyGear/build_skyygear_0.2.8.py      (never --deploy)
Harness: python SkyyGear/test_skyygear_0.2.8.py (the 0.2.7 harness on the new jar + section AI).

0.2.8 = THE KUNAI LADDER'S LEVEL BANDS (SkyyArmory 0.1.6 ships the Assassin kunai Weapon_Kunai_Crude / _Copper ... _Onyxium and the Mage
spellbooks Weapon_Spellbook_Copper ... _Onyxium; Skyy LOCKED docs/answered/gear.md 2026-10-07 "SPELLBOOKS + KUNAI": every default of
research/cloud/Kunai-Ladder.md, whose section 9 item 1 asks exactly this). Proven at build time (both before and after the change):
  - THE TRAP: GearLevel's band lookup reads the id words from the left, the longest entry first, and the vanilla Kunai has its own family row
    level.material.Kunai (20, band 20-27). So Weapon_Kunai_Copper resolved to "kunai" (20-27) instead of Copper 10-18, and the Crude kunai
    (Lv 1 for a new Assassin) to 20 - the band lookup of 0.2.7 is asserted below to give exactly that.
  - THE FIX (one rule, both Java loops = GearLevel.level + GearLevel.entry, and the Python mirror lvl_lookup): for an id
    Weapon_<word>_<more> whose <word> is in METAL_FIRST (= ["kunai"]: a family word that has its own row AND a metal ladder after it), the
    look starts at the third word; when nothing matches from there, the old full look runs (an id like Weapon_Kunai_Foo keeps the Kunai row).
    Proof: every vanilla gear id of Assets.zip resolves to the same entry as in 0.2.7 (no vanilla id starts with Weapon_Kunai_), the vanilla
    Weapon_Kunai stays "kunai" 20-27, Weapon_Kunai_<Crude ... Onyxium> resolve to their metal (Crude 1-13 ... Onyxium 40-49).
  - SPELLBOOKS NEED NO FIX (proven): no level row is the single word "spellbook" (only Spellbook_Fire / Spellbook_Frost), so
    Weapon_Spellbook_<Metal> already resolves to its metal word; SPELL_PREFIXES already holds Weapon_Spellbook_ (spells: K = 1).
  - FAMILY BASES (GearBase.baseOf): the Kunai and Spellbook families had no Crude / Wood / Iron base item (BASE_NOFAM), so each vanilla item
    was its own base. With SkyyArmory's Weapon_Kunai_Crude / Weapon_Spellbook_Iron in the live item map, the run-time search would now pick
    them as the base of the VANILLA Weapon_Kunai and the vanilla spellbooks and change the vanilla Kunai's damage. OWN_BASE pins every vanilla
    item of those two families to itself (exactly 0.2.7's answer); our kunai find Weapon_Kunai_Crude (band 1, divisor 1) by the same search,
    so the level band divisor is the Crude one (band start 1, divisor 1) like the daggers'.
  - KUNAI TWIN (fix round, critic: "kunai DPS = 80 % of the dagger" must hold WITH SkyyGear too): SkyyArmory sets every kunai hit to 1.12 x
    the same-metal dagger's average hit (= 80 % of its DPS at the Fast cadence). SkyyGear's K normalises each item by its largest damage entry,
    so the old K (Crude kunai size / this kunai's size) gave every kunai the Crude kunai's hit x F(level) while each dagger kept its own
    entry shape - 0.93-1.11 x the same-level dagger, 0.62 at Onyxium. GearBase.kunaiTwin: a Weapon_Kunai_<Metal> whose Weapon_Daggers_<Metal>
    exists takes THAT dagger's K (ratio + family base divisor), so kunai / dagger at the same level = exactly SkyyArmory's 1.12 x the average
    (the hit rounding aside) at every metal. The vanilla Weapon_Kunai (no metal word) and an id with no matching dagger keep the 0.2.7 path.
Nothing else changes: no rows, no data, no migration, no system / command. Rolling back to 0.2.7 is safe (the kunai then level by the Kunai row
20-27, the vanilla Kunai takes Weapon_Kunai_Crude as its base while SkyyArmory 0.1.6 is installed).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.7.py")
DST = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.8.py")
raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.2.7"' in s and s.startswith('"""SkyyGear 0.2.7 - build script'), "build_skyygear_0.2.7.py is not the live 0.2.7"
SYS0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:160])
    s = s.replace(old, new)


# ================================================================================================================ header + version
HEAD = open(__file__, encoding="utf8").read().split('"""')[1]
rep('''"""SkyyGear 0.2.7 - build script (javassist via jpype). GENERATED by tools/gear_0_2_7_patch.py from the LIVE 0.2.6 - edit the patch,
never this file. Run: python SkyyGear/build_skyygear_0.2.7.py -> SkyyGear/SkyyGear-0.2.7.jar (never --deploy).

0.2.7 = ''', '''"""SkyyGear 0.2.8 - build script (javassist via jpype). GENERATED by tools/gear_0_2_8_patch.py from the LIVE 0.2.7 - edit the patch,
never this file. Run: python SkyyGear/build_skyygear_0.2.8.py -> SkyyGear/SkyyGear-0.2.8.jar (never --deploy).

''' + HEAD[HEAD.index("0.2.8 = "):].strip() + '''

0.2.7 (the base, everything below is still true unless 0.2.8 above says otherwise):
0.2.7 = ''')
rep('VERSION = "0.2.7"', 'VERSION = "0.2.8"')

# ================================================================================================================ the Python mirror + proof
rep('''def lvl_lookup(table, i):
    """GearLevel.level's material step in Python (the jar runs the same loop): at each id word from the left the longest entry first,
    up to the most words any entry has (max 3); -> (entry in lower case, level) or (None, None)"""
    m = dict((t.lower(), l) for t, l in table)
    mw = min(3, max(len(t.split("_")) for t, _l in table))
    tk = i.split("_")
    for a in range(len(tk)):
        for n in range(mw, 0, -1):
            if a + n <= len(tk) and "_".join(tk[a:a + n]).lower() in m:
                return "_".join(tk[a:a + n]).lower(), m["_".join(tk[a:a + n]).lower()]
    return None, None
''', '''# 0.2.8: family words whose ids carry a metal ladder after them (Weapon_Kunai_<Metal>, SkyyArmory 0.1.6): the look starts at the third word
METAL_FIRST = ["kunai"]


def lvl_first(tk):
    """0.2.8: where the material look starts (GearLevel.first): word 2 for Weapon_<METAL_FIRST word>_<more>, else word 0"""
    return 2 if len(tk) >= 3 and tk[0] == "Weapon" and tk[1].lower() in METAL_FIRST else 0


def lvl_lookup(table, i, rule028=True):
    """GearLevel.level's material step in Python (the jar runs the same loop): at each id word from the left the longest entry first,
    up to the most words any entry has (max 3); -> (entry in lower case, level) or (None, None). 0.2.8 (rule028): a METAL_FIRST id looks
    from its third word first, then (nothing found there) from the first word like before"""
    m = dict((t.lower(), l) for t, l in table)
    mw = min(3, max(len(t.split("_")) for t, _l in table))
    tk = i.split("_")
    starts = ([lvl_first(tk)] if rule028 and lvl_first(tk) > 0 else []) + [0]
    for st0 in starts:
        for a in range(st0, len(tk)):
            for n in range(mw, 0, -1):
                if a + n <= len(tk) and "_".join(tk[a:a + n]).lower() in m:
                    return "_".join(tk[a:a + n]).lower(), m["_".join(tk[a:a + n]).lower()]
    return None, None
''')
rep('''assert _now["Weapon_Daggers_Stone_Trork"] == ("stone", 5), "Skyy's report: Stone Trork Daggers"
''', '''assert _now["Weapon_Daggers_Stone_Trork"] == ("stone", 5), "Skyy's report: Stone Trork Daggers"
# 0.2.8 PROOF (Kunai-Ladder.md section 9 item 1): the 0.2.7 rule put the SkyyArmory kunai ladder in the Kunai row; the 0.2.8 rule puts it on its
# metal word and changes NO vanilla gear id; the spellbook ladder resolves to its metal under both rules (no spellbook fix needed)
KUNAI_LADDER = ["Weapon_Kunai_%s" % _m for _m in ("Crude", "Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")]
BOOK_LADDER = ["Weapon_Spellbook_%s" % _m for _m in ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium")]
_k027 = dict((i, lvl_lookup(_NEW2, i, False)) for i in KUNAI_LADDER + BOOK_LADDER + ["Weapon_Kunai"])
_k028 = dict((i, lvl_lookup(_NEW2, i)) for i in KUNAI_LADDER + BOOK_LADDER + ["Weapon_Kunai"])
assert all(_k027[i] == ("kunai", 20) for i in KUNAI_LADDER), "0.2.7 should resolve the kunai ladder to the Kunai row: %s" % _k027
assert [_k028[i][0] for i in KUNAI_LADDER] == ["crude", "copper", "iron", "thorium", "cobalt", "adamantite", "mithril", "onyxium"], _k028
assert _k028["Weapon_Kunai"] == _k027["Weapon_Kunai"] == ("kunai", 20), "the vanilla Kunai keeps its own row"
assert all(_k027[i] == _k028[i] and _k028[i][0] == i.split("_")[2].lower() for i in BOOK_LADDER), "spellbook ladder: %s" % _k027
assert "spellbook" not in dict((t.lower(), l) for t, l in _NEW2), "a level row named Spellbook would catch the spellbook ladder"
assert lvl_lookup(_NEW2, "Weapon_Kunai_Foo") == ("kunai", 20), "a METAL_FIRST id without a metal word keeps the family row"
_chg028 = [i for i in sorted(AZ_ITEMS) if lvl_lookup(_NEW2, i) != lvl_lookup(_NEW2, i, False)]
assert not _chg028 and not [i for i in AZ_ITEMS if i.startswith("Weapon_Kunai_")], "0.2.8 changed a vanilla id's level entry: %s" % _chg028[:5]
print("0.2.8 kunai ladder bands: %s (0.2.7: all 'kunai' 20); spellbook ladder = its metal under both rules; vanilla ids changed: none of %d"
      % (", ".join("%s=%s" % (i[len("Weapon_Kunai_"):], _k028[i][0]) for i in KUNAI_LADDER), len(AZ_ITEMS)))
''')

# ================================================================================================================ the own-base pin
rep('''BASE_NOFAM = sorted(set(base_family(i) for i in BASE_GEAR) - set(f for f, _b in FAM_BASE))
assert BASE_NOFAM == ["Kunai", "Spellbook"], BASE_NOFAM
''', '''BASE_NOFAM = sorted(set(base_family(i) for i in BASE_GEAR) - set(f for f, _b in FAM_BASE))
assert BASE_NOFAM == ["Kunai", "Spellbook"], BASE_NOFAM
# 0.2.8: the vanilla items of the own-base families stay their own base (SkyyArmory 0.1.6 adds Weapon_Kunai_Crude / Weapon_Spellbook_Iron, which
# the run-time Crude / Wood / Iron search would otherwise pick for them)
OWN_BASE = sorted(i for i in BASE_GEAR if base_family(i) in BASE_NOFAM)
assert "Weapon_Kunai" in OWN_BASE and not [i for i in OWN_BASE if i.startswith("Weapon_Kunai_")] and len(OWN_BASE) >= 2, OWN_BASE
print("0.2.8 own-base pins (vanilla items of %s): %s" % (", ".join(BASE_NOFAM), ", ".join(OWN_BASE)))
''')
rep('''F(gdf, "public static final String[] FB_ID = %s;" % jarr([b for f, b in FAM_BASE]))
''', '''F(gdf, "public static final String[] FB_ID = %s;" % jarr([b for f, b in FAM_BASE]))
F(gdf, "public static final String[] OWN_BASE = %s;" % jarr(OWN_BASE))          # 0.2.8: vanilla own-base items stay their own base
F(gdf, "public static final String[] METAL_FIRST = %s;" % jarr(METAL_FIRST))    # 0.2.8: Weapon_Kunai_<Metal> looks from its third word
''')
rep('''  Object o = BASE.get(id);
  if (o instanceof String) { String s0 = (String) o; return s0.length() == 0 ? id : s0; }
  String f = family(id);''', '''  Object o = BASE.get(id);
  if (o instanceof String) { String s0 = (String) o; return s0.length() == 0 ? id : s0; }
  for (int k = 0; k < @PKG@.GearDefs.OWN_BASE.length; k++) {          // 0.2.8: the vanilla Kunai / spellbooks stay their own base
    if (@PKG@.GearDefs.OWN_BASE[k].equals(id)) { if (BASE.size() > 4096) BASE.clear(); BASE.put(id, ""); return id; }
  }
  String f = family(id);''')

# ================================================================================================================ the kunai twin (K follows the dagger)
rep('''M(gbase, r"""
public static double ratio(String id) {''', '''# 0.2.8 KUNAI TWIN: a SkyyArmory Weapon_Kunai_<Metal> scales exactly like Weapon_Daggers_<Metal> (its hit is set to 1.12 x that dagger's average
# hit = 80 % of the dagger's DPS); no matching dagger (or the vanilla Weapon_Kunai) = the id itself
M(gbase, r"""
public static String kunaiTwin(String id) {
  if (id == null || id.length() <= 13 || !id.startsWith("Weapon_Kunai_")) return id;
  String dg = "Weapon_Daggers_" + id.substring(13);
  return @PKG@.Gear.item(dg) == null ? id : dg;
}""")
M(gbase, r"""
public static double ratio(String id) {''')
rep('''  boolean keep = true;
  String b = baseOf(id);
  if (!b.equals(id)) {
    float mi = maxEntry(id);
    float mb = maxEntry(b);''', '''  boolean keep = true;
  String src = kunaiTwin(id);          // 0.2.8: a kunai reads its dagger twin (the id itself otherwise)
  String b = baseOf(src);
  if (!b.equals(src)) {
    float mi = maxEntry(src);
    float mb = maxEntry(b);''')
rep('''public static double kOf(String id, boolean spell) {
  if (spell) return 1.0;
  String b = baseOf(id);''', '''public static double kOf(String id, boolean spell) {
  if (spell) return 1.0;
  String b = baseOf(kunaiTwin(id));          // 0.2.8: a kunai takes its dagger twin's family base divisor''')

# ================================================================================================================ the Java look (both loops)
rep('''M(glv, r"""
public static int level(String id, @BD@ d) {''', '''# 0.2.8: where the material look starts (Weapon_Kunai_<Metal>: the third word) + the look itself from a word (null = none) - level() and
# entry() use both, so the two loops can never drift apart
M(glv, r"""
public static int first(String[] tk) {
  if (tk == null || tk.length < 3 || !"Weapon".equals(tk[0])) return 0;
  String f = tk[1].toLowerCase();
  for (int i = 0; i < @PKG@.GearDefs.METAL_FIRST.length; i++) if (@PKG@.GearDefs.METAL_FIRST[i].equals(f)) return 2;
  return 0;
}""")
M(glv, r"""
public static String keyFrom(String[] tk, int from, java.util.HashMap mat, int mw) {
  if (tk == null || mat == null) return null;
  for (int i = from; i < tk.length; i++) {
    for (int n = mw; n >= 1; n--) {
      if (i + n > tk.length) continue;
      String key = tk[i].toLowerCase();
      for (int j = 1; j < n; j++) key = key + "_" + tk[i + j].toLowerCase();
      if (mat.get(key) instanceof Integer) return key;
    }
  }
  return null;
}""")
M(glv, r"""
public static String look(String[] tk, java.util.HashMap mat, int mw) {
  int f0 = first(tk);
  String k = keyFrom(tk, f0, mat, mw);
  if (k == null && f0 > 0) k = keyFrom(tk, 0, mat, mw);
  return k;
}""")
M(glv, r"""
public static int level(String id, @BD@ d) {''')
rep('''  java.util.HashMap mat = @PKG@.GearCfg.MAT;
  int mw = @PKG@.GearCfg.MAT_WORDS;
  String[] tk = id.split("_");
  for (int i = 0; i < tk.length; i++) {
    for (int n = mw; n >= 1; n--) {
      if (i + n > tk.length) continue;
      String key = tk[i].toLowerCase();
      for (int j = 1; j < n; j++) key = key + "_" + tk[i + j].toLowerCase();
      Object m = mat.get(key);
      if (m instanceof Integer) return clamp(((Integer) m).intValue());
    }
  }
  if (@PKG@.GearCfg.LEVEL_VANILLA) {''', '''  java.util.HashMap mat = @PKG@.GearCfg.MAT;
  int mw = @PKG@.GearCfg.MAT_WORDS;
  String mk = look(id.split("_"), mat, mw);          // 0.2.8: Weapon_Kunai_<Metal> looks from its metal word first
  Object m = mk == null ? null : mat.get(mk);
  if (m instanceof Integer) return clamp(((Integer) m).intValue());
  if (@PKG@.GearCfg.LEVEL_VANILLA) {''')
rep('''  java.util.HashMap mat = @PKG@.GearCfg.MAT;
  int mw = @PKG@.GearCfg.MAT_WORDS;
  String[] tk = id.split("_");
  for (int i = 0; i < tk.length; i++) {
    for (int n = mw; n >= 1; n--) {
      if (i + n > tk.length) continue;
      String key = tk[i].toLowerCase();
      for (int j = 1; j < n; j++) key = key + "_" + tk[i + j].toLowerCase();
      if (mat.get(key) instanceof Integer) return key;
    }
  }
  return null;
}""")''', '''  java.util.HashMap mat = @PKG@.GearCfg.MAT;
  int mw = @PKG@.GearCfg.MAT_WORDS;
  return look(id.split("_"), mat, mw);          // 0.2.8: the same look as level()
}""")''')

# ================================================================================================================ write
assert s.count("registerSystem(") == SYS0 and s.count("registerCommand(") == CMD0, "0.2.8 adds no system / command"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))
