"""Derive SkyyGear/build_skyygear_0.2.9.py from the LIVE 0.2.8 (build_skyygear_0.2.8.py = the tools/deploy_set.py SET pin, itself GENERATED
by tools/gear_0_2_8_patch.py). Edit THIS file, never the generated script; every anchor is asserted. Run:
    python tools/gear_0_2_9_patch.py      then      python SkyyGear/build_skyygear_0.2.9.py      (never --deploy)
Harness: python SkyyGear/test_skyygear_0.2.9.py (the 0.2.8 harness on the new jar + section AJ).

0.2.9 = THE MONK WEAPONS SCALE LIKE THE SAME-METAL SWORD (SkyyArmory 0.1.7 ships Weapon_Bo_<Metal>, Weapon_Fist_Gauntlets_<Metal> and
Weapon_Fist_Wraps_<Linen / Cotton / Silk / Cindercloth / Shadoweave>; Skyy LOCKED docs/answered/gear.md 2026-10-07 MONK WEAPONS round + the FIST
ATTACKS lock in classes.md; their hits are set in SkyyArmory as a share of the same-metal vanilla sword's DPS - bo 0.82, gauntlets 0.9, wraps
0.95 x the sword of the cloth's metal column, research/cloud/Monk-Kit-Spec.md 1.1 / 2.1). Proven at build time + in the harness:
  - THE TRAP (0.2.8): SkyyGear's K normalises an item to its FAMILY BASE (the Crude / Wood / Iron item of the id's family word). The new families
    "Fist" (no Crude / Wood / Iron item) make every fist weapon its own base: it deals its own hit at its band start x F(level) / F(start) - while
    a sword deals the CRUDE sword's hit x F(level). With the default Weapon curve that is about 0.66 x the intended share of the sword at
    Copper (Lv 10) and 0.39 x at Adamantite (Lv 35) (largest entries 16 / 21 / 41, F 2.0 / 6.5, before the material bonus); the "Bo" family
    took SkyyArmory's own Iron Bo as its base (about 0.75 x at Lv 15, every tier tied to the Iron Bo).
  - THE FIX (the kunai-twin rule, generalised): GearBase.kunaiTwin also maps Weapon_Fist_Gauntlets_<Metal> and Weapon_Bo_<Metal> to
    Weapon_Sword_<Metal>, Weapon_Fist_Wraps_<Cloth> to Weapon_Sword_<the cloth's metal column> (Linen Copper, Cotton Iron, Silk Thorium,
    Cindercloth Cobalt, Shadoweave Adamantite - the SkyyArmory / make_fists.py table). Such an item takes THAT sword's K (ratio + family base
    divisor), so its hit / the sword's hit at the same level = SkyyArmory's own share at every level. No twin sword in the item map / an id
    outside the three prefixes = the id itself (0.2.8's answer). No vanilla id starts with the three prefixes (asserted).
  - LEVELS NEED NO FIX (proven in SkyyArmory 0.1.7's harness R11a): bo staffs + gauntlets band by their metal word, wraps by SkyyGear's cloth
    rows (Linen 10-17 ... Cindercloth 30-37); Shadoweave has no row -> its item level 35 (an admin adds level.material.Shadoweave in Server Setup).
Nothing else changes: no rows, no data, no migration, no system / command. Rolling back to 0.2.8 is safe (the Monk weapons then scale as their
own base: weaker per level, nothing lost).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.8.py")
DST = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.9.py")
raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.2.8"' in s and s.startswith('"""SkyyGear 0.2.8 - build script'), "build_skyygear_0.2.8.py is not the live 0.2.8"
SYS0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:160])
    s = s.replace(old, new)


# ================================================================================================================ header + version
HEAD = open(__file__, encoding="utf8").read().split('"""')[1]
rep('''"""SkyyGear 0.2.8 - build script (javassist via jpype). GENERATED by tools/gear_0_2_8_patch.py from the LIVE 0.2.7 - edit the patch,
never this file. Run: python SkyyGear/build_skyygear_0.2.8.py -> SkyyGear/SkyyGear-0.2.8.jar (never --deploy).

0.2.8 = ''', '''"""SkyyGear 0.2.9 - build script (javassist via jpype). GENERATED by tools/gear_0_2_9_patch.py from the LIVE 0.2.8 - edit the patch,
never this file. Run: python SkyyGear/build_skyygear_0.2.9.py -> SkyyGear/SkyyGear-0.2.9.jar (never --deploy).

''' + HEAD[HEAD.index("0.2.9 = "):].strip() + '''

0.2.8 (the base, everything below is still true unless 0.2.9 above says otherwise):
0.2.8 = ''')
rep('VERSION = "0.2.8"', 'VERSION = "0.2.9"')

# ================================================================================================================ the twin table + its proof
TWIN_PY = '''
# 0.2.9: the Monk weapon twin (SkyyArmory 0.1.7): these prefixes + a metal (wraps: a cloth -> its metal column) take Weapon_Sword_<metal>'s K
TWIN_PRE = ["Weapon_Fist_Gauntlets_", "Weapon_Fist_Wraps_", "Weapon_Bo_"]
TWIN_CLOTH = ["Linen", "Cotton", "Silk", "Cindercloth", "Shadoweave"]
TWIN_COL = ["Copper", "Iron", "Thorium", "Cobalt", "Adamantite"]
assert not [i for i in AZ_ITEMS if i.startswith(tuple(TWIN_PRE))], "a vanilla id starts with a Monk twin prefix - the twin would move it"
for _c in TWIN_COL:
    assert ("Weapon_Sword_" + _c) in AZ_ITEMS, "no vanilla Weapon_Sword_" + _c
for _m in ("Copper", "Iron", "Thorium", "Cobalt", "Adamantite", "Mithril", "Onyxium"):
    assert ("Weapon_Sword_" + _m) in AZ_ITEMS, "no vanilla Weapon_Sword_" + _m
print("0.2.9 Monk twin: %s -> Weapon_Sword_<metal>; wraps %s" % (", ".join(TWIN_PRE), ", ".join("%s=%s" % (c, m) for c, m in zip(TWIN_CLOTH, TWIN_COL))))
'''
rep('''print("0.2.8 own-base pins (vanilla items of %s): %s" % (", ".join(BASE_NOFAM), ", ".join(OWN_BASE)))
''', '''print("0.2.8 own-base pins (vanilla items of %s): %s" % (", ".join(BASE_NOFAM), ", ".join(OWN_BASE)))
''' + TWIN_PY)
rep('''F(gdf, "public static final String[] METAL_FIRST = %s;" % jarr(METAL_FIRST))    # 0.2.8: Weapon_Kunai_<Metal> looks from its third word
''', '''F(gdf, "public static final String[] METAL_FIRST = %s;" % jarr(METAL_FIRST))    # 0.2.8: Weapon_Kunai_<Metal> looks from its third word
F(gdf, "public static final String[] TWIN_PRE = %s;" % jarr(TWIN_PRE))          # 0.2.9: the Monk weapon twin (-> Weapon_Sword_<metal>)
F(gdf, "public static final String[] TWIN_CLOTH = %s;" % jarr(TWIN_CLOTH))
F(gdf, "public static final String[] TWIN_COL = %s;" % jarr(TWIN_COL))
''')

# ================================================================================================================ the twin (K follows the sword)
rep('''M(gbase, r"""
public static String kunaiTwin(String id) {
  if (id == null || id.length() <= 13 || !id.startsWith("Weapon_Kunai_")) return id;
  String dg = "Weapon_Daggers_" + id.substring(13);
  return @PKG@.Gear.item(dg) == null ? id : dg;
}""")''', '''# 0.2.9 MONK TWIN: the metal of a Monk weapon id (a wrap's cloth -> its metal column); null = not a Monk weapon id
M(gbase, r"""
public static String monkMetal(String id) {
  if (id == null) return null;
  for (int i = 0; i < @PKG@.GearDefs.TWIN_PRE.length; i++) {
    String p = @PKG@.GearDefs.TWIN_PRE[i];
    if (id.length() <= p.length() || !id.startsWith(p)) continue;
    String w = id.substring(p.length());
    for (int k = 0; k < @PKG@.GearDefs.TWIN_CLOTH.length; k++) if (@PKG@.GearDefs.TWIN_CLOTH[k].equals(w)) return @PKG@.GearDefs.TWIN_COL[k];
    return w;
  }
  return null;
}""")
M(gbase, r"""
public static String kunaiTwin(String id) {
  if (id == null) return id;
  if (id.length() > 13 && id.startsWith("Weapon_Kunai_")) {
    String dg = "Weapon_Daggers_" + id.substring(13);
    return @PKG@.Gear.item(dg) == null ? id : dg;
  }
  String mm = monkMetal(id);          // 0.2.9: a Monk weapon scales like the same-metal sword
  if (mm == null) return id;
  String sw = "Weapon_Sword_" + mm;
  return @PKG@.Gear.item(sw) == null ? id : sw;
}""")''')

# ================================================================================================================ write
assert s.count("registerSystem(") == SYS0 and s.count("registerCommand(") == CMD0, "0.2.9 adds no system / command"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))
