"""Derive SkyyGear/build_skyygear_0.2.4.py from the LIVE 0.2.3 (build_skyygear_0.2.3.py = the tools/deploy_set.py SET pin). SkyyGear had no
patch scripts until now (each version was a direct copy); this is the first - every anchor is asserted. Edit THIS file, never the generated
script. Run:  python tools/gear_0_2_4_patch.py   then   python SkyyGear/build_skyygear_0.2.4.py   (never --deploy; deploy order
SkyyClasses 0.1.12 -> SkyyArmory 0.1.1 -> SkyyGear 0.2.4, research/Magic-Traversal-Spec.md 3.4). Regression: the 0.2.3 harness runs on the
new jar (python SkyyGear/test_skyygear_0.2.3.py --jar SkyyGear/SkyyGear-0.2.4.jar); the new lines are executed by SkyyArmory's 0.1.1 harness
(section G2: SkyyGear 0.2.4's GearBase.shots on SkyyArmory 0.1.1's real armory:fn:info answers).

0.2.4 = THE TRAVERSAL WORDS IN THE WAND / STAFF TOOLTIP (research/Magic-Traversal-Spec.md 3.3; SkyyArmory 0.1.1):
  SkyyArmory 0.1.1's armory:fn:info answers 11 elements: [8] String traversal words ("Hold - blink 10 blocks + light trail - 10 Stamina" /
  "Hold - hop back + burst 6 blocks + heal orb 9 blocks - 7.5 Stamina"; "" = none: the Wood wand's hold, staff.mode orb, part.trav off),
  [9] String quick-shot words ("pierces - 16 blocks" / "24 blocks"), [10] Double the staff quick-shot bonus % (its live quick.staffBonus;
  0 for wands and with SkyyArmory's damage tune off). GearBase.shots now:
    - adds ONE line right after "Charged shot - N Mana - X damage at Lv L": [8] (when not empty);
    - appends " - " + [9] to the "Quick shot - M Mana - Y damage at Lv L" line (when not empty);
    - multiplies the staff quick shot's shown damage by (1 + [10] / 100) inside the tune branch - the number ArmoryTuneSys really deals.
  An older SkyyArmory (8 elements) = exactly 0.2.3's lines. GearCfg.armorySig already hashes the whole answer, so a row change in
  Server Setup > Armory re-renders the lines. Nothing else changes (no rows, no data, no migration; rolling back to 0.2.3 is safe).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.3.py")
DST = os.path.join(ROOT, "SkyyGear", "build_skyygear_0.2.4.py")
raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.2.3"' in s and s.startswith('"""SkyyGear 0.2.3 - build script'), "build_skyygear_0.2.3.py is not the live 0.2.3"
SYS0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:140])
    s = s.replace(old, new)


HEAD = open(__file__, encoding="utf8").read().split('"""')[1]
rep('"""SkyyGear 0.2.3 - build script (javassist via jpype). NEW mod:',
    '"""SkyyGear 0.2.4 - build script (javassist via jpype). GENERATED by tools/gear_0_2_4_patch.py from the LIVE 0.2.3 - edit the patch,\n'
    'never this file. Run: python SkyyGear/build_skyygear_0.2.4.py -> SkyyGear/SkyyGear-0.2.4.jar (never --deploy).\n\n'
    + HEAD[HEAD.index("0.2.4 = "):].strip() + "\n\n0.2.3 (the base, everything below is still true unless 0.2.4 above says otherwise):\n"
    'SkyyGear 0.2.3 - build script (javassist via jpype). NEW mod:')
rep('VERSION = "0.2.3"', 'VERSION = "0.2.4"')
# ---- GearBase.shots: the traversal line + the quick words + the staff quick bonus
rep('''    String cp = a[6] instanceof String ? (String) a[6] : "";
    String qp = a[7] instanceof String ? (String) a[7] : "";''', '''    String cp = a[6] instanceof String ? (String) a[6] : "";
    String qp = a[7] instanceof String ? (String) a[7] : "";
    // 0.2.4 (SkyyArmory 0.1.1, Magic-Traversal-Spec 3.3): [8] traversal words, [9] quick words, [10] staff quick bonus % (older = 8 elements)
    String tw = (a.length >= 10 && a[8] instanceof String) ? (String) a[8] : "";
    String qw = (a.length >= 10 && a[9] instanceof String) ? (String) a[9] : "";
    double qb = (a.length >= 11 && a[10] instanceof Number) ? ((Number) a[10]).doubleValue() : 0.0;
    if (!(qb > 0.0) || Double.isInfinite(qb)) qb = 0.0;''')
rep('''      double qf = (ton && qp.startsWith("SkyyArmory_")) ? tune / 100.0 * armoryQuickPct() / 20.0 : 1.0;
      qv = shown(prjDamage(qp, qd) * qf * m);
      q = "Quick shot - " + qm + " Mana - " + qv + at;
    }
    return new Object[] { c, q, Long.valueOf(cv), Long.valueOf(qv), Integer.valueOf(cm), Integer.valueOf(qm) };''',
    '''      double qf = (ton && qp.startsWith("SkyyArmory_")) ? tune / 100.0 * armoryQuickPct() / 20.0 * (1.0 + qb / 100.0) : 1.0;
      qv = shown(prjDamage(qp, qd) * qf * m);
      q = "Quick shot - " + qm + " Mana - " + qv + at;
      if (qw.length() > 0) q = q + " - " + qw;
    }
    return new Object[] { c, q, Long.valueOf(cv), Long.valueOf(qv), Integer.valueOf(cm), Integer.valueOf(qm), tw.length() > 0 ? tw : null };''')
rep('''# null = no SkyyArmory answer (SkyyArmory absent, or a wand / staff it does not own) -> the caller shows 0.2.1's lines; else Object[] {
# String charged line, String quick line (null = this tap is a melee swing: SkyyArmory built with the vanilla tap), Long charged damage,
# Long quick damage (-1 = none), Integer charged Mana, Integer quick Mana }''',
    '''# null = no SkyyArmory answer (SkyyArmory absent, or a wand / staff it does not own) -> the caller shows 0.2.1's lines; else Object[] {
# String charged line, String quick line (null = this tap is a melee swing: SkyyArmory built with the vanilla tap), Long charged damage,
# Long quick damage (-1 = none), Integer charged Mana, Integer quick Mana, String traversal line (0.2.4; null = none) }''')
rep('''    if (sh != null) {
      add(txt, col, (String) sh[0], null);
      if (sh[1] != null) add(txt, col, (String) sh[1], null);''', '''    if (sh != null) {
      add(txt, col, (String) sh[0], null);
      if (sh.length > 6 && sh[6] != null) add(txt, col, (String) sh[6], null);     // 0.2.4: the hold's traversal (SkyyArmory 0.1.1)
      if (sh[1] != null) add(txt, col, (String) sh[1], null);''')
assert s.count("registerSystem(") == SYS0 and s.count("registerCommand(") == CMD0, "0.2.4 adds no system / command"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))
