"""Derive SkyyGuilds/build_skyyguilds_0.1.3.py from the LIVE 0.1.2 (build_skyyguilds_0.1.2.py = the tools/deploy_set.py SET pin).
Start of the SkyyGuilds patch chain (0.1.1 and 0.1.2 were copy + edit): edit THIS file, never the generated build script.
Run:  python tools/guilds_0_1_3_patch.py   then   python SkyyGuilds/build_skyyguilds_0.1.3.py   (no --deploy: coordinated deploy)
0.1.3 = research/Classes-Berserker-Priest-Spec.md follow-up F1 (pairs with SkyySkills 0.4.4 / SkyyClasses 0.1.6):
 - xpSkills DEFAULT gains Fury (Berserker, SkyySkills slot 14) and Divinity (Priest, slot 15), appended after Exploration.
 - KNOWN NAMES (GHooks.SK_NAMES = the xpSkills check=): fury / berserker / combat.berserker = 14, divinity / priest / combat.priest = 15,
   so Server Setup > Guilds > Skills that count stops asking "not a SkyySkills skill name ... Save anyway?" for them.
 - MIGRATION at start (GCfg.migrateSkills inside GCfg.load, before the kit starts): ONLY an xpSkills value that is still exactly the
   0.1 - 0.1.2 default gets the new default (that one value text changes, the rest of the file byte for byte, atomic, verified);
   the new default is left alone silently; a customised list is kept, with one INFO line per start (it names what the list lacks, or
   says it already has Fury and Divinity).
 - ONE COUNT PER SKILL (review fix): GCfg.parseSkills (start, reload, hand edit) keeps the first name of each SkyySkills slot and drops
   a later name of the same slot (Fury + Berserker) or the same name again (any case), with one WARN - checkSkills only guards the
   in-game / command / import paths, so a hand-edited "Fury,Berserker" counted that XP twice. The slot table (SKILL_NAMES) moved up to
   the GCfg fields so GCfg and GHooks share it (GCfg is compiled first).
 - CONFIG KIT 1.1: picked up by the rebuild (tools/skyycfg.py); the build asserts kit >= 1.1.
Nothing else: rows, commands, page, bridge keys, files and Settings switches stay 0.1.2's.
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyGuilds", "build_skyyguilds_0.1.2.py")
dst = os.path.join(ROOT, "SkyyGuilds", "build_skyyguilds_0.1.3.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
REG0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")
OLD = "Mining,Foraging,Farming,Acrobatics,Archery,Swordsmanship,Assassination,Shaman,Sorcery,Alchemy,Smithing,Cooking,Exploration"


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:100])
    s = s.replace(old, new, 1)


# ---------------------------------------------------------------- docstring + version
rep('''"""SkyyGuilds 0.1.2 - build script (javassist via jpype). Derived from the LIVE 0.1.1 (build_skyyguilds_0.1.1.py, the
tools/deploy_set.py SET pin) by copy + edit (SkyyGuilds has no tools/ patch script).
Run:   python build_skyyguilds_0.1.2.py          -> SkyyGuilds/SkyyGuilds-0.1.2.jar
       (no --deploy in this script on purpose: tools/deploy_set.py installs the whole set once Skyy says deploy)
''', '''"""SkyyGuilds 0.1.3 - build script (javassist via jpype). GENERATED by tools/guilds_0_1_3_patch.py from the LIVE 0.1.2
(build_skyyguilds_0.1.2.py, the tools/deploy_set.py SET pin) - edit the patch, never this file (0.1.2 and 0.1.1 were copy + edit).
Run:   python build_skyyguilds_0.1.3.py          -> SkyyGuilds/SkyyGuilds-0.1.3.jar
       (no --deploy in this script on purpose: tools/deploy_set.py installs the whole set once Skyy says deploy)

0.1.3 (2026-09-25; research/Classes-Berserker-Priest-Spec.md follow-up F1 - pairs with SkyySkills 0.4.4 + SkyyClasses 0.1.6):
  XP SKILLS: Fury (Berserker, SkyySkills 0.4.4 slot 14) and Divinity (Priest, slot 15) are APPENDED to the default xpSkills list
    (Mining,Foraging,Farming,Acrobatics,Archery,Swordsmanship,Assassination,Shaman,Sorcery,Alchemy,Smithing,Cooking,Exploration,Fury,
    Divinity): a fresh config.properties, the kit row's default (Server Setup "default" / /guildadmin set xpSkills default), and a
    missing or empty xpSkills line (start and reload). With a SkyySkills older than 0.4.4 the two names answer 0 XP (nothing breaks).
  KNOWN NAMES (GHooks.SK_NAMES / SK_SLOTS, the xpSkills check=): fury / berserker / combat.berserker (slot 14) and divinity / priest /
    combat.priest (slot 15) = what SkyySkills 0.4.4's skill:fn:xp answers exactly. Server Setup > Guilds > Skills that count no longer
    asks "... is not a SkyySkills skill name ... Save anyway?" for them; Fury + Berserker in one list is refused as the same skill (like
    Archery + Archer); /guildadmin set xpSkills gives no "adds 0 guild XP" note for them.
  MIGRATION (GCfg.migrateSkills, called in GCfg.load at setup = BEFORE the config kit starts, after the 0.1.1 key appends; the SkyySkills
    0.4.4 DivCfg pattern): ONLY when the file's xpSkills value (trimmed) is still exactly the old default (GCfg.OLD_SKILLS - the same text
    in 0.1, 0.1.1 and 0.1.2) is that value replaced by the new default. Only the value text changes: key, separator, trailing white
    space, CRLF / LF and every other line stay byte for byte (read + written as ISO-8859-1 = byte exact; continuation and comment lines
    are skipped). Checked before writing: the new text parsed as Properties has the same keys and values except xpSkills = the new
    default - else nothing is written, one WARN, and the old list keeps running (file and game agree). Written atomically (tmp + fsync +
    ATOMIC_MOVE, 5 x 20 ms retries). One INFO line: "xpSkills was still the old default - added Fury and Divinity ...".
    The NEW default (exactly DEF_SKILLS, e.g. after this migration) is left alone with no line. A CUSTOMISED list (anything else: other
    names, order or case, Fury already added) is never touched, and one INFO line per start says it was kept: when it names no Fury
    and / or Divinity skill the line says which and how to add them; when it already names both, the line says so ("... already counts
    Fury and Divinity - kept as it is ... Nothing to update.") so it cannot be read as a failed update.
    Start only: a later hand edit or in-game change back to the old list is kept. Not in config-changes.log / config-history (the kit
    has not started yet - the same as the 0.1.1 key appends); the server log line is the record. The XP baseline lives in memory, so
    the first check after this start records it with the new list (no one-off credit for Fury / Divinity XP earned before the update).
  ONE COUNT PER SKILL (review fix, GCfg.parseSkills = start, /guildadmin reload, the page's Reload, a hand edit found at a save):
    XpTask.total() adds skill:fn:xp for every name in GCfg.SKILLS, and GHooks.checkSkills (which refuses "Fury,Berserker" or "Mining,
    mining") only runs for in-game / command / import values - the kit does not run check= on a hand-edited scalar line. So a hand-edited
    "xpSkills=Fury,Berserker,Mining" counted a Berserker's Fury XP twice (0.1.2 had the same gap for Archery + Archer). The parse now
    keeps the FIRST name of each known SkyySkills slot (GCfg.skillSlot = the same SKILL_NAMES table as GHooks.slotOf) and the first of
    a name listed again in any case (an unknown name too); a dropped name gives one WARN per parse ("xpSkills names the same skill more
    than once (Berserker = Fury) - it counts once ..."). The file keeps its text (the kit owns every write); saving the list in game
    fixes it (checkSkills refuses the duplicate there). Names SkyySkills only matches by prefix (3+ letters, e.g. "Min") are not in the
    table and are not collapsed - checkSkills already asks "Save anyway?" for them (0.1.2 behaviour, unchanged).
  CONFIG KIT 1.1 (tools/skyycfg.py KIT_VERSION, CfgRows.KIT; tools/CONFIG-CONTRACT.md): picked up by this rebuild. SkyyGuilds has no
    table, custom or value-action rows, so it gains only the kit's shared internals (the reload op merges under the save monitor, reload
    routines wait for a save that is writing, a lone reload request runs); the schema (14 rows, 3 categories), file, log, history,
    export and bridge formats are unchanged. The build asserts kit >= 1.1.
  Nothing else: rows, commands, the page, bridge keys, data files and the Settings switches are 0.1.2's.
  CHECKED 0.1.3 in a bare JVM (2026-09-25, scratch harness under tools/dev/scratch/r7-skyyguilds, deleted afterwards; 113 checks, 0
    fails): all 48 classes (41 + 7 kit) load under -Xverify:all, CfgRows.KIT = "1.1"; a missing file is seeded with the new list; the
    live 0.1.2 default text (LF) gets only the xpSkills value changed (INFO line, no tmp left, a second load changes nothing); CRLF +
    "xpSkills = <old>  " + a commented old line + a UTF-8 comment: byte exact except the value; customised lists (other names, the old
    list + Fury, Priest only, the old list in lower case, Berserker + Combat.Priest, the new list) are untouched and run as written,
    with the "does not list Fury and Divinity / Divinity / Fury" line or no line; an empty or missing line = the new list, file
    untouched; a 0.1 file gets the 0.1.1 keys AND the new list; two xpSkills lines (custom then old: only the old one changes; old then
    custom: untouched); the old list written across two lines: WARN, untouched, old list runs; a read-only file: WARN, untouched, old
    list runs, no tmp left; checkSkills passes the new / old / Fury / Divinity / Berserker / Priest / Combat.* lists, refuses Fury +
    Berserker and Priest + Divinity as the same skill and still asks for an unknown name; kit: config:def 14 rows, version 0.1.3, row
    default = the new list, get, status ok, a console set of Mining,Fury,Divinity answers ok with no question, writes its line and runs
    reloadSkills, an unknown name answers confirm "Save anyway?", reset to default, export. A copy of the live world's config.properties
    (LF, 1880 bytes, xpSkills = the old default) migrates to the new list with only that value changed.
  RE-CHECKED after the review fixes (2026-09-25, same scratch folder, deleted afterwards; 95 checks, 0 fails): all 48 classes load under
    -Xverify:all; GCfg.skillSlot = GHooks.slotOf for all 29 names; parseSkills: Fury,Berserker,Mining -> Fury,Mining (WARN "Berserker =
    Fury"), Divinity,Combat.Priest -> Divinity, Archery,Archer -> Archery, Mining,mining and Foo,foo -> once ("twice"), Shaman + Shaman
    Skill + Combat.Shaman -> Shaman, the new / old / empty / missing list and Priest,Fury -> as written with no WARN; XpTask.total with a
    fake per-slot skill:fn:xp counts each slot once; reloadSkills from a hand-edited file drops the duplicate and leaves the file as
    typed; load(): the old default still migrates (no tmp left) and a second load logs nothing, the new default logs nothing, a
    customised list with both new names logs one "already counts Fury and Divinity - kept as it is" INFO line, a list lacking one / both
    logs the "does not list" line only, a missing or empty line logs nothing; checkSkills answers are unchanged.
  UNVERIFIED 0.1.3 (needs the game): the INFO line in the real server log at the first 0.1.3 start, Server Setup > Guilds > Skills that
    count showing the new list, saving Fury / Divinity lists there without the question, and guild XP from a real Berserker / Priest.
''')
rep('''  (Mining, Foraging, Farming, Acrobatics, Archery, Swordsmanship, Assassination, Shaman, Sorcery, Alchemy, Smithing, Cooking,
  Exploration - "Combat" is left out on purpose''', '''  (Mining, Foraging, Farming, Acrobatics, Archery, Swordsmanship, Assassination, Shaman, Sorcery, Alchemy, Smithing, Cooking,
  Exploration, 0.1.3: Fury, Divinity - "Combat" is left out on purpose''')
rep('import skyycfg as CFG\n\nVERSION = "0.1.2"\n',
    'import skyycfg as CFG\n'
    '# 0.1.3: built on config kit 1.1 or newer (tools/CONFIG-CONTRACT.md "Kit versions")\n'
    'assert tuple(int(x) for x in getattr(CFG, "KIT_VERSION", "1.0").split(".")) >= (1, 1), "SkyyGuilds 0.1.3 needs config kit 1.1+"\n'
    '\nVERSION = "0.1.3"\n')

# ---------------------------------------------------------------- the default list + GCfg fields
rep('SKILLS = "%s"\n' % OLD,
    '# 0.1.3: Fury (Berserker) and Divinity (Priest) = SkyySkills 0.4.4 slots 14 / 15, appended. OLD_SKILLS = the 0.1 - 0.1.2 default, the\n'
    '# only xpSkills value GCfg.migrateSkills rewrites at start. NEW_SKILL_NAMES: every name SkyySkills 0.4.4 answers for the two (checked\n'
    '# against SKILL_NAMES below), used for the "your list lacks Fury / Divinity" log line.\n'
    'OLD_SKILLS = "%s"\n'
    'SKILLS = OLD_SKILLS + ",Fury,Divinity"\n'
    'NEW_SKILL_NAMES = [("Fury", ("fury", "berserker", "combat.berserker"), 14), ("Divinity", ("divinity", "priest", "combat.priest"), 15)]\n'
    '# The names SkyySkills 0.4.4 answers in skill:fn:xp (SkillDefs.indexOf: NAMES, LABELS and class names, any case) and the storage slot\n'
    '# each one reads - two names on one slot would count the same XP twice. Kept here as data (the kit never calls another mod); a name\n'
    '# that is not listed only ASKS first (a future SkyySkills skill still works), it is never refused. 0.1.3: moved up from the GHooks\n'
    '# section so GCfg (compiled first) has its own copy - GCfg.parseSkills counts each slot once (review fix); GHooks.slotOf reads the same list.\n'
    'SKILL_NAMES = [("mining", 0), ("foraging", 1), ("farming", 2), ("acrobatics", 4),\n'
    '               ("archery", 5), ("archer", 5), ("combat.archer", 5), ("swordsmanship", 6), ("warrior", 6), ("combat.warrior", 6),\n'
    '               ("assassination", 7), ("assassin", 7), ("combat.assassin", 7), ("shaman", 8), ("shaman skill", 8), ("combat.shaman", 8),\n'
    '               ("sorcery", 9), ("mage", 9), ("combat.mage", 9), ("alchemy", 10), ("smithing", 11), ("cooking", 12), ("exploration", 13),\n'
    '               # 0.1.3: SkyySkills 0.4.4 Berserker / Priest (label, class name, saved key)\n'
    '               ("fury", 14), ("berserker", 14), ("combat.berserker", 14), ("divinity", 15), ("priest", 15), ("combat.priest", 15)]\n'
    'for _n, _al, _sl in NEW_SKILL_NAMES:\n'
    '    assert sorted(_al) == sorted(n for n, s_ in SKILL_NAMES if s_ == _sl), "NEW_SKILL_NAMES %%s != SKILL_NAMES slot %%d" %% (_n, _sl)\n'
    '    assert _n.lower() in _al\n'
    'assert len(set(n for n, _ in SKILL_NAMES)) == len(SKILL_NAMES)\n'
    'for _s in SKILLS.split(","):\n'
    '    assert _s.lower() in [n for n, _ in SKILL_NAMES], "default xpSkills name %%s is not in SKILL_NAMES" %% _s\n'
    'F(cfg, "public static final String[] SK_NAMES = new String[] { %%s };" %% ", ".join(\'"%%s"\' %% n for n, _ in SKILL_NAMES))\n'
    'F(cfg, "public static final int[] SK_SLOTS = new int[] { %%s };" %% ", ".join(str(s) for _, s in SKILL_NAMES))\n'
    % OLD)
rep('''          'public static final String DEF_SKILLS = "%s";' % SKILLS):
    F(cfg, f)''', '''          'public static final String DEF_SKILLS = "%s";' % SKILLS,
          # 0.1.3: the old default (the only value the start-up migration replaces) + the names of the two new skills
          'public static final String OLD_SKILLS = "%s";' % OLD_SKILLS,
          "public static final String[] NEW_SKILLS = new String[] { %s };" % ", ".join('"%s"' % n for n, _, _ in NEW_SKILL_NAMES),
          "public static final String[] NEW_ALIASES = new String[] { %s };" % ", ".join('",%s,"' % ",".join(a) for _, a, _ in NEW_SKILL_NAMES)):
    F(cfg, f)''')

# ---------------------------------------------------------------- GCfg.parseSkills: each SkyySkills skill counts once (review fix)
# XpTask.total() sums skill:fn:xp over GCfg.SKILLS; checkSkills refuses two names of one slot only on the in-game / command / import
# paths, so a hand-edited "Fury,Berserker" (or "Mining,mining") counted that XP twice. Keep the first name of each known slot and the
# first of a name listed again in any case; one WARN names what was dropped. skillSlot = GHooks.slotOf over the same SKILL_NAMES table.
rep('''M(cfg, r"""
public static void parseSkills(java.util.Properties p) {
  String sk = p.getProperty("xpSkills");
  if (sk == null || sk.trim().length() == 0) sk = DEF_SKILLS;
  String[] a = sk.split(",");
  java.util.ArrayList l = new java.util.ArrayList();
  for (int i = 0; i < a.length; i++) {
    String x = a[i].trim();
    if (x.length() > 0 && !x.equalsIgnoreCase("combat")) l.add(x);
  }
  String[] r = new String[l.size()];
  for (int i = 0; i < r.length; i++) r[i] = (String) l.get(i);
  SKILLS = r;
}""")
''', '''# 0.1.3 (review fix): the SkyySkills storage slot of a lower-case name (SKILL_NAMES), -1 = not a known name
M(cfg, r"""
public static int skillSlot(String lower) {
  for (int i = 0; i < SK_NAMES.length; i++) if (SK_NAMES[i].equals(lower)) return SK_SLOTS[i];
  return -1;
}""")
# 0.1.3 (review fix): each skill counts ONCE - the first name of a known slot wins (Fury,Berserker -> Fury), a name listed again in any
# case is dropped (an unknown name too); one WARN per parse names what was dropped. The file keeps its text (the kit owns every write).
M(cfg, r"""
public static void parseSkills(java.util.Properties p) {
  String sk = p.getProperty("xpSkills");
  if (sk == null || sk.trim().length() == 0) sk = DEF_SKILLS;
  String[] a = sk.split(",");
  java.util.ArrayList l = new java.util.ArrayList();
  java.util.HashSet names = new java.util.HashSet();
  java.util.HashMap slots = new java.util.HashMap();
  StringBuilder dup = new StringBuilder();
  for (int i = 0; i < a.length; i++) {
    String x = a[i].trim();
    if (x.length() == 0 || x.equalsIgnoreCase("combat")) continue;
    String lx = x.toLowerCase();
    int s = skillSlot(lx);
    Object first = s >= 0 ? slots.get(Integer.valueOf(s)) : null;
    if (first != null || names.contains(lx)) {
      if (dup.length() > 0) dup.append(", ");
      if (first != null && !((String) first).equalsIgnoreCase(x)) dup.append(x).append(" = ").append((String) first);
      else dup.append(x).append(" twice");
      continue;
    }
    names.add(lx);
    if (s >= 0) slots.put(Integer.valueOf(s), x);
    l.add(x);
  }
  String[] r = new String[l.size()];
  for (int i = 0; i < r.length; i++) r[i] = (String) l.get(i);
  SKILLS = r;
  if (dup.length() > 0) {
    String d = dup.length() > 300 ? dup.substring(0, 300) + "..." : dup.toString();
    @PKG@.GuildStore.warn("config.properties: xpSkills names the same skill more than once (" + d + ") - it counts once. Save the list once per skill in Server Setup > Guilds > Skills that count (or /guildadmin set xpSkills <list>) to remove this warning.");
  }
}""")
''')

# ---------------------------------------------------------------- GCfg.migrateSkills (+ helpers), compiled before load()
MIGRATE = r'''# ---- 0.1.3: the xpSkills migration (setup only, inside load(), BEFORE the config kit starts - the kit owns every write after that).
# Only an xpSkills value that is still exactly OLD_SKILLS gets DEF_SKILLS; only that value text changes (see the 0.1.3 header block).
M(cfg, r"""
public static boolean isWs(char c) {
  return c == ' ' || c == '\t' || c == 12;
}""")
# where the value of a live xpSkills line starts (Properties syntax: white space, the key, then white space and / or one = or :);
# -1 = not an xpSkills line. body = the line without its CR.
M(cfg, r"""
public static int skillsValueAt(String body) {
  int n = body.length();
  int i = 0;
  while (i < n && isWs(body.charAt(i))) i++;
  if (!body.startsWith("xpSkills", i)) return -1;
  i = i + 8;
  int j = i;
  while (j < n && isWs(body.charAt(j))) j++;
  if (j < n && (body.charAt(j) == '=' || body.charAt(j) == ':')) {
    j++;
    while (j < n && isWs(body.charAt(j))) j++;
  } else if (j == i && j < n) return -1;
  return j;
}""")
# a logical line that continues on the next one (an odd number of trailing backslashes)
M(cfg, r"""
public static boolean contLine(String body) {
  int k = 0;
  int i = body.length() - 1;
  while (i >= 0 && body.charAt(i) == '\\') { k++; i--; }
  return k % 2 == 1;
}""")
M(cfg, r"""
public static boolean commentOrBlank(String body) {
  int n = body.length();
  int i = 0;
  while (i < n && isWs(body.charAt(i))) i++;
  return i >= n || body.charAt(i) == '#' || body.charAt(i) == '!';
}""")
# the new default skills (Fury, Divinity) a list names by none of their SkyySkills 0.4.4 names ("" = both listed)
M(cfg, r"""
public static String missingNew(String list) {
  String[] a = list == null ? new String[0] : list.split(",");
  String miss = "";
  for (int k = 0; k < NEW_SKILLS.length; k++) {
    boolean found = false;
    for (int i = 0; i < a.length && !found; i++) {
      String x = a[i].trim().toLowerCase();
      if (x.length() > 0 && NEW_ALIASES[k].indexOf("," + x + ",") >= 0) found = true;
    }
    if (!found) miss = miss.length() == 0 ? NEW_SKILLS[k] : miss + " and " + NEW_SKILLS[k];
  }
  return miss;
}""")
# the rewritten text must parse to the same keys and values, except xpSkills = the new default
M(cfg, r"""
public static boolean sameExceptSkills(java.util.Properties a, java.util.Properties b) {
  if (a.size() != b.size()) return false;
  String bv = b.getProperty("xpSkills");
  if (bv == null || !bv.trim().equals(DEF_SKILLS)) return false;
  java.util.Iterator it = a.stringPropertyNames().iterator();
  while (it.hasNext()) {
    String k = (String) it.next();
    if (k.equals("xpSkills")) continue;
    String y = b.getProperty(k);
    if (y == null || !y.equals(a.getProperty(k))) return false;
  }
  return true;
}""")
# tmp + fsync + atomic rename, 5 x 20 ms retries on a Windows FileSystemException (the GuildStore.replaceFile pattern; GuildStore's own
# helper is compiled after GCfg, so this is its own copy)
M(cfg, r"""
public static void writeAtomic(byte[] b) throws java.io.IOException {
  java.nio.file.Path tmp = FILE.resolveSibling(FILE.getFileName().toString() + ".migrate.tmp");
  java.io.FileOutputStream out = new java.io.FileOutputStream(tmp.toFile());
  try {
    out.write(b);
    out.flush();
    out.getFD().sync();
  } finally { out.close(); }
  java.io.IOException last = null;
  for (int i = 0; i < 5; i++) {
    try {
      try {
        java.nio.file.Files.move(tmp, FILE, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.REPLACE_EXISTING, java.nio.file.StandardCopyOption.ATOMIC_MOVE });
      } catch (java.nio.file.AtomicMoveNotSupportedException a) {
        java.nio.file.Files.move(tmp, FILE, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.REPLACE_EXISTING });
      }
      return;
    } catch (java.nio.file.NoSuchFileException e) {
      throw e;
    } catch (java.nio.file.FileSystemException e) {
      last = e;
    }
    try { Thread.sleep(20L); } catch (InterruptedException ie) { }
  }
  try { java.nio.file.Files.deleteIfExists(tmp); } catch (Throwable t) { }
  throw last;
}""")
# p = the properties load() parses: set to the new default only after the file says so (a failed rewrite keeps the old list running,
# so the file, the page and the running list always agree)
M(cfg, r"""
public static void migrateSkills(java.util.Properties p) {
  String cur = p.getProperty("xpSkills");
  if (cur == null || cur.trim().length() == 0) return;
  String t = cur.trim();
  if (t.equals(DEF_SKILLS)) return;
  if (!t.equals(OLD_SKILLS)) {
    String miss = missingNew(t);
    String shown = t.length() > 300 ? t.substring(0, 300) + "..." : t;
    if (miss.length() > 0) @PKG@.GuildStore.info("config.properties: xpSkills is a changed list, kept as it is (" + shown + "). It does not list " + miss + ", so that Berserker / Priest skill XP adds no guild XP - add it in Server Setup > Guilds > Skills that count, or /guildadmin set xpSkills <list>.");
    else @PKG@.GuildStore.info("config.properties: xpSkills is a changed list that already counts Fury and Divinity - kept as it is (" + shown + "). Nothing to update.");
    return;
  }
  String keep = " (the old list is kept - add Fury,Divinity in Server Setup > Guilds > Skills that count)";
  try {
    byte[] old = java.nio.file.Files.readAllBytes(FILE);
    java.util.Properties before = new java.util.Properties();
    before.load(new java.io.ByteArrayInputStream(old));
    String bv = before.getProperty("xpSkills");
    if (bv == null || !bv.trim().equals(OLD_SKILLS)) { @PKG@.GuildStore.warn("config.properties changed while it was read - xpSkills not updated" + keep); return; }
    String text = new String(old, "ISO-8859-1");
    String[] lines = text.split("\n", -1);
    StringBuilder out = new StringBuilder(text.length() + 32);
    int changed = 0;
    boolean cont = false;
    for (int i = 0; i < lines.length; i++) {
      String l = lines[i];
      String body = l.endsWith("\r") ? l.substring(0, l.length() - 1) : l;
      if (cont) cont = contLine(body);
      else if (!commentOrBlank(body)) {
        int at = skillsValueAt(body);
        if (at >= 0 && body.startsWith(OLD_SKILLS, at) && body.substring(at + OLD_SKILLS.length()).trim().length() == 0) {
          l = l.substring(0, at) + DEF_SKILLS + l.substring(at + OLD_SKILLS.length());
          changed++;
        }
        cont = contLine(body);
      }
      if (i > 0) out.append('\n');
      out.append(l);
    }
    if (changed == 0) { @PKG@.GuildStore.warn("config.properties: xpSkills is the old default but its line could not be rewritten safely" + keep); return; }
    byte[] nb = out.toString().getBytes("ISO-8859-1");
    java.util.Properties after = new java.util.Properties();
    after.load(new java.io.ByteArrayInputStream(nb));
    if (!sameExceptSkills(before, after)) { @PKG@.GuildStore.warn("config.properties: rewriting xpSkills would change more than that line - nothing written" + keep); return; }
    writeAtomic(nb);
    p.setProperty("xpSkills", DEF_SKILLS);
    @PKG@.GuildStore.info("config.properties: xpSkills was still the old default - added Fury and Divinity (Berserker / Priest skill XP now counts for guild XP). A list an admin changed is never touched.");
  } catch (Throwable x) { @PKG@.GuildStore.warn("could not add Fury and Divinity to xpSkills in " + FILE + keep + ": " + x); }
}""")
'''
rep('# setup only (before the kit starts): seed a missing file, append missing 0.1.1 keys, parse\n',
    MIGRATE + '# setup only (before the kit starts): seed a missing file, append missing 0.1.1 keys, 0.1.3: migrate an untouched xpSkills, parse\n')
rep('''      } catch (Throwable t) { @PKG@.GuildStore.warn("could not add the 0.1.1 key(s) " + names.substring(2) + " to " + FILE + " (defaults used): " + t); }
    }
    parse(p);
''', '''      } catch (Throwable t) { @PKG@.GuildStore.warn("could not add the 0.1.1 key(s) " + names.substring(2) + " to " + FILE + " (defaults used): " + t); }
    }
    migrateSkills(p);
    parse(p);
''')

# ---------------------------------------------------------------- GHooks: SKILL_NAMES now lives with the GCfg fields (see above)
rep('''# The names SkyySkills 0.4.2 answers in skill:fn:xp (SkillDefs.indexOf: NAMES, LABELS and class names, any case) and the storage slot
# each one reads - two names on one slot would count the same XP twice. Kept here as data (the kit never calls another mod); a name
# that is not listed only ASKS first (a future SkyySkills skill still works), it is never refused.
SKILL_NAMES = [("mining", 0), ("foraging", 1), ("farming", 2), ("acrobatics", 4),
               ("archery", 5), ("archer", 5), ("combat.archer", 5), ("swordsmanship", 6), ("warrior", 6), ("combat.warrior", 6),
               ("assassination", 7), ("assassin", 7), ("combat.assassin", 7), ("shaman", 8), ("shaman skill", 8), ("combat.shaman", 8),
               ("sorcery", 9), ("mage", 9), ("combat.mage", 9), ("alchemy", 10), ("smithing", 11), ("cooking", 12), ("exploration", 13)]
for _s in SKILLS.split(","):
    assert _s.lower() in [n for n, _ in SKILL_NAMES], "default xpSkills name %s is not in SKILL_NAMES" % _s
F(hk,''', '''# SKILL_NAMES (the names SkyySkills 0.4.4 answers in skill:fn:xp and the storage slot each one reads; 0.1.3 adds Fury / Berserker /
# Combat.Berserker = 14 and Divinity / Priest / Combat.Priest = 15) is defined with the GCfg fields since 0.1.3, so GCfg.parseSkills and
# GHooks.slotOf / checkSkills read the same table. A name that is not listed only ASKS first, it is never refused.
F(hk,''')

# ---------------------------------------------------------------- checks on the result
assert s.count('"0.1.2"') == 0, "a 0.1.2 version string is left"
assert s.count("registerSystem(") == REG0 and s.count("registerCommand(") == CMD0      # no new system, no new command
assert s.count("migrateSkills(p);") == 1
# review fix: one SKILL_NAMES table, defined before GCfg's fields; GCfg.skillSlot compiled before parseSkills, which uses it
assert s.count("\nSKILL_NAMES = [") == 1 and s.index("\nSKILL_NAMES = [") < s.index('for f in ("public static java.nio.file.Path FILE;"')
assert s.index("public static int skillSlot(String lower) {") < s.index("public static void parseSkills(java.util.Properties p) {") \
    < s.index("public static void parse(java.util.Properties p) {")
assert "int s = skillSlot(lx);" in s and s.count("xpSkills names the same skill more than once") == 1
assert s.count('already counts Fury and Divinity - kept as it is (" + shown + ")') == 1
assert s.count("  if (t.equals(DEF_SKILLS)) return;\n  if (!t.equals(OLD_SKILLS)) {") == 1
assert s.index("public static void info(String msg) {") < s.index("public static void migrateSkills(java.util.Properties p) {")
assert s.index("public static boolean isWs(char c) {") < s.index("public static int skillsValueAt(String body) {") \
    < s.index("public static boolean contLine(String body) {") < s.index("public static boolean commentOrBlank(String body) {") \
    < s.index("public static String missingNew(String list) {") < s.index("public static boolean sameExceptSkills(") \
    < s.index("public static void writeAtomic(byte[] b)") < s.index("public static void migrateSkills(java.util.Properties p) {") \
    < s.index("public static void load() {")
_ld = s[s.index("public static void load() {"):]
_ld = _ld[:_ld.index('}""".replace(')]
assert _ld.index("names.substring(2)") < _ld.index("migrateSkills(p);") < _ld.index("parse(p);")
# config publication stays the LAST statement of setup(), after GCfg.load()
_su = s[s.index("public void setup() {"):]
_su = _su[:_su.index('}""")')]
assert _su.rstrip().endswith("@PKG@.CfgPub.start(getDataDirectory().getParent(), getLogger());")
assert _su.index("@PKG@.GCfg.load();") < _su.index("CfgPub.start(")
assert "B.deploy(" not in s and "enable_in_world(" not in s
import re
for ident in re.findall(r"#(Skyy[A-Za-z0-9_]*)", s):
    assert "_" not in ident, "UI id with an underscore: " + ident

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(line endings %s)" % ("CRLF" if NL == CR + LF else "LF"))
