"""Derive SkyyGuilds/build_skyyguilds_0.1.5.py from the LIVE 0.1.4 (build_skyyguilds_0.1.4.py = the tools/deploy_set.py SET pin).
Run:  python tools/guilds_0_1_5_patch.py   then   python SkyyGuilds/build_skyyguilds_0.1.5.py   (never --deploy: coordinated deploy)
SkyyGuilds is patch-based since 0.1.3: edit THIS file, never the generated build script. Harness: SkyyGuilds/test_skyyguilds_0.1.5.py.

0.1.5 = Skyy's two guild bank decisions (OPEN-QUESTIONS.md, LOCKED 2026-10-01):
  1. DISBAND PAYS THE BANK BACK BY PERCENTAGE (/guild disband, the last member leaving, and /guildadmin delete - the same disbandNow):
     each member still in the guild gets the share of the WHOLE bank equal to their share of the positive net contributions of the
     current members (net = deposits - withdrawals); members with a zero / negative net get nothing; nobody positive = an even split.
     Whole coins (rounded down), the remainder to the biggest contributor (highest net; tie: higher rank, earlier join), the shares
     sum to the bank exactly. Offline members are paid through coins:fn:add like everyone else: SkyyCoins writes the player's ACTIVE
     profile purse (pkey -> SkyyProfiles' profile:fn:key, read from disk for an offline player; tools/PROFILES-CONTRACT.md). The bank
     log has no profile column and guilds are per player, so "the profile that made the deposits" cannot be known - the active profile
     is the only purse the bridge can name, and it is the purse withdrawals already pay. Safety kept + extended: every payee's purse is
     read first (unreadable = refused, nothing changed), the guild file is written as disbanded with bank 0 BEFORE any coin moves, a
     failed payout takes back every share paid so far (coins:fn:take) and writes the live file again (refused); a share that cannot be
     taken back stays with that member as a logged disband-payout (the bank keeps the rest - no coin created or lost). Was: everything
     to the Leader.
  2. THE MEMBER LIST SHOWS EACH MEMBER'S CONTRIBUTION (net = deposits - withdrawals, negative in the kit's error red, else the row's
     value colour), sorted by rank (Leader, Admins, Members), then contribution (highest first), then online, then name.
     The guild file log keeps only the newest bankLogKeep (200) moves, so the totals are NEW per-player running totals
     (Guild.net: uuid -> {deposited, withdrawn}, file keys net.<uuid>=dep|wd, kept for players who leave so a rejoin keeps them),
     updated on every deposit / withdraw (with the bank, before the file write), seeded ONCE per guild (file key netSeed) at the first
     0.1.5 start from banklog.log (every move since 0.1) + the guild file log, de-duplicated, matched to current members by name.
     The seed says how complete it is ("complete" = the history adds up to today's bank exactly).
  3. THE 0.1.5 REVIEW (APPROVE; findings 1, 2, 4, 5 applied, the rest are notes for Skyy - see the generated docstring, part 3):
     the payout plan goes to the server log + banklog.log (DISBAND-PAYOUT-START / PAID / DONE / CANCELLED) before the first coin
     moves, so a crash mid-payout can be repaid by hand; the rollback save is tried 3 times, then a loud WARN; leave confirms name a
     positive contribution that stays in the bank (a positive Member's /guild leave asks once); /guildadmin info shows the seed status.
"""
import collections
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyGuilds", "build_skyyguilds_0.1.4.py")
dst = os.path.join(ROOT, "SkyyGuilds", "build_skyyguilds_0.1.5.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1.4"' in s and "GENERATED by tools/guilds_0_1_4_patch.py" in s, "build_skyyguilds_0.1.4.py is not the live 0.1.4"
REG0 = s.count("registerCommand(")
SYS0 = s.count("registerSystem(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
assert len(BIND0) == 27, "0.1.4 has 27 event binding lines (all in GuildPage), found %d" % len(BIND0)


def rep(old, new, n=1):
    global s
    c = s.count(old)
    assert c == n, "anchor count %d (want %d): %s" % (c, n, old[:160])
    s = s.replace(old, new)


def block(a, b):
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


# blocks that must come out of this patch byte-identical to 0.1.4 (XpTask, DayTask, GuildTick, GuildOnlineFn, GHooks, the page logic,
# the config kit, the commands but /guildadmin delete's description)
KEEP = [block("# ================= XpTask (the member's own world thread)", "# ================= GuildPage (0.1.3 logic"),
        block('M(page, r"""\npublic void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {', "# ================= commands ================="),
        block("# ================= 0.1.2: the admin config kit", "M(gs, r\"\"\"\npublic static @UNI@ uni() {"),
        block('cmd("GHelpCmd", "help"', 'cmd("GADeleteCmd", "delete"'),
        block('cmd("GASeasonNextCmd", "next"', "# ================= plugin =================")]

# ================================================================================================ docstring
HEAD_OLD = '''"""SkyyGuilds 0.1.4 - build script (javassist via jpype). GENERATED by tools/guilds_0_1_4_patch.py from the LIVE 0.1.3
(build_skyyguilds_0.1.3.py, the tools/deploy_set.py SET pin) - edit the patch, never this file.
Run:   python build_skyyguilds_0.1.4.py          -> SkyyGuilds/SkyyGuilds-0.1.4.jar
       (no --deploy in this script on purpose: tools/deploy_set.py installs the whole set once Skyy says deploy)
'''
HEAD_NEW = '''"""SkyyGuilds 0.1.5 - build script (javassist via jpype). GENERATED by tools/guilds_0_1_5_patch.py from the LIVE 0.1.4
(build_skyyguilds_0.1.4.py, the tools/deploy_set.py SET pin) - edit the patch, never this file.
Run:   python build_skyyguilds_0.1.5.py          -> SkyyGuilds/SkyyGuilds-0.1.5.jar
       (no --deploy in this script on purpose: tools/deploy_set.py installs the whole set once Skyy says deploy)

0.1.5 (2026-10-01, Skyy's guild bank decisions - OPEN-QUESTIONS.md LOCKED 2026-10-01):
  1. DISBAND PAYS THE BANK BACK BY CONTRIBUTION (GuildStore.payouts + disbandNow; /guild disband, the last member's /guild leave and
     /guildadmin delete all end in disbandNow). Every member still in the guild gets the share of the WHOLE bank equal to their share
     of the positive nets of the current members (net = deposited - withdrawn, Guild.net below): share = bank x net / total (exact,
     BigInteger, rounded down to whole coins). A zero or negative net gets nothing. Nobody positive = the bank split evenly between
     the members. The coins the rounding leaves (fewer than the members sharing) go to the biggest contributor (highest net; a tie:
     the higher rank, then the earlier join), so the shares add up to the bank exactly. Example: nets 600 / 400, bank 1,000 -> 600 /
     400; nets 3 / 3 / 3, bank 10 -> the Leader 4, the others 3 each; nets 500 / -200, bank 300 -> 300 / 0.
     OFFLINE MEMBERS are paid through coins:fn:add too: SkyyCoins resolves the purse with pkey (SkyyProfiles' profile:fn:key, read from
     players/<uuid>.properties for an offline player - tools/PROFILES-CONTRACT.md "offline") and writes that ACTIVE profile's balance
     file. Guilds are per player and the bank log has no profile column, so "the profile that made the deposits" cannot be told apart;
     the active profile is the only purse the bridge can name and the one guild withdrawals already pay (an offline player's active
     profile cannot change until they log in). Offline members get no chat line (the bank log in the archived file lists each share).
     SAFETY: (a) every payee's purse must be readable first (coins:fn:get; unreadable = refused, nothing changed); (b) the guild file is
     rewritten as disbanded with bank 0 BEFORE any coin moves (0.1.4's rule: a failed write = refused, nothing changed; a crash can
     never pay the bank twice); (c) the shares are paid one by one; if ANY payout fails, every share paid so far is taken back
     (coins:fn:take) and the live guild file is written again - the disband is refused and the bank keeps every coin. A share that
     cannot be taken back (that purse became unreadable or was spent in the same moment) stays with that member: the bank is lowered
     by it, it is logged as their disband-payout and counted as their withdrawal - no coin is created or lost; (d) the file then moves
     to guilds/deleted/ (0.1.4). Texts: when ONE member gets the whole bank (always the case for the last member leaving) every chat /
     result line is 0.1.4's ("... coins to your purse" / "went to <name>'s purse"); otherwise the confirm lines say "pays the bank's N
     coins back to the members by contribution (your share: X)" and the result "went back to K members by contribution". Was: the
     whole bank to the Leader (0.1 - 0.1.4).
  2. MEMBER LIST: a Contribution column (net = deposited - withdrawn, e.g. 75,000 or -3,000; negative in the kit's error red #ff6b6b,
     else the row value colour #b7cedd; past +-999,999,999,999,999 the short form 1000000.00b) between Rank and Guild XP added.
     Sorted by rank (Leader, Admins, Members), then contribution (highest first), then online, then name (0.1.4: rank, online, name).
     /guildadmin info lists each member's contribution too.
     RUNNING TOTALS (why: the guild file log keeps only the newest bankLogKeep moves, default 200 - not full history): Guild.net = player
     uuid -> long[]{deposited, withdrawn}, file keys net.<uuid>=deposited|withdrawn. deposit adds with the bank (before the file write);
     withdraw adds with the lowered bank (before the first write) and takes it back with the bank when the write or SkyyCoins fails.
     A player's totals stay in the file when they leave or are kicked (a rejoin keeps them, as a full bank log would); only current
     members show and share. SEED (once per guild, GuildStore.seedNet in loadAll, before the files are saved): a guild file without
     netSeed (= every file from 0.1 - 0.1.4) is seeded from banklog.log (every bank move since 0.1, one line per move) united with the
     guild file's own log (the newest bankLogKeep), the same move counted once; deposits add to "deposited", withdrawals and
     disband-payouts to "withdrawn"; a mover is matched to a CURRENT member by name (the log has names, not uuids; any case). The info
     line and netSeed=<millis>|complete|partial|<moves>|<unmatched moves> say how complete it is: "complete" = deposits - withdrawals of
     every move found equals today's bank exactly (the history explains every coin); "partial" = moves are missing (banklog.log edited /
     deleted / unreadable); moves of players no longer in the guild are counted but credited to nobody (a returning player starts from
     0.1.5's totals). A guild created by 0.1.5 starts with netSeed=<millis>|new|0|0 (never seeded). Rollback to 0.1.4 is safe: 0.1.4
     ignores net.* / netSeed (and drops them at its next save); a later 0.1.5 then seeds again from the history.
     LOOK: the window is 1400 px wide (0.1.4: 1200) in all three views so the Contribution column (190 px: "-999,999,999,999,999"
     fits) comes on top of 0.1.4's columns; Status 72 -> 82 px; every other width is computed from GUILD_W as in 0.1.4 (the log view's
     Bank after column, the summary row's bank line, the footer gaps grow). Kit only (tools/skyyui.py 1.4), the same proven properties
     as 0.1.4 (no FlexWeight / LayoutMode Right / button b.set needed). Everything else on the page is 0.1.4's: ids (+ #SkyyGRowNet<i>),
     the 27 event bindings, EventData, b.set lines (+ the new cell), handleDataEvent.
  3. REVIEW HARDENING (the 0.1.5 review, 2026-10-01: APPROVE, no coin creation; findings 1, 2, 4, 5 applied):
     (finding 1) a crash or kill DURING the payouts used to lose the unpaid shares with no record (the file already says bank 0; the
     disband-payout lines came only after every payout). Now, before the first coins:fn:add, one server-log info line ("disband of
     <id> '<name>' by <who>: ... paying the bank's N coins to K member(s) in this order: <name> <uuid> <share>, ...") and one banklog.log
     line "DISBAND-PAYOUT-START" with the same list; every share that lands gets "DISBAND-PAYOUT-PAID i/K: <name> <uuid> <share> coins.";
     the end is "DISBAND-PAYOUT-DONE" or, on a rollback, "DISBAND-PAYOUT-CANCELLED" (naming any share that stayed with its member).
     A START without DONE / CANCELLED = the server stopped mid-payout: an admin pays the shares without a PAID line by hand (the one
     right after the last PAID line may have landed just before the stop - check that purse). No automatic replay (it could pay twice).
     These lines have no " player=" and never end in "bank=<n>", so parseBankLine (the 0.1.1 backfill, the 0.1.5 seed) skips them.
     (finding 2) the rollback rewrite of the live guild file (after a failed payout) is tried 3 times; if all fail, a loud WARN "DISBAND
     ROLLBACK NOT ON DISK: guild <id> '<name>' holds N bank coins in memory, but guilds/<id>.properties still says DISBANDED with
     bank 0 ..." tells an admin what to fix by hand; the guild stays dirty (flushDirty retries every 5 s; the write order is 0.1.4's).
     (finding 4) every leave confirm of a member who is NOT the last one ends with "Your guild bank contribution (N coins) stays in
     the bank for the other members - withdraw first if you want coins back." when their contribution is positive (the withdraw hint
     only when their rank may withdraw: a Member under the default limit 0 gets just the first sentence); a Member's /guild leave
     (no confirm since 0.1) asks once first in that case (repeat within 10 s); a zero / negative contribution = 0.1.4's texts and an
     immediate /guild leave; the last member gets the whole bank, so their texts are unchanged. (finding 5) /guildadmin info's bank
     line shows how complete the contributions are: "(contributions seeded <instant> from N bank move(s) of its history: COMPLETE |
     PARTIAL ..., M move(s) by players no longer in the guild (or renamed since) credited to nobody)", "(contributions counted from
     every move since the guild was made <instant>)" or "(contributions not seeded yet)".
     NOT CHANGED (review notes, for Skyy): (3) with "orphan" coins in the bank (left there by members who left or were kicked), a
     member who deposits just before a disband gets a share of the orphans too - Skyy's locked rule (current members only) allows
     it; a refund-on-leave rule would close it; guild bank interest / rewards would make it larger. (6) contributions are per player,
     not per profile (since 0.1.1). (7) each payee costs one SkyyCoins read + write (+ now one banklog.log append) under the guild
     lock on the clicking player's world thread: tens of ms at 25 members, seconds if maxMembers is raised to 500. (8) a rollback
     take hits the member's CURRENT active profile. (9) SkyyCoins keeps a balance in memory when its file write fails (all callers).
     (10) the confirm's "(your share: X)" is the share when it was armed; the result line states the real one. (11) two members with
     the same stored name get one combined seed.
@@CHECKED@@
  NOT IN THIS VERSION: the "?" back on the armed Kick / Make leader buttons (probe page 20 passed; a look follow-up), a chat line for
    offline members about their disband share (they see the coins in their purse; the archived guild file lists every share).
  UNVERIFIED (needs the game): the 1400 px window (client draw; the same kit blocks as 0.1.4), real SkyyCoins + SkyyProfiles paying an
    offline member's active profile on a live server (the harness runs the real SkyyCoins 0.1.5 classes with a stand-in profile:fn:key).
'''
CHECKED = '''  CHECKED with SkyyGuilds/test_skyyguilds_0.1.5.py - re-run it before a deploy (python SkyyGuilds/test_skyyguilds_0.1.5.py; the harness is
    the source of truth, not this text): @@RESULT@@'''
RESULT = """2026-10-01 (after the review fixes), kit skyyui 1.4 ac93356c4c60,
    page 26645a3ab908: @@COUNT@@ ok, 0 fail. The in-game ready line reads "0.1.5 ready (skyyui 1.4 ac93356c4c60, page 26645a3ab908)".
    One JVM (-Xverify:all; 0.1.4, 0.1.5 and the real SkyyCoins 0.1.5 each in its own class loader): A 48 + 48 + 11 classes load,
    verify and initialise. B 40 classes byte-identical to 0.1.4 (XpTask too); GCfg / CfgFn / CfgRows / manifest = 0.1.4 but the
    version; SkyyGuildsPlugin = 0.1.4 but the ready constant (version + page id); GADeleteCmd = 0.1.4 but its description; Guild +
    net / netSeed (only <init> changed); GuildStore 15 methods changed, 15 new, 102 instruction-identical; GuildPage: only buildNone /
    buildGuild / buildLog changed. C XpTask gives the same guild XP on both jars. P 411 splits (60/40, 75,000 / -3,000, one negative,
    nobody positive, rank / join tie-breaks, 1e15, 400 random) = the Python reference, every sum exact. Q end to end: 3,000 -> 900 /
    600 / 1,500 / 0 with an offline member and a negative one, even split 284 / 283 / 283, admin delete, the last member (= 0.1.4),
    refused on an unreadable purse with nothing changed, payout failures on the 1st / 2nd / 3rd payee fully rolled back (live file,
    bank, log, totals, purses), a share that could not be taken back logged as a disband-payout; coins conserved every time. R real
    SkyyCoins: the offline member's active profile (p2) paid, profile 1 untouched; an unreadable balance file = refused, every file
    byte-identical. S running totals; a scratch COPY of the live GodSquad data seeded once (SkyLordPlayz 2,200 in / 1,100 out,
    WesleyPlayz 200 / 200 = the bank 1,100: complete), start twice = seeded once, later moves kept, 0.1.4 reads the file and 0.1.5
    seeds again after 0.1.4 dropped the keys, a 3-line log without banklog.log keeps the totals, a partial history is reported;
    /guildadmin info shows the seed status (4 cases). V review fixes: the plan in the server log + banklog.log before the first coin
    (a snapshot at the 2nd payout holds it + 1 PAID line), PAID / DONE / CANCELLED lines never read as moves; a blocked rollback save
    tried 3 times, the loud WARN, memory right + dirty, flushDirty repairs; leave confirms with the contribution note (Member / Admin /
    Leader, /guild leave asks a positive Member first), zero / negative = 0.1.4. D 31 states x 2 jars identical but the new cell; 11 new
    states: Leader | Admins | Members, each by contribution (-5,000 | 75,000, 0 | 500, 0, 0, -3,000), negatives #ff6b6b, the rest
    #b7cedd, the widest leave notes. E 134 clicks identical on both jars but the one leave note, each jar's rows in its own documented
    order. F 745 texts fit. G the page id is the checked one."""
HARNESS_OK = 80103          # SkyyGuilds/test_skyyguilds_0.1.5.py "N ok, 0 fail" on the build this patch writes
HEAD_NEW = HEAD_NEW.replace("@@CHECKED@@", CHECKED.replace("@@RESULT@@", RESULT.replace("@@COUNT@@", str(HARNESS_OK))))
rep(HEAD_OLD, HEAD_NEW)

# ================================================================================================ version + kit messages
rep('\nVERSION = "0.1.4"\n', '\nVERSION = "0.1.5"\n')
rep('("SkyyGuilds 0.1.4 needs the vanilla UI kit 1.4+ (static blocks, "', '("SkyyGuilds 0.1.5 needs the vanilla UI kit 1.4+ (static blocks, "')

# ================================================================================================ Guild: running bank totals
rep('''          "public boolean legacy;", "public java.util.HashMap wdKeep;"):
    F(gld, f)''', '''          "public boolean legacy;", "public java.util.HashMap wdKeep;",
          # 0.1.5: net = player uuid -> long[]{deposited, withdrawn} (running bank totals, kept for players who left; file net.<uuid>);
          # netSeed = "<millis>|complete|partial|new|<moves>|<unmatched>" once the totals were seeded (file netSeed; null = seed at load)
          "public java.util.HashMap net;", "public String netSeed;"):
    F(gld, f)''')
rep('''  this.wdKeep = new java.util.HashMap();
}""")''', '''  this.wdKeep = new java.util.HashMap();
  this.net = new java.util.HashMap();
  this.netSeed = null;
}""")''')

# ================================================================================================ propsOf / loadGuildFile: net.* + netSeed
rep('''    p.setProperty("wdk." + k, v);
  }
  java.util.Iterator si = g.season.keySet().iterator();''', '''    p.setProperty("wdk." + k, v);
  }
  java.util.Iterator ni = g.net.keySet().iterator();
  while (ni.hasNext()) {
    String k = (String) ni.next();
    long[] nv = (long[]) g.net.get(k);
    if (nv == null || (nv[0] == 0L && nv[1] == 0L)) continue;
    p.setProperty("net." + k, nv[0] + "|" + nv[1]);
  }
  if (g.netSeed != null) p.setProperty("netSeed", g.netSeed);
  java.util.Iterator si = g.season.keySet().iterator();''')
rep('''    g.limMember = @PKG@.GCfg.limProp(p, "limitMember", @PKG@.GCfg.DEF_LIM_MEMBER);
    java.util.ArrayList mems = new java.util.ArrayList();''', '''    g.limMember = @PKG@.GCfg.limProp(p, "limitMember", @PKG@.GCfg.DEF_LIM_MEMBER);
    String seedV = p.getProperty("netSeed");
    g.netSeed = (seedV == null || seedV.trim().length() == 0) ? null : seedV.trim();
    java.util.ArrayList mems = new java.util.ArrayList();''')
rep('''      if (k.startsWith("wdk.")) { g.wdKeep.put(k.substring(4).trim(), p.getProperty(k).trim()); continue; }
      if (!k.startsWith("wd.")) continue;''', '''      if (k.startsWith("wdk.")) { g.wdKeep.put(k.substring(4).trim(), p.getProperty(k).trim()); continue; }
      if (k.startsWith("net.")) {
        String nu = k.substring(4).trim();
        String[] nv = p.getProperty(k).split("\\\\|", 2);
        if (nu.length() > 0 && nv.length == 2) g.net.put(nu, new long[] { Math.max(0L, parseLong(nv[0], 0L)), Math.max(0L, parseLong(nv[1], 0L)) });
        continue;
      }
      if (!k.startsWith("wd.")) continue;''')

# ================================================================================================ running totals + the seed (before loadAll)
NET_METHODS = r'''# 0.1.5: a player's running bank totals in a guild, long[]{deposited, withdrawn} (null = no move yet). Every caller holds the lock.
M(gs, r"""
public static synchronized long[] netOf(@PKG@.Guild g, String us) {
  if (g == null || us == null || g.net == null) return null;
  Object o = g.net.get(us);
  if (o == null) return null;
  return (long[]) o;
}""")
M(gs, r"""
public static synchronized void netAdd(@PKG@.Guild g, String us, long dep, long wd) {
  if (g == null || us == null) return;
  long[] v = netOf(g, us);
  if (v == null) { v = new long[] { 0L, 0L }; g.net.put(us, v); }
  v[0] = v[0] + dep;
  v[1] = v[1] + wd;
}""")
# net contribution = deposited - withdrawn (0 = no moves)
M(gs, r"""
public static synchronized long netValue(@PKG@.Guild g, String us) {
  long[] v = netOf(g, us);
  return v == null ? 0L : v[0] - v[1];
}""")
# the member list cell: exact with commas, the short form past +-999,999,999,999,999 (the column fits the exact form up to there)
M(gs, r"""
public static String netText(long v) {
  if (v > -1000000000000000L && v < 1000000000000000L) return num(v);
  return fmt(v);
}""")
# 0.1.5 seed: one history move "millis|who|action|amount|bankAfter" into byName (lower-case name -> long[]{deposited, withdrawn,
# moves}); returns its bank change (+ deposit, - withdraw / disband-payout, 0 = not a coin move: limit changes)
M(gs, r"""
public static long seedLine(java.util.HashMap byName, String line) {
  if (line == null) return 0L;
  String[] v = line.split("\\|", 5);
  if (v.length < 5) return 0L;
  long amt = parseLong(v[3], -1L);
  if (amt <= 0L) return 0L;
  boolean dep = v[2].equals("deposit");
  boolean out = v[2].equals("withdraw") || v[2].equals("disband-payout");
  if (!dep && !out) return 0L;
  String k = v[1].trim().toLowerCase();
  Object o = byName.get(k);
  long[] t = null;
  if (o != null) t = (long[]) o;
  if (t == null) { t = new long[] { 0L, 0L, 0L }; byName.put(k, t); }
  if (dep) t[0] = t[0] + amt; else t[1] = t[1] + amt;
  t[2] = t[2] + 1L;
  return dep ? amt : -amt;
}""")
# banklog.log as lines for the seed: empty = no file, null = unreadable (the guild file logs are used alone)
M(gs, r"""
public static java.util.List readBankLines() {
  java.nio.file.Path f = DIR.resolve("banklog.log");
  if (!java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) return new java.util.ArrayList();
  try { return java.nio.file.Files.readAllLines(f, java.nio.charset.StandardCharsets.UTF_8); }
  catch (Throwable t) { warn("could not read banklog.log for the 0.1.5 contribution seed (each guild file's own log is used): " + t); return null; }
}""")
# 0.1.5: seed g.net ONCE from the history: banklog.log (bank = its lines, null = unreadable) united with the guild file log (the same move
# is the same line - parseBankLine makes the guild file form), each move counted once; movers matched to CURRENT members by name.
# Sets g.netSeed and g.dirty; returns the info line (how complete the seed is).
M(gs, r"""
public static synchronized String seedNet(@PKG@.Guild g, java.util.List bank) {
  java.util.LinkedHashSet lines = new java.util.LinkedHashSet();
  int fromBank = 0;
  if (bank != null) {
    for (int i = 0; i < bank.size(); i++) {
      String e = parseBankLine((String) bank.get(i), g.id);
      if (e != null && lines.add(e)) fromBank++;
    }
  }
  int fromFile = 0;
  for (int i = 0; i < g.log.size(); i++) if (lines.add((String) g.log.get(i))) fromFile++;
  java.util.HashMap byName = new java.util.HashMap();
  long sum = 0L;
  long moves = 0L;
  java.util.Iterator it = lines.iterator();
  while (it.hasNext()) {
    long d = seedLine(byName, (String) it.next());
    if (d != 0L) moves++;
    sum = sum + d;
  }
  g.net.clear();
  int credited = 0;
  java.util.Iterator mi = g.members.values().iterator();
  while (mi.hasNext()) {
    @PKG@.GMember m = (@PKG@.GMember) mi.next();
    if (m.name == null) continue;
    Object o = byName.remove(m.name.trim().toLowerCase());
    if (o == null) continue;
    long[] t = (long[]) o;
    g.net.put(m.uuid, new long[] { t[0], t[1] });
    credited++;
  }
  long unmatched = 0L;
  java.util.Iterator ui = byName.values().iterator();
  while (ui.hasNext()) unmatched = unmatched + ((long[]) ui.next())[2];
  boolean complete = sum == g.bank;
  g.netSeed = System.currentTimeMillis() + "|" + (complete ? "complete" : "partial") + "|" + moves + "|" + unmatched;
  g.dirty = true;
  return "0.1.5 bank contributions of guild " + g.id + " '" + g.name + "' seeded once from its history ("
    + (bank == null ? "banklog.log unreadable" : fromBank + " banklog.log move(s)") + " + " + fromFile + " more from the guild file log): "
    + moves + " deposit(s) / withdrawal(s), " + credited + " member(s) credited; "
    + (complete ? "COMPLETE - the history adds up to today's bank (" + g.bank + " coins)"
                : "PARTIAL - the history adds up to " + sum + " coins but the bank holds " + g.bank + " (moves are missing), so the contributions count only the moves found")
    + (unmatched > 0L ? "; " + unmatched + " move(s) by players no longer in the guild are credited to nobody" : "") + ".";
}""")
# 0.1.5 review (finding 5): how complete the contributions are, for the /guildadmin info bank line (netSeed above; the first-start info
# line is gone once the server log rolls). "complete" only says the history added up to the bank; moves of players who left (or of a
# member who was renamed since) are credited to nobody, so their count is shown too.
M(gs, r"""
public static String seedText(@PKG@.Guild g) {
  String s = g.netSeed;
  if (s == null) return "contributions not seeded yet";
  String[] v = s.split("\\|");
  if (v.length < 4) return "contributions seed " + s;
  String when = "?";
  try { when = java.time.Instant.ofEpochMilli(Long.parseLong(v[0])).toString(); } catch (Throwable t) { }
  if (v[1].equals("new")) return "contributions counted from every move since the guild was made " + when;
  long un = parseLong(v[3], 0L);
  return "contributions seeded " + when + " from " + v[2] + " bank move(s) of its history: "
    + (v[1].equals("complete") ? "COMPLETE (the history added up to the bank)" : "PARTIAL (moves were missing; only the moves found count)")
    + (un > 0L ? ", " + un + " move(s) by players no longer in the guild (or renamed since) credited to nobody" : "");
}""")
'''
rep('''M(gs, r"""
public static synchronized void loadAll() {''', NET_METHODS + '''M(gs, r"""
public static synchronized void loadAll() {''')
# the seed runs in loadAll after the 0.1.1 log backfill (a 0.1 file's log is rebuilt first) and before the dirty files are saved
rep('''  saveMeta();
  saveIndex();
  java.util.Iterator gi = GUILDS.values().iterator();
  while (gi.hasNext()) {
    @PKG@.Guild g = (@PKG@.Guild) gi.next();
    if (g.dirty) saveGuild(g);
    publishGuild(g);
  }''', '''  java.util.List bankAll = null;
  boolean readBank = false;
  java.util.Iterator si = GUILDS.values().iterator();
  while (si.hasNext()) {
    @PKG@.Guild g = (@PKG@.Guild) si.next();
    if (g.netSeed != null) continue;
    if (!readBank) { bankAll = readBankLines(); readBank = true; }
    info(seedNet(g, bankAll));
  }
  saveMeta();
  saveIndex();
  java.util.Iterator gi = GUILDS.values().iterator();
  while (gi.hasNext()) {
    @PKG@.Guild g = (@PKG@.Guild) gi.next();
    if (g.dirty) saveGuild(g);
    publishGuild(g);
  }''')

# ================================================================================================ create: a new guild is never seeded
rep('''  g.name = name;
  g.created = now;
  @PKG@.GMember m = new @PKG@.GMember();''', '''  g.name = name;
  g.created = now;
  g.netSeed = now + "|new|0|0";
  @PKG@.GMember m = new @PKG@.GMember();''')

# ================================================================================================ the disband split + disbandNow
PAYOUTS = r'''# 0.1.5 (Skyy 2026-10-01, "use %"): how a disband pays amt coins out. Rows Object[]{GMember, Long share, Long net} for EVERY member in
# member (join) order; the shares sum to amt exactly. Members with a positive net (deposited - withdrawn) share the WHOLE bank by their
# part of the positive nets: share = amt x net / total (BigInteger, rounded down); a zero or negative net gets 0. Nobody positive =
# amt / members each. The coins the rounding leaves go to the biggest contributor (highest net; tie: higher rank, then earlier join).
M(gs, r"""
public static synchronized java.util.ArrayList payouts(@PKG@.Guild g, long amt) {
  java.util.ArrayList rows = new java.util.ArrayList();
  java.util.ArrayList mems = new java.util.ArrayList(g.members.values());
  int n = mems.size();
  if (n == 0) return rows;
  long a = amt < 0L ? 0L : amt;
  long[] net = new long[n];
  java.math.BigInteger tot = java.math.BigInteger.ZERO;
  int best = 0;
  for (int i = 0; i < n; i++) {
    @PKG@.GMember m = (@PKG@.GMember) mems.get(i);
    net[i] = netValue(g, m.uuid);
    if (net[i] > 0L) tot = tot.add(java.math.BigInteger.valueOf(net[i]));
    @PKG@.GMember b = (@PKG@.GMember) mems.get(best);
    if (net[i] > net[best] || (net[i] == net[best] && (m.rank > b.rank || (m.rank == b.rank && m.joined < b.joined)))) best = i;
  }
  boolean even = tot.signum() == 0;
  java.math.BigInteger ba = java.math.BigInteger.valueOf(a);
  long[] share = new long[n];
  long given = 0L;
  for (int i = 0; i < n; i++) {
    if (even) share[i] = a / (long) n;
    else if (net[i] > 0L) share[i] = ba.multiply(java.math.BigInteger.valueOf(net[i])).divide(tot).longValue();
    given = given + share[i];
  }
  share[best] = share[best] + (a - given);
  for (int i = 0; i < n; i++) rows.add(new Object[] { mems.get(i), Long.valueOf(share[i]), Long.valueOf(net[i]) });
  return rows;
}""")
# a member's disband share of the bank right now (0 = none / not a member)
M(gs, r"""
public static synchronized long shareOf(@PKG@.Guild g, String us) {
  java.util.ArrayList rows = payouts(g, g.bank);
  for (int i = 0; i < rows.size(); i++) {
    Object[] r = (Object[]) rows.get(i);
    if (((@PKG@.GMember) r[0]).uuid.equals(us)) return ((Long) r[1]).longValue();
  }
  return 0L;
}""")
# how many members get a share (> 0)
M(gs, r"""
public static int payees(java.util.ArrayList rows) {
  int c = 0;
  for (int i = 0; i < rows.size(); i++) if (((Long) ((Object[]) rows.get(i))[1]).longValue() > 0L) c++;
  return c;
}""")
# "Steve 600, Alex 400" for the server log
M(gs, r"""
public static String shareList(java.util.ArrayList rows) {
  StringBuilder sb = new StringBuilder();
  for (int i = 0; i < rows.size(); i++) {
    Object[] r = (Object[]) rows.get(i);
    if (sb.length() > 0) sb.append(", ");
    sb.append(((@PKG@.GMember) r[0]).name).append(' ').append(r[1]).append(" (net ").append(r[2]).append(')');
  }
  return sb.toString();
}""")
# 0.1.5 review (finding 1): a disband payout's own lines in banklog.log, "<ISO instant> guild=<id> (<name>) DISBAND-PAYOUT-... <text>".
# They have no " player=" and never end in "bank=<n>", so parseBankLine (the 0.1.1 backfill + the 0.1.5 seed) skips them: not moves.
M(gs, r"""
public static synchronized void bankNote(@PKG@.Guild g, String text) {
  try {
    java.nio.file.Files.createDirectories(DIR, new java.nio.file.attribute.FileAttribute[0]);
    String line = java.time.Instant.now().toString() + " guild=" + g.id + " (" + g.name + ") " + text + System.lineSeparator();
    java.nio.file.Files.write(DIR.resolve("banklog.log"), line.getBytes("UTF-8"), new java.nio.file.OpenOption[] { java.nio.file.StandardOpenOption.CREATE, java.nio.file.StandardOpenOption.APPEND });
  } catch (Throwable t) { warn("could not write banklog.log: " + t); }
}""")
'''
OLD_DISBAND = block('''# Disband: (1) the guild file is rewritten as disbanded with bank 0 BEFORE any coin moves (a failed write refuses the disband, nothing
# changed), (2) the bank is paid to payTo (the Leader)''', '''M(gs, r"""
public static synchronized String leaveWarning(java.util.UUID u) {''')
NEW_DISBAND = PAYOUTS + r'''# Disband (0.1.5: the bank goes back to the members by contribution, payouts): (1) every payee's purse must be readable (coins:fn:get)
# - else refused, nothing changed; (2) the guild file is rewritten as disbanded with bank 0 BEFORE any coin moves (a failed write
# refuses the disband, nothing changed); (3) each share is paid with coins:fn:add (offline members too: SkyyCoins pays the player's
# active profile); if ANY payout fails, every share paid so far is taken back with coins:fn:take and the live file is written again
# (refused, the bank keeps its coins) - a share that cannot be taken back stays with that member, leaves the bank as a logged
# disband-payout and counts as their withdrawal (no coin created or lost); (4) the file moves to guilds/deleted/. The file on disk never
# shows more coins than exist, so a crash can never pay the same bank twice.
# 0.1.5 review: (finding 1) a crash or kill DURING the payouts loses the unpaid shares (the file already says bank 0), so the plan is
# recorded before the first coin moves - one server-log info line + one banklog.log DISBAND-PAYOUT-START line with every payee's name,
# uuid and share - and each share gets a DISBAND-PAYOUT-PAID line as it lands, then DISBAND-PAYOUT-DONE / -CANCELLED: an admin can pay
# the missing shares by hand (no automatic replay: that could pay twice). (finding 2) the rollback rewrite of the live file is tried
# 3 times; if all fail a loud WARN names the guild and its bank (memory is right, the disk still says disbanded / bank 0; the guild
# stays dirty, so flushDirty keeps retrying every 5 s).
M(gs, r"""
public static synchronized String disbandNow(@PKG@.Guild g, String actorU, String by) {
  long amt = g.bank;
  java.util.ArrayList rows = payouts(g, amt);
  if (amt > 0L && rows.size() == 0) return "-The guild bank still holds " + amt + " coins and the guild has no members to pay them to, so " + g.name + " was NOT disbanded.";
  if (amt > 0L && !coinsReady()) return "-The guild bank still holds " + amt + " coins and SkyyCoins is not available to pay them out, so " + g.name + " was NOT disbanded.";
  if (amt > 0L) {
    for (int i = 0; i < rows.size(); i++) {
      Object[] r = (Object[]) rows.get(i);
      @PKG@.GMember m = (@PKG@.GMember) r[0];
      if (((Long) r[1]).longValue() > 0L && coinsGet(m.uid) == null) return "-" + m.name + "'s purse cannot be read right now, so the guild bank cannot be paid out and " + g.name + " was NOT disbanded (nothing changed). Try again.";
    }
  }
  try {
    java.util.Properties p = propsOf(g);
    p.setProperty("bank", "0");
    p.setProperty("disbanded", String.valueOf(System.currentTimeMillis()));
    writeProps(GDIR.resolve(g.id + ".properties"), p, "SkyyGuilds guild file - DISBANDED (" + amt + " bank coins paid back to the members by contribution), kept for the record only");
  } catch (Throwable t) {
    warn("disband of " + g.id + " refused: the guild file could not be written: " + t);
    return "-The guild file could not be written, so " + g.name + " was NOT disbanded (nothing changed). Try again.";
  }
  int np = payees(rows);
  if (amt > 0L) {
    StringBuilder plan = new StringBuilder();
    for (int i = 0; i < rows.size(); i++) {
      Object[] r = (Object[]) rows.get(i);
      long sh = ((Long) r[1]).longValue();
      if (sh <= 0L) continue;
      @PKG@.GMember m = (@PKG@.GMember) r[0];
      if (plan.length() > 0) plan.append(", ");
      plan.append(m.name).append(' ').append(m.uuid).append(' ').append(sh);
    }
    String pl = plan.toString();
    info("disband of " + g.id + " '" + g.name + "' by " + by + ": the guild file now says disbanded with bank 0; paying the bank's " + amt + " coins to " + np + " member(s) in this order: " + pl + ". If no '" + g.name + " (" + g.id + ") disbanded by' line follows, the server stopped during the payout: banklog.log marks each share PAID as it lands - pay the others by hand.");
    bankNote(g, "DISBAND-PAYOUT-START by " + by + ": bank " + amt + " coins to " + np + " member(s) in this order: " + pl + ". The guild file already says disbanded with bank 0. Each share gets a DISBAND-PAYOUT-PAID line once it is in the purse. No DISBAND-PAYOUT-DONE or DISBAND-PAYOUT-CANCELLED line after this one = the server stopped mid-payout: pay the shares without a PAID line by hand (check the first one's purse, it may have landed just before the stop).");
  }
  boolean[] paid = new boolean[rows.size()];
  String failName = null;
  int done = 0;
  for (int i = 0; i < rows.size() && amt > 0L; i++) {
    Object[] r = (Object[]) rows.get(i);
    long sh = ((Long) r[1]).longValue();
    if (sh <= 0L) continue;
    @PKG@.GMember m = (@PKG@.GMember) r[0];
    if (!coinsAdd(m.uid, sh)) { failName = m.name; break; }
    paid[i] = true;
    done = done + 1;
    bankNote(g, "DISBAND-PAYOUT-PAID " + done + "/" + np + ": " + m.name + " " + m.uuid + " " + sh + " coins.");
  }
  if (failName != null) {
    long kept = 0L;
    java.util.ArrayList stuck = new java.util.ArrayList();
    for (int i = 0; i < rows.size(); i++) {
      if (!paid[i]) continue;
      Object[] r = (Object[]) rows.get(i);
      @PKG@.GMember m = (@PKG@.GMember) r[0];
      long sh = ((Long) r[1]).longValue();
      Object back = coinsTake(m.uid, sh);
      if (back instanceof Boolean && ((Boolean) back).booleanValue()) continue;
      kept = kept + sh;
      stuck.add(r);
    }
    g.bank = amt;
    for (int i = 0; i < stuck.size(); i++) {
      Object[] r = (Object[]) stuck.get(i);
      @PKG@.GMember m = (@PKG@.GMember) r[0];
      long sh = ((Long) r[1]).longValue();
      g.bank = g.bank - sh;
      netAdd(g, m.uuid, 0L, sh);
      addLog(g, m.name, "disband-payout", sh);
    }
    g.dirty = true;
    boolean saved = false;
    for (int tries = 0; tries < 3 && !saved; tries++) saved = saveGuild(g);
    if (!saved) warn("DISBAND ROLLBACK NOT ON DISK: guild " + g.id + " '" + g.name + "' holds " + g.bank + " bank coins in memory, but guilds/" + g.id + ".properties still says DISBANDED with bank 0 after 3 tries. It is retried every 5 s; if the server stops before a save works, edit that file while the server is stopped: bank=" + g.bank + " and delete its disbanded line.");
    warn("disband of " + g.id + " refused: SkyyCoins could not pay " + failName + "'s share - the shares paid before were taken back"
         + (kept > 0L ? " except " + kept + " coins (" + shareList(stuck) + ") that stay with those members and left the bank as disband-payout" : "") + "; bank now " + g.bank);
    bankNote(g, "DISBAND-PAYOUT-CANCELLED: SkyyCoins could not pay " + failName + "'s share, so every share paid before was taken back"
         + (kept > 0L ? " except " + kept + " coins (" + shareList(stuck) + ") that stay with those members, logged above as disband-payout" : "") + "; the guild is NOT disbanded and keeps " + g.bank + " coins.");
    if (kept > 0L) return "-SkyyCoins could not pay " + failName + "'s share, so " + g.name + " was NOT disbanded. " + kept + " coins already paid could not be taken back - see the bank log. Try again.";
    return "-SkyyCoins could not pay " + failName + "'s share of the guild bank, so " + g.name + " was NOT disbanded - every coin paid so far went back to the guild bank. Try again.";
  }
  long left = amt;
  String single = null;
  for (int i = 0; i < rows.size(); i++) {
    if (!paid[i]) continue;
    Object[] r = (Object[]) rows.get(i);
    @PKG@.GMember m = (@PKG@.GMember) r[0];
    long sh = ((Long) r[1]).longValue();
    left = left - sh;
    g.bank = left;
    netAdd(g, m.uuid, 0L, sh);
    addLog(g, m.name, "disband-payout", sh);
    if (sh == amt) single = m.uuid;
  }
  if (amt > 0L) bankNote(g, "DISBAND-PAYOUT-DONE: all " + np + " share(s) paid, " + amt + " coins; the guild is disbanded.");
  g.bank = 0L;
  archive(g);
  GUILDS.remove(g.id);
  if (g.id.equals(BYNAME.get(g.name.toLowerCase()))) BYNAME.remove(g.name.toLowerCase());
  java.util.HashMap shareBy = new java.util.HashMap();
  for (int i = 0; i < rows.size(); i++) {
    Object[] r = (Object[]) rows.get(i);
    shareBy.put(((@PKG@.GMember) r[0]).uuid, r[1]);
  }
  java.util.Iterator it = g.members.values().iterator();
  while (it.hasNext()) {
    @PKG@.GMember m = (@PKG@.GMember) it.next();
    BYPLAYER.remove(m.uuid);
    unpublish(m.uuid);
    if (actorU == null || !actorU.equals(m.uuid)) {
      Object so = shareBy.get(m.uuid);
      long sh = so instanceof Long ? ((Long) so).longValue() : 0L;
      sayU(m.uid, "[Guild] " + g.name + " was disbanded by " + by + "." + (sh > 0L ? " Your share of the guild bank, " + sh + " coins, is in your purse." : ""), "#ffd070");
    }
  }
  java.util.Iterator ii = INVITES.entrySet().iterator();
  while (ii.hasNext()) {
    java.util.Map.Entry e = (java.util.Map.Entry) ii.next();
    Object[] v = (Object[]) e.getValue();
    if (v != null && g.id.equals(v[0])) ii.remove();
  }
  saveIndex();
  info(g.name + " (" + g.id + ") disbanded by " + by + (amt > 0L ? ", bank " + amt + " coins paid back by contribution: " + shareList(rows) : ""));
  if (amt <= 0L) return "+" + g.name + " is disbanded.";
  if (single != null) {
    boolean self = actorU != null && actorU.equals(single);
    String who = self ? "your purse." : g.member(single).name + "'s purse.";
    return "+" + g.name + " is disbanded. The guild bank's " + amt + " coins went to " + who;
  }
  Object mine = actorU == null ? null : shareBy.get(actorU);
  boolean even = true;
  for (int i = 0; i < rows.size(); i++) if (((Long) ((Object[]) rows.get(i))[2]).longValue() > 0L) even = false;
  return "+" + g.name + " is disbanded. The guild bank's " + amt + " coins went back to " + payees(rows) + " members "
    + (even ? "in equal parts (nobody had put in more than they took out)" : "by contribution")
    + (mine instanceof Long ? " - your share: " + mine + " coins." : ".");
}""")
# 0.1.5 review (finding 4): what a member leaves behind - a positive contribution is not paid back, it stays in the bank for the members
# who stay (a disband shares the bank among CURRENT members). " Your guild bank contribution (N coins) stays ..." or "" (net <= 0).
# The withdraw hint only when their rank may withdraw (the limit inlined: limitFor comes later in the class).
M(gs, r"""
public static synchronized String leaveNote(@PKG@.Guild g, @PKG@.GMember me) {
  long n = netValue(g, me.uuid);
  if (n <= 0L) return "";
  long lim = me.rank >= 2 ? -1L : (me.rank == 1 ? g.limAdmin : g.limMember);
  return " Your guild bank contribution (" + num(n) + " coins) stays in the bank for the other members" + (lim != 0L ? " - withdraw first if you want coins back." : ".");
}""")
'''
rep(OLD_DISBAND, NEW_DISBAND)

# ---- the confirm texts: unchanged when the asker would get the whole bank (0.1.4 text), else the split
rep('''  if (g.member(us).rank < 2) return "-Only the Leader can disband the guild.";
  return "=Disbanding deletes " + g.name + " for all " + g.members.size() + " members" + (g.bank > 0L ? " and pays the bank's " + g.bank + " coins to your purse" : "") + ". Click Disband again within 10 s.";''',
    '''  if (g.member(us).rank < 2) return "-Only the Leader can disband the guild.";
  long mine = shareOf(g, us);
  String pay = mine == g.bank ? " and pays the bank's " + g.bank + " coins to your purse" : " and pays the bank's " + g.bank + " coins back to the members by contribution (your share: " + mine + ")";
  return "=Disbanding deletes " + g.name + " for all " + g.members.size() + " members" + (g.bank > 0L ? pay : "") + ". Click Disband again within 10 s.";''')
rep('''  if (!confirmed && !confirm("disband:" + us)) return "=This deletes " + g.name + " for every member" + (g.bank > 0L ? " and pays the guild bank's " + g.bank + " coins into your purse" : "") + ". Type /guild disband again within 10 s to confirm.";
  return disbandNow(g, u, uname, us, uname);''', '''  long mine = shareOf(g, us);
  String pay = mine == g.bank ? " and pays the guild bank's " + g.bank + " coins into your purse" : " and pays the guild bank's " + g.bank + " coins back to the members by contribution (your share: " + mine + ")";
  if (!confirmed && !confirm("disband:" + us)) return "=This deletes " + g.name + " for every member" + (g.bank > 0L ? pay : "") + ". Type /guild disband again within 10 s to confirm.";
  return disbandNow(g, us, uname);''')
# the last member leaving: they are the only member, so the whole bank is theirs (0.1.4's texts stay true)
rep('''    return disbandNow(g, u, uname, us, uname);
  }
  if (me.rank == 2) {''', '''    return disbandNow(g, us, uname);
  }
  if (me.rank == 2) {''')
# ---- 0.1.5 review (finding 4): every leave confirm of a member who is NOT the last one names the positive contribution they leave in the
# bank (leaveNote; "" = 0.1.4's text exactly). The last member gets the whole bank (0.1.4's texts stay true). A Member's /guild leave
# had no confirm (0.1 - 0.1.4: it left at once); with a positive contribution it now asks once (repeat within 10 s), so the
# chat user reads it before the coins stay behind; a zero / negative contribution still leaves at once (the page always confirms).
rep('''  if (me.rank == 2) return "=Leaving makes " + successor(g, us).name + " the new Leader. Click Leave again within 10 s.";
  return "=Click Leave again within 10 s to leave " + g.name + ".";''',
    '''  if (me.rank == 2) return "=Leaving makes " + successor(g, us).name + " the new Leader." + leaveNote(g, me) + " Click Leave again within 10 s.";
  return "=Click Leave again within 10 s to leave " + g.name + "." + leaveNote(g, me);''')
rep('''    if (!confirmed && !confirm("leave:" + us)) return "=You are the Leader: leaving makes " + s.name + " the new Leader. Type /guild leave again within 10 s to confirm.";''',
    '''    if (!confirmed && !confirm("leave:" + us)) return "=You are the Leader: leaving makes " + s.name + " the new Leader." + leaveNote(g, me) + " Type /guild leave again within 10 s to confirm.";''')
rep('''  removeMember(g, us);
  saveGuild(g);
  saveIndex();
  publishGuild(g);
  broadcastK(g, "[Guild] " + uname + " left the guild.", "#cfe3ff", null, "guild.members", null);''',
    '''  String note = leaveNote(g, me);
  if (note.length() > 0 && !confirmed && !confirm("leave:" + us)) return "=" + note.substring(1) + " Type /guild leave again within 10 s to leave " + g.name + ".";
  removeMember(g, us);
  saveGuild(g);
  saveIndex();
  publishGuild(g);
  broadcastK(g, "[Guild] " + uname + " left the guild.", "#cfe3ff", null, "guild.members", null);''')
rep('''  @PKG@.GMember l = g.leader();
  if (!confirm("adel:" + admin + ":" + g.id)) return "=This deletes " + g.name + " (" + g.members.size() + " members" + (g.bank > 0L ? ", its bank's " + g.bank + " coins are paid to its Leader " + (l == null ? "?" : l.name) : "") + "). Type the same command again within 10 s to confirm.";
  return disbandNow(g, l == null ? null : l.uid, l == null ? "?" : l.name, admin.toString(), adminName + " (admin)");''',
    '''  if (!confirm("adel:" + admin + ":" + g.id)) return "=This deletes " + g.name + " (" + g.members.size() + " members" + (g.bank > 0L ? ", its bank's " + g.bank + " coins are paid back to its members by contribution" : "") + "). Type the same command again within 10 s to confirm.";
  return disbandNow(g, admin.toString(), adminName + " (admin)");''')
rep('''    "=/guildadmin info <guild>  -  /guildadmin delete <guild> (repeat to confirm; bank paid to the Leader)",''',
    '''    "=/guildadmin info <guild>  -  /guildadmin delete <guild> (repeat to confirm; bank paid back to the members by contribution)",''')
rep('''cmd("GADeleteCmd", "delete", "Admin: delete a guild (repeat to confirm; bank paid to its Leader)",''',
    '''cmd("GADeleteCmd", "delete", "Admin: delete a guild (repeat to confirm; bank paid back to its members by contribution)",''')
rep('''  out.add("=Level " + li[0] + " (" + li[1] + "/" + li[2] + "), total XP " + g.xp + ", season " + SEASON + " XP " + g.seasonXp(SEASON) + ", bank " + g.bank + " coins");''',
    '''  out.add("=Level " + li[0] + " (" + li[1] + "/" + li[2] + "), total XP " + g.xp + ", season " + SEASON + " XP " + g.seasonXp(SEASON) + ", bank " + g.bank + " coins (" + seedText(g) + ")");''')
rep('''    out.add("=  " + rankName(m.rank) + " " + m.name + (online(m.uid) != null ? " (online)" : "") + " - " + m.contrib + " guild XP added - " + m.uuid);''',
    '''    out.add("=  " + rankName(m.rank) + " " + m.name + (online(m.uid) != null ? " (online)" : "") + " - " + m.contrib + " guild XP added - bank contribution " + num(netValue(g, m.uuid)) + " coins - " + m.uuid);''')

# ================================================================================================ deposit / withdraw keep the totals
rep('''  g.bank = g.bank + n;
  addLog(g, uname, "deposit", n);''', '''  g.bank = g.bank + n;
  netAdd(g, us, n, 0L);
  addLog(g, uname, "deposit", n);''')
rep('''  g.bank = g.bank - n;
  if (day >= 0L) { me.wdDay = day; me.wdUsed = used + n; }
  if (!saveGuild(g)) {
    g.bank = g.bank + n;
    me.wdDay = oldDay;''', '''  g.bank = g.bank - n;
  netAdd(g, us, 0L, n);
  if (day >= 0L) { me.wdDay = day; me.wdUsed = used + n; }
  if (!saveGuild(g)) {
    g.bank = g.bank + n;
    netAdd(g, us, 0L, -n);
    me.wdDay = oldDay;''')
rep('''  if (!coinsAdd(u, n)) {
    g.bank = g.bank + n;
    me.wdDay = oldDay;''', '''  if (!coinsAdd(u, n)) {
    g.bank = g.bank + n;
    netAdd(g, us, 0L, -n);
    me.wdDay = oldDay;''')

# ================================================================================================ member list: data + order
rep('''public static int cmpRow(String[] a, String[] b) {
  int ra = Integer.parseInt(a[2]);
  int rb = Integer.parseInt(b[2]);
  if (ra != rb) return rb - ra;
  if (!a[4].equals(b[4])) return a[4].equals("1") ? -1 : 1;''', '''public static int cmpRow(String[] a, String[] b) {
  int ra = Integer.parseInt(a[2]);
  int rb = Integer.parseInt(b[2]);
  if (ra != rb) return rb - ra;
  long na = a.length > 6 ? parseLong(a[6], 0L) : 0L;
  long nb = b.length > 6 ? parseLong(b[6], 0L) : 0L;
  if (na != nb) return na > nb ? -1 : 1;
  if (!a[4].equals(b[4])) return a[4].equals("1") ? -1 : 1;''')
rep('''# page data: {name, tag, Long xp, Long bank, Integer myRank, rows String[]{uuid, name, rank, contrib, online 1/0, coins taken today},''',
    '''# 0.1.5: rows sort by rank, then bank contribution (highest first), then online, then name (Skyy 2026-10-01)
# page data: {name, tag, Long xp, Long bank, Integer myRank, rows String[]{uuid, name, rank, contrib, online 1/0, coins taken today,
# (0.1.5) bank contribution = deposited - withdrawn},''')
rep('''    rows.add(new String[] { m.uuid, m.name == null ? "?" : m.name, String.valueOf(m.rank), String.valueOf(m.contrib), on ? "1" : "0",
                            String.valueOf(usedToday(m, day)) });''', '''    rows.add(new String[] { m.uuid, m.name == null ? "?" : m.name, String.valueOf(m.rank), String.valueOf(m.contrib), on ? "1" : "0",
                            String.valueOf(usedToday(m, day)), String.valueOf(netValue(g, m.uuid)) });''')

# ================================================================================================ the page: 1400 wide + the Contribution column
rep("# ================= GuildPage (0.1.3 logic; 0.1.4 look = the vanilla UI kit tools/skyyui.py; inline, rebuilt only after a click) =================",
    "# ================= GuildPage (0.1.3 logic; 0.1.4 look = the vanilla UI kit tools/skyyui.py, 0.1.5 + Contribution; inline, rebuilt only after a click) =================")
rep('''GUILD_W = 1200                                   # every view (0.1.3: 1120); the frame adds 38 px of title bar + 2 x 17 px padding''',
    '''GUILD_W = 1400                                   # every view (0.1.3: 1120, 0.1.4: 1200; 0.1.5: + the Contribution column); the frame adds 38 px of title bar + 2 x 17 px padding''')
rep('''GUILD_COLS = [("Member", 326), ("Rank", 86), ("Guild XP added", 150), ("Taken today", 142)]''',
    '''# 0.1.5: + Contribution (190: GUILD_NET_WIDE, the widest exact form, fits; GuildStore.netText switches to the short form past it)
GUILD_COLS = [("Member", 326), ("Rank", 86), ("Contribution", 190), ("Guild XP added", 150), ("Taken today", 142)]''')
rep('''GUILD_BANK_WIDE = "1,000,000,000,000,000 coins"
''', '''GUILD_BANK_WIDE = "1,000,000,000,000,000 coins"
GUILD_NET_WIDE = "-999,999,999,999,999"            # 0.1.5: GuildStore.netText at its widest exact form
GUILD_NET_SHORT = "-9223372036.85b"                # ... and the short form at its widest (GuildStore.fmt(Long.MIN_VALUE + 1))
''')
rep('''    for text, kind, w, what in ((GUILD_NAME_WIDE, "rowName", ws[0], "member name"), (GUILD_NAME_YOU, "rowName", ws[0], "your name"),
                                ("Leader", "bold", ws[1], "rank"), ("Admin", "bold", ws[1], "rank"), ("Member", "bold", ws[1], "rank"),
                                ("9999.99b XP", "default", ws[2], "guild XP added"), (GUILD_TAKEN_WIDE, "default", ws[3], "taken today"),
                                ("online", "default", ws[4], "status"), ("offline", "default", ws[4], "status")):''',
    '''    for text, kind, w, what in ((GUILD_NAME_WIDE, "rowName", ws[0], "member name"), (GUILD_NAME_YOU, "rowName", ws[0], "your name"),
                                ("Leader", "bold", ws[1], "rank"), ("Admin", "bold", ws[1], "rank"), ("Member", "bold", ws[1], "rank"),
                                (GUILD_NET_WIDE, "default", ws[2], "contribution"), (GUILD_NET_SHORT, "default", ws[2], "contribution"),
                                ("9999.99b XP", "default", ws[3], "guild XP added"), (GUILD_TAKEN_WIDE, "default", ws[4], "taken today"),
                                ("online", "default", ws[5], "status"), ("offline", "default", ws[5], "status")):''')
rep('''             SUI.label("SkyyGRowXp" + i, "", "default", w=ws[2], h=GUILD_ROW_H, col="value"),
             SUI.label("SkyyGRowDay" + i, "", "default", w=ws[3], h=GUILD_ROW_H, col=SUI.color_by([("took > 0L", "gold")], "disabled")),
             SUI.label("SkyyGRowOn" + i, "", "default", w=ws[4], h=GUILD_ROW_H, col=SUI.color_by([("on", "success")], "disabled"))]''',
    '''             # 0.1.5: the bank contribution - negative in the kit's error red, else the row value colour (Skyy 2026-10-01)
             SUI.label("SkyyGRowNet" + i, "", "default", w=ws[2], h=GUILD_ROW_H, col=SUI.color_by([("net < 0L", "error")], "value")),
             SUI.label("SkyyGRowXp" + i, "", "default", w=ws[3], h=GUILD_ROW_H, col="value"),
             SUI.label("SkyyGRowDay" + i, "", "default", w=ws[4], h=GUILD_ROW_H, col=SUI.color_by([("took > 0L", "gold")], "disabled")),
             SUI.label("SkyyGRowOn" + i, "", "default", w=ws[5], h=GUILD_ROW_H, col=SUI.color_by([("on", "success")], "disabled"))]''')
rep('''    depends on the viewer's rank (pw), a status bar (green = online), the 5 cells with their 0.1.3 ids"""''',
    '''    depends on the viewer's rank (pw), a status bar (green = online), the 5 cells with their 0.1.3 ids + (0.1.5) #SkyyGRowNet"""''')
rep('''    # the Leader's panel (the narrowest) holds the bar + the 5 cells exactly: read back out of the markup''',
    '''    # the Leader's panel (the narrowest) holds the bar + the 6 cells exactly: read back out of the markup''')
rep('''    long took = @PKG@.GuildStore.parseLong(r[5], 0L);
    String rid = "#SkyyGRow" + idx;''', '''    long took = @PKG@.GuildStore.parseLong(r[5], 0L);
    long net = @PKG@.GuildStore.parseLong(r[6], 0L);
    String rid = "#SkyyGRow" + idx;''')
rep('''    b.set("#SkyyGRowRank" + idx + ".Text", @PKG@.GuildStore.rankName(rr));
''', '''    b.set("#SkyyGRowRank" + idx + ".Text", @PKG@.GuildStore.rankName(rr));
    b.set("#SkyyGRowNet" + idx + ".Text", @PKG@.GuildStore.netText(net));
''')
# the page check lines name 0.1.5's harness + patch
rep('''# the page id (GUILD_PAGE_ID below) that SkyyGuilds/test_skyyguilds_0.1.4.py last passed on (tools/guilds_0_1_4_patch.py''',
    '''# the page id (GUILD_PAGE_ID below) that SkyyGuilds/test_skyyguilds_0.1.5.py last passed on (tools/guilds_0_1_5_patch.py''')
# the page id SkyyGuilds/test_skyyguilds_0.1.5.py passed on (GUILD_PAGE_ID of the checked build)
PAGE_CHECKED = "26645a3ab908"
_pc = re.search(r'\nGUILD_PAGE_CHECKED = "([0-9a-f]{12})"\n', s)
assert _pc, "GUILD_PAGE_CHECKED line"
rep(_pc.group(0), '\nGUILD_PAGE_CHECKED = "%s"\n' % PAGE_CHECKED)
rep('''    print("guild page %s = the page SkyyGuilds/test_skyyguilds_0.1.4.py last passed on" % GUILD_PAGE_ID)''',
    '''    print("guild page %s = the page SkyyGuilds/test_skyyguilds_0.1.5.py last passed on" % GUILD_PAGE_ID)''')
rep('''    print("WARNING: guild page %s is NOT the page SkyyGuilds/test_skyyguilds_0.1.4.py last passed on (%s): the kit output changed the "
          "page. Run the harness, then set PAGE_CHECKED in tools/guilds_0_1_4_patch.py and regenerate; never deploy an unchecked page"''',
    '''    print("WARNING: guild page %s is NOT the page SkyyGuilds/test_skyyguilds_0.1.5.py last passed on (%s): the kit output changed the "
          "page. Run the harness, then set PAGE_CHECKED in tools/guilds_0_1_5_patch.py and regenerate; never deploy an unchecked page"''')

# ================================================================================================ checks on the result
assert "@@" not in s, "a @@ token is left in the generated script"
assert s.count("registerCommand(") == REG0 and s.count("registerSystem(") == SYS0, "command / system registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
for k in KEEP:
    assert k in s, "a block that must stay 0.1.4's changed: %s" % k[:80]
assert "disbandNow(g, u, uname" not in s and "disbandNow(g, l ==" not in s, "an old disbandNow call is left"
assert s.count("disbandNow(") == 4, "disbandNow: 1 definition + 3 callers (disband, last-member leave, admin delete)"
# javassist: methods before callers
order = ["public static synchronized long[] netOf(", "public static synchronized void netAdd(", "public static synchronized long netValue(",
         "public static String netText(", "public static long seedLine(", "public static java.util.List readBankLines(",
         "public static synchronized String seedNet(", "public static String seedText(", "public static synchronized void loadAll(",
         "public static synchronized String create(", "public static synchronized java.util.ArrayList payouts(",
         "public static synchronized long shareOf(", "public static int payees(", "public static String shareList(",
         "public static synchronized void bankNote(", "public static synchronized String disbandNow(",
         "public static synchronized String leaveNote(", "public static synchronized String leaveWarning(",
         "public static synchronized String disbandWarning(", "public static synchronized String leave(",
         "public static synchronized String disband(", "public static synchronized String deposit(",
         "public static synchronized String withdraw(", "public static int cmpRow(", "public static synchronized Object[] snapshot(",
         "public static synchronized String[] adminInfo(", "public static synchronized String adminDelete("]
pos = [s.index(o) for o in order]
assert pos == sorted(pos), "method order: %s" % [o for o, p in zip(order, pos)]
assert s.index("public static String parseBankLine(") < s.index("public static synchronized String seedNet(")
assert s.index("public static String num(long n) {") < s.index("public static String netText(")
assert s.index("public static String fmt(long n) {") < s.index("public static String netText(")
assert s.index("public static long parseLong(String s, long d) {") < s.index("public static String seedText(")
# 0.1.5 review: the pending record comes before the first coinsAdd of the payout loop; the rollback save is retried; leave texts
_dn = s[s.index("public static synchronized String disbandNow("):s.index("public static synchronized String leaveNote(")]
assert _dn.index('bankNote(g, "DISBAND-PAYOUT-START') < _dn.index("if (!coinsAdd(m.uid, sh))") and _dn.count("coinsAdd(") == 1
assert _dn.index('info("disband of " + g.id') < _dn.index("if (!coinsAdd(m.uid, sh))")
assert "for (int tries = 0; tries < 3 && !saved; tries++) saved = saveGuild(g);" in _dn and _dn.count("saveGuild(g)") == 1
assert s.count("leaveNote(g, me)") == 4, "leaveNote: 2 page confirms + the Leader's and the Member's /guild leave"
for ident in re.findall(r"#(Skyy[A-Za-z0-9_]*)", s):
    assert "_" not in ident, "UI id with an underscore: " + ident
for c in ("flex=", "max_lines=", "spacing=", "trial=True"):
    assert c not in s[s.index("# ================= 0.1.4: GuildPage's look"):s.index("GUILD_PAGE = guild_page()")], "the page block uses " + c
assert "B.deploy(" not in s and "enable_in_world(" not in s
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.4 had %d; line endings %s)" % (s.count(LF), OLD.count(LF), "CRLF" if NL == CR + LF else "LF"))
