"""Derive SkyyHud/build_skyyhud_0.3.6.py from 0.3.5 (0.3.5 is left untouched; line endings preserved).
0.3.6: every /skyyhud form usable by ordinary players (hytale:Adventurer permission group on the root and every subcommand)
and the documented positional forms made real with subcommands (export | import <code> | reset | preview |
profile list | profile save|load|delete <name>). Layout codes switch from "," to ":" between fields because the engine
tokenizer turns commas into list syntax (more than 10 items = parse error before any command runs). See the new docstring.
Review fix (same 0.3.6): the legacy flag form --action profile --code "save x" gets its surrounding quotes stripped in
HudCmd.act (a quoted flag value keeps its quotes). To regenerate, delete SkyyHud/build_skyyhud_0.3.6.py first.
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.5.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.6.py")
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


def between(start_marker, end_marker, new):
    """Replace s[start_marker .. end_marker) (end marker kept)."""
    global s
    assert s.count(start_marker) == 1, "start marker not unique: " + start_marker[:90]
    a = s.index(start_marker)
    b = s.index(end_marker, a)
    s = s[:a] + new + s[b:]


# ---------------- docstring + version ----------------
OLD_HEAD = s[:s.index('"""' + LF + "import sys, os")]
assert OLD_HEAD.startswith('"""SkyyHud 0.3.4 - build script')
old_notes = OLD_HEAD[OLD_HEAD.index("0.3.4 editor rework"):OLD_HEAD.index("Commands: /skyyhud (alias /shud) opens the editor")]
NEW_HEAD = r'''"""SkyyHud 0.3.6 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.6.py            -> SkyyHud/SkyyHud-0.3.6.jar
       python build_skyyhud_0.3.6.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.6 SkyyHud" in the HUD mod world
0.3.6 (generated by tools/hud_0_3_6_patch.py from 0.3.5): usable by every player + real positional forms.
  - permissions: AbstractCommand.setOwner() gives a command that never called requirePermission() an auto node
    (<plugin base permission>.command.skyyhud, a subcommand appends ".<name>", the base contains the version). Default players
    (group hytale:Adventurer) hold no nodes, so before 0.3.6 only "*" admins could run /skyyhud. The root and EVERY subcommand
    call setPermissionGroups({"hytale:Adventurer"}) (vanilla /help /who /ping pattern, as in SkyyEssentials 0.1). Checked in
    HytaleServer.jar: CommandManager.createVirtualPermissionGroups -> AbstractCommand.putRecursivePermissionGroups walks
    subcommands (not variants); hasPermission() of a subcommand with its own groups does not also require the parent's node;
    acceptCall0 dispatches to a subcommand BEFORE the parent's permission check, so each subcommand needs its own grant.
  - arguments: acceptCall0 needs positional-token count == required-arg count (unless extra args are allowed), so the old
    optional args only worked as --action/--code flags. 0.3.6 uses real subcommands: checkForExecutingSubcommands dispatches on
    the first positional token; with no tokens there is no match and no 0-arg variant, so the root runs its own execute().
      /skyyhud (alias /shud)                    open the editor (unchanged)
      /skyyhud export | reset | preview
      /skyyhud import <code>                    greedy string = raw rest of the line (AbstractCommand.extractGreedyRawTail)
      /skyyhud profile                          usage line
      /skyyhud profile list
      /skyyhud profile save|load|delete <name>  greedy too; spaces/symbols are stripped by cleanName exactly as before
    The old flag forms (/skyyhud --action import --code <code>, --action profile --code "save x", ...) still work: the root
    keeps its two optional args and the same action code (HudCmd.act, shared with the subcommands). A quoted flag value
    arrives WITH its quotes (--code "save x" gives '"save x"'), so act() strips one pair of surrounding " or ' from the
    profile text first (0.3.5 read the keyword as '"save' and fell through to the usage line).
  - layout codes: the engine Tokenizer makes "," its own token and ParserContext turns a,b,c into a list argument that fails
    past 10 items (server.commands.parsing.error.tooManyListItems) BEFORE any command sees the line, so an 8-widget comma code
    (40 commas) could never be pasted positionally. Export now writes ":" between fields (Coords=1:tl:8:8:100:1;Zone=...).
    Import and profile load accept ":" or "," and strip one pair of surrounding quotes, so an old comma code still imports
    when quoted (/skyyhud import "Coords=1,tl,8,8,100,1;...") and old profile files still load. The saved per-player
    .properties layout format is unchanged.
0.3.5: Widgets page and per-widget Settings page ~1.8x bigger; '< Back' buttons (Settings -> Widgets list -> editor).
''' + old_notes + r'''Commands: see 0.3.6 above.
'''
s = NEW_HEAD + s[len(OLD_HEAD):]
rep('VERSION = "0.3.5"', 'VERSION = "0.3.6"')

# ---------------- probes for the APIs 0.3.6 relies on ----------------
rep('pool.get(OPT)  # class must exist' + LF,
    'pool.get(OPT)  # class must exist' + LF + r'''AC  = "com.hypixel.hytale.server.core.command.system.AbstractCommand"
RA  = "com.hypixel.hytale.server.core.command.system.arguments.system.RequiredArg"
for c, m in ((AC, "setPermissionGroups"), (AC, "addSubCommand"), (AC, "withRequiredArg"), (AC, "addAliases"), (ARG, "GREEDY_STRING"), (CTX, "get")):
    B.probe(pool, c, m)
pool.get(RA)
''')

# ---------------- new command classes ----------------
rep('cmd  = pool.makeClass(PKG + ".HudCmd", pool.get(APC))' + LF,
    'cmd  = pool.makeClass(PKG + ".HudCmd", pool.get(APC))' + LF + r'''# 0.3.6 subcommands (top-level classes; javassist has no inner classes)
cexp = pool.makeClass(PKG + ".HudExportCmd", pool.get(APC))
cimp = pool.makeClass(PKG + ".HudImportCmd", pool.get(APC))
crst = pool.makeClass(PKG + ".HudResetCmd", pool.get(APC))
cprv = pool.makeClass(PKG + ".HudPreviewCmd", pool.get(APC))
cpro = pool.makeClass(PKG + ".HudProfileCmd", pool.get(APC))
cpls = pool.makeClass(PKG + ".HudProfileListCmd", pool.get(APC))
cpsv = pool.makeClass(PKG + ".HudProfileSaveCmd", pool.get(APC))
cpld = pool.makeClass(PKG + ".HudProfileLoadCmd", pool.get(APC))
cpdl = pool.makeClass(PKG + ".HudProfileDeleteCmd", pool.get(APC))
# vanilla /help /who /ping: grants the auto-generated node of the command to the default player group (see the docstring)
ADV = 'setPermissionGroups(new String[] { "hytale:Adventurer" });'
''')

# ---------------- layout codes: ":" between fields, import accepts both ----------------
rep('    sb.append(ids[i]).append("=").append(l.ser());' + LF,
    '    sb.append(ids[i]).append("=").append(l.ser().replace(\',\', \':\'));' + LF)
rep(r'''  java.util.Map m = get(u);
  int n = 0;
  String[] parts = code.trim().split(";");
''', r'''  java.util.Map m = get(u);
  int n = 0;
  String c = code == null ? "" : code.trim();
  if (c.length() >= 2 && ((c.charAt(0) == '"' && c.charAt(c.length() - 1) == '"') || (c.charAt(0) == '\\'' && c.charAt(c.length() - 1) == '\\''))) c = c.substring(1, c.length() - 1).trim();
  c = c.replace(':', ',');
  String[] parts = c.split(";");
''')

# ---------------- HudCmd: shared action code + subcommands + permission group ----------------
NEW_CMD = r'''# ================= HudCmd + subcommands (0.3.6) =================
# javassist order: HudCmd.act (called by every subcommand) -> each subcommand's constructor + execute -> the parents'
# constructors that addSubCommand(new ...) -> HudCmd.execute.
cmd.addField(CtField.make(f"public {PKG}.SkyyHudPlugin plugin;", cmd))
cmd.addField(CtField.make(f"public {OPT} actionArg;", cmd))
cmd.addField(CtField.make(f"public {OPT} codeArg;", cmd))
cmd.addMethod(CtNewMethod.make(f"""
public static void act({PKG}.SkyyHudPlugin plugin, {PR} pr, String action, String rest) {{
  java.util.UUID u = pr.getUuid();
  if (action.equals("export")) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] layout code: " + {PKG}.LayoutStore.export(u)));
    return;
  }}
  if (action.equals("import")) {{
    if (rest == null || rest.trim().length() == 0) {{ pr.sendMessage({MSG}.raw("[SkyyHud] usage: /skyyhud import <code>")); return; }}
    int n = {PKG}.LayoutStore.importCode(u, rest);
    if (n > 0) plugin.rebuildFor(u);
    pr.sendMessage({MSG}.raw("[SkyyHud] imported " + n + " widget layout(s)"));
    return;
  }}
  if (action.equals("reset")) {{
    {PKG}.LayoutStore.reset(u);
    plugin.rebuildFor(u);
    pr.sendMessage({MSG}.raw("[SkyyHud] layout reset to defaults"));
    return;
  }}
  if (action.equals("preview")) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] since 0.3.4 the editor always shows live previews behind invisible drag handles - nothing to switch"));
    return;
  }}
  if (action.equals("profile")) {{
    String r = rest == null ? "" : rest.trim();
    if (r.length() >= 2 && ((r.charAt(0) == '"' && r.charAt(r.length() - 1) == '"') || (r.charAt(0) == '\\'' && r.charAt(r.length() - 1) == '\\''))) r = r.substring(1, r.length() - 1).trim();
    String sub = r; String name = "";
    int sp = r.indexOf(' ');
    if (sp > 0) {{ sub = r.substring(0, sp); name = r.substring(sp + 1).trim(); }}
    sub = sub.toLowerCase();
    if (sub.equals("list")) {{ String lst2 = {PKG}.LayoutStore.profileList(u); pr.sendMessage({MSG}.raw("[SkyyHud] profiles: " + (lst2.length() == 0 ? "(none)" : lst2))); return; }}
    if (sub.equals("save")) {{ pr.sendMessage({MSG}.raw({PKG}.LayoutStore.profileSave(u, name) ? "[SkyyHud] saved profile " + {PKG}.LayoutStore.cleanName(name) : "[SkyyHud] usage: /skyyhud profile save <name>")); return; }}
    if (sub.equals("load")) {{ int n = {PKG}.LayoutStore.profileLoad(u, name); if (n > 0) plugin.rebuildFor(u); pr.sendMessage({MSG}.raw(n >= 0 ? "[SkyyHud] loaded profile " + {PKG}.LayoutStore.cleanName(name) : "[SkyyHud] no such profile")); return; }}
    if (sub.equals("delete")) {{ pr.sendMessage({MSG}.raw({PKG}.LayoutStore.profileDelete(u, name) ? "[SkyyHud] deleted profile" : "[SkyyHud] no such profile")); return; }}
    pr.sendMessage({MSG}.raw("[SkyyHud] usage: /skyyhud profile save|load|delete <name> | list")); return;
  }}
  pr.sendMessage({MSG}.raw("[SkyyHud] unknown action '" + action + "' (export | import <code> | reset | profile ...)"));
}}""", cmd))


def hud_sub(cls, name, desc, ctor_extra, body, arg_field=None):
    """One player subcommand: plugin field, (name, desc) constructor with the Adventurer group, execute -> body."""
    cls.addField(CtField.make(f"public {PKG}.SkyyHudPlugin plugin;", cls))
    if arg_field:
        cls.addField(CtField.make(f"public {RA} {arg_field};", cls))
    cls.addConstructor(CtNewConstructor.make(f"""
public {cls.getSimpleName()}({PKG}.SkyyHudPlugin p) {{
  super("{name}", "{desc}");
  this.plugin = p;
{ctor_extra}
  {ADV}
}}""", cls))
    cls.addMethod(CtNewMethod.make(f"""
protected void execute({CTX} ctx, {ST} store, {REF} ref, {PR} pr, {WLD} world) {{
  try {{
{body}
  }} catch (Throwable t) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] error: " + t));
  }}
}}""", cls))


def name_arg(desc):
    return f'  this.nameArg = withRequiredArg("name", "{desc}", {ARG}.GREEDY_STRING);'


NAME_VAL = "    Object nv = ctx.get(this.nameArg); String nm = nv == null ? \"\" : nv.toString();"

hud_sub(cexp, "export", "Print your HUD layout as a code", "", f'    {PKG}.HudCmd.act(this.plugin, pr, "export", "");')
hud_sub(cimp, "import", "Load a HUD layout code from /skyyhud export",
        f'  this.codeArg = withRequiredArg("code", "layout code from /skyyhud export", {ARG}.GREEDY_STRING);',
        f'    Object cv = ctx.get(this.codeArg);' + "\n" + f'    {PKG}.HudCmd.act(this.plugin, pr, "import", cv == null ? "" : cv.toString());',
        arg_field="codeArg")
hud_sub(crst, "reset", "Reset your HUD layout to the defaults", "", f'    {PKG}.HudCmd.act(this.plugin, pr, "reset", "");')
hud_sub(cprv, "preview", "Editor preview mode (always on since 0.3.4)", "", f'    {PKG}.HudCmd.act(this.plugin, pr, "preview", "");')
hud_sub(cpls, "list", "List your saved HUD layouts", "", f'    {PKG}.HudCmd.act(this.plugin, pr, "profile", "list");')
hud_sub(cpsv, "save", "Save your HUD layout under a name", name_arg("profile name (letters, digits, -)"),
        NAME_VAL + "\n" + f'    {PKG}.HudCmd.act(this.plugin, pr, "profile", "save " + nm);', arg_field="nameArg")
hud_sub(cpld, "load", "Load a saved HUD layout", name_arg("profile name"),
        NAME_VAL + "\n" + f'    {PKG}.HudCmd.act(this.plugin, pr, "profile", "load " + nm);', arg_field="nameArg")
hud_sub(cpdl, "delete", "Delete a saved HUD layout", name_arg("profile name"),
        NAME_VAL + "\n" + f'    {PKG}.HudCmd.act(this.plugin, pr, "profile", "delete " + nm);', arg_field="nameArg")
# /skyyhud profile (typed alone: usage) with its own subcommands; constructed after its children exist
hud_sub(cpro, "profile", "Named HUD layouts: list | save | load | delete <name>",
        f"""  addSubCommand(new {PKG}.HudProfileListCmd(p));
  addSubCommand(new {PKG}.HudProfileSaveCmd(p));
  addSubCommand(new {PKG}.HudProfileLoadCmd(p));
  addSubCommand(new {PKG}.HudProfileDeleteCmd(p));""",
        f'    pr.sendMessage({MSG}.raw("[SkyyHud] usage: /skyyhud profile save|load|delete <name> | list"));')

cmd.addConstructor(CtNewConstructor.make(f"""
public HudCmd({PKG}.SkyyHudPlugin p) {{
  super("skyyhud", "SkyyHud: open the HUD editor, or export/import/reset your layout");
  addAliases(new String[] {{ "shud" }});
  this.plugin = p;
  this.actionArg = withOptionalArg("action", "export | import | reset | profile (omit to open the editor)", {ARG}.STRING);
  this.codeArg = withOptionalArg("code", "layout code (import) or: save|load|delete <name> | list (profile)", {ARG}.GREEDY_STRING);
  {ADV}
  addSubCommand(new {PKG}.HudExportCmd(p));
  addSubCommand(new {PKG}.HudImportCmd(p));
  addSubCommand(new {PKG}.HudResetCmd(p));
  addSubCommand(new {PKG}.HudPreviewCmd(p));
  addSubCommand(new {PKG}.HudProfileCmd(p));
}}""", cmd))
cmd.addMethod(CtNewMethod.make(f"""
protected void execute({CTX} ctx, {ST} store, {REF} ref, {PR} pr, {WLD} world) {{
  try {{
    String action = ctx.provided(this.actionArg) ? String.valueOf(ctx.get(this.actionArg)).toLowerCase() : "";
    java.util.UUID u = pr.getUuid();
    if (action.length() > 0) {{ act(this.plugin, pr, action, ctx.provided(this.codeArg) ? String.valueOf(ctx.get(this.codeArg)) : ""); return; }}
    {PLA} player = ({PLA}) store.getComponent(ref, {PLA}.getComponentType());
    if (player == null) {{ pr.sendMessage({MSG}.raw("[SkyyHud] player entity not found")); return; }}
    if (!this.plugin.huds.containsKey(u)) this.plugin.attach(pr);
    player.getPageManager().openCustomPage(ref, store, new {PKG}.EditorPage(pr, this.plugin));
  }} catch (Throwable t) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] error: " + t));
  }}
}}""", cmd))

'''
between('# ================= HudCmd =================' + LF, '# ================= TickTask =================', NEW_CMD)

# ---------------- write every new class ----------------
rep('for c in (wl, lst, wid, hudc, page, sett, wpg, cmd, tick, att, rdy, pl):',
    'for c in (wl, lst, wid, hudc, page, sett, wpg, cmd, cexp, cimp, crst, cprv, cpro, cpls, cpsv, cpld, cpdl, tick, att, rdy, pl):')

assert not os.path.exists(dst), "refusing to overwrite " + dst
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
