"""Derive SkyyHud/build_skyyhud_0.3.7.py from 0.3.6 (0.3.6 is left untouched; line endings preserved).
0.3.7 (Skyy, looking at a widget's Settings page: "add color, bold, italicize, and glow to the settings so you can make them stand
out if you want"):
  - per-widget text style stored with the widget's layout (Color palette, Bold, Italic, Glow + Glow color palette); old layouts,
    export codes and profiles load unchanged (missing style fields = today's look)
  - glow is faked (Hytale labels have no glow/outline property): 8 copies of the text in the glow colour at alpha 0.45, offset
    around the real label, drawn before it inside the same widget Group, so the widget's anchor/size maths do not change
  - Zone widget shows a friendly name instead of the raw world name (skyy-island-<uuid>-p2 ran into the next widget)
  - Settings page rebuilt bigger with the new rows + a live preview on dark and bright backdrops (fits a 1080-high screen)
To regenerate, delete SkyyHud/build_skyyhud_0.3.7.py first (the script refuses to overwrite it).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.6.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.7.py")
assert not os.path.exists(dst), "refusing to overwrite " + dst
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


def between(start_marker, end_marker, new):
    """Replace s[start_marker .. end_marker) (end marker kept)."""
    global s
    assert s.count(start_marker) == 1, "start marker not unique: " + start_marker[:90]
    a = s.index(start_marker)
    b = s.index(end_marker, a)
    s = s[:a] + new + s[b:]


# ---------------- docstring + version ----------------
rep('''"""SkyyHud 0.3.6 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.6.py            -> SkyyHud/SkyyHud-0.3.6.jar
       python build_skyyhud_0.3.6.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.6 SkyyHud" in the HUD mod world
''', '''"""SkyyHud 0.3.7 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.7.py            -> SkyyHud/SkyyHud-0.3.7.jar
       python build_skyyhud_0.3.7.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.7 SkyyHud" in the HUD mod world
0.3.7 (generated by tools/hud_0_3_7_patch.py from 0.3.6): widget text styles + friendly Zone names.
  - Per-widget STYLE on the widget's Settings page (Skyy: "add color, bold, italicize, and glow ... so you can make them stand out"):
      Color       palette row: Default (#eaf6ff, the old look) + White Gold Yellow Green Lime Aqua Blue Purple Pink Red Orange Gray
      Bold        ON (default, the old look) / OFF          Italic   ON / OFF (default OFF)
      Glow        ON / OFF (default OFF)                   Glow color  Same (= the text colour) + the colours above + Black
    Selected swatch = white+black ring. Picking a glow colour also turns Glow ON. "Reset style" puts all five back to default.
    Label style properties used are the ones the game's own .ui files use: TextColor #rrggbb / #rrggbb(alpha), RenderBold,
    RenderItalics (RenderItalics is only written when ON, so a default widget sends exactly the 0.3.6 markup).
  - GLOW IS FAKED: Hytale labels have no glow/outline/shadow property (the client's only OutlineColor/OutlineSize are ELEMENT
    rectangle outlines, not text). Widgets.textSrc() draws 8 copies of the text in the glow colour at alpha 0.45 BEFORE the real
    label inside the same widget Group: 4 orthogonal at D px and 4 diagonal at (D+1)/2 px, D = (FontSize*3+12)/24 (2 px at 100%,
    1 px in the 2/3-scale editor preview). Each copy's box is the widget box inset by D on every side and shifted by its offset
    using only non-negative Left/Top/Width/Height, and the text is centred, so each copy's text centre sits exactly at the offset.
    The widget Group's anchor/size (180x26 x scale) and every snap position are unchanged.
    Element ids: #SkyyW<id>G0..G7 (HUD), #SkyyEPv<id>G0..G7 (editor preview), #SkyySetPvAG0.. / #SkyySetPvBG0.. (Settings preview).
    Editor hit areas: previews (and their glow copies) are still appended BEFORE the ItemGrid of invisible drag handles, so the
    grid stays on top and receives every click/drag; the Settings preview sits in its own row, clear of every button.
  - Storage: WLayout.ser() writes the 6 0.3.6 fields when the style is default (byte-identical files/codes), else 11 fields:
      en,anchor,dx,dy,scale,bg,color,bold,italic,glow,glowColor   e.g. 1,tr,8,8,100,1,gold,1,0,1,black
    (codes use ":" as before). parse() fills missing/unknown style fields with the defaults, so every old properties file, export
    code and profile loads as today; 0.3.6 reading a 0.3.7 file ignores the extra fields. Export/import and profiles carry the style.
  - HudMain.built (id -> glow copy count) remembers what build() actually sent; the 1 s tick only sets elements of that document,
    and tick/rebuild/first show are synchronized on the HudMain, so a tick can never set a label (glow copy or a just-enabled
    widget) before the rebuilt HUD that contains it has been sent.
  - Zone widget friendly name (Skyy's screenshot: 'skyy-island-<uuid>-p2' ran into the next widget):
      skyy-island-<key>  -> "Your Island" when <key> is the viewer's ACTIVE profile key (bridge profile:fn:key, else the UUID; also
                            when the world equals bridge island:<uuid>), otherwise "Island"
      hub / default world -> the Hytale zone the player stands in: Player (PlayerRef.getComponentConcurrent - safe off the world
                            thread, the tick runs on the scheduler) .getWorldMapTracker().getCurrentZone() -> ZoneDiscoveryInfo
                            regionName() translated with I18nModule.getMessage(lang, "server.map.region.<r>") exactly like the
                            vanilla /zone command (e.g. Zone1_Tier1 -> "Drifting Plains"), else zoneName() via server.map.zone.<z>,
                            else "Hub". Max 24 chars. Hub world = Skyy_SkyyIslands/hub.properties "world" (re-read every 15 s)
                            or Universe.getDefaultWorld(). hubWorld() is static synchronized (tick + page threads).
      any other world    -> its name, cut to 18 chars + "..."
      Fit (measured with the client's NunitoSans glyph advances, FontSize 12 bold, 180 px box; font and box scale together):
      longest real names "Whisperfrost Frontiers" ~131 px, "First Gate of the Echo" ~124 px, 24-char cap ~145-160 px.
  - Settings page: 1500 x 790 (was 940 x 440), label column 200, the same 20/17 px fonts, a "Text style" header, the palette rows,
    Bold/Italic/Glow rows, a Preview row (the widget at its real HUD size on a dark and on a bright backdrop, text as when the page
    was opened - no periodic page updates) and "< Back" + "Reset style".
''')
rep('VERSION = "0.3.6"', 'VERSION = "0.3.7"')

# ---------------- API probes ----------------
rep('''pool.get(RA)
''', '''pool.get(RA)
# 0.3.7 Zone friendly name + style
WMT = "com.hypixel.hytale.server.core.universe.world.WorldMapTracker"
ZDI = WMT + "$ZoneDiscoveryInfo"
I18 = "com.hypixel.hytale.server.core.modules.i18n.I18nModule"
for c, m in ((PR, "getComponentConcurrent"), (PR, "getLanguage"), (PLA, "getWorldMapTracker"), (WMT, "getCurrentZone"),
             (ZDI, "regionName"), (ZDI, "zoneName"), (I18, "get"), (I18, "getMessage"), (I18, "DEFAULT_LANGUAGE"),
             (UNI, "getDefaultWorld"), (UCB, "set")):
    B.probe(pool, c, m)
''')

# ---------------- palette (build-time table) + WLayout style fields ----------------
rep('''# ================= WLayout =================
''', '''# 0.3.7 style palette: key (saved in layouts / codes / profiles), button name, colour. Text colours = the first TEXT_N entries;
# the Glow color row offers all of them, where index 0 means "Same as the text colour" and Black gives a dark outline.
PAL = [("def", "Default", "#eaf6ff"), ("white", "White", "#ffffff"), ("gold", "Gold", "#ffaa00"), ("yellow", "Yellow", "#ffff55"),
       ("green", "Green", "#3fbf3f"), ("lime", "Lime", "#7cff4f"), ("aqua", "Aqua", "#55ffff"), ("blue", "Blue", "#4f8cff"),
       ("purple", "Purple", "#b066ff"), ("pink", "Pink", "#ff77d0"), ("red", "Red", "#ff4f4f"), ("orange", "Orange", "#ff8c1a"),
       ("gray", "Gray", "#a8b0b8"), ("black", "Black", "#000000")]
TEXT_N = 13


def _mix(h, t, f):
    a = [int(h[i:i + 2], 16) for i in (1, 3, 5)]
    b = [int(t[i:i + 2], 16) for i in (1, 3, 5)]
    return "#%02x%02x%02x" % tuple(int(round(a[i] + (b[i] - a[i]) * f)) for i in range(3))


def _fg(h):
    r, g, b = [int(h[i:i + 2], 16) / 255.0 for i in (1, 3, 5)]
    return "#10161c" if 0.299 * r + 0.587 * g + 0.114 * b > 0.55 else "#ffffff"


PAL_HOV = [("#3a4450" if k == "black" else _mix(c, "#ffffff", 0.3)) for k, n, c in PAL]
PAL_PRS = [_mix(c, "#000000", 0.25) for k, n, c in PAL]
PAL_FG = [_fg(c) for k, n, c in PAL]


def jarr(xs):
    return "new String[] { " + ", ".join('"%s"' % x for x in xs) + " }"


# ================= WLayout =================
''')
rep('''wl.addField(CtField.make("public boolean bg;", wl))
wl.addConstructor(CtNewConstructor.make("""
public WLayout(boolean en, String anchor, int dx, int dy, int scale) {
  this.en = en; this.anchor = anchor; this.dx = dx; this.dy = dy; this.scale = scale; this.bg = true;
}""", wl))
wl.addMethod(CtNewMethod.make("""
public String ser() { return (en ? "1" : "0") + "," + anchor + "," + dx + "," + dy + "," + scale + "," + (bg ? "1" : "0"); }""", wl))
''', '''wl.addField(CtField.make("public boolean bg;", wl))
# 0.3.7 style: col / gcol = palette keys ("def" = default text colour / glow in the text colour), bold defaults to true (old look)
for f in ("public String col;", "public boolean bold;", "public boolean ital;", "public boolean glow;", "public String gcol;"):
    wl.addField(CtField.make(f, wl))
wl.addField(CtField.make("public static final String[] PAL_KEYS = %s;" % jarr([p[0] for p in PAL]), wl))
wl.addField(CtField.make("public static final String[] PAL_NAMES = %s;" % jarr([p[1] for p in PAL]), wl))
wl.addField(CtField.make("public static final String[] PAL_HEX = %s;" % jarr([p[2] for p in PAL]), wl))
wl.addField(CtField.make("public static final String[] PAL_HOV = %s;" % jarr(PAL_HOV), wl))
wl.addField(CtField.make("public static final String[] PAL_PRS = %s;" % jarr(PAL_PRS), wl))
wl.addField(CtField.make("public static final String[] PAL_FG = %s;" % jarr(PAL_FG), wl))
wl.addField(CtField.make("public static final int TEXT_N = %d;" % TEXT_N, wl))
wl.addConstructor(CtNewConstructor.make("""
public WLayout(boolean en, String anchor, int dx, int dy, int scale) {
  this.en = en; this.anchor = anchor; this.dx = dx; this.dy = dy; this.scale = scale; this.bg = true;
  this.col = "def"; this.bold = true; this.ital = false; this.glow = false; this.gcol = "def";
}""", wl))
wl.addMethod(CtNewMethod.make("""
public static int palIdx(String k) {
  if (k == null) return -1;
  for (int i = 0; i < PAL_KEYS.length; i++) if (PAL_KEYS[i].equals(k)) return i;
  return -1;
}""", wl))
wl.addMethod(CtNewMethod.make("""
public boolean styleDefault() { return "def".equals(col) && bold && !ital && !glow && "def".equals(gcol); }""", wl))
# default style -> exactly the 0.3.6 six fields; otherwise the five style fields follow
wl.addMethod(CtNewMethod.make("""
public String ser() {
  String s = (en ? "1" : "0") + "," + anchor + "," + dx + "," + dy + "," + scale + "," + (bg ? "1" : "0");
  if (styleDefault()) return s;
  return s + "," + col + "," + (bold ? "1" : "0") + "," + (ital ? "1" : "0") + "," + (glow ? "1" : "0") + "," + gcol;
}""", wl))
''')
rep('''    if (p.length > 5) w.bg = "1".equals(p[5].trim());
    return w;
''', '''    if (p.length > 5) w.bg = "1".equals(p[5].trim());
    if (p.length > 6) {{ String c = p[6].trim(); int ci = palIdx(c); if (ci >= 0 && ci < TEXT_N) w.col = c; }}
    if (p.length > 7) w.bold = !"0".equals(p[7].trim());
    if (p.length > 8) w.ital = "1".equals(p[8].trim());
    if (p.length > 9) w.glow = "1".equals(p[9].trim());
    if (p.length > 10) {{ String g = p[10].trim(); if (palIdx(g) >= 0) w.gcol = g; }}
    return w;
''')

# ---------------- Widgets: hub file field, zone helpers ----------------
rep('''wid.addField(CtField.make('public static final String[] IDS = new String[] { %s };' % ", ".join('"%s"' % i for i in IDS), wid))
''', '''wid.addField(CtField.make('public static final String[] IDS = new String[] { %s };' % ", ".join('"%s"' % i for i in IDS), wid))
# 0.3.7 Zone: SkyyIslands' hub point file (set in setup), its "world" re-read at most every 15 s
wid.addField(CtField.make("public static java.nio.file.Path HUBFILE;", wid))
wid.addField(CtField.make("public static String HUBW;", wid))
wid.addField(CtField.make("public static long HUBAT;", wid))
''')
ZONE_HELPERS = r'''# 0.3.7 Zone friendly name helpers (all before text(), javassist order)
wid.addMethod(CtNewMethod.make("""
public static String shorten(String s, int max) {
  if (s == null) return "";
  String t = s.trim();
  if (t.length() <= max) return t;
  return t.substring(0, max).trim() + "...";
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static java.util.Map bridge() {
  try { Object b = System.getProperties().get("skyy.bridge"); if (b instanceof java.util.Map) return (java.util.Map) b; } catch (Throwable t) { }
  return null;
}""", wid))
# tools/PROFILES-CONTRACT.md helper: storage key of the ACTIVE profile (profile 1 / no SkyyProfiles = the UUID)
wid.addMethod(CtNewMethod.make("""
public static String pkey(java.util.UUID u) {
  try {
    java.util.Map b = bridge();
    Object f = b == null ? null : b.get("profile:fn:key");
    if (f instanceof java.util.function.Function) {
      Object r = ((java.util.function.Function) f).apply(u);
      if (r instanceof String && ((String) r).length() > 0) return (String) r;
    }
  } catch (Throwable t) { }
  return u.toString();
}""", wid))
# static synchronized: the 1 s HUD tick (scheduler thread) and page builds (SettingsPage.previewText) call this concurrently;
# the Widgets.class monitor makes HUBW/HUBAT visible across threads and stops a caller from seeing HUBAT already refreshed while
# HUBW is still the old value. It only reads one small file and takes no other lock (lock order HudMain -> Widgets.class only).
wid.addMethod(CtNewMethod.make("""
public static synchronized String hubWorld() {
  long now = System.currentTimeMillis();
  if (HUBAT != 0L && now - HUBAT < 15000L) return HUBW;
  HUBAT = now;
  String w = null;
  try {
    if (HUBFILE != null && java.nio.file.Files.exists(HUBFILE, new java.nio.file.LinkOption[0])) {
      java.util.Properties p = new java.util.Properties();
      java.io.InputStream in = java.nio.file.Files.newInputStream(HUBFILE, new java.nio.file.OpenOption[0]);
      try { p.load(in); } finally { in.close(); }
      String v = p.getProperty("world");
      if (v != null && v.trim().length() > 0) w = v.trim();
    }
  } catch (Throwable t) { w = HUBW; }
  HUBW = w;
  return w;
}""", wid))
# the Hytale zone under the player, as the vanilla /zone command prints it (server.map.region.<regionName>); off-thread safe:
# PlayerRef.getComponentConcurrent is the engine's async read (ServerPlayerListModule uses it), the tracker field is a plain getter
wid.addMethod(CtNewMethod.make(f"""
public static String regionText({PR} pr) {{
  try {{
    {PLA} p = ({PLA}) pr.getComponentConcurrent({PLA}.getComponentType());
    if (p == null) return null;
    {WMT} t = p.getWorldMapTracker();
    if (t == null) return null;
    {ZDI} z = t.getCurrentZone();
    if (z == null) return null;
    String lang = pr.getLanguage();
    if (lang == null || lang.length() == 0) lang = {I18}.DEFAULT_LANGUAGE;
    {I18} i18 = {I18}.get();
    String r = z.regionName();
    String zn = z.zoneName();
    if (i18 != null && r != null && r.length() > 0) {{
      String s = i18.getMessage(lang, "server.map.region." + r);
      if (s != null && s.trim().length() > 0 && !s.startsWith("server.")) return s.trim();
    }}
    if (i18 != null && zn != null && zn.length() > 0) {{
      String s = i18.getMessage(lang, "server.map.zone." + zn);
      if (s != null && s.trim().length() > 0 && !s.startsWith("server.")) return s.trim();
    }}
    if (r != null && r.length() > 0) return r.replace('_', ' ');
    if (zn != null && zn.length() > 0) return zn.replace('_', ' ');
  }} catch (Throwable t) {{ }}
  return null;
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String zoneText({PR} pr, {WLD} w) {{
  String n = w.getName();
  if (n == null) n = "";
  if (n.startsWith("skyy-island-")) {{
    java.util.UUID u = pr.getUuid();
    if (n.substring(12).equals(pkey(u))) return "Your Island";
    try {{
      java.util.Map b = bridge();
      Object own = b == null ? null : b.get("island:" + u.toString());
      if (own != null && n.equals(own.toString())) return "Your Island";
    }} catch (Throwable t) {{ }}
    return "Island";
  }}
  boolean hub = false;
  try {{ {WLD} d = {UNI}.get().getDefaultWorld(); hub = d != null && n.equals(d.getName()); }} catch (Throwable t) {{ hub = false; }}
  if (!hub) {{ String hw = hubWorld(); hub = hw != null && hw.equals(n); }}
  if (hub) {{
    String r = regionText(pr);
    return r != null ? shorten(r, 24) : "Hub";
  }}
  return shorten(n, 18);
}}""", wid))
'''
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String text(String id, {PR} pr, long joinMs) {{
''', ZONE_HELPERS + '''wid.addMethod(CtNewMethod.make(f"""
public static String text(String id, {PR} pr, long joinMs) {{
''')
rep('''      {WLD} w = {UNI}.get().getWorld(wu);
      return w == null ? "?" : w.getName();
''', '''      {WLD} w = {UNI}.get().getWorld(wu);
      return w == null ? "?" : zoneText(pr, w);
''')

# ---------------- Widgets: style + fake glow markup ----------------
STYLE_HELPERS = r'''# 0.3.7 text style + fake glow (see the docstring): markup for the glow copies + the real label inside a widget box of w x h
wid.addMethod(CtNewMethod.make("""
public static String hexOf(String key) {
  int i = com.skyy.hud.WLayout.palIdx(key);
  return i < 0 ? "#eaf6ff" : com.skyy.hud.WLayout.PAL_HEX[i];
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String glowHex({PKG}.WLayout l) {{
  return "def".equals(l.gcol) ? hexOf(l.col) : hexOf(l.gcol);
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int glowCount({PKG}.WLayout l) {{
  return l.glow ? 8 : 0;
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String styleSrc(int fs, {PKG}.WLayout l, String color) {{
  return "Style: (FontSize: " + fs + ", RenderBold: " + (l.bold ? "true" : "false") + (l.ital ? ", RenderItalics: true" : "") + ", TextColor: " + color + ", HorizontalAlignment: Center, VerticalAlignment: Center);";
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String textSrc(String base, int w, int h, int fs, {PKG}.WLayout l) {{
  StringBuilder sb = new StringBuilder();
  if (l.glow) {{
    int d = (fs * 3 + 12) / 24;
    if (d < 1) d = 1;
    int e = (d + 1) / 2;
    int[] ox = new int[] {{ -d, d, 0, 0, -e, e, -e, e }};
    int[] oy = new int[] {{ 0, 0, -d, d, -e, -e, e, e }};
    int iw = w - 2 * d; if (iw < 1) iw = 1;
    int ih = h - 2 * d; if (ih < 1) ih = 1;
    String gs = styleSrc(fs, l, glowHex(l) + "(0.45)");
    for (int k = 0; k < 8; k++) {{
      sb.append("Label #").append(base).append("G").append(k).append(" {{ Anchor: (Left: ").append(d + ox[k]).append(", Top: ").append(d + oy[k]).append(", Width: ").append(iw).append(", Height: ").append(ih).append("); Text: \\"\\"; ").append(gs).append(" }} ");
    }}
  }}
  sb.append("Label #").append(base).append("Txt {{ Anchor: (Full: 0); Text: \\"\\"; ").append(styleSrc(fs, l, hexOf(l.col))).append(" }}");
  return sb.toString();
}}""", wid))
# sel = "#<base>": sets the real label and its n glow copies
wid.addMethod(CtNewMethod.make(f"""
public static void setText({UCB} b, String sel, int n, String t) {{
  b.set(sel + "Txt.Text", t);
  for (int k = 0; k < n; k++) b.set(sel + "G" + k + ".Text", t);
}}""", wid))
'''
rep(r'''wid.addMethod(CtNewMethod.make(f"""
public static String widgetSrc(String id, {PKG}.WLayout l) {{
  int fs = 12 * l.scale / 100; if (fs < 6) fs = 6;
  return "Group #SkyyW" + id + " {{ Anchor: " + anchorSrc(l) + "; " + (l.bg ? "Background: #0b1524(0.72); " : "") + "Label #SkyyW" + id + "Txt {{ Anchor: (Full: 0); Text: \\"\\"; Style: (FontSize: " + fs + ", RenderBold: true, TextColor: #eaf6ff, HorizontalAlignment: Center, VerticalAlignment: Center); }} }}";
}}""", wid))
''', STYLE_HELPERS + r'''wid.addMethod(CtNewMethod.make(f"""
public static String widgetSrc(String id, {PKG}.WLayout l) {{
  int fs = 12 * l.scale / 100; if (fs < 6) fs = 6;
  int w = 180 * l.scale / 100; int h = 26 * l.scale / 100;
  return "Group #SkyyW" + id + " {{ Anchor: " + anchorSrc(l) + "; " + (l.bg ? "Background: #0b1524(0.72); " : "") + textSrc("SkyyW" + id, w, h, fs, l) + " }}";
}}""", wid))
''')

# ---------------- HudMain: built map, glow-aware fill, synchronized sends ----------------
rep('''hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap last = new java.util.concurrent.ConcurrentHashMap();", hudc))
''', '''hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap last = new java.util.concurrent.ConcurrentHashMap();", hudc))
# 0.3.7: widget id -> Integer glow copy count of the document build() last sent (fill() only touches those elements)
hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap built = new java.util.concurrent.ConcurrentHashMap();", hudc))
''')
between('''hudc.addMethod(CtNewMethod.make(f"""
public void fill(''', '''# ================= Plugin (part A) =================''', r'''hudc.addMethod(CtNewMethod.make(f"""
public void fill({UCB} b, boolean full) {{
  {PR} pr = getPlayerRef();
  String[] ids = {PKG}.Widgets.IDS;
  for (int i = 0; i < ids.length; i++) {{
    Object g = this.built.get(ids[i]);
    if (g == null) continue;
    String t = {PKG}.Widgets.text(ids[i], pr, this.joinMs);
    String prev = (String) this.last.get(ids[i]);
    if (full || prev == null || !prev.equals(t)) {{
      this.last.put(ids[i], t);
      {PKG}.Widgets.setText(b, "#SkyyW" + ids[i], ((Integer) g).intValue(), t);
    }}
  }}
}}""", hudc))
hudc.addMethod(CtNewMethod.make(f"""
protected void build({UCB} b) {{
  // 0.2.3: whole HUD sent inline (pattern from EndlessLeveling DungeonQueueHud) - no .ui document lookup on the client.
  b.appendInline((String) null, "Group #SkyyHudRoot {{ Anchor: (Full: 0); }}");
  java.util.Map m = {PKG}.LayoutStore.get(this.uuid);
  String[] ids = {PKG}.Widgets.IDS;
  this.built.clear();
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || !l.en) continue;
    b.appendInline("#SkyyHudRoot", {PKG}.Widgets.widgetSrc(ids[i], l));
    this.built.put(ids[i], Integer.valueOf({PKG}.Widgets.glowCount(l)));
  }}
  this.last.clear();
  fill(b, true);
}}""", hudc))
# tick (scheduler thread), rebuild (world thread, page clicks) and the first show (attach) share the HudMain monitor, so an
# update built from one document can never be sent after/before the show() of another
hudc.addMethod(CtNewMethod.make(f"""
public synchronized void tick() {{
  try {{
    {UCB} b = new {UCB}();
    fill(b, false);
    if (b.getCommands().length > 0) update(false, b);
  }} catch (Throwable t) {{ }}
}}""", hudc))
hudc.addMethod(CtNewMethod.make("""
public synchronized void rebuild() {
  try { show(); } catch (Throwable t) { }
}""", hudc))
hudc.addMethod(CtNewMethod.make("""
public synchronized void showNow() {
  show();
}""", hudc))

''')
rep('''    this.huds.put(pr.getUuid(), h);
    h.show();
''', '''    this.huds.put(pr.getUuid(), h);
    h.showNow();
''')

# ---------------- EditorPage previews: styled + glow ----------------
rep(r'''    b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + "Label #SkyyEPv" + ids[i] + "Txt {{ Anchor: (Full: 0); Text: \\"\\"; Style: (FontSize: " + fs + ", RenderBold: true, TextColor: #eaf6ff, HorizontalAlignment: Center, VerticalAlignment: Center); }} }}");
    b.set("#SkyyEPv" + ids[i] + "Txt.Text", text);
''', r'''    b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + {PKG}.Widgets.textSrc("SkyyEPv" + ids[i], cw, ch, fs, l) + " }}");
    {PKG}.Widgets.setText(b, "#SkyyEPv" + ids[i], {PKG}.Widgets.glowCount(l), text);
''')

# ---------------- SettingsPage: bigger page + style rows + preview ----------------
SETT_BUILD = r'''sett.addMethod(CtNewMethod.make("""
public static String cap(String k) {
  if (k == null || k.length() == 0) return "";
  return k.substring(0, 1).toUpperCase() + k.substring(1);
}""", sett))
# one palette swatch: 84 x 44 cell; the button shows the colour itself (name in a readable dark/light text); the selected one gets
# a white + black ring (visible on every swatch, white and black included)
sett.addMethod(CtNewMethod.make(f"""
public String swatch(String bid, int pi, boolean selected, String label) {{
  String bg = {PKG}.WLayout.PAL_HEX[pi]; String hv = {PKG}.WLayout.PAL_HOV[pi]; String ps = {PKG}.WLayout.PAL_PRS[pi]; String fg = {PKG}.WLayout.PAL_FG[pi];
  String ls = "FontSize: 15, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center, TextColor: " + fg;
  String st = "Style: TextButtonStyle(Default: (Background: " + bg + ", LabelStyle: (" + ls + ")), Hovered: (Background: " + hv + ", LabelStyle: (" + ls + ")), Pressed: (Background: " + ps + ", LabelStyle: (" + ls + ")));";
  return "Group {{ Anchor: (Width: 84, Height: 44); " + (selected ? "Background: #ffffff; " : "") + "Group {{ Anchor: (Left: 2, Right: 2, Top: 2, Bottom: 2); " + (selected ? "Background: #000000; " : "") + "TextButton #" + bid + " {{ Anchor: (Left: 2, Right: 2, Top: 2, Bottom: 2); Text: \\"" + label + "\\"; " + st + " }} }} }}";
}}""", sett))
sett.addMethod(CtNewMethod.make(f"""
public String previewText() {{
  long join = System.currentTimeMillis();
  try {{ {PKG}.HudMain hm = ({PKG}.HudMain) this.plugin.huds.get(this.playerRef.getUuid()); if (hm != null) join = hm.joinMs; }} catch (Throwable t) {{ }}
  String t = null;
  try {{ t = {PKG}.Widgets.text(this.wid, this.playerRef, join); }} catch (Throwable x) {{ t = null; }}
  if (t == null || t.length() == 0 || t.equals("?")) t = {PKG}.Widgets.label(this.wid);
  return t;
}}""", sett))
sett.addMethod(CtNewMethod.make(f"""
public void onOff({UCB} b, {UEB} ev, String row, String label, String idOn, String idOff, boolean val, String pOn, String pOff, String bs, String on) {{
  b.appendInline("#SkyySet", "Group #" + row + " {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");
  b.appendInline("#" + row, "Label {{ Anchor: (Width: 200, Height: 44); Text: \\"" + label + "\\"; Style: (FontSize: 20, TextColor: #ffffff, VerticalAlignment: Center); }}");
  b.appendInline("#" + row, "TextButton #" + idOn + " {{ Anchor: (Width: 104, Height: 44); Text: \\"ON\\"; " + (val ? on : bs) + " }}");
  b.appendInline("#" + row, "Label {{ Anchor: (Width: 8, Height: 44); Text: \\"\\"; }}");
  b.appendInline("#" + row, "TextButton #" + idOff + " {{ Anchor: (Width: 104, Height: 44); Text: \\"OFF\\"; " + (val ? bs : on) + " }}");
  ev.addEventBinding({BT}.Activating, "#" + idOn, {EVD}.of("a", pOn));
  ev.addEventBinding({BT}.Activating, "#" + idOff, {EVD}.of("a", pOff));
}}""", sett))
sett.addMethod(CtNewMethod.make(f"""
public void build({REF} ref, {UCB} b, {UEB} ev, {ST} st) {{
  java.util.UUID u = this.playerRef.getUuid();
  {PKG}.WLayout l = ({PKG}.WLayout) {PKG}.LayoutStore.get(u).get(this.wid);
  String bs = "Style: TextButtonStyle(Default: (Background: #1d3a5f, LabelStyle: (FontSize: 17, TextColor: #dceeff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Hovered: (Background: #2f5a8f, LabelStyle: (FontSize: 17, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Pressed: (Background: #0f2038, LabelStyle: (FontSize: 17, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));";
  String on = "Style: TextButtonStyle(Default: (Background: #7fe07f, LabelStyle: (FontSize: 17, TextColor: #062a06, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Hovered: (Background: #a0f0a0, LabelStyle: (FontSize: 17, TextColor: #062a06, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Pressed: (Background: #5fb05f, LabelStyle: (FontSize: 17, TextColor: #062a06, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));";
  String rl = "Style: (FontSize: 20, TextColor: #ffffff, VerticalAlignment: Center);";
  b.appendInline((String) null, "Group #SkyySet {{ Anchor: (Width: 1500, Height: 790); Background: #0b1524(0.96); Padding: (Horizontal: 16, Vertical: 10); LayoutMode: Top; }}");
  b.appendInline("#SkyySet", "Group {{ Anchor: (Height: 2); Background: #7fe07f; }}");
  b.appendInline("#SkyySet", "Label {{ Anchor: (Height: 44); Text: \\"" + {PKG}.Widgets.label(this.wid) + " settings\\"; Style: (FontSize: 26, RenderBold: true, TextColor: #eaffea, HorizontalAlignment: Center, VerticalAlignment: Center); }}");
  if (l == null) return;
  onOff(b, ev, "SkyySetRow1", "Visible", "SkyySetOn", "SkyySetOff", l.en, "on", "off", bs, on);
  onOff(b, ev, "SkyySetRow2", "Background", "SkyySetBgOn", "SkyySetBgOff", l.bg, "bgon", "bgoff", bs, on);
  b.appendInline("#SkyySet", "Group #SkyySetRow3 {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");
  b.appendInline("#SkyySetRow3", "Label {{ Anchor: (Width: 200, Height: 44); Text: \\"Size " + l.scale + "%\\"; " + rl + " }}");
  int[] sizes = new int[] {{ 50, 75, 100, 125, 150, 200 }};
  for (int i = 0; i < sizes.length; i++) {{
    b.appendInline("#SkyySetRow3", "TextButton #SkyySetSz" + sizes[i] + " {{ Anchor: (Width: 92, Height: 44); Text: \\"" + sizes[i] + "%\\"; " + (l.scale == sizes[i] ? on : bs) + " }}");
    b.appendInline("#SkyySetRow3", "Label {{ Anchor: (Width: 8, Height: 44); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyySetSz" + sizes[i], {EVD}.of("a", "sz:" + sizes[i]));
  }}
  b.appendInline("#SkyySet", "Group #SkyySetRow4 {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");
  b.appendInline("#SkyySetRow4", "Label {{ Anchor: (Width: 200, Height: 44); Text: \\"Snap to\\"; " + rl + " }}");
  String[] an = new String[] {{ "tl", "t", "tr", "l", "c", "r", "bl", "b", "br" }};
  for (int i = 0; i < an.length; i++) {{
    b.appendInline("#SkyySetRow4", "TextButton #SkyySetAn" + an[i].toUpperCase() + " {{ Anchor: (Width: 66, Height: 44); Text: \\"" + an[i].toUpperCase() + "\\"; " + (l.anchor.equals(an[i]) ? on : bs) + " }}");
    b.appendInline("#SkyySetRow4", "Label {{ Anchor: (Width: 6, Height: 44); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyySetAn" + an[i].toUpperCase(), {EVD}.of("a", "an:" + an[i]));
  }}
  b.appendInline("#SkyySet", "Label {{ Anchor: (Height: 34); Text: \\"Text style - make this widget stand out\\"; Style: (FontSize: 18, RenderBold: true, TextColor: #9fe0ff, VerticalAlignment: Center); }}");
  int ci = {PKG}.WLayout.palIdx(l.col);
  if (ci < 0 || ci >= {PKG}.WLayout.TEXT_N) ci = 0;
  b.appendInline("#SkyySet", "Group #SkyySetRowCol {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");
  b.appendInline("#SkyySetRowCol", "Label {{ Anchor: (Width: 200, Height: 44); Text: \\"Color\\"; " + rl + " }}");
  for (int i = 0; i < {PKG}.WLayout.TEXT_N; i++) {{
    String k = {PKG}.WLayout.PAL_KEYS[i];
    b.appendInline("#SkyySetRowCol", swatch("SkyySetTc" + cap(k), i, i == ci, {PKG}.WLayout.PAL_NAMES[i]));
    b.appendInline("#SkyySetRowCol", "Label {{ Anchor: (Width: 6, Height: 44); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyySetTc" + cap(k), {EVD}.of("a", "col:" + k));
  }}
  onOff(b, ev, "SkyySetRowB", "Bold", "SkyySetBOn", "SkyySetBOff", l.bold, "bon", "boff", bs, on);
  onOff(b, ev, "SkyySetRowI", "Italic", "SkyySetIOn", "SkyySetIOff", l.ital, "ion", "ioff", bs, on);
  onOff(b, ev, "SkyySetRowGl", "Glow", "SkyySetGlOn", "SkyySetGlOff", l.glow, "gon", "goff", bs, on);
  b.appendInline("#SkyySetRowGl", "Label {{ Anchor: (Width: 24, Height: 44); Text: \\"\\"; }}");
  b.appendInline("#SkyySetRowGl", "Label {{ Anchor: (Width: 900, Height: 44); Text: \\"a soft halo in the glow color behind the text - picking a glow color turns it on\\"; Style: (FontSize: 16, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
  int gi = {PKG}.WLayout.palIdx(l.gcol);
  if (gi < 0) gi = 0;
  b.appendInline("#SkyySet", "Group #SkyySetRowGc {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");
  b.appendInline("#SkyySetRowGc", "Label {{ Anchor: (Width: 200, Height: 44); Text: \\"Glow color\\"; " + rl + " }}");
  for (int i = 0; i < {PKG}.WLayout.PAL_KEYS.length; i++) {{
    String k = {PKG}.WLayout.PAL_KEYS[i];
    b.appendInline("#SkyySetRowGc", swatch("SkyySetGc" + cap(k), i == 0 ? ci : i, i == gi, i == 0 ? "Same" : {PKG}.WLayout.PAL_NAMES[i]));
    if (i + 1 < {PKG}.WLayout.PAL_KEYS.length) b.appendInline("#SkyySetRowGc", "Label {{ Anchor: (Width: 6, Height: 44); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyySetGc" + cap(k), {EVD}.of("a", "gcol:" + k));
  }}
  int pw = 180 * l.scale / 100; int ph = 26 * l.scale / 100;
  int fs = 12 * l.scale / 100; if (fs < 6) fs = 6;
  String text = previewText();
  int gn = {PKG}.Widgets.glowCount(l);
  b.appendInline("#SkyySet", "Group #SkyySetRowPv {{ Anchor: (Height: 76); LayoutMode: Left; Padding: (Top: 8); }}");
  b.appendInline("#SkyySetRowPv", "Label {{ Anchor: (Width: 200, Height: 60); Text: \\"Preview\\"; " + rl + " }}");
  String[] pv = new String[] {{ "SkyySetPvA", "SkyySetPvB" }};
  String[] bd = new String[] {{ "#141a22", "#8fb3cf" }};
  for (int j = 0; j < pv.length; j++) {{
    b.appendInline("#SkyySetRowPv", "Group #" + pv[j] + "Wrap {{ Anchor: (Width: 400, Height: 60); Background: " + bd[j] + "; }}");
    b.appendInline("#" + pv[j] + "Wrap", "Group #" + pv[j] + " {{ Anchor: (Left: " + ((400 - pw) / 2) + ", Top: " + ((60 - ph) / 2) + ", Width: " + pw + ", Height: " + ph + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + {PKG}.Widgets.textSrc(pv[j], pw, ph, fs, l) + " }}");
    b.appendInline("#SkyySetRowPv", "Label {{ Anchor: (Width: 12, Height: 60); Text: \\"\\"; }}");
    {PKG}.Widgets.setText(b, "#" + pv[j], gn, text);
  }}
  b.appendInline("#SkyySetRowPv", "Label {{ Anchor: (Width: 360, Height: 60); Text: \\"on dark and on bright scenery\\"; Style: (FontSize: 15, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
  b.appendInline("#SkyySet", "Group #SkyySetRow5 {{ Anchor: (Height: 70); LayoutMode: Left; Padding: (Top: 20); }}");
  b.appendInline("#SkyySetRow5", "TextButton #SkyySetBack {{ Anchor: (Width: 220, Height: 46); Text: \\"< Back\\"; " + bs + " }}");
  b.appendInline("#SkyySetRow5", "Label {{ Anchor: (Width: 16, Height: 46); Text: \\"\\"; }}");
  b.appendInline("#SkyySetRow5", "TextButton #SkyySetRst {{ Anchor: (Width: 220, Height: 46); Text: \\"Reset style\\"; " + bs + " }}");
  ev.addEventBinding({BT}.Activating, "#SkyySetBack", {EVD}.of("a", "back"));
  ev.addEventBinding({BT}.Activating, "#SkyySetRst", {EVD}.of("a", "rstyle"));
}}""", sett))
'''
between('''sett.addMethod(CtNewMethod.make(f"""
public void build(''', '''sett.addMethod(CtNewMethod.make("""
public static int jsonAfter(''', SETT_BUILD)
rep('''sett.addMethod(CtNewMethod.make(f"""
public void handleDataEvent(''', '''sett.addMethod(CtNewMethod.make("""
public static String strAfter(String data, String marker) {
  int p = data.indexOf(marker);
  if (p < 0) return "";
  p += marker.length();
  int q = data.indexOf('\\"', p);
  if (q < 0) return "";
  return data.substring(p, q);
}""", sett))
sett.addMethod(CtNewMethod.make(f"""
public void handleDataEvent(''')
rep(r'''    else if (data.indexOf("\\"an:") >= 0) {{ int p = data.indexOf("\\"an:") + 4; int q = data.indexOf('\\"', p); String a = data.substring(p, q); if ({PKG}.WLayout.validAnchor(a)) {{ l.anchor = a; l.dx = 8; l.dy = 8; }} }}
    else return;
''', r'''    else if (data.indexOf("\\"an:") >= 0) {{ int p = data.indexOf("\\"an:") + 4; int q = data.indexOf('\\"', p); String a = data.substring(p, q); if ({PKG}.WLayout.validAnchor(a)) {{ l.anchor = a; l.dx = 8; l.dy = 8; }} }}
    else if (data.indexOf("\\"bon\\"") >= 0) l.bold = true;
    else if (data.indexOf("\\"boff\\"") >= 0) l.bold = false;
    else if (data.indexOf("\\"ion\\"") >= 0) l.ital = true;
    else if (data.indexOf("\\"ioff\\"") >= 0) l.ital = false;
    else if (data.indexOf("\\"gon\\"") >= 0) l.glow = true;
    else if (data.indexOf("\\"goff\\"") >= 0) l.glow = false;
    else if (data.indexOf("\\"rstyle\\"") >= 0) {{ l.col = "def"; l.bold = true; l.ital = false; l.glow = false; l.gcol = "def"; }}
    else if (data.indexOf("\\"col:") >= 0) {{ String c = strAfter(data, "\\"col:"); int ci = {PKG}.WLayout.palIdx(c); if (ci >= 0 && ci < {PKG}.WLayout.TEXT_N) l.col = c; }}
    else if (data.indexOf("\\"gcol:") >= 0) {{ String c = strAfter(data, "\\"gcol:"); if ({PKG}.WLayout.palIdx(c) >= 0) {{ l.gcol = c; l.glow = true; }} }}
    else return;
''')

# ---------------- plugin setup + manifest ----------------
rep('''  {PKG}.LayoutStore.DIR = getDataDirectory().resolveSibling("Skyy_SkyyHud").resolve("layouts");
''', '''  {PKG}.LayoutStore.DIR = getDataDirectory().resolveSibling("Skyy_SkyyHud").resolve("layouts");
  {PKG}.Widgets.HUBFILE = getDataDirectory().resolveSibling("Skyy_SkyyIslands").resolve("hub.properties");
''')
rep('"SkyyHud: customizable server-side HUD. 8 widgets, per-player layouts, /skyyhud editor + layout codes. Zero dependencies."',
    '"SkyyHud: customizable server-side HUD. 8 widgets, per-player layouts and text styles (color, bold, italic, glow), /skyyhud editor + layout codes. Zero dependencies."')

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
