"""Derive SkyyHud/build_skyyhud_0.3.10.py from the LIVE 0.3.9 (0.3.9 is left untouched; line endings preserved).
0.3.10 = adoption of the admin config kit (research/Server-Setup-Spec.md 4.8 + section 7, tools/CONFIG-CONTRACT.md, tools/skyycfg.py):
  - NEW file <world>/mods/Skyy_SkyyHud/config.properties (written with its comments at the first start when missing), key defaultLayout
    = a layout code from /skyyhud export; empty (the default) = the built-in layout, so nothing changes until an admin sets one.
  - rows (Server Setup -> HUD, config:def:SkyyHud / config:fn:SkyyHud, node skyyhud.admin):
      hud.defaultLayout  text    ""   new   field HudCfg.DEFAULT_LAYOUT, check= HudCfg.checkLayout (refuses anything that is not a code)
      hud.useMine        action       new   HudCfg.useMine: the admin's own current layout -> hud.defaultLayout through CfgFn.set
                                            (logged, versioned, undoable); check= HudCfg.checkUse asks first ("?question", no red button)
      hud.editor         link         -     runs /skyyhud (opens the admin's own editor; its footer gets "< Server Setup" back to
                                            Server Setup -> HUD for a player with skyymenu.modconfig when /modconfig exists)
  - where the server default applies (Widgets.start(id) = its entry for that widget, clamped, else the built-in Widgets.def(id)):
    a player with no layout file (never changed the HUD: new players, and at their next join everyone who never edited), a widget
    missing from an old layout file, /skyyhud reset. A player's own saved layout always wins. importCode keeps Widgets.def for the box.
  - NEW admin subcommands /skyyhud default [use | clear] (requirePermission skyyhud.admin + setPermissionGroups(new String[0]), execute
    re-checks the node) - the no-SkyyMenu path; writes go through the kit (via=command).
  - setup(): HudCfg.load() after the layout paths, CfgPub.start(...) at the END; shutdown(): CfgPub.shutdown() (a failure is logged).
  - no player Settings switch (research/Settings-Spec.md 3.13: SkyyHud sends no unprompted messages).
To regenerate, delete SkyyHud/build_skyyhud_0.3.10.py first (the script refuses to overwrite it).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.9.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.10.py")
assert not os.path.exists(dst), "refusing to overwrite " + dst
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


# ---------------- docstring + version ----------------
rep('''"""SkyyHud 0.3.9 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.9.py            -> SkyyHud/SkyyHud-0.3.9.jar
       python build_skyyhud_0.3.9.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.9 SkyyHud" in the HUD mod world
''', '''"""SkyyHud 0.3.10 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.10.py            -> SkyyHud/SkyyHud-0.3.10.jar
       (deploys only through tools/deploy_set.py - never pass --deploy here)
0.3.10 (generated by tools/hud_0_3_10_patch.py from 0.3.9): in-game admin config (research/Server-Setup-Spec.md 4.8, tools/skyycfg.py,
  contract tools/CONFIG-CONTRACT.md). SkyWynn Menu -> Server Setup -> HUD (SkyyMenu 0.3+) shows three rows:
    hud.defaultLayout  text, NEW ONLY  the layout code new players start with (a code from /skyyhud export; empty = built-in).
                                       check= HudCfg.checkLayout refuses a typed value that is not a code: every part id=fields, a known
                                       widget id (Coords Zone Gclock Rclock Day Session Online Coins Party Guild), each id once, fields
                                       that WLayout.parse accepts (the importCode rules: ":" or ",", one pair of quotes stripped).
    hud.useMine        action          "Use my layout": copies the admin's OWN current layout (LayoutStore.export) into
                                       hud.defaultLayout through CfgFn.set (validated, logged, versioned, Undo in Changes); asks first
                                       through check= HudCfg.checkUse ("?question" - no danger flag, the spec lists none).
    hud.editor         link            runs /skyyhud as the admin (their editor, to set the look up first). The way back: the editor's
                                       footer shows "< Server Setup" (runs /modconfig hud; Server Setup -> HUD replaces the editor, no
                                       close first) ONLY when /modconfig exists (SkyyMenu 0.3+) and the player has skyymenu.modconfig -
                                       the SkyyRanks 0.1 RankEditorPage pattern. Every other player's editor is the 0.3.9 page unchanged.
  File <world>/mods/Skyy_SkyyHud/config.properties (NEW; written with comments at the first start when missing), key defaultLayout,
  bound field:HudCfg.DEFAULT_LAYOUT (public static volatile String). No RELOAD routine: a hand edit is applied by the kit (Reload file,
  or at its next write) or at the next start (HudCfg.load); an invalid hand-edited code is not refused - its valid parts are used and
  the start log warns. Node skyyhud.admin (ops have it through "*").
  Where the server default applies: Widgets.start(id) = the default code's entry for that widget (WLayout.parse with the built-in box,
  then clampToScreen), else the built-in Widgets.def(id). Used by LayoutStore.get for a player with NO layout file (new players, and
  anyone who never changed the HUD - they follow the server default at their next join; the cache lives until they leave), for a
  widget missing from an older layout file, and by /skyyhud reset (which saves the current default into the player's file, as
  0.3.9 saved the built-in one). A player's saved layout always wins; importCode keeps Widgets.def for the box size. With
  defaultLayout empty every path is byte-for-byte the 0.3.9 path (start(id) returns def(id) untouched).
  Admin commands (no-SkyyMenu path; writes through the kit with via=command, so they are logged and versioned):
    /skyyhud default         status + usage          /skyyhud default use     your current layout becomes the default
    /skyyhud default clear   back to the built-in layout
    Each: requirePermission("skyyhud.admin") AND setPermissionGroups(new String[0]) (an admin SUB-command under the Adventurer
    command /skyyhud - without the empty list the engine copies hytale:Adventurer onto it and hands every player skyyhud.admin,
    tools/ci/lint.py perm_group_leaks); execute() re-checks pr.hasPermission.
  setup(): HudCfg.load() right after the layout paths, CfgPub.start(mods dir) at the END (config:def:SkyyHud + config:fn:SkyyHud);
  shutdown(): CfgPub.shutdown() (a failure is logged as a warning). No player Settings switch (research/Settings-Spec.md 3.13: SkyyHud
  sends no unprompted messages).
  Unchanged: every widget, page (except the admin-only footer button above), layout file / export code / profile format, the bridge
  reads, every player command.
''')
rep('''import skyybuild as B

VERSION = "0.3.9"''', '''import skyybuild as B
import skyycfg as CFG        # 0.3.10: the admin config kit (research/Server-Setup-Spec.md 1.4)

VERSION = "0.3.10"''')

# ---------------- probes for the new engine calls ----------------
rep('''             (UNI, "getDefaultWorld"), (UCB, "set")):
    B.probe(pool, c, m)
''', '''             (UNI, "getDefaultWorld"), (UCB, "set")):
    B.probe(pool, c, m)
# 0.3.10 admin subcommands (/skyyhud default ...) + the admin config kit
for c, m in ((PR, "hasPermission"), (PR, "getUsername"), (AC, "requirePermission")):
    B.probe(pool, c, m)
# 0.3.10 the editor's "< Server Setup" button (SkyyMenu 0.3's /modconfig; the SkyyRanks 0.1 RankEditorPage pattern)
CMGR = "com.hypixel.hytale.server.core.command.system.CommandManager"
for c, m in ((CMGR, "get"), (CMGR, "resolveCommand"), (CMGR, "handleCommand")):
    B.probe(pool, c, m)
''')

# ---------------- new classes ----------------
rep('''cpdl = pool.makeClass(PKG + ".HudProfileDeleteCmd", pool.get(APC))
''', '''cpdl = pool.makeClass(PKG + ".HudProfileDeleteCmd", pool.get(APC))
# 0.3.10 admin subcommands /skyyhud default [use | clear] and the admin config holder (tools/skyycfg.py binds HudCfg.DEFAULT_LAYOUT)
cdef  = pool.makeClass(PKG + ".HudDefaultCmd", pool.get(APC))
cduse = pool.makeClass(PKG + ".HudDefaultUseCmd", pool.get(APC))
cdclr = pool.makeClass(PKG + ".HudDefaultClearCmd", pool.get(APC))
hcfg  = pool.makeClass(PKG + ".HudCfg")
HUD_NODE = "skyyhud.admin"
''')

# ---------------- HudCfg part A + Widgets.start + the kit (before LayoutStore, which uses Widgets.start) ----------------
rep('''# ================= LayoutStore =================
''', r'''# ================= HudCfg part A (0.3.10: the server default layout; admin config through tools/skyycfg.py) =================
# javassist order: fields (before CFG.emit, which reads the bound field's type) -> code parsing + check hook (Widgets.IDS, WLayout.parse
# exist) -> Widgets.start (LayoutStore.get / reset call it) -> CFG.emit. Part B (load, the action, setDefault) follows LayoutStore.
def jlit(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


CONFIG_TEXT = "\n".join([
    "# SkyyHud server settings. Change them in game (SkyWynn Menu -> Server Setup -> HUD, or /modconfig), with /skyyhud default use|clear,",
    "# or edit this file and click Reload file on that page (the next server start reads it too).",
    "#",
    "# defaultLayout = the HUD layout new players start with: a layout code from /skyyhud export (empty = the built-in layout).",
    "# Players who never changed their HUD get it at their next join; /skyyhud reset puts a player on it. A player's own layout wins.",
    "defaultLayout=",
    "",
])
for f in ('public static volatile String DEFAULT_LAYOUT = "";', "public static java.nio.file.Path FILE;",
          "public static com.hypixel.hytale.logger.HytaleLogger LOG;",
          # { code the cache was parsed from, java.util.HashMap widget id -> its fields } - one volatile publish, never a torn pair
          "public static volatile Object[] PARSED;",
          "public static final String DEFAULT_TEXT = %s;" % jlit(CONFIG_TEXT)):
    hcfg.addField(CtField.make(f, hcfg))
hcfg.addMethod(CtNewMethod.make("""
public static void info(String m) {
  try { if (LOG != null) LOG.at(java.util.logging.Level.INFO).log("[SkyyHud] " + m); } catch (Throwable t) { }
}""", hcfg))
hcfg.addMethod(CtNewMethod.make("""
public static void warn(String m) {
  try { if (LOG != null) LOG.at(java.util.logging.Level.WARNING).log("[SkyyHud] " + m); } catch (Throwable t) { }
}""", hcfg))
# the importCode rules: trim, strip ONE pair of surrounding " or ' (34 / 39), ":" -> ","
hcfg.addMethod(CtNewMethod.make("""
public static String unquote(String code) {
  String c = code == null ? "" : code.trim();
  if (c.length() >= 2) {
    char q = c.charAt(0);
    if ((q == 34 || q == 39) && c.charAt(c.length() - 1) == q) c = c.substring(1, c.length() - 1).trim();
  }
  return c.replace(':', ',');
}""", hcfg))
hcfg.addMethod(CtNewMethod.make(f"""
public static boolean knownId(String id) {{
  String[] ids = {PKG}.Widgets.IDS;
  for (int i = 0; i < ids.length; i++) if (ids[i].equals(id)) return true;
  return false;
}}""", hcfg))
hcfg.addMethod(CtNewMethod.make(f"""
public static String idList() {{
  StringBuilder sb = new StringBuilder();
  String[] ids = {PKG}.Widgets.IDS;
  for (int i = 0; i < ids.length; i++) {{ if (i > 0) sb.append(", "); sb.append(ids[i]); }}
  return sb.toString();
}}""", hcfg))
# lenient (use time): every known widget part that WLayout.parse accepts; anything else is skipped, like /skyyhud import
hcfg.addMethod(CtNewMethod.make(f"""
public static java.util.HashMap parseCode(String code) {{
  java.util.HashMap m = new java.util.HashMap();
  String[] parts = unquote(code).split(";");
  for (int i = 0; i < parts.length; i++) {{
    int eq = parts[i].indexOf('=');
    if (eq <= 0) continue;
    String id = parts[i].substring(0, eq).trim();
    if (!knownId(id)) continue;
    String f = parts[i].substring(eq + 1).trim();
    if ({PKG}.WLayout.parse(f, null) == null) continue;
    m.put(id, f);
  }}
  return m;
}}""", hcfg))
# strict (typed / imported / restored values, via the kit's check= hook): null = fine (empty = built-in), else the reason
hcfg.addMethod(CtNewMethod.make(f"""
public static String codeError(String code) {{
  String c = unquote(code);
  if (c.length() == 0) return null;
  String[] parts = c.split(";");
  java.util.HashSet seen = new java.util.HashSet();
  int n = 0;
  for (int i = 0; i < parts.length; i++) {{
    String p = parts[i].trim();
    if (p.length() == 0) continue;
    int eq = p.indexOf('=');
    if (eq <= 0) return "Not a layout code - paste the whole code from /skyyhud export (Coords=1:tl:8:8:100:1;Zone=...).";
    String id = p.substring(0, eq).trim();
    if (!knownId(id)) return {PKG}.Widgets.cut(id, 20) + " is not a SkyyHud widget - the widgets are " + idList() + ".";
    if (!seen.add(id)) return id + " is in the code twice.";
    if ({PKG}.WLayout.parse(p.substring(eq + 1), null) == null) return "The " + id + " part is not valid - use a code from /skyyhud export.";
    n++;
  }}
  if (n == 0) return "Not a layout code - paste the whole code from /skyyhud export.";
  return null;
}}""", hcfg))
hcfg.addMethod(CtNewMethod.make("""
public static java.util.HashMap layoutMap() {
  String src = DEFAULT_LAYOUT;
  if (src == null || src.trim().length() == 0) return null;
  Object[] p = PARSED;
  if (p != null && src.equals(p[0])) return (java.util.HashMap) p[1];
  java.util.HashMap m = parseCode(src);
  PARSED = new Object[] { src, m };
  return m;
}""", hcfg))
hcfg.addMethod(CtNewMethod.make("""
public static boolean hasDefault() {
  java.util.HashMap m = layoutMap();
  return m != null && m.size() > 0;
}""", hcfg))
# the kit's check= hook of hud.defaultLayout: static String (key, canonical value) -> null = fine, text = refuse with that reason
hcfg.addMethod(CtNewMethod.make("""
public static String checkLayout(String key, String value) {
  return codeError(value);
}""", hcfg))
# the layout a player starts with for one widget: the server default's entry (built-in box size, kept on screen) or the built-in one;
# with no default code this returns exactly Widgets.def(id), so 0.3.9 behaviour is unchanged until an admin sets one
wid.addMethod(CtNewMethod.make(f"""
public static {PKG}.WLayout start(String id) {{
  {PKG}.WLayout d = def(id);
  try {{
    java.util.HashMap m = {PKG}.HudCfg.layoutMap();
    Object s = m == null ? null : m.get(id);
    if (s == null) return d;
    {PKG}.WLayout w = {PKG}.WLayout.parse((String) s, d);
    if (w == null || w == d) return d;
    clampToScreen(w);
    return w;
  }} catch (Throwable t) {{ return d; }}
}}""", wid))

# the admin config registry (research/Server-Setup-Spec.md 4.8): Server Setup -> HUD
HUD_CFG_CATS = [("hud", "HUD")]
HUD_CFG_ROWS = [  # (key, label, cat, type, default, min, max, opts, unit, flags, help, binding) - tools/CONFIG-CONTRACT.md
    ("hud.defaultLayout", "Default HUD layout", "hud", "text", "", "", "2000", "", "", "new",
     "Code from /skyyhud export. New players, and anyone who never edited their HUD, start with it.",
     "field:HudCfg.DEFAULT_LAYOUT@config.properties:defaultLayout;check=HudCfg.checkLayout"),
    ("hud.useMine", "Use my layout as the default", "hud", "action", "", "", "", "Use my layout", "", "new",
     "Copies your own current HUD layout into Default HUD layout (asks first). Undo it in Changes.",
     "action:HudCfg.useMine;check=HudCfg.checkUse"),
    ("hud.editor", "HUD editor", "hud", "link", "", "", "", "skyyhud", "", "",
     "Opens your own HUD editor: set the look up there, then press Use my layout above.", ""),
]
kit = CFG.emit(pool, PKG, MOD="SkyyHud", TITLE="HUD", VERSION=VERSION, NODE=HUD_NODE, CATS=HUD_CFG_CATS, ROWS=HUD_CFG_ROWS,
               FILES=["Skyy_SkyyHud/config.properties"],
               NOTE="Empty Default HUD layout = the built-in one. A player's own saved layout always wins.",
               RELOAD=None, KEEP=20, DEFAULTS={"config.properties": CONFIG_TEXT})

# ================= LayoutStore =================
''')

# ---------------- LayoutStore: the server default where the built-in default applied (no file, missing widget, reset) ----------------
rep('''        {PKG}.WLayout d = {PKG}.Widgets.def(ids[i]);
        m.put(ids[i], v == null ? d : {PKG}.WLayout.parse(v, d));''', '''        {PKG}.WLayout d = {PKG}.Widgets.start(ids[i]);
        m.put(ids[i], v == null ? d : {PKG}.WLayout.parse(v, d));''')
rep('''  for (int i = 0; i < ids.length; i++) if (!m.containsKey(ids[i])) m.put(ids[i], {PKG}.Widgets.def(ids[i]));''',
    '''  for (int i = 0; i < ids.length; i++) if (!m.containsKey(ids[i])) m.put(ids[i], {PKG}.Widgets.start(ids[i]));''')
rep('''  for (int i = 0; i < ids.length; i++) m.put(ids[i], {PKG}.Widgets.def(ids[i]));
  save(u);''', '''  for (int i = 0; i < ids.length; i++) m.put(ids[i], {PKG}.Widgets.start(ids[i]));
  save(u);''')

# ---------------- HudCfg part B (after LayoutStore: load writes with atomicWrite, the action exports the admin's layout) ----------------
rep('''# ================= HudMain =================
''', r'''# ================= HudCfg part B (0.3.10) =================
hcfg.addMethod(CtNewMethod.make(f"""
public static void writeDefaults() {{
  try {{
    if (FILE == null || java.nio.file.Files.exists(FILE, new java.nio.file.LinkOption[0])) return;
    {PKG}.LayoutStore.atomicWrite(FILE, DEFAULT_TEXT.getBytes("ISO-8859-1"));
    info("wrote " + FILE + " (server default HUD layout: built-in)");
  }} catch (Throwable t) {{ warn("could not write the default config.properties: " + t); }}
}}""", hcfg))
# the mod's own loader (setup(), before CfgPub.start): the field holds exactly the trimmed file text, so the kit's start check agrees
hcfg.addMethod(CtNewMethod.make("""
public static String load() {
  writeDefaults();
  String v = "";
  try {
    if (FILE != null && java.nio.file.Files.exists(FILE, new java.nio.file.LinkOption[0])) {
      java.util.Properties p = new java.util.Properties();
      java.io.InputStream in = java.nio.file.Files.newInputStream(FILE, new java.nio.file.OpenOption[0]);
      try { p.load(in); } finally { in.close(); }
      String s = p.getProperty("defaultLayout");
      if (s != null) v = s.trim();
    }
  } catch (Throwable t) { warn("config.properties could not be read - new players get the built-in layout: " + t); v = ""; }
  DEFAULT_LAYOUT = v;
  String e = codeError(v);
  if (e != null) warn("config.properties defaultLayout: " + e + " Only its valid parts are used.");
  java.util.HashMap m = layoutMap();
  if (m == null || m.size() == 0) return "default layout: built-in";
  return "default layout: server code (" + m.size() + " widgets)";
}""", hcfg))
# the action's check= hook (key, null): "?question" = the kit asks before running it (no danger flag, so no red CONFIRM button)
hcfg.addMethod(CtNewMethod.make("""
public static String checkUse(String key, String value) {
  return "?Make your current HUD layout the server default? New players start with it; players who never changed their HUD get it at their next join.";
}""", hcfg))
# one path for the action (via=menu) and /skyyhud default use (via=command): the kit's set = validated, logged, versioned, undoable
hcfg.addMethod(CtNewMethod.make(f"""
public static Object[] setDefault(String code, java.util.UUID who, String name, String via) {{
  String c = code == null ? "" : code.trim();
  String before = {PKG}.CfgFn.cmdGet("hud.defaultLayout");
  if (before != null && before.equals(c)) return new Object[] {{ "ok", c, "The default HUD layout is already your layout." }};
  Object[] r = {PKG}.CfgFn.set("hud.defaultLayout", c, who, name, "yes", via);
  if (r == null || r.length < 3) return new Object[] {{ "error", null, "internal error - see the server log" }};
  if ("ok".equals(r[0])) return new Object[] {{ "ok", r[1], "Done - your HUD layout is the server default now: new players start with it." }};
  return r;
}}""", hcfg))
# action:HudCfg.useMine - static Object[] (UUID who, String name) -> R; runs outside every kit lock (CONFIG-CONTRACT guarantee 6)
hcfg.addMethod(CtNewMethod.make(f"""
public static Object[] useMine(java.util.UUID who, String name) {{
  if (who == null) return new Object[] {{ "bad", null, "Only a player can do this - it copies their own HUD layout." }};
  String code;
  try {{ code = {PKG}.LayoutStore.export(who); }}
  catch (Throwable t) {{ warn("could not read the HUD layout of " + who + ": " + t); return new Object[] {{ "error", null, "Could not read your HUD layout - see the server log." }}; }}
  return setDefault(code, who, name, "menu");
}}""", hcfg))

# ================= HudMain =================
''')

# ---------------- /skyyhud reset says where it put the player ----------------
rep('''    pr.sendMessage({MSG}.raw("[SkyyHud] layout reset to defaults"));''',
    '''    pr.sendMessage({MSG}.raw({PKG}.HudCfg.hasDefault() ? "[SkyyHud] layout reset to this server's default layout" : "[SkyyHud] layout reset to defaults"));''')

# ---------------- the editor's "< Server Setup" button (the way back after Server Setup -> HUD -> HUD editor) ----------------
# The SkyyRanks 0.1 RankEditorPage pattern: shown only when /modconfig exists (SkyyMenu 0.3+) - and, because every player uses this
# editor, only to a player who may open Server Setup (skyymenu.modconfig). Everyone else gets the 0.3.9 page unchanged (same footer
# widths, no extra element). The click runs /modconfig hud: Server Setup -> HUD replaces this page directly (no close first).
rep('''page.addField(CtField.make("public java.util.HashMap pm;", page))
page.addConstructor(CtNewConstructor.make(f"""
public EditorPage({PR} pr, {PKG}.SkyyHudPlugin plugin) {{
  super(pr, {LIFE}.CanDismiss);
  this.plugin = plugin;
  this.sel = null;
  this.info = "";
}}""", page))''', '''page.addField(CtField.make("public java.util.HashMap pm;", page))
# 0.3.10: true = draw "< Server Setup" in the footer (decided once per page: /modconfig exists and this player may open it)
page.addField(CtField.make("public boolean setupBtn;", page))
page.addConstructor(CtNewConstructor.make(f"""
public EditorPage({PR} pr, {PKG}.SkyyHudPlugin plugin) {{
  super(pr, {LIFE}.CanDismiss);
  this.plugin = plugin;
  this.sel = null;
  this.info = "";
  this.setupBtn = false;
  try {{ this.setupBtn = pr.hasPermission("skyymenu.modconfig") && {CMGR}.get().resolveCommand("modconfig") != null; }} catch (Throwable t) {{ this.setupBtn = false; }}
}}""", page))''')
rep(r'''  b.appendInline("#SkyyEFoot", "Label {{ Anchor: (Width: 1100, Height: 26); Text: \\"" + (this.info == null ? "" : this.info.replace('\\"', ' ')) + "   /skyyhud export | import | reset | profile save|load|list <name>\\"; Style: (FontSize: 10, TextColor: #6f8498, VerticalAlignment: Center); }}");
  b.appendInline("#SkyyEFoot", "TextButton #SkyyEWidgets {{ Anchor: (Width: 150, Height: 26); Text: \\"Widgets / Settings\\"; " + bs + " }}");
  ev.addEventBinding({BT}.Activating, "#SkyyEWidgets", {EVD}.of("a", "widgets"));
}}""", page))''', r'''  b.appendInline("#SkyyEFoot", "Label {{ Anchor: (Width: " + (this.setupBtn ? 946 : 1100) + ", Height: 26); Text: \\"" + (this.info == null ? "" : this.info.replace('\\"', ' ')) + "   /skyyhud export | import | reset | profile save|load|list <name>\\"; Style: (FontSize: 10, TextColor: #6f8498, VerticalAlignment: Center); }}");
  if (this.setupBtn) {{
    b.appendInline("#SkyyEFoot", "TextButton #SkyyESetup {{ Anchor: (Width: 150, Height: 26); Text: \\"< Server Setup\\"; " + bs + " }}");
    b.appendInline("#SkyyEFoot", "Label {{ Anchor: (Width: 4, Height: 26); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyyESetup", {EVD}.of("a", "setup"));
  }}
  b.appendInline("#SkyyEFoot", "TextButton #SkyyEWidgets {{ Anchor: (Width: 150, Height: 26); Text: \\"Widgets / Settings\\"; " + bs + " }}");
  ev.addEventBinding({BT}.Activating, "#SkyyEWidgets", {EVD}.of("a", "widgets"));
}}""", page))
# 0.3.10: Server Setup -> HUD replaces this page directly (no close first); the node is checked again, /modconfig checks it too
page.addMethod(CtNewMethod.make(f"""
public void openSetup() {{
  try {{
    if (!this.playerRef.hasPermission("skyymenu.modconfig") || {CMGR}.get().resolveCommand("modconfig") == null) {{
      this.setupBtn = false; this.info = "Server Setup is not available to you"; rebuild(); return;
    }}
    {CMGR}.get().handleCommand(this.playerRef, "modconfig hud");
  }} catch (Throwable t) {{
    {PKG}.HudCfg.warn("could not open Server Setup from the HUD editor: " + t);
    this.info = "Server Setup could not be opened (SkyyMenu 0.3 needed)"; rebuild();
  }}
}}""", page))''')
rep(r'''    if (data.indexOf("\\"dragcancel\\"") >= 0) return;
    if (data.indexOf("\\"widgets\\"") >= 0) {{''', r'''    if (data.indexOf("\\"dragcancel\\"") >= 0) return;
    if (data.indexOf("\\"setup\\"") >= 0) {{ openSetup(); return; }}
    if (data.indexOf("\\"widgets\\"") >= 0) {{''')

# ---------------- admin subcommands /skyyhud default [use | clear] (constructed before HudCmd's constructor adds them) ----------------
rep('''cmd.addConstructor(CtNewConstructor.make(f"""
public HudCmd({PKG}.SkyyHudPlugin p) {{''', r'''# 0.3.10 admin: /skyyhud default [use | clear]. Admin SUB-commands under the Adventurer command /skyyhud: requirePermission AND
# setPermissionGroups(new String[0]) - without the empty list the engine copies the parent's hytale:Adventurer group onto them and
# hands every player skyyhud.admin (tools/ci/lint.py perm_group_leaks). execute() re-checks the node (the /collections reload pattern).
# Writes go through the config kit (via=command): validated, logged, versioned - the same path as Server Setup -> HUD.
cduse.addField(CtField.make(f"public {PKG}.SkyyHudPlugin plugin;", cduse))
cduse.addConstructor(CtNewConstructor.make(f"""
public HudDefaultUseCmd({PKG}.SkyyHudPlugin p) {{
  super("use", "Admin: make your current HUD layout the default for new players");
  this.plugin = p;
  requirePermission("{HUD_NODE}");
  setPermissionGroups(new String[0]);
}}""", cduse))
cduse.addMethod(CtNewMethod.make(f"""
protected void execute({CTX} ctx, {ST} store, {REF} ref, {PR} pr, {WLD} world) {{
  try {{
    if (!pr.hasPermission("{HUD_NODE}")) {{ pr.sendMessage({MSG}.raw("[SkyyHud] no permission ({HUD_NODE})")); return; }}
    java.util.UUID u = pr.getUuid();
    Object[] r = {PKG}.HudCfg.setDefault({PKG}.LayoutStore.export(u), u, pr.getUsername(), "command");
    pr.sendMessage({MSG}.raw("[SkyyHud] " + String.valueOf(r[2])));
  }} catch (Throwable t) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] error: " + t));
  }}
}}""", cduse))
cdclr.addField(CtField.make(f"public {PKG}.SkyyHudPlugin plugin;", cdclr))
cdclr.addConstructor(CtNewConstructor.make(f"""
public HudDefaultClearCmd({PKG}.SkyyHudPlugin p) {{
  super("clear", "Admin: new players start with the built-in HUD layout again");
  this.plugin = p;
  requirePermission("{HUD_NODE}");
  setPermissionGroups(new String[0]);
}}""", cdclr))
cdclr.addMethod(CtNewMethod.make(f"""
protected void execute({CTX} ctx, {ST} store, {REF} ref, {PR} pr, {WLD} world) {{
  try {{
    if (!pr.hasPermission("{HUD_NODE}")) {{ pr.sendMessage({MSG}.raw("[SkyyHud] no permission ({HUD_NODE})")); return; }}
    String before = {PKG}.CfgFn.cmdGet("hud.defaultLayout");
    if (before != null && before.length() == 0) {{ pr.sendMessage({MSG}.raw("[SkyyHud] new players already start with the built-in layout.")); return; }}
    Object[] r = {PKG}.CfgFn.set("hud.defaultLayout", (String) null, pr.getUuid(), pr.getUsername(), "yes", "command");
    if (r != null && r.length > 2 && "ok".equals(r[0])) pr.sendMessage({MSG}.raw("[SkyyHud] default layout cleared - new players start with the built-in layout again."));
    else pr.sendMessage({MSG}.raw("[SkyyHud] " + (r == null || r.length < 3 ? "internal error - see the server log" : String.valueOf(r[2]))));
  }} catch (Throwable t) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] error: " + t));
  }}
}}""", cdclr))
cdef.addField(CtField.make(f"public {PKG}.SkyyHudPlugin plugin;", cdef))
cdef.addConstructor(CtNewConstructor.make(f"""
public HudDefaultCmd({PKG}.SkyyHudPlugin p) {{
  super("default", "Admin: the HUD layout new players start with (use | clear)");
  this.plugin = p;
  requirePermission("{HUD_NODE}");
  setPermissionGroups(new String[0]);
  addSubCommand(new {PKG}.HudDefaultUseCmd(p));
  addSubCommand(new {PKG}.HudDefaultClearCmd(p));
}}""", cdef))
cdef.addMethod(CtNewMethod.make(f"""
protected void execute({CTX} ctx, {ST} store, {REF} ref, {PR} pr, {WLD} world) {{
  try {{
    if (!pr.hasPermission("{HUD_NODE}")) {{ pr.sendMessage({MSG}.raw("[SkyyHud] no permission ({HUD_NODE})")); return; }}
    java.util.HashMap m = {PKG}.HudCfg.layoutMap();
    String what = (m == null || m.size() == 0) ? "the built-in layout" : "the server's layout code (" + m.size() + " widgets)";
    pr.sendMessage({MSG}.raw("[SkyyHud] New players start with " + what + ". /skyyhud default use = your current layout becomes the default, /skyyhud default clear = back to the built-in one. Also: SkyWynn Menu -> Server Setup -> HUD."));
  }} catch (Throwable t) {{
    pr.sendMessage({MSG}.raw("[SkyyHud] error: " + t));
  }}
}}""", cdef))

cmd.addConstructor(CtNewConstructor.make(f"""
public HudCmd({PKG}.SkyyHudPlugin p) {{''')
rep('''  addSubCommand(new {PKG}.HudProfileCmd(p));
}}""", cmd))''', '''  addSubCommand(new {PKG}.HudProfileCmd(p));
  addSubCommand(new {PKG}.HudDefaultCmd(p));
}}""", cmd))''')

# ---------------- plugin lifecycle: load the config after the layout paths, publish the kit at the END of setup ----------------
rep('''  {PKG}.Widgets.HUBFILE = getDataDirectory().resolveSibling("Skyy_SkyyIslands").resolve("hub.properties");
  getEventRegistry().registerGlobal({PRE}.class, new {PKG}.SkyyHudReady(this));
  getCommandRegistry().registerCommand(new {PKG}.HudCmd(this));
  this.ticker = {HSV}.SCHEDULED_EXECUTOR.scheduleAtFixedRate(new {PKG}.TickTask(this), 1L, 1L, java.util.concurrent.TimeUnit.SECONDS);
  getLogger().at(java.util.logging.Level.INFO).log("[SkyyHud] {VERSION} ready - /skyyhud (alias /shud)");
}}""", pl))''', '''  {PKG}.Widgets.HUBFILE = getDataDirectory().resolveSibling("Skyy_SkyyIslands").resolve("hub.properties");
  {PKG}.HudCfg.LOG = getLogger();
  {PKG}.HudCfg.FILE = getDataDirectory().resolveSibling("Skyy_SkyyHud").resolve("config.properties");
  String cs = {PKG}.HudCfg.load();
  getEventRegistry().registerGlobal({PRE}.class, new {PKG}.SkyyHudReady(this));
  getCommandRegistry().registerCommand(new {PKG}.HudCmd(this));
  this.ticker = {HSV}.SCHEDULED_EXECUTOR.scheduleAtFixedRate(new {PKG}.TickTask(this), 1L, 1L, java.util.concurrent.TimeUnit.SECONDS);
  // 0.3.10: config:def:SkyyHud + config:fn:SkyyHud, at the END of setup() after the config load (Server-Setup-Spec section 7)
  {PKG}.CfgPub.start(getDataDirectory().getParent(), getLogger());
  getLogger().at(java.util.logging.Level.INFO).log("[SkyyHud] {VERSION} ready - /skyyhud (alias /shud); " + cs + " (admins: /skyyhud default, Server Setup -> HUD)");
}}""", pl))''')
rep('''pl.addMethod(CtNewMethod.make("""
protected void shutdown() {
  try { if (this.ticker != null) this.ticker.cancel(false); } catch (Throwable t) { }
  this.huds.clear();
  super.shutdown();
}""", pl))''', '''pl.addMethod(CtNewMethod.make(f"""
protected void shutdown() {{
  try {{ if (this.ticker != null) this.ticker.cancel(false); }} catch (Throwable t) {{ }}
  this.huds.clear();
  try {{ {PKG}.CfgPub.shutdown(); }} catch (Throwable t) {{ {PKG}.HudCfg.warn("config kit flush at shutdown failed: " + t); }}
  super.shutdown();
}}""", pl))''')

# ---------------- write the new classes + the kit's seven ----------------
rep('''for c in (wl, lst, wid, hudc, page, sett, wpg, cmd, cexp, cimp, crst, cprv, cpro, cpls, cpsv, cpld, cpdl, tick, att, rdy, pl):
    c.writeFile(OUT)
print("classes written")''', '''ALL = (wl, lst, wid, hudc, page, sett, wpg, cmd, cexp, cimp, crst, cprv, cpro, cpls, cpsv, cpld, cpdl, cdef, cduse, cdclr, hcfg, tick, att, rdy, pl)
for c in ALL:
    c.writeFile(OUT)
kit.write(OUT)     # deferred kit checks (check= / action: hooks exist with the right signatures), then the 7 Cfg* classes
print("classes written:", len(ALL) + len(kit.classes), "(%d kit)" % len(kit.classes))''')
rep('''/skyyhud editor + layout codes. Zero dependencies."''',
    '''/skyyhud editor + layout codes, server default layout for new players (in-game admin config). Zero dependencies."''')

# ---------------- self-checks ----------------
assert s.count("{PKG}.Widgets.start(ids[i])") == 3, "LayoutStore must use Widgets.start in get (2x) and reset"
assert s.count("{PKG}.Widgets.def(id)") == 1 and "l.bw = dd.bw; l.bh = dd.bh;" in s, "importCode keeps the built-in box size"
assert s.count('requirePermission("{HUD_NODE}");\n  setPermissionGroups(new String[0]);') == 3, "every admin subcommand clears its groups"
assert s.index("{PKG}.CfgPub.start(") > s.index("{PKG}.HudCfg.load()"), "publish after the config load"
assert s.index("kit = CFG.emit(") < s.index("# ================= LayoutStore ================="), "emit before the classes that call the kit"
assert s.index("public static Object[] setDefault(") > s.index("kit = CFG.emit("), "setDefault calls CfgFn after emit"
assert s.count("#SkyyESetup") == 2 and "this.setupBtn = pr.hasPermission(\"skyymenu.modconfig\") && " in s, "editor way back, admins only"
assert "catch (Throwable t) {{ }}\n  super.shutdown();" not in s, "a failed kit flush at shutdown is logged"
assert "--deploy" in s   # the old deploy block stays as it was (never used: tools/deploy_set.py is the only deploy path)

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
