"""Derive SkyyHud/build_skyyhud_0.3.9.py from the LIVE 0.3.8 (0.3.8 is left untouched; line endings preserved).
0.3.9 (Skyy's beta screenshots, 2026-09-24 evening: "Party widget drawn misaligned until clicked/moved in the editor"):
Party / Guild widget alignment fix only - no new features, no other widget behaviour changed except the shared Snap to / anchor
rendering (the same bug class: a non-corner anchor the HUD placed differently from the editor until a drag) and the layout save
(bounded retry + log, the codebase's Windows-safe write).
  - flat markup: every line label (and glow copy) is a direct child of the widget Group with absolute anchors (the one-line
    widgets' structure); Background on the widget Group; no anonymous per-line wrapper Groups, no separate background Group
  - the widget Group is sized to the rows actually drawn (Widgets.bodyH), and every layout calculation that must match what the
    player sees (HUD anchor, editor preview, outline, drag handle, drag, Snap to) uses that height (the ...H methods); clamps keep
    the maximum box
  - Settings "Snap to" stores the pressed point as the anchor (8 px from an edge, 0 = true centre on a centred axis); the HUD
    never gets Horizontal:/Vertical: margins - anchorSrcH sends a centred axis as the nearest-edge margin computed from the DRAWN
    height at every send (= screenPosH, where the editor draws it), so a Party / Guild snapped to L / C / R stays centred when
    rows are added or removed; load / import keep the anchor (no corner conversion that would freeze a centred widget's edge)
  - LayoutStore.save / profileSave: tmp + fsync + atomic rename with 5 x 20 ms retries (SkyyProfiles' atomicWrite), failure logged
  - HudMain sends the whole HUD once more 1.5 s after a Party / Guild widget appears or changes shape (the editor-move re-send)
  - round cross-check: the Party widget's "Your Island" also matches bridge island:<uuid> (SkyyIslands 0.5 co-op / reset worlds)
To regenerate, delete SkyyHud/build_skyyhud_0.3.9.py first (the script refuses to overwrite it).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.8.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.9.py")
assert not os.path.exists(dst), "refusing to overwrite " + dst
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


def rep_block(start, end, new):
    """replace s[start marker .. end marker) (end marker kept); both markers must be unique"""
    global s
    assert s.count(start) == 1, "start marker count %d: %s" % (s.count(start), start[:90])
    assert s.count(end) == 1, "end marker count %d: %s" % (s.count(end), end[:90])
    i = s.index(start)
    j = s.index(end)
    assert j > i, "end marker before start marker: " + end[:90]
    s = s[:i] + new + s[j:]


# ---------------- docstring + version ----------------
rep('''"""SkyyHud 0.3.8 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.8.py            -> SkyyHud/SkyyHud-0.3.8.jar
       python build_skyyhud_0.3.8.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.8 SkyyHud" in the HUD mod world
''', '''"""SkyyHud 0.3.9 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.9.py            -> SkyyHud/SkyyHud-0.3.9.jar
       python build_skyyhud_0.3.9.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.9 SkyyHud" in the HUD mod world
0.3.9 (generated by tools/hud_0_3_9_patch.py from 0.3.8): Party / Guild widget alignment fix (Skyy's beta screenshots 2026-09-24:
the Party widget was drawn misaligned - its lines offset from its box - until it was clicked/moved once in the editor).
  What differed between the first render and the post-move render in 0.3.8 (an editor move only changes anchor/dx/dy and sends
  the whole HUD again; the row markup itself is the same both times):
  - Box vs lines: the widget Group was sized for the MAXIMUM rows (Party 340 x 116 = 5 members, Guild 260 x 94 = 2 name rows)
    while only the rows in use were drawn (a separate background Group covered just those). Anchor edge, corner choice, clamp,
    drag handle cell, selection outline and Snap to all used the big box, so the drawn lines never lined up with the box the
    editor works with: a bottom-anchored widget floated (unused rows) above its edge, the handle sat below the middle of the
    visible rows, the outline enclosed empty space, a middle snap was off-centre by half the unused rows.
  - Snap to T / L / C / R / B (Settings page) stored a non-corner anchor with dx = dy = 8. The HUD sends those as
    Horizontal: / Vertical: MARGINS next to Width / Height, which the client does not place where the editor draws the widget
    (editor = screenPos maths). A drag turns the anchor into a corner (cornerAt) and only then did HUD and editor agree - the
    "until it is moved once" part. /skyyhud import kept such anchors too (only LayoutStore.get converted them, at load).
  - Structure: each row was an anonymous wrapper Group (own anchor) holding its label, plus the separate background Group -
    a nesting no other SkyyHud element uses (one-line widgets: labels + Background directly on the widget Group). The rows
    were first created by a tick re-show that was never followed by a second full send, while every editor move re-sends.
  0.3.9:
  - FLAT markup: every line label (and its glow copies) is a DIRECT child of the widget Group with absolute Left/Top/Width/Height
    (the one-line widgets' proven structure); Background sits on the widget Group itself. Every label keeps its 0.3.8 pixel
    position inside the widget; element ids are unchanged (#SkyyW<Party|Guild><T|N0-4|S0-4|L|O|A|B>Txt / G0..G7, #SkyyEPv...).
  - The widget Group IS the drawn box: Height = Widgets.bodyH(id, model, size) = the rows in use (100%: Party 3+20+18n+3,
    Guild 3+20+36+16r+3; floored exactly like the rows are placed). HUD anchor, editor preview, selection outline, drag-handle
    cell, drag and Snap to use this height (Widgets.screenPosH / cornerAtH / cellOfH / moveByCellsH / anchorSrcH). EditorPage
    computes the view model (real lines, or the sample while not in a party / guild) and its height once per build (prepView)
    and uses them for the handles, previews and the next click/drag. Clamping (load, import, Size, arrows, Settings) keeps the
    MAXIMUM box (Widgets.hMax), so a widget stays on screen even with a full party. A bottom-anchored Party / Guild now sits on
    its edge and grows upward when members join; a top-anchored one grows downward. The editor preview of a bottom-anchored
    multi-line widget is placed by its bottom edge, a vertically centred one by its centre (no 2/3 rounding drift).
  - Snap to: Widgets.snapTo stores the pressed point itself as the anchor with 8 px on an edge axis and 0 on a centred axis (T/B:
    horizontal centre, L/R: vertical centre, C: both), i.e. the exact spot 8 px from the screen edges / the true centre. The HUD
    never sends Horizontal: / Vertical: margins any more: anchorSrcH turns a centred axis into the nearest-edge margin computed
    from the height being SENT (Party / Guild: the drawn rows) with the screenPosH maths, at every send - so the HUD always sits
    where the editor draws the widget, and a Party / Guild snapped to L / C / R stays vertically centred when members join or
    leave or Online names is toggled (the first 0.3.9 draft froze the snap into a corner + offset: the widget then grew from a
    fixed bottom edge and drifted off centre by half of every height change). Corner anchors render exactly as before. A drag
    still re-picks the nearest corner (moveByCellsH -> cornerAtH); arrows / Size / clamps keep a centred anchor centred.
    LayoutStore.get and /skyyhud import / profile load keep the stored anchor (no load-time corner conversion - with the
    render-time margins it is not needed, and it would freeze a centred Party / Guild to its maximum-box edge). The Snap to
    button of the current anchor is lit (as in 0.3.8).
  - Layout saves (LayoutStore.save, profileSave): SkyyProfiles' atomicWrite (tmp + fsync + ATOMIC_MOVE, 5 x 20 ms retries on a
    Windows FileSystemException); a save that still fails is logged ("[SkyyHud] layout save failed ...") instead of dropped
    silently.
  - Confirm send: whenever a Party / Guild widget appears or changes shape (join, leave, world switch, grey line, names row),
    HudMain.build() arms confirmAt and the 1 s tick sends the whole HUD once more 1.5-2.5 s later - the same full re-send an
    editor move does. One extra packet per shape change, never periodic; a pending shape re-show takes precedence.
  - Unchanged: layout file / export code / profile formats, the bridge contract, commands, the eight one-line widgets' markup.
  - Not verified in game (no client here): which of the three causes Skyy's screenshots showed, and the flat markup / confirm send
    on the real client. Offline checks: every label + glow copy keeps its 0.3.8 widget-relative rect (Party / Guild, glow on/off),
    widget height == drawn rows at 50-200%, drag round trips, -Xverify. Review round (jpype against the built jar, -Xverify:all):
    9 snap points x 7 sizes (50-200 %, incl. 130) x every row count (Party 0-5 members, Guild 0-2 name rows) + two one-line
    widgets = 693 cases: the sent margins land on the exact snap spot and on screenPosH (HUD == editor), no Horizontal: /
    Vertical: margin, clamp idempotent, ser/parse keeps the anchor, a drag re-picks a corner; corner strings identical to 0.3.8;
    save -> get / profileSave -> profileLoad / export -> import keep a centred anchor, no .tmp left; a save whose target is held
    open succeeds on a retry once released (~65 ms) and gives up without throwing after 5 tries (~110 ms, old file kept).
''')
rep('VERSION = "0.3.8"', 'VERSION = "0.3.9"')
rep('''# 0.3.8 multi-line widgets: default position (left middle, guild under party; corner anchors only - LayoutStore.get turns any
# other anchor into a corner) and base box size''', '''# 0.3.8 multi-line widgets: default position (left middle, guild under party; corner anchors - 0.3.9: a centred anchor from
# Snap to is kept and resolved at every send by Widgets.anchorSrcH) and base box size''')

# ---------------- Widgets.anchorSrc -> anchorSrcH (explicit pixel height, edge margins only) + the old signature ----------------
rep_block('''
wid.addMethod(CtNewMethod.make(f"""
public static String anchorSrc({PKG}.WLayout l) {{
  int w = l.bw * l.scale / 100; int h = l.bh * l.scale / 100;''', '# 0.3.7 text style + fake glow (see the docstring)', '''
# 0.3.9: the widget Group's Anchor for a box of w x h (h = the height being sent: one-line hMax, Party / Guild the drawn rows).
# Corner anchors are sent as before (Top|Bottom + Left|Right). A CENTRED axis (anchor t / b / c horizontally, l / r / c vertically,
# from Settings "Snap to") is never sent as a Horizontal: / Vertical: margin (the client does not place those where the editor
# draws the widget): it is resolved with the screenPosH maths for THIS h and sent as the nearest-edge margin (the cornerAtH
# tie-break), so the HUD sits exactly where the editor draws it and a snapped Party / Guild stays centred as its height changes.
wid.addMethod(CtNewMethod.make(f"""
public static String anchorSrcH({PKG}.WLayout l, int h) {{
  int w = l.bw * l.scale / 100;
  String a = l.anchor;
  String va = "Top"; int my = l.dy;
  if (a.equals("tl") || a.equals("t") || a.equals("tr")) va = "Top";
  else if (a.equals("bl") || a.equals("b") || a.equals("br")) va = "Bottom";
  else {{
    int y = 540 - h / 2 + l.dy;
    if (y + h / 2 < 540) {{ va = "Top"; my = y; }} else {{ va = "Bottom"; my = 1080 - h - y; }}
  }}
  String ha = "Left"; int mx = l.dx;
  if (a.equals("tl") || a.equals("l") || a.equals("bl")) ha = "Left";
  else if (a.equals("tr") || a.equals("r") || a.equals("br")) ha = "Right";
  else {{
    int x = 960 - w / 2 + l.dx;
    if (x + w / 2 < 960) {{ ha = "Left"; mx = x; }} else {{ ha = "Right"; mx = 1920 - w - x; }}
  }}
  return "(" + va + ": " + my + ", " + ha + ": " + mx + ", Width: " + w + ", Height: " + h + ")";
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String anchorSrc({PKG}.WLayout l) {{
  return anchorSrcH(l, l.bh * l.scale / 100);
}}""", wid))
''')

# ---------------- multi-line rendering: flat labels, content-sized widget Group ----------------
rep_block('# 0.3.8 multi-line rendering. styleA = styleSrc with a chosen alignment.', '''wid.addMethod(CtNewMethod.make(f"""
public static void setLines({UCB} b, String sel, int n, String[] pairs) {{''', r'''# 0.3.9 multi-line rendering (FLAT; see the 0.3.9 docstring). styleA = styleSrc with a chosen alignment. lineSrc = one text line
# whose line box is (x, y, w, h) in WIDGET coordinates: the 8 glow copies (0.3.7 offsets) and the real label are appended as DIRECT
# children of the widget Group with absolute anchors (the one-line widgets' structure - no wrapper Group); the real label sits in
# the line box inset by D on every side and each copy in the same inset box shifted by its offset (|offset| <= D, so never
# negative), which keeps Start/End aligned text glowing symmetrically. sc = effective size percent (HUD: layout scale; editor:
# scale x 2/3), minFs = smallest font (HUD 6, editor 5, as for the one-line widgets).
wid.addMethod(CtNewMethod.make(f"""
public static String styleA(int fs, {PKG}.WLayout l, String color, String align) {{
  return "Style: (FontSize: " + fs + ", RenderBold: " + (l.bold ? "true" : "false") + (l.ital ? ", RenderItalics: true" : "") + ", TextColor: " + color + ", HorizontalAlignment: " + align + ", VerticalAlignment: Center);";
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String lineSrc(String base, int x, int y, int w, int h, int fs, {PKG}.WLayout l, String color, String gcolor, String align) {{
  StringBuilder sb = new StringBuilder();
  int d = (fs * 3 + 12) / 24;
  if (d < 1) d = 1;
  int e = (d + 1) / 2;
  int iw = w - 2 * d; if (iw < 1) iw = 1;
  int ih = h - 2 * d; if (ih < 1) ih = 1;
  if (l.glow) {{
    int[] ox = new int[] {{ -d, d, 0, 0, -e, e, -e, e }};
    int[] oy = new int[] {{ 0, 0, -d, d, -e, -e, e, e }};
    String gs = styleA(fs, l, gcolor, align);
    for (int k = 0; k < 8; k++) {{
      sb.append("Label #").append(base).append("G").append(k).append(" {{ Anchor: (Left: ").append(x + d + ox[k]).append(", Top: ").append(y + d + oy[k]).append(", Width: ").append(iw).append(", Height: ").append(ih).append("); Text: \\"\\"; ").append(gs).append(" }} ");
    }}
  }}
  sb.append("Label #").append(base).append("Txt {{ Anchor: (Left: ").append(x + d).append(", Top: ").append(y + d).append(", Width: ").append(iw).append(", Height: ").append(ih).append("); Text: \\"\\"; ").append(styleA(fs, l, color, align)).append(" }} ");
  return sb.toString();
}}""", wid))
# rows actually drawn (Party: member lines 0..5, Guild: online-name rows 0..2) and the drawn content height at size sc: ONE formula
# with the same floored parts partyBody / guildBody place their lines with - used for the widget Group height, the editor preview
# and every layout calculation of a multi-line widget
wid.addMethod(CtNewMethod.make("""
public static int partyRows(String[] m) {
  if (m == null) return 0;
  int n = 0;
  for (int i = 0; i < 5 && 4 + 3 * i < m.length; i++) { if (m[2 + 3 * i] == null) break; n = i + 1; }
  return n;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static int guildRows(String[] m) {
  if (m == null || m.length < 6 || m[4] == null) return 0;
  return m[5] != null ? 2 : 1;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static int bodyH(String id, String[] m, int sc) {
  int tp = 3 * sc / 100; int th = 20 * sc / 100; int rh = 18 * sc / 100;
  if ("Party".equals(id)) return tp + th + partyRows(m) * rh + tp;
  int nh = 16 * sc / 100;
  return tp + th + 2 * rh + guildRows(m) * nh + tp;
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String partyBody(String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  int w = l.bw * sc / 100;
  int sp = 6 * sc / 100; int tp = 3 * sc / 100;
  int th = 20 * sc / 100; int rh = 18 * sc / 100; int nw = 128 * sc / 100;
  int fsT = 12 * sc / 100; if (fsT < minFs) fsT = minFs;
  int fsR = 11 * sc / 100; if (fsR < minFs) fsR = minFs;
  int n = partyRows(m);
  StringBuilder sb = new StringBuilder();
  String col = hexOf(l.col);
  String gcol = glowHex(l) + "(0.45)";
  sb.append(lineSrc(base + "T", sp, tp, w - 2 * sp, th, fsT, l, col, gcol, "Start"));
  for (int i = 0; i < n; i++) {{
    boolean grey = "1".equals(m[4 + 3 * i]);
    String c = grey ? GREY : col;
    String g = grey ? GREYG : gcol;
    int y = tp + th + i * rh;
    sb.append(lineSrc(base + "N" + i, sp, y, nw, rh, fsR, l, c, g, "Start"));
    sb.append(lineSrc(base + "S" + i, sp + nw, y, w - 2 * sp - nw, rh, fsR, l, c, g, "End"));
  }}
  return sb.toString();
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String guildBody(String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  int w = l.bw * sc / 100;
  int sp = 6 * sc / 100; int tp = 3 * sc / 100;
  int th = 20 * sc / 100; int rh = 18 * sc / 100; int nh = 16 * sc / 100;
  int fsT = 12 * sc / 100; if (fsT < minFs) fsT = minFs;
  int fsR = 11 * sc / 100; if (fsR < minFs) fsR = minFs;
  int fsN = 10 * sc / 100; if (fsN < minFs) fsN = minFs;
  int rows = guildRows(m);
  StringBuilder sb = new StringBuilder();
  String col = hexOf(l.col);
  String gcol = glowHex(l) + "(0.45)";
  int iw = w - 2 * sp;
  sb.append(lineSrc(base + "T", sp, tp, iw, th, fsT, l, col, gcol, "Start"));
  sb.append(lineSrc(base + "L", sp, tp + th, iw, rh, fsR, l, col, gcol, "Start"));
  sb.append(lineSrc(base + "O", sp, tp + th + rh, iw, rh, fsR, l, col, gcol, "Start"));
  if (rows > 0) sb.append(lineSrc(base + "A", sp, tp + th + 2 * rh, iw, nh, fsN, l, col, gcol, "Start"));
  if (rows > 1) sb.append(lineSrc(base + "B", sp, tp + th + 2 * rh + nh, iw, nh, fsN, l, col, gcol, "Start"));
  return sb.toString();
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String multiBody(String id, String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  if ("Party".equals(id)) return partyBody(base, l, sc, m, minFs);
  return guildBody(base, l, sc, m, minFs);
}}""", wid))
# the widget Group IS the drawn box: Height = bodyH (rows in use), Background on the Group itself like every one-line widget
wid.addMethod(CtNewMethod.make(f"""
public static String multiWidgetSrc(String id, {PKG}.WLayout l, String[] m) {{
  return "Group #SkyyW" + id + " {{ Anchor: " + anchorSrcH(l, bodyH(id, m, l.scale)) + "; " + (l.bg ? "Background: #0b1524(0.72); " : "") + multiBody(id, "SkyyW" + id, l, l.scale, m, 6) + " }}";
}}""", wid))
''')

# ---------------- layout maths with an explicit pixel height + Snap to + the editor's view model ----------------
rep_block('# screen position (top-left corner of the widget, 1080p) from a layout', 'SHORT = {', r'''# screen position (top-left corner of the widget, 1080p) from a layout. 0.3.9: the calculations take the widget's pixel HEIGHT h
# explicitly (the ...H methods). One-line widgets always use hMax (= bh x scale, the old maths). Party / Guild pass the drawn
# content height (bodyH of the model on screen) wherever the box has to match what the player sees: HUD anchor, editor preview /
# outline / drag handle / drag. clampToScreen keeps the maximum box, so a full party always fits on screen. (0.3.8's toCorner is
# gone: nothing converts a stored centred anchor any more - anchorSrcH resolves it at every send.)
wid.addMethod(CtNewMethod.make(f"""
public static int hMax({PKG}.WLayout l) {{
  return l.bh * l.scale / 100;
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int[] screenPosH({PKG}.WLayout l, int h) {{
  int w = l.bw * l.scale / 100;
  String a = l.anchor; int x; int y;
  if (a.equals("tl") || a.equals("l") || a.equals("bl")) x = l.dx;
  else if (a.equals("tr") || a.equals("r") || a.equals("br")) x = 1920 - w - l.dx;
  else x = 960 - w / 2 + l.dx;
  if (a.equals("tl") || a.equals("t") || a.equals("tr")) y = l.dy;
  else if (a.equals("bl") || a.equals("b") || a.equals("br")) y = 1080 - h - l.dy;
  else y = 540 - h / 2 + l.dy;
  return new int[] {{ x, y }};
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int[] screenPos({PKG}.WLayout l) {{
  return screenPosH(l, hMax(l));
}}""", wid))
# 0.3.4: exact inverse of screenPosH for the layout's current anchor (same h); the top-left is clamped so the box stays on screen
wid.addMethod(CtNewMethod.make(f"""
public static void setTopLeftH({PKG}.WLayout l, int x, int y, int h) {{
  int w = l.bw * l.scale / 100;
  if (x > 1920 - w) x = 1920 - w;
  if (x < 0) x = 0;
  if (y > 1080 - h) y = 1080 - h;
  if (y < 0) y = 0;
  String a = l.anchor;
  if (a.equals("tl") || a.equals("l") || a.equals("bl")) l.dx = x;
  else if (a.equals("tr") || a.equals("r") || a.equals("br")) l.dx = 1920 - w - x;
  else l.dx = x - (960 - w / 2);
  if (a.equals("tl") || a.equals("t") || a.equals("tr")) l.dy = y;
  else if (a.equals("bl") || a.equals("b") || a.equals("br")) l.dy = 1080 - h - y;
  else l.dy = y - (540 - h / 2);
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static void clampToScreen({PKG}.WLayout l) {{
  int h = hMax(l);
  int[] p = screenPosH(l, h);
  setTopLeftH(l, p[0], p[1], h);
}}""", wid))
# put the widget's top-left at (x, y) and anchor it to the nearest screen corner (judged by the centre of the w x h box)
wid.addMethod(CtNewMethod.make(f"""
public static void cornerAtH({PKG}.WLayout l, int x, int y, int h) {{
  int w = l.bw * l.scale / 100;
  if (x > 1920 - w) x = 1920 - w;
  if (x < 0) x = 0;
  if (y > 1080 - h) y = 1080 - h;
  if (y < 0) y = 0;
  boolean left = x + w / 2 < 960; boolean top = y + h / 2 < 540;
  l.anchor = top ? (left ? "tl" : "tr") : (left ? "bl" : "br");
  setTopLeftH(l, x, y, h);
}}""", wid))
# 0.3.4 canvas grid: 32 x 18 cells of 40 canvas px = 60 screen px; a widget's handle belongs in the cell under its centre
wid.addMethod(CtNewMethod.make(f"""
public static int cellOfH({PKG}.WLayout l, int h) {{
  int[] p = screenPosH(l, h);
  int cx = p[0] + (l.bw * l.scale / 100) / 2; int cy = p[1] + h / 2;
  int col = cx / 60; if (col < 0) col = 0; if (col > 31) col = 31;
  int row = cy / 60; if (row < 0) row = 0; if (row > 17) row = 17;
  return row * 32 + col;
}}""", wid))
# a drag from cell `from` to cell `to` moves the widget by that distance (keeps sub-cell offsets), nearest corner anchor re-picked
wid.addMethod(CtNewMethod.make(f"""
public static void moveByCellsH({PKG}.WLayout l, int from, int to, int h) {{
  int[] p = screenPosH(l, h);
  int mx = (to % 32 - from % 32) * 60; int my = (to / 32 - from / 32) * 60;
  cornerAtH(l, p[0] + mx, p[1] + my, h);
}}""", wid))
# 0.3.9 Settings "Snap to": the pressed point itself becomes the anchor, 8 px from the screen edge on an edge axis and 0 (the true
# centre) on a centred axis. The anchor is KEPT (not frozen into a corner + offset computed from the height at snap time): the
# screenPosH maths centre by the height of the moment, and anchorSrcH sends a centred axis as the nearest-edge margin for the
# height being sent - so a Party / Guild snapped to L / C / R stays vertically centred when rows come and go, and HUD + editor agree
wid.addMethod(CtNewMethod.make(f"""
public static void snapTo({PKG}.WLayout l, String a) {{
  l.anchor = a;
  l.dx = (a.equals("t") || a.equals("c") || a.equals("b")) ? 0 : 8;
  l.dy = (a.equals("l") || a.equals("c") || a.equals("r")) ? 0 : 8;
  clampToScreen(l);
}}""", wid))
# what the editor / Settings page show for a multi-line widget: the real lines, or the sample while not in a party / guild
wid.addMethod(CtNewMethod.make(f"""
public static String[] viewModel(String id, {PR} pr, boolean opt) {{
  String[] mm = null;
  try {{ mm = model(id, pr, opt); }} catch (Throwable t) {{ mm = null; }}
  if (!shown(mm)) mm = sample(id, pr, opt);
  return mm;
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int viewH(String id, {PKG}.WLayout l, {PR} pr) {{
  if (!multi(id)) return hMax(l);
  return bodyH(id, viewModel(id, pr, l.opt), l.scale);
}}""", wid))
''')

# ---------------- LayoutStore.get: keep the stored anchor (/skyyhud import + profile load already only clamp) ----------------
# A centred anchor (Snap to T / L / C / R / B) is resolved at every send by anchorSrcH / screenPosH with the height of the moment;
# 0.3.8's load-time toCorner used the MAXIMUM box, which froze a snapped Party / Guild to that box's edge after every restart.
rep('''    boolean corner = w.anchor.equals("tl") || w.anchor.equals("tr") || w.anchor.equals("bl") || w.anchor.equals("br");
    if (!corner) {PKG}.Widgets.toCorner(w);
    {PKG}.Widgets.clampToScreen(w);''', '''    {PKG}.Widgets.clampToScreen(w);''')

# ---------------- LayoutStore: Windows-safe layout writes (SkyyProfiles' atomicWrite), failures logged ----------------
# tmp + fsync + ATOMIC_MOVE (plain replace only where the file system cannot rename atomically); the rename is retried 5 x 20 ms on
# any FileSystemException (AccessDeniedException / a sharing violation from a virus scanner, indexer or backup tool briefly holding
# the file). 0.3.8 did one plain move and swallowed any failure, so a lost save silently reverted at the next restart.
rep('''lst.addMethod(CtNewMethod.make(f"""
public static void save(java.util.UUID u) {{''', '''lst.addMethod(CtNewMethod.make("""
public static void atomicWrite(java.nio.file.Path f, byte[] data) throws java.io.IOException {
  java.nio.file.Files.createDirectories(f.getParent(), new java.nio.file.attribute.FileAttribute[0]);
  java.nio.file.Path tmp = f.resolveSibling(f.getFileName().toString() + ".tmp");
  java.io.FileOutputStream out = new java.io.FileOutputStream(tmp.toFile());
  try {
    out.write(data);
    out.flush();
    out.getFD().sync();
  } finally { out.close(); }
  java.io.IOException last = null;
  for (int i = 0; i < 5; i++) {
    try {
      java.nio.file.Files.move(tmp, f, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.ATOMIC_MOVE, java.nio.file.StandardCopyOption.REPLACE_EXISTING });
      return;
    } catch (java.nio.file.AtomicMoveNotSupportedException e) {
      java.nio.file.Files.move(tmp, f, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.REPLACE_EXISTING });
      return;
    } catch (java.nio.file.FileSystemException e) {
      last = e;
    }
    try { Thread.sleep(20L); } catch (InterruptedException ie) { }
  }
  throw last;
}""", lst))
lst.addMethod(CtNewMethod.make(f"""
public static void save(java.util.UUID u) {{''')
rep('''    java.nio.file.Files.createDirectories(DIR, new java.nio.file.attribute.FileAttribute[0]);
    java.nio.file.Path tmp = DIR.resolve(u.toString() + ".properties.tmp");
    java.io.OutputStream out = java.nio.file.Files.newOutputStream(tmp, new java.nio.file.OpenOption[0]);
    try {{ p.store(out, "SkyyHud layout"); }} finally {{ out.close(); }}
    java.nio.file.Files.move(tmp, DIR.resolve(u.toString() + ".properties"), new java.nio.file.CopyOption[] {{ java.nio.file.StandardCopyOption.REPLACE_EXISTING }});
  }} catch (Throwable t) {{ }}''', '''    java.io.ByteArrayOutputStream bo = new java.io.ByteArrayOutputStream();
    p.store(bo, "SkyyHud layout");
    atomicWrite(DIR.resolve(u.toString() + ".properties"), bo.toByteArray());
  }} catch (Throwable t) {{ debug("layout save failed for " + u + " (the change is live but not saved): " + t); }}''')
rep('''    java.nio.file.Path d = profileDir(u);
    java.nio.file.Files.createDirectories(d, new java.nio.file.attribute.FileAttribute[0]);
    java.nio.file.Path tmp = d.resolve(n + ".txt.tmp");
    java.nio.file.Files.write(tmp, export(u).getBytes("UTF-8"), new java.nio.file.OpenOption[0]);
    java.nio.file.Files.move(tmp, d.resolve(n + ".txt"), new java.nio.file.CopyOption[] {{ java.nio.file.StandardCopyOption.REPLACE_EXISTING }});
    return true;
  }} catch (Throwable t) {{ return false; }}''', '''    atomicWrite(profileDir(u).resolve(n + ".txt"), export(u).getBytes("UTF-8"));
    return true;
  }} catch (Throwable t) {{ debug("layout profile save failed for " + u + ": " + t); return false; }}''')

# ---------------- HudMain: confirm send after a multi-line shape change ----------------
rep('hudc.addField(CtField.make("public long lastRe;", hudc))', '''hudc.addField(CtField.make("public long lastRe;", hudc))
# 0.3.9: time of the confirm send (0 = none) - armed by build() when a Party / Guild widget appears or changes shape
hudc.addField(CtField.make("public long confirmAt;", hudc))''')
rep('''  this.built.clear();
  this.shape.clear();
  this.models.clear();''', '''  java.util.HashMap oldShape = new java.util.HashMap(this.shape);
  this.built.clear();
  this.shape.clear();
  this.models.clear();''')
rep('''      if (!{PKG}.Widgets.shown(mm)) continue;
      b.appendInline("#SkyyHudRoot", {PKG}.Widgets.multiWidgetSrc(ids[i], l, mm));''', '''      if (!{PKG}.Widgets.shown(mm)) continue;
      if (!mm[0].equals(oldShape.get(ids[i]))) this.confirmAt = System.currentTimeMillis() + 1500L;
      b.appendInline("#SkyyHudRoot", {PKG}.Widgets.multiWidgetSrc(ids[i], l, mm));''')
rep('''    boolean re = fill(b, false);
    if (re) {{
      long now = System.currentTimeMillis();
      if (now - this.lastRe >= 1500L) {{ this.lastRe = now; show(); return; }}
    }}
    if (b.getCommands().length > 0) update(false, b);''', '''    boolean re = fill(b, false);
    long now = System.currentTimeMillis();
    if (re) {{
      if (now - this.lastRe >= 1500L) {{ this.lastRe = now; show(); return; }}
    }} else if (this.confirmAt != 0L && now >= this.confirmAt) {{
      this.confirmAt = 0L; show(); return;
    }}
    if (b.getCommands().length > 0) update(false, b);''')

# ---------------- EditorPage: one view model + height per multi-line widget per build ----------------
rep('page.addField(CtField.make("public String info;", page))', '''page.addField(CtField.make("public String info;", page))
# 0.3.9: id -> Integer pixel height the editor lays the widget out with (multi-line: drawn rows of the view model), id -> String[]
# view model of a multi-line widget; both filled by prepView() at the start of every build and used until the next build
page.addField(CtField.make("public java.util.HashMap hh;", page))
page.addField(CtField.make("public java.util.HashMap pm;", page))''')
rep('''# the visible widget covering most of a canvas cell''', '''page.addMethod(CtNewMethod.make(f"""
public void prepView(java.util.Map m, String[] ids) {{
  this.hh = new java.util.HashMap();
  this.pm = new java.util.HashMap();
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null) continue;
    if ({PKG}.Widgets.multi(ids[i])) {{
      String[] mm = {PKG}.Widgets.viewModel(ids[i], this.playerRef, l.opt);
      this.pm.put(ids[i], mm);
      this.hh.put(ids[i], Integer.valueOf({PKG}.Widgets.bodyH(ids[i], mm, l.scale)));
    }} else this.hh.put(ids[i], Integer.valueOf({PKG}.Widgets.hMax(l)));
  }}
}}""", page))
page.addMethod(CtNewMethod.make(f"""
public int heightOf(String id, {PKG}.WLayout l) {{
  Object o = this.hh == null ? null : this.hh.get(id);
  if (o != null) return ((Integer) o).intValue();
  return {PKG}.Widgets.viewH(id, l, this.playerRef);
}}""", page))
# the visible widget covering most of a canvas cell''')
rep('''    int[] p = {PKG}.Widgets.screenPos(l);
    int w = l.bw * l.scale / 100; int h = l.bh * l.scale / 100;''', '''    int h = heightOf(ids[i], l);
    int[] p = {PKG}.Widgets.screenPosH(l, h);
    int w = l.bw * l.scale / 100;''')
rep('    boolean displaced = c != {PKG}.Widgets.cellOf(hl);', '    boolean displaced = c != {PKG}.Widgets.cellOfH(hl, heightOf(hid, hl));')
rep('''    int[] p = {PKG}.Widgets.screenPos(l);
    int cw = (l.bw * l.scale / 100) * 2 / 3; int ch = (l.bh * l.scale / 100) * 2 / 3;
    int left = p[0] * 2 / 3; int top = p[1] * 2 / 3;''', '''    boolean mw = {PKG}.Widgets.multi(ids[i]);
    String[] mm = null;
    if (mw) {{ mm = (String[]) this.pm.get(ids[i]); if (mm == null) mm = {PKG}.Widgets.viewModel(ids[i], this.playerRef, l.opt); }}
    int hs = heightOf(ids[i], l);
    int[] p = {PKG}.Widgets.screenPosH(l, hs);
    int cw = (l.bw * l.scale / 100) * 2 / 3; int ch = mw ? {PKG}.Widgets.bodyH(ids[i], mm, l.scale * 2 / 3) : (l.bh * l.scale / 100) * 2 / 3;
    int left = p[0] * 2 / 3; int top = p[1] * 2 / 3;
    if (mw && (l.anchor.equals("bl") || l.anchor.equals("b") || l.anchor.equals("br"))) top = (p[1] + hs) * 2 / 3 - ch;
    else if (mw && (l.anchor.equals("l") || l.anchor.equals("c") || l.anchor.equals("r"))) top = (2 * p[1] + hs) / 3 - ch / 2;''')
rep('''    if ({PKG}.Widgets.multi(ids[i])) {{
      String[] mm = null;
      try {{ mm = {PKG}.Widgets.model(ids[i], this.playerRef, l.opt); }} catch (Throwable t) {{ mm = null; }}
      if (!{PKG}.Widgets.shown(mm)) mm = {PKG}.Widgets.sample(ids[i], this.playerRef, l.opt);
      b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + {PKG}.Widgets.multiBody(ids[i], "SkyyEPv" + ids[i], l, l.scale * 2 / 3, mm, l.bg, 5) + " }}");''', '''    if (mw) {{
      b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + {PKG}.Widgets.multiBody(ids[i], "SkyyEPv" + ids[i], l, l.scale * 2 / 3, mm, 5) + " }}");''')
rep('''  if (this.sel != null) {{ {PKG}.WLayout sl = ''', '''  prepView(m, ids);
  if (this.sel != null) {{ {PKG}.WLayout sl = ''')
rep('    int cell = freeCellNear({PKG}.Widgets.cellOf(l));', '    int cell = freeCellNear({PKG}.Widgets.cellOfH(l, heightOf(id, l)));')
rep('      {PKG}.Widgets.moveByCells(l, from, to);', '      {PKG}.Widgets.moveByCellsH(l, from, to, heightOf(wid, l));')

# ---------------- SettingsPage: Snap to -> the pressed point as anchor (8 px / true centre), resolved at every send ----------------
# (the lit Snap to button stays 0.3.8's "button of the current anchor"; a Size change keeps a snapped widget at its point)
rep('if ({PKG}.WLayout.validAnchor(a)) {{ l.anchor = a; l.dx = 8; l.dy = 8; }}',
    'if ({PKG}.WLayout.validAnchor(a)) {PKG}.Widgets.snapTo(l, a);')

# ---------------- round cross-check 2026-09-24 (SkyyIslands 0.5): the Party widget's place name follows the Zone widget's rule ----------------
# SkyyIslands 0.5 co-op members live on the OWNER's island and /island reset makes skyy-island-<key>-r<N>; both are the viewer's home
# island when the world equals bridge island:<uuid> (SkyyIslands publishes the HOME island world there; zoneText already checks it)
rep('''    try {{ if (viewer != null && n.substring(12).equals(pkey(viewer))) return "Your Island"; }} catch (Throwable t) {{ }}
    return "Island";''', '''    try {{ if (viewer != null && n.substring(12).equals(pkey(viewer))) return "Your Island"; }} catch (Throwable t) {{ }}
    try {{
      java.util.Map b = bridge();
      Object own = (b == null || viewer == null) ? null : b.get("island:" + viewer.toString());
      if (own != null && n.equals(own.toString())) return "Your Island";
    }} catch (Throwable t) {{ }}
    return "Island";''')

# every multi-line helper call site now uses the new signatures (no leftover bg argument / old maths)
assert "multiBody(ids[i], \"SkyyEPv\" + ids[i], l, l.scale * 2 / 3, mm, l.bg, 5)" not in s
assert "Widgets.cellOf(" not in s and "Widgets.moveByCells(" not in s and "Widgets.setTopLeft(" not in s and "Widgets.cornerAt(" not in s
# no Horizontal: / Vertical: margin can reach the HUD, nothing calls the removed toCorner, and the save path has no silent catch
assert 'Horizontal: " + l.dx' not in s and 'Vertical: " + l.dy' not in s and "toCorner(" not in s
assert "catch (Throwable t) {{ }}\n}}\"\"\", lst))" not in s

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
