"""Derive SkyyHud/build_skyyhud_0.3.4.py from 0.3.3 (0.3.3 stays untouched; CRLF/LF line endings of the source are preserved).
0.3.4 editor rework, from Skyy's 0.3.3 feedback ("i can't fine control the two in the top right, so they overlap. and it still
shows the items too. i just want to see the preview. click and hold to drag AND click to select, then arrows and size buttons"):
  * root cause: 0.3.3 drew each preview at its GRID CELL (col*80, row*80+64), not at the widget's true position, so 10 px nudges
    were invisible until a cell boundary was crossed and two widgets in one cell were pushed apart on the canvas.
  * previews now sit at the widget's TRUE position: Widgets.screenPos(l) and the real 180x26*scale size, all x 2/3 (canvas 1280x720),
    same font (12*scale/100 x 2/3) and background as the live HUD; the selected one gets a yellow outline + its name.
  * drag handles are invisible: SlotIconSize 1 (the key this grid already uses, value change only) + ItemGridSlot
    setSkipItemQualityBackground(true) (a server codec field). The grid has no SlotBackground, so empty slots are transparent
    (0.3.3 screenshot proved previews behind the grid show through). A custom transparent-PNG item was rejected: it needs an asset
    pack (Server/Item/Items/X.json + Common/Icons/ItemsGenerated/X.png) and cached assets are unreliable on Skyy's client.
  * finer grid 32 x 18 of 40 px (= 60 screen px); each handle is in the cell under the CENTRE of its preview; the selected widget is
    placed first; collisions take the nearest free cell (never hidden) and such displaced handles get a small labelled marker.
  * drop = move by the dragged distance (to - from cells x 60 px) and re-pick the nearest corner anchor: the widget follows the
    cursor like a normal drag and keeps its fine (arrow) offset. Drop on the same cell = select only (no snapping).
  * Select row (one small button per visible widget); clicking a handle also selects (and an empty cell selects the widget under it).
  * < > ^ v with a Step button cycling 1/5/10/25 px (per player, survives Settings/Widgets round trips), Size- / Size+ (10%, 50..200),
    Hide, Settings; every action clamps the widget inside the 1920x1080 screen and rebuilds.
  * /skyyhud preview front|back|off removed (previews are always behind the handles now); the action stays as a harmless no-op message.
Review fixes (0.3.4 review pass):
  * Widgets.clampToScreen also runs on the Settings page (after every change - a direct 50% -> 200% jump could push an edge-nudged
    widget off the canvas), on the Widgets page ON button, on every loaded layout (replaces the old negative-only dx/dy clamp) and
    on every imported/profile-loaded layout - no path can leave a widget off the 1920x1080 screen while the editor preview hides it.
  * EditorPage.STEPS is pruned together with huds/CACHE in SkyyHudPlugin.tickAll when a player leaves.
  * dead code removed: Widgets.buildAnchor (never called), VAL, ACTS/ACT_LABEL/ACTS_JAVA/ACT_LABELS_JAVA and the unused HUD_UI /
    EDITOR_UI .ui text (it used underscored element IDs, which the UI rules ban; nothing of it was shipped).
Run: python tools/hud_0_3_4_patch.py  then  python SkyyHud/build_skyyhud_0.3.4.py   (never --deploy from automation)
"""
import re
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.3.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.4.py")
raw = open(src, "rb").read().decode("utf8")
CRLF = "\r\n" in raw
s = raw.replace("\r\n", "\n")


def rep(old, new, count=1):
    global s
    assert s.count(old) == count, "anchor count %d != %d: %s" % (s.count(old), count, old[:90])
    s = s.replace(old, new)


def rep_block(start_anchor, end_anchor, new, keep_end=True):
    """replace s[start_anchor : end_anchor) - both anchors asserted unique and in order"""
    global s
    assert s.count(start_anchor) == 1, "start anchor: " + start_anchor[:90]
    assert s.count(end_anchor) == 1, "end anchor: " + end_anchor[:90]
    a = s.index(start_anchor)
    b = s.index(end_anchor)
    assert a < b, "anchors out of order: " + start_anchor[:60]
    s = s[:a] + new + s[b if keep_end else b + len(end_anchor):]


# ---------------------------------------------------------------- docstring + version
DOC = r'''"""SkyyHud 0.3.4 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.4.py            -> SkyyHud/SkyyHud-0.3.4.jar
       python build_skyyhud_0.3.4.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.4 SkyyHud" in the HUD mod world
0.3.4 editor rework (generated by tools/hud_0_3_4_patch.py from 0.3.3):
  - previews are drawn at the widgets' TRUE positions (1080p screen x 2/3), same size, font and background as the HUD;
    the selected widget is outlined in yellow and named
  - drag handles are invisible (SlotIconSize 1, no quality background); 32 x 18 grid of 40 px cells (= 60 screen px);
    each handle sits in the cell under the centre of its preview; collisions take the nearest free cell (marked), never hidden
  - click and hold to drag: the widget moves by the dragged distance and keeps its fine offset (nearest corner anchor re-picked)
  - click a widget (or its button in the Select row) to select it; < > ^ v with Step 1/5/10/25 px, Size- / Size+, Hide, Settings;
    a widget can never leave the screen (editor, Settings, Widgets page, import and load all clamp to 1920x1080)
  - /skyyhud preview is a no-op now (previews are always behind the handles)
Commands: /skyyhud (alias /shud) opens the editor; /skyyhud export | import <code> | reset | profile save|load|delete|list <name>.
"""
'''
rep_block('"""SkyyHud 0.2 - build script', '"""\nimport sys, os', DOC + 'import sys, os', keep_end=False)
rep('VERSION = "0.3.3"', 'VERSION = "0.3.4"')

# ---------------------------------------------------------------- EditorPage static state: preview switch -> per-player nudge step
rep("page.addField(CtField.make('public static volatile String PREVIEW = \"back\";', page))",
    "page.addField(CtField.make('public static final java.util.concurrent.ConcurrentHashMap STEPS = new java.util.concurrent.ConcurrentHashMap();', page))")

# ---------------------------------------------------------------- Widgets geometry (true 1080p pixels, 32x18 canvas grid)
WIDGETS_GEOM = r'''# screen position (top-left corner of the widget, 1080p) from a layout
wid.addMethod(CtNewMethod.make(f"""
public static int[] screenPos({PKG}.WLayout l) {{
  int w = 180 * l.scale / 100; int h = 26 * l.scale / 100;
  String a = l.anchor; int x; int y;
  if (a.equals("tl") || a.equals("l") || a.equals("bl")) x = l.dx;
  else if (a.equals("tr") || a.equals("r") || a.equals("br")) x = 1920 - w - l.dx;
  else x = 960 - w / 2 + l.dx;
  if (a.equals("tl") || a.equals("t") || a.equals("tr")) y = l.dy;
  else if (a.equals("bl") || a.equals("b") || a.equals("br")) y = 1080 - h - l.dy;
  else y = 540 - h / 2 + l.dy;
  return new int[] {{ x, y }};
}}""", wid))
# 0.3.4: exact inverse of screenPos for the layout's current anchor; the top-left is clamped so the widget stays on screen
wid.addMethod(CtNewMethod.make(f"""
public static void setTopLeft({PKG}.WLayout l, int x, int y) {{
  int w = 180 * l.scale / 100; int h = 26 * l.scale / 100;
  if (x > 1920 - w) x = 1920 - w;
  if (x < 0) x = 0;
  if (y > 1080 - h) y = 1080 - h;
  if (y < 0) y = 0;
  String a = l.anchor;
  if (a.equals("tl") || a.equals("l") || a.equals("bl")) l.dx = x;
  else if (a.equals("tr") || a.equals("r") || a.equals("br")) l.dx = 1920 - w - x;
  else l.dx = x - (960 - w / 2);
  if (a.equals("tl") || a.equals("t") || a.equals("tr")) l.dy = y;
  else if (a.equals("bl") || a.equals("b") || a.equals("br")) l.dy = 1080 - h - y;
  else l.dy = y - (540 - h / 2);
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static void clampToScreen({PKG}.WLayout l) {{
  int[] p = screenPos(l);
  setTopLeft(l, p[0], p[1]);
}}""", wid))
# put the widget's top-left at (x, y) and anchor it to the nearest screen corner (judged by the widget's centre)
wid.addMethod(CtNewMethod.make(f"""
public static void cornerAt({PKG}.WLayout l, int x, int y) {{
  int w = 180 * l.scale / 100; int h = 26 * l.scale / 100;
  if (x > 1920 - w) x = 1920 - w;
  if (x < 0) x = 0;
  if (y > 1080 - h) y = 1080 - h;
  if (y < 0) y = 0;
  boolean left = x + w / 2 < 960; boolean top = y + h / 2 < 540;
  l.anchor = top ? (left ? "tl" : "tr") : (left ? "bl" : "br");
  setTopLeft(l, x, y);
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static void toCorner({PKG}.WLayout l) {{
  int[] p = screenPos(l);
  cornerAt(l, p[0], p[1]);
}}""", wid))
# 0.3.4 canvas grid: 32 x 18 cells of 40 canvas px = 60 screen px; a widget's handle belongs in the cell under its centre
wid.addMethod(CtNewMethod.make(f"""
public static int cellOf({PKG}.WLayout l) {{
  int[] p = screenPos(l);
  int cx = p[0] + (180 * l.scale / 100) / 2; int cy = p[1] + (26 * l.scale / 100) / 2;
  int col = cx / 60; if (col < 0) col = 0; if (col > 31) col = 31;
  int row = cy / 60; if (row < 0) row = 0; if (row > 17) row = 17;
  return row * 32 + col;
}}""", wid))
# a drag from cell `from` to cell `to` moves the widget by that distance (keeps sub-cell offsets), nearest corner anchor re-picked
wid.addMethod(CtNewMethod.make(f"""
public static void moveByCells({PKG}.WLayout l, int from, int to) {{
  int[] p = screenPos(l);
  int mx = (to % 32 - from % 32) * 60; int my = (to / 32 - from / 32) * 60;
  cornerAt(l, p[0] + mx, p[1] + my);
}}""", wid))
SHORT = {"Coords": "Coords", "Zone": "Zone", "Gclock": "Clock", "Rclock": "Real time",
         "Day": "Day", "Session": "Session", "Online": "Online", "Coins": "Coins"}
short_lines = "\n".join('  if (id.equals("%s")) return "%s";' % (i, l) for i, l in SHORT.items())
wid.addMethod(CtNewMethod.make(f"""
public static String shortLabel(String id) {{
{short_lines}
  return id;
}}""", wid))
'''
rep_block('# screen position (top-left corner of the widget, 1080p) from a layout\n', '\n# ================= LayoutStore =================', WIDGETS_GEOM)

# non-corner anchors (Settings "Snap to") are converted to the nearest corner on load - now exact instead of snapped to a cell
rep('    if (!corner) {PKG}.Widgets.placeAtCell(w, {PKG}.Widgets.cellOf(w));',
    '    if (!corner) {PKG}.Widgets.toCorner(w);')

# review fix: a stale/garbled saved layout used to be clamped only for NEGATIVE dx/dy on load; clamp it fully onto the 1920x1080
# screen (clampToScreen covers dx/dy >= 0 as well as the upper bound for the widget's current scale)
rep('    if (w.dx < 0) w.dx = 0;\n    if (w.dy < 0) w.dy = 0;\n',
    '    {PKG}.Widgets.clampToScreen(w);\n')
# review fix: /skyyhud import <code> and profile load (importCode) put parsed layouts straight into the live cache - clamp them too
rep('    if (l == null) continue;\n    m.put(id, l); n++;',
    '    if (l == null) continue;\n    {PKG}.Widgets.clampToScreen(l);\n    m.put(id, l); n++;')
# review fix: EditorPage.STEPS (per-player nudge step) is pruned with huds/CACHE when the player is gone
rep('{PKG}.LayoutStore.CACHE.remove(e.getKey()); continue; }}',
    '{PKG}.LayoutStore.CACHE.remove(e.getKey()); {PKG}.EditorPage.STEPS.remove(e.getKey()); continue; }}')

# review fix: dead code - Widgets.buildAnchor is never called (the HUD is sent as inline text via anchorSrc/widgetSrc)
rep_block('wid.addMethod(CtNewMethod.make(f"""\npublic static {ANC} buildAnchor(',
          '\nwid.addMethod(CtNewMethod.make(f"""\npublic static String anchorSrc(', '')
rep('VAL = "com.hypixel.hytale.server.core.ui.Value"\n', '')
# ... and the constants only the unused .ui editor text used
rep('ACTS = ["Tog", "Tl", "T", "Tr", "L", "C", "R", "Bl", "B2", "Br", "Lt", "Rt", "Up", "Dn", "Sm", "Sp"]\n'
    'ACT_LABEL = {"Tog": "On/Off", "Tl": "TL", "T": "T", "Tr": "TR", "L": "L", "C": "C", "R": "R", "Bl": "BL", "B2": "B", "Br": "BR",\n'
    '             "Lt": "<", "Rt": ">", "Up": "^", "Dn": "v", "Sm": "Size-", "Sp": "Size+"}\n', '')
rep('ACTS_JAVA = ", ".join(\'"%s"\' % a for a in ACTS)\n'
    'ACT_LABELS_JAVA = ", ".join(\'"%s"\' % ACT_LABEL[a] for a in ACTS)\n', '')
# ... and the unused HUD_UI / EDITOR_UI .ui text (never shipped; underscored element IDs are banned by the UI rules)
rep_block('# ================= UI documents =================\n', 'jar = os.path.join(HERE', '')

# ---------------------------------------------------------------- EditorPage: selInfo .. handleDataEvent
EDITOR = r'''page.addMethod(CtNewMethod.make(f"""
public String selInfo() {{
  if (this.sel == null) return "Nothing selected - click a widget on the canvas or its button in the Select row";
  java.util.Map m = {PKG}.LayoutStore.get(this.playerRef.getUuid());
  {PKG}.WLayout l = ({PKG}.WLayout) m.get(this.sel);
  if (l == null) return "?";
  return {PKG}.Widgets.label(this.sel) + "      " + l.anchor.toUpperCase() + "      x " + l.dx + "   y " + l.dy + "      " + l.scale + "%";
}}""", page))
page.addMethod(CtNewMethod.make(f"""
public static String esc(String t) {{
  if (t == null) return "";
  return t.replace('\\\\', ' ').replace('"', ' ').replace('{{', '(').replace('}}', ')').replace(';', ',');
}}""", page))
page.addMethod(CtNewMethod.make(f"""
public int getStep() {{
  Object o = STEPS.get(this.playerRef.getUuid());
  return o == null ? 5 : ((Integer) o).intValue();
}}""", page))
page.addMethod(CtNewMethod.make(f"""
public void nextStep() {{
  int s = getStep();
  int n = s == 1 ? 5 : (s == 5 ? 10 : (s == 10 ? 25 : 1));
  STEPS.put(this.playerRef.getUuid(), Integer.valueOf(n));
}}""", page))
# nearest free canvas cell to `target` (squared grid distance, lowest index on ties) - handles are never dropped
page.addMethod(CtNewMethod.make(f"""
public int freeCellNear(int target) {{
  if (target < 0) target = 0;
  if (target > 575) target = 575;
  if (this.cellWidget[target] == null) return target;
  int tc = target % 32; int tr = target / 32;
  int best = -1; int bestD = 2147483647;
  for (int c = 0; c < 576; c++) {{
    if (this.cellWidget[c] != null) continue;
    int dc = c % 32 - tc; int dr = c / 32 - tr;
    int d = dc * dc + dr * dr;
    if (d < bestD) {{ bestD = d; best = c; }}
  }}
  return best;
}}""", page))
# the visible widget covering most of a canvas cell (later widgets are drawn on top and win ties)
page.addMethod(CtNewMethod.make(f"""
public String widgetAtCell(java.util.Map m, String[] ids, int cell) {{
  int x0 = (cell % 32) * 60; int y0 = (cell / 32) * 60;
  String best = null; int bestA = 0;
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || !l.en) continue;
    int[] p = {PKG}.Widgets.screenPos(l);
    int w = 180 * l.scale / 100; int h = 26 * l.scale / 100;
    int ox = Math.min(p[0] + w, x0 + 60) - Math.max(p[0], x0);
    int oy = Math.min(p[1] + h, y0 + 60) - Math.max(p[1], y0);
    if (ox <= 0 || oy <= 0) continue;
    if (ox * oy >= bestA) {{ bestA = ox * oy; best = ids[i]; }}
  }}
  return best;
}}""", page))
# previews at TRUE positions (screen x 2/3), drawn BEFORE the grid = behind the invisible handles (proven visible on 0.3.3)
page.addMethod(CtNewMethod.make(f"""
public void appendPreviews({UCB} b, java.util.Map m, String[] ids) {{
  b.appendInline("#SkyyECanvasWrap", "Group #SkyyEPrev {{ Anchor: (Horizontal: 0, Top: 2, Width: 1280, Height: 720); }}");
  for (int c = 0; c < 576; c++) {{
    String hid = this.cellWidget[c];
    if (hid == null) continue;
    {PKG}.WLayout hl = ({PKG}.WLayout) m.get(hid);
    if (hl == null) continue;
    boolean displaced = c != {PKG}.Widgets.cellOf(hl);
    boolean isSel = hid.equals(this.sel);
    if (!displaced && !isSel) continue;
    b.appendInline("#SkyyEPrev", "Group #SkyyEMk" + hid + " {{ Anchor: (Left: " + ((c % 32) * 40) + ", Top: " + ((c / 32) * 40) + ", Width: 40, Height: 40); Background: " + (isSel ? "#ffd24a(0.2)" : "#7fb8ff(0.25)") + "; }}");
    if (displaced) {{
      b.appendInline("#SkyyEMk" + hid, "Label #SkyyEMk" + hid + "Txt {{ Anchor: (Full: 0); Text: \\"\\"; Style: (FontSize: 8, RenderBold: true, TextColor: #cfe6ff, HorizontalAlignment: Center, VerticalAlignment: Center); }}");
      b.set("#SkyyEMk" + hid + "Txt.Text", {PKG}.Widgets.shortLabel(hid));
    }}
  }}
  long now = System.currentTimeMillis();
  long join = now;
  try {{ {PKG}.HudMain hm = ({PKG}.HudMain) this.plugin.huds.get(this.playerRef.getUuid()); if (hm != null) join = hm.joinMs; }} catch (Throwable t) {{ join = now; }}
  int sx = -1; int sy = 0; int sw = 0; int sh = 0;
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || !l.en) continue;
    int[] p = {PKG}.Widgets.screenPos(l);
    int cw = (180 * l.scale / 100) * 2 / 3; int ch = (26 * l.scale / 100) * 2 / 3;
    int left = p[0] * 2 / 3; int top = p[1] * 2 / 3;
    if (left > 1280 - cw) left = 1280 - cw;
    if (left < 0) left = 0;
    if (top > 720 - ch) top = 720 - ch;
    if (top < 0) top = 0;
    int fs = 12 * l.scale / 100; if (fs < 6) fs = 6;
    fs = fs * 2 / 3; if (fs < 5) fs = 5;
    String text;
    try {{ text = {PKG}.Widgets.text(ids[i], this.playerRef, join); }} catch (Throwable t) {{ text = {PKG}.Widgets.label(ids[i]); }}
    if (text == null) text = "";
    b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + "Label #SkyyEPv" + ids[i] + "Txt {{ Anchor: (Full: 0); Text: \\"\\"; Style: (FontSize: " + fs + ", RenderBold: true, TextColor: #eaf6ff, HorizontalAlignment: Center, VerticalAlignment: Center); }} }}");
    b.set("#SkyyEPv" + ids[i] + "Txt.Text", text);
    if (ids[i].equals(this.sel)) {{ sx = left; sy = top; sw = cw; sh = ch; }}
  }}
  if (sx >= 0) {{
    int ox = sx - 2; int oy = sy - 2; int ow = sw + 4; int oh = sh + 4;
    if (ox < 0) {{ ow = ow + ox; ox = 0; }}
    if (oy < 0) {{ oh = oh + oy; oy = 0; }}
    if (ox + ow > 1280) ow = 1280 - ox;
    if (oy + oh > 720) oh = 720 - oy;
    b.appendInline("#SkyyEPrev", "Group {{ Anchor: (Left: " + ox + ", Top: " + oy + ", Width: " + ow + ", Height: 2); Background: #ffd24a; }}");
    b.appendInline("#SkyyEPrev", "Group {{ Anchor: (Left: " + ox + ", Top: " + (oy + oh - 2) + ", Width: " + ow + ", Height: 2); Background: #ffd24a; }}");
    b.appendInline("#SkyyEPrev", "Group {{ Anchor: (Left: " + ox + ", Top: " + oy + ", Width: 2, Height: " + oh + "); Background: #ffd24a; }}");
    b.appendInline("#SkyyEPrev", "Group {{ Anchor: (Left: " + (ox + ow - 2) + ", Top: " + oy + ", Width: 2, Height: " + oh + "); Background: #ffd24a; }}");
    boolean rightSide = ox + ow / 2 > 640;
    int nx = rightSide ? ox + ow - 220 : ox;
    if (nx > 1060) nx = 1060;
    if (nx < 0) nx = 0;
    int ny = oy >= 16 ? oy - 15 : oy + oh + 1;
    b.appendInline("#SkyyEPrev", "Label #SkyyESelName {{ Anchor: (Left: " + nx + ", Top: " + ny + ", Width: 220, Height: 14); Text: \\"\\"; Style: (FontSize: 10, RenderBold: true, TextColor: #ffd24a, HorizontalAlignment: " + (rightSide ? "End" : "Start") + ", VerticalAlignment: Center); }}");
    b.set("#SkyyESelName.Text", {PKG}.Widgets.label(this.sel));
  }}
}}""", page))
page.addMethod(CtNewMethod.make(f"""
public void build({REF} ref, {UCB} b, {UEB} ev, {ST} st) {{
  java.util.UUID u = this.playerRef.getUuid();
  java.util.Map m = {PKG}.LayoutStore.get(u);
  String[] ids = {PKG}.Widgets.IDS;
  String bs = "Style: TextButtonStyle(Default: (Background: #1d3a5f, LabelStyle: (FontSize: 10, TextColor: #dceeff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Hovered: (Background: #2f5a8f, LabelStyle: (FontSize: 10, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Pressed: (Background: #0f2038, LabelStyle: (FontSize: 10, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));";
  String on = "Style: TextButtonStyle(Default: (Background: #7fe07f, LabelStyle: (FontSize: 10, TextColor: #062a06, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Hovered: (Background: #a0f0a0, LabelStyle: (FontSize: 10, TextColor: #062a06, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), Pressed: (Background: #5fb05f, LabelStyle: (FontSize: 10, TextColor: #062a06, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));";
  if (this.sel != null) {{ {PKG}.WLayout sl = ({PKG}.WLayout) m.get(this.sel); if (sl == null || !sl.en) this.sel = null; }}
  b.appendInline((String) null, "Group #SkyyEditor {{ Anchor: (Width: 1330, Height: 930); Background: #0b1524(0.96); Padding: (Horizontal: 20, Vertical: 10); LayoutMode: Top; }}");
  b.appendInline("#SkyyEditor", "Group {{ Anchor: (Height: 2); Background: #7fe07f; }}");
  b.appendInline("#SkyyEditor", "Label {{ Anchor: (Height: 22); Text: \\"SkyyHud Editor\\"; Style: (FontSize: 15, RenderBold: true, TextColor: #eaffea, HorizontalAlignment: Center, VerticalAlignment: Center); }}");
  b.appendInline("#SkyyEditor", "Label {{ Anchor: (Height: 14); Text: \\"Click and hold the middle of a widget to drag it. Click a widget or its button below to select it - then fine-tune with the arrows and Size buttons. The canvas is your screen at 2/3 scale.\\"; Style: (FontSize: 10, TextColor: #9fb8d0, HorizontalAlignment: Center); }}");
  b.appendInline("#SkyyEditor", "Group #SkyyECanvasWrap {{ Anchor: (Height: 724); }}");
  this.cellWidget = new String[576];
  java.util.ArrayList slots = new java.util.ArrayList();
  for (int i = 0; i < 576; i++) slots.add(new {IGS}());
  for (int k = -1; k < ids.length; k++) {{
    String id = k < 0 ? this.sel : ids[k];
    if (id == null) continue;
    if (k >= 0 && id.equals(this.sel)) continue;
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(id);
    if (l == null || !l.en) continue;
    int cell = freeCellNear({PKG}.Widgets.cellOf(l));
    if (cell < 0) continue;
    this.cellWidget[cell] = id;
    {IGS} gs = new {IGS}(new {IS}({PKG}.Widgets.chipItem(id), 1));
    gs.setName({PKG}.Widgets.label(id));
    gs.setDescription("Drag to move. Click to select.");
    gs.setActivatable(true);
    gs.setSkipItemQualityBackground(true);
    slots.set(cell, gs);
  }}
  appendPreviews(b, m, ids);
  b.appendInline("#SkyyECanvasWrap", "ItemGrid #SkyyECanvas {{ Anchor: (Horizontal: 0, Top: 2, Width: 1280, Height: 720); SlotsPerRow: 32; AreItemsDraggable: true; Style: (SlotSize: 40, SlotIconSize: 1, SlotSpacing: 0); }}");
  b.appendInline("#SkyyECanvasWrap", "Group #SkyyEBorder {{ Anchor: (Horizontal: 0, Top: 2, Width: 1280, Height: 720); HitTestVisible: false; }}");
  b.appendInline("#SkyyEBorder", "Group {{ Anchor: (Left: 0, Top: 0, Width: 1280, Height: 3); Background: #7fe07f; HitTestVisible: false; }}");
  b.appendInline("#SkyyEBorder", "Group {{ Anchor: (Left: 0, Top: 717, Width: 1280, Height: 3); Background: #7fe07f; HitTestVisible: false; }}");
  b.appendInline("#SkyyEBorder", "Group {{ Anchor: (Left: 0, Top: 0, Width: 3, Height: 720); Background: #7fe07f; HitTestVisible: false; }}");
  b.appendInline("#SkyyEBorder", "Group {{ Anchor: (Left: 1277, Top: 0, Width: 3, Height: 720); Background: #7fe07f; HitTestVisible: false; }}");
  b.appendInline("#SkyyEBorder", "Label {{ Anchor: (Left: 8, Top: 4, Width: 80, Height: 14); Text: \\"screen edge\\"; Style: (FontSize: 9, TextColor: #7fe07f); }}");
  b.set("#SkyyECanvas.Slots", slots);
  ev.addEventBinding({BT}.Dropped, "#SkyyECanvas", {EVD}.of("a", "drop"));
  ev.addEventBinding({BT}.SlotClicking, "#SkyyECanvas", {EVD}.of("a", "slot"));
  ev.addEventBinding({BT}.DragCancelled, "#SkyyECanvas", {EVD}.of("a", "dragcancel"));
  b.appendInline("#SkyyEditor", "Group #SkyyESelRow {{ Anchor: (Height: 26); LayoutMode: Left; Padding: (Top: 2); }}");
  b.appendInline("#SkyyESelRow", "Label {{ Anchor: (Width: 56, Height: 22); Text: \\"Select\\"; Style: (FontSize: 10, RenderBold: true, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
  int shown = 0;
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || !l.en) continue;
    shown++;
    b.appendInline("#SkyyESelRow", "TextButton #SkyyESel" + ids[i] + " {{ Anchor: (Width: 84, Height: 22); Text: \\"" + {PKG}.Widgets.shortLabel(ids[i]) + "\\"; " + (ids[i].equals(this.sel) ? on : bs) + " }}");
    b.appendInline("#SkyyESelRow", "Label {{ Anchor: (Width: 4, Height: 22); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyyESel" + ids[i], {EVD}.of("a", "sel:" + ids[i]));
  }}
  if (shown == 0) b.appendInline("#SkyyESelRow", "Label {{ Anchor: (Width: 500, Height: 22); Text: \\"no visible widgets - show one from the Hidden row\\"; Style: (FontSize: 10, TextColor: #6f8498, VerticalAlignment: Center); }}");
  b.appendInline("#SkyyEditor", "Label #SkyyEInfo {{ Anchor: (Height: 18); Text: \\"" + esc(selInfo()) + "\\"; Style: (FontSize: 11, RenderBold: true, TextColor: #ffe9c9, HorizontalAlignment: Center, VerticalAlignment: Center); }}");
  b.appendInline("#SkyyEditor", "Group #SkyyEBar {{ Anchor: (Height: 28); LayoutMode: Left; Padding: (Top: 2); }}");
  if (this.sel != null) {{
    String[] acts = new String[] {{ "Lt", "Rt", "Up", "Dn", "Step", "Sm", "Sp", "Hide", "Cog" }};
    String[] labels = new String[] {{ "<", ">", "^", "v", "Step", "Size-", "Size+", "Hide", "Settings" }};
    labels[4] = "Step " + getStep() + " px";
    int[] widths = new int[] {{ 40, 40, 40, 40, 90, 60, 60, 70, 90 }};
    for (int a = 0; a < acts.length; a++) {{
      b.appendInline("#SkyyEBar", "TextButton #SkyyEB" + acts[a] + " {{ Anchor: (Width: " + widths[a] + ", Height: 24); Text: \\"" + labels[a] + "\\"; " + bs + " }}");
      b.appendInline("#SkyyEBar", "Label {{ Anchor: (Width: " + ((a == 3 || a == 4 || a == 6) ? 14 : 4) + ", Height: 24); Text: \\"\\"; }}");
      ev.addEventBinding({BT}.Activating, "#SkyyEB" + acts[a], {EVD}.of("a", "act:" + acts[a]));
    }}
  }}
  b.appendInline("#SkyyEditor", "Group #SkyyEOff {{ Anchor: (Height: 26); LayoutMode: Left; Padding: (Top: 2); }}");
  b.appendInline("#SkyyEOff", "Label {{ Anchor: (Width: 56, Height: 22); Text: \\"Hidden\\"; Style: (FontSize: 10, RenderBold: true, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
  int off = 0;
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || l.en) continue;
    off++;
    b.appendInline("#SkyyEOff", "TextButton #SkyyEOn" + ids[i] + " {{ Anchor: (Width: 84, Height: 22); Text: \\"" + {PKG}.Widgets.shortLabel(ids[i]) + "\\"; " + bs + " }}");
    b.appendInline("#SkyyEOff", "Label {{ Anchor: (Width: 4, Height: 22); Text: \\"\\"; }}");
    ev.addEventBinding({BT}.Activating, "#SkyyEOn" + ids[i], {EVD}.of("a", "show:" + ids[i]));
  }}
  if (off == 0) b.appendInline("#SkyyEOff", "Label {{ Anchor: (Width: 300, Height: 22); Text: \\"none\\"; Style: (FontSize: 10, TextColor: #6f8498, VerticalAlignment: Center); }}");
  b.appendInline("#SkyyEditor", "Group #SkyyEFoot {{ Anchor: (Height: 30); LayoutMode: Left; Padding: (Top: 4); }}");
  b.appendInline("#SkyyEFoot", "Label {{ Anchor: (Width: 1100, Height: 26); Text: \\"" + (this.info == null ? "" : this.info.replace('\\"', ' ')) + "   /skyyhud export | import | reset | profile save|load|list <name>\\"; Style: (FontSize: 10, TextColor: #6f8498, VerticalAlignment: Center); }}");
  b.appendInline("#SkyyEFoot", "TextButton #SkyyEWidgets {{ Anchor: (Width: 150, Height: 26); Text: \\"Widgets / Settings\\"; " + bs + " }}");
  ev.addEventBinding({BT}.Activating, "#SkyyEWidgets", {EVD}.of("a", "widgets"));
}}""", page))
page.addMethod(CtNewMethod.make(f"""
public void handleDataEvent({REF} ref, {ST} st, String data) {{
  try {{
    if (data == null) return;
    java.util.UUID u = this.playerRef.getUuid();
    java.util.Map m = {PKG}.LayoutStore.get(u);
    String[] ids = {PKG}.Widgets.IDS;
    if (data.indexOf("\\"drop\\"") >= 0 || data.indexOf("Dropped") >= 0) {{
      int from = jsonInt(data, "SourceSlotId");
      int to = jsonInt(data, "SlotIndex");
      if (from < 0 || to < 0 || from >= 576 || to >= 576 || this.cellWidget == null) {{ {PKG}.LayoutStore.debug("drop payload: " + data); return; }}
      String wid = this.cellWidget[from];
      if (wid == null) return;
      {PKG}.WLayout l = ({PKG}.WLayout) m.get(wid);
      if (l == null) return;
      if (to == from) {{ this.sel = wid; this.info = ""; rebuild(); return; }}
      {PKG}.Widgets.moveByCells(l, from, to);
      String other = this.cellWidget[to];
      this.sel = wid;
      this.info = (other != null && !other.equals(wid)) ? "moved " + {PKG}.Widgets.label(wid) + " onto " + {PKG}.Widgets.label(other) + " - nudge with the arrows to separate them" : "moved " + {PKG}.Widgets.label(wid);
      {PKG}.LayoutStore.save(u); plugin.rebuildFor(u); rebuild(); return;
    }}
    if (data.indexOf("\\"slot\\"") >= 0) {{
      int idx = jsonInt(data, "SlotIndex");
      if (idx < 0 || idx >= 576 || this.cellWidget == null) {{ {PKG}.LayoutStore.debug("slot payload: " + data); return; }}
      String hit = this.cellWidget[idx];
      if (hit == null) hit = widgetAtCell(m, ids, idx);
      if (hit != null && !hit.equals(this.sel)) {{ this.sel = hit; this.info = ""; rebuild(); }}
      return;
    }}
    if (data.indexOf("\\"dragcancel\\"") >= 0) return;
    if (data.indexOf("\\"widgets\\"") >= 0) {{
      {PLA} player = ({PLA}) st.getComponent(ref, {PLA}.getComponentType());
      if (player != null) player.getPageManager().openCustomPage(ref, st, new {PKG}.WidgetsPage(this.playerRef, this.plugin));
      return;
    }}
    for (int i = 0; i < ids.length; i++) {{
      if (data.indexOf("sel:" + ids[i] + "\\"") >= 0) {{
        {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
        if (l != null && l.en && !ids[i].equals(this.sel)) {{ this.sel = ids[i]; this.info = ""; rebuild(); }}
        return;
      }}
    }}
    for (int i = 0; i < ids.length; i++) {{
      if (data.indexOf("show:" + ids[i] + "\\"") >= 0) {{
        {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
        if (l != null) {{ l.en = true; {PKG}.Widgets.clampToScreen(l); this.sel = ids[i]; {PKG}.LayoutStore.save(u); plugin.rebuildFor(u); }}
        rebuild(); return;
      }}
    }}
    if (this.sel == null) return;
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(this.sel);
    if (l == null) return;
    if (data.indexOf("act:Cog\\"") >= 0) {{
      {PLA} player = ({PLA}) st.getComponent(ref, {PLA}.getComponentType());
      if (player != null) player.getPageManager().openCustomPage(ref, st, new {PKG}.SettingsPage(this.playerRef, this.plugin, this.sel));
      return;
    }}
    if (data.indexOf("act:Step\\"") >= 0) {{ nextStep(); rebuild(); return; }}
    int step = getStep();
    String a = l.anchor;
    boolean rightEdge = a.equals("tr") || a.equals("r") || a.equals("br");
    boolean bottomEdge = a.equals("bl") || a.equals("b") || a.equals("br");
    if (data.indexOf("act:Hide\\"") >= 0) {{ l.en = false; this.info = "hid " + {PKG}.Widgets.label(this.sel) + " - click it in the Hidden row to bring it back"; this.sel = null; }}
    else if (data.indexOf("act:Lt\\"") >= 0) l.dx += rightEdge ? step : -step;
    else if (data.indexOf("act:Rt\\"") >= 0) l.dx += rightEdge ? -step : step;
    else if (data.indexOf("act:Up\\"") >= 0) l.dy += bottomEdge ? step : -step;
    else if (data.indexOf("act:Dn\\"") >= 0) l.dy += bottomEdge ? -step : step;
    else if (data.indexOf("act:Sm\\"") >= 0) l.scale -= 10;
    else if (data.indexOf("act:Sp\\"") >= 0) l.scale += 10;
    else {{ {PKG}.LayoutStore.debug("unknown editor payload: " + data); return; }}
    if (l.scale < 50) l.scale = 50;
    if (l.scale > 200) l.scale = 200;
    {PKG}.Widgets.clampToScreen(l);
    {PKG}.LayoutStore.save(u); plugin.rebuildFor(u); rebuild();
  }} catch (Throwable t) {{ {PKG}.LayoutStore.debug("editor event failed: " + t); }}
}}""", page))

'''
rep_block('page.addMethod(CtNewMethod.make(f"""\npublic String selInfo() {{', '# ================= SettingsPage (cog) =================', EDITOR)

# ---------------------------------------------------------------- /skyyhud preview: switch removed, action kept as a harmless no-op
PREVIEW_CMD = r'''    if (action.equals("preview")) {{
      pr.sendMessage({MSG}.raw("[SkyyHud] since 0.3.4 the editor always shows live previews behind invisible drag handles - nothing to switch"));
      return;
    }}
'''
rep_block('    if (action.equals("preview")) {{', '    if (action.equals("profile")) {{', PREVIEW_CMD)
rep('"export | import | reset | profile | preview (omit to open the editor)"', '"export | import | reset | profile (omit to open the editor)"')

# ---------------------------------------------------------------- review fix: Settings / Widgets pages clamp like the editor does
# SettingsPage: the size jump buttons (50..200 in one click), ON and Snap-to all change geometry; clamp unconditionally before the
# shared save + live rebuild (harmless for bg/off, and it repairs anything stale)
rep(r'''    else return;
    {PKG}.LayoutStore.save(u); plugin.rebuildFor(u); rebuild();
  }} catch (Throwable t) {{ {PKG}.LayoutStore.debug("settings event failed: " + t); }}''',
    r'''    else return;
    {PKG}.Widgets.clampToScreen(l);
    {PKG}.LayoutStore.save(u); plugin.rebuildFor(u); rebuild();
  }} catch (Throwable t) {{ {PKG}.LayoutStore.debug("settings event failed: " + t); }}''')
# WidgetsPage ON: a widget resized while hidden must come back on screen
rep(r'''if (data.indexOf("on:" + ids[i] + "\\"") >= 0) {{ l.en = true; {PKG}.LayoutStore.save(u);''',
    r'''if (data.indexOf("on:" + ids[i] + "\\"") >= 0) {{ l.en = true; {PKG}.Widgets.clampToScreen(l); {PKG}.LayoutStore.save(u);''')

# ---------------------------------------------------------------- sanity: nothing from the 0.3.3 editor geometry may survive
for gone in ("PREVIEW", "placeAtCell", "new String[144]", "SlotsPerRow: 16", "cell % 16", "SlotIconSize: 56",
             "buildAnchor", "{VAL}", "HUD_UI", "EDITOR_UI", "BTN_STYLE", "anchor_src", "ACT_LABEL", "ACTS",
             "if (w.dx < 0)", "if (w.dy < 0)"):
    assert gone not in s, "leftover 0.3.3 code: " + gone
for need in ("SlotIconSize: 1,", "SlotsPerRow: 32", "new String[576]", "moveByCells", "clampToScreen", "setSkipItemQualityBackground(true)",
             'VERSION = "0.3.4"', "{PKG}.EditorPage.STEPS.remove(e.getKey());", "public static String anchorSrc(", "B.assemble(jar"):
    assert need in s, "missing: " + need
# every geometry-changing handler clamps: editor tail + show:, Settings tail, Widgets ON, load loop, importCode (6 call sites)
assert s.count("{PKG}.Widgets.clampToScreen(") == 6, "clampToScreen call sites: %d" % s.count("{PKG}.Widgets.clampToScreen(")
# UI rule: no underscored element IDs anywhere in the generated script
bad = re.findall(r'#[A-Za-z][A-Za-z0-9]*_', s)
assert not bad, "underscored element id(s): %s" % bad[:5]

out = s.replace("\n", "\r\n") if CRLF else s
open(dst, "wb").write(out.encode("utf8"))
print("wrote", dst, "(CRLF)" if CRLF else "(LF)")
