"""Derive SkyyHud/build_skyyhud_0.3.12.py from the LIVE 0.3.11 (the SET pin; 0.3.11 is left untouched; line endings preserved).
0.3.12 = the COMBAT INDICATOR widget (Skyy 2026-10-02: "id add a widget for combat indicator too. goes red when in combat. and id
either do a small count down, or use the animation to indicate how close you are to being out of combat"; OPEN-QUESTIONS.md LOCKED
2026-10-02: red while in combat, a small countdown AND a shrinking bar, out of combat hidden by default as a widget setting).
  - new widget id Combat ("Combat Indicator"), appended to Widgets.IDS (old layout files / export codes / profiles read exactly as
    before; 0.3.11 ignores the id). Default ON, t 0,130 (top centre, under the vanilla compass + boss bar), box 180 x 34 at 100%.
  - ONE source of truth: SkyySkills 0.4.13's bridge Function skill:fn:combat apply(UUID) -> Long ms left in combat (0 = out of combat;
    the in-combat Mana regen's rule, vanilla NoDamageTaken 6 s). The HUD never decides combat itself.
      in combat      "In combat" + "4s" (whole seconds rounded up, max 99) in red #ff6b6b (the vanilla error red = skyyui
                     COLOR["error"]; a colour picked in the widget's Settings replaces it) + under them the vanilla ProgressBar
                     (Common/ProgressBar.png track + Common/ProgressBarFill.png fill, the markup SkyyUiProbe proved on a page,
                     without the Effect glow - like the vanilla HUD Mana bar), Value = ms left / the window, clamped 0-1
                     (window = SkyySkills 0.4.13's apply("window") = the condition's own Delay; 6000 if it gives no answer)
      out of combat  hidden (default) or a grey #8b949e "Out of combat" line, no bar: Settings row "Out of combat  Hide / Show"
                     (WLayout.opt: Hide = true = the default, so a default Combat widget keeps the 6-field layout line)
      no skill:fn:combat (SkyySkills missing or older than 0.4.13): hidden on the HUD (the Party / Guild / Skills convention); the
                     editor + Settings preview show "Needs SkyySkills 0.4.13"
  - refresh = the existing 1 s HUD tick (no new timer): in combat at most two tiny Set commands per tick (the countdown .Text when the
    second changes + #SkyyWCombatBar.Value as a float) inside the update packet the tick sends anyway; nothing out of combat. Entering
    / leaving combat = a SHAPE change (C0 / CI / CO) = the 0.3.8 shape re-send (at most once per 1.5 s) + the 0.3.9 confirm send.
  - shape-driven like Party / Guild / Skills; FLAT markup (labels + the bar are direct children of the widget Group).
Harness: python SkyyHud/test_skyyhud_0.3.12.py (bare JVM, see its docstring).
To regenerate, delete SkyyHud/build_skyyhud_0.3.12.py first (the script refuses to overwrite it).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.11.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.12.py")
assert not os.path.exists(dst), "refusing to overwrite " + dst
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


# ---------------- docstring + version ----------------
rep('''"""SkyyHud 0.3.11 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.11.py            -> SkyyHud/SkyyHud-0.3.11.jar
       (deploys only through tools/deploy_set.py - never pass --deploy here)
0.3.11 (generated by tools/hud_0_3_11_patch.py from 0.3.10): the SKILLS widget''', '''"""SkyyHud 0.3.12 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.12.py            -> SkyyHud/SkyyHud-0.3.12.jar
       (deploys only through tools/deploy_set.py - never pass --deploy here)
0.3.12 (generated by tools/hud_0_3_12_patch.py from 0.3.11): the COMBAT INDICATOR widget (Skyy 2026-10-02: "add a widget for combat
  indicator too. goes red when in combat. and either do a small count down, or use the animation to indicate how close you are to
  being out of combat"; OPEN-QUESTIONS LOCKED 2026-10-02: red, a small countdown AND a shrinking bar, out of combat hidden by default).
  - New widget id Combat ("Combat Indicator"), APPENDED to Widgets.IDS (0.3.11 layout files, export codes and profiles read exactly as
    before; 0.3.11 ignores the id). Default ON at t 0,130 (top centre, under the vanilla compass and boss bar - BossBar.ui Top 57 +
    66), box 180 x 34 at 100% (one text row + the bar; 26 high without the bar; every clamp keeps the 34 px box on screen).
  - The rule is SkyySkills' own (one source of truth, the in-combat Mana regen's): bridge Function skill:fn:combat apply(UUID) -> Long
    ms left in combat (0 = out of combat; vanilla: 6 s after taking damage). The HUD never decides combat itself.
      in combat      "In combat" left + the countdown "4s" right (whole seconds rounded up, at most 99) in RED #ff6b6b (the vanilla
                     error red, skyyui COLOR["error"]; a colour picked in the widget's Settings replaces it; glow "Same" follows it),
                     and under them a shrinking bar: the vanilla ProgressBar (track Common/ProgressBar.png, fill
                     Common/ProgressBarFill.png - the markup SkyyUiProbe proved in game on a page, without its Effect glow, like the
                     vanilla HUD Mana bar), Value = ms left / the window (clamped 0-1), 168 x 6 px at 100%. The window is
                     SkyySkills' own too: apply("window") -> Long ms (0.4.13: the Delay of the same NoDamageTaken condition); a
                     Function without that answer (exception / no number / outside 1-600 s) -> 6000, vanilla's 6 s.
      out of combat  hidden (the default) or a quiet grey #8b949e "Out of combat" line without the bar (26 px box): the widget's
                     Settings row "Out of combat  Hide / Show" (WLayout.opt: Hide = opt true = the default, so a default Combat
                     widget keeps the 6-field layout line; Show = the existing 12th field ",0").
      no skill:fn:combat (SkyySkills missing or older than 0.4.13): hidden on the HUD (the Party / Guild / Skills convention for a
                     widget whose mod is absent); the editor and the Settings preview show "Needs SkyySkills 0.4.13" so it can still
                     be placed and styled. A Function that throws or answers no number counts as out of combat.
  - Refresh: the existing 1 s HUD tick (no new timer, no new thread). In combat a tick sends at most two tiny Set commands - the
    countdown .Text (when the whole second changes) and #SkyyWCombatBar.Value (a float) - inside the update packet the tick sends
    anyway; out of combat nothing is sent. Entering / leaving combat changes the widget's SHAPE (C0 hidden, CI in combat, CO the grey
    line) = the 0.3.8 shape re-send (the whole HUD, at most once per 1.5 s) + the 0.3.9 confirm send about 2 s later, exactly like a
    party join. The tick asks skill:fn:combat once a second per player with the widget ON (+ once for the window while in combat; off
    the world thread: SkyySkills 0.4.13 answers from memory, any thread, never throws); a widget switched OFF costs nothing.
  - Why a ProgressBar may sit in the HUD: HUD and page documents are the same CustomUICommand list (CustomUIHud.update -> CustomHud
    packet, CustomUIPage.sendUpdate -> CustomPage packet, both from UICommandBuilder.getCommands()); the vanilla HUD's own Health,
    Stamina, Mana, Oxygen and boss bars are ProgressBar elements (Client/Data/Game/Interface/InGame/Hud); EndlessLeveling's server
    HUD drives a ProgressBar with b.set("#ProgressBar.Value"); the inline ProgressBar + b.set float Value is proven in game on a page
    (SkyyUiProbe 2026-09-30). UNVERIFIED in game: the bar inside OUR inline HUD document (the first combat after the deploy shows it).
  - Settings page (Combat only): the Background row carries "Out of combat  Hide / Show" (the Party / Guild option row's place, ids
    and opton / optoff payloads) and a hint; the Preview draws the text in the widget's real colour. 1500 x 790 like the others.
  - Unchanged: every 0.3.11 widget's markup, texts and editor behaviour, the layout / code / profile format, commands, permissions,
    the admin rows (Server Setup -> HUD), the config file. No new config row, command or player switch.
0.3.11 (generated by tools/hud_0_3_11_patch.py from 0.3.10): the SKILLS widget''')
rep('''VERSION = "0.3.11"''', '''VERSION = "0.3.12"''')

# ---------------- the widget id + defaults + the Combat constants ----------------
rep('''IDS = ["Coords", "Zone", "Gclock", "Rclock", "Day", "Session", "Online", "Coins", "Party", "Guild", "Skills"]''',
    '''IDS = ["Coords", "Zone", "Gclock", "Rclock", "Day", "Session", "Online", "Coins", "Party", "Guild", "Skills", "Combat"]''')
rep('''assert (SKL_TP, SKL_ROW) == (3, 20), "Widgets.bodyH (not an f-string) spells the Skills row maths out as 3 / 20"
''', '''assert (SKL_TP, SKL_ROW) == (3, 20), "Widgets.bodyH (not an f-string) spells the Skills row maths out as 3 / 20"
# 0.3.12 COMBAT INDICATOR widget (OPEN-QUESTIONS LOCKED 2026-10-02): default ON at the top centre, under the vanilla compass and boss
# bar (BossBar.ui Top 57, 66 high); one text row (name left, countdown right) and, in combat, the vanilla ProgressBar under it
DEFAULTS["Combat"] = (True, "t", 0, 130)
LABELS["Combat"] = "Combat Indicator"
CMB_TP, CMB_ROW, CMB_BAR, CMB_BP, CMB_VW, CMB_FS = 3, 20, 6, 5, 40, 12   # top pad, text row, bar, pad under the bar, countdown column, font
SIZES["Combat"] = (180, CMB_TP + CMB_ROW + CMB_BAR + CMB_BP)
CMB_WIN = 6000            # ms: the fallback window (vanilla NoDamageTaken 6 s) when skill:fn:combat gives no apply("window") answer
CMB_RED = "#ff6b6b"       # the vanilla error red (tools/skyyui.py COLOR["error"]; the harness checks they agree)
CMB_TRACK, CMB_FILL = "Common/ProgressBar.png", "Common/ProgressBarFill.png"   # skyyui TEX progress / progressFill (probe page 6)
CMB_NEED = "Needs SkyySkills 0.4.13"
assert SIZES["Combat"] == (180, 34) and DEFAULTS["Combat"][1] == "t"
assert (CMB_TP, CMB_ROW, CMB_BAR, CMB_BP) == (3, 20, 6, 5), "Widgets.bodyH (not an f-string) spells the Combat maths out as 3 / 20 / 6 / 5"
''')

# ---------------- Widgets: fields + multi ----------------
rep('''wid.addField(CtField.make('public static final String GREYG = "#5a626b(0.35)";', wid))
''', '''wid.addField(CtField.make('public static final String GREYG = "#5a626b(0.35)";', wid))
# 0.3.12 Combat: the in-combat red, the window the bar is measured against, the stand-in line while skill:fn:combat is missing
wid.addField(CtField.make('public static final String CRED = "%s";' % CMB_RED, wid))
wid.addField(CtField.make("public static final long CWIN = %dL;" % CMB_WIN, wid))
wid.addField(CtField.make('public static final String CNEED = "%s";' % CMB_NEED, wid))
''')
rep('''public static boolean multi(String id) { return "Party".equals(id) || "Guild".equals(id) || "Skills".equals(id); }""", wid))''',
    '''public static boolean multi(String id) { return "Party".equals(id) || "Guild".equals(id) || "Skills".equals(id) || "Combat".equals(id); }""", wid))''')

# ---------------- Widgets: the Combat model (before model(), javassist order) ----------------
rep('''# model() is the MASK-LESS entry (Party / Guild pass their option here): for Skills it gives the BUILT-IN lines.''',
    '''# 0.3.12 Combat model: [0] SHAPE ("C0" hidden, "CI" in combat, "CO" the grey out-of-combat line; "S" = an editor / Settings sample,
# never a HUD shape), [1] headline (null = hidden), [2] name text, [3] countdown text ("" = none), [4] bar Value text "0.000" - "1.000"
# (null = no bar), [5] tone ("r" in combat = red or the picked colour, "g" grey, "n" the widget's own colour - the stand-in line).
# ONE source of truth: SkyySkills' bridge Function skill:fn:combat apply(UUID) -> Long ms left (0 = out of combat); the HUD only shows it.
wid.addMethod(CtNewMethod.make("""
public static boolean combatHave(java.util.Map b) {
  try { return b != null && b.get("skill:fn:combat") instanceof java.util.function.Function; } catch (Throwable t) { return false; }
}""", wid))
# ms left in combat: -1 = no skill:fn:combat (SkyySkills missing or older than 0.4.13), 0 = out of combat (also a Function that throws
# or answers no number), > 0 = in combat
wid.addMethod(CtNewMethod.make("""
public static long combatLeft(java.util.Map b, java.util.UUID u) {
  if (u == null) return -1L;
  Object f = null;
  try { f = b == null ? null : b.get("skill:fn:combat"); } catch (Throwable t) { f = null; }
  if (!(f instanceof java.util.function.Function)) return -1L;
  try {
    Object r = ((java.util.function.Function) f).apply(u);
    if (r instanceof Number) {
      long v = ((Number) r).longValue();
      return v > 0L ? v : 0L;
    }
  } catch (Throwable t) { }
  return 0L;
}""", wid))
# the countdown: whole seconds rounded up ("6s" right after a hit, "1s" in the last second), at most 99
wid.addMethod(CtNewMethod.make("""
public static String combatSecs(long ms) {
  long m = ms > 99000L ? 99000L : ms;
  long s = (m + 999L) / 1000L;
  if (s < 1L) s = 1L;
  return s + "s";
}""", wid))
# the whole window the bar is measured against: SkyySkills 0.4.13 also answers apply("window") -> Long ms (the Delay of the very
# NoDamageTaken condition the Mana regen tests - one source for the window too); a Function without it (an exception, no number, or a
# value outside 1 - 600 s) -> CWIN, vanilla's 6 s
wid.addMethod(CtNewMethod.make("""
public static long combatWin(java.util.Map b) {
  try {
    Object f = b == null ? null : b.get("skill:fn:combat");
    if (f instanceof java.util.function.Function) {
      Object r = ((java.util.function.Function) f).apply("window");
      if (r instanceof Number) {
        long w = ((Number) r).longValue();
        if (w >= 1000L && w <= 600000L) return w;
      }
    }
  } catch (Throwable t) { }
  return CWIN;
}""", wid))
# the bar: ms left / window, clamped 0 - 1, as fixed-point text with 3 decimals (inline Value and the change check; never 1.0E-4)
wid.addMethod(CtNewMethod.make("""
public static String combatBar(long ms, long win) {
  long w = win > 0L ? win : CWIN;
  long v;
  if (ms >= w) v = 1000L;
  else if (ms <= 0L) v = 0L;
  else v = (ms * 1000L + w / 2L) / w;
  if (v > 1000L) v = 1000L;
  String f = String.valueOf(v % 1000L);
  while (f.length() < 3) f = "0" + f;
  return (v / 1000L) + "." + f;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String[] combatModelU(java.util.UUID me, boolean hideOut) {
  String[] m = new String[6];
  m[0] = "C0";
  if (me == null) return m;
  java.util.Map b = bridge();
  long left = combatLeft(b, me);
  if (left < 0L) return m;
  if (left > 0L) {
    m[0] = "CI"; m[2] = "In combat"; m[3] = combatSecs(left); m[4] = combatBar(left, combatWin(b)); m[5] = "r";
    m[1] = m[2] + " " + m[3];
    return m;
  }
  if (hideOut) return m;
  m[0] = "CO"; m[2] = "Out of combat"; m[3] = ""; m[4] = null; m[5] = "g";
  m[1] = m[2];
  return m;
}""", wid))
# model() is the MASK-LESS entry (Party / Guild pass their option here): for Skills it gives the BUILT-IN lines.''')
rep('''    if ("Skills".equals(id)) return skillsModelU(pr.getUuid(), {PKG}.WLayout.LINES_DEF);
  }} catch (Throwable t) {{ }}
  if ("Skills".equals(id)) {{ String[] k = new String[{SKL_ARR}]; k[0] = "K0"; return k; }}''',
    '''    if ("Skills".equals(id)) return skillsModelU(pr.getUuid(), {PKG}.WLayout.LINES_DEF);
    if ("Combat".equals(id)) return combatModelU(pr.getUuid(), opt);
  }} catch (Throwable t) {{ }}
  if ("Skills".equals(id)) {{ String[] k = new String[{SKL_ARR}]; k[0] = "K0"; return k; }}
  if ("Combat".equals(id)) {{ String[] c = new String[6]; c[0] = "C0"; return c; }}''')
# editor / Settings stand-in while the Combat widget is hidden: the in-combat look as a sample, or the "needs SkyySkills" line
rep('''# editor / settings sample lines while not in a party / guild
wid.addMethod(CtNewMethod.make("""
public static String[] sampleU(String id, String me, boolean opt) {
  if ("Skills".equals(id)) return skillsSample();''', '''# 0.3.12: the Combat widget's editor / Settings stand-in while it is hidden: the in-combat look as a sample ("In combat 4s", bar
# 4 / 6 full) so it can be placed and styled, or "Needs SkyySkills 0.4.13" while skill:fn:combat is missing
wid.addMethod(CtNewMethod.make("""
public static String[] combatSample() {
  String[] m = new String[6];
  m[0] = "S";
  if (!combatHave(bridge())) { m[2] = CNEED; m[3] = ""; m[4] = null; m[5] = "n"; }
  else { m[2] = "In combat"; m[3] = "4s"; m[4] = combatBar(4000L, CWIN); m[5] = "r"; }
  m[1] = m[3].length() > 0 ? m[2] + " " + m[3] : m[2];
  return m;
}""", wid))
# editor / settings sample lines while not in a party / guild
wid.addMethod(CtNewMethod.make("""
public static String[] sampleU(String id, String me, boolean opt) {
  if ("Skills".equals(id)) return skillsSample();
  if ("Combat".equals(id)) return combatSample();''')
# linePairs: the Combat line is N0 / S0 (no title line)
rep('''  if (m != null && m.length > 1 && m[1] != null && "Skills".equals(id)) {
    for (int i = 0; i < com.skyy.hud.WLayout.LINE_N && 3 + 2 * i < m.length; i++) {''', '''  if (m != null && m.length > 3 && m[1] != null && "Combat".equals(id)) {
    a.add("N0"); a.add(m[2] == null ? "" : m[2]);
    a.add("S0"); a.add(m[3] == null ? "" : m[3]);
  } else if (m != null && m.length > 1 && m[1] != null && "Skills".equals(id)) {
    for (int i = 0; i < com.skyy.hud.WLayout.LINE_N && 3 + 2 * i < m.length; i++) {''')
# the drawn height (one formula with the same floored parts combatBody places its line and bar with)
rep('''  if ("Skills".equals(id)) { int kp = 3 * sc / 100; return kp + skillRows(m) * (20 * sc / 100) + kp; }
''', '''  if ("Skills".equals(id)) { int kp = 3 * sc / 100; return kp + skillRows(m) * (20 * sc / 100) + kp; }
  if ("Combat".equals(id)) { int cp = 3 * sc / 100; int cr = 20 * sc / 100; if (m != null && m.length > 4 && m[4] != null) { int cb = 6 * sc / 100; if (cb < 1) cb = 1; return cp + cr + cb + 5 * sc / 100; } return cp + cr + cp; }
''')

# ---------------- Widgets: textSrc with given colours (the Combat Settings preview) ----------------
rep('''# sel = "#<base>": sets the real label and its n glow copies''', r'''# 0.3.12: textSrc with the colours given (the Combat widget's Settings preview: red in combat / the picked colour, grey out of combat)
wid.addMethod(CtNewMethod.make(f"""
public static String textSrcC(String base, int w, int h, int fs, {PKG}.WLayout l, String color, String gcolor) {{
  StringBuilder sb = new StringBuilder();
  if (l.glow) {{
    int d = (fs * 3 + 12) / 24;
    if (d < 1) d = 1;
    int e = (d + 1) / 2;
    int[] ox = new int[] {{ -d, d, 0, 0, -e, e, -e, e }};
    int[] oy = new int[] {{ 0, 0, -d, d, -e, -e, e, e }};
    int iw = w - 2 * d; if (iw < 1) iw = 1;
    int ih = h - 2 * d; if (ih < 1) ih = 1;
    String gs = styleSrc(fs, l, gcolor);
    for (int k = 0; k < 8; k++) {{
      sb.append("Label #").append(base).append("G").append(k).append(" {{ Anchor: (Left: ").append(d + ox[k]).append(", Top: ").append(d + oy[k]).append(", Width: ").append(iw).append(", Height: ").append(ih).append("); Text: \\"\\"; ").append(gs).append(" }} ");
    }}
  }}
  sb.append("Label #").append(base).append("Txt {{ Anchor: (Full: 0); Text: \\"\\"; ").append(styleSrc(fs, l, color)).append(" }}");
  return sb.toString();
}}""", wid))
# sel = "#<base>": sets the real label and its n glow copies''')

# ---------------- Widgets: the Combat markup (FLAT: two labels + the bar, direct children of the widget Group) ----------------
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String multiBody(String id, String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  if ("Skills".equals(id)) return skillsBody(base, l, sc, m, minFs);''', r'''# 0.3.12 Combat colours: in combat the picked palette colour, or red #ff6b6b for "Default"; out of combat the quiet party grey
# (GREY / GREYG); the stand-in line the widget's own colour. Glow "Same" follows the colour actually drawn.
wid.addMethod(CtNewMethod.make(f"""
public static String combatColor({PKG}.WLayout l, String tone) {{
  if ("g".equals(tone)) return GREY;
  if ("r".equals(tone) && "def".equals(l.col)) return CRED;
  return hexOf(l.col);
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String combatGlow({PKG}.WLayout l, String tone) {{
  if ("g".equals(tone)) return GREYG;
  return ("def".equals(l.gcol) ? combatColor(l, tone) : hexOf(l.gcol)) + "(0.45)";
}}""", wid))
# one line at the top (name Start, countdown End - the Skills row look) and in combat the vanilla ProgressBar under it, inset like the
# text (6 px a side at 100%); the bar's Value is inline (first render) and b.set by HudMain.fill on every change
wid.addMethod(CtNewMethod.make(f"""
public static String combatBody(String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  int w = l.bw * sc / 100;
  int sp = 6 * sc / 100; int tp = {CMB_TP} * sc / 100;
  int rh = {CMB_ROW} * sc / 100; int vw = {CMB_VW} * sc / 100;
  int fs = {CMB_FS} * sc / 100; if (fs < minFs) fs = minFs;
  int iw = w - 2 * sp;
  String tone = (m == null || m.length < 6 || m[5] == null) ? "n" : m[5];
  String col = combatColor(l, tone);
  String gcol = combatGlow(l, tone);
  String v = (m == null || m.length < 4) ? null : m[3];
  boolean whole = v == null || v.length() == 0;
  StringBuilder sb = new StringBuilder();
  sb.append(lineSrc(base + "N0", sp, tp, whole ? iw : iw - vw, rh, fs, l, col, gcol, "Start"));
  sb.append(lineSrc(base + "S0", sp + iw - vw, tp, vw, rh, fs, l, col, gcol, "End"));
  if (m != null && m.length > 4 && m[4] != null) {{
    int bh = {CMB_BAR} * sc / 100; if (bh < 1) bh = 1;
    sb.append("ProgressBar #").append(base).append("Bar {{ Anchor: (Left: ").append(sp).append(", Top: ").append(tp + rh).append(", Width: ").append(iw).append(", Height: ").append(bh).append("); Background: \\"{CMB_TRACK}\\"; BarTexturePath: \\"{CMB_FILL}\\"; Value: ").append(m[4]).append("; }} ");
  }}
  return sb.toString();
}}""", wid))
# the bar Value text of a shown Combat model (null = no bar: hidden, out of combat, the stand-in, every other widget)
wid.addMethod(CtNewMethod.make("""
public static String barOf(String id, String[] m) {
  if (!"Combat".equals(id) || m == null || m.length < 5 || m[1] == null) return null;
  return m[4];
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String multiBody(String id, String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  if ("Combat".equals(id)) return combatBody(base, l, sc, m, minFs);
  if ("Skills".equals(id)) return skillsBody(base, l, sc, m, minFs);''')

# ---------------- HudMain.fill: the bar Value (a float set, only when it changed - the light per-second update) ----------------
rep('''          {PKG}.Widgets.setText(b, "#SkyyW" + ids[i] + pairs[k], gn, lt);
        }}
      }}
      continue;
    }}
    Object g = this.built.get(ids[i]);''', '''          {PKG}.Widgets.setText(b, "#SkyyW" + ids[i] + pairs[k], gn, lt);
        }}
      }}
      String bv = {PKG}.Widgets.barOf(ids[i], mm);
      if (bv != null) {{
        String bk = ids[i] + ":Bar";
        String bp = (String) this.last.get(bk);
        if (full || bp == null || !bp.equals(bv)) {{
          this.last.put(bk, bv);
          float fv = 0.0f;
          try {{ fv = Float.parseFloat(bv); }} catch (Throwable x) {{ fv = 0.0f; }}
          b.set("#SkyyW" + ids[i] + "Bar.Value", fv);
        }}
      }}
      continue;
    }}
    Object g = this.built.get(ids[i]);''')

# ---------------- SettingsPage: preview text, the "Out of combat" row, the preview colour ----------------
rep('''public String previewText() {{
  if ("Skills".equals(this.wid)) {{''', '''public String previewText() {{
  if ("Skills".equals(this.wid) || "Combat".equals(this.wid)) {{''')
rep(r'''    ev.addEventBinding({BT}.Activating, "#SkyySetOptOn", {EVD}.of("a", "opton"));
    ev.addEventBinding({BT}.Activating, "#SkyySetOptOff", {EVD}.of("a", "optoff"));
  }}
  b.appendInline("#SkyySet", "Group #SkyySetRow3 {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");''',
    r'''    ev.addEventBinding({BT}.Activating, "#SkyySetOptOn", {EVD}.of("a", "opton"));
    ev.addEventBinding({BT}.Activating, "#SkyySetOptOff", {EVD}.of("a", "optoff"));
  }} else if ("Combat".equals(this.wid)) {{
    // 0.3.12 Combat: what the widget shows out of combat - Hide (WLayout.opt true, the default) or Show (a grey Out of combat line);
    // the Party / Guild option row's place, ids and payloads (Background row = 1322 of the page's 1468 px inner width, as theirs)
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 60, Height: 44); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 250, Height: 44); Text: \\"Out of combat\\"; " + rl + " }}");
    b.appendInline("#SkyySetRow2", "TextButton #SkyySetOptOn {{ Anchor: (Width: 104, Height: 44); Text: \\"Hide\\"; " + (l.opt ? on : bs) + " }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 8, Height: 44); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRow2", "TextButton #SkyySetOptOff {{ Anchor: (Width: 104, Height: 44); Text: \\"Show\\"; " + (l.opt ? bs : on) + " }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 20, Height: 44); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 360, Height: 44); Text: \\"Show adds a grey line out of combat\\"; Style: (FontSize: 16, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
    ev.addEventBinding({BT}.Activating, "#SkyySetOptOn", {EVD}.of("a", "opton"));
    ev.addEventBinding({BT}.Activating, "#SkyySetOptOff", {EVD}.of("a", "optoff"));
  }}
  b.appendInline("#SkyySet", "Group #SkyySetRow3 {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");''')
rep('''  String text = previewText();
  int gn = {PKG}.Widgets.glowCount(l);
''', '''  String text = previewText();
  int gn = {PKG}.Widgets.glowCount(l);
  // 0.3.12 Combat: the preview in the colour the HUD draws (red in combat / the picked colour, grey out of combat)
  boolean cmb = "Combat".equals(this.wid);
  String ccol = null; String cglo = null;
  if (cmb) {{
    String tone = "r";
    try {{ String[] cv = {PKG}.Widgets.viewModel(this.wid, this.playerRef, l); if (cv != null && cv.length > 5 && cv[5] != null) tone = cv[5]; }} catch (Throwable x) {{ tone = "r"; }}
    ccol = {PKG}.Widgets.combatColor(l, tone);
    cglo = {PKG}.Widgets.combatGlow(l, tone);
  }}
''')
rep('''(l.bg ? "Background: #0b1524(0.72); " : "") + {PKG}.Widgets.textSrc(pv[j], pw, ph, fs, l) + " }}");''',
    '''(l.bg ? "Background: #0b1524(0.72); " : "") + (cmb ? {PKG}.Widgets.textSrcC(pv[j], pw, ph, fs, l, ccol, cglo) : {PKG}.Widgets.textSrc(pv[j], pw, ph, fs, l)) + " }}");''')

# ---------------- manifest description ----------------
rep('''"SkyyHud: customizable server-side HUD. 11 widgets incl. Party, Guild and Skills (Overall Level + the skill levels you pick), per-player layouts''',
    '''"SkyyHud: customizable server-side HUD. 12 widgets incl. Party, Guild, Skills (Overall Level + the skill levels you pick) and a Combat Indicator (red in combat with a countdown and a shrinking bar), per-player layouts''')

# ---------------- self-checks ----------------
assert s.count('"Combat"') >= 14
assert '"Skills", "Combat"]' in s, "Combat is appended to IDS (old codes / files keep their meaning)"
assert 'DEFAULTS["Combat"] = (True, "t", 0, 130)' in s and 'SIZES["Combat"] = (180, CMB_TP + CMB_ROW + CMB_BAR + CMB_BP)' in s
assert "if (\"Combat\".equals(id)) return combatModelU(pr.getUuid(), opt);" in s, "model(): Combat takes the layout's option (hide out of combat)"
assert s.count("skill:fn:combat") >= 3 and ".apply(u)" in s and '.apply("window")' in s, "the only combat source is SkyySkills' bridge Function"
assert 'b.set("#SkyyW" + ids[i] + "Bar.Value", fv);' in s, "the bar is a float Value set (the probe-proven overload), not a re-send"
assert s.count("#SkyySetOptOn") == 4 and s.count('"opton"') == 2, "the option row ids / payloads: Party / Guild + Combat"
assert "(cmb ? {PKG}.Widgets.textSrcC(" in s, "the Combat Settings preview draws the real colour"
assert 'Background: \\\\"{CMB_TRACK}\\\\"; BarTexturePath: \\\\"{CMB_FILL}\\\\"; Value: ' in s, "the probe-proven ProgressBar textures"
assert "EffectTexturePath" not in s.split("public static String combatBody(")[1].split('}}""", wid))')[0], "no Effect glow in the HUD bar"
# javassist order: helpers before their callers
assert s.index("public static boolean combatHave(") < s.index("public static long combatLeft(") < s.index(
    "public static String combatSecs(") < s.index("public static long combatWin(") < s.index("public static String combatBar(") < s.index(
    "public static String[] combatModelU(") < s.index("public static String[] model(") < s.index(
    "public static String[] combatSample(") < s.index("public static String[] sampleU("), "javassist order: Combat model helpers"
assert s.index("public static String hexOf(") < s.index("public static String textSrcC(") < s.index(
    "public static String lineSrc(") < s.index("public static String combatColor(") < s.index(
    "public static String combatGlow(") < s.index("public static String combatBody(") < s.index(
    "public static String barOf(") < s.index("public static String multiBody(") < s.index(
    "public boolean fill("), "javassist order: Combat markup helpers before multiBody / HudMain.fill"
assert s.index("public static String combatColor(") < s.index("boolean cmb = \"Combat\".equals(this.wid);"), "javassist order: SettingsPage"
assert "KEEP=10" in s and "KEEP=20" not in s
assert "--deploy" in s   # the old deploy block stays as it was (never used: tools/deploy_set.py is the only deploy path)

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
