"""Derive SkyyHud/build_skyyhud_0.3.11.py from the LIVE 0.3.10 (the SET pin; 0.3.10 is left untouched; line endings preserved).
0.3.11 = the SKILLS widget (Skyy, OPEN-QUESTIONS.md "Q&A with Skyy 2026-10-02" round 4: "a HUD WIDGET for the Overall Level and skills,
where each skill can be toggled on / off in the widget (show all, or just the class level, or Overall + Mining - any combo)"; round 9
build order: quick fixes + the skills HUD widget first).
  - new widget id Skills, appended to Widgets.IDS (old layout files / export codes / profiles read exactly as before; 0.3.10 ignores
    the id). Default ON, tl 8,544 (the left edge, about half way down - under the DEFAULT Guild box), box 180 x 206 at 100% (10
    lines max; clamps keep it on screen).
  - one line per shown entry, name left + level right (the Party row look): Overall Level (bridge skill:overall:<uuid>, SkyySkills'
    own Overall Level), Class skill (name = class:skill:<uuid> from SkyyClasses, level = that entry of skill:<uuid>), Mining,
    Foraging, Farming, Alchemy, Smithing, Cooking, Acrobatics, Exploration (entries of skill:<uuid>). Defaults: Overall + Class ON.
  - per player in the layout file: WLayout.lines (bit mask) + WLayout.ldef (built-in default, -1 = no lines); a 13th field only when
    the mask differs from the default (byte-identical files for every 0.3.10 widget and a default Skills widget).
  - Settings page (Skills only): "Lines" toggle rows + All on / Default; the last line that can show cannot be switched off.
  - bridge reads only (memory) on the 1 s tick; SkyySkills missing -> hidden on the HUD (Party / Guild convention), the editor and
    Settings preview show "Skills not installed"; SkyyClasses missing -> no Class skill line.
  - config kit: 1.1 from tools/skyycfg.py (picked up at this build) and KEEP=10 (OPEN-QUESTIONS "LOCKED 2026-09-25 (Skyy): old config
    file versions kept is 10").
Review fixes (2026-10-02; the review of the first 0.3.11 build passed it with 3 LOW + 8 INFO findings):
  - LOW 1: the Skills Settings page is 1500 x 940 (920 left 6 px spare under its rows: 894 px of rows + 20 padding; now 26 px, the
    other pages keep 790 with 22 px spare).
  - LOW 2: "Default" = the lines a NEW player starts with (Widgets.startLines: the server default layout's Skills mask when an admin
    set one and it shows a line here, else the built-in Overall Level + Class skill = what /skyyhud reset gives) and it is lit for
    exactly that mask. ldef (the built-in mask) still decides the file format.
  - LOW 3: without SkyyClasses (no bridge key class:list - every SkyyClasses version puts it once in setup() and never removes it) the
    Class skill line is left out instead of showing "Class skill  -" forever; the last-line rule counts only lines that can show
    (Widgets.skillsVis), the Settings hint then says "Class skill needs SkyyClasses", the hidden stand-in says "No lines to show".
  - INFO: "under the Guild widget" reworded (the left edge, about half way down); Widgets.model is noted as mask-less (every Skills
    caller asks modelL / viewModel); the harness skips H when the live Skyy_SkyyHud folder does not exist (clean checkout).
  - Kept on purpose (the safe option): the 0.3.9 confirm send also fires for the Skills widget (one extra full HUD packet 1.5-2.5 s
    after a join / world switch, never periodic) - the Party / Guild alignment fix covers the same flat markup.
Harness: python SkyyHud/test_skyyhud_0.3.11.py (bare JVM, see its docstring).
To regenerate, delete SkyyHud/build_skyyhud_0.3.11.py first (the script refuses to overwrite it).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.10.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.11.py")
assert not os.path.exists(dst), "refusing to overwrite " + dst
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


# ---------------- docstring + version ----------------
rep('''"""SkyyHud 0.3.10 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.10.py            -> SkyyHud/SkyyHud-0.3.10.jar
       (deploys only through tools/deploy_set.py - never pass --deploy here)
0.3.10 (generated by tools/hud_0_3_10_patch.py from 0.3.9): in-game admin config''', '''"""SkyyHud 0.3.11 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.11.py            -> SkyyHud/SkyyHud-0.3.11.jar
       (deploys only through tools/deploy_set.py - never pass --deploy here)
0.3.11 (generated by tools/hud_0_3_11_patch.py from 0.3.10): the SKILLS widget (Skyy, OPEN-QUESTIONS Q&A 2026-10-02 round 4: "a HUD
  widget for the Overall Level and skills, where each skill can be toggled on / off in the widget - show all, or just the class level,
  or Overall + Mining, any combo").
  - New widget id Skills, APPENDED to Widgets.IDS (0.3.10 layout files, export codes and profiles read exactly as before; 0.3.10
    ignores the new id). Default ON at tl 8,544 (the left edge, about half way down - under the DEFAULT Guild box at tl 8,444; moved
    Party / Guild boxes may sit elsewhere). Box 180 px wide; one line per shown entry, the name left and the level right (the Party
    row look): font 12 at 100%, 20 px rows, height 3 + 20 x lines + 3 (max 206 for all 10 lines - every clamp keeps that maximum box
    on screen, like Party / Guild).
  - Lines, in this order (bit k of the mask = line k):
      0 Overall Level  bridge skill:overall:<uuid> (Integer that SkyySkills 0.4.6+ publishes every second from its own Overall Level =
                       floor of the average of its overall.skills; the HUD never computes it); '-' until it is published
      1 Class skill    the CURRENT class's weapon skill: name = class:skill:<uuid> (SkyyClasses: Archery, Swordsmanship, Sorcery, Fury,
                       Divinity, Assassination, Shaman skill), level = that name's entry in skill:<uuid>; no class yet = "Class
                       skill  -"; SkyyClasses not installed (no bridge key class:list) = the line is LEFT OUT (review fix)
      2-9              Mining, Foraging, Farming, Alchemy, Smithing, Cooking, Acrobatics, Exploration (the /skills order): their
                       entries in skill:<uuid> ("Mining:12,Foraging:3,..." - SkyySkills' levelsOf, republished on every level up,
                       class change and profile switch)
    Defaults: Overall Level + Class skill ON, the rest OFF (mask 3). Labels are matched case-insensitively; a missing or broken entry
    shows '-'.
  - Bridge reads only (System.getProperties() skyy.bridge, memory): the 1 s HUD tick never calls a SkyySkills function, so it can never
    load a player file on the shared scheduler thread. SkyySkills missing (no skill:fn:level) -> the HUD hides the widget, the Party /
    Guild convention for a widget whose mod is absent; the editor and the Settings preview show one line "Skills not installed" so it
    can still be placed.
  - Shape-driven like Party / Guild: shape "K<n>" (n lines, "K0" = hidden). A class change or level up changes only texts (.Text sets on
    the 1 s tick); a different number of lines re-sends the whole HUD (the 0.3.8 shape rebuild + the 0.3.9 confirm send).
  - Storage (per player, layouts/<uuid>.properties; export codes, profiles and the server default layout carry it too): WLayout.lines
    (bit mask) + WLayout.ldef (the widget's built-in default; -1 = the widget has no lines). ser() writes a 13th field - after the
    five style fields and opt ("1"/"0") - ONLY when lines != ldef, so every 0.3.10 widget and a default Skills widget keep the exact
    0.3.10 format. parse() takes the built-in default when the field is missing, 0, negative or not a number; unknown (future) bits are
    kept. importCode copies ldef from Widgets.def like the box size.
  - Settings page (Skills only; 1500 x 940, other widgets keep 1500 x 790): two "Lines" rows of toggle buttons (lit = shown) + "All on"
    and "Default", and a hint row. The last line that can show cannot be switched off (Visible OFF hides the widget). "Default" = the
    lines a new player starts with (review fix). The Party / Guild option row is shown for Party / Guild only (as before). Toggles
    save the layout and re-send the HUD (the existing click path).
  - Unchanged: every 0.3.10 widget's markup, texts and editor behaviour, commands and permissions, the admin rows (Server Setup ->
    HUD), the layout / code / profile format of the old widgets. Config kit 1.1 (tools/skyycfg.py, picked up at this build) with
    KEEP=10 old config versions (OPEN-QUESTIONS LOCKED 2026-09-25; 0.3.10 kept 20). No new config row, command or player switch.
  Review fixes (same day; the review passed the first build with 3 LOW + 8 INFO findings):
  - Settings page 1500 x 940 (was 920): its rows take 894 px + 20 px padding, so 920 left 6 px spare under "< Back / Reset style";
    940 leaves 26 px (the other pages: 768 of 790, 22 px spare).
  - "Default" (Widgets.startLines) = the lines a NEW player starts with, the same lines /skyyhud reset gives: the server default
    layout's Skills mask when an admin set one and it shows at least one line here, else the built-in Overall Level + Class skill
    (mask 3). Lit for exactly that mask. WLayout.ldef stays the BUILT-IN mask, so the file format does not depend on the server
    default (a 13th field whenever lines != 3; changing the server default never changes a player's saved lines).
  - SkyyClasses not installed (no bridge key class:list; every SkyyClasses version since 0.1 puts it once in setup() and never
    removes it): the Class skill line is left out instead of "Class skill  -" forever. Widgets.skillsVis(bridge) = the lines that
    can show (all 10, or all but Class skill); the last-line rule (toggles) and "Default" count only those, the Settings hint ends
    "Class skill needs SkyyClasses", and a hidden widget's stand-in reads "No lines to show" (a mask with only lines this version
    does not know, or only Class skill without SkyyClasses). The shape depends only on the mask and the installed mods (no flapping).
    SkyySkills older than 0.4.6 (below the SET floor) has no skill:overall:<uuid>: its Overall line stays "-".
  - Kept on purpose (the safe option): the Skills widget is visible for everyone, so the 0.3.9 confirm send (one extra full HUD
    packet 1.5-2.5 s after the HUD appears or changes shape) now follows every join and world switch, not only party / guild members
    - never periodic; the Party / Guild alignment fix covers the same flat markup. Watch for a flash about 2 s after joining.
0.3.10 (generated by tools/hud_0_3_10_patch.py from 0.3.9): in-game admin config''')
rep('''VERSION = "0.3.10"''', '''VERSION = "0.3.11"''')

# ---------------- the widget id + defaults + the line table ----------------
rep('''IDS = ["Coords", "Zone", "Gclock", "Rclock", "Day", "Session", "Online", "Coins", "Party", "Guild"]''',
    '''IDS = ["Coords", "Zone", "Gclock", "Rclock", "Day", "Session", "Online", "Coins", "Party", "Guild", "Skills"]''')
rep('''SIZES = {"Party": (340, 116), "Guild": (260, 94)}
''', '''SIZES = {"Party": (340, 116), "Guild": (260, 94)}
# 0.3.11 SKILLS widget (OPEN-QUESTIONS Q&A 2026-10-02 R4): default ON at the left edge, about half way down (under the DEFAULT
# Guild box); one line per shown entry (name left, level right), 20 px rows with font 12 at 100%; the box height is the 10-line
# maximum (clamps keep it on screen)
SKILL_LINES = ["Overall Level", "Class skill", "Mining", "Foraging", "Farming", "Alchemy", "Smithing", "Cooking", "Acrobatics",
               "Exploration"]      # bit k of WLayout.lines = line k (APPEND-ONLY: saved masks keep their meaning)
SKILL_DEF_MASK = 3                 # Overall Level + Class skill (Skyy: the class skill + Overall shown, everything else off)
SKL_CLASS_BIT = 1 << SKILL_LINES.index("Class skill")   # review fix: the line left out while SkyyClasses is not installed
assert SKL_CLASS_BIT == 2, "skillsModelU treats line k == 1 as the class line"
SKL_TP, SKL_ROW, SKL_FS, SKL_VW = 3, 20, 12, 40     # top/bottom pad, row height, font, level column width (px at 100%)
SKL_ARR = 2 + 2 * len(SKILL_LINES)                   # model array: [0] shape, [1] headline, [2 + 2k] name, [3 + 2k] level
DEFAULTS["Skills"] = (True, "tl", 8, 544)
LABELS["Skills"] = "Skills"
SIZES["Skills"] = (180, SKL_TP + len(SKILL_LINES) * SKL_ROW + SKL_TP)
assert SIZES["Skills"] == (180, 206) and len(SKILL_LINES) <= 30 and 0 < SKILL_DEF_MASK < (1 << len(SKILL_LINES))
assert (SKL_TP, SKL_ROW) == (3, 20), "Widgets.bodyH (not an f-string) spells the Skills row maths out as 3 / 20"
''')
rep('''def _def_line(i, d):
    if i in SIZES:
        return '  if (id.equals("%s")) { %s.WLayout w = new %s.WLayout(%s, "%s", %d, %d, 100); w.bw = %d; w.bh = %d; return w; }' % (
            i, PKG, PKG, str(d[0]).lower(), d[1], d[2], d[3], SIZES[i][0], SIZES[i][1])''', '''def _def_line(i, d):
    if i in SIZES:
        # 0.3.11: the Skills widget also carries its built-in line mask (ldef) - Party / Guild lines are unchanged ("" extra)
        extra = (" w.ldef = %d; w.lines = %d;" % (SKILL_DEF_MASK, SKILL_DEF_MASK)) if i == "Skills" else ""
        return '  if (id.equals("%s")) { %s.WLayout w = new %s.WLayout(%s, "%s", %d, %d, 100); w.bw = %d; w.bh = %d;%s return w; }' % (
            i, PKG, PKG, str(d[0]).lower(), d[1], d[2], d[3], SIZES[i][0], SIZES[i][1], extra)''')

# ---------------- WLayout: lines + ldef, ser (13th field only when not default), parse ----------------
rep('''for f in ("public int bw;", "public int bh;", "public boolean opt;"):
    wl.addField(CtField.make(f, wl))
''', '''for f in ("public int bw;", "public int bh;", "public boolean opt;"):
    wl.addField(CtField.make(f, wl))
# 0.3.11: lines = the Skills widget's shown lines (bit mask), ldef = the widget's built-in mask (-1 = a widget without lines; copied
# from Widgets.def by parse / importCode like bw / bh) + the line table
for f in ("public int lines;", "public int ldef;"):
    wl.addField(CtField.make(f, wl))
wl.addField(CtField.make("public static final String[] LINE_LABELS = %s;" % jarr(SKILL_LINES), wl))
wl.addField(CtField.make("public static final int LINE_N = %d;" % len(SKILL_LINES), wl))
wl.addField(CtField.make("public static final int LINES_DEF = %d;" % SKILL_DEF_MASK, wl))
wl.addField(CtField.make("public static final int LINES_ALL = %d;" % ((1 << len(SKILL_LINES)) - 1), wl))
''')
rep('''  this.bw = 180; this.bh = 26; this.opt = true;
}""", wl))''', '''  this.bw = 180; this.bh = 26; this.opt = true;
  this.lines = -1; this.ldef = -1;
}""", wl))''')
rep('''public String ser() {
  String s = (en ? "1" : "0") + "," + anchor + "," + dx + "," + dy + "," + scale + "," + (bg ? "1" : "0");
  if (styleDefault() && opt) return s;
  s = s + "," + col + "," + (bold ? "1" : "0") + "," + (ital ? "1" : "0") + "," + (glow ? "1" : "0") + "," + gcol;
  if (opt) return s;
  return s + ",0";
}""", wl))''', '''public String ser() {
  boolean lx = ldef >= 0 && lines > 0 && lines != ldef;
  String s = (en ? "1" : "0") + "," + anchor + "," + dx + "," + dy + "," + scale + "," + (bg ? "1" : "0");
  if (styleDefault() && opt && !lx) return s;
  s = s + "," + col + "," + (bold ? "1" : "0") + "," + (ital ? "1" : "0") + "," + (glow ? "1" : "0") + "," + gcol;
  if (!lx) {
    if (opt) return s;
    return s + ",0";
  }
  return s + "," + (opt ? "1" : "0") + "," + lines;
}""", wl))''')
rep('''    if (def != null) {{ w.bw = def.bw; w.bh = def.bh; }}''',
    '''    if (def != null) {{ w.bw = def.bw; w.bh = def.bh; w.ldef = def.ldef; w.lines = def.ldef; }}''')
rep('''    if (p.length > 11) w.opt = !"0".equals(p[11].trim());
''', '''    if (p.length > 11) w.opt = !"0".equals(p[11].trim());
    if (p.length > 12) {{ try {{ int lv = Integer.parseInt(p[12].trim()); if (lv > 0) w.lines = lv; }} catch (Throwable x) {{ }} }}
''')

# ---------------- Widgets: multi + the Skills model (before model(), javassist order) ----------------
rep('''public static boolean multi(String id) { return "Party".equals(id) || "Guild".equals(id); }""", wid))''',
    '''public static boolean multi(String id) { return "Party".equals(id) || "Guild".equals(id) || "Skills".equals(id); }""", wid))''')
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String[] model(String id, {PR} pr, boolean opt) {{
  try {{
    if ("Party".equals(id)) return partyModelU(pr.getUuid(), worldName(pr), opt);
    if ("Guild".equals(id)) return guildModelU(pr.getUuid(), opt);
  }} catch (Throwable t) {{ }}
  String[] m = new String[17];
  m[0] = "Party".equals(id) ? "P0" : "G0";
  return m;
}}""", wid))
''', '''# 0.3.11 Skills model: [0] SHAPE "K<n>" ("K0" = hidden), [1] headline (first line "name level", null = hidden), [2 + 2k] name,
# [3 + 2k] level text of shown line k (null name = no line). Bridge reads only (memory): skill:fn:level present = SkyySkills loaded,
# skill:<uuid> = "Mining:12,Foraging:3,..." (SkyySkills levelsOf), skill:overall:<uuid> = Integer (SkyySkills' Overall Level, published
# every second), class:skill:<uuid> = the current class's weapon skill name (SkyyClasses). Never calls a Function (no file I/O here).
wid.addMethod(CtNewMethod.make("""
public static String skillVal(String[] parts, String label) {
  if (parts == null || label == null) return "-";
  String want = label.trim();
  if (want.length() == 0) return "-";
  for (int i = 0; i < parts.length; i++) {
    String p = parts[i];
    if (p == null) continue;
    int c = p.lastIndexOf(':');
    if (c <= 0) continue;
    if (!p.substring(0, c).trim().equalsIgnoreCase(want)) continue;
    long v = lnum(p.substring(c + 1), -1L);
    return v < 0L ? "-" : String.valueOf(v);
  }
  return "-";
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static boolean skillsHave(java.util.Map b) {
  try { return b != null && b.get("skill:fn:level") != null; } catch (Throwable t) { return false; }
}""", wid))
# review fix (LOW 3): SkyyClasses loaded = its bridge key class:list (put once in setup() by every SkyyClasses version since 0.1,
# never removed). Without SkyyClasses there is no class skill, so the Class skill line is left out (it would read "Class skill  -"
# forever). skillsVis = the lines that can show; the shape then depends only on the mask and the installed mods (never flaps), and
# the Settings page's last-line rule and "Default" count only these lines
wid.addMethod(CtNewMethod.make("""
public static boolean classesHave(java.util.Map b) {
  try { return b != null && b.get("class:list") != null; } catch (Throwable t) { return false; }
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int skillsVis(java.util.Map b) {{
  return classesHave(b) ? {PKG}.WLayout.LINES_ALL : {PKG}.WLayout.LINES_ALL - {SKL_CLASS_BIT};
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String[] skillsModelU(java.util.UUID me, int mask) {{
  String[] m = new String[{SKL_ARR}];
  m[0] = "K0";
  if (me == null) return m;
  java.util.Map b = bridge();
  if (!skillsHave(b)) return m;
  int vis = mask & skillsVis(b);
  String meS = me.toString();
  String lv = bstr(b, "skill:" + meS);
  String[] parts = null;
  if (lv != null) parts = splitc(lv, ',');
  String cls = bstr(b, "class:skill:" + meS);
  int n = 0;
  for (int k = 0; k < {PKG}.WLayout.LINE_N; k++) {{
    if ((vis & (1 << k)) == 0) continue;
    String name = {PKG}.WLayout.LINE_LABELS[k];
    String val = "-";
    if (k == 0) {{
      long o = lnum(bstr(b, "skill:overall:" + meS), -1L);
      val = o < 0L ? "-" : String.valueOf(o);
    }} else if (k == 1) {{
      if (cls != null && cls.trim().length() > 0) {{ name = cut(cls, 16); val = skillVal(parts, cls); }}
    }} else val = skillVal(parts, name);
    m[2 + 2 * n] = name;
    m[3 + 2 * n] = val;
    n++;
  }}
  if (n == 0) return m;
  m[0] = "K" + n;
  m[1] = m[2] + " " + m[3];
  return m;
}}""", wid))
# model() is the MASK-LESS entry (Party / Guild pass their option here): for Skills it gives the BUILT-IN lines. Every Skills caller
# in this jar asks with the player's layout instead - modelL (HUD build / fill) and viewModel (editor, Settings preview) - and text()
# never reaches its multi-line branch for Skills (fill, appendPreviews and previewText handle the multi-line widgets first).
wid.addMethod(CtNewMethod.make(f"""
public static String[] model(String id, {PR} pr, boolean opt) {{
  try {{
    if ("Party".equals(id)) return partyModelU(pr.getUuid(), worldName(pr), opt);
    if ("Guild".equals(id)) return guildModelU(pr.getUuid(), opt);
    if ("Skills".equals(id)) return skillsModelU(pr.getUuid(), {PKG}.WLayout.LINES_DEF);
  }} catch (Throwable t) {{ }}
  if ("Skills".equals(id)) {{ String[] k = new String[{SKL_ARR}]; k[0] = "K0"; return k; }}
  String[] m = new String[17];
  m[0] = "Party".equals(id) ? "P0" : "G0";
  return m;
}}""", wid))
# 0.3.11: the model a LAYOUT asks for - the Skills widget uses the layout's line mask, Party / Guild their option (as model() always did)
wid.addMethod(CtNewMethod.make(f"""
public static String[] modelL(String id, {PR} pr, {PKG}.WLayout l) {{
  if (!"Skills".equals(id)) return model(id, pr, l == null || l.opt);
  try {{ return skillsModelU(pr.getUuid(), l == null || l.lines <= 0 ? {PKG}.WLayout.LINES_DEF : l.lines); }} catch (Throwable t) {{ }}
  String[] k = new String[{SKL_ARR}];
  k[0] = "K0";
  return k;
}}""", wid))
# editor / Settings stand-in while the Skills widget is hidden: SkyySkills missing, or no selected line can show (a mask with only
# lines this version does not know, or only Class skill while SkyyClasses is not installed)
wid.addMethod(CtNewMethod.make(f"""
public static String[] skillsSample() {{
  String[] k = new String[{SKL_ARR}];
  k[0] = "S";
  String t = skillsHave(bridge()) ? "No lines to show" : "Skills not installed";
  k[1] = t; k[2] = t; k[3] = "";
  return k;
}}""", wid))
''')
rep('''public static String[] sampleU(String id, String me, boolean opt) {
  if (me == null || me.trim().length() == 0) me = "You";''', '''public static String[] sampleU(String id, String me, boolean opt) {
  if ("Skills".equals(id)) return skillsSample();
  if (me == null || me.trim().length() == 0) me = "You";''')
# linePairs: the Skills lines are N<k> / S<k> (no title line)
rep('''public static String[] linePairs(String id, String[] m) {
  java.util.ArrayList a = new java.util.ArrayList();
  if (m != null && m.length > 1 && m[1] != null) {
    a.add("T"); a.add(m[1]);''', '''public static String[] linePairs(String id, String[] m) {
  java.util.ArrayList a = new java.util.ArrayList();
  if (m != null && m.length > 1 && m[1] != null && "Skills".equals(id)) {
    for (int i = 0; i < com.skyy.hud.WLayout.LINE_N && 3 + 2 * i < m.length; i++) {
      if (m[2 + 2 * i] == null) break;
      a.add("N" + i); a.add(m[2 + 2 * i]);
      a.add("S" + i); a.add(m[3 + 2 * i] == null ? "" : m[3 + 2 * i]);
    }
  } else if (m != null && m.length > 1 && m[1] != null) {
    a.add("T"); a.add(m[1]);''')
# rows + height (one formula with the same floored parts skillsBody places its lines with)
rep('''wid.addMethod(CtNewMethod.make("""
public static int bodyH(String id, String[] m, int sc) {
  int tp = 3 * sc / 100; int th = 20 * sc / 100; int rh = 18 * sc / 100;''', '''wid.addMethod(CtNewMethod.make("""
public static int skillRows(String[] m) {
  if (m == null) return 0;
  int n = 0;
  for (int i = 0; i < com.skyy.hud.WLayout.LINE_N && 3 + 2 * i < m.length; i++) { if (m[2 + 2 * i] == null) break; n = i + 1; }
  return n;
}""", wid))
# 0.3.11: the Skills height = SKL_TP (3) + rows x SKL_ROW (20) + SKL_TP, the floored parts skillsBody places its lines with (the two
# numbers are asserted where SKL_TP / SKL_ROW are defined; this method is not an f-string)
wid.addMethod(CtNewMethod.make("""
public static int bodyH(String id, String[] m, int sc) {
  if ("Skills".equals(id)) { int kp = 3 * sc / 100; return kp + skillRows(m) * (20 * sc / 100) + kp; }
  int tp = 3 * sc / 100; int th = 20 * sc / 100; int rh = 18 * sc / 100;''')
# markup (FLAT, the 0.3.9 lineSrc structure: name Start, level End; an empty level gives the name the whole width - the stand-in line)
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String multiBody(String id, String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  if ("Party".equals(id)) return partyBody(base, l, sc, m, minFs);
  return guildBody(base, l, sc, m, minFs);
}}""", wid))''', '''wid.addMethod(CtNewMethod.make(f"""
public static String skillsBody(String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  int w = l.bw * sc / 100;
  int sp = 6 * sc / 100; int tp = {SKL_TP} * sc / 100;
  int rh = {SKL_ROW} * sc / 100; int vw = {SKL_VW} * sc / 100;
  int fs = {SKL_FS} * sc / 100; if (fs < minFs) fs = minFs;
  int n = skillRows(m);
  StringBuilder sb = new StringBuilder();
  String col = hexOf(l.col);
  String gcol = glowHex(l) + "(0.45)";
  int iw = w - 2 * sp;
  for (int i = 0; i < n; i++) {{
    int y = tp + i * rh;
    String v = m[3 + 2 * i];
    boolean whole = v == null || v.length() == 0;
    sb.append(lineSrc(base + "N" + i, sp, y, whole ? iw : iw - vw, rh, fs, l, col, gcol, "Start"));
    sb.append(lineSrc(base + "S" + i, sp + iw - vw, y, vw, rh, fs, l, col, gcol, "End"));
  }}
  return sb.toString();
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String multiBody(String id, String base, {PKG}.WLayout l, int sc, String[] m, int minFs) {{
  if ("Skills".equals(id)) return skillsBody(base, l, sc, m, minFs);
  if ("Party".equals(id)) return partyBody(base, l, sc, m, minFs);
  return guildBody(base, l, sc, m, minFs);
}}""", wid))''')
# the editor / Settings view model takes the LAYOUT (Skills needs its mask); Party / Guild get exactly the 0.3.10 calls
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String[] viewModel(String id, {PR} pr, boolean opt) {{
  String[] mm = null;
  try {{ mm = model(id, pr, opt); }} catch (Throwable t) {{ mm = null; }}
  if (!shown(mm)) mm = sample(id, pr, opt);
  return mm;
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int viewH(String id, {PKG}.WLayout l, {PR} pr) {{
  if (!multi(id)) return hMax(l);
  return bodyH(id, viewModel(id, pr, l.opt), l.scale);
}}""", wid))''', '''wid.addMethod(CtNewMethod.make(f"""
public static String[] viewModel(String id, {PR} pr, {PKG}.WLayout l) {{
  boolean opt = l == null || l.opt;
  String[] mm = null;
  try {{ mm = modelL(id, pr, l); }} catch (Throwable t) {{ mm = null; }}
  if (!shown(mm)) mm = sample(id, pr, opt);
  return mm;
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static int viewH(String id, {PKG}.WLayout l, {PR} pr) {{
  if (!multi(id)) return hMax(l);
  return bodyH(id, viewModel(id, pr, l), l.scale);
}}""", wid))''')

# ---------------- review fix (LOW 2): the Skills "Default" = the lines a new player starts with (after start(), javassist order) ----
rep('''    {PKG}.WLayout w = {PKG}.WLayout.parse((String) s, d);
    if (w == null || w == d) return d;
    clampToScreen(w);
    return w;
  }} catch (Throwable t) {{ return d; }}
}}""", wid))
''', '''    {PKG}.WLayout w = {PKG}.WLayout.parse((String) s, d);
    if (w == null || w == d) return d;
    clampToScreen(w);
    return w;
  }} catch (Throwable t) {{ return d; }}
}}""", wid))
# 0.3.11 review fix: the line mask a NEW player starts with (= what /skyyhud reset gives): the server default layout's mask when it
# shows at least one line that can show here (Widgets.skillsVis), else the built-in one (ldef). The Skills Settings page's "Default"
# button sets it and is lit for it. -1 = a widget without lines. WLayout.ldef stays the built-in mask (the file format).
wid.addMethod(CtNewMethod.make(f"""
public static int startLines(String id) {{
  {PKG}.WLayout d = def(id);
  if (d.ldef < 0) return d.ldef;
  try {{
    {PKG}.WLayout s = start(id);
    if (s != null && s.lines > 0 && (s.lines & skillsVis(bridge())) != 0) return s.lines;
  }} catch (Throwable t) {{ }}
  return d.ldef;
}}""", wid))
''')

# ---------------- config kit: KEEP 10 old versions (OPEN-QUESTIONS LOCKED 2026-09-25) ----------------
rep('''               RELOAD=None, KEEP=20, DEFAULTS={"config.properties": CONFIG_TEXT})''',
    '''               RELOAD=None, KEEP=10, DEFAULTS={"config.properties": CONFIG_TEXT})   # 0.3.11: KEEP 10 (LOCKED 2026-09-25)''')

# ---------------- LayoutStore.importCode: the line default comes from Widgets.def like the box size ----------------
rep('''    {PKG}.WLayout dd = {PKG}.Widgets.def(id);
    l.bw = dd.bw; l.bh = dd.bh;''', '''    {PKG}.WLayout dd = {PKG}.Widgets.def(id);
    l.bw = dd.bw; l.bh = dd.bh;
    l.ldef = dd.ldef; if (dd.ldef < 0) l.lines = -1; else if (l.lines <= 0) l.lines = dd.ldef;''')

# ---------------- HudMain: the model the layout asks for (Skills mask; Party / Guild unchanged) ----------------
rep('''      {PKG}.WLayout ml = ({PKG}.WLayout) {PKG}.LayoutStore.get(this.uuid).get(ids[i]);
      boolean opt = ml == null || ml.opt;
      String[] mm = null;
      if (full) mm = (String[]) this.models.get(ids[i]);
      if (mm == null) mm = {PKG}.Widgets.model(ids[i], pr, opt);''', '''      {PKG}.WLayout ml = ({PKG}.WLayout) {PKG}.LayoutStore.get(this.uuid).get(ids[i]);
      String[] mm = null;
      if (full) mm = (String[]) this.models.get(ids[i]);
      if (mm == null) mm = {PKG}.Widgets.modelL(ids[i], pr, ml);''')
rep('''      String[] mm = {PKG}.Widgets.model(ids[i], pr, l.opt);''', '''      String[] mm = {PKG}.Widgets.modelL(ids[i], pr, l);''')

# ---------------- EditorPage: view models by layout ----------------
rep('''      String[] mm = {PKG}.Widgets.viewModel(ids[i], this.playerRef, l.opt);''',
    '''      String[] mm = {PKG}.Widgets.viewModel(ids[i], this.playerRef, l);''')
rep('''    if (mw) {{ mm = (String[]) this.pm.get(ids[i]); if (mm == null) mm = {PKG}.Widgets.viewModel(ids[i], this.playerRef, l.opt); }}''',
    '''    if (mw) {{ mm = (String[]) this.pm.get(ids[i]); if (mm == null) mm = {PKG}.Widgets.viewModel(ids[i], this.playerRef, l); }}''')

# ---------------- SettingsPage: preview text, page height, option row (Party / Guild only), the Lines rows, the toggles ----------------
rep('''public String previewText() {{
  long join = System.currentTimeMillis();
  try {{ {PKG}.HudMain hm = ({PKG}.HudMain) this.plugin.huds.get(this.playerRef.getUuid()); if (hm != null) join = hm.joinMs; }} catch (Throwable t) {{ }}
  String t = null;''', '''public String previewText() {{
  if ("Skills".equals(this.wid)) {{
    try {{
      {PKG}.WLayout sl = ({PKG}.WLayout) {PKG}.LayoutStore.get(this.playerRef.getUuid()).get(this.wid);
      String[] sm = {PKG}.Widgets.viewModel(this.wid, this.playerRef, sl);
      if (sm != null && sm[1] != null && sm[1].length() > 0) return sm[1];
    }} catch (Throwable x) {{ }}
    return {PKG}.Widgets.label(this.wid);
  }}
  long join = System.currentTimeMillis();
  try {{ {PKG}.HudMain hm = ({PKG}.HudMain) this.plugin.huds.get(this.playerRef.getUuid()); if (hm != null) join = hm.joinMs; }} catch (Throwable t) {{ }}
  String t = null;''')
# review fix (LOW 1): the Skills page's rows take 748 + 2 x 58 (Lines) + 30 (hint) = 894 px + 20 px padding = 914 -> 940 high (26 px
# spare; 920 left 6). Every other page keeps 790 (768 used, 22 spare) - the harness sums every page's rows.
rep('''  b.appendInline((String) null, "Group #SkyySet {{ Anchor: (Width: 1500, Height: 790); Background: #0b1524(0.96); Padding: (Horizontal: 16, Vertical: 10); LayoutMode: Top; }}");''',
    '''  boolean skl = "Skills".equals(this.wid);
  b.appendInline((String) null, "Group #SkyySet {{ Anchor: (Width: 1500, Height: " + (skl ? 940 : 790) + "); Background: #0b1524(0.96); Padding: (Horizontal: 16, Vertical: 10); LayoutMode: Top; }}");''')
rep('''  if ({PKG}.Widgets.multi(this.wid)) {{
    boolean isP = "Party".equals(this.wid);''', '''  if ("Party".equals(this.wid) || "Guild".equals(this.wid)) {{
    boolean isP = "Party".equals(this.wid);''')
rep(r'''  b.appendInline("#SkyySet", "Label {{ Anchor: (Height: 34); Text: \\"Text style - make this widget stand out\\"; Style: (FontSize: 18, RenderBold: true, TextColor: #9fe0ff, VerticalAlignment: Center); }}");''',
    r'''  // 0.3.11 Skills: which lines the widget shows (lit = shown; the last line that can show stays on). Rows 200 + 5 x 178 + 20 + 150 = 1260 px.
  // "Default" = the lines a new player starts with (Widgets.startLines: the server default layout's, else the built-in), lit for exactly them.
  if (skl) {{
    String[] ln = {PKG}.WLayout.LINE_LABELS;
    int dm = {PKG}.Widgets.startLines(this.wid);
    boolean hasCls = {PKG}.Widgets.classesHave({PKG}.Widgets.bridge());
    for (int r = 0; r < 2; r++) {{
      String row = "SkyySetRowLn" + r;
      b.appendInline("#SkyySet", "Group #" + row + " {{ Anchor: (Height: 58); LayoutMode: Left; Padding: (Top: 12); }}");
      b.appendInline("#" + row, "Label {{ Anchor: (Width: 200, Height: 44); Text: \\"" + (r == 0 ? "Lines" : "") + "\\"; " + rl + " }}");
      for (int k = r * 5; k < r * 5 + 5 && k < ln.length; k++) {{
        b.appendInline("#" + row, "TextButton #SkyySetLn" + k + " {{ Anchor: (Width: 170, Height: 44); Text: \\"" + ln[k] + "\\"; " + ((l.lines & (1 << k)) != 0 ? on : bs) + " }}");
        b.appendInline("#" + row, "Label {{ Anchor: (Width: 8, Height: 44); Text: \\"\\"; }}");
        ev.addEventBinding({BT}.Activating, "#SkyySetLn" + k, {EVD}.of("a", "ln:" + k));
      }}
      b.appendInline("#" + row, "Label {{ Anchor: (Width: 20, Height: 44); Text: \\"\\"; }}");
      if (r == 0) {{
        b.appendInline("#" + row, "TextButton #SkyySetLnAll {{ Anchor: (Width: 150, Height: 44); Text: \\"All on\\"; " + ((l.lines & {PKG}.WLayout.LINES_ALL) == {PKG}.WLayout.LINES_ALL ? on : bs) + " }}");
        ev.addEventBinding({BT}.Activating, "#SkyySetLnAll", {EVD}.of("a", "lnall"));
      }} else {{
        b.appendInline("#" + row, "TextButton #SkyySetLnDef {{ Anchor: (Width: 150, Height: 44); Text: \\"Default\\"; " + (l.lines == dm ? on : bs) + " }}");
        ev.addEventBinding({BT}.Activating, "#SkyySetLnDef", {EVD}.of("a", "lndef"));
      }}
    }}
    b.appendInline("#SkyySet", "Group #SkyySetRowLnH {{ Anchor: (Height: 30); LayoutMode: Left; }}");
    b.appendInline("#SkyySetRowLnH", "Label {{ Anchor: (Width: 200, Height: 30); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRowLnH", "Label {{ Anchor: (Width: 1200, Height: 30); Text: \\"Click a line to show or hide it on your HUD - at least one line stays on - " + (hasCls ? "Class skill follows your class" : "Class skill needs SkyyClasses") + "\\"; Style: (FontSize: 16, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
  }}
  b.appendInline("#SkyySet", "Label {{ Anchor: (Height: 34); Text: \\"Text style - make this widget stand out\\"; Style: (FontSize: 18, RenderBold: true, TextColor: #9fe0ff, VerticalAlignment: Center); }}");''')
rep(r'''    else if (data.indexOf("\\"gcol:") >= 0) {{ String c = strAfter(data, "\\"gcol:"); if ({PKG}.WLayout.palIdx(c) >= 0) {{ l.gcol = c; l.glow = true; }} }}
    else return;''', r'''    else if (data.indexOf("\\"gcol:") >= 0) {{ String c = strAfter(data, "\\"gcol:"); if ({PKG}.WLayout.palIdx(c) >= 0) {{ l.gcol = c; l.glow = true; }} }}
    else if (data.indexOf("\\"ln:") >= 0) {{
      int k = jsonAfter(data, "ln:");
      if (l.ldef < 0 || k < 0 || k >= {PKG}.WLayout.LINE_N) return;
      int nm = l.lines ^ (1 << k);
      if ((nm & {PKG}.Widgets.skillsVis({PKG}.Widgets.bridge())) == 0) return;
      l.lines = nm;
    }}
    else if (data.indexOf("\\"lnall\\"") >= 0) {{ if (l.ldef < 0) return; l.lines = l.lines | {PKG}.WLayout.LINES_ALL; }}
    else if (data.indexOf("\\"lndef\\"") >= 0) {{ if (l.ldef < 0) return; l.lines = {PKG}.Widgets.startLines(this.wid); }}
    else return;''')

# ---------------- manifest description ----------------
rep('''"SkyyHud: customizable server-side HUD. 10 widgets incl. Party and Guild, per-player layouts''',
    '''"SkyyHud: customizable server-side HUD. 11 widgets incl. Party, Guild and Skills (Overall Level + the skill levels you pick), per-player layouts''')

# ---------------- self-checks ----------------
assert s.count('"Skills"') >= 10
assert "{PKG}.Widgets.model(ids[i]" not in s, "HudMain asks for the layout's model (modelL)"
assert s.count("{PKG}.Widgets.modelL(ids[i], pr, ") == 2, "fill + build use modelL"
assert s.count("l.opt)") == 1 and "model(id, pr, l == null || l.opt)" in s, "only modelL turns a layout into Party / Guild's option"
assert s.count("viewModel(") == 5, "viewModel: definition + viewH + prepView + appendPreviews + previewText"
assert "w.ldef = def.ldef; w.lines = def.ldef;" in s and "if (lv > 0) w.lines = lv;" in s, "parse: built-in default + 13th field"
assert "boolean lx = ldef >= 0 && lines > 0 && lines != ldef;" in s, "ser writes the mask only when it is not the default"
assert "l.ldef = dd.ldef;" in s, "importCode copies the line default"
assert s.count("#SkyySetLn") == 6 and s.count("\"ln:\" + k") == 1, "the Lines toggles + their bindings"
assert "if ((nm & {PKG}.Widgets.skillsVis({PKG}.Widgets.bridge())) == 0) return;" in s, "the last line that can show stays on"
# review fixes
assert "(skl ? 940 : 790)" in s and "(skl ? 920" not in s, "LOW 1: the Skills Settings page is 940 high"
assert "l.lines = {PKG}.Widgets.startLines(this.wid);" in s and "(l.lines == dm ? on : bs)" in s and "l.lines = l.ldef;" not in s, \
    "LOW 2: Default sets / lights the lines a new player starts with"
assert "int vis = mask & skillsVis(b);" in s and "if ((vis & (1 << k)) == 0) continue;" in s and '"No lines to show"' in s \
    and '"No lines selected"' not in s and 'b.get("class:list") != null' in s, "LOW 3: no Class skill line without SkyyClasses"
assert s.index("public static boolean classesHave(") < s.index("public static int skillsVis(") < s.index(
    "public static String[] skillsModelU("), "javassist order: classesHave / skillsVis before their callers"
assert s.index("public static {PKG}.WLayout start(String id)") < s.index("public static int startLines(") < s.index(
    "int dm = {PKG}.Widgets.startLines(this.wid);") < s.index("l.lines = {PKG}.Widgets.startLines(this.wid);"), \
    "javassist order: start -> startLines -> SettingsPage.build / handleDataEvent"
assert 'if ("Party".equals(this.wid) || "Guild".equals(this.wid)) {{' in s, "the Party / Guild option row stays theirs"
assert "KEEP=10" in s and "KEEP=20" not in s
assert s.index("public static String[] skillsModelU(") < s.index("public static String[] model(") < s.index(
    "public static String[] modelL(") < s.index("public static String[] skillsSample(") < s.index(
    "public static String[] sampleU(") < s.index("public static String[] viewModel("), "javassist order: helpers before callers"
assert s.index("public static int skillRows(") < s.index("public static int bodyH(") < s.index("public static String skillsBody(") < s.index(
    "public static String multiBody("), "javassist order: rows / body before their callers"
assert "skill:fn:addxp" not in s and ".apply(" not in s.split("public static String[] skillsModelU(")[1].split("}}\"\"\", wid))")[0], \
    "the Skills model never calls a bridge Function (no file I/O on the scheduler thread)"
assert "--deploy" in s   # the old deploy block stays as it was (never used: tools/deploy_set.py is the only deploy path)

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
