"""Derive SkyyHud/build_skyyhud_0.3.8.py from 0.3.7 (0.3.7 is left untouched; line endings preserved).
0.3.8 (Skyy, 2026-09-24: "make sure [the party and guild system is] all good to go, and that there are party and guild widgets
built and working for our test tonight"): two multi-line HUD widgets, Party and Guild, fed ONLY by the fixed bridge contract
(per PLAYER keys in System.getProperties().get("skyy.bridge")):
  SkyyParty  party:fn:members (Function UUID -> String[] member UUIDs, leader first, empty = no party), party:leader:<uuid>,
             party:name:<uuid>, party:stats:<uuid> = "hp,maxHp,stamina,maxStamina,mana,maxMana,worldName"
  SkyyGuilds guild:<uuid> (guild name, absent = no guild), guild:info:<uuid> = "name|tag|level|xp|xpForNext|onlineCount|memberCount|rank",
             guild:fn:online (Function UUID -> String[] online member display names)
Both widgets use the 0.3.7 style system (colour / bold / italic / glow, size, snap, visible, background, editor preview, export /
import / profiles). Old layouts load unchanged; the two new widgets default to visible and auto-hide while empty.
To regenerate, delete SkyyHud/build_skyyhud_0.3.8.py first (the script refuses to overwrite it).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.7.py")
dst = os.path.join(ROOT, "SkyyHud", "build_skyyhud_0.3.8.py")
assert not os.path.exists(dst), "refusing to overwrite " + dst
raw = open(src, encoding="utf8", newline="").read()
CR = chr(13)
LF = chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d != %d: %s" % (n, count, old[:90])
    s = s.replace(old, new)


# ---------------- docstring + version ----------------
rep('''"""SkyyHud 0.3.7 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.7.py            -> SkyyHud/SkyyHud-0.3.7.jar
       python build_skyyhud_0.3.7.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.7 SkyyHud" in the HUD mod world
''', '''"""SkyyHud 0.3.8 - build script (javassist via jpype).
Run:   python build_skyyhud_0.3.8.py            -> SkyyHud/SkyyHud-0.3.8.jar
       python build_skyyhud_0.3.8.py --deploy   -> also copies to Mods/SkyyHud.jar and enables "Skyy:0.3.8 SkyyHud" in the HUD mod world
0.3.8 (generated by tools/hud_0_3_8_patch.py from 0.3.7): Party + Guild widgets (Skyy 2026-09-24, for the first 2-player test).
  - Bridge contract (per PLAYER, System.getProperties().get("skyy.bridge")); the widgets read ONLY these keys:
      party:fn:members   Function apply(UUID viewer) -> String[] member UUID strings, leader first; empty = not in a party
      party:leader:<u>   leader UUID string          party:name:<u>  display name (fallback: first 8 chars of the UUID)
      party:stats:<u>    "hp,maxHp,stamina,maxStamina,mana,maxMana,worldName" (ints; ~1 s refresh; absent = offline)
      guild:<u>          guild name (absent = not in a guild)
      guild:info:<u>     "name|tag|level|xp|xpForNext|onlineCount|memberCount|rank" (a '|' inside the name is tolerated: the
                         last 7 fields are fixed, everything before them is the name)
      guild:fn:online    Function apply(UUID viewer) -> String[] online member display names
    Every read is wrapped (missing mod, wrong type, throwing Function = the widget stays hidden / shows '-'). Parsing uses
    char splits (no regex) and tolerant number parsing (ints, or doubles rounded).
  - PARTY widget (340 x 116 at 100%, default tl 8,320 = left middle): title 'Party (n)', then one line per member (max 5, the
    viewer always included - if the party is bigger than 5, the 5th line is the viewer): name (+ ' (L)' for the leader - the
    client font NunitoSans has no star glyph U+2605, checked in Client/Data/Shared/UI/Fonts/*.json) left, stats right:
      same world     'HP 83/100  ST 10/10  MP 20/20'  (MP only when maxMana > 0; 'Stamina and mana' OFF -> 'HP 83/100')
      another world  greyed, 'HP 83/100 - Hub' (world: 'Your Island' / 'Island' / 'Hub' / name cut to 14)
      no stats       greyed, 'offline'
    The viewer's own line is never greyed. Hidden while party:fn:members is empty/absent.
  - GUILD widget (260 x 94 at 100%, default tl 8,444 = under the party widget): '[TAG] Guild Name', 'Lv 3  (1,240 / 2,000 XP)'
    ('(1,240 XP)' when xpForNext <= 0), 'Online 2/5  |  Officer', and with 'Online names' ON up to 4 online names on 2 lines.
    Hidden while guild:<uuid> is absent.
  - Rendering: each line = an anonymous Group at its row + (with Glow) 8 glow copies + the real label, all inside the widget
    Group; ids #SkyyW<Party|Guild><T|N0-4|S0-4|L|O|A|B>Txt / ...G0..G7 (HUD) and #SkyyEPv<...> (editor). Glow uses the 0.3.7
    offsets; the real label sits in the same inset box as its copies so Start/End aligned text glows symmetrically. The
    background covers only the rows in use. Greyed lines use #8b949e (glow #5a626b at 0.35).
  - Shape-driven rebuild: HudMain remembers the SHAPE each multi-line widget was built with (hidden, number of lines, which
    member lines are grey). The 1 s tick only sets .Text of elements in the sent document; when a shape changes (join, leave,
    world switch, names row appears) the tick calls show() - a full HUD re-send, the same path as every editor click - at most
    once per 1.5 s. No .Visible / .Style toggles, no page updates.
  - Layout box size per widget: WLayout.bw/bh (180 x 26 for the eight 0.3.7 widgets, taken from Widgets.def(id)); every anchor,
    screen-position, clamp, snap, drag-cell and editor-preview calculation uses them. WLayout.opt = the widget option
    (Party: Stamina and mana, Guild: Online names; default ON) - saved as a 12th field only when OFF, so every 0.3.7 file /
    code / profile is read the same and 0.3.8 writes the 0.3.7 format for the eight old widgets. 0.3.7 ignores the new ids.
  - Editor: previews show the real lines when you are in a party / guild, otherwise sample lines ('Party (sample)',
    '[SKY] Sample Guild'); the selection outline shows the full box. Settings page: an extra ON/OFF on the Background row for
    the widget option; the style preview shows the widget title.
''')
rep('VERSION = "0.3.7"', 'VERSION = "0.3.8"')

# ---------------- ids / defaults / sizes ----------------
rep('IDS = ["Coords", "Zone", "Gclock", "Rclock", "Day", "Session", "Online", "Coins"]',
    'IDS = ["Coords", "Zone", "Gclock", "Rclock", "Day", "Session", "Online", "Coins", "Party", "Guild"]')
rep('''          "Day": "Day Counter", "Session": "Session Time", "Online": "Players Online", "Coins": "Coins"}
''', '''          "Day": "Day Counter", "Session": "Session Time", "Online": "Players Online", "Coins": "Coins"}
# 0.3.8 multi-line widgets: default position (left middle, guild under party; corner anchors only - LayoutStore.get turns any
# other anchor into a corner) and base box size at 100% (the eight one-line widgets stay 180 x 26)
DEFAULTS["Party"] = (True, "tl", 8, 320)
DEFAULTS["Guild"] = (True, "tl", 8, 444)
LABELS["Party"] = "Party"
LABELS["Guild"] = "Guild"
SIZES = {"Party": (340, 116), "Guild": (260, 94)}
''')

# ---------------- WLayout: box size + widget option ----------------
rep('''wl.addConstructor(CtNewConstructor.make("""
public WLayout(boolean en, String anchor, int dx, int dy, int scale) {
  this.en = en; this.anchor = anchor; this.dx = dx; this.dy = dy; this.scale = scale; this.bg = true;
  this.col = "def"; this.bold = true; this.ital = false; this.glow = false; this.gcol = "def";
}""", wl))
''', '''# 0.3.8: base box size at 100% (set from Widgets.def(id)) + the widget's own option (Party: stamina/mana, Guild: online names)
for f in ("public int bw;", "public int bh;", "public boolean opt;"):
    wl.addField(CtField.make(f, wl))
wl.addConstructor(CtNewConstructor.make("""
public WLayout(boolean en, String anchor, int dx, int dy, int scale) {
  this.en = en; this.anchor = anchor; this.dx = dx; this.dy = dy; this.scale = scale; this.bg = true;
  this.col = "def"; this.bold = true; this.ital = false; this.glow = false; this.gcol = "def";
  this.bw = 180; this.bh = 26; this.opt = true;
}""", wl))
''')
rep('''  if (styleDefault()) return s;
  return s + "," + col + "," + (bold ? "1" : "0") + "," + (ital ? "1" : "0") + "," + (glow ? "1" : "0") + "," + gcol;
''', '''  if (styleDefault() && opt) return s;
  s = s + "," + col + "," + (bold ? "1" : "0") + "," + (ital ? "1" : "0") + "," + (glow ? "1" : "0") + "," + gcol;
  if (opt) return s;
  return s + ",0";
''')
rep('''    {PKG}.WLayout w = new {PKG}.WLayout("1".equals(p[0].trim()), a, dx, dy, sc);
    if (p.length > 5) w.bg = "1".equals(p[5].trim());
''', '''    {PKG}.WLayout w = new {PKG}.WLayout("1".equals(p[0].trim()), a, dx, dy, sc);
    if (def != null) {{ w.bw = def.bw; w.bh = def.bh; }}
    if (p.length > 5) w.bg = "1".equals(p[5].trim());
''')
rep('''    if (p.length > 10) {{ String g = p[10].trim(); if (palIdx(g) >= 0) w.gcol = g; }}
''', '''    if (p.length > 10) {{ String g = p[10].trim(); if (palIdx(g) >= 0) w.gcol = g; }}
    if (p.length > 11) w.opt = !"0".equals(p[11].trim());
''')

# ---------------- Widgets.def with sizes ----------------
rep('''def_lines = "\\n".join('  if (id.equals("%s")) return new %s.WLayout(%s, "%s", %d, %d, 100);' % (i, PKG, str(d[0]).lower(), d[1], d[2], d[3]) for i, d in DEFAULTS.items())
''', '''def _def_line(i, d):
    if i in SIZES:
        return '  if (id.equals("%s")) { %s.WLayout w = new %s.WLayout(%s, "%s", %d, %d, 100); w.bw = %d; w.bh = %d; return w; }' % (
            i, PKG, PKG, str(d[0]).lower(), d[1], d[2], d[3], SIZES[i][0], SIZES[i][1])
    return '  if (id.equals("%s")) return new %s.WLayout(%s, "%s", %d, %d, 100);' % (i, PKG, str(d[0]).lower(), d[1], d[2], d[3])


def_lines = "\\n".join(_def_line(i, d) for i, d in DEFAULTS.items())
''')

# ---------------- every box-size calculation uses the layout's bw/bh ----------------
rep("int w = 180 * l.scale / 100; int h = 26 * l.scale / 100;", "int w = l.bw * l.scale / 100; int h = l.bh * l.scale / 100;", count=6)
rep("int cx = p[0] + (180 * l.scale / 100) / 2; int cy = p[1] + (26 * l.scale / 100) / 2;",
    "int cx = p[0] + (l.bw * l.scale / 100) / 2; int cy = p[1] + (l.bh * l.scale / 100) / 2;")
rep("int cw = (180 * l.scale / 100) * 2 / 3; int ch = (26 * l.scale / 100) * 2 / 3;",
    "int cw = (l.bw * l.scale / 100) * 2 / 3; int ch = (l.bh * l.scale / 100) * 2 / 3;")

# ---------------- Widgets: party / guild models (before text(), javassist order) ----------------
MODELS = r'''# 0.3.8 Party + Guild models. A model is a String[]: [0] = SHAPE (what the built markup depends on), [1] = title (null = hidden).
#   Party (17): [2+3k] name, [3+3k] stats text, [4+3k] "1" = greyed, k = 0..4 (null name = no line)
#   Guild (6):  [2] level line, [3] online line, [4] / [5] online-name rows (null = no row)
# Only the fixed bridge contract keys are read (see the docstring); the viewer's own world comes from the engine (Zone widget path).
wid.addField(CtField.make('public static final String GREY = "#8b949e";', wid))
wid.addField(CtField.make('public static final String GREYG = "#5a626b(0.35)";', wid))
wid.addMethod(CtNewMethod.make("""
public static boolean multi(String id) { return "Party".equals(id) || "Guild".equals(id); }""", wid))
wid.addMethod(CtNewMethod.make("""
public static boolean shown(String[] m) { return m != null && m.length > 1 && m[1] != null; }""", wid))
wid.addMethod(CtNewMethod.make("""
public static String cut(String s, int max) {
  if (s == null) return "";
  String t = s.trim();
  return t.length() <= max ? t : t.substring(0, max).trim();
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String bstr(java.util.Map b, String k) {
  if (b == null) return null;
  try { Object o = b.get(k); return o == null ? null : o.toString(); } catch (Throwable t) { return null; }
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String[] strArr(Object r) {
  if (r == null) return null;
  Object[] a = null;
  if (r instanceof Object[]) a = (Object[]) r;
  else if (r instanceof java.util.Collection) a = ((java.util.Collection) r).toArray();
  if (a == null) return null;
  String[] s = new String[a.length];
  for (int i = 0; i < a.length; i++) s[i] = a[i] == null ? "" : a[i].toString();
  return s;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String[] callArr(java.util.Map b, String key, java.util.UUID u) {
  try {
    Object f = b == null ? null : b.get(key);
    if (f instanceof java.util.function.Function) return strArr(((java.util.function.Function) f).apply(u));
  } catch (Throwable t) { }
  return null;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static long lnum(String s, long d) {
  if (s == null) return d;
  String t = s.trim();
  if (t.length() == 0) return d;
  try { return Long.parseLong(t); } catch (Throwable x) { }
  try { return Math.round(Double.parseDouble(t)); } catch (Throwable x) { }
  return d;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String[] splitc(String s, char c) {
  java.util.ArrayList out = new java.util.ArrayList();
  int st = 0;
  for (int i = 0; i < s.length(); i++) {
    if (s.charAt(i) == c) { out.add(s.substring(st, i)); st = i + 1; }
  }
  out.add(s.substring(st));
  String[] r = new String[out.size()];
  for (int i = 0; i < r.length; i++) r[i] = (String) out.get(i);
  return r;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String fmt(long v) {
  return java.text.NumberFormat.getIntegerInstance(java.util.Locale.US).format(v);
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String worldName({PR} pr) {{
  try {{
    java.util.UUID wu = pr.getWorldUuid();
    if (wu == null) return null;
    {WLD} w = {UNI}.get().getWorld(wu);
    return w == null ? null : w.getName();
  }} catch (Throwable t) {{ return null; }}
}}""", wid))
# a party member's world as a short friendly name (same rules as the Zone widget, without the region lookup)
wid.addMethod(CtNewMethod.make(f"""
public static String worldFriendly(String n, java.util.UUID viewer) {{
  if (n == null || n.length() == 0) return "?";
  if (n.startsWith("skyy-island-")) {{
    try {{ if (viewer != null && n.substring(12).equals(pkey(viewer))) return "Your Island"; }} catch (Throwable t) {{ }}
    return "Island";
  }}
  boolean hub = false;
  try {{ {WLD} d = {UNI}.get().getDefaultWorld(); hub = d != null && n.equals(d.getName()); }} catch (Throwable t) {{ hub = false; }}
  if (!hub) {{ try {{ String hw = hubWorld(); hub = hw != null && hw.equals(n); }} catch (Throwable t) {{ hub = false; }} }}
  if (hub) return "Hub";
  return shorten(n, 14);
}}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String[] partyModelU(java.util.UUID me, String myWorld, boolean opt) {
  String[] m = new String[17];
  m[0] = "P0";
  if (me == null) return m;
  java.util.Map b = bridge();
  String[] mem = callArr(b, "party:fn:members", me);
  if (mem == null || mem.length == 0) return m;
  String meS = me.toString();
  String leader = bstr(b, "party:leader:" + meS);
  if (leader == null || leader.trim().length() == 0) leader = mem[0];
  leader = leader == null ? "" : leader.trim();
  int n = mem.length;
  int shown = n < 5 ? n : 5;
  String[] sel = new String[shown];
  for (int i = 0; i < shown; i++) sel[i] = mem[i] == null ? "" : mem[i].trim();
  if (n > 5) {
    boolean found = false;
    for (int i = 0; i < shown; i++) if (meS.equalsIgnoreCase(sel[i])) found = true;
    if (!found) sel[4] = meS;
  }
  m[1] = "Party (" + n + ")";
  StringBuilder shape = new StringBuilder();
  shape.append("P").append(shown).append(":");
  for (int i = 0; i < shown; i++) {
    String us = sel[i];
    boolean self = meS.equalsIgnoreCase(us);
    String nm = bstr(b, "party:name:" + us);
    if (nm == null || nm.trim().length() == 0) nm = us.length() > 8 ? us.substring(0, 8) : us;
    nm = cut(nm, 14);
    if (leader.length() > 0 && us.equalsIgnoreCase(leader)) nm = nm + " (L)";
    String st = bstr(b, "party:stats:" + us);
    String line = "";
    boolean grey = false;
    if (st == null || st.trim().length() == 0) {
      line = "offline";
      grey = !self;
    } else {
      String[] p = splitc(st, ',');
      long hp = p.length > 0 ? lnum(p[0], 0L) : 0L;
      long mhp = p.length > 1 ? lnum(p[1], 0L) : 0L;
      long sta = p.length > 2 ? lnum(p[2], 0L) : 0L;
      long msta = p.length > 3 ? lnum(p[3], 0L) : 0L;
      long mp = p.length > 4 ? lnum(p[4], 0L) : 0L;
      long mmp = p.length > 5 ? lnum(p[5], 0L) : 0L;
      String w = "";
      if (p.length > 6) {
        StringBuilder wb = new StringBuilder();
        for (int j = 6; j < p.length; j++) { if (j > 6) wb.append(','); wb.append(p[j]); }
        w = wb.toString().trim();
      }
      boolean same = self || myWorld == null || w.length() == 0 || w.equals(myWorld);
      if (same) {
        line = "HP " + hp + "/" + mhp;
        if (opt) {
          line = line + "  ST " + sta + "/" + msta;
          if (mmp > 0L) line = line + "  MP " + mp + "/" + mmp;
        }
        grey = false;
      } else {
        line = "HP " + hp + "/" + mhp + " - " + worldFriendly(w, me);
        grey = true;
      }
    }
    m[2 + 3 * i] = nm;
    m[3 + 3 * i] = line;
    m[4 + 3 * i] = grey ? "1" : "0";
    shape.append(grey ? 'g' : 'n');
  }
  m[0] = shape.toString();
  return m;
}""", wid))
wid.addMethod(CtNewMethod.make("""
public static String[] guildModelU(java.util.UUID me, boolean opt) {
  String[] m = new String[6];
  m[0] = "G0";
  if (me == null) return m;
  java.util.Map b = bridge();
  String meS = me.toString();
  String gname = bstr(b, "guild:" + meS);
  if (gname == null || gname.trim().length() == 0) return m;
  String info = bstr(b, "guild:info:" + meS);
  String name = gname.trim(); String tag = ""; String lvl = "-"; long xp = -1L; long nx = -1L; String on = "-"; String tot = "-"; String rank = "";
  if (info != null) {
    String[] p = splitc(info, '|');
    if (p.length >= 8) {
      int k = p.length - 7;
      StringBuilder nb = new StringBuilder();
      for (int i = 0; i < k; i++) { if (i > 0) nb.append('|'); nb.append(p[i]); }
      if (nb.toString().trim().length() > 0) name = nb.toString().trim();
      tag = p[k].trim();
      if (p[k + 1].trim().length() > 0) lvl = p[k + 1].trim();
      xp = lnum(p[k + 2], -1L);
      nx = lnum(p[k + 3], -1L);
      if (p[k + 4].trim().length() > 0) on = p[k + 4].trim();
      if (p[k + 5].trim().length() > 0) tot = p[k + 5].trim();
      rank = p[k + 6].trim();
    }
  }
  m[1] = shorten(tag.length() > 0 ? "[" + tag + "] " + name : name, 28);
  String l2 = "Lv " + lvl;
  if (nx > 0L && xp >= 0L) l2 = l2 + "  (" + fmt(xp) + " / " + fmt(nx) + " XP)";
  else if (xp >= 0L) l2 = l2 + "  (" + fmt(xp) + " XP)";
  m[2] = l2;
  m[3] = "Online " + on + "/" + tot + (rank.length() > 0 ? "  |  " + rank : "");
  int rows = 0;
  if (opt) {
    String[] names = callArr(b, "guild:fn:online", me);
    if (names != null) {
      String ra = ""; String rb = ""; int c = 0;
      for (int i = 0; i < names.length && c < 4; i++) {
        String x = cut(names[i], 14);
        if (x.length() == 0) continue;
        if (c < 2) ra = ra.length() == 0 ? x : ra + ",  " + x;
        else rb = rb.length() == 0 ? x : rb + ",  " + x;
        c++;
      }
      if (ra.length() > 0) { m[4] = ra; rows = 1; }
      if (rb.length() > 0) { m[5] = rb; rows = 2; }
    }
  }
  m[0] = "G1:" + rows;
  return m;
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String[] model(String id, {PR} pr, boolean opt) {{
  try {{
    if ("Party".equals(id)) return partyModelU(pr.getUuid(), worldName(pr), opt);
    if ("Guild".equals(id)) return guildModelU(pr.getUuid(), opt);
  }} catch (Throwable t) {{ }}
  String[] m = new String[17];
  m[0] = "Party".equals(id) ? "P0" : "G0";
  return m;
}}""", wid))
# editor / settings sample lines while not in a party / guild
wid.addMethod(CtNewMethod.make("""
public static String[] sampleU(String id, String me, boolean opt) {
  if (me == null || me.trim().length() == 0) me = "You";
  if ("Party".equals(id)) {
    String[] m = new String[17];
    m[0] = "S"; m[1] = "Party (sample)";
    m[2] = cut(me, 14) + " (L)"; m[3] = opt ? "HP 83/100  ST 10/10" : "HP 83/100"; m[4] = "0";
    m[5] = "Friend"; m[6] = opt ? "HP 100/100  ST 7/10  MP 20/20" : "HP 100/100"; m[7] = "0";
    m[8] = "Alex"; m[9] = "HP 40/100 - Hub"; m[10] = "1";
    return m;
  }
  String[] g = new String[6];
  g[0] = "S"; g[1] = "[SKY] Sample Guild"; g[2] = "Lv 3  (1,240 / 2,000 XP)"; g[3] = "Online 2/5  |  Leader";
  if (opt) g[4] = cut(me, 14) + ",  Friend";
  return g;
}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String[] sample(String id, {PR} pr, boolean opt) {{
  String me = null;
  try {{ me = pr.getUsername(); }} catch (Throwable t) {{ me = null; }}
  return sampleU(id, me, opt);
}}""", wid))
# (element suffix, text) pairs of a shown model, in markup order: T, N0 S0 .. N4 S4 (Party) or T L O A B (Guild)
wid.addMethod(CtNewMethod.make("""
public static String[] linePairs(String id, String[] m) {
  java.util.ArrayList a = new java.util.ArrayList();
  if (m != null && m.length > 1 && m[1] != null) {
    a.add("T"); a.add(m[1]);
    if ("Party".equals(id)) {
      for (int i = 0; i < 5 && 4 + 3 * i < m.length; i++) {
        if (m[2 + 3 * i] == null) break;
        a.add("N" + i); a.add(m[2 + 3 * i]);
        a.add("S" + i); a.add(m[3 + 3 * i] == null ? "" : m[3 + 3 * i]);
      }
    } else if (m.length >= 6) {
      a.add("L"); a.add(m[2] == null ? "" : m[2]);
      a.add("O"); a.add(m[3] == null ? "" : m[3]);
      if (m[4] != null) { a.add("A"); a.add(m[4]); }
      if (m[5] != null) { a.add("B"); a.add(m[5]); }
    }
  }
  String[] r = new String[a.size()];
  for (int i = 0; i < r.length; i++) r[i] = (String) a.get(i);
  return r;
}""", wid))
'''
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String text(String id, {PR} pr, long joinMs) {{
''', MODELS + '''wid.addMethod(CtNewMethod.make(f"""
public static String text(String id, {PR} pr, long joinMs) {{
''')
# text() of a multi-line widget = its title (Settings style preview); sample title while hidden
rep('''    if (id.equals("Coords")) {{
      com.hypixel.hytale.math.vector.Transform t = pr.getTransform();
''', '''    if (multi(id)) {{
      String[] mm = model(id, pr, true);
      if (!shown(mm)) mm = sample(id, pr, true);
      return mm[1];
    }}
    if (id.equals("Coords")) {{
      com.hypixel.hytale.math.vector.Transform t = pr.getTransform();
''')

# ---------------- Widgets: multi-line rendering (after setText, before widgetSrc) ----------------
RENDER = r'''# 0.3.8 multi-line rendering. styleA = styleSrc with a chosen alignment. lineSrc = one text line at (x, y, w, h) inside the
# widget Group: an anonymous Group holding the 8 glow copies (0.3.7 offsets) and the real label; the real label sits in the
# same inset box as its copies, so Start/End aligned text is offset exactly like centred text. sc = effective size percent
# (HUD: layout scale; editor: scale x 2/3), minFs = smallest font (HUD 6, editor 5, as for the one-line widgets).
wid.addMethod(CtNewMethod.make(f"""
public static String styleA(int fs, {PKG}.WLayout l, String color, String align) {{
  return "Style: (FontSize: " + fs + ", RenderBold: " + (l.bold ? "true" : "false") + (l.ital ? ", RenderItalics: true" : "") + ", TextColor: " + color + ", HorizontalAlignment: " + align + ", VerticalAlignment: Center);";
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String lineSrc(String base, int x, int y, int w, int h, int fs, {PKG}.WLayout l, String color, String gcolor, String align) {{
  StringBuilder sb = new StringBuilder();
  int d = (fs * 3 + 12) / 24;
  if (d < 1) d = 1;
  int e = (d + 1) / 2;
  int iw = w - 2 * d; if (iw < 1) iw = 1;
  int ih = h - 2 * d; if (ih < 1) ih = 1;
  sb.append("Group {{ Anchor: (Left: ").append(x).append(", Top: ").append(y).append(", Width: ").append(w).append(", Height: ").append(h).append("); ");
  if (l.glow) {{
    int[] ox = new int[] {{ -d, d, 0, 0, -e, e, -e, e }};
    int[] oy = new int[] {{ 0, 0, -d, d, -e, -e, e, e }};
    String gs = styleA(fs, l, gcolor, align);
    for (int k = 0; k < 8; k++) {{
      sb.append("Label #").append(base).append("G").append(k).append(" {{ Anchor: (Left: ").append(d + ox[k]).append(", Top: ").append(d + oy[k]).append(", Width: ").append(iw).append(", Height: ").append(ih).append("); Text: \\"\\"; ").append(gs).append(" }} ");
    }}
  }}
  sb.append("Label #").append(base).append("Txt {{ Anchor: (Left: ").append(d).append(", Top: ").append(d).append(", Width: ").append(iw).append(", Height: ").append(ih).append("); Text: \\"\\"; ").append(styleA(fs, l, color, align)).append(" }} }} ");
  return sb.toString();
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String partyBody(String base, {PKG}.WLayout l, int sc, String[] m, boolean bg, int minFs) {{
  int w = l.bw * sc / 100;
  int sp = 6 * sc / 100; int tp = 3 * sc / 100;
  int th = 20 * sc / 100; int rh = 18 * sc / 100; int nw = 128 * sc / 100;
  int fsT = 12 * sc / 100; if (fsT < minFs) fsT = minFs;
  int fsR = 11 * sc / 100; if (fsR < minFs) fsR = minFs;
  int n = 0;
  for (int i = 0; i < 5 && 4 + 3 * i < m.length; i++) {{ if (m[2 + 3 * i] == null) break; n = i + 1; }}
  StringBuilder sb = new StringBuilder();
  if (bg) sb.append("Group {{ Anchor: (Left: 0, Top: 0, Width: " + w + ", Height: " + (tp + th + n * rh + tp) + "); Background: #0b1524(0.72); }} ");
  String col = hexOf(l.col);
  String gcol = glowHex(l) + "(0.45)";
  sb.append(lineSrc(base + "T", sp, tp, w - 2 * sp, th, fsT, l, col, gcol, "Start"));
  for (int i = 0; i < n; i++) {{
    boolean grey = "1".equals(m[4 + 3 * i]);
    String c = grey ? GREY : col;
    String g = grey ? GREYG : gcol;
    int y = tp + th + i * rh;
    sb.append(lineSrc(base + "N" + i, sp, y, nw, rh, fsR, l, c, g, "Start"));
    sb.append(lineSrc(base + "S" + i, sp + nw, y, w - 2 * sp - nw, rh, fsR, l, c, g, "End"));
  }}
  return sb.toString();
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String guildBody(String base, {PKG}.WLayout l, int sc, String[] m, boolean bg, int minFs) {{
  int w = l.bw * sc / 100;
  int sp = 6 * sc / 100; int tp = 3 * sc / 100;
  int th = 20 * sc / 100; int rh = 18 * sc / 100; int nh = 16 * sc / 100;
  int fsT = 12 * sc / 100; if (fsT < minFs) fsT = minFs;
  int fsR = 11 * sc / 100; if (fsR < minFs) fsR = minFs;
  int fsN = 10 * sc / 100; if (fsN < minFs) fsN = minFs;
  int rows = 0;
  if (m.length >= 6 && m[4] != null) rows = 1;
  if (m.length >= 6 && m[4] != null && m[5] != null) rows = 2;
  StringBuilder sb = new StringBuilder();
  if (bg) sb.append("Group {{ Anchor: (Left: 0, Top: 0, Width: " + w + ", Height: " + (tp + th + 2 * rh + rows * nh + tp) + "); Background: #0b1524(0.72); }} ");
  String col = hexOf(l.col);
  String gcol = glowHex(l) + "(0.45)";
  int iw = w - 2 * sp;
  sb.append(lineSrc(base + "T", sp, tp, iw, th, fsT, l, col, gcol, "Start"));
  sb.append(lineSrc(base + "L", sp, tp + th, iw, rh, fsR, l, col, gcol, "Start"));
  sb.append(lineSrc(base + "O", sp, tp + th + rh, iw, rh, fsR, l, col, gcol, "Start"));
  if (rows > 0) sb.append(lineSrc(base + "A", sp, tp + th + 2 * rh, iw, nh, fsN, l, col, gcol, "Start"));
  if (rows > 1) sb.append(lineSrc(base + "B", sp, tp + th + 2 * rh + nh, iw, nh, fsN, l, col, gcol, "Start"));
  return sb.toString();
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String multiBody(String id, String base, {PKG}.WLayout l, int sc, String[] m, boolean bg, int minFs) {{
  if ("Party".equals(id)) return partyBody(base, l, sc, m, bg, minFs);
  return guildBody(base, l, sc, m, bg, minFs);
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static String multiWidgetSrc(String id, {PKG}.WLayout l, String[] m) {{
  return "Group #SkyyW" + id + " {{ Anchor: " + anchorSrc(l) + "; " + multiBody(id, "SkyyW" + id, l, l.scale, m, l.bg, 6) + " }}";
}}""", wid))
wid.addMethod(CtNewMethod.make(f"""
public static void setLines({UCB} b, String sel, int n, String[] pairs) {{
  for (int k = 0; k + 1 < pairs.length; k += 2) setText(b, sel + pairs[k], n, pairs[k + 1]);
}}""", wid))
'''
rep('''wid.addMethod(CtNewMethod.make(f"""
public static String widgetSrc(String id, {PKG}.WLayout l) {{
''', RENDER + '''wid.addMethod(CtNewMethod.make(f"""
public static String widgetSrc(String id, {PKG}.WLayout l) {{
''')

# ---------------- LayoutStore.importCode: imported layouts get the widget's box size ----------------
rep('''    {PKG}.WLayout l = {PKG}.WLayout.parse(parts[i].substring(eq + 1), null);
    if (l == null) continue;
    {PKG}.Widgets.clampToScreen(l);
''', '''    {PKG}.WLayout l = {PKG}.WLayout.parse(parts[i].substring(eq + 1), null);
    if (l == null) continue;
    {PKG}.WLayout dd = {PKG}.Widgets.def(id);
    l.bw = dd.bw; l.bh = dd.bh;
    {PKG}.Widgets.clampToScreen(l);
''')

# ---------------- HudMain: shapes, multi-line fill, shape-driven rebuild ----------------
rep(r'''hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap built = new java.util.concurrent.ConcurrentHashMap();", hudc))
''', r'''hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap built = new java.util.concurrent.ConcurrentHashMap();", hudc))
# 0.3.8: multi-line widget id -> SHAPE string its markup was built for (only for enabled Party/Guild layouts, "P0"/"G0" = hidden),
# id -> the String[] model build() used (fill(full) reuses it so build and its first fill agree), last shape rebuild time
hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap shape = new java.util.concurrent.ConcurrentHashMap();", hudc))
hudc.addField(CtField.make("public final java.util.concurrent.ConcurrentHashMap models = new java.util.concurrent.ConcurrentHashMap();", hudc))
hudc.addField(CtField.make("public long lastRe;", hudc))
''')
rep(r'''public void fill({UCB} b, boolean full) {{
  {PR} pr = getPlayerRef();
  String[] ids = {PKG}.Widgets.IDS;
  for (int i = 0; i < ids.length; i++) {{
    Object g = this.built.get(ids[i]);
''', r'''public boolean fill({UCB} b, boolean full) {{
  {PR} pr = getPlayerRef();
  String[] ids = {PKG}.Widgets.IDS;
  boolean re = false;
  for (int i = 0; i < ids.length; i++) {{
    if ({PKG}.Widgets.multi(ids[i])) {{
      Object sh = this.shape.get(ids[i]);
      if (sh == null) continue;
      {PKG}.WLayout ml = ({PKG}.WLayout) {PKG}.LayoutStore.get(this.uuid).get(ids[i]);
      boolean opt = ml == null || ml.opt;
      String[] mm = null;
      if (full) mm = (String[]) this.models.get(ids[i]);
      if (mm == null) mm = {PKG}.Widgets.model(ids[i], pr, opt);
      if (!sh.equals(mm[0])) {{ re = true; continue; }}
      Object mg = this.built.get(ids[i]);
      if (mg == null) continue;
      int gn = ((Integer) mg).intValue();
      String[] pairs = {PKG}.Widgets.linePairs(ids[i], mm);
      for (int k = 0; k + 1 < pairs.length; k += 2) {{
        String key = ids[i] + ":" + pairs[k];
        String lt = pairs[k + 1];
        String lp = (String) this.last.get(key);
        if (full || lp == null || !lp.equals(lt)) {{
          this.last.put(key, lt);
          {PKG}.Widgets.setText(b, "#SkyyW" + ids[i] + pairs[k], gn, lt);
        }}
      }}
      continue;
    }}
    Object g = this.built.get(ids[i]);
''')
rep(r'''      {PKG}.Widgets.setText(b, "#SkyyW" + ids[i], ((Integer) g).intValue(), t);
    }}
  }}
}}""", hudc))
''', r'''      {PKG}.Widgets.setText(b, "#SkyyW" + ids[i], ((Integer) g).intValue(), t);
    }}
  }}
  return re;
}}""", hudc))
''')
rep(r'''  this.built.clear();
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || !l.en) continue;
    b.appendInline("#SkyyHudRoot", {PKG}.Widgets.widgetSrc(ids[i], l));
''', r'''  this.built.clear();
  this.shape.clear();
  this.models.clear();
  {PR} pr = getPlayerRef();
  for (int i = 0; i < ids.length; i++) {{
    {PKG}.WLayout l = ({PKG}.WLayout) m.get(ids[i]);
    if (l == null || !l.en) continue;
    if ({PKG}.Widgets.multi(ids[i])) {{
      String[] mm = {PKG}.Widgets.model(ids[i], pr, l.opt);
      this.shape.put(ids[i], mm[0]);
      this.models.put(ids[i], mm);
      if (!{PKG}.Widgets.shown(mm)) continue;
      b.appendInline("#SkyyHudRoot", {PKG}.Widgets.multiWidgetSrc(ids[i], l, mm));
      this.built.put(ids[i], Integer.valueOf({PKG}.Widgets.glowCount(l)));
      continue;
    }}
    b.appendInline("#SkyyHudRoot", {PKG}.Widgets.widgetSrc(ids[i], l));
''')
rep(r'''public synchronized void tick() {{
  try {{
    {UCB} b = new {UCB}();
    fill(b, false);
    if (b.getCommands().length > 0) update(false, b);
  }} catch (Throwable t) {{ }}
}}""", hudc))
''', r'''public synchronized void tick() {{
  try {{
    {UCB} b = new {UCB}();
    boolean re = fill(b, false);
    if (re) {{
      long now = System.currentTimeMillis();
      if (now - this.lastRe >= 1500L) {{ this.lastRe = now; show(); return; }}
    }}
    if (b.getCommands().length > 0) update(false, b);
  }} catch (Throwable t) {{ }}
}}""", hudc))
''')

# ---------------- editor previews: real lines, else sample lines ----------------
rep(r'''    String text;
    try {{ text = {PKG}.Widgets.text(ids[i], this.playerRef, join); }} catch (Throwable t) {{ text = {PKG}.Widgets.label(ids[i]); }}
    if (text == null) text = "";
    b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + {PKG}.Widgets.textSrc("SkyyEPv" + ids[i], cw, ch, fs, l) + " }}");
    {PKG}.Widgets.setText(b, "#SkyyEPv" + ids[i], {PKG}.Widgets.glowCount(l), text);
''', r'''    if ({PKG}.Widgets.multi(ids[i])) {{
      String[] mm = null;
      try {{ mm = {PKG}.Widgets.model(ids[i], this.playerRef, l.opt); }} catch (Throwable t) {{ mm = null; }}
      if (!{PKG}.Widgets.shown(mm)) mm = {PKG}.Widgets.sample(ids[i], this.playerRef, l.opt);
      b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + {PKG}.Widgets.multiBody(ids[i], "SkyyEPv" + ids[i], l, l.scale * 2 / 3, mm, l.bg, 5) + " }}");
      {PKG}.Widgets.setLines(b, "#SkyyEPv" + ids[i], {PKG}.Widgets.glowCount(l), {PKG}.Widgets.linePairs(ids[i], mm));
    }} else {{
    String text;
    try {{ text = {PKG}.Widgets.text(ids[i], this.playerRef, join); }} catch (Throwable t) {{ text = {PKG}.Widgets.label(ids[i]); }}
    if (text == null) text = "";
    b.appendInline("#SkyyEPrev", "Group #SkyyEPv" + ids[i] + " {{ Anchor: (Left: " + left + ", Top: " + top + ", Width: " + cw + ", Height: " + ch + "); " + (l.bg ? "Background: #0b1524(0.72); " : "") + {PKG}.Widgets.textSrc("SkyyEPv" + ids[i], cw, ch, fs, l) + " }}");
    {PKG}.Widgets.setText(b, "#SkyyEPv" + ids[i], {PKG}.Widgets.glowCount(l), text);
    }}
''')

# ---------------- Settings page: widget option on the Background row ----------------
rep(r'''  onOff(b, ev, "SkyySetRow2", "Background", "SkyySetBgOn", "SkyySetBgOff", l.bg, "bgon", "bgoff", bs, on);
''', r'''  onOff(b, ev, "SkyySetRow2", "Background", "SkyySetBgOn", "SkyySetBgOff", l.bg, "bgon", "bgoff", bs, on);
  if ({PKG}.Widgets.multi(this.wid)) {{
    boolean isP = "Party".equals(this.wid);
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 60, Height: 44); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 250, Height: 44); Text: \\"" + (isP ? "Stamina and mana" : "Online names") + "\\"; " + rl + " }}");
    b.appendInline("#SkyySetRow2", "TextButton #SkyySetOptOn {{ Anchor: (Width: 104, Height: 44); Text: \\"ON\\"; " + (l.opt ? on : bs) + " }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 8, Height: 44); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRow2", "TextButton #SkyySetOptOff {{ Anchor: (Width: 104, Height: 44); Text: \\"OFF\\"; " + (l.opt ? bs : on) + " }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 20, Height: 44); Text: \\"\\"; }}");
    b.appendInline("#SkyySetRow2", "Label {{ Anchor: (Width: 480, Height: 44); Text: \\"" + (isP ? "shown only while you are in a party" : "shown only while you are in a guild") + "\\"; Style: (FontSize: 16, TextColor: #9fb8d0, VerticalAlignment: Center); }}");
    ev.addEventBinding({BT}.Activating, "#SkyySetOptOn", {EVD}.of("a", "opton"));
    ev.addEventBinding({BT}.Activating, "#SkyySetOptOff", {EVD}.of("a", "optoff"));
  }}
''')
rep(r'''    if (data.indexOf("\\"on\\"") >= 0) l.en = true;
''', r'''    if (data.indexOf("\\"opton\\"") >= 0) l.opt = true;
    else if (data.indexOf("\\"optoff\\"") >= 0) l.opt = false;
    else if (data.indexOf("\\"on\\"") >= 0) l.en = true;
''')

# ---------------- manifest ----------------
rep('"SkyyHud: customizable server-side HUD. 8 widgets, per-player layouts and text styles (color, bold, italic, glow), /skyyhud editor + layout codes. Zero dependencies."',
    '"SkyyHud: customizable server-side HUD. 10 widgets incl. Party and Guild, per-player layouts and text styles (color, bold, italic, glow), /skyyhud editor + layout codes. Zero dependencies."')

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
