"""Derive SkyyIslands/build_skyyislands_0.5.4.py from the LIVE 0.5.3 (edit THIS file, then regenerate: python tools/islands_0_5_4_patch.py,
then python SkyyIslands/build_skyyislands_0.5.4.py; never --deploy - tools/deploy_set.py deploys the whole set).
Base = build_skyyislands_0.5.3.py (the tools/deploy_set.py SET pin, generated by tools/islands_0_5_3_patch.py from 0.5.2; the chain
goes back to 0.5.1 = the security hotfix; NEVER 0.5).

0.5.4 = the vanilla UI pass for the island menu (Skyy 2026-09-28: "the new goal for any and all UI added in the game is for them to
look and feel vanilla"; HANDOFF section 2 rule 0; research/Vanilla-UI-Style-Guide.md sections 7, 8c, 12, 13; research/Skyy-UI-
Inventory.md 5.14, batch B2). ONLY THE LOOK OF IslandMenuPage (/island menu) CHANGES - a look-only restyle on the shared kit
tools/skyyui.py (1.4):
  - the generated script imports skyyui as SUI and calls SUI.verify() before anything else (every vanilla value the page writes is
    proven against Assets.zip at every build), puts SUI.kit_id() and the page id into the ready log line, and lists its data colours
    (island role colours, the [Island] chat colours, the world tint) in UI_DATA_COLORS for the kit lint;
  - IslandMenuPage's look methods (style / lbl / gap / btn / row / twoLine / cell / dot / buildTabs / buildOverview / buildMembers /
    buildPerms / buildVisitors / buildIsland / build) are regenerated at BUILD time from kit calls (the page code below goes into the
    generated script by @@TOKEN@@ replacement; guide 8c A): the page Java keeps 0.5.3's control flow statement for statement - every
    text, every b.set target and value, every element id (the SkyyIsL<n> label counter included: the frame title is #SkyyIsL0, the
    same id and text as 0.5.3's title label), every event binding and EventData in the same order - and only the markup changed;
  - the fields, constructor, safe, jsonStr, two, date, idx, closePage and handleDataEvent of IslandMenuPage are 0.5.3's text, copied
    by this patch (asserted), and so is every other class, command, permission, config key / row, file format, bridge key, the
    island protection guards, beds member-only (the default grid), co-op invites (admins invite), the visitor limit 10 and the 0.5.1
    security fix (IslandReloadCmd / SetHubCmd requirePermission("skyyislands.admin") + setPermissionGroups(new String[0])).
Checked by SkyyIslands/test_skyyislands_0.5.4.py (committed next to the build; re-run it, do not trust this text).

Review fixes (2026-09-29, the 0.5.4 review; still look only, still 0.5.4 - never deployed):
  - The in-game gate names all four base probe pages: base1-3 cover parse safety (only proven properties, SUI.assert_proven), but
    the page composes kit 1.4 blocks (list_well, group(bg=color_by(...)) for the status bar and the online dot, confirm_view(wrap=
    True), column_spec, used_height) whose layout only probe page 19 base4 shows (Style Guide sections 0 / 12); base4 needs a
    SkyyUiProbe 0.2 (the deployed 0.1 opens pages 1-18). The generated docstring lists them as UNVERIFIED.
  - A page the harness has not passed stops the build (SystemExit before the jar is written) instead of a WARNING line; the
    explicit override SKYY_UNCHECKED_PAGE=1 builds it as SkyyIslands/SkyyIslands-0.5.4-UNCHECKED.jar, a name tools/deploy_set.py
    never deploys, for the harness run (--jar); a checked build removes that leftover.
  - The permission names start 13 px in (a spacer; IS_W_PNAME 220 -> 207, the What column stays 508 px) and the visitor names 3
    px in (a spacer; the name column keeps 250 px), so both line up under their column heads' leading spaces again (0.5.3 did it
    with Left: 12; the texts, b.set lines and ids are unchanged).
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyIslands", "build_skyyislands_0.5.3.py")
dst = os.path.join(ROOT, "SkyyIslands", "build_skyyislands_0.5.4.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.5.3"' in s, "build_skyyislands_0.5.3.py is not the live 0.5.3"
assert "import skyyui" not in s and "@@" not in s, "0.5.3 already imports the UI kit / holds a @@ token"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
assert len(BIND0) == 4, "0.5.3 has 4 addEventBinding lines (btn + the name box / invite / trust), found %d" % len(BIND0)
# the 0.5.1 security fix and the 0.5.3 locks this restyle must not touch (asserted again on the result)
SECURITY = ['  requirePermission("skyyislands.admin");\n  setPermissionGroups(new String[0]);   // 0.5.1: do NOT inherit /island\'s '
            'hytale:Adventurer (it handed every player skyyislands.admin)']
LOCKS = ['    ("beds", "Beds", "Sleeping, setting your respawn", "member"),',
         '"public static volatile int COOP_MAX = 5;", "public static volatile boolean ADMINS_INVITE = true;"',
         'DEF_LIMIT = (int) lng(p, "defaults.visit.limit", 10L, 1L, 100L);']
for x in SECURITY + LOCKS:
    assert s.count(x) == 1, "0.5.3 lost a line this restyle keeps: " + x[:80]


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def cut(a, b, new=""):
    """replace everything from anchor a (included) up to anchor b (kept) with new; returns the text that was cut"""
    global s
    assert s.count(a) == 1, "cut start count %d: %s" % (s.count(a), a[:120])
    assert s.count(b) == 1, "cut end count %d: %s" % (s.count(b), b[:120])
    i, j = s.index(a), s.index(b)
    assert i < j, "cut anchors out of order: %s / %s" % (a[:60], b[:60])
    old = s[i:j]
    s = s[:i] + new + s[j:]
    return old


def block(a, b):
    """the text from anchor a (included) to anchor b (excluded) of the CURRENT source (for unchanged-block asserts)"""
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


TOKEN_RE = re.compile(r"@@[A-Z0-9]+@@")


def fill(template, values):
    """@@NAME@@ replacement (research/Vanilla-UI-Style-Guide.md 8c): every token of `values` occurs exactly once in the template,
    no value holds a token or "@@" (the build scripts' own @PKG@ / @UCB@ tokens are single-@), and no token is left over."""
    for name, value in values.items():
        tok = "@@%s@@" % name
        assert template.count(tok) == 1, "token %s occurs %d times" % (tok, template.count(tok))
        assert "@@" not in value, "the value for %s holds '@@'" % tok
        template = template.replace(tok, value)
    left = TOKEN_RE.findall(template)
    assert not left, "tokens left unfilled: %s" % left
    return template


# blocks that must come out of this patch byte-identical (everything but the docstring head, VERSION, the kit import, the data
# colours, IslandMenuPage's look methods and the ready log line)
KEEP = [block("\nHERE = os.path.dirname(os.path.abspath(__file__))", "# IslandMenuPage (/island menu): inline only"),
        block("for f in (\"public int tab;\", \"public String info;\"", 'M(page, r"""\npublic static String style('),
        block("# one string value out of the page event JSON", 'M(page, r"""\npublic void lbl('),
        block('M(page, r"""\npublic void closePage(', 'M(page, r"""\npublic void buildTabs('),
        block('M(page, r"""\npublic void handleDataEvent(', "# ================= plugin ================="),
        block("# ================= plugin =================", '  getLogger().at(java.util.logging.Level.INFO).log("[SkyyIslands] @VERSION@ ready'),
        block("  // 0.5.3: which config lines still hold the untouched old default", "\njar = os.path.join(HERE")]

# ================================================================================================ docstring
HEAD_OLD = '"""0.5.3 (2026-09-28): '
assert s.startswith(HEAD_OLD), "0.5.3 docstring head changed: " + s[:200]
HEAD_NEW = '''"""SkyyIslands 0.5.4 - build script (javassist via jpype). GENERATED by tools/islands_0_5_4_patch.py from the LIVE 0.5.3 - edit the
patch, then regenerate; never edit this file by hand. Never run with --deploy (tools/deploy_set.py deploys the coordinated set).

0.5.4 (2026-09-29, the vanilla UI pass, batch B2 - Skyy 2026-09-28: "the new goal for any and all UI added in the game is for them to
look and feel vanilla"; HANDOFF section 2 rule 0; research/Vanilla-UI-Style-Guide.md; research/Skyy-UI-Inventory.md 5.14):
  ONLY THE LOOK OF THE ISLAND MENU (/island menu, the SkyyMenu "Island Menu" tile) CHANGED, on the shared kit tools/skyyui.py.
  Commands, aliases, permissions, the 0.5.1 security fix, config keys and Server Setup rows, island files, bridge keys, player
  switches, island protection, beds member-only, co-op invites (admins invite), the visitor limit, every page text, every element
  id of 0.5.3 (the SkyyIsL<n> label counter included), every b.set target and value, every event binding and EventData (same
  order), handleDataEvent and closePage are 0.5.3's - the patch asserts it and SkyyIslands/test_skyyislands_0.5.4.py proves it
  side by side with the 0.5.3 jar.
  - The build calls SUI.verify() first (every vanilla style value / texture / sound the page writes is proven against Assets.zip,
    read-only; a game update that changes one stops the build); KIT_ID (kit version + file hash) and the page id (IS_PAGE_ID, a
    hash of the kit-made page code) are in the ready log line.
  - Window: the vanilla decorated container (page_shell: ContainerHeader title bar with runes + the two gold ornaments, the title in
    the 15 px Secondary uppercase title style, ContainerPatch body, padding 17), 1240 x 980 (0.5.3: 1240 x 900 without a frame);
    0.5.3's root #SkyyIsRoot is the body now, the title label #SkyyIsL0 sits in the title bar (same id, same text: "<owner>'s
    Island" / "Your Island"). Gone: the dark-blue root, the gold accent stripe, the 26 px custom title, the empty Label spacers.
  - Role line: the default label (16 px, centred) in the role's own colour (IslandPerms.roleColor, a data colour: UI_DATA_COLORS).
  - Tabs: the kit tab row (EntitySpawnPage: Secondary buttons, the open tab Primary, 5 px apart), 5 x 237 px, fixed widths (no
    FlexWeight). Body: #SkyyIsBody, 713 px (0.5.3: 640), every tab laid out to fit it (the harness sums every state).
  - Lists sit on the vanilla list well (#000000(0.15), padding 4): co-op members (#SkyyIsMList), trusted players (#SkyyIsTList),
    the permission grid (#SkyyIsPList) and the visitors / bans rows (#SkyyIsVList) - new element ids, the rows keep theirs. Every
    row is the WorldEventListRow panel (#101925(0.55), 40 px + 3, padding 8) with full-height labels (row name 18 px bold, sub
    15 px) and full-height small buttons (the vanilla row action: 14 px labels), the column heads in the section head style
    (16 px bold uppercase #9aacbc) lined up over the well (padding 12 = well 4 + row 8). The permission names start after a
    13 px spacer and the visitor names after a 3 px one, so their texts start under the heads' texts (0.5.3's heads keep their
    3 leading spaces = 13.3 px; the visitor names their 2 = 10 px). Your own member row carries the 4 px selected status bar;
    the online dot is the vanilla success green / disabled grey.
  - Buttons: the vanilla kinds - Create my island / Go to island / Invite to co-op / Accept and the open tab = Primary; Trust (build
    only), Promote / Demote, Expel, Unban, Refresh list, the pagers, Refresh = Secondary; Close = Secondary with the cancel sound;
    Disband / Reset island / Leave island / Kick / Untrust / Ban / Reset to defaults = Destructive; the visit mode = Primary for the
    current mode, Secondary for the others; the permission cells, Visit ping and the island rules (PvP, mob spawning) = the
    quiet Tertiary toggle (Tertiary_Active = YES / On / ON). Read-only cells / values: YES success green, NO error red.
    The "click again" arms keep 0.5.3's second click on the same button (same id, same payload, same label): an in-page
    confirm_view would add a Cancel button + binding, which this look-only round may not.
  - The pending co-op invite is the kit's one-row confirm view (confirm_view compact, ids kept: #SkyyIsInvRow, the question = the
    0.5.3 label id, #SkyyIsAcc / #SkyyIsDec): the question in the confirm yellow (wraps to two lines), Accept = Primary, Decline =
    Secondary + cancel; while the invite can't be accepted only Decline is shown (as in 0.5.3) and the question takes Accept's room.
  - The trusted list pager and the bans pager are the kit pager (small Secondary buttons 150 wide around a centred caption, Prev /
    Next in the vanilla Disabled look at the ends - still bound, handleDataEvent clamps as before).
  - Name box: the vanilla text field (InputBox.png) around #SkyyIsName (placeholder, 32 characters, the Validating binding kept).
  - Result line: the kit status line (16 px bold, centred, wraps to two lines): "+" vanilla success green, "-" error red, "=" the
    vanilla info blue (IslandMenuPage.colorOf / textOf = the kit's java_status_methods; the [Island] chat lines keep
    IslandStore.colorOf). Footer: the content separator, Refresh left and Close right (WorldEventPanelPage footer).
  - Uses only what deployed Skyy pages already use inline (LayoutMode Top / Left, fixed widths / heights, Anchor margins, Padding,
    Wrap, the button / input textures, inline Sounds, the title bar of SkyyRanks 0.1.1 / SkyyVault 0.1.3): no FlexWeight,
    WrapMaxLines, LetterSpacing, LayoutMode Center / Right / Full, no UNVERIFIED (trial) element, no b.set on a TextButton - the
    build asserts it with SUI.assert_proven. Runtime button labels ("Sure?", "Disband co-op (2)", "Public (anyone)" ...) stay
    inline through safe() exactly as 0.5.3 wrote them (KIT-GAP: the kit's only runtime-label path is the UNVERIFIED b.set one).
  - Page gate: IS_PAGE_ID (a hash of the kit-made page code) must equal IS_PAGE_CHECKED (the page the harness last passed on, set
    by the patch) or the build stops before the jar is written (a kit change can't slip an unchecked page into
    SkyyIslands-0.5.4.jar). The explicit override SKYY_UNCHECKED_PAGE=1 builds SkyyIslands-0.5.4-UNCHECKED.jar instead - a name
    tools/deploy_set.py never deploys - for the harness (--jar); then set PAGE_CHECKED in the patch, regenerate, rebuild.
@@CHECKED@@
  UNVERIFIED (needs the game): the whole new look - the kit's "base" look has not been seen in game yet. Parse safety: the page
    uses only proven properties (SUI.assert_proven), the ones skyyui probe pages base1 / base2 / base3 show (base3 = the kit 1.3
    builders it uses: tab_row, pager, confirm_view compact, text_field). Layout: it also composes kit 1.4 blocks - list_well (the
    four list wells), group(bg=color_by(...)) (your member row's status bar, the online dot), confirm_view(wrap=True) (the
    two-line invite question), column_spec (the permission / visitor column widths) and used_height (the body budget) - which
    only probe page 19 base4 shows (research/Vanilla-UI-Style-Guide.md sections 0 and 12). base4 CAN'T be opened yet: the
    deployed SkyyUiProbe 0.1 opens pages 1-18 only, so it needs a SkyyUiProbe 0.2 on kit 1.4. A parse error disconnects on
    /island menu and the SkyyMenu Island Menu tile: keep the tools/deploy_set.py SET pin at ("SkyyIslands", "0.5.3") until Skyy
    has opened base1 / base2 / base3 AND base4 cleanly.
    Also only the game can show: the frame, ornaments and textures as the client draws them; the Tertiary toggles (the
    Tertiary_Active look for YES / On / ON); the Disabled look of the pager ends; the 120 px small Primary Trust in a visitor row
    (below 160 px its 80 px texture ends overlap - vanilla accepts it on PointInspectorPage) next to Expel / Ban; inline button
    labels with ? ( ) + (0.5.3's, unchanged); Server admin visitor rows; the fixed 713 px body on the short tabs (Island uses
    about 224 px of it, Overview about 540, Visitors about 560; 0.5.3 also kept one body height for every tab); the Permissions
    tab's rebuild size (about 108 KB, 236 elements per click - 0.5.3 about 50 KB, 192).

'''
CHECKED = '''  CHECKED with SkyyIslands/test_skyyislands_0.5.4.py (committed; re-run it: python SkyyIslands/test_skyyislands_0.5.4.py) -
    2026-09-29 (after the review fixes), kit skyyui 1.4 ac93356c4c60, page 144f342c8b5a; one JVM with -Xverify:all,
    HytaleServer.jar, 0.5.3 and 0.5.4 each in its own class loader, an Unsafe-allocated Universe / Worlds / PlayerRefs for online
    players and visitors:
    A all 72 classes of both jars load, verify and initialise. B 67 classes byte-identical; CfgFn, CfgRows, IslandCfg differ only in
    version-string constants (the config kit version, the config file text); SkyyIslandsPlugin = 0.5.3's bytes once its ready-log
    constant is swapped back; IslandMenuPage: same fields and superclass, <init> / safe / jsonStr / two / date / idx / closePage /
    handleDataEvent instruction-identical; changed build, buildTabs, buildOverview / Members / Perms / Visitors / Island, gap, dot;
    gone style, lbl, btn, row, the old twoLine / cell; new colorOf / textOf (the kit's), kbtn, rowP / rowPB / rowH / rowL, bar, the
    label looks, twoLine / cell. C 21 island states x 5 tabs x result marks = 233 builds per jar: identical event bindings (4361:
    type, id, EventData, lock, order), identical b.set lines (4747), identical inline texts, every 0.5.3 id present (11290);
    0.5.4: 18280 markups pass check_markup, 233 pages check_page + assert_proven, kit / declared data colours only, the frame body
    column = 908 px in every build, #SkyyIsBody (713 px) holds every tab (fullest: permissions 711), 1633 rows + 623 columns hold
    their children; the column heads start over their rows' names (What 476 rows, On the island now 92, Banned 64; worst 0.3 px);
    253 coverage checks (every tab, every arm, the pagers, both invite rows, read-only views). D 4 scenarios, 74 clicks per jar
    through handleDataEvent: identical results, arms, name box, tab, pages, island files, invites and rebuilt pages (47 different
    result lines). E about 685 texts (the invite countdowns move the count) in 514 boxes fit (client NunitoSans / Lexend
    tables): every button label at full size, every one-line label, every wrapped label in its lines. F the page id in the jar = the kit's page now = this; the page gate (6
    cases: a mismatch stops the build, SKYY_UNCHECKED_PAGE=1 only writes the -UNCHECKED jar name).'''
# the page id (IS_PAGE_ID, a hash of the kit-made IslandMenuPage code) that SkyyIslands/test_skyyislands_0.5.4.py last passed on
PAGE_CHECKED = "144f342c8b5a"
rep(HEAD_OLD, fill(HEAD_NEW, {"CHECKED": CHECKED}) + "0.5.3 (2026-09-28): ")
rep("Run:   python build_skyyislands_0.5.py            -> SkyyIslands/SkyyIslands-0.5.jar  (never --deploy: tools/deploy_set.py deploys)",
    "Run:   python build_skyyislands_0.5.4.py          -> SkyyIslands/SkyyIslands-0.5.4.jar  (never --deploy: tools/deploy_set.py deploys)")

# ================================================================================================ version, kit import, data colours
rep('VERSION = "0.5.3"', '''VERSION = "0.5.4"
# 0.5.4: data colours for the kit lint (research/Vanilla-UI-Style-Guide.md section 5) - not page chrome: the island role colours
# (IslandPerms.roleColor + the page's "Server admin" role), the [Island] chat line colours (Message.color, IslandStore.colorOf) and
# the island template's grass tint
UI_DATA_COLORS = {"roleBanned": "#ff8080", "roleTrusted": "#8fc8ff", "roleMember": "#7fe07f", "roleAdmin": "#c9a0ff",
                  "roleOwner": "#ffd060", "roleVisitor": "#c8d4e0", "roleServerAdmin": "#ffb070",
                  "chatInfo": "#cfe3ff", "chatDone": "#8fe39a", "chatRefused": "#ff9d6b", "chatNote": "#ffe08a", "chatHint": "#9fb8d0",
                  "tint": "#5b9e28"}''')
rep("import skyycfg as CFG   # 0.5.2: the admin config kit (tools/CONFIG-CONTRACT.md)\n",
    """import skyycfg as CFG   # 0.5.2: the admin config kit (tools/CONFIG-CONTRACT.md)
import skyyui as SUI     # 0.5.4: the ONE shared vanilla UI kit (research/Vanilla-UI-Style-Guide.md); not "as UI"
SUI.verify()             # proves every vanilla value / texture / sound the page uses against Assets.zip (read-only); stops the build on drift
KIT_ID = SUI.kit_id()    # "skyyui <version> <blob12>" - in the ready log line
""")

# ================================================================================================ the page: the look only
rep("# IslandMenuPage (/island menu): inline only (HANDOFF section 2), ids without underscores, root anchor Width/Height only,\n"
    "# TextButton + EventData, rebuilt only after a click (never periodically), big and readable. Spec section 7.\n",
    "# IslandMenuPage (/island menu): inline only (HANDOFF section 2), ids without underscores, root anchor Width/Height only,\n"
    "# TextButton + EventData, rebuilt only after a click (never periodically), big and readable. Spec section 7.\n"
    "# 0.5.4: the look = the vanilla UI kit tools/skyyui.py (look only; 0.5.3's logic, texts, ids and bindings - see the docstring).\n")
# the custom button style helper is replaced by the kit's button styles
OLD_STYLE = cut('M(page, r"""\npublic static String style(', "# one string value out of the page event JSON")
assert "TextButtonStyle(Default: (Background: " in OLD_STYLE
# the look helpers + tab builders (lbl ... buildIsland) and build(); closePage (between dot and buildTabs) is kept verbatim
OLD_LOOK = cut('M(page, r"""\npublic void lbl(', 'M(page, r"""\npublic void closePage(', "@@LOOKHELPERS@@")
OLD_TABS = cut('M(page, r"""\npublic void buildTabs(', 'M(page, r"""\npublic void handleDataEvent(', "@@TABS@@")
for need in ("public void lbl(", "public void gap(", "public void btn(", "public String row(", "public void twoLine(", "public void cell(",
             "public void dot("):
    assert OLD_LOOK.count(need) == 1, "0.5.3 look helper missing: " + need
for need in ("public void buildTabs(", "public void buildOverview(", "public void buildMembers(", "public void buildPerms(",
             "public void buildVisitors(", "public void buildIsland(", "public void build(@REF@ ref"):
    assert OLD_TABS.count(need) == 1, "0.5.3 page method missing: " + need
# the texts 0.5.3's page shows must all be in the new page code (the harness proves the values at run time)
_OLD_JAVA = LF.join(re.findall(r'M\(page, r"""(.*?)"""\)', OLD_TABS, re.S))      # the Java only (not the Python quotes)
assert _OLD_JAVA.count("public void ") == 7, "0.5.3 page Java not found"
OLD_TEXTS = sorted(set(t for t in re.findall(r'"((?:[^"\\]|\\.)*)"', _OLD_JAVA) if len(t) > 3 and not t.startswith(("#", "Skyy"))
                       and not re.fullmatch(r"#?[0-9a-fA-F]{6}(\([0-9.]+\))?", t) and "{" not in t and "}" not in t))

# The page code for the generated script: a RAW template filled by @@TOKEN@@ replacement (research/Vanilla-UI-Style-Guide.md 8c A):
# the kit calls inside run when the BUILD runs (every value proven by SUI.verify() then). Java lives in r\"\"\"...\"\"\" strings whose
# <<NAME>> slots are kit output (is_src below); the build scripts' own @PKG@ / @UCB@ tokens are single-@ and filled by jv().
LOOKHELPERS = r'''# ---- 0.5.4: the island menu look from the shared kit (tools/skyyui.py; research/Vanilla-UI-Style-Guide.md sections 7, 8c, 13) ------
# The page Java below keeps 0.5.3's control flow, texts, ids (the SkyyIsL<n> counter included), b.set lines and bindings; only the
# markup is kit-made. Every <<NAME>> slot is filled with kit output by is_src() when this script runs.
IS_PREFIX = "SkyyIs"                   # every element id starts with it (0.5.3's did)
IS_W, IS_H = 1240, 980                 # the page root; the frame takes 38 px of title bar + 2 x 17 px padding: body 1206 x 908
IS_ROLE_H = 28                         # the role line #SkyyIsL1 (0.5.3: 28)
IS_TAB_W, IS_TAB_TOP, IS_TAB_BOTTOM = 237, 4, 8                    # 5 tabs x 237 + 4 x 5 px = 1205 of 1206 px, no FlexWeight
IS_RES_H, IS_RES_TOP = 46, 4           # result line: two wrapped 16 px lines (2 x 16 x 1.364 = 43.7 px) + 2 spare, 4 below the body
IS_ROW_H = 40                          # list rows (members, trusted, permissions, visitors): labels and small buttons full height
IS_LINE_H = SUI.BTN_H                  # 44: control rows (name box, go, owner actions, visit mode, visitor limit, island rules)
IS_CTL_GAP = 6                         # under a control row (a vanilla spacing step)
IS_GAP = SUI.ROW_GAP                   # 3 under each list row (WorldEventListRow)
IS_WELL = SUI.WELL_LIST_PAD            # 4: the list well's padding (WorldEventPanelPage #ListContainer)
IS_ROWPAD = 8                          # a list row's padding left / right (WorldEventListRow)
IS_HEAD_H = 26                         # column heads / section heads (16 px bold uppercase + 10)
IS_BTN = SUI.BTN_MIN_W                 # 172: Refresh / Close (@DefaultButtonMinWidth)
IS_J = {}                              # <<NAME>> -> Java source (kit output)
IS_MARKUPS = []                        # every markup shape the page can send (assert_proven / check_markup at build time)
IS_SRC = []                            # the kit-made page Java (hashed into IS_PAGE_ID)

IS_SH = SUI.page_shell("SkyyIsF", IS_W, IS_H, SUI.J("title", "Your Island"), body_id="SkyyIsRoot", title_id="SkyyIsL0")
IS_IW = IS_SH.inner_w                  # 1206
IS_WIN = IS_IW - 2 * IS_WELL           # 1198: a list row (in a well)
IS_RIN = IS_WIN - 2 * IS_ROWPAD        # 1182: a list row's content
IS_LIN = IS_IW - 2 * IS_ROWPAD         # 1190: an island rule row's content (a list row panel straight in the body)
# the body column: role line, tabs, #SkyyIsBody, result line, separator, footer - filled exactly (read back out of the markup)
IS_BODY_H = IS_SH.inner_h - (IS_ROLE_H + (IS_LINE_H + IS_TAB_TOP + IS_TAB_BOTTOM) + (IS_RES_H + IS_RES_TOP) + (1 + 2 * SUI.SEP_MARGIN)
                             + SUI.BTN_H)
assert IS_BODY_H >= 700, "the island menu body is too small: %d px" % IS_BODY_H


def is_put(name, java):
    assert re.fullmatch(r"[A-Z][A-Z0-9]*", name) and name not in IS_J, name
    IS_J[name] = java


def is_src(src):
    """Java source with its <<NAME>> slots filled from IS_J (kit output); every slot must exist and none may be left."""
    out = re.sub(r"<<([A-Z][A-Z0-9]*)>>", lambda m: IS_J[m.group(1)], src)
    assert "<<" not in out, "unfilled slot in page code"
    IS_SRC.append(out)
    return out


def is_mk(mk):
    """record + check one markup shape (J() values stand for their samples)"""
    for v in (mk.variants() if isinstance(mk, SUI.Choice) else (mk,)):
        SUI.check_markup(v, prefix=IS_PREFIX)
        IS_MARKUPS.append(v)
    return mk


def is_inside(outer, *kids):
    """kit markup `outer` with `kids` placed inside it (outer ends with its closing brace)"""
    assert outer.endswith("}"), outer[:60]
    return outer[:-1] + " ".join(kids) + " }"


def is_btn(name, kind, size="normal", w=None, h=None, selected=False, sound=None):
    """A kit button look for kbtn(): the markup around its label, split at the Text value (0.5.3 wrote every button label inline
    through safe() - so does 0.5.4, only the look around it is the kit's). <<NAME>> = "a", "z"; <<NAMEA>> / <<NAMEZ>> alone."""
    head, key = "TextButton #SkyyIsXq", 'Text: ""; '
    mk = SUI.button("SkyyIsXq", "", kind, size, w=w, h=h, selected=selected, sound=sound)
    assert mk.startswith(head + " ") and mk.count(key) == 1, mk[:80]
    i = mk.index(key) + len('Text: "')
    a, z = mk[len(head):i], mk[i:]
    is_mk(head + a + "Sample" + z)
    is_put(name, SUI.java_lit(a) + ", " + SUI.java_lit(z))
    is_put(name + "A", SUI.java_lit(a))
    is_put(name + "Z", SUI.java_lit(z))
    return a, z


def is_label(name, kind, col=False, **kw):
    """Java source of one label look method NAME(b, parent, w, h, [col,] text): it takes the next SkyyIsL<n> id and b.sets the text
    exactly like 0.5.3's lbl() (w 0 = no Width: the label fills its row / column)."""
    idj = SUI.J("id", "SkyyIsL1")
    c = SUI.J("col", SUI.COLOR["white"]) if col else kw.pop("col", None)
    mw = is_mk(SUI.label(idj, "", kind, w=SUI.J("w", "300"), h=SUI.J("h", "30"), col=c, **kw))
    mh = is_mk(SUI.label(idj, "", kind, h=SUI.J("h", "30"), col=c, **kw))
    return is_src(r"""
public void %s(@UCB@ b, String parent, int w, int h, %sString text) {
  String id = "SkyyIsL" + this.nid;
  this.nid = this.nid + 1;
  if (w > 0) b.appendInline(parent, %s);
  else b.appendInline(parent, %s);
  b.set("#" + id + ".Text", text == null ? "" : text);
}""" % (name, "String col, " if col else "", SUI.java_expr(mw), SUI.java_expr(mh)))


def is_statements(part, parent=None):
    """the Java append statements of a kit Part (Choices -> (cond) ? a : b), optionally re-parented"""
    out = []
    for p, mk in part:
        is_mk(mk)
        out.append(SUI.java_append(parent if parent is not None else p, mk))
    assert not getattr(part, "sets", None), "the page b.sets these texts itself (0.5.3's values)"
    return "\n".join("    " + ln for ln in out)


# ---- buttons (kind, size, width) - the vanilla kinds for 0.5.3's colour families (research/Skyy-UI-Inventory.md section 3)
IS_BTN_W = {}
for _n, _k, _sz, _w, _sel, _snd in (
        ("BCREATE", "primary", "big", 320, False, None),          # Create my island (0.5.3 green 360 x 56)
        ("BGO", "primary", "normal", 240, False, None),           # Go to island
        ("BINV", "primary", "normal", 240, False, None),          # Invite to co-op
        ("BTRUST", "secondary", "normal", 260, False, None),      # Trust (build only) (0.5.3 blue)
        ("BDANGER", "destructive", "normal", 300, False, None),   # Disband / Reset island / Leave island (0.5.3 red)
        ("BPDEF", "destructive", "normal", 280, False, None),     # Reset to defaults
        ("BROW", "secondary", "small", 120, False, None),         # Promote / Demote
        ("BROWDEL", "destructive", "small", 110, False, None),    # Kick / Untrust
        ("BYES", "tertiary", "small", 130, True, None),           # a permission cell: YES = the tertiary toggle active
        ("BNO", "tertiary", "small", 130, False, None),           # NO
        ("BMODEON", "primary", "normal", 394, False, None),       # the current visit mode (0.5.3 gold)
        ("BMODEOFF", "secondary", "normal", 394, False, None),    # the other modes (0.5.3 blue)
        ("BSTEP", "secondary", "normal", 64, False, None),        # visitor limit - / +
        ("BTGLON", "tertiary", "normal", 120, True, None),        # Visit ping On (0.5.3 green)
        ("BTGLOFF", "tertiary", "normal", 120, False, None),      # Off (0.5.3 grey)
        ("BVEXPEL", "secondary", "small", 100, False, None),      # visitor row: Expel
        ("BVTRUST", "primary", "small", 120, False, None),        # Trust (0.5.3 green; a Primary is >= 120 px)
        ("BVBAN", "destructive", "small", 100, False, None),      # Ban
        ("BVUNBAN", "secondary", "small", 110, False, None),      # Unban (0.5.3 blue)
        ("BNAV", "secondary", "small", 150, False, None),         # Refresh list
        ("BISLON", "tertiary", "normal", 140, True, None),        # PvP / mob spawning ON (0.5.3 red / green)
        ("BISLOFF", "tertiary", "normal", 140, False, None),      # OFF (0.5.3 grey)
        ("BFOOT", "secondary", "normal", IS_BTN, False, None),    # Refresh (0.5.3 blue)
        ("BCLOSE", "secondary", "normal", IS_BTN, False, "cancel")):  # Close = Secondary + the vanilla cancel sound
    _h = SUI.BTN_BIG_H if _sz == "big" else (IS_ROW_H if _sz == "small" else IS_LINE_H)
    if _n in ("BNAV",):
        _h = SUI.BTN_SMALL_H
    is_btn(_n, _k, _sz, w=_w, h=_h, selected=_sel, sound=_snd)
    IS_BTN_W[_n] = _w
# tabs: the kit's tab row (EntitySpawnPage) with fixed widths - the open tab Primary, the others Secondary
IS_TAB_IDS = ["SkyyIsTabOv", "SkyyIsTabMem", "SkyyIsTabPerm", "SkyyIsTabVis", "SkyyIsTabIsl"]
IS_TAB_TXT = ["Overview", "Members", "Permissions", "Visitors", "Island"]
_ta_on, _tz_on = is_btn("BTABON", "primary", w=IS_TAB_W)
_ta_off, _tz_off = is_btn("BTABOFF", "secondary", w=IS_TAB_W)
for _sel in range(5):
    _row = SUI.tab_row("SkyyIsRoot", "SkyyIsTabs", IS_TAB_IDS, IS_TAB_TXT, _sel, w=IS_TAB_W, top=IS_TAB_TOP, bottom=IS_TAB_BOTTOM)
    assert len(_row) == 10 and _row[0][0] == "SkyyIsRoot"
    for _i in range(5):
        _want = "TextButton #" + IS_TAB_IDS[_i] + (_ta_on if _i == _sel else _ta_off) + IS_TAB_TXT[_i] + (_tz_on if _i == _sel else _tz_off)
        assert _row[1 + 2 * _i] == ("SkyyIsTabs", _want), "kbtn tab %d is not the kit tab_row button" % _i
        is_mk(_want)
    assert all(_row[2 + 2 * _i] == _row[2] for _i in range(4)), "tab spacers"
is_put("TABROW", SUI.java_lit(is_mk(_row[0][1])))
is_put("TABGAP", SUI.java_lit(is_mk(_row[2][1])))

# ---- containers
is_put("ROWP", SUI.java_expr(is_mk(SUI.group(SUI.J("id", "SkyyIsXr0"), "Left", h=SUI.J("h", "44")))))
is_put("ROWPB", SUI.java_expr(is_mk(SUI.group(SUI.J("id", "SkyyIsXr0"), "Left", h=SUI.J("h", "44"), anchor={"bottom": IS_CTL_GAP}))))
is_put("ROWH", SUI.java_expr(is_mk(SUI.group(SUI.J("id", "SkyyIsXr0"), "Left", h=SUI.J("h", "26"),
                                             pad={"left": IS_WELL + IS_ROWPAD}))))
is_put("ROWL", SUI.java_expr(is_mk(SUI.group(SUI.J("id", "SkyyIsXr0"), "Left", h=SUI.J("h", "40"), anchor={"bottom": IS_GAP},
                                             pad={"left": IS_ROWPAD, "right": IS_ROWPAD}, bg="row"))))
is_put("SPW", SUI.java_expr(is_mk(SUI.spacer(w=SUI.J("w", "12"), h=SUI.J("h", "40")))))
is_put("SPH", SUI.java_expr(is_mk(SUI.spacer(h=SUI.J("h", "8")))))
# the 4 px status bar of your own member row (WorldEventListRow #StatusBar, selected blue; transparent keeps its 12 px on the others)
is_put("BAR", SUI.java_expr(is_mk(SUI.group(None, None, w=4, h=IS_ROW_H, anchor={"right": 8},
                                            bg=SUI.color_by([("on", "selected")], "transparent")))))
# the online dot: success green / disabled grey (0.5.3: its own green / grey), placed like 0.5.3's (a 14 px square in a plain Group)
is_put("DOT", SUI.java_expr(is_mk(is_inside(SUI.group(None, None, w=26, h=IS_ROW_H),
                                             SUI.group(None, None, w=14, h=14, anchor={"left": 4, "top": (IS_ROW_H - 14) // 2},
                                                       bg=SUI.color_by([("on", "success")], "disabled"))))))
IS_BODY = is_mk(SUI.group("SkyyIsBody", "Top", h=IS_BODY_H))
is_put("BODY", SUI.java_lit(IS_BODY))
IS_OWNBOX = is_mk(SUI.panel("SkyyIsBox", "well", h=4 * 30 + 2 * SUI.WELL_PAD))
is_put("OWNBOX", SUI.java_lit(IS_OWNBOX))
IS_SEP = is_mk(SUI.separator("content", anchor={"top": SUI.SEP_MARGIN, "bottom": SUI.SEP_MARGIN}))
is_put("SEP", SUI.java_lit(IS_SEP))
IS_FOOT = is_mk(SUI.group("SkyyIsBottom", "Left", h=SUI.BTN_H))
is_put("FOOT", SUI.java_lit(IS_FOOT))
is_put("FOOTGAP", SUI.java_lit(is_mk(SUI.spacer(w=IS_IW - 2 * IS_BTN, h=SUI.BTN_H))))
IS_NAMEBOX = is_mk(SUI.text_field("SkyyIsNameBox", "SkyyIsName", w=420, h=IS_LINE_H, placeholder="Player name", max_length=32))
is_put("NAMEBOX", SUI.java_lit(IS_NAMEBOX))
for _n, _v in (("MLIST", "shown"), ("TLIST", "nrows"), ("PLIST", "nperm"), ("VLIST", "nrows")):
    _id = {"MLIST": "SkyyIsMList", "TLIST": "SkyyIsTList", "PLIST": "SkyyIsPList", "VLIST": "SkyyIsVList"}[_n]
    is_put(_n, SUI.java_expr(is_mk(SUI.list_well(_id, h=SUI.J("%d + %s * %d" % (2 * IS_WELL, _v, IS_ROW_H + IS_GAP), "180")))))
IS_SHELL = SUI.Appends(IS_SH.appends)
for _p, _mk in IS_SHELL:
    is_mk(_mk)
is_put("SHELL", "\n".join("  " + ln for ln in IS_SH.java("b").split("\n")))
assert IS_SH.sets == [("SkyyIsL0", "Text", SUI.J("title", "Your Island"))]

# ---- the pending invite: the kit's one-row confirm view (ids kept); without Accept (can't accept) the question takes its room
_idq = SUI.J("qid", "SkyyIsL9")
IS_INV = SUI.confirm_view("SkyyIsBody", "SkyyIsInv", IS_IW, question="", yes_text="Accept", no_text="Decline", yes_w=150, no_w=150,
                          panel="well", compact=True, top=0, wrap=True,
                          ids={"box": "SkyyIsInvRow", "question": _idq, "yes": "SkyyIsAcc", "no": "SkyyIsDec"})
assert [p for p, _mk in IS_INV] == ["SkyyIsBody", "SkyyIsInvRow", "SkyyIsInvRow", "SkyyIsInvRow"]
_qw = IS_IW - 2 * 12 - 150 - 150 - 2 * 6
_q_ok = SUI.label(_idq, "", "bold", w=_qw, h=SUI.BTN_H, col="warning", wrap=True)
assert IS_INV[1][1] == _q_ok, "the confirm_view question look moved"
_q_bad = SUI.label(_idq, "", "bold", w=_qw + 150 + 6, h=SUI.BTN_H, col="warning", wrap=True)
IS_INVBAD = SUI.Appends([IS_INV[0], ("SkyyIsInvRow", _q_bad), IS_INV[3]])
is_put("INVOK", is_statements(IS_INV))
is_put("INVBAD", is_statements(IS_INVBAD))
IS_INV_H = IS_INV.h                    # 60 (44 + 2 x 8)

# ---- the pagers: the kit pager (Prev / Next in the vanilla Disabled look at the ends, still bound); the bans pager's parts go into
# 0.5.3's nav row #SkyyIsVNav right of Refresh list (KIT-GAP: pager() always makes its own row)
_idp = SUI.J("pid", "SkyyIsL9")
IS_TPAGER = SUI.pager("SkyyIsBody", "SkyyIsTNav", IS_IW, prev_text="< Prev", next_text="Next >", prev_on=SUI.J("this.trustPage > 0"), next_on=SUI.J("this.trustPage < pages - 1"),
                      ids={"row": "SkyyIsTNav", "prev": "SkyyIsTp", "page": _idp, "next": "SkyyIsTn"})
is_put("TPAGER", is_statements(IS_TPAGER))
_bp = SUI.pager("SkyyIsVNav", "SkyyIsBPg", 2 * 150 + 2 * 12 + 260, prev_text="< Prev", next_text="Next >", prev_on=SUI.J("this.banPage > 0"),
                next_on=SUI.J("this.banPage < bpages - 1"), align="left", top=0,
                ids={"row": "SkyyIsBPg", "prev": "SkyyIsBp", "page": _idp, "next": "SkyyIsBn"})
IS_BPAGER = SUI.Appends(list(_bp)[1:])
is_put("BPAGER", is_statements(IS_BPAGER, parent="SkyyIsVNav"))
IS_PAGER_W = 2 * 150 + 2 * 12 + 260    # 584
IS_NAV_H = SUI.BTN_SMALL_H             # 32

# ---- widths (the tabs' rows; each asserted to fit its row below)
IS_W_GOHINT = 800
IS_W_RESET = 780
IS_W_LEAVE = 820
IS_W_MNAME, IS_W_MROLE = 300, 140
IS_W_MSINCE = IS_RIN - (4 + 8) - 26 - IS_W_MNAME - IS_W_MROLE - (IS_BTN_W["BROW"] + 8 + IS_BTN_W["BROWDEL"])
IS_W_TNAME, IS_W_TGAP = 460, 30
# the permission grid and the visitors / bans list: heads, rows and widths from ONE kit column spec each (kit 1.4 column_spec - a
# width calculator only, no markup: the heads stay 0.5.3's b.set labels). pad_left = the list row's padding (the heads row adds the
# well's 4); the first permission column holds the flag name + 8 + its hint
# The heads keep 0.5.3's leading spaces ("   What", "   On the island now": 3 spaces of the 16 px bold section style = 13.3 px
# with the client's font tables); the names start under them: a 13 px spacer before each permission name (0.5.3: Left 12) and
# a 3 px one before each visitor name (its text already starts with 2 spaces of the 18 px bold row name = 10 px). Texts unchanged.
IS_PNAME_IN, IS_VNAME_IN = 13, 3
IS_W_PNAME, IS_W_PHINT = 220 - IS_PNAME_IN, 280    # the What column stays 508 px (the longest name, "Chairs and benches", 166 px)
IS_PCOLS = SUI.column_spec([("What", IS_PNAME_IN + IS_W_PNAME + 8 + IS_W_PHINT), ("Visitor", IS_BTN_W["BYES"]), ("Trusted", IS_BTN_W["BYES"]),
                            ("Member", IS_BTN_W["BYES"]), ("Admin", IS_BTN_W["BYES"]), ("Owner", 110)],
                           avail=IS_WIN - IS_ROWPAD, pad_left=IS_ROWPAD, gap=8)
IS_W_PWHAT, IS_W_PCELL, IS_W_POWN = IS_PCOLS.width("What"), IS_PCOLS.width("Visitor"), IS_PCOLS.width("Owner")
assert all(IS_PCOLS.width(c) == IS_W_PCELL for c in ("Trusted", "Member", "Admin"))
IS_W_PTOP = IS_IW - 16 - IS_BTN_W["BPDEF"]
IS_W_VNAME, IS_W_VROLE = 250, 140
IS_VCOLS = SUI.column_spec([("On the island now", 730), ("Banned", 410)], avail=IS_WIN - IS_ROWPAD, pad_left=IS_ROWPAD, gap=20)
IS_W_VSIDE, IS_W_BSIDE, IS_W_BNAME = IS_VCOLS.width(0), IS_VCOLS.width(1), 300
IS_W_PING = 480
IS_W_ISLNAME, IS_W_ISLTGL, IS_W_ISLHINT = 400, IS_BTN_W["BISLON"], 636
IS_VM_GAP = (IS_IW - 3 * IS_BTN_W["BMODEON"]) // 2
IS_NAV_GAP = IS_IW - IS_BTN_W["BNAV"] - IS_PAGER_W
for _parts, _room, _what in (
        ([IS_BTN_W["BGO"], 16, IS_W_GOHINT], IS_IW, "go row"),
        ([IS_BTN_W["BDANGER"], 16, IS_BTN_W["BDANGER"]], IS_IW, "owner actions"),
        ([IS_BTN_W["BDANGER"], 16, IS_W_RESET], IS_IW, "owner actions (no reset)"),
        ([IS_BTN_W["BDANGER"], 16, IS_W_LEAVE], IS_IW, "leave row"),
        ([2 * 12, _qw, 6, 150, 6, 150], IS_IW, "invite row (confirm_view compact: padding 12 + question + 2 buttons)"),
        ([420, 12, IS_BTN_W["BINV"], 12, IS_BTN_W["BTRUST"]], IS_IW, "name row"),
        ([4 + 8, 26, IS_W_MNAME, IS_W_MROLE, IS_W_MSINCE, IS_BTN_W["BROW"], 8, IS_BTN_W["BROWDEL"]], IS_RIN, "member row"),
        ([IS_W_TNAME, IS_BTN_W["BROWDEL"], IS_W_TGAP, IS_W_TNAME, IS_BTN_W["BROWDEL"]], IS_RIN, "trusted row"),
        ([IS_W_PTOP, 16, IS_BTN_W["BPDEF"]], IS_IW, "permissions top row"),
        ([IS_PNAME_IN, IS_W_PNAME, 8, IS_W_PHINT] + [IS_PCOLS.gap, IS_W_PCELL] * 4 + [IS_PCOLS.gap, IS_W_POWN], IS_RIN,
         "permission row"),
        ([IS_PCOLS.total], IS_RIN, "permission heads"),
        ([IS_BTN_W["BMODEON"]] * 3 + [IS_VM_GAP] * 2, IS_IW, "visit mode row"),
        ([170, IS_BTN_W["BSTEP"], 80, IS_BTN_W["BSTEP"], 60, 140, IS_BTN_W["BTGLON"], IS_W_PING], IS_IW, "visitor limit row"),
        ([170, 200, 60, 140, 140, IS_W_PING], IS_IW, "visitor limit row (read only)"),
        ([IS_VNAME_IN, IS_W_VNAME, IS_W_VROLE, IS_BTN_W["BVEXPEL"], 6, IS_BTN_W["BVTRUST"], 6, IS_BTN_W["BVBAN"]], IS_W_VSIDE,
         "visitor side"),
        ([IS_W_VSIDE, IS_VCOLS.gap, IS_W_BNAME, IS_BTN_W["BVUNBAN"]], IS_RIN, "visitor row"),
        ([IS_VCOLS.total], IS_RIN, "visitor heads"),
        ([IS_BTN_W["BNAV"], IS_NAV_GAP, IS_PAGER_W], IS_IW, "visitor nav row"),
        ([IS_W_ISLNAME, IS_W_ISLTGL, 12, IS_W_ISLHINT], IS_LIN, "island rule row"),
        ([IS_BTN] * 2 + [IS_IW - 2 * IS_BTN], IS_IW, "footer")):
    SUI.fit(_parts, _room, _what)
assert IS_W_BNAME + IS_BTN_W["BVUNBAN"] <= IS_W_BSIDE and IS_W_MSINCE >= 400
assert IS_PCOLS.pad_left + IS_WELL == IS_WELL + IS_ROWPAD == IS_VCOLS.pad_left + IS_WELL, "the heads row padding (ROWH) = the spec's"
assert IS_PCOLS.slack >= 0 and IS_VCOLS.slack >= 0
for _n, _v in (("GOHINTW", IS_W_GOHINT), ("RESETW", IS_W_RESET), ("LEAVEW", IS_W_LEAVE), ("MNAMEW", IS_W_MNAME),
               ("MROLEW", IS_W_MROLE), ("MSINCEW", IS_W_MSINCE), ("TNAMEW", IS_W_TNAME), ("TCOLGAP", IS_W_TGAP),
               ("BROWDELW", IS_BTN_W["BROWDEL"]), ("PTOPW", IS_W_PTOP), ("PWHATW", IS_W_PWHAT), ("PCELLW", IS_W_PCELL),
               ("POWNW", IS_W_POWN), ("VNAMEW", IS_W_VNAME), ("VROLEW", IS_W_VROLE), ("VSIDEW", IS_W_VSIDE), ("BSIDEW", IS_W_BSIDE),
               ("BNAMEW", IS_W_BNAME), ("PINGW", IS_W_PING), ("ISLNAMEW", IS_W_ISLNAME), ("ISLTGLW", IS_W_ISLTGL),
               ("ISLHINTW", IS_W_ISLHINT), ("VMGAP", IS_VM_GAP), ("NAVGAP", IS_NAV_GAP), ("NAVH", IS_NAV_H),
               ("ROWHT", IS_ROW_H), ("LINEH", IS_LINE_H), ("HEADH", IS_HEAD_H), ("ROLEH", IS_ROLE_H), ("RESH", IS_RES_H),
               ("CREATEH", SUI.BTN_BIG_H), ("CREATEL", (IS_IW - IS_BTN_W["BCREATE"]) // 2),
               ("PGAP", IS_PCOLS.gap), ("VGAP", IS_VCOLS.gap), ("VEW", IS_BTN_W["BVEXPEL"]), ("VTW", IS_BTN_W["BVTRUST"]), ("VBW", IS_BTN_W["BVBAN"]),
               ("VNAMEROLEW", IS_VNAME_IN + IS_W_VNAME + IS_W_VROLE), ("PNAMEIN", IS_PNAME_IN), ("VNAMEIN", IS_VNAME_IN)):
    is_put(_n, str(_v))
# kit colours the Java picks at runtime (and the "Server admin" role colour, a data colour)
for _n, _c in (("CROWNAME", SUI.COLOR["rowName"]), ("CDISABLED", SUI.COLOR["disabled"]), ("CWARN", SUI.COLOR["warning"]),
               ("CTEXT", SUI.COLOR["text"]), ("CADMIN", UI_DATA_COLORS["roleServerAdmin"])):
    is_put(_n, SUI.java_lit(_c))

# ---- the body column budget (read back out of the markup: role line, tabs, body, result line, separator, footer = the frame body)
_col = SUI.Appends([("SkyyIsRoot", SUI.label("SkyyIsL1", "", "default", h=IS_ROLE_H, align="Center")), _row[0],
                    ("SkyyIsRoot", IS_BODY),
                    ("SkyyIsRoot", SUI.status_line("SkyyIsL2", "col", h=IS_RES_H, wrap=True, anchor={"top": IS_RES_TOP})),
                    ("SkyyIsRoot", IS_SEP), ("SkyyIsRoot", IS_FOOT)])
assert SUI.fit([SUI.used_height(_col, "SkyyIsRoot")], IS_SH.inner_h, "island menu body column") == 0, "the body column must fill the frame"
# the worst case of each tab (the most rows / lines it can draw) must fit #SkyyIsBody (the harness also sums every built state)
_well = lambda rows: 2 * IS_WELL + rows * (IS_ROW_H + IS_GAP)
_sec = IS_HEAD_H + 6 + 4
IS_TAB_WORST = {
    "overview": 136 + 8 + IS_LINE_H + 8 + IS_INV_H + 10 + _sec + IS_LINE_H + 25 + 14 + _sec + 5 * 24,
    "members": (IS_LINE_H + IS_CTL_GAP) + 25 + _sec + _well(5) + 25 + 25 + 6 + _sec + _well(5) + (IS_NAV_H + 8),
    "permissions": (IS_LINE_H + IS_CTL_GAP) + 25 + IS_HEAD_H + _well(14),
    "visitors": _sec + 2 * (IS_LINE_H + IS_CTL_GAP) + 6 + IS_HEAD_H + _well(8) + 6 + IS_NAV_H,
    "island": 10 + _sec + 2 * (IS_LINE_H + IS_GAP) + 8 + 20 + 28 + 28,
    "no island": 24 + 44 + 46 + 10 + SUI.BTN_BIG_H + 8 + 8 + IS_INV_H + 14 + _sec + 5 * 24}
for _t, _h in IS_TAB_WORST.items():
    SUI.fit([_h], IS_BODY_H, "island menu tab %s (worst case)" % _t)


# ---- the label looks (0.5.3's lbl(fs, bold, colour) calls -> vanilla label kinds; each takes the next SkyyIsL<n> id)
IS_LOOK_SRC = [
    is_label("lRole", "default", col=True, align="Center"),                     # role line (0.5.3: 16 px in the role colour)
    is_src(r"""
public void lResult(@UCB@ b, String parent, int w, int h, String col, String text) {
  String id = "SkyyIsL" + this.nid;
  this.nid = this.nid + 1;
  b.appendInline(parent, """ + SUI.java_expr(is_mk(SUI.status_line(SUI.J("id", "SkyyIsL1"), "col", h=SUI.J("h", "46"), wrap=True,
                                                               anchor={"top": IS_RES_TOP}))) + r""");
  b.set("#" + id + ".Text", text == null ? "" : text);
}"""),                                                                          # result line (the kit status line, two lines)
    is_label("lErr", "error", align="Center", bold=True, wrap=True),            # file unreadable / tab failed / island gone
    is_label("lEmpty", "message"),                                              # "Create your island first ..."
    is_label("lHead", "heading", wrap=False),                                   # the owner line
    is_label("lHeadC", "heading", wrap=False, align="Center"),                  # "You have no island yet"
    is_label("lMsgC", "message"),                                               # the line under it
    is_label("lText", "default"),                                               # info lines
    is_label("lTextW", "default", wrap=True),                                   # the permission hint (two lines)
    is_label("lBold", "bold"),                                                  # "Visitor limit", "Visit ping", read-only mode
    is_label("lVal", "strong"),                                                 # read-only values
    is_label("lValC", "strong", align="Center"),                                # the visitor limit between - and +
    is_label("lCap", "caption"),                                                # hints, notes, commands, world line
    is_label("lCapC", "caption", align="Center"),                               # "always"
    is_label("lSec", "section", anchor={"top": 6, "bottom": 4}),                # section heads (WorldEventSectionLabel)
    is_label("lColH", "section"),                                               # column heads over a list well
    is_label("lColHC", "section", align="Center"),                              # column heads over the permission cells
    is_label("lName", "rowName"),                                               # row names (18 px bold)
    is_label("lNameCol", "rowName", col=True),                                  # names / roles in a runtime colour
    is_label("lSub", "rowSub"),                                                 # the member "since" line
    is_label("lInfo", "info"),                                                  # "Invited: ..." (0.5.3 gold)
    is_label("lBan", "error"),                                                  # banned names (0.5.3 light red)
    is_label("lStateC", "bold", col=True, align="Center"),                      # read-only ON / OFF
]
IS_CELL_YES = is_mk(SUI.label(SUI.J("id", "SkyyIsL1"), "", "success", w=SUI.J("w", "130"), h=SUI.J("h", "40"), align="Center"))
IS_CELL_NO = is_mk(SUI.label(SUI.J("id", "SkyyIsL1"), "", "error", w=SUI.J("w", "130"), h=SUI.J("h", "40"), align="Center", bold=True))
IS_TWO_A = is_mk(SUI.label(SUI.J("a", "SkyyIsL1"), "", "rowName", w=IS_W_PNAME, h=IS_ROW_H))
IS_TWO_C = is_mk(SUI.label(SUI.J("c", "SkyyIsL2"), "", "rowSub", w=IS_W_PHINT, h=IS_ROW_H))
IS_LOOK_SRC += [
    is_src(r"""
public void gap(@UCB@ b, String parent, int w, int h) {
  if (w > 0) b.appendInline(parent, <<SPW>>);
  else b.appendInline(parent, <<SPH>>);
}"""),
    is_src(r"""
public void kbtn(@UCB@ b, @UEB@ ev, String parent, String id, String text, String a, String z, String payload) {
  b.appendInline(parent, "TextButton #" + id + a + safe(text) + z);
  if (payload != null) ev.addEventBinding(@BT@.Activating, "#" + id, @EVD@.of("a", payload));
}"""),
    is_src(r"""
public String rowP(@UCB@ b, String parent, String id, int h) {
  b.appendInline(parent, <<ROWP>>);
  return "#" + id;
}"""),
    is_src(r"""
public String rowPB(@UCB@ b, String parent, String id, int h) {
  b.appendInline(parent, <<ROWPB>>);
  return "#" + id;
}"""),
    is_src(r"""
public String rowH(@UCB@ b, String parent, String id, int h) {
  b.appendInline(parent, <<ROWH>>);
  return "#" + id;
}"""),
    is_src(r"""
public String rowL(@UCB@ b, String parent, String id, int h) {
  b.appendInline(parent, <<ROWL>>);
  return "#" + id;
}"""),
    is_src(r"""
public void twoLine(@UCB@ b, String parent, String top, String bottom) {
  String a = "SkyyIsL" + this.nid;
  this.nid = this.nid + 1;
  String c = "SkyyIsL" + this.nid;
  this.nid = this.nid + 1;
  gap(b, parent, <<PNAMEIN>>, <<ROWHT>>);
  b.appendInline(parent, """ + SUI.java_expr(IS_TWO_A) + r""");
  gap(b, parent, 8, <<ROWHT>>);
  b.appendInline(parent, """ + SUI.java_expr(IS_TWO_C) + r""");
  b.set("#" + a + ".Text", top);
  b.set("#" + c + ".Text", bottom);
}"""),
    is_src(r"""
public void cell(@UCB@ b, String parent, int w, int h, boolean yes, String text) {
  String id = "SkyyIsL" + this.nid;
  this.nid = this.nid + 1;
  b.appendInline(parent, yes ? (""" + SUI.java_expr(IS_CELL_YES) + r""") : (""" + SUI.java_expr(IS_CELL_NO) + r"""));
  b.set("#" + id + ".Text", text);
}"""),
    is_src(r"""
public void dot(@UCB@ b, String parent, boolean on) {
  b.appendInline(parent, <<DOT>>);
}"""),
    is_src(r"""
public void bar(@UCB@ b, String parent, boolean on) {
  b.appendInline(parent, <<BAR>>);
}"""),
]
# the result line colours: the kit's (same names as IslandStore's, vanilla success / error / info blue); the chat keeps IslandStore's
IS_STATUS_SRC = [is_src(_m) for _m in SUI.java_status_methods("colorOf", "textOf")]
for _src in IS_STATUS_SRC + IS_LOOK_SRC:
    M(page, _src)
'''

TABS = r'''IS_TAB_SRC = [is_src(r"""
public void buildTabs(@UCB@ b, @UEB@ ev) {
  String[] ids = new String[] { "SkyyIsTabOv", "SkyyIsTabMem", "SkyyIsTabPerm", "SkyyIsTabVis", "SkyyIsTabIsl" };
  String[] txt = new String[] { "Overview", "Members", "Permissions", "Visitors", "Island" };
  String[] pay = new String[] { "tabov", "tabmem", "tabperm", "tabvis", "tabisl" };
  b.appendInline("#SkyyIsRoot", <<TABROW>>);
  for (int i = 0; i < 5; i++) {
    if (i > 0) b.appendInline("#SkyyIsTabs", <<TABGAP>>);
    kbtn(b, ev, "#SkyyIsTabs", ids[i], txt[i], i == this.tab ? <<BTABONA>> : <<BTABOFFA>>, i == this.tab ? <<BTABONZ>> : <<BTABOFFZ>>, pay[i]);
  }
}"""), is_src(r"""
public void buildOverview(@UCB@ b, @UEB@ ev, java.util.UUID u, String k, String hk, @PKG@.IslandSettings s, int rank) {
  String P = "#SkyyIsBody";
  long now = System.currentTimeMillis();
  boolean has = s.world != null;
  if (!has && hk.equals(k)) {
    gap(b, P, 0, 24);
    lHeadC(b, P, 0, 44, "You have no island yet");
    lMsgC(b, P, 0, 46, "Your private sky island is where you farm, build and later keep minions. It is created the first time you go there.");
    gap(b, P, 0, 10);
    String r = rowP(b, P, "SkyyIsCreateRow", <<CREATEH>>);
    gap(b, r, <<CREATEL>>, <<CREATEH>>);
    kbtn(b, ev, r, "SkyyIsCreate", "Create my island", <<BCREATE>>, "create");
  } else if (!has) {
    gap(b, P, 0, 24);
    lErr(b, P, 0, 34, "The island you are a co-op member of is not available right now - ask its owner.");
  } else {
    String on = @PKG@.IslandStore.ownerDisplay(hk, s);
    b.appendInline(P, <<OWNBOX>>);
    lHead(b, "#SkyyIsBox", 0, 30, "Owner: " + on + (hk.equals(k) ? "   (that is you)" : "   - you are a co-op " + @PKG@.IslandPerms.roleName(rank) + " here"));
    lText(b, "#SkyyIsBox", 0, 30, "Co-op: " + (1 + @PKG@.IslandStore.count(s.members)) + " / " + @PKG@.IslandCfg.COOP_MAX + " players      Trusted: " + @PKG@.IslandStore.count(s.trusted) + "      Banned: " + @PKG@.IslandStore.count(s.banned));
    @WLD@ w = @PKG@.IslandStore.loadedWorld(s.world);
    int vis = w == null ? 0 : @PKG@.IslandPerms.visitorCount(w, hk, s, null);
    lText(b, "#SkyyIsBox", 0, 30, "Visits: " + @PKG@.IslandCfg.modeLabel(s.mode) + " (limit " + s.limit + ")      Visitors now: " + vis + "      PvP: " + (s.pvp ? "ON" : "off") + "      Mob spawning: " + (s.spawning ? "on" : "off"));
    lCap(b, "#SkyyIsBox", 0, 30, "World: " + s.world + (w != null ? "  (loaded)" : "  (not loaded - it loads when someone goes there)"));
    gap(b, P, 0, 8);
    if (rank >= 2) {
      String r = rowP(b, P, "SkyyIsGoRow", <<LINEH>>);
      kbtn(b, ev, r, "SkyyIsGo", "Go to island", <<BGO>>, "go");
      gap(b, r, 16, <<LINEH>>);
      lCap(b, r, <<GOHINTW>>, <<LINEH>>, "Same as /island. Closes this page and takes you there.");
    }
  }
  Object[] inv = @PKG@.IslandCoop.inviteFor(u);
  if (inv != null) {
    gap(b, P, 0, 8);
    long secs = (((Long) inv[2]).longValue() - now) / 1000L;
    String why = @PKG@.IslandCoop.acceptProblem(this.playerRef);
    String qid = "SkyyIsL" + this.nid;
    this.nid = this.nid + 1;
    if (why == null) {
<<INVOK>>
      ev.addEventBinding(@BT@.Activating, "#SkyyIsAcc", @EVD@.of("a", "acc"));
    } else {
<<INVBAD>>
    }
    ev.addEventBinding(@BT@.Activating, "#SkyyIsDec", @EVD@.of("a", "dec"));
    String it = inv[3] + " invited you to join " + inv[4] + "'s island - " + secs + " s left" + (why == null ? ". Joining uses your current profile." : "  (can't accept: " + why + ")");
    b.set("#" + qid + ".Text", it == null ? "" : it);
  }
  if (rank == 4 && has) {
    gap(b, P, 0, 10);
    lSec(b, P, 0, <<HEADH>>, "Owner actions");
    String r = rowP(b, P, "SkyyIsOwnRow", <<LINEH>>);
    int nm = @PKG@.IslandStore.count(s.members);
    if (nm > 0) {
      kbtn(b, ev, r, "SkyyIsDisb", this.confirm.equals("disb") ? "Click again to DISBAND" : "Disband co-op (" + nm + ")", <<BDANGER>>, "disb");
      gap(b, r, 16, <<LINEH>>);
    }
    String rb = @PKG@.IslandCoop.resetCheck(this.playerRef);
    if (rb == null) {
      String t = this.confirm.equals("reset2") ? "Really? Last click" : (this.confirm.equals("reset1") ? "Delete everything?" : "Reset island");
      kbtn(b, ev, r, "SkyyIsReset", t, <<BDANGER>>, "reset");
    } else lCap(b, r, <<RESETW>>, <<LINEH>>, "Reset island: " + @PKG@.IslandStore.textOf(rb));
    lCap(b, P, 0, 25, "Reset rebuilds your island from scratch with a fresh starter kit. Members, trusted players, bans and settings stay. Once every " + @PKG@.IslandCfg.RESET_HOURS + " h.");
  }
  if (rank == 2 || rank == 3) {
    gap(b, P, 0, 10);
    String r = rowP(b, P, "SkyyIsLeaveRow", <<LINEH>>);
    kbtn(b, ev, r, "SkyyIsLeave", this.confirm.equals("leave") ? "Click again to leave" : "Leave island", <<BDANGER>>, "leave");
    gap(b, r, 16, <<LINEH>>);
    lText(b, r, <<LEAVEW>>, <<LINEH>>, "Your own island stays saved and comes back when you leave.");
  }
  gap(b, P, 0, 14);
  lSec(b, P, 0, <<HEADH>>, "Commands");
  String[] help = new String[] {
    "/island - go to your island      /island menu - this page      /island info      /island visit <player>      /hub",
    "/island invite <player> - co-op invite (they type /island accept or /island decline)      /island leave",
    "/island kick <name> | promote <name> | demote <name>      /island disband      /island reset   (owner)",
    "/island trust <player> | untrust <name> - build rights only, their /island stays their own",
    "/island expel <player>      /island ban <player> | unban <name> | bans      /island lock | unlock" };
  for (int i = 0; i < help.length; i++) lCap(b, P, 0, 24, help[i]);
}"""), is_src(r"""
public void buildMembers(@UCB@ b, @UEB@ ev, java.util.UUID u, String k, String hk, @PKG@.IslandSettings s, int rank) {
  String P = "#SkyyIsBody";
  if (s.world == null) {
    gap(b, P, 0, 30);
    lEmpty(b, P, 0, 34, "Create your island first (Overview tab), then invite co-op members or trust builders here.");
    return;
  }
  boolean canInv = rank == 4 || (rank == 3 && @PKG@.IslandCfg.ADMINS_INVITE);
  if (rank >= 3) {
    String r = rowPB(b, P, "SkyyIsNameRow", <<LINEH>>);
    b.appendInline(r, <<NAMEBOX>>);
    if (this.keepName != null && this.keepName.length() > 0) b.set("#SkyyIsName.Value", this.keepName);
    ev.addEventBinding(@BT@.Validating, "#SkyyIsName", @EVD@.of("a", "name").append("@IsName", "#SkyyIsName.Value"), false);
    gap(b, r, 12, <<LINEH>>);
    if (canInv) {
      b.appendInline(r, "TextButton #SkyyIsInvBtn" + <<BINVA>> + "Invite to co-op" + <<BINVZ>>);
      ev.addEventBinding(@BT@.Activating, "#SkyyIsInvBtn", @EVD@.of("a", "invite").append("@IsName", "#SkyyIsName.Value"));
      gap(b, r, 12, <<LINEH>>);
    }
    b.appendInline(r, "TextButton #SkyyIsTrustBtn" + <<BTRUSTA>> + "Trust (build only)" + <<BTRUSTZ>>);
    ev.addEventBinding(@BT@.Activating, "#SkyyIsTrustBtn", @EVD@.of("a", "trust").append("@IsName", "#SkyyIsName.Value"));
    lCap(b, P, 0, 25, (canInv ? "Invite to co-op = they join " + (rank == 4 ? "your" : "the") + " island (their /island comes here).   " : "") + "Trust = build rights only, their /island stays their own.   Enter only keeps the name.");
  }
  String[] m = @PKG@.IslandStore.split(s.members);
  int total = m.length + 1;
  lSec(b, P, 0, <<HEADH>>, "Co-op members  (" + total + " / " + @PKG@.IslandCfg.COOP_MAX + ")");
  this.rowKeys = new java.util.ArrayList();
  int shown = total < 5 ? total : 5;
  b.appendInline(P, <<MLIST>>);
  for (int i = 0; i < shown; i++) {
    String key = i == 0 ? hk : m[i - 1];
    this.rowKeys.add(key);
    boolean me = key.equals(k);
    int rr = i == 0 ? 4 : (@PKG@.IslandStore.contains(s.admins, key) ? 3 : 2);
    java.util.UUID ku = @PKG@.IslandStore.ownerUuid(key);
    @PR@ op = @PKG@.IslandStore.online(ku);
    boolean on = op != null && key.equals(@PKG@.IslandStore.pkey(ku));
    String r = rowL(b, "#SkyyIsMList", "SkyyIsMr" + i, <<ROWHT>>);
    bar(b, r, me);
    dot(b, r, on);
    lNameCol(b, r, <<MNAMEW>>, <<ROWHT>>, on ? <<CROWNAME>> : <<CDISABLED>>, @PKG@.IslandStore.nameOf(s, key) + (me ? "  (you)" : ""));
    lNameCol(b, r, <<MROLEW>>, <<ROWHT>>, @PKG@.IslandPerms.roleColor(rr), @PKG@.IslandPerms.roleName(rr));
    Object since = s.since.get(key);
    lSub(b, r, <<MSINCEW>>, <<ROWHT>>, i == 0 ? "leader" : (since instanceof String ? "since " + date((String) since) : "member") + (op != null && !on ? " - on another profile" : ""));
    if (rank == 4 && i > 0) {
      if (rr == 2) kbtn(b, ev, r, "SkyyIsPr" + i, "Promote", <<BROW>>, "pr" + i);
      else kbtn(b, ev, r, "SkyyIsDm" + i, "Demote", <<BROW>>, "dm" + i);
      gap(b, r, 8, <<ROWHT>>);
      kbtn(b, ev, r, "SkyyIsKk" + i, this.confirm.equals("kk:" + key) ? "Sure?" : "Kick", <<BROWDEL>>, "kk" + i);
    }
  }
  if (total > shown) lCap(b, P, 0, 25, "... and " + (total - shown) + " more - /island info lists everyone.");
  if (rank >= 3) {
    String pend = @PKG@.IslandCoop.pendingText(hk);
    if (pend.length() > 0) lInfo(b, P, 0, 25, "Invited: " + pend);
  }
  gap(b, P, 0, 6);
  String[] tr = @PKG@.IslandStore.split(s.trusted);
  lSec(b, P, 0, <<HEADH>>, "Trusted players - build only  (" + tr.length + " / " + @PKG@.IslandCfg.TRUSTED_MAX + ")");
  this.trustKeys = new java.util.ArrayList();
  if (tr.length == 0) {
    // 0.5.3: text only (same label, same style), from the island's grid; a heavily customised grid points to the Permissions tab
    String nt = @PKG@.IslandPerms.trustedDeniedText(s);
    String th = "Nobody yet. Trusted players may place and break blocks, use crafting benches and pick up items" + (nt.length() > 0 ? " - not " + nt : "") + ".";
    if (th.length() > 160) th = "Nobody yet. Trusted players may place and break blocks, use crafting benches and pick up items (the Permissions tab lists the rest).";
    if (!@PKG@.IslandPerms.trustedBuilds(s)) th = "Nobody yet. The Permissions tab shows what Trusted players may do on this island.";
    lCap(b, P, 0, 26, th);
    return;
  }
  int per = 10;
  int pages = (tr.length + per - 1) / per;
  if (this.trustPage >= pages) this.trustPage = pages - 1;
  if (this.trustPage < 0) this.trustPage = 0;
  int start = this.trustPage * per;
  int left = tr.length - start;
  if (left > per) left = per;
  int nrows = (left + 1) / 2;
  b.appendInline(P, <<TLIST>>);
  for (int ri = 0; ri < 5; ri++) {
    int a0 = start + ri * 2;
    if (a0 >= tr.length || a0 >= start + per) break;
    String r = rowL(b, "#SkyyIsTList", "SkyyIsTr" + ri, <<ROWHT>>);
    for (int c = 0; c < 2; c++) {
      int ix = a0 + c;
      if (ix >= tr.length) break;
      int slot = this.trustKeys.size();
      this.trustKeys.add(tr[ix]);
      if (c == 1) gap(b, r, <<TCOLGAP>>, <<ROWHT>>);
      String pn = tr[ix].length() > 36 ? "  (" + @PKG@.IslandStore.profileNameOf(tr[ix]) + ")" : "";
      lName(b, r, <<TNAMEW>>, <<ROWHT>>, "  " + @PKG@.IslandStore.nameOf(s, tr[ix]) + pn);
      if (rank >= 3) kbtn(b, ev, r, "SkyyIsUt" + slot, "Untrust", <<BROWDEL>>, "ut" + slot);
      else gap(b, r, <<BROWDELW>>, <<ROWHT>>);
    }
  }
  if (pages > 1) {
    String pid = "SkyyIsL" + this.nid;
    this.nid = this.nid + 1;
<<TPAGER>>
    ev.addEventBinding(@BT@.Activating, "#SkyyIsTp", @EVD@.of("a", "tp"));
    ev.addEventBinding(@BT@.Activating, "#SkyyIsTn", @EVD@.of("a", "tn"));
    String pt = "Page " + (this.trustPage + 1) + " / " + pages;
    b.set("#" + pid + ".Text", pt == null ? "" : pt);
  }
}"""), is_src(r"""
public void buildPerms(@UCB@ b, @UEB@ ev, java.util.UUID u, String hk, @PKG@.IslandSettings s, int rank) {
  String P = "#SkyyIsBody";
  if (s.world == null) {
    gap(b, P, 0, 30);
    lEmpty(b, P, 0, 34, "Create your island first (Overview tab).");
    return;
  }
  boolean ed = rank >= 3;
  String r0 = rowPB(b, P, "SkyyIsPTop", <<LINEH>>);
  lTextW(b, r0, <<PTOPW>>, <<LINEH>>, ed ? "Click a cell to allow or deny. Allowing a role also allows every role to its right; denying it also denies every role to its left." : "Only the owner and island admins can change these.");
  if (ed) {
    gap(b, r0, 16, <<LINEH>>);
    kbtn(b, ev, r0, "SkyyIsPdef", this.confirm.equals("pdef") ? "Click again to reset" : "Reset to defaults", <<BPDEF>>, "pdef");
  }
  lCap(b, P, 0, 25, @PKG@.IslandCfg.STRICT_OTHER ? "Server rule: a player who has a role here on ANOTHER of their profiles only gets doors, seats and mobs while on the wrong profile (no items move between profiles)." : "Server rule: a player who has a role here on ANOTHER of their profiles can't drop items while on the wrong profile.");
  String rh = rowH(b, P, "SkyyIsPHdr", <<HEADH>>);
  lColH(b, rh, <<PWHATW>>, <<HEADH>>, "   What");
  String[] cols = new String[] { "Visitor", "Trusted", "Member", "Admin" };
  for (int c = 0; c < 4; c++) {
    gap(b, rh, <<PGAP>>, <<HEADH>>);
    lColHC(b, rh, <<PCELLW>>, <<HEADH>>, cols[c]);
  }
  gap(b, rh, <<PGAP>>, <<HEADH>>);
  lColHC(b, rh, <<POWNW>>, <<HEADH>>, "Owner");
  String letters = "vtma";
  int nperm = s.perm.length < @PKG@.IslandPerms.LABELS.length ? s.perm.length : @PKG@.IslandPerms.LABELS.length;
  b.appendInline(P, <<PLIST>>);
  for (int i = 0; i < s.perm.length && i < @PKG@.IslandPerms.LABELS.length; i++) {
    String r = rowL(b, "#SkyyIsPList", "SkyyIsPRow" + i, <<ROWHT>>);
    twoLine(b, r, @PKG@.IslandPerms.LABELS[i], @PKG@.IslandPerms.HINTS[i]);
    for (int c = 0; c < 4; c++) {
      boolean yes = c >= s.perm[i];
      String code = two(i) + String.valueOf(letters.charAt(c));
      gap(b, r, <<PGAP>>, <<ROWHT>>);
      if (ed) kbtn(b, ev, r, "SkyyIsPc" + code, yes ? "YES" : "NO", yes ? <<BYESA>> : <<BNOA>>, yes ? <<BYESZ>> : <<BNOZ>>, "pc" + code);
      else cell(b, r, <<PCELLW>>, <<ROWHT>>, yes, yes ? "YES" : "NO");
    }
    gap(b, r, <<PGAP>>, <<ROWHT>>);
    lCapC(b, r, <<POWNW>>, <<ROWHT>>, "always");
  }
}"""), is_src(r"""
public void buildVisitors(@UCB@ b, @UEB@ ev, java.util.UUID u, String k, String hk, @PKG@.IslandSettings s, int rank) {
  String P = "#SkyyIsBody";
  if (s.world == null) {
    gap(b, P, 0, 30);
    lEmpty(b, P, 0, 34, "Create your island first (Overview tab).");
    return;
  }
  boolean ed = rank >= 3;
  lSec(b, P, 0, <<HEADH>>, "Who may visit");
  if (ed) {
    String r = rowPB(b, P, "SkyyIsVmRow", <<LINEH>>);
    String[] t = new String[] { "Public (anyone)", "Friends (members + trusted)", "Closed (members only)" };
    for (int i = 0; i < 3; i++) {
      if (i > 0) gap(b, r, <<VMGAP>>, <<LINEH>>);
      kbtn(b, ev, r, "SkyyIsVm" + i, t[i], i == s.mode ? <<BMODEONA>> : <<BMODEOFFA>>, i == s.mode ? <<BMODEONZ>> : <<BMODEOFFZ>>, "vm" + i);
    }
  } else lBold(b, P, 0, 34, "Visits: " + @PKG@.IslandCfg.modeLabel(s.mode));
  String r2 = rowPB(b, P, "SkyyIsVlRow", <<LINEH>>);
  lBold(b, r2, 170, <<LINEH>>, "Visitor limit");
  if (ed) {
    kbtn(b, ev, r2, "SkyyIsVlm", "-", <<BSTEP>>, "vlm");
    lValC(b, r2, 80, <<LINEH>>, String.valueOf(s.limit));
    kbtn(b, ev, r2, "SkyyIsVlp", "+", <<BSTEP>>, "vlp");
  } else lVal(b, r2, 200, <<LINEH>>, String.valueOf(s.limit));
  gap(b, r2, 60, <<LINEH>>);
  lBold(b, r2, 140, <<LINEH>>, "Visit ping");
  if (ed) kbtn(b, ev, r2, "SkyyIsVn", s.notify ? "On" : "Off", s.notify ? <<BTGLONA>> : <<BTGLOFFA>>, s.notify ? <<BTGLONZ>> : <<BTGLOFFZ>>, "vn");
  else lVal(b, r2, 140, <<LINEH>>, s.notify ? "On" : "Off");
  lCap(b, r2, <<PINGW>>, <<LINEH>>, "   Ping = a chat line to the owner and members when someone visits.");
  gap(b, P, 0, 6);
  java.util.ArrayList vu = new java.util.ArrayList();
  java.util.ArrayList vn = new java.util.ArrayList();
  java.util.ArrayList vr = new java.util.ArrayList();
  @WLD@ w = @PKG@.IslandStore.loadedWorld(s.world);
  if (w != null) {
    java.util.Iterator it = w.getPlayerRefs().iterator();
    while (it.hasNext()) {
      @PR@ p = (@PR@) it.next();
      if (p == null || !p.isValid()) continue;
      vu.add(p.getUuid().toString());
      vn.add(p.getUsername());
      vr.add(Integer.valueOf(@PKG@.IslandPerms.isAdmin(p) ? 9 : @PKG@.IslandPerms.rank(hk, p.getUuid(), s)));
    }
  }
  String[] bn = @PKG@.IslandStore.split(s.banned);
  String rh = rowH(b, P, "SkyyIsVHdr", <<HEADH>>);
  lColH(b, rh, <<VSIDEW>>, <<HEADH>>, "   On the island now (" + vu.size() + ")" + (w == null ? " - the island is not loaded" : ""));
  gap(b, rh, <<VGAP>>, <<HEADH>>);
  lColH(b, rh, <<BSIDEW>>, <<HEADH>>, "Banned (" + bn.length + " / " + @PKG@.IslandCfg.BANS_MAX + ")");
  this.visUuids = new java.util.ArrayList();
  this.banKeys = new java.util.ArrayList();
  int per = 8;
  int bpages = (bn.length + per - 1) / per;
  if (bpages < 1) bpages = 1;
  if (this.banPage >= bpages) this.banPage = bpages - 1;
  if (this.banPage < 0) this.banPage = 0;
  int bstart = this.banPage * per;
  int nv = vu.size() < per ? vu.size() : per;
  int nb = bn.length - bstart;
  if (nb > per) nb = per;
  if (nb < 0) nb = 0;
  int nrows = nv > nb ? nv : nb;
  if (nrows > 0) b.appendInline(P, <<VLIST>>);
  for (int i = 0; i < per; i++) {
    boolean hasV = i < vu.size();
    int bi = bstart + i;
    boolean hasB = bi < bn.length;
    if (!hasV && !hasB) break;
    String r = rowL(b, "#SkyyIsVList", "SkyyIsVRow" + i, <<ROWHT>>);
    if (hasV) {
      String us = (String) vu.get(i);
      this.visUuids.add(us);
      boolean me = us.equals(u.toString());
      int tr = ((Integer) vr.get(i)).intValue();
      boolean adm = tr == 9;
      int used = 0;
      gap(b, r, <<VNAMEIN>>, <<ROWHT>>);
      lName(b, r, <<VNAMEW>>, <<ROWHT>>, "  " + vn.get(i) + (me ? " (you)" : ""));
      lNameCol(b, r, <<VROLEW>>, <<ROWHT>>, adm ? <<CADMIN>> : @PKG@.IslandPerms.roleColor(tr), adm ? "Server admin" : @PKG@.IslandPerms.roleName(tr));
      used = <<VNAMEROLEW>>;
      if (!me && !adm && tr <= 1 && rank >= 2) { kbtn(b, ev, r, "SkyyIsVe" + i, "Expel", <<BVEXPEL>>, "ve" + i); gap(b, r, 6, <<ROWHT>>); used += <<VEW>> + 6; }
      if (!me && !adm && tr == 0 && rank >= 3) { kbtn(b, ev, r, "SkyyIsVt" + i, "Trust", <<BVTRUST>>, "vt" + i); gap(b, r, 6, <<ROWHT>>); used += <<VTW>> + 6; }
      if (!me && !adm && tr <= 1 && rank >= 3) { kbtn(b, ev, r, "SkyyIsVb" + i, this.confirm.equals("vb:" + us) ? "Sure?" : "Ban", <<BVBAN>>, "vb" + i); used += <<VBW>>; }
      if (used < <<VSIDEW>>) gap(b, r, <<VSIDEW>> - used, <<ROWHT>>);
    } else {
      this.visUuids.add("");
      gap(b, r, <<VSIDEW>>, <<ROWHT>>);
    }
    gap(b, r, <<VGAP>>, <<ROWHT>>);
    if (hasB) {
      this.banKeys.add(bn[bi]);
      lBan(b, r, <<BNAMEW>>, <<ROWHT>>, @PKG@.IslandStore.nameOf(s, bn[bi]));
      if (rank >= 3) kbtn(b, ev, r, "SkyyIsVu" + i, "Unban", <<BVUNBAN>>, "vu" + i);
    } else this.banKeys.add("");
  }
  if (vu.isEmpty() && bn.length == 0) lCap(b, P, 0, 30, "   Nobody is on the island right now, and nobody is banned.");
  gap(b, P, 0, 6);
  String rn = rowP(b, P, "SkyyIsVNav", <<NAVH>>);
  kbtn(b, ev, rn, "SkyyIsVr", "Refresh list", <<BNAV>>, "vr");
  if (bpages > 1) {
    gap(b, rn, <<NAVGAP>>, <<NAVH>>);
    String pid = "SkyyIsL" + this.nid;
    this.nid = this.nid + 1;
<<BPAGER>>
    ev.addEventBinding(@BT@.Activating, "#SkyyIsBp", @EVD@.of("a", "bp"));
    ev.addEventBinding(@BT@.Activating, "#SkyyIsBn", @EVD@.of("a", "bn"));
    String pt = "Bans " + (this.banPage + 1) + " / " + bpages;
    b.set("#" + pid + ".Text", pt == null ? "" : pt);
  }
}"""), is_src(r"""
public void buildIsland(@UCB@ b, @UEB@ ev, java.util.UUID u, String hk, @PKG@.IslandSettings s, int rank) {
  String P = "#SkyyIsBody";
  if (s.world == null) {
    gap(b, P, 0, 30);
    lEmpty(b, P, 0, 34, "Create your island first (Overview tab).");
    return;
  }
  boolean ed = rank >= 3;
  gap(b, P, 0, 10);
  lSec(b, P, 0, <<HEADH>>, "Island rules");
  String r1 = rowL(b, P, "SkyyIsIpRow", <<LINEH>>);
  lName(b, r1, <<ISLNAMEW>>, <<LINEH>>, "   PvP - players can hurt each other");
  if (ed) kbtn(b, ev, r1, "SkyyIsIp", s.pvp ? "ON" : "OFF", s.pvp ? <<BISLONA>> : <<BISLOFFA>>, s.pvp ? <<BISLONZ>> : <<BISLOFFZ>>, "ipvp");
  else lStateC(b, r1, <<ISLTGLW>>, <<LINEH>>, s.pvp ? <<CWARN>> : <<CTEXT>>, s.pvp ? "ON" : "OFF");
  gap(b, r1, 12, <<LINEH>>);
  lCap(b, r1, <<ISLHINTW>>, <<LINEH>>, "    Turning PvP on sends visitors to the hub. Members and trusted players stay.");
  gap(b, P, 0, 8);
  String r2 = rowL(b, P, "SkyyIsIsRow", <<LINEH>>);
  lName(b, r2, <<ISLNAMEW>>, <<LINEH>>, "   Mob spawning");
  if (ed) kbtn(b, ev, r2, "SkyyIsIs", s.spawning ? "ON" : "OFF", s.spawning ? <<BISLONA>> : <<BISLOFFA>>, s.spawning ? <<BISLONZ>> : <<BISLOFFZ>>, "ispawn");
  else lStateC(b, r2, <<ISLTGLW>>, <<LINEH>>, <<CTEXT>>, s.spawning ? "ON" : "OFF");
  gap(b, r2, 12, <<LINEH>>);
  lCap(b, r2, <<ISLHINTW>>, <<LINEH>>, "    Needs a biome with wildlife - Void Sky (today's islands) has none, so nothing spawns yet.");
  gap(b, P, 0, 20);
  lText(b, P, 0, 28, "Coming in a later version: island biome (grass colour, sky, weather, wildlife), a weather lock and a visitor landing point.");
  if (!ed) lCap(b, P, 0, 28, "Only the owner and island admins can change these.");
}"""), is_src(r"""
public void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {
  this.nid = 0;
  long now = System.currentTimeMillis();
  if (this.confirmUntil < now) this.confirm = "";
  java.util.UUID u = this.playerRef.getUuid();
  String k = @PKG@.IslandStore.pkey(u);
  String hk = @PKG@.IslandStore.homeKey(u);
  @PKG@.IslandSettings s = @PKG@.IslandStore.settings(hk);
  int rank = @PKG@.IslandPerms.rank(hk, u, s);
  boolean has = s.world != null;
  String title = has ? @PKG@.IslandStore.ownerDisplay(hk, s) + "'s Island" : "Your Island";
  // the vanilla decorated window (page_shell): root #SkyyIsF, the title bar with the title label #SkyyIsL0 (= 0.5.3's first lbl id,
  // same text), the body #SkyyIsRoot (0.5.3's root id) and the ornaments
<<SHELL>>
  this.nid = 1;
  String sub = "Your role: " + @PKG@.IslandPerms.roleName(rank) + @PKG@.IslandStore.profileLabel(u);
  if (has) sub = sub + "      Co-op " + (1 + @PKG@.IslandStore.count(s.members)) + " / " + @PKG@.IslandCfg.COOP_MAX + "      Visits: " + @PKG@.IslandCfg.modeName(s.mode);
  lRole(b, "#SkyyIsRoot", 0, <<ROLEH>>, @PKG@.IslandPerms.roleColor(rank), sub);
  buildTabs(b, ev);
  b.appendInline("#SkyyIsRoot", <<BODY>>);
  try {
    if (s.bad) lErr(b, "#SkyyIsBody", 0, 60, "Your island file can't be read right now - click Refresh in a moment. Nothing was changed.");
    else if (this.tab == 1) buildMembers(b, ev, u, k, hk, s, rank);
    else if (this.tab == 2) buildPerms(b, ev, u, hk, s, rank);
    else if (this.tab == 3) buildVisitors(b, ev, u, k, hk, s, rank);
    else if (this.tab == 4) buildIsland(b, ev, u, hk, s, rank);
    else buildOverview(b, ev, u, k, hk, s, rank);
  } catch (Throwable t) {
    @PKG@.IslandStore.warn("island menu tab " + this.tab + " failed: " + t);
    lErr(b, "#SkyyIsBody", 0, 34, "This tab could not be drawn - the server log has the details.");
  }
  lResult(b, "#SkyyIsRoot", 0, <<RESH>>, colorOf(this.info), textOf(this.info));
  b.appendInline("#SkyyIsRoot", <<SEP>>);
  b.appendInline("#SkyyIsRoot", <<FOOT>>);
  kbtn(b, ev, "#SkyyIsBottom", "SkyyIsRef", "Refresh", <<BFOOT>>, "refresh");
  b.appendInline("#SkyyIsBottom", <<FOOTGAP>>);
  kbtn(b, ev, "#SkyyIsBottom", "SkyyIsClose", "Close", <<BCLOSE>>, "close");
}""")]
for _src in IS_TAB_SRC:
    M(page, _src)
# only proven properties on the page (kit 1.4: one table of what the deployed pages use, minus PROBED - nothing UNVERIFIED), and no
# b.set on a TextButton (UNVERIFIED button-text)
IS_PROVEN = SUI.assert_proven(IS_MARKUPS, what="SkyyIslands island menu")
for _mk in IS_MARKUPS:
    _r = SUI.render(_mk)
    for _bad in ("FlexWeight", "WrapMaxLines", "LetterSpacing", "LayoutMode: Center", "LayoutMode: Right", "LayoutMode: Full"):
        assert _bad not in _r, "the island menu must not use %s yet: %s" % (_bad, _r[:80])
assert not [t for t in re.findall(r'b\.set\("#(SkyyIs[A-Za-z]+)', "\n".join(IS_SRC)) if "Btn" in t or t in ("SkyyIsTp", "SkyyIsTn")]
# the page id = a hash of every piece of IslandMenuPage that 0.5.4 makes from the kit (its look methods, colorOf / textOf, the tab
# builders and build()): a later kit change that alters the page changes it. It is in the ready log line.
import hashlib
IS_PAGE_ID = hashlib.sha256("\n".join(IS_SRC).encode("utf8")).hexdigest()[:12]
IS_PAGE_CHECKED = "@@PAGECHECKED@@"   # the page id SkyyIslands/test_skyyislands_0.5.4.py last passed on (tools/islands_0_5_4_patch.py)
T["KITID"] = KIT_ID           # the ready log line names the kit ...
T["PAGEID"] = IS_PAGE_ID      # ... and the page build
# ---- page gate (0.5.4 review): an unchecked page never becomes SkyyIslands-0.5.4.jar (tools/deploy_set.py deploys the jar on disk)
IS_JAR_TAG = ""
if IS_PAGE_ID == IS_PAGE_CHECKED:
    print("island menu page %s = the page SkyyIslands/test_skyyislands_0.5.4.py last passed on" % IS_PAGE_ID)
elif os.environ.get("SKYY_UNCHECKED_PAGE") == "1":
    IS_JAR_TAG = "-UNCHECKED"
    print("WARNING: island menu page %s is NOT the page SkyyIslands/test_skyyislands_0.5.4.py last passed on (%s). SKYY_UNCHECKED_PAGE=1: "
          "building SkyyIslands/SkyyIslands-0.5.4-UNCHECKED.jar for the harness only (tools/deploy_set.py never deploys that name) - run "
          "python SkyyIslands/test_skyyislands_0.5.4.py --jar SkyyIslands/SkyyIslands-0.5.4-UNCHECKED.jar, then set PAGE_CHECKED in "
          "tools/islands_0_5_4_patch.py, regenerate and rebuild without the flag" % (IS_PAGE_ID, IS_PAGE_CHECKED))
else:
    raise SystemExit("island menu page %s is NOT the page SkyyIslands/test_skyyislands_0.5.4.py last passed on (%s) - the kit output "
                     "or the page code changed the page. Stopped: no jar written (a SkyyIslands-0.5.4.jar already on disk is the checked page). Build once "
                     "with SKYY_UNCHECKED_PAGE=1 (-> SkyyIslands-0.5.4-UNCHECKED.jar), run python SkyyIslands/test_skyyislands_0.5.4.py "
                     "--jar SkyyIslands/SkyyIslands-0.5.4-UNCHECKED.jar, then set PAGE_CHECKED in tools/islands_0_5_4_patch.py, "
                     "regenerate and rebuild" % (IS_PAGE_ID, IS_PAGE_CHECKED))
# ---- end page gate
'''

rep("@@LOOKHELPERS@@", LOOKHELPERS)
rep("@@TABS@@", fill(TABS, {"PAGECHECKED": PAGE_CHECKED}))

# the ready log line names the kit and the page build
rep('log("[SkyyIslands] @VERSION@ ready - /island [menu|', 'log("[SkyyIslands] @VERSION@ ready (@KITID@, page @PAGEID@) - /island [menu|')

# the page gate's jar name (0.5.4 review): an unchecked page built with SKYY_UNCHECKED_PAGE=1 never lands on the deployable name
rep('jar = os.path.join(HERE, "SkyyIslands-%s.jar" % VERSION)\n',
    '# 0.5.4: IS_JAR_TAG is "-UNCHECKED" for a page the harness has not passed (the page gate; tools/deploy_set.py deploys only\n'
    '# SkyyIslands-<version>.jar); a checked build removes that leftover\n'
    'jar = os.path.join(HERE, "SkyyIslands-%s%s.jar" % (VERSION, IS_JAR_TAG))\n'
    '_unchecked = os.path.join(HERE, "SkyyIslands-%s-UNCHECKED.jar" % VERSION)\n'
    'if not IS_JAR_TAG and os.path.isfile(_unchecked):\n'
    '    os.remove(_unchecked)\n')

# ================================================================================================ checks on the result
assert "@@" not in s, "a @@ token is left in the generated script"
assert s.count("registerCommand(") == REG0, "command registrations changed"
for k in KEEP:
    assert k in s, "a block that must stay 0.5.3's changed: %s" % k[:80]
for x in SECURITY + LOCKS:
    assert s.count(x) == 1, "a kept line changed: " + x[:80]
# 0.5.3's event bindings: the name box / invite / trust lines verbatim; btn()'s generic binding lives on in kbtn()
NEWBIND = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
for ln in BIND0[1:]:
    assert ln in NEWBIND, "a 0.5.3 binding line is gone: " + ln
assert '  if (payload != null) ev.addEventBinding(@BT@.Activating, "#" + id, @EVD@.of("a", payload));' in NEWBIND
# every 0.5.3 payload is still bound somewhere (tab / button payloads, the pc / pr / dm / kk / ut / ve / vt / vb / vu families)
for pay in ("tabov", "tabmem", "tabperm", "tabvis", "tabisl", '"create"', '"go"', '"acc"', '"dec"', '"disb"', '"reset"', '"leave"',
            '"pr" + i', '"dm" + i', '"kk" + i', '"ut" + slot', '"tp"', '"tn"', '"pdef"', '"pc" + code', '"vm" + i', '"vlm"', '"vlp"',
            '"vn"', '"ve" + i', '"vt" + i', '"vb" + i', '"vu" + i', '"vr"', '"bp"', '"bn"', '"ipvp"', '"ispawn"', '"refresh"', '"close"'):
    assert pay in s[s.index("IS_TAB_SRC = [is_src("):], "payload %s is not bound in 0.5.4" % pay
# every text 0.5.3's page code wrote is in the 0.5.4 page code (the harness compares the values at run time)
_new_tabs = s[s.index("# ---- 0.5.4: the island menu look"):s.index("IS_PROVEN = SUI.assert_proven")]
_missing = [t for t in OLD_TEXTS if t not in _new_tabs]
assert not _missing, "0.5.3 page texts missing in 0.5.4: %s" % _missing
# the 0.5.3 custom look is gone from the page (the colours IslandStore / IslandPerms keep for chat + roles are UI_DATA_COLORS)
_page = s[s.index("# ---- 0.5.4: the island menu look"):s.index('M(page, r"""\npublic void handleDataEvent(')]
for c in ("#0b1524", "#ffd070", "#1d3a5f", "#2f5a8f", "#0f2038", "#7a5a10", "#9a7418", "#4a3608", "#132236", "#142030", "#1c2c44",
          "#1d3320", "#1f5a34", "#2c7a48", "#133a22", "#5a2424", "#7a3030", "#3a1414", "#2a3340", "#3a4556", "#1a2230", "#2f6a3a",
          "#3f8a4c", "#6a2f2f", "#8a3f3f", "#16263a", "#50d060", "#55606e", "#e6f2ff", "TextButtonStyle(Default: (Background: #",
          "public static String style(", "public void lbl(", "public void btn(", "public String row("):
    assert c not in _page, "0.5.3 custom look left in the 0.5.4 page: " + c
assert s.index("SUI.verify()") < s.index("J = B.start()"), "verify() must run before the build"
assert s.index("T[\"PAGEID\"] = IS_PAGE_ID") < s.index("ready (@KITID@, page @PAGEID@)"), "IS_PAGE_ID before the log line"
# the page gate: a mismatch stops the build unless SKYY_UNCHECKED_PAGE=1, which only ever writes the -UNCHECKED jar name
_gate = s[s.index("# ---- page gate (0.5.4 review)"):s.index("# ---- end page gate")]
assert _gate.count("raise SystemExit(") == 1 and _gate.count('os.environ.get("SKYY_UNCHECKED_PAGE") == "1"') == 1, "page gate"
assert s.index("# ---- end page gate") < s.index('jar = os.path.join(HERE, "SkyyIslands-%s%s.jar" % (VERSION, IS_JAR_TAG))')
assert s.count("IS_JAR_TAG = ") == 2 and s.count('"SkyyIslands-%s.jar"') == 0, "the jar name goes through the page gate"
# javassist: methods before callers - the look helpers and colorOf / textOf come before the tab builders, build() before handleDataEvent
_o = [s.index(x) for x in ("public void kbtn(", "public void closePage(", "public void buildTabs(", "public void buildOverview(",
                           "public void build(@REF@ ref", "public void handleDataEvent(")]
assert _o == sorted(_o), "page method order"
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.5.3 had %d)" % (s.count(LF), OLD.count(LF)))
