"""Derive SkyyIslands/build_skyyislands_0.5.3.py from the LIVE 0.5.2 (edit THIS file, then regenerate: python tools/islands_0_5_3_patch.py,
then python SkyyIslands/build_skyyislands_0.5.3.py; never --deploy - tools/deploy_set.py deploys the whole set).
Base = build_skyyislands_0.5.2.py (the tools/deploy_set.py SET pin, generated by tools/islands_0_5_2_patch.py from 0.5.1 = the security
hotfix; NEVER 0.5). 0.5.3 = Skyy's 2026-09-25 island locks (OPEN-QUESTIONS.md "Islands", research/Island-Settings-Spec.md 1.2 / 3.2 /
4 / 6 / 9.2) with the beds part replaced by Skyy's 2026-09-28 decision (SkyWynn-Decisions.md change note 10: beds MEMBER-only):
 - CO-OP INVITES BY ISLAND ADMINS: coop.adminsInvite defaults to true (IslandCfg.ADMINS_INVITE field, loader default for a missing or
   empty line, the new-install config text, the Server Setup row default + help). The owner still alone kicks, promotes, demotes,
   disbands and resets. /island invite's refusal names who may invite ("the island owner and island admins" while the switch is on).
 - VISITOR LIMIT 10: defaults.visit.limit defaults to 10 (field DEF_LIMIT, loader default, config text, row default). Every island is
   still capped at visit.limitMax (10) by IslandSettings.parse, unchanged.
 - BEDS STAY MEMBER (Skyy 2026-09-28, SkyWynn-Decisions.md change note 10 - replaces the 2026-09-25 'visitors may use beds' lock:
   in Hytale sleeping in a bed claims it as that player's respawn point, and the island owner then can't sleep in it or break it).
   The default grid is 0.5.2's, unchanged and asserted below (the whole FLAGS default column equals the base's): beds member,
   containers (chests) member, harvest (crops) member, processing (furnaces) member, animals member, crafting (benches) trusted,
   doors + seats visitor. So visitors: doors, seats (+ hostile mobs); Trusted: no chests, furnaces, beds, crops or farm animals.
   The other-profile rule (perm.otherProfileStrict) still gives a role held on another profile only doors, seats, mobs (spec 3.2).
   Every text that names what visitors / Trusted players may do is built from the island's own grid (visitor welcome line =
   IslandPerms.visitorAllowedText, the trusted texts below), so none of them says visitors may use beds on the default grid.
 - ISLAND OWNERS' OWN CHOICES STAY (the setter paths, asserted below): an island file stores perm.<flag> / visit.limit ONLY after its
   owner (or an island admin) changed that one value - a grid click writes just the clicked flag (IslandCoop.clickPerm: one
   perm.<flag> line + settings=1), the limit buttons just visit.limit (changeLimit), and "Reset to defaults" REMOVES every perm.* line
   (resetPerms: value null), it never writes the current defaults. So an island whose owner never touched the limit follows the
   new server default at once (IslandStore.reparseAll re-parses the cache when the default changes), an island with its own perm.<flag>
   or visit.limit line (any value, also one that equals the old default) keeps it, and after "Reset to defaults" the island follows
   the server defaults again, now and after later default changes. No island file is read for or rewritten by the 0.5.3 step.
 - The two texts that listed what Trusted players may not do ("not chests, furnaces, crops, beds or animals": the /island trust answer
   and the Members tab hint when nobody is trusted) are built from the island's own grid: IslandPerms.trustedDeniedText (flags whose
   minimum is above trusted; default grid "chests, furnaces, beds, crops or farm animals") and IslandPerms.trustedBuilds (Trusted may place,
   break, use benches and pick up here). An owner who closed building to Trusted gets "the Permissions tab shows what Trusted players
   may do" instead of a wrong "they may build"; a Members hint longer than 160 characters (a heavily customised grid) points to the
   Permissions tab for the rest. Text only: no element, style or size of the /island menu changed (Skyy 2026-09-28 vanilla-look
   rule: the menu keeps its look; nothing was restyled - the menu's vanilla pass is RESUME step 5).
 - UNTOUCHED-DEFAULT MIGRATION (once per world, at the first 0.5.3 start): IslandCfg.plan053() runs in setup() right BEFORE the config
   kit starts and reads config.properties as it is on disk. Two keys (beds is NOT one of them since Skyy's 2026-09-28 bed decision:
   defaults.perm.beds is neither planned, changed nor named in the marker). A line migrates only when its trimmed value is EXACTLY the
   old default (coop.adminsInvite=false, defaults.visit.limit=5) AND config-changes.log (+ its 3 rotated copies) never
   names that key in a line written by anyone but this step itself - i.e. no admin ever set it in game, by command, import, restore,
   undo or a hand edit the kit noticed. Any other value (the new default, a customised value, a line an admin set back to the old
   default) is kept; a missing / empty line already means the new default. IslandHooks.apply053(mask) then sets each untouched line
   right AFTER CfgPub.start through the kit's own path (CfgFn.set, name "SkyyIslands 0.5.3 update", via console, confirm yes):
   validated, the running value changes at once (afterDefaults re-parses the islands for the limit), then
   CfgPub.flush() writes the file NOW (line replaced in place: comments, order, line endings kept; config-history keeps the pre-0.5.3
   file - Server Setup -> Islands -> History can restore it; config-changes.log gets an 'ok' line - Undo offered in the Changes view;
   the kit's INFO line), plus one INFO line per migrated key with the reason and one summary line. The step is recorded in
   Skyy_SkyyIslands/migrations.properties (defaults.0.5.3=<time> | per-key outcome) only when every planned key applied AND the file
   on disk now holds the new value (re-read after the flush), so an admin who later sets a value back to the old default keeps it for
   good. No marker is written while config.properties, migrations.properties or a change log can't be read, a set did not apply (kit
   not started, file broken) or the write did not reach the disk (the kit retries every 30 s): the step simply looks again at the next
   start (its own log lines are ignored then, so a set whose save was lost is tried again). Island files are never touched by it.
 - CONFIG KIT: KEEP = 10 history copies per file (Skyy's 2026-09-25 lock, OPEN-QUESTIONS Server Setup 3; was 20). tools/skyycfg.py is
   kit 1.1 now (the live 0.5.2 jar was built on 1.0): custom rows' file lines (defaults.perm.*, defaults.visit.mode, tint.resend) now
   run IslandHooks.reloadCfg after the write by themselves - a harmless re-read of the file the kit just wrote. The build asserts
   kit >= 1.1.
 - Already live and kept as they are (asserted where they are code): co-op size 5 (coop.maxPlayers), /island reset cooldown 24 h with 3
   confirms (reset.cooldownHours / reset.confirmSeconds), no visits to your own dormant island while in a co-op (homeKey; /island visit
   goes to the target's HOME island). Biome change: slice B (biomes) is not built in any 0.5.x jar - there is nothing to price yet;
   the lock (free) applies when it is built.
 - REVIEW FIXES (2026-09-28): a co-op invite is re-checked at accept (IslandCoop.acceptProblem, also the Overview tab's invite row):
   the sender must still be allowed to invite to that island - the owner (any profile), or an island admin on that profile while
   coop.adminsInvite is on - so a demoted / kicked / banned admin, an admin who switched profile, or the switch turned off within
   invite.seconds makes the invite unusable ("that invite is no longer valid - ..."). An island admin's invite is told to the owner
   (if online: "<admin> invited <player> to your island ..."). Members tab hint: "they join your island" only for the owner ("the
   island" for an admin). The Trusted player's own lines (the trusted notice, /island visit, the arrival welcome) come from the island's
   grid (IslandPerms.trustedYouText) like the other 0.5.3 trusted texts. IslandCfg.plain() maps '\\' to '?' (Properties.load escapes).
 - BED REVERT (2026-09-28, change note 10): an earlier 0.5.3 build set beds to visitor and migrated an untouched defaults.perm.beds=member
   line. Now the grid default is member again, MIG_KEYS / MIG_OLD / MIG_NEW / MIG_WHY hold only the two other keys, and the marker lists
   only them. A test world that already ran that earlier build keeps what it wrote (defaults.perm.beds=visitor + its defaults.0.5.3
   marker): the step never plans beds and never touches that line again - an admin puts it back to member in Server Setup ->
   Islands (Default: Beds, or Undo in the Changes view).
 - KEPT: the 0.5.1 security fix (IslandReloadCmd: requirePermission("skyyislands.admin") + setPermissionGroups(new String[0]); lint
   perm_group_leaks), every command, system, bridge key, file format and Settings switch of 0.5.2. No new command, system or UI element.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyIslands", "build_skyyislands_0.5.2.py")
dst = os.path.join(ROOT, "SkyyIslands", "build_skyyislands_0.5.3.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
REG0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")
SUB0 = s.count("\nsub(")
IDS0 = sorted(set(re.findall(r"#(SkyyIs[A-Za-z0-9]*)", s)))


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:100])
    s = s.replace(old, new, 1)


def body(start, end='}""")'):
    """The Java source from `start` (unique) to the first `end` after it."""
    assert s.count(start) == 1, "body start not unique: " + start[:90]
    i = s.index(start)
    return s[i:s.index(end, i)]


# ---------------------------------------------------------------- 0.5.2 facts this version builds on (fail loudly if the base moved)
# The setter paths of island settings: a grid click writes ONLY the clicked flag, the limit buttons ONLY visit.limit, and Reset to
# defaults REMOVES every perm.* line. That is what lets an island whose owner never touched a value follow the new defaults while an
# owner's own choice stays (Skyy 2026-09-25: "islands whose owner customised a flag keep their choice").
_ck = body("public static String clickPerm(@PR@ pr, int f, int r) {")
assert ('setProps(hk, new String[] { "perm." + @PKG@.IslandCfg.FLAG_IDS[f], "settings" }, new String[] { @PKG@.IslandCfg.rankName(nm), "1" })'
        in _ck) and _ck.count("setProps(") == 1 and "int nm = r >= s.perm[f] ? r + 1 : r;" in _ck, "clickPerm changed"
_rs = body("public static String resetPerms(@PR@ pr) {")
assert ('for (int i = 0; i < n; i++) { ks[i] = "perm." + @PKG@.IslandCfg.FLAG_IDS[i]; vs[i] = null; }' in _rs
        and _rs.count("setProps(") == 1 and "DEF_PERM" not in _rs), "resetPerms changed (it must remove the lines, never write defaults)"
_cl = body("public static String changeLimit(@PR@ pr, int d) {")
assert 'new String[] { "visit.limit", "settings" }, new String[] { String.valueOf(n), "1" }' in _cl and _cl.count("setProps(") == 1
# ... and nothing else writes perm.<flag> or visit.limit into an island file (the only other island writers: lists, names, world, reset)
assert s.count('"perm." + @PKG@.IslandCfg.FLAG_IDS[') == 3   # clickPerm, resetPerms, IslandSettings.parse (read)
assert s.count('"visit.limit"') == 2 and s.count('p.getProperty("visit.limit")') == 1   # changeLimit (write) + parse (read)
# a missing island line = the server default at parse time (so a default change reaches every untouched island)
_pa = body("public static @PKG@.IslandSettings parse(String key, java.util.Properties p) {")
assert 'rankOf(p.getProperty("perm." + @PKG@.IslandCfg.FLAG_IDS[i]), dp[i])' in _pa and 'num(p.getProperty("visit.limit"), @PKG@.IslandCfg.DEF_LIMIT)' in _pa
# a server default change re-parses every cached island (custom rows: customSet, field rows: after=IslandHooks.afterDefaults)
_cs = body("public static Object[] customSet(String key, String value) {")
assert _cs.index("permPut(i, r);") < _cs.index("@PKG@.IslandStore.reparseAll();")
assert "field:IslandCfg.DEF_LIMIT@config.properties:defaults.visit.limit;after=IslandHooks.afterDefaults" in s
assert "field:IslandCfg.ADMINS_INVITE@config.properties:coop.adminsInvite\")" in s


# the permission grid's default column (FLAGS: id -> default minimum role); 0.5.3 keeps 0.5.2's grid (beds member: Skyy 2026-09-28)
def flag_defaults():
    return dict((m.group(1), m.group(2)) for m in re.finditer(r'\("(\w+)", "[^"]*", "[^"]*", "(visitor|trusted|member|admin|owner)"\)',
                                                             s[s.index("FLAGS = ["):s.index("RANKS = [")]))


FL0 = flag_defaults()
assert FL0["beds"] == "member" and FL0["doors"] == "visitor" and FL0["seats"] == "visitor", FL0

# ---------------------------------------------------------------- version, docstring, kit version
rep('VERSION = "0.5.2"', 'VERSION = "0.5.3"')
rep('import skyycfg as CFG   # 0.5.2: the admin config kit (tools/CONFIG-CONTRACT.md)\n',
    'import skyycfg as CFG   # 0.5.2: the admin config kit (tools/CONFIG-CONTRACT.md)\n'
    '# 0.5.3: built on config kit 1.1 or newer (tools/CONFIG-CONTRACT.md "Kit versions")\n'
    'assert tuple(int(x) for x in getattr(CFG, "KIT_VERSION", "1.0").split(".")) >= (1, 1), "SkyyIslands 0.5.3 needs config kit 1.1+"\n')
first = s.index('"""') + 3
s = s[:first] + (
    "0.5.3 (2026-09-28): Skyy's 2026-09-25 ISLAND LOCKS, derived from the live 0.5.2 by tools/islands_0_5_3_patch.py (edit the patch, not\n"
    "  this file; notes there). coop.adminsInvite default true (island admins may invite co-op members), defaults.visit.limit default 10.\n"
    "  Beds stay MEMBER (Skyy 2026-09-28, change note 10: sleeping claims a bed as the sleeper's respawn point) - the permission grid\n"
    "  is 0.5.2's (chests, furnaces, beds, crops, animals member; crafting benches trusted; doors + seats visitor). Untouched-default\n"
    "  migration once per world at the first start, those two keys only (beds is not migrated): a config line still EXACTLY the old\n"
    "  default (false / 5) that no admin ever set (config-changes.log never names it) is set through the config kit and written at once\n"
    "  (logged with Undo, History copy, INFO line); anything else is kept; done = Skyy_SkyyIslands/migrations.properties (a world that\n"
    "  already ran an earlier 0.5.3 build keeps its values). Island files are never rewritten: a grid click stores\n"
    "  only the clicked flag and Reset to defaults removes the lines, so an owner's own choice stays and untouched islands follow the new\n"
    "  defaults. Trusted-player texts built from the island's grid. Config kit KEEP 10 (kit 1.1). Menu look unchanged (text only).\n"
    "  Review fixes: co-op invites re-checked at accept (the sender must still be allowed to invite), the owner hears of an island\n"
    "  admin's invite, admin-correct Members hint, the Trusted player's own lines from the grid, plain() drops backslashes.\n") + s[first:]

# ---------------------------------------------------------------- 3. beds stay member (Skyy 2026-09-28, change note 10): the grid is 0.5.2's
rep('''    ("beds", "Beds", "Sleeping, setting your respawn", "member"),''',
    '''    ("beds", "Beds", "Sleeping, setting your respawn", "member"),   # 0.5.3: stays MEMBER-only (Skyy 2026-09-28, change note 10)''')

# ---------------------------------------------------------------- 1 + 2. new-install config text
rep('''    "defaults.visit.limit=5",''', '''    "defaults.visit.limit=10",''')
rep('''    "coop.adminsInvite=false",''', '''    "coop.adminsInvite=true",''')

# ---------------------------------------------------------------- IslandCfg fields + loader defaults
rep('"public static volatile int DEF_LIMIT = 5;"', '"public static volatile int DEF_LIMIT = 10;"')
rep('"public static volatile boolean ADMINS_INVITE = false;"', '"public static volatile boolean ADMINS_INVITE = true;"')
rep('''      DEF_LIMIT = (int) lng(p, "defaults.visit.limit", 5L, 1L, 100L);   // 0.5.2: the row range; IslandSettings.parse caps each island at LIMIT_MAX''',
    '''      DEF_LIMIT = (int) lng(p, "defaults.visit.limit", 10L, 1L, 100L);   // 0.5.3: default 10 (was 5); the row range; parse caps each island at LIMIT_MAX''')
rep('''      ADMINS_INVITE = "true".equalsIgnoreCase(String.valueOf(p.getProperty("coop.adminsInvite", "false")).trim());''',
    '''      String ai = p.getProperty("coop.adminsInvite");   // 0.5.3: a missing or empty line = the new default true (LOCKED 2026-09-25)
      ADMINS_INVITE = (ai == null || ai.trim().length() == 0) ? true : "true".equalsIgnoreCase(ai.trim());''')

# ---------------------------------------------------------------- IslandCfg: the 0.5.3 untouched-default plan (before the kit schema)
rep('''  for (int i = 0; i < e.length; i++) if (e[i].trim().length() > 0) an.add(e[i].trim());
  return an;
}""")

# =====================================================================================================================
# 0.5.2 admin config kit''', r'''  for (int i = 0; i < e.length; i++) if (e[i].trim().length() > 0) an.add(e[i].trim());
  return an;
}""")

# ---- 0.5.3: Skyy's 2026-09-25 island locks = new defaults. plan053() (setup, BEFORE the config kit starts) picks the config lines that
# still hold the untouched OLD default; IslandHooks.apply053 (right after CfgPub.start) sets them through the kit. Once per world:
# migrations.properties records the step (see tools/islands_0_5_3_patch.py). Island files are never read or written here.
# Two keys: beds stay member (Skyy 2026-09-28, change note 10), so defaults.perm.beds is never planned, set or named in the marker.
for f in ('public static final String[] MIG_KEYS = new String[] { "coop.adminsInvite", "defaults.visit.limit" };',
          'public static final String[] MIG_OLD = new String[] { "false", "5" };',
          'public static final String[] MIG_NEW = new String[] { "true", "10" };',
          'public static final String[] MIG_WHY = new String[] { "island admins may invite co-op members now (only the owner kicks, promotes, disbands and resets)", '
          '"islands whose owner never set a visitor limit allow 10 visitors at once now (never above visit.limitMax)" };',
          'public static final String MIG_STEP = "defaults.0.5.3";',
          'public static final String MIG_BY = "SkyyIslands 0.5.3 update";',
          'public static volatile String[] MIG_NOTE = new String[0];'):
    F(cfg, f)
# a Properties file: empty = the file does not exist, null = it exists (or can't be told apart) and could not be read
M(cfg, r"""
public static java.util.Properties readProps(java.nio.file.Path f) {
  try {
    java.util.Properties p = new java.util.Properties();
    if (java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) {
      java.io.InputStream in = java.nio.file.Files.newInputStream(f, new java.nio.file.OpenOption[0]);
      try { p.load(in); } finally { in.close(); }
    } else if (!java.nio.file.Files.notExists(f, new java.nio.file.LinkOption[0])) {
      return null;
    }
    return p;
  } catch (Throwable t) { return null; }
}""")
# the keys the kit's change log names (columns time/name/uuid/via/key/old/new/status: key = column 5), the live file + its 3 rotated
# copies (config-changes.log.1-3), leaving out the lines written by `skip` (this step's own name: a set whose save was lost must be
# tried again); null = one of them exists but can't be read (then nobody can tell whether an admin set a value - the step waits)
M(cfg, r"""
public static java.util.HashSet loggedKeys(java.nio.file.Path log, String skip) {
  java.util.HashSet keys = new java.util.HashSet();
  for (int n = 0; n <= 3; n++) {
    java.nio.file.Path f = n == 0 ? log : log.resolveSibling(log.getFileName().toString() + "." + n);
    try {
      if (java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) {
        String[] ls = new String(java.nio.file.Files.readAllBytes(f), "UTF-8").split("\n");
        for (int i = 0; i < ls.length; i++) {
          String[] c = ls[i].split("\t");
          if (c.length < 5 || c[4].trim().length() == 0) continue;
          if (skip != null && c[1].trim().equals(skip)) continue;
          keys.add(c[4].trim());
        }
      } else if (!java.nio.file.Files.notExists(f, new java.nio.file.LinkOption[0])) {
        return null;
      }
    } catch (Throwable x) { return null; }
  }
  return keys;
}""")
# printable ASCII only, max n characters (values quoted in log lines and in migrations.properties); a backslash becomes '?' too
# (0.5.3 review: Properties.load reads '\' as an escape - an admin value holding "\u" with fewer than 4 hex digits would make
# migrations.properties unreadable)
M(cfg, r"""
public static String plain(String v, int n) {
  if (v == null) return "";
  StringBuilder sb = new StringBuilder();
  for (int i = 0; i < v.length() && sb.length() < n; i++) {
    char c = v.charAt(i);
    if (c >= ' ' && c < 127 && c != '\\') sb.append(c); else sb.append('?');
  }
  return sb.toString();
}""")
# -1 = nothing to do this start (the step already ran, or a file can't be read: it runs again next start); else a bit mask over
# MIG_KEYS of the lines that are still EXACTLY the old default and that no admin ever set (config-changes.log never names them).
# MIG_NOTE holds the outcome text of every key.
M(cfg, r"""
public static int plan053() {
  try {
    if (FILE == null) return -1;
    java.nio.file.Path mk = FILE.resolveSibling("migrations.properties");
    java.util.Properties done = readProps(mk);
    if (done == null) { @PKG@.IslandStore.warn("could not read " + mk + " - the 0.5.3 default update waits for the next start"); return -1; }
    if (done.getProperty(MIG_STEP) != null) return -1;
    java.util.Properties p = readProps(FILE);
    if (p == null) { @PKG@.IslandStore.warn("could not read config.properties - the 0.5.3 default update waits for the next start"); return -1; }
    java.util.HashSet seen = loggedKeys(FILE.resolveSibling("config-changes.log"), MIG_BY);
    if (seen == null) { @PKG@.IslandStore.warn("could not read config-changes.log - the 0.5.3 default update waits for the next start (it must know which values an admin set)"); return -1; }
    int mask = 0;
    String[] note = new String[MIG_KEYS.length];
    for (int i = 0; i < MIG_KEYS.length; i++) {
      String raw = p.getProperty(MIG_KEYS[i]);
      String v = raw == null ? "" : raw.trim();
      if (v.length() == 0) note[i] = "no line - the new default " + MIG_NEW[i] + " applies";
      else if (v.equals(MIG_NEW[i])) note[i] = "already " + MIG_NEW[i];
      else if (!v.equals(MIG_OLD[i])) note[i] = "kept " + plain(v, 40) + " (an admin's value)";
      else if (seen.contains(MIG_KEYS[i])) note[i] = "kept " + MIG_OLD[i] + " (an admin set it - config-changes.log)";
      else { mask = mask | (1 << i); note[i] = "old default " + MIG_OLD[i]; }
    }
    MIG_NOTE = note;
    return mask;
  } catch (Throwable t) { @PKG@.IslandStore.warn("the 0.5.3 default update was skipped this start (it runs again next start): " + t); return -1; }
}""")
# tmp + fsync + atomic rename (plain replace fallback), 5 x 20 ms retries on a Windows sharing violation; false = not written
M(cfg, r"""
public static boolean writeText(java.nio.file.Path f, String text) {
  java.nio.file.Path tmp = f.resolveSibling(f.getFileName().toString() + ".tmp");
  boolean ok = false;
  try {
    java.nio.file.Files.createDirectories(f.getParent(), new java.nio.file.attribute.FileAttribute[0]);
    java.io.FileOutputStream out = new java.io.FileOutputStream(tmp.toFile());
    try {
      out.write(text.getBytes("ISO-8859-1"));
      out.flush();
      out.getFD().sync();
    } finally { out.close(); }
    for (int i = 0; i < 5 && !ok; i++) {
      try {
        try {
          java.nio.file.Files.move(tmp, f, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.REPLACE_EXISTING, java.nio.file.StandardCopyOption.ATOMIC_MOVE });
        } catch (java.nio.file.AtomicMoveNotSupportedException a) {
          java.nio.file.Files.move(tmp, f, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.REPLACE_EXISTING });
        }
        ok = true;
      } catch (java.nio.file.FileSystemException e) {
        try { Thread.sleep(20L); } catch (Throwable ie) { }
      }
    }
  } catch (Throwable t) { ok = false; }
  if (!ok) { try { java.nio.file.Files.deleteIfExists(tmp); } catch (Throwable t) { } }
  return ok;
}""")
# records the step in migrations.properties (other lines of the file are kept); false = not written (the step runs again next start)
M(cfg, r"""
public static boolean markDone(String summary) {
  try {
    if (FILE == null) return false;
    java.nio.file.Path mk = FILE.resolveSibling("migrations.properties");
    String old = "";
    if (java.nio.file.Files.exists(mk, new java.nio.file.LinkOption[0])) old = new String(java.nio.file.Files.readAllBytes(mk), "ISO-8859-1");
    else old = "# SkyyIslands one-time update steps. Each listed step has run and does not run again. Do not edit.\n";
    if (old.length() > 0 && !old.endsWith("\n")) old = old + "\n";
    String when = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss").format(java.time.LocalDateTime.now());
    return writeText(mk, old + MIG_STEP + "=" + when + " | " + plain(summary, 600) + "\n");
  } catch (Throwable t) { return false; }
}""")

# =====================================================================================================================
# 0.5.2 admin config kit''')

# ---------------------------------------------------------------- Server Setup rows: new defaults, KEEP 10
rep('''    ("defaults.visit.limit", "Default visitor limit", "visits", "int", "5", "1", "100", "step=1", "", "live",''',
    '''    ("defaults.visit.limit", "Default visitor limit", "visits", "int", "10", "1", "100", "step=1", "", "live",   # 0.5.3: was 5''')
rep('''    ("coop.adminsInvite", "Island admins may invite", "coop", "bool", "false", "", "", "", "", "live",
     "Off: only the owner invites. Only the owner kicks, promotes, disbands and resets either way.",''',
    '''    ("coop.adminsInvite", "Island admins may invite", "coop", "bool", "true", "", "", "", "", "live",   # 0.5.3: was false
     "On: island admins invite too. Off: only the owner. Only the owner kicks, promotes, disbands, resets.",''')
rep('''RELOAD="IslandHooks.reloadCfg", KEEP=20,''', '''RELOAD="IslandHooks.reloadCfg", KEEP=10,''')

# ---------------------------------------------------------------- IslandPerms: what Trusted may / may NOT do, from the island's grid
rep('''  return sb.length() == 0 ? "look around" : sb.toString();
}""")
''', '''  return sb.length() == 0 ? "look around" : sb.toString();
}""")
# 0.5.3: the things a Trusted player may NOT do on this island (flags whose minimum role is above trusted), "a, b or c"; "" = nothing.
# Default grid: "chests, furnaces, beds, crops or farm animals" (beds member-only: Skyy 2026-09-28)
M(perm, r"""
public static String trustedDeniedText(@PKG@.IslandSettings s) {
  java.util.ArrayList l = new java.util.ArrayList();
  for (int i = 0; i < s.perm.length && i < SHORT.length; i++) if (s.perm[i] > 1) l.add(SHORT[i]);
  StringBuilder sb = new StringBuilder();
  for (int i = 0; i < l.size(); i++) {
    if (i > 0) sb.append(i == l.size() - 1 ? " or " : ", ");
    sb.append((String) l.get(i));
  }
  return sb.toString();
}""")
# 0.5.3: true = a Trusted player may place and break blocks, use crafting benches and pick up items on this island (the builder set
# of the default grid), so "they may build" is true here
M(perm, r"""
public static boolean trustedBuilds(@PKG@.IslandSettings s) {
  if (s.perm.length <= PICKUP) return false;
  return s.perm[BUILD] <= 1 && s.perm[BREAK] <= 1 && s.perm[CRAFTING] <= 1 && s.perm[PICKUP] <= 1;
}""")
# 0.5.3 review: what a Trusted player may do on this island, for THEIR chat lines (trusted notice, /island visit, arrival welcome):
# "you may build (not chests, furnaces, beds, crops or farm animals)" on the default grid, "you may build" when nothing is closed to
# Trusted, else (the owner closed building to Trusted) the flags still open to Trusted, e.g. "you may: doors, seats, hostile mobs", or
# "you may only look around"
M(perm, r"""
public static String trustedYouText(@PKG@.IslandSettings s) {
  if (trustedBuilds(s)) {
    String nt = trustedDeniedText(s);
    return "you may build" + (nt.length() > 0 ? " (not " + nt + ")" : "");
  }
  StringBuilder sb = new StringBuilder();
  for (int i = 0; i < s.perm.length && i < SHORT.length; i++) {
    if (s.perm[i] > 1) continue;
    if (sb.length() > 0) sb.append(", ");
    sb.append(SHORT[i]);
  }
  return sb.length() == 0 ? "you may only look around" : "you may: " + sb.toString();
}""")
''')

# ---------------------------------------------------------------- texts: invite refusal, trust answer, Members tab hint
rep('''  if (!(rank == 4 || (rank == 3 && @PKG@.IslandCfg.ADMINS_INVITE))) return "-Only the island owner can invite co-op members (you are a co-op "''',
    '''  if (!(rank == 4 || (rank == 3 && @PKG@.IslandCfg.ADMINS_INVITE))) return "-" + (@PKG@.IslandCfg.ADMINS_INVITE ? "Only the island owner and island admins can" : "Only the island owner can") + " invite co-op members (you are a co-op "''')
rep('''  return "+" + tn + " is now Trusted: they may build on the island (not chests, furnaces, crops, beds or animals)." + (r == 1''',
    '''  String nt = @PKG@.IslandPerms.trustedDeniedText(s);   // 0.5.3: from the island's grid (default: chests, furnaces, beds, crops, animals)
  String td = @PKG@.IslandPerms.trustedBuilds(s) ? "they may build on the island" : "the Permissions tab (/island menu) shows what they may do";
  return "+" + tn + " is now Trusted: " + td + (nt.length() > 0 ? " (not " + nt + ")" : "") + "." + (r == 1''')
rep('''    lbl(b, P, 0, 26, 14, false, "#9fb8d0", false, "Nobody yet. Trusted players may place and break blocks, use crafting benches and pick up items - not chests, furnaces, crops, beds or animals.");''',
    '''    // 0.5.3: text only (same label, same style), from the island's grid; a heavily customised grid points to the Permissions tab
    String nt = @PKG@.IslandPerms.trustedDeniedText(s);
    String th = "Nobody yet. Trusted players may place and break blocks, use crafting benches and pick up items" + (nt.length() > 0 ? " - not " + nt : "") + ".";
    if (th.length() > 160) th = "Nobody yet. Trusted players may place and break blocks, use crafting benches and pick up items (the Permissions tab lists the rest).";
    if (!@PKG@.IslandPerms.trustedBuilds(s)) th = "Nobody yet. The Permissions tab shows what Trusted players may do on this island.";
    lbl(b, P, 0, 26, 14, false, "#9fb8d0", false, th);''')

# ---------------------------------------------------------------- 0.5.3 review fixes
# (1) a co-op invite is re-checked at accept (and on the Overview tab's invite row, which shows acceptProblem's reason): the player who
# sent it must still be allowed to invite to that island NOW - the owner (on any profile: the island stays theirs), or an island admin
# ON THAT PROFILE while coop.adminsInvite is on. A demoted / kicked / banned admin, an admin who switched profile, or coop.adminsInvite
# turned off within invite.seconds -> the invite can't be accepted. inv = { island key, inviter UUID, expiry, inviter name, owner name }.
rep('''  if (u.equals(@PKG@.IslandStore.ownerUuid(ok))) return "that island belongs to one of your own profiles";
''', '''  if (u.equals(@PKG@.IslandStore.ownerUuid(ok))) return "that island belongs to one of your own profiles";
  java.util.UUID iu = (java.util.UUID) inv[1];   // 0.5.3 review: the inviter must still be allowed to invite (same rule as invite())
  int ir = iu.equals(@PKG@.IslandStore.ownerUuid(ok)) ? 4 : @PKG@.IslandPerms.rank(ok, iu, s);
  if (!(ir == 4 || (ir == 3 && @PKG@.IslandCfg.ADMINS_INVITE))) return "that invite is no longer valid - the player who sent it may not invite any more";
''')
# (2) an island admin's co-op invite is told to the island owner (if online, on any profile; names the island's profile when the owner is
# on another one - profileNameOf: the profile's name, else "profile N")
rep('''  @PKG@.IslandStore.INVITES.put(tu, new Object[] { hk, u, Long.valueOf(exp), pr.getUsername(), on });
''', '''  @PKG@.IslandStore.INVITES.put(tu, new Object[] { hk, u, Long.valueOf(exp), pr.getUsername(), on });
  if (!hk.equals(k)) {   // 0.5.3 review: an island admin invited (rank 4 = hk is the inviter's own key) - tell the owner if online
    java.util.UUID ou = @PKG@.IslandStore.ownerUuid(hk);
    @PR@ op = @PKG@.IslandStore.online(ou);
    if (op != null) @PKG@.IslandStore.say(op, "[Island] " + pr.getUsername() + " invited " + tn + " to your island" + (hk.equals(@PKG@.IslandStore.pkey(ou)) ? "" : " on another of your profiles (" + @PKG@.IslandStore.profileNameOf(hk) + ")") + " as a co-op member - they have " + @PKG@.IslandCfg.INVITE_SECONDS + " s to accept.", "#ffe08a");
  }
''')
# (2) Members tab hint: "your island" only for the owner (an island admin invites to the owner's island)
rep('''(canInv ? "Invite to co-op = they join your island (their /island comes here).   " : "")''',
    '''(canInv ? "Invite to co-op = they join " + (rank == 4 ? "your" : "the") + " island (their /island comes here).   " : "")''')
# (2) the Trusted player's own lines follow the island's grid like the other 0.5.3 trusted texts (IslandPerms.trustedYouText)
rep('''(rank == 1 ? " - you are Trusted here: you may build." : ''',
    '''(rank == 1 ? " - you are Trusted here: " + @PKG@.IslandPerms.trustedYouText(s) + "." : ''')
rep('''"[Island] Welcome to " + on + "'s island - you are Trusted here (you may build).", "#8fc8ff");''',
    '''"[Island] Welcome to " + on + "'s island - you are Trusted here: " + @PKG@.IslandPerms.trustedYouText(s) + ".", "#8fc8ff");''')
rep('''" trusted you on " + on + "'s island: you may build there (/island visit " + on + "). Your own /island does not change.", "#8fc8ff");''',
    '''" trusted you on " + on + "'s island (/island visit " + on + ") - there " + @PKG@.IslandPerms.trustedYouText(s) + ". Your own /island does not change.", "#8fc8ff");''')

# ---------------------------------------------------------------- IslandHooks.apply053 (after the kit exists: CfgFn / CfgPub)
rep('''  return R("ok", null, "Reading your hotbar - the new starter kit is shown in the chat in a moment.");
}""")
''', '''  return R("ok", null, "Reading your hotbar - the new starter kit is shown in the chat in a moment.");
}""")
# 0.5.3: the untouched old defaults IslandCfg.plan053 found are set through the kit's own path (validated, running value, History copy,
# config-changes.log 'ok' line with Undo, the kit's INFO line), by "SkyyIslands 0.5.3 update" via console, then written NOW
# (CfgPub.flush: the file line in place + RELOAD). The step is recorded (migrations.properties) only when every planned key applied and
# config.properties on disk holds the new value; else it runs again at the next start. Never throws. Island files: never touched.
M(hooks, r"""
public static String apply053(int mask) {
  if (mask < 0) return null;
  String[] keys = @PKG@.IslandCfg.MIG_KEYS;
  String[] note = @PKG@.IslandCfg.MIG_NOTE;
  boolean all = true;
  int applied = 0;
  String[] res = new String[keys.length];
  for (int i = 0; i < keys.length; i++) {
    res[i] = (note == null || i >= note.length || note[i] == null) ? "-" : note[i];
    if ((mask & (1 << i)) == 0) continue;
    Object[] r = null;
    if (@PKG@.CfgPub.STARTED) {
      try { r = @PKG@.CfgFn.set(keys[i], @PKG@.IslandCfg.MIG_NEW[i], null, @PKG@.IslandCfg.MIG_BY, "yes", "console"); } catch (Throwable t) { r = null; }
    }
    String st = (r == null || r.length < 1 || r[0] == null) ? "error" : String.valueOf(r[0]);
    if (st.equals("ok") || st.equals("restart")) {
      applied = applied | (1 << i);
      res[i] = @PKG@.IslandCfg.MIG_OLD[i] + " -> " + @PKG@.IslandCfg.MIG_NEW[i] + " (was the untouched old default)";
      @PKG@.IslandStore.info("config.properties: " + keys[i] + " was still the untouched old default " + @PKG@.IslandCfg.MIG_OLD[i] + " - now " + @PKG@.IslandCfg.MIG_NEW[i] + ": " + @PKG@.IslandCfg.MIG_WHY[i] + ". Server Setup -> Islands -> Changes lists it (Undo there goes back).");
    } else {
      all = false;
      String why = (r != null && r.length > 2 && r[2] != null) ? String.valueOf(r[2]) : (@PKG@.CfgPub.STARTED ? "see the server log" : "the config kit did not start");
      res[i] = "NOT changed yet (" + @PKG@.IslandCfg.plain(why, 120) + ") - tried again at the next start";
      @PKG@.IslandStore.warn("config.properties: " + keys[i] + " is still the old default " + @PKG@.IslandCfg.MIG_OLD[i] + " but could not be set to " + @PKG@.IslandCfg.MIG_NEW[i] + " (" + why + ") - tried again at the next start.");
    }
  }
  if (applied != 0) {
    try { @PKG@.CfgPub.flush(); } catch (Throwable t) { @PKG@.IslandStore.warn("0.5.3 default update: writing config.properties failed: " + t); }
    java.util.Properties p = @PKG@.IslandCfg.readProps(@PKG@.IslandCfg.FILE);
    for (int i = 0; i < keys.length; i++) {
      if ((applied & (1 << i)) == 0) continue;
      String v = p == null ? null : p.getProperty(keys[i]);
      if (v != null && v.trim().equals(@PKG@.IslandCfg.MIG_NEW[i])) continue;
      all = false;
      res[i] = res[i] + " - in use now, but config.properties does not show it yet (the kit retries the write every 30 s; this step looks again at the next start)";
      @PKG@.IslandStore.warn("config.properties: " + keys[i] + " is " + @PKG@.IslandCfg.MIG_NEW[i] + " in the running server, but the file does not show it yet - the config kit retries the write; the 0.5.3 default update looks again at the next start.");
    }
  }
  StringBuilder sum = new StringBuilder();
  for (int i = 0; i < keys.length; i++) {
    if (i > 0) sum.append(" | ");
    sum.append(keys[i]).append(": ").append(res[i]);
  }
  String out = sum.toString();
  if (all && !@PKG@.IslandCfg.markDone(out)) @PKG@.IslandStore.warn("could not write migrations.properties - the 0.5.3 default update looks again at the next start (it only ever changes values that are still the untouched old defaults).");
  @PKG@.IslandStore.info("0.5.3 default update (Skyy's 2026-09-25 island locks)" + (all ? "" : " - NOT finished, runs again at the next start") + ": " + out);
  return out;
}""")
''')

# ---------------------------------------------------------------- setup(): plan before the kit starts, apply right after
rep('''  // 0.5.2: admin config kit - config:def:SkyyIslands + config:fn:SkyyIslands, at the END of setup(), after IslandCfg.load (never throws)
  @PKG@.CfgPub.start(getDataDirectory().getParent(), getLogger());
}""".replace("%%ANIMALS%%", ANIMALS_CSV))''', '''  // 0.5.3: which config lines still hold the untouched old default of Skyy's 2026-09-25 island locks - read BEFORE the kit starts
  int mig = @PKG@.IslandCfg.plan053();
  // 0.5.2: admin config kit - config:def:SkyyIslands + config:fn:SkyyIslands, at the END of setup(), after IslandCfg.load (never throws)
  @PKG@.CfgPub.start(getDataDirectory().getParent(), getLogger());
  // 0.5.3: ... and set them through the kit right after it started (logged, History copy, Undo); once per world (migrations.properties)
  try { @PKG@.IslandHooks.apply053(mig); } catch (Throwable t) { @PKG@.IslandStore.warn("0.5.3 default update failed (runs again next start): " + t); }
}""".replace("%%ANIMALS%%", ANIMALS_CSV))''')

# ---------------------------------------------------------------- checks on the result
assert s.count('VERSION = "0.5.3"') == 1 and 'VERSION = "0.5.2"' not in s
assert s.count("registerSystem(") == REG0 and s.count("registerCommand(") == CMD0 and s.count("\nsub(") == SUB0   # nothing new
assert sorted(set(re.findall(r"#(SkyyIs[A-Za-z0-9]*)", s))) == IDS0, "a UI element id changed (0.5.3 is text only)"
# the 0.5.1 security fix stays: /island reload = admin node, no inherited Adventurer group
_rl = body("public IslandReloadCmd() {")
assert 'requirePermission("skyyislands.admin");' in _rl and "setPermissionGroups(new String[0]);" in _rl
# the locked grid (spec 3.2 + Skyy 2026-09-25 + Skyy 2026-09-28 beds): visitors doors / seats (+ mobs); chests, crops, furnaces, BEDS,
# animals member; benches trusted - exactly 0.5.2's default column
_fl = flag_defaults()
assert _fl == {"build": "trusted", "break": "trusted", "containers": "member", "doors": "visitor", "crafting": "trusted", "processing": "member",
               "beds": "member", "seats": "visitor", "harvest": "member", "animals": "member", "mobs": "visitor", "pickup": "trusted",
               "drop": "trusted", "other": "trusted"}, _fl
assert _fl == FL0, "the default permission grid must stay 0.5.2's (beds member: Skyy 2026-09-28)"
# the one-time step plans only the two other keys (beds is not migrated, not named in the marker, no 'visitor' target)
assert s.count('public static final String[] MIG_KEYS = new String[] { "coop.adminsInvite", "defaults.visit.limit" };') == 1
assert s.count('public static final String[] MIG_OLD = new String[] { "false", "5" };') == 1
assert s.count('public static final String[] MIG_NEW = new String[] { "true", "10" };') == 1
_mw = s[s.index("public static final String[] MIG_WHY"):s.index("public static final String MIG_STEP")]
assert len(re.findall(r'"[^"]+"', _mw)) == 2 and _mw.count(" };") == 1 and "bed" not in _mw.lower(), _mw
assert s.count('"defaults.perm.beds"') == 0 and "defaults.perm.beds=member" not in s
# no text (Java string, config text, row help, comment) says visitors may use beds or that beds are visitor level
for _bad in ("visitors may use beds", "may use doors, seats, and beds", "beds are visitor", "doors, beds, seats", "doors, seats, beds",
             "beds flag default visitor", '"Sleeping, setting your respawn", "visitor"'):
    assert _bad not in s, _bad
# what the grid-built texts say on the DEFAULT grid (same loops as IslandPerms.visitorAllowedText / trustedDeniedText, SHORT = FLAGS order)
_sh = re.findall(r'"([^"]+)"', s[s.index("public static final String[] SHORT = new String[] {"):s.index("};", s.index("public static final String[] SHORT"))])
_ids = [m.group(1) for m in re.finditer(r'\("(\w+)", "[^"]*", "[^"]*", "(?:visitor|trusted|member|admin|owner)"\)', s[s.index("FLAGS = ["):s.index("RANKS = [")])]
assert len(_sh) == len(_ids) == 14 and _sh[_ids.index("beds")] == "beds", (_sh, _ids)
_rk = ["visitor", "trusted", "member", "admin", "owner"]
_vis = ", ".join(_sh[i] for i, f in enumerate(_ids) if _rk.index(_fl[f]) == 0)
_den = [_sh[i] for i, f in enumerate(_ids) if _rk.index(_fl[f]) > 1]
_den = ", ".join(_den[:-1]) + " or " + _den[-1]
assert _vis == "doors, seats, hostile mobs", _vis   # "[Island] Visiting X's island - PvP off - visitors may: doors, seats, hostile mobs."
assert _den == "chests, furnaces, beds, crops or farm animals", _den
assert len("Nobody yet. Trusted players may place and break blocks, use crafting benches and pick up items - not " + _den + ".") <= 160
# already-live locks, unchanged: co-op 5, reset 24 h with 3 confirm runs, visit limit capped at visit.limitMax 10; the new defaults
for _x in ('"coop.maxPlayers=5",', '"reset.cooldownHours=24",', '"visit.limitMax=10",', '"public static volatile int COOP_MAX = 5;"',
           '"public static volatile long RESET_HOURS = 24L;"', '"public static volatile int LIMIT_MAX = 10;"', '"defaults.visit.limit=10",',
           '"coop.adminsInvite=true",', "if (lim > @PKG@.IslandCfg.LIMIT_MAX) lim = @PKG@.IslandCfg.LIMIT_MAX;",
           '"public static volatile int DEF_LIMIT = 10;"', '"public static volatile boolean ADMINS_INVITE = true;"',
           'lng(p, "defaults.visit.limit", 10L, 1L, 100L)', '("defaults.visit.limit", "Default visitor limit", "visits", "int", "10",',
           '("coop.adminsInvite", "Island admins may invite", "coop", "bool", "true",'):
    assert s.count(_x) == 1, _x
assert "beds or animals" not in s and "crops, beds" not in s
# /island reset: 3 runs within reset.confirmSeconds; /island visit goes to the target's HOME island (so a co-op member can't visit
# their own dormant island); biomes (slice B) are not built, so there is no biome price anywhere (the "free" lock holds)
assert "if (step < 3) {" in body("public static String resetCmd(@ST@ store, @REF@ ref, @PR@ pr, @WLD@ world) {")
assert "String tk = @PKG@.IslandStore.homeKey(tu);" in body("public static void visit(@ST@ store, @REF@ ref, @PR@ pr, @WLD@ world, @PR@ target) {")
assert "biome.cost" not in s and "BIOME_COST" not in s
# the setter paths are still the 0.5.2 ones (one clicked flag / the limit / remove every perm line): nothing above touched them
assert body("public static String clickPerm(@PR@ pr, int f, int r) {") == _ck and body("public static String resetPerms(@PR@ pr) {") == _rs
assert body("public static String changeLimit(@PR@ pr, int d) {") == _cl
# the 0.5.3 step never reads or writes an island file (IslandStore file / cache paths)
for _m in ("public static int plan053()", "public static String apply053(int mask)", "public static boolean markDone(",
           "public static java.util.HashSet loggedKeys("):
    _b = body(_m)
    for _bad in ("IslandStore.DIR", "setProps", "write0", "read0", "IslandStore.settings(", "islands"):
        assert _bad not in _b, (_m, _bad)
# setup: plan before CfgPub.start, apply right after it, as the last statement
_su = body("public void setup() {", '}""".replace(')
assert _su.index("@PKG@.IslandCfg.load(") < _su.index("@PKG@.IslandStore.loadIslandWorlds();") < _su.index("int mig = @PKG@.IslandCfg.plan053();") \
    < _su.index("@PKG@.CfgPub.start(") < _su.index("@PKG@.IslandHooks.apply053(mig);")
assert _su.rstrip().endswith('try { @PKG@.IslandHooks.apply053(mig); } catch (Throwable t) { @PKG@.IslandStore.warn("0.5.3 default update failed (runs again next start): " + t); }')
# javassist order: IslandCfg's plan helpers before plan053; apply053 compiled after the kit's emit (CfgFn / CfgPub exist) and before
# the plugin; the IslandPerms text helpers before their callers
assert s.index("public static java.util.Properties readProps(") < s.index("public static java.util.HashSet loggedKeys(") \
    < s.index("public static String plain(String v, int n)") < s.index("public static int plan053()") \
    < s.index("public static boolean writeText(") < s.index("public static boolean markDone(") < s.index("kit = CFG.emit(") \
    < s.index("public static String apply053(int mask)") < s.index("public void setup() {")
assert s.index("public static String trustedDeniedText(") < s.index("public static boolean trustedBuilds(") \
    < s.index("public static String trust(@PR@ pr, @PR@ target)") < s.index("public void buildMembers(")
assert s.index("F(perm, \"public static final int %s = %d;\"") < s.index("public static boolean trustedBuilds(")
# review fixes: the Trusted player's own lines come from the grid (helper compiled before /island visit, the arrival task and trust)
assert s.index("public static boolean trustedBuilds(") < s.index("public static String trustedYouText(") \
    < s.index("public static void visit(@ST@ store, @REF@ ref, @PR@ pr, @WLD@ world, @PR@ target) {") \
    < s.index("public ArrivalTask(") < s.index("public static String trust(@PR@ pr, @PR@ target)")
assert s.count("@PKG@.IslandPerms.trustedYouText(s)") == 3 and "(you may build)" not in s and "you may build there" not in s \
    and "you are Trusted here: you may build." not in s
# ... the invite is re-checked at accept with invite()'s own rule, before the other accept checks; the owner hears of an admin's invite
_ap = body("public static String acceptProblem(@PR@ pr) {")
assert _ap.index("return \"that island belongs to one of your own profiles\";") < _ap.index("int ir = ") < _ap.index("String hk = @PKG@.IslandStore.homeKey(u);")
assert "if (!(ir == 4 || (ir == 3 && @PKG@.IslandCfg.ADMINS_INVITE))) return" in _ap
assert "if (!(rank == 4 || (rank == 3 && @PKG@.IslandCfg.ADMINS_INVITE))) return" in body("public static String invite(@PR@ pr, @PR@ target) {")
assert s.index("public static int rank(String owner, java.util.UUID u, @PKG@.IslandSettings s) {") < s.index("public static String acceptProblem(@PR@ pr) {")
assert body("public static String invite(@PR@ pr, @PR@ target) {").count("to your island") == 1
assert "they join your island" not in s and "c != '\\\\') sb.append(c); else sb.append('?');" in body("public static String plain(String v, int n) {")
assert "KEEP=10," in s and "KEEP=20" not in s
assert "B.deploy(" not in s and "enable_in_world(" not in s
for ident in re.findall(r"#(Skyy[A-Za-z0-9_]*)", s):
    assert "_" not in ident, "underscore in a UI id: " + ident

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
