"""Derive SkyyIslands/build_skyyislands_0.5.5.py from the LIVE 0.5.4 (edit THIS file, then regenerate: python tools/islands_0_5_5_patch.py,
then python SkyyIslands/build_skyyislands_0.5.5.py; never --deploy - tools/deploy_set.py deploys the whole set).
Base = build_skyyislands_0.5.4.py (the tools/deploy_set.py SET pin, generated by tools/islands_0_5_4_patch.py from 0.5.3; the chain goes
back to 0.5.1 = the security hotfix; NEVER 0.5).

0.5.5 = DORMANT ISLANDS (Skyy 2026-10-01, OPEN-QUESTIONS LOCKED: "yes, a player can always leave an island and make their own. so only the
owner of an island can delete it."). SkyyProfiles 0.1.5 lets a player delete a profile (6 h undo, then archived, never wiped); 0.5.4 let the
co-op members of that profile's island keep full access. Read through the SkyyProfiles bridge key profile:fn:state (Function apply(String
storage key) -> "active" | "inactive" | "pending" | "archived" | null; tools/PROFILES-CONTRACT.md section 6):
  (1) owner's key "pending" (deleted, undo window) = the island is CLOSED: every entry path refuses co-op members, trusted players and
      visitors (IslandCmd.go - /island, /island home|go, the page's Go to island, SkyyProfiles' switch teleport (/island), /island visit|warp
      and the old --action visit flag form; IslandCmd.visit refuses before its visiting line; island:perm:fn "enter" = FALSE), anyone already
      on it is sent off on arrival (ArrivalTask: /tp, /tpa, warps, respawns, other mods) and by the 5 s island sweep (SweepTask) - a co-op
      member of it who has an island of their own on that profile goes there (the kick / disband destination), everyone else to the hub
      (the visitor / unavailable destination; a member without an island too) - with the closed line. Server admins (skyyislands.admin)
      still enter (inspection note on arrival). Join: the closed line for a member at their first ready (JoinNote, +3 s).
  (2) restore (state back to inactive / active) = open again: nothing was changed meanwhile (membership, settings, files).
  (3) owner's key "archived" = still closed, and the co-op members are RELEASED: the island file's members / admins / coopSince lines and
      the MEMBER_OF index (both sides Islands stores); told once (online now, else at their next join via Skyy_SkyyIslands/notices.properties).
      The island world and every other island line stay; an admin archive restore gives the owner the island back WITHOUT members.
  (4) a MEMBER's own key "archived" = removed from the host island (frees the slot), the owner told once (now or next join). A member's
      "pending" key changes nothing (that profile simply is not there).
  (5) no profile:fn:state (no SkyyProfiles, or 0.1.4) or a null / unknown answer = open = 0.5.4.
  (6) the island menu opens with the closed line in its result line (IslandMenuCmd sets the page's info - the page code is 0.5.4's: page
      id unchanged, the page gate passes without a new page check); /island info adds the closed line; co-op invites to a closed island
      are refused (invite + accept + the page's pending-invite row via acceptProblem); trust / untrust / ban / unban / every island
      setting are refused while closed (the island comes back exactly as it was). Nothing ever deletes island data.
Cost: one profile:fn:state call per entry attempt, per arrival, per occupied island world per 5 s sweep; the archive scan (SeenTick, every
30 s, scheduler thread, AFTER that tick's sweeps are queued) asks only about islands that list members (+ one call per member) and writes
only when it releases someone.
Review fixes (2026-10-01, the 0.5.5 review's low findings): SeenTick queues the island sweeps BEFORE the archive scan (a slow
profile:fn:state there no longer delays the 5 s send-offs); IslandCmd.go skips the closed check only for the player's own CURRENT
profile key (the caller's own flag is not trusted); a deleted profile Islands can't name reads "profile #2" (the number /profiles list
shows); JoinNote waits 6 s (after the login hub teleport); an offline player's one-time line is saved BEFORE the island file write
that releases them (a stop between the two can't release anyone silently; dropped again when the write fails, not re-saved while a
failed release is retried); an unreadable notices.properties is read again after a minute (notices kept in memory meanwhile are merged
in, not lost at the next restart); a release whose island file write failed is really retried every 30 s (write0 drops the island
from the cache on a failed write - archiveScan reads it back).
Checked by SkyyIslands/test_skyyislands_0.5.5.py (re-run it, do not trust this text).
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyIslands", "build_skyyislands_0.5.4.py")
dst = os.path.join(ROOT, "SkyyIslands", "build_skyyislands_0.5.5.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.5.4"' in s, "build_skyyislands_0.5.4.py is not the live 0.5.4"
assert "profile:fn:state" not in s and "JoinNote" not in s, "0.5.4 already reads profile:fn:state"
REG0 = s.count("registerCommand(")
SYS0 = s.count("registerSystem(")
# the 0.5.1 security fix and the 0.5.3 locks this round must not touch (asserted again on the result)
SECURITY = ['  requirePermission("skyyislands.admin");\n  setPermissionGroups(new String[0]);   // 0.5.1: do NOT inherit /island\'s '
            'hytale:Adventurer (it handed every player skyyislands.admin)']
LOCKS = ['    ("beds", "Beds", "Sleeping, setting your respawn", "member"),',
         '"public static volatile int COOP_MAX = 5;", "public static volatile boolean ADMINS_INVITE = true;"',
         'DEF_LIMIT = (int) lng(p, "defaults.visit.limit", 10L, 1L, 100L);']
for x in SECURITY + LOCKS:
    assert s.count(x) == 1, "0.5.4 lost a line this round keeps: " + x[:80]


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def block(a, b):
    """the text from anchor a (included) to anchor b (excluded) of the CURRENT source (for unchanged-block asserts)"""
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


# the island menu page (every IslandMenuPage method, the kit look block and the page gate's page id) stays 0.5.4's byte for byte: the
# page id does not change, so the 0.5.4 page check still covers it (only the gate's harness / patch names move to 0.5.5)
PAGE_KEEP = block("# IslandMenuPage (/island menu): inline only", 'IS_PAGE_CHECKED = "144f342c8b5a"')
PAGE_KEEP2 = block("# ---- end page gate", "# /island subcommands (constructor + execute BEFORE")
GUARDS_KEEP = block("# Guards (ONE registerSystem per class).", "# IslandMenuPage (/island menu): inline only")

# ================================================================================================ docstring
HEAD_OLD = ('"""SkyyIslands 0.5.4 - build script (javassist via jpype). GENERATED by tools/islands_0_5_4_patch.py from the LIVE 0.5.3 - edit the\n'
            'patch, then regenerate; never edit this file by hand. Never run with --deploy (tools/deploy_set.py deploys the coordinated set).\n\n')
assert s.startswith(HEAD_OLD), "0.5.4 docstring head changed: " + s[:200]
HEAD_NEW = r'''"""SkyyIslands 0.5.5 - build script (javassist via jpype). GENERATED by tools/islands_0_5_5_patch.py from the LIVE 0.5.4 - edit the
patch, then regenerate; never edit this file by hand. Never run with --deploy (tools/deploy_set.py deploys the coordinated set).

0.5.5 (2026-10-01, DORMANT ISLANDS - Skyy, OPEN-QUESTIONS LOCKED 2026-10-01: "yes, a player can always leave an island and make their own.
so only the owner of an island can delete it."): SkyyProfiles 0.1.5 deletes profiles (6 h undo, then archived, never wiped). Islands now
reads profile:fn:state (Function apply(String storage key) -> "active" | "inactive" | "pending" | "archived" | null, tools/PROFILES-
CONTRACT.md section 6) for the island OWNER's key (IslandStore.closedState: 1 = pending, 2 = archived, 0 = open):
  - CLOSED while the owner's profile is pending or archived: co-op members, trusted players and visitors can't enter - every entry path:
    IslandCmd.go (/island, /island home|go, the menu's Go to island, the SkyyProfiles switch teleport = /island, /island visit|warp, the old
    --action visit|home flag form) refuses with the closed line before any teleport; IslandCmd.visit refuses before its visiting line;
    island:perm:fn "enter" (and "settings") = FALSE. Anyone already there is sent off on arrival (ArrivalTask, every world switch:
    /tp, /tpa, warps, respawns, other mods) and by the 5 s island sweep (SweepTask): the closed line, then a co-op member of it who has an
    island of their own on that profile goes there (go(own) = the kick / disband destination), everyone else - a member without an
    island too - to the hub (SendHubTask = the visitor / unavailable destination); one send per player per 4 s. Server admins
    (skyyislands.admin) still enter and stay (a "you may stay to inspect it" line on arrival). The closed line (pending): "<owner>'s
    island is closed - its profile was deleted. It comes back if they restore it within the undo window; otherwise you can make your
    own island." (+ "(/island leave ends your co-op membership now.)" for members; the owner on another profile hears that it is their
    deleted profile and to restore it; archived: "... was deleted for good.").
  - Join: a member whose co-op island is closed gets the closed line at their first ready of the session (JoinNote, scheduler, +6 s,
    after the login routing line and its hub teleport), plus any one-time notices saved while they were offline.
  - RESTORE (state back to inactive / active): open again with membership, settings and files exactly as before - nothing on a closed
    island can change meanwhile: co-op invites to it are refused (invite, accept and the menu's invite row = acceptProblem), and so are
    trust / untrust / ban / unban and every island setting (IslandCoop.editRefusal: visits, limit, ping, PvP, spawning, permissions,
    lock). Leaving always works (Skyy: "a player can always leave an island").
  - ARCHIVED owner: the co-op members are RELEASED - the island file's members / admins / coopSince.* lines (every other line kept) and
    the MEMBER_OF index - so /island makes (or brings back) their own island; each is told once: at once when online (any profile), else
    at their next join (Skyy_SkyyIslands/notices.properties, player UUID = lines; read once, written only when a notice is added,
    dropped or shown; an unreadable file is left untouched, notices are kept in memory and the file is read again after a minute and
    merged). An offline player's line is saved BEFORE the island file write that releases them (a server stop between the two can't
    release anyone silently) and dropped again if that write fails. The island world and file stay; an admin archive restore
    (/profileadmin archive restore) gives the owner the island back WITHOUT members - they re-invite.
  - A MEMBER deleting their own profile never touches the island: pending = that profile is simply not there; ARCHIVED = removed from the
    host island's co-op (frees the slot, same lines as /island kick), the owner told once (now or next join; saved first when offline).
  - The archive check: IslandStore.archiveScan, SeenTick every 30 s on the scheduler thread, AFTER that tick's island sweeps are queued
    (a slow profile:fn:state never delays the 5 s send-offs) - only islands that list members are asked about (one profile:fn:state call
    each + one per member), and it writes only when it releases someone (a restart never rewrites a file). A release whose island file
    could not be written is retried every 30 s (the island is read back into the cache first).
  - IslandCmd.go skips the closed check only for the player's own CURRENT profile key (it does not trust its caller's own flag). A
    deleted profile Islands can't name (SkyyProfiles lists live profiles only) reads "profile #2" - the number /profiles list shows.
  - Without profile:fn:state (no SkyyProfiles, or SkyyProfiles 0.1.4) or for a null / unknown answer every island is open: 0.5.4's
    behaviour (archiveScan returns at once; no chat line, no file write).
  - The menu page is 0.5.4's byte for byte (IslandMenuPage, the page id, the page gate): /island menu opens it with the closed line in its
    result line (IslandMenuCmd sets the page's info field), so no page text or layout changed.
  @@CHECKED@@

'''
rep(HEAD_OLD, HEAD_NEW)

rep('VERSION = "0.5.4"', 'VERSION = "0.5.5"')
rep("Run:   python build_skyyislands_0.5.4.py          -> SkyyIslands/SkyyIslands-0.5.4.jar  (never --deploy: tools/deploy_set.py deploys)",
    "Run:   python build_skyyislands_0.5.5.py          -> SkyyIslands/SkyyIslands-0.5.5.jar  (never --deploy: tools/deploy_set.py deploys)")

# ================================================================================================ the new class
rep('kht  = K("KitHotbarTask")    # 0.5.2: "Starter kit from my hotbar" action (world thread)\n',
    'kht  = K("KitHotbarTask")    # 0.5.2: "Starter kit from my hotbar" action (world thread)\n'
    'jnt  = K("JoinNote")         # 0.5.5: first ready of the session: one-time island notices + the closed line (scheduler thread)\n')
rep("rdy, seen, hooks, hht, kht]", "rdy, seen, hooks, hht, kht, jnt]")

# ================================================================================================ IslandStore: state, texts, notices, release
STORE = r'''
# =====================================================================================================================
# 0.5.5 DORMANT ISLANDS (Skyy 2026-10-01: "a player can always leave an island and make their own. so only the owner of an island can
# delete it"). SkyyProfiles 0.1.5+ profile:fn:state (Function apply(String storage key) -> "active" | "inactive" | "pending" | "archived" |
# null; tools/PROFILES-CONTRACT.md section 6; a cache hit there is no I/O, never throws, never calls out). The island of an OWNER key that
# is pending (deleted, undo window) or archived is closed. No profile:fn:state (no SkyyProfiles / 0.1.4) or null = open = 0.5.4.
# =====================================================================================================================
for f in ("public static final Object NOTE_LOCK = new Object();",
          "public static java.util.Properties NOTES;",
          "public static boolean NOTES_RO;",
          "public static long NOTES_AT;",
          "public static final java.util.concurrent.ConcurrentHashMap REL_FAIL = new java.util.concurrent.ConcurrentHashMap();"):
    F(st_, f)
M(st_, r"""
public static String profState(String key) {
  if (key == null) return null;
  try {
    Object f = bridge().get("profile:fn:state");
    if (f instanceof java.util.function.Function) {
      Object r = ((java.util.function.Function) f).apply(key);
      if (r instanceof String) return (String) r;
    }
  } catch (Throwable t) { }
  return null;
}""")
# 1 = the owner's profile is deleted and inside its undo window, 2 = archived, 0 = open (active, inactive, unknown, no SkyyProfiles)
M(st_, r"""
public static int closedState(String ownerKey) {
  String st = profState(ownerKey);
  if ("pending".equals(st)) return 1;
  if ("archived".equals(st)) return 2;
  return 0;
}""")
# "profile Pear" for a storage key SkyyProfiles lists (live profiles), else "profile #2": a deleted (pending / archived) profile is not in
# profile:list, so its name is unknown here - the number is what /profiles list shows in front of it (review: not "profile 2")
M(st_, r"""
public static String profWord(String key) {
  String n = profileNameOf(key);
  if (!n.startsWith("profile ")) return "profile " + n;
  String id = n.substring(8);
  if (id.length() == 0) return n;
  for (int i = 0; i < id.length(); i++) if (id.charAt(i) < '0' || id.charAt(i) > '9') return n;
  return "profile #" + id;
}""")
# the refusal / sent-off line ("-" = refused) for player u and a closed island (cs = closedState)
M(st_, r"""
public static String closedText(String ownerKey, @PKG@.IslandSettings s, int cs, java.util.UUID u) {
  if (u != null && u.equals(ownerUuid(ownerKey))) {
    if (cs == 2) return "-This island belongs to your archived " + profWord(ownerKey) + " - it stays closed unless a server admin restores that profile.";
    return "-This island belongs to your deleted " + profWord(ownerKey) + " - it is closed until you restore that profile (/profiles) within its undo window.";
  }
  String on = ownerDisplay(ownerKey, s);
  boolean member = u != null && s != null && contains(s.members, pkey(u));
  if (cs == 2) return "-" + on + "'s island is closed - its profile was deleted for good." + (member ? " Your co-op membership ends in a moment; then /island makes your own island." : "");
  return "-" + on + "'s island is closed - its profile was deleted. It comes back if they restore it within the undo window; otherwise you can make your own island." + (member ? " (/island leave ends your co-op membership now.)" : "");
}""")
# trust / ban / settings on a closed island: refused (the island comes back exactly as it was); null = open
M(st_, r"""
public static String closedEdit(String key, @PKG@.IslandSettings s) {
  if (closedState(key) == 0) return null;
  return "-" + ownerDisplay(key, s) + "'s island is closed - its owner's profile was deleted. Nothing on it can change until that profile is restored.";
}""")
# the closed line for a co-op member whose co-op island is closed (join, /island menu), else null
M(st_, r"""
public static String closedNote(java.util.UUID u) {
  if (u == null) return null;
  String k = pkey(u);
  String hk = homeKey(u);
  if (hk.equals(k)) return null;
  @PKG@.IslandSettings s = settings(hk);
  if (s.bad || s.world == null) return null;
  int cs = closedState(hk);
  return cs == 0 ? null : closedText(hk, s, cs, u);
}""")
# ---- one-time notices for players who are offline when it happens: Skyy_SkyyIslands/notices.properties (player UUID = chat lines,
# newline separated). Read once per JVM; written only when a notice is added, dropped or shown. A failed read never re-creates the
# file: the notices stay in memory (NOTES_RO), the file is read again at most once a minute (NOTES_AT) and, once it reads, the
# in-memory notices are merged into it and saved (review: one transient error no longer lasts until the restart). NOTE_LOCK guards
# it; nothing else is called while it is held.
M(st_, r"""
public static java.nio.file.Path noteFile() {
  return DIR == null ? null : DIR.getParent().resolve("notices.properties");
}""")
M(st_, r"""
public static boolean noteSave0(java.util.Properties p) {
  if (NOTES_RO) return false;
  java.nio.file.Path f = noteFile();
  if (f == null) return false;
  try {
    java.nio.file.Files.createDirectories(f.getParent(), new java.nio.file.attribute.FileAttribute[0]);
    java.nio.file.Path tmp = f.resolveSibling("notices.properties.tmp");
    java.io.OutputStream out = java.nio.file.Files.newOutputStream(tmp, new java.nio.file.OpenOption[0]);
    try { p.store(out, "SkyyIslands one-time notices: player UUID = chat lines shown at their next join"); } finally { out.close(); }
    Throwable last = null;
    for (int i = 0; i < 5; i++) {
      try {
        java.nio.file.Files.move(tmp, f, new java.nio.file.CopyOption[] { java.nio.file.StandardCopyOption.REPLACE_EXISTING });
        last = null;
        break;
      } catch (java.nio.file.FileSystemException e) {
        last = e;
        if (i < 4) { try { Thread.sleep(20L); } catch (Throwable ie) { } }
      }
    }
    if (last != null) throw last;
    return true;
  } catch (Throwable t) { warn("could not write notices.properties: " + t); return false; }
}""")
M(st_, r"""
public static java.util.Properties notes0() {
  if (NOTES != null && (!NOTES_RO || System.currentTimeMillis() - NOTES_AT < 60000L)) return NOTES;
  java.util.Properties p = new java.util.Properties();
  java.nio.file.Path f = noteFile();
  try {
    if (f != null && java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) {
      java.io.InputStream in = java.nio.file.Files.newInputStream(f, new java.nio.file.OpenOption[0]);
      try { p.load(in); } finally { in.close(); }
    }
  } catch (Throwable t) {
    NOTES_AT = System.currentTimeMillis();
    if (NOTES == null) {
      NOTES_RO = true;
      NOTES = new java.util.Properties();
      warn("could not read notices.properties (" + t + ") - it is left untouched and read again every minute; island notices stay in memory meanwhile");
    }
    return NOTES;
  }
  if (NOTES != null) {
    java.util.Properties m = NOTES;
    java.util.Iterator it = m.stringPropertyNames().iterator();
    while (it.hasNext()) {
      String us = (String) it.next();
      String[] a = m.getProperty(us, "").split("\n");
      for (int i = 0; i < a.length; i++) {
        String old = p.getProperty(us);
        if (a[i].length() == 0 || (old != null && ("\n" + old + "\n").indexOf("\n" + a[i] + "\n") >= 0)) continue;
        p.setProperty(us, old == null || old.length() == 0 ? a[i] : old + "\n" + a[i]);
      }
    }
    NOTES = p;
    NOTES_RO = false;
    noteSave0(p);
    info("notices.properties can be read again - the island notices kept in memory meanwhile are merged into it");
    return p;
  }
  NOTES = p;
  return p;
}""")
# true = added (false = that exact line already waits for this player)
M(st_, r"""
public static boolean noticeAdd0(String us, String text) {
  java.util.Properties p = notes0();
  String old = p.getProperty(us);
  if (old != null && ("\n" + old + "\n").indexOf("\n" + text + "\n") >= 0) return false;
  p.setProperty(us, old == null || old.length() == 0 ? text : old + "\n" + text);
  noteSave0(p);
  return true;
}""")
# removes one waiting line (a release that was announced before its island file write, and that write failed)
M(st_, r"""
public static void noticeDrop0(String us, String text) {
  java.util.Properties p = notes0();
  String old = p.getProperty(us);
  if (old == null) return;
  String[] a = old.split("\n");
  StringBuilder sb = new StringBuilder();
  boolean hit = false;
  for (int i = 0; i < a.length; i++) {
    if (!hit && a[i].equals(text)) { hit = true; continue; }
    if (sb.length() > 0) sb.append("\n");
    sb.append(a[i]);
  }
  if (!hit) return;
  if (sb.length() == 0) p.remove(us); else p.setProperty(us, sb.toString());
  noteSave0(p);
}""")
M(st_, r"""
public static String noticeTake0(String us) {
  java.util.Properties p = notes0();
  String t = p.getProperty(us);
  if (t == null) return null;
  p.remove(us);
  noteSave0(p);
  return t;
}""")
M(st_, r"""
public static boolean noticeAdd(java.util.UUID u, String text) {
  if (u == null || text == null) return false;
  String us = u.toString();
  boolean r = false;
  synchronized (NOTE_LOCK) { r = noticeAdd0(us, text); }
  return r;
}""")
M(st_, r"""
public static void noticeDrop(java.util.UUID u, String text) {
  if (u == null || text == null) return;
  String us = u.toString();
  synchronized (NOTE_LOCK) { noticeDrop0(us, text); }
}""")
M(st_, r"""
public static String noticeTake(java.util.UUID u) {
  if (u == null) return null;
  String us = u.toString();
  String r = null;
  synchronized (NOTE_LOCK) { r = noticeTake0(us); }
  return r;
}""")
# a one-time line: at once when the player is online (any profile), else at their next join
M(st_, r"""
public static void tellOnce(java.util.UUID u, String text) {
  @PR@ p = online(u);
  if (p != null) say(p, text, "#ffe08a"); else noticeAdd(u, text);
}""")
# under lockOf(ok): clearCoop0 for a released island, but it writes nothing when the file lists no members. The removed members
# (comma list, maybe empty) or null = island file error (nothing changed). Only members / admins / coopSince.* change.
M(st_, r"""
public static String releaseCoop0(String ok) {
  java.util.Properties p = readForUpdate0(ok);
  if (p == null) return null;
  String m = norm(p.getProperty("members", ""));
  if (m.length() == 0) return "";
  String[] a = split(m);
  for (int i = 0; i < a.length; i++) p.remove("coopSince." + a[i]);
  p.setProperty("members", "");
  p.setProperty("admins", "");
  return write0(ok, p) ? m : null;
}""")
M(st_, r"""
public static String releaseCoop(String ok) {
  String r = null;
  synchronized (lockOf(ok)) { r = releaseCoop0(ok); }
  return r;
}""")
# the one-time line of a co-op member released because the island owner's profile is archived
M(st_, r"""
public static String relText(String on, String mk) {
  return "[Island] " + on + "'s island profile was deleted for good, so you are no longer in its co-op (your " + profWord(mk) + "). /island makes your own island now.";
}""")
# the owner's profile is archived: every co-op member released (island file + MEMBER_OF), each told once. -1 = file error (retried).
# Review: an OFFLINE member's line is saved BEFORE the island file write (a server stop between the write and the line can't release
# them silently) and dropped again when that write fails or does not list them; not saved again while a failed release is retried.
M(st_, r"""
public static int releaseAll(String ok, @PKG@.IslandSettings s) {
  String on = ownerDisplay(ok, s);
  String[] pre = split(s.members);
  String[] tx = new String[pre.length];
  boolean[] q = new boolean[pre.length];
  boolean retry = REL_FAIL.containsKey(ok);
  for (int i = 0; i < pre.length; i++) {
    java.util.UUID mu = ownerUuid(pre[i]);
    if (mu == null) continue;
    tx[i] = relText(on, pre[i]);
    if (!retry && online(mu) == null) q[i] = noticeAdd(mu, tx[i]);
  }
  String removed = releaseCoop(ok);
  for (int i = 0; i < pre.length; i++) {
    if (q[i] && (removed == null || !contains(removed, pre[i]))) noticeDrop(ownerUuid(pre[i]), tx[i]);
  }
  if (removed == null) {
    if (REL_FAIL.putIfAbsent(ok, Boolean.TRUE) == null) warn("could not release the co-op members of " + ok + " (its owner's profile is archived): the island file can't be read or written - retried every 30 s");
    return -1;
  }
  REL_FAIL.remove(ok);
  String[] a = split(removed);
  if (a.length == 0) return 0;
  for (int i = 0; i < a.length; i++) {
    MEMBER_OF.remove(a[i], ok);
    java.util.UUID mu = ownerUuid(a[i]);
    if (mu == null) continue;
    if (online(mu) != null) publish(mu);
    boolean saved = false;
    for (int j = 0; j < pre.length; j++) if (q[j] && pre[j].equals(a[i])) saved = true;
    if (!saved) tellOnce(mu, relText(on, a[i]));
  }
  bump();
  info("released " + a.length + " co-op member(s) of " + ok + " - its owner's profile is archived (the island file and world stay; an archive restore gives the owner the island back without members)");
  return a.length;
}""")
# a co-op member's own profile is archived: removed from the island (frees the slot), the owner told once. true = removed. Review: an
# OFFLINE owner's line is saved before the island file write and dropped again when it fails (not saved again while it is retried)
M(st_, r"""
public static boolean releaseMember(String ok, @PKG@.IslandSettings s, String mk) {
  String mn = nameOf(s, mk);
  String fk = ok + "|" + mk;
  java.util.UUID ou = ownerUuid(ok);
  String txt = ou == null ? null : "[Island] " + mn + " deleted the profile they had in your island co-op" + (ok.equals(pkey(ou)) ? "" : " (your " + profWord(ok) + ")") + ", so they are no longer a member - their co-op slot is free again.";
  boolean q = ou != null && !REL_FAIL.containsKey(fk) && online(ou) == null && noticeAdd(ou, txt);
  int lr = leaveCoop(ok, mk);
  if (q && lr != 0) noticeDrop(ou, txt);
  if (lr == 2) {
    if (REL_FAIL.putIfAbsent(fk, Boolean.TRUE) == null) warn("could not remove the archived profile " + mk + " from the co-op of " + ok + ": the island file can't be read or written - retried every 30 s");
    return false;
  }
  REL_FAIL.remove(fk);
  if (lr != 0) return false;
  MEMBER_OF.remove(mk, ok);
  bump();
  if (ou != null && !q) tellOnce(ou, txt);
  info("removed " + mk + " (" + mn + ") from the co-op of " + ok + " - that member's profile is archived");
  return true;
}""")
# SeenTick, every 30 s, scheduler thread (after that tick's sweeps are queued): islands whose OWNER's profile is archived release their
# members; members whose own profile is archived leave. Only islands that list members are asked about; nothing at all without
# profile:fn:state. Returns players released. Review: a failed island file write (write0) drops that island from SETTINGS, so the
# islands of failed releases (REL_FAIL) are read back first - the retry really happens every 30 s.
M(st_, r"""
public static int archiveScan() {
  Object fn = bridge().get("profile:fn:state");
  if (!(fn instanceof java.util.function.Function)) return 0;
  if (!REL_FAIL.isEmpty()) {
    java.util.ArrayList fk = new java.util.ArrayList(REL_FAIL.keySet());
    for (int i = 0; i < fk.size(); i++) {
      String k = (String) fk.get(i);
      int bar = k.indexOf('|');
      String ik = bar < 0 ? k : k.substring(0, bar);
      try { if (!SETTINGS.containsKey(ik)) settings(ik); } catch (Throwable t) { }
    }
  }
  int n = 0;
  java.util.ArrayList keys = new java.util.ArrayList(SETTINGS.keySet());
  for (int i = 0; i < keys.size(); i++) {
    String ok = (String) keys.get(i);
    try {
      Object o = SETTINGS.get(ok);
      if (!(o instanceof @PKG@.IslandSettings)) continue;
      @PKG@.IslandSettings s = (@PKG@.IslandSettings) o;
      if (s.bad || s.members == null || s.members.length() == 0) continue;
      if ("archived".equals(profState(ok))) {
        int r = releaseAll(ok, s);
        if (r > 0) n = n + r;
        continue;
      }
      String[] m = split(s.members);
      for (int j = 0; j < m.length; j++) {
        if (!m[j].equals(ok) && "archived".equals(profState(m[j])) && releaseMember(ok, s, m[j])) n++;
      }
    } catch (Throwable t) { warn("archive check of island " + ok + " failed: " + t); }
  }
  return n;
}""")
'''
rep('''M(st_, r"""
public static void notifyIsland(String ok, String text, String color, java.util.UUID ex1, java.util.UUID ex2) {
  notifyIslandKey(ok, text, color, ex1, ex2, null);
}""")
''', '''M(st_, r"""
public static void notifyIsland(String ok, String text, String color, java.util.UUID ex1, java.util.UUID ex2) {
  notifyIslandKey(ok, text, color, ex1, ex2, null);
}""")
''' + STORE)

# ================================================================================================ entry paths
# IslandCmd.go: every teleport to someone else's island (own == false) - /island, /island home|go, the menu's Go to island, the SkyyProfiles
# switch teleport (/island), /island visit|warp (+ the old flag form). Before any teleport; server admins pass.
rep("""  if (s0.bad) { @PKG@.IslandStore.tell(pr, @PKG@.IslandStore.READ_ERR); return; }
  String name = s0.world;""", """  if (s0.bad) { @PKG@.IslandStore.tell(pr, @PKG@.IslandStore.READ_ERR); return; }
  // 0.5.5: the owner's profile is deleted (pending) or archived. Only the player's own CURRENT profile key skips the check (review: the
  // caller's own flag is not trusted; an active key is never pending or archived)
  int cs5 = @PKG@.IslandStore.pkey(u).equals(owner) ? 0 : @PKG@.IslandStore.closedState(owner);
  if (cs5 > 0 && !@PKG@.IslandPerms.isAdmin(pr)) { @PKG@.IslandStore.tell(pr, @PKG@.IslandStore.closedText(owner, s0, cs5, u)); return; }
  String name = s0.world;""")
# /island info: the closed line under "Home island"
rep("""    @PKG@.IslandStore.say(pr, "[Island]" + prof + " Home island: " + who, "#ffe08a");
""", """    @PKG@.IslandStore.say(pr, "[Island]" + prof + " Home island: " + who, "#ffe08a");
    int cs5 = hk.equals(k) ? 0 : @PKG@.IslandStore.closedState(hk);   // 0.5.5
    if (cs5 > 0) @PKG@.IslandStore.tell(pr, @PKG@.IslandStore.closedText(hk, s, cs5, u));
""")
# /island visit: refused before the visiting line (go() checks again)
rep("""    if (@PKG@.IslandStore.isRetired(s.world)) { @PKG@.IslandStore.tell(pr, "-That island is being reset - try again in a moment."); return; }
""", """    int cs5 = @PKG@.IslandStore.closedState(tk);   // 0.5.5
    if (cs5 > 0) { @PKG@.IslandStore.tell(pr, @PKG@.IslandStore.closedText(tk, s, cs5, u)); return; }
    if (@PKG@.IslandStore.isRetired(s.world)) { @PKG@.IslandStore.tell(pr, "-That island is being reset - try again in a moment."); return; }
""")

# ================================================================================================ sent off: sweep + arrival
SENDOFF = r'''# 0.5.5 (world thread): someone (not a server admin) on an island whose owner's profile is deleted (pending) or archived -> the closed
# line, then away: a co-op member of it with an island of their own on this profile goes there (the kick / disband destination,
# SendHomeTask's go(own)), everyone else - a member without an island too - to the hub (SendHubTask: the visitor / unavailable-island
# destination). At most one send per player per 4 s (EXPELLING, shared with SendHubTask.now).
M(swp, r"""
public static void sendOffClosed(@ST@ st, @REF@ ref, @PR@ p, @WLD@ w, String owner, @PKG@.IslandSettings s, int cs) {
  try {
    java.util.UUID u = p.getUuid();
    long t = System.currentTimeMillis();
    Long last = (Long) @PKG@.IslandStore.EXPELLING.get(u);
    if (last != null && t - last.longValue() < 4000L) return;
    String k = @PKG@.IslandStore.pkey(u);
    @PKG@.IslandStore.tell(p, @PKG@.IslandStore.closedText(owner, s, cs, u));
    if (!k.equals(owner) && @PKG@.IslandStore.contains(s.members, k)) {
      @PKG@.IslandSettings own = @PKG@.IslandStore.settings(k);
      if (!own.bad && own.world != null && !own.world.equals(w.getName())) {
        @PKG@.IslandStore.EXPELLING.put(u, Long.valueOf(t));
        @PKG@.IslandCmd.go(st, ref, p, w, k, true);
        return;
      }
    }
    @PKG@.SendHubTask.now(st, ref, p, w, null);
  } catch (Throwable x) { @PKG@.IslandStore.warn("could not send a player off a closed island: " + x); }
}""")
'''
rep("# world thread: apply the settings, then send off everyone who may not be here (spec 4.1 sweep, no limit clause; PvP-on expels visitors)\n",
    SENDOFF + "# world thread: apply the settings, then send off everyone who may not be here (spec 4.1 sweep, no limit clause; PvP-on expels visitors)\n"
    "# 0.5.5: and everyone but server admins while the owner's profile is deleted or archived (one profile:fn:state call per sweep)\n")
rep("""    boolean retired = @PKG@.IslandStore.isRetired(wn);
    if (!retired) apply(w, s);
""", """    boolean retired = @PKG@.IslandStore.isRetired(wn);
    if (!retired) apply(w, s);
    int cs5 = retired ? 0 : @PKG@.IslandStore.closedState(owner);   // 0.5.5
""")
rep("""      if (@PKG@.IslandPerms.isAdmin(p)) continue;
      java.util.UUID u = p.getUuid();
      String why = null;""", """      if (@PKG@.IslandPerms.isAdmin(p)) continue;
      if (cs5 > 0) {
        @REF@ cref = p.getReference();
        if (cref == null) continue;
        @ST@ cst = cref.getStore();
        if (cst == null) continue;
        sendOffClosed(cst, cref, p, w, owner, s, cs5);
        continue;
      }
      java.util.UUID u = p.getUuid();
      String why = null;""")
rep("""      @PKG@.SendHubTask.now(st, ref, pr, w, "[Island] This island was reset - /island takes co-op members to the new one.");
      return;
    }
""", """      @PKG@.SendHubTask.now(st, ref, pr, w, "[Island] This island was reset - /island takes co-op members to the new one.");
      return;
    }
    int cs5 = @PKG@.IslandStore.closedState(owner);   // 0.5.5: the owner's profile is deleted (pending) or archived
    if (cs5 > 0) {
      if (!admin) { @PKG@.SweepTask.sendOffClosed(st, ref, pr, w, owner, s, cs5); return; }
      @PKG@.IslandStore.say(pr, "[Island] Server admin: " + on + "'s island is closed - its owner's profile was " + (cs5 == 2 ? "deleted for good (archived)" : "deleted (undo window)") + ". You may stay to inspect it.", "#ffe08a");
    }
""")

# ================================================================================================ co-op actions on a closed island
rep("""  if (s.world == null) return "that island is gone";
""", """  if (s.world == null) return "that island is gone";
  int cs5 = @PKG@.IslandStore.closedState(ok);   // 0.5.5: no joining a closed island (the menu's invite row shows this reason too)
  if (cs5 > 0) return "that island is closed - its owner's profile was deleted" + (cs5 == 2 ? " for good" : "");
""")
rep("""  long exp = System.currentTimeMillis() + @PKG@.IslandCfg.INVITE_SECONDS * 1000L;
""", """  if (@PKG@.IslandStore.closedState(hk) > 0) return "-" + on + "'s island is closed - its owner's profile was deleted. No co-op invites until that profile is restored.";   // 0.5.5
  long exp = System.currentTimeMillis() + @PKG@.IslandCfg.INVITE_SECONDS * 1000L;
""")
CL5 = "\n  String cl5 = @PKG@.IslandStore.closedEdit(hk, s);   // 0.5.5: nothing on a closed island changes\n  if (cl5 != null) return cl5;"
rep('  if (rank < 3) return "-Only the island owner and island admins can trust players.";',
    '  if (rank < 3) return "-Only the island owner and island admins can trust players.";' + CL5)
rep('  if (@PKG@.IslandPerms.rank(hk, u, s) < 3) return "-Only the island owner and island admins can untrust players.";\n'
    '  if (tk == null || !@PKG@.IslandStore.contains(s.trusted, tk))',
    '  if (@PKG@.IslandPerms.rank(hk, u, s) < 3) return "-Only the island owner and island admins can untrust players.";' + CL5 + '\n'
    '  if (tk == null || !@PKG@.IslandStore.contains(s.trusted, tk))')
rep('  if (@PKG@.IslandPerms.rank(hk, u, s) < 3) return "-Only the island owner and island admins can ban.";',
    '  if (@PKG@.IslandPerms.rank(hk, u, s) < 3) return "-Only the island owner and island admins can ban.";' + CL5)
rep('  if (@PKG@.IslandPerms.rank(hk, u, s) < 3) return "-Only the island owner and island admins can unban.";\n'
    '  if (uu == null || !@PKG@.IslandStore.contains(s.banned, uu))',
    '  if (@PKG@.IslandPerms.rank(hk, u, s) < 3) return "-Only the island owner and island admins can unban.";' + CL5 + '\n'
    '  if (uu == null || !@PKG@.IslandStore.contains(s.banned, uu))')
rep("""  if (rank < 3) return "-Only the island owner and island admins can change the island settings.";
  if (s.world == null) return "-Create your island first: /island";
  return null;""", """  if (rank < 3) return "-Only the island owner and island admins can change the island settings.";
  if (s.world == null) return "-Create your island first: /island";
  if (s.key != null) {   // 0.5.5: visits, limit, ping, PvP, spawning, permissions, lock - not on a closed island
    String cl5 = @PKG@.IslandStore.closedEdit(s.key, s);
    if (cl5 != null) return cl5;
  }
  return null;""")

# ================================================================================================ bridge island:perm:fn
rep("""      if (@PKG@.IslandStore.isRetired(wn)) return Boolean.FALSE;
""", """      if (@PKG@.IslandStore.isRetired(wn)) return Boolean.FALSE;
      if (@PKG@.IslandStore.closedState(owner) > 0) return Boolean.FALSE;   // 0.5.5 (server admins got TRUE above)
""")
rep("""    if (flag.equalsIgnoreCase("settings")) return Boolean.valueOf(rank >= 3);""",
    """    if (flag.equalsIgnoreCase("settings")) return Boolean.valueOf(rank >= 3 && @PKG@.IslandStore.closedState(owner) == 0);   // 0.5.5""")

# ================================================================================================ /island menu: the closed line at open
rep('''    p.getPageManager().openCustomPage(ref, store, new @PKG@.IslandMenuPage(pr));""", aliases=("settings", "options"))''',
    '''    @PKG@.IslandMenuPage pg = new @PKG@.IslandMenuPage(pr);
    String cn = @PKG@.IslandStore.closedNote(pr.getUuid());   // 0.5.5: a closed co-op island = the closed line in the result line
    if (cn != null) pg.info = cn;
    p.getPageManager().openCustomPage(ref, store, pg);""", aliases=("settings", "options"))''')

# ================================================================================================ join: JoinNote + IslandReady
JOIN = r'''# 0.5.5: first ready of the online session (+6 s, scheduler thread, after the login routing line and its hub teleport at +1.5 s - review:
# not mid-transition, where a client might drop the line after noticeTake already removed it): the one-time island notices saved
# while the player was offline (co-op released, a member's profile archived), then - for a co-op member - the closed line when their
# co-op island's owner profile is deleted or archived (they hear it at once, not at their next /island)
jnt.addInterface(pool.get("java.lang.Runnable"))
F(jnt, "public @PR@ pr;")
C(jnt, "public JoinNote(@PR@ p) { this.pr = p; }")
M(jnt, r"""
public void run() {
  try {
    if (pr == null || !pr.isValid()) return;
    java.util.UUID u = pr.getUuid();
    String t = @PKG@.IslandStore.noticeTake(u);
    if (t != null) {
      String[] a = t.split("\n");
      for (int i = 0; i < a.length; i++) if (a[i].trim().length() > 0) @PKG@.IslandStore.say(pr, a[i], "#ffe08a");
    }
    String cn = @PKG@.IslandStore.closedNote(u);
    if (cn != null) @PKG@.IslandStore.tell(pr, cn);
  } catch (Throwable x) { @PKG@.IslandStore.warn("join notice failed: " + x); }
}""")
M(jnt, r"""
public static void schedule(@PR@ pr) {
  try { @HSV@.SCHEDULED_EXECUTOR.schedule(new @PKG@.JoinNote(pr), 6000L, java.util.concurrent.TimeUnit.MILLISECONDS); } catch (Throwable t) { }
}""")
'''
rep('rdy.addInterface(pool.get("java.util.function.Consumer"))\n', JOIN + 'rdy.addInterface(pool.get("java.util.function.Consumer"))\n')
rep("    if (@PKG@.IslandStore.SEEN.putIfAbsent(pr.getUuid(), Boolean.TRUE) == null) { @PKG@.RouteTask.schedule(pr); return; }",
    "    if (@PKG@.IslandStore.SEEN.putIfAbsent(pr.getUuid(), Boolean.TRUE) == null) { @PKG@.RouteTask.schedule(pr); @PKG@.JoinNote.schedule(pr); return; }")
# SeenTick: the archive check every 30 s (offset from retryBad), AFTER this tick's island sweeps are queued (review: a slow
# profile:fn:state call there - a cache miss under the SkyyProfiles store lock, an island file lock, notices I/O - must not delay the
# 5 s send-offs of every island)
rep("      w.execute(new @PKG@.SweepTask(w, false));\n    }\n  } catch (Throwable t) { }\n}",
    "      w.execute(new @PKG@.SweepTask(w, false));\n    }\n"
    "    if (this.runs % 6 == 3) @PKG@.IslandStore.archiveScan();   // 0.5.5: archived owners release their co-op, archived members leave\n"
    "  } catch (Throwable t) { }\n}")

# ================================================================================================ the page gate's names (build-time text only)
g0 = s.index('IS_PAGE_CHECKED = "144f342c8b5a"')
g1 = s.index("# ---- end page gate")
gate = s[g0:g1]
assert (gate.count("test_skyyislands_0.5.4.py"), gate.count("tools/islands_0_5_4_patch.py"), gate.count("SkyyIslands-0.5.4-UNCHECKED.jar"),
        gate.count("SkyyIslands-0.5.4.jar")) == (6, 3, 4, 2), "the 0.5.4 page gate texts changed"
gate = (gate.replace("test_skyyislands_0.5.4.py", "test_skyyislands_0.5.5.py").replace("tools/islands_0_5_4_patch.py", "tools/islands_0_5_5_patch.py")
        .replace("SkyyIslands-0.5.4-UNCHECKED.jar", "SkyyIslands-0.5.5-UNCHECKED.jar").replace("SkyyIslands-0.5.4.jar", "SkyyIslands-0.5.5.jar"))
_cl = 'IS_PAGE_CHECKED = "144f342c8b5a"   # the page id SkyyIslands/test_skyyislands_0.5.5.py last passed on (tools/islands_0_5_5_patch.py)'
assert gate.count(_cl) == 1, "page gate comment"
PAGE_CHECKED = "144f342c8b5a"   # the page id the page harness last passed on (0.5.4's page = 0.5.5's: F of test_skyyislands_0.5.5.py)
gate = gate.replace(_cl, 'IS_PAGE_CHECKED = "%s"   # the page id the page harness last passed on (PAGE_CHECKED in tools/islands_0_5_5_patch.py)' % PAGE_CHECKED)
s = s[:g0] + gate + s[g1:]

# ================================================================================================ CHECKED (the harness results, pasted in after a run)
CHECKED = r'''CHECKED with SkyyIslands/test_skyyislands_0.5.5.py (committed next to the build; re-run it, do not trust this text).'''
RESULTS = r"""
2026-10-01 (after the review fixes), kit skyyui 1.4 ac93356c4c60, page 144f342c8b5a: 91588 ok, 0 fails. One JVM with -Xverify:all,
HytaleServer.jar, 0.5.4 and 0.5.5 each in its own class loader:
A all 72 / 73 classes of both jars load, verify and initialise. B 59 classes byte-identical (IslandMenuPage included), CfgFn / CfgRows /
IslandCfg differ only in version strings, SkyyIslandsPlugin = 0.5.4's bytes once its ready constant is swapped back (setup untouched),
+ JoinNote (schedule waits 6000 ms); changed exactly as planned (155 methods compared): IslandStore <clinit> + 22 new methods + 5
fields, IslandCmd go / info / visit, SweepTask run + sendOffClosed, ArrivalTask run, IslandCoop acceptProblem / invite / trust /
untrustByKey / ban / unbanByKey / editRefusal, PermFn apply, IslandReady accept, SeenTick run, IslandMenuCmd execute. C 932 page builds:
466 identical to 0.5.4 (whole command list + bindings) without and with a profile:fn:state that answers live; the 0.5.4 page checks on
the output (18280 markups, 233 pages assert_proven, layout, 253 coverage checks, column heads). D 296 clicks, identical to 0.5.4 in both
modes. E 685 texts fit (the text count follows the live save the harness copies; the review's run also counted 685).
F page id 144f342c8b5a = the checked page; page gate 6 cases. G 93 checks on a scratch copy of the live save (HUD mod: owner = Skyy's
profile 1 island, member = WesleyPlayz with an island of their own, + harness players) with a stubbed profile:fn:state reading the
copied players files: 7 entry paths refused (IslandCmd.go with own=true too) + accept / invite / 10 edits / perm:fn / info / menu line;
arrival + sweep + SeenTick send-offs (own island / hub / admin stays, no double send; the archive scan asks only after the sweeps are
queued); restore; leave while closed; release both sides once (online + next join); an offline player's line saved before the island
file write, dropped when it fails, not saved twice by the retry, released once writable (owner archived and member archived); archived
member (owner online / offline); "profile #N" for a deleted profile; a corrupt notices file read again after a minute and merged; no
SkyyProfiles, 0.1.4, null, unknown = 0.5.4 side by side; start twice writes nothing.
UNVERIFIED (needs the game): the teleports themselves (the same IslandCmd.go(own) / SendHubTask calls 0.5.4 uses for kicks and
visitors), the real SkyyProfiles 0.1.5 profile:fn:state next to it, chat lines on a real client, JoinNote's +6 s after the login line.
"""   # the summary lines of the latest SkyyIslands/test_skyyislands_0.5.5.py run, pasted here
RESULTS = RESULTS.strip()
if RESULTS:
    CHECKED = "CHECKED with SkyyIslands/test_skyyislands_0.5.5.py (re-run it: python SkyyIslands/test_skyyislands_0.5.5.py):\n" + "\n".join(
        "    " + ln for ln in RESULTS.splitlines())
rep("  @@CHECKED@@\n", "  " + CHECKED + "\n")

# ================================================================================================ checks on the result
assert "@@" not in s, "a @@ token is left in the generated script"
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert s.count("registerSystem(") == SYS0, "system registrations changed"
for x in SECURITY + LOCKS:
    assert s.count(x) == 1, "a kept line changed: " + x[:80]
assert PAGE_KEEP in s and PAGE_KEEP2 in s, "the island menu page changed"
assert GUARDS_KEEP in s, "the guards changed"
assert s.count('"profile:fn:state"') == 2, "profile:fn:state is read in profState and archiveScan only"
# javassist: methods before callers
_o = [s.index(x) for x in ("public static int closedState(", "public static String closedText(", "public static int archiveScan(",
                           "public static void go(@ST@ store", "public static void sendOffClosed(", "public void run() {\n  try {\n    @WLD@ w = this.world;",
                           "public static void schedule(@PR@ pr) {\n  try { @HSV@.SCHEDULED_EXECUTOR.schedule(new @PKG@.JoinNote(pr), 6000L",
                           "@PKG@.JoinNote.schedule(pr); return; }")]
assert _o == sorted(_o), "method order: %s" % _o
assert s.index("public static String closedText(") > s.index("public static String ownerDisplay(") > 0
assert s.index("public static int archiveScan(") > s.index("public static int leaveCoop(String ok, String k)")
# review fixes: helpers before their callers; the archive scan after SeenTick's sweep dispatch; go() keys the check on pkey(u)
_o2 = [s.index(x) for x in ("public static boolean noteSave0(", "public static java.util.Properties notes0()", "public static boolean noticeAdd0(",
                            "public static void noticeDrop0(", "public static boolean noticeAdd(java", "public static void noticeDrop(java",
                            "public static void tellOnce(", "public static String relText(", "public static int releaseAll(",
                            "public static boolean releaseMember(", "public static int archiveScan(")]
assert _o2 == sorted(_o2), "review helper order: %s" % _o2
assert s.index("public static @PKG@.IslandSettings settings(String key)") < s.index("public static int archiveScan(")
_st = s.index("public void run() {\n  try {\n    java.util.HashSet online = new java.util.HashSet();")
assert s.index("w.execute(new @PKG@.SweepTask(w, false));", _st) < s.index("@PKG@.IslandStore.archiveScan();", _st), "archiveScan after the sweeps"
assert s.count("@PKG@.IslandStore.archiveScan();") == 1 and "own ? 0 : @PKG@.IslandStore.closedState" not in s
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.5.4 had %d)" % (s.count(LF), OLD.count(LF)))
