"""Derive SkyyMobs/build_skyymobs_0.1.5.py from the LIVE 0.1.4 (build_skyymobs_0.1.4.py = the tools/deploy_set.py SET pin). SkyyMobs had
no patch scripts before (0.1.4 was a copy + edit of 0.1.3); this is its first one. Edit THIS file, never the generated script; every anchor
is asserted. Run:
    python tools/mobs_0_1_5_patch.py      then      python SkyyMobs/build_skyymobs_0.1.5.py      (never --deploy)
Harness: python SkyyMobs/test_skyymobs_0.1.5.py

0.1.5 = THE LOOT ROUND's SkyyMobs part (research/Loot-Unid-Spec.md 4.5 + research/cloud/Loot-Round-Revision.md section 5; Skyy LOCKED
docs/answered/gear.md 2026-10-02 "about 1 in 3 world chests gets an extra unidentified piece matching the zone", 2026-10-06 + 2026-10-08 the
Unclaimed Luggage chests "appear all over" with unidentified gear): ONE new bridge, mob:fn:levelAt - the levels a mob spawning on a block
would get, so SkyyGear (fresh vanilla loot chests) and SkyyExploration (Unclaimed Luggage) use the SAME zone level as the mobs there and keep
no copy of the zone tables.
  - mob:fn:levelAt = java.util.function.Function, put in setup next to mob:fn:level, removed in shutdown.
    Argument: Object[] { String worldName, Number x, Number y, Number z } (block coordinates; doubles are floored by MobLevel.lookupAt).
    Result: Object[] { Integer lo, Integer hi, String step, String key } = MobLevel.lookupAt's band + its Bonus, each exactly like levelFor
    (a min <= 0 counts as 1, + bonus, clamped to 1..levels.max), lo <= hi; step / key = the lookup's step and row key (logs, /gear read).
    null: no level there (band 0,0: SkyyIslands islands, bands.default 0, a world row 0,0), part.levels off, unknown world, bad arguments,
    any error. Never throws, never loads a chunk, never writes a file (it fills the existing per-column worldgen cache MobLevel.WG).
    Threads: any. On that world's own thread (World.isInThread) the block environment is read too (lava caves, environment Bonus); from any
    other thread only the 2D worldgen lookup runs (envIdx -1 = no environment row) and the step gets "-2d".
  - MobLevelAtFn.at(World, x, y, z, onThread) is the testable core (the harness runs it on stand-in worlds).
Nothing else changes: no row, no file, no system, no command, no migration. Rolling back to 0.1.4 is safe (the bridge disappears; SkyyGear
0.2.11 and SkyyExploration 0.2.4 then use their own fallbacks: the drop list's zone / no Unclaimed Luggage).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "SkyyMobs", "build_skyymobs_0.1.4.py")
DST = os.path.join(ROOT, "SkyyMobs", "build_skyymobs_0.1.5.py")
raw = open(SRC, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
assert 'VERSION = "0.1.4"' in s and s.startswith('"""SkyyMobs 0.1.4 - build script'), "build_skyymobs_0.1.4.py is not the live 0.1.4"
SYS0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:160])
    s = s.replace(old, new)


# ================================================================================================================ header + version
HEAD = open(__file__, encoding="utf8").read().split('"""')[1]
rep('''"""SkyyMobs 0.1.4 - build script (javassist via jpype). A copy of the SET pin build_skyymobs_0.1.3.py''',
    '''"""SkyyMobs 0.1.5 - build script (javassist via jpype). GENERATED by tools/mobs_0_1_5_patch.py from the LIVE 0.1.4 - edit the patch,
never this file. Run: python SkyyMobs/build_skyymobs_0.1.5.py -> SkyyMobs/SkyyMobs-0.1.5.jar (never --deploy).
Test: python SkyyMobs/test_skyymobs_0.1.5.py

''' + HEAD[HEAD.index("0.1.5 = "):].strip() + '''

0.1.4 (the base, everything below is still true unless 0.1.5 above says otherwise):
SkyyMobs 0.1.4 - build script (javassist via jpype). A copy of the SET pin build_skyymobs_0.1.3.py''')
rep('VERSION = "0.1.4"', 'VERSION = "0.1.5"')

# ================================================================================================================ tokens + probes
rep('''    "WLD": "com.hypixel.hytale.server.core.universe.world.World",
''', '''    "WLD": "com.hypixel.hytale.server.core.universe.world.World",
    "UNIV": "com.hypixel.hytale.server.core.universe.Universe",      # 0.1.5 mob:fn:levelAt (Universe.get().getWorld(name))
''')
rep('''for _c, _m, _r, _a in SIGS:
    probe_sig(_c, _m, _r, _a)
''', '''# 0.1.5 mob:fn:levelAt: the world by name + the world-thread test (TickingThread.isInThread, inherited by World)
SIGS += [(G["UNIV"], "get", G["UNIV"], []), (G["UNIV"], "getWorld", G["WLD"], ["java.lang.String"]),
         (G["WLD"], "isInThread", "boolean", [])]
for _c, _m, _r, _a in SIGS:
    probe_sig(_c, _m, _r, _a)
''')

# ================================================================================================================ the class
rep('''m14 = pool.makeClass(PKG + ".MobMig14")
''', '''m14 = pool.makeClass(PKG + ".MobMig14")
lat = pool.makeClass(PKG + ".MobLevelAtFn")   # 0.1.5: mob:fn:levelAt (the zone level at a block, for loot)
''')
rep('''ALL = [lg, gb, bd, mi, cfg, lv, hk, dm, dmu, fn, ps, sc, pt, rf, mh, mc, mm, gp, gd, gdu, ifn, m14]''',
    '''ALL = [lg, gb, bd, mi, cfg, lv, hk, dm, dmu, fn, ps, sc, pt, rf, mh, mc, mm, gp, gd, gdu, ifn, m14, lat]''')

LAT_PY = r'''
# ---------------------------------------------------------------- 0.1.5 mob:fn:levelAt (bridge, any thread, never throws; see the header)
# Object[]{ String world, Number x, Number y, Number z } -> Object[]{ Integer lo, Integer hi, String step, String key } or null
lat.addInterface(pool.get("java.util.function.Function"))
C(lat, "public MobLevelAtFn() { }")
M(lat, r"""
public static int clampLv(int v) {
  int mx = @PKG@.MobCfg.MAX_LEVEL;
  if (v > mx) v = mx;
  if (v < 1) v = 1;
  return v;
}""")
# the testable core: MobLevel.lookupAt (the spawn lookup of every mob) at the block; envIdx MIN = read the block environment (world
# thread only), -1 = none (any other thread: the 2D worldgen lookup only)
M(lat, r"""
public static Object[] at(@WLD@ w, double x, double y, double z, boolean onThread) {
  if (w == null || !@PKG@.MobCfg.ON) return null;
  Object[] r = @PKG@.MobLevel.lookupAt(w, x, y, z, onThread ? Integer.MIN_VALUE : -1);
  if (r == null || r.length < 5 || !(r[0] instanceof Integer) || !(r[1] instanceof Integer) || !(r[2] instanceof Integer)) return null;
  int a = ((Integer) r[0]).intValue(), b = ((Integer) r[1]).intValue(), bonus = ((Integer) r[2]).intValue();
  if (a <= 0 && b <= 0) return null;
  if (a <= 0) a = 1;
  if (b < a) b = a;
  int lo = clampLv(a + bonus), hi = clampLv(b + bonus);
  if (hi < lo) hi = lo;
  String step = r[3] == null ? "?" : String.valueOf(r[3]);
  String key = r[4] == null ? "?" : String.valueOf(r[4]);
  return new Object[] { Integer.valueOf(lo), Integer.valueOf(hi), onThread ? step : step + "-2d", key };
}""")
M(lat, r"""
public static @WLD@ world(String name) {
  if (name == null || name.length() == 0) return null;
  try {
    @UNIV@ u = @UNIV@.get();
    return u == null ? null : u.getWorld(name);
  } catch (Throwable t) { return null; }
}""")
M(lat, r"""
public static boolean onThread(@WLD@ w) {
  try { return w != null && w.isInThread(); } catch (Throwable t) { return false; }
}""")
M(lat, r"""
public Object apply(Object o) {
  try {
    if (!(o instanceof Object[])) return null;
    Object[] a = (Object[]) o;
    if (a.length < 4 || !(a[0] instanceof String) || !(a[1] instanceof Number) || !(a[2] instanceof Number) || !(a[3] instanceof Number)) return null;
    double x = ((Number) a[1]).doubleValue(), y = ((Number) a[2]).doubleValue(), z = ((Number) a[3]).doubleValue();
    if (Double.isNaN(x) || Double.isNaN(y) || Double.isNaN(z) || Math.abs(x) > 1.0E8 || Math.abs(z) > 1.0E8 || Math.abs(y) > 1.0E5) return null;
    @WLD@ w = world((String) a[0]);
    if (w == null) return null;
    return at(w, x, y, z, onThread(w));
  } catch (Throwable t) { return null; }
}""")

'''
rep('''# ---------------------------------------------------------------- 0.1.4 mob:fn:info (bridge, any thread, never throws; spec 7.3)
''', LAT_PY + '''# ---------------------------------------------------------------- 0.1.4 mob:fn:info (bridge, any thread, never throws; spec 7.3)
''')

# ================================================================================================================ setup / shutdown / ready line
rep('''  @PKG@.MobLevel.bridge().put("mob:fn:info", new @PKG@.MobInfoFn());   // 0.1.4: SkyySkills' kill XP by mob level
''', '''  @PKG@.MobLevel.bridge().put("mob:fn:info", new @PKG@.MobInfoFn());   // 0.1.4: SkyySkills' kill XP by mob level
  @PKG@.MobLevel.bridge().put("mob:fn:levelAt", new @PKG@.MobLevelAtFn());   // 0.1.5: the zone level at a block (SkyyGear chests, SkyyExploration luggage)
''')
rep('''  try { @PKG@.MobLevel.bridge().remove("mob:fn:info"); } catch (Throwable t) { }
''', '''  try { @PKG@.MobLevel.bridge().remove("mob:fn:info"); } catch (Throwable t) { }
  try { @PKG@.MobLevel.bridge().remove("mob:fn:levelAt"); } catch (Throwable t) { }
''')
rep('''a [Lv 9] nameplate, /mobs, mob:fn:level + mob:fn:info "''', '''a [Lv 9] nameplate, /mobs, mob:fn:level + mob:fn:info + mob:fn:levelAt "''')
_rl = s.count(' mob:fn:level + mob:fn:info')
assert _rl >= 1, "the manifest names the bridges"

# ================================================================================================================ write
assert s.count("registerSystem(") == SYS0 and s.count("registerCommand(") == CMD0, "0.1.5 adds no system and no command"
out = s.replace(LF, NL)
with open(DST, "w", encoding="utf8", newline="") as f:
    f.write(out)
print("wrote %s (%d lines)" % (os.path.relpath(DST, ROOT), out.count(NL) + 1))
