"""Derive SkyyPets/build_skyypets_0.2.py from SkyyPets 0.1 (SkyyPets/build_skyypets_0.1.py = the tools/deploy_set.py SET pin; a plain
build script, no patch chain before it - never edit the generated 0.2 script, edit this patch).
Run:  python tools/pets_0_2_patch.py   then   python SkyyPets/build_skyypets_0.2.py   (never --deploy)
      then  python SkyyPets/test_skyypets_0.2.py   (the harness: every new code path executed on engine stand-ins, -Xverify:all, class
      compare 0.1 vs 0.2, start twice on a scratch copy of live data, engine-access audit)

0.2 = research/cloud/Pet-Core-Spec.md PHASE 2: VISIBLE PETS, with research/Pet-Probe-Results.md (Skyy's probe session 2026-10-10) winning
where it differs from the spec. Skyy's own words (docs/answered/pets.md, 2026-10-08 / 2026-10-10):
  "we should make a pet for every nutral mob in the game ... i want all the pets of them to be similar just a little smaller and cuter.
   (keep the mounts near the same size or bigger, but like a skeleton pet would be about fox size."
  "pet follows, and teleports when i get too far away.  F to interact does nothing. later it should pet the pets you cant ride."
  "fish just flop, ill try getting in water, but id make the fish fly around, seems cooler"
  "bat and 1 owl flys, the other owl walks after me. flying ones just fly around, they dont follow me."
What changes (the generated docstring has the full list):
  - build time: the per-kind looks (model, size, walk / fly / fish), the baby looks + sizes, the petting animation per model (all checked
    against Assets.zip), and TWO NPC ROLES generated from vanilla data (never committed): Skyy_Pet_Walk (Test_Pet's follow = Seek the locked
    player + Teleport when far, without its Debug nameplate / state dance / interaction) and Skyy_Pet_Fly (Test_Fly's Fly controller,
    no instructions: our code flies it). The jar now ships those two role files (IncludesAssetPack true).
  - PetsCfg: Server Setup tab rows "Pets in the world" (show, delay, distances, fly height / steering, baby level, mounts, blocked worlds,
    petting cooldown, the two role names) + tables "Pet looks" / "Baby looks" (no row = the built-in look).
  - new PetLook, PetView, PetFly, PetWorldApi / PetWorld (the engine seam), PetViews (spawn / follow / fly / lifecycle / ghost sweep /
    petting), PetSpawnJob / PetRemoveJob / PetPetJob (World.execute), PetUseSys (F = pet it), PetLoadSys (ghost sweep on chunk load).
  - PetTickSys: per-tick fly steering + per-second view upkeep (isParallel false); PetTick.leave removes the views; PetOps /petadmin sweep;
    the plugin registers the two new systems + the /settings switch "pets.show", logs the role census at start, removes every pet at stop.
Everything else is 0.1's - asserted at the end by undoing every recorded change and comparing.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyPets", "build_skyypets_0.1.py")
dst = os.path.join(ROOT, "SkyyPets", "build_skyypets_0.2.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1"' in s and "NEW standalone mod: SLOT PETS, PHASE 1" in s, "not the SkyyPets 0.1 build script"
REG0 = s.count("registerCommand(")
CHANGES = []


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:160])
    s = s.replace(old, new, 1)
    CHANGES.append((new, old))


# ================================================================================================ docstring + version
rep('''"""SkyyPets 0.1 - build script (javassist via jpype, tools/skyybuild.py). NEW standalone mod: SLOT PETS, PHASE 1 (records + buffs).
Owner: Skyy (they/them). Run:  python SkyyPets/build_skyypets_0.1.py   -> SkyyPets/SkyyPets-0.1.jar
(no --deploy on purpose: tools/deploy_set.py installs the set once the round is ready). Test: python SkyyPets/test_skyypets_0.1.py
''', '''"""SkyyPets 0.2 - build script (javassist via jpype, tools/skyybuild.py). GENERATED by tools/pets_0_2_patch.py from SkyyPets 0.1
(build_skyypets_0.1.py, the SET pin) - edit the patch, never this file. SLOT PETS, PHASE 2: VISIBLE PETS.
Owner: Skyy (they/them). Run:  python SkyyPets/build_skyypets_0.2.py   -> SkyyPets/SkyyPets-0.2.jar
(no --deploy on purpose: tools/deploy_set.py installs the set once the round is ready). Test: python SkyyPets/test_skyypets_0.2.py

0.2 WHY (Skyy, docs/answered/pets.md 2026-10-08 / 2026-10-10): "i want all the pets of them to be similar just a little smaller and
cuter. (keep the mounts near the same size or bigger, but like a skeleton pet would be about fox size." + "pet follows, and teleports
when i get too far away.  F to interact does nothing. later it should pet the pets you cant ride." + "fish just flop ... id make the
fish fly around, seems cooler" + "bat and 1 owl flys, the other owl walks after me. flying ones just fly around, they dont follow me."
Design: research/cloud/Pet-Core-Spec.md PHASE 2 (section 8 row 2) + research/Pet-Probe-Results.md (the probe session wins where it
differs: P5 NonSerialized does NOT stop chunk saving -> the ghost sweep; P1 air / water -> our own fly-follow; P10 any size on a mount
role is rideable -> no mount role now; Test_Pet shows a debug nameplate -> our own roles).
0.2 WHAT:
A. LOOKS (Server Setup > Pets > Pet looks / Baby looks, no row = the built-in look): every kind = a SHRUNK vanilla model by id at
   runtime (never copied): Pets-Roster.md 'Pet scale' (skeleton x0.6 = fox size, Void Eye x0.35, ...). Motion walk / fly / fish per kind
   (Hawk + Void Eye fly; fish kinds fly too - none in the launch roster, an admin can give any kind a fish look). BABIES (LOCKED "baby
   until pet Lv 30"): the vanilla baby model below pets.babyUntil (30); a baby taller than its adult pet look is shrunk to 85% of it.
   MOUNTS (Horse, Camel, Ram): pet size in the pet slot, pets.mount.scale (x1.0 = vanilla, "near the same size or bigger") in the summon
   slot - NOT rideable (non-mount roles; riding is phase 5).
B. ROLES (generated at build time from vanilla data, shipped in the jar - IncludesAssetPack true): Skyy_Pet_Walk = Test_Pet's follow
   Seek (stop at 3) on the locked target = the owner (vanilla Template_Trork_Companion's Target -> Seek), else Test_Pet's Player sensor
   (15, LockOnTarget); NO role Teleport (fix round: it fired at ~15-19 blocks, before pets.follow.teleport - our code teleports), without
   Debug / states / interaction, MaxWalkSpeed 6, Invulnerable, DefaultPlayerAttitude Ignore; Skyy_Pet_Fly = Test_Fly's Fly controller with no instructions (Empty_Role's [{}]), Invulnerable, Ignore.
   Both names match SkyyMobs' never-level guard *_Pet* and are in no SkyyMobs list (P8). A role that did not load -> the vanilla
   Test_Pet / Test_Fly with the debug flags cleared from code (warning logged once). Rows pets.role.walk / pets.role.fly (adv).
C. VIEWS (PetViews, the world thread): once a second per online player the pet slot (and the summon slot when it is open) is reconciled:
   wanted = part on + pets.visible + the player's /settings "Show my pets" (pets.show) + shown.1 not false + slot filled + kind on + not a
   blocked world (pets.worlds.blocked) + the owner alive. A wanted pet appears pets.spawn.delay (2) s after join / world arrival next to
   the owner (World.execute: NPCPlugin.spawnEntity with the scaled Model; nameplate "<name or kind> (Lv N)", DisplayName, F-able with the
   vanilla "Press [F] to pet" hint). A changed look (level 30, a new pet in the slot, Server Setup) = the old creature goes, the new one
   comes. Walking pets: the role follows; every second the owner is set as its locked target (never another player) and the debug flags
   are cleared; > pets.follow.teleport (20) blocks or 12 blocks of height for 2 s -> teleported next to the owner. FLYING + FISH pets:
   OUR fly-follow every tick (PetFly): circle the owner at pets.follow.distance (2.5) blocks, pets.fly.height (1.8) above the feet (fish
   80% / 70%, slower, a gentle bob), catch up fast, teleport when far; moved with TransformComponent.setPosition (pets.fly.steer 'move')
   or the Teleport component ('teleport', a fallback if 'move' stutters).
D. LIFECYCLE (spec 2.2 + probes): logout (and the 30 s offline sweep), world change, profile switch, owner death, slot change, setting
   off -> the creature is removed on its own world thread; it comes back on the next second it is wanted. Server stop -> every creature
   queued for removal. Nothing about a creature is saved: it is a throwaway view of the record.
E. GHOST SWEEP (mandatory, P5): every creature's entity UUID is tracked per owner; a pet creature loaded from a chunk (AddReason LOAD)
   that is not the live tracked one - role Skyy_Pet_*, or a UUID we lost track of (unloaded / not found at removal) - is removed at once.
F. F = PET IT (Skyy): our UseEntityEvent$Pre system cancels the vanilla use on our creatures; the owner (cooldown pets.pet.cooldown 3 s)
   gets vanilla Hearts particles, the model's own greeting animation (GreetAnimation / Greet / TiltHead / ... per model, checked), a
   flying pet does a happy loop, a chat line and a bond tick (pet.<id>.bond + 1, saved with the record; no economy effect). Another
   player's pet: "That is <owner>'s <kind>." Summon-slot pets do NOT fight yet (phase 4).
G. /petadmin sweep (op): live creatures, spawned / removed / ghosts / lost / petted counters.
REMOVAL FLOOR (0.2): pet creatures saved in chunks carry our role names. Before removing SkyyPets: Server Setup > Pets > Show pets in the
world OFF (or every player logs out), then remove the jar; a later load of a left-over creature logs an unknown-role NPC once.
The SAME floor holds for a ROLLBACK to 0.1 (no sweep, no Skyy_Pet_* roles): server stop only QUEUES the removals, so a world saved at
stop (or a crash) can keep pet creatures in chunks - roll back only after the switch is OFF and a restart + a visit of the worlds let the
0.2 sweep clear them (tools/deploy_set.py floor note: the main session adds it when 0.2 is pinned).

0.1 (the base, still true unless 0.2 above says otherwise):
''')
rep('VERSION = "0.1"', 'VERSION = "0.2"')

# ================================================================================================ build-time data: looks, babies, anims, roles
rep('''assert len(KINDS) == 30 and len(set(k[0] for k in KINDS)) == 30
assert "Rabbit" in [k[0] for k in KINDS]
''', r'''assert len(KINDS) == 30 and len(set(k[0] for k in KINDS)) == 30
assert "Rabbit" in [k[0] for k in KINDS]

# ================= 0.2: VISIBLE PETS - looks, babies, the petting animation, our two NPC roles (vanilla-derived, generated at build time)
# (kind, model, size in the pet slot, motion) - Pets-Roster.md 'Pet scale'; Skyy: "a little smaller and cuter", skeleton x0.6 = fox size
LOOKS = [
    ("Rabbit", "Rabbit", 0.7, "walk"), ("Chicken", "Chicken", 0.75, "walk"), ("Goat", "Goat", 0.7, "walk"), ("Warthog", "Warthog", 0.8, "walk"),
    ("Bear", "Bear_Grizzly", 0.6, "walk"), ("Turkey", "Turkey", 0.7, "walk"), ("Wolf", "Wolf_Black", 0.75, "walk"), ("Boar", "Boar", 0.8, "walk"),
    ("Hawk", "Hawk", 0.9, "fly"), ("Ram", "Ram", 0.55, "walk"), ("Skrill", "Skrill", 0.75, "walk"), ("Tusker", "Warthog", 0.9, "walk"),
    ("Mouflon", "Mouflon", 0.65, "walk"), ("Horse", "Horse", 0.45, "walk"), ("Camel", "Camel", 0.4, "walk"), ("Fox", "Fox", 0.8, "walk"),
    ("Rat", "Rat", 0.8, "walk"), ("Skeleton", "Skeleton_Fighter", 0.6, "walk"), ("VoidEye", "Eye_Void", 0.35, "fly"),
    ("VoidCrawler", "Crawler_Void", 0.75, "walk"), ("VoidLarva", "Larva_Void", 0.8, "walk"), ("Cat", "Cat", 1.0, "walk"),
    ("Dog", "Dog", 0.8, "walk"), ("Corgi", "Corgi", 1.0, "walk"), ("Frog", "Frog_Green", 1.0, "walk"), ("Mouse", "Mouse", 1.0, "walk"),
    ("Squirrel", "Squirrel", 1.0, "walk"), ("Bunny", "Bunny", 0.8, "walk"), ("Meerkat", "Meerkat", 0.9, "walk"), ("Gecko", "Gecko", 1.0, "walk"),
]
# vanilla babies (Pets-Roster.md 'Babies': "the pet is the BABY until a level (default Lv 30)")
BABIES = [("Chicken", "Chick"), ("Goat", "Goat_Kid"), ("Warthog", "Warthog_Piglet"), ("Turkey", "Turkey_Chick"), ("Boar", "Boar_Piglet"),
          ("Ram", "Ram_Lamb"), ("Skrill", "Skrill_Chick"), ("Tusker", "Warthog_Piglet"), ("Mouflon", "Mouflon_Lamb"), ("Horse", "Horse_Foal"),
          ("Camel", "Camel_Calf"), ("Cat", "Kitten")]
MOUNT_KINDS = "Horse,Camel,Ram"                      # Pets-Roster: Tamed_Horse / Tamed_Camel / Tamed_Ram are the vanilla mounts
ROLE_WALK, ROLE_FLY = "Skyy_Pet_Walk", "Skyy_Pet_Fly"
ROLE_PREFIX = "Skyy_Pet_"
PET_HINT = "server.interactionHints.pet"             # vanilla lang: "Press [{key}] to pet"
USE_ROOT = "*UseNPC"                                 # RoleBuilderSystem: every NPC's Use root (the SkyyMerchants 0.1 F path)
HEARTS = "Hearts"                                    # Server/Particles/NPC/Emotions/Hearts.particlesystem (LifeSpan 3 s: it ends by itself)
ANIM_ORDER = ["GreetAnimation", "Greet", "TiltHead", "Curious", "Croak", "Shake", "Neigh", "Groom", "Eat", "Alerted"]
MOTIONS = ("walk", "fly", "fish")


def vjson(path):
    return json.loads(az.read(path).decode("utf-8-sig"))


MODEL_PATH = dict((n.rsplit("/", 1)[1][:-5], n) for n in AZ if n.startswith("Server/Models/") and n.endswith(".json"))
ROLE_PATH = dict((n.rsplit("/", 1)[1][:-5], n) for n in AZ if n.startswith("Server/NPC/Roles/") and n.endswith(".json"))


def model_h(mid, depth=0):
    """the vanilla hitbox height of a model (following Parent); None when there is none"""
    d = vjson(MODEL_PATH[mid])
    hb = d.get("HitBox") or d.get("BoundingBox")
    if hb:
        return float(hb["Max"]["Y"]) - float(hb["Min"]["Y"])
    return model_h(d["Parent"], depth + 1) if d.get("Parent") and depth < 8 else None


def model_anims(mid, depth=0):
    d = vjson(MODEL_PATH[mid])
    a = set((d.get("AnimationSets") or {}).keys())
    if d.get("Parent") and depth < 8:
        a |= model_anims(d["Parent"], depth + 1)
    return a


assert [k[0] for k in LOOKS] == [k[0] for k in KINDS], "one look per launch kind, in roster order"
for _k, _m, _sc, _mo in LOOKS:
    assert _m in MODELS and 0.1 <= _sc <= 3.0 and _mo in MOTIONS, (_k, _m, _sc, _mo)
assert dict((k[0], k[4]) for k in KINDS)["Skeleton"] == "Skeleton" and dict((k[0], k[1]) for k in LOOKS)["Skeleton"] == "Skeleton_Fighter"
_lk = dict((k, (m, sc)) for k, m, sc, mo in LOOKS)
BABY_ROWS = []           # (kind, baby model, size): a vanilla baby stays x1.0 unless it would stand taller than its adult pet look
for _k, _b in BABIES:
    assert _b in MODELS and _k in _lk, (_k, _b)
    _ah, _bh = model_h(_lk[_k][0]), model_h(_b)
    _sc = 1.0 if (not _ah or not _bh or _bh <= _ah * _lk[_k][1]) else round(0.85 * _ah * _lk[_k][1] / _bh, 2)
    BABY_ROWS.append((_k, _b, _sc))
assert dict((k, s_) for k, m, s_ in BABY_ROWS)["Horse"] < 1.0 and dict((k, s_) for k, m, s_ in BABY_ROWS)["Chicken"] == 1.0
ANIMS = {}
for _m in sorted(set([k[1] for k in LOOKS] + [b[1] for b in BABIES])):
    _a = model_anims(_m)
    ANIMS[_m] = [x for x in ANIM_ORDER if x in _a][0]          # every vanilla creature has at least Alerted
assert ANIMS["Wolf_Black"] == "Greet" and ANIMS["Fox"] == "TiltHead" and all("Alerted" in model_anims(m) for m in ANIMS)
_hearts = [n for n in AZ if n.endswith("/" + HEARTS + ".particlesystem") and n.startswith("Server/Particles/")]
assert len(_hearts) == 1 and vjson(_hearts[0]).get("LifeSpan", 0) > 0, "the vanilla Hearts particle system (with a LifeSpan) is gone"
_lang = az.read("Server/Languages/en-US/server.lang").decode("utf-8-sig")
assert ("\n" + PET_HINT[len("server."):] + " = ") in _lang, "vanilla hint %s missing" % PET_HINT

# ---- the two roles, from vanilla data (Test_Pet's follow, Test_Fly's Fly controller, Empty_Role's empty instructions)
_tp, _tf, _er = vjson(ROLE_PATH["Test_Pet"]), vjson(ROLE_PATH["Test_Fly"]), vjson(ROLE_PATH["Empty_Role"])
assert _tp.get("Debug") == "DisplayState" and _tp.get("Invulnerable") is True and _tp.get("Type") == "Generic"


def _default_state(instrs):
    for i in instrs:
        sn = i.get("Sensor") or {}
        if sn.get("Type") == "State" and sn.get("State") == ".Default":
            return i["Instructions"]
        if "Instructions" in i:
            r = _default_state(i["Instructions"])
            if r is not None:
                return r
    return None


_follow = [i for i in _default_state(_tp["Instructions"]) if (i.get("Sensor") or {}).get("Type") in ("Player", "Target") and "BodyMotion" in i
           and "Filters" not in i["Sensor"] and "Actions" not in i]
assert [i["BodyMotion"]["Type"] for i in _follow] == ["Seek", "Teleport"] and _follow[0]["Sensor"].get("LockOnTarget") is True, _follow
_walk_mc = dict(_tp["MotionControllerList"][0])
assert _walk_mc.get("Type") == "Walk"
_walk_mc["MaxWalkSpeed"] = 6
ROLE_WALK_JSON = {"Type": "Generic", "Appearance": _tp["Appearance"], "Invulnerable": True, "DefaultPlayerAttitude": "Ignore",
                  "MotionControllerList": [_walk_mc], "MaxHealth": _tp["MaxHealth"],
                  # fix round: seek the owner (our locked target) first, Test_Pet's Player sensor only until the target is set; the
                  # role's own Teleport is dropped - it fired at ~15-19 blocks (P3), so pets.follow.teleport never applied to walkers
                  "Instructions": [{"Instructions": [{"Sensor": {"Type": "Target"}, "BodyMotion": dict(_follow[0]["BodyMotion"])}, _follow[0]]}],
                  "NameTranslationKey": _tp["NameTranslationKey"]}
assert _tf["MotionControllerList"][0].get("Type") == "Fly" and _er.get("Instructions") == [{}]
ROLE_FLY_JSON = {"Type": "Generic", "Appearance": "Bat", "Invulnerable": True, "DefaultPlayerAttitude": "Ignore",
                 "MotionControllerList": [dict(_tf["MotionControllerList"][0])], "MaxHealth": 50, "Instructions": [{}],
                 "NameTranslationKey": _tf["NameTranslationKey"]}
ROLE_ASSETS = {"Server/NPC/Roles/SkyyPets/%s.json" % ROLE_WALK: json.dumps(ROLE_WALK_JSON, indent=2) + "\n",
               "Server/NPC/Roles/SkyyPets/%s.json" % ROLE_FLY: json.dumps(ROLE_FLY_JSON, indent=2) + "\n"}
_gen_keys = set()
for _n, _p in ROLE_PATH.items():
    try:
        _j = vjson(_p)
    except Exception:
        continue
    if _j.get("Type") == "Generic":
        _gen_keys |= set(_j.keys())
for _rj in (ROLE_WALK_JSON, ROLE_FLY_JSON):
    assert set(_rj) <= _gen_keys, "role key no vanilla Generic role uses: %s" % (set(_rj) - _gen_keys)
    _txt = json.dumps(_rj)
    assert '"Parallel"' not in _txt and "Debug" not in _rj and "StartState" not in _rj and "State" not in _txt.replace("States", "")
    assert _rj["Appearance"] in MODELS and _rj["DefaultPlayerAttitude"] == "Ignore" and _rj["Invulnerable"] is True
assert ROLE_WALK not in ROLE_PATH and ROLE_FLY not in ROLE_PATH and ROLE_WALK.startswith(ROLE_PREFIX) and ROLE_FLY.startswith(ROLE_PREFIX)
assert "Ignore" in [json.loads(az.read(p).decode("utf-8-sig")).get("DefaultPlayerAttitude") for p in
                    [ROLE_PATH["Test_Attack_Melee"]]], "DefaultPlayerAttitude Ignore is not a vanilla Generic-role value any more"
# fix round: the bare Target sensor -> Seek (follow the locked target, any distance) is a vanilla pattern (the Trork companion)
assert '{"Sensor": {"Type": "Target"}, "BodyMotion": {"Type": "Seek"' in json.dumps(vjson(ROLE_PATH["Template_Trork_Companion"])), "vanilla Target -> Seek gone"
assert "Teleport" not in json.dumps(ROLE_WALK_JSON) and [i["Sensor"]["Type"] for i in ROLE_WALK_JSON["Instructions"][0]["Instructions"]] == ["Target", "Player"]
''')

# ================================================================================================ engine tokens + probes
rep('''    "BT": "com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType",
}''', '''    "BT": "com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType",
    # 0.2: visible pets
    "CAC": "com.hypixel.hytale.component.ComponentAccessor",
    "NPCP": "com.hypixel.hytale.server.npc.NPCPlugin",
    "NPC": "com.hypixel.hytale.server.npc.entities.NPCEntity",
    "MDL": "com.hypixel.hytale.server.core.asset.type.model.config.Model",
    "MDA": "com.hypixel.hytale.server.core.asset.type.model.config.ModelAsset",
    "TC": "com.hypixel.hytale.server.core.modules.entity.component.TransformComponent",
    "TEL": "com.hypixel.hytale.server.core.modules.entity.teleport.Teleport",
    "V3D": "org.joml.Vector3d",
    "R3F": "com.hypixel.hytale.math.vector.Rotation3f",
    "PAIR": "it.unimi.dsi.fastutil.Pair",
    "TRI": "com.hypixel.hytale.function.consumer.TriConsumer",
    "UUC": "com.hypixel.hytale.server.core.entity.UUIDComponent",
    "NPL": "com.hypixel.hytale.server.core.entity.nameplate.Nameplate",
    "DNC": "com.hypixel.hytale.server.core.modules.entity.component.DisplayNameComponent",
    "PDN": "com.hypixel.hytale.server.core.modules.entity.component.PersistentDisplayName",
    "ITB": "com.hypixel.hytale.server.core.modules.entity.component.Interactable",
    "ITS": "com.hypixel.hytale.server.core.modules.interaction.Interactions",
    "ITY": "com.hypixel.hytale.protocol.InteractionType",
    "UEPRE": "com.hypixel.hytale.server.core.event.events.ecs.UseEntityEvent$Pre",
    "EES": "com.hypixel.hytale.component.system.EntityEventSystem",
    "ARCH": "com.hypixel.hytale.component.Archetype",
    "EV": "com.hypixel.hytale.component.system.EcsEvent",
    "RSYS": "com.hypixel.hytale.component.system.RefSystem",
    "ADR": "com.hypixel.hytale.component.AddReason",
    "RR": "com.hypixel.hytale.component.RemoveReason",
    "DTH": "com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent",
    "DBG": "com.hypixel.hytale.server.npc.role.support.DebugSupport",
    "RDF": "com.hypixel.hytale.server.npc.role.RoleDebugFlags",
    "MES": "com.hypixel.hytale.server.npc.role.support.MarkedEntitySupport",
    "PTU": "com.hypixel.hytale.server.core.universe.world.ParticleUtil",
    "ANU": "com.hypixel.hytale.server.core.entity.AnimationUtils",
    "ASL": "com.hypixel.hytale.protocol.AnimationSlot",
}''')
rep('''assert any(s.startswith("(ILjava/lang/String;Lcom/hypixel/hytale/server/core/modules/entitystats/modifier/Modifier;)") for s in _sig(T["ESM"], "putModifier")), _sig(T["ESM"], "putModifier")
''', '''assert any(s.startswith("(ILjava/lang/String;Lcom/hypixel/hytale/server/core/modules/entitystats/modifier/Modifier;)") for s in _sig(T["ESM"], "putModifier")), _sig(T["ESM"], "putModifier")
# 0.2: every engine member the visible pets use (the probe-proven calls of SkyyPetProbe 0.1 + the SkyyMerchants 0.1 F path)
for c, m in ((T["NPCP"], "get"), (T["NPCP"], "getIndex"), (T["NPCP"], "spawnEntity"), (T["NPC"], "getRoleName"), (T["NPC"], "getComponentType"),
             (T["MDA"], "getAssetMap"), (T["MDL"], "createScaledModel"), (T["TC"], "getComponentType"), (T["TC"], "getPosition"),
             (T["TC"], "setPosition"), (T["TC"], "setRotation"), (T["TEL"], "createExact"), (T["TEL"], "getComponentType"), (T["R3F"], "setYaw"),
             (T["PAIR"], "first"), (T["UUC"], "getUuid"), (T["UUC"], "getComponentType"), (T["NPL"], "getComponentType"), (T["NPL"], "getText"),
             (T["DNC"], "getComponentType"), (T["PDN"], "getComponentType"), (T["ITB"], "getComponentType"), (T["ITB"], "INSTANCE"),
             (T["ITS"], "getComponentType"), (T["ITS"], "getInteractionId"), (T["ITS"], "setInteractionId"), (T["ITS"], "getInteractionHint"),
             (T["ITS"], "setInteractionHint"), (T["ITY"], "Use"), (T["UEPRE"], "getTargetEntity"), (T["UEPRE"], "setCancelled"),
             (T["UEPRE"], "isCancelled"), (T["ARCH"], "empty"), (T["RSYS"], "onEntityAdded"), (T["RSYS"], "onEntityRemove"), (T["ADR"], "LOAD"),
             (T["RR"], "REMOVE"), (T["RR"], "UNLOAD"), (T["DTH"], "getComponentType"), (T["DBG"], "getComponentType"), (T["DBG"], "getDebugFlags"),
             (T["DBG"], "setDebugFlags"), (T["MES"], "getComponentType"), (T["MES"], "setMarkedEntity"), (T["MES"], "getMarkedEntityRef"),
             (T["MES"], "DEFAULT_TARGET_SLOT"), (T["PTU"], "spawnParticleEffect"), (T["ANU"], "playAnimation"), (T["ASL"], "Action"),
             (T["CB"], "putComponent"), (T["CB"], "tryRemoveEntity"), (T["ST"], "removeEntity"), (T["ST"], "putComponent"), (T["REF"], "getStore"),
             (T["WLD"], "execute"), (T["WLD"], "getEntityStore"), (T["EST"], "getStore"), (T["EST"], "getRefFromUUID"), (T["PR"], "getReference"),
             (T["CAC"], "getComponent"), (T["CAC"], "putComponent"), ("com.hypixel.hytale.component.system.tick.EntityTickingSystem", "isParallel")):
    B.probe(pool, c, m)
assert "(Lcom/hypixel/hytale/component/Store;ILorg/joml/Vector3dc;Lcom/hypixel/hytale/math/vector/Rotation3fc;Lcom/hypixel/hytale/server/core/asset/type/model/config/Model;Lcom/hypixel/hytale/function/consumer/TriConsumer;Lcom/hypixel/hytale/function/consumer/TriConsumer;)Lit/unimi/dsi/fastutil/Pair;" in _sig(T["NPCP"], "spawnEntity"), _sig(T["NPCP"], "spawnEntity")
assert "(Ljava/lang/String;Lorg/joml/Vector3dc;Lcom/hypixel/hytale/component/ComponentAccessor;)V" in _sig(T["PTU"], "spawnParticleEffect")
assert "(Lcom/hypixel/hytale/component/Ref;Lcom/hypixel/hytale/protocol/AnimationSlot;Ljava/lang/String;Lcom/hypixel/hytale/component/ComponentAccessor;)V" in _sig(T["ANU"], "playAnimation")
assert "(Ljava/lang/String;Lcom/hypixel/hytale/component/Ref;)V" in _sig(T["MES"], "setMarkedEntity")
''')

# ================================================================================================ PetLook part 1 (no PetsCfg use) before PetsCfg
rep('''cfgc = cls("PetsCfg")
SCALARS = [''', r'''# =====================================================================================================================
# 0.2 PetLook (part 1): the built-in looks / babies / petting animations + the line parsers (PetsCfg.applyTables + the check hooks)
# =====================================================================================================================
lkc = cls("PetLook")
F(lkc, "public static final String[] LOOK_DEF = %s;" % jarr(["%s=%s/%s/%s" % (k, m, repr(float(sc)), mo) for k, m, sc, mo in LOOKS]))
F(lkc, "public static final String[] BABY_DEF = %s;" % jarr(["%s=%s/%s" % (k, m, repr(float(sc))) for k, m, sc in BABY_ROWS]))
F(lkc, "public static final String[] ANIM = %s;" % jarr(["%s=%s" % (m, a) for m, a in sorted(ANIMS.items())]))
F(lkc, "public static final String DEFAULT_ANIM = \"Alerted\";")
M(lkc, r"""
public static int motionOf(String s) {
  if (s == null) return -1;
  String t = s.trim().toLowerCase();
  if (t.equals("walk")) return 0;
  if (t.equals("fly")) return 1;
  if (t.equals("fish")) return 2;
  return -1;
}""")
M(lkc, r"""
public static String motionName(int m) {
  return m == 1 ? "fly" : (m == 2 ? "fish" : "walk");
}""")
M(lkc, r"""
public static boolean modelOk(String m) {
  if (m == null || m.length() == 0 || m.length() > 80) return false;
  for (int i = 0; i < m.length(); i++) {
    char c = m.charAt(i);
    if (!(c >= 'a' && c <= 'z') && !(c >= 'A' && c <= 'Z') && !(c >= '0' && c <= '9') && c != '_') return false;
  }
  return true;
}""")
M(lkc, r"""
public static float size(String s) {
  try { double d = Double.parseDouble(s.trim()); return d >= 0.1 && d <= 3.0 ? (float) d : -1.0f; } catch (Throwable t) { return -1.0f; }
}""")
# "Fox/0.8/walk" (file, sep /) or "Fox|0.8|walk" (the kit's columns) -> { model, size, motion } or null
M(lkc, r"""
public static String[] parse(String value, String sep) {
  if (value == null || sep == null) return null;
  String[] p = value.split(java.util.regex.Pattern.quote(sep), -1);
  if (p.length != 3) return null;
  String m = p[0].trim();
  if (!modelOk(m)) return null;
  float sc = size(p[1]);
  if (sc < 0.0f) return null;
  int mo = motionOf(p[2]);
  if (mo < 0) return null;
  return new String[] { m, String.valueOf(sc), motionName(mo) };
}""")
# "Chick/1.0" -> { model, size }; "-/1" or "none/1" = no baby look -> { "-", size }; null = bad
M(lkc, r"""
public static String[] parseBaby(String value, String sep) {
  if (value == null || sep == null) return null;
  String[] p = value.split(java.util.regex.Pattern.quote(sep), -1);
  if (p.length != 2) return null;
  String m = p[0].trim();
  float sc = size(p[1]);
  if (sc < 0.0f) return null;
  if (m.equals("-") || m.equalsIgnoreCase("none")) return new String[] { "-", String.valueOf(sc) };
  if (!modelOk(m)) return null;
  return new String[] { m, String.valueOf(sc) };
}""")
# case-insensitive "Key=value" lookup
M(lkc, r"""
public static String lookupCi(String[] pairs, String k) {
  if (k == null) return null;
  String t = k.trim();
  for (int i = 0; i < pairs.length; i++) {
    int e = pairs[i].indexOf('=');
    if (e > 0 && pairs[i].substring(0, e).equalsIgnoreCase(t)) return pairs[i].substring(e + 1);
  }
  return null;
}""")
# fix round: the built-in looks as text (/petadmin kinds) - the Pet looks / Baby looks tables start empty on a 0.1 config
M(lkc, r"""
public static String builtIn(String[] pairs) {
  StringBuilder sb = new StringBuilder();
  for (int i = 0; i < pairs.length; i++) {
    int e = pairs[i].indexOf('=');
    if (e <= 0) continue;
    if (sb.length() > 0) sb.append(", ");
    sb.append(pairs[i].substring(0, e)).append(' ').append(pairs[i].substring(e + 1).replace('/', ' '));
  }
  return sb.toString();
}""")

cfgc = cls("PetsCfg")
SCALARS = [''')

# ================================================================================================ Server Setup rows
rep('''     "SkyySkills skills the fallback reads. Use Combat.<class> rows; a bare Combat is skipped.", "POLL_SKILLS", "java.lang.String"),
]''', '''     "SkyySkills skills the fallback reads. Use Combat.<class> rows; a bare Combat is skipped.", "POLL_SKILLS", "java.lang.String"),
    # 0.2: pets in the world
    ("pets.visible", "Show pets in the world", "show", "bool", "true", "", "", "", "", "live",
     "Off = no pet creatures (buffs stay). Players hide their own in /settings.", "VISIBLE", "boolean"),
    ("pets.spawn.delay", "Pet appears after", "show", "int", "2", "0", "30", "", "s", "live",
     "Seconds after you join or arrive in a world.", "SPAWN_DELAY", "int"),
    ("pets.follow.distance", "Flying pet distance", "show", "dec", "2.5", "1", "8", "", "", "live",
     "Flying and fish pets circle you this many blocks away. Walking pets stop 3 blocks away.", "FOLLOW_DIST", "double"),
    ("pets.follow.teleport", "Teleport to you after", "show", "int", "20", "12", "64", "", "", "live",
     "A pet this far away for 2 s jumps back to you. Flying pets: at least circle + height + 4.", "TELE_DIST", "int"),
    ("pets.fly.height", "Flying pet height", "show", "dec", "1.8", "0.5", "6", "", "", "live,adv",
     "Blocks above your feet (fish pets 70% of it).", "FLY_HEIGHT", "double"),
    ("pets.fly.steer", "Flying pet movement", "show", "choice", "move", "", "", "move|Smooth,teleport|Small jumps", "", "live,adv",
     "Smooth = moved every tick. Small jumps = the teleport way (try it if flying pets stutter).", "FLY_STEER", "java.lang.String"),
    ("pets.babyUntil", "Baby look until level", "show", "int", "30", "1", "100", "", "", "live",
     "Pets with a baby look (Baby looks table) show it below this level.", "BABY_UNTIL", "int"),
    ("pets.mount.kinds", "Mount pets", "show", "text", MOUNT_KINDS, "1", "400", "", "", "live",
     "Kinds shown at mount size in the summon slot (riding comes later). Comma separated.", "MOUNT_KINDS", "java.lang.String"),
    ("pets.mount.scale", "Mount size in the summon slot", "show", "dec", "1", "0.3", "2", "", "x", "live",
     "1 = the vanilla size.", "MOUNT_SCALE", "double"),
    ("pets.worlds.blocked", "Worlds without pet creatures", "show", "text", "-", "1", "2000", "", "", "live",
     "World names, comma separated. - = none. Buffs still work there.", "BLOCKED", "java.lang.String"),
    ("pets.pet.cooldown", "Petting cooldown", "show", "int", "3", "1", "60", "", "s", "live",
     "F on your pet = hearts and a bond point, once per this many seconds.", "PET_COOLDOWN", "int"),
    ("pets.role.walk", "Walking pet role", "show", "text", ROLE_WALK, "1", "80", "", "", "live,adv",
     "NPC role of walking pets (SkyyPets' own).", "ROLE_WALK", "java.lang.String"),
    ("pets.role.fly", "Flying pet role", "show", "text", ROLE_FLY, "1", "80", "", "", "live,adv",
     "NPC role of flying and fish pets (SkyyPets' own).", "ROLE_FLY", "java.lang.String"),
]''')
rep('''     "Stats at Legendary Lv 100, e.g. str:20,cd:15. Keys: /petadmin kinds. Skill gets 100% pet XP.", "kind."),
]''', '''     "Stats at Legendary Lv 100, e.g. str:20,cd:15. Keys: /petadmin kinds. Skill gets 100% pet XP.", "kind."),
    ("pets.looks", "Pet looks", "look", "table", "", "0.1", "3", "text|dec|text;none;Model|Size|Motion", "", "live",
     "Model id, size (1 = vanilla), walk / fly / fish. No row = the built-in look (see /petadmin kinds).", "look."),
    ("pets.babies", "Baby looks", "look", "table", "", "0.1", "3", "text|dec;none;Baby model|Size", "", "live",
     "Shown below the baby level. Model - = no baby look. No row = the built-in one (/petadmin kinds).", "baby."),
]''')
rep('''_chk = {"pets.starter": "PetsCfg.checkStarter", "pets.kinds.off": "PetsCfg.checkList", "pets.worlds.noBuffs": "PetsCfg.checkList",
        "pets.xp.fallbackSkills": "PetsCfg.checkSkills"}''', '''_chk = {"pets.starter": "PetsCfg.checkStarter", "pets.kinds.off": "PetsCfg.checkList", "pets.worlds.noBuffs": "PetsCfg.checkList",
        "pets.xp.fallbackSkills": "PetsCfg.checkSkills", "pets.worlds.blocked": "PetsCfg.checkList", "pets.mount.kinds": "PetsCfg.checkList",
        "pets.role.walk": "PetsCfg.checkRole", "pets.role.fly": "PetsCfg.checkRole"}
_tchk = {"pets.kinds": "PetsCfg.checkKind", "pets.looks": "PetsCfg.checkLook", "pets.babies": "PetsCfg.checkBaby"}''')
rep('''CFG_ROWS += [r[:11] + ("reload@%s:%s;sep=/;check=PetsCfg.checkKind" % (CFG_FILE, r[11]),) for r in TABLES]
CFG_CATS = [("pets", "Pets"), ("xp", "Pet XP"), ("rarity", "Rarity"), ("kinds", "Pet kinds")]
CFG_NOTE = "Chat: /pets (players), /petadmin give | take | unlock | lock | list | restore | xp | kinds (admins)."''',
    '''CFG_ROWS += [r[:11] + ("reload@%s:%s;sep=/;check=%s" % (CFG_FILE, r[11], _tchk[r[0]]),) for r in TABLES]
CFG_CATS = [("pets", "Pets"), ("show", "Pets in the world"), ("look", "Pet looks"), ("xp", "Pet XP"), ("rarity", "Rarity"),
            ("kinds", "Pet kinds")]
CFG_NOTE = "Chat: /pets, /settings Show my pets (players); /petadmin give | take | ... | kinds | sweep (admins)."''')
rep('''for _k in KINDS:
    _d.append("kind.%s=%s/%s/%s" % (_k[0], _k[1], _k[2], _k[3]))
_d.append("")''', '''for _k in KINDS:
    _d.append("kind.%s=%s/%s/%s" % (_k[0], _k[1], _k[2], _k[3]))
_d += ["", "# Pet looks: look.<Kind>=Model/Size/walk, fly or fish (size 1 = the vanilla size). A kind without a line uses the built-in look."]
for _k, _m, _sc, _mo in LOOKS:
    _d.append("look.%s=%s/%s/%s" % (_k, _m, repr(float(_sc)), _mo))
_d += ["", "# Baby looks (below pets.babyUntil): baby.<Kind>=Model/Size (Model - = no baby look). No line = the built-in one."]
for _k, _m, _sc in BABY_ROWS:
    _d.append("baby.%s=%s/%s" % (_k, _m, repr(float(_sc))))
_d.append("")''')

# ================================================================================================ PetsCfg: maps, steering choice, tables, checks
rep('''F(cfgc, "public static volatile @PKG@.PetKind[] KINDS = new @PKG@.PetKind[0];")''',
    '''F(cfgc, "public static volatile @PKG@.PetKind[] KINDS = new @PKG@.PetKind[0];")
F(cfgc, "public static volatile java.util.Map LOOKS = java.util.Collections.EMPTY_MAP;")
F(cfgc, "public static volatile java.util.Map BABIES = java.util.Collections.EMPTY_MAP;")''')
rep('''_ap.append('  if (!SLOT2_MODE.equals("quest") && !SLOT2_MODE.equals("always") && !SLOT2_MODE.equals("off")) SLOT2_MODE = "quest";')''',
    '''_ap.append('  if (!SLOT2_MODE.equals("quest") && !SLOT2_MODE.equals("always") && !SLOT2_MODE.equals("off")) SLOT2_MODE = "quest";')
_ap.append('  if (!FLY_STEER.equals("move") && !FLY_STEER.equals("teleport")) FLY_STEER = "move";')''')
rep(r'''M(cfgc, r"""
public static void applyTables(java.util.Properties p) {
  java.util.ArrayList ks = new java.util.ArrayList();
  if (p != null) {
    java.util.ArrayList keys = new java.util.ArrayList(p.stringPropertyNames());
    java.util.Collections.sort(keys);
    for (int i = 0; i < keys.size(); i++) {
      String k = (String) keys.get(i);
      if (!k.startsWith("kind.")) continue;''', r'''M(cfgc, r"""
public static void applyTables(java.util.Properties p) {
  java.util.ArrayList ks = new java.util.ArrayList();
  java.util.HashMap looks = new java.util.HashMap();
  java.util.HashMap babies = new java.util.HashMap();
  if (p != null) {
    java.util.ArrayList keys = new java.util.ArrayList(p.stringPropertyNames());
    java.util.Collections.sort(keys);
    for (int i = 0; i < keys.size(); i++) {
      String k = (String) keys.get(i);
      if (k.startsWith("look.") && k.length() > 5) {
        String[] lv = @PKG@.PetLook.parse(p.getProperty(k), "/");
        if (lv == null) { @PKG@.PetsLog.warnOnce("look:" + k + "=" + p.getProperty(k), k + "=" + p.getProperty(k) + " is not 'Model/Size/walk|fly|fish' - that kind uses its built-in look until it is fixed"); continue; }
        looks.put(k.substring(5).trim().toLowerCase(), lv);
        continue;
      }
      if (k.startsWith("baby.") && k.length() > 5) {
        String[] bv = @PKG@.PetLook.parseBaby(p.getProperty(k), "/");
        if (bv == null) { @PKG@.PetsLog.warnOnce("baby:" + k + "=" + p.getProperty(k), k + "=" + p.getProperty(k) + " is not 'Model/Size' - that kind uses its built-in baby look until it is fixed"); continue; }
        babies.put(k.substring(5).trim().toLowerCase(), bv);
        continue;
      }
      if (!k.startsWith("kind.")) continue;''')
rep('''  @PKG@.PetKind[] a = new @PKG@.PetKind[ks.size()];
  for (int i = 0; i < a.length; i++) a[i] = (@PKG@.PetKind) ks.get(i);
  KINDS = a;
}""")''', '''  @PKG@.PetKind[] a = new @PKG@.PetKind[ks.size()];
  for (int i = 0; i < a.length; i++) a[i] = (@PKG@.PetKind) ks.get(i);
  KINDS = a;
  LOOKS = java.util.Collections.unmodifiableMap(looks);
  BABIES = java.util.Collections.unmodifiableMap(babies);
}""")''')
rep('''M(cfgc, r"""
public static String checkSkills(String key, String value) {''', '''M(cfgc, r"""
public static String checkLook(String key, String value) {
  if (value == null) return null;
  if (value.indexOf('/') >= 0) return "No / in a look line.";
  if (@PKG@.PetLook.parse(value, "|") == null) return "Use Model | Size | walk, fly or fish - e.g. Fox | 0.8 | walk (size 0.1 - 3, a vanilla model id).";
  return null;
}""")
M(cfgc, r"""
public static String checkBaby(String key, String value) {
  if (value == null) return null;
  if (value.indexOf('/') >= 0) return "No / in a baby line.";
  if (@PKG@.PetLook.parseBaby(value, "|") == null) return "Use Baby model | Size - e.g. Chick | 1 (size 0.1 - 3), or - | 1 for no baby look.";
  return null;
}""")
M(cfgc, r"""
public static String checkRole(String key, String value) {
  if (value == null) return null;
  if (!@PKG@.PetLook.modelOk(value.trim())) return "An NPC role id: letters, digits and _ only.";
  return null;
}""")
M(cfgc, r"""
public static String checkSkills(String key, String value) {''')

# ================================================================================================ PetLook part 2 (uses PetsCfg) + the views
VIEWS = r'''
# =====================================================================================================================
# 0.2 PetLook (part 2): which model / size / motion a pet shows (look row or built-in; baby below pets.babyUntil; mounts in slot 2)
# =====================================================================================================================
M(lkc, r"""
public static String[] look(String kind) {
  if (kind == null) return null;
  Object o = @PKG@.PetsCfg.LOOKS.get(kind.trim().toLowerCase());
  if (o instanceof String[]) return (String[]) o;
  String d = lookupCi(LOOK_DEF, kind);
  if (d != null) return parse(d, "/");
  String m = @PKG@.PetKind.lookup(@PKG@.PetKind.MODEL_IDS, kind.trim(), null);
  if (m == null) { @PKG@.PetKind pk = @PKG@.PetsCfg.kind(kind); m = pk == null || pk.model.length() == 0 ? null : pk.model; }
  if (m == null) return null;
  return new String[] { m, "1.0", "walk" };
}""")
M(lkc, r"""
public static String[] baby(String kind) {
  if (kind == null) return null;
  Object o = @PKG@.PetsCfg.BABIES.get(kind.trim().toLowerCase());
  String[] b = null;
  if (o instanceof String[]) b = (String[]) o;
  if (b == null) { String d = lookupCi(BABY_DEF, kind); if (d != null) b = parseBaby(d, "/"); }
  if (b == null || b[0].equals("-")) return null;
  return b;
}""")
M(lkc, r"""
public static boolean mount(String kind) {
  return kind != null && @PKG@.PetsCfg.listed(@PKG@.PetsCfg.MOUNT_KINDS, kind);
}""")
# { String model, Float size, Integer motion (0 walk / 1 fly / 2 fish), Boolean baby } or null (no model for that kind)
M(lkc, r"""
public static Object[] resolve(String kind, int level, int slot) {
  String[] l = look(kind);
  if (l == null) return null;
  int mo = motionOf(l[2]);
  if (mo < 0) mo = 0;
  String model = l[0];
  float sc = size(l[1]);
  if (sc < 0.0f) sc = 1.0f;
  boolean bb = false;
  String[] b = null;
  boolean mt = slot == 2 && mount(kind);
  if (level < @PKG@.PetsCfg.BABY_UNTIL && !mt) b = baby(kind);
  if (b != null) { model = b[0]; sc = size(b[1]); if (sc < 0.0f) sc = 1.0f; bb = true; }
  else if (mt) sc = (float) @PKG@.PetsCfg.MOUNT_SCALE;
  return new Object[] { model, Float.valueOf(sc), Integer.valueOf(mo), Boolean.valueOf(bb) };
}""")
M(lkc, r"""
public static String anim(String model) {
  return @PKG@.PetKind.lookup(ANIM, model, DEFAULT_ANIM);
}""")

# =====================================================================================================================
# 0.2 PetView: one pet creature (a throwaway view of the record - it holds no saved data)
# =====================================================================================================================
pvc = cls("PetView")
for _f in ("String uuid", "java.util.UUID owner", "String key", "int slot", "String petId", "String kind", "String model", "float scale",
           "int motion", "String spec", "String world", "@WLD@ w", "@REF@ ref", "String role", "long born", "double ang", "double ph",
           "double px", "double py", "double pz", "boolean hasPos", "int far", "double farT", "long joy", "long lastPet", "boolean gone", "String plate",
           "String why"):
    F(pvc, "public %s;" % _f)
C(pvc, 'public PetView() { this.uuid = ""; this.key = ""; this.petId = ""; this.kind = ""; this.model = ""; this.spec = ""; this.world = ""; this.role = ""; this.plate = ""; this.why = ""; }')

# =====================================================================================================================
# 0.2 PetFly: OUR fly-follow for flying + fish pets (pure maths; Skyy: "flying ones just fly around, they dont follow me")
# =====================================================================================================================
pfc = cls("PetFly")
M(pfc, r"""
public static double dist(double ax, double ay, double az, double bx, double by, double bz) {
  double dx = ax - bx; double dy = ay - by; double dz = az - bz;
  return Math.sqrt(dx * dx + dy * dy + dz * dz);
}""")
# the yaw (radians) that faces (dx, dz): yaw 0 faces -z (SkyyPetProbe PpLogic.yawToward)
M(pfc, r"""
public static float yaw(double dx, double dz) {
  if (dx == 0.0 && dz == 0.0) return 0.0f;
  return (float) Math.atan2(-dx, -dz);
}""")
M(pfc, r"""
public static double radius(int motion) {
  double r = @PKG@.PetsCfg.FOLLOW_DIST;
  return motion == 2 ? r * 0.8 : r;
}""")
M(pfc, r"""
public static double height(int motion, boolean joy) {
  double h = @PKG@.PetsCfg.FLY_HEIGHT;
  if (motion == 2) h = h * 0.7;
  return joy ? h + 0.6 : h;
}""")
M(pfc, r"""
public static double angSpeed(int motion, boolean joy) {
  double w = motion == 2 ? 0.5 : 0.8;
  return joy ? w * 4.0 : w;
}""")
M(pfc, r"""
public static double bob(int motion, double ph) {
  return Math.sin(ph) * (motion == 2 ? 0.15 : 0.25);
}""")
M(pfc, r"""
public static double[] orbit(double ox, double oy, double oz, double ang, double r, double h, double b) {
  return new double[] { ox + Math.cos(ang) * r, oy + h + b, oz + Math.sin(ang) * r };
}""")
# catch-up speed: faster the further behind (8 .. 30 blocks / s)
M(pfc, r"""
public static double speedFor(double d) {
  double v = 8.0 + d * 2.0;
  return v > 30.0 ? 30.0 : v;
}""")
# one smooth step from c toward t: a quarter of the way per 1/16 s, never faster than max blocks / s
M(pfc, r"""
public static double[] step(double cx, double cy, double cz, double tx, double ty, double tz, double dt, double max) {
  double dx = tx - cx; double dy = ty - cy; double dz = tz - cz;
  double d = Math.sqrt(dx * dx + dy * dy + dz * dz);
  if (d < 1.0E-6 || !(dt > 0.0)) return new double[] { cx, cy, cz };
  double k = dt * 4.0;
  if (k > 1.0) k = 1.0;
  double mv = d * k;
  double cap = max * dt;
  if (mv > cap) mv = cap;
  return new double[] { cx + dx / d * mv, cy + dy / d * mv, cz + dz / d * mv };
}""")
# a flying pet's teleport distance: the setting, but never inside its own circle (distance + height + 4)
M(pfc, r"""
public static double teleLimit(int motion) {
  double lim = (double) @PKG@.PetsCfg.TELE_DIST;
  double lo = radius(motion) + height(motion, true) + 4.0;
  return lim < lo ? lo : lim;
}""")
# one tick of one flying pet around the owner at (ox, oy, oz): { x, y, z, yaw, 1 = jump there (first sight / too far) }
M(pfc, r"""
public static double[] tick(@PKG@.PetView v, double ox, double oy, double oz, double dt, long now) {
  boolean joy = now < v.joy;
  if (dt > 0.25) dt = 0.25;
  if (dt < 0.0) dt = 0.0;
  v.ang = v.ang + angSpeed(v.motion, joy) * dt;
  if (v.ang > Math.PI * 2.0) v.ang = v.ang - Math.PI * 2.0;
  v.ph = v.ph + dt * (v.motion == 2 ? 1.6 : 2.4);
  if (v.ph > Math.PI * 2.0) v.ph = v.ph - Math.PI * 2.0;
  double[] t = orbit(ox, oy, oz, v.ang, radius(v.motion), height(v.motion, joy), bob(v.motion, v.ph));
  boolean jump = !v.hasPos;
  if (!jump) {
    if (dist(v.px, v.py, v.pz, ox, oy, oz) > teleLimit(v.motion)) { v.farT = v.farT + dt; if (v.farT >= 2.0) jump = true; }
    else v.farT = 0.0;
  }
  if (jump) {
    v.px = t[0]; v.py = t[1]; v.pz = t[2]; v.hasPos = true; v.farT = 0.0;
    return new double[] { t[0], t[1], t[2], (double) yaw(ox - t[0], oz - t[2]), 1.0 };
  }
  double[] n = step(v.px, v.py, v.pz, t[0], t[1], t[2], dt, speedFor(dist(v.px, v.py, v.pz, t[0], t[1], t[2])));
  double mx = n[0] - v.px; double mz = n[2] - v.pz;
  float y = (mx * mx + mz * mz) > 1.0E-6 ? yaw(mx, mz) : yaw(ox - n[0], oz - n[2]);
  v.px = n[0]; v.py = n[1]; v.pz = n[2];
  return new double[] { n[0], n[1], n[2], (double) y, 0.0 };
}""")

# =====================================================================================================================
# 0.2 PetWorldApi + PetWorld: the engine seam (API == null in game = the real calls, each copied from the probe / the merchants)
# =====================================================================================================================
pwa = pool.makeInterface(PKG + ".PetWorldApi")
ALL.append(pwa)
for sig in ("public abstract int roleIndex(String role);",
            "public abstract Object model(String id, float scale);",
            "public abstract @REF@ spawn(@ST@ st, int role, double x, double y, double z, float yaw, Object model);",
            "public abstract @ST@ store(@WLD@ w);",
            "public abstract @REF@ ownerRef(java.util.UUID u);",
            "public abstract @REF@ refOf(@WLD@ w, java.util.UUID u);",
            "public abstract boolean execute(@WLD@ w, Runnable r);",
            "public abstract double[] pos(@CAC@ acc, @REF@ r);",
            "public abstract void setPos(@CAC@ acc, @REF@ r, double x, double y, double z, float yaw);",
            "public abstract void teleport(@CAC@ acc, @REF@ r, double x, double y, double z, float yaw);",
            "public abstract boolean dead(@CAC@ acc, @REF@ r);",
            "public abstract java.util.UUID uuid(@CAC@ acc, @REF@ r);",
            "public abstract String roleOf(@CAC@ acc, @REF@ r);",
            "public abstract String tags(@CAC@ acc, @REF@ r);",
            "public abstract void prepare(@CAC@ acc, @REF@ r, String plate);",
            "public abstract void plate(@CAC@ acc, @REF@ r, String plate);",
            "public abstract void clearDebug(@CAC@ acc, @REF@ r);",
            "public abstract void mark(@CAC@ acc, @REF@ r, @REF@ owner);",
            "public abstract boolean remove(@CAC@ acc, @REF@ r);",
            "public abstract void hearts(@CAC@ acc, double x, double y, double z);",
            "public abstract void anim(@CAC@ acc, @REF@ r, String anim);"):
    M(pwa, sig)
pwc = cls("PetWorld")
F(pwc, "public static volatile @PKG@.PetWorldApi API = null;")
F(pwc, "public static final String HINT = %s;" % jstr(PET_HINT))
F(pwc, "public static final String USE_ROOT = %s;" % jstr(USE_ROOT))
F(pwc, "public static final String HEARTS = %s;" % jstr(HEARTS))
M(pwc, r"""
public static int roleIndex(String role) {
  if (API != null) return API.roleIndex(role);
  try { return @NPCP@.get().getIndex(role); } catch (Throwable t) { return -1; }
}""")
M(pwc, r"""
public static Object model(String id, float scale) {
  if (API != null) return API.model(id, scale);
  try {
    Object a = @MDA@.getAssetMap().getAsset(id);
    if (!(a instanceof @MDA@)) return null;
    return @MDL@.createScaledModel((@MDA@) a, scale);
  } catch (Throwable t) { return null; }
}""")
# NPCPlugin.spawnEntity 7-argument form (both consumers null - NPCPlugin null-checks them), the probe's PpEng.spawn
M(pwc, r"""
public static @REF@ spawn(@ST@ st, int role, double x, double y, double z, float yaw, Object model) {
  if (API != null) return API.spawn(st, role, x, y, z, yaw, model);
  @R3F@ rot = new @R3F@();
  rot.setYaw(yaw);
  @PAIR@ p = @NPCP@.get().spawnEntity(st, role, new @V3D@(x, y, z), rot, (@MDL@) model, (@TRI@) null, (@TRI@) null);
  return p == null ? null : (@REF@) p.first();
}""")
M(pwc, r"""
public static @ST@ store(@WLD@ w) {
  if (API != null) return API.store(w);
  try { return w == null ? null : w.getEntityStore().getStore(); } catch (Throwable t) { return null; }
}""")
M(pwc, r"""
public static @REF@ ownerRef(java.util.UUID u) {
  if (API != null) return API.ownerRef(u);
  try { @PR@ pr = @UNI@.get().getPlayer(u); return pr == null ? null : pr.getReference(); } catch (Throwable t) { return null; }
}""")
M(pwc, r"""
public static @REF@ refOf(@WLD@ w, java.util.UUID u) {
  if (API != null) return API.refOf(w, u);
  try { return w == null || u == null ? null : w.getEntityStore().getRefFromUUID(u); } catch (Throwable t) { return null; }
}""")
M(pwc, r"""
public static boolean execute(@WLD@ w, Runnable r) {
  if (API != null) return API.execute(w, r);
  if (w == null || r == null) return false;
  try { w.execute(r); return true; } catch (Throwable t) { return false; }
}""")
M(pwc, r"""
public static double[] pos(@CAC@ acc, @REF@ r) {
  if (API != null) return API.pos(acc, r);
  try {
    if (acc == null || r == null || !r.isValid()) return null;
    @TC@ tc = (@TC@) acc.getComponent(r, @TC@.getComponentType());
    if (tc == null) return null;
    @V3D@ p = tc.getPosition();
    return new double[] { p.x, p.y, p.z };
  } catch (Throwable t) { return null; }
}""")
# move one tick (the way GamePacketHandler.handleMountMovement moves a ridden NPC: TransformComponent.setPosition)
M(pwc, r"""
public static void setPos(@CAC@ acc, @REF@ r, double x, double y, double z, float yaw) {
  if (API != null) { API.setPos(acc, r, x, y, z, yaw); return; }
  @TC@ tc = (@TC@) acc.getComponent(r, @TC@.getComponentType());
  if (tc == null) return;
  tc.setPosition(new @V3D@(x, y, z));
  @R3F@ rot = new @R3F@();
  rot.setYaw(yaw);
  tc.setRotation(rot);
}""")
# the vanilla BodyMotionTeleport way (the probe's PpFollow.teleport)
M(pwc, r"""
public static void teleport(@CAC@ acc, @REF@ r, double x, double y, double z, float yaw) {
  if (API != null) { API.teleport(acc, r, x, y, z, yaw); return; }
  @R3F@ rot = new @R3F@();
  rot.setYaw(yaw);
  acc.putComponent(r, @TEL@.getComponentType(), @TEL@.createExact(new @V3D@(x, y, z), rot));
}""")
M(pwc, r"""
public static boolean dead(@CAC@ acc, @REF@ r) {
  if (API != null) return API.dead(acc, r);
  try { return acc != null && r != null && acc.getComponent(r, @DTH@.getComponentType()) != null; } catch (Throwable t) { return false; }
}""")
M(pwc, r"""
public static java.util.UUID uuid(@CAC@ acc, @REF@ r) {
  if (API != null) return API.uuid(acc, r);
  try {
    if (acc == null || r == null) return null;
    @UUC@ u = (@UUC@) acc.getComponent(r, @UUC@.getComponentType());
    return u == null ? null : u.getUuid();
  } catch (Throwable t) { return null; }
}""")
M(pwc, r"""
public static String roleOf(@CAC@ acc, @REF@ r) {
  if (API != null) return API.roleOf(acc, r);
  try {
    Object e = acc.getComponent(r, @NPC@.getComponentType());
    return e instanceof @NPC@ ? ((@NPC@) e).getRoleName() : null;
  } catch (Throwable t) { return null; }
}""")
# fix round (ghost sweep): our marks on a creature = "<nameplate text> NEWLINE <interaction hint>" ("" for a missing one); null = unreadable
M(pwc, r"""
public static String tags(@CAC@ acc, @REF@ r) {
  if (API != null) return API.tags(acc, r);
  try {
    if (acc == null || r == null) return null;
    @NPL@ n = (@NPL@) acc.getComponent(r, @NPL@.getComponentType());
    @ITS@ its = (@ITS@) acc.getComponent(r, @ITS@.getComponentType());
    String p = n == null ? null : n.getText();
    String h = its == null ? null : its.getInteractionHint();
    return (p == null ? "" : p) + "\n" + (h == null ? "" : h);
  } catch (Throwable t) { return null; }
}""")
# the name over its head (Nameplate + DisplayName + PersistentDisplayName, the vanilla EntityNameplateCommand set)
M(pwc, r"""
public static void plate(@CAC@ acc, @REF@ r, String text) {
  if (API != null) { API.plate(acc, r, text); return; }
  @MSG@ m = @MSG@.raw(text);
  acc.putComponent(r, @DNC@.getComponentType(), new @DNC@(m));
  acc.putComponent(r, @PDN@.getComponentType(), new @PDN@(m));
  acc.putComponent(r, @NPL@.getComponentType(), new @NPL@(text));
}""")
# + F works (Interactable + the Use root + the vanilla "Press [F] to pet" hint) - the SkyyMerchants 0.1 MerchEng.prepare path
M(pwc, r"""
public static void prepare(@CAC@ acc, @REF@ r, String text) {
  if (API != null) { API.prepare(acc, r, text); return; }
  plate(acc, r, text);
  if (acc.getComponent(r, @ITB@.getComponentType()) == null) acc.putComponent(r, @ITB@.getComponentType(), @ITB@.INSTANCE);
  @ITS@ its = (@ITS@) acc.getComponent(r, @ITS@.getComponentType());
  if (its == null) { its = new @ITS@(); acc.putComponent(r, @ITS@.getComponentType(), its); }
  if (its.getInteractionId(@ITY@.Use) == null) its.setInteractionId(@ITY@.Use, USE_ROOT);
  if (its.getInteractionHint() == null || !HINT.equals(its.getInteractionHint())) its.setInteractionHint(HINT);
}""")
# no debug nameplate ("Idle.Default"): only a role with a Debug field sets flags (the vanilla fallback role Test_Pet)
M(pwc, r"""
public static void clearDebug(@CAC@ acc, @REF@ r) {
  if (API != null) { API.clearDebug(acc, r); return; }
  try {
    @DBG@ d = (@DBG@) acc.getComponent(r, @DBG@.getComponentType());
    if (d != null && d.getDebugFlags() != null && !d.getDebugFlags().isEmpty()) d.setDebugFlags(java.util.EnumSet.noneOf(@RDF@.class));
  } catch (Throwable t) { }
}""")
# the owner = the walking pet's locked target (its Player sensor locks on; Test_Pet's Teleport body motion goes to that target)
M(pwc, r"""
public static void mark(@CAC@ acc, @REF@ r, @REF@ owner) {
  if (API != null) { API.mark(acc, r, owner); return; }
  try {
    @MES@ m = (@MES@) acc.getComponent(r, @MES@.getComponentType());
    if (m == null || owner == null) return;
    @REF@ cur = m.getMarkedEntityRef(@MES@.DEFAULT_TARGET_SLOT);
    if (cur == null || !cur.equals(owner)) m.setMarkedEntity(@MES@.DEFAULT_TARGET_SLOT, owner);
  } catch (Throwable t) { }
}""")
M(pwc, r"""
public static boolean remove(@CAC@ acc, @REF@ r) {
  if (API != null) return API.remove(acc, r);
  if (acc == null || r == null || !r.isValid()) return false;
  if (acc instanceof @CB@) { ((@CB@) acc).tryRemoveEntity(r, @RR@.REMOVE); return true; }
  if (acc instanceof @ST@) { ((@ST@) acc).removeEntity(r, @RR@.REMOVE); return true; }
  return false;
}""")
M(pwc, r"""
public static void hearts(@CAC@ acc, double x, double y, double z) {
  if (API != null) { API.hearts(acc, x, y, z); return; }
  try { @PTU@.spawnParticleEffect(HEARTS, new @V3D@(x, y, z), acc); } catch (Throwable t) { }
}""")
M(pwc, r"""
public static void anim(@CAC@ acc, @REF@ r, String anim) {
  if (API != null) { API.anim(acc, r, anim); return; }
  try { @ANU@.playAnimation(r, @ASL@.Action, anim, acc); } catch (Throwable t) { }
}""")

# =====================================================================================================================
# 0.2 the world-thread jobs (fields + constructors now; run() after PetViews)
# =====================================================================================================================
sjc = cls("PetSpawnJob")
sjc.addInterface(pool.get("java.lang.Runnable"))
for _f in ("java.util.UUID u", "int slot", "String want", "@WLD@ w", "String wn", "String res"):
    F(sjc, "public %s;" % _f)
C(sjc, "public PetSpawnJob(java.util.UUID u, int slot, String want, @WLD@ w, String wn) { this.u = u; this.slot = slot; this.want = want; this.w = w; this.wn = wn; this.res = \"\"; }")
rjc = cls("PetRemoveJob")
rjc.addInterface(pool.get("java.lang.Runnable"))
F(rjc, "public @PKG@.PetView v;")
F(rjc, "public boolean done;")
C(rjc, "public PetRemoveJob(@PKG@.PetView v) { this.v = v; }")
pjc = cls("PetPetJob")
pjc.addInterface(pool.get("java.lang.Runnable"))
F(pjc, "public @PKG@.PetView v;")
C(pjc, "public PetPetJob(@PKG@.PetView v) { this.v = v; }")

# =====================================================================================================================
# 0.2 PetViews: the pet creatures - want / spawn / follow / fly / lifecycle / ghost sweep / petting (world threads)
# =====================================================================================================================
pvs = cls("PetViews")
F(pvs, "public static final java.util.concurrent.ConcurrentHashMap LIVE = new java.util.concurrent.ConcurrentHashMap();")     # entity uuid -> PetView
F(pvs, "public static final java.util.concurrent.ConcurrentHashMap OWN = new java.util.concurrent.ConcurrentHashMap();")      # owner -> Object[3] (slot 1, 2)
F(pvs, "public static final java.util.concurrent.ConcurrentHashMap PENDING = new java.util.concurrent.ConcurrentHashMap();")  # owner|slot -> Long (spawn queued)
F(pvs, "public static final java.util.concurrent.ConcurrentHashMap SEEN = new java.util.concurrent.ConcurrentHashMap();")     # owner -> { world, Long since }
F(pvs, "public static final java.util.concurrent.ConcurrentHashMap DROPPED = new java.util.concurrent.ConcurrentHashMap();")  # entity uuid -> world (lost track)
for _c in ("SPAWNED", "REMOVED", "SWEPT", "LOST", "PETTED", "TELEPORTS", "STEPS", "FALLBACKS", "REATTACHED", "GONE_BY_GAME"):
    F(pvs, "public static final java.util.concurrent.atomic.AtomicLong %s = new java.util.concurrent.atomic.AtomicLong();" % _c)
F(pvs, "public static final String SETTING = \"pets.show\";")
F(pvs, "public static final String ROLE_PREFIX = %s;" % jstr(ROLE_PREFIX))
F(pvs, "public static final String[] LINES = %s;" % jarr(["It looks very happy!", "It loves it!", "It wiggles happily!", "It nuzzles your hand."]))
# the /settings switch (research/Settings-Spec.md 1.3 adopter helper; no SkyyMenu = on)
M(pvs, r"""
public static void regSetting() {
  try {
    Object[] a = new Object[] { "SkyyPets", SETTING, "Show my pets", "general", Boolean.TRUE, "Your pets walk or fly with you. Off = hidden (their buffs stay)." };
    java.util.Map br = @PKG@.PetsLog.bridge();
    br.put("settings:def:" + SETTING, a);
    Object f = br.get("settings:fn:register");
    if (f instanceof java.util.function.Function) ((java.util.function.Function) f).apply(a);
  } catch (Throwable t) { }
}""")
M(pvs, r"""
public static boolean showOn(java.util.UUID u) {
  if (u == null) return true;
  try {
    Object f = @PKG@.PetsLog.bridge().get("settings:fn:get");
    if (f instanceof java.util.function.Function) {
      Object r = ((java.util.function.Function) f).apply(new Object[] { u, SETTING });
      if (r instanceof Boolean) return ((Boolean) r).booleanValue();
    }
  } catch (Throwable t) { }
  return true;
}""")
M(pvs, r"""
public static @PKG@.PetView view(java.util.UUID u, int slot) {
  if (u == null || slot < 1 || slot > 2) return null;
  Object o = OWN.get(u);
  if (!(o instanceof Object[])) return null;
  Object v = ((Object[]) o)[slot];
  return v instanceof @PKG@.PetView ? (@PKG@.PetView) v : null;
}""")
M(pvs, r"""
public static void register(@PKG@.PetView v) {
  LIVE.put(v.uuid, v);
  Object o = OWN.get(v.owner);
  Object[] a = null;
  if (o instanceof Object[]) a = (Object[]) o;
  if (a == null) {
    a = new Object[3];
    Object prev = OWN.putIfAbsent(v.owner, a);
    if (prev instanceof Object[]) a = (Object[]) prev;
  }
  a[v.slot] = v;
}""")
M(pvs, r"""
public static void unview(@PKG@.PetView v) {
  if (v == null || v.owner == null) return;
  Object o = OWN.get(v.owner);
  if (o instanceof Object[] && ((Object[]) o)[v.slot] == v) ((Object[]) o)[v.slot] = null;
}""")
# we lost track of it (not loaded when it had to go): its uuid waits in DROPPED - the ghost sweep removes it the moment its chunk loads
M(pvs, r"""
public static void dropped(@PKG@.PetView v, String why) {
  if (v == null) return;
  v.gone = true;
  if (why != null) v.why = why;
  unview(v);
  LIVE.remove(v.uuid);
  if (v.uuid.length() > 0) {
    if (DROPPED.size() > 5000) DROPPED.clear();
    DROPPED.put(v.uuid, v.world == null ? "" : v.world);
  }
  LOST.incrementAndGet();
}""")
M(pvs, r"""
public static String plate(@PKG@.PetRec r, String id) {
  String n = r.get("pet." + id + ".name");
  String nm = null;
  if (n != null && n.trim().length() > 0) nm = @PKG@.PetsLog.clean(n.trim());
  if (nm != null && nm.length() > 24) nm = nm.substring(0, 24);
  if (nm == null) { @PKG@.PetKind pk = @PKG@.PetsCfg.kind(r.kindOf(id)); nm = pk == null ? @PKG@.PetKind.display(r.kindOf(id)) : pk.name; }
  return nm + " (Lv " + r.levelOf(id) + ")";
}""")
# the creature this slot should show right now: "key|slot|petId|model|size|motion" or null (nothing)
M(pvs, r"""
public static String want(java.util.UUID u, @PKG@.PetRec r, String key, int slot, String wn, boolean dead) {
  if (!@PKG@.PetsCfg.ON || !@PKG@.PetsCfg.VISIBLE || r == null || r.bad || dead || u == null) return null;
  if (wn != null && @PKG@.PetsCfg.listed(@PKG@.PetsCfg.BLOCKED, wn)) return null;
  if (!showOn(u)) return null;
  if (slot == 1) { String sh = r.get("shown.1"); if (sh != null && sh.trim().equalsIgnoreCase("false")) return null; }
  if (slot == 2 && !@PKG@.PetBuff.slot2Open(r)) return null;
  String id = r.active(slot);
  if (id.length() == 0) return null;
  String k = r.kindOf(id);
  if (!@PKG@.PetsCfg.kindOn(k)) return null;
  Object[] lk = @PKG@.PetLook.resolve(k, r.levelOf(id), slot);
  if (lk == null) return null;
  return key + "|" + slot + "|" + id + "|" + lk[0] + "|" + lk[1] + "|" + lk[2];
}""")
# world arrival clock (pets.spawn.delay after join / a world change)
M(pvs, r"""
public static void seen(java.util.UUID u, String wn, long now) {
  String w = wn == null ? "" : wn;
  Object o = SEEN.get(u);
  if (o instanceof Object[] && w.equals(((Object[]) o)[0])) return;
  SEEN.put(u, new Object[] { w, Long.valueOf(now) });
}""")
M(pvs, r"""
public static boolean ready(java.util.UUID u, long now) {
  Object o = SEEN.get(u);
  if (!(o instanceof Object[])) return false;
  return now - ((Long) ((Object[]) o)[1]).longValue() >= (long) @PKG@.PetsCfg.SPAWN_DELAY * 1000L;
}""")
# remove inside a ticking system (the CommandBuffer); not loaded -> dropped
M(pvs, r"""
public static boolean removeHere(@CB@ cb, @PKG@.PetView v, String why) {
  if (v == null || v.gone) return false;
  v.gone = true;
  v.why = why;
  unview(v);
  boolean ok = false;
  try { ok = v.ref != null && v.ref.isValid() && @PKG@.PetWorld.remove(cb, v.ref); } catch (Throwable t) { ok = false; }
  if (ok) { LIVE.remove(v.uuid); REMOVED.incrementAndGet(); return true; }
  dropped(v, why + " (not loaded)");
  return false;
}""")
# remove on the creature's own world thread (logout, another world, server stop)
M(pvs, r"""
public static boolean removeQueued(@PKG@.PetView v, String why) {
  if (v == null || v.gone) return false;
  v.gone = true;
  v.why = why;
  unview(v);
  if (v.w != null && @PKG@.PetWorld.execute(v.w, new @PKG@.PetRemoveJob(v))) return true;
  dropped(v, why + " (no world thread)");
  return false;
}""")
M(pvs, r"""
public static boolean finishRemove(@PKG@.PetView v) {
  if (v == null) return false;
  @ST@ st = @PKG@.PetWorld.store(v.w);
  @REF@ r = v.ref;
  if ((r == null || !r.isValid()) && v.w != null) { try { r = @PKG@.PetWorld.refOf(v.w, java.util.UUID.fromString(v.uuid)); } catch (Throwable t) { r = null; } }
  boolean ok = false;
  try { ok = st != null && r != null && r.isValid() && @PKG@.PetWorld.remove(st, r); } catch (Throwable t) { ok = false; }
  if (ok) { LIVE.remove(v.uuid); REMOVED.incrementAndGet(); return true; }
  dropped(v, v.why + " (not loaded)");
  return false;
}""")
M(pvs, r"""
public static boolean queueSpawn(java.util.UUID u, int slot, String want, @WLD@ w, String wn, long now) {
  String pk = u.toString() + "|" + slot;
  Object t = PENDING.get(pk);
  if (t instanceof Long && now - ((Long) t).longValue() < 10000L) return false;
  PENDING.put(pk, Long.valueOf(now));
  if (@PKG@.PetWorld.execute(w, new @PKG@.PetSpawnJob(u, slot, want, w, wn))) return true;
  PENDING.remove(pk);
  return false;
}""")
# the spawn itself (World.execute = the world thread, never inside a system); "+uuid" or a "-" / "=" reason
M(pvs, r"""
public static String spawnNow(java.util.UUID u, int slot, String want, @WLD@ w, String wn) {
  String pk = u == null ? "" : u.toString() + "|" + slot;
  try {
    if (u == null || want == null) return "-nothing to spawn";
    if (view(u, slot) != null) return "=already out";
    String[] p = want.split("\\|", -1);
    if (p.length != 6) return "-bad spec";
    @ST@ st = @PKG@.PetWorld.store(w);
    @REF@ o = @PKG@.PetWorld.ownerRef(u);
    if (st == null || o == null || !o.isValid() || o.getStore() != st) return "-the owner is not in that world";
    double[] op = @PKG@.PetWorld.pos(st, o);
    if (op == null) return "-the owner position is unreadable";
    int motion = Integer.parseInt(p[5]);
    float sc = Float.parseFloat(p[4]);
    String role = motion == 0 ? @PKG@.PetsCfg.ROLE_WALK : @PKG@.PetsCfg.ROLE_FLY;
    int ri = @PKG@.PetWorld.roleIndex(role);
    if (ri < 0) {
      String fb = motion == 0 ? "Test_Pet" : "Test_Fly";
      @PKG@.PetsLog.warnOnce("role:" + role, "the pet role " + role + " is not loaded - pets use the vanilla " + fb + " until it is (look for an NPC asset error above)");
      role = fb;
      ri = @PKG@.PetWorld.roleIndex(fb);
      FALLBACKS.incrementAndGet();
    }
    if (ri < 0) return "-no pet role";
    Object m = @PKG@.PetWorld.model(p[3], sc);
    if (m == null) { @PKG@.PetsLog.warnOnce("model:" + p[3], "the pet model " + p[3] + " does not exist - fix Server Setup > Pets > Pet looks"); return "-no model " + p[3]; }
    double side = slot == 1 ? 1.4 : -1.4;
    double x = op[0] + side;
    double y = op[1] + (motion == 0 ? 0.0 : @PKG@.PetFly.height(motion, false));
    double z = op[2] + 1.2;
    @REF@ r = @PKG@.PetWorld.spawn(st, ri, x, y, z, @PKG@.PetFly.yaw(op[0] - x, op[2] - z), m);
    if (r == null || !r.isValid()) return "-the spawn gave nothing";
    java.util.UUID eu = @PKG@.PetWorld.uuid(st, r);
    if (eu == null) { @PKG@.PetWorld.remove(st, r); return "-no entity id"; }
    @PKG@.PetView v = new @PKG@.PetView();
    v.uuid = eu.toString(); v.owner = u; v.key = p[0]; v.slot = slot; v.petId = p[2]; v.model = p[3]; v.scale = sc; v.motion = motion;
    v.spec = want; v.world = wn == null ? "" : wn; v.w = w; v.ref = r; v.role = role; v.born = System.currentTimeMillis();
    v.ang = Math.atan2(z - op[2], x - op[0]); v.px = x; v.py = y; v.pz = z; v.hasPos = true;
    Object ro = @PKG@.PetStore.REC.get(v.key);
    @PKG@.PetRec rec = ro instanceof @PKG@.PetRec ? (@PKG@.PetRec) ro : null;
    v.kind = rec == null ? "" : rec.kindOf(v.petId);
    v.plate = rec == null || !rec.has(v.petId) ? @PKG@.PetKind.display(v.kind) : plate(rec, v.petId);
    register(v);
    @PKG@.PetWorld.prepare(st, r, v.plate);
    @PKG@.PetWorld.clearDebug(st, r);
    if (motion == 0) @PKG@.PetWorld.mark(st, r, o);
    SPAWNED.incrementAndGet();
    return "+" + v.uuid;
  } catch (Throwable t) {
    @PKG@.PetsLog.warnOnce("spawn:" + t.getClass().getName(), "a pet could not appear: " + t);
    return "-" + t;
  } finally {
    if (pk.length() > 0) PENDING.remove(pk);
  }
}""")
# every second for a live creature: the name (level up), walking pets: the owner = the target, no debug flags, teleport when far
M(pvs, r"""
public static void upkeep(@PKG@.PetView v, @PKG@.PetRec r, @REF@ o, @CB@ cb, double[] op) {
  if (r != null && !r.bad && r.has(v.petId)) {
    String pl = plate(r, v.petId);
    if (!pl.equals(v.plate)) { v.plate = pl; @PKG@.PetWorld.plate(cb, v.ref, pl); }
  }
  if (v.motion != 0) return;
  @PKG@.PetWorld.clearDebug(cb, v.ref);
  @PKG@.PetWorld.mark(cb, v.ref, o);
  double[] pp = @PKG@.PetWorld.pos(cb, v.ref);
  if (pp == null || op == null) return;
  double d = @PKG@.PetFly.dist(pp[0], pp[1], pp[2], op[0], op[1], op[2]);
  if (d > (double) @PKG@.PetsCfg.TELE_DIST || Math.abs(pp[1] - op[1]) > 12.0) v.far = v.far + 1; else v.far = 0;
  if (v.far < 2) return;
  v.far = 0;
  double side = v.slot == 1 ? 1.4 : -1.4;
  @PKG@.PetWorld.teleport(cb, v.ref, op[0] + side, op[1], op[2] + 1.2, @PKG@.PetFly.yaw(-side, -1.2));
  TELEPORTS.incrementAndGet();
}""")
M(pvs, r"""
public static void reconcile(java.util.UUID u, int slot, String want, @PKG@.PetRec r, @REF@ o, @CB@ cb, @WLD@ w, String wn, double[] op, long now) {
  @PKG@.PetView v = view(u, slot);
  if (v != null) {
    String here = wn == null ? "" : wn;
    if (!here.equals(v.world)) { removeQueued(v, "owner left world " + v.world); v = null; }
    else if (v.ref == null || !v.ref.isValid()) { dropped(v, "not loaded"); v = null; }
    else if (want == null || !want.equals(v.spec)) { removeHere(cb, v, want == null ? "hidden" : "changed"); v = null; }
  }
  if (v != null) { upkeep(v, r, o, cb, op); return; }
  if (want != null && ready(u, now)) queueSpawn(u, slot, want, w, wn, now);
}""")
# once a second per online player (the owner's world thread, PetTickSys) - after PetTick.second loaded the active profile's record
M(pvs, r"""
public static void second(java.util.UUID u, @REF@ o, @ST@ st, @CB@ cb, @WLD@ w, String wn) {
  if (u == null || o == null) return;
  long now = System.currentTimeMillis();
  seen(u, wn, now);
  String key = @PKG@.PetStore.pkey(u);
  @PKG@.PetRec r = @PKG@.PetStore.get(key);
  boolean dead = @PKG@.PetWorld.dead(cb, o);
  double[] op = @PKG@.PetWorld.pos(cb, o);
  for (int s = 1; s <= 2; s++) reconcile(u, s, want(u, r, key, s, wn, dead), r, o, cb, w, wn, op, now);
}""")
# every tick: OUR fly-follow for the owner's flying / fish pets in this world
M(pvs, r"""
public static int steer(java.util.UUID u, @REF@ o, @CB@ cb, float dt) {
  if (u == null || o == null || OWN.isEmpty()) return 0;
  Object a = OWN.get(u);
  if (!(a instanceof Object[])) return 0;
  double[] op = null;
  int n = 0;
  long now = System.currentTimeMillis();
  for (int s = 1; s <= 2; s++) {
    Object x = ((Object[]) a)[s];
    if (!(x instanceof @PKG@.PetView)) continue;
    @PKG@.PetView v = (@PKG@.PetView) x;
    if (v.gone || v.motion == 0 || v.ref == null || !v.ref.isValid() || v.ref.getStore() != o.getStore()) continue;
    if (op == null) { op = @PKG@.PetWorld.pos(cb, o); if (op == null) return n; }
    double[] cur = @PKG@.PetWorld.pos(cb, v.ref);
    if (cur != null && v.hasPos) { v.px = cur[0]; v.py = cur[1]; v.pz = cur[2]; }
    double[] t = @PKG@.PetFly.tick(v, op[0], op[1], op[2], (double) dt, now);
    if (t[4] > 0.5 || "teleport".equals(@PKG@.PetsCfg.FLY_STEER)) @PKG@.PetWorld.teleport(cb, v.ref, t[0], t[1], t[2], (float) t[3]);
    else @PKG@.PetWorld.setPos(cb, v.ref, t[0], t[1], t[2], (float) t[3]);
    STEPS.incrementAndGet();
    n++;
  }
  return n;
}""")
# logout (PetQuit), the 30 s offline sweep (PetTimer) -> the owner's creatures go on their own world threads
M(pvs, r"""
public static int leave(java.util.UUID u, String why) {
  if (u == null) return 0;
  SEEN.remove(u);
  PENDING.remove(u.toString() + "|1");
  PENDING.remove(u.toString() + "|2");
  Object o = OWN.remove(u);
  if (!(o instanceof Object[])) return 0;
  Object[] a = (Object[]) o;
  int n = 0;
  for (int s = 1; s < a.length; s++) if (a[s] instanceof @PKG@.PetView && removeQueued((@PKG@.PetView) a[s], why)) n++;
  return n;
}""")
M(pvs, r"""
public static int removeAll(String why) {
  Object[] vs = LIVE.values().toArray();
  int n = 0;
  for (int i = 0; i < vs.length; i++) if (removeQueued((@PKG@.PetView) vs[i], why)) n++;
  OWN.clear();
  SEEN.clear();
  PENDING.clear();
  return n;
}""")
# fix round: a role our pets may carry without the Skyy_Pet_ prefix (the vanilla fallbacks Test_Pet / Test_Fly, or a renamed
# pets.role.walk / pets.role.fly) - such a creature is ours only with our nameplate "<name> (Lv N)" and no other F hint than ours
M(pvs, r"""
public static boolean maybeOurs(String role) {
  if (role == null) return false;
  return role.equals("Test_Pet") || role.equals("Test_Fly") || role.equals(@PKG@.PetsCfg.ROLE_WALK) || role.equals(@PKG@.PetsCfg.ROLE_FLY);
}""")
M(pvs, r"""
public static boolean ourTags(String tags) {
  if (tags == null) return false;
  int nl = tags.indexOf('\n');
  String p = nl < 0 ? tags : tags.substring(0, nl);
  String h = nl < 0 ? "" : tags.substring(nl + 1);
  if (h.length() > 0 && !h.equals(@PKG@.PetWorld.HINT)) return false;
  return p.matches("^.+ \\(Lv [0-9]{1,3}\\)$");
}""")
# THE GHOST SWEEP (P5: NonSerialized does not stop chunk saving): a pet creature LOADED from a chunk that is not the live tracked one
# (our role prefix, or a uuid we lost track of) is removed at once; the live one's chunk coming back re-attaches it. 0 = not ours.
M(pvs, r"""
public static int onLoad(@REF@ ref, @ADR@ why, @ST@ st, @CB@ cb) {
  if (why != @ADR@.LOAD || ref == null) return 0;
  java.util.UUID eu = @PKG@.PetWorld.uuid(st, ref);
  if (eu == null) return 0;
  String k = eu.toString();
  Object lo = LIVE.get(k);
  if (lo instanceof @PKG@.PetView && !((@PKG@.PetView) lo).gone) { ((@PKG@.PetView) lo).ref = ref; REATTACHED.incrementAndGet(); return 1; }
  String role = @PKG@.PetWorld.roleOf(st, ref);
  boolean ours = (role != null && role.startsWith(ROLE_PREFIX)) || DROPPED.containsKey(k) || lo != null;
  if (!ours && maybeOurs(role)) ours = ourTags(@PKG@.PetWorld.tags(st, ref));
  if (!ours) return 0;
  @PKG@.PetWorld.remove(cb, ref);
  DROPPED.remove(k);
  LIVE.remove(k);
  long n = SWEPT.incrementAndGet();
  if (n <= 20L || n % 100L == 0L) @PKG@.PetsLog.info("ghost sweep: removed a left-over pet creature (" + role + ", " + k + ") when its chunk loaded - " + n + " so far");
  return 2;
}""")
M(pvs, r"""
public static void onRemoved(@REF@ ref, @RR@ why, @ST@ st) {
  if (LIVE.isEmpty() || ref == null) return;
  java.util.UUID eu = @PKG@.PetWorld.uuid(st, ref);
  if (eu == null) return;
  Object lo = LIVE.get(eu.toString());
  if (!(lo instanceof @PKG@.PetView)) return;
  @PKG@.PetView v = (@PKG@.PetView) lo;
  if (v.gone || why == @RR@.UNLOAD) return;
  v.gone = true;
  v.why = "removed by the game (" + why + ")";
  unview(v);
  LIVE.remove(v.uuid);
  GONE_BY_GAME.incrementAndGet();
}""")
M(pvs, r"""
public static int bond(@PKG@.PetView v) {
  Object ro = @PKG@.PetStore.REC.get(v.key);
  if (!(ro instanceof @PKG@.PetRec)) return 0;
  @PKG@.PetRec r = (@PKG@.PetRec) ro;
  if (r.bad || !r.has(v.petId)) return 0;
  long n = r.lv("pet." + v.petId + ".bond", 0L) + 1L;
  if (n < 1L) n = 1L;
  if (n > 1000000L) n = 1000000L;
  r.set("pet." + v.petId + ".bond", String.valueOf(n));
  return (int) n;
}""")
# F on a pet creature (Skyy: "later it should pet the pets you cant ride"): 1 = someone else's, 2 = cooldown, 3 = petted
M(pvs, r"""
public static int use(java.util.UUID user, @PKG@.PetView v, long now) {
  if (user == null || v == null || v.gone) return 0;
  if (!user.equals(v.owner)) {
    @PKG@.PetsEng.tell(user, "[Pets] That is " + @PKG@.PetsEng.nameOf(v.owner) + "'s " + @PKG@.PetKind.display(v.kind) + ".", "@COLINF@");
    return 1;
  }
  if (now - v.lastPet < (long) @PKG@.PetsCfg.PET_COOLDOWN * 1000L) return 2;
  v.lastPet = now;
  v.joy = now + 1500L;
  int b = bond(v);
  Object ro = @PKG@.PetStore.REC.get(v.key);
  String nm = null;
  if (ro instanceof @PKG@.PetRec) { String n0 = ((@PKG@.PetRec) ro).get("pet." + v.petId + ".name"); if (n0 != null && n0.trim().length() > 0) nm = @PKG@.PetsLog.clean(n0.trim()); }
  if (nm == null) nm = "your " + @PKG@.PetKind.display(v.kind);
  @PKG@.PetsEng.tell(user, "[Pets] You pet " + nm + ". " + LINES[b % LINES.length] + (b > 0 ? " (Bond " + b + ")" : ""), "@COLGLD@");
  if (v.w != null) @PKG@.PetWorld.execute(v.w, new @PKG@.PetPetJob(v));
  PETTED.incrementAndGet();
  return 3;
}""")
M(pvs, r"""
public static boolean effects(@PKG@.PetView v) {
  if (v == null || v.gone || v.ref == null || !v.ref.isValid()) return false;
  @ST@ st = @PKG@.PetWorld.store(v.w);
  if (st == null) return false;
  double[] p = @PKG@.PetWorld.pos(st, v.ref);
  if (p == null) return false;
  @PKG@.PetWorld.hearts(st, p[0], p[1] + 0.4 + (double) v.scale * 0.6, p[2]);
  @PKG@.PetWorld.anim(st, v.ref, @PKG@.PetLook.anim(v.model));
  return true;
}""")
M(pvs, r"""
public static String status() {
  int walk = 0, fly = 0;
  Object[] vs = LIVE.values().toArray();
  for (int i = 0; i < vs.length; i++) { if (((@PKG@.PetView) vs[i]).motion == 0) walk++; else fly++; }
  return "Pet creatures out: " + vs.length + " (" + walk + " walking, " + fly + " flying / fish); appeared " + SPAWNED.get() + ", put away " + REMOVED.get() + ", ghosts removed on chunk load " + SWEPT.get() + ", lost track (removed when their chunk loads) " + LOST.get() + " (" + DROPPED.size() + " waiting), removed by the game " + GONE_BY_GAME.get() + ", petted " + PETTED.get() + ", teleported " + TELEPORTS.get() + ", role fallbacks " + FALLBACKS.get() + ". Visible pets " + (@PKG@.PetsCfg.VISIBLE ? "on" : "off") + ", roles " + @PKG@.PetsCfg.ROLE_WALK + " / " + @PKG@.PetsCfg.ROLE_FLY + ".";
}""")
# start census: the roles + every built-in look model
M(pvs, r"""
public static void censusModels(String[] list, java.util.HashSet seen, StringBuilder miss) {
  for (int i = 0; i < list.length; i++) {
    String v = list[i].substring(list[i].indexOf('=') + 1);
    String m = v.substring(0, v.indexOf('/'));
    if (!seen.add(m)) continue;
    if (@PKG@.PetWorld.model(m, 1.0f) == null) miss.append(miss.length() == 0 ? "" : ", ").append(m);
  }
}""")
M(pvs, r"""
public static String census() {
  int a = @PKG@.PetWorld.roleIndex(@PKG@.PetsCfg.ROLE_WALK);
  int b = @PKG@.PetWorld.roleIndex(@PKG@.PetsCfg.ROLE_FLY);
  StringBuilder miss = new StringBuilder();
  java.util.HashSet seen = new java.util.HashSet();
  censusModels(@PKG@.PetLook.LOOK_DEF, seen, miss);
  censusModels(@PKG@.PetLook.BABY_DEF, seen, miss);
  return "pet roles " + @PKG@.PetsCfg.ROLE_WALK + " = " + a + ", " + @PKG@.PetsCfg.ROLE_FLY + " = " + b + (a < 0 || b < 0 ? " (NOT LOADED - pets use the vanilla Test_Pet / Test_Fly)" : "") + "; " + seen.size() + " pet models " + (miss.length() == 0 ? "all loaded" : "MISSING " + miss.toString());
}""")
M(sjc, r"""
public void run() {
  try { this.res = @PKG@.PetViews.spawnNow(this.u, this.slot, this.want, this.w, this.wn); }
  catch (Throwable t) { @PKG@.PetsLog.warnOnce("spawnjob:" + t.getClass().getName(), "pet spawn job failed: " + t); }
}""")
M(rjc, r"""
public void run() {
  try { this.done = @PKG@.PetViews.finishRemove(this.v); }
  catch (Throwable t) { @PKG@.PetsLog.warnOnce("removejob:" + t.getClass().getName(), "pet removal job failed: " + t); }
}""")
M(pjc, r"""
public void run() {
  try { @PKG@.PetViews.effects(this.v); }
  catch (Throwable t) { @PKG@.PetsLog.warnOnce("petjob:" + t.getClass().getName(), "petting effects failed: " + t); }
}""")

# =====================================================================================================================
# 0.2 PetUseSys (UseEntityEvent$Pre, fired on the PLAYER - the SkyyMerchants 0.1 MerchUseSys shape) + PetLoadSys (RefSystem on NPCs)
# =====================================================================================================================
usys = cls("PetUseSys", T["EES"])
F(usys, "public static boolean FAILED_ONCE = false;")
F(usys, "public static final java.util.concurrent.atomic.AtomicLong HITS = new java.util.concurrent.atomic.AtomicLong();")
C(usys, "public PetUseSys() { super(@UEPRE@.class); }")
M(usys, "public @QRY@ getQuery() { return @ARCH@.empty(); }")
M(usys, r"""
public void handle(int idx, @ACH@ chunk, @ST@ st, @CB@ buf, @EV@ ev) {
  try {
    if (@PKG@.PetViews.LIVE.isEmpty() || !(ev instanceof @UEPRE@)) return;
    @UEPRE@ e = (@UEPRE@) ev;
    if (e.isCancelled()) return;
    @REF@ t = e.getTargetEntity();
    if (t == null || !t.isValid()) return;
    java.util.UUID tu = @PKG@.PetWorld.uuid(st, t);
    if (tu == null) return;
    Object o = @PKG@.PetViews.LIVE.get(tu.toString());
    if (!(o instanceof @PKG@.PetView)) return;
    e.setCancelled(true);
    HITS.incrementAndGet();
    @REF@ me = chunk.getReferenceTo(idx);
    @PR@ pr = me == null ? null : (@PR@) st.getComponent(me, @PR@.getComponentType());
    if (pr == null) return;
    @PKG@.PetViews.use(pr.getUuid(), (@PKG@.PetView) o, System.currentTimeMillis());
  } catch (Throwable x) {
    if (!FAILED_ONCE) { FAILED_ONCE = true; @PKG@.PetsLog.warn("pet use hook failed (logged once): " + x); }
  }
}""")
lsys = cls("PetLoadSys", T["RSYS"])
F(lsys, "public static boolean FAILED_ONCE = false;")
F(lsys, "public @QRY@ query;")
C(lsys, "public PetLoadSys() { super(); }")
M(lsys, r"""
public @QRY@ getQuery() {
  if (this.query == null) this.query = (@QRY@) @NPC@.getComponentType();
  return this.query;
}""")
M(lsys, r"""
public void onEntityAdded(@REF@ ref, @ADR@ why, @ST@ st, @CB@ cb) {
  try { @PKG@.PetViews.onLoad(ref, why, st, cb); }
  catch (Throwable x) { if (!FAILED_ONCE) { FAILED_ONCE = true; @PKG@.PetsLog.warn("pet ghost sweep failed (logged once): " + x); } }
}""")
M(lsys, r"""
public void onEntityRemove(@REF@ ref, @RR@ why, @ST@ st, @CB@ cb) {
  try { @PKG@.PetViews.onRemoved(ref, why, st); }
  catch (Throwable x) { if (!FAILED_ONCE) { FAILED_ONCE = true; @PKG@.PetsLog.warn("pet remove hook failed (logged once): " + x); } }
}""")

'''
rep('''# =====================================================================================================================
# PetOps: slots, starter, admin operations (each returns a "+"/"-"/"=" marked line)
# =====================================================================================================================
ops = cls("PetOps")''', VIEWS + '''# =====================================================================================================================
# PetOps: slots, starter, admin operations (each returns a "+"/"-"/"=" marked line)
# =====================================================================================================================
ops = cls("PetOps")''')

# ================================================================================================ PetsEng.worldObj (the store's World)
rep('''M(eng, r"""
public static boolean open(@REF@ ref, @ST@ st, @PAGE@ page) {''', '''M(eng, r"""
public static @WLD@ worldObj(@ST@ st) {
  try {
    Object ext = st == null ? null : st.getExternalData();
    if (ext instanceof @EST@) return ((@EST@) ext).getWorld();
  } catch (Throwable t) { }
  return null;
}""")
M(eng, r"""
public static boolean open(@REF@ ref, @ST@ st, @PAGE@ page) {''')

# ================================================================================================ /petadmin sweep
rep('''  if (v.length() == 0 || v.equals("help")) return "=/petadmin give <player> <kind> [rarity] [level] | take <player> <id> | unlock <player> | lock <player> | list <player> | restore <player> <id> | xp <player> <skill> <amount> | kinds";''',
    '''  if (v.length() == 0 || v.equals("help")) return "=/petadmin give <player> <kind> [rarity] [level] | take <player> <id> | unlock <player> | lock <player> | list <player> | restore <player> <id> | xp <player> <skill> <amount> | kinds | sweep";
  if (v.equals("sweep")) return "=" + @PKG@.PetViews.status();''')
rep('''    ("PetAdminArg1Cmd", "(admin) /petadmin kinds | help", ["option"]),''', '''    ("PetAdminArg1Cmd", "(admin) /petadmin kinds | sweep | help", ["option"]),''')
rep('''    for (int i = 0; i < @PKG@.PetKind.STAT_KEYS.length; i++) sb.append(i > 0 ? ", " : "").append(@PKG@.PetKind.STAT_KEYS[i]);
    return "=" + sb.toString();''', '''    for (int i = 0; i < @PKG@.PetKind.STAT_KEYS.length; i++) sb.append(i > 0 ? ", " : "").append(@PKG@.PetKind.STAT_KEYS[i]);
    sb.append("\\nBuilt-in pet looks (model size motion; a Server Setup > Pets > Pet looks row wins): " + @PKG@.PetLook.builtIn(@PKG@.PetLook.LOOK_DEF));
    sb.append("\\nBuilt-in baby looks (model size; Baby looks row wins): " + @PKG@.PetLook.builtIn(@PKG@.PetLook.BABY_DEF));
    return "=" + sb.toString();''')
rep('''ARG_HELP = {"option": "give, take, unlock, lock, list, restore, xp or kinds",''', '''ARG_HELP = {"option": "give, take, unlock, lock, list, restore, xp, kinds or sweep",''')
rep('''  if (!v.equals("list") && !v.equals("kinds") && !v.equals("help") && res.startsWith("+"))''', '''  if (!v.equals("list") && !v.equals("kinds") && !v.equals("help") && !v.equals("sweep") && res.startsWith("+"))''')
rep('''_ac = ["public PetAdminCmd() {", '  super("petadmin", "(admin) Pets: /petadmin give | take | unlock | lock | list | restore | xp | kinds");',''',
    '''_ac = ["public PetAdminCmd() {", '  super("petadmin", "(admin) Pets: /petadmin give | take | unlock | lock | list | restore | xp | kinds | sweep");',''')

# fix round: a spawn job that ran after leave() (the owner still had a valid ref for a moment while disconnecting) puts the owner
# back into PetViews.OWN only - the 30 s offline sweep must see those owners too, or that pet stays until a restart
rep('''  seen.addAll(@PKG@.PetBuff.LAST.keySet());
  int n = 0;''', '''  seen.addAll(@PKG@.PetBuff.LAST.keySet());
  seen.addAll(@PKG@.PetViews.OWN.keySet());
  int n = 0;''')

# ================================================================================================ leave -> the views go too
rep('''public static void leave(java.util.UUID u) {
  if (u == null) return;
  @PKG@.PetBuff.clear(u);''', '''public static void leave(java.util.UUID u) {
  if (u == null) return;
  try { @PKG@.PetViews.leave(u, "owner left"); } catch (Throwable t0) { @PKG@.PetsLog.warnOnce("leaveviews:" + t0.getClass().getName(), "removing the pets of a leaving player failed: " + t0); }
  @PKG@.PetBuff.clear(u);''')

# ================================================================================================ PetTickSys: steering every tick + views each second
rep('''M(tsys, "public @QRY@ getQuery() { return (@QRY@) @PLA@.getComponentType(); }")''',
    '''M(tsys, "public @QRY@ getQuery() { return (@QRY@) @PLA@.getComponentType(); }")
F(tsys, "public static boolean VIEW_FAILED_ONCE = false;")
# 0.2: one player at a time (the fly steering moves the player's pets, spawns go through World.execute)
M(tsys, "public boolean isParallel(int a, int b) { return false; }")''')
rep('''    java.util.UUID u = pr.getUuid();
    if (!@PKG@.PetTick.due(u, dt)) return;
    @ESM@ m = (@ESM@) cb.getComponent(ref, @ESM@.getComponentType());
    @PKG@.PetTick.second(u, @PKG@.PetsEng.worldOf(store), m);
  } catch (Throwable t) {''', '''    java.util.UUID u = pr.getUuid();
    try { @PKG@.PetViews.steer(u, ref, cb, dt); } catch (Throwable t1) { if (!VIEW_FAILED_ONCE) { VIEW_FAILED_ONCE = true; @PKG@.PetsLog.warn("pet steering failed (logged once): " + t1); } }
    if (!@PKG@.PetTick.due(u, dt)) return;
    @ESM@ m = (@ESM@) cb.getComponent(ref, @ESM@.getComponentType());
    String wn = @PKG@.PetsEng.worldOf(store);
    @PKG@.PetTick.second(u, wn, m);
    try { @PKG@.PetViews.second(u, ref, store, cb, @PKG@.PetsEng.worldObj(store), wn); } catch (Throwable t2) { if (!VIEW_FAILED_ONCE) { VIEW_FAILED_ONCE = true; @PKG@.PetsLog.warn("pet creatures failed (logged once): " + t2); } }
  } catch (Throwable t) {''')

# ================================================================================================ the plugin
rep('''  try { getEntityStoreRegistry().registerSystem(new @PKG@.PetTickSys()); }
  catch (Throwable t) { @PKG@.PetsLog.warn("PetTickSys could not be registered: " + t + " - no pet buffs and no starter pets"); }''',
    '''  try { getEntityStoreRegistry().registerSystem(new @PKG@.PetTickSys()); }
  catch (Throwable t) { @PKG@.PetsLog.warn("PetTickSys could not be registered: " + t + " - no pet buffs and no starter pets"); }
  try { getEntityStoreRegistry().registerSystem(new @PKG@.PetUseSys()); }
  catch (Throwable t6) { @PKG@.PetsLog.warn("PetUseSys could not be registered: " + t6 + " - F does not pet pets"); }
  try { getEntityStoreRegistry().registerSystem(new @PKG@.PetLoadSys()); }
  catch (Throwable t7) { @PKG@.PetsLog.warn("PetLoadSys could not be registered: " + t7 + " - left-over pet creatures are not swept"); }
  @PKG@.PetViews.regSetting();''')
rep('''summon slot " + @PKG@.PetsCfg.SLOT2_MODE + " (" + @PKG@.PetsCfg.SLOT2_PCT + "%), starter " + @PKG@.PetsCfg.STARTER + ", XP fallback " + (@PKG@.PetsCfg.FALLBACK ? "on" : "off") + "; bridge pets:fn:onxp + pets:stats:<uuid>; /pets, /petadmin; kit @KITID@, page @PAGEID@");
}""".replace("@PAGEID@", PAGE_ID))''', '''summon slot " + @PKG@.PetsCfg.SLOT2_MODE + " (" + @PKG@.PetsCfg.SLOT2_PCT + "%), starter " + @PKG@.PetsCfg.STARTER + ", XP fallback " + (@PKG@.PetsCfg.FALLBACK ? "on" : "off") + "; pets in the world " + (@PKG@.PetsCfg.VISIBLE ? "ON" : "OFF") + " (roles " + @PKG@.PetsCfg.ROLE_WALK + " / " + @PKG@.PetsCfg.ROLE_FLY + ", ghost sweep on chunk load, F = pet it); bridge pets:fn:onxp + pets:stats:<uuid>; /pets, /petadmin; kit @KITID@, page @PAGEID@");
}""".replace("@PAGEID@", PAGE_ID))
# 0.2: the role / model census once the assets are loaded
M(plug, r"""
protected void start() {
  try { @PKG@.PetsLog.info("census at start: " + @PKG@.PetViews.census()); } catch (Throwable t) { @PKG@.PetsLog.warn("pet census failed: " + t); }
}""")''')
rep('''  try { @PKG@.PetStore.flushDirty(); } catch (Throwable t2) { @PKG@.PetsLog.warn("the last pet save failed: " + t2); }''',
    '''  try { int q = @PKG@.PetViews.removeAll("server stop"); if (q > 0) @PKG@.PetsLog.info("stop: " + q + " pet creatures queued for removal (anything a saved chunk keeps is swept when it loads)"); } catch (Throwable t6) { @PKG@.PetsLog.warn("removing the pet creatures at stop failed: " + t6); }
  try { @PKG@.PetStore.flushDirty(); } catch (Throwable t2) { @PKG@.PetsLog.warn("the last pet save failed: " + t2); }''')

# ================================================================================================ the jar: + the two role files
rep('''man = B.manifest(MOD, VERSION, "SkyWynn slot pets (phase 1): per-profile pet records, the pet slot + summon slot with buffs, pet XP and "
                 "levels, /pets page, /petadmin. Visible pets, eggs and fighting come in later versions.", PKG + ".SkyyPetsPlugin")
man["IncludesAssetPack"] = False
B.assemble(jar, man, OUT)''', '''man = B.manifest(MOD, VERSION, "SkyWynn slot pets (phase 2): per-profile pet records, the pet slot + summon slot with buffs, pet XP and "
                 "levels, VISIBLE PETS (small vanilla creatures that follow or fly around you, F to pet them), /pets page, /petadmin. Eggs "
                 "and fighting come in later versions.", PKG + ".SkyyPetsPlugin")
man["IncludesAssetPack"] = True     # 0.2: the two NPC roles (generated at build time from vanilla data)
B.assemble(jar, man, OUT, ROLE_ASSETS)''')
rep('''print("classes written: %d (+ the config kit's 7); pets page id %s; %d pet kinds" % (len(ALL), PAGE_ID, len(KINDS)))''',
    '''print("classes written: %d (+ the config kit's 7); pets page id %s; %d pet kinds; %d looks, %d babies, roles %s + %s" % (len(ALL), PAGE_ID, len(KINDS), len(LOOKS), len(BABY_ROWS), ROLE_WALK, ROLE_FLY))''')

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert s.count("registerSystem(new @PKG@.") == 3, "three systems, each registered once"
_u = s
for _new, _old in reversed(CHANGES):
    assert _u.count(_new) == 1, "a change is not unique any more: %s" % _new[:80]
    _u = _u.replace(_new, _old, 1)
assert _u == OLD, "the generated script differs from 0.1 outside the recorded changes"
for _k in ('def page_java():', 'public static boolean writeAtomic(java.nio.file.Path f, byte[] b) {', 'public static int[] scanAll() {',
           'public static int give(java.util.UUID u, String skill, long amount) {', 'public void handleDataEvent(@REF@ ref, @ST@ st, String data) {'):
    assert s.count(_k) == 1 and OLD.count(_k) == 1, "0.1 code lost: " + _k
# javassist order: PetLook part 1 -> PetsCfg -> the kit -> PetBuff -> PetLook part 2 / views -> PetOps -> PetTick -> the plugin
assert s.index('lkc = cls("PetLook")') < s.index('cfgc = cls("PetsCfg")') < s.index("kit = CFG.emit(") < s.index('bf = cls("PetBuff")') \
    < s.index("public static String[] look(String kind) {") < s.index('pvs = cls("PetViews")') < s.index('ops = cls("PetOps")') \
    < s.index('tk = cls("PetTick")') < s.index('plug = cls("SkyyPetsPlugin", T["JP"])'), "javassist order"
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1 had %d; %d changes)" % (s.count(LF), OLD.count(LF), len(CHANGES)))
