"""Derive SkyyProfiles/build_skyyprofiles_0.1.3.py from the LIVE 0.1.2 (build_skyyprofiles_0.1.2.py = the tools/deploy_set.py SET pin).
Run:  python tools/profiles_0_1_3_patch.py   then   python SkyyProfiles/build_skyyprofiles_0.1.3.py   (never --deploy: coordinated deploy)
Patch chain (the 0.1.2 header): 0.1 -> 0.1.1 (copy + edit) -> tools/profiles_0_1_2_patch.py -> 0.1.2 -> THIS patch -> 0.1.3. Edit THIS
file, never the generated build script.

0.1.3 = the vanilla UI pass (Skyy 2026-09-28: "the new goal for any and all UI added in the game is for them to look and feel
vanilla"; HANDOFF section 2 rule 0; research/Vanilla-UI-Style-Guide.md section 7; research/Skyy-UI-Inventory.md 5.17 + section 6
"Class cards"). ONLY THE LOOK OF ProfilePage (/profiles: the Profiles list and the Create Profile view) CHANGES - a look-only
restyle on the shared kit tools/skyyui.py (1.3):
  - the generated script imports skyyui as SUI and calls SUI.verify() before anything else (every vanilla value the page uses is
    proven against Assets.zip at every build) and puts SUI.kit_id() into the ready log line;
  - a SKYY CARD block (the ONE shared card component, identical in SkyyClasses 0.1.8 - tools/classes_0_1_8_patch.py; both patches
    assert the same hash, CARD_SHA) builds the profile cards, the empty-slot card and the Create Profile class cards from kit calls;
  - ProfilePage.buildList() / buildCreate() are generated at build time by profile_list_java() / profile_create_java(): 0.1.2's
    statements (active / pending profile, the texts, the roster loop up to MAX_CARDS, the pick / name / first-profile state, the
    event bindings pfsw<id> / pfnew / pfyes / pfno / pfname / pfcls<i> / pfmake / pfback with their EventData, in their order) are
    kept word for word - asserted below against the 0.1.2 methods; only the appends changed and the texts go in with b.set (0.1.2
    wrote them inline after safe(); the same safe() text is b.set now). The switch question and the create row are the kit's
    confirm_view(compact=True) with 0.1.2's ids (#SkyyPfConfirm / #SkyyPfYes / #SkyyPfNo, #SkyyPfMakeRow / #SkyyPfMake /
    #SkyyPfBack). The 'tight' 8-card variant and the CL / LL size tables are gone: the Create Profile list well holds MAX_CARDS.
  - UI_DATA_COLORS lists the class colours (the fallback roster + the extra-class grey, data colours) and the chat line colours for
    the kit lint.
  - review fixes (second pass, 2026-09-29): CARD_LOOKS["selected"] = the row pressed step (contrast), the description box 40 px
    (CARD_SHA moved in both patches), pf_row asserts every rewrite of the kit's compact confirm row. Harness (new):
    SkyyProfiles/test_skyyprofiles_0.1.3.py.
Everything else (commands, permissions, config, files, bridge keys, profile switching / creating / deleting, the first-join OpenTask
gates, ProfilePage's fields, constructor, safe(), prepareCreate(), build(), closeSelf(), remindFirst(), handleDataEvent(),
onDismiss(), open(), every other class) is byte-identical to 0.1.2 - asserted below (KEEP blocks).
"""
import collections
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.2.py")
dst = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.3.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1.2"' in s and "GENERATED by tools/profiles_0_1_2_patch.py from build_skyyprofiles_0.1.1.py" in s, \
    "build_skyyprofiles_0.1.2.py is not the live 0.1.2"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
assert len(BIND0) == 8, "0.1.2 has 8 event bindings (all in ProfilePage), found %d" % len(BIND0)


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)


def cut(a, b, new=""):
    """replace everything from anchor a (included) up to anchor b (kept) with new; returns the text that was cut"""
    global s
    assert s.count(a) == 1, "cut start count %d: %s" % (s.count(a), a[:120])
    assert s.count(b) == 1, "cut end count %d: %s" % (s.count(b), b[:120])
    i, j = s.index(a), s.index(b)
    assert i < j, "cut anchors out of order: %s / %s" % (a[:60], b[:60])
    old = s[i:j]
    s = s[:i] + new + s[j:]
    return old


def block(a, b):
    """the text from anchor a (included) to anchor b (excluded) of the CURRENT source (for unchanged-block asserts)"""
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


# blocks that must come out of this patch byte-identical (everything but the docstring head, VERSION, the kit import, the data
# colour list, the old page size tables, ProfilePage's look and the ready log line)
KEEP = [block("\nHERE = os.path.dirname(os.path.abspath(__file__))", "\nFRUITS = ["),
        block("\nFRUITS = [", "PAGE_W, PAGE_H = 1000, 900"),
        block("\nBAD_UI = set(", "# ================= ProfilePage: Profiles list (view 0) + Create Profile (view 1) ================="),
        block('F(page, "public int view;")', 'M(page, ui(r"""\npublic void buildList('),
        block('M(page, r"""\npublic void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {',
              'getLogger().at(java.util.logging.Level.INFO).log("[SkyyProfiles] __VER__ ready'),
        block("# profile:fn:key stays registered on purpose", "if \"--deploy\" in sys.argv:")]

# ================================================================================================ docstring
rep('''"""SkyyProfiles 0.1.2 - build script (javassist via jpype). SkyBlock-style profiles for SkyWynn = the class selector.
Run:   python build_skyyprofiles_0.1.2.py          -> SkyyProfiles/SkyyProfiles-0.1.2.jar
       (never --deploy: tools/deploy_set.py is the only deploy path; HANDOFF section 3)
GENERATED by tools/profiles_0_1_2_patch.py from build_skyyprofiles_0.1.1.py - edit the patch, never this file (0.1.1 was a copy + edit
of 0.1). Everything below the 0.1.2 and 0.1.1 blocks is the 0.1 design, unchanged unless a line says 0.1.1 or 0.1.2.
''', '''"""SkyyProfiles 0.1.3 - build script (javassist via jpype). SkyBlock-style profiles for SkyWynn = the class selector.
Run:   python build_skyyprofiles_0.1.3.py          -> SkyyProfiles/SkyyProfiles-0.1.3.jar
       (never --deploy: tools/deploy_set.py is the only deploy path; HANDOFF section 3)
GENERATED by tools/profiles_0_1_3_patch.py from build_skyyprofiles_0.1.2.py (itself generated by tools/profiles_0_1_2_patch.py from
0.1.1, a copy + edit of 0.1) - edit the patch, never this file. Everything below the 0.1.3, 0.1.2 and 0.1.1 blocks is the 0.1 design,
unchanged unless a line says 0.1.1, 0.1.2 or 0.1.3.

0.1.3 (2026-09-29, the vanilla UI pass - Skyy 2026-09-28: "the new goal for any and all UI added in the game is for them to look and
  feel vanilla"; HANDOFF section 2 rule 0; research/Vanilla-UI-Style-Guide.md): ONLY THE LOOK OF /profiles CHANGED (the Profiles
  list and the Create Profile view), on the shared kit tools/skyyui.py. Commands, permissions, config, files, bridge keys, switching
  / creating profiles, the first-join Create Profile gates, every element id of 0.1.2, the 8 event bindings (pfsw<id>, pfnew,
  pfyes, pfno, pfname, pfcls<i>, pfmake, pfback) and every text are 0.1.2's (the patch asserts it).
  - The build calls SUI.verify() first (every vanilla style value / texture / sound the page uses is proven against Assets.zip,
    read-only; a game update that changes one stops the build); KIT_ID (kit version + file hash) is in the ready log line.
  - Window: the vanilla decorated container (ContainerHeader title bar with runes + the two gold ornaments; title PROFILES /
    CREATE YOUR FIRST PROFILE / CREATE A NEW PROFILE in the 15 px Secondary title style; the ContainerPatch body, padding 17), ONE
    size for both views as in 0.1.2: 1100 x 980. 0.1.2's root #SkyyPf is the body now. Gone: the dark-blue root, the copper accent
    stripe, the custom title, the empty Label spacers.
  - Cards = the SKYY CARD component (the same code as SkyyClasses 0.1.8's class cards) in a vanilla list well (#000000(0.15),
    padding 4). Profile cards: the class icon in a vanilla item slot border, the name (vanilla success green while active), the
    class line in the class colour, the dates in the list row caption colour, Switch = vanilla Secondary (Primary while it waits for
    Confirm) or the state word Active (success green). The empty slot = a card in the list well tone with the Voidheart icon and a
    vanilla Primary "Create new". Create Profile class cards: up to 3 weapon icons, the class name in the class colour with the
    role right-aligned on the same row, the combat skill line, the description (two lines), Select = vanilla Secondary, state words
    Selected (success green) / Coming later (disabled grey); coming-later cards = BarterTradeRow's disabled card, grey text, the
    sold-out cover over the icons. Looks: active profile / picked class = the list row's pressed step #182a40(0.9) + the
    selected blue bar; waiting for Confirm = the hovered row + a yellow bar.
  - Rows: the switch question = the kit's in-page confirm_view(compact=True) (question in the vanilla confirm yellow, wraps to two
    lines; Confirm = Primary with the save sound, Cancel = Secondary with the cancel sound); the create row = the same look with
    Create profile (Primary; shown in the vanilla Disabled look, unbound as before, until a class is selected) and Later / Back
    (Secondary + cancel sound). Name row: the name line in the vanilla heading style + a small Secondary "Other name". Info line =
    the vanilla info blue, bold; footer = the vanilla caption grey. Esc closes the page as before (no new button, no new binding).
  - Texts are b.set now (0.1.2 put them inline); the text itself is unchanged (still passed through safe()).
  - Review fixes (2026-09-29, second pass): the selected card background is the WorldEventListRow pressed step #182a40(0.9), not
    the active tint #7a9cc6(0.25) (Berserker red 2.6:1 -> 3.4:1, disabled grey 2.7:1 -> 3.5:1); the two-line description box
    is 40 px (was 38 + 2 spare); the Create profile question wraps to two lines like the switch question (a long name overflowed
    the one-line label); pf_row asserts that each rewrite of the kit's compact confirm row found exactly one markup of the expected
    shape (a kit change stops the build). The list view keeps ONE window size for both views (spec 4.2: never change the
    root size between rebuilds of one page) - with 1-3 profiles the list well stays partly empty, like a vanilla list well.
  UNVERIFIED (needs the game): the kit's "base" look has not been seen in game yet (skyyui probe pages base1 / base2 / base3).
''')

# ================================================================================================ version, kit import, data colours
rep('VERSION = "0.1.2"', 'VERSION = "0.1.3"')
rep("import skyybuild as B\n", """import skyybuild as B
import skyyui as SUI       # 0.1.3: the ONE shared vanilla UI kit (research/Vanilla-UI-Style-Guide.md); not "as UI"
SUI.verify()               # proves every vanilla value / texture / sound the page uses against Assets.zip (read-only); stops the build on drift
KIT_ID = SUI.kit_id()      # "skyyui <version> <blob12>" - in the ready log line
""")
rep("\nFRUITS = [", """
# 0.1.3: DATA colours for the vanilla UI kit's lint (research/Vanilla-UI-Style-Guide.md section 5): the class colours (the fallback
# roster below + #c9d6e2 for a class only SkyyClasses knows; checked against CLASSES right below) + the chat line colours
# (Message.color, not page chrome)
UI_DATA_COLORS = ["#8fd67a", "#e0b060", "#7fb0e0", "#d9443f", "#f2e6a0", "#b58cff", "#ff7a5c", "#c9d6e2"] + ["#8fe39a", "#ffc800", "#ff9d6b",
                                                                                                          "#9fd8a2"]
need(sorted(set(UI_DATA_COLORS[:len(CLASSES)])) == sorted(set(c["color"] for c in CLASSES)), "UI_DATA_COLORS must start with the CLASSES colours")
FRUITS = [""")

# ================================================================================================ the old page size tables
OLD_SIZES = cut("PAGE_W, PAGE_H = 1000, 900", "\nBAD_UI = set(", '''MAX_CARDS = 8                          # 0.1.2: class cards drawn on the Create Profile page AND pfcls<i> payloads handled (0.1.1: 6)
# 0.1.3: the page sizes live in the ProfilePage block (PF_W / PF_H, the SKYY CARD sizes); the Create Profile list well holds MAX_CARDS
# cards, so the 0.1.2 CL / LL tables and the 'tight' 8-card variant are gone
need(len(CLASSES) <= MAX_CARDS, "the fallback roster has more classes than the Create Profile page draws")
''')
assert "MAX_CARDS = 8 " in OLD_SIZES and "LL = {" in OLD_SIZES and "CL = {" in OLD_SIZES

# ================================================================================================ ProfilePage: the look only
OLD_LOOK = cut("# 0.1.2: button labels 14 pt (were 12) - the page is 1000 x 900 now", 'F(page, "public int view;")', "@@CARD_AND_PAGE@@")
assert "BTN_GO = " in OLD_LOOK and "def ui(src):" in OLD_LOOK
OLD_VIEWS = cut('M(page, ui(r"""\npublic void buildList(', 'M(page, r"""\npublic void build(@REF@ ref, @UCB@ b, @UEB@ ev, @ST@ st) {', "@@VIEWS@@")
CARD_BLOCK = r'''# =====================================================================================================================
# SKYY CARD - the ONE shared card component (research/Skyy-UI-Inventory.md 5.5, 5.17 and section 6 "Class cards"): the class
# cards of SkyyClasses' ClassPage and of SkyyProfiles' Create Profile page, SkyyProfiles' profile cards and its empty-slot card.
# Built from kit calls only (tools/skyyui.py). THE SAME BLOCK is in SkyyClasses 0.1.8 and SkyyProfiles 0.1.3: both patches
# (tools/classes_0_1_8_patch.py, tools/profiles_0_1_3_patch.py) insert it and assert its hash - change it in both together.
# A card is one row of a list well (the vanilla #000000(0.15) list inset, padding 4): Group <card> (LayoutMode Left) = a 4 px status
# bar <card>Bar + the card body <card>In (the state background; side by side, so a look without a bar is one plain colour) holding
# the item cells (the vanilla BarterTradeRow slot border with an ItemIcon) | the text column (up to three label lines, their Text
# is b.set) | the action column (a vanilla button or a state word, appended by the page). Only
# properties the deployed pages already use: LayoutMode Left / Top, fixed widths / heights, Anchor margins, Padding, colour
# backgrounds, ItemIcon with an inline ItemId, Wrap (no FlexWeight, no WrapMaxLines, no LayoutMode Center / Full).
# =====================================================================================================================
CARD_H = 84                 # card height: name 24 + line two 20 + line three 40 (two wrapped lines; review fix: was 38 + 2 spare,
                            # a two-line 15 px text needs ~41 px at the game's Nunito Sans line height)
CARD_GAP = 4                # space under each card (the OverrideRespawnPointButton option rows: 50 + 4)
CARD_BAR = 4                # status bar at the left edge (WorldEventListRow #StatusBar: 4 px)
CARD_FRAME = 64             # item cell border (BarterTradeRow slot border #1a2530, padding 2) around a 60 px ItemIcon
CARD_CELL = CARD_FRAME + 8  # one icon cell: an 8 px gap + the frame
CARD_ACT_W = 200            # action column: a vanilla normal button (172 = @DefaultButtonMinWidth) centred in it
CARD_BTN_W = SUI.BTN_MIN_W
CARD_PAD_R = 12             # space right of the action column
CARD_LIST_PAD = SUI.WELL_LIST_PAD   # the list well's padding (WorldEventPanelPage #ListContainer: 4)
# card looks: (background, status bar), kit colour names
CARD_LOOKS = {
    "selected": ("rowPressed", "selected"),    # your class / the picked class / the active profile: the WorldEventListRow pressed
                                               # step #182a40(0.9) + its selected blue #4274a5 as the bar (review fix: the active
                                               # tint #7a9cc6(0.25) put the Berserker red at 2.6:1 and the disabled grey at 2.7:1;
                                               # on the pressed step every card text is >= 3.4:1; vanilla's solid #4274a5 row
                                               # would drop the class colours to 1.1-2:1)
    "pending": ("rowHover", "warning"),        # waiting for Confirm: the hovered row #132033(0.8) + the confirm question yellow bar
    "normal": ("row", "row"),                  # the WorldEventListRow panel #101925(0.55); the bar in the card colour = no bar
    "off": ("cardDisabled", "cardDisabled"),   # coming later: BarterTradeRow's disabled card #1a1e24 (+ grey text, covered icons)
    "empty": ("well", "well"),                 # an empty slot: one more step of the list well tone
}


def card_list_h(rows):
    """The height of a list well holding `rows` cards (padding 4 + rows x (card + gap))."""
    return 2 * CARD_LIST_PAD + rows * (CARD_H + CARD_GAP)


def card_list(ident, h, anchor=None):
    """The list well the cards go into (a vanilla panel "well", LayoutMode Top, padding 4)."""
    return SUI.panel(ident, "well", h=h, pad=CARD_LIST_PAD, anchor=anchor)


def card_text_w(w, icon_max):
    """The text column width of a w px card with icon_max item cells."""
    tw = w - CARD_BAR - icon_max * CARD_CELL - CARD_ACT_W - CARD_PAD_R
    SUI.fit([CARD_BAR, icon_max * CARD_CELL, tw, CARD_ACT_W, CARD_PAD_R], w, "card width")
    assert tw >= 240, "card text column too narrow: %d px" % tw
    return tw


def _card_in(outer, *kids):
    """kit markup `outer` with the kit markups `kids` placed inside it (before its closing brace)."""
    assert outer.endswith("}") and kids, outer[:60]
    return outer[:-1] + " ".join(kids) + " }"


def _card_col(col, on):
    """A line colour: a kit colour name or a J(java expr, sample) data colour; with on (a Java boolean expression) the vanilla
    disabled grey when it is false."""
    c = SUI.color(col)
    if on is None:
        return c
    sample = SUI.render(c) if SUI.has_j(c) else c
    return SUI.J("(%s) ? (%s) : %s" % (on, SUI.java_value(c), SUI.java_lit(SUI.COLOR["disabled"])), sample)


def _card_look(look, var):
    """(java declarations, background, bar) for a static look name or [(look, java boolean), ..., last look]."""
    if isinstance(look, str):
        bg, bar = CARD_LOOKS[look]
        return [], SUI.color(bg), SUI.color(bar)
    conds, last = list(look[:-1]), look[-1]
    assert conds and isinstance(last, str), look
    e_bg, e_bar = SUI.java_lit(SUI.color(CARD_LOOKS[last][0])), SUI.java_lit(SUI.color(CARD_LOOKS[last][1]))
    for name, cond in reversed(conds):
        e_bg = "(%s) ? %s : (%s)" % (cond, SUI.java_lit(SUI.color(CARD_LOOKS[name][0])), e_bg)
        e_bar = "(%s) ? %s : (%s)" % (cond, SUI.java_lit(SUI.color(CARD_LOOKS[name][1])), e_bar)
    first = CARD_LOOKS[conds[0][0]]
    decl = ["String %sBg = %s;" % (var, e_bg), "String %sBar = %s;" % (var, e_bar)]
    return decl, SUI.J(var + "Bg", SUI.color(first[0])), SUI.J(var + "Bar", SUI.color(first[1]))


def _card_cell(fid, item, on):
    """One item cell: an 8 px gap + the slot border (padding 2) with the ItemIcon; the coming-later look lays the vanilla
    sold-out cover (BarterTradeRow #0a0e12(0.75)) over it. With on: both looks, picked in the Java (choose)."""
    cell = SUI.group(None, None, w=CARD_CELL, h=CARD_H)
    frame = SUI.item_frame(fid, CARD_FRAME, anchor={"left": CARD_CELL - CARD_FRAME, "top": (CARD_H - CARD_FRAME) // 2})
    icon = SUI.item_icon(None, item, CARD_FRAME - 4, anchor={"left": 0, "top": 0})
    live = _card_in(cell, _card_in(frame, icon))
    if on is None:
        return live
    cover = SUI.group(None, None, anchor={"full": 0}, extra="Background: %s" % SUI.COLOR["cardOverlay"])
    return SUI.choose(SUI.J(on), live, _card_in(cell, _card_in(frame, icon, cover)))


def card_java(ids, w, look, lines, icons=None, icon_item=None, icon_max=1, on=None, var="card", k="k", b="b"):
    """Java statements that append ONE card (they go inside the page's Java loop; ids / texts / colours may be J() values):
      ids       {"list": the list well, "card", "icons" (None = <card>Ics), "text", "act"} - the page's OLD element ids
      w         the card width (the list well's inner width)
      look      a CARD_LOOKS name, or [(look, java boolean), ..., last look name]: the first true condition wins
      lines     [{"id": suffix, "text": java String expression, "kind": label kind, "h": px, "col": kit colour name or
                J(java expr, sample), "wrap": bool, "tag": {"id", "text", "col", "w", "kind"}}] - the label is <card><suffix>; a tag
                is a second, right-aligned label on the same row (<card><tag id>, the row <card><suffix>Row)
      icons     a Java String[] expression (one cell per entry, at most icon_max; icon_item = J(item id of entry k)), or
                icons=None and icon_item = J(one item id): one cell
      on        a Java boolean: false = the coming-later look (grey text, covered icons); None = always on
    The page appends the action column content (card_button / card_state) into ids["act"] afterwards."""
    card, text, act = ids["card"], ids["text"], ids["act"]
    icons_id = ids.get("icons") or card + "Ics"
    tw = card_text_w(w, icon_max)
    decl, bg, bar = _card_look(look, var)
    out = list(decl)
    body = card + "In"
    out.append(SUI.java_append(ids["list"], SUI.group(card, "Left", h=CARD_H, anchor={"bottom": CARD_GAP}), b))
    out.append(SUI.java_append(card, SUI.group(card + "Bar", None, w=CARD_BAR, h=CARD_H, extra="Background: %s" % bar), b))
    out.append(SUI.java_append(card, SUI.group(body, "Left", w=w - CARD_BAR, h=CARD_H, extra="Background: %s" % bg), b))
    out.append(SUI.java_append(body, SUI.group(icons_id, "Left", w=icon_max * CARD_CELL, h=CARD_H), b))
    if icons is None:
        out.append(SUI.java_append(icons_id, _card_cell(card + "F0", icon_item, on), b))
    else:
        out.append("for (int %s = 0; %s < %s.length && %s < %d; %s++) {" % (k, k, icons, k, icon_max, k))
        out.append("  " + SUI.java_append(icons_id, _card_cell(card + "F" + SUI.J(k), icon_item, on), b))
        out.append("}")
    top = SUI.fit([ln["h"] for ln in lines], CARD_H, "card text lines") // 2
    out.append(SUI.java_append(body, SUI.group(text, "Top", w=tw, h=CARD_H, pad={"top": top} if top else None), b))
    sets = []
    for ln in lines:
        lid, col = card + ln["id"], _card_col(ln["col"], on)
        tag = ln.get("tag")
        if tag is None:
            out.append(SUI.java_append(text, SUI.label(lid, "", ln["kind"], h=ln["h"], col=col, wrap=ln.get("wrap", False)), b))
        else:
            row, tid = card + ln["id"] + "Row", card + tag["id"]
            out.append(SUI.java_append(text, SUI.group(row, "Left", h=ln["h"]), b))
            out.append(SUI.java_append(row, SUI.label(lid, "", ln["kind"], w=tw - tag["w"], h=ln["h"], col=col, wrap=False), b))
            out.append(SUI.java_append(row, SUI.label(tid, "", tag.get("kind", "default"), w=tag["w"], h=ln["h"],
                                                      col=_card_col(tag["col"], on), align="End", wrap=False), b))
        sets.append(SUI.java_set(lid, "Text", SUI.J(ln["text"]), b))
        if tag is not None:
            sets.append(SUI.java_set(tid, "Text", SUI.J(tag["text"]), b))
    out.extend(sets)
    out.append(SUI.java_append(body, SUI.group(act, "Top", w=CARD_ACT_W, h=CARD_H, pad={"top": (CARD_H - SUI.BTN_H) // 2,
                                                                                            "left": (CARD_ACT_W - CARD_BTN_W) // 2}), b))
    return "\n".join(out)


def card_button(ident, text, kind="secondary", sound=None):
    """The card's action button: a vanilla normal text button (172 x 44) - append it into the card's action column."""
    return SUI.button(ident, text, kind, w=CARD_BTN_W, sound=sound)


def card_state(text, kind):
    """A state word in the action column instead of a button: Selected / Active = the vanilla success green, Locked / Coming
    soon / Coming later = the vanilla disabled grey (both bold, centred where the button would be)."""
    return SUI.label(None, text, kind, w=CARD_BTN_W, h=SUI.BTN_H, align="Center", bold=True)


def java_block(src, indent):
    """Java statements re-indented by `indent` spaces (for pasting kit output into a method template)."""
    return "\n".join((" " * indent + ln) if ln.strip() else ln for ln in src.split("\n"))


def java_fill(tpl, parts):
    """A Java method template with {{NAME}} placeholders filled with the kit-built Java in parts (each placeholder used at least
    once, none left over)."""
    out = tpl
    for name, java in parts.items():
        tok = "{{" + name + "}}"
        assert tok in out, "unused Java part " + name
        out = out.replace(tok, java)
    left = re.findall(r"\{\{[A-Z0-9]+\}\}", out)
    assert not left, "unfilled Java placeholder: %s" % left
    return out
# ======================================================================= (end of the shared SKYY CARD block)'''
PAGE_BLOCK = r'''# 0.1.3 (the vanilla UI pass): ProfilePage's look = the vanilla UI kit + the shared SKYY CARD above. profile_list_java() and
# profile_create_java() build the markup with kit calls at BUILD time (every value proven by SUI.verify()) and return the Java of
# buildList() / buildCreate(): 0.1.2's statements (state, texts, the event bindings in their order) are kept word for word (the patch
# asserts it); only the appends changed and the texts now go in with b.set (0.1.2 wrote them inline). ONE window size for both views
# (0.1.2's rule): the decorated window, 1100 x 980; the body is 0.1.2's root #SkyyPf, so every old id is unchanged.
PF_W, PF_H = 1100, 980
PF_PREFIX = "SkyyPf"
PF_IDS_012 = {  # every element id of the 0.1.2 views (kept); runtime ids end in 0 / 1
    "list": ["SkyyPf", "SkyyPfCard1", "SkyyPfTxt1", "SkyyPfAct1", "SkyyPfSw1", "SkyyPfNewCard", "SkyyPfNewAct", "SkyyPfNew",
             "SkyyPfInfo", "SkyyPfConfirm", "SkyyPfYes", "SkyyPfNo", "SkyyPfFoot"],
    "create": ["SkyyPf", "SkyyPfNameRow", "SkyyPfName", "SkyyPfCls0", "SkyyPfIco0", "SkyyPfCTx0", "SkyyPfCAct0", "SkyyPfPick0",
               "SkyyPfMakeRow", "SkyyPfMake", "SkyyPfBack", "SkyyPfInfo"]}
PF_SUB_H, PF_INFO_H, PF_END_H = 26, 28, SUI.BTN_H + 16       # list sub line, info line, confirm row / footer (+ margins)
PF_NAME_H, PF_CSUB_H = SUI.BTN_SMALL_H, 44                    # create view: name row (a small button), sub line (two lines)
PF_BUILD_LIST = r"""
public void buildList(@UCB@ b, @UEB@ ev, java.util.UUID u, java.util.Properties p) {
  String act = @PKG@.ProfStore.activeOf(p);
  int n = @PKG@.ProfStore.count(p);
  int max = @PKG@.ProfCfg.MAX_PROFILES;
{{SHELL}}
{{SUB}}
{{LIST}}
  for (int i = 1; i <= @PKG@.ProfCfg.MAX_ID; i++) {
    String id = String.valueOf(i);
    if (!@PKG@.ProfStore.exists(p, id)) continue;
    boolean on = id.equals(act);
    boolean pend = id.equals(this.pending);
    String name = p.getProperty("p." + id + ".name", "Profile " + id);
    String cls = p.getProperty("p." + id + ".class", "");
    String[] ce = @PKG@.ProfRoster.entry(cls);
    String color = ce == null ? "#c9d6e2" : ce[3];
    String line2 = cls.length() == 0 ? "No class - an admin can set it" : cls + " - combat skill " + @PKG@.ProfRoster.skillOf(cls);
    String line3 = "Created " + @PKG@.ProfStore.fmtDate(@PKG@.ProfStore.num(p, "p." + id + ".created")) + " - "
      + (on ? "playing now" : "last played " + @PKG@.ProfStore.fmtAgo(@PKG@.ProfStore.num(p, "p." + id + ".lastPlayed")));
{{CARD}}
    if (on) {
{{ACTIVE}}
    } else {
{{SWITCH}}
      ev.addEventBinding(@BT@.Activating, "#SkyyPfSw" + id, @EVD@.of("a", "pfsw" + id));
    }
  }
  if (n < max) {
{{NEWCARD}}
    ev.addEventBinding(@BT@.Activating, "#SkyyPfNew", @EVD@.of("a", "pfnew"));
  }
{{INFO}}
  if (this.pending != null && @PKG@.ProfStore.exists(p, this.pending) && !this.pending.equals(act)) {
    String pn = p.getProperty("p." + this.pending + ".name", "Profile " + this.pending);
    String pc = p.getProperty("p." + this.pending + ".class", "");
    String q = "Switch to " + pn + (pc.length() > 0 ? " (" + pc + ")" : "") + "? Your inventory is saved and you go to the island of that profile.";
{{CONFIRM}}
    ev.addEventBinding(@BT@.Activating, "#SkyyPfYes", @EVD@.of("a", "pfyes"));
    ev.addEventBinding(@BT@.Activating, "#SkyyPfNo", @EVD@.of("a", "pfno"));
  } else {
    String used = n + " of " + max + " profile slots used.";
    if (n > max) used = n + " profiles - this server now allows " + max + ". You keep them all but cannot create more.";
    String foot = used + " Switching saves your inventory and takes you to the island of the other profile. Not while in combat.";
{{FOOT}}
  }
}"""
PF_BUILD_CREATE = r"""
public void buildCreate(@UCB@ b, @UEB@ ev, java.util.UUID u, java.util.Properties p) {
  String newId = this.first ? "1" : @PKG@.ProfStore.nextId(p);
  if (newId == null) newId = "?";
{{SHELL}}
{{NAMEROW}}
  ev.addEventBinding(@BT@.Activating, "#SkyyPfName", @EVD@.of("a", "pfname"));
  boolean kits = @PKG@.ProfKit.available();
  String sub = "";
  if (this.first) {
    sub = kits ? "Pick your class. It is locked to this profile forever. You get your class kit - its basic weapon - right after creating it. Everything you already have stays on this first profile."
               : "Pick your class. It is locked to this profile forever - like creating a world. Everything you already have stays on this first profile.";
  } else {
    sub = kits ? "Pick your class. It is locked to this profile forever. You get your class kit - its basic weapon - right after creating it. The profile starts from zero with its own island and coins."
               : "Pick a class. It is locked to this profile forever. The new profile starts from zero - empty inventory and its own island and coins and skills.";
  }
{{SUB}}
{{LIST}}
  java.util.ArrayList r = @PKG@.ProfRoster.roster();
  int shown = r.size() < MAX_CARDS ? r.size() : MAX_CARDS;
  for (int i = 0; i < shown; i++) {
    String[] c = (String[]) r.get(i);
    boolean on = "1".equals(c[6]);
    boolean sel = this.pickClass != null && c[0].equalsIgnoreCase(this.pickClass);
    String role = c.length > 7 && c[7] != null ? c[7] : "";
    String[] ic = c[5].split(",");
    String title = c[0] + (sel ? " - selected" : (on ? "" : " - coming later"));
{{CARD}}
    if (!on) {
{{LATER}}
    } else if (sel) {
{{SELECTED}}
    } else {
{{SELECT}}
      ev.addEventBinding(@BT@.Activating, "#SkyyPfPick" + i, @EVD@.of("a", "pfcls" + i));
    }
  }
  String q = this.pickClass == null ? "Select a class to continue."
    : "Create " + this.pickName + " as " + @PKG@.ProfRoster.article(this.pickClass) + "? The class can never be changed.";
  if (this.pickClass != null) {
    if (this.first) {
{{MAKEFIRST}}
    } else {
{{MAKE}}
    }
    ev.addEventBinding(@BT@.Activating, "#SkyyPfMake", @EVD@.of("a", "pfmake"));
  } else {
    if (this.first) {
{{WAITFIRST}}
    } else {
{{WAIT}}
    }
  }
  ev.addEventBinding(@BT@.Activating, "#SkyyPfBack", @EVD@.of("a", "pfback"));
{{INFO}}
}"""


def pf_ids_kept(java, view):
    """Every 0.1.2 element id of that view is still created (runtime ids: "#<id>" + (i) / + (id))."""
    for ident in PF_IDS_012[view]:
        base = ident[:-1]
        ok = ("#%s {" % ident) in java or ('#%s" + (i)' % base) in java or ('#%s" + (id)' % base) in java
        assert ok, "0.1.3 dropped the 0.1.2 element id #%s (%s view)" % (ident, view)


def pf_row(body, box, question, yes, no, yes_text, no_text, yes_w, no_w, yes_on=True, ask=True, wrap=False):
    """An in-page question row = the kit's confirm_view(compact=True) with the page's old ids. yes_on=False = the yes button in the
    vanilla Disabled look (unbound: nothing is selected yet); ask=False = the line in the plain label colour (a hint, not a
    question); wrap=True = the question wraps to two lines (a long question).
    Review fix: every rewrite asserts that it found exactly ONE kit markup to replace, in the shape it expects (a label / a
    Primary button under the kit's own anchor), so a later kit revision of confirm_view(compact=True) stops the build instead of
    silently leaving an enabled-looking Create profile or an unwrapped question."""
    q = box + "Q"
    part = SUI.confirm_view(body, box, PF_W - 2 * SUI.CONTENT_PAD, question=question, yes_text=yes_text, no_text=no_text,
                            yes_w=yes_w, no_w=no_w, compact=True, top=8, ids={"box": box, "question": q, "yes": yes, "no": no})
    want_q, want_y = (wrap or not ask), (not yes_on)
    hits_q = [n for n, (_p, mk) in enumerate(part) if re.search(r"#%s\s*\{" % q, mk)]
    hits_y = [n for n, (_p, mk) in enumerate(part) if re.search(r"#%s\s*\{" % yes, mk)]
    assert len(hits_q) == 1 and len(hits_y) == 1, "confirm_view(compact) changed: %d question / %d yes markups for #%s" % (
        len(hits_q), len(hits_y), box)
    if want_q:
        n = hits_q[0]
        parent, mk = part[n]
        assert parent == box and mk.startswith("Label #%s { Anchor: (Width: " % q) and "Height: %d" % SUI.BTN_H in mk, \
            "confirm_view(compact) question markup changed: %s" % mk[:120]
        qw = int(re.match(r"Label #%s \{ Anchor: \(Width: (\d+)," % q, mk).group(1))      # the kit's own question width
        part[n] = (parent, SUI.label(q, "", "bold", w=qw, h=SUI.BTN_H, col="warning" if ask else "text", wrap=wrap))
        assert ("Wrap: true" in part[n][1]) == bool(wrap), "the question label did not take wrap=%s" % wrap
    if want_y:
        n = hits_y[0]
        parent, mk = part[n]
        kit_yes = SUI.button(yes, yes_text, "primary", w=yes_w, sound="save", anchor={"left": 6})
        assert parent == box and mk == kit_yes, "confirm_view(compact) yes button changed: %s" % mk[:120]
        part[n] = (parent, SUI.button(yes, yes_text, "primary", w=yes_w, disabled=True, anchor={"left": 6}))
        assert ('Default: (Background: (TexturePath: "%s"' % SUI.TEX["btnDisabled"]) in part[n][1] and "Sounds:" not in part[n][1], \
            "the greyed yes button is not the kit's silent Disabled look"
    return part


def profile_list_java():
    """ProfilePage.buildList(): PF_BUILD_LIST with its {{parts}} built from kit calls; the list well fills the body."""
    sh = SUI.page_shell("SkyyPfF", PF_W, PF_H, "Profiles", body_id="SkyyPf")
    body, W = sh.body, sh.inner_w
    list_h = sh.inner_h - (PF_SUB_H + 10) - (8 + PF_INFO_H) - (8 + PF_END_H)
    assert list_h >= card_list_h(6), "the list well must hold 6 profile cards (%d px)" % list_h
    assert sh.fit([PF_SUB_H + 10, list_h, 8 + PF_INFO_H, 8 + PF_END_H]) == 0
    cw = W - 2 * CARD_LIST_PAD
    ident = SUI.J("id", "1")
    act = "SkyyPfAct" + ident
    ids = {"list": "SkyyPfList", "card": "SkyyPfCard" + ident, "text": "SkyyPfTxt" + ident, "act": act}
    name_col = SUI.J('on ? "%s" : "%s"' % (SUI.COLOR["success"], SUI.COLOR["rowName"]), SUI.COLOR["success"])
    lines = [{"id": "Nm", "text": 'safe(name + (on ? " - ACTIVE" : ""))', "kind": "rowName", "h": 24, "col": name_col},
             {"id": "L2", "text": "safe(line2)", "kind": "fieldLabel", "h": 20, "col": SUI.J("color", CLASSES[0]["color"])},
             {"id": "L3", "text": "safe(line3)", "kind": "rowSub", "h": 20, "col": "rowSub"}]
    sw = "SkyyPfSw" + ident
    new_ids = {"list": "SkyyPfList", "card": "SkyyPfNewCard", "text": "SkyyPfNewTxt", "act": "SkyyPfNewAct"}
    new_lines = [{"id": "Tx", "text": 'safe("Empty slot - a new profile starts from zero with the class you pick (" + (max - n) + " free)")',
                  "kind": "default", "h": 44, "col": "text", "wrap": True}]
    foot = SUI.label("SkyyPfFoot", "", "caption", h=PF_END_H, align="Center", wrap=True, anchor={"top": 8})
    confirm = pf_row(body, "SkyyPfConfirm", SUI.J("safe(q)"), "SkyyPfYes", "SkyyPfNo", "Confirm", "Cancel", 180, 180, wrap=True)
    assert confirm.h == 8 + PF_END_H
    sub = SUI.Appends()
    sub.text(body, "SkyyPfSub", "Each profile is its own save - class, island, coins, skills, bags and inventory.", "default",
             h=PF_SUB_H, align="Center", anchor={"bottom": 10})
    parts = {
        "SHELL": sh.java("b"),
        "SUB": sub.java("b"),
        "LIST": SUI.java_append(body, card_list("SkyyPfList", list_h)),
        "CARD": card_java(ids, cw, [("selected", "on"), ("pending", "pend"), "normal"], lines,
                          icon_item=SUI.J("safe(@PKG@.ProfRoster.iconOf(cls))", CLASSES[0]["icons"][0]), icon_max=1),
        "ACTIVE": SUI.java_append(act, card_state("Active", "success")),
        "SWITCH": SUI.java_append(act, SUI.choose(SUI.J("pend"), card_button(sw, "Switch", "primary"), card_button(sw, "Switch"))),
        "NEWCARD": "\n".join([card_java(new_ids, cw, "empty", new_lines, icon_item=SUI.J("@PKG@.ProfRoster.NEW_ICON", NEW_ICON),
                                        icon_max=1, var="newCard"),
                              SUI.java_append("SkyyPfNewAct", card_button("SkyyPfNew", "Create new", "primary"))]),
        "INFO": "\n".join([SUI.java_append(body, SUI.label("SkyyPfInfo", "", "info", h=PF_INFO_H, bold=True, align="Center",
                                                            anchor={"top": 8})),
                           SUI.java_set("SkyyPfInfo", "Text", SUI.J("safe(this.info)"))]),
        "CONFIRM": confirm.java("b"),
        "FOOT": "\n".join([SUI.java_append(body, foot), SUI.java_set("SkyyPfFoot", "Text", SUI.J("safe(foot)"))]),
    }
    sh.appends.check(PF_PREFIX)
    indent = {"SHELL": 2, "SUB": 2, "LIST": 2, "CARD": 4, "ACTIVE": 6, "SWITCH": 6, "NEWCARD": 4, "INFO": 2, "CONFIRM": 4, "FOOT": 4}
    java = java_fill(PF_BUILD_LIST, dict((k, java_block(v, indent[k])) for k, v in parts.items()))
    pf_ids_kept(java, "list")
    return java, sh


def profile_create_java():
    """ProfilePage.buildCreate(): PF_BUILD_CREATE with its {{parts}} built from kit calls. The list well holds MAX_CARDS cards
    (0.1.2 drew at most 8 - its 'tight' variant is not needed any more); the heights fill the body exactly (asserted)."""
    heights = [PF_NAME_H + 8, PF_CSUB_H + 8, card_list_h(MAX_CARDS), 8 + PF_END_H, 8 + PF_INFO_H]
    sh = SUI.page_shell("SkyyPfF", PF_W, PF_H, SUI.J('this.first ? "Create your first profile" : "Create a new profile"'),
                        body_id="SkyyPf")
    assert sh.fit(heights) == 0, "the Create Profile body must be filled exactly"
    body, W = sh.body, sh.inner_w
    cw = W - 2 * CARD_LIST_PAD
    i = SUI.J("i")
    act = "SkyyPfCAct" + i
    ids = {"list": "SkyyPfList", "card": "SkyyPfCls" + i, "icons": "SkyyPfIco" + i, "text": "SkyyPfCTx" + i, "act": act}
    ccol = SUI.J("c[3]", CLASSES[0]["color"])
    icon_max = 3                                  # 0.1.2 drew at most 3 weapon icons per card (the fallback table has 1-3)
    tw = card_text_w(cw, icon_max)
    lines = [{"id": "Nm", "text": "safe(title)", "kind": "rowName", "h": 24, "col": ccol,
              "tag": {"id": "Rl", "text": "safe(role)", "col": ccol, "w": tw // 2, "kind": "default"}},
             {"id": "Sk", "text": 'safe("Combat skill " + c[1] + " - " + c[4])', "kind": "fieldLabel", "h": 20, "col": "value"},
             {"id": "Ds", "text": "safe(c[2])", "kind": "rowSub", "h": 40, "col": "rowSub", "wrap": True}]
    pick = "SkyyPfPick" + i
    name_w = W - SUI.BTN_MIN_W - 12
    row = SUI.Appends()
    row.append((body, SUI.group("SkyyPfNameRow", "Left", h=PF_NAME_H, anchor={"bottom": 8})))
    row.append(("SkyyPfNameRow", SUI.label("SkyyPfNameTx", "", "heading", w=name_w, h=PF_NAME_H, wrap=False, anchor={"right": 12})))
    row.append(("SkyyPfNameRow", SUI.button("SkyyPfName", "Other name", "secondary", "small", w=SUI.BTN_MIN_W)))
    row.sets.append(("SkyyPfNameTx", "Text", SUI.J('safe("Profile " + newId + " will be called " + this.pickName)')))
    sub = SUI.label("SkyyPfCSub", "", "default", h=PF_CSUB_H, align="Center", wrap=True, anchor={"bottom": 8})

    def make(no_text, picked):
        # wrap=True (review fix, second pass: the page-state harness measured "Create <32-letter name> as a Berserker? ..." at 701 px
        # in the 650 px one-line question; the switch question already wraps - two 16 px lines fit the 44 px row)
        return pf_row(body, "SkyyPfMakeRow", SUI.J("safe(q)"), "SkyyPfMake", "SkyyPfBack", "Create profile", no_text, 200, 180,
                      yes_on=picked, ask=picked, wrap=True).java("b")
    parts = {
        "SHELL": sh.java("b"),
        "NAMEROW": row.java("b"),
        "SUB": "\n".join([SUI.java_append(body, sub), SUI.java_set("SkyyPfCSub", "Text", SUI.J("safe(sub)"))]),
        "LIST": SUI.java_append(body, card_list("SkyyPfList", card_list_h(MAX_CARDS))),
        "CARD": card_java(ids, cw, [("selected", "sel"), ("normal", "on"), "off"], lines, icons="ic",
                          icon_item=SUI.J("safe(ic[k])", CLASSES[0]["icons"][0]), icon_max=icon_max, on="on"),
        "LATER": SUI.java_append(act, card_state("Coming later", "disabled")),
        "SELECTED": SUI.java_append(act, card_state("Selected", "success")),
        "SELECT": SUI.java_append(act, card_button(pick, "Select")),
        "MAKEFIRST": make("Later", True), "MAKE": make("Back", True),
        "WAITFIRST": make("Later", False), "WAIT": make("Back", False),
        "INFO": "\n".join([SUI.java_append(body, SUI.label("SkyyPfInfo", "", "info", h=PF_INFO_H, bold=True, align="Center",
                                                            anchor={"top": 8})),
                           SUI.java_set("SkyyPfInfo", "Text", SUI.J("safe(this.info)"))]),
    }
    sh.appends.check(PF_PREFIX)
    indent = {"SHELL": 2, "NAMEROW": 2, "SUB": 2, "LIST": 2, "CARD": 4, "LATER": 6, "SELECTED": 6, "SELECT": 6, "MAKEFIRST": 6,
              "MAKE": 6, "WAITFIRST": 6, "WAIT": 6, "INFO": 2}
    java = java_fill(PF_BUILD_CREATE, dict((k, java_block(v, indent[k])) for k, v in parts.items()))
    pf_ids_kept(java, "create")
    return java, sh


PF_LIST_JAVA, PF_LIST_SHELL = profile_list_java()
PF_CREATE_JAVA, PF_CREATE_SHELL = profile_create_java()
print("profiles page %dx%d (body %dx%d): list view + Create Profile (%d class cards), kit %s"
      % (PF_W, PF_H, PF_LIST_SHELL.inner_w, PF_LIST_SHELL.inner_h, MAX_CARDS, SUI.kit_id()))'''
CARD_SHA = "85a047857ef2762641fb7045aee6f5ce9acd4e1ded05f55ba4a2a7496445f7d5"     # the SAME value in tools/classes_0_1_8_patch.py: the card block is one component in both mods
assert hashlib.sha256(CARD_BLOCK.encode("utf8")).hexdigest() == CARD_SHA, "the SKYY CARD block differs from SkyyClasses 0.1.8's"
rep("@@CARD_AND_PAGE@@", CARD_BLOCK + "\n" + PAGE_BLOCK + "\n")
rep("@@VIEWS@@", "M(page, PF_LIST_JAVA)\nM(page, PF_CREATE_JAVA)\n")

# 0.1.2's buildList() / buildCreate() statements that are not markup must all be in the 0.1.3 templates, word for word
_i = OLD_VIEWS.index('M(page, ui(r"""\npublic void buildCreate(')
_old = {"list": OLD_VIEWS[:_i].split(LF)[1:], "create": OLD_VIEWS[_i:].split(LF)[1:]}
_drop = ("b.appendInline(", 'String bs = "__BTN__";', 'String go = "__BTNGO__";', "String bg = ", 'String cid = "#SkyyPf',
         'String iid = "#SkyyPf', 'String tid = "#SkyyPf', 'String aid = "#SkyyPf', '}"""))', "boolean tight = ", "int ch = tight",
         "int gap = tight", "int tp = tight", "int t1 = tight", "int t4 = tight", "int it = (ch", "int at = (ch")
for _view, _name in (("list", "PF_BUILD_LIST"), ("create", "PF_BUILD_CREATE")):
    kept = [ln for ln in _old[_view] if ln.strip() and not any(d in ln for d in _drop)]
    if _view == "create":      # the weapon icon loop is markup now (the card component emits it): its header and closing brace go
        kept.remove("    for (int k = 0; k < ic.length && k < 3; k++) {")
        kept.remove("    }")
    tpl = PAGE_BLOCK[PAGE_BLOCK.index(_name + ' = r"""'):].split('}"""', 1)[0].split(LF)
    missing = collections.Counter(kept) - collections.Counter(tpl)
    assert not missing, "0.1.2 %s lines missing from the 0.1.3 template: %s" % (_view, list(missing))
    old_b = [ln for ln in _old[_view] if "ev.addEventBinding(" in ln]
    assert [ln for ln in tpl if "ev.addEventBinding(" in ln] == old_b, "%s: binding lines or their order changed" % _view
    assert len(kept) >= 25, (_view, len(kept))

# ================================================================================================ ready log line: the kit id
rep('log("[SkyyProfiles] __VER__ ready - /profiles, /profileadmin; " + cfgText',
    'log("[SkyyProfiles] __VER__ ready (__KIT__) - /profiles, /profileadmin; " + cfgText')
rep('''  @PKG@.CfgPub.start(getDataDirectory().getParent(), getLogger());
}""".replace("__VER__", VERSION))''', '''  @PKG@.CfgPub.start(getDataDirectory().getParent(), getLogger());
}""".replace("__VER__", VERSION).replace("__KIT__", KIT_ID))''')

# ================================================================================================ checks on the result
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
for k in KEEP:
    assert k in s, "a block that must stay 0.1.2's changed: %s" % k[:80]
_page = s[s.index("# ================= ProfilePage: Profiles list (view 0)"):s.index('M(page, r"""\npublic void build(@REF@ ref')]
for c in ("#0b1524", "#d08a4a", "#ffe9c9", "#9fb8cc", "#173524", "#3a2f1a", "#142030", "#0d1219", "#5f6b78", "#9fd8a2",
          "#8fa4b8", "#ffd27a", "#5a4420", "#8a6a30", "#3a2a10", "#2f6a3a", "#3f8a4a", "#1f4a2a", "#e9ffe9", "TextButtonStyle(Default: (Background: #",
          "__BTN__", "__C", "__L"):
    assert c not in _page, "0.1.2 custom look left in the 0.1.3 page: " + c
assert "import skyyui as SUI" in s and s.index("SUI.verify()") < s.index("J = B.start()"), "verify() must run before the build"
assert s.index("def card_java(") < s.index("PF_CREATE_JAVA, PF_CREATE_SHELL = profile_create_java()") < s.index("M(page, PF_CREATE_JAVA)")
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.2 had %d)" % (s.count(LF), OLD.count(LF)))
