"""Derive SkyyProfiles/build_skyyprofiles_0.1.6.py from the LIVE 0.1.5 (build_skyyprofiles_0.1.5.py = the tools/deploy_set.py SET pin).
Run:  python tools/profiles_0_1_6_patch.py   then   python SkyyProfiles/build_skyyprofiles_0.1.6.py   (never --deploy: coordinated deploy)
Patch chain: 0.1 -> 0.1.1 (copy + edit) -> profiles_0_1_2_patch.py -> ... -> profiles_0_1_5_patch.py -> 0.1.5 -> THIS patch -> 0.1.6.
Edit THIS file, never the generated build script. Harness: python SkyyProfiles/test_skyyprofiles_0.1.6.py.

0.1.6 = THE CREATE PROFILE PAGE KNOWS THE ASSASSIN + MONK (Skyy LOCKED 2026-10-07 "1. make the classes"; deploy WITH SkyyClasses 0.1.14,
SkySkills 0.4.21). WHY THIS MOD: with SkyyClasses 0.1.14's class:list (Archer ... Priest, Assassin, Monk) a 0.1.5 roster
(fallback Archer, Warrior, Mage, Berserker, Priest, Assassin, SHAMAN + every unknown class:list name as an extra card) would draw 8 cards
and the Create Profile page shows 7 (MAX_CARDS) - the Monk would be the 8th card, never drawn, never pickable.
  - The fallback roster (the card texts; class:list still decides what is selectable): Assassin playable (role Priority killer, its
    text), the Shaman entry is the MONK (skill Discipline, colour #f08a30, the two vanilla Bo staff icons, role Self-speed disruptor) -
    the same texts as SkyyClasses 0.1.14's cards. 7 cards = MAX_CARDS: every class fits.
  - "Shaman" is an ALIAS of the Monk (ProfRoster.canon): a players file whose profile says p.<id>.class=Shaman (/profileadmin setclass
    allowed it) shows the Monk card and PUBLISHES profile:class:<uuid> = Monk (and Monk in profile:list) - the file itself is not
    rewritten (a fix that only renames). /profileadmin setclass <player> <n> shaman stores Monk. A class:list entry "Shaman" turns the
    Monk card on (an older SkyyClasses).
  - The automatic profile limit (maxProfiles=auto = one per class in class:list) becomes 7 by itself with SkyyClasses 0.1.14 (it was 5)
    - the 0.1.4 design ("6 / 7 by itself when Assassin / Shaman open"); a fixed number is unchanged. No setting is changed.
  - Texts: the setclass argument help, the manifest description.
Nothing else changes: no command / binding / system / bridge key / file / setting added or removed; the SKYY CARD block is untouched.
"""
import hashlib
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.5.py")
dst = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.6.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1.5"' in s and "GENERATED by tools/profiles_0_1_5_patch.py from build_skyyprofiles_0.1.4.py" in s, \
    "build_skyyprofiles_0.1.5.py is not the live 0.1.5"
REG0 = s.count("registerCommand(")
BIND0 = [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln]
SYS0 = [ln for ln in s.split(LF) if "registerSystem(" in ln]
CARD_START = "# =====================================================================================================================\n# SKYY CARD"
CARD_END = "# ======================================================================= (end of the shared SKYY CARD block)"
CARD_SHA = "bf659e0208b537a81ac8758d909f81976f03069816ea9dddb300f843a7eaa028"   # = profiles_0_1_4 / classes_0_1_9..14 patches


def rep(old, new, count=1):
    global s
    n = s.count(old)
    assert n == count, "anchor count %d (want %d): %s" % (n, count, old[:120])
    s = s.replace(old, new)


def block(a, b):
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


_card = block(CARD_START, CARD_END) + CARD_END
assert hashlib.sha256(_card.encode("utf8")).hexdigest() == CARD_SHA, "the SKYY CARD block is not the shared one"

# ================================================================================================ docstring, version
rep('''"""SkyyProfiles 0.1.5 - build script (javassist via jpype). SkyBlock-style profiles for SkyWynn = the class selector.
Run:   python build_skyyprofiles_0.1.5.py          -> SkyyProfiles/SkyyProfiles-0.1.5.jar''',
    '''"""SkyyProfiles 0.1.6 - build script (javassist via jpype). SkyBlock-style profiles for SkyWynn = the class selector.
Run:   python build_skyyprofiles_0.1.6.py          -> SkyyProfiles/SkyyProfiles-0.1.6.jar''')
rep('''GENERATED by tools/profiles_0_1_5_patch.py from build_skyyprofiles_0.1.4.py (generated by tools/profiles_0_1_4_patch.py from 0.1.3,''',
    '''GENERATED by tools/profiles_0_1_6_patch.py from build_skyyprofiles_0.1.5.py (generated by tools/profiles_0_1_5_patch.py from 0.1.4,
generated by tools/profiles_0_1_4_patch.py from 0.1.3,''')
rep('''Harness: python SkyyProfiles/test_skyyprofiles_0.1.5.py
''', '''Harness: python SkyyProfiles/test_skyyprofiles_0.1.6.py

0.1.6 (2026-10-07, Skyy LOCKED "1. make the classes"): the Create Profile cards know the ASSASSIN (playable) and the MONK (the old Shaman
  slot: Discipline, #f08a30, Bo staffs). "Shaman" is an alias of the Monk (ProfRoster.canon): an old p.<id>.class=Shaman shows and
  publishes as Monk (file not rewritten); setclass shaman stores Monk. With SkyyClasses 0.1.14 the auto limit is 7. Full notes in
  tools/profiles_0_1_6_patch.py. Deploy WITH SkyyClasses 0.1.14.
''')
rep('VERSION = "0.1.5"', 'VERSION = "0.1.6"')

# ================================================================================================ the fallback roster
ASSASSIN_DESC = "Burst damage on one target. Fast twin daggers up close and kunai thrown from range - strike from behind for more."
MONK_DESC = "Fast melee fighter. A bo staff strikes with reach - quick hand wraps and heavy gauntlets."
rep('''    {"name": "Assassin", "skill": "Assassination", "color": "#b58cff", "enabled": False, "role": "Fast burst damage",
     "desc": "Coming later. Fast and deadly with twin daggers and kunai throwing knives.",
     "icons": ["Weapon_Daggers_Iron", "Weapon_Kunai"], "weapon_text": "Daggers / Kunai"},
    {"name": "Shaman", "skill": "Shaman skill", "color": "#ff7a5c", "enabled": False, "role": "Designed later",
     "desc": "Coming later. The fifth Wynncraft class - it gets its own custom weapon.",
     "icons": ["Weapon_Deployable_Slowness_Totem"], "weapon_text": "Custom weapon later"},''',
    '''    # 0.1.6 (Skyy LOCKED 2026-10-07 "make the classes"): Assassin playable; the Shaman slot is the MONK (= SkyyClasses 0.1.14's cards)
    {"name": "Assassin", "skill": "Assassination", "color": "#b58cff", "enabled": True, "role": "Priority killer",
     "desc": "%s",
     "icons": ["Weapon_Daggers_Iron", "Weapon_Kunai"], "weapon_text": "Daggers / Kunai"},
    {"name": "Monk", "skill": "Discipline", "color": "#f08a30", "enabled": True, "role": "Self-speed disruptor",
     "desc": "%s",
     "icons": ["Weapon_Staff_Bo_Wood", "Weapon_Staff_Bo_Bamboo"], "weapon_text": "Bo Staves / Wraps / Gauntlets"},''' % (ASSASSIN_DESC, MONK_DESC))
rep('''UI_DATA_COLORS = ["#8fd67a", "#e0b060", "#7fb0e0", "#d9443f", "#f2e6a0", "#b58cff", "#ff7a5c", "#c9d6e2"]''',
    '''UI_DATA_COLORS = ["#8fd67a", "#e0b060", "#7fb0e0", "#d9443f", "#f2e6a0", "#b58cff", "#f08a30", "#c9d6e2"]''')
rep('''need([c["name"] for c in CLASSES] == ["Archer", "Warrior", "Mage", "Berserker", "Priest", "Assassin", "Shaman"], "fallback roster order (spec 4.1)")
need([c["name"] for c in CLASSES if c["enabled"]] == ["Archer", "Warrior", "Mage", "Berserker", "Priest"], "launch roster (Skyy 2026-09-25)")''',
    '''need([c["name"] for c in CLASSES] == ["Archer", "Warrior", "Mage", "Berserker", "Priest", "Assassin", "Monk"], "fallback roster order (0.1.6: Shaman -> Monk)")
need(all(c["enabled"] for c in CLASSES), "0.1.6: all seven playable (Skyy LOCKED 2026-10-07)")
need(len(CLASSES) == MAX_CARDS, "0.1.6: the seven classes fill the Create Profile page's seven cards")
# 0.1.6: old class names -> today's (ProfRoster.canon; any case, trimmed). Nothing is rewritten: reads, publishes and new writes use it.
CLASS_ALIASES = [("Shaman", "Monk"), ("Shamans", "Monk"), ("Shaman skill", "Monk")]
need(all(n in [c["name"] for c in CLASSES] and a not in [c["name"] for c in CLASSES] for a, n in CLASS_ALIASES), "aliases name a class")
# 0.1.6: the fallback = SkyyClasses 0.1.14's cards (name, skill, colour, role, text) - checked against its build script when it is here
_cs14 = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "SkyyClasses", "build_skyyclasses_0.1.14.py")
if os.path.isfile(_cs14):
    _ct = open(_cs14, encoding="utf8").read()
    for _c in CLASSES[5:]:
        need(('"name": "%s", "skill": "%s", "color": "%s", "enabled": True, "role": "%s"' % (_c["name"], _c["skill"], _c["color"], _c["role"])) in _ct
             and ('"desc": "%s"' % _c["desc"]) in _ct, "the %s card = SkyyClasses 0.1.14's" % _c["name"])''')

# ================================================================================================ ProfRoster: the alias
rep('''F(ros, "public static final String EXTRA_DESC = %s;" % jstr(EXTRA_DESC))
''', '''F(ros, "public static final String EXTRA_DESC = %s;" % jstr(EXTRA_DESC))
F(ros, "public static final String[] ALIAS_FROM = %s;" % jarr([a for a, _ in CLASS_ALIASES]))     # 0.1.6
F(ros, "public static final String[] ALIAS_TO = %s;" % jarr([n for _, n in CLASS_ALIASES]))
# 0.1.6: an old class name -> today's ("Shaman" -> "Monk"), anything else as it is (null stays null)
M(ros, r"""
public static String canon(String c) {
  if (c == null) return null;
  String t = c.trim();
  for (int i = 0; i < ALIAS_FROM.length && i < ALIAS_TO.length; i++) if (ALIAS_FROM[i].equalsIgnoreCase(t)) return ALIAS_TO[i];
  return c;
}""")
''')
rep('''public static int indexOf(String s) {
  if (s == null) return -1;
  s = s.trim();
  for (int i = 0; i < NAMES.length; i++) if (NAMES[i].equalsIgnoreCase(s)) return i;''', '''public static int indexOf(String s) {
  if (s == null) return -1;
  s = canon(s.trim());
  for (int i = 0; i < NAMES.length; i++) if (NAMES[i].equalsIgnoreCase(s)) return i;''')
rep('''        String[] nv = parts[k].split(":");
        if (nv.length > 0 && nv[0].trim().equalsIgnoreCase(NAMES[i])) {''', '''        String[] nv = parts[k].split(":");
        if (nv.length > 0 && canon(nv[0].trim()).equalsIgnoreCase(NAMES[i])) {''')
rep('''public static String[] entry(String name) {
  if (name == null) return null;
  String s = name.trim();''', '''public static String[] entry(String name) {
  if (name == null) return null;
  String s = canon(name.trim());''')

# ================================================================================================ the reads that show / publish a class
rep('''    sb.append(id).append(":").append(p.getProperty("p." + id + ".name", "")).append(":").append(p.getProperty("p." + id + ".class", ""));''',
    '''    sb.append(id).append(":").append(p.getProperty("p." + id + ".name", "")).append(":").append(@PKG@.ProfRoster.canon(p.getProperty("p." + id + ".class", "")));''')
rep('''    String c = p.getProperty("p." + a + ".class", "");
    if (c.length() > 0) b.put("profile:class:" + us, c); else b.remove("profile:class:" + us);''',
    '''    String c = @PKG@.ProfRoster.canon(p.getProperty("p." + a + ".class", ""));   // 0.1.6: an old Shaman profile publishes Monk
    if (c.length() > 0) b.put("profile:class:" + us, c); else b.remove("profile:class:" + us);''')
rep('''    String c = p.getProperty("p." + id + ".class", "");
    String nm = p.getProperty("p." + id + ".name", "?");''', '''    String c = @PKG@.ProfRoster.canon(p.getProperty("p." + id + ".class", ""));
    String nm = p.getProperty("p." + id + ".name", "?");''')
rep('''    String cls = p.getProperty("p." + id + ".class", "");
    String[] ce = @PKG@.ProfRoster.entry(cls);''', '''    String cls = @PKG@.ProfRoster.canon(p.getProperty("p." + id + ".class", ""));
    String[] ce = @PKG@.ProfRoster.entry(cls);''')
rep('''    String pc = p.getProperty("p." + this.pending + ".class", "");''',
    '''    String pc = @PKG@.ProfRoster.canon(p.getProperty("p." + this.pending + ".class", ""));''')
rep('''    String cls = p.getProperty("p." + act + ".class", "");
    if (@PKG@.ProfCfg.notifyOn(u, "profiles.loginStatus"))''', '''    String cls = @PKG@.ProfRoster.canon(p.getProperty("p." + act + ".class", ""));
    if (@PKG@.ProfCfg.notifyOn(u, "profiles.loginStatus"))''')

# ================================================================================================ texts
rep('''  this.classArg = withRequiredArg("class", "archer | warrior | mage | berserker | priest (assassin, shaman later)", @ATY@.STRING);''',
    '''  this.classArg = withRequiredArg("class", "archer | warrior | mage | berserker | priest | assassin | monk", @ATY@.STRING);''')
rep('''class (Archer, Warrior, Mage, Berserker or Priest; picked at creation''',
    '''class (Archer, Warrior, Mage, Berserker, Priest, Assassin or Monk; picked at creation''')

# ================================================================================================ checks
assert s.count("registerCommand(") == REG0, "command registrations changed"
assert [ln for ln in s.split(LF) if "ev.addEventBinding(" in ln] == BIND0, "event bindings changed"
assert [ln for ln in s.split(LF) if "registerSystem(" in ln] == SYS0, "system registrations changed"
_card2 = block(CARD_START, CARD_END) + CARD_END
assert _card2 == _card, "the SKYY CARD block must stay the shared one"
assert s.index("public static String canon(") < s.index("public static int indexOf(String s)") < s.index("public static java.util.ArrayList roster()")
assert s.index("public static String canon(") < s.index("@PKG@.ProfRoster.canon(p.getProperty(")
assert '"Shaman"' not in s.split("CLASS_ALIASES = ")[0].split("CLASSES = [")[1].split("UI_DATA_COLORS")[0], "the roster has no Shaman entry"
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst, "(%d lines; 0.1.5 had %d)" % (s.count(LF), OLD.count(LF)))
