"""Derive SkyyProfiles/build_skyyprofiles_0.1.2.py from 0.1.1 (run: python tools/profiles_0_1_2_patch.py, then build the 0.1.2 script).
Start of the SkyyProfiles patch chain (0.1.1 was a copy + edit of 0.1): edit THIS file, never the generated build script.
Spec: research/Classes-Berserker-Priest-Spec.md section 4 (Berserker + Priest + class kits, Skyy 2026-09-25). Built with SkyyClasses 0.1.6
and SkyySkills 0.4.4 - deploy the three together (0.1.1 draws at most 6 class cards: with SkyyClasses 0.1.6 Priest would be hidden).
0.1.2:
 - ROSTER (fallback table; class:list decides what is selectable when SkyyClasses is present): Archer, Warrior, Mage, Berserker (Fury),
   Priest (Divinity) selectable; Assassin, Shaman "coming later". Texts, colors, icons = SkyyClasses 0.1.6 (spec 2.1). Entries grow to
   8 fields, role at index 7 (Priest = "AoE healer / support"; extras from class:list get "A class from SkyyClasses").
 - CREATE PROFILE PAGE: MAX_CARDS = 8 (drawing + pfcls<i> handling), a role line per card, one root 1000 x 900 for both views (fits 1080);
   list view scaled ~1.2x. Layout numbers are build constants (CL / LL) and the build checks they fit the 968 x 880 content box.
 - CLASS KIT HAND-OFF: ProfKit.kitNew -> bridge class:fn:kitnew (SkyyClasses 0.1.6) after ProfStore.create + publish, outside every
   SkyyProfiles monitor: createFirst (key = uuid) and createAndSwitch (key = keyFor(uuid, id), BEFORE switchTo). Absent = nothing; any
   answer but TRUE or an exception = one WARN per JVM + a KIT-MISSED line in switches.log for EVERY miss (the admin's list for
   /classadmin kit). Never from /profileadmin setclass (its reply points at /classadmin kit).
 - "Create profile" is ONE create per selection (review fix): the pfmake handler takes the selection before any create work and only
   puts it back where the create form shows again with nothing created; the first-profile form never creates a second profile.
 - Texts: setclass class help, manifest description; the Create page sub line mentions the kit while class:fn:kitnew exists.
No new config rows, Settings switches or files; players files unchanged (switches.log gains KIT-MISSED lines).
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.1.py")
dst = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.2.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:100])
    s = s.replace(old, new, 1)


def rep_between(start, end, new):
    """Replace the text from `start` (unique) up to, not including, the first `end` after it."""
    global s
    n = s.count(start)
    assert n == 1, "start anchor count %d: %s" % (n, start[:100])
    a = s.index(start)
    b = s.find(end, a + len(start))
    assert b > a, "end anchor not found after start: %s" % end[:100]
    s = s[:a] + new + s[b:]


# ---------------------------------------------------------------- version + docstring
rep('VERSION = "0.1.1"', 'VERSION = "0.1.2"')
rep('"""SkyyProfiles 0.1.1 - build script (javassist via jpype).', '"""SkyyProfiles 0.1.2 - build script (javassist via jpype).')
rep("Run:   python build_skyyprofiles_0.1.1.py          -> SkyyProfiles/SkyyProfiles-0.1.1.jar",
    "Run:   python build_skyyprofiles_0.1.2.py          -> SkyyProfiles/SkyyProfiles-0.1.2.jar")
rep("Derived by copy + edit from build_skyyprofiles_0.1.py (0.1 has no patch script). Everything below the 0.1.1 block is the 0.1 design," + LF +
    "unchanged unless a line says 0.1.1." + LF,
    "GENERATED by tools/profiles_0_1_2_patch.py from build_skyyprofiles_0.1.1.py - edit the patch, never this file (0.1.1 was a copy + edit" + LF +
    "of 0.1). Everything below the 0.1.2 and 0.1.1 blocks is the 0.1 design, unchanged unless a line says 0.1.1 or 0.1.2." + LF +
    LF +
    "0.1.2 (2026-09-25; research/Classes-Berserker-Priest-Spec.md section 4 - Skyy: Berserker back, new Priest class, a class kit per class;" + LF +
    "  built with SkyyClasses 0.1.6 + SkyySkills 0.4.4 - DEPLOY THE THREE TOGETHER, spec section 5):" + LF +
    "  ROSTER (fallback table, used when SkyyClasses is absent; class:list decides what is selectable when it is present): Archer, Warrior," + LF +
    "    Mage, BERSERKER (Fury - axes, battleaxes, maces, clubs) and PRIEST (Divinity - wands, spellbooks) selectable; Assassin and Shaman" + LF +
    "    'coming later' (Shaman: a custom weapon later, Slowness Totem icon - the wand is a Priest weapon now). Names, skills, colors, weapon" + LF +
    "    texts and descriptions = SkyyClasses 0.1.6 (spec 2.1). ProfRoster entries grow to 8 fields: role at index 7, one line per class" + LF +
    "    (Priest = 'AoE healer / support'; an extra class published only by SkyyClasses gets 'A class from SkyyClasses'). With SkyyClasses" + LF +
    "    0.1.5 (no Berserker / Priest in class:list) both cards show greyed 'coming later' and cannot be picked." + LF +
    "  CREATE PROFILE PAGE: up to MAX_CARDS = 8 class cards, drawn AND handled (0.1.1 drew 6 and handled pfcls0..5 - with a 7-entry roster" + LF +
    "    Priest was invisible); a role line per card in the class color. ONE root for both views of ProfilePage: 1000 x 900 (was 780 x 600;" + LF +
    "    fits 1080), padding 16 / 10 = a 968 x 880 content box. Create view: bar 2, title 36, name row 36, sub 34, 7 x (gap 4 + card 90)," + LF +
    "    gap 8, make row 40, info 24 = 838 px (a rare 8th card - a class this build does not know - switches to gap 2 + card 84 = 868 px)." + LF +
    "    List view: the same content scaled ~1.2x (cards 76 high, fonts +2, buttons 14 pt). The numbers are build constants (CL / LL) that" + LF +
    "    the build checks against the content box. Element ids unchanged. While SkyyClasses publishes class:fn:kitnew the sub line says" + LF +
    "    the class kit (its basic weapon) arrives right after creating the profile." + LF +
    "  CLASS KIT HAND-OFF (spec 4.3): ProfKit.kitNew(uuid, key, class) calls the SkyyClasses 0.1.6 bridge function class:fn:kitnew" + LF +
    "    (apply(Object[] { UUID, String pkey, String class }) -> Boolean) right after a profile is created, OUTSIDE every SkyyProfiles" + LF +
    "    monitor (after ProfStore.create and publish returned): createFirst with key uuid (profile 1); createAndSwitch with" + LF +
    "    keyFor(uuid, id) BEFORE switchTo (a failed switch still leaves the kit pending for the day the player switches to that profile)." + LF +
    "    SkyyClasses owns the rest (kit state per profile, delivery on the ACTIVE key after profile:busy clears and 31 s after the epoch" + LF +
    "    change, storage first, claims via /class kit). Missing function = SkyyClasses absent or older = nothing; an answer other than TRUE" + LF +
    "    or an exception logs ONE warning per JVM and, for EVERY miss, a KIT-MISSED line in switches.log (uuid, profile key, class, why:" + LF +
    "    the admin's list for /classadmin kit). /profileadmin setclass never calls it (a fix, not a pick; its reply points admins at" + LF +
    "    /classadmin kit)." + LF +
    "  ONE CREATE PER SELECTION (review fix): the pfmake handler takes pickClass BEFORE any create work and puts it back only where the" + LF +
    "    create form shows again with nothing created; a first-profile form whose player already has a profile goes to the list instead" + LF +
    "    of creating a second one. PageManager already drops clicks while an update / close is unacknowledged (verified: rebuild and" + LF +
    "    setPage(None) both add a required ack, setPage(None) also nulls customPage); this covers the rest (an exception between the create" + LF +
    "    and the close, a close that silently failed, a create by command while the page was open) so no stale click makes an extra profile" + LF +
    "    and with it an extra class kit." + LF +
    "  Texts: /profileadmin setclass class help, manifest description. No new config rows, Settings switches or files; players files and" + LF +
    "  every bridge key unchanged (profile:class:<uuid> may now also be Berserker or Priest, as tools/PROFILES-CONTRACT.md lists)." + LF)
rep("  switches.log             one line per CREATE / SWITCH / ROLLBACK / RECOVER / RECOVER-INCOMPLETE (admin audit trail)" + LF,
    "  switches.log             one line per CREATE / SWITCH / ROLLBACK / RECOVER / RECOVER-INCOMPLETE / KIT-MISSED (0.1.2: SkyyClasses did" + LF +
    "                           not record the class kit of a new profile) (admin audit trail)" + LF)
rep("CREATE PROFILE page (Minecraft create-world style): class cards from the SkyyClasses bridge (class:list = the ENABLED classes, \"Name:Skill\")" + LF +
    "  merged with a built-in fallback roster (Archer, Warrior, Mage selectable; Assassin, Shaman \"coming later\"); pick one, \"Create profile\".",
    "CREATE PROFILE page (Minecraft create-world style): class cards from the SkyyClasses bridge (class:list = the ENABLED classes, \"Name:Skill\")" + LF +
    "  merged with a built-in fallback roster (0.1.2: Archer, Warrior, Mage, Berserker, Priest selectable; Assassin, Shaman \"coming later\");" + LF +
    "  pick one, \"Create profile\".")

# ---------------------------------------------------------------- roster data (spec 2.1 / 4.1)
rep("# Fallback roster = SkyyClasses 0.1.3 (used when SkyyClasses is not loaded; class:list decides which are selectable when it is).",
    "# Fallback roster = SkyyClasses 0.1.6 (used when SkyyClasses is not loaded; class:list decides which are selectable when it is)." + LF +
    "# 0.1.2 (research/Classes-Berserker-Priest-Spec.md 2.1 / 4.1): order = card order; Berserker + Priest added, Shaman's icon is the Slowness" + LF +
    "# Totem (the wand is a Priest weapon now); role = the one line under the combat skill on the Create Profile card.")
rep_between("CLASSES = [" + LF, "FRUITS = [",
    "CLASSES = [" + LF +
    '    {"name": "Archer", "skill": "Archery", "color": "#8fd67a", "enabled": True, "role": "Ranged damage",' + LF +
    '     "desc": "Fights from range. Charge a shortbow or load a crossbow and strike before the enemy gets close. Arrows are Archer ammo.",' + LF +
    '     "icons": ["Weapon_Shortbow_Iron", "Weapon_Crossbow_Iron", "Weapon_Arrow_Crude"], "weapon_text": "Shortbows / Crossbows"},' + LF +
    '    {"name": "Warrior", "skill": "Swordsmanship", "color": "#e0b060", "enabled": True, "role": "Melee fighter",' + LF +
    '     "desc": "Front line blade fighter. Swords and longswords up close and spears for reach.",' + LF +
    '     "icons": ["Weapon_Sword_Iron", "Weapon_Longsword_Iron", "Weapon_Spear_Iron"], "weapon_text": "Swords / Longswords / Spears"},' + LF +
    '    {"name": "Mage", "skill": "Sorcery", "color": "#7fb0e0", "enabled": True, "role": "Magic damage",' + LF +
    '     "desc": "Spellcaster. Staves strike up close and cast magic at range.",' + LF +
    '     "icons": ["Weapon_Staff_Iron", "Weapon_Staff_Wizard", "Weapon_Staff_Crystal_Ice"], "weapon_text": "Staves"},' + LF +
    '    {"name": "Berserker", "skill": "Fury", "color": "#d9443f", "enabled": True, "role": "Heavy melee damage",' + LF +
    '     "desc": "Heavy melee fighter. Axes and battleaxes cleave - maces and clubs crush. Hatchets stay gathering tools for everyone.",' + LF +
    '     "icons": ["Weapon_Battleaxe_Iron", "Weapon_Axe_Iron", "Weapon_Mace_Iron"], "weapon_text": "Axes / Battleaxes / Maces / Clubs"},' + LF +
    '    {"name": "Priest", "skill": "Divinity", "color": "#f2e6a0", "enabled": True, "role": "AoE healer / support",' + LF +
    '     "desc": "AoE healer and support. Your wand and spellbook hits on monsters heal party members near you. Spells come later.",' + LF +
    '     "icons": ["Weapon_Wand_Wood", "Weapon_Spellbook_Grimoire_Brown", "Weapon_Spellbook_Frost"], "weapon_text": "Wands / Spellbooks"},' + LF +
    '    {"name": "Assassin", "skill": "Assassination", "color": "#b58cff", "enabled": False, "role": "Fast burst damage",' + LF +
    '     "desc": "Coming later. Fast and deadly with twin daggers and kunai throwing knives.",' + LF +
    '     "icons": ["Weapon_Daggers_Iron", "Weapon_Kunai"], "weapon_text": "Daggers / Kunai"},' + LF +
    '    {"name": "Shaman", "skill": "Shaman skill", "color": "#ff7a5c", "enabled": False, "role": "Designed later",' + LF +
    '     "desc": "Coming later. The fifth Wynncraft class - it gets its own custom weapon.",' + LF +
    '     "icons": ["Weapon_Deployable_Slowness_Totem"], "weapon_text": "Custom weapon later"},' + LF +
    "]" + LF)
rep('EXTRA_ICON = "Weapon_Sword_Iron"       # a class published by SkyyClasses that this build does not know' + LF,
    'EXTRA_ICON = "Weapon_Sword_Iron"       # a class published by SkyyClasses that this build does not know' + LF +
    'EXTRA_ROLE = "A class from SkyyClasses"  # 0.1.2: its role line (spec 4.1)' + LF +
    'EXTRA_DESC = "Open /class after creating the profile to see its weapons."   # 0.1.2 (was the role text a second time)' + LF)

# ---------------------------------------------------------------- page size + layout constants, checked at build time (spec 4.2)
rep("PAGE_W, PAGE_H = 780, 600" + LF,
    "PAGE_W, PAGE_H = 1000, 900             # 0.1.2: ONE root for both views (was 780 x 600); fits 1080 (spec 4.2)" + LF +
    "PAD_H, PAD_V = 16, 10                  # root padding of both views: content box (PAGE_W - 2*PAD_H) x (PAGE_H - 2*PAD_V) = 968 x 880" + LF +
    "MAX_CARDS = 8                          # 0.1.2: class cards drawn on the Create Profile page AND pfcls<i> payloads handled (0.1.1: 6)" + LF +
    "# Create Profile view (spec 4.2), px. Heights: BAR TITLE NAME SUB, per card GAP + CARD, then AFTER MAKE INFO. Card text column: TPAD T1" + LF +
    "# (title, 16 pt) T2 (combat skill + weapons, 12 pt bold) T3 (role, 12 pt, class color) T4 (description, 11 pt wrapped; 28 = the spec's" + LF +
    "# 26 + the 2 px the 90 px card had spare, room for the second line). *8 = the rare 8-card page (a class this build does not know)." + LF +
    "# Widths: LPAD + 3 x ICO (ItemIcon ICON at ICOL) + TEXT + ACT (button BTNW x BTNH); name row NAMEL + NAMEB; make row MAKEL + MAKEB + 10 + BACKB." + LF +
    "# Buttons 150 x 34 at 14 pt: spec 4.2 fixes only the 170 action column (160 x 40 at 15 pt in spec 2.6 is the SkyyClasses /class page);" + LF +
    "# BTNH is also the make row's button height, and 40 + its 3 px top padding would not fit the 40 px make row." + LF +
    'CL = {"BAR": 2, "TITLE": 36, "NAME": 36, "SUB": 34, "GAP": 4, "CARD": 90, "AFTER": 8, "MAKE": 40, "INFO": 24,' + LF +
    '      "TPAD": 2, "T1": 24, "T2": 18, "T3": 18, "T4": 28, "GAP8": 2, "CARD8": 84, "TPAD8": 0, "T18": 22, "T48": 26,' + LF +
    '      "LPAD": 8, "ICO": 52, "ICON": 44, "ICOL": 4, "TEXT": 600, "ACT": 170, "BTNW": 150, "BTNH": 34,' + LF +
    '      "NAMEL": 760, "NAMEB": 170, "NAMEBH": 32, "MAKEL": 600, "MAKEB": 170, "BACKB": 150}' + LF +
    'CL["ICOS"] = 3 * CL["ICO"]' + LF +
    "# Profiles list view: 0.1.1 scaled ~1.2x (cards 76 high, fonts +2). Heights: BAR TITLE SUB, per profile GAP + CARD, the free-slot card" + LF +
    "# GAP + NEW, then AFTER INFO and CONF (confirm row) or FOOT. Card text column: TPAD T1 (name, 17 pt) T2 (class, 14 pt) T3 (dates, 13 pt)." + LF +
    'LL = {"BAR": 3, "TITLE": 36, "SUB": 24, "GAP": 8, "CARD": 76, "NEW": 68, "AFTER": 10, "INFO": 26, "CONF": 40, "FOOT": 36,' + LF +
    '      "TPAD": 6, "T1": 26, "T2": 22, "T3": 20,' + LF +
    '      "LPAD": 12, "ICO": 72, "ICON": 52, "ICOL": 10, "NEWICON": 44, "NEWICOL": 14, "TEXT": 620, "ACT": 200, "BTNW": 180, "BTNH": 36,' + LF +
    '      "CONFL": 560, "CONFB": 150}' + LF +
    'LL["ICOT"] = (LL["CARD"] - LL["ICON"]) // 2' + LF +
    'LL["ACTT"] = (LL["CARD"] - LL["BTNH"]) // 2' + LF +
    'LL["NEWICOT"] = (LL["NEW"] - LL["NEWICON"]) // 2' + LF +
    'LL["NEWACTT"] = (LL["NEW"] - LL["BTNH"]) // 2' + LF +
    "_CW, _CH = PAGE_W - 2 * PAD_H, PAGE_H - 2 * PAD_V" + LF +
    'need(PAGE_H <= 1080 - 60, "page taller than a 1080 screen allows")' + LF +
    '_c_head = CL["BAR"] + CL["TITLE"] + CL["NAME"] + CL["SUB"]' + LF +
    '_c_tail = CL["AFTER"] + CL["MAKE"] + CL["INFO"]' + LF +
    '_c7 = _c_head + 7 * (CL["GAP"] + CL["CARD"]) + _c_tail' + LF +
    '_c8 = _c_head + MAX_CARDS * (CL["GAP8"] + CL["CARD8"]) + _c_tail' + LF +
    'need(len(CLASSES) <= 7, "the 90 px card layout is sized for at most 7 fallback classes (8 = tight variant for one extra)")' + LF +
    'need(MAX_CARDS == 8, "the tight card variant is sized for exactly 8 cards")' + LF +
    'need(_c7 <= _CH, "create view with 7 cards is %d px, content box %d" % (_c7, _CH))' + LF +
    'need(_c8 <= _CH, "create view with %d cards is %d px, content box %d" % (MAX_CARDS, _c8, _CH))' + LF +
    'need(CL["TPAD"] + CL["T1"] + CL["T2"] + CL["T3"] + CL["T4"] <= CL["CARD"], "card text column taller than the card")' + LF +
    'need(CL["TPAD8"] + CL["T18"] + CL["T2"] + CL["T3"] + CL["T48"] <= CL["CARD8"], "tight card text column taller than the card")' + LF +
    'need(CL["ICON"] <= CL["CARD8"] and CL["BTNH"] <= CL["CARD8"] and CL["NAMEBH"] + 2 <= CL["NAME"] and CL["BTNH"] + 3 <= CL["MAKE"], "create view buttons / icons do not fit their rows")' + LF +
    'need(CL["LPAD"] + CL["ICOS"] + CL["TEXT"] + CL["ACT"] <= _CW, "create card wider than the content box")' + LF +
    'need(CL["BTNW"] <= CL["ACT"] and CL["ICOL"] + CL["ICON"] <= CL["ICO"], "create card action / icon column too narrow")' + LF +
    'need(CL["NAMEL"] + CL["NAMEB"] <= _CW and CL["MAKEL"] + CL["MAKEB"] + 10 + CL["BACKB"] <= _CW, "create view name / make row wider than the content box")' + LF +
    '_l_head = LL["BAR"] + LL["TITLE"] + LL["SUB"]' + LF +
    '_l_tail = LL["AFTER"] + LL["INFO"] + max(LL["CONF"], LL["FOOT"])' + LF +
    '_l6 = _l_head + 6 * (LL["GAP"] + LL["CARD"]) + _l_tail' + LF +
    '_l5 = _l_head + 5 * (LL["GAP"] + LL["CARD"]) + LL["GAP"] + LL["NEW"] + _l_tail' + LF +
    'need(max(_l6, _l5) <= _CH, "list view is %d px, content box %d" % (max(_l6, _l5), _CH))' + LF +
    'need(LL["TPAD"] + LL["T1"] + LL["T2"] + LL["T3"] <= LL["CARD"], "list card text column taller than the card")' + LF +
    'need(LL["LPAD"] + LL["ICO"] + LL["TEXT"] + LL["ACT"] <= _CW, "list card wider than the content box")' + LF +
    'need(LL["BTNW"] <= LL["ACT"] and LL["ICOL"] + LL["ICON"] <= LL["ICO"] and LL["NEWICOL"] + LL["NEWICON"] <= LL["ICO"], "list card action / icon column too narrow")' + LF +
    'need(LL["CONFL"] + 2 * LL["CONFB"] + 10 <= _CW and 34 + 3 <= LL["CONF"], "list view confirm row does not fit")' + LF +
    'print("page %dx%d: create view %d px (7 cards) / %d px (%d cards), list view %d px (6 profiles), content box %dx%d"' + LF +
    '      % (PAGE_W, PAGE_H, _c7, _c8, MAX_CARDS, max(_l6, _l5), _CW, _CH))' + LF)
rep('    for _k in ("name", "skill", "desc", "weapon_text"):',
    '    for _k in ("name", "skill", "desc", "weapon_text", "role"):')
rep('    need(1 <= len(_c["icons"]) <= 3, "1-3 icons per class")' + LF,
    '    need(1 <= len(_c["icons"]) <= 3, "1-3 icons per class")' + LF +
    '    need(0 < len(_c["role"]) <= 40, "role of %s: one short line (1-40 characters)" % _c["name"])' + LF +
    '    need(len(_c["desc"]) <= 130, "description of %s: at most 130 characters (two lines on the card)" % _c["name"])' + LF +
    'need([c["name"] for c in CLASSES] == ["Archer", "Warrior", "Mage", "Berserker", "Priest", "Assassin", "Shaman"], "fallback roster order (spec 4.1)")' + LF +
    'need([c["name"] for c in CLASSES if c["enabled"]] == ["Archer", "Warrior", "Mage", "Berserker", "Priest"], "launch roster (Skyy 2026-09-25)")' + LF +
    'need(dict((c["name"], c["role"]) for c in CLASSES)["Priest"] == "AoE healer / support", "Priest role text (spec 4.1)")' + LF +
    'for _t in (EXTRA_ROLE, EXTRA_DESC):' + LF +
    '    need(not (BAD_UI & set(_t)), "UI text %r" % _t)' + LF +
    '# review fix: the extra-class texts get the same length limits as every CLASSES entry (role one line, description two lines)' + LF +
    'need(0 < len(EXTRA_ROLE) <= 40, "EXTRA_ROLE: one short line (1-40 characters)")' + LF +
    'need(0 < len(EXTRA_DESC) <= 130, "EXTRA_DESC: at most 130 characters (two lines on the card)")' + LF)

# ---------------------------------------------------------------- ProfKit class (made here; its methods compile after ProfStore - they log to
# switches.log - and before ProfSwitch and the page, which call them)
rep('ros  = pool.makeClass(PKG + ".ProfRoster")' + LF,
    'ros  = pool.makeClass(PKG + ".ProfRoster")' + LF +
    'pkit = pool.makeClass(PKG + ".ProfKit")        # 0.1.2: class kit hand-off to SkyyClasses (class:fn:kitnew)' + LF)

# ---------------------------------------------------------------- ProfRoster: role at index 7
rep('F(ros, "public static final String[] ICONS = %s;" % jarr([",".join(c["icons"]) for c in CLASSES]))' + LF,
    'F(ros, "public static final String[] ICONS = %s;" % jarr([",".join(c["icons"]) for c in CLASSES]))' + LF +
    'F(ros, "public static final String[] ROLES = %s;" % jarr([c["role"] for c in CLASSES]))      # 0.1.2' + LF)
rep('F(ros, "public static final String EXTRA_ICON = %s;" % jstr(EXTRA_ICON))' + LF,
    'F(ros, "public static final String EXTRA_ICON = %s;" % jstr(EXTRA_ICON))' + LF +
    'F(ros, "public static final String EXTRA_ROLE = %s;" % jstr(EXTRA_ROLE))' + LF +
    'F(ros, "public static final String EXTRA_DESC = %s;" % jstr(EXTRA_DESC))' + LF)
rep('# one entry = String[] { name, skill, desc, color, weapons text, icons (comma list), "1" selectable / "0" coming later }',
    '# one entry = String[] { name, skill, desc, color, weapons text, icons (comma list), "1" selectable / "0" coming later, role (0.1.2) }' + LF +
    '# (0.1.2 appends the role at index 7, so every 0.1.1 index keeps its meaning)')
rep('    out.add(new String[] { NAMES[i], skill, DESCS[i], COLORS[i], WTEXT[i], ICONS[i], on ? "1" : "0" });',
    '    out.add(new String[] { NAMES[i], skill, DESCS[i], COLORS[i], WTEXT[i], ICONS[i], on ? "1" : "0", ROLES[i] });')
rep('      out.add(new String[] { n, sk, "A class from SkyyClasses.", "#c9d6e2", "See /class", EXTRA_ICON, "1" });',
    '      out.add(new String[] { n, sk, EXTRA_DESC, "#c9d6e2", "See /class", EXTRA_ICON, "1", EXTRA_ROLE });')

PROFKIT = r'''
# ================= ProfKit (0.1.2): tell SkyyClasses a profile picked its class, so the class kit follows (spec 4.3) =================
# class:fn:kitnew (SkyyClasses 0.1.6+) = Function apply(Object[] { UUID player, String pkey, String className }) -> Boolean: TRUE =
# recorded (pending, or off while kits are off) or the profile already has a kit state; FALSE = bad arguments / class file unusable.
# It runs on the caller's thread (a small synchronous file write under SkyyClasses' own lock, never a call into another mod), so the
# callers invoke it OUTSIDE every SkyyProfiles monitor. Missing = SkyyClasses absent or older = nothing to do. Never throws.
# A miss (answer other than TRUE, or an exception) = a KIT-MISSED line in switches.log EVERY time (review fix: the admin's list of who
# needs /classadmin kit) + ONE console warning per JVM (spec 4.3) that points at that list.
# Compiled after ProfStore (log -> switches.log) and before ProfSwitch / ProfilePage / the setclass command (the callers).
F(pkit, "public static final java.util.concurrent.atomic.AtomicBoolean WARNED = new java.util.concurrent.atomic.AtomicBoolean(false);")
M(pkit, r"""
public static java.util.function.Function fn() {
  try {
    Object f = @PKG@.ProfCfg.bridge().get("class:fn:kitnew");
    if (f instanceof java.util.function.Function) return (java.util.function.Function) f;
  } catch (Throwable t) { }
  return null;
}""")
M(pkit, r"""
public static boolean available() {
  return fn() != null;
}""")
M(pkit, r"""
public static void warnOnce(String msg) {
  if (WARNED.compareAndSet(false, true)) @PKG@.ProfCfg.warn(msg + " (this warning is logged once per server start)");
}""")
M(pkit, r"""
public static void missed(java.util.UUID u, String key, String cls, String why) {
  try { @PKG@.ProfStore.log("KIT-MISSED " + u + " key " + key + " class " + cls + " - " + why); } catch (Throwable t) { }
  warnOnce("the class kit of a new profile was not recorded: " + u + " (profile key " + key + ", class " + cls + ") - " + why + " - /classadmin kit <player> can hand it out; switches.log lists every miss (KIT-MISSED lines)");
}""")
M(pkit, r"""
public static boolean kitNew(java.util.UUID u, String key, String cls) {
  if (u == null || key == null || key.length() == 0 || cls == null || cls.trim().length() == 0) return false;
  java.util.function.Function f = fn();
  if (f == null) return false;
  String why = null;
  try {
    Object r = f.apply(new Object[] { u, key, cls });
    if (Boolean.TRUE.equals(r)) return true;
    why = "class:fn:kitnew answered " + r;
  } catch (Throwable t) {
    why = "class:fn:kitnew failed: " + t;
  }
  missed(u, key, cls, why);
  return false;
}""")

'''
# review fix: inserted after ProfStore (was before ProfNames) so missed() can call ProfStore.log; still before ProfSwitch and the page
rep(LF + "# ================= KeyFn: bridge profile:fn:key =================" + LF,
    PROFKIT + "# ================= KeyFn: bridge profile:fn:key =================" + LF)

# ---------------------------------------------------------------- the two create paths call ProfKit.kitNew (spec 4.3)
rep('  pr.sendMessage(@MSG@.raw("[Profiles] Profile " + name + " created - you are " + @PKG@.ProfRoster.article(cls) + " for good on this profile. Everything you already had belongs to it. /profiles manages your profiles.").color("#8fe39a"));' + LF +
    '  return null;' + LF,
    '  pr.sendMessage(@MSG@.raw("[Profiles] Profile " + name + " created - you are " + @PKG@.ProfRoster.article(cls) + " for good on this profile. Everything you already had belongs to it. /profiles manages your profiles.").color("#8fe39a"));' + LF +
    '  // 0.1.2: the class kit - after create + publish returned, no SkyyProfiles monitor held; profile 1 = key uuid.toString()' + LF +
    '  @PKG@.ProfKit.kitNew(u, @PKG@.ProfStore.keyFor(u, "1"), cls);' + LF +
    '  return null;' + LF)
rep('  @PKG@.ProfStore.log("CREATE " + u + " " + pr.getUsername() + " profile " + id + " " + name + " " + cls);' + LF +
    '  String err = switchTo(st, ref, pr, player, id);' + LF,
    '  @PKG@.ProfStore.log("CREATE " + u + " " + pr.getUsername() + " profile " + id + " " + name + " " + cls);' + LF +
    '  // 0.1.2: the class kit - BEFORE the switch, so a failed switch still leaves it pending for that profile (SkyyClasses delivers only' + LF +
    '  // to the ACTIVE key, after profile:busy clears and 31 s after the epoch change); no SkyyProfiles monitor is held here' + LF +
    '  @PKG@.ProfKit.kitNew(u, @PKG@.ProfStore.keyFor(u, id), cls);' + LF +
    '  String err = switchTo(st, ref, pr, player, id);' + LF)

# ---------------------------------------------------------------- page: buttons +2 pt, layout tokens, MAX_CARDS
rep('BTN = ("Style: TextButtonStyle(Default: (Background: #5a4420, LabelStyle: (FontSize: 12, TextColor: #ffe9c9, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '       "Hovered: (Background: #8a6a30, LabelStyle: (FontSize: 12, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '       "Pressed: (Background: #3a2a10, LabelStyle: (FontSize: 12, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));")' + LF +
    'BTN_GO = ("Style: TextButtonStyle(Default: (Background: #2f6a3a, LabelStyle: (FontSize: 12, TextColor: #e9ffe9, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '          "Hovered: (Background: #3f8a4a, LabelStyle: (FontSize: 12, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '          "Pressed: (Background: #1f4a2a, LabelStyle: (FontSize: 12, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));")' + LF +
    'def ui(src):' + LF +
    '    return (src.replace("__BTN__", BTN.replace(\'"\', \'\\\\"\')).replace("__BTNGO__", BTN_GO.replace(\'"\', \'\\\\"\'))' + LF +
    '               .replace("__W__", str(PAGE_W)).replace("__H__", str(PAGE_H)))' + LF,
    '# 0.1.2: button labels 14 pt (were 12) - the page is 1000 x 900 now' + LF +
    'BTN = ("Style: TextButtonStyle(Default: (Background: #5a4420, LabelStyle: (FontSize: 14, TextColor: #ffe9c9, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '       "Hovered: (Background: #8a6a30, LabelStyle: (FontSize: 14, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '       "Pressed: (Background: #3a2a10, LabelStyle: (FontSize: 14, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));")' + LF +
    'BTN_GO = ("Style: TextButtonStyle(Default: (Background: #2f6a3a, LabelStyle: (FontSize: 14, TextColor: #e9ffe9, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '          "Hovered: (Background: #3f8a4a, LabelStyle: (FontSize: 14, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)), "' + LF +
    '          "Pressed: (Background: #1f4a2a, LabelStyle: (FontSize: 14, TextColor: #ffffff, RenderBold: true, HorizontalAlignment: Center, VerticalAlignment: Center)));")' + LF +
    'def ui(src):' + LF +
    '    """Page source: button styles, root size + padding, and the 0.1.2 layout constants (__C<key>__ from CL, __L<key>__ from LL)."""' + LF +
    '    out = (src.replace("__BTN__", BTN.replace(\'"\', \'\\\\"\')).replace("__BTNGO__", BTN_GO.replace(\'"\', \'\\\\"\'))' + LF +
    '              .replace("__W__", str(PAGE_W)).replace("__H__", str(PAGE_H)).replace("__PADH__", str(PAD_H)).replace("__PADV__", str(PAD_V)))' + LF +
    '    for k in sorted(CL, key=len, reverse=True):' + LF +
    '        out = out.replace("__C" + k + "__", str(CL[k]))' + LF +
    '    for k in sorted(LL, key=len, reverse=True):' + LF +
    '        out = out.replace("__L" + k + "__", str(LL[k]))' + LF +
    '    left = re.findall(r"__[A-Z0-9]+__", out)' + LF +
    '    need(not left, "unreplaced page tokens: %s" % left)' + LF +
    '    return out' + LF)
rep('F(page, "public boolean reminded;")' + LF,
    'F(page, "public boolean reminded;")' + LF +
    'F(page, "public static final int MAX_CARDS = %d;" % MAX_CARDS)      # 0.1.2: cards drawn + pfcls<i> handled (0.1.1: 6)' + LF)

NEW_LIST = r'''M(page, ui(r"""
public void buildList(@UCB@ b, @UEB@ ev, java.util.UUID u, java.util.Properties p) {
  String bs = "__BTN__";
  String go = "__BTNGO__";
  String act = @PKG@.ProfStore.activeOf(p);
  int n = @PKG@.ProfStore.count(p);
  int max = @PKG@.ProfCfg.MAX_PROFILES;
  b.appendInline((String) null, "Group #SkyyPf { Anchor: (Width: __W__, Height: __H__); Background: #0b1524(0.96); Padding: (Horizontal: __PADH__, Vertical: __PADV__); LayoutMode: Top; }");
  b.appendInline("#SkyyPf", "Group { Anchor: (Height: __LBAR__); Background: #d08a4a; }");
  b.appendInline("#SkyyPf", "Label { Anchor: (Height: __LTITLE__); Text: \"Profiles\"; Style: (FontSize: 20, RenderBold: true, TextColor: #ffe9c9, HorizontalAlignment: Center, VerticalAlignment: Center); }");
  b.appendInline("#SkyyPf", "Label { Anchor: (Height: __LSUB__); Text: \"Each profile is its own save - class, island, coins, skills, bags and inventory.\"; Style: (FontSize: 13, TextColor: #9fb8cc, HorizontalAlignment: Center, VerticalAlignment: Center); }");
  for (int i = 1; i <= @PKG@.ProfCfg.MAX_ID; i++) {
    String id = String.valueOf(i);
    if (!@PKG@.ProfStore.exists(p, id)) continue;
    boolean on = id.equals(act);
    boolean pend = id.equals(this.pending);
    String name = p.getProperty("p." + id + ".name", "Profile " + id);
    String cls = p.getProperty("p." + id + ".class", "");
    String[] ce = @PKG@.ProfRoster.entry(cls);
    String color = ce == null ? "#c9d6e2" : ce[3];
    String bg = on ? "#173524(0.95)" : (pend ? "#3a2f1a(0.95)" : "#142030(0.9)");
    String cid = "#SkyyPfCard" + id;
    String tid = "#SkyyPfTxt" + id;
    String aid = "#SkyyPfAct" + id;
    b.appendInline("#SkyyPf", "Label { Anchor: (Height: __LGAP__); Text: \"\"; }");
    b.appendInline("#SkyyPf", "Group #SkyyPfCard" + id + " { Anchor: (Height: __LCARD__); LayoutMode: Left; Background: " + bg + "; }");
    b.appendInline(cid, "Label { Anchor: (Width: __LLPAD__, Height: __LCARD__); Text: \"\"; }");
    b.appendInline(cid, "Group { Anchor: (Width: __LICO__, Height: __LCARD__); ItemIcon { Anchor: (Width: __LICON__, Height: __LICON__, Left: __LICOL__, Top: __LICOT__); ItemId: \"" + safe(@PKG@.ProfRoster.iconOf(cls)) + "\"; } }");
    b.appendInline(cid, "Group #SkyyPfTxt" + id + " { Anchor: (Width: __LTEXT__, Height: __LCARD__); LayoutMode: Top; Padding: (Top: __LTPAD__); }");
    b.appendInline(tid, "Label { Anchor: (Height: __LT1__); Text: \"" + safe(name + (on ? " - ACTIVE" : "")) + "\"; Style: (FontSize: 17, RenderBold: true, TextColor: " + (on ? "#8fe39a" : "#ffe9c9") + ", VerticalAlignment: Center); }");
    String line2 = cls.length() == 0 ? "No class - an admin can set it" : cls + " - combat skill " + @PKG@.ProfRoster.skillOf(cls);
    b.appendInline(tid, "Label { Anchor: (Height: __LT2__); Text: \"" + safe(line2) + "\"; Style: (FontSize: 14, RenderBold: true, TextColor: " + color + ", VerticalAlignment: Center); }");
    String line3 = "Created " + @PKG@.ProfStore.fmtDate(@PKG@.ProfStore.num(p, "p." + id + ".created")) + " - "
      + (on ? "playing now" : "last played " + @PKG@.ProfStore.fmtAgo(@PKG@.ProfStore.num(p, "p." + id + ".lastPlayed")));
    b.appendInline(tid, "Label { Anchor: (Height: __LT3__); Text: \"" + safe(line3) + "\"; Style: (FontSize: 13, TextColor: #9fb8cc, VerticalAlignment: Center); }");
    b.appendInline(cid, "Group #SkyyPfAct" + id + " { Anchor: (Width: __LACT__, Height: __LCARD__); LayoutMode: Top; Padding: (Top: __LACTT__); }");
    if (on) {
      b.appendInline(aid, "Label { Anchor: (Width: __LBTNW__, Height: __LBTNH__); Text: \"Active\"; Style: (FontSize: 15, RenderBold: true, TextColor: #8fe39a, HorizontalAlignment: Center, VerticalAlignment: Center); }");
    } else {
      b.appendInline(aid, "TextButton #SkyyPfSw" + id + " { Anchor: (Width: __LBTNW__, Height: __LBTNH__); Text: \"Switch\"; " + (pend ? go : bs) + " }");
      ev.addEventBinding(@BT@.Activating, "#SkyyPfSw" + id, @EVD@.of("a", "pfsw" + id));
    }
  }
  if (n < max) {
    b.appendInline("#SkyyPf", "Label { Anchor: (Height: __LGAP__); Text: \"\"; }");
    b.appendInline("#SkyyPf", "Group #SkyyPfNewCard { Anchor: (Height: __LNEW__); LayoutMode: Left; Background: #0d1219(0.85); }");
    b.appendInline("#SkyyPfNewCard", "Label { Anchor: (Width: __LLPAD__, Height: __LNEW__); Text: \"\"; }");
    b.appendInline("#SkyyPfNewCard", "Group { Anchor: (Width: __LICO__, Height: __LNEW__); ItemIcon { Anchor: (Width: __LNEWICON__, Height: __LNEWICON__, Left: __LNEWICOL__, Top: __LNEWICOT__); ItemId: \"" + @PKG@.ProfRoster.NEW_ICON + "\"; } }");
    b.appendInline("#SkyyPfNewCard", "Label { Anchor: (Width: __LTEXT__, Height: __LNEW__); Text: \"" + safe("Empty slot - a new profile starts from zero with the class you pick (" + (max - n) + " free)") + "\"; Style: (FontSize: 14, TextColor: #c9d6e2, VerticalAlignment: Center, Wrap: true); }");
    b.appendInline("#SkyyPfNewCard", "Group #SkyyPfNewAct { Anchor: (Width: __LACT__, Height: __LNEW__); LayoutMode: Top; Padding: (Top: __LNEWACTT__); }");
    b.appendInline("#SkyyPfNewAct", "TextButton #SkyyPfNew { Anchor: (Width: __LBTNW__, Height: __LBTNH__); Text: \"Create new\"; " + go + " }");
    ev.addEventBinding(@BT@.Activating, "#SkyyPfNew", @EVD@.of("a", "pfnew"));
  }
  b.appendInline("#SkyyPf", "Label { Anchor: (Height: __LAFTER__); Text: \"\"; }");
  b.appendInline("#SkyyPf", "Label #SkyyPfInfo { Anchor: (Height: __LINFO__); Text: \"" + safe(this.info) + "\"; Style: (FontSize: 14, RenderBold: true, TextColor: #ffd27a, HorizontalAlignment: Center, VerticalAlignment: Center); }");
  if (this.pending != null && @PKG@.ProfStore.exists(p, this.pending) && !this.pending.equals(act)) {
    String pn = p.getProperty("p." + this.pending + ".name", "Profile " + this.pending);
    String pc = p.getProperty("p." + this.pending + ".class", "");
    String q = "Switch to " + pn + (pc.length() > 0 ? " (" + pc + ")" : "") + "? Your inventory is saved and you go to the island of that profile.";
    b.appendInline("#SkyyPf", "Group #SkyyPfConfirm { Anchor: (Height: __LCONF__); LayoutMode: Left; Padding: (Top: 3); }");
    b.appendInline("#SkyyPfConfirm", "Label { Anchor: (Width: __LCONFL__, Height: 34); Text: \"" + safe(q) + "\"; Style: (FontSize: 13, RenderBold: true, TextColor: #ffe9c9, VerticalAlignment: Center, Wrap: true); }");
    b.appendInline("#SkyyPfConfirm", "TextButton #SkyyPfYes { Anchor: (Width: __LCONFB__, Height: 34); Text: \"Confirm\"; " + go + " }");
    b.appendInline("#SkyyPfConfirm", "Label { Anchor: (Width: 10, Height: 34); Text: \"\"; }");
    b.appendInline("#SkyyPfConfirm", "TextButton #SkyyPfNo { Anchor: (Width: __LCONFB__, Height: 34); Text: \"Cancel\"; " + bs + " }");
    ev.addEventBinding(@BT@.Activating, "#SkyyPfYes", @EVD@.of("a", "pfyes"));
    ev.addEventBinding(@BT@.Activating, "#SkyyPfNo", @EVD@.of("a", "pfno"));
  } else {
    String used = n + " of " + max + " profile slots used.";
    if (n > max) used = n + " profiles - this server now allows " + max + ". You keep them all but cannot create more.";
    String foot = used + " Switching saves your inventory and takes you to the island of the other profile. Not while in combat.";
    b.appendInline("#SkyyPf", "Label #SkyyPfFoot { Anchor: (Height: __LFOOT__); Text: \"" + safe(foot) + "\"; Style: (FontSize: 13, TextColor: #8fa4b8, HorizontalAlignment: Center, VerticalAlignment: Center, Wrap: true); }");
  }
}"""))
'''

NEW_CREATE = r'''M(page, ui(r"""
public void buildCreate(@UCB@ b, @UEB@ ev, java.util.UUID u, java.util.Properties p) {
  String bs = "__BTN__";
  String go = "__BTNGO__";
  String newId = this.first ? "1" : @PKG@.ProfStore.nextId(p);
  if (newId == null) newId = "?";
  b.appendInline((String) null, "Group #SkyyPf { Anchor: (Width: __W__, Height: __H__); Background: #0b1524(0.96); Padding: (Horizontal: __PADH__, Vertical: __PADV__); LayoutMode: Top; }");
  b.appendInline("#SkyyPf", "Group { Anchor: (Height: __CBAR__); Background: #d08a4a; }");
  b.appendInline("#SkyyPf", "Label { Anchor: (Height: __CTITLE__); Text: \"" + (this.first ? "Create your first profile" : "Create a new profile") + "\"; Style: (FontSize: 20, RenderBold: true, TextColor: #ffe9c9, HorizontalAlignment: Center, VerticalAlignment: Center); }");
  b.appendInline("#SkyyPf", "Group #SkyyPfNameRow { Anchor: (Height: __CNAME__); LayoutMode: Left; Padding: (Top: 2); }");
  b.appendInline("#SkyyPfNameRow", "Label { Anchor: (Width: __CNAMEL__, Height: __CNAMEBH__); Text: \"" + safe("Profile " + newId + " will be called " + this.pickName) + "\"; Style: (FontSize: 15, RenderBold: true, TextColor: #ffe9c9, VerticalAlignment: Center); }");
  b.appendInline("#SkyyPfNameRow", "TextButton #SkyyPfName { Anchor: (Width: __CNAMEB__, Height: __CNAMEBH__); Text: \"Other name\"; " + bs + " }");
  ev.addEventBinding(@BT@.Activating, "#SkyyPfName", @EVD@.of("a", "pfname"));
  boolean kits = @PKG@.ProfKit.available();
  String sub = "";
  if (this.first) {
    sub = kits ? "Pick your class. It is locked to this profile forever. You get your class kit - its basic weapon - right after creating it. Everything you already have stays on this first profile."
               : "Pick your class. It is locked to this profile forever - like creating a world. Everything you already have stays on this first profile.";
  } else {
    sub = kits ? "Pick your class. It is locked to this profile forever. You get your class kit - its basic weapon - right after creating it. The profile starts from zero with its own island and coins."
               : "Pick a class. It is locked to this profile forever. The new profile starts from zero - empty inventory and its own island and coins and skills.";
  }
  b.appendInline("#SkyyPf", "Label { Anchor: (Height: __CSUB__); Text: \"" + safe(sub) + "\"; Style: (FontSize: 12, TextColor: #9fb8cc, HorizontalAlignment: Center, VerticalAlignment: Center, Wrap: true); }");
  java.util.ArrayList r = @PKG@.ProfRoster.roster();
  int shown = r.size() < MAX_CARDS ? r.size() : MAX_CARDS;
  boolean tight = shown > 7;
  int ch = tight ? __CCARD8__ : __CCARD__;
  int gap = tight ? __CGAP8__ : __CGAP__;
  int tp = tight ? __CTPAD8__ : __CTPAD__;
  int t1 = tight ? __CT18__ : __CT1__;
  int t4 = tight ? __CT48__ : __CT4__;
  int it = (ch - __CICON__) / 2;
  int at = (ch - __CBTNH__) / 2;
  for (int i = 0; i < shown; i++) {
    String[] c = (String[]) r.get(i);
    boolean on = "1".equals(c[6]);
    boolean sel = this.pickClass != null && c[0].equalsIgnoreCase(this.pickClass);
    String bg = sel ? "#173524(0.95)" : (on ? "#142030(0.9)" : "#0d1219(0.85)");
    String role = c.length > 7 && c[7] != null ? c[7] : "";
    String cid = "#SkyyPfCls" + i;
    String iid = "#SkyyPfIco" + i;
    String tid = "#SkyyPfCTx" + i;
    String aid = "#SkyyPfCAct" + i;
    b.appendInline("#SkyyPf", "Label { Anchor: (Height: " + gap + "); Text: \"\"; }");
    b.appendInline("#SkyyPf", "Group #SkyyPfCls" + i + " { Anchor: (Height: " + ch + "); LayoutMode: Left; Background: " + bg + "; }");
    b.appendInline(cid, "Label { Anchor: (Width: __CLPAD__, Height: " + ch + "); Text: \"\"; }");
    b.appendInline(cid, "Group #SkyyPfIco" + i + " { Anchor: (Width: __CICOS__, Height: " + ch + "); LayoutMode: Left; }");
    String[] ic = c[5].split(",");
    for (int k = 0; k < ic.length && k < 3; k++) {
      b.appendInline(iid, "Group { Anchor: (Width: __CICO__, Height: " + ch + "); ItemIcon { Anchor: (Width: __CICON__, Height: __CICON__, Left: __CICOL__, Top: " + it + "); ItemId: \"" + safe(ic[k]) + "\"; } }");
    }
    b.appendInline(cid, "Group #SkyyPfCTx" + i + " { Anchor: (Width: __CTEXT__, Height: " + ch + "); LayoutMode: Top; Padding: (Top: " + tp + "); }");
    String title = c[0] + (sel ? " - selected" : (on ? "" : " - coming later"));
    b.appendInline(tid, "Label { Anchor: (Height: " + t1 + "); Text: \"" + safe(title) + "\"; Style: (FontSize: 16, RenderBold: true, TextColor: " + (on ? c[3] : "#5f6b78") + ", VerticalAlignment: Center); }");
    b.appendInline(tid, "Label { Anchor: (Height: __CT2__); Text: \"" + safe("Combat skill " + c[1] + " - " + c[4]) + "\"; Style: (FontSize: 12, RenderBold: true, TextColor: " + (on ? "#9fd8a2" : "#5f6b78") + ", VerticalAlignment: Center); }");
    b.appendInline(tid, "Label { Anchor: (Height: __CT3__); Text: \"" + safe(role) + "\"; Style: (FontSize: 12, TextColor: " + (on ? c[3] : "#5f6b78") + ", VerticalAlignment: Center); }");
    b.appendInline(tid, "Label { Anchor: (Height: " + t4 + "); Text: \"" + safe(c[2]) + "\"; Style: (FontSize: 11, TextColor: " + (on ? "#c9d6e2" : "#5f6b78") + ", VerticalAlignment: Center, Wrap: true); }");
    b.appendInline(cid, "Group #SkyyPfCAct" + i + " { Anchor: (Width: __CACT__, Height: " + ch + "); LayoutMode: Top; Padding: (Top: " + at + "); }");
    if (!on) {
      b.appendInline(aid, "Label { Anchor: (Width: __CBTNW__, Height: __CBTNH__); Text: \"Coming later\"; Style: (FontSize: 14, RenderBold: true, TextColor: #5f6b78, HorizontalAlignment: Center, VerticalAlignment: Center); }");
    } else if (sel) {
      b.appendInline(aid, "Label { Anchor: (Width: __CBTNW__, Height: __CBTNH__); Text: \"Selected\"; Style: (FontSize: 15, RenderBold: true, TextColor: #8fe39a, HorizontalAlignment: Center, VerticalAlignment: Center); }");
    } else {
      b.appendInline(aid, "TextButton #SkyyPfPick" + i + " { Anchor: (Width: __CBTNW__, Height: __CBTNH__); Text: \"Select\"; " + bs + " }");
      ev.addEventBinding(@BT@.Activating, "#SkyyPfPick" + i, @EVD@.of("a", "pfcls" + i));
    }
  }
  b.appendInline("#SkyyPf", "Label { Anchor: (Height: __CAFTER__); Text: \"\"; }");
  String q = this.pickClass == null ? "Select a class to continue."
    : "Create " + this.pickName + " as " + @PKG@.ProfRoster.article(this.pickClass) + "? The class can never be changed.";
  b.appendInline("#SkyyPf", "Group #SkyyPfMakeRow { Anchor: (Height: __CMAKE__); LayoutMode: Left; Padding: (Top: 3); }");
  b.appendInline("#SkyyPfMakeRow", "Label { Anchor: (Width: __CMAKEL__, Height: __CBTNH__); Text: \"" + safe(q) + "\"; Style: (FontSize: 14, RenderBold: true, TextColor: #ffe9c9, VerticalAlignment: Center, Wrap: true); }");
  if (this.pickClass != null) {
    b.appendInline("#SkyyPfMakeRow", "TextButton #SkyyPfMake { Anchor: (Width: __CMAKEB__, Height: __CBTNH__); Text: \"Create profile\"; " + go + " }");
    ev.addEventBinding(@BT@.Activating, "#SkyyPfMake", @EVD@.of("a", "pfmake"));
  } else {
    b.appendInline("#SkyyPfMakeRow", "Label { Anchor: (Width: __CMAKEB__, Height: __CBTNH__); Text: \"\"; }");
  }
  b.appendInline("#SkyyPfMakeRow", "Label { Anchor: (Width: 10, Height: __CBTNH__); Text: \"\"; }");
  b.appendInline("#SkyyPfMakeRow", "TextButton #SkyyPfBack { Anchor: (Width: __CBACKB__, Height: __CBTNH__); Text: \"" + (this.first ? "Later" : "Back") + "\"; " + bs + " }");
  ev.addEventBinding(@BT@.Activating, "#SkyyPfBack", @EVD@.of("a", "pfback"));
  b.appendInline("#SkyyPf", "Label #SkyyPfInfo { Anchor: (Height: __CINFO__); Text: \"" + safe(this.info) + "\"; Style: (FontSize: 14, RenderBold: true, TextColor: #ffd27a, HorizontalAlignment: Center, VerticalAlignment: Center); }");
}"""))
'''

rep_between('M(page, ui(r"""' + LF + 'public void buildList(', 'M(page, ui(r"""' + LF + 'public void buildCreate(', NEW_LIST)
rep_between('M(page, ui(r"""' + LF + 'public void buildCreate(', 'M(page, r"""' + LF + 'public void build(@REF@ ref,', NEW_CREATE)
rep("    for (int i = 0; i < r.size() && i < 6; i++) {" + LF + '      if (data.indexOf("pfcls" + i + "\\"") < 0) continue;',
    "    for (int i = 0; i < r.size() && i < MAX_CARDS; i++) {" + LF + '      if (data.indexOf("pfcls" + i + "\\"") < 0) continue;')

# ---------------------------------------------------------------- review fix: "Create profile" = ONE create per selection
# 0.1.1 kept pickClass set through the create and branched only on activeOf(p): a click that still reached this page after a create
# (an exception between the create and the close, a close that silently failed, a /profiles create typed while the page was open) fell
# through to createAndSwitch and made an extra profile - with 0.1.2 also an extra class kit. PageManager already drops clicks while an
# update / close is unacknowledged (rebuild + setPage(None) each add a required ack; setPage(None) also nulls customPage), so a plain
# double click was never the way in; this closes the rest. Every failure path that shows the create form again with NOTHING created
# puts the selection back, so a refused create (combat, slots, a save error) keeps the player's pick.
PFMAKE = r'''    if (data.indexOf("pfmake\"") >= 0) {
      // 0.1.2 (review fix): ONE create per selection - take the pick BEFORE any create work, put it back only where the create form shows
      // again with nothing created; a first-profile form whose player already has a profile goes to the list instead of creating another
      String pick = this.pickClass;
      this.pickClass = null;
      if (this.first && @PKG@.ProfStore.activeOf(p) != null) { this.view = 0; this.first = false; this.info = "Your first profile already exists - Create new makes another one."; rebuild(); return; }
      if (pick == null) { this.info = "Select a class first."; rebuild(); return; }
      String[] ce = @PKG@.ProfRoster.entry(pick);
      if (ce == null || !"1".equals(ce[6])) { this.info = pick + " is not available."; rebuild(); return; }
      @PLA@ player = (@PLA@) st.getComponent(ref, @PLA@.getComponentType());
      if (player == null) { this.pickClass = pick; return; }
      if (@PKG@.ProfStore.activeOf(p) == null) {
        String e1 = @PKG@.ProfSwitch.createFirst(this.playerRef, ce[0], this.pickName);
        if (e1 == null) { closeSelf(ref, st); return; }
        this.info = e1;
        this.pickClass = pick;
        rebuild();
        return;
      }
      int before = @PKG@.ProfStore.count(p);
      String e2 = @PKG@.ProfSwitch.createAndSwitch(st, ref, this.playerRef, player, ce[0], this.pickName);
      if (e2 == null) return;
      this.info = e2;
      if (@PKG@.ProfStore.count(@PKG@.ProfStore.load(u)) > before) { this.view = 0; this.first = false; }
      else this.pickClass = pick;
      rebuild();
      return;
    }
'''
rep_between(r'    if (data.indexOf("pfmake\"") >= 0) {' + LF, r'    if (data.indexOf("pfback\"") >= 0) {' + LF, PFMAKE)

# ---------------------------------------------------------------- admin texts, class list, manifest
rep('  this.classArg = withRequiredArg("class", "archer | warrior | mage (assassin, shaman later)", @ATY@.STRING);',
    '  this.classArg = withRequiredArg("class", "archer | warrior | mage | berserker | priest (assassin, shaman later)", @ATY@.STRING);')
rep('    if (tp != null && tp.isValid()) tp.sendMessage(@MSG@.raw("[Profiles] An admin set the class of your profile " + id + " to " + c[0] + ".").color("#ffc800"));' + LF,
    '    if (tp != null && tp.isValid()) tp.sendMessage(@MSG@.raw("[Profiles] An admin set the class of your profile " + id + " to " + c[0] + ".").color("#ffc800"));' + LF +
    '    // 0.1.2: a fix is not a pick - no class kit (spec 4.3 / Q14); tell the admin how to hand one out' + LF +
    '    if (@PKG@.ProfKit.available()) pr.sendMessage(@MSG@.raw("[Profiles] No class kit is given for a class fix - /classadmin kit <player> [class] hands one out."));' + LF)
rep("ALL = (cfg, ros, nam, sto, pub, kfn, inv, sw, clr, page, opn, rec, pj, rtk, svt, rdy, pcon, quit_, pcre, psw, plst, pcmd, ainf, acls, arel,",
    "ALL = (cfg, ros, pkit, nam, sto, pub, kfn, inv, sw, clr, page, opn, rec, pj, rtk, svt, rdy, pcon, quit_, pcre, psw, plst, pcmd, ainf, acls, arel,")
rep('m = B.manifest("SkyyProfiles", VERSION, "SkyWynn profiles (SkyBlock style): each profile is its own save - class (picked at creation, locked), island, coins, skills, bags and vanilla inventory. /profiles. Zero dependencies; SkyyClasses and SkyyIslands are used when present.", PKG + ".SkyyProfilesPlugin")',
    'm = B.manifest("SkyyProfiles", VERSION, "SkyWynn profiles (SkyBlock style): each profile is its own save - class (Archer, Warrior, Mage, Berserker or Priest; picked at creation, locked, with its class kit from SkyyClasses), island, coins, skills, bags and vanilla inventory. /profiles. Zero dependencies; SkyyClasses and SkyyIslands are used when present.", PKG + ".SkyyProfilesPlugin")')

open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", dst)
