"""Derive SkyyProfiles/build_skyyprofiles_0.1.8.py from the generated 0.1.7 (build_skyyprofiles_0.1.7.py = the tools/deploy_set.py SET pin).
Edit THIS file, never the generated build script. Harness: python SkyyProfiles/test_skyyprofiles_0.1.8.py.
Run:  python tools/profiles_0_1_8_patch.py   then   python SkyyProfiles/build_skyyprofiles_0.1.8.py   (never --deploy)

0.1.8 = THE MONK SKILL IS "ZEN" (Skyy LOCKED 2026-10-08, docs/answered/classes.md popup batch 1; research/classes/Monk.md). Data only:
  the FALLBACK roster's Monk card (ProfRoster.SKILLS - shown only when SkyyClasses is not loaded; with SkyyClasses the card's skill comes
  from its class:list, so 0.1.7 already shows "Zen" next to SkyyClasses 0.1.15) says Zen. The build-time check of the Assassin / Monk
  cards now reads SkyyClasses 0.1.15's build script (0.1.14 is the fallback when 0.1.15 is not there).
  Profile files store the CLASS name (p.<id>.class=Monk), never the skill - nothing is read or written differently. No migration, no
  key, no setting. ROLLBACK 0.1.8 -> 0.1.7: safe.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.7.py")
dst = os.path.join(ROOT, "SkyyProfiles", "build_skyyprofiles_0.1.8.py")
raw = open(src, encoding="utf8", newline="").read()
CR, LF = chr(13), chr(10)
NL = CR + LF if (CR + LF) in raw else LF
s = raw.replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.1.7"' in s and "GENERATED by tools/profiles_0_1_7_patch.py from build_skyyprofiles_0.1.6.py" in s, "not the generated 0.1.7"
assert '"skill": "Zen"' not in s
CHANGES = []


def rep(old, new):
    global s
    n = s.count(old)
    assert n == 1, "anchor count %d: %s" % (n, old[:120])
    s = s.replace(old, new, 1)
    CHANGES.append((new, old))


rep('''"""SkyyProfiles 0.1.7 - build script (javassist via jpype). SkyBlock-style profiles for SkyWynn = the class selector.
Run:   python build_skyyprofiles_0.1.7.py          -> SkyyProfiles/SkyyProfiles-0.1.7.jar''',
    '''"""SkyyProfiles 0.1.8 - build script (javassist via jpype). SkyBlock-style profiles for SkyWynn = the class selector.
Run:   python build_skyyprofiles_0.1.8.py          -> SkyyProfiles/SkyyProfiles-0.1.8.jar''')
rep('''GENERATED by tools/profiles_0_1_7_patch.py from build_skyyprofiles_0.1.6.py (generated by tools/profiles_0_1_6_patch.py from 0.1.5,''',
    '''GENERATED by tools/profiles_0_1_8_patch.py from build_skyyprofiles_0.1.7.py (generated by tools/profiles_0_1_7_patch.py from 0.1.6,
generated by tools/profiles_0_1_6_patch.py from 0.1.5,''')
rep('''Harness: python SkyyProfiles/test_skyyprofiles_0.1.7.py

0.1.7 (2026-10-08, Skyy's tests):''', '''Harness: python SkyyProfiles/test_skyyprofiles_0.1.8.py

0.1.8 (2026-10-09, Skyy LOCKED 2026-10-08 the Monk skill "Zen"): the fallback roster's Monk card says Zen (used only without SkyyClasses;
  with it the card's skill comes from class:list). Data only - no saved data, key or setting. Full notes in tools/profiles_0_1_8_patch.py.

0.1.7 (2026-10-08, Skyy's tests):''')
rep('VERSION = "0.1.7"\n', 'VERSION = "0.1.8"\n')
rep('''    {"name": "Monk", "skill": "Discipline", "color": "#f08a30", "enabled": True, "role": "Self-speed disruptor",
''', '''    # 0.1.8 (Skyy LOCKED 2026-10-08): the Monk's skill is "Zen" (= SkyyClasses 0.1.15)
    {"name": "Monk", "skill": "Zen", "color": "#f08a30", "enabled": True, "role": "Self-speed disruptor",
''')
rep('''_cs14 = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "SkyyClasses", "build_skyyclasses_0.1.14.py")
''', '''_cs14 = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "SkyyClasses", "build_skyyclasses_0.1.15.py")   # 0.1.8: Zen
need(os.path.isfile(_cs14), "0.1.8: the SkyyClasses 0.1.15 build script (the Monk = Zen) is there to compare the cards with")
''')

_code = s[s.index('VERSION = "0.1.8"'):]
_code = LF.join(ln for ln in _code.split(LF) if not ln.lstrip().startswith("#"))
assert "discipline" not in _code.lower(), "0.1.8: a Discipline text is left"
_u = s
for _new, _old in reversed(CHANGES):
    assert _u.count(_new) == 1, "a change is not unique any more: %s" % _new[:80]
    _u = _u.replace(_new, _old, 1)
assert _u == OLD, "the generated script differs from 0.1.7 outside the recorded changes"
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline="").write(s.replace(LF, NL))
print("wrote", os.path.relpath(dst, ROOT), "(%d lines; 0.1.7 had %d; %d changes)" % (s.count(LF), OLD.count(LF), len(CHANGES)))
