"""Derive SkyyTrees/build_skyytrees_0.3.2.py from the LIVE SkyyTrees/build_skyytrees_0.3.1.py (the tools/deploy_set.py SET pin).
Run:  python tools/trees_0_3_2_patch.py   then   python SkyyTrees/build_skyytrees_0.3.2.py   (never --deploy: coordinated deploy)
      then python SkyyTrees/test_skyytrees_0.3.2.py (the bare-JVM harness; needs SkyyTrees-0.3.1.jar, the SET pin, next to it)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.2.3 -> trees_0_2_4_patch.py -> 0.2.4 -> trees_0_2_5_patch.py -> 0.2.5
-> trees_0_3_patch.py -> 0.3 -> trees_0_3_1_patch.py -> the generated 0.3.1 read here; tools/trees_0_2_3_patch.py and older are NEVER
re-run. Edit THIS file, never the generated build script. Same style as trees_0_3_1_patch.py (rep() with asserted single anchors,
newline-agnostic; 0.3.1 stays untouched, its line endings are kept; KEEP blocks assert the parts 0.3.2 must not touch).

0.3.2 = Skyy LOCKED 2026-10-05 "CLASS TREES On" (docs/log/2026-10.md 2026-10-05: "pack default ON in the next SkyyTrees build"):
  (1) THE PACK DEFAULT of class.enabled becomes ON: the default file writes class.enabled=true (its comment line says so and carries the
      marker skyytrees-0.3.2-classon), a missing / unreadable line reads ON (TreeCfg), the Server Setup row's default is true. The
      0.3 one-time update (TreeMig) appends the same class block to a pre-0.3 file, so such a file gets class.enabled=true + the marker.
  (2) ONE-TIME MIGRATION of an existing trees.properties (new class TreeMig32, setup() runs it right AFTER TreeMig.run, before
      CfgPub.start), PROJECT-RULES section 4:
      - runs once: a comment line holding the marker skyytrees-0.3.2-classon = never again (the default file and the 0.3 block carry it;
        every run that decides writes the marker line);
      - flips the line ONLY while it still holds the old default (false, or off - which the loader read as the old default false) AND
        nobody set it by hand: a config-changes.log (+ .1 .. .3) line keyed class.enabled from anyone but this update = set by a person
        -> KEPT and named in an INFO line. A value that is true already (Skyy switched it on live), a doubled or continued line, a value
        that is no true / false (kept as typed) and a missing line are not rewritten either; each gets an INFO line and the marker.
      - the flip changes the value text of that ONE physical line ("false" -> "true", the separator, spacing and the rest of the file
        byte for byte, the file's own line ending); the marker comment line is appended after the old bytes (a missing final newline
        added first). A Properties check (every other key keeps its value, class.enabled = true only on a flip, nothing added) guards it.
      - History first: CfgHist.snapshot of the old bytes ("before the 0.3.2 class trees ON update") and NO write unless config-history
        really holds them (TreeMig.mgSaved); written with the kit's atomicWrite; one config-changes.log line in the kit's format
        "SkyyTrees 0.3.2 - update class.enabled false -> true ok" so Server Setup -> Trees -> Changes -> Undo puts it back; then
        TreeCfg.CLASS_ON = true for this start (TreeCfg.load ran before the flip).
      - any failure (unreadable file / change log, History not writable, the Properties check) writes nothing: WARN, the file is used
        as it is (class trees stay as the file says), the next start tries again.
  UNCHANGED: everything else - the class rules, saved data (still v=2), the 41 Server Setup rows (one default), TreeMig 0.3 (its marker,
    labels and code; only the class block it appends now says true), commands, permissions, the probe page, the template trees.
  ROLLBACK: 0.3.2 -> 0.3.1 is safe (same files and keys; 0.3.1 reads class.enabled=true like any hand-set value, so class trees stay
    ON - switch them OFF in Server Setup if wanted; a file without the line would read OFF there). Never below 0.3 (the floor stands).
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.1.py")
dst = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.2.py")
raw = open(src, "rb").read()
NL = "\r\n" if b"\r\n" in raw else "\n"
assert NL == "\n" or raw.count(b"\r\n") == raw.count(b"\n"), "mixed line endings in 0.3.1"
s = raw.decode("utf8").replace("\r\n", "\n")
LF = "\n"
OLD = s
# the source must be the generated 0.3.1 of the edited lineage (the SET pin)
assert 'VERSION = "0.3.1"' in s and "GENERATED by tools/trees_0_3_1_patch.py from the LIVE build_skyytrees_0.3.py" in s, \
    "build_skyytrees_0.3.1.py is not the live 0.3.1 of the edited lineage"
for _a in ('MG_WHO = "SkyyTrees 0.3"', "public static boolean[] intactOf(boolean[] own, int ci) {", "def class_page_java():",
           "public static synchronized String run(java.nio.file.Path base) {", "import skyyui as SUI"):
    assert _a in s, "not the live 0.3.1: missing %r" % _a
REG0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    assert s.count(old) == count, "anchor count %d != %d: %s" % (s.count(old), count, old[:120])
    s = s.replace(old, new)


def block(a, b):
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


# blocks that must come out of this patch byte-identical: the node table .. the class tree template, every class from TreeDefs up to
# TreeCfg's apply, TreeData .. the page builder, the config kit rows before the class rows, TreeMig (the 0.3 one-time update) and the
# commands
KEEP = [block("# ================= the node table (spec 5 + 6, Cooking spec 7.2) =================",
              "# 0.3 part 2: the class tree block - every class.* key TreeCfg reads has a line here"),
        block("# ================= TreeData: one profile's tree state =================",
              "# custom: table (no hand-edit log, no History restore - CONFIG-CONTRACT \"Known limits\")"),
        block("# ================= 0.3 TreeMig: the ONE-TIME Alchemy + Smithing update of an existing trees.properties =================",
              "# ================= commands (HANDOFF command rules) ================="),
        block("# ================= commands (HANDOFF command rules) =================", "# ================= plugin =================")]

# ================================================================================================================ docstring
DOC_OLD = '''"""SkyyTrees 0.3.1 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_1_patch.py from the LIVE build_skyytrees_0.3.py (the SET pin) - edit the patch, not this file. 0.3 was
GENERATED'''
DOC_NEW = '''"""SkyyTrees 0.3.2 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_2_patch.py from the LIVE build_skyytrees_0.3.1.py (the SET pin) - edit the patch, not this file. 0.3.1
was GENERATED by tools/trees_0_3_1_patch.py from the LIVE build_skyytrees_0.3.py.
0.3 was GENERATED'''
rep(DOC_OLD, DOC_NEW)
rep('''0.3.1 (2026-10-03; Skyy's answers to the SkyyTrees 0.3 questions, LOCKED''', '''0.3.2 (2026-10-05; Skyy LOCKED 2026-10-05 "CLASS TREES On"; full notes: tools/trees_0_3_2_patch.py):
  (1) class.enabled defaults to ON: the default file line class.enabled=true (+ the marker skyytrees-0.3.2-classon in its comment), a
    missing / unreadable line reads ON, the Server Setup row's default is true; the 0.3 update's class block (pre-0.3 files) says true.
  (2) ONE-TIME MIGRATION (TreeMig32, right after TreeMig in setup()): an existing trees.properties whose class.enabled line still holds
    the old default (false / off) and that nobody set by hand (no config-changes.log line keyed class.enabled from anyone else) gets
    that ONE value rewritten to true; every other byte and the line endings are kept; History copy first (verified), one change-log line
    "class.enabled false -> true" (Server Setup -> Trees -> Changes -> Undo), the marker comment line appended so it never runs again.
    A hand-set value, true already, a doubled / continued line, an unreadable value or a missing line: kept + INFO, marker only.
  UNCHANGED: the class rules, saved data, commands, permissions, TreeMig 0.3, the template trees, the probe page.
  CHECKED: see SkyyTrees/test_skyytrees_0.3.2.py (bare JVM; the migration matrix on scratch copies, class trees ON on copies of the live
    player files, class bytes 0.3.1 vs 0.3.2).

=== SkyyTrees 0.3.1 notes (history; still true unless 0.3.2 above says otherwise) ===
0.3.1 (2026-10-03; Skyy's answers to the SkyyTrees 0.3 questions, LOCKED''')
rep('''Run:   python build_skyytrees_0.3.1.py            -> SkyyTrees/SkyyTrees-0.3.1.jar
       python build_skyytrees_0.3.1.py --deploy   -> also''', '''Run:   python build_skyytrees_0.3.2.py            -> SkyyTrees/SkyyTrees-0.3.2.jar
       python build_skyytrees_0.3.2.py --deploy   -> also''')

# ================================================================================================================ version
rep('VERSION = "0.3.1"', 'VERSION = "0.3.2"')

# ================================================================================================================ (1) the default ON
MK32 = "skyytrees-0.3.2-classon"
rep('''CLASS_SCALARS = [("class.enabled", "false"), ''', '''CLASS_SCALARS = [("class.enabled", "true"), ''')   # 0.3.2: Skyy LOCKED 2026-10-05 "CLASS TREES On"
rep('''              "# class.enabled=false until Skyy has seen /tree probe (admin) work; switch it on in Server Setup -> Trees -> Class trees.",''',
    '''              # 0.3.2: the marker of the one-time class trees ON update (TreeMig32 never touches a file whose comment lines hold it)
              "# class.enabled=true: class trees are ON by default since SkyyTrees 0.3.2 (Skyy 2026-10-05; marker %s)." % MK32_ID,''')
rep('''# 0.3 part 2: the class tree block - every class.* key TreeCfg reads has a line here''',
    '''MK32_ID = %s   # 0.3.2: TreeMig32's marker (in the class block's comment line: the default file and the 0.3 block carry it)
# 0.3 part 2: the class tree block - every class.* key TreeCfg reads has a line here''' % repr(MK32))
rep('''< DEFAULTS.index("class.enabled=false")''',
    '''< DEFAULTS.index("class.enabled=true")
assert DEFAULTS.count(MK32_ID) == 1 and [l for l in DEFAULTS.splitlines() if MK32_ID in l][0].startswith("# ") and "\\nclass.enabled=" not in DEFAULTS.replace("\\nclass.enabled=true\\n", "")''')
rep('''assert ADD03[0] == ("", MG_MARK), "TreeMig re-adds only ADD_LINE[0] (the marker) to a file that holds every keyed line"''',
    '''assert ADD03[0] == ("", MG_MARK), "TreeMig re-adds only ADD_LINE[0] (the marker) to a file that holds every keyed line"
assert ("class.enabled", "class.enabled=true") in ADD03 and sum(1 for _k, l in ADD03 if MK32_ID in l and l.startswith("# ")) == 1, \\
    "0.3.2: the 0.3 block of a pre-0.3 file says class.enabled=true and carries the 0.3.2 marker"''')
rep('''             "boolean CLASS_ON = false", "int AP_FIRST = 1",''', '''             "boolean CLASS_ON = true", "int AP_FIRST = 1",''')
rep('''  // 0.3 part 2: the class tree (class.enabled ships false; class.nodes.<Class>.<Id>=<on>,<amount>,<ap>; class.minLevel.<Class>.<Id>)
  CLASS_ON = bool(p, "class.enabled", false);''', '''  // 0.3 part 2: the class tree (class.nodes.<Class>.<Id>=<on>,<amount>,<ap>; class.minLevel.<Class>.<Id>); 0.3.2: class.enabled
  // defaults to ON (Skyy 2026-10-05) - a missing or unreadable line reads true
  CLASS_ON = bool(p, "class.enabled", true);''')
rep('''    ("class.enabled", "Class trees", "classes", "bool", "false", "", "", "", "", "live",
     "ON = the class tab, its stats and tree:names Class. Keep OFF until /tree probe looked right.", "reload"),''',
    '''    ("class.enabled", "Class trees", "classes", "bool", "true", "", "", "", "", "live",
     "ON = the class tab, its stats and tree:names Class. ON by default since 0.3.2 (Skyy 2026-10-05).", "reload"),''')

# ================================================================================================================ (2) TreeMig32
MIG32 = r'''
# ================= 0.3.2 TreeMig32: the ONE-TIME class trees ON update of an existing trees.properties =================
# setup() only, right AFTER TreeMig.run (a pre-0.3 file has the 0.3 block - class.enabled=true + this marker - by then) and BEFORE
# CfgPub.start. PROJECT-RULES 4, TreeMig's machinery: the marker in a comment line = never again; the pure text step m32Update rewrites
# ONLY the value text of the one class.enabled line while it holds the old default (false / off) and nobody set it by hand (byHand: a
# config-changes.log line keyed class.enabled from anyone but this update), keeps every other byte and the line ending, and appends the
# marker line; sameAfter32 (Properties: nothing else changes); History snapshot + TreeMig.mgSaved before the write; one Undo-able
# change-log line; TreeCfg.CLASS_ON follows the flip for this start (load ran before it).
mig32 = pool.makeClass(PKG + ".TreeMig32")
for _d in ("public static final String MK = %s;" % json.dumps(MK32_ID),
           'public static final String WHO = "SkyyTrees 0.3.2";',
           'public static final String KEY = "class.enabled";',
           "public static final String MARK_LINE = %s;" % json.dumps(
               "# ---------- SkyyTrees 0.3.2 (added once - marker %s): class trees are ON by default (Skyy 2026-10-05) ----------" % MK32_ID)):
    F(mig32, _d)
M(mig32, r"""
public static boolean marked(java.util.ArrayList l) {
  int k = 0;
  while (k < l.size()) {
    String s = (String) l.get(k);
    if (@PKG@.CfgFile.isComment(s)) { if (s.indexOf(MK) >= 0) return true; k++; continue; }
    k = @PKG@.CfgFile.end(l, k) + 1;
  }
  return false;
}""")
# 1 = a person changed class.enabled (in game, by command or a hand edit the kit logged: a config-changes.log or .1 - .3 line keyed
# class.enabled whose who is not this update), 0 = never, -1 = a log file exists but cannot be read (the caller writes nothing)
M(mig32, r"""
public static int byHand(java.nio.file.Path home) {
  for (int n = 0; n <= 3; n++) {
    java.nio.file.Path f = home.resolve(n == 0 ? "config-changes.log" : "config-changes.log." + n);
    if (!java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) continue;
    try {
      String[] ls = new String(java.nio.file.Files.readAllBytes(f), "ISO-8859-1").split("\n");
      for (int i = 0; i < ls.length; i++) {
        String[] c = ls[i].split("\t", -1);
        if (c.length >= 7 && KEY.equals(c[4].trim()) && !WHO.equals(c[1].trim())) return 1;
      }
    } catch (Throwable t) { return -1; }
  }
  return 0;
}""")
# pure text step (ISO-8859-1 chars). null = the marker is already in a comment line or the text cannot be read as Properties. Else
# { new text, String state, String the old value (trimmed, "" when there is none) }; state: "flip" (the one line now says true),
# "hand" (false / off set by a person - kept), "odd" (false / off on a doubled or continued line - kept), "on" (true already),
# "missing" (no line: the code default ON applies), "other" (no true / false - kept, read as the default ON). Never throws.
M(mig32, r"""
public static Object[] m32Update(String text, int hand) {
  try {
    java.util.ArrayList l = @PKG@.CfgFile.split(text);
    if (marked(l)) return null;
    java.util.Properties p = new java.util.Properties();
    p.load(new java.io.StringReader(text));
    String v = p.getProperty(KEY);
    int cnt = 0;
    int at = -1;
    int k = 0;
    while (k < l.size()) {
      String s = (String) l.get(k);
      if (@PKG@.CfgFile.isComment(s)) { k++; continue; }
      int e = @PKG@.CfgFile.end(l, k);
      if (KEY.equals(@PKG@.CfgFile.key(s))) { cnt++; at = e == k ? k : -2; }
      k = e + 1;
    }
    String eol = text.indexOf("\r\n") >= 0 ? "\r\n" : "\n";
    String state = "other";
    String vt = v == null ? "" : v.trim();
    String body = text;
    if (v == null) state = "missing";
    else if (vt.equalsIgnoreCase("true")) state = "on";
    else if (vt.equalsIgnoreCase("false") || vt.equalsIgnoreCase("off")) {
      if (hand != 0) state = "hand";
      else if (cnt != 1 || at < 0) state = "odd";
      else {
        String s = (String) l.get(at);
        int vs = @PKG@.CfgFile.valStart(s);
        String rv = s.substring(vs);
        String tok = rv.trim();
        if (rv.indexOf('\\') >= 0 || !rv.startsWith(tok) || !tok.equalsIgnoreCase(vt)) state = "odd";
        else {
          int off = 0;
          for (int i = 0; i < at; i++) off = text.indexOf('\n', off) + 1;
          if (!text.startsWith(s, off)) return null;
          body = text.substring(0, off) + s.substring(0, vs) + "true" + rv.substring(tok.length()) + text.substring(off + s.length());
          state = "flip";
        }
      }
    }
    StringBuilder sb = new StringBuilder(body.length() + 160);
    sb.append(body);
    if (body.length() > 0 && !body.endsWith("\n")) sb.append(eol);
    sb.append(MARK_LINE).append(eol);
    return new Object[] { sb.toString(), state, vt };
  } catch (Throwable t) { return null; }
}""")
# the update may change at most class.enabled (to true, on a flip): both texts as Properties, every other key keeps its value, nothing
# is added or removed
M(mig32, r"""
public static boolean sameAfter32(byte[] old, byte[] nb, boolean flip) {
  try {
    java.util.Properties a = new java.util.Properties();
    java.util.Properties b = new java.util.Properties();
    a.load(new java.io.ByteArrayInputStream(old));
    b.load(new java.io.ByteArrayInputStream(nb));
    if (a.size() != b.size()) return false;
    java.util.Iterator it = a.stringPropertyNames().iterator();
    while (it.hasNext()) {
      String k = (String) it.next();
      if (flip && KEY.equals(k)) { String nv = b.getProperty(k); if (nv == null || !"true".equals(nv.trim())) return false; continue; }
      if (!a.getProperty(k).equals(b.getProperty(k))) return false;
    }
    return true;
  } catch (Throwable t) { return false; }
}""")
M(mig32, r"""
public static synchronized String run(java.nio.file.Path base) {
  if (base == null) return "";
  java.nio.file.Path f = base.resolve("trees.properties");
  try {
    if (!java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) return "";
    byte[] old = java.nio.file.Files.readAllBytes(f);
    String text = new String(old, "ISO-8859-1");
    if (marked(@PKG@.CfgFile.split(text))) return "";
    int hand = byHand(f.toAbsolutePath().getParent());
    if (hand < 0) {
      @PKG@.TreeCfg.warn("trees.properties NOT updated for SkyyTrees 0.3.2 (class trees ON): config-changes.log could not be read (the file is used as it is; the next start tries again)");
      return "";
    }
    Object[] r = m32Update(text, hand);
    if (r == null) return "";
    String state = (String) r[1];
    String ov = (String) r[2];
    boolean flip = "flip".equals(state);
    byte[] data = ((String) r[0]).getBytes("ISO-8859-1");
    if (!sameAfter32(old, data, flip)) {
      @PKG@.TreeCfg.warn("trees.properties NOT updated for SkyyTrees 0.3.2 (class trees ON): the update would change more than class.enabled (the file is used as it is; the next start tries again)");
      return "";
    }
    int fi = @PKG@.TreeMig.fileIdx();
    if (fi < 0) return "";
    @PKG@.TreeMig.mgKit(f.toAbsolutePath().getParent());
    @PKG@.CfgHist.snapshot(fi, old, @PKG@.CfgHist.stamp(), WHO, "before the 0.3.2 class trees ON update");
    if (!@PKG@.TreeMig.mgSaved(fi, old)) {
      @PKG@.TreeCfg.warn("trees.properties NOT updated for SkyyTrees 0.3.2 (class trees ON): the old file could not be kept in " + @PKG@.CfgHist.DIR + " (the file is used as it is; the next start tries again)");
      return "";
    }
    @PKG@.CfgRows.atomicWrite(f, data);
    String msg;
    if (flip) {
      @PKG@.CfgLog.enqueue(@PKG@.CfgLog.now() + "\t" + WHO + "\t-\tupdate\t" + KEY + "\tfalse\ttrue\tok");
      @PKG@.CfgLog.flush();
      @PKG@.TreeCfg.CLASS_ON = true;
      msg = "trees.properties updated for SkyyTrees 0.3.2: class.enabled " + ov + " -> true - class trees are ON (Skyy 2026-10-05: the new pack default; the old file is in config-history; Server Setup -> Trees -> Changes can undo it)";
    } else if ("hand".equals(state)) msg = "class.enabled=" + @PKG@.CfgRows.oneLine(ov) + " kept - it was set by hand (config-changes.log); the 0.3.2 default is ON (Server Setup -> Trees -> Class trees)";
    else if ("odd".equals(state)) msg = "class.enabled=" + @PKG@.CfgRows.oneLine(ov) + " kept - the line is doubled or continues on the next line; switch class trees on in Server Setup -> Trees -> Class trees";
    else if ("on".equals(state)) msg = "class.enabled=true already - class trees are ON (nothing to change)";
    else if ("missing".equals(state)) msg = "trees.properties has no class.enabled line - class trees follow the 0.3.2 default: ON";
    else msg = "class.enabled=" + @PKG@.CfgRows.oneLine(ov) + " kept (not true or false) - read as the 0.3.2 default: ON";
    msg = msg + " [marker " + MK + " added, runs once]";
    @PKG@.TreeCfg.info(msg);
    return msg;
  } catch (Throwable t) {
    @PKG@.TreeCfg.warn("could not update trees.properties for SkyyTrees 0.3.2 (class trees ON; the file is used as it is): " + t);
    return "";
  }
}""")

'''
rep('''
# ================= commands (HANDOFF command rules) =================''', MIG32 + '''# ================= commands (HANDOFF command rules) =================''')
rep('''  @PKG@.TreeMig.run(base);   // 0.3: the Alchemy + Smithing lines and the Mining Dust rate, once (History first; Undo in Server Setup)''',
    '''  @PKG@.TreeMig.run(base);   // 0.3: the Alchemy + Smithing lines and the Mining Dust rate, once (History first; Undo in Server Setup)
  @PKG@.TreeMig32.run(base);   // 0.3.2: class.enabled false -> true once, only while it holds the old default (History first; Undo)''')
rep('''ALL = (defs, cfg, dat, sto, stk, calc, cls, fx, swg, msg, abil, gat, tfn, bfn, ffn, dmg, tick, svr, ops, cops, page, kitc, mig, vcmd,''',
    '''ALL = (defs, cfg, dat, sto, stk, calc, cls, fx, swg, msg, abil, gat, tfn, bfn, ffn, dmg, tick, svr, ops, cops, page, kitc, mig, mig32, vcmd,''')

# ================================================================================================================ checks on the result
assert s.count("registerSystem(") == REG0, "0.3.2 adds no system"
assert s.count("registerCommand(") == CMD0, "command registrations changed"
for kb in KEEP:
    assert kb in s, "a block that must stay 0.3.1's changed: %s" % kb[:80]
_ix = s.index
assert _ix("public static boolean mgSaved(int f, byte[] old) {") < _ix('mig32 = pool.makeClass(PKG + ".TreeMig32")') < _ix("public static Object[] m32Update(String text, int hand) {") \
    < _ix("public static boolean sameAfter32(byte[] old, byte[] nb, boolean flip) {") < _ix('''public static synchronized String run(java.nio.file.Path base) {
  if (base == null) return "";
  java.nio.file.Path f = base.resolve("trees.properties");
  try {
    if (!java.nio.file.Files.exists(f, new java.nio.file.LinkOption[0])) return "";
    byte[] old = java.nio.file.Files.readAllBytes(f);
    String text''') < _ix("@PKG@.TreeMig32.run(base);"), "javassist: methods before their callers"
assert 'MG_WHO = "SkyyTrees 0.3"' in s and 'MG_MARK_ID = "skyytrees-0.3-trees"' in s, "the 0.3 one-time update keeps its marker and labels"
assert s.count('"class.enabled", "true"') == 1 and 'bool(p, "class.enabled", true)' in s and '"class.enabled", false' not in s
assert "KEEP=10" in s and "KEEP=20" not in s
assert all(len(_l) <= 140 for _l in s[:s.index("=== SkyyTrees 0.3.1 notes")].split(LF)), "docstring lines <= 140: %s" % [_l for _l in s[:s.index("=== SkyyTrees 0.3.1 notes")].split(LF) if len(_l) > 140]
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline=NL).write(s)   # keep the line endings of 0.3.1
print("wrote", dst, "(%d lines; 0.3.1 had %d)" % (s.count(LF), OLD.count(LF)))
