"""Derive SkyyTrees/build_skyytrees_0.3.4.py from the LIVE generated SkyyTrees/build_skyytrees_0.3.3.py (the tools/deploy_set.py SET pin).
Run:  python tools/trees_0_3_4_patch.py   then   python SkyyTrees/build_skyytrees_0.3.4.py   (never --deploy: coordinated deploy)
      then python SkyyTrees/test_skyytrees_0.3.4.py --dir <tools/dev/scratch/<task>/...> (bare JVM; needs SkyyTrees-0.3.3.jar, the SET pin)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.2.3 -> trees_0_2_4_patch.py -> ... -> trees_0_3_3_patch.py -> the
generated 0.3.3 read here; tools/trees_0_2_3_patch.py and older are NEVER re-run. Edit THIS file, never the generated build script. Same
style as trees_0_3_3_patch.py (rep() with asserted single anchors, newline-agnostic; 0.3.3's line endings are kept).

0.3.4 = LOG FIX (Skyy's 2026-10-09 play session server log, twice: '[Hytale] Missing interaction **Skyy_Tree_Chop_Wood_Next_Next' and
'**Skyy_Tree_Chop_Wood_Next_Failed'; the round task "get everything on your list done while im at work"):
  WHAT IT IS: Skyy_Tree_Chop_Wood is the 0.2.4 hatchet chain (the chopping-speed bonus only on wood - NOT Tree Feller, which is Java: the
    BreakBlockEvent hook TreeAbil). It was one file with INLINE steps (BlockCondition -> inline EffectCondition -> inline tier tree). The
    engine builds a batch's client packet (HytaleAssetStore.handleRemoveOrUpdate -> InteractionPacketGenerator -> configurePacket ->
    Interaction.getInteractionIdOrUnknown) BEFORE it loads that batch's inline children (AssetStore.loadAssets0, then
    loadContainedAssets), so an inline step's engine name ('**<file>_Next_Next') is "missing" for a moment: the engine logs the WARN and
    puts a placeholder SendMessage under Hytale:Hytale, then loads the real step over it - the same class of problem SkyySkills 0.4.23 fixed
    for its rolls (tools/skills_0_4_23_patch.py). In a bare JVM the 0.3.3 jar's 5 interaction files log 80+ such lines (every inline step
    of Skyy_Tree_Swing_Mine / _Swing_Chop / _Chop / _Chop_Wood); the live server showed the 2 above.
  FIX: NO INLINE STEPS. Every SkyyTrees interaction file is flattened at build time: each inline interaction (a Next / Failed object, a
    Chaining entry, an interaction inside an inline root of a Parallel branch / Replace default / Selector hit chain) becomes its OWN NAMED
    file in the same folder (Server/Item/Interactions/SkyyTrees/, this jar's one Interactions batch), so every name resolves before the
    packet is built. Inline ROOTS (the Parallel branches, Replace defaults, the Selector's HitEntity) stay inline objects - their engine
    names are not looked up by getInteractionIdOrUnknown (0 lines in the bare JVM). Names: the tier trees by meaning
    (<file>_If_<a>_<b> = the EffectCondition "none of tiers a..b", <file>_Tier_<k> = the TriggerCooldown of tier k (00 = the vanilla
    rest), Skyy_Tree_Chop_Wood_NotWood = the not-wood leaf, Skyy_Tree_Swing_Chop_Reset = the 0.35 s reset), the vanilla Hatchet_Chop copy by
    place (<file>_N, _N_P0, _N_P0_N, _N_P0_HE, _N_P1, _N_P2). Every 0.3.3 inline step = exactly one named file (none shared): 5 files -> 173
    interaction files; the 80 effect files and the 2 root overrides are unchanged.
  BEHAVIOUR UNCHANGED (asserted at build time): every flattened file re-inlined equals 0.3.3's file exactly (JSON, key order included);
    no inline step left anywhere; every name a file uses is ours or vanilla; no new id is a vanilla id; no Parallel with fewer than 2
    branches (the engine validator that once stopped the server). The harness loads both jars in a real asset store and compares the
    compiled root chains op by op.
  UNCHANGED: every class except the version strings, the Java (MINE_TREE / CHOP_TREE ids), saved data, settings, commands, permissions.
    No migration. ROLLBACK 0.3.4 -> 0.3.3: safe (the same chain inline, the 2 warnings come back).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.3.py")
dst = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.4.py")
raw = open(src, "rb").read()
NL = "\r\n" if b"\r\n" in raw else "\n"
assert NL == "\n" or raw.count(b"\r\n") == raw.count(b"\n"), "mixed line endings in 0.3.3"
s = raw.decode("utf8").replace("\r\n", "\n")
LF = "\n"
OLD = s
assert 'VERSION = "0.3.3"' in s and "GENERATED by tools/trees_0_3_3_patch.py from the LIVE build_skyytrees_0.3.2.py" in s, \
    "build_skyytrees_0.3.3.py is not the live 0.3.3 of the edited lineage"
assert "SWING_FLAT" not in s, "0.3.3 already has the 0.3.4 parts"
REG0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    assert s.count(old) == count, "anchor count %d != %d: %s" % (s.count(old), count, old[:140])
    s = s.replace(old, new)


# ================================================================================================================ header + version
rep('''"""SkyyTrees 0.3.3 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_3_patch.py from the LIVE build_skyytrees_0.3.2.py (the SET pin) - edit the patch, not this file. 0.3.2
was GENERATED''', '''"""SkyyTrees 0.3.4 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_4_patch.py from the LIVE build_skyytrees_0.3.3.py (the SET pin) - edit the patch, not this file. 0.3.3
was GENERATED by tools/trees_0_3_3_patch.py from the LIVE build_skyytrees_0.3.2.py. 0.3.2
was GENERATED''')
rep('''0.3.3 (2026-10-07; the CLASS PATH TREES - research/cloud/Class-Tree-Paths.md + Class-Tree-Build-Map.md; notes: tools/trees_0_3_3_patch.py):''',
    '''0.3.4 (2026-10-09; LOG FIX - Skyy's play log: 'Missing interaction **Skyy_Tree_Chop_Wood_Next_Next' / '_Next_Failed'; notes:
    tools/trees_0_3_4_patch.py): the hatchet wood chain and every other SkyyTrees interaction file ship as NAMED files only (no inline
    step; the engine builds a batch's client packet before it loads inline children - the SkyySkills 0.4.23 fix). 5 files -> 173, each
    re-inlined = 0.3.3's file exactly (asserted). Nothing else changes (no class logic, saved data, settings or migration).
  CHECKED: SkyyTrees/test_skyytrees_0.3.4.py (bare JVM: engine validators, one-batch load = 0 missing lines, the compiled root chains
    op by op vs 0.3.3, class compare, -Xverify:all, the access audit, start twice on a copy of the live data).

=== SkyyTrees 0.3.3 notes (history; still true unless 0.3.4 above says otherwise) ===
0.3.3 (2026-10-07; the CLASS PATH TREES - research/cloud/Class-Tree-Paths.md + Class-Tree-Build-Map.md; notes: tools/trees_0_3_3_patch.py):''')
rep('''Run:   python build_skyytrees_0.3.3.py            -> SkyyTrees/SkyyTrees-0.3.3.jar
       python build_skyytrees_0.3.3.py --deploy   -> also''', '''Run:   python build_skyytrees_0.3.4.py            -> SkyyTrees/SkyyTrees-0.3.4.jar
       python build_skyytrees_0.3.4.py --deploy   -> also''')
rep('VERSION = "0.3.3"', 'VERSION = "0.3.4"')

# ================================================================================================================ the flattening
rep('''assert len(SWING_FILES) == 2 * SWING_MAX + 4 + 3   # 0.2.4: + the chop chain, swing copy and wood check''',
    '''assert len(SWING_FILES) == 2 * SWING_MAX + 4 + 3   # 0.2.4: + the chop chain, swing copy and wood check
# ---- 0.3.4 LOG FIX (Skyy's 2026-10-09 server log: 'Missing interaction **Skyy_Tree_Chop_Wood_Next_Next' / '_Next_Failed'): NO INLINE STEPS.
# The engine builds a batch's client packet (InteractionPacketGenerator -> configurePacket -> Interaction.getInteractionIdOrUnknown) before
# it loads that batch's inline children (AssetStore.loadAssets0: handleRemoveOrUpdate, then loadContainedAssets), so an inline step's
# engine name ('*'-prefixed) is "missing" for a moment (WARN + a Hytale:Hytale SendMessage placeholder, then the real step loads over it;
# the SkyySkills 0.4.23 roll fix). Every SkyyTrees interaction file is flattened here: each inline INTERACTION becomes its own named file in
# Server/Item/Interactions/SkyyTrees/ (this jar's one Interactions batch). Inline ROOTS (Parallel branches, Replace defaults, Selector hit
# chains) stay inline objects; the interactions inside them are named. Re-inlined, every file is exactly 0.3.3's (asserted below).
SWING_FILES_033 = dict(SWING_FILES)          # the 0.3.3 shapes (inline) - kept only for the checks
SWING_FLAT = {}                              # name -> body of every NEW named step (0.3.4)
_FLAT_TOPS = sorted(os.path.basename(_p)[:-5] for _p in SWING_FILES if _p.startswith("Server/Item/Interactions/"))
assert _FLAT_TOPS == sorted([swing_tree_id("Mine"), swing_tree_id("Chop")] + CHOP_NEW), _FLAT_TOPS
_TIER_RE = re.compile(r"^Skyy_Tree_Swing_(Mine|Chop)_(\\d\\d)$")
def _islots(x):
    """the interaction-valued places of one interaction body: (container, key, name token). Next / Failed (a Chaining's Next is a list);
    the interactions inside the inline roots of a Parallel branch, a Replace default and a Selector's HitEntity / HitBlock / rule Next"""
    out = []
    for _k, _tk in (("Next", "N"), ("Failed", "F")):
        _v = x.get(_k)
        if isinstance(_v, list): out += [(_v, _i, "%s%d" % (_tk, _i)) for _i in range(len(_v))]
        elif _v is not None: out.append((x, _k, _tk))
    _roots = []
    if x.get("Type") == "Parallel": _roots += [(x["Interactions"], _j, "P%d" % _j) for _j in range(len(x["Interactions"]))]
    if x.get("Type") == "Replace" and "DefaultValue" in x: _roots.append((x, "DefaultValue", "D"))
    if x.get("Type") == "Selector":
        _roots += [(x, _k, _tk) for _k, _tk in (("HitEntity", "HE"), ("HitBlock", "HB")) if _k in x]
        _roots += [(_r, "Next", "HR%d" % _ri) for _ri, _r in enumerate(x.get("HitEntityRules") or []) if "Next" in _r]
    for _c, _k, _tk in _roots:
        _rv = _c[_k]
        if isinstance(_rv, dict):
            _l = _rv.get("Interactions") or []
            out += [(_l, _i, _tk if len(_l) == 1 else "%s_%d" % (_tk, _i)) for _i in range(len(_l))]
    return out
def _flat_name(top, node, fallback):
    """tier-tree steps by meaning, the rest by place"""
    _t = node.get("Type")
    if _t == "EffectCondition":
        _m = [_TIER_RE.match(_e) for _e in node.get("EntityEffectIds", [])]
        if _m and all(_m):
            _ks = [int(_x.group(2)) for _x in _m]
            assert _ks == list(range(_ks[0], _ks[-1] + 1)), (top, _ks)
            return "%s_If_%02d_%02d" % (top, _ks[0], _ks[-1])
    if _t == "TriggerCooldown" and sorted(node) == ["Cooldown", "Next", "Type"]:
        _cd, _nx = node["Cooldown"]["Cooldown"], node["Next"]
        if top == swing_tree_id("Mine") and _nx == "Pickaxe_Attack" and _cd in SWING_CD: return "%s_Tier_%02d" % (top, SWING_CD.index(_cd))
        if top == "Skyy_Tree_Chop_Wood" and _nx == "Block_Break" and _cd in CHOP_CD: return "%s_Tier_%02d" % (top, CHOP_CD.index(_cd))
        if top == swing_tree_id("Chop") and _nx == "Skyy_Tree_Chop_Chain" and _cd == SWING_BASE: return top + "_Reset"
    return fallback
def _flatten(top, body, here):
    for _c, _k, _tk in _islots(body):
        _v = _c[_k]
        if isinstance(_v, dict):
            # the wood check's "not wood" leaf has the same body as tier 0 - its own file, so every 0.3.3 step stays exactly one step
            _nm = top + "_NotWood" if (top == "Skyy_Tree_Chop_Wood" and here == top and _tk == "F") else _flat_name(top, _v, here + "_" + _tk)
            _child = _copy.deepcopy(_v)
            _flatten(top, _child, _nm)
            assert _nm not in SWING_FLAT and _nm not in _FLAT_TOPS, "0.3.4: the name %s would be used twice" % _nm
            SWING_FLAT[_nm] = _child
            _c[_k] = _nm
def _reinline(body):
    """a flattened body with every NEW name put back inline (the 0.3.3 shape)"""
    _b = _copy.deepcopy(body)
    for _c, _k, _tk in _islots(_b):
        if isinstance(_c[_k], str) and _c[_k] in SWING_FLAT:
            _c[_k] = _reinline(SWING_FLAT[_c[_k]])
    return _b
def _has_inline(x, top=True):
    """True when anything below the top is an inline interaction object (a dict with a Type)"""
    if isinstance(x, dict):
        if not top and "Type" in x: return True
        return any(_has_inline(_v, False) for _v in x.values())
    if isinstance(x, list): return any(_has_inline(_v, False) for _v in x)
    return False
_FLAT_BODY = {}
for _top in _FLAT_TOPS:
    _p = "Server/Item/Interactions/SkyyTrees/%s.json" % _top
    _b = json.loads(SWING_FILES[_p])
    _flatten(_top, _b, _top)
    _FLAT_BODY[_top] = _b
for _top in _FLAT_TOPS:
    _p = "Server/Item/Interactions/SkyyTrees/%s.json" % _top
    if json.dumps(_reinline(_FLAT_BODY[_top]), indent=2) != SWING_FILES_033[_p]:
        raise SystemExit("0.3.4 flatten: %s re-inlined is not 0.3.3's file" % _top)
    SWING_FILES[_p] = json.dumps(_FLAT_BODY[_top], indent=2)
for _nm in sorted(SWING_FLAT):
    SWING_FILES["Server/Item/Interactions/SkyyTrees/%s.json" % _nm] = json.dumps(SWING_FLAT[_nm], indent=2)
# the checks: nothing inline left; every name a step uses is ours or vanilla; no new id is a vanilla id (any asset type); no Parallel with
# < 2 branches (the engine's validator: "Array size" - what once stopped the server); the expected file set
_FLAT_ALL = dict((_t, _FLAT_BODY[_t]) for _t in _FLAT_TOPS)
_FLAT_ALL.update(SWING_FLAT)
assert not [_n for _n, _b in _FLAT_ALL.items() if _has_inline(_b)], "0.3.4: an inline step is left"
for _n, _b in _FLAT_ALL.items():
    for _c, _k, _tk in _islots(_b):
        _r = _c[_k]
        assert isinstance(_r, str) and (_r in _FLAT_ALL or _r in V_INT), "0.3.4: %s names %r - neither ours nor vanilla" % (_n, _r)
    assert _b.get("Type") != "Parallel" or len(_b["Interactions"]) >= 2, "0.3.4: a Parallel with fewer than 2 branches: " + _n
for _n in SWING_FLAT:
    if _n in V_INT or _n in V_ROOT or _n in V_EFF or _n in V_ITEM: raise SystemExit("0.3.4 flatten: vanilla already has an asset " + _n)
    assert re.match(r"^Skyy_Tree_[A-Za-z0-9_]+$", _n) and not _n.startswith("*"), _n
def _fam(n): return max([_t for _t in _FLAT_TOPS if n.startswith(_t + "_")], key=len)   # the file a named step came from
_FLAT_N = dict((_t, len([_n for _n in SWING_FLAT if _fam(_n) == _t])) for _t in _FLAT_TOPS)
assert _FLAT_N[swing_tree_id("Mine")] == 2 * SWING_MAX - 1, _FLAT_N                     # 39 splits + 40 tier leaves
assert _FLAT_N["Skyy_Tree_Chop_Wood"] == 2 * SWING_MAX + 2 and _FLAT_N["Skyy_Tree_Chop"] == 6 and _FLAT_N["Skyy_Tree_Chop_Chain"] == 0, _FLAT_N
assert _FLAT_N[swing_tree_id("Chop")] == 1 and sum(_FLAT_N.values()) == len(SWING_FLAT), _FLAT_N   # Wood: If_01_40 + 39 + Tier_00..40 + NotWood
assert SWING_FLAT["Skyy_Tree_Chop_Wood_NotWood"] == SWING_FLAT["Skyy_Tree_Chop_Wood_Tier_00"] == {"Type": "TriggerCooldown", "Cooldown": {"Id": "Hatchet_Attack", "Cooldown": CHOP_CD[0]}, "Next": "Block_Break"}
assert _FLAT_BODY["Skyy_Tree_Chop_Wood"]["Failed"] == "Skyy_Tree_Chop_Wood_NotWood" and SWING_FLAT["Skyy_Tree_Chop_Wood_If_01_40"]["Next"] == "Skyy_Tree_Chop_Wood_Tier_00"
assert swing_tree_id("Chop") + "_Reset" in SWING_FLAT and "Skyy_Tree_Chop_Wood_Tier_00" in SWING_FLAT and "Skyy_Tree_Chop_Wood_If_01_40" in SWING_FLAT
assert SWING_FLAT["Skyy_Tree_Chop_N_P1"]["Next"] == "Skyy_Tree_Chop_Wood" and SWING_FLAT["Skyy_Tree_Chop_N"]["Type"] == "Parallel"
assert all(SWING_FLAT["Skyy_Tree_Chop_Wood_Tier_%02d" % _k]["Cooldown"]["Cooldown"] == CHOP_CD[_k] for _k in range(SWING_MAX + 1))
assert all(SWING_FLAT["%s_Tier_%02d" % (swing_tree_id("Mine"), _k)]["Cooldown"]["Cooldown"] == SWING_CD[_k] for _k in range(1, SWING_MAX + 1))
assert set(SWING_FILES_033) <= set(SWING_FILES) and len(SWING_FILES) == len(SWING_FILES_033) + len(SWING_FLAT)
assert all(SWING_FILES[_p] == SWING_FILES_033[_p] for _p in SWING_FILES_033 if not _p.startswith("Server/Item/Interactions/"))
print("0.3.4 named steps: %d interaction files -> %d (+%d named steps: %s), re-inlined = 0.3.3, no inline step, every name resolves"
      % (len(_FLAT_TOPS), len(_FLAT_TOPS) + len(SWING_FLAT), len(SWING_FLAT), ", ".join("%s %d" % (_t, _FLAT_N[_t]) for _t in _FLAT_TOPS)))''')

# ================================================================================================================ checks on the result
assert s.count("registerSystem(") == REG0, "0.3.4 adds no system"
assert s.count("registerCommand(") == CMD0, "command registrations changed"
# outside the header, the version and the new block, nothing changed
_a, _b = OLD.split("assert len(SWING_FILES) == 2 * SWING_MAX + 4 + 3")
assert s.endswith(LF + _b.split(LF, 1)[1]) and s.count("import copy as _copy") == 1 and s.index("import copy as _copy") < s.index("SWING_FILES_033 = dict(SWING_FILES)")
assert "KEEP=10" in s and "KEEP=20" not in s
assert all(len(_l) <= 140 for _l in s[:s.index("=== SkyyTrees 0.3.3 notes")].split(LF)), \
    "docstring lines <= 140: %s" % [_l for _l in s[:s.index("=== SkyyTrees 0.3.3 notes")].split(LF) if len(_l) > 140]
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline=NL).write(s)   # keep the line endings of 0.3.3
print("wrote", dst, "(%d lines; 0.3.3 had %d)" % (s.count(LF), OLD.count(LF)))
