"""Derive SkyyTrees/build_skyytrees_0.3.1.py from the LIVE SkyyTrees/build_skyytrees_0.3.py (the tools/deploy_set.py SET pin).
Run:  python tools/trees_0_3_1_patch.py   then   python SkyyTrees/build_skyytrees_0.3.1.py   (never --deploy: coordinated deploy)
      then python SkyyTrees/test_skyytrees_0.3.1.py (the bare-JVM harness; needs SkyyTrees-0.3.jar (the SET pin) and SkyyTrees-0.2.5.jar
      next to it: every 0.3 check is re-run on 0.3.1 against 0.2.5, and 0.3.1 is compared with 0.3)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.2.3 -> trees_0_2_4_patch.py -> 0.2.4 -> trees_0_2_5_patch.py -> 0.2.5
-> trees_0_3_patch.py -> the generated 0.3 read here; tools/trees_0_2_3_patch.py and older are NEVER re-run. Edit THIS file, never the
generated build script. Same style as trees_0_3_patch.py (rep() with asserted single anchors, newline-agnostic; 0.3 stays untouched,
its CRLF line endings are kept; KEEP blocks assert the parts 0.3.1 must not touch).

0.3.1 = Skyy's answers to the SkyyTrees 0.3 questions (OPEN-QUESTIONS.md "ANSWERED 2026-10-03 (Skyy, SkyyTrees 0.3 questions)"):
  (1) "Let waiting nodes be skipped": in the CLASS tree a node that waits for its reader mod (Strength until SkyyGear lists gear:extras,
      the Archer crossbow nodes until SkyySkills lists their keys, Mana Regen until skill:fn:manaregen exists) no longer blocks the
      nodes after it - the chain rule passes through it (and it counts for the lane rule); it stays unbuyable itself ("Coming with
      <mod>"). Once its reader is live, an unowned node of those kinds stays passable while it still holds up an owned node below it, so
      nothing bought through it breaks, refunds or counts twice. Undo checks on a copy that no other intact node breaks.
  (2) a DELETED class.minLevel row = NO class level needed (0.3 kept the built-in 15 / 15 / 50); 0 = none; an unreadable value keeps
      the built-in level. Help text + file comment updated.
  Unchanged: the template-tree tier skip (Skyy: yes), class trees OFF by default, saved data, config rows, TreeMig (the 0.3 one-time
  update), commands, permissions. The Python model in SkyyTrees/test_skyytrees_0.3.1.py restates both rules independently.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.py")
dst = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.1.py")
raw = open(src, "rb").read()
NL = "\r\n" if b"\r\n" in raw else "\n"
assert NL == "\n" or raw.count(b"\r\n") == raw.count(b"\n"), "mixed line endings in 0.3"
s = raw.decode("utf8").replace("\r\n", "\n")
LF = "\n"
OLD = s
# the source must be the generated 0.3 of the edited lineage (the SET pin, deployed 2026-10-03)
assert 'VERSION = "0.3"' in s and "GENERATED by tools/trees_0_3_patch.py from the LIVE build_skyytrees_0.2.5.py" in s, \
    "build_skyytrees_0.3.py is not the live 0.3 of the edited lineage"
for _a in ("0.3 FIX ROUND (2026-10-03, after the spec / data / UI reviews", 'MG_WHO = "SkyyTrees 0.3"', "public static boolean[] intact(@PKG@.TreeData d, int ci) {",
           "public static String cmdClass(java.util.UUID u, String a) {", "import skyyui as SUI", "def class_page_java():"):
    assert _a in s, "not the live 0.3: missing %r" % _a
REG0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")


def rep(old, new, count=1):
    global s
    assert s.count(old) == count, "anchor count %d != %d: %s" % (s.count(old), count, old[:120])
    s = s.replace(old, new)


def block(a, b):
    """the text from anchor a (included) to anchor b (excluded) of the CURRENT source (for unchanged-block asserts)"""
    assert s.count(a) == 1 and s.count(b) == 1, (a[:60], b[:60])
    return s[s.index(a):s.index(b)]


# blocks that must come out of this patch byte-identical: the template trees end to end (node table, swing assets, TreeDefs, TreeData,
# TreeStore, TreeCalc), TreeFx .. TreeOps (effects, abilities, gather, swing, tick, saver, template buy / respec), the probe ops, the
# template page builder, TreeMig (the 0.3 one-time update) and the commands / plugin
KEEP = [block("# ================= the node table (spec 5 + 6, Cooking spec 7.2) =================",
              "# ================= 0.3 PART 2: the class tree template (research/Skill-Trees-2-Spec.md 5-7, Skyy's answers 1-5 + 7) ================="),
        block("# ================= classes =================", "# ================= TreeCfg: trees.properties ================="),
        block("# ================= TreeData: one profile's tree state =================",
              "# ================= 0.3 part 2 TreeClass: the class tree's rules (spec 5: AP, the unlock rule, integrity), reader gating, bridge posts ======"),
        block("# ================= TreeFx: per-player effect vector + everything published from it =================",
              "# ================= 0.3 part 2 TreeClassOps: buy / Undo / respec of the class tree + the page texts (world thread; every rule re-checked) ===="),
        block("# ================= TreePage: the inline tree page (0.2.5: the vanilla UI kit, tools/skyyui.py) =================",
              "def class_tab_chain(app):"),
        block("# ================= 0.3 TreeMig: the ONE-TIME Alchemy + Smithing update of an existing trees.properties =================",
              "# ================= 0.3: ACCESS AUDIT - what the JVM would refuse at RUN time with IllegalAccessError (the SkyyUiProbe 0.3.1 guard) =======")]
# the class rules that 0.3.1 keeps word for word (the rest of TreeClass: AP, kinds, readers, posts, the bridge answers, /tree class)
KEEP_CLS = [block("public static String classOf(java.util.UUID u) {", "# INTEGRITY (spec 5): an owned node counts only while its chain is intact"),
            block("public static int spent(boolean[] it, int ci) {", "public static int reason(boolean[] own, boolean[] it, int ci, int n, int lvl, int apFree) {"),
            block("# 0 locked, 1 unlockable, 2 owned (intact), 3 coming, 4 owned but its chain is broken", "# the cell's state line (one 15 px bold line in 96 px"),
            block("# gold bars: a link is gold when both of its nodes are intact; per drawn piece of page pg (8 piece roles per slot)",
                  "# ================= TreeFx: per-player effect vector + everything published from it =================")]

# ================================================================================================================ docstring
DOC_HEAD_OLD = '''"""SkyyTrees 0.3 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_patch.py from the LIVE build_skyytrees_0.2.5.py (the SET pin of the EDITED lineage: Skyy's edited 0.2.3
-> trees_0_2_4_patch.py -> 0.2.4 -> trees_0_2_5_patch.py -> 0.2.5) - edit the patch, not this file; trees_0_2_3_patch.py and older
are never re-run. 0.2.5 was GENERATED by tools/trees_0_2_5_patch.py from the LIVE build_skyytrees_0.2.4.py. 0.2.4 was DERIVED
from the EDITED build_skyytrees_0.2.3.py by tools/trees_0_2_4_patch.py. 0.2.3 was derived from
0.2.2 by tools/trees_0_2_3_patch.py and then edited by Skyy in commit ab75b6c (locked defaults) - never re-run that patch; 0.2.2 was
derived from 0.2.1 by tools/trees_0_2_2_patch.py, 0.2.1 from 0.2 by tools/trees_0_2_1_patch.py, 0.2 from 0.1 by tools/trees_0_2_patch.py.
0.3 PART 1 (2026-10-02;'''
DOC_HEAD_NEW = '''"""SkyyTrees 0.3.1 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_1_patch.py from the LIVE build_skyytrees_0.3.py (the SET pin) - edit the patch, not this file. 0.3 was
GENERATED by tools/trees_0_3_patch.py from the LIVE build_skyytrees_0.2.5.py (the EDITED lineage: Skyy's edited 0.2.3 ->
trees_0_2_4_patch.py -> 0.2.4 -> trees_0_2_5_patch.py -> 0.2.5); trees_0_2_3_patch.py and older
are never re-run. 0.2.5 was GENERATED by tools/trees_0_2_5_patch.py from the LIVE build_skyytrees_0.2.4.py. 0.2.4 was DERIVED
from the EDITED build_skyytrees_0.2.3.py by tools/trees_0_2_4_patch.py. 0.2.3 was derived from
0.2.2 by tools/trees_0_2_3_patch.py and then edited by Skyy in commit ab75b6c (locked defaults) - never re-run that patch; 0.2.2 was
derived from 0.2.1 by tools/trees_0_2_2_patch.py, 0.2.1 from 0.2 by tools/trees_0_2_1_patch.py, 0.2 from 0.1 by tools/trees_0_2_patch.py.
0.3.1 (2026-10-03; Skyy's answers to the SkyyTrees 0.3 questions, LOCKED in OPEN-QUESTIONS.md "ANSWERED 2026-10-03 (Skyy, SkyyTrees
  0.3 questions)" - (1) "Let waiting nodes be skipped", (2) a deleted "class minimum level" row = no requirement, (3) the template-tree
  tier skip stays as built; class trees stay OFF by default in this build):
  (1) WAITING CLASS NODES ARE SKIPPED. A class node that waits for its reader mod - Strength until SkyyGear lists gear:extras (the
    physical classes' P1, X1, P4 and their Strength lanes), the Archer crossbow nodes until SkyySkills lists their keys, Mana Regen
    until SkyySkills' skill:fn:manaregen exists - no longer blocks the nodes after it: the chain rule passes through it as if it were
    owned, and it counts for the lane rule (a core needs 3 lane nodes, owned or skipped). The waiting node itself stays unbuyable
    (card "Coming", detail "Coming with <mod>", the Coming soon button, the 0.3 refusal), costs no AP and gives nothing. With today's
    live readers (SkyySkills' Mana Regen registry yes, gear:extras and the crossbow keys not yet) Archer, Warrior and Berserker now
    reach every node Mage reaches except their waiting nodes: Warrior ROOT P2 X2 P3 C3 C4 R1-R4 and Berserker ROOT P2 X2 P3 L1-L4 R3 R4
    (10 nodes / 16 AP each), Archer ROOT P2 X2 P3 C1-C4 (8 / 11 AP); Mage and Priest keep 19 nodes / 27 AP (0.3: the physical classes
    could buy ROOT only).
    RULES (TreeClass): skipKind = the node kinds that can wait (Strength, crossbow, Mana Regen; never Health / Mana nodes, never a rune /
    element slot, never the ROOT); skips(own) = the unowned, switched-on nodes of such a kind that wait for their reader NOW or still
    hold up an owned node below them (a node bought through them; leaves first, so a chain of skipped nodes C1 > C2 > C3 holds as a
    whole); intactOf(own) = 0.3's integrity fixpoint where a skip counts as a passable parent (the root or an owned / skipped parent,
    every Need intact, no Lock owned, switched on); passed = the skips reachable now; reason() takes an intact OR passed parent and
    laneHas (owned + passed) for the lane rule; everything else of 0.3's unlock rule is unchanged and in the same order.
    AP AND EFFECTS: spent AP, the stats SkyyTrees applies (Health, Mana), the bridge posts (gear:extras Strength, skill:fn:manaregen),
    tree:fn:level / tree:fn:bonus and tree:<uuid> still come ONLY from owned intact nodes - a skipped node is never spent, never a stat.
    WHEN THE READER APPEARS: the skipped node is no longer waiting but keeps holding up what was bought through it, so every such node
    stays intact (no refund, no stat change); the node becomes Unlockable for its own AP (bought once, counted once); the pick-one
    pair still works on owned nodes (X1 after X2 = "Pick one"). WHEN IT GOES AWAY AGAIN: owned nodes stay intact (0.3: coming never
    breaks an owned node), unowned ones wait (= skipped) again. Respec clears everything as in 0.3 (coins = level x perLevel).
    INTEGRITY: an admin who switches a node OFF still breaks its chain (an off node is never a skip); a hand-edited file that leaves out
    a Strength / crossbow / Mana Regen node above an owned node is accepted (the same state a player reaches while it waits); every
    other 0.3 integrity case is unchanged (no root, both picks, an off node, a gap at a Health / Mana node).
    UNDO (class.undo): the newest unlock of the page can be undone when no OTHER intact node would break - simulated on a copy without it
    (0.3 tested "an owned child with no other owned parent", which refused e.g. the Undo of a Might I bought after the reader appeared
    while Vitality I, bought through it while it waited, hangs on it - though nothing breaks). A real dependency still refuses with
    0.3's words ("Reservoir I cannot be undone - Focus I (P2) still needs it").
    PAGE: gold bars also run through a skipped node a chain really uses (TreeClass.used / lit: the passed parent of an intact or used
    node that has no intact parent of its own); the waiting node's detail Needs line says "Waits for SkyyGear - skipped until then: the
    nodes after it can be unlocked without it" (slots keep "until then it cannot be unlocked"); a locked node whose parent waits names
    the node to buy instead of the waiting one: card "Needs ROOT" (0.3 "Needs P1"), buy answer "Vitality I needs Root (ROOT) first (P1
    waits for SkyyGear and is skipped)". Everything else on the page is 0.3's.
  (2) class.minLevel: a DELETED line (Server Setup -> Trees -> Class trees -> Class level per node -> remove) = NO class level needed (0.3
    kept the built-in 15 / 15 / 50); typed 0 = none (as before); a line that holds no number keeps the built-in level (a typo cannot drop
    the lock). The default file and the one-time 0.3 update still write the LOCKED lines Archer.R2=15, R3=15, R4=50, so nothing changes
    until an admin deletes one. Row help "Removed or 0 = no level needed"; file comment "(a deleted line or 0 = no level needed)" - a
    trees.properties the 0.3 update already wrote keeps its old comment line (comment only; the live world never ran 0.3, so it gets
    the new one).
  UNCHANGED: the template trees (incl. the tier skip of part 1 - Skyy: yes), saved data (no new key, still v=2; 0.3 reads every 0.3.1
    file), the 41 Server Setup rows, TreeMig (the 0.3 one-time update, marker skyytrees-0.3-trees, its History / log labels say 0.3),
    commands, permissions, class.enabled=false, the probe page.
  ROLLBACK: 0.3.1 -> 0.3 is safe (same files and keys); under 0.3 a node bought through a skipped node shows "Owned - chain broken" (no
    AP spent, no stat) until 0.3.1 is back, and a deleted minLevel row means 15 / 15 / 50 again. Never below 0.3 (the 0.3 floor stands).
  CHECKED: see CHECKED_031 below (filled in from the harness run).
  TEST: see TEST_031 below.

=== SkyyTrees 0.3 notes (history; still true unless 0.3.1 above says otherwise) ===
0.3 PART 1 (2026-10-02;'''
rep(DOC_HEAD_OLD, DOC_HEAD_NEW)
CHECKED_031 = '''  CHECKED (2026-10-03, bare JVM, SkyyTrees/test_skyytrees_0.3.1.py; scratch tools/dev/scratch/trees031, deleted afterwards):
    @CHECKED@'''
TEST_031 = '''  TEST (in game, after the deploy - class trees stay OFF; steps 1-3 need no switch):
    @TEST@'''
rep("  CHECKED: see CHECKED_031 below (filled in from the harness run).\n  TEST: see TEST_031 below.\n", CHECKED_031 + "\n" + TEST_031 + "\n")
rep('''Run:   python build_skyytrees_0.3.py            -> SkyyTrees/SkyyTrees-0.3.jar
       python build_skyytrees_0.3.py --deploy   -> also''', '''Run:   python build_skyytrees_0.3.1.py            -> SkyyTrees/SkyyTrees-0.3.1.jar
       python build_skyytrees_0.3.1.py --deploy   -> also''')

# ================================================================================================================ version
rep('VERSION = "0.3"', 'VERSION = "0.3.1"')

# ================================================================================================================ (2) class.minLevel
rep('''CLASS_LVL_HEAD = ["# Class skill level a node needs: class.minLevel.<Class>.<Id>=<level> (no line = the built-in default below, 0 = none).",''',
    '''CLASS_LVL_HEAD = ["# Class skill level a node needs: class.minLevel.<Class>.<Id>=<level> (a deleted line or 0 = no level needed).",   # 0.3.1''')
rep('''    cmn[j] = (int) clampL(lng(p, "class.minLevel." + @PKG@.TreeClass.CLASSES[ci] + "." + @PKG@.TreeClass.NID[nn], (long) @PKG@.TreeClass.CMIN[j]), 0L, 100L);''',
    '''    // 0.3.1 (Skyy 2026-10-03): a DELETED class.minLevel line = no class level needed (0.3 kept the built-in 15 / 15 / 50); 0 = none as
    // before; a line that is there but holds no number keeps the built-in level (a typo cannot drop the lock)
    String mk = "class.minLevel." + @PKG@.TreeClass.CLASSES[ci] + "." + @PKG@.TreeClass.NID[nn];
    cmn[j] = p.getProperty(mk) == null ? 0 : (int) clampL(lng(p, mk, (long) @PKG@.TreeClass.CMIN[j]), 0L, 100L);''')
rep('''     "Entry = <Class>.<Id> (Archer.R2). Class skill level the node needs. Removed = built-in; 0 = none.",''',
    '''     "Entry = <Class>.<Id> (Archer.R2). Class skill level the node needs. Removed or 0 = no level needed.",   # 0.3.1''')

# ================================================================================================================ (1) TreeClass: skips
rep(r'''# INTEGRITY (spec 5): an owned node counts only while its chain is intact - the root or an owned intact parent, every Need intact, no
# Lock owned, switched on, not a coming slot. Iterated to a fixpoint, so a dropped node drops what hangs off it.
M(cls, r"""
public static boolean[] intact(@PKG@.TreeData d, int ci) {
  boolean[] it = new boolean[NN];
  if (d == null || ci < 0 || ci >= NC || d.bad) return it;
  boolean[] own = ownOf(d, ci);
  boolean[] ok = new boolean[NN];
  for (int n = 0; n < NN; n++) ok[n] = own[n] && on(ci, n) && !slotComing(n);
  boolean again = true;
  while (again) {
    again = false;
    for (int n = 0; n < NN; n++) it[n] = false;
    if (ok[0]) {
      it[0] = true;
      boolean ch = true;
      while (ch) {
        ch = false;
        for (int n = 1; n < NN; n++) {
          if (it[n] || !ok[n]) continue;
          int p1 = NPAR1[n];
          int p2 = NPAR2[n];
          if ((p1 >= 0 && it[p1]) || (p2 >= 0 && it[p2])) { it[n] = true; ch = true; }
        }
      }
    }
    for (int n = 0; n < NN; n++) {
      if (!it[n]) continue;
      int nd = NNEED[n];
      int lk = NLOCK[n];
      if ((nd >= 0 && !it[nd]) || (lk >= 0 && own[lk])) { ok[n] = false; again = true; }
    }
  }
  return it;
}""")''', r'''# 0.3.1 (Skyy 2026-10-03, "Let waiting nodes be skipped"): the node kinds that can wait for a reader mod - Strength (SkyyGear's
# gear:extras), the Archer crossbow nodes (SkyySkills' key list), Mana Regen (skill:fn:manaregen). Health / Mana nodes, the rune / element
# slots and (by its kind) the ROOT are never skipped.
M(cls, r"""
public static boolean skipKind(int ci, int n) {
  if (ci < 0 || ci >= NC || n < 0 || n >= NN || slotComing(n)) return false;
  int k = CK[ci * NN + n];
  return k == K_S || k == K_X || k == K_R;
}""")
# 0.3.1: the SKIPPED nodes of an owned set - unowned, switched on, of a kind that can wait, and either waiting for its reader right now
# or still holding up an owned node below it (a node bought through it while it waited, so nothing breaks or refunds when the reader
# appears). Computed from the leaves up (a child always comes after its parents in the table), so a chain of skipped nodes (C1 > C2 >
# C3 owned) keeps holding as a whole. A node an admin switched off is never a skip (its chain breaks, as in 0.3).
M(cls, r"""
public static boolean[] skips(boolean[] own, int ci) {
  boolean[] sk = new boolean[NN];
  if (own == null || ci < 0 || ci >= NC) return sk;
  boolean[] hold = new boolean[NN];
  for (int n = NN - 1; n >= 0; n--) {
    boolean h = false;
    for (int c = n + 1; c < NN && !h; c++) {
      if (NPAR1[c] != n && NPAR2[c] != n) continue;
      if ((own[c] && on(ci, c) && !slotComing(c)) || (sk[c] && hold[c])) h = true;
    }
    hold[n] = h;
    if (own[n] || !on(ci, n) || !skipKind(ci, n)) continue;
    sk[n] = h || coming(ci, n);
  }
  return sk;
}""")
# INTEGRITY (spec 5 + 0.3.1): an owned node counts only while its chain is intact - the root, an owned intact parent or a SKIPPED parent
# (0.3.1) leads to it, every Need intact, no Lock owned, switched on, not a coming slot. Iterated to a fixpoint, so a dropped node drops
# what hangs off it. A skipped node is passed (ps), never intact: it is never spent and gives nothing.
M(cls, r"""
public static boolean[] intactOf(boolean[] own, int ci) {
  boolean[] it = new boolean[NN];
  if (own == null || ci < 0 || ci >= NC) return it;
  boolean[] sk = skips(own, ci);
  boolean[] ok = new boolean[NN];
  for (int n = 0; n < NN; n++) ok[n] = own[n] && on(ci, n) && !slotComing(n);
  boolean[] ps = new boolean[NN];
  boolean again = true;
  while (again) {
    again = false;
    for (int n = 0; n < NN; n++) { it[n] = false; ps[n] = false; }
    if (ok[0]) {
      it[0] = true;
      boolean ch = true;
      while (ch) {
        ch = false;
        for (int n = 1; n < NN; n++) {
          if (it[n] || ps[n] || !(ok[n] || sk[n])) continue;
          int p1 = NPAR1[n];
          int p2 = NPAR2[n];
          if ((p1 >= 0 && (it[p1] || ps[p1])) || (p2 >= 0 && (it[p2] || ps[p2]))) {
            if (ok[n]) it[n] = true; else ps[n] = true;
            ch = true;
          }
        }
      }
    }
    for (int n = 0; n < NN; n++) {
      if (!it[n]) continue;
      int nd = NNEED[n];
      int lk = NLOCK[n];
      if ((nd >= 0 && !it[nd]) || (lk >= 0 && own[lk])) { ok[n] = false; again = true; }
    }
  }
  return it;
}""")
M(cls, r"""
public static boolean[] intact(@PKG@.TreeData d, int ci) {
  if (d == null || ci < 0 || ci >= NC || d.bad) return new boolean[NN];
  return intactOf(ownOf(d, ci), ci);
}""")
# 0.3.1: the skipped nodes a player passes right now - a skip whose parent is intact or passed itself (one pass in table order; the
# same set intactOf reaches)
M(cls, r"""
public static boolean[] passed(boolean[] own, boolean[] it, int ci) {
  boolean[] ps = new boolean[NN];
  if (own == null || it == null || ci < 0 || ci >= NC || !it[0]) return ps;
  boolean[] sk = skips(own, ci);
  for (int n = 1; n < NN; n++) {
    if (!sk[n]) continue;
    int p1 = NPAR1[n];
    int p2 = NPAR2[n];
    if ((p1 >= 0 && (it[p1] || ps[p1])) || (p2 >= 0 && (it[p2] || ps[p2]))) ps[n] = true;
  }
  return ps;
}""")
# 0.3.1: the passed nodes a chain really runs through (their bars turn gold): from the leaves up, an intact or used node with no intact
# parent of its own uses its first passed parent (the pick-one pair: a skipped Edge is not "used" when Bulwark is owned)
M(cls, r"""
public static boolean[] used(boolean[] it, boolean[] ps) {
  boolean[] us = new boolean[NN];
  if (it == null || ps == null) return us;
  for (int c = NN - 1; c >= 1; c--) {
    if (!(it[c] || us[c])) continue;
    int p1 = NPAR1[c];
    int p2 = NPAR2[c];
    if ((p1 >= 0 && it[p1]) || (p2 >= 0 && it[p2])) continue;
    if (p1 >= 0 && ps[p1]) us[p1] = true;
    else if (p2 >= 0 && ps[p2]) us[p2] = true;
  }
  return us;
}""")
# 0.3.1: the nodes whose bars may be gold - intact, or a skipped node a chain uses (pieceGold's input on the class page)
M(cls, r"""
public static boolean[] lit(boolean[] own, boolean[] it, int ci) {
  boolean[] r = new boolean[NN];
  if (it == null) return r;
  boolean[] us = used(it, passed(own, it, ci));
  for (int n = 0; n < NN; n++) r[n] = it[n] || us[n];
  return r;
}""")
# 0.3.1: the lane rule counts the owned intact AND the passed nodes of the lane ("as if the path passed through it")
M(cls, r"""
public static int laneHas(boolean[] it, boolean[] ps, int lane) {
  int s = 0;
  for (int n = 0; n < NN; n++) if ((it[n] || (ps != null && ps[n])) && NLANE[n] == lane) s++;
  return s;
}""")
# 0.3.1: the node to name instead of a skipped parent - up the parent line past every skip (a skip has one parent in this map)
M(cls, r"""
public static int gate(boolean[] sk, int p) {
  int g = p;
  int guard = 0;
  while (g >= 0 && sk[g] && guard < NN) { g = NPAR1[g]; guard++; }
  return g < 0 ? p : g;
}""")''')
rep(r'''  if (coming(ci, n)) return 2;
  int p1 = NPAR1[n];
  int p2 = NPAR2[n];
  if (!(n == 0 || (p1 >= 0 && it[p1]) || (p2 >= 0 && it[p2]))) return 3;
  int nd = NNEED[n];
  if (nd >= 0 && !it[nd]) return 4;
  int lk = NLOCK[n];
  if (lk >= 0 && own[lk]) return 5;
  if (NLANEN[n] > 0 && laneOwned(it, NLANE[n]) < NLANEN[n]) return 6;''', r'''  if (coming(ci, n)) return 2;
  int p1 = NPAR1[n];
  int p2 = NPAR2[n];
  boolean par = n == 0 || (p1 >= 0 && it[p1]) || (p2 >= 0 && it[p2]);
  boolean[] ps = null;
  if (!par) {   // 0.3.1: a skipped (waiting) parent the player passes counts like an owned one
    ps = passed(own, it, ci);
    par = (p1 >= 0 && ps[p1]) || (p2 >= 0 && ps[p2]);
  }
  if (!par) return 3;
  int nd = NNEED[n];
  if (nd >= 0 && !it[nd]) return 4;
  int lk = NLOCK[n];
  if (lk >= 0 && own[lk]) return 5;
  if (NLANEN[n] > 0) {   // 0.3.1: owned + passed lane nodes
    if (ps == null) ps = passed(own, it, ci);
    if (laneHas(it, ps, NLANE[n]) < NLANEN[n]) return 6;
  }''')
rep(r'''  if (why == 3) return NPAR2[n] >= 0 || NPAR1[n] < 0 ? "Locked" : "Needs " + NID[NPAR1[n]];''',
    r'''  if (why == 3) return NPAR2[n] >= 0 || NPAR1[n] < 0 ? "Locked" : "Needs " + NID[gate(skips(own, ci), NPAR1[n])];   // 0.3.1: past a skipped parent''')
rep(r'''  if (why == 3) {
    int p1 = NPAR1[n];
    int p2 = NPAR2[n];
    if (p1 < 0) return nm + " cannot be unlocked";
    String s = nm + " needs " + name(ci, p1) + " (" + NID[p1] + ")";
    if (p2 >= 0) s = s + " or " + name(ci, p2) + " (" + NID[p2] + ")";
    return s + " first";
  }''', r'''  if (why == 3) {
    int p1 = NPAR1[n];
    int p2 = NPAR2[n];
    if (p1 < 0) return nm + " cannot be unlocked";
    boolean[] sk = skips(own, ci);   // 0.3.1: name the node to buy, not the skipped one in between
    int g1 = gate(sk, p1);
    int g2 = p2 < 0 ? -1 : gate(sk, p2);
    String s = nm + " needs " + name(ci, g1) + " (" + NID[g1] + ")";
    if (g2 >= 0 && g2 != g1) s = s + " or " + name(ci, g2) + " (" + NID[g2] + ")";
    s = s + " first";
    int w = sk[p1] ? p1 : ((p2 >= 0 && sk[p2]) ? p2 : -1);
    if (w >= 0) s = s + " (" + NID[w] + (coming(ci, w) ? " waits for " + comingWho(ci, w) + " and is skipped)" : " is skipped)");
    return s;
  }''')
rep(r'''  if (why == 6) return nm + " needs " + NLANEN[n] + " nodes of the " + LANE[ci * 3 + NLANE[n] - 1] + " lane first (you own " + laneOwned(it, NLANE[n]) + ")";''',
    r'''  if (why == 6) {   // 0.3.1: passed (skipped) lane nodes count too
    int lo = laneOwned(it, NLANE[n]);
    int lp = laneHas(it, passed(own, it, ci), NLANE[n]) - lo;
    return nm + " needs " + NLANEN[n] + " nodes of the " + LANE[ci * 3 + NLANE[n] - 1] + " lane first (you own " + lo + (lp > 0 ? ", " + lp + " skipped" : "") + ")";
  }''')

# ================================================================================================================ (1) TreeClassOps
rep(r'''  boolean[] own = @PKG@.TreeClass.ownOf(d, ci);
  if (n < 0 || n >= @PKG@.TreeClass.NN || !own[n]) { undo.remove(undo.size() - 1); return "Nothing to undo - that node is not yours any more" + suffix(probe); }
  for (int m = 0; m < @PKG@.TreeClass.NN; m++) {
    if (m == n || !own[m]) continue;
    boolean needs = @PKG@.TreeClass.NNEED[m] == n;
    int p1 = @PKG@.TreeClass.NPAR1[m];
    int p2 = @PKG@.TreeClass.NPAR2[m];
    if (p1 == n && (p2 < 0 || !own[p2])) needs = true;
    if (p2 == n && (p1 < 0 || !own[p1])) needs = true;
    if (needs) return @PKG@.TreeClass.name(ci, n) + " cannot be undone - " + @PKG@.TreeClass.name(ci, m) + " (" + @PKG@.TreeClass.NID[m] + ") still needs it" + suffix(probe);
  }''', r'''  boolean[] own = @PKG@.TreeClass.ownOf(d, ci);
  if (n < 0 || n >= @PKG@.TreeClass.NN || !own[n]) { undo.remove(undo.size() - 1); return "Nothing to undo - that node is not yours any more" + suffix(probe); }
  // 0.3.1: refused only when ANOTHER intact node would break - simulated on a copy without n (a skipped node may hold up the nodes
  // bought through it while it waited, so the 0.3 test "an owned child with no other owned parent" refused Undos that break nothing)
  boolean[] it0 = @PKG@.TreeClass.intactOf(own, ci);
  boolean[] own2 = @PKG@.TreeClass.ownOf(d, ci);
  own2[n] = false;
  boolean[] it2 = @PKG@.TreeClass.intactOf(own2, ci);
  for (int m = 0; m < @PKG@.TreeClass.NN; m++) {
    if (m == n || !it0[m] || it2[m]) continue;
    return @PKG@.TreeClass.name(ci, n) + " cannot be undone - " + @PKG@.TreeClass.name(ci, m) + " (" + @PKG@.TreeClass.NID[m] + ") still needs it" + suffix(probe);
  }''')
rep(r'''  if (stt == 3) return "Waits for " + @PKG@.TreeClass.comingWho(ci, n) + " - until then it cannot be unlocked";''',
    r'''  if (stt == 3) return "Waits for " + @PKG@.TreeClass.comingWho(ci, n) + (@PKG@.TreeClass.skipKind(ci, n) ? " - skipped until then: the nodes after it can be unlocked without it" : " - until then it cannot be unlocked");   // 0.3.1''')

# ================================================================================================================ (1) the class page
rep(r'''  boolean[] pg = @PKG@.TreeClass.pieceGold(cp, it);''',
    r'''  boolean[] pg = @PKG@.TreeClass.pieceGold(cp, @PKG@.TreeClass.lit(own, it, ci));   // 0.3.1: gold through a skipped node a chain uses''')

# ================================================================================================================ checks on the result
assert s.count("registerSystem(") == REG0, "0.3.1 adds no system (one registerSystem per class)"
assert s.count("registerCommand(") == CMD0, "command registrations changed"
for kb in KEEP + KEEP_CLS:
    assert kb in s, "a block that must stay 0.3's changed: %s" % kb[:80]
# javassist: methods before their callers (skipKind / skips / intactOf before intact; passed / used / lit / laneHas / gate before reason,
# cardText, reasonText; intactOf before TreeClassOps.undo; skipKind before TreeClassOps.needLine; lit before the class page)
_ix = s.index
assert _ix("public static boolean on(int ci, int n) {") < _ix("public static boolean skipKind(int ci, int n) {") < _ix("public static boolean[] skips(boolean[] own, int ci) {") \
    < _ix("public static boolean[] intactOf(boolean[] own, int ci) {") < _ix("public static boolean[] intact(@PKG@.TreeData d, int ci) {") \
    < _ix("public static boolean[] passed(boolean[] own, boolean[] it, int ci) {") < _ix("public static boolean[] used(boolean[] it, boolean[] ps) {") \
    < _ix("public static boolean[] lit(boolean[] own, boolean[] it, int ci) {") < _ix("public static int laneHas(boolean[] it, boolean[] ps, int lane) {") \
    < _ix("public static int gate(boolean[] sk, int p) {") < _ix("public static int spent(boolean[] it, int ci) {") \
    < _ix("public static int laneOwned(boolean[] it, int lane) {") < _ix("public static int reason(boolean[] own, boolean[] it, int ci, int n, int lvl, int apFree) {") \
    < _ix("public static String cardText(") < _ix("public static String reasonText(") < _ix("# ================= TreeFx: per-player effect vector") \
    < _ix("public static String undo(java.util.UUID u, @PKG@.TreeData d, int ci, java.util.ArrayList undo, boolean probe) {") \
    < _ix("public static String needLine(boolean[] own, boolean[] it, int ci, int n, int lvl, int apFree, int stt) {") < _ix("public void buildClass("), \
    "javassist: methods before their callers"
assert s.count("@PKG@.TreeClass.intactOf(") == 2 and s.count("intactOf(ownOf(d, ci), ci)") == 1 and s.count("passed(own, it, ci)") == 4
assert s.count("@PKG@.TreeClass.lit(own, it, ci)") == 1 and s.count("pieceGold(cp, it)") == 0
assert s.count('p.getProperty(mk) == null ? 0 :') == 1 and "Removed = built-in; 0 = none." not in s and "(no line = the built-in default below, 0 = none)" not in s
assert 'MG_WHO = "SkyyTrees 0.3"' in s and 'MG_MARK_ID = "skyytrees-0.3-trees"' in s, "the 0.3 one-time update keeps its marker and labels"
assert s.count("@CHECKED@") == 1 and s.count("@TEST@") == 1
# the harness run's numbers and the in-game steps (docstring CHECKED / TEST of 0.3.1)
CHECKED_BODY = '''896,040 checks, 0 fails (the build's access audit:
    10,493 references in 37 classes, 0 refused; lint 0 fails). A: every class of 0.3.1 / 0.3 / 0.2.5 loads under -Xverify:all (37 / 37
    / 33). EVERY 0.3 CHECK re-run on 0.3.1 against 0.2.5 (B-D the six old trees, N Alchemy / Smithing, K 81 class page states + 27 click
    sequences against the class model - now restating the skip rule -, L M P S, E, Z); the expectations the skip rule changes on purpose
    are marked "0.3.1" in the harness (K7 "Needs ROOT"; k6 = an Undo the skip makes safe, k6b keeps 0.3's refusal on a node that is never
    skipped). B2 / D2: 305 template page states and 93 template clicks byte-identical to 0.3. X CLASS COMPARE: the 0.3 jar against the
    0.3 model on all 81 class states; 54 class pages byte-identical, 27 differ in exactly the 65 cells the two models disagree on; 136
    click steps identical, 25 expected 0.3 answers where the skip acts. W1: the reachable node set of all 5 classes under 5 reader
    situations (today / all / none / gear only / crossbow keys only), both jars = both models; today Warrior + Berserker 10 nodes / 16 AP,
    Archer 8 / 11, Mage + Priest 19 / 27 (0.3: the physical classes ROOT only). W2: a Warrior buys through the waiting P1 / P4 / C1 / C2;
    the reader appears (nothing refunded or re-counted, the newly live nodes bought once for their own AP), goes away (owned stays intact)
    and comes back; Strength (gear:extras) and Mana Regen posts; Undo on a copy (held nodes allowed, a real dependency refused); respec
    4,000 coins once. W4: 1,000 random owned sets per jar (37,000 node states / reasons / card texts and 2,000 Undo answers) = the model.
    W5: tree:fn:level / bonus and the stats through a skipped chain. W3: class.minLevel deleted / 0 / unreadable / all deleted / added
    in both jars, Server Setup remove -> a level-14 Archer buys Bolt Rack I (0.3: needs 15), the row help + file comment. E2: 0.3 vs 0.3.1
    differ only in TreeClass (+8 methods, 4 changed), TreeClassOps (undo, needLine), TreePage (buildClass), TreeCfg (apply + 2 default
    lines), TreeMig (1 comment line), CfgRows (row help, VERSION, the 2 lines), CfgFn + the plugin (version), the manifest (Name,
    Version). P2: the live player files read and saved alike by 0.3 and 0.3.1; a skip-bought file round-trips through 0.3. M: the one-time
    0.3 update on a scratch COPY of the live world (it never ran 0.3): start 1 appends the block (the new comment), start 2 writes
    nothing; the live files are never written. Z: the engine-access audit, 10,493 references, 0 refused.'''
TEST_BODY = '''(1) server log: "[SkyyTrees] 0.3.1 ready ... class trees OFF";
    the live world never ran 0.3, so this first start also logs the one-time "trees.properties updated for SkyyTrees 0.3: 317 line(s)
    added ..." (0.3's TEST steps 1-9 still apply). (2) /tree probe (admin) on an Archer, Warrior or Berserker profile (no class = Archer):
    Respec twice (free in the probe), Unlock ROOT, click Might I - card Coming, detail "Coming with SkyyGear", Needs "Waits for SkyyGear -
    skipped until then: the nodes after it can be unlocked without it"; click Vitality I - green "Unlock 1 AP"; Unlock it: the bars ROOT >
    Might I > Vitality I turn gold; Unlock Bulwark and Focus I (Edge stays Coming). Next >: Might II says Coming; on a Warrior Battle Monk
    III shows "Unlock 2 AP", then Battle Monk IV "Unlock 3 AP" (the lane rule counts the two skipped Battle Monk nodes); Paladin I-IV
    unlock as before; every answer ends "(probe - not saved)". On a Mage the tree looks as in 0.3 (no waiting node while SkyySkills is
    live). (3) SkyWynn Menu -> Server Setup -> Trees -> Class trees -> Class level per node: the help ends "Removed or 0 = no level
    needed" and Archer.R2 15 / R3 15 / R4 50 are still listed (removing a row takes the level away; the crossbow nodes stay "Coming with
    SkyySkills" until SkyySkills lists them, so the effect shows only then). (4) Optional, real data: Class trees ON, then on a Warrior
    profile /tree class -> Unlock ROOT and Vitality I straight away (+4 max Health each, Might I Coming); relog keeps the picks; switch
    Class trees OFF again (they stay OFF by default). (5) The eight skill trees behave exactly as in 0.3.'''
s = s.replace("@CHECKED@", CHECKED_BODY).replace("@TEST@", TEST_BODY)
assert '"""' not in CHECKED_BODY + TEST_BODY and all(len(_l) <= 140 for _l in s[:s.index("=== SkyyTrees 0.3 notes")].split(LF)), "docstring lines <= 140"
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline=NL).write(s)   # keep the line endings of 0.3
print("wrote", dst, "(%d lines; 0.3 had %d)" % (s.count(LF), OLD.count(LF)))
