"""Derive SkyyTrees/build_skyytrees_0.3.5.py from the LIVE generated SkyyTrees/build_skyytrees_0.3.4.py (the tools/deploy_set.py SET pin).
Run:  python tools/trees_0_3_5_patch.py   then   python SkyyTrees/build_skyytrees_0.3.5.py   (never --deploy: coordinated deploy)
      then python SkyyTrees/test_skyytrees_0.3.5.py --dir <tools/dev/scratch/<task>/...> (bare JVM; needs SkyyTrees-0.3.4.jar, the SET pin)
EDITED-SCRIPTS RULE (commit ab75b6c): the lineage is Skyy's EDITED 0.2.3 -> trees_0_2_4_patch.py -> ... -> trees_0_3_4_patch.py -> the
generated 0.3.4 read here; tools/trees_0_2_3_patch.py and older are NEVER re-run. Edit THIS file, never the generated build script.

0.3.5 = THE MONK SKILL IS "ZEN" (Skyy LOCKED 2026-10-08, docs/answered/classes.md popup batch 1; research/classes/Monk.md):
  - TreeClass.CSKILL (what players see: the class tree's level label "Zen 12", "needs Zen 20", the respec price text, the Ability Points
    help) says Zen for the Monk; the fresh trees.properties comment "# Monk (Zen): paths ..." too (an existing file is never rewritten -
    a comment only; no key changes).
  - NEW TreeClass.CSKILL_KEY = 0.3.4's CSKILL exactly (the Monk = "Discipline"): the name TreeClass.level() hands to skill:fn:level. Both
    SkyySkills 0.4.26 (its label) and 0.4.27 (its alias of the Monk slot) resolve it to the same slot - so 0.3.5 works with either, and
    the level / Ability Points / spent / refunds of every Monk tree are the same numbers as 0.3.4's.
  No saved data (tree saves key by class NAME: Class.Monk.*), no config key, no migration, no new class / system / command.
  ROLLBACK 0.3.5 -> 0.3.4: safe (texts only).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.4.py")
dst = os.path.join(ROOT, "SkyyTrees", "build_skyytrees_0.3.5.py")
raw = open(src, "rb").read()
NL = "\r\n" if b"\r\n" in raw else "\n"
CR, LF = chr(13), chr(10)
s = raw.decode("utf8").replace(CR + LF, LF)
OLD = s
assert 'VERSION = "0.3.4"' in s and "GENERATED by tools/trees_0_3_4_patch.py from the LIVE build_skyytrees_0.3.3.py" in s, \
    "build_skyytrees_0.3.4.py is not the live 0.3.4 of the edited lineage"
assert "CSKILL_KEY" not in s, "0.3.4 already has the 0.3.5 parts"
REG0 = s.count("registerSystem(")
CMD0 = s.count("registerCommand(")
CHANGES = []


def rep(old, new, count=1):
    global s
    assert s.count(old) == count, "anchor count %d != %d: %s" % (s.count(old), count, old[:140])
    s = s.replace(old, new)
    CHANGES.append((new, old))


# ================================================================================================================ header + version
rep('''"""SkyyTrees 0.3.4 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_4_patch.py from the LIVE build_skyytrees_0.3.3.py (the SET pin) - edit the patch, not this file. 0.3.3
was GENERATED''', '''"""SkyyTrees 0.3.5 - build script (javassist via jpype, tools/skyybuild.py). Owner: Skyy (they/them).
GENERATED by tools/trees_0_3_5_patch.py from the LIVE build_skyytrees_0.3.4.py (the SET pin) - edit the patch, not this file. 0.3.4
was GENERATED by tools/trees_0_3_4_patch.py from the LIVE build_skyytrees_0.3.3.py. 0.3.3
was GENERATED''')
rep('''0.3.4 (2026-10-09; LOG FIX - Skyy's play log: 'Missing interaction **Skyy_Tree_Chop_Wood_Next_Next' / '_Next_Failed'; notes:''',
    '''0.3.5 (2026-10-09; Skyy LOCKED 2026-10-08 the Monk skill "Zen"; notes: tools/trees_0_3_5_patch.py): the Monk tree's texts say Zen
    (TreeClass.CSKILL); skill:fn:level is still asked with 0.3.4's names (TreeClass.CSKILL_KEY - SkyySkills 0.4.26 and 0.4.27 both
    resolve "Discipline" to the Monk slot). Texts only - no saved data, key, setting or migration.
  CHECKED: SkyyTrees/test_skyytrees_0.3.5.py (bare JVM: class compare vs 0.3.4, -Xverify:all, the level lookup, the texts, the access
    audit, start twice on a copy of the live data).

=== SkyyTrees 0.3.4 notes (history; still true unless 0.3.5 above says otherwise) ===
0.3.4 (2026-10-09; LOG FIX - Skyy's play log: 'Missing interaction **Skyy_Tree_Chop_Wood_Next_Next' / '_Next_Failed'; notes:''')
rep('''Run:   python build_skyytrees_0.3.4.py            -> SkyyTrees/SkyyTrees-0.3.4.jar
       python build_skyytrees_0.3.4.py --deploy   -> also''', '''Run:   python build_skyytrees_0.3.5.py            -> SkyyTrees/SkyyTrees-0.3.5.jar
       python build_skyytrees_0.3.5.py --deploy   -> also''')
rep('VERSION = "0.3.4"', 'VERSION = "0.3.5"')

# ================================================================================================================ the names
rep('''CSKILL = ["Archery", "Swordsmanship", "Sorcery", "Fury", "Divinity", "Assassination", "Discipline"]   # skill:fn:level names (SkyySkills 0.4.21)
''', '''CSKILL = ["Archery", "Swordsmanship", "Sorcery", "Fury", "Divinity", "Assassination", "Zen"]   # 0.3.5: what players see (Monk = Zen, LOCKED 2026-10-08)
# 0.3.5: the skill:fn:level names = 0.3.4's CSKILL exactly (SkyySkills 0.4.21-0.4.26 know "Discipline" as the Monk label, 0.4.27+ as its alias)
CSKILL_KEY = ["Archery", "Swordsmanship", "Sorcery", "Fury", "Divinity", "Assassination", "Discipline"]
assert [a for a, b in zip(CSKILL, CSKILL_KEY) if a != b] == ["Zen"]
''')
rep('''F(cls, "public static final String[] CSKILL = %s;" % jstr(CSKILL))
''', '''F(cls, "public static final String[] CSKILL = %s;" % jstr(CSKILL))
F(cls, "public static final String[] CSKILL_KEY = %s;" % jstr(CSKILL_KEY))   # 0.3.5: the skill:fn:level names (0.3.4's)
''')
rep('''    Object r = f.apply(new Object[] { u, CSKILL[ci] });
''', '''    Object r = f.apply(new Object[] { u, CSKILL_KEY[ci] });
''')

# ================================================================================================================ checks on the result
assert s.count("registerSystem(") == REG0, "0.3.5 adds no system"
assert s.count("registerCommand(") == CMD0, "command registrations changed"
assert "KEEP=10" in s and "KEEP=20" not in s
_u = s
for _new, _old in reversed(CHANGES):
    assert _u.count(_new) == 1, "a change is not unique any more: %s" % _new[:80]
    _u = _u.replace(_new, _old, 1)
assert _u == OLD, "the generated script differs from 0.3.4 outside the recorded changes"
assert all(len(_l) <= 140 for _l in s[:s.index("=== SkyyTrees 0.3.4 notes")].split(LF))
compile(s, dst, "exec")
open(dst, "w", encoding="utf8", newline=NL).write(s)   # keep the line endings of 0.3.4
print("wrote", dst, "(%d lines; 0.3.4 had %d; %d changes)" % (s.count(LF), OLD.count(LF), len(CHANGES)))
