"""SkyyWorldGen 0.3 patch (Zone-Archipelago-Spec step 0.3 = the NODE PROOF): reads the SET build script
SkyyWorldGen/build_skyyworldgen_0.1.py and its harness SkyyWorldGen/test_skyyworldgen_0.1.py (both unchanged) and writes the GENERATED
SkyyWorldGen/build_skyyworldgen_0.3.py + SkyyWorldGen/test_skyyworldgen_0.3.py. Edit THIS file, never the generated ones.

Run:   python tools/worldgen_0_3_patch.py                      -> the two generated scripts
       python SkyyWorldGen/build_skyyworldgen_0.3.py           -> SkyyWorldGen/SkyyWorldGen-0.3.jar ("assembled ...")
       python SkyyWorldGen/test_skyyworldgen_0.3.py            -> the 0.1 harness (every 0.1 check on the unchanged Zone 1 island) + the 0.3
                                                                 sections Q (proof terrain), QP (proof world create / load / commands)

What 0.3 adds (nothing of 0.1 changes: the Zone 1 assets, world skywynn_z1, its template, settings and /zone 1 stay byte-for-byte / as is):
  - a NEW test world type: WorldStructure SkyWynn_P3_Archipelago, instance template SkyWynn_Proof, world skywynn_proof, made once by the
    new admin-only /zone proof (the same create / load / teleport machinery as /zone 1; kept until an admin deletes its folder).
  - one zone archipelago laid out like the spec's Zone 1 table (5.1): the summit isle 1E (R 600) + 4 outer islands 1A-1D (R 400-520) at
    fixed centres, 2 land necks (1A, 1C), 1 rock arch over the void (1B) and 1 bridge gap with flat bridgeheads (1D, exactly 40 blocks
    along the z axis). One biome look per island (vanilla Zone 1 environments, V1 tile grass tints, 0.1's Birch / Azure tree folders),
    a stone look on the arch. No caves / lava yet (0.4) - the Empty queue is Empty only, so the void can never fill with lava.
The proof-asset code is the PROOF_BLOCK below (inserted after the 0.1 assets); the Java changes are exact text replacements, each one
asserted to match exactly once.
"""
import os, re, sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
SRC = os.path.join(ROOT, "SkyyWorldGen", "build_skyyworldgen_0.1.py")
DST = os.path.join(ROOT, "SkyyWorldGen", "build_skyyworldgen_0.3.py")
HSRC = os.path.join(ROOT, "SkyyWorldGen", "test_skyyworldgen_0.1.py")
HDST = os.path.join(ROOT, "SkyyWorldGen", "test_skyyworldgen_0.3.py")

# ================================================================= the inserted texts
HEADER = r'''"""SkyyWorldGen 0.3 - build script (javassist via jpype). GENERATED by tools/worldgen_0_3_patch.py from build_skyyworldgen_0.1.py - edit
the patch, never this file. Run: python SkyyWorldGen/build_skyyworldgen_0.3.py -> SkyyWorldGen/SkyyWorldGen-0.3.jar
Harness: python SkyyWorldGen/test_skyyworldgen_0.3.py (also generated by the patch: every 0.1 check + sections Q and QP).

NEW IN 0.3 - research/cloud/Zone-Archipelago-Spec.md build step 0.3, the NODE PROOF (Skyy 2026-10-09: "i dont mind if each zone is a few
islands with ways they connect, (or ways we build to get between them) i want to keep the distinct zones, and have the zones far enough
apart you need dragons or portals to get around." - defaults accepted: zones 1,100 apart, ~3x land per zone, building bridges allowed
inside a zone, no-build gaps between zones):
  - a NEW test world type only - the Zone 1 island (skywynn_z1, /zone 1, its assets, template and settings) is unchanged byte for byte.
    WorldStructure SkyWynn_P3_Archipelago + template SkyWynn_Proof -> world skywynn_proof, made by the admin-only /zone proof (same
    create / reopen / teleport machinery and guards as /zone 1; kept until an admin deletes universe/worlds/skywynn_proof).
  - ONE zone archipelago laid out like the spec's Zone 1 table (5.1), fixed centres: the summit isle 1E Azure Crown (R 600, peak y 214)
    + 1A Arrival Isle, 1B Birchwood, 1C Gorgeback, 1D Fenmoss (R 400-520). Joins: land necks 1A-1E and 1C-1E (60 blocks rim to rim, about
    56 wide), a rock arch 1B-1E (80 blocks, 22 wide, bowed, open void under and beside it), a bridge gap 1D-1E (exactly 40 blocks along the
    z axis with flat 15-wide bridgeheads on both lips, for a SkyyTowns bridge piece later).
  - vanilla HytaleGenerator nodes only, own numbers, nothing copied: island distance = Sqrt(Sum(Multiplier(x - cx)^2, (z - cz)^2)) from
    XValue / ZValue / Constant (the spec's "Offset" is a Y-function node in this engine - OffsetDensityAsset has only FunctionForY);
    union = Max, the gap cuts = Min, joins = CurveMappers on two linear axis coordinates; the 0.1 proven Cache / YOverride / warp /
    BaseHeight / Simplex / Solidity / prop shapes. One biome look per island (vanilla Zone 1 environments, V1 tile grass tints, 0.1's
    Birch / Azure tree folders), stone on the arch, void around.
  - spec 6.3 hazard (a biome's Empty queue fills every empty voxel of the column, so lava in it would hang under every island): the proof
    has NO fluid - every Empty queue is Empty only; the harness proves not one fluid section / lava / water block in any generated chunk.
    Lava (option 1: a density-delimited Empty provider limited to above the underside; option 2: cave-floor lava prefabs; option 3: a
    plugin pass) is step 0.4.
ROLLBACK RULE (0.3 fixer, 2026-10-09): once /zone proof has run, universe/worlds/skywynn_proof names the WorldStructure
  SkyWynn_P3_Archipelago, which only this jar (and later ones that keep it) supplies; every saved world is reopened at boot, so a jar
  without it would fill the proof world with void fallback chunks (the same failure WgCheck guards for Zone 1). Before rolling back to
  0.1 (or retiring the proof world): players /zone leave, stop the server, delete universe/worlds/skywynn_proof and the skywynn_proof.*
  lines of mods/Skyy_SkyyWorldGen/worlds.properties. The world's own game mode (Adventure) only applies to a player whose game mode was
  never set (Player.initGameMode) - a /gamemode change follows the player across /zone and /zone leave.
NOT IN 0.3 (spec staging): caves + lava caverns (0.4), the real Zone 1 world skywynn + biome bands per island + the town (0.5), zones
  2-4 and the 1,100-block zone gaps (0.6+), the no-build rule over zone gaps, wg:fn:ring v2 / zoneOf / land bridge keys, dragons.'''

# the proof assets: inserted after the 0.1 assets (uses 0.1's num / curve / jdump / instance_template / ASSETS / B / re / os)
PROOF_BLOCK = r'''
import math
# ================================================================= 0.3 NODE PROOF: one zone archipelago in its own test world (skywynn_proof)
# research/cloud/Zone-Archipelago-Spec.md step 0.3, laid out like its Zone 1 table (section 5.1): the summit isle 1E + 4 outer islands
# (fixed centres) joined by 2 land necks, 1 rock arch and 1 bridge gap with flat bridgeheads (exact 40-block span along the z axis).
# Vanilla HytaleGenerator nodes only (types read from the release jar's AssetManager registry): XValue / ZValue / Constant / Sum /
# Multiplier / Sqrt = the distance from an island centre (the spec's "Offset" turned out to be a Y function - OffsetDensityAsset only has
# FunctionForY - so the offset is plain arithmetic); Max / Min = union / cut; CurveMapper (clamps to its end values - probed); the
# proven 0.1 BaseHeight / Normalizer / Simplex / FastGradientWarp / Cache / YOverride / Exported / Imported shapes. No caves, no fluid
# (0.4): every land biome's Empty queue is Empty only, so the "Empty queue fills the void with lava" hazard cannot happen here - the
# harness proves there is not one fluid block in the world. ONE table below -> every JSON number + the Java place names.
PROOF = {
    "id": "proof", "name": "Archipelago proof", "world": "skywynn_proof", "template": "SkyWynn_Proof",
    "structure": "SkyWynn_P3_Archipelago", "seed": "SkyWynn-P3", "base": 140, "K": 12.0, "hull": 1700,
    # (id, name, centre x, centre z, R, rim y, peak y, underside y, look) - absolute y; spec 5.1 (Zone 1 - Emerald Wilds)
    "islands": [
        ("1E", "Azure Crown (summit isle)", 0, 0, 600, 156, 214, 28, "Azure"),
        ("1A", "Arrival Isle", 0, 1060, 400, 146, 172, 58, "Plains"),
        ("1B", "Birchwood", -1109, -404, 500, 150, 184, 30, "Birch"),
        ("1C", "Gorgeback", 1109, -404, 520, 152, 196, 30, "Gorge"),
        ("1D", "Fenmoss", 0, -1060, 420, 148, 180, 50, "Swamp"),
    ],
    # (kind, from island, to island); every join runs from the outer island to the summit isle
    "joins": [("neck", "1A", "1E"), ("arch", "1B", "1E"), ("neck", "1C", "1E"), ("bridge", "1D", "1E")],
    "warp": {"factor": 40, "scale": 300, "persistence": 0.5, "lacunarity": 2, "octaves": 2},
    "inside": 70,          # a join reaches this far inside each nominal rim (the 40-block outline warp can pull a coast back)
    "neck": {"half": 28, "flat": 20, "thick": 26},          # walkable 41+ blocks, 26 thick under its middle
    "arch": {"half": 11, "flat": 8, "bow": 6, "end_thick": 22, "mid_thick": 12},
    "bridgehead": {"half": 7, "thick": 20},                  # 15 wide, flat at the rim height
    "moat": 160,           # the arch / bridge gap is cut clean (void) this far either side of the join axis (the warp could close it)
    "hills": {"amp": 0.3, "scale": 70, "octaves": 2, "seed": "SkyWynn-P3-Hills"},
    "under": {"amp": 0.4, "scale_xz": 40, "scale_y": 20, "octaves": 2, "seed": "SkyWynn-P3-Under"},
    "tint_noise": {"scale": 14, "octaves": 3, "seed": "SkyWynn-P3-Tint"},
    "tree_seed": "SkyWynn-P3-Trees",
    "code_pad": 24, "edge_pad": 18,  # biome code reaches R + 24 / join edge + 18: the void biome stays 16+ blocks from any terrain
    "landing": (0.5, 0.0, 760.5, 0.0),   # x, y (set below from the measured ground), z, yaw 0 = facing north: the neck and the summit isle
    "void_biome": "SkyWynn_P3_Void", "void_env": "Env_Void", "void_tint": "#5b9e28",
}
# looks: biome id suffix, environment, tint 1, tint 2, split, surface ("grass" / "stone"), tree spacing, tree prefabs (0.1's proven folders)
PROOF_LOOKS = {
    "Azure": ("Env_Zone1_Azure", "#2F798A", "#2F868A", 0.3, "grass", 13, [("Trees/Azure/Stage_2", 50), ("Trees/Azure/Stage_3", 50)]),
    "Plains": ("Env_Zone1_Plains", "#709d3a", "#78ac39", 0.5, "grass", 0, []),
    "Birch": ("Env_Zone1_Forests", "#9ec752", "#8ba441", 0.4, "grass", 11,
              [("Trees/Birch/Stage_1", 30), ("Trees/Birch/Stage_2", 45), ("Trees/Birch/Stage_3", 25)]),
    "Gorge": ("Env_Zone1_Mountains", "#82b742", "#598b27", 0.5, "grass", 0, []),
    "Swamp": ("Env_Zone1_Swamps", "#4b6919", "#65750d", 0.5, "grass", 0, []),
    "Arch": ("Env_Zone1_Mountains", "#82b742", "#598b27", 0.5, "stone", 0, []),
    # the bridge corridor (bridgeheads + 70 blocks inland on both lips): treeless, so no canopy hangs over the bridge spot or into the gap
    "Bridge": ("Env_Zone1_Swamps", "#4b6919", "#65750d", 0.5, "grass", 0, []),
}
P = PROOF
PB = P["base"]
PK = P["K"]
P_ISL = dict((i[0], i) for i in P["islands"])
assert all(PROOF_LOOKS[k][1] in UI_DATA_COLORS and PROOF_LOOKS[k][2] in UI_DATA_COLORS for k in PROOF_LOOKS) and P["void_tint"] in UI_DATA_COLORS


def p_biome(look):
    return "SkyWynn_P3_" + look


def p_code(iid):
    """biome code base of an island: 1A 1100 ... 1E 1500 (spec 3.2 / 5.1); band 50 = the middle of its 100-wide range"""
    return 1000 + 100 * (ord(iid[1]) - ord("A") + 1)


ARCH_CODE = 950
BRIDGE_CODE = 1950


def p_top_pts(R, rim, peak):
    """island ground (blocks above Base) by warped distance: a mountain trend from the peak to the rim, then a cliff to -1000"""
    a, b = rim - PB, peak - PB
    d = b - a
    return [(0, b), (0.15 * R, b - 0.06 * d), (0.4 * R, a + 0.55 * d), (0.7 * R, a + 0.22 * d), (0.9 * R, a + 0.06 * d), (R, a),
            (R + 6, -1000)]


def p_bot_pts(R, rim, under):
    """the keel: flat at the underside under the inner 75% of R, a smoothstep skirt up to rim - 10 at R, then +1000 (no land)"""
    lo, hi = under - PB, rim - PB - 10
    pts = [(0, lo), (0.75 * R, lo)]
    for t in (0.2, 0.4, 0.6, 0.8, 1.0):
        s = t * t * (3 - 2 * t)
        pts.append(((0.75 + 0.25 * t) * R, lo + (hi - lo) * s))
    pts.append((R + 6, 1000))
    return pts


for _i in P["islands"]:
    assert _i[7] < _i[5] < _i[6] and _i[7] >= 8, "island %s heights" % _i[0]
    _tp = p_top_pts(_i[4], _i[5], _i[6])
    _bp = p_bot_pts(_i[4], _i[5], _i[7])
    assert all(a[0] < b[0] for a, b in zip(_tp, _tp[1:])) and all(a[1] > b[1] for a, b in zip(_tp, _tp[1:])), "top curve " + _i[0]
    assert all(a[0] < b[0] for a, b in zip(_bp, _bp[1:])) and all(a[1] <= b[1] for a, b in zip(_bp, _bp[1:])), "bottom curve " + _i[0]


def p_join_geo(j):
    """(ax, az) = the outer island's nominal rim point on the axis, (ux, uz) = unit axis toward the summit isle, span = rim to rim"""
    kind, a, b = j
    A, Bi = P_ISL[a], P_ISL[b]
    dx, dz = Bi[2] - A[2], Bi[3] - A[3]
    L = math.hypot(dx, dz)
    ux, uz = dx / L, dz / L
    span = L - A[4] - Bi[4]
    return A[2] + ux * A[4], A[3] + uz * A[4], ux, uz, span


P_JOINS = []
for _j in P["joins"]:
    _ax, _az, _ux, _uz, _span = p_join_geo(_j)
    P_JOINS.append((_j, _ax, _az, _ux, _uz, _span))
    assert 30 <= _span <= 120, "join span %s %.1f" % (_j, _span)
    if _j[0] == "bridge":
        assert (abs(_ux) < 1e-9 or abs(_uz) < 1e-9) and abs(_span - round(_span)) < 1e-9, "a bridge gap runs along the x or z axis, whole blocks"
# every pair of islands that is NOT joined stays far apart even after the outline warp (2 x 40)
for _x in range(len(P["islands"])):
    for _y in range(_x + 1, len(P["islands"])):
        _a, _b = P["islands"][_x], P["islands"][_y]
        _gap = math.hypot(_a[2] - _b[2], _a[3] - _b[3]) - _a[4] - _b[4]
        _linked = any(set(j[1:]) == {_a[0], _b[0]} for j in P["joins"])
        assert _linked or _gap > 2 * P["warp"]["factor"] + 40, "unlinked islands %s / %s only %.0f apart" % (_a[0], _b[0], _gap)


def cm(inp, pts):
    return {"Type": "CurveMapper", "Curve": curve(pts), "Inputs": [inp]}


def imp(name):
    return {"Type": "Imported", "Name": name}


def const(v):
    return {"Type": "Constant", "Value": num(v)}


def lin_xz(kx, kz, c):
    """kx * x + kz * z + c (x, z = the sample position)"""
    parts = []
    if abs(kx) > 1e-12:
        parts.append({"Type": "Multiplier", "Inputs": [{"Type": "XValue"}, const(kx)]})
    if abs(kz) > 1e-12:
        parts.append({"Type": "Multiplier", "Inputs": [{"Type": "ZValue"}, const(kz)]})
    parts.append(const(c))
    return {"Type": "Sum", "Inputs": parts}


def exported2d(name, node):
    """the 0.1 2D pattern: Exported (SingleInstance) -> YOverride 0 -> Cache 3 -> node (computed once per column)"""
    return {"Type": "Exported", "ExportAs": name, "SingleInstance": True, "Inputs": [
        {"Type": "YOverride", "Value": 0, "Inputs": [{"Type": "Cache", "Capacity": 3, "Inputs": [node]}]}]}


def p_dist_name(iid):
    return "SkyWynn-P3-D-" + iid


def p_join_name(j, axis):
    return "SkyWynn-P3-J-%s%s-%s" % (j[1], j[2], axis)


def p_density_dist(isl):
    """warped horizontal distance from the island centre: sqrt((x - cx)^2 + (z - cz)^2) after a 40-block gradient warp"""
    iid, _n, cx, cz = isl[0], isl[1], isl[2], isl[3]
    w = P["warp"]
    dx = lin_xz(1, 0, -cx)
    dz = lin_xz(0, 1, -cz)
    d = {"Type": "Sqrt", "Inputs": [{"Type": "Sum", "Inputs": [{"Type": "Multiplier", "Inputs": [dx, dx]},
                                                                  {"Type": "Multiplier", "Inputs": [dz, dz]}]}]}
    return exported2d(p_dist_name(iid), {
        "Type": "FastGradientWarp", "WarpScale": w["scale"], "WarpPersistence": w["persistence"], "WarpLacunarity": w["lacunarity"],
        "WarpOctaves": w["octaves"], "WarpFactor": w["factor"], "Seed": "SkyWynn-P3-" + iid, "Inputs": [d]})


def p_density_join(jg, axis):
    """S = blocks along the join axis from the outer rim point; Q = signed blocks across it (unwarped: the joins are exact)"""
    j, ax, az, ux, uz, _span = jg
    if axis == "S":
        node = lin_xz(ux, uz, -(ax * ux + az * uz))
    else:
        node = lin_xz(-uz, ux, -(-ax * uz + az * ux))
    return exported2d(p_join_name(j, axis), node)


def p_join_parts(jg):
    """per join: (top terms, bottom terms, cut-top, cut-bottom) in blocks above Base (sentinels -1000 / +1000)"""
    j, _ax, _az, _ux, _uz, span = jg
    kind, a, b = j
    ha, hb = P_ISL[a][5] - PB, P_ISL[b][5] - PB
    ins = P["inside"]
    S, Q = imp(p_join_name(j, "S")), imp(p_join_name(j, "Q"))
    if kind == "neck":
        n = P["neck"]
        top_s = [(-ins - 2, -1000), (-ins, ha), (0, ha), (span, hb), (span + ins, hb), (span + ins + 2, -1000)]
        bot_s = [(-ins - 2, 1000), (-ins, ha - n["thick"]), (0, ha - n["thick"]), (span, hb - n["thick"]), (span + ins, hb - n["thick"]),
                 (span + ins + 2, 1000)]
        top_q = [(-n["half"] - 2, -1000), (-n["half"], -3), (-n["flat"], 0), (n["flat"], 0), (n["half"], -3), (n["half"] + 2, -1000)]
        bot_q = [(-n["half"] - 2, 1000), (-n["half"], 12), (-n["flat"], 0), (n["flat"], 0), (n["half"], 12), (n["half"] + 2, 1000)]
        return [{"Type": "Sum", "Inputs": [cm(S, top_s), cm(Q, top_q)]}], [{"Type": "Sum", "Inputs": [cm(S, bot_s), cm(Q, bot_q)]}], None, None, []
    if kind == "arch":
        n = P["arch"]
        mid = (ha + hb) / 2.0 + n["bow"]
        top_s = [(-ins - 2, -1000), (-ins, ha), (0, ha), (span / 2.0, mid), (span, hb), (span + ins, hb), (span + ins + 2, -1000)]
        bot_s = [(-ins - 2, 1000), (-ins, ha - n["end_thick"]), (0, ha - n["end_thick"]), (span / 2.0, mid - n["mid_thick"]),
                 (span, hb - n["end_thick"]), (span + ins, hb - n["end_thick"]), (span + ins + 2, 1000)]
        top_q = [(-n["half"] - 1, -1000), (-n["half"], -2), (-n["flat"], 0), (n["flat"], 0), (n["half"], -2), (n["half"] + 1, -1000)]
        bot_q = [(-n["half"] - 1, 1000), (-n["half"], 3), (-n["flat"], 0), (n["flat"], 0), (n["half"], 3), (n["half"] + 1, 1000)]
        cut_top = {"Type": "Max", "Inputs": [cm(S, [(-0.6, 1000), (-0.4, -1000), (span + 0.4, -1000), (span + 0.6, 1000)]),
                                             cm(Q, [(-P["moat"] - 1, 1000), (-P["moat"], -1000), (P["moat"], -1000), (P["moat"] + 1, 1000)])]}
        cut_bot = {"Type": "Min", "Inputs": [cm(S, [(-0.6, -1000), (-0.4, 1000), (span + 0.4, 1000), (span + 0.6, -1000)]),
                                             cm(Q, [(-P["moat"] - 1, -1000), (-P["moat"], 1000), (P["moat"], 1000), (P["moat"] + 1, -1000)])]}
        late = [({"Type": "Sum", "Inputs": [cm(S, top_s), cm(Q, top_q)]}, {"Type": "Sum", "Inputs": [cm(S, bot_s), cm(Q, bot_q)]})]
        return [], [], cut_top, cut_bot, late
    # bridge: the open gap = S 0 .. span - 1 (whole blocks, S = blocks from the outer rim along the axis); flat bridgeheads on both sides
    n = P["bridgehead"]
    g0, g1 = -0.4, span - 0.6
    cut_top = {"Type": "Max", "Inputs": [cm(S, [(g0 - 0.2, 1000), (g0, -1000), (g1, -1000), (g1 + 0.2, 1000)]),
                                         cm(Q, [(-P["moat"] - 1, 1000), (-P["moat"], -1000), (P["moat"], -1000), (P["moat"] + 1, 1000)])]}
    cut_bot = {"Type": "Min", "Inputs": [cm(S, [(g0 - 0.2, -1000), (g0, 1000), (g1, 1000), (g1 + 0.2, -1000)]),
                                         cm(Q, [(-P["moat"] - 1, -1000), (-P["moat"], 1000), (P["moat"], 1000), (P["moat"] + 1, -1000)])]}
    hq_t = [(-n["half"] - 0.6, -1000), (-n["half"] - 0.4, 0), (n["half"] + 0.4, 0), (n["half"] + 0.6, -1000)]
    hq_b = [(-n["half"] - 0.6, 1000), (-n["half"] - 0.4, 0), (n["half"] + 0.4, 0), (n["half"] + 0.6, 1000)]
    late = []
    for lo, hi, h in ((-ins, g0 - 0.2, ha), (g1 + 0.2, span + ins, hb)):
        ts = [(lo - 2, -1000), (lo, h), (hi, h), (hi + 0.2, -1000)] if lo < 0 else [(lo - 0.2, -1000), (lo, h), (hi, h), (hi + 2, -1000)]
        bs = [(a_, (1000 if v_ < -999 else v_ - n["thick"])) for a_, v_ in ts]
        late.append(({"Type": "Sum", "Inputs": [cm(S, ts), cm(Q, hq_t)]}, {"Type": "Sum", "Inputs": [cm(S, bs), cm(Q, hq_b)]}))
    return [], [], cut_top, cut_bot, late


def p_fields():
    tops = [cm(imp(p_dist_name(i[0])), p_top_pts(i[4], i[5], i[6])) for i in P["islands"]]
    bots = [cm(imp(p_dist_name(i[0])), p_bot_pts(i[4], i[5], i[7])) for i in P["islands"]]
    cuts_t, cuts_b, late_t, late_b = [], [], [], []
    for jg in P_JOINS:
        t_, b_, ct, cb, late = p_join_parts(jg)
        tops += t_
        bots += b_
        if ct is not None:
            cuts_t.append(ct)
            cuts_b.append(cb)
        for lt, lb in late:
            late_t.append(lt)
            late_b.append(lb)
    top = {"Type": "Max", "Inputs": [{"Type": "Min", "Inputs": [{"Type": "Max", "Inputs": tops}] + cuts_t}] + late_t}
    bot = {"Type": "Min", "Inputs": [{"Type": "Max", "Inputs": [{"Type": "Min", "Inputs": bots}] + cuts_b}] + late_b}
    return exported2d("SkyWynn-P3-Top2D", top), exported2d("SkyWynn-P3-Bot2D", bot)


def p_code_field():
    """the WorldStructure map: an island's code inside R + 24, a neck's lower-island code / the arch code inside the join strip, else void"""
    parts = []
    for i in P["islands"]:
        c = p_code(i[0]) + 50
        parts.append(cm(imp(p_dist_name(i[0])), [(0, c), (i[4] + P["code_pad"], c), (i[4] + P["code_pad"] + 1, -100000)]))
    for jg in P_JOINS:
        j, _ax, _az, _ux, _uz, span = jg
        # a neck carries its outer island's code (the islands' higher codes win inside them); the arch strip its stone look; the bridge
        # corridor the treeless Bridge look over everything (BRIDGE_CODE is the highest code)
        c = {"neck": p_code(j[1]) + 50, "arch": ARCH_CODE, "bridge": BRIDGE_CODE}[j[0]]
        half = {"neck": P["neck"]["half"], "arch": P["arch"]["half"], "bridge": P["bridgehead"]["half"]}[j[0]] + P["edge_pad"]
        ins = P["inside"]
        S, Q = imp(p_join_name(j, "S")), imp(p_join_name(j, "Q"))
        parts.append({"Type": "Sum", "Inputs": [cm(S, [(-ins - 1, -100000), (-ins, c), (span + ins, c), (span + ins + 1, -100000)]),
                                                cm(Q, [(-half - 1, -100000), (-half, 0), (half, 0), (half + 1, -100000)])]})
    return exported2d("SkyWynn-P3-Code2D", {"Type": "Max", "Inputs": parts})


def p_density_land():
    h = {"Type": "BaseHeight", "BaseHeightName": "Base", "Distance": True}
    hm = round(400.0 / PK, 3)
    km = round(1000.0 / PK, 3)
    hills, under = P["hills"], P["under"]
    top_sum = {"Type": "Sum", "Inputs": [
        cm(h, [(-400, hm), (400, -hm)]),
        cm(imp("SkyWynn-P3-Top2D"), [(-1000, -km), (1000, km)]),
        {"Type": "Normalizer", "FromMin": -1, "FromMax": 1, "ToMin": -hills["amp"], "ToMax": hills["amp"], "Inputs": [
            {"Type": "SimplexNoise2D", "Lacunarity": 2, "Persistence": 0.5, "Octaves": hills["octaves"], "Scale": hills["scale"],
             "Seed": hills["seed"]}]}]}
    bottom_sum = {"Type": "Sum", "Inputs": [
        cm(h, [(-400, -hm), (400, hm)]),
        cm(imp("SkyWynn-P3-Bot2D"), [(-1000, km), (1000, -km)]),
        {"Type": "Normalizer", "FromMin": -1, "FromMax": 1, "ToMin": -under["amp"], "ToMax": under["amp"], "Inputs": [
            {"Type": "SimplexNoise3D", "Lacunarity": 2, "Persistence": 0.5, "Octaves": under["octaves"], "ScaleXZ": under["scale_xz"],
             "ScaleY": under["scale_y"], "Seed": under["seed"]}]}]}
    return {"Type": "Exported", "ExportAs": "SkyWynn-P3-Land", "SingleInstance": True, "Inputs": [{"Type": "Min", "Inputs": [top_sum, bottom_sum]}]}


def p_biome_land(look):
    env, c1, c2, split, surface, spacing, paths = PROOF_LOOKS[look]
    tn = P["tint_noise"]
    if surface == "grass":
        solid = {"Type": "Queue", "Queue": [
            {"Type": "SpaceAndDepth", "LayerContext": "DEPTH_INTO_FLOOR", "MaxExpectedDepth": 4, "Layers": [
                {"Type": "ConstantThickness", "Thickness": 1, "Material": {"Type": "Constant", "Material": {"Solid": "Soil_Grass"}}},
                {"Type": "ConstantThickness", "Thickness": 3, "Material": {"Type": "Constant", "Material": {"Solid": "Soil_Dirt"}}}]},
            {"Type": "Constant", "Material": {"Solid": "Rock_Stone"}}]}
    else:
        solid = {"Type": "Queue", "Queue": [{"Type": "Constant", "Material": {"Solid": "Rock_Stone"}}]}
    out = {"Name": p_biome(look), "Terrain": {"Type": "DAOTerrain", "Density": imp("SkyWynn-P3-Land")},
           # the Empty queue is Empty ONLY (spec 6.3 hazard: an Empty queue fills every empty voxel of the column, the void under the
           # island included - lava belongs to 0.4, through a density-delimited provider or cave-floor prefabs, never a plain queue)
           "MaterialProvider": {"Type": "Solidity", "Solid": solid,
                                "Empty": {"Type": "Queue", "Queue": [{"Type": "Constant", "Material": {"Solid": "Empty"}}]}},
           "Props": [],
           "EnvironmentProvider": {"Type": "Constant", "Environment": env},
           "TintProvider": {"Type": "DensityDelimited", "Density": {"Type": "Normalizer", "FromMin": -1, "FromMax": 1, "ToMin": 0, "ToMax": 1,
                                                                   "Inputs": [{"Type": "SimplexNoise2D", "Lacunarity": 2, "Persistence": 0.5,
                                                                               "Octaves": tn["octaves"], "Scale": tn["scale"],
                                                                               "Seed": tn["seed"]}]},
                            "Delimiters": [{"Tint": {"Type": "Constant", "Color": c1}, "Range": {"MinInclusive": 0, "MaxExclusive": split}},
                                           {"Tint": {"Type": "Constant", "Color": c2}, "Range": {"MinInclusive": split, "MaxExclusive": 1.0001}}]}}
    if paths:
        out["Props"] = [{"Runtime": 0, "Positions": {"Type": "Mesh2D", "PointsY": 0, "PointGenerator": {
            "Type": "Mesh", "Jitter": 0.4, "ScaleX": spacing, "ScaleY": spacing, "ScaleZ": spacing, "Seed": P["tree_seed"]}},
            "Assignments": {"Type": "Constant", "Prop": {
                "Type": "Prefab", "WeightedPrefabPaths": [{"Path": p, "Weight": w} for p, w in paths], "LegacyPath": False, "LoadEntities": True,
                "Directionality": {"Type": "Random", "Seed": P["tree_seed"], "Pattern": {
                    "Type": "Floor", "Origin": {"Type": "BlockSet", "BlockSet": {"Inclusive": True, "Materials": [{"Solid": "Empty"}]}},
                    "Floor": {"Type": "BlockSet", "BlockSet": {"Inclusive": True, "Materials": [{"Solid": "Soil_Grass"}]}}}},
                # the islands rise to Base + 74 (0.1's scan stopped at + 40)
                "Scanner": {"Type": "ColumnLinear", "MaxY": 90, "MinY": -8, "RelativeToPosition": False, "BaseHeightName": "Base",
                            "TopDownOrder": True, "ResultCap": 1},
                "MoldingDirection": "None", "MoldingChildren": False}}}]
    return out


def p_biome_void():
    return {"Name": P["void_biome"], "Terrain": {"Type": "DAOTerrain", "Density": {"Type": "Constant", "Value": 0}},
            "MaterialProvider": {"Type": "Constant", "Material": {"Solid": "Empty"}}, "Props": [],
            "EnvironmentProvider": {"Type": "Constant", "Environment": P["void_env"]},
            "TintProvider": {"Type": "Constant", "Color": P["void_tint"]}}


def p_world_structure():
    biomes = [{"Biome": P["void_biome"], "Min": -1000000, "Max": 0}, {"Biome": p_biome("Arch"), "Min": 900, "Max": 1000},
              {"Biome": p_biome("Bridge"), "Min": 1900, "Max": 2000}]
    for i in sorted(P["islands"], key=lambda x: p_code(x[0])):
        biomes.append({"Biome": p_biome(i[8]), "Min": p_code(i[0]), "Max": p_code(i[0]) + 100})
    lx, ly, lz, _yaw = P["landing"]
    return {"Type": "NoiseRange", "Biomes": biomes, "DefaultBiome": P["void_biome"], "DefaultTransitionDistance": 16,
            "MaxBiomeEdgeDistance": 16, "Density": imp("SkyWynn-P3-Code2D"),
            "SpawnPositions": {"Type": "List", "Positions": [{"X": lx, "Y": ly, "Z": lz}]},
            "Framework": [{"Type": "DecimalConstants", "Entries": [{"Name": "Base", "Value": PB}, {"Name": "Water", "Value": PB},
                                                                   {"Name": "Bedrock", "Value": 0}]}]}


def p_instance_template():
    t = instance_template()
    lx, ly, lz, yaw = P["landing"]
    t["$Comment"] = ("SkyWynn archipelago PROOF world (SkyyWorldGen %s, Zone-Archipelago-Spec step 0.3): a throwaway admin test world from the "
                     "WorldStructure %s - the summit isle + 4 outer islands, 2 land necks, a rock arch and a bridge gap. Made once by /zone proof, "
                     "then kept until an admin deletes universe/worlds/%s (server stopped). Never use /instances spawn for it. Deaths keep items."
                     % (VERSION, P["structure"], P["world"]))
    t["DisplayName"] = "SkyWynn - archipelago proof"
    t["WorldGen"] = {"Type": "HytaleGenerator", "WorldStructure": P["structure"], "SeedOverride": P["seed"]}
    t["SpawnProvider"] = {"Id": "Global", "SpawnPoint": {"X": lx, "Y": ly, "Z": lz, "Pitch": 0.0, "Yaw": yaw, "Roll": 0.0}}
    return t


# the landing Y: 2 blocks above the highest ground the harness measured in the 3 x 3 around it (test_skyyworldgen_0.3.py section Q
# re-measures it; change the geometry = re-measure)
PROOF_LANDING_GROUND = 149
P["landing"] = (P["landing"][0], float(PROOF_LANDING_GROUND + 2), P["landing"][2], P["landing"][3])
_pl1A = P_ISL["1A"]
assert math.hypot(P["landing"][0] - _pl1A[2], P["landing"][2] - _pl1A[3]) < 0.8 * _pl1A[4], "the proof landing stands well inside 1A"

for _i in P["islands"]:
    ASSETS["Server/HytaleGenerator/Density/SkyWynn_P3_D_%s.json" % _i[0]] = jdump(p_density_dist(_i))
for _jg in P_JOINS:
    for _axis in ("S", "Q"):
        ASSETS["Server/HytaleGenerator/Density/SkyWynn_P3_J_%s%s_%s.json" % (_jg[0][1], _jg[0][2], _axis)] = jdump(p_density_join(_jg, _axis))
_pt, _pbt = p_fields()
ASSETS["Server/HytaleGenerator/Density/SkyWynn_P3_Top2D.json"] = jdump(_pt)
ASSETS["Server/HytaleGenerator/Density/SkyWynn_P3_Bot2D.json"] = jdump(_pbt)
ASSETS["Server/HytaleGenerator/Density/SkyWynn_P3_Code2D.json"] = jdump(p_code_field())
ASSETS["Server/HytaleGenerator/Density/SkyWynn_P3_Land.json"] = jdump(p_density_land())
ASSETS["Server/HytaleGenerator/WorldStructures/%s.json" % P["structure"]] = jdump(p_world_structure())
ASSETS["Server/HytaleGenerator/Biomes/SkyWynn/%s.json" % P["void_biome"]] = jdump(p_biome_void())
for _look in PROOF_LOOKS:
    ASSETS["Server/HytaleGenerator/Biomes/SkyWynn/%s.json" % p_biome(_look)] = jdump(p_biome_land(_look))
ASSETS["Server/Instances/%s/instance.bson" % P["template"]] = jdump(p_instance_template())
ASSETS["Server/Instances/%s/resources/InstanceData.json" % P["template"]] = '{\n  "HadPlayer": false\n}\n'
PROOF_EXPORTS = sorted(set(re.findall(r'"ExportAs": "([^"]+)"', "".join(t for p, t in ASSETS.items() if "SkyWynn_P3_" in p))))
assert len(PROOF_EXPORTS) == len(P["islands"]) + 2 * len(P_JOINS) + 4, PROOF_EXPORTS
_used_types = set(re.findall(r'"Type": "([^"]+)"', "".join(t for p, t in ASSETS.items() if "SkyWynn_P3_" in p or "SkyWynn_Proof" in p)))
PROOF_NODE_TYPES = sorted(_used_types)
# ---- the 0.3 asset ids against Assets.zip: no vanilla clash, every vanilla id referenced exists (the 0.1 checks below cover the rest)
with zipfile.ZipFile(os.path.join(B.HYTALE, "install", "release", "package", "game", "latest", "Assets.zip")) as _azp:
    _np = _azp.namelist()
    for _env in [v[0] for v in PROOF_LOOKS.values()] + [P["void_env"]]:
        assert any(n.startswith("Server/Environments/") and n.endswith("/%s.json" % _env) for n in _np), "environment " + _env
    for _v in PROOF_LOOKS.values():
        for _pp, _w in _v[6]:
            assert any(n.startswith("Server/Prefabs/%s/" % _pp) and n.endswith(".prefab.json") for n in _np), "prefab folder " + _pp
    assert not any(n.startswith("Server/Instances/%s/" % P["template"]) for n in _np), "vanilla instance name clash"
    _vexp = set()
    for _n in _np:
        if _n.startswith("Server/HytaleGenerator/") and _n.endswith(".json"):
            for _m in re.finditer(r'"ExportAs"\s*:\s*"([^"]+)"', _azp.read(_n).decode("utf-8", "replace")):
                _vexp.add(_m.group(1))
    assert not (set(PROOF_EXPORTS) & _vexp), "proof export names must be ours"
# every node type the proof uses is a registered HytaleGenerator asset type name (the release jar's AssetManager constant pool)
with zipfile.ZipFile(B.SERVER_JAR) as _sj:
    _amc = _sj.read("com/hypixel/hytale/builtin/hytalegenerator/assets/AssetManager.class")
for _ty in ("XValue", "ZValue", "Sqrt", "Multiplier", "Max"):
    assert (b"\x01" + len(_ty).to_bytes(2, "big") + _ty.encode()) in _amc, "node type %s is not registered by the V2 AssetManager" % _ty
print("0.3 proof assets: %d islands, %d joins (%s), %d exports, node types %s"
      % (len(P["islands"]), len(P_JOINS), ", ".join("%s %s-%s %.1f" % (j[0][0], j[0][1], j[0][2], j[5]) for j in P_JOINS), len(PROOF_EXPORTS),
         ", ".join(PROOF_NODE_TYPES)))
'''

# WgZones additions (after RING_TEXT): the proof world = zone index 1
ZONES_JAVA = r'''# ---- 0.3: the proof world is zone index 1 (WgZones.PROOF); its place names come from the PROOF table (plain distance, no warp)
F(zn, "public static final int PROOF = 1;")
F(zn, "public static final String[] SIZE_TEXTS = %s;" % jarr([SIZE_TEXT, "summit isle + %d outer islands, about %d blocks across"
                                                            % (len(P["islands"]) - 1, 2 * P["hull"])]))
PROOF_TEXT = ("Islands: " + ", ".join("%s %s (radius %d)" % (i[0], i[1], i[4]) for i in P["islands"]) + ". Joins: "
              + ", ".join("%s-%s %s (%d blocks)" % (j[0][1], j[0][2], {"neck": "land neck", "arch": "rock arch", "bridge": "bridge gap"}[j[0][0]],
                                                      round(j[5])) for j in P_JOINS) + ".")
F(zn, "public static final String PROOF_TEXT = %s;" % jstr(PROOF_TEXT))
F(zn, "public static final String[] P_IDS = %s;" % jarr([i[0] for i in P["islands"]]))
F(zn, "public static final String[] P_NAMES = %s;" % jarr([i[1] for i in P["islands"]]))
F(zn, "public static final double[] P_CX = new double[] { %s };" % ", ".join(repr(float(i[2])) for i in P["islands"]))
F(zn, "public static final double[] P_CZ = new double[] { %s };" % ", ".join(repr(float(i[3])) for i in P["islands"]))
F(zn, "public static final double[] P_R = new double[] { %s };" % ", ".join(repr(float(i[4])) for i in P["islands"]))
M(zn, r"""
public static String proofPlace(double x, double z) {
  int best = -1;
  double bu = 1.0E9;
  double bd = 0.0;
  for (int i = 0; i < P_IDS.length; i++) {
    double dx = x - P_CX[i];
    double dz = z - P_CZ[i];
    double d = Math.sqrt(dx * dx + dz * dz);
    if (d / P_R[i] < bu) { bu = d / P_R[i]; best = i; bd = d; }
  }
  if (best < 0) return "the void";
  String nm = P_NAMES[best] + " (" + P_IDS[best] + ")";
  if (bd <= P_R[best] - 40.0) return "on " + nm + ", " + Math.round(bd) + " blocks from its centre";
  if (bd <= P_R[best] + 40.0) return "at the coast of " + nm;
  return "over the void (or on a neck / arch / bridgehead) - the nearest island is " + nm;
}""")
'''

# harness section Q (inserted before section T) and QP (after section O)
HARNESS_Q = r'''
    # ---------------- Q. (0.3) the archipelago PROOF world: generated chunks from the jar's own assets, sampled column by column
    PB_ = 140
    PISL = {"1E": (0, 0, 600, 156, 214, 28, "Env_Zone1_Azure", {"#2f798a", "#2f868a"}),
            "1A": (0, 1060, 400, 146, 172, 58, "Env_Zone1_Plains", {"#709d3a", "#78ac39"}),
            "1B": (-1109, -404, 500, 150, 184, 30, "Env_Zone1_Forests", {"#9ec752", "#8ba441"}),
            "1C": (1109, -404, 520, 152, 196, 30, "Env_Zone1_Mountains", {"#82b742", "#598b27"}),
            "1D": (0, -1060, 420, 148, 180, 50, "Env_Zone1_Swamps", {"#4b6919", "#65750d"})}
    PTREES = {"1E": "Azure", "1B": "Birch"}
    PJOINS = [("neck", "1A"), ("arch", "1B"), ("neck", "1C"), ("bridge", "1D")]
    WARP_ = 40

    def p_top(i_, d_):
        cx_, cz_, R__, rim, peak, under = PISL[i_][:6]
        a_, b_ = rim - PB_, peak - PB_
        dd = b_ - a_
        return interp([(0, b_), (0.15 * R__, b_ - 0.06 * dd), (0.4 * R__, a_ + 0.55 * dd), (0.7 * R__, a_ + 0.22 * dd), (0.9 * R__, a_ + 0.06 * dd),
                       (R__, a_)], d_)

    def p_bot(i_, d_):
        cx_, cz_, R__, rim, peak, under = PISL[i_][:6]
        lo, hi = under - PB_, rim - PB_ - 10
        t_ = min(1.0, max(0.0, (d_ / R__ - 0.75) / 0.25))
        return lo + (hi - lo) * t_ * t_ * (3 - 2 * t_)

    def jgeo(a_):
        A_, E_ = PISL[a_], PISL["1E"]
        dx_, dz_ = E_[0] - A_[0], E_[1] - A_[1]
        L_ = math.hypot(dx_, dz_)
        ux_, uz_ = dx_ / L_, dz_ / L_
        return A_[0] + ux_ * A_[2], A_[1] + uz_ * A_[2], ux_, uz_, L_ - A_[2] - E_[2]

    def sq_to_xz(a_, s_, q_):
        ax_, az_, ux_, uz_, _sp = jgeo(a_)
        return ax_ + ux_ * s_ - uz_ * q_, az_ + uz_ * s_ + ux_ * q_
    PSTRUCT = "SkyWynn_P3_Archipelago"
    PSEED = JString("SkyWynn-P3").hashCode()
    check(am.getWorldStructureAsset(PSTRUCT) is not None, "Q. the generator's AssetManager holds the proof structure %s" % PSTRUCT)
    t0 = time.time()
    genP = ggm.invoke(hg, GP(PSTRUCT, PSEED, 11))
    check(str(genP.getClass().getSimpleName()) == "StagedChunkGenerator", "Q. getGenerator(%s) = StagedChunkGenerator (%.2fs)" % (PSTRUCT, time.time() - t0))
    island_ids = [int(btmap.getIndex(b_)) for b_ in ("Soil_Grass", "Soil_Dirt", "Rock_Stone")]
    scan2 = CPs.makeClass("wgharness.Scan2")
    scan2.addMethod(JClass("javassist.CtNewMethod").make(
        "public static int[] info(com.hypixel.hytale.server.core.universe.world.worldgen.GeneratedBlockChunk bc, int empty, int g, int d, int s) {\n"
        "  int[] out = new int[4096];\n"
        "  for (int lx = 0; lx < 32; lx++) for (int lz = 0; lz < 32; lz++) {\n"
        "    int top = -1; int bot = -1; int runs = 0; int other = 0; boolean prev = false;\n"
        "    for (int y = 0; y < 320; y++) {\n"
        "      int b = bc.getBlock(lx, y, lz);\n"
        "      boolean isl = b == g || b == d || b == s;\n"
        "      if (isl) { if (bot < 0) bot = y; top = y; if (!prev) runs++; }\n"
        "      else if (b != empty) other++;\n"
        "      prev = isl;\n"
        "    }\n"
        "    int k = (lx * 32 + lz) * 4; out[k] = top; out[k + 1] = bot; out[k + 2] = runs; out[k + 3] = other;\n"
        "  }\n  return out;\n}", scan2))
    scan2.writeFile(hcls)
    Scan2 = JClass("wgharness.Scan2")
    FSc = JClass("com.hypixel.hytale.server.core.universe.world.chunk.section.FluidSection")
    fst = FSc.getComponentType()
    pcache, ptimes, pfluid = {}, [], []

    def pchunk(cx_, cz_, g_=None, sd=PSEED):
        key = (cx_, cz_)
        if g_ is None and key in pcache:
            return pcache[key]
        t_ = time.time()
        ch_ = (g_ or genP).generate(ARGS(sd, CU.indexChunk(cx_, cz_), cx_, cz_, AT, PRIO), "High")
        bc_ = ch_.getBlockChunk()
        if g_ is not None:
            return bc_
        ptimes.append(time.time() - t_)
        nf = 0
        for h_ in ch_.getSections():
            if h_ is None:
                continue
            fs_ = h_.getComponent(fst)
            if fs_ is not None and not fs_.isEmpty():
                nf += 1
        pfluid.append(((cx_, cz_), nf))
        pcache[key] = (bc_, list(Scan2.info(bc_, empty_id, island_ids[0], island_ids[1], island_ids[2])))
        return pcache[key]

    def pcol(bx_, bz_):
        bx_, bz_ = int(math.floor(bx_)), int(math.floor(bz_))
        bc_, inf = pchunk(bx_ >> 5, bz_ >> 5)
        k_ = ((bx_ & 31) * 32 + (bz_ & 31)) * 4
        return dict(top=inf[k_], bot=inf[k_ + 1], runs=inf[k_ + 2], other=inf[k_ + 3], bc=bc_, lx=bx_ & 31, lz=bz_ & 31)
    # Q1. island interiors + coasts + the void around them: 8 radial lines per island
    bad_in, bad_h, bad_void, n_in, n_void, devs_t, devs_b = [], [], [], 0, 0, [], []
    near_join, multi = [], []
    for i_, (cx_, cz_, R__, rim, peak, under, env, tints) in PISL.items():
        for k8 in range(8):
            ang = k8 * math.pi / 4 + 0.3
            for fr in (0.0, 0.25, 0.5, 0.75, 0.85, None, "out1", "out2"):
                d_ = (R__ - 2 * WARP_ - 10) if fr is None else (R__ + 60 if fr == "out1" else (R__ + 140 if fr == "out2" else fr * R__))
                bx_, bz_ = cx_ + math.cos(ang) * d_, cz_ + math.sin(ang) * d_
                c_ = pcol(bx_, bz_)
                if fr in ("out1", "out2"):
                    # outside every island by 60+ blocks: void unless a join corridor / another island is there
                    inside_other = any(math.hypot(bx_ - v[0], bz_ - v[1]) < v[2] + 60 for kk, v in PISL.items() if kk != i_)
                    in_join = False
                    for kind, a_ in PJOINS:
                        ax_, az_, ux_, uz_, sp_ = jgeo(a_)
                        s_ = (bx_ - ax_) * ux_ + (bz_ - az_) * uz_
                        q_ = -(bx_ - ax_) * uz_ + (bz_ - az_) * ux_
                        if -80 <= s_ <= sp_ + 80 and abs(q_) <= 60:
                            in_join = True
                    if inside_other or in_join:
                        near_join.append((i_, round(bx_), round(bz_)))
                        continue
                    n_void += 1
                    if c_["runs"] != 0 or c_["other"] != 0:
                        bad_void.append((i_, round(bx_), round(bz_), c_["top"], c_["other"]))
                    continue
                n_in += 1
                if c_["runs"] < 1:
                    bad_in.append((i_, round(bx_), round(bz_), round(d_)))
                    continue
                span = [max(0.0, d_ + s2) for s2 in range(-WARP_ - 5, WARP_ + 6, 5)]
                tmin = PB_ + min(p_top(i_, x) for x in span) - 3.6 - 1.5
                tmax = PB_ + max(p_top(i_, x) for x in span) + 3.6 + 1.5
                bmin = PB_ + min(p_bot(i_, x) for x in span) - 4.8 - 1.5
                bmax = PB_ + max(p_bot(i_, x) for x in span) + 4.8 + 1.5
                devs_t.append(c_["top"] - (PB_ + p_top(i_, d_)))
                devs_b.append(c_["bot"] - (PB_ + p_bot(i_, d_)))
                if c_["runs"] > 1:
                    multi.append((i_, round(bx_), round(bz_)))
                if not (tmin <= c_["top"] <= tmax and bmin <= c_["bot"] <= bmax):
                    bad_h.append((i_, round(bx_), round(bz_), round(d_), c_["top"], c_["bot"], c_["runs"], round(tmin), round(tmax), round(bmin), round(bmax)))
    check(n_in >= 200 and not bad_in, "Q. land on every sampled column inside the 5 islands (to R - 90, %d columns, 8 radial lines each): %s" % (n_in, bad_in[:4]))
    check(not bad_h, "Q. every island column has its ground / underside inside the table's curves (+- the 40-block warp, hills, underside "
          "noise): %s" % bad_h[:4])
    check(n_void >= 40 and not bad_void, "Q. not one block (island or other) on any column 60 / 140 blocks off a coast, away from the joins (%d columns): %s"
          % (n_void, bad_void[:4]))
    # Q2. the summit: the highest ground of each island near its centre
    peaks = {}
    for i_, v in PISL.items():
        tops_ = [pcol(v[0] + dx_, v[1] + dz_)["top"] for dx_ in (-24, -8, 8, 24) for dz_ in (-24, -8, 8, 24)]
        peaks[i_] = max(tops_)
    check(all(abs(peaks[i_] - PISL[i_][4]) <= 7 for i_ in PISL), "Q. the peaks (highest ground within 24 of each centre) = the table's peak y +- 7: %s"
          % {i_: (peaks[i_], PISL[i_][4]) for i_ in PISL})
    # Q3. environments, tints, trees per island (centre columns + the radial samples)
    bad_env, bad_tint, tree_seen = [], [], collections.defaultdict(set)
    for i_, v in PISL.items():
        for dx_, dz_ in ((0, 0), (37, -21), (-60, 45), (0.3 * v[2], 0), (0, -0.4 * v[2])):
            c_ = pcol(v[0] + dx_, v[1] + dz_)
            if c_["top"] < 0:
                continue
            e_ = ename(c_["bc"].getEnvironment(c_["lx"], c_["top"], c_["lz"]))
            eb_ = ename(c_["bc"].getEnvironment(c_["lx"], c_["bot"], c_["lz"]))
            if e_ != v[6] or eb_ != v[6]:
                bad_env.append((i_, e_, eb_))
            tn_ = "#%06x" % (int(c_["bc"].getTint(c_["lx"], c_["lz"])) & 0xffffff)
            if tn_ not in v[7]:
                bad_tint.append((i_, tn_))
    check(not bad_env, "Q. each island's vanilla environment on its surface AND underside (1E Azure, 1A Plains, 1B Forests, 1C Mountains, 1D Swamps): %s" % bad_env[:4])
    check(not bad_tint, "Q. each island's grass tints (V1 tile palettes): %s" % bad_tint[:4])
    tree_cols = collections.Counter()
    for (cx_, cz_), (bc_, inf) in list(pcache.items()):
        for lx_ in range(0, 32, 2):
            for lz_ in range(0, 32, 2):
                k_ = (lx_ * 32 + lz_) * 4
                if inf[k_ + 3] > 0:
                    bx_, bz_ = cx_ * 32 + lx_, cz_ * 32 + lz_
                    best = min(PISL, key=lambda kk: math.hypot(bx_ - PISL[kk][0], bz_ - PISL[kk][1]) / PISL[kk][2])
                    tree_cols[best] += 1
                    for y_ in range(inf[k_] + 1, min(320, inf[k_] + 30)):
                        b_ = bname(bc_.getBlock(lx_, y_, lz_))
                        if b_ != "Empty":
                            tree_seen[best].add(b_.split("_")[1] if "_" in b_ else b_)
    t_ok = all(tree_cols[i_] > 0 and any(PTREES[i_] in x for x in tree_seen[i_]) for i_ in PTREES) and \
        all(tree_cols[i_] == 0 for i_ in PISL if i_ not in PTREES) and not any("Birch" in x for x in tree_seen["1E"]) and not any("Azure" in x for x in tree_seen["1B"])
    check(t_ok, "Q. trees: Azure on the summit isle, Birch on Birchwood, none on 1A / 1C / 1D (columns with blocks above the ground: %s, kinds %s)"
          % (dict(tree_cols), {k: sorted(v)[:4] for k, v in tree_seen.items()}))
    # Q4. the land necks (1A, 1C): solid end to end, walkable width, ground on the ramp between the two rim heights
    for kind, a_ in PJOINS:
        ax_, az_, ux_, uz_, sp_ = jgeo(a_)
        ha, hb = PISL[a_][3], PISL["1E"][3]
        if kind == "neck":
            bad_n, thick = [], []
            for s_ in range(-10, int(sp_) + 11, 2):
                hr = ha + (hb - ha) * min(1.0, max(0.0, s_ / sp_))
                for q_ in (-18, -9, 0, 9, 18):
                    c_ = pcol(*sq_to_xz(a_, s_, q_))
                    if c_["runs"] > 1:
                        multi.append((a_ + "-neck", s_, q_))
                    if c_["runs"] < 1 or not (hr - 3.6 - 3 <= c_["top"] <= hr + 3.6 + 2 + (60 if s_ < 0 or s_ > sp_ else 0)):
                        bad_n.append((s_, q_, c_["top"], c_["bot"], c_["runs"], round(hr)))
                    if q_ == 0:
                        thick.append(c_["top"] - c_["bot"] + 1)
            check(not bad_n and min(thick) >= 12, "Q. the %s-1E land neck (span %.1f): land on every column of 5 lines across it (q -18 .. 18), "
                  "ground on the rim-to-rim ramp, thickness %d-%d: %s" % (a_, sp_, min(thick), max(thick), bad_n[:4]))
        if kind == "arch":
            bad_a, bad_m, thick, mid_top, abots = [], [], [], None, []
            for s_ in range(2, int(sp_) - 1, 2):
                for q_ in (-6, 0, 6):
                    c_ = pcol(*sq_to_xz(a_, s_, q_))
                    mid_ = (ha + hb) / 2.0 + 6
                    nb = interp([(0, ha - 22), (sp_ / 2.0, mid_ - 12), (sp_, hb - 22)], s_)
                    if c_["runs"] > 1:
                        multi.append((a_ + "-arch", s_, q_))
                    if c_["runs"] < 1 or c_["bot"] < nb - 8:
                        bad_a.append((s_, q_, c_["top"], c_["bot"], c_["runs"], round(nb)))
                    abots.append(c_["bot"])
                    if q_ == 0:
                        thick.append(c_["top"] - c_["bot"] + 1)
                        if abs(s_ - sp_ / 2) <= 1:
                            mid_top = c_["top"]
                for q_ in (-150, -100, -60, -30, -16, 16, 30, 60, 100, 150):
                    c_ = pcol(*sq_to_xz(a_, s_, q_))
                    if c_["runs"] != 0 or (c_["other"] != 0 and 8 <= s_ <= sp_ - 8):
                        bad_m.append((s_, q_, c_["top"], c_["runs"], c_["other"]))
            check(not bad_a, "Q. the %s-1E rock arch (span %.1f): land on every column along it (q -6 / 0 / 6) and open void under it (its "
                  "lowest block at y %d or higher, never more than 8 under the table's arch underside, nothing below down to y 0), thickness %d-%d: %s"
                  % (a_, sp_, min(abots), min(thick), max(thick), bad_a[:4]))
            check(not bad_m, "Q. ... and open void on both sides of it (16 to 150 blocks off the axis, the whole span - the outline warp cannot "
                  "close the gap; tree leaves may hang 8 blocks out from a coast): %s" % bad_m[:4])
            check(mid_top is not None and mid_top >= (ha + hb) / 2.0 + 6 - 3.6 - 2, "Q. ... the arch bows up in the middle (top y %s, ends %d / %d)" % (mid_top, ha, hb))
            ACH = mid_top
        if kind == "bridge":
            bad_g, bad_e, edge = [], [], {}
            z_open = range(int(round(az_)), int(round(az_ + sp_)))
            for x_ in range(-7, 8):
                for z_ in z_open:
                    c_ = pcol(x_, z_)
                    if c_["runs"] != 0 or c_["other"] != 0:
                        bad_g.append((x_, z_, c_["top"]))
                for z_ in (int(round(az_)) - 1, int(round(az_ + sp_))):
                    c_ = pcol(x_, z_)
                    edge[(x_, z_)] = c_["top"]
                    if c_["runs"] < 1:
                        bad_e.append((x_, z_, c_["top"], c_["runs"]))
            for x_ in (-150, -100, -60, -20, 20, 60, 100, 150):
                for z_ in z_open:
                    c_ = pcol(x_, z_)
                    if c_["runs"] != 0 or (c_["other"] != 0 and abs(x_) <= 20):
                        bad_g.append((x_, z_, c_["top"], c_["other"]))
            # the bridge corridor: treeless (no canopy over the bridge spot), the Bridge look's environment on both lips
            bad_c = []
            for x_ in range(-7, 8):
                for z_ in list(range(int(round(az_)) - 21, int(round(az_)))) + list(range(int(round(az_ + sp_)), int(round(az_ + sp_)) + 21)):
                    c_ = pcol(x_, z_)
                    e_ = ename(c_["bc"].getEnvironment(c_["lx"], max(0, c_["top"]), c_["lz"]))
                    if c_["other"] != 0 or c_["runs"] < 1 or e_ != "Env_Zone1_Swamps":
                        bad_c.append((x_, z_, c_["top"], c_["other"], e_))
            check(not bad_c, "Q. ... the bridge corridor is land with no tree on 20 blocks of each lip (the Bridge look, Env_Zone1_Swamps): %s" % bad_c[:4])
            ztop = [edge[(x_, int(round(az_)) - 1)] for x_ in range(-7, 8)]
            etop = [edge[(x_, int(round(az_ + sp_)))] for x_ in range(-7, 8)]
            check(not bad_g and len(z_open) == 40, "Q. the %s-1E bridge gap: EXACTLY %d open blocks along z (z %d .. %d) on the whole 15-wide bridge line "
                  "and up to 150 blocks either side (no block at all): %s" % (a_, len(z_open), z_open[0], z_open[-1], bad_g[:4]))
            check(not bad_e and abs(min(ztop) - ha) <= 5 and abs(max(etop) - hb) <= 5,
                  "Q. ... solid bridgeheads on both lips (z %d: ground %d-%d, rim %d; z %d: ground %d-%d, rim %d) - a bridge piece sits on them: %s"
                  % (int(round(az_)) - 1, min(ztop), max(ztop), ha, int(round(az_ + sp_)), min(etop), max(etop), hb, bad_e[:3]))
    # Q5. no fluid anywhere (the spec 6.3 hazard: an Empty queue that fills the void) and no lava / water block
    lava_like = set()
    for (cx_, cz_), (bc_, inf) in list(pcache.items()):
        for lx_ in range(0, 32, 8):
            for lz_ in range(0, 32, 8):
                for y_ in range(0, 320, 4):
                    b_ = bname(bc_.getBlock(lx_, y_, lz_))
                    if "Lava" in b_ or "Water" in b_ or "Fluid" in b_:
                        lava_like.add(b_)
    fl_bad = [x for x in pfluid if x[1]]
    check(not fl_bad and not lava_like, "Q. no fluid in any generated section of %d chunks and no lava / water block: the void under every island is empty "
          "(the Empty queue is Empty only): %s %s" % (len(pfluid), fl_bad[:3], sorted(lava_like)[:3]))
    # Q6. far void: whole chunks between the zone and nowhere
    fv = [pcol(x_, z_) for x_, z_ in ((2200, 0), (-2400, 1800), (0, 2300), (900, 900), (-900, 1000), (1600, -1500))]
    check(all(c_["runs"] == 0 and c_["other"] == 0 for c_ in fv) and ename(fv[0]["bc"].getEnvironment(fv[0]["lx"], 150, fv[0]["lz"])) == "Env_Void",
          "Q. open void (Env_Void) between the islands and around the zone: %s" % [(c_["top"], c_["other"]) for c_ in fv])
    # Q7. the arch biome + the landing
    ax_, az_, ux_, uz_, sp_ = jgeo("1B")
    cm_ = pcol(*sq_to_xz("1B", sp_ / 2, 0))
    am_env = ename(cm_["bc"].getEnvironment(cm_["lx"], cm_["top"], cm_["lz"]))
    am_top = bname(cm_["bc"].getBlock(cm_["lx"], cm_["top"], cm_["lz"]))
    check(am_env == "Env_Zone1_Mountains" and am_top == "Rock_Stone", "Q. the arch's middle: stone on top, Env_Zone1_Mountains: %s / %s" % (am_top, am_env))
    PLAND = [float(x) for x in JClass(PKG + "WgCfg").PROOF_LANDING]
    lt = [pcol(PLAND[0] + dx_, PLAND[2] + dz_) for dx_ in (-1, 0, 1) for dz_ in (-1, 0, 1)]
    lt_tops = [c_["top"] for c_ in lt]
    lclear = [pcol(PLAND[0] + dx_, PLAND[2] + dz_)["other"] for dx_ in range(-3, 4) for dz_ in range(-3, 4)]
    check(max(lt_tops) >= 0 and PLAND[1] == max(lt_tops) + 2 and PLAND[1] - (min(lt_tops) + 1) <= 3 and not any(lclear) and PLAND[3] == 0.0,
          "Q. the proof landing %s: 1 block above the highest ground of its 3x3 (ground %d-%d), nothing above the ground within 3 blocks, yaw 0 (facing "
          "the neck and the summit isle)" % (PLAND, min(lt_tops), max(lt_tops)))
    check(ename(lt[4]["bc"].getEnvironment(lt[4]["lx"], lt[4]["top"], lt[4]["lz"])) == "Env_Zone1_Plains", "Q. ... on the Arrival Isle (Env_Zone1_Plains)")
    # Q8. the Java place names (plain distance) and the island table baked into WgZones = this harness's own table
    Znp = JClass(PKG + "WgZones")
    check([str(x) for x in Znp.P_IDS] == list(PISL) and [float(x) for x in Znp.P_CX] == [float(v[0]) for v in PISL.values()]
          and [float(x) for x in Znp.P_CZ] == [float(v[1]) for v in PISL.values()] and [float(x) for x in Znp.P_R] == [float(v[2]) for v in PISL.values()],
          "Q. WgZones' proof table = the harness's (ids, centres, radii)")
    pl_ = [str(Znp.ringAt(1, 0, 0)), str(Znp.ringAt(1, 5, 1440)), str(Znp.ringAt(1, -1109, -404)), str(Znp.ringAt(1, 0, -630)), str(Znp.ringAt(1, 2500, 2500))]
    check(pl_[0].startswith("on Azure Crown") and pl_[1].startswith("at the coast of Arrival Isle") and pl_[2].startswith("on Birchwood")
          and "Fenmoss" in pl_[3] and pl_[4].startswith("over the void"), "Q. /zone info place names: %s" % pl_)
    # Q9. determinism (a fresh generator, the same seed) + timing
    g2_ = ggm.invoke(hg, GP(PSTRUCT, PSEED, 12))
    b1_, b2_ = pchunk(0, -20)[0], pchunk(0, -20, g_=g2_)
    same_ = all(int(b1_.getBlock(x_, y_, z_)) == int(b2_.getBlock(x_, y_, z_)) for x_ in range(0, 32, 3) for z_ in range(0, 32, 3) for y_ in range(0, 320, 2))
    check(same_, "Q. the same seed gives identical proof chunks from a fresh generator")
    pt_ = sorted(ptimes[1:])
    NOTES.append("proof world generation (bare JVM, 2+2+2 threads): %d chunks, first %.2fs, then median %.0f ms, avg %.0f ms, max %.0f ms (0.1 island: see above)"
                 % (len(ptimes), ptimes[0], 1000 * pt_[len(pt_) // 2], 1000 * sum(pt_) / len(pt_), 1000 * pt_[-1]))
    NOTES.append("proof columns with more than one solid run (underside noise pockets / overhangs, no gap through the ground): %d of the sampled, e.g. %s"
                 % (len(multi), multi[:5]))
    NOTES.append("proof terrain vs the table: ground %+.1f .. %+.1f, underside %+.1f .. %+.1f blocks off the unwarped curves (warp + noise); peaks %s; arch top %s"
                 % (min(devs_t), max(devs_t), min(devs_b), max(devs_b), peaks, ACH))
    print("Q. proof archipelago: %d chunks, %d island columns, %d void columns; necks / arch / bridge gap checked; %d skipped near joins / other islands"
          % (len(pcache), n_in, n_void, len(near_join)))
'''
HARNESS_QP = r'''
    # ---------------- QP. (0.3) /zone proof executed: the proof world is created / reopened / entered through the same machinery
    PW, PT, PS_ = "skywynn_proof", "SkyWynn_Proof", "SkyWynn_P3_Archipelago"
    PLAND = tuple(float(x) for x in JClass(PKG + "WgCfg").PROOF_LANDING)

    def settle_p(timeout=20):
        t_end = time.time() + timeout
        while time.time() < t_end:
            w_ = uni.getWorld(PW)
            if not Open.CREATING.containsKey(PW) and Open.loadingFor(PW) is None and (w_ is None or not w_.isAlive()):
                break
            time.sleep(0.1)
        w_ = uni.getWorld(PW)
        if w_ is not None:
            wmap.remove(PW)
            try:
                wbyu.remove(w_.getWorldConfig().getUuid())
            except Exception:
                pass
        time.sleep(0.3)
        return w_

    def ours_p(cfg_):
        hp2 = cfg_.getWorldGenProvider()
        sp_ = cfg_.getSpawnProvider().getSpawnPoint(JObject(None, WLD), UUID.randomUUID())
        iw2 = IWC.get(cfg_)
        dco_ = cfg_.getDeathConfigOverride()
        p_ = sp_.getPosition()
        return (str(hp2.getClass().getSimpleName()) == "HandleProvider" and str(hp2.getWorldStructureName()) == PS_ and str(hp2.getSeedOverride()) == "SkyWynn-P3"
                and (p_.x(), p_.y(), p_.z()) == PLAND[:3] and abs(sp_.getRotation().yaw()) < 1e-6 and iw2 is not None and len(iw2.getRemovalConditions()) == 0
                and dco_ is not None and str(dco_.getItemsLossMode()) == "NONE" and str(cfg_.getGameMode()) == "Adventure")
    ptp = os.path.join(tdir, "proof.bson")
    with open(ptp, "wb") as f_:
        f_.write(z.read("Server/Instances/SkyWynn_Proof/instance.bson"))
    pcfg0 = WC.load(Paths.get(ptp)).join()
    check(ours_p(pcfg0) and str(pcfg0.getDisplayName()) == "SkyWynn - archipelago proof", "QP. the proof template decodes through WorldConfig.CODEC: HandleProvider %s / "
          "SkyWynn-P3, spawn = the fixed landing %s yaw 0, Adventure, no removal conditions, deaths keep items" % (PS_, PLAND[:3]))
    Chk.OK[1] = False
    check(Chk.structureProblem(1) is None and bool(Chk.OK[1]) and bool(Chk.templateOk(1)) and INS.doesInstanceAssetExist(PT),
          "QP. WgCheck: the real generator holds %s and the template %s resolves from the jar pack" % (PS_, PT))
    check([int(Zn.index(a)) for a in ("proof", " Proof ", "skywynn_proof", "archipelago proof", "1")] == [1, 1, 1, 1, 0]
          and int(Zn.worldIndex(PW)) == 1 and str(Zn.label(1)) == "The Archipelago proof world", "QP. /zone proof parsing + label")
    shutil.rmtree(os.path.join(worlds_dir, PW), ignore_errors=True)
    check(int(Open.decide(1, hub)) == 4, "QP. nothing on disk: decide(proof) = 4 (create)")
    sp0 = int(Open.SPAWNS)
    n_log0 = len(records())
    fut = Open.startCreate(1, hub, TRF(1.0, 100.0, 2.0), pr)
    try:
        made = fut.get(60, TU.SECONDS)
    except Exception as ex_:
        made = None
        print("   (the proof creation future failed: %s)" % str(ex_)[:300])
    t_end = time.time() + 10
    while Open.CREATING.containsKey(PW) and time.time() < t_end:
        time.sleep(0.05)
    check(made is not None and str(made.getName()) == PW and ours_p(made.getWorldConfig()) and int(Open.SPAWNS) == sp0 + 1
          and str(IWC.get(made.getWorldConfig()).getInstanceName()) == PT, "QP. the REAL spawnInstance + Universe.makeWorld built %s from %s (our config)" % (PW, PT))
    wtxt = open(os.path.join(wgdata, "worlds.properties"), encoding="latin-1").read()
    check("skywynn_proof.template=SkyWynn_Proof" in wtxt and "skywynn_proof.structure=SkyWynn_P3_Archipelago" in wtxt and "skywynn_proof.by=0.3" in wtxt
          and "skywynn_z1.template=SkyWynn_Zone1" in wtxt, "QP. WgDone recorded the proof world next to the Zone 1 island in worlds.properties")
    check(open(os.path.join(worlds_dir, PW, "instance.bson"), "rb").read() == z.read("Server/Instances/SkyWynn_Proof/instance.bson")
          and ours_p(WC.load(Paths.get(os.path.join(worlds_dir, PW, "config.json"))).join()), "QP. the folder holds the jar's template; config.json decodes back to the proof world")
    check(any("The Archipelago proof world: island world 'skywynn_proof' created" in m for lv, m in records()[n_log0:]), "QP. ... and the creation is logged")
    chat()
    settle_p()
    check(int(Open.decide(1, hub)) == 3, "QP. saved, not loaded: decide(proof) = 3 (load)")
    lo0 = int(Open.LOADS)
    f1 = Open.openSaved(1, pr)
    try:
        lw = f1.get(60, TU.SECONDS)
    except Exception:
        lw = None
    check(lw is not None and str(lw.getName()) == PW and ours_p(lw.getWorldConfig()) and int(Open.LOADS) == lo0 + 1, "QP. Universe.loadWorld reopened the SAME proof world")
    chat()
    settle_p()

    def run_go_p(world):
        chat()
        try:
            Cmds.goCmd(JObject(None, JClass("com.hypixel.hytale.component.Store")), JObject(None, JClass("com.hypixel.hytale.component.Ref")), pr, world, "proof")
            return None, chat()
        except Exception as ex_:
            return ex_, chat()
    ex_, cl = run_go_p(hub)
    check(ex_ is not None and any("Loading The Archipelago proof world" in t for t, _c in cl) and "teleportPlayerToLoadingInstance" in trace(ex_),
          "QP. /zone proof to the saved world: the 'Loading' line, then the engine teleport call: %s" % (cl,))
    settle_p()
    chat()
    pzone = world_stub(PW, WC.load(Paths.get(ptp)).join())
    wmap.put(PW, pzone)
    ex_, cl = run_go_p(hub)
    check(ex_ is not None and any("Teleporting to The Archipelago proof world" in t for t, _c in cl) and "teleportPlayerToLoadingInstance" in trace(ex_),
          "QP. /zone proof to the loaded world: the 'Teleporting' line + teleportPlayerToLoadingInstance: %s" % (cl,))
    check(int(Open.decide(1, pzone)) == 2 and int(Open.decide(1, hub)) == 1, "QP. decide(proof) = 2 on the proof world (back to its landing), 1 from elsewhere")
    Cfg.LANDING = "0.5 144 344.5 0"
    # the fixed landing: WgCfg.landing(1), WgApplyLanding keeps the proof world's spawn on it, /zone setlanding refuses there
    check(tuple(float(x) for x in Cfg.landing(1)) == PLAND and tuple(float(x) for x in Cfg.landing(0)) == (0.5, 144.0, 344.5, 0.0),
          "QP. WgCfg.landing: proof = the fixed %s, Zone 1 = its own setting" % (PLAND,))
    pc_ = pzone.getWorldConfig()
    pc_.consumeHasChanged()
    check(not bool(AL.applyTo(pzone)) and not bool(pc_.consumeHasChanged()), "QP. WgApplyLanding on the proof world: its spawn already is the landing -> no change")
    pc_.setSpawnProvider(JClass("com.hypixel.hytale.server.core.universe.world.spawn.GlobalSpawnProvider")(TRF(5.0, 99.0, 5.0)))
    pc_.consumeHasChanged()
    AL(pzone).run()
    p5_ = pc_.getSpawnProvider().getSpawnPoint(pzone, UUID.randomUUID()).getPosition()
    check(bool(pc_.consumeHasChanged()) and (p5_.x(), p5_.y(), p5_.z()) == PLAND[:3], "QP. ... a moved spawn point is put back on the fixed landing (the arrival task)")
    Cfg.LANDING = "10.5 150 300.5 90"
    check(not bool(AL.applyTo(pzone)), "QP. a changed Zone 1 landing never touches the proof world")
    Cfg.LANDING = "0.5 144 344.5 0"
    r_sh = str(HT.setHere(None, None, pr, pzone))
    check("fixed in its files" in r_sh, "QP. /zone setlanding on the proof world refuses: %s" % r_sh)
    il_p = [str(x) for x in Cmds.infoLines(None, None, pr, pzone)]
    check(len(il_p) == 2 and "The Archipelago proof world" in il_p[0] and "Landing point (fixed)" in il_p[1] and "1D Fenmoss" in il_p[1] and "rock arch" in il_p[1],
          "QP. /zone info on the proof world: %s" % il_p)
    lines = [str(x) for x in Cmds.listLines()]
    check(len(lines) == 4 and "/zone proof" in lines[2] and "Archipelago proof" in lines[2] and "summit isle + 4 outer islands" in lines[2], "QP. /zone list shows the proof world: %s" % lines[2:3])
    pz2 = player_stub("WgAdmin3", UUID.randomUUID())
    pbu.put(pz2.getUuid(), pz2)
    zu2 = UUID.randomUUID()
    setf(pz2, PRc, "worldUuid", zu2)
    wbyu.put(zu2, pzone)
    r_ = Hooks.landingHere(pz2.getUuid(), "WgAdmin3")
    check(str(r_[0]) == "ok" and drain(pzone) == 1, "QP. the landing action on the proof world queues WgHereTask on its thread (it stops quietly: a "
          "stand-in player has no entity; its setHere answer on the proof world is checked above)")
    chat()
    wbyu.remove(zu2)
    pbu.remove(pz2.getUuid())
    Cmds.goCmd(None, None, pr, hub, "2")
    cl = chat()
    check(len(cl) == 1 and "proof (the archipelago proof world)" in cl[0][0], "QP. an unknown zone names both: %s" % cl)
    wmap.remove(PW)
    shutil.rmtree(os.path.join(worlds_dir, PW), ignore_errors=True)
    # 0.3 fixer: the rollback rule (critic finding: a kept proof world must not survive a downgrade) is written into the build script header
    bhead = open(os.path.join(HERE, "build_skyyworldgen_%s.py" % VERSION), encoding="utf-8").read().split('"""', 2)[1]
    check("ROLLBACK RULE" in bhead and "delete universe/worlds/skywynn_proof" in bhead and "skywynn_proof.*" in bhead
          and "Player.initGameMode" in bhead, "QP. the build header carries the proof-world rollback rule + the game-mode note")
    print("QP. /zone proof: created by the real spawnInstance, reopened by loadWorld, entered through teleportPlayerToLoadingInstance; fixed landing kept")
'''

HARNESS_REPLACEMENTS = [
    ('"""SkyyWorldGen 0.1 harness - bare JVM, no game. Run: python SkyyWorldGen/test_skyyworldgen_0.1.py [--jar <jar>] [--dir <scratch>] [--keep]\n',
     '"""SkyyWorldGen 0.3 harness - GENERATED by tools/worldgen_0_3_patch.py from test_skyyworldgen_0.1.py (edit the patch). Bare JVM, no game.\n'
     'Run: python SkyyWorldGen/test_skyyworldgen_0.3.py [--jar <jar>] [--dir <scratch>] [--keep]\n'
     '0.3 = every 0.1 check below on the unchanged Zone 1 island, PLUS:\n'
     '  Q  the archipelago PROOF world generated from the jar\'s own assets (StagedChunkGenerator): 5 islands land on 8 radial lines each,\n'
     '     one solid run, ground / underside inside the table\'s curves, void 60 / 140 blocks off every coast, peaks, environments + tints per\n'
     '     island, Azure / Birch trees only where they belong, the two land necks solid end to end, the rock arch with open void under and\n'
     '     beside it, the bridge gap EXACTLY 40 blocks with bridgeheads on both lips, no fluid section / lava / water anywhere (spec 6.3\n'
     '     hazard), the fixed landing on the measured ground, the Java place names, determinism, generation time\n'
     '  QP /zone proof through the real spawnInstance / Universe.loadWorld / teleportPlayerToLoadingInstance; the fixed landing; setlanding\n'
     '     refusal; /zone list + info texts; the landing action\n', 1),
    ('VERSION = "0.1"\n', 'VERSION = "0.3"\n', 1),
    ('os.path.join(TOOLS, "dev", "scratch", "wg01", "harness")', 'os.path.join(TOOLS, "dev", "scratch", "wg03", "harness")', 1),
    ('                   "Server/Instances/SkyWynn_Zone1/resources/InstanceData.json"]\n',
     '                   "Server/Instances/SkyWynn_Zone1/resources/InstanceData.json"]\n'
     '# 0.3: the archipelago proof world\'s files (typed here independently of the build)\n'
     'PROOF_DENSITY = ["SkyWynn_P3_D_%s" % i for i in ("1E", "1A", "1B", "1C", "1D")]\n'
     'PROOF_DENSITY += ["SkyWynn_P3_J_%s1E_%s" % (a, x) for a in ("1A", "1B", "1C", "1D") for x in ("S", "Q")]\n'
     'PROOF_DENSITY += ["SkyWynn_P3_Top2D", "SkyWynn_P3_Bot2D", "SkyWynn_P3_Code2D", "SkyWynn_P3_Land"]\n'
     'PROOF_BIOMES = ["SkyWynn_P3_" + b for b in ("Void", "Azure", "Plains", "Birch", "Gorge", "Swamp", "Arch", "Bridge")]\n'
     'PROOF_ASSETS = ["Server/HytaleGenerator/Density/%s.json" % d for d in PROOF_DENSITY]\n'
     'PROOF_ASSETS += ["Server/HytaleGenerator/WorldStructures/SkyWynn_P3_Archipelago.json"]\n'
     'PROOF_ASSETS += ["Server/HytaleGenerator/Biomes/SkyWynn/%s.json" % b for b in PROOF_BIOMES]\n'
     'PROOF_ASSETS += ["Server/Instances/SkyWynn_Proof/instance.bson", "Server/Instances/SkyWynn_Proof/resources/InstanceData.json"]\n'
     'EXPECTED_ASSETS = EXPECTED_ASSETS + PROOF_ASSETS\n'
     'EXPECTED_KEYS = {"WS": sorted([STRUCT, "SkyWynn_P3_Archipelago"]), "D": sorted(["SkyWynn_Z1S_Dist", "SkyWynn_Z1S_Island"] + PROOF_DENSITY),\n'
     '                 "B": sorted(["SkyWynn_Void", "SkyWynn_Z1S_Core", "SkyWynn_Z1S_Forest", "SkyWynn_Z1S_Meadow"] + PROOF_BIOMES)}\n', 1),
    ('"M. exactly the 9 asset files: %s"', '"M. exactly the 9 Zone 1 + 28 proof asset files: %s"', 1),
    ('check(keys == {"WS": [STRUCT], "D": ["SkyWynn_Z1S_Dist", "SkyWynn_Z1S_Island"], "B": ["SkyWynn_Void", "SkyWynn_Z1S_Core", "SkyWynn_Z1S_Forest", "SkyWynn_Z1S_Meadow"]},\n'
     '          "D. 1 WorldStructure, 2 Density, 4 Biome assets: %s" % keys)',
     'check(keys == EXPECTED_KEYS, "D. 2 WorldStructures, 19 Density, 12 Biome assets (Zone 1 + the proof): %s" % keys)', 1),
    ('"skywynn_z1.by=0.1" in wtxt', '"skywynn_z1.by=0.3" in wtxt', 1),
    ('"SkyyWorldGen 0.1" in str(Store.createdText(WORLD))', '"SkyyWorldGen 0.3" in str(Store.createdText(WORLD))', 1),
    ('"Skyy_SkyyWorldGen-0.1"', '"Skyy_SkyyWorldGen-0.3"', 1),
    ('"[SkyyWorldGen] 0.1 ready" in m]', '"[SkyyWorldGen] 0.3 ready" in m]', 1),
    ('check(len(ready) == 2 and "TEST VERSION" in ready[0] and "template SkyWynn_Zone1 found" in ready[0],',
     'check(len(ready) == 2 and "TEST VERSION" in ready[0] and "template SkyWynn_Zone1 found" in ready[0] and "/zone proof" in ready[0]\n'
     '          and "template SkyWynn_Proof found" in ready[0],', 1),
    ('check(len(lines) == 3 and "TEST VERSION" in lines[0] and "/zone 1" in lines[1]', 'check(len(lines) == 4 and "TEST VERSION" in lines[0] and "/zone 1" in lines[1]', 1),
    ('for line in ("zone", "zone 1", "zone info", "zone leave", "zone setlanding", "zone reload"):',
     'for line in ("zone", "zone 1", "zone proof", "zone info", "zone leave", "zone setlanding", "zone reload"):', 1),
    ('for line in ("zone", "zone 1", "zone foo", "zone info", "zone leave", "zone setlanding", "zone reload"):',
     'for line in ("zone", "zone 1", "zone proof", "zone foo", "zone info", "zone leave", "zone setlanding", "zone reload"):', 1),
    ('    # ---------------- T. determinism\n', HARNESS_Q + '\n    # ---------------- T. determinism\n', 1),
    ('    print("O. /zone + /zone leave executed: refusals in chat, create / load / teleport reach the engine teleport calls, guards and world-thread tasks")\n',
     '    print("O. /zone + /zone leave executed: refusals in chat, create / load / teleport reach the engine teleport calls, guards and world-thread tasks")\n'
     + HARNESS_QP, 1),
]

with open(SRC, "rb") as f:
    raw = f.read()
NL = "\r\n" if b"\r\n" in raw else "\n"
s = raw.decode("utf-8").replace("\r\n", "\n")


def rep(old, new, count=1):
    global s
    n = s.count(old)
    if n != count:
        raise SystemExit("patch: expected %d match(es), found %d for:\n%s" % (count, n, old[:300]))
    s = s.replace(old, new)


# ---------------------------------------------------------------- header, version
rep('"""SkyyWorldGen 0.1 - build script (javassist via jpype).', HEADER + '\n--- 0.1 notes (unchanged, still true for Zone 1) ---\nSkyyWorldGen 0.1 - build script (javassist via jpype).')
rep('VERSION = "0.1"\n', 'VERSION = "0.3"\n')
# the Zone 1 template keeps its 0.1 bytes (its comment names the version that made the island, not the jar's)
rep('''                    "extra copies). Deaths here keep items (Death override)." % (VERSION, G["structure"]),''',
    '''                    "extra copies). Deaths here keep items (Death override)." % ("0.1", G["structure"]),''')
rep("Run:   python SkyyWorldGen/build_skyyworldgen_0.1.py      -> SkyyWorldGen/SkyyWorldGen-0.1.jar",
    "Run:   python SkyyWorldGen/build_skyyworldgen_0.3.py      -> SkyyWorldGen/SkyyWorldGen-0.3.jar (0.1 said 0.1)")
rep("Test:  python SkyyWorldGen/test_skyyworldgen_0.1.py       (bare JVM, -Xverify:all; scratch under tools/dev/scratch/wg01/)",
    "Test:  python SkyyWorldGen/test_skyyworldgen_0.3.py       (bare JVM, -Xverify:all; scratch under tools/dev/scratch/wg03/)")
# grass tints: the 0.1 seven + the proof looks (V1 tile palettes); the 0.1 assert keeps checking its own seven
rep('UI_DATA_COLORS = ["#2F798A", "#7f9b1f", "#639726", "#2F868A", "#69970f", "#3b8e32", "#5b9e28"]\n'
    'assert UI_DATA_COLORS == [r[4] for r in G["rings"]] + [r[5] for r in G["rings"]] + [G["void_tint"]]\n',
    'UI_DATA_COLORS = ["#2F798A", "#7f9b1f", "#639726", "#2F868A", "#69970f", "#3b8e32", "#5b9e28",\n'
    '                  "#709d3a", "#78ac39", "#9ec752", "#8ba441", "#82b742", "#598b27", "#4b6919", "#65750d"]\n'
    'assert UI_DATA_COLORS[:7] == [r[4] for r in G["rings"]] + [r[5] for r in G["rings"]] + [G["void_tint"]]\n')
# ---------------------------------------------------------------- the proof assets (after the 0.1 assets, before the ASCII check)
rep('ASSETS["Server/Instances/%s/resources/InstanceData.json" % G["template"]] = \'{\\n  "HadPlayer": false\\n}\\n\'\n',
    'ASSETS["Server/Instances/%s/resources/InstanceData.json" % G["template"]] = \'{\\n  "HadPlayer": false\\n}\\n\'\n' + PROOF_BLOCK)
# ---------------------------------------------------------------- WgZones: zone 1 + the proof world (index 1)
rep('F(zn, "public static final String[] IDS = %s;" % jarr([G["zone"]]))', 'F(zn, "public static final String[] IDS = %s;" % jarr([G["zone"], P["id"]]))')
rep('F(zn, "public static final String[] NAMES = %s;" % jarr([G["name"]]))', 'F(zn, "public static final String[] NAMES = %s;" % jarr([G["name"], P["name"]]))')
rep('F(zn, "public static final String[] WORLDS = %s;" % jarr([G["world"]]))', 'F(zn, "public static final String[] WORLDS = %s;" % jarr([G["world"], P["world"]]))')
rep('F(zn, "public static final String[] TEMPLATES = %s;" % jarr([G["template"]]))',
    'F(zn, "public static final String[] TEMPLATES = %s;" % jarr([G["template"], P["template"]]))')
rep('F(zn, "public static final String[] STRUCTURES = %s;" % jarr([G["structure"]]))',
    'F(zn, "public static final String[] STRUCTURES = %s;" % jarr([G["structure"], P["structure"]]))')
rep('F(zn, "public static final int[] RADIUS = %s;" % jints([R]))', 'F(zn, "public static final int[] RADIUS = %s;" % jints([R, P["hull"]]))')
rep('F(zn, "public static final String RING_TEXT = %s;" % jstr(RING_TEXT))\n',
    'F(zn, "public static final String RING_TEXT = %s;" % jstr(RING_TEXT))\n' + ZONES_JAVA)
rep('M(zn, "public static String label(int zi) { return \\"Zone \\" + IDS[zi] + \\" - \\" + NAMES[zi]; }")',
    'M(zn, "public static String label(int zi) { return zi == PROOF ? \\"The \\" + NAMES[zi] + \\" world\\" : \\"Zone \\" + IDS[zi] + \\" - \\" + NAMES[zi]; }")')
rep('public static String ringAt(int zi, double x, double z) {\n  double d = dist(x, z);',
    'public static String ringAt(int zi, double x, double z) {\n  if (zi == PROOF) return proofPlace(x, z);\n  double d = dist(x, z);')
# ---------------------------------------------------------------- WgCheck / WgCfg: one OK flag per zone; the proof landing is fixed
rep('F(chk, "public static final boolean[] OK = new boolean[%d];" % 1)', 'F(chk, "public static final boolean[] OK = new boolean[%d];" % 2)')
rep('F(cfg, "public static final double Y_ABOVE = %r;" % LANDING_Y_ABOVE)\n',
    'F(cfg, "public static final double Y_ABOVE = %r;" % LANDING_Y_ABOVE)\n'
    '# the proof world\'s landing is fixed in its files (on 1A, facing the neck and the summit isle) - not a setting\n'
    'F(cfg, "public static final double[] PROOF_LANDING = new double[] { %s };" % ", ".join(repr(float(v)) for v in P["landing"]))\n')
rep('public static double[] landing(int zi) {\n  double[] p = parseLanding(LANDING);',
    'public static double[] landing(int zi) {\n  if (zi == @PKG@.WgZones.PROOF) return new double[] { PROOF_LANDING[0], PROOF_LANDING[1], PROOF_LANDING[2], PROOF_LANDING[3] };\n'
    '  double[] p = parseLanding(LANDING);')
# ---------------------------------------------------------------- chat texts
rep('l.add("=  /zone " + @PKG@.WgZones.IDS[i] + "  " + @PKG@.WgZones.label(i) + " (" + @PKG@.WgZones.SIZE_TEXT + "): "',
    'l.add("=  /zone " + @PKG@.WgZones.IDS[i] + "  " + @PKG@.WgZones.label(i) + " (" + @PKG@.WgZones.SIZE_TEXTS[i] + "): "')
rep('''  return new String[] {
    "=[Zone] " + @PKG@.WgZones.label(zi) + " (world '" + world.getName() + "'): you are at " + where + " - " + ring + ".",''',
    '''  if (zi == @PKG@.WgZones.PROOF) return new String[] {
    "=[Zone] " + @PKG@.WgZones.label(zi) + " (world '" + world.getName() + "'): you are at " + where.replace(" blocks from the centre", " blocks from the summit isle's centre") + " - " + ring + ".",
    "=  " + @PKG@.WgZones.PROOF_TEXT + " Landing point (fixed): " + @PKG@.WgCfg.landingText(@PKG@.WgCfg.landing(zi)) + "."
  };
  return new String[] {
    "=[Zone] " + @PKG@.WgZones.label(zi) + " (world '" + world.getName() + "'): you are at " + where + " - " + ring + ".",''')
rep('''if (zi < 0) { tell(pr, "-[Zone] There is no zone '" + arg + "' yet - zones: 1 (the Zone 1 test island). /zone lists them."); return; }''',
    '''if (zi < 0) { tell(pr, "-[Zone] There is no zone '" + arg + "' yet - zones: 1 (the Zone 1 test island), proof (the archipelago proof world). /zone lists them."); return; }''')
rep('''  if (zi < 0) return "-[Zone] Stand on the zone island first (/zone 1), then set the landing point.";\n''',
    '''  if (zi < 0) return "-[Zone] Stand on the zone island first (/zone 1), then set the landing point.";\n'''
    '''  if (zi == @PKG@.WgZones.PROOF) return "-[Zone] The proof world's landing point is fixed in its files - /zone setlanding only moves the Zone 1 landing.";\n''')
rep('super("Go to a zone island: /zone 1 = the Zone 1 test island");', 'super("Go to a zone island: /zone 1 = the Zone 1 test island, /zone proof = the archipelago proof world");')
rep('this.zoneArg = withRequiredArg("zone", "Zone number (1)", @ATY@.STRING);', 'this.zoneArg = withRequiredArg("zone", "Zone: 1 or proof", @ATY@.STRING);')
rep('super("zone", "SkyWynn zone islands (test version, admins): /zone 1 goes to the Zone 1 island");',
    'super("zone", "SkyWynn zone islands (test version, admins): /zone 1 = the Zone 1 island, /zone proof = the archipelago proof");')
rep('NOTE="Chat (admins, test version): /zone, /zone 1, info, leave, setlanding, reload."',
    'NOTE="Chat (admins, test version): /zone, /zone 1, /zone proof, info, leave, setlanding, reload."')
rep('''  @PKG@.WgLog.info("@VERSION@ ready (@KITID@) - TEST VERSION: /zone, /zone 1, /zone info''',
    '''  String pmade = @PKG@.WgStore.createdText(@PKG@.WgZones.WORLDS[@PKG@.WgZones.PROOF]);
  @PKG@.WgLog.info("@VERSION@ ready (@KITID@) - TEST VERSION: /zone, /zone 1, /zone proof, /zone info''')
rep('''+ ", structure " + @PKG@.WgZones.STRUCTURES[0] + " (checked at the first /zone); settings''',
    '''+ ", structure " + @PKG@.WgZones.STRUCTURES[0] + " (checked at the first /zone); archipelago proof = world " + @PKG@.WgZones.WORLDS[@PKG@.WgZones.PROOF] + " (" + (pmade == null ? "not created yet" : "made " + pmade) + "), template " + @PKG@.WgZones.TEMPLATES[@PKG@.WgZones.PROOF] + " " + (@PKG@.WgCheck.templateOk(@PKG@.WgZones.PROOF) ? "found" : "NOT FOUND") + "; settings''')
rep('''man = B.manifest(MOD, VERSION, "SkyWynn zone islands (World Gen V2), TEST VERSION: the Zone 1 test island - a floating island (radius 384) with "''',
    '''man = B.manifest(MOD, VERSION, "SkyWynn zone islands (World Gen V2), TEST VERSION: /zone proof = the archipelago proof world (a summit isle + 4 "
                 "outer islands joined by land necks, a rock arch and a bridge gap, world skywynn_proof); /zone 1 = the Zone 1 test island - a floating island (radius 384) with "''')
assert "0.1" not in re.findall(r'VERSION = "([^"]+)"', s)
with open(DST, "wb") as f:
    f.write((s.replace("\n", NL)).encode("utf-8"))
print("wrote", DST)

HARNESS_S2 = r'''
    # ---------------- S2. (0.3) setup() twice on a scratch COPY of the LIVE data folder (Saves/<deploy_set.WORLD>/mods/Skyy_SkyyWorldGen, read only)
    import deploy_set as DSET
    live_src = os.path.join(B.USERDATA, "Saves", DSET.WORLD, "mods", "Skyy_SkyyWorldGen")
    if os.path.isdir(live_src):
        sroot = os.path.join(SCRATCH, "live", "mods")
        shutil.rmtree(os.path.dirname(sroot), ignore_errors=True)
        shutil.copytree(live_src, os.path.join(sroot, "Skyy_SkyyWorldGen"))
        before = dict((k, v[0]) for k, v in snap().items())
        n_log0 = len(records())
        start_plugin()
        l1 = snap()
        time.sleep(1.1)
        start_plugin()
        l2 = snap()
        ready = [m for lv, m in records()[n_log0:] if "[SkyyWorldGen] 0.3 ready" in m]
        bad_ = [m for lv, m in records()[n_log0:] if lv in ("WARNING", "SEVERE") and "SkyyWorldGen" in m]
        check(len(ready) == 2 and "Zone 1 = world skywynn_z1 (made 20" in ready[0] and "world skywynn_proof (not created yet)" in ready[0] and not bad_,
              "S2. setup() twice on a copy of the live data (%s): ready lines read the live record (Zone 1 made, proof not yet), no warning: %s %s"
              % (DSET.WORLD, (ready[:1] or [None])[0], bad_[:2]))
        check(dict((k, v[0]) for k, v in l2.items()) == before and l1 == l2, "S2. ... the live files are byte-identical after both starts, no file added "
              "or touched (no migration in 0.3): %s" % sorted(set(before) ^ set(l2)))
        # a server that already made the proof world: its record reads back in the ready line (the copy only - the live file is untouched)
        with open(os.path.join(sroot, "Skyy_SkyyWorldGen", "worlds.properties"), "a", encoding="latin-1", newline="\n") as f_:
            f_.write("skywynn_proof.by=0.3\nskywynn_proof.createdMillis=1791500000000\nskywynn_proof.structure=SkyWynn_P3_Archipelago\n"
                     "skywynn_proof.template=SkyWynn_Proof\n")
        n_log0 = len(records())
        start_plugin()
        ready = [m for lv, m in records()[n_log0:] if "[SkyyWorldGen] 0.3 ready" in m]
        check(len(ready) == 1 and "world skywynn_proof (made 2026-10-" in ready[0] and "template SkyWynn_Proof found" in ready[0],
              "S2. ... with a proof record added to the copy, the ready line says when the proof world was made: %s" % (ready[:1] or [None])[0])
    else:
        NOTES.append("S2 skipped: no live data folder at %s" % live_src)

'''
E_HEAD = "    # ---------------- E. the REAL command dispatch: CommandManager.handleCommand (parsing + the engine's permission check) -> the /zone tree\n"
HARNESS_REPLACEMENTS.append((E_HEAD, HARNESS_S2 + E_HEAD, 1))

# ================================================================= the harness: the 0.1 harness, re-pointed at 0.3, + sections Q / QP
with open(HSRC, "rb") as f:
    hraw = f.read()
HNL = "\r\n" if b"\r\n" in hraw else "\n"
s = hraw.decode("utf-8").replace("\r\n", "\n")
for old, new, cnt in HARNESS_REPLACEMENTS:
    rep(old, new, cnt)
with open(HDST, "wb") as f:
    f.write((s.replace("\n", HNL)).encode("utf-8"))
print("wrote", HDST)
